<?php

return [
    'halo_descr' => 'Halo és una franquícia de mitjans de fantasia de combat creada per Bungie. Basada en la trilogia original de videojocs de tir en primera persona. La trama gira al voltant dels esdeveniments que tenen lloc a la vida del Mestre en Cap, un d\'un grup de super-soldats amb el nom en clau Spartans, i la seva companya, la intel·ligència artificial Cortana. L\'èxit dels jocs ha portat a l\'expansió de la franquícia en altres mitjans: l\'univers Halo s\'estén actualment a molts llibres, novel·les gràfiques, còmics, curtmetratges, animacions i llargmetratges.',
    'halo_short_descr' => 'Toca el cursor de l\'artefacte, potser ets l\'escollit',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'Les nines LOL Surprise van enamorar els xiquets i van guanyar els seus cors des dels primers minuts. I això no és sorprenent, perquè aquest èxit es basa en un misteri, l\'expectació d\'un miracle, una agradable sorpresa, que fa les delícies no només dels xiquets, sinó també dels seus pares. El secret del regal es revela al xiquet només després del desempaquetatge final. En qualsevol cas, les nines LOL són un disseny atractiu, intriga, un gran nombre d\'accessoris sorprenents i realistes i petites coses agradables, així com la més alta qualitat de producció i detall de la joguina.',
    'lol_surprise_short_descr' => 'Criatures simpàtiques per a coneixedors de sorpreses maques',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'La sèrie gira al voltant d\'un concurs on 456 jugadors, tots endeutats financerament, arrisquen les seves vides per jugar a una sèrie de jocs infantils mortals per la possibilitat de guanyar un premi de mil milions. A dins, espera un premi temptador amb apostes mortalment altes. El títol de la sèrie s\'inspira en un joc infantil coreà del mateix nom. Hwang va concebre la idea basant-se en les seves pròpies dificultats econòmiques al principi de la seva vida, així com en la disparitat de classes a Corea del Sud i el capitalisme.',
    'squid_game_short_descr' => 'Escull la cara del jugador correcte quan ho apostes tot',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter és el protagonista d\'una sèrie de novel·les de l\'escriptora anglesa JK Rowling. L\'onzè aniversari, l\'Harry s\'assabenta que és un mag i està destinat a un lloc a l\'Escola Hogwarts de Màgia, on practicarà màgia sota la direcció del director Albus Dumbledore i altres professors de l\'escola. L\'Harry també descobreix que ja és conegut a tota la comunitat màgica de la novel·la, i que el seu destí està connectat amb el destí de Voldemort, un mag fosc perillós.',
    'harry_potter_short_descr' => 'Què faràs amb una vareta màgica de la col·lecció de cursos de Harry Potter',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics és una editorial de còmics coneguda per crear superherois notables com Spider-Man, Iron Man, Captain America, Hulk, Thor, els Avengers, els Guardians of the Galaxy, els X-Men, els Fantastic Four i Deadpool. Els vilans més coneguts de Marvel inclouen el Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom i Magneto. Marvel Comics i DC Comics han col·laborat en diversos projectes de crossover junts i també van cofundar l\'empremta intencionadament de curta durada Amalgam Comics.',
    'marvel_comics_short_descr' => 'El superheroi viu en cadascun de nosaltres: tria el teu',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Ben tornat al Regne de les Galetes a Cookie Run: Kingdom de Devsisters, l\'adorable RPG d\'estratègia ambientat a l\'univers de Cookie Run. Ara que GingerBrave ha escapat del forn de la bruixa malvada, és hora que construeixi un equip de Galetes i s\'embarqui en una missió per reconstruir el Regne de les Galetes caigut. Descobriu la veritat darrere de la caiguda del Regne i formeu un equip de les Galetes més poderoses del Regne per derrotar les forces fosques que volen impedir que GingerBrave compleixi el seu destí.',
    'cookie_run_kingdom_short_descr' => 'Petits guerrers acabats de sortir del forn',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact és un joc d\'aventures de món obert. Això significa que un paisatge nou i deliciós us espera a l\'altra banda del riu o de la muntanya, només heu d\'utilitzar la vostra energia amb prudència. Si us trobeu amb una fada errant o un mecanisme estrany, atreviu-vos i intenteu desentranyar el seu misteri. Però allò que prometen, problemes o una agradable sorpresa, només ho podreu descobrir vosaltres! Al vast continent de Teyvat, visitareu set regnes, trobareu companys amb diverses habilitats i lluitareu contra enemics poderosos a la recerca d\'un ésser estimat desaparegut.',
    'genshin_impact_short_descr' => 'Converteix-te en el Mestre Elemental dels Set Regnes',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Quan una antiga profecia es fa realitat i el regne s\'enfonsa a l\'abraçada de l\'hivern, tres herois intrèpids, la princesa Anna, el valent Kristoff i el seu fidel ren Sven, van a les muntanyes per trobar la germana de l\'Anna, Elsa, que pot treure l\'encantador encanteri del país. Pel camí, els esperen moltes sorpreses i aventures emocionants. Coneixeran trolls místics, un encantador ninot de neu anomenat Olaf, pics de muntanya més empinats que l\'Everest i molta màgia. Els herois han de resistir als poderosos elements per tal de salvar el regne i els que estimen.',
    'frozen_short_descr' => 'Trencar el gel és fàcil amb la col·lecció de cursors de Frozen',
    'frozen' => 'Frozen',
    'stranger_things_descr' => 'Han passat poc més de sis mesos des del final de la tercera temporada. La Joyce, el Will, l\'Eleven i en Jonathan s\'han mudat a Califòrnia, on la noia pateix assetjament a l\'escola. La resta comencen a lluitar contra un nou monstre d\'un món paral·lel que ha aparegut a Hawkins. Va ser anomenat Vecna ​​pel personatge del joc de taula Dungeons & Dragons. Afecta els adolescents psicològicament, després puja mentalment al cap i mata. En paral·lel, la Joyce i en Murray s\'assabenten que en Jim Gopper és viu i van a buscar-lo a una presó soviètica a Kamchatka. I l\'Eleven haurà de tornar i augmentar els seus poders, però també aprendre el seu important paper en la creació del mateix monstre a Gokins.

Els guionistes no van canviar les tàctiques de la trama que els van agradar les últimes temporades. En la quarta temporada, van dividir el gran grup de personatges principals en grups, van idear tasques difícils per a ells i al final van construir les seves històries juntes en un final sorprenent. Us oferim que entengueu totes aquestes aventures en detall amb l\'ajuda de la col·lecció de cursors de Stranger Things.',
    'stranger_things_short_descr' => 'Què passarà després? - Cursors de Stranger Things 4',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars és una modalitat original que va aparèixer per primera vegada a Minecraft. La tasca dels jugadors era que l\'usuari protegís la seva base i el seu llit.

Roblox porta jocs més emocionants cada dia i BedWars no n\'és una excepció. I la cosa és que, si t\'encanten les bed wars i defensar-te a la teva habitació, aquest és el títol per a tu perquè et porta a la infància, encara que sigui digitalment aquesta vegada.

Tots el que necessites fer és defensar el teu llit dels atacants amb el teu company. Entreus a un vestíbul, tries amb qui jugar i voilà, només és una qüestió de protecció.

Per descomptat, quan es tracta de defensa, tindràs alguns problemes i hi ha certs recursos, articles i ítems que t\'ajudaran a guanyar. Per exemple, aspectes exclusius que trobaràs a la col·lecció de cursors de Bed Wars.',
    'roblox_bed_wars_short_descr' => 'Protegeu el vostre llit amb els cursors de Roblox Bed Wars',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'El dia del naixement de Naruto Uzumaki, un dimoni llegendari, la Guineu de Nou Cues, va atacar un poble anomenat Konoha. El Quart Hokage, a costa de la seva vida, va salvar el poble segellant el dimoni en el nounat Naruto, condemnant-lo sense saber-ho a una vida d\'odi dels seus veïns.
Malgrat la seva manca de talent en moltes àrees del ninjutsu, la inquietud i la vanitat, Naruto somia a convertir-se en Hokage, el ninja més fort del poble. Desitjant el reconeixement que no va obtenir, treballa dur i s\'entrena juntament amb els seus companys d\'equip Sasuke Uchiha i Sakura Haruno, així com el seu mentor Kakashi Hatake. Ell i els seus companys hauran de passar per moltes coses en el camí cap als seus somnis estimats: batalles, amor, amistat, traïció, set de poder. Una col·lecció de cursos d\'anime de Naruto us ajudarà a navegar pel vostre propi camí!',
    'naruto_anime_short_descr' => 'Camina pel teu camí ninja amb els cursors de l\'anime Naruto',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'L\'acció té lloc durant l\'era Taisho. Des de temps antics, hi ha hagut rumors que dimonis humanoides viuen al bosc, que s\'alimenten de persones i caminen a la nit, buscant una nova víctima. Però... és només una llegenda, oi?..

Tanjiro Kamado és el fill gran de la família, que va perdre el seu pare i va tenir cura de la seva família. Un dia va a una ciutat propera a vendre carbó. Tornant al matí, el noi descobreix una imatge terrible davant seu: tots els familiars van ser brutalment assassinats, i l\'única supervivent és Nezuko, una germana petita convertida en dimoni, però que encara no ha perdut tota la seva humanitat.

Des d\'aquest moment, Tanjiro i Nezuko comencen un llarg i perillós viatge, en el qual el noi pretén trobar l\'assassí i descobrir una manera de curar la seva germana. Però són els nens capaços de superar totes les dificultats i tornar a casa? Ja saps la resposta, i si no - millor posa els cursors Demon Slayer, amb personatges d\'un dels mangas més populars.',
    'demon_slayer_anime_short_descr' => 'Cursors de Demon Slayer - per a veritables caçadors nocturns',
    'demon_slayer_anime' => 'Anime de Demon Slayer',
    'bts_descr' => 'BTS és un grup de nois de set membres sota BigHit Music. Van debutar el 13 de juny de 2013 amb el senzill "No More Dream". Al Japó, van debutar el 24 de desembre de 2014 amb l\'àlbum d\'estudi Wake Up.

El nom del grup prové de l\'expressió coreana Bangtan Sonyeondan, que significa "escoltes de nois a prova de bales". Segons J Hope, el nom significa el desig de la banda de bloquejar els estereotips, les crítiques i les expectatives que s\'apliquen als adolescents com bales.

La col·lecció de cursors dedicats al grup inclou tots els membres del grup, aquí el cursor Kim Nam Joon (també conegut com RM), el cursor Kim Seok Jin (Jin), el cursor Min Yoongi (Suga), el cursor Jung Ho Suk (J-Hope), el cursor Park Ji Min (Jimin), el cursor Kim Tae Hyun (V) i el cursor Jeon Jungkook (Jungkook).',
    'bts_short_descr' => 'Coneix els teus ídols amb els cursors de BTS',
    'bts' => 'BTS',
    'miraculous_descr' => 'Miraculous: Les aventures de Ladybug i Cat Noir, més conegut com a Miraculous Ladybug i Cat Noir, són les aventures de superherois de la sèrie de dibuixos animats sobre dos companys de classe que, sota màscares, interpreten el paper de defensors de París d\'un vilà que a cada episodi pensa en una nova manera de fer mal a la ciutat. Miraculous està fet a França amb CGI i animació. Miraculous no és només una sèrie animada, sinó també una col·lecció de còmics publicats a tot el món. La sèrie és molt estimada pel públic jove.

L\'acció té lloc a París, on la Marinette i l\'Adrian són estudiants de secundària en una escola moderna. Se\'ls va donar el paper de convertir-se en l\'escollit en la lluita contra el mal, salvant la seva ciutat natal. El seu objectiu és protegir la gent dels Akumas. Aquestes petites criatures en forma de papallones poden habitar una persona i convertir-la en un vilà.

La Marinette es pot transformar en una marieta, i l\'Adrian, en un Cat Noir, però, sorprenentment, treballant en parella, no es reconeixen sota les màscares de superherois.

Ajuda Cat Noir i Ladybug a salvar París amb els nostres cursors amb els teus personatges preferits. Quin personatge triaràs per al cursor? Serà un cursor de Miraculous Ladybug, o potser l\'adorable marieta petita de Tikki o el cursor de Cat Noir? O potser una Queen Bee amb els cursors de Rena Rouge? L\'elecció és teva!',
    'miraculous_short_descr' => 'Uneix-te a les files de superherois amb la col·lecció de cursors de Lady Bug i Cat Noir',
    'miraculous' => 'Miraculous: Les aventures de Ladybug i Cat Noir',
    'talking_tom_descr' => 'La sèrie segueix la vida quotidiana de Talking Tom i els seus amics. En Tom i el seu soci comercial nerd Ben estan constantment desenvolupant aplicacions mòbils i altres invents per aconseguir fama i fortuna i intentar mostrar-se al món, però això sempre surt malament. La nòvia de Tom, Angela, intenta ser cantant, passi el que passi per aconseguir-ho. El veí de Tom, Ginger, molt sovint deixa caure aquí per fer bromes amb malifetes a la màniga. El seu millor amic i company d\'habitació, Hank, és es quedat a casa, mira MOLTA TV. I l\'antiga estrella del pop dissident Becca Sparkles s\'ha convertit en la nova companya d\'habitació d\'Angela i sembla haver-se enamorat d\'Hank. No obstant això, per molt malament que vagin les coses de totes les formes i mides, ja sigui l\'odiós CEO, el nou veí misteriós d\'en Tom, o només un accident a la nova creació d\'en Ben, la colla es divertirà passi el que passi, i sempre recordaran una cosa que els manté units: l\'amistat mai s\'acaba, igual que el nostre amor pels personatges de la sèrie no s\'acaba, així que ara pots posar-te el cursor de Talking Tom o el cursor de Ben, o potser el cursor d\'Angela, el cursor d\'Oliver!',
    'talking_tom_short_descr' => 'Parlem del teu personatge favorit de la col·lecció de cursos Talking Tom',
    'talking_tom' => 'Talking Tom and Friends',
    'lego_descr' => 'L\'empresa LEGO Group va ser fundada l\'any 1932 i llavors només constava de 7 persones. L\'objectiu de l\'equip de Lego era crear joguines que desenvolupessin la creativitat, la imaginació i l\'enginy dels nens. Un fet sorprenent, des de la seva creació el 1949, els elements LEGO en totes les seves variants han continuat sent compatibles entre ells. Tots els articles creats posteriorment segueixen sent compatibles amb els articles que s\'estan llançant avui, malgrat els canvis en el disseny i la forma al llarg dels anys.

Un maó LEGO és una base, que és un bloc de plàstic buit que connecta amb altres maons similars. Però els conjunts de Lego també contenen altres parts, rodes, figures, plataformes i fins i tot circuits electrònics amb sensors i motors elèctrics. Podeu col·leccionar models de cotxes, avions, trens, vaixells, edificis, robots. LEGO s\'adhereix a la idea de la modularitat, que mostra clarament als nens com resoldre certs problemes, desenvolupar la imaginació, les habilitats motores fines de les mans i les habilitats de muntatge. Els maons LEGO estan fets amb una precisió increïble i encaixen a la perfecció per una precisió impressionant de 10 micres.

Recentment, s\'han creat moltes històries populars de Lego en animació 3D, on els personatges dels conjunts cobren vida i es converteixen en participants d\'increïbles aventures. Si voleu un cursor genial, trobareu molts personatges de les sèries de televisió i pel·lícules d\'animació Lego a la nostra col·lecció de Cursors Lego. Cursor Lego Ninjago, Cursor Lego Batman, Cursor Lego Ninjago, Cursor Lego Wyldstyle i molts més.',
    'lego_short_descr' => 'Construeix el teu navegador de somni amb la col·lecció de cursors de Lego',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Després d\'un finançament reeixit a Kickstarter, el 2017, Team Cherry va llançar el joc multiplataforma per a PC Hollow Knight. Aquesta és la història d\'un cavaller sense nom i els seus descobriments al regne d\'insectes Hallownest. El joc va ser justificadament reconegut com un dels millors del gènere metroidvania.

La jugabilitat de Hollow Knight es basa en l\'exploració del món del joc. Superar obstacles, resoldre trencaclosques i trobar secrets, així com lluitar contra enemics. El jugador té un conjunt únic de millores i trucs per explorar el món i lluitar en batalles. Movent-se de zona a zona, el jugador derrota caps i obté les millores necessàries per avançar més. Com a resultat, els jugadors han de visitar les àrees ja passades per trobar secrets i passar per la història. I també és emocionant perquè les zones canvien cada vegada, aportant noves sorpreses i experiències. El joc es pot jugar de diferents maneres, perquè hi ha diversos camins diferents entre les zones. Passant per la història, obriu el mapa de la zona, però primer heu d\'aconseguir el mapa.

L\'arma principal de l\'heroi és un clau, que s\'assembla una mica a una espasa, les armes es poden millorar amb un ferrer, així com aprendre diferents habilitats en l\'ús d\'armes, cosa que amplia la varietat d\'atacs. En atacar els enemics, acumuleu un recurs especial, que més tard es pot utilitzar per a millores o curació.

Divertiu-vos jugant a Hollow Knight i no oblideu els nostres cursors de Hollow Knight amb el vostre personatge preferit. La nostra col·lecció inclou el Cursor de Mister Mushroom, el Cursor de Quirrel, el Cursor de l\'Agulla de la Vespa, el Cursor de Clau Antiga, el Cursor de Myla i altres.',
    'hollow-knight_short_descr' => 'Intenta no perdre\'t al regne dels insectes utilitzant la col·lecció de cursors de Hollow Knight',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman és el personatge principal de la sèrie. Stikmin, abans sense nom, va començar com un lladre menor, amb el desig de guanyar diners fàcils ràpidament. No obstant això, després d\'escapar de la presó de West Mesa, molts canvis tenen lloc a la seva vida, i es converteix en un criminal famós després de robar el Diamant Tunisià. Henry té una elecció: convertir-se en un agent governamental d\'èxit, caçador de recompenses, líder d\'una organització criminal, cyborg, o continuar el camí criminal sol. El joc fa les delícies dels aficionats al gènere amb moltes aventures i misteris, i trobareu la nostra nova col·lecció de cursors de Henry Stickman amb els seus personatges divertits, incloent el cursor de Henry Stickmin, el cursor de Charles Calvin, el cursor de Reginald Copperbottom, el cursor de Right Hand, el cursor d\'Ellie Rose i altres!',
    'henry-stickmin_short_descr' => 'Planifica la teva fugida del avorriment amb la col·lecció de cursors de Henry Stickmin',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'El popular joc en línia Adopt Me es va llançar el 2017 i es va convertir en el més popular a la plataforma de jocs Roblox. L\'essència del joc és molt senzilla: aconseguir ous amb mascotes i tenir-ne cura.

Les mascotes virtuals es divideixen en 5 classes, algunes d\'elles són molt rares i cares, mentre que d\'altres són molt fàcils d\'aconseguir. Aquests són grups poc comuns, com el Gos Blau, el cursor Comú, el Rare, per exemple, el cursor de ratolí Adopt Me Monkey, així com els ultra-raros, com el cursor Koala, i el Legendari, el cursor Dragó i l\'unicorn Accept Me. Si el jugador té quatre mascotes adultes del mateix tipus, es poden combinar en una mascota neon, com el cursor del joc Neon Horse o l\'Estrella de mar Neon Adopt Me. Combinant quatre mascotes normals, podeu fer una mascota neon que realment brilla, i de les mascotes neon podeu crear una mascota mega-neon.

Les compres al joc Adopt Me! es fan amb la moneda virtual Roblox, els anomenats Robux, i el joc també té la seva pròpia moneda, Bucks. Tenint cura de la teva mascota, a més de l\'entreteniment, pots guanyar bucks, només alimentant-lo, ficant-lo al llit o llegint-li un conte de fades, en general, moltes coses interessants.

Ara els aficionats al joc Roblox "Adopt Me!" poden decorar el seu cursor de joc amb la mascota preferida!',
    'adopt-me_short_descr' => 'Diverteix-te amb simpàtiques mascotes a la nostra col·lecció de cursos del joc Adopt Me!',
    'adopt-me' => 'Adopt me!',
    'among-us_descr' => 'L\'Among Us es basa en el famós joc de rol "Màfia". Es va planejar que el joc fos exclusiu per a dispositius mòbils, perquè només tenia un mapa. El joc es va fer popular ràpidament. Més tard, l\'equip de desenvolupament va afegir un mode multijugador i es van llançar dos mapes addicionals el 2019.
Among Us és un joc de tercera persona de dalt a baix que permet al jugador moure\'s en totes les direccions. De quatre a deu jugadors poden jugar en una ronda. Al començament del joc, a tothom se li assigna secretament el paper de traïdor o membre de la tripulació. L\'Impostor (en traducció russa "Traïdor") pot amagar-se a la comporta de ventilació, sabotejar i matar membres de la tripulació. El seu objectiu és destruir tots els membres de la tripulació o destruir la nau mitjançant sabotatge. L\'objectiu de la tripulació de la nau és resoldre diversos trencaclosques preparats per a ells al començament del joc. Si cadascun dels membres de la tripulació completa totes les tasques, els traïdors perdran. A més, la tripulació de la nau pot aconseguir la victòria eliminant els traïdors durant la votació.
Els traïdors poden sabotejar de tant en tant i, si les avaries no es solucionen en 30 segons, la tripulació perdrà. Abans de començar el joc, podeu triar el color del personatge amb el qual esteu jugant, blau, vermell, groc, gris, el que sigui! I no oblideu configurar el cursor adequat de la nova col·lecció Among Us!',
    'among-us_short_descr' => 'No et deixis enganyar en aquest complicat joc espacial amb els cursors d\'Among Us',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'La creadora de "Steven Universe" va ser Rebecca Sugar. És coneguda per la seva obra anterior anomenada Adventure Time. El primer episodi de Steven Universe va ser llançat a la plataforma de vídeo de YouTube a la primavera de 2013. Però a la tardor, el canal americà Cartoon Network va començar a retransmetre-ho per als seus teleespectadors. Des de llavors, s\'han publicat 6 temporades. La sisena promet ser la final.
Pel que fa a la trama de la sèrie animada, gira al voltant de l\'equip de les Gemmes de Cristall. Consta de criatures alienígenes amb noms característics: Perles, Ametista i Magrana. Però hi ha un altre participant, en el paper del qual actua un noi normal, l\'Stephen. Junts busquen monstres i intenten neutralitzar-los perquè no s\'apoderin de la Terra per benefici personal. S\'hi oposen Jasper i Peridot, missatgers del seu planeta natal que volen derrotar les Gemmes i activar el Cluster.
Si sou fans de Steven Universe i voleu veure els personatges de la sèrie animada allà on podeu, instal·leu l\'extensió Cursor Style! Per què fer això? Podeu afegir una col·lecció dedicada a "Steven Universe" i convertir el punter del ratolí estàndard en un dels vostres personatges preferits.',
    'steven_universe_short_descr' => 'Descobriu el secret de les gemmes amb els cursors de Steven Universe',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Una comèdia de situació animada anomenada "Family Guy" en tota la història de la seva existència va guanyar 4 vegades el premi Emmy i 3 vegades l\'"Annie". La sèrie animada ridiculitza els temes dolorosos de la societat nord-americana, com ara: el feminisme, l\'esclavitud, l\'obesitat, la política, etc. A diferència d\'altres obres, aquí s\'utilitzen insercions amb bromes i sarcasme. A més, en molts casos no s\'integren a la trama, sinó que existeixen per si soles.
Un episodi de la sèrie animada es crea durant més de 10 mesos. Per què tant de temps? Perquè tota l\'animació es dibuixa a mà. A causa d\'això, alguns dels esdeveniments coberts per l\'obra tenen temps de perdre rellevància. Però tot i així, la comèdia de situació segueix sent molt interessant i guanya el favor dels espectadors d\'arreu del món. Al cap i a la fi, a qui no li agrada riure bé dels polítics, celebritats o persones que cometen desvaris i, per tant, sorprenen o fins i tot xoquen a la gent normal.
T\'agrada "Family Guy"? Tens una oportunitat única de convertir un cursor de ratolí normal en qualsevol dels personatges d\'aquesta sèrie animada! Què he de fer? Només cal instal·lar l\'extensió del navegador “Cursor Style”, afegir-hi una col·lecció dedicada a “Family Guy” i gaudir d\'una reencarnació fabulosa!',
    'family_guy_short_descr' => 'Col·lecció de cursors de Family Guy per a coneixedors d\'humor especial',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Segur que heu sentit l\'expressió "La bellesa salvarà el món"? Per tant, moltes persones, especialment noies, estan d\'acord amb aquesta afirmació. Per tant, s\'esforcen per envoltar-se de tot el més bonic i agradable a la vista. Pot ser fons de pantalla rosa a l\'habitació, peluixos, coixins brodats amb comptes, joies precioses, etc. Des de fora, tot sembla molt simpàtic i fins i tot una mica infantil. Però cadascú de nosaltres és una mica nen en el nostre cor, així que per què no deixar-lo mostrar la nostra imaginació?
La tendresa en nosaltres pot causar moltes coses. Per exemple, els ulls compassius d\'un gatet que vol ser acariciat o alimentat. Un arc de Sant Martí multicolor, que s\'entreveu després d\'una pluja de primavera que brilla amb tots els colors del sol. El nen que va ser convidat a menjar xocolata i va decidir compartir-la amb la seva xicota o xicot. Hi ha força motius per emocionar-se, i vam decidir utilitzar-los com a cursors.
Cansats de la fletxa blanca avorrida al vostre navegador? Substituïu-la per alguna cosa bonica de la nostra col·lecció! Per exemple, un unicorn rosa i blanc, un tomàquet trist, un núvol ombrívol, un cactus espinós en forma de gat, o el que vulgueu. Tot el que heu de fer és instal·lar l\'extensió Cursor Style i afegir-hi una col·lecció de cursors simpàtics. I llarga vida al salvador del món: la bellesa!',
    'cute_cursors_short_descr' => 'El món serà més amable amb la col·lecció de cursos simpàtics',
    'cute_cursors' => 'Cursos Simpàtics',
    'web_media_descr' => 'En les realitats modernes, gairebé tothom utilitza Internet. Des de nens petits fins a jubilats. Alguns naveguen amb un navegador, d\'altres miren vídeos a YouTube, i d\'altres necessiten la xarxa per comunicar-se amb els seus éssers estimats. Qualsevol d\'aquests usuaris no pot imaginar un dia sense la World Wide Web.
Les persones grans sovint s\'asseuen en una xarxa social com Facebook o VK. També solen comunicar-se amb els seus fills i néts a Skype. Això és especialment convenient si els nens i els pares viuen en ciutats diferents o fins i tot països.
Els joves prefereixen comunicar-se a través de Viber o Telegram, pujar fotos a Instagram, riure\'s dels memes de FB. Els vídeos de YouTube de les reaccions de la gent estan guanyant milions de visualitzacions, igual que diverses bromes o experiments socials. A Tik-Tok, centenars de milers de persones ballen, mostren trucs de màgia i s\'expressen.
Estàs interessat o simplement utilitzes sovint algun tipus de recurs de l\'àmbit dels mitjans web? Vols desfer-te de la fletxa del ratolí avorrida al teu navegador? Aleshores, instal·la l\'extensió i canvia el cursor predeterminat al nostre creatiu! Pot ser el cursor de YouTube, el cursor de Viber, el cursor de Google Chrome o altres recursos.',
    'web_media_short_descr' => 'Viu en un ritme modern amb la col·lecció de cursos de mitjans web',
    'web_media' => 'Mitjans Web',
    'bobs_burgers_descr' => 'La sèrie d\'animació Bob’s Burgers és l\'argument de l\'obra d\'animació i el carisma dels personatges. I, a jutjar per la nominació al premi Emmy i el reconeixement de l\'obra com un dels millors dibuixos animats de tot el món, Bob\'s Snack realment va causar sensació.
L\'argument de la sèrie d\'animació gira al voltant de la família Belcher. Aquesta persona és el propietari del menjador de la primera planta, i a la segona viu amb els seus éssers estimats. En Bob té una esposa alegre, la Linda, i 3 fills: Gene, Louise i Tina. El noi somia amb una carrera musical, la filla gran Tina és molt amable, però incòmoda, i la més jove - Louise encara és una petita diablilla i sovint posa la seva família en una posició incòmoda. El principal competidor de Bob’s Burgers és la Pizzeria de Jimmy Pesto. Com podríeu endevinar, el propietari d\'aquesta pizzeria es diu Jim, i ell i en Bob es detesten. Tot això va ser tractat perquè semblés còmic, no seriosament. Per tant, moltes de les seves escaramusses només causen un somriure.
Si us agrada la sèrie d\'animació “Bob\'s Burgers” i voleu veure els seus personatges no només a la pantalla del monitor o a la televisió, instal·leu l\'extensió, afegiu una col·lecció i canvieu el cursor del ratolí al navegador a qualsevol dels personatges d\'aquest dibuix animat!',
    'bobs_burgers_short_descr' => 'En Bob fa hamburgueses, i nosaltres fem els cursors de Bob\'s Burgers',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'La història del videojoc "Kirby" va començar ja als anys 90 del segle passat. Es compon de moltes sèries que van ser desenvolupades per Nintendo i HAL Laboratory. El joc està pensat per a nens d\'un any i mig a 8 anys. La seva popularitat es pot jutjar pel nombre de còpies venudes. Més de 34 milions a tot el món.
El personatge principal de Kirby és la criatura rosa epònima. Viu en un planeta anomenat Pop Star, i periòdicament el protegeix de diversos perills. En Kerby pot respirar alguns objectes i els seus enemics per tal d\'aprendre les seves habilitats: combat cos a cos, possessió d\'una espasa, respiració de foc, etc. Tanmateix, la bufadora rosa no només lluita amb enemics, sinó que també resol diversos trencaclosques, viatja a altres països i fins i tot pot volar a nivell.
Es pot jugar a aquest videojoc a les consoles Nintendo o Game Boy. En totes les sèries hi ha herois simpàtics, bons gràfics i bandes sonores divertides. Per cert, durant gairebé 30 anys des de el llançament de la primera versió, el món va aconseguir veure 20 sèries de Kirby. Aquest indicador, juntament amb el volum multimilionari de còpies venudes, va ajudar el joc a estar en el TOP 50 dels videojocs més exitosos i buscats de la indústria del joc.
T\'encanta Kirby tant que t\'agradaria veure aquest personatge sempre que fos possible? Aleshores utilitza la col·lecció Kirby i converteix el punter del ratolí normal en el personatge principal del teu videojoc preferit! Estem segurs que t\'agradarà el nou aspecte del cursor.',
    'kirby_short_descr' => 'Intenta inhalar tota la col·lecció de cursors del Kirby',
    'kirby' => 'Kirby',
    'undertale_descr' => 'En temps antics, la Terra estava habitada no només per persones, sinó també per monstres. A causa dels desacords entre ells, va esclatar una guerra, que va acabar a favor de la raça humana. Set mags van conduir els monstres sota terra i els van empresonar allà per sempre amb un encanteri de barrera. No obstant això, només hi havia una entrada al Mont Ebott, que el nen va aprofitar. És per a ell per qui jugaràs executant el videojoc Undertale.
Aquest joc va ser desenvolupat per Toby Fox, un programador conegut dels Estats Units. Al principi, els propietaris d\'ordinadors personals que executaven Microsoft Windows i Linux OS podien gaudir-ne, i després va arribar el torn dels usuaris de consoles de joc.
Quin és el punt d\'aquest joc? El noi viatja pel submón habitat per monstres. Alguns d\'ells són immediatament hostils, mentre que a d\'altres els agrada parlar. El jugador pot triar un dels 2 comportaments: evitar la violència o lluitar. En el primer cas, passar el joc serà més fàcil, en el segon, al contrari, és més difícil. La trama i el final, que poden ramificar-se i canviar, també depenen d\'aquesta elecció.
Si t\'agrada Underground Tale i vols veure els seus personatges al teu navegador, instal·la l\'extensió i afegeix la col·lecció de cursos adequada! Converteix un punter de ratolí avorrit en un dels monstres o en el personatge principal d\'Undertale!',
    'undertale_short_descr' => 'És hora de sortir del forat utilitzant els cursors d\'Undertale',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune és un joc de rol llançat per a ordinadors fa un parell d\'anys. Va ser creat pel mateix programador que va desenvolupar Undertale. No obstant això, aquests dos jocs gairebé no s\'assemblen entre ells, encara que tenen un parell de personatges i ubicacions en comú.
Hi ha diversos personatges principals a Delta Rune. Aquest és un estudiant Chris, que es pot controlar, i una encantadora monstre Susie, incontrolable. Tots dos personatges cauen al món de la foscor, on coneixen un dels seus habitants: Ralsay. Els diu que, de fet, són criatures de llum que tenen una missió: aturar el flux d\'energia fosca en un món ombrívol. Per fer-ho, han d\'estalviar els monstres locals i intentar no participar en batalles amb ells, tot i que de vegades és força difícil de fer.
El jugador té una elecció simple: estalviar les criatures fosques o atacar-les. Com que a la Susie no li agraden les mitges mesures, en molts casos tria una batalla. Per tant, en Chris no té més remei que donar suport a la seva xicota i ajudar-la en les batalles.
T\'agrada el joc Deltarune? Aleshores estilizes el cursor del ratolí al navegador per a un dels seus personatges! Pots fer-ho amb la nostra extensió. Instal·la-la, afegeix la col·lecció “Rune Delta” i activa-la! Ara la teva fletxa ha deixat de ser la mateixa que la de tothom i s\'ha convertit en Chris, Susie o una de les criatures del món fosc.',
    'deltarune_short_descr' => 'Submergeix-te en el món fosc amb aquesta col·lecció de cursor',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario és una sèrie de videojocs llançats per Nintendo. El primer i més popular joc es deia Super Mario Bros. Va veure la llum el 1985. Més tard va ser inclòs al Llibre Guinness dels Rècords. Des de llavors, s\'han llançat més de 20 jocs, cadascun amb la seva pròpia trama. El 2019, va aparèixer una nova versió anomenada Super Mario Maker 2. Malgrat la millora dels gràfics, l\'estil i els personatges van romandre iguals, i això evoca nostàlgia pels Super Mario dels 80.
El protagonista segueix sent el lampista Mario. A la trama de l\'última variació del joc, el castell de la Princesa no va tenir una pedra per aixecar. Mario ha de reconstruir-lo, havent guanyat abans les monedes que se li paguen per tasques. En total, aquest joc té més de 100 nivells de diversa complexitat amb la possibilitat de modificació. També a Super Mario Maker 2 hi ha nous modes de joc. Pots jugar-ne quatre alhora i tan bon punt un acaba, el nivell es considera completat. També hi ha modes com: Marató Mario, Duel i curses Ninjik.
Adoreu Super Mario i tot el relacionat amb aquest meravellós joc? Aleshores, configureu els cursors fets a l\'estil d\'aquest joc de plataformes! Estem segurs que us agradarà el cursor Mario, el cursor Luigi, el cursor Princesa Peach i altres cursors que es presenten a la nostra col·lecció!',
    'super_mario_short_descr' => 'Recorre el regne Xampinyó amb la col·lecció de cursors de Super Mario',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls va ser creat conjuntament per Disney Television Animation Corporation i Alex Hirsch. L\'estrena es va publicar el 2012 i es va emetre a Disney Channel. Tota la primera temporada de la sèrie d\'animació va donar voltes allà. Dos anys després, es va llançar la segona temporada, que els espectadors van poder veure al canal anterior i a Disney XD. Malauradament, els fans de Gravity Falls no van esperar la tercera i posteriors temporades. Els creadors van decidir limitar-se a dues temporades sense cap seqüela.
Pel que fa a la trama d\'aquesta pel·lícula d\'animació, tota l\'acció té lloc en una ciutat fictícia anomenada Gravity Falls. Hi arriben dos bessons, que es diuen Mabel i Dipper. S\'allotgen amb el seu cosí Stan. Ell té la seva pròpia botiga de souvenirs turístics. Quan els germans s\'avorreixen de "no fer res", surten a la recerca d\'aventures. Un d\'ells troba un diari estrany al bosc, que parla de les anomalies d\'aquesta ciutat. Els bessons surten a la recerca del seu autor i es troben amb criatures i llocs inusuals. Si us interessa aquesta sèrie d\'animació, i una vegada vau ser fans dels seus personatges, us recomanem la nostra col·lecció de cursos de ratolí a l\'estil de Gravity Falls!',
    'gravity_falls_short_descr' => 'Emprèn una aventura amb els cursors de Gravity Falls',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Absolutament tothom ha sentit parlar d\'una sèrie d\'animació tan famosa com Els Simpson. Fins i tot aquelles persones que mai han mirat això són conscients de l\'existència de personatges grocs. I els fans estan encantats quan surt la propera temporada del seu dibuix animat preferit. Per cert, a la tardor de 2019, es van estrenar 31 temporades. I la primera va aparèixer a les pantalles de televisió l\'any 1989. Fox va començar a emetre-la i encara ho fa a causa de les altes audiències i la simpatia del públic.
Els Simpson és un gènere satíric que toca temes rellevants. Això pot ser l\'estil de vida del nord-americà mitjà, qüestions polítiques i religioses, els trucs "estel·lars" de les celebritats, el feminisme, el matrimoni homosexual. En general, tot el relacionat amb els esdeveniments locals i globals en què participen els Estats Units.
L\'acció de la sèrie d\'animació té lloc a la ciutat inexistent de Springfield. De fet, hi ha moltes ciutats amb aquest nom a Amèrica. Potser per això va ser elegit perquè el públic no associés el que passava a les pantalles amb una localitat específica, sinó que només endevinés on podria ser.
És molt probable que siguis fan dels Simpson. En cas contrari, per què llegiries aquest text fins al final? I si és així, teniu l\'oportunitat de canviar el cursor del ratolí avorrit per un punter que està fet a l\'estil d\'aquesta sèrie d\'animació.',
    'simpsons_short_descr' => 'Una petita i divertida família protagonitzada pels cursos dels Simpson',
    'simpsons' => 'Els Simpson',
    'youtubers_descr' => 'La plataforma de vídeos de YouTube va aparèixer l\'any 2005. Al principi, els vídeos s\'hi publicaven només per expressar-se o informar sobre alguna cosa. No obstant això, amb el temps, tot això va créixer fins a convertir-se en un negoci rendible, que aporta milers i, de vegades, milions de dòlars al mes als usuaris de YouTube amb èxit. Com més popular és el vlogger (la persona que dirigeix ​​el vídeo blog), més pot guanyar a través del seu canal.
Quant guanya una nena vlogger de cinc anys, els pares de la qual la porten a les atraccions més interessants i graven el que passa davant de la càmera? És només com s\'ho passa una criatura en els parcs infantils, que expressa emocions, com fer el pallasso i tot això. La quantitat és realment sorprenent: avui en dia, el canal de la nena ha guanyat gairebé 47 milions de subscriptors i va començar a generar ingressos per un import de 5 milions de rubles al mes.
Algú puja vídeos on comenta videojocs, algú fa beatboxing o organitza bromes per als vianants al carrer. Alguns dediquen els seus vídeos a temes sensibles, com ara la relació entre homes i dones. Com més agrada als usuaris de YouTube aquests vídeos, més alta és la popularitat del vlogger.
La col·lecció ja ha afegit el cursor de PewDiePie, el cursor de Shane Dawson, el cursor de Ray William Johnson, el cursor de Zoella, el cursor de MyLifeAsEva i altres.',
    'youtubers_short_descr' => 'Una nova generació d\'estrelles està sempre en línia a la nostra col·lecció YouTubers',
    'youtubers' => 'YouTubers',
    'pusheen_descr' => 'Gairebé tothom coneix el gat Pushin. Tot i que només és un personatge d\'un còmic infantil inventat fa 10 anys, avui té milions de fans. El gat Pusheen va aparèixer com una il·lustració creada per l\'artista Claire Belton.
Un any després, el gat va adquirir la seva pròpia pàgina a Tumblr.com i en poques setmanes va guanyar tot un exèrcit de fans, unes 10.000 persones. El 2013, Facebook estava desitjós d\'incloure imatges de Pushin en col·leccions amb altres emoticones. Després de les negociacions amb el creador, aquesta idea es va posar en pràctica i va “esclatar” a Internet! Les imatges del gat Pusheen s\'utilitzen en correspondència més de 10 milions de vegades al dia!
El 2014, un dels fabricants de joguines més grans dels Estats Units va posar la seva atenció en aquest personatge. GUND (va ser ella qui va inventar els óssos de peluix) va llançar un parell de models de Pushin. Com que l\'èxit va ser enorme, al cap d\'uns mesos es va crear una col·lecció completa de joguines en forma d\'aquest gat.
On més podeu conèixer el gat Pusheen? En conjunts de regal d\'Isaac Morris Ltd, en núvols de sucre de Boomf i, per descomptat, a la nostra col·lecció de cursors Pusheen!',
    'pusheen_short_descr' => 'Afegeix una mica de confort al teu navegador amb la col·lecció de cursor de la Pusheen',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'La primera sèrie de l\'obra d\'animació “Rick i Morty” es va estrenar el 2013. Aquesta caricatura es pot atribuir directament a 2 gèneres: ciència ficció i comèdia. Els seus creadors van ser Dan Harmon i Justin Royland. Inicialment, totes les sèries es van mostrar al canal Cartoon Network, i només després es van duplicar en cinemes en línia i allotjament de vídeo. Cada pocs anys, es publiquen noves temporades de Rick i Morty, i el novembre de 2019 va sortir la quarta temporada, que va resultar no menys interessant que les anteriors. La trama de la sèrie d\'animació gira al voltant d\'un geni i, al mateix temps, un científic boig anomenat Rick, així com el seu net poc destacat, Morty. Aquests dos personatges estan connectats per aventures conjuntes en els llocs més inusuals. I hi arriben en un plat volador, capaç de moure\'s per un túnel interespacial. Com podríeu haver endevinat, aquesta sèrie d\'animació s\'assembla una mica a la pel·lícula Back to the Future, però tot i així no és la seva versió animada. No obstant això, va ser elogiat per molts crítics pels episodis humorístics, la creativitat i l\'originalitat. Vols veure en Rick o en Morty no només a la sèrie d\'aquesta obra, sinó també al navegador? Si és així, instala l\'extensió i afegeix la nostra col·lecció dedicada a la teva caricatura preferida! Aquí tenim el cursor Rick Sanchez, el cursor Morty Smith, el cursor Portal Gun i, per descomptat, el cursor Mr. Meeseeks.',
    'rick_and_morty_short_descr' => 'Deixa de rondinar, només utilitza els cursors de la col·lecció Rick and Morty',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Els aficionats al beisbol es poden trobar a qualsevol part del món. Això és especialment cert per als residents de països com: EUA, Xina, Cuba, Corea del Sud, Japó i Veneçuela. Contrari a la creença popular, el beisbol no es va originar a Amèrica, sinó a Anglaterra. La primera menció i descripció del beisbol va aparèixer en el llunyà 1744, en l\'edició anglesa. Després de 145 anys, els nord-americans es van apropiar aquesta invenció per a ells, malgrat els fets.
La Lliga Nacional es va formar el 1876. Forma part de la Major League al Canadà i als Estats Units. Avui dia, hi ha 15 equips a la Lliga Nacional de Beisbol. En la part final de cada temporada, arriba el moment dels playoffs, en els quals participen els 4 millors equips. Així es revela el guanyador de tota la Lliga Nacional. Després, l\'equip guanyador té l\'oportunitat de jugar contra el guanyador de la Lliga Americana a la World Series.
Estàs interessat en el beisbol o fins i tot animes un dels equips? Aleshores ret homenatge al teu equip favorit configurant els cursos del ratolí en forma dels seus atributs! Canvia l\'aspecte avorrit del punter al navegador per la familiar identitat corporativa del beisbol! Converteix la fletxa en un bat o casc de jugador en qualsevol dels equips de la Lliga Nacional, que ja inclouen el cursor dels New York Yankees, el cursor dels Great Falls Dodgers, el cursor dels Boston Red Sox, el cursor dels Baltimore Orioles, el cursor dels Oakland Athletics.',
    'mlb_teams_short_descr' => 'Col·lecció de cursors d\'equips de la MLB per a tots els nostres fans.',
    'mlb_teams' => 'Equips de la MLB',
    'brawl_stars_descr' => 'Brawl Stars és un joc per a mòbils del gènere MOBA de Supercell. Malgrat el llançament a finals del 2018, el joc va guanyar gran popularitat, en gran part a causa de l\'abundància de modes de batalla i herois fantàstics i colorits: els brawlers. El jugador té molt per triar: 32 personatges únics i cadascun d\'ells té el seu propi conjunt d\'habilitats i capacitats. Cada heroi també té la seva pròpia habilitat passiva, que està disponible a través de cofres de botí. Els jugadors poden lluitar en diversos modes, per exemple, "Recompensa per la captura" - un dels dos equips guanya, que ha recollit més estrelles, matant oponents. En el mode "robatori", és necessari trencar les caixes fortes dels oponents mantenint les seves pròpies. Un mode interessant "Agafar gemmes" - l\'equip es converteix en el guanyador, l\'equip que recull la majoria de gemmes guanya. Bé, en el mode "Col·lisió", 10 jugadors lluiten entre ells al mapa, on les fronteres es redueixen a causa d\'un núvol tòxic. El joc està ple d\'un disseny colorit que agrada a molta gent, incloent-nos a nosaltres, cosa que ens va inspirar a crear una col·lecció separada de cursors de Brawl Stars. Hi ha el cursor de la Shelley de Brawl Stars, el cursor de Barley, el cursor de Penny, el cursor de Frank, el cursor de Mortis i altres.',
    'brawl_stars_short_descr' => 'Escull els cursors de Brawl Stars i deixa que comenci la batalla',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Canvia el cursor del teu ratolí en dos clics! Col·leccions gratuïtes per a tots els gustos.',
    'all_descr' => 'Si alguna vegada heu pensat com canviar un cursor del ratolí avorrit, les nostres col·leccions de cursor són per a vosaltres! Aquí trobareu herois de còmics genials, cursos bonics per a jugadors amb personatges de jocs populars, conjunts divertits de cursor per a bromes pràctiques, cursos de colors i moltes altres opcions interessants.',
    'text_title' => 'Col·leccions de cursors divertides i genials per a cada dia',
    'text_allcat_title' => 'Cursors de ratolí únics i creatius per combinar amb tots els teus estats d\'ànim',
    'text_1' => 'No vols ser com tothom? O simplement t\'encanta tot el que és inusual? Vols formar part del teu heroi de videojoc o personatge de dibuixos animats preferit? Llavors has arribat a la direcció correcta. Aquí trobaràs conjunts de cursors brillants i inusuals que poden substituir la fletxa blanca, familiar i ja bastant avorrida. El cursor del ratolí ens acompanya tot el dia a la feina i l\'estudi, per tant, hauria de donar un gran estat d\'ànim i predisposar positivament.',
    'text_2' => 'Aquí trobaràs cursors per a jugadors i amants del cinema, bonics cursors basats en els teus dibuixos animats preferits i motius esportius per a les persones més actives. T\'agraden els còmics o no pots imaginar un sol dia sense memes divertits? Adores els animals o somies a visitar tots els països del món? Tot és simple: també tenim una imatge de cursor adequada per a tu. També pots seleccionar imatges en funció de amb què estàs treballant. Per exemple, un cursor negre serà molt més convenient que el blanc quan treballes amb documents o dibuixos, i un cursor de mà serà més convenient si has de treballar amb petits elements gràfics. Tria la teva imatge preferida, ajusta la seva mida directament a l\'extensió i utilitza-la amb gust, cada dia començant amb una nota positiva!',
    'install_to_preview' => 'Si us plau, instal·la l\'extensió per previsualitzar',
    'install' => 'Instal·lar',
    'add_button' => 'Afegir',
    'preview_button' => 'Previsualitzar',
    'added_button' => 'Afegit',
    'add_cursor' => 'Afegeix el cursor',
    'to_your_collection' => 'a la teva col·lecció',
    'prev_text_1' => 'Previsualització a pantalla completa',
    'prev_text_2' => 'cursor',
    'cursor' => 'cursor',
    'pointer' => 'punter',
    'a_title_1' => 'Cursor Style - Corsors genials per al teu navegador',
    'a_title_2' => 'Col·leccions genials de cursors temàtics',
    'mouse_cursors' => 'cursors de ratolí',
    'cursor_collection' => 'Col·lecció de cursors',
    'sborka_cursorov' => 'col·lecció de cursors',
    'collection_list_from_colllection' => 'Llista de cursors - ',
    'christmas' => 'Nadal',
    'nhl_teams' => 'Lliga Nacional d\'Hoquei',
    'neon' => 'Neon',
    'adventure_time' => 'Hora d\'Aventura',
    'nba_teams' => 'Associació Nacional de Bàsquet',
    'spongebob' => 'Bob Esponja',
    'phineas_and_ferb' => 'Phineas i Ferb',
    'fortnite_chapter_2' => 'Fortnite Capítol 2',
    'pokemon' => 'Pokémon',
    'famous_people' => 'Famosos',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Còmics',
    'igry' => 'Jocs',
    'multfilmy' => 'Dibuixos animats',
    'kino_i_serialy' => 'Pel·lícules',
    'anime' => 'Anime',
    'futbol' => 'Futbol',
    'avtomobili' => 'Cotxes',
    'memy' => 'Memes',
    'emodji' => 'Emoji',
    'pitomcy' => 'Mascotes',
    'stil_i_krasota' => 'Moda i estil',
    'prazdniki' => 'Festes',
    'flagi' => 'Banderes',
    'vokrug_sveta' => 'Al voltant del món',
    'eda_i_napitki' => 'Menjar i begudes',
    'cvetnye' => 'De colors',
    'prank' => 'Miques',
    'startovyj_nabor' => 'Kit d\'inici',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'A Santa li encantarà la teva selecció de cursors de Nadal',
    'nhl_teams_short_descr' => 'Una col·lecció de cursors de la NHL per a aficionats de veritat',
    'neon_short_descr' => 'Afegeix brillantor amb una col·lecció de neon',
    'adventure_time_short_descr' => 'Aprenent matemàtiques amb la col·lecció de cursors d\'Adventure Time',
    'nba_teams_short_descr' => 'Cursors de l\'NBA com a símbol de grans victòries de bàsquet',
    'spongebob_short_descr' => 'Descobreix qui viu al fons de l\'oceà amb la col·lecció de cursors de Bob Esponja',
    'phineas_and_ferb_short_descr' => 'Definitivament no t\'avorriràs amb la col·lecció de cursors de Phineas i Ferb',
    'fortnite_chapter_2_short_descr' => 'El nou capítol del joc de culte Fortnite',
    'pokemon_short_descr' => 'Agafa\'ls tots si pots',
    'famous_people_short_descr' => 'Inspira el teu cursor ídol',
    'the_elder_scrools_short_descr' => 'Submergeix-te en el món de cavallers i dracs',
    'halloween_short_descr' => 'Tingues por de perdre\'t la nova col·lecció de Halloween',
    'nfl_teams_short_descr' => 'Per als autèntics aficionats al futbol americà',
    'five_nights_at_freddy_short_descr' => 'Intenta no espantar-te d\'aquests animatrònics',
    'komiksy_short_descr' => 'Cursors de còmics: tria el teu estat d\'ànim avui.',
    'igry_short_descr' => 'Realitat virtual: a què jugues avui?',
    'multfilmy_short_descr' => 'Els personatges de dibuixos animats preferits amb un nou disseny',
    'kino_i_serialy_short_descr' => 'El Senyor del Cursor: La Germandat de l\'Escriptori',
    'anime_short_descr' => 'A tothom li agrada l\'anime: quin és el teu personatge preferit?',
    'futbol_short_descr' => 'Ets un veritable fan dels esports? Llavors has d\'estar aquí',
    'avtomobili_short_descr' => 'El cotxe dels teus somnis: una gran flota per a professionals',
    'memy_short_descr' => 'Motius preferits: col·lecció de cursors de memes',
    'emodji_short_descr' => 'Mostra el teu veritable estat d\'ànim als altres: estableix Cursoji!',
    'pitomcy_short_descr' => 'Cursors brillants per a tots els amants dels nostres germans petits',
    'stil_i_krasota_short_descr' => 'Cursors originals per a totes les ocasions',
    'prazdniki_short_descr' => 'Què hi ha al calendari? Nova col·lecció de cursos de festius!',
    'flagi_short_descr' => 'Buscant aventura: on anem avui?',
    'vokrug_sveta_short_descr' => 'La volta al món en un instant: on anem avui?',
    'eda_i_napitki_short_descr' => 'Cursors per llepar-se els dits per a la creativitat',
    'cvetnye_short_descr' => 'Pinteu la vostra vida amb colors brillants i pinzellades audaces',
    'prank_short_descr' => 'Un conjunt de cursors per als bromes més divertides',
    'startovyj_nabor_short_descr' => 'Una nova mirada a les coses familiars: una sèrie de cursors actualitzada',
    'fortnite_short_descr' => 'Segueix els streamers!',
    'dota_2_short_descr' => 'Fes que el teu món virtual sigui real!',
    'minecraft_short_descr' => 'Els personatges del teu joc preferit sempre a prop',
    'christmas_descr' => 'Cadascú de nosaltres, sens dubte, espera les vacances més populars: el Nadal. Tots els cristians del món el celebren tradicionalment cada any, el 25 de desembre. Un moment en què les famílies es reuneixen a taula, comparteixen la seva alegria i amor i intercanvien regals. Molt abans del Nadal, la gent decora els carrers amb garlandes brillants i les seves cases amb atributs tradicionals. És difícil trobar una persona a qui no li agradi el Nadal, unes vacances divertides i misterioses, ja que va acompanyat de moltes tradicions i rituals que ens retornen a les arrels de tota la nostra família. La vigília de Nadal, literalment, tot està saturat del seu esperit, des del pa de gingebre pintat fins als càntics commovedors. Un elegant arbre de Nadal i regals a sota, una alegria familiar per a cadascú de nosaltres des de la infància. Volem unir-nos a aquestes vacances màgiques i, qui sap, potser el Pare Noel us prepararà un regal especial si decoreu el vostre cursor amb la nostra col·lecció de Nadal. Ho teniu tot per fer-ho, el cursor del Pare Noel, el cursor de l\'arbre de Nadal, el cursor de pa de gingebre, el cursor de l\'home de neu i, fins i tot, el cursor del sac de regals. Bon Nadal!',
    'nhl_teams_descr' => 'La National Hockey League es va formar el 1917 - és una organització esportiva professional que reuneix clubs d\'hoquei dels EUA i el Canadà. I aquesta és una de les primeres lligues d\'hoquei professional del món. La NHL és una de les principals lligues esportives d\'Amèrica del Nord, juntament amb la NFL, la NBA, la Major League Baseball i la MLS. Cada any, 31 equips de 30 ciutats dels EUA i el Canadà lluiten pel trofeu principal - la Copa Stanley, i l\'equip que va obtenir la majoria de punts en la temporada regular rep la Copa del President. És hora d\'honrar aquest gran joc creant una col·lecció de cursors de la NHL. Si a tu també t\'agrada l\'hoquei, anima al teu club favorit o participa en aquest esport, només has de canviar el cursor i no separar-te del teu equip favorit, inclòs el cursor dels Boston Bruins, el cursor dels St. Louis Blues, el cursor dels Columbus Blue Jackets, el cursor dels Tampa Bay Lightning, el cursor dels Dallas Stars i altres clubs dignes de sincer respecte.',
    'neon_descr' => 'Hem creat una col·lecció única de cursors de neó per afegir varietat a la navegació diària per Internet i afegir una mica de brillantor a les fascinants llums de neó. Deixeu que els seus rics colors creïn l\'atmosfera envoltant de la ciutat a la nit, doneu inspiració per crear alguna cosa nova. En el món modern, les llums d\'una metròpoli sempre anuncien l\'arribada de la nit, ens segueixen a cada carrer i aquesta resplendor s\'omple d\'energia. Que també sigui seguit per un cursor de gelat brillant, un cursor de gos calent deliciós, un cursor d\'hamburguesa sucosa, un cursor de diamant brillant i altres cursors de la nova col·lecció de neó.',
    'adventure_time_descr' => '"Adventure Time" és una sèrie de dibuixos animats de gènere fantàstic en què l\'acció té lloc en un món que ha sobreviscut a l\'apocalipsi. Aquest territori es diu Terra d\'Ooo, que fins fa poc va ser una guerra nuclear. Però tot això ja és al passat, no obstant això, totes les persones supervivents van ser subjectes a mutacions, i el món es va omplir de màgia. Els personatges principals de la sèrie animada són Finn, un noi de 14 anys i el seu amic un gos anomenat Jake. El noi i el gos són molt aficionats a l\'aventura, constantment ajuden a tothom que està en problemes. Els amics viuen en un arbre i passen tot el temps junts. Si vols submergir-te en un món d\'aventures amb altres admiradors, crida "Matemàtiques". Aquí teniu tant el cursor Finn Boy com el cursor Jake, així com el cursor Princessa Xiclet. Per descomptat, no ens vam oblidar del cursor Bimo, del cursor Rei Gel i d\'altres.',
    'nba_teams_descr' => 'Si el bàsquet és el teu joc favorit, com ho és per a nosaltres, llavors una col·lecció de cursors dedicats als equips de l\'NBA és el que necessites. L\'NBA és una de les principals associacions esportives del continent nord-americà. Quan vam crear aquesta col·lecció, ens va turmentar la tria: quin equip triar, perquè n\'hi ha trenta a l\'NBA. Però hi ha equips que són llegendes. Aquests i els Chicago Bulls, que van establir un rècord de victòries a mitjans dels 90. Aquests són els Golden State Warriors, que van reunir els millors jugadors de la lliga fa un parell d\'anys. O, per exemple, Lakers, Celtics també són equips increïblement genials. Si, com nosaltres, esteu esperant els partits dels vostres equips de bàsquet preferits i voleu mostrar el vostre suport a l\'equip o als jugadors, descarregueu la nostra col·lecció de cursors de l\'NBA.',
    'spongebob_descr' => 'La sèrie d\'animació "Bob Esponja" és coneguda per tanta gent. Va ser un èxit aclaparador després que Nickelodeon decidís el 1999 crear una sèrie d\'animació basada en la tira còmica educativa Tide Zone, i es va convertir en una franquícia molt lucrativa. El creador de la sèrie és un antic empleat del laboratori oceanològic, per la qual cosa gairebé tots els personatges de la sèrie d\'animació són divertits habitants del fons marí, amb les seves pròpies característiques i carisma. L\'acció gira al voltant de la recepta secreta de la Krabsburguer que només el personatge principal pot cuinar: Bob Esponja. I els altres habitants del mar intenten aconseguir-la, inclòs l\'antiheroi principal, Sheldon Plankton, que no ho aconsegueix mai. A la col·lecció de cursors Bob Esponja, hem reunit els cursors de tots els personatges i esdeveniments notables de la sèrie. Per exemple, el cursor del Sr. Krabs amb el dòlar, el cursor de Patricio Estrella, Calamardo amb el seu clarinet, el cursor de la medusa, el cursor de Bob Esponja i molts altres personatges.',
    'phineas_and_ferb_descr' => 'A la ciutat americana fictícia de Denville de la inexistent Trishtatya, hi viuen dos nois interessants. Cada dia de les seves vacances es converteix en aventures increïbles, perquè poden fer una muntanya russa de la mida d\'una ciutat sencera o un portal real a un altre planeta. Comparteixen el seu increïble entreteniment amb els amics. Al mateix temps, mentre els nois s\'ho passen bé, el científic malvat Heinz Fufelschmertz està construint una altra màquina malvada que crea el caos, amb el nom que acaba en "-inator", amb l\'ajuda de la qual vol venjar els seus greuges de la infància o apoderar-se del poder a Trishtat, però Perry l\'està obstaculitzant - Utkonos, el secret "Agent Pi", que treballa sota la disfressa de mascota dels nois. La popularitat d\'aquesta sèrie d\'animació, tant entre nens com entre adults, ens va inspirar a crear una col·lecció de cursors de Phineas i Ferb perquè puguis canviar el cursor del ratolí pels personatges de la sèrie. Entre ells hi ha el cursor de Phineas Flynn, el cursor del Dr. Heinz Fufelschmertz, el cursor de Ferb Fletcher, el cursor de Candace Gertrude Flynn i el cursor de Perry l\'ornitorrinc.',
    'fortnite_chapter_2_descr' => 'El segon capítol de Fortnite va arribar després d\'un gran esdeveniment: The End, que va arrossegar tot el que els jugadors del joc estimaven en un forat negre. Fortnite Chapter 2 ara té un nou mapa, que a primera vista és encara més salvatge que el mapa original, així com molts canvis en la mecànica del joc i, per descomptat, un munt de contingut nou al joc! Vehicles, emocions, mecàniques de natació i molt més: tot això en imatges fresques i interessants, tot tal com t\'agrada i aprecia en aquest joc de culte. Submergeix-te en un món nou: tria un lloc d\'aterratge i explora una illa completament nova amb 13 ubicacions. Natació, pesca, llanxes motores: aquesta és una nova jugabilitat aquàtica. Més diversió i menys esforç: actualitza un capítol 2 completament nou i no t\'oblidis de canviar el cursor a noves skins i armes. Ja t\'esperen les skins actualitzades Turk cursor, Riptide cursor, Rippley cursor, Remedy cursor, Toxin cursor, 8-Ball cursor, Fusion cursor i altres!',
    'pokemon_descr' => 'La paraula "pokemon" significa una criatura amb poders sobrenaturals. Tenen intel·ligència i alguns d\'ells fins i tot poden parlar. Actualment, ja hi ha 802 varietats de Pokémon. A l\'univers inventat dels Pokémon, les persones s\'anomenen entrenadors Pokémon, als quals entrenen per a batalles amb els Pokémon d\'altres entrenadors. I com més experimentat i fort sigui l\'entrenador, més respecte gaudeix. Afortunadament, cal assenyalar que les baralles de Pokémon mai acaben amb la mort d\'aquestes criatures úniques. Tots els Pokémon tenen habilitats diferents i difereixen en el tipus d\'element, i la seva resistència a diferents atacs depèn en gran mesura d\'això, i algunes criatures tenen l\'habilitat de dos elements alhora. Després de guanyar la batalla, el Pokémon obté l\'experiència valuosa que és necessària per augmentar el nivell i, en conseqüència, les seves característiques. Avui, l\'univers Pokémon és una enorme franquícia mediàtica i decidirem preparar-vos una col·lecció de cursors amb alguns Pokémon populars. Entre ells, el més famós és el cursor Pikachu, així com el cursor Rattata, el cursor Squirt, el cursor Bulbasaur i el cursor Charmander. Aquesta llista s\'actualitzarà, perquè n\'hi ha tants i cadascun d\'ells és únic a la seva manera.',
    'famous_people_descr' => 'Entre les moltes persones famoses, cadascú de nosaltres troba un model a seguir o simplement admira el geni, el talent i la perseverança d\'aquestes celebritats. Hem preparat una col·lecció de cursors de celebritats per inspirar-vos i recordar-vos els grans èxits que cadascú de vosaltres pot augmentar. No totes les personalitats famoses van tenir un destí feliç, però ens ensenyen la cosa principal que mai necessites retirar-te del teu objectiu estimat, malgrat les dificultats i els problemes. Després de tot, aquest és el principi principal per aconseguir l\'èxit: anar al teu somni cada dia i, finalment, convertir-te en el millor en el teu camp. Potser avui només vols canviar el cursor del ratolí, i demà tota la teva vida canviarà per a millor! La col·lecció s\'actualitzarà constantment amb representants nous i dignes de la humanitat. Entre ells, per descomptat, científics, polítics, esportistes, representants de l\'art i molts altres.  El cursor de George Washington, el cursor de Michael Jordan, el cursor de Stephen King, el cursor d\'Elvis Presley i el cursor de Marilyn Monroe són només el començament.',
    'the_elder_scrools_descr' => 'The Elder Scrolls és una sèrie de jocs de rol per ordinador, units per un univers comú, meticulosament dissenyat, que proporciona al jugador una enorme llibertat d\'elecció, permetent-li visitar diferents zones i ciutats del món de fantasia i explorar nous llocs i missions per si mateix. El treball en la sèrie es va iniciar el 1992 i, al llarg dels anys, el joc ha unit una gran comunitat de jugadors al seu voltant. Per tant, a petició popular, hem llançat una col·lecció de cursos de The Elder Scrolls, perquè pugueu submergir-vos en l\'atmosfera única del joc. L\'eterna batalla de cavallers i dracs, de quin bàndol esteu? Canvieu el cursor a un drac i uniu-vos a l\'exèrcit de monstres que respiren foc o lluitau noblement al costat de la gent escollint el cursor d\'espasa i la imatge del vostre personatge favorit: la decisió és vostra! El més important és que amb la nostra nova col·lecció, esteu preparats per a qualsevol batalla.',
    'halloween_descr' => 'Esperant una nit mística la vigília del dia de Tots els Sants. La història de Halloween es remunta a fa més de dos mil anys. Potser aquesta és la festa més estranya que combina diversió i por, nativa de la cultura celta. Llavors, la gent cremaven fogueres i es posaven disfresses esgarrifoses per allunyar els fantasmes. La paraula "Halloween" es va esmentar per primera vegada al segle XVI com una abreviatura escocesa de la frase anglesa All-Hallows-Even. El papa Gregori III va declarar l\'1 de novembre el dia de Tots els Sants, i el vespre anterior es coneixia com la vigília de Tots els Sants, i més tard Halloween. En aquest dia, la gent porta disfresses de llops, fantasmes i altres monstres i van a cases veïnes, oferint-se a comprar dolços. Les festes temàtiques, els focs artificials, les boniques llanternes, les carbasses i les acrobàcies creen una atmosfera única. També volem celebrar aquest terrible dia amb cursos d\'accessoris i personatges de Halloween. A la nostra col·lecció podeu trobar: cursor zombi, cursor fantasma, cursor gat negre, cursor carbassa i molt més. Canviar el teu estat d\'ànim ara és tan fàcil com canviar el teu cursor amb la nostra nova col·lecció de Halloween.',
    'nfl_teams_descr' => 'Què podria ser millor per a un autèntic fan del futbol americà que un cursor del ratolí en forma de simbolisme de l\'equip del qual és fan? A la moderna National Football League, trenta-dos equips juguen, dividits entre les Conferències Nacionals i Americanes de Futbol (National Football Conference, NFC i American Football Conference, AFC). Al seu torn, cadascuna de les conferències es divideix en quatre divisions: Est, Nord, Sud i Oest. La temporada de la NFL consta de partits de pretemporada, una temporada regular i una sèrie de partits de playoffs. El partit final de la temporada de la NFL s\'anomena Super Bowl i és essencialment l\'esdeveniment esportiu més popular als Estats Units. Aquest és un joc favorit per a milions de fans i, per tant, hem creat una col·lecció de cursors de la NFL perquè no us separeu dels símbols del vostre equip favorit. Siguin els New England Patriots, els New York Giants, els Buffalo Bills o un altre equip, estigueu sempre a la mateixa longitud d\'ona que els vostres ídols, utilitzant els nostres cursors en forma de logotip i casc de l\'equip. La col·lecció s\'actualitzarà constantment perquè tothom pugui canviar el cursor a la imatge del seu equip favorit.',
    'five_nights_at_freddy_descr' => 'El joc realment únic Five Nights at Freddy\'s va guanyar ràpidament una gran popularitat i això no és sorprenent, perquè la seva trama senzilla i alhora fascinant pot mantenir els jugadors a les pantalles durant hores. Vam dissenyar els cursors de Five Nights at Freddy\'s a petició dels aficionats al joc i ens va fer molta il·lusió encarnar personatges tan interessants i divertits. Però a diferència del joc, res us amenaça amb els nostres cursors, així que no dubteu a triar els vostres animatrònics preferits, ja sigui l\'Os Freddy o el Conill Bonnie o altres. El més important és que ara el joc cobra vida al vostre navegador i dóna noves emocions. Garantim que no hi ha fantasmes als nostres cursors, però transmeten perfectament l\'esperit d\'un joc que inspira por a causa de les complexitats del disseny i els elements de la trama. Però, què passa si feu que la mida del cursor sigui molt gran? Pots mantenir la calma i no espantar-te?',
    'komiksy_descr' => 'Semblaria que el cursor del ratolí és una trivialitat, però sovint són aquests detalls els que poden millorar el teu estat d\'ànim, despertar-te en el matí gris o simplement donar emocions brillants. Una col·lecció de cursors de còmics dissenyats específicament per a tots els amants dels superherois. Aquí pots trobar absolutament tot l\'Univers Marvel i DC Comics - des d\'Iron Man fins a Thanos, Spider-Man i Hulk. L\'estil del cursor pot ser en forma de superheroi, o en forma del seu personatge. Un cursor no és només un element funcional; és important en un sentit professional. Per exemple, si estàs gravant un vídeo des de la pantalla, serà millor veure una imatge brillant i original, i sembla molt més interessant. I, per descomptat, qui no voldria utilitzar el guant de l\'infinit a la vida real? Canviar el cursor del ratolí és senzill: només has de descarregar l\'extensió al teu navegador i afegir el cursor que t\'agradi a la configuració. Pots triar un cursor segons el teu estat d\'ànim almenys cada dia. Prou dies grisos: converteix-te en un superheroi ara mateix!',
    'igry_descr' => 'Els jocs d\'ordinador fa temps que s\'han convertit en una part integral de les nostres vides. Amb la seva ajuda, podeu submergir-vos en un món nou, participar en aventures i convertir-vos en una persona completament diferent. Cadascú té la seva pròpia joguina preferida, els personatges de la qual ja s\'han convertit gairebé en família. Un conjunt de cursors basats en jocs d\'ordinador coneguts és una oportunitat per diluir la vida quotidiana avorrida i afegir una mica de creativitat, brillantor i diversió al flux de treball. El conjunt conté tant imatges dels propis herois del joc, com personatges auxiliars, armes i icones del joc. Trieu el que s\'adapti al vostre estat d\'ànim: els cursors del joc atrauran no només els jugadors, sinó també tothom que simplement estigui cansat de la vida quotidiana grisa. Només cal que descarregueu el conjunt, canvieu el cursor del ratolí i aneu, per completar tasques de missió, destruir enemics i assolir els vostres objectius.',
    'multfilmy_descr' => 'Dins de cada adult encara hi ha un nen a qui li encanten les dibuixos animats i que encara somia amb convertir-se en un dels herois. Ajudarem a fer realitat els teus somnis: utilitza la nova col·lecció de cursors basada en els dibuixos animats més famosos i preferits. Tom i Jerry, Buzz Lightyear i Shrek, Gravity Falls i fins i tot Pokémon: pots convertir-te en el que vulguis cada dia. Selecciona el cursor del ratolí segons el teu estat d\'ànim. Qui ets avui? Un minion temerari i alegre que resol fàcilment qualsevol problema o un Rafael fort i valent, l\'objectiu del qual no només és aconseguir gestes, sinó també menjar pizza? Potser ets el geni totpoderós que té tota una oficina sota el seu comandament? A la col·lecció hi ha herois per a tothom, des de princeses fins a dracs, només queda decidir qui reflecteix l\'estat d\'ànim actual. Cursor Style no és només una imatge bonica. Aquesta és una reflexió de la individualitat, l\'autoexpressió i simplement: diversió, alegria i positivisme per a tot el dia. És avorrit treballar o massa gandul per estudiar? T\'has posat trist i no ets feliç? Canvia el cursor i el món brillarà amb nous colors.',
    'kino_i_serialy_descr' => 'Les pel·lícules: la màgia, el misticisme i una fantàstica manera de relaxar-se, divertir-se i obtenir emocions vívides. Al mateix temps, després de veure-les, encara recordem els herois favorits que realment volem conèixer en la realitat. Ara és possible: només cal descarregar la nova col·lecció de cursors basada en pel·lícules i sèries de televisió famoses. Els cursors brillants i genials seran una gran addició a l\'escriptori, convertiran la grisa i avorrida vida quotidiana en una festa, i les tasques banals, en una aventura emocionant. Canvieu el cursor de l\'heroi cada dia: per l\'humor, les tasques o a l\'atzar. Qui sereu avui? L\'honest i just John Snow o el valent i implacable John Wick? Potser teniu una missió difícil per davant i només Frodo pot completar-la? Potser avui només sou un alien que no vol contactar amb els altres? Trieu un cursor adequat: animeu-vos i, al mateix temps, mostreu als altres què penseu i com teniu previst passar el dia. Proveu-ho: no només és divertit, sinó que també crea addicció: segur que no voldreu tornar a la fletxa habitual.',
    'anime_descr' => 'L\'anime és un estil únic d\'animació que, malgrat la seva pronunciada ètnia, ha estat gaudit per milions de persones arreu del món. És poc probable que hi hagi almenys una persona que no hagi vist dibuixos animats d\'aquest estil. Hem creat els cursos d\'estil anime més interessants que encantarà a tots els fans d\'aquest estil. Els cursos estàndard són avorrits i gastats. Mostra la teva personalitat: utilitza la col·lecció de cursos Anime amb els teus personatges preferits. Tria el cursor d\'una espasa fosca si somies amb aventures i batalles valentes. El simpàtic home gras Totoro t\'animarà fins i tot en el dia més trist, i Naruto et motivarà en aventures i demostrarà a tothom que ets un mega guai. Els cursos brillants alegraran la jornada laboral o faran que el procés d\'aprenentatge sigui més interessant i agradable. No et limitis, utilitza els teus motius preferits fins i tot en elements tan petits com el cursor del ratolí. Canvia de cursor cada dia, adapta\'ls al teu estat d\'ànim i mostra la teva personalitat: amb els cursos d\'estil anime és així de senzill.',
    'futbol_descr' => 'El futbol és un esport especial que inclou elements de lluita, atletisme i precisió. En general, és espectacular, despietat i aplega milions de fans arreu del món. T\'agrada el futbol o simplement estimes l\'esport? Aleshores, descarrega un conjunt de cursors a l\'estil del joc de fama mundial i demostra el títol de fan lleial. La col·lecció conté 24 opcions per dissenyar cursors: en forma dels equips més populars que mereixen els seus títols com un joc desesperat i persistent. Els cursors estan fets en dues versions: en forma de triangle estàndard, decorat amb els colors de l\'equip, o en forma de casc de joc corresponent. El cursor estàndard del navegador és avorrit i no digne d\'un autèntic fan de l\'esport. Sigues original i únic amb la nostra col·lecció. Descarrega imatges i tria els colors del teu equip favorit o els cursors personalitzats si simplement estimes l\'esport i fas forces per tothom. Seguir les teves aficions és tan senzill: no has d\'anar a treballar amb una bufanda o gorra del teu equip favorit, és ràpidament i fàcil canviar el cursor per una imatge brillant i elegant.',
    'avtomobili_descr' => 'T\'agraden els cotxes i gaudeixes mirant models de diferents fabricants? O fa temps que somies amb una marca en particular, però encara no tens l\'oportunitat de comprar-la? Especialment per a tu, hem creat un conjunt de cursos brillants "Supercars". Aquí trobaràs Ford clàssics i Bentley elegants, Lamborghini brillants i Ferrari únics. Vols convertir-te en el propietari del cotxe original? És senzill: baixa la nostra col·lecció de cursos al teu dispositiu i canvia la imatge del cotxe almenys cada dia. Els cursos estan dissenyats en dues versions: com un cotxe complet o com el seu signe. Tria el que més t\'agrada o com prefereixes treballar. Aquestes imatges es veuran fantàstiques com a cursos de joc o simplement com un element inusual de l\'escriptori. Ser brillant és senzill: no és necessari fer coses inimaginables per això o canviar el teu aspecte. N\'hi ha prou amb deixar d\'utilitzar objectes comuns i triar el que realment t\'agrada. La col·lecció de cursos "Cotxes" és la selecció per a aquells que no tenen por de demostrar-se a si mateixos.',
    'memy_descr' => 'Els memes han estat una part familiar de les nostres vides durant molt de temps. I a qui de nosaltres no li agraden aquestes imatges capaces, interessants i originals per desafiar el dia? Molts herois dels memes s\'han tornat no només populars, sinó que han adquirit l\'estatus de favorits populars, i les frases i expressions s’han inclòs durant molt de temps en la parla col·loquial com a girs ben establerts. Presentem una col·lecció dels millors cursors basats en els memes més populars. Amb la seva ajuda, no només podeu mostrar la vostra personalitat, sinó que també podeu expressar el vostre estat d\'ànim. Esteu tots cansats i farts de tot? Trieu un gat enfadat que, amb tota la seva aparença, expressa indignació i hostilitat per tot el que l\'envolta. O brilla amb sarcasme avui i no us importa riure? Aleshores, Drake Bling serà un excel·lent acompanyament: us animarà i farà que qualsevol tasca sigui original i interessant. Instal·leu l\'extensió, baixeu la nostra col·lecció i trieu un estil de cursor per a cada dia. No és difícil ser brillant i original: canvieu el disseny estàndard de la icona per un dels herois dels memes i obteniu un impuls d’energia per a tot el dia.',
    'emodji_descr' => 'Emoji - icones brillants i divertits, sense els quals ja no podem comunicar-nos habitualment. Amb la seva ajuda, no necessiteu descriure el vostre estat d\'ànim amb paraules - només seleccioneu la icona desitjada i l\'interlocutor us entén sense més preàmbuls. En el nostre nou conjunt de cursors, vam encarnar la idea dels emoji - així és com van aparèixer els divertits i inusuals Cursoji que donaran color al món i faran la vida més interessant. Amb l\'ajuda dels cursos, no només podeu treballar i realitzar tasques familiars, sinó també mostrar als vostres companys, amics i a la resta el vostre estat d\'ànim. Un cursor adormit és perfecte per al dilluns al matí, i un cursor plorant expressarà una actitud sobre responsabilitats addicionals. Un cursor genial amb ulleres és la millor opció abans de les vacances, i un cursor amb dòlars als ulls és una bona raó per insinuar al cap sobre l\'augment de sou. Usar Cursoji és divertit i interessant, ja sigui per treballar, estudiar o presentar. En aquest darrer cas, fins i tot es recomana fer-ho si els companys tenen sentit de l\'humor o simplement necessiten desinflamar la situació. En general, per a qualsevol tasca - només cal triar el curs adequat!',
    'pitomcy_descr' => 'Us agraden els animals? Segurament, són tan macos, divertits i molt graciosos. Per què no passar tot el dia acompanyat dels millors amics d\'una persona? Descarrega la col·lecció de cursors Pets per a tu i tria un amic per a cada dia. La icona del cursor pot ser bonica, com una alpaca amable, o elegant, com un flamenc rosa. O potser estaràs ocupat tot el dia i triaràs un unicorn llegint un diari, o simplement no vols comunicar-te amb ningú, com un gat negre malvat? Per a qualsevol estat d\'ànim, tenim l\'animal corresponent. Un carlí alegre et farà aixecar l\'ànim fins i tot en el dia més avorrit i gris, i el cursor rosa en forma d\'unicorn mostrarà a tothom que no estàs privat del sentit de la bellesa, fins i tot sent un home barbut brutal. I si no hi ha ànim, i no tinc ganes de fer tasques rutinàries? La recepta és senzilla: descarrega la col·lecció Pets, canvia el cursor del ratolí i voilà, el sol torna a brillar, el temps és bo i l\'estat d\'ànim està al nivell més alt. No és d\'estranyar que diguin que els animals ajuden a combatre la depressió i la tristesa!',
    'stil_i_krasota_descr' => 'A la nova col·lecció de cursors, hem recopilat una gran varietat de temes que ens causen emocions agradables i ens animen. Aquest conjunt de cursors es diu “Estil i Bellesa”, perquè són les vostres coses preferides que determinen la nostra vida quotidiana, ens donen alegria i ens motiven a fer coses importants, despertant-nos el desig de millorar. Teniu afició per l\'espai i somieu anar a altres planetes? Trieu un cursor de la NASA o un plat d\'extraterrestres: aprop-vos al vostre somni. Si no podeu imaginar la vida sense música o sou un rocker empedreït, aleshores el cursor a l\'estil d\'una guitarra elèctrica és per a vosaltres. El cursor de pinzell, regla i compàs ha estat desenvolupat especialment per a enginyers: aquestes imatges ajudaran a convertir càlculs i dibuixos avorrits en solucions originals. Una vareta màgica i sabatilles esportives, un monopatí i pintallavis, el sol i cons químics: trieu el que s\'adapti al vostre estil de vida, als vostres desitjos i aspiracions, i les tasques ordinàries es tornaran més interessants, i els dies laborables es pintaran amb colors nous i brillants.',
    'prazdniki_descr' => 'T\'agraden les festes? Però a qui no li agraden, amics, regals, de nou el mateix cap de setmana. Per fer que l\'espera de les festes sigui més agradable, més curta i més càlida, no només podeu comptar els dies al calendari, sinó també establir la icona corresponent com a cursor del ratolí. Comencem amb l\'Any Nou: triarem un arbre de Nadal, un regal o Pare Noel, perquè la festa sigui brillant i alegre. Potser l\'home de gingebre estarà més a prop, divertit, simpàtic i sempre alegre? Amb ell, difícilment hi haurà temps per estar trist i avorrit. Continuem celebrant amb cupidos i cors alegres, i no hi ha gaire per al Conill de Pasqua. Enmig de les festes, hi haurà un aniversari, que serà encara més agradable d\'esperar amb globus en lloc de la fletxa del cursor estàndard. I a Halloween, podeu sorprendre els col·legues i els que us envolten amb un cursor del ratolí inusual en forma de carbassa ominosa o un fantasma. Un conjunt de cursos per a les festes és una oportunitat per alegrar l\'expectativa, sintonitzar per endavant la diversió que ve i mantenir un estat d\'ànim excel·lent no només la vigília de la celebració, sinó durant tot l\'any.',
    'flagi_descr' => 'La bandera és un símbol únic que s\'utilitza àmpliament a totes les xarxes socials. Vam pensar, per què no fer que el cursor sigui una bandera? Després de tot, és realment brillant i inusual. Ara podeu passar cada dia en companyia d\'un nou país, i el treball no serà tan monòton i avorrit. Els cursos del ratolí ara es poden convertir en la bandera nacional de la Xina o dels EUA, el Japó o el Canadà, i en altres 38 opcions de bandera, i podeu triar la forma de fletxa estàndard en un color inusual o el cursor en forma de la pròpia bandera. Aquest conjunt apel·larà a tots els amants dels viatges. Amb ell, podeu planificar nous viatges i somiar amb llargs viatges. Heu planejat unes vacances? Mostreu a tothom a quin país voleu anar. Potser heu decidit aprendre un nou idioma estranger? Llavors, aquest cursor definitivament us donarà suport i us motivarà a estudiar amb cura. O, com Sheldon, us encanten les banderes? En tots els casos, la col·lecció de cursos de Bandera serà una gran addició al vostre escriptori i us traslladarà a nous descobriments.',
    'vokrug_sveta_descr' => 'A tothom li agrada viatjar. Que meravellós és visitar països i ciutats nous, veure els llocs d\'interès i passar-ho bé en la nova cultura. És una llàstima que no puguem viatjar tan sovint, però hem intentat solucionar-ho. El conjunt de cursos “Al voltant del món” és una col·lecció de les imatges més impactants, símbols de diferents països, amb l\'ajuda dels quals, fins i tot asseguts a casa, podeu sentir-vos com un autèntic viatger. Al nostre kit podeu trobar el Japó i Austràlia, Itàlia i Canadà, els EUA i Mèxic: els països més interessants, originals i pintorescos del món. La imatge del cursor pot convertir-se en una fletxa estàndard, amb els colors de la bandera del país, o convertir-se en una de les principals atraccions de l\'estat. Per exemple, podeu obrir documents amb la Torre Inclinada de Pisa i fer presentacions utilitzant l\'Estàtua de la Llibertat. Garantim que l\'èxit estarà assegurat. Bé, o si no l\'èxit, els somriures dels companys i el reconeixement de l\'originalitat, segur. Sí, i insinuar a la direcció que és hora d\'anar de vacances també valdrà la pena: només configureu la maleta o l\'avió com a cursor, i el més probable és que volareu molt aviat.',
    'eda_i_napitki_descr' => 'Un conjunt de cursors en forma de productes és una increïble col·lecció d\'imatges brillants, saboroses i que fan la boca aigua que a tothom li agradarà i serà una gran addició al navegador. Alguna vegada has fet clic en bròquil o patates fregides? Tens aquesta oportunitat: només has de descarregar un nou conjunt de cursors i configurar-los en lloc d\'una fletxa blanca avorrida. Els cursors "Menjar" estan fets tant en forma d\'un punter triangular estàndard com en forma de productes. Aquí trobaràs verdures i fruites, els teus plats preferits, com pizza o gossos calents, cafè, piruletes i molt més, que alegren qualsevol dia. T\'agrada el cafè, però prendre\'n tot el dia no és tan bo? Complementa la teva dieta amb cafè virtual, que també t\'invigorarà i et despertarà, a més de donar emocions vívides. Un cursor pronunciat en forma de donut virtual no perjudicarà la figura, a la vegada que donarà emocions vívides i animarà. Pots utilitzar els teus cursors preferits o canviar la imatge cada dia: una gran selecció de cursors ajudarà a acolorir la vida quotidiana i afegir nous colors a les accions habituals.',
    'cvetnye_descr' => 'El cursor és l\'element principal del navegador, amb el qual passem tot el dia laboral, estudiem, ens comuniquem i ens relaxem. La vista estàndard del cursor és avorrida i fins i tot una mica depriment, però tot i així, per a moltes persones, aquesta forma és convenient, i canviar-la serà incòmode. Però per a aquesta situació, tenim una solució: un conjunt de cursos en colors brillants i alegres que afegiran varietat a la vostra vida quotidiana i faran que resoldre qualsevol problema sigui més fàcil i ràpid. Si esteu pensant en com canviar el color del cursor, responem: descarregueu la nostra col·lecció i trieu solucions brillants per a tots els dies! Podeu triar tons monocromàtics en diferents colors per adaptar-vos a l\'estat d\'ànim o a les especificitats del treball. Per exemple, quan treballeu amb documents estàndard, un cursor morat destacarà sobre el fons, i sobre un fons fosc, al contrari, serà més fàcil treballar amb cursos grocs. Si voleu una explosió de color, brillantor i màxima originalitat, trieu un cursor d\'arc de Sant Martí que inclou tots els colors de l\'espectre; amb aquesta icona, l\'estat d\'ànim definitivament serà bo durant tot el dia.',
    'prank_descr' => 'Les bromes a la feina no sempre són benvingudes, ja que sovint interfereixen amb el flux de treball. Però amb el nou conjunt de cursors “Bromes”, podeu fer una broma amablement als vostres companys o amics sense perjudicar la vostra feina o estudi. Hem desenvolupat una col·lecció especial que farà riure a qualsevol i donarà un motiu per relaxar-se una mica enmig del procés ocupat de treball o de realització d\'una altra tasca. Per canviar el cursor del ratolí, només cal que baixeu el kit al dispositiu i seleccioneu el disseny que us agradi als paràmetres. Per exemple, podeu obtenir un cursor de forma estàndard, però en un estat invertit o una fletxa corbada per una ona. Aquesta forma no impedirà el procés de treball, però al mateix temps presentarà un estat d\'ànim meravellós i us posarà de bon humor. Canvieu la configuració de visualització del cursor segons el vostre estat d\'ànim o cada dia, i qualsevol tasca esdevindrà més interessant i agradable, i la vida quotidiana deixarà de causar emocions negatives. A més, aquests cursors es poden utilitzar fins i tot per a projectes seriosos: tenen colors neutres i no destaquen de l\'escriptori.',
    'startovyj_nabor_descr' => 'Els cursors de la col·lecció inicial són una barreja de formes i mides estàndard amb un aspecte brillant i inusual. Aquesta és una elecció excel·lent per a aquells que prefereixen les formes habituals, però volen aportar diversitat, originalitat i brillantor a la vida quotidiana. La col·lecció té un cursor de mà i una fletxa familiar en una varietat de variants: des del logotip de Google Chrome fins a emoticones, fins i tot podeu trobar aquí un drac oblidat fa temps amb cactus i nostàlgia. Demostrem que un cursor estàndard també pot ser interessant i atractiu. Diferents colors, formes, textures i un disseny interessant us ajudaran a triar el cursor al vostre gust o canviar-lo cada dia depenent de l\'estat d\'ànim o les tasques realitzades. Canviar els cursos del navegador és molt senzill: només cal instal·lar l\'extensió i descarregar la col·lecció al vostre dispositiu. Cursors divertits i interessants no només donaran color als dies laborables, sinó que també, per exemple, ajudaran a fer que qualsevol presentació sigui més interessant i, amb l\'ajuda de cursos especialment brillants, també cridaran l\'atenció sobre elements individuals de l\'informe.',
    'fortnite_descr' => 'Fortnite ha conquerit milions de persones arreu del món. Batalles emocionants, estratègia i tàctiques, aventures: ho ha absorbit absolutament tot el que agrada tant als jugadors. No ens vam poder quedar al marge i vam desenvolupar un conjunt de cursors a l\'estil del joc que agradaran no només als jugadors àvids, sinó fins i tot als que van sentir parlar de Fortnite per primera vegada. La icona del cursor de Fortnite és una imatge d\'un heroi o de la seva arma, treballada fins al més mínim detall. Aquí podeu trobar imatges de guineus i peixos, màscares d\'infern i cavallers negres, establir-vos una fletxa o una dalla amb punxes com a fletxa. Estem segurs que ningú romandrà indiferent! Ser esgarrifós o misteriós, original o humorístic: depèn de vosaltres. Trieu el vostre estil i seguiu-lo o configureu els cursors personalitzats a la configuració i canvieu el vostre paper cada dia. Ara serà molt més interessant i agradable realitzar fins i tot treballs tediosos i monòtons: el temps passarà ràpidament en companyia d\'imatges vívides i personatges preferits. O potser organitzareu competicions amb els companys, quin heroi serà més fort? L\'elecció és vostra!',
    'dota_2_descr' => 'DotA2 ara no és només un joc simple, és un món paral·lel real. En la realitat virtual a DotA2, pots fer-ho tot: viure, lluitar, desenvolupar-te, viatjar, fer amics. En general, tot és com a la vida, només que a vegades més interessant. Els cursos de Dota 2 són una continuació d\'una estratègia que et permetrà obtenir emocions vives i expressar-te al món real. Un nou conjunt de cursos inclou els personatges més destacats del joc, així com articles originals que no es poden confondre amb res més. Trieu un cursor que estigui més a prop teu, i embarca\'t en una aventura sense sortir del teu lloc de treball. Que avorrit és a vegades estar a la feina o realitzar tasques educatives, però amb els cursos del joc aquest problema ja no et confrontarà. Una mica d\'imaginació, un cursor brillant, i llestos, qualsevol negoci serà una aventura inusual, amb la qual no serà difícil i interessant. No cal reprimir-se. T\'agrada Dota? Llavors assegura\'t de descarregar la nostra col·lecció, selecciona un o diversos cursos aleatoris alhora, i cada nou dia esdevindrà més brillant, interessant i saturat.',
    'minecraft_descr' => 'Els cursos de ratolí en forma de fletxes i dits estàndard fa temps que han esdevingut avorrits per a tothom. Si sou fan de l\'inusual i original, llavors és el moment de canviar el cursor del ratolí i donar-li un disseny més interessant. Hem desenvolupat una col·lecció de cursos a l\'estil del mundialment famós joc Minecraft, on podeu trobar els personatges més impactants. Llop i guineu, Alex i Creeper, espasa de diamant i peix - podeu triar el que més us agradi o instal·lar un nou heroi cada dia. Aquests són cursos reals per a jugadors, i absolutament a tothom els agradaran - després de tot, qui de nosaltres no ha jugat a Minecraft? Estem segurs que simplement no existeixen. Abaix la vida quotidiana avorrida - és hora de submergir-se en aventures, cosa que es pot fer fins i tot sense sortir de la cadira de casa o de l\'oficina. Serà més interessant preparar un informe i reduir el saldo amb una pistola - qualsevol tasca esdevindrà més agradable i no us deixarà avorrir-vos al lloc. Descarregueu la nova col·lecció de cursos de Minecraft - configureu-los i fins i tot en el dia més gris i avorrit el vostre estat d\'ànim sempre serà el millor. I els companys envejaran els vostres resultats - és simplement impossible no fer la feina amb l\'ajuda dels valents herois de Minecraft.',
    'astrology-signs-zodiac' => 'Signes del zodíac',
    'sports-cars_short_descr' => 'Cotxes potents i amb estil construïts per a la velocitat i l\'agilitat',
    'spider-man' => 'Spider-Man',
    'astrology-signs-zodiac_short_descr' => 'Un conjunt de 12 símbols astrològics que representen trets de personalitat, energies còsmiques i patrons de vida.',
    'sports-cars' => 'Cotxes esportius',
    'sports-cars_descr' => 'Els cotxes esportius són vehicles d\'alt rendiment dissenyats per a una acceleració ràpida, una conducció precisa i una experiència de conducció emocionant. Des de cupès elegants fins a roadsters àgils, aquesta categoria presenta algunes de les màquines més icòniques construïdes per al plaer de la carretera o la pista. Ideal per als entusiastes que estimen la velocitat, el disseny i la potència. 🏎️🔥',
    'spider-man_short_descr' => 'Herois de l\'univers de Spider-Man',
    'starwars' => 'Star Wars',
    'spider-man_descr' => 'Una col·lecció de personatges i herois de l\'univers d\'Spider-Man. Inclou diverses versions de Spider-Man, aliats i estils únics de còmics, jocs i sèries d\'animació. Cada disseny reflecteix l\'agilitat, el coratge i la identitat visual que defineix el món d\'Spider-Man.',
    'astrology-signs-zodiac_descr' => 'Els signes del zodíac ♈♉♊♋♌♍♎♏♐♑♒♓ són dotze divisions simbòliques del cinturó celestial utilitzades en astrologia. Cada signe s\'associa amb dates específiques, elements (🌍 Terra, 🔥 Foc, 🌊 Aigua, 💨 Aire), planetes rectors i característiques de personalitat úniques. Els astròlegs utilitzen els signes del zodíac per interpretar el comportament, predir la compatibilitat i explorar els camins de la vida. Tant si ets un Lleó 🔥 apassionat com un Peixos 🌊 reflexiu, el teu signe t\'ofereix coneixements sobre el teu món interior. Aquesta categoria inclou els 12 signes, els seus significats i representacions visuals.',
    'starwars_descr' => 'Submergeix-te a la galàxia molt, molt llunyana amb aquesta col·lecció que inclou herois llegendaris, poderosos senyors sith, dròids, rebels i molt més. Des de cavallers jedi fins a soldats d\'assalt, cada icona dóna vida a l\'esperit de Star Wars en forma de cursor. Perfecte per als fans de cada trilogia. 🌌',
    'starwars_short_descr' => 'Personatges i símbols de l\'univers Star Wars',
    'glitter' => 'Purpurina',
    'glitter_short_descr' => 'Cursors brillants i espurnejants amb estil de purpurina ✨🌟',
    'roblox-2025' => 'Roblox 2025',
    'roblox-2025_short_descr' => 'Personatges de l\'última onada de Roblox 🕹️🚀',
    'glitter_descr' => 'Una col·lecció glamurosa de cursors inspirats en textures brillants i visuals lluminosos. Perfecte per a aquells que estimen una estètica brillant a la seva pantalla. Aquests cursors aporten brillantor, elegància i una mica de màgia a cada clic.',
    'roblox-2025_descr' => 'Una col·lecció nova del 2025 que presenta personatges icònics i moderns de Roblox. Inclou noobs clàssics, llegendes de terror i avatars preferits pels fans de jocs populars. Dissenyat amb un estil divertit i colorit perfecte per a nens i fans de Roblox de totes les edats.',
];
