<?php

return [
    'title' => 'Сursor Style - Condicions d\'ús del nostre producte',
    'descr' => 'Les condicions d\'ús s\'estableixen entre vostè i “Cursor Style” (“Servei”, “nosaltres” o “Servei”). Aquest servei s\'ofereix i està disponible per a usuaris de 13 anys o més només per a ús personal i no per a ús comercial.',
    'text' => '<h2> Condicions del servei </h2>
<h3> SI US PLAU, LLEGIU AQUESTOS TERMES I CONDICIONS ABANS D\'UTILITZAR EL LLOC WEB I L\'EXTENSIÓ. </h3>
<p> Aquests termes d\'ús s\'estableixen entre vosaltres i "Cursor Style" ("Servei", "nosaltres" o "Servei"). Els termes i condicions següents, juntament amb qualsevol document que inclouen expressament per referència (col·lectivament, aquests "Termes d\'ús"), regeixen el vostre accés i ús del lloc web cursor.style i les seves extensions de navegador, inclòs qualsevol contingut, funcionalitat i serveis que s\'ofereixen a través del nostre servei (conjuntament el “Servei”). </p>
<p> En utilitzar el lloc web o l\'extensió, accepteu i accepteu complir aquests Termes d\'ús. Si no esteu d\'acord amb aquests Termes d\'ús o amb la nostra <a href="/privacy"> Política de privadesa </a>, no hauríeu d\'accedir ni utilitzar el Lloc web i l\'Extensió. </p>
<p> Aquest servei s\'ofereix i està disponible per a usuaris de 13 anys o més només per a ús personal i no per a ús comercial. En utilitzar aquest Servei, declareu i garantitzé que teniu (I) 13 anys o més, (II) no teniu prohibit utilitzar els llocs web d\'acord amb la legislació aplicable i (III) utilitzeu el Servei només per a les vostres necessitats personals. Si no compliu aquests requisits, no hauríeu d\'accedir ni utilitzar el Servei. </p>
<p> Podem revisar i actualitzar aquests Termes d\'ús de tant en tant a la nostra discreció. Tots els canvis entren en vigor immediatament després de la seva publicació. El vostre ús continuat del Servei després de la publicació dels Termes d\'ús revisats significa que accepteu i accepteu els canvis. S\'espera que visiteu aquesta pàgina amb freqüència per mantenir-vos al corrent de qualsevol canvi, ja que us són vinculants. </p>
<p> Ens reservem el dret de retirar o modificar aquest lloc web i l\'extensió, qualsevol servei o material que proporcionem al lloc web i l\'extensió, a la nostra exclusiva discreció, sense previ avís. No garantim que el nostre lloc, l\'extensió o qualsevol contingut sempre estiguin disponibles o s\'interrompran. No serem responsables si per qualsevol motiu la totalitat o part del Servei no està disponible en cap moment o durant cap període. De tant en tant, podem restringir l\'accés a determinades parts del lloc web o de l\'extensió o a tot el Servei per als usuaris. </p>
<p> Sou responsable de prendre totes les mesures necessàries per assegurar-vos que teniu accés al Servei. Assegurar-se que totes les persones que accedeixen al Servei mitjançant la vostra connexió a Internet coneixen aquests Termes d\'ús i els compleixen. Per tal d\'accedir al Servei o a alguns dels recursos que ofereix, és possible que us demanin que proporcioneu determinada informació o altra informació. Accepteu que tota la informació que ens proporcioneu mitjançant aquest Servei o d\'una altra manera, inclosa, entre d\'altres, l\'ús de qualsevol funció interactiva del Servei, es regeix per la nostra <a href="/privacy"> Política de privadesa </a>, i accepteu totes les accions que fem pel que fa a la vostra informació. d\'acord amb la nostra <a href="/privacy"> Política de privadesa </a>. </p>
<p> Heu de tenir especial cura en introduir informació personal al Servei en un ordinador públic o compartit perquè altres persones no puguin veure ni registrar la vostra informació personal. El lloc web, l\'extensió i tots els seus continguts, funcions i característiques (incloent, entre d\'altres, tota la informació, l\'extensió, el text, les imatges, les imatges i els cursor, així com el seu disseny, selecció i ubicació) pertanyen al "Cursor Style", els seus llicenciadors o altres proveïdors d\'aquests materials estan protegits per drets d\'autor, marques comercials, patents, secrets comercials i altres lleis de propietat intel·lectual o drets de propietat. </p>
<p> Aquests Termes d\'ús us permeten utilitzar els llocs web només per al vostre ús personal i no comercial. No heu de reproduir, distribuir, modificar, crear obres derivades, republicar, descarregar, emmagatzemar ni transmetre cap material al nostre lloc web, excepte en els casos següents: podeu utilitzar-lo per a necessitats personals, podeu imprimir o descarregar una còpia d\'una quantitat raonable de pàgines del lloc web i de l\'Extensió o del seu contingut per a ús personal i no comercial, i no per a una reproducció, publicació o distribució posteriors. </p>
<p> No heu de modificar les còpies de cap material d\'aquest lloc o extensió i el seu contingut. Suprimir o modificar qualsevol avís de drets d\'autor, marca comercial o altre avís de propietat de les còpies d\'aquest lloc i l\'extensió. No heu d\'accedir ni utilitzar per a cap propòsit comercial cap part dels llocs web o extensions, així com cap servei o material disponible a través del lloc web o l\'Extensió. </p>
<p> Si voleu utilitzar algun material als llocs web o extensions, diferents dels que s\'enumeren en aquesta secció, envieu una sol·licitud a la pàgina d\'assistència de la Chrome Web Store. </p>
<p> Si imprimiu, copieu, modifiqueu, descarregueu o utilitzeu o proporcioneu d\'una altra manera accés a qualsevol altra persona a qualsevol part del lloc web o de l\'extensió incomplint els Termes d\'ús, el vostre dret d\'utilitzar el lloc web i l\'extensió finalitza immediatament i ha de, a la nostra discreció, retornar o destruir qualsevol còpia dels materials que tingueu. Qualsevol ús del lloc web de l\'extensió que no estigui expressament permès per aquests Termes d\'ús incompleix aquests Termes d\'ús i pot infringir els drets d\'autor, les marques comercials i altres lleis. </p>
<p> El nom "Cursor Style", el logotip "Cursor Style" i tots els noms, logotips, imatges, cursor i noms de servei, dissenys i eslògans associats són marques comercials de "Cursor Style" o dels seus afiliats o llicenciadors. No heu d\'utilitzar aquestes marques sense el permís previ per escrit del Servei. Tots els altres noms, logotips, noms de productes i serveis, dissenys i eslògans del lloc web i de l\'extensió són marques comercials dels seus respectius propietaris. Només podeu utilitzar el Servei amb finalitats legítimes i d\'acord amb aquests Termes d\'ús. </p>
<h3> Accepteu NO utilitzar el Servei: </h3>
<ul>
<li> De cap manera que infringeixi les lleis o regulacions federals, regionals, locals o internacionals aplicables (incloses, entre d\'altres, les lleis relatives a l\'exportació de dades o programari a Rússia i altres països). </li >
<li> Amb la finalitat d\'explotació, dany o intents d\'utilitzar o perjudicar menors, exposant-los a contingut inadequat, sol·licitant informació que els identifiqui o d\'una altra manera. </li >
<li> Per enviar, rebre conscientment, descarregar, utilitzar o reutilitzar qualsevol material que no compleixi aquests Termes d\'ús. </li >
<li> Transmetre o comprar l\'enviament d\'anuncis o materials promocionals sense el nostre consentiment previ per escrit, incloses les "cartes no sol•licitades", "cartes en cadena" o "spam" o qualsevol altra oferta similar. </li >
<li> Per suplantar o intentar suplantar un empleat de “Cursor Style”, un altre usuari o qualsevol altra persona o organització (incloent, entre d\'altres, l\'ús d\'adreces de correu electrònic o àlies associats a qualsevol dels anteriors). </li >
<li> Participació en qualsevol altra acció que limiti o impedeixi l\'ús del Servei o l\'ús de ningú, o que, com determinem, pugui perjudicar el Servei o els usuaris del Servei o fer-los responsables. </li > </ul>
<h3> A més, accepteu NO: </h3>
<ul>
<li> Utilitzar el Servei de cap manera que pugui desactivar, sobrecarregar, danyar o degradar el funcionament del lloc, expandir o interferir amb l\'ús del Servei per qualsevol altra part, inclosa la seva capacitat per participar en accions en temps real mitjançant el Servei. </li >
<li> Utilitzar cap eina d\'automatització, procés o mitjà per accedir al Servei per a qualsevol propòsit, inclòs el seguiment o la còpia de qualsevol material del Servei. </li >
<li> Utilitzar cap procés manual per rastrejar ni copiar cap material del Servei o per a cap altre propòsit no autoritzat sense el nostre consentiment previ per escrit. </li >
<li> Utilitzar cap dispositiu, programari o procediment que interfereixi amb el funcionament normal del Servei. </li >
<li> Introduir qualsevol virus, cavall de Troia, cuc, bomba lògica o altres materials nocius o tecnològicament nocius. </li >
<li> Intentar obtenir accés no autoritzat, interferir, danyar o interrompre qualsevol part del Servei, el servidor en què s\'emmagatzema el Servei o qualsevol servidor, ordinador o base de dades connectats al Servei. </li >
<li> Atacar un Servei mitjançant un atac de denegació de servei o un atac de denegació de servei distribuït. </li > </ul>
<p> La informació proporcionada al Servei o a través d\'ell es proporciona només amb finalitats informatives generals. No garantim l\'exactitud, la integritat o la utilitat d\'aquesta informació. Confieu en aquesta informació només al vostre propi risc. Renunciem a tota responsabilitat i responsabilitat derivada de la confiança que tingueu en aquests materials, qualsevol altre visitant del Servei o qualsevol persona que pugui ser informada de qualsevol contingut. </p>
<p> Aquest Servei inclou contingut proporcionat per tercers, inclosos materials proporcionats per altres usuaris i llicenciadors, sindicadors, agregadors i / o serveis d\'informes de tercers. Totes les declaracions i / o opinions expressades en aquests materials, així com tots els articles i respostes a preguntes i altres continguts, excepte el contingut proporcionat pel Servei, són només les opinions i responsabilitats de la persona o organització que proporciona aquests materials. Aquests materials no reflecteixen necessàriament les opinions del Servei. No som responsables davant de vosaltres ni de cap tercer del contingut o l\'exactitud de cap material proporcionat per tercers. </p>
<p> Podem actualitzar el contingut del Servei de tant en tant, però el seu contingut no és necessàriament complet ni actual. Qualsevol material del Servei pot estar desactualitzat en qualsevol moment i no estem obligats a actualitzar aquest material. Podem actualitzar, modificar, modificar informació i contingut al lloc web i a l\'Extensió, fer qualsevol canvi i actualització segons la nostra pròpia decisió. </p>
<p> Tota la informació que recollim en aquest Servei està subjecta a la nostra Política de privadesa. En utilitzar el Servei, accepteu totes les accions que prenem en relació amb la vostra informació d\'acord amb la <a href="/privacy"> Política de privadesa </a>. </p>
<p> També es poden aplicar termes addicionals a determinades parts, serveis o funcions del Servei. Tots aquests termes i condicions addicionals s\'incorporen aquí com a referència a aquests Termes d\'ús.
Podeu enllaçar al nostre lloc web o extensió si ho feu de manera honesta i legal i no danyeu la nostra reputació ni l\'utilitzeu, però no heu d\'establir l\'enllaç de manera que ofereixi cap forma d\'associació, suport o aprovació per part nostra sense el nostre consentiment per escrit. </p>
<p> El servei conté enllaços a altres llocs i recursos proporcionats per tercers, aquests vincles només es proporcionen per a la vostra comoditat. Això inclou enllaços continguts en anuncis, inclosos bàners publicitaris i enllaços patrocinats. No controlem el contingut d\'aquests llocs o recursos i no som responsables d\'ells ni de cap pèrdua o dany que pugui resultar del seu ús. Si decidiu accedir a qualsevol lloc web de tercers associat a aquest Servei, ho feu al vostre propi risc i d\'acord amb les condicions d\'ús d\'aquests llocs web. Ens reservem el dret de revocar el permís per enllaçar sense previ avís. </p>
<p> Enteneu que no podem i no garantim ni garantim que els fitxers disponibles per descarregar a través d\'Internet o als llocs web no contindran virus ni cap altre codi maliciós. Sou responsable de la implementació de procediments i punts de control suficients per satisfer els vostres requisits especials de protecció antivirus i l\'exactitud de l\'entrada i la sortida de dades, així com de mantenir mitjans externs al nostre lloc per recuperar les dades perdudes. NO SEREM RESPONSABLES DE CAP DANYS O LESIONS CAUSATS ATAC D\'ORDENADOR, virus o un altre malware tecnològic OBTINGUT A TRAVÉS DEL SERVEI, O DESCARREGANT QUALSEVOL MATERIAL PUBLICAT A AQUESTA, O QUALSEVOL LLOCS WEB, RELACIONATS, POT INFEIR O DANAR EL SEU EQUIP D\'ORDINADOR, PROGRAMARI D\'ORDINADOR, DADES. </p>
<p> UTILITZEU EL SERVEI, EL SEU CONTINGUT I QUALSEVOL SERVEI O ARTICLE OBTINGUTS A TRAVÉS DELS SERVEIS AL SEU ÚNIC RISC. EL SERVEI, ELS SEUS CONTINGUTS I QUALSEVOL SERVEI O ARTICLE OBTINGUTS A TRAVÉS DEL LLOC WEB I EXTENSIÓ ES PROPORCIONEN EN CONDICIONS “TAL COM SÓN” I “SEGONS DISPONIBILITAT”, SENSE CAP GARANTIA. QUALSEVOL PERSONA ASSOCIADA AL SERVEI NO PROPORCIONA CAP GARANTIA NI REPRESENTACIÓ PEL QUE FA A LA COMPLETESA, SEGURETAT, FIABILITAT, QUALITAT, PRECISIÓ O ACCESSIBILITAT DEL SERVEI. SENSE LIMITACIÓ ANTERIOR, CAP “CURSOR STYLE” NI RELACIONAT AMB REPRESENTANTS DE “CURSOR STYLE” NO GARANTEIX QUE EL LLOC, L\'EXTENSIÓ, EL SEU CONTINGUT O QUALSEVOL REPARACIÓ HAGIN D\'ESTAR PRÈVIAMENT DISPONIBLES QUE LA NOSTRA EXTENSIÓ, UN LLOC O UN SERVIDOR EN QUÈ ES SITUA, SERAN SENSE VIRUS O ALTRES COMPONENTS NOCIONS O AQUEST LLOC WEB O QUALSEVOL SERVEI O ARTICLES REALITZATS, PREFERITS.
<p> En cap circumstància el SERVEI, ELS SEUS AFILIATS O LLICENCIADORIS, SERVEIS, EMPLEATS, AGENTS, FUNCIONARIS O DIRECTORS SERAN RESPONSABLES DE DANYS DE CAP TIPUS, NOSALTRES SERVEI A QUALSEVOL RESPONSABILITAT. O AQUEST A RES DE LLOCS WEB O QUALSEVOL SERVEI O ARTICLES OBTINGUTS AL SERVEI O A ALTRES LLOCS WEB, INCLOSOS QUALSEVOL DANYS DIRECTES, ESPECIALS O CONSEQUENTS, INCLOSOS LESIONS PERSONALS, trastorns emocionals, DANYS O ESTALVIS ESPERATS, PÈRDUA D\'ÚS, DADES O ALTRES CONDICIONS. LA DEFINICIÓ NO AFECTA CAP RESPONSABILITAT QUE NO ES POGUÉS EXCLOURE O LIMITAR D\'ACORD AMB LA LLEI APLICABLE QUE POGUÉS INCLOURE FRAU. </p>
<p> Accepteu protegir, indemnitzar i difondre el “Cursor Style”, els seus afiliats, llicenciadors i proveïdors de serveis, així com els seus respectius funcionaris, directors, empleats, contractistes, agents, llicenciadors, proveïdors, cessionaris i de qualsevol reclamació i passius, pèrdua de sentències judicials, costos, despeses o comissions (inclosos els honoraris d\'advocat) derivats de o en relació amb la vostra violació d\'aquests Termes d\'ús o ús del Servei, incloent-hi la renúncia de qualsevol ús del contingut, serveis i productes del lloc web o de les extensions, excepte el que es disposa expressament en aquests Termes d\'ús, o el vostre ús de qualsevol informació rebuda del Servei. </p>
<p> Si alguna disposició d\'aquests Termes d\'ús es considera invàlida, il·legal o inaplicable per un tribunal o altre tribunal de jurisdicció competent per qualsevol motiu, aquesta disposició s\'ha de derogar o limitar mínimament, de manera que la resta de les disposicions dels Termes d\'ús continuïn al màxim. Els Termes d\'ús, la nostra Política de privadesa i les condicions per registrar esdeveniments constitueixen l\'acord únic i complet entre vosaltres i el "Cursor Style" respecte del Servei i substitueixen tots els acords, acords, representacions i garanties anteriors i simultanis, tant escrits com orals, pel que fa al Servei. </p>
<p> Totes les ressenyes, comentaris, sol·licituds d\'assistència tècnica i altres missatges relacionats amb el Servei s\'han d\'adreçar a la pàgina d\'assistència de "Cursor Style" a la Chrome Web Store. </p> ',
];
