<?php

return [
    'title' => 'Cursor Style - Kebijakan Privasi',
    'descr' => 'Di “Cursor Style,” tersedia di cursor.style atau melalui ekstensi Chrome, salah satu prioritas utama kami adalah privasi pengunjung kami. Di bagian inilah kami akan berbicara tentang semua aspek bekerja dengan ekstensi.',
    'text' => '<h2> Kebijakan Privasi </h2>
                <p> Di Cursor Style, tersedia di <a href="https://cursor.style"> cursor.style </a> atau melalui ekstensi Chrome, salah satu prioritas utama kami adalah privasi pengunjung kami. Dokumen Kebijakan Privasi ini berisi jenis informasi yang dikumpulkan dan dicatat oleh situs web cursor.style, dan cara kami menggunakannya. Jika Anda memiliki pertanyaan tambahan atau membutuhkan informasi lebih lanjut tentang Kebijakan Privasi kami, jangan ragu untuk menghubungi kami. </p>
                <p> Ekstensi "Cursor Style" dan situs web mengikuti prosedur standar untuk menggunakan file log. File-file ini mendaftarkan pengunjung ketika mereka mengunjungi situs web atau menggunakan ekstensi kami. Semua perusahaan hosting melakukan ini dan merupakan bagian dari analitik layanan hosting. Informasi yang dikumpulkan melalui file log termasuk alamat Internet Protocol (IP), jenis browser, Internet Service Provider (ISP), cap tanggal dan waktu, halaman transisi / keluar, dan kemungkinan jumlah klik. Mereka tidak terkait dengan informasi pribadi yang dapat diidentifikasi. Tujuan dari informasi ini adalah untuk menganalisis tren, mengelola situs dan memperluas, melacak pergerakan pengguna di situs dan memperluas, dan mengumpulkan informasi demografis. </p>
                <p> Seperti situs lainnya, cursor.style menggunakan cookie. Cookie ini digunakan untuk menyimpan informasi, termasuk preferensi pengunjung dan halaman di situs web yang dikunjungi atau dikunjungi pengunjung. Informasi ini digunakan untuk mengoptimalkan pengalaman pengguna dengan menyesuaikan konten halaman web kami berdasarkan jenis browser pengunjung dan / atau informasi lainnya. Kami juga menggunakan iklan pihak ketiga di cursor.style untuk mendukung proyek dan mendukung situs web kami. Beberapa pengiklan ini dapat menggunakan teknologi seperti cookie dan suar web saat mereka beriklan di situs web kami, yang juga akan mengirimkan pengiklan ini (misalnya, Google melalui program Google AdSense) informasi, termasuk alamat IP Anda, penyedia Internet Anda, browser yang Anda gunakan untuk mengunjungi situs kami, dan dalam beberapa kasus, jika Anda telah menginstal Flash. Ini biasanya digunakan untuk tujuan penargetan geografis (misalnya, menampilkan iklan untuk penjualan barang di kota Anda) atau untuk menampilkan iklan tertentu berdasarkan situs web tertentu yang dikunjungi (misalnya, menampilkan pengumuman pembelian kepada mereka yang sering mengunjungi situs belanja). </ P >
                <p> Anda dapat menonaktifkan atau secara selektif menonaktifkan cookie kami atau pihak ketiga di pengaturan browser atau dengan mengelola pengaturan di program seperti Kaspersky, dll. Namun, ini dapat memengaruhi cara Anda berinteraksi dengan situs kami, serta dengan situs lain. Ini mungkin termasuk ketidakmampuan untuk masuk ke layanan atau program, seperti masuk ke forum atau akun. </p>
<p> Google adalah salah satu penyedia pihak ketiga di situs kami. Itu juga menggunakan cookie, yang dikenal sebagai cookie DART, untuk menayangkan iklan kepada pengunjung situs kami berdasarkan kunjungan mereka ke cursor.style dan situs lain di Internet. Namun, pengunjung dapat memilih untuk tidak menggunakan cookie DART dengan mengunjungi kebijakan privasi Jaringan Periklanan dan Konten Google di <a href="https://policies.google.com/technologies/ads"> alamat berikut </a>. Beberapa pengiklan di situs web kami dapat menggunakan cookie dan suar web. Setiap mitra periklanan kami memiliki kebijakan privasi sendiri untuk kebijakannya mengenai data pengguna. Anda dapat membaca lebih lanjut tentang Kebijakan Privasi mereka <a href="https://policies.google.com/technologies/ads"> di sini </a>. </p>
                <p> Situs web kami menggunakan Google Analytics, layanan analisis web dari Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com (“Google Analytics” atau “Google”). Google Analytics menggunakan cookie yang disimpan di komputer Anda untuk memfasilitasi analisis penggunaan situs web Anda. Informasi yang dihasilkan oleh cookie ini, seperti waktu, tempat, dan frekuensi kunjungan Anda ke situs web kami, termasuk alamat IP Anda, ditransfer ke lokasi Google di AS dan disimpan di sana. Google juga dapat mentransfer informasi ini ke pihak ketiga jika diperlukan oleh hukum atau jika pihak ketiga memproses data ini atas nama Google. Google menyatakan bahwa ia tidak akan pernah mengaitkan alamat IP Anda dengan data Google lainnya. Anda dapat mencegah pengaturan cookie dengan mengubah pengaturan perangkat lunak browser Anda yang sesuai, seperti yang ditentukan dalam Kebijakan Privasi ini. Namun, Anda harus menyadari bahwa dengan cara ini Anda tidak akan dapat sepenuhnya menggunakan semua fungsi situs web kami. </p>
                <p> Google Analytics juga menggunakan gambar elektronik yang dikenal sebagai suar web (terkadang disebut GIF satu piksel) dan digunakan dengan cookie untuk mengumpulkan statistik agregat untuk menganalisis penggunaan situs kami.
Anda dapat menemukan informasi lebih lanjut tentang cara menginstal add-on browser yang Anda tautkan di atas <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> tautan </a>.
Situs ini menggunakan Google Tag Manager. Layanan ini memungkinkan Anda untuk mengelola tag situs melalui antarmuka. Google Tag Manager hanya mengimplementasikan tag. Ini berarti bahwa cookie tidak diatur dan tidak ada data pribadi yang direkam. Google Tag Manager meluncurkan tag lain, yang pada gilirannya dapat merekam data. Namun, Google Tag Manager tidak memiliki akses ke data ini. Jika tag telah dinonaktifkan di tingkat domain atau cookie, mereka disimpan untuk semua tag pelacakan, jika diimplementasikan menggunakan Google Tag Manager. Anda dapat mempelajari lebih lanjut tentang Google Tag Manager dengan mengunjungi <a href="http://www.google.com/tagmanager/use-policy.html"> tautan </a>. </p>
<p> Anda dapat membiasakan diri dengan daftar ini untuk menemukan Kebijakan Privasi untuk masing-masing mitra periklanan "Cursor Style". Server iklan pihak ketiga atau jaringan iklan menggunakan teknologi seperti cookie, JavaScript atau suar web, yang digunakan dalam iklan dan tautan masing-masing, yang ditampilkan di “Cursor Style” dan dikirim langsung ke browser pengguna. Mereka secara otomatis mendapatkan alamat IP Anda ketika ini terjadi. Teknologi ini digunakan untuk mengukur efektivitas kampanye periklanan mereka dan / atau untuk mempersonalisasi konten periklanan yang Anda lihat di situs web yang Anda kunjungi. Harap dicatat bahwa “Cursor Style” tidak memiliki akses atau kendali atas cookie yang digunakan oleh pengiklan pihak ketiga ini. Kebijakan privasi Cursor Style tidak berlaku untuk pengiklan atau situs web lain. Oleh karena itu, kami merekomendasikan agar Anda meninjau kebijakan privasi yang relevan dari server iklan pihak ketiga ini untuk informasi lebih lanjut. Ini mungkin termasuk metode dan instruksi mereka tentang cara memilih keluar dari opsi tertentu. Anda dapat menemukan tautan ke Kebijakan Privasi Pihak Ketiga ini di atas atau di situs web layanan pihak ketiga ini. </p>
                <p> Anda dapat menonaktifkan cookie di pengaturan browser Anda. Untuk mempelajari lebih lanjut tentang pengelolaan cookie di browser web tertentu, Anda dapat menemukannya di situs web browser masing-masing. Bagian lain dari prioritas kami adalah menambahkan perlindungan anak saat menggunakan Internet. Kami mendorong orang tua dan wali untuk mengamati, berpartisipasi dan / atau memantau dan mengarahkan aktivitas mereka di Internet. "Cursor Style" secara sadar tidak mengumpulkan informasi pribadi dari anak-anak di bawah usia 13 tahun. Jika Anda berpikir anak Anda telah memberikan informasi tersebut di situs web kami, kami sangat menyarankan Anda untuk segera menghubungi kami dan kami akan melakukan yang terbaik untuk segera menghapus informasi tersebut dari catatan kami. Kebijakan Privasi ini hanya berlaku untuk aktivitas online kami dan berlaku untuk pengunjung ke situs web kami terkait dengan informasi yang mereka bagikan dan / atau kumpulkan di “Cursor Style”. Kebijakan ini tidak berlaku untuk informasi apa pun yang dikumpulkan secara offline atau melalui saluran selain situs web ini. </p>
                <p> Anda dapat membaca lebih lanjut tentang penggunaan cookie di Layanan kami dalam <a href="/cookie-policy"> Kebijakan Cookie </a> kami. </p> ',
];
