<?php

return [
    'halo_descr' => 'Halo è un franchise di media di fantasia di combattimento creato da Bungie. Basato sulla trilogia originale di videogiochi sparatutto in prima persona. La trama ruota attorno agli eventi che si svolgono nella vita di Master Chief, uno di un gruppo di super-soldati in codice Spartans, e del suo compagno, l\'intelligenza artificiale Cortana. Il successo dei giochi ha portato all\'espansione del franchise in altri media: l\'universo di Halo attualmente comprende molti libri, graphic novel, fumetti, cortometraggi, animazioni e film.',
    'halo_short_descr' => 'Tocca il cursore manufatto, forse sei tu l\'eletto',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'Le bambole LOL Surprise si sono innamorate dei bambini e hanno conquistato i loro cuori fin dai primi minuti. E questo non sorprende, perché tale successo si basa su un mistero, l\'attesa di un miracolo, una piacevole sorpresa, che delizia non solo i bambini, ma anche i loro genitori. Il segreto del regalo viene rivelato al bambino solo dopo lo spacchettamento finale. In ogni caso, le bambole LOL sono un design accattivante, intrighi, un gran numero di accessori sorprendenti e realistici e piccole cose piacevoli, così come la massima qualità della produzione e la cura dei dettagli del giocattolo.',
    'lol_surprise_short_descr' => 'Simpatiche bambole per intenditori di bellissime sorprese',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'La serie ruota attorno a un concorso in cui 456 giocatori, tutti con profondi debiti finanziari, rischiano la vita per giocare a una serie di giochi mortali per bambini, con la possibilità di vincere un premio di un miliardo. All\'interno, un allettante premio attende con in gioco poste alte e mortali. Il titolo della serie deriva da un gioco per bambini coreano con lo stesso nome. Hwang ha concepito l\'idea basata sulle sue stesse difficoltà economiche all\'inizio della vita, così come sulla disparità di classe in Corea del Sud e sul capitalismo.',
    'squid_game_short_descr' => 'Scegli la faccia del giocatore giusto quando fai all-in',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter è il protagonista di una serie di romanzi della scrittrice inglese JK Rowling. L\'undicesimo compleanno di Harry, apprende di essere un mago e destinato a frequentare la Scuola di Magia e Stregoneria di Hogwarts, dove praticherà la magia sotto la guida del preside Albus Silente e degli altri professori. Harry scopre anche di essere già famoso in tutta la comunità magica del romanzo, e che il suo destino è legato a quello di Voldemort, un potente mago oscuro.',
    'harry_potter_short_descr' => 'Cosa farai con una bacchetta magica dalla collezione di cursori di Harry Potter',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics è una casa editrice di fumetti nota per aver creato noti supereroi come Spider-Man, Iron Man, Captain America, Hulk, Thor, gli Avengers, i Guardiani della Galassia, gli X-Men, i Fantastici Quattro e Deadpool. I cattivi più noti della Marvel includono Goblin, Teschio Rosso, Loki, Thanos, Ultron, Doctor Doom e Magneto. Marvel Comics e DC Comics hanno collaborato a diversi progetti crossover insieme e hanno anche co-fondato l\'editore intenzionalmente di breve durata Amalgam Comics.',
    'marvel_comics_short_descr' => 'Il supereroe vive in ognuno di noi - scegli il tuo',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Bentornato nel Regno dei Cookie in Cookie Run: Kingdom di Devsisters, l\'adorabile gioco di ruolo strategico ambientato nell\'universo di Cookie Run. Ora che GingerBrave è scappato dal forno della strega malvagia, è tempo per lui di costruire una squadra di Cookie e intraprendere una missione per ricostruire il Regno dei Cookie caduto. Scopri la verità dietro la caduta del Regno e metti insieme una squadra dei Cookie più potenti del Regno per sconfiggere le forze oscure che vogliono impedire a GingerBrave di adempiere al suo destino.',
    'cookie_run_kingdom_short_descr' => 'Piccoli guerrieri appena usciti dal forno',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact è un gioco di avventura open world. Questo significa che un nuovo, delizioso paesaggio ti aspetta dall\'altra parte del fiume o della montagna, devi solo usare la tua energia saggiamente. Se ti imbatti in una fata errante o in uno strano meccanismo, osa e cerca di svelare il loro mistero. Ma cosa promettono - guai o una piacevole sorpresa - solo tu puoi scoprirlo! Sul vasto continente di Teyvat, visiterai sette regni, troverai compagni con varie abilità e combatterai contro potenti nemici alla ricerca di una persona cara scomparsa.',
    'genshin_impact_short_descr' => 'Diventa il Maestro Elementale dei Sette Regni',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Quando un\'antica profezia si avvera e il regno precipita nell\'abbraccio dell\'inverno, tre eroi senza paura - la principessa Anna, il coraggioso Kristoff e la sua fedele renna Sven - vanno sulle montagne per trovare la sorella di Anna, Elsa, che può rimuovere l\'incantesimo gelido dal paese. Lungo il cammino, li attendono molte difficili sorprese ed eccitanti avventure. Incontri con troll mistici, l\'incontro con un affascinante pupazzo di neve di nome Olaf, vette montuose più ripide dell\'Everest e molta magia. Gli eroi devono resistere ai potenti elementi per salvare il regno e coloro che sono cari a loro.',
    'frozen_short_descr' => 'Rompi il ghiaccio facilmente con la collezione di cursori di Frozen',
    'frozen' => 'Frozen',
    'stranger_things_descr' => 'Sono passati poco più di sei mesi dalla finale della terza stagione. Joyce, Will, Undici e Jonathan si sono trasferiti in California, dove la ragazza viene vittimizzata a scuola. Il resto inizia a combattere un nuovo mostro proveniente da un mondo parallelo apparso a Hawkins. È stato chiamato Vecna ​​in onore del personaggio del gioco da tavolo Dungeons & Dragons. Influisce psicologicamente sugli adolescenti, poi si intrufola mentalmente nella testa e uccide. In parallelo, Joyce e Murray apprendono che Jim Gopper è vivo e lo inseguono in una prigione sovietica in Kamchatka. E Undici dovrà tornare e aumentare i suoi poteri, ma anche conoscere il suo ruolo importante nella creazione dello stesso mostro a Gokins.

Gli sceneggiatori non hanno cambiato le tattiche della trama che hanno apprezzato nelle ultime stagioni. Nella quarta stagione, hanno diviso il grande gruppo di personaggi principali in gruppi, hanno ideato compiti difficili per loro e alla fine hanno costruito le loro storie insieme in un finale sorprendente. Ti offriamo di comprendere in dettaglio tutte queste avventure con l\'aiuto della collezione di cursori di Stranger Things.',
    'stranger_things_short_descr' => 'Cosa succederà dopo? - Cursori di Stranger Things 4',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars è una modalità originale che è apparsa per la prima volta in Minecraft. Il compito dei giocatori era per l\'utente proteggere la propria base e il letto.

Roblox porta ogni giorno giochi più eccitanti e BedWars non fa eccezione. E il punto è che, se ami Bed Wars e ti difendi nella tua stanza, questo è il titolo che fa per te perché ti riporta all\'infanzia, anche se questa volta in digitale.

Tutto quello che devi fare è difendere il tuo letto dagli attaccanti con il tuo partner. Entri in una lobby, scegli con chi giocare, e voilà, è solo una questione di protezione.

Naturalmente, quando si tratta di difesa, avrai alcuni problemi e ci sono certe risorse, oggetti e articoli che ti aiuteranno a vincere. Ad esempio, skin esclusive che troverai nella collezione di cursori di Bed Wars.',
    'roblox_bed_wars_short_descr' => 'Proteggi il tuo letto con i cursori di Roblox Bed Wars',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'Il giorno del compleanno di Naruto Uzumaki, un demone leggendario, la Volpe a Nove Code, attaccò un villaggio chiamato Konoha. Il Quarto Hokage, al costo della sua vita, salvò il villaggio sigillando il demone nel neonato Naruto, condannandolo inconsapevolmente a una vita di odio dai suoi compaesani.
Nonostante la sua mancanza di talento in molte aree del ninjutsu, l\'irrequietezza e la superbia, Naruto ha il sogno di diventare Hokage, il ninja più forte del villaggio. Desiderando il riconoscimento che non ha avuto, lavora sodo e si allena insieme ai suoi compagni di squadra Sasuke Uchiha e Sakura Haruno, così come il suo mentore Kakashi Hatake. Lui e i suoi compagni dovranno passare attraverso molte cose per raggiungere i loro sogni tanto cari: battaglie, amore, amicizia, tradimento, sete di potere. Una collezione di cursori anime di Naruto ti aiuterà a navigare nel tuo cammino!',
    'naruto_anime_short_descr' => 'Percorri il tuo cammino ninja con i cursori anime di Naruto',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'L\'azione si svolge durante l\'era Taisho. Fin dai tempi antichi, ci sono state voci secondo cui demoni umanoidi vivono nella foresta, si nutrono di persone e camminano di notte, alla ricerca di una nuova vittima. Ma... è solo una leggenda, giusto?..

Tanjiro Kamado è il figlio maggiore della famiglia, che ha perso il padre e si è preso cura della sua famiglia. Un giorno va in una città vicina per vendere carbone. Tornando la mattina, il ragazzo scopre un quadro terribile di fronte a sé: tutti i parenti sono stati brutalmente uccisi e l\'unica sopravvissuta è Nezuko, una sorella minore trasformata in demone, ma che non ha ancora perso tutta la sua umanità.

Da questo momento, Tanjiro e Nezuko iniziano un lungo e pericoloso viaggio, in cui il ragazzo intende trovare l\'assassino e trovare un modo per curare la sorella. Ma i bambini sono in grado di superare tutte le difficoltà e tornare a casa? Sai già la risposta, e se no - piuttosto imposta i cursori Demon Slayer, con personaggi di uno dei manga più popolari.',
    'demon_slayer_anime_short_descr' => 'Cursori di Demon Slayer - per veri cacciatori notturni',
    'demon_slayer_anime' => 'Anime di Demon Slayer',
    'bts_descr' => 'I BTS sono un gruppo di sette membri sotto BigHit Music. Hanno debuttato il 13 giugno 2013 con il singolo "No More Dream". In Giappone, hanno fatto il loro debutto il 24 dicembre 2014 con l\'album in studio Wake Up.

Il nome del gruppo deriva dall\'espressione coreana Bangtan Sonyeondan, che significa "scout ragazzi a prova di proiettile". Secondo J Hope, il nome significa il desiderio della band di bloccare gli stereotipi, le critiche e le aspettative che sono rivolte agli adolescenti come proiettili.

La collezione di cursori dedicata al gruppo include tutti i membri del gruppo, qui il cursore di Kim Nam Joon (alias RM), il cursore di Kim Seok Jin (Jin), il cursore di Min Yoongi (Suga), il cursore di Jung Ho Suk (J-Hope), il cursore di Park Ji Min (Jimin), il cursore di Kim Tae Hyun (V) e il cursore di Jeon Jungkook (Jungkook).',
    'bts_short_descr' => 'Incontra i tuoi idoli con i cursori dei BTS',
    'bts' => 'BTS',
    'miraculous_descr' => 'Miraculous: Le storie di Ladybug e Chat Noir, meglio conosciuto come Miraculous Ladybug e Chat Noir, sono le avventure dei supereroi del cartone animato su due compagni di classe che, sotto le maschere, interpretano il ruolo dei difensori di Parigi da un cattivo che in ogni episodio inventa un nuovo modo per danneggiare la città. Miraculous è realizzato in Francia utilizzando CGI e animazione. Miraculous non è solo una serie animata, ma anche una raccolta di fumetti pubblicati in tutto il mondo. La serie è molto amata dal giovane pubblico.

L\'azione si svolge a Parigi, dove Marinette e Adrian sono studenti delle scuole superiori in una scuola moderna. È stato loro affidato il ruolo di diventare i prescelti nella lotta contro il male, salvando la loro città natale. Il loro obiettivo è proteggere le persone dagli Akuma. Queste piccole creature a forma di farfalla sono in grado di abitare una persona e trasformarla in un cattivo.

Marinette può trasformarsi in una coccinella e Adrian in un Chat Noir, ma sorprendentemente, lavorando in coppia, non si riconoscono sotto le maschere dei supereroi.

Aiuta Chat Noir e Ladybug a salvare Parigi con i nostri cursori con i tuoi personaggi preferiti. Quale personaggio sceglierai per il cursore? Sarà un cursore Miraculous Ladybug, o forse l\'adorabile piccola Ladybug di Tikki o il cursore di Chat Noir? O forse un cursore di Queen Bee con Rena Rouge? La scelta è tua!',
    'miraculous_short_descr' => 'Unisciti ai ranghi dei supereroi con la collezione di cursori di Ladybug e Chat Noir',
    'miraculous' => 'Miraculous: Le storie di Ladybug e Chat Noir',
    'talking_tom_descr' => 'La serie segue la vita quotidiana di Talking Tom e dei suoi amici. Tom e il suo socio in affari nerd Ben sviluppano costantemente app mobili e altre invenzioni per raggiungere fama e fortuna e cercano di farsi vedere dal mondo, ma questo si ritorce sempre contro. La fidanzata di Tom, Angela, cerca di diventare una cantante, qualunque cosa faccia per raggiungerlo. Il vicino di Tom, Ginger, si intromette molto spesso per fare scherzi con la malizia in serbo. Lo stupido migliore amico e coinquilino Hank è un casalingo, guarda MOLTA TV. E l\'ex dissident star Becca Sparkles è diventata la nuova coinquilina di Angela e sembra essersi innamorata di Hank. Tuttavia, non importa quanto brutte siano le cose di tutte le forme e dimensioni, che si tratti del malvagio CEO, del misterioso nuovo vicino di Tom, o solo di un incidente nella nuova creazione di Ben, la banda si divertirà comunque, e ricorderà sempre una cosa che li tiene uniti: l\'amicizia non finisce mai, proprio come il nostro amore per i personaggi della serie non finisce, quindi ora puoi impostare il cursore di Talking Tom o il cursore di Ben, o forse il cursore di Angela, il cursore di Oliver!',
    'talking_tom_short_descr' => 'Parliamo del tuo personaggio preferito nella Collezione Cursor Style di Talking Tom',
    'talking_tom' => 'Talking Tom and Friends',
    'lego_descr' => 'L\'azienda LEGO Group è stata fondata nel 1932 e allora era composta da sole 7 persone. L\'obiettivo del team Lego era quello di creare giocattoli che sviluppassero la creatività, l\'immaginazione e l\'ingegno dei bambini. Un fatto sorprendente, fin dalla sua nascita nel 1949, gli elementi LEGO in tutte le loro varianti sono rimasti compatibili tra loro. Tutti gli articoli creati successivamente sono ancora compatibili con gli articoli che vengono rilasciati oggi, nonostante i cambiamenti di design e forma nel corso degli anni.

Un mattoncino LEGO è una base, che è un blocco di plastica cavo che si collega ad altri mattoncini simili. Ma i set Lego contengono anche altre parti, ruote, figure, piattaforme e persino circuiti elettronici con sensori e motori elettrici. Puoi collezionare modelli di auto, aerei, treni, navi, edifici, robot. LEGO aderisce all\'idea della modularità, che dimostra chiaramente ai bambini come risolvere determinati problemi, sviluppare l\'immaginazione, le capacità motorie fini delle mani e le capacità di assemblaggio. I mattoncini LEGO sono realizzati con un\'incredibile precisione e si incastrano perfettamente per una straordinaria precisione di 10 micron.

Recentemente, sono state create molte popolari storie animate in 3D Lego, in cui i personaggi dei set prendono vita e diventano partecipanti a incredibili avventure. Se vuoi un cursore fantastico, troverai molti personaggi delle serie TV e dei film d\'animazione Lego nella nostra collezione Lego Cursors. Lego Ninjago Cursor, Lego Batman Cursor, Lego Ninjago Cursor, Lego Wyldstyle Cursor e molti altri.',
    'lego_short_descr' => 'Costruisci il tuo browser dei sogni con la collezione di cursori Lego',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Dopo un finanziamento di successo su Kickstarter, nel 2017, Team Cherry ha pubblicato il gioco multipiattaforma per PC Hollow Knight. Questa è la storia di un cavaliere senza nome e delle sue scoperte nel regno degli insetti di Hallownest. Il gioco è stato giustamente riconosciuto come uno dei migliori nel genere metroidvania.

Il gameplay di Hollow Knight si basa sull\'esplorazione del mondo di gioco. Superare ostacoli, risolvere enigmi e trovare segreti, oltre a combattere i nemici. Il giocatore ha una serie unica di miglioramenti e trucchi per esplorare il mondo e combattere nelle battaglie. Passando da una zona all\'altra, il giocatore sconfigge i boss e ottiene i miglioramenti necessari per avanzare ulteriormente. Di conseguenza, i giocatori devono visitare le aree già attraversate per trovare segreti e proseguire nella storia. Ed è anche emozionante perché le zone cambiano ogni volta, portando nuove sorprese ed esperienze. Il gioco può essere giocato in modi diversi, perché ci sono diversi percorsi tra le zone. Passando attraverso la storia, si apre la mappa della zona, ma prima è necessario ottenere la mappa.

L\'arma principale dell\'eroe è un chiodo, che assomiglia un po\' a una spada, le armi possono essere migliorate con un fabbro, e si possono anche apprendere diverse abilità nell\'uso delle armi, il che espande la varietà degli attacchi. Attaccando i nemici, si accumula una risorsa speciale, che può essere successivamente utilizzata per miglioramenti o guarigione.

Che ti diverta a giocare a Hollow Knight e non dimenticare i nostri cursori di Hollow Knight con il tuo personaggio preferito. La nostra collezione include il cursore Mister Mushroom, il cursore Quirrel, il cursore Hornet Needle, il cursore Old Nail, il cursore Myla e altri.',
    'hollow-knight_short_descr' => 'Cerca di non perderti nel regno degli insetti usando la collezione di cursori di Hollow Knight',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman è il personaggio principale della serie. Stikmin, precedentemente senza nome, ha iniziato come un ladro minore, con il desiderio di fare soldi facili e veloci. Tuttavia, dopo essere fuggito dalla prigione di West Mesa, molti cambiamenti avvengono nella sua vita e diventa un famoso criminale dopo aver rubato il diamante tunisino. Henry ha una scelta: diventare un agente governativo di successo, un cacciatore di taglie, il leader di un\'organizzazione criminale, un cyborg o continuare il percorso criminale da solo. Il gioco delizia i fan del genere con molte avventure e misteri, e troverai la nostra nuova collezione di cursori di Henry Stickman con i suoi divertenti personaggi, tra cui il cursore di Henry Stickmin, il cursore di Charles Calvin, il cursore di Reginald Copperbottom, il cursore di Right Hand, il cursore di Ellie Rose e altri!',
    'henry-stickmin_short_descr' => 'Pianifica la tua fuga dalla noia con la collezione di cursori di Henry Stickman',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'Il popolarissimo gioco online Adopt Me è stato lanciato nel 2017 ed è diventato il più popolare sulla piattaforma di gioco Roblox. L\'essenza del gioco è molto semplice: ottenere uova con animali domestici e prendersene cura.

Gli animali domestici virtuali sono divisi in 5 classi, alcuni dei quali sono molto rari e costosi, mentre altri sono molto facili da ottenere. Questi sono gruppi Non comuni, come il Cane Blu, Comune, Cursore Raro, ad esempio il cursore del mouse Adopt Me Scimmia, così come quelli ultra-rari, come il cursore Koala, e Leggendario, cursore Drago e Accetta me Unicorno. Se il giocatore ha quattro animali domestici adulti dello stesso tipo, può combinarli in un animale domestico neon, come il cursore del gioco Cavallo Neon o la Stella Marina Neon Adopt Me. Combinando quattro animali domestici normali, puoi creare un animale domestico neon che brilla davvero, e da animali domestici neon puoi creare un animale domestico mega-neon.

Lo shopping nel gioco Adopt Me! viene effettuato con la valuta virtuale Roblox - i cosiddetti Robux, e il gioco ha anche la sua valuta - Bucks. Prendersi cura del tuo animale domestico, oltre all\'intrattenimento, puoi guadagnare bucks, basta dargli da mangiare, metterlo a letto o leggere una favola, in generale, un sacco di cose interessanti.

Ora i fan del gioco Roblox "Adopt Me!" possono decorare il cursore del loro gioco con l\'animale domestico preferito!',
    'adopt-me_short_descr' => 'Divertiti con simpatici animali domestici nella nostra collezione di cursori di gioco Adopt Me!',
    'adopt-me' => 'Adottami!',
    'among-us_descr' => 'Among Us è basato sul famoso gioco di ruolo "Mafia". Era stato previsto che il gioco fosse esclusivo per i dispositivi mobili, perché aveva una sola mappa. Il gioco divenne rapidamente popolare. Successivamente, il team di sviluppo aggiunse una modalità multiplayer e nel 2019 furono rilasciate due mappe aggiuntive.
Among Us è un gioco a tre persone dall\'alto verso il basso che permette al giocatore di muoversi in tutte le direzioni. Da quattro a dieci giocatori possono giocare in un round. All\'inizio del gioco, a tutti viene segretamente assegnato il ruolo di traditore o membro dell\'equipaggio. L\'Impostore (nella traduzione russa "Traditore") può nascondersi nello sfiato, sabotare e uccidere i membri dell\'equipaggio. Il suo obiettivo è distruggere tutti i membri dell\'equipaggio o distruggere l\'astronave con il sabotaggio. L\'obiettivo dell\'equipaggio della nave è risolvere vari enigmi preparati per loro all\'inizio del gioco. Se ciascuno dei membri dell\'equipaggio completa tutti i compiti, i traditori perderanno. Inoltre, l\'equipaggio della nave può raggiungere la vittoria eliminando i traditori durante il voto.
I traditori possono sabotare di tanto in tanto e se i guasti non vengono riparati in 30 secondi, l\'equipaggio perderà. Prima di iniziare il gioco, puoi scegliere il colore del personaggio per cui stai giocando, blu, rosso, giallo, grigio - quello che vuoi! E non dimenticare di impostare il cursore appropriato dalla nuova collezione di Among Us!',
    'among-us_short_descr' => 'Non farti ingannare in questo intricato gioco spaziale con i cursori di Among Us',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Il creatore di "Steven Universe" è stato Rebecca Sugar. È nota per il suo precedente lavoro chiamato Adventure Time. Il primo episodio di Steven Universe è stato rilasciato sulla piattaforma video YouTube nella primavera del 2013. Ma in autunno, il canale americano Cartoon Network ha iniziato a trasmetterlo per i suoi spettatori. Da allora sono state rilasciate 6 stagioni. La sesta promette di essere l\'ultima.
Per quanto riguarda la trama della serie animata, essa ruota attorno al team delle Crystal Gems. È composto da creature aliene con nomi caratteristici: Perle, Ametista e Melagrana. Ma c\'è un altro partecipante, nel ruolo del quale agisce un normale ragazzo di nome Stephen. Insieme cercano mostri e cercano di neutralizzarli in modo che non si impossessino della Terra per interesse personale. A loro si oppongono Jasper e Peridot - messaggeri dal loro pianeta natale che vogliono sconfiggere le Gems e attivare il Cluster.
Se sei un fan di Steven Universe e vuoi vedere i personaggi della serie animata ovunque tu possa, installa l\'estensione Cursor Style! Perché farlo? Puoi aggiungere una collezione dedicata a "Steven Universe" e trasformare il puntatore del mouse standard in uno dei tuoi personaggi preferiti.',
    'steven_universe_short_descr' => 'Svela il segreto delle gemme con i cursori di Steven Universe',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Una sitcom animata chiamata "I Griffin" nell\'intera storia della sua esistenza ha vinto 4 volte l\'Emmy Award e 3 volte l\'"Annie". La serie animata ridicolizza gli argomenti dolenti della società americana, come: femminismo, schiavitù, obesità, politica, ecc. A differenza di altre opere, qui vengono utilizzati inserti con battute e sarcasmo. Inoltre, in molti casi non sono integrati nella trama, ma esistono da soli.
Un episodio della serie animata viene creato in oltre 10 mesi. Perché così tanto? Perché l\'intera animazione è disegnata a mano. Per questo motivo, alcuni degli eventi trattati dall\'opera hanno il tempo di perdere rilevanza. Ma anche così, la sitcom rimane molto interessante e guadagna il favore degli spettatori di tutto il mondo. Dopotutto, a chi non piace ridere bene dei politici, delle celebrità o delle persone che commettono pazzie e quindi sorprendono o addirittura sciocano la gente comune.
Ti piacciono "I Griffin"? Hai un\'opportunità unica per trasformare un normale cursore del mouse in uno qualsiasi dei personaggi di questa serie animata! Cosa devo fare? Basta installare l\'estensione del browser “Cursor Style”, aggiungere una collezione dedicata a “I Griffin” e goderti una favolosa reincarnazione!',
    'family_guy_short_descr' => 'Raccolta di cursori di Griffin per intenditori di umorismo speciale',
    'family_guy' => 'I Griffin',
    'cute_cursors_descr' => 'Sicuramente hai sentito l\'espressione "La bellezza salverà il mondo"? Quindi, molte persone, specialmente le ragazze, sono d\'accordo con questa affermazione. Pertanto, si sforzano di circondarsi di tutto ciò che è più bello e piacevole alla vista. Possono essere sfondi rosa in camera da letto, peluche, cuscini ricamati con perline, gioielli preziosi, ecc. Dall\'esterno, tutto sembra molto carino e persino un po\' infantile. Ma ognuno di noi è un bambino nel cuore, quindi perché non lasciare che esprima la nostra immaginazione?
La tenerezza può provocarci molto. Ad esempio, gli occhi compassionevoli di un gattino che vuole essere accarezzato o nutrito. Un arcobaleno multicolore, che spunta dopo una pioggia primaverile e brilla con tutti i colori del sole. Il bambino a cui è stato offerto del cioccolato, e che ha deciso di condividerlo con la sua ragazza o il suo ragazzo. Ci sono diversi motivi per emozionarsi, e abbiamo deciso di usarli come cursori.
Stanco della noiosa freccia bianca nel tuo browser? Sostituiscila con qualcosa di carino dalla nostra collezione! Ad esempio, un unicorno rosa e bianco, un pomodoro triste, una nuvola cupa, un cactus spinoso a forma di gatto, o quello che vuoi. Tutto ciò che devi fare è installare l\'estensione Cursor Style e aggiungere una collezione di cursori carini. E lunga vita al salvatore del mondo - la bellezza!',
    'cute_cursors_short_descr' => 'Il mondo sarà più gentile con la collezione di cursori carini',
    'cute_cursors' => 'Cursori Carini',
    'web_media_descr' => 'Nelle realtà moderne, quasi tutti usano Internet. A partire dai bambini piccoli e finendo con i pensionati. Qualcuno naviga utilizzando un browser, un altro guarda video su YouTube, e qualcuno ha bisogno della rete per comunicare con i propri cari. Qualunque di questi utenti non può immaginare un giorno senza il World Wide Web.
Le persone anziane spesso siedono su un social network come Facebook o VK. Comunicano anche spesso con i loro figli e nipoti su Skype. Questo è particolarmente conveniente se i figli e i genitori vivono in città diverse o addirittura in paesi diversi.
I giovani preferiscono comunicare tramite Viber o Telegram, caricare foto su Instagram, ridere dei meme di FB. I video di YouTube delle reazioni delle persone stanno guadagnando milioni di visualizzazioni, proprio come varie burle o esperimenti sociali. In Tik-Tok, centinaia di migliaia di persone ballano, mostrano trucchi di magia e si esprimono.
Sei interessato o usi spesso un qualche tipo di risorsa dalla sfera dei web media? Vuoi sbarazzarti della noiosa freccia del mouse nel tuo browser? Allora installa l\'estensione e cambia il cursore predefinito con il nostro creativo! Può essere il cursore di YouTube, il cursore di Viber, il cursore di Google Chrome o altre risorse.',
    'web_media_short_descr' => 'Vivi in un ritmo moderno con la collezione di cursori web media',
    'web_media' => 'Web Media',
    'bobs_burgers_descr' => 'La serie animata Bob\'s Burgers è la trama dell\'opera di animazione e il carisma dei personaggi. E, a giudicare dalla nomination per l\'Emmy Award e dal riconoscimento dell\'opera come uno dei migliori cartoni animati del mondo, Bob\'s Snack ha davvero fatto scalpore.
La trama della serie animata ruota attorno alla famiglia Belcher. Questa persona è il proprietario della tavola calda al primo piano, e al secondo vive con i suoi cari. Bob ha una moglie allegra, Linda, e 3 figli: Gene, Louise e Tina. Il ragazzo sogna una carriera musicale, la figlia maggiore Tina è molto gentile, ma impacciata, e la più giovane - Louise è ancora una birichina e spesso mette la sua famiglia in una posizione scomoda. Il principale concorrente di Bob\'s Burgers è la Pizzeria di Jimmy Pesto. Come si può immaginare, il proprietario di questa pizzeria si chiama Jim e lui e Bob si detestano. Tutto questo è stato elaborato in modo da sembrare comico, non serio. Pertanto, molte delle loro schermaglie causano solo un sorriso.
Se ami la serie animata "Bob\'s Burgers" e vuoi vedere i suoi personaggi non solo sullo schermo del monitor o della TV, installa l\'estensione, aggiungi una raccolta e cambia il cursore del mouse nel browser con uno qualsiasi dei personaggi di questo cartone animato!',
    'bobs_burgers_short_descr' => 'Bob prepara hamburger e noi prepariamo i cursori di Bob\'s Burgers',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'La storia del videogioco "Kirby" è iniziata già negli anni \'90 del secolo scorso. È composta da molte serie sviluppate da Nintendo e HAL Laboratory. Il gioco è destinato ai bambini da uno e mezzo a 8 anni. La sua popolarità può essere giudicata dal numero di copie vendute. Oltre 34 milioni in tutto il mondo.
Il personaggio principale di Kirby è l\'omonima creatura rosa. Vive su un pianeta chiamato Pop Star e periodicamente lo protegge da vari pericoli. Kerby può inspirare alcuni oggetti e i suoi nemici per poi imparare le loro abilità: combattimento corpo a corpo, possesso di una spada, respirazione del fuoco, ecc. Tuttavia, il puffer rosa non combatte solo con i nemici, ma risolve anche vari enigmi, viaggia in altri paesi e può persino volare nei livelli.
Puoi giocare a questo videogioco su console Nintendo o Game Boy. In tutte le serie ci sono eroi carini, una bella grafica e colonne sonore divertenti. A proposito, in quasi 30 anni dall\'uscita della prima versione, il mondo è riuscito a vedere 20 serie di Kirby. Questo indicatore, unito al volume multimilionario di copie vendute, ha contribuito a far sì che il gioco fosse nella TOP 50 dei videogiochi di maggior successo e più ricercati nel settore dei giochi.
Ami Kirby così tanto che vorresti vedere questo personaggio ovunque possibile? Allora usa la collezione Kirby e trasforma il puntatore del mouse normale nel personaggio principale del tuo videogioco preferito! Siamo sicuri che ti piacerà il nuovo aspetto del cursore.',
    'kirby_short_descr' => 'Prova ad inalare l\'intera collezione di cursori di Kirby',
    'kirby' => 'Kirby',
    'undertale_descr' => 'Nei tempi antichi, la Terra era abitata non solo da persone, ma anche da mostri. A causa di disaccordi tra loro, scoppiò una guerra, che si concluse a favore della razza umana. Sette maghi spinsero i mostri nel sottosuolo e li imprigionarono per sempre con un incantesimo barriera. Tuttavia, c\'era un solo ingresso al Monte Ebott, di cui il bambino approfittò. È per lui che giocherai eseguendo il videogioco Undertale.
Questo gioco è stato sviluppato da Toby Fox, un noto programmatore degli Stati Uniti. All\'inizio, i proprietari di personal computer con sistemi operativi Microsoft Windows e Linux potevano goderne, e poi arrivò il turno degli utenti delle console di gioco.
Qual è il punto di questo gioco? Il ragazzo viaggia attraverso il mondo sotterraneo abitato da mostri. Alcuni di loro sono immediatamente ostili, mentre altri amano parlare. Il giocatore può scegliere uno dei 2 comportamenti: evitare la violenza o combattere. Nel primo caso, superare il gioco sarà più facile, nel secondo, al contrario, è più difficile. Anche la trama e il finale, che possono ramificarsi e cambiare, dipendono da questa scelta.
Se ti piace Underground Tale e vorresti vedere i suoi personaggi nel tuo browser, installa l\'estensione e aggiungi la collezione di cursori appropriata! Trasforma un noioso puntatore del mouse in uno dei mostri o nel personaggio principale di Undertale!',
    'undertale_short_descr' => 'È ora di uscire dal buco usando i cursori di Undertale',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune è un gioco di ruolo uscito per computer un paio di anni fa. È stato creato dallo stesso programmatore che ha sviluppato Undertale. Tuttavia, questi due giochi non sono quasi per niente simili, anche se hanno un paio di personaggi e ambientazioni in comune.
Ci sono diversi personaggi principali in Delta Rune. Questo è lo studente Chris, che può essere controllato, e un\'affascinante mostro Susie, incontrollabile. Entrambi i personaggi cadono nel mondo delle tenebre, dove incontrano uno dei suoi abitanti - Ralsay. Egli dice loro che in realtà sono creature di luce che hanno una missione - fermare il flusso di energia oscura in un mondo cupo. Per fare questo, hanno bisogno di risparmiare i mostri locali e cercare di non impegnarsi in battaglia con loro, anche se questo a volte è abbastanza difficile da fare.
Il giocatore ha una semplice scelta: o risparmiare le creature oscure, o attaccarle. Poiché Susie non è una fan delle mezze misure, in molti casi sceglie la battaglia. Pertanto, Chris non ha altra scelta che supportare la sua ragazza e aiutarla nelle battaglie.
Ami il gioco Deltarune? Allora stilizza il tuo cursore del mouse nel browser per uno dei suoi personaggi! Puoi farlo con la nostra estensione. Installala, aggiungi la collezione “Rune Delta” e attivala! Ora la tua freccia ha smesso di essere la stessa di tutti gli altri, ed è diventata Chris, Susie o una delle creature del mondo oscuro.',
    'deltarune_short_descr' => 'Immergiti nel mondo oscuro con questa collezione di cursori',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario è una serie di videogiochi pubblicati da Nintendo. Il primo e più popolare gioco si chiamava Super Mario Bros. Ha visto la luce nel 1985. Successivamente è stato inserito nel Guinness dei primati. Da allora, sono stati rilasciati più di 20 giochi, ognuno dei quali ha la sua trama. Nel 2019, è apparsa una nuova versione chiamata Super Mario Maker 2. Nonostante il miglioramento della grafica, lo stile e i personaggi sono rimasti gli stessi, e questo evoca nostalgia per il Super Mario degli anni \'80.
Il protagonista è ancora l\'idraulico Mario. Nella trama dell\'ultima variazione del gioco, il castello della Principessa non ha avuto una pietra non smossa. Mario deve ricostruirlo, avendo guadagnato prima le monete che gli vengono pagate per i compiti. In totale, questo gioco ha più di 100 livelli di varia complessità con la possibilità di modifica. Anche in Super Mario Maker 2 ci sono nuove modalità di gioco. Puoi giocarne quattro contemporaneamente e non appena uno finisce, il livello è considerato completato. Ci sono anche modalità come: Maratona Mario, Duello e gare Ninjik.
Ami Super Mario e tutto ciò che riguarda questo meraviglioso gioco? Allora imposta i cursori realizzati nello stile di questo platform! Siamo sicuri che ti piaceranno il cursore di Mario, il cursore di Luigi, il cursore della Principessa Peach e altri cursori che sono presentati nella nostra collezione!',
    'super_mario_short_descr' => 'Attraversa il Regno dei Funghi con la collezione di cursori di Super Mario',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls è stato creato congiuntamente da Disney Television Animation Corporation e Alex Hirsch. La premiere è stata rilasciata nel 2012 ed è stata trasmessa su Disney Channel. L\'intera prima stagione della serie animata è stata trasmessa lì. Due anni dopo, è stata rilasciata la seconda stagione, che gli spettatori potevano guardare sul canale precedente e su Disney XD. Sfortunatamente, i fan di Gravity Falls non hanno aspettato la terza e le successive stagioni. I creatori hanno deciso di limitarsi a due stagioni senza alcun seguito.
Per quanto riguarda la trama di questo cartone animato, tutta l\'azione si svolge in una città fittizia chiamata Gravity Falls. Due gemelli ci vanno, i cui nomi sono Mabel e Dipper. Stanno con il loro cugino Stan. Ha il suo negozio di souvenir turistici. Quando i fratelli si annoiano a "non fare niente", vanno alla ricerca di avventure. Uno di loro trova uno strano diario nella foresta, che racconta delle anomalie di questa città. I gemelli partono alla ricerca del suo autore e incontrano creature e luoghi insoliti. Se sei interessato a questa serie animata e un tempo eri fan dei suoi personaggi, ti consigliamo la nostra collezione di puntatori del mouse in stile Gravity Falls!',
    'gravity_falls_short_descr' => 'Parti per un\'avventura con i cursori di Gravity Falls',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Assolutamente tutti hanno sentito parlare di una serie animata così famosa come I Simpson. Anche quelle persone che non hanno mai visto la serie sono a conoscenza dell\'esistenza dei personaggi gialli. E i fan sono felicissimi quando esce la prossima stagione del loro cartone animato preferito. A proposito, nell\'autunno del 2019 sono stati rilasciati 31 account di stagione. E il primo è apparso sugli schermi televisivi nel 1989. Fox ha iniziato a trasmetterla e continua a farlo grazie agli alti ascolti e alla simpatia del pubblico.
I Simpson è un genere satirico che tocca argomenti rilevanti. Questo può essere lo stile di vita dell\'americano medio, questioni politiche e religiose, trucchi "stellari" delle celebrità, femminismo, matrimoni omosessuali. In generale, tutto ciò che riguarda eventi locali e globali a cui partecipano gli Stati Uniti.
L\'azione della serie animata si svolge nella città inesistente di Springfield. In realtà, ci sono molte città con questo nome in America. Forse è per questo che è stata scelta, in modo che il pubblico non associasse ciò che accadeva sugli schermi a una località specifica, ma solo indovinasse dove ciò potesse essere.
Molto probabilmente sei un fan dei Simpson. Altrimenti, perché dovresti leggere questo testo fino alla fine? E in tal caso, allora hai l\'opportunità di cambiare il noioso cursore del mouse in un puntatore realizzato nello stile di questa serie animata.',
    'simpsons_short_descr' => 'Una simpatica famigliola con i cursori dei Simpson',
    'simpsons' => 'I Simpson',
    'youtubers_descr' => 'La piattaforma video di YouTube è apparsa nel 2005. All\'inizio, i video venivano pubblicati lì solo per l\'espressione di sé o per informare su qualcosa. Tuttavia, nel tempo, tutto ciò è cresciuto in un business redditizio, che porta migliaia e, a volte, milioni di dollari al mese agli utenti di YouTube di successo. Più il vlogger (la persona che conduce il video blog) è popolare, più può guadagnare attraverso il suo canale.
Quanto guadagna una vlogger di cinque anni, i cui genitori la portano alle attrazioni più interessanti e riprendono ciò che accade sulla telecamera? È solo come un bambino si diverte nei parchi giochi per bambini, che esprime emozioni, come fare il buffone e tutto quel genere di cose. L\'importo è davvero sorprendente: oggi il canale del bambino ha guadagnato quasi 47 milioni di abbonati e ha iniziato a generare entrate per un importo di 5 milioni di rubli al mese.
Qualcuno carica video in cui discute di giochi per computer, qualcuno fa beatboxing o organizza scherzi ai passanti per strada. Alcuni dedicano i loro video a temi sensibili, come la relazione tra uomini e donne. Più gli utenti di YouTube apprezzano queste riprese, maggiore è la popolarità del vlogger.
La collezione ha già aggiunto il cursore di PewDiePie, il cursore di Shane Dawson, il cursore di Ray William Johnson, il cursore di Zoella, il cursore di MyLifeAsEva e altri.',
    'youtubers_short_descr' => 'Una nuova generazione di star è sempre online nella nostra collezione YouTubers',
    'youtubers' => 'YouTubers',
    'pusheen_descr' => 'Quasi tutti conoscono il gatto Pusheen. Anche se è solo un personaggio di un fumetto per bambini inventato 10 anni fa, oggi ha milioni di fan. Il gatto Pusheen è apparso come un\'illustrazione creata dall\'artista Claire Belton.
Un anno dopo, il gatto ha acquisito una sua pagina su Tumblr.com e in poche settimane ha guadagnato un intero esercito di fan - circa 10.000 persone. Nel 2013, Facebook era impaziente di includere immagini di Pushin nelle raccolte con altre emoticon. Dopo le trattative con il creatore, questa idea è stata messa in pratica e ha “fatto esplodere” Internet! Le immagini del gatto Pusheen vengono utilizzate nella corrispondenza più di 10 milioni di volte al giorno!
Nel 2014, uno dei maggiori produttori di giocattoli negli Stati Uniti ha rivolto la sua attenzione a questo personaggio. GUND (è stata lei a inventare gli orsacchiotti) ha lanciato un paio di modelli di Pushin. Poiché il successo è stato enorme, dopo pochi mesi è stata creata una collezione completa di giocattoli a forma di questo gatto.
Dove altro puoi incontrare il gatto Pusheen? Nei set regalo di Isaac Morris Ltd, nei marshmallow di Boomf e, naturalmente, nella nostra collezione di cursori Pusheen!',
    'pusheen_short_descr' => 'Aggiungi un po\' di comfort nel tuo browser con la collezione di cursori di Pusheen',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'La prima serie del lavoro d\'animazione “Rick and Morty” è stata rilasciata nel 2013. Questo cartone animato può essere attribuito direttamente a 2 generi: fantascienza e commedia. I suoi creatori sono stati Dan Harmon e Justin Royland. Inizialmente, tutte le serie sono state trasmesse sul canale Cartoon Network, e solo successivamente sono state duplicate nei cinema online e negli hosting video. Ogni pochi anni, vengono rilasciate nuove stagioni di Rick and Morty, e nel novembre 2019 è uscita la quarta stagione, che si è rivelata non meno interessante delle precedenti. La trama della serie animata ruota attorno a un genio e, allo stesso tempo, a uno scienziato pazzo di nome Rick, così come al suo nipote anonimo - Morty. Questi due personaggi sono collegati da avventure congiunte nei luoghi più insoliti. E ci arrivano su un disco volante, capace di muoversi attraverso un tunnel inter-spaziale. Come forse avrai intuito, questa serie animata è un po\' come il film Ritorno al Futuro, ma comunque non è la sua versione animata. Tuttavia, è stato elogiato da molti critici per gli episodi umoristici, la creatività e l\'originalità. Vuoi vedere Rick o Morty non solo nella serie di quest\'opera, ma anche nel browser? Se è così, installa l\'estensione e aggiungi la nostra collezione dedicata al tuo cartone animato preferito! Ecco il cursore di Rick Sanchez, il cursore di Morty Smith, il cursore di Portal Gun e, naturalmente, il cursore di Mr. Meeseeks.',
    'rick_and_morty_short_descr' => 'Smettila di brontolare, usa semplicemente i cursori della collezione Rick and Morty',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'I fan del baseball si possono trovare ovunque nel mondo. Questo è particolarmente vero per i residenti di paesi come: USA, Cina, Cuba, Corea del Sud, Giappone e Venezuela. Contrariamente alla credenza popolare, il baseball non è nato in America, ma in Inghilterra. La prima menzione e descrizione del baseball apparve nel lontano 1744, nell\'edizione inglese. Dopo 145 anni, gli americani si appropriarono di questa invenzione, nonostante i fatti.
La National League fu formata nel 1876. Fa parte delle Major League in Canada e negli Stati Uniti. Oggi ci sono 15 squadre nella National Baseball League. Nella parte finale di ogni stagione, arriva il momento dei playoff, a cui partecipano le 4 migliori squadre. Così viene rivelato il vincitore dell\'intera National League. Quindi la squadra vincitrice ha l\'opportunità di giocare contro il vincitore dell\'American League nelle World Series.
Sei interessato al baseball o fai il tifo per una delle squadre? Allora rendi omaggio alla tua squadra preferita impostando i cursori del mouse sotto forma dei suoi attributi! Cambia l\'aspetto noioso del puntatore nel browser con la familiare identità aziendale del baseball! Trasforma la freccia in una mazza o un casco di un giocatore in una qualsiasi delle squadre della National League, che includono già il cursore dei New York Yankees, il cursore dei Great Falls Dodgers, il cursore dei Boston Red Sox, il cursore dei Baltimore Orioles, il cursore degli Oakland Athletics.',
    'mlb_teams_short_descr' => 'Una raccolta di cursori delle squadre MLB per tutti i nostri tifosi.',
    'mlb_teams' => 'Squadre MLB',
    'brawl_stars_descr' => 'Brawl Stars è un gioco mobile nel genere MOBA di Supercell. Nonostante l\'uscita alla fine del 2018, il gioco ha guadagnato grande popolarità, in gran parte grazie all\'abbondanza di modalità di battaglia ed eroi colorati e fantastici - brawler. Il giocatore ha molto da scegliere - 32 personaggi unici e ognuno di loro ha il proprio set di abilità e competenze. Ogni eroe ha anche la sua abilità passiva, disponibile attraverso forzieri. I giocatori possono combattere in diverse modalità, ad esempio, "Ricompensa per la cattura" - vince una delle due squadre che ha raccolto più stelle, uccidendo gli avversari. Nella modalità "rapina", è necessario rompere le casseforti degli avversari, mantenendo le proprie. Un\'interessante modalità “Gem Grab” - la squadra vincitrice è quella che raccoglie il maggior numero di gemme. Bene, nella modalità "Collisione", 10 giocatori si affrontano sulla mappa, dove i bordi vengono ridotti a causa di una nube tossica. Il gioco è pieno di un design colorato che piace a molte persone, compresi noi, il che ci ha ispirato a creare una collezione separata di cursori Brawl Stars. Ci sono il cursore di Shelley di Brawl Stars, il cursore di Barley, il cursore di Penny, il cursore di Frank, il cursore di Mortis e altri.',
    'brawl_stars_short_descr' => 'Scegli i cursori di Brawl Stars e che la battaglia abbia inizio',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Cambia il tuo cursore del mouse in due clic! Collezioni gratuite per tutti i gusti.',
    'all_descr' => 'Se hai mai pensato a come cambiare un noioso cursore del mouse, allora le nostre raccolte di cursori fanno per te! Qui troverai fantastici eroi dei fumetti, bellissimi cursori per giocatori con personaggi di giochi popolari, divertenti set di cursori per scherzi pratici, cursori a colori e molte altre interessanti opzioni.',
    'text_title' => 'Collezioni di cursori divertenti e originali per tutti i giorni',
    'text_allcat_title' => 'Cursori del mouse unici e creativi per abbinarsi a ogni tuo umore',
    'text_1' => 'Non vuoi essere come tutti gli altri? O semplicemente ami tutto ciò che è insolito? Vuoi far parte del tuo eroe di gioco o personaggio dei cartoni animati preferito? Allora sei arrivato all\'indirizzo giusto. Qui troverai set di cursori brillanti e insoliti che possono sostituire la familiare e già piuttosto noiosa freccia bianca. Il cursore del mouse ci accompagna tutto il giorno nel lavoro e nello studio, quindi dovrebbe dare un ottimo umore e preparare al positivo.',
    'text_2' => 'Qui troverai cursori per giocatori e amanti dei film, bellissimi cursori basati sui tuoi cartoni animati e motivi sportivi preferiti per le persone più attive. Ti piacciono i fumetti o non riesci a immaginare un solo giorno senza divertenti meme? Adori gli animali o sogni di visitare tutti i paesi del mondo? È tutto semplice: abbiamo un\'immagine del cursore adatta anche a te. Puoi anche selezionare le immagini a seconda di cosa stai lavorando. Ad esempio, un cursore nero sarà molto più comodo di quello bianco quando si lavora con documenti o disegni, e un cursore a forma di mano sarà più comodo se devi lavorare con piccoli elementi grafici. Scegli la tua immagine preferita, regola le sue dimensioni direttamente nell\'estensione - e usala con piacere, ogni giorno iniziando con una nota positiva!',
    'install_to_preview' => 'Per favore, installa l\'estensione per l\'anteprima',
    'install' => 'Installa',
    'add_button' => 'Aggiungi',
    'preview_button' => 'Anteprima',
    'added_button' => 'Aggiunto',
    'add_cursor' => 'Aggiungi cursore',
    'to_your_collection' => 'alla tua collezione',
    'prev_text_1' => 'Anteprima a schermo intero',
    'prev_text_2' => 'cursore',
    'cursor' => 'cursore',
    'pointer' => 'puntatore',
    'a_title_1' => 'Cursor Style - Fantastici cursori per il tuo browser',
    'a_title_2' => 'Fantastische collezioni di cursori tematici',
    'mouse_cursors' => 'cursori del mouse',
    'cursor_collection' => 'Collezione di cursori',
    'sborka_cursorov' => 'raccolta di cursori',
    'collection_list_from_colllection' => 'Elenco dei cursori - ',
    'christmas' => 'Natale',
    'nhl_teams' => 'Lega Nazionale di Hockey',
    'neon' => 'Neon',
    'adventure_time' => 'Adventure Time',
    'nba_teams' => 'National Basketball Association',
    'spongebob' => 'SpongeBob',
    'phineas_and_ferb' => 'Phineas e Ferb',
    'fortnite_chapter_2' => 'Fortnite Capitolo 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Personaggi Famosi',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Fumetti',
    'igry' => 'Giochi',
    'multfilmy' => 'Cartoni animati',
    'kino_i_serialy' => 'Film e serie TV',
    'anime' => 'Anime',
    'futbol' => 'Calcio',
    'avtomobili' => 'Automobili',
    'memy' => 'Meme',
    'emodji' => 'Emoji',
    'pitomcy' => 'Animali domestici',
    'stil_i_krasota' => 'Moda e stile',
    'prazdniki' => 'Festività',
    'flagi' => 'Bandiere',
    'vokrug_sveta' => 'In giro per il mondo',
    'eda_i_napitki' => 'Cibo e bevande',
    'cvetnye' => 'Colorati',
    'prank' => 'Scherzi',
    'startovyj_nabor' => 'Kit di partenza',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Babbo Natale adorerà i tuoi cursori di Natale',
    'nhl_teams_short_descr' => 'Una collezione di cursori NHL per veri fan',
    'neon_short_descr' => 'Aggiungi luminosità con una collezione neon',
    'adventure_time_short_descr' => 'Imparare la matematica con la collezione di cursori di Adventure Time',
    'nba_teams_short_descr' => 'Cursori NBA come simbolo di grandi vittorie nel basket',
    'spongebob_short_descr' => 'Scopri chi vive sul fondale marino con la collezione di cursori di SpongeBob',
    'phineas_and_ferb_short_descr' => 'Non ti annoierai di certo con la collezione di cursori di Phineas e Ferb',
    'fortnite_chapter_2_short_descr' => 'Il nuovo capitolo del gioco di culto Fortnite',
    'pokemon_short_descr' => 'Acchiappali tutti, se ci riesci',
    'famous_people_short_descr' => 'Ispirati al cursore del tuo idolo',
    'the_elder_scrools_short_descr' => 'Immergiti nel mondo di cavalieri e draghi',
    'halloween_short_descr' => 'Sii spaventato di perdere la nuova collezione di Halloween',
    'nfl_teams_short_descr' => 'Per i veri fan del football',
    'five_nights_at_freddy_short_descr' => 'Cerca di non spaventarti da questi animatroni',
    'komiksy_short_descr' => 'Cursori dei fumetti: scegli il tuo umore oggi.',
    'igry_short_descr' => 'Realtà virtuale: chi stai interpretando oggi?',
    'multfilmy_short_descr' => 'Personaggi dei cartoni animati preferiti in un nuovo design',
    'kino_i_serialy_short_descr' => 'Il Signore del Cursore: La Fratellanza del Desktop',
    'anime_short_descr' => 'Tutti amano gli anime: qual è il tuo personaggio preferito?',
    'futbol_short_descr' => 'Sei un vero appassionato di sport? Allora devi essere qui',
    'avtomobili_short_descr' => 'L\'auto dei tuoi sogni: una vasta flotta per professionisti',
    'memy_short_descr' => 'Motivi preferiti: collezione di cursori Meme',
    'emodji_short_descr' => 'Mostra il tuo vero stato d\'animo agli altri - imposta Cursoji!',
    'pitomcy_short_descr' => 'Cursori brillanti per tutti gli amanti dei nostri fratelli minori',
    'stil_i_krasota_short_descr' => 'Cursori originali per tutte le occasioni',
    'prazdniki_short_descr' => 'Cosa c\'è sul calendario? Nuova collezione di cursori festivi!',
    'flagi_short_descr' => 'In cerca di avventura: dove andiamo oggi?',
    'vokrug_sveta_short_descr' => 'In giro per il mondo in un istante: dove andiamo oggi?',
    'eda_i_napitki_short_descr' => 'Cursor appetitosi per la creatività',
    'cvetnye_short_descr' => 'Dipingi la tua vita con colori vivaci e pennellate audaci',
    'prank_short_descr' => 'Una serie di cursori per gli scherzi più divertenti',
    'startovyj_nabor_short_descr' => 'Un nuovo sguardo alle cose familiari: una serie di cursori aggiornata',
    'fortnite_short_descr' => 'Segui gli streamer!',
    'dota_2_short_descr' => 'Rendi il tuo mondo virtuale reale!',
    'minecraft_short_descr' => 'I personaggi del tuo gioco preferito sono sempre vicini',
    'christmas_descr' => 'Ognuno di noi aspetta senza dubbio la festa più popolare: il Natale. Tutti i cristiani del mondo lo celebrano tradizionalmente ogni anno, il 25 dicembre. Un momento in cui le famiglie si riuniscono a tavola, condividono la loro gioia e il loro amore e si scambiano regali. Molto prima di Natale, le persone decorano le strade con ghirlande luminose e le loro case con gli attributi tradizionali. È difficile trovare una persona a cui non piaccia il Natale - una festa divertente e misteriosa, perché è accompagnata da molte tradizioni e rituali, che ci riportano alle radici di tutta la nostra famiglia. Alla vigilia di Natale, letteralmente tutto è saturo del suo spirito, dai pan di zenzero dipinti ai canti toccanti. Un elegante albero di Natale e regali sotto di esso, una gioia familiare a ciascuno di noi fin dall\'infanzia. Vogliamo unirci a questa magica festa e, chissà, forse Babbo Natale preparerà un regalo speciale per te se decori il tuo cursore con la nostra collezione di Natale. C\'è tutto ciò di cui hai bisogno per questo, il cursore di Babbo Natale, il cursore dell\'albero di Natale, il cursore di pan di zenzero, il cursore del pupazzo di neve e persino il cursore del sacchetto regalo. Buon Natale!',
    'nhl_teams_descr' => 'La National Hockey League è stata fondata nel 1917 - è un\'organizzazione sportiva professionistica che riunisce club di hockey dagli Stati Uniti e dal Canada. Ed è uno dei primi campionati professionistici di hockey al mondo. La NHL è uno dei principali campionati sportivi del Nord America, insieme a NFL, NBA, Major League Baseball e MLS. Ogni anno, 31 squadre di 30 città negli Stati Uniti e in Canada combattono per il trofeo principale - la Stanley Cup, e la squadra che ha segnato più punti nella stagione regolare viene premiata con la Presidential Cup. È tempo per noi di onorare questo grande gioco creando una collezione di cursori NHL. Se anche a te piace l\'hockey, fai il tifo per la tua squadra preferita o partecipa a questo sport, basta cambiare il cursore e non separarti dalla tua squadra preferita, incluso il cursore dei Boston Bruins, il cursore dei St. Louis Blues, il cursore dei Columbus Blue Jackets, il cursore dei Tampa Bay Lightning, il cursore dei Dallas Stars e altri club degni di sincero rispetto.',
    'neon_descr' => 'Abbiamo creato una collezione unica di cursori neon per aggiungere varietà alla navigazione quotidiana su internet e aggiungere un po\' di luminosità alle affascinanti luci al neon. Lascia che i loro colori ricchi creino l\'atmosfera avvolgente della città di notte, dando l\'ispirazione per creare qualcosa di nuovo. Nel mondo moderno, le luci di una metropoli annunciano sempre l\'inizio della notte, ci seguono in ogni strada e questo bagliore è pieno di energia. Lascia che sia seguito anche da un cursore gelato luminoso, un cursore hot dog delizioso, un cursore hamburger succoso, un cursore diamante scintillante e altri cursori dalla nuova collezione neon.',
    'adventure_time_descr' => '"Adventure Time" è un cartone animato di genere fantastico in cui l\'azione si svolge in un mondo che è sopravvissuto all\'apocalisse. Questo territorio si chiama Land Ooo, che fino a poco tempo fa era una guerra nucleare. Ma tutto questo è già nel passato, tuttavia, tutte le persone sopravvissute sono state soggette a mutazioni e il mondo si è riempito di magia. I personaggi principali della serie animata sono Finn, un ragazzo di 14 anni e il suo amico un cane di nome Jake. Il ragazzo e il cane amano molto l\'avventura, aiutano costantemente tutti coloro che sono in difficoltà. Gli amici vivono su un albero e trascorrono tutto il loro tempo insieme. Se vuoi immergerti in un mondo di avventure con altri ammiratori, allora grida "Mathematics". Ecco sia il cursore Finn Boy che il cursore Jake, così come il cursore Princess Chewing gum. Ovviamente, non ci siamo dimenticati del cursore Bimo, del cursore Ice King e altri.',
    'nba_teams_descr' => 'Se il basket è il tuo gioco preferito, come lo è per noi, allora una collezione di cursori dedicata alle squadre NBA è ciò di cui hai bisogno. L\'NBA è una delle principali associazioni sportive del continente nordamericano. Quando abbiamo creato questa collezione, siamo stati tormentati dalla scelta: quale squadra scegliere, perché ce ne sono trenta nell\'NBA. Ma ci sono squadre che sono leggende. Questi sono i Chicago Bulls, che hanno stabilito un record di vittorie a metà degli anni \'90. Questi sono i Golden State Warriors, che hanno riunito i migliori giocatori della lega un paio di anni fa. O, ad esempio, Lakers, Celtics sono anche squadre incredibilmente fantastiche. Se, come noi, non vedi l\'ora delle partite delle tue squadre di basket preferite e vuoi mostrare il tuo sostegno alla squadra o ai giocatori, scarica la nostra collezione di cursori NBA.',
    'spongebob_descr' => 'La serie animata "SpongeBob SquarePants" è conosciuta da così tante persone. È stato un successo travolgente dopo che Nickelodeon nel 1999 ha deciso di creare una serie animata basata sulla striscia comica educativa Tide Zone e si è trasformata in un franchise molto redditizio. Il creatore della serie è un ex dipendente del laboratorio oceanologico, motivo per cui quasi tutti i personaggi della serie animata sono divertenti abitanti dei fondali marini, con le loro caratteristiche e il loro carisma. L\'azione ruota attorno alla ricetta segreta del Krabsburger che solo il personaggio principale può cucinare - Sponge Bob. E gli altri abitanti del mare giorno cercano di ottenerla, compreso l\'anti-eroe principale Sheldon Plankton, che non ci riesce ogni volta. Nella collezione di cursori di SpongeBob, abbiamo raccolto i cursori di tutti i personaggi e gli eventi notevoli della serie. Ad esempio, il cursore di Mr. Krabs con il dollaro, il cursore di Patrick Stella, Squiddi con il suo clarinetto, il cursore della medusa, il cursore di Sponge Bob e molti altri personaggi.',
    'phineas_and_ferb_descr' => 'Nella fittizia città americana di Denville dell\'inesistente Trishtatya, vivono due ragazzi interessanti. Ogni giorno della loro vacanza si trasforma in incredibili avventure, perché possono costruire delle montagne russe grandi come un\'intera città o un vero portale per un altro pianeta. Condividono il loro fantastico intrattenimento con gli amici. Allo stesso tempo, mentre i ragazzi si divertono, lo scienziato malvagio Heinz Fufelschmertz sta costruendo un\'altra macchina malvagia che crea caos, con il nome che termina in "-inator", con l\'aiuto della quale vuole vendicare i suoi rancori infantili o impadronirsi del potere a Trishtat, ma Perry lo ostacola - Utkonos, il segreto "Agente Pi", che lavora sotto le mentite spoglie dell\'animale domestico dei ragazzi. La popolarità di questa serie animata, sia tra i bambini che tra gli adulti, ci ha ispirato a creare la collezione di cursori di Phineas e Ferb in modo da poter cambiare il cursore del mouse con i personaggi della serie. Tra questi ci sono il cursore di Phineas Flynn, il cursore del Dr. Heinz Fufelschmertz, il cursore di Ferb Fletcher, il cursore di Candace Gertrude Flynn e il cursore dell\'ornitorinco Perry.',
    'fortnite_chapter_2_descr' => 'Il secondo capitolo di Fortnite è arrivato dopo un grande evento - La Fine, che ha trascinato tutto ciò che i giocatori amavano nel gioco in un buco nero. Fortnite Capitolo 2 ora ha una nuova mappa, che a prima vista è ancora più selvaggia della mappa originale, così come molti cambiamenti nelle meccaniche di gioco e, naturalmente, un sacco di nuovi contenuti di gioco! Veicoli, emozioni, meccaniche di nuoto e molto altro - tutto questo in immagini fresche e interessanti, tutto come ami e apprezzi in questo gioco cult. Immergiti in un nuovo mondo - scegli un sito di atterraggio ed esplora un\'isola completamente nuova con 13 località. Nuoto, pesca, motoscafi - questo è un nuovo gameplay acquatico. Più divertimento e meno sforzo - aggiorna un capitolo 2 completamente nuovo e non dimenticare di cambiare il cursore con nuove skin e armi. Stanno già aspettando le skin aggiornate Cursore Turk, Cursore Riptide, Cursore Rippley, Cursore Remedy, Cursore Toxin, Cursore 8-Ball, Cursore Fusion e altri!',
    'pokemon_descr' => 'La parola "pokemon" significa una creatura con poteri soprannaturali. Hanno intelligenza e alcuni di loro sono persino in grado di parlare. Attualmente, ci sono già 802 varietà di Pokemon. Nell\'universo Pokémon inventato, le persone sono chiamate allenatori di Pokémon, che addestrano per battaglie con i Pokémon di altri allenatori. E più l\'allenatore è esperto e forte, più rispetto gode. Fortunatamente, va notato che i combattimenti Pokémon non finiscono mai con la morte di queste creature uniche. Tutti i Pokémon hanno abilità diverse e differiscono per tipo di elemento, e la sua resistenza a diversi attacchi dipende fortemente da questo, e alcune creature hanno la capacità di due elementi contemporaneamente. Dopo aver vinto la battaglia, il Pokemon ottiene la preziosa esperienza necessaria per aumentare il livello e, di conseguenza, le sue caratteristiche. Oggi, l\'universo Pokémon è un\'enorme franchise mediatico e abbiamo deciso di preparare per te una collezione di cursori con alcuni Pokémon popolari. Tra questi, il più famoso è il cursore Pikachu, così come il cursore Rattata, il cursore Squirt, il cursore Bulbasaur e il cursore Charmander. Questo elenco verrà aggiornato, perché ce ne sono così tanti e ognuno di essi è unico a modo suo.',
    'famous_people_descr' => 'Tra le molte persone famose, ognuno di noi trova un modello di riferimento o semplicemente ammira il genio, il talento e la perseveranza di queste celebrità. Abbiamo preparato una collezione di cursori di celebrità per ispirarti e ricordarti i grandi risultati che ognuno di voi può incrementare. Non tutte le personalità famose hanno avuto un destino felice, ma ci insegnano la cosa principale: che non bisogna mai ritirarsi dal proprio obiettivo, nonostante le difficoltà e i problemi. Dopotutto, questo è il principio fondamentale per raggiungere il successo: andare verso il proprio sogno ogni giorno e, alla fine, diventare i migliori nel proprio campo. Forse oggi vuoi semplicemente cambiare il cursore del mouse, e domani tutta la tua vita cambierà in meglio! La collezione sarà costantemente aggiornata con nuovi e degni rappresentanti dell\'umanità. Tra questi, ovviamente, scienziati, politici, atleti, rappresentanti dell\'arte e molti altri. Il cursore George Washington, il cursore Michael Jordan, il cursore Stephen King, il cursore Elvis Presley e il cursore Marilyn Monroe sono solo l\'inizio.',
    'the_elder_scrools_descr' => 'The Elder Scrolls è una serie di giochi di ruolo per computer, uniti da un universo comune, meticolosamente progettato, che offre al giocatore un\'enorme libertà di scelta, permettendogli di visitare diverse aree e città del mondo fantasy e di esplorare nuovi luoghi e missioni in modo autonomo. Il lavoro sulla serie è iniziato nel 1992 e negli anni il gioco ha unito attorno a sé un\'enorme comunità di giocatori. Pertanto, su richiesta popolare, abbiamo rilasciato una collezione di cursori The Elder Scrolls, in modo che tu possa immergerti nell\'atmosfera unica del gioco. L\'eterna battaglia di cavalieri e draghi, da che parte stai? Cambia il cursore in un drago e unisciti all\'esercito di mostri sputafuoco o combatti nobilmente dalla parte delle persone scegliendo il cursore a spada e l\'immagine del tuo personaggio preferito: la decisione spetta a te! La cosa principale è che con la nostra nuova collezione, sei pronto per qualsiasi battaglia.',
    'halloween_descr' => 'Aspettando una notte mistica alla vigilia del Giorno di Ognissanti. La storia di Halloween risale a più di duemila anni fa. Forse questa è la festa più strana che combina divertimento e paura, nativa della cultura celtica. Allora la gente bruciava falò e indossava costumi spaventosi per allontanare i fantasmi. La parola "Halloween" fu menzionata per la prima volta nel XVI secolo come abbreviazione scozzese della frase inglese All-Hallows-Even. Papa Gregorio III dichiarò il 1° novembre il giorno di Ognissanti, e la sera prima era conosciuta come Vigilia di Ognissanti, e successivamente Halloween. In questo giorno, le persone indossano costumi di lupi mannari, fantasmi e altri mostri e vanno nelle case vicine, offrendo di comprare dolci. Feste a tema, fuochi d\'artificio, lanterne splendide, zucche e acrobazie creano un\'atmosfera unica. Vogliamo anche celebrare questa terribile festa con i cursori degli accessori e i personaggi di Halloween. Nella nostra collezione puoi trovare: cursore zombie, cursore fantasma, cursore gatto nero, cursore zucca e molto altro. Cambiare il tuo umore è ora facile come cambiare il tuo cursore con la nostra nuova collezione di Halloween.',
    'nfl_teams_descr' => 'Cosa c\'è di meglio per un vero appassionato di football americano di un cursore del mouse sotto forma di simbolismo della squadra per cui è tifoso? Nella moderna National Football League, trentadue squadre giocano, divise tra la National and American Football Conferences (National Football Conference, NFC e American Football Conference, AFC). A sua volta, ciascuna delle conference è divisa in quattro divisioni: East, North, South e West. La stagione NFL consiste in partite di pre-stagione, una stagione regolare e una serie di partite di playoff. La partita finale della stagione NFL si chiama Super Bowl ed è essenzialmente l\'evento sportivo più popolare negli Stati Uniti. Questo è un gioco preferito per milioni di fan e quindi abbiamo creato una collezione di cursori NFL in modo che tu non ti separi mai dai simboli della tua squadra preferita. Che si tratti dei New England Patriots, dei New York Giants, dei Buffalo Bills o di un\'altra squadra, sii sempre sulla stessa lunghezza d\'onda dei tuoi idoli, usando i nostri cursori a forma di logo e casco della squadra. La collezione sarà costantemente aggiornata in modo che tutti possano cambiare il cursore con l\'immagine della loro squadra preferita.',
    'five_nights_at_freddy_descr' => 'Il gioco davvero unico Five Nights at Freddy\'s ha rapidamente guadagnato una vasta popolarità e questo non sorprende, perché la sua trama semplice e allo stesso tempo affascinante può tenere i giocatori sugli schermi per ore. Abbiamo progettato i cursori di Five Nights at Freddy\'s su richiesta dei fan del gioco e siamo stati molto lieti di incarnare personaggi così interessanti e divertenti. Ma a differenza del gioco, nulla ti minaccia con i nostri cursori, quindi sentiti libero di scegliere i tuoi animatronics preferiti, che si tratti di Orso Freddy o Coniglio Bonnie o altri. La cosa principale è che ora il gioco prende vita nel tuo browser e regala nuove emozioni. Garantiamo che non ci sono fantasmi nei nostri cursori, ma trasmettono perfettamente lo spirito di un gioco che ispira paura a causa delle complessità del design e degli elementi della trama. Ma cosa succede se si imposta la dimensione del cursore molto grande? Riuscite a mantenere la calma e a non spaventarvi?',
    'komiksy_descr' => 'Potrebbe sembrare che il cursore del mouse sia un\'inezia, ma spesso sono questi dettagli che possono migliorare l\'umore, risvegliarti in una grigia mattina o semplicemente regalare emozioni vivaci. Una collezione di cursori di fumetti progettata appositamente per tutti gli amanti dei supereroi. Qui puoi trovare assolutamente tutto l\'Universo Marvel e DC Comics - da Iron Man a Thanos, Spider-Man e Hulk. Lo stile del cursore può essere sia sotto forma di un supereroe, sia sotto forma del suo personaggio. Un cursore non è solo un elemento funzionale; è importante in senso professionale. Ad esempio, se stai registrando un video dallo schermo, sarà meglio vedere un\'immagine luminosa e originale, e sembra molto più interessante. E naturalmente - chi non vorrebbe usare il guanto dell\'infinito nella vita reale? Cambiare il cursore del mouse è semplice: basta scaricare l\'estensione al tuo browser e aggiungere il cursore che ti piace alle tue impostazioni tramite esso. Puoi scegliere un cursore in base al tuo umore almeno ogni giorno. Basta con i giorni grigi - diventa un supereroe proprio ora!',
    'igry_descr' => 'I videogiochi sono diventati da tempo parte integrante delle nostre vite. Con il loro aiuto, puoi immergerti in un nuovo mondo, partecipare ad avventure e diventare una persona completamente diversa. Ognuno ha il suo giocattolo preferito, i cui personaggi sono già diventati quasi familiari. Un set di cursori basato su noti giochi per computer è un\'opportunità per diluire la noiosa vita quotidiana e aggiungere un po\' di creatività, vivacità e divertimento al flusso di lavoro. Il set contiene sia immagini degli eroi di gioco stessi, sia personaggi ausiliari, armi e icone di gioco. Scegli ciò che si adatta al tuo umore: i cursori di gioco piaceranno non solo ai giocatori, ma anche a tutti coloro che sono semplicemente stanchi della grigia quotidianità. Basta scaricare il set, cambiare il cursore del mouse e via, per completare le missioni, distruggere i nemici e raggiungere i tuoi obiettivi.',
    'multfilmy_descr' => 'Dentro ogni adulto c\'è ancora un bambino che ama i cartoni animati e sogna ancora di diventare uno degli eroi. Ti aiuteremo a realizzare i tuoi sogni: usa la nuova collezione di cursori basati sui cartoni animati più famosi e amati. Tom e Jerry, Buzz Lightyear e Shrek, Gravity Falls e persino Pokemon: puoi diventare quello che vuoi ogni giorno. Seleziona il cursore del mouse in base al tuo umore. Chi sei oggi? Un minion scapestrato e allegro che risolve facilmente qualsiasi problema o un forte e coraggioso Raffaello, il cui obiettivo non è solo compiere gesta, ma anche mangiare la pizza? Forse sei il genio onnipotente che tiene sotto il suo comando un intero ufficio? Nella collezione ci sono eroi per tutti - dalle principesse ai draghi - resta solo da decidere chi riflette l\'umore di oggi. Il Cursor Style non è solo una bella immagine. Questa è una riflessione dell\'individualità, dell\'espressione di sé e semplicemente - divertimento, gioia e positività per tutto il giorno. È noioso lavorare o troppo pigro per studiare? Sei diventato triste e non sei felice? Cambia il cursore e il mondo risplenderà di nuovi colori.',
    'kino_i_serialy_descr' => 'Film - sono magia, misticismo e solo un ottimo modo per rilassarsi, divertirsi e provare emozioni vivide. Allo stesso tempo, dopo aver guardato, ricordiamo ancora gli eroi preferiti che vorrei davvero incontrare nella realtà. Ora è possibile: basta scaricare la nuova raccolta di cursori basata su film e serie TV famose. I cursori luminosi e fantastici saranno un\'ottima aggiunta al desktop, trasformeranno la noiosa vita quotidiana grigia in una festa e i compiti banali in un\'avventura emozionante. Cambia l\'eroe del cursore ogni giorno - per umore, compiti o a caso. Chi sarai oggi? L\'onesto e giusto John Snow o l\'audace e implacabile John Wick? Forse hai una missione difficile da affrontare e solo Frodo può completarla? Forse oggi sei solo un alieno che non vuole entrare in contatto con gli altri? Scegli un cursore adatto: tira su il morale e allo stesso tempo mostra agli altri cosa pensi e come intendi trascorrere la giornata. Provalo: non è solo divertente, ma anche coinvolgente: non vorrai assolutamente tornare alla solita freccia.',
    'anime_descr' => 'Anime è un stile di animazione unico, che, nonostante la sua spiccata etnia, è stato apprezzato da milioni di persone in tutto il mondo. È improbabile che ci sia almeno una persona che non abbia guardato cartoni animati in questo stile. Abbiamo creato i puntatori in stile anime più cool che tutti i fan di questo stile ameranno. I puntatori standard sono noiosi e banali. Mostra la tua personalità: usa la collezione di puntatori Anime con i tuoi personaggi preferiti. Scegli il puntatore di una spada oscura se sogni avventure e battaglie coraggiose. Il simpatico uomo grasso Totoro ti rallegrerà anche nel giorno più triste, e Naruto ti motiverà nelle avventure e mostrerà a tutti quelli che ti circondano che sei un mega figo. I puntatori luminosi illumineranno la giornata lavorativa o renderanno il processo di apprendimento più interessante e divertente. Non limitarti: usa i tuoi motivi preferiti anche in elementi così piccoli come il puntatore del mouse. Cambia i puntatori ogni giorno, adattali al tuo umore e mostra la tua personalità: con i puntatori in stile anime è così semplice.',
    'futbol_descr' => 'Il calcio è uno sport speciale che include elementi di wrestling, atletica leggera e precisione. In generale, è spettacolare, spietato e raccoglie milioni di fan in tutto il mondo. Ti piace il calcio o ami semplicemente lo sport? Allora scarica un set di cursori nello stile del gioco famoso in tutto il mondo e dimostra di essere un fan leale. La collezione contiene 24 opzioni per la progettazione dei cursori: sotto forma delle squadre più popolari che meritano i loro titoli come un gioco disperato e persistente. I cursori sono realizzati in due versioni: sotto forma di un triangolo standard, decorato con i colori della squadra, o sotto forma di un casco di gioco corrispondente. Il cursore standard del browser è noioso e non degno di un vero appassionato di sport. Diventa originale e unico con la nostra collezione. Scarica le immagini e scegli i colori della tua squadra preferita o cursori personalizzati, se ami semplicemente lo sport e fai il tifo per tutti. Seguire i tuoi hobby è così semplice: non devi andare al lavoro con una sciarpa o un berretto della tua squadra preferita, è facile e veloce cambiare il cursore con un\'immagine brillante ed elegante.',
    'avtomobili_descr' => 'Ti piacciono le auto e ti diverti a guardare i modelli di diversi produttori? O sogni da molto tempo un marchio particolare, ma non hai ancora la possibilità di acquistarlo? Specialmente per te, abbiamo creato un set di cursori brillanti "Supercars". Qui troverai Ford classiche e Bentley eleganti, Lamborghini brillanti e Ferrari uniche. Vuoi diventare il proprietario dell\'auto originale? È semplice: scarica la nostra raccolta di cursori sul tuo dispositivo e cambia l\'immagine dell\'auto almeno ogni giorno. I cursori sono progettati in due versioni: come un\'auto a tutti gli effetti o come il suo simbolo. Scegli quello che ti piace di più o come preferisci lavorare. Tali immagini avranno un bell\'aspetto come cursori di gioco o semplicemente come un elemento insolito del desktop. Essere brillanti è semplice: non è necessario fare cose inimmaginabili per questo o cambiare il proprio aspetto. Basta smettere di usare oggetti comuni e scegliere ciò che ti piace veramente. La raccolta di cursori "Cars" è la scelta per chi non ha paura di mettersi alla prova.',
    'memy_descr' => 'I meme sono da tempo una parte familiare delle nostre vite. E chi di noi non ama queste immagini capienti, interessanti e originali per dispetto della giornata? Molti eroi dei meme sono diventati non solo popolari, ma hanno anche acquisito lo status di preferiti popolari, e frasi ed espressioni sono state a lungo incluse nel linguaggio colloquiale come espressioni ben consolidate. Presentiamo una raccolta dei migliori cursori basati sui meme più popolari. Con il loro aiuto, non solo puoi mostrare la tua personalità, ma anche esprimere il tuo umore. Sei stanco e stufo di tutto? Scegli un gatto arrabbiato che, con tutto il suo aspetto, esprime indignazione e ostilità verso tutto ciò che lo circonda. O oggi brilli di sarcasmo e non ti dispiace ridere? Allora Drake Bling sarà un eccellente accompagnamento: ti rallegrerà e renderà ogni compito originale e interessante. Installa l\'estensione, scarica la nostra raccolta e scegli uno stile di cursore per ogni giorno. Non è difficile essere brillanti e originali: cambia il design standard dell\'icona con uno degli eroi dei meme e ottieni una carica di energia per l\'intera giornata.',
    'emodji_descr' => 'Emoji - icone luminose e simpatiche, senza le quali non possiamo più comunicare abitualmente. Con il loro aiuto, non è necessario descrivere il tuo umore a parole - basta selezionare l\'icona desiderata e l\'interlocutore ti capisce senza ulteriori indugi. Nel nostro nuovo set di cursori, abbiamo incarnato l\'idea degli emoji: ecco come sono apparsi i divertenti e insoliti Cursoji che coloreranno il mondo e renderanno la vita più interessante. Con l\'aiuto dei cursus, non solo puoi lavorare ed eseguire compiti familiari, ma anche mostrare ai tuoi colleghi, amici e semplicemente agli altri il tuo umore. Un cursore assonnato è perfetto per il lunedì mattina, e un cursore che piange esprimerà un atteggiamento nei confronti di responsabilità aggiuntive. Un fantastico cursore con gli occhiali è la scelta migliore prima delle vacanze, e un cursore con i soldi negli occhi è un buon motivo per accennare al capo sull\'aumento degli stipendi. Usare Cursoji è divertente e interessante, che si tratti di lavoro, studio o presentazione. In quest\'ultimo caso, è persino consigliabile farlo se i colleghi hanno senso dell\'umorismo o hanno solo bisogno di stemperare la situazione. In generale, per qualsiasi compito - basta scegliere il corso giusto!',
    'pitomcy_descr' => 'Ti piacciono gli animali? Sicuramente - sono così carini, divertenti e molto buffi. Perché non passare l\'intera giornata in compagnia dei migliori amici dell\'uomo? Scarica la collezione di cursori Pets per te e scegli un amico per te ogni giorno. L\'icona del cursore può essere carina, come un alpaca bonario, o elegante, come un fenicottero rosa. O forse sarai occupato tutto il giorno e sceglierai un unicorno che legge un giornale, oppure semplicemente non vorrai comunicare con nessuno, come un gatto nero malvagio? Per ogni stato d\'animo, abbiamo un animale corrispondente. Un allegro carlino ti rallegrerà anche nella giornata più noiosa e grigia, e il cursore rosa a forma di unicorno mostrerà a tutti che non sei privo di un senso della bellezza, anche essendo un uomo barbuto brutale. E se non c\'è l\'umore e non ho voglia di fare compiti di routine? La ricetta è semplice: scarica la raccolta Pets, cambia il cursore del mouse - e voilà, il sole splende di nuovo, il tempo è bello e l\'umore è al massimo livello. Non c\'è da meravigliarsi se si dice che gli animali aiutano a combattere la depressione e la tristezza!',
    'stil_i_krasota_descr' => 'Nella nuova collezione di cursori, abbiamo raccolto un\'ampia varietà di soggetti che ci causano emozioni piacevoli e ci risollevano il morale. Questo set di cursori si chiama “Stile e Bellezza”, perché sono le tue cose preferite che determinano la nostra vita quotidiana, danno gioia e ci motivano a fare cose importanti, risvegliano il desiderio di migliorarci. Sei appassionato di spazio e sogni di andare su altri pianeti? Scegli un cursore NASA o un piatto di alieni - avvicinati al tuo sogno. Se non riesci a immaginare la vita senza musica o sei un rocker incallito, allora il cursore in stile chitarra elettrica fa per te. Il cursore con pennello, righello e compasso è stato appositamente sviluppato per gli ingegneri - tali immagini aiuteranno a trasformare calcoli e disegni noiosi in soluzioni originali. Una bacchetta magica e scarpe da ginnastica, uno skateboard e un rossetto, il sole e coni chimici - scegli quello che si adatta al tuo stile di vita, ai tuoi desideri e aspirazioni - e i compiti ordinari diventeranno più interessanti e i giorni feriali si tingeranno di nuovi e brillanti colori.',
    'prazdniki_descr' => 'Ti piacciono le vacanze? Ma a chi non piacciono - amici, regali, di nuovo lo stesso fine settimana. Per rendere l\'attesa delle vacanze più piacevole, più breve e più calda, puoi non solo contare i giorni sul calendario, ma anche impostare l\'icona corrispondente come cursore del mouse. Iniziamo con il Capodanno: sceglieremo un albero di Natale, un regalo o Babbo Natale, in modo che la festa sia luminosa e allegra. Forse l\'omino di pan di zenzero sarà più vicino - divertente, carino e sempre allegro? Con lui certamente non ci sarà tempo per essere tristi e annoiati. Continuiamo a festeggiare con cupidi e cuori allegri, e non c\'è molta strada per il Coniglietto Pasquale. Da qualche parte tra le vacanze, ci sarà un compleanno, che sarà ancora più piacevole aspettare con dei palloncini invece della freccia del cursore standard. E ad Halloween, puoi sorprendere colleghi e persone intorno a te con un insolito cursore del mouse a forma di un\'inquietante zucca o di un fantasma. Un set di cursori per le vacanze è un\'opportunità per rallegrare l\'attesa, sintonizzarsi in anticipo per il divertimento imminente e mantenere un ottimo umore non solo alla vigilia della festa, ma per tutto l\'anno.',
    'flagi_descr' => 'La bandiera è un simbolo unico ampiamente utilizzato in tutti i social network. Abbiamo pensato, perché non rendere il cursore una bandiera? Dopotutto, è davvero brillante e insolito. Ora puoi trascorrere ogni giorno in compagnia di un nuovo paese, e il lavoro non sarà così monotono e noioso. I cursori del mouse possono ora essere trasformati nella bandiera nazionale della Cina o degli Stati Uniti, del Giappone o del Canada, e in altre 38 opzioni di bandiera, e puoi scegliere la forma a freccia standard in un colore insolito o il cursore a forma di bandiera stessa. Questo set piacerà a tutti gli amanti dei viaggi. Con esso, puoi pianificare nuovi viaggi e sognare lunghi viaggi. Hai programmato una vacanza? Mostra a tutti in quale paese vuoi andare. Forse hai deciso di imparare una nuova lingua straniera? Allora questo cursore ti supporterà sicuramente e ti motiverà a studiare attentamente. O tu, come Sheldon, ami solo le bandiere? In tutti i casi, la collezione di cursori Flags sarà una fantastica aggiunta al tuo desktop e ti sposterà verso nuove scoperte.',
    'vokrug_sveta_descr' => 'A tutti piace viaggiare. Com\'è meraviglioso visitare nuovi paesi e città, vedere le attrazioni e divertirsi nella nuova cultura. È un peccato che possiamo viaggiare non così spesso, ma abbiamo cercato di porvi rimedio. Il set di cursori “In giro per il mondo” è una raccolta delle immagini più sorprendenti, simboli di diversi paesi, con l\'aiuto dei quali anche stando a casa puoi sentirti un vero viaggiatore. Nel nostro kit puoi trovare Giappone e Australia, Italia e Canada, USA e Messico - i paesi più interessanti, originali e pittoreschi del mondo. L\'immagine del cursore può diventare una freccia standard, nei colori della bandiera del paese, o diventare una delle principali attrazioni dello stato. Ad esempio, puoi aprire documenti con la Torre Pendente di Pisa e fare presentazioni utilizzando la Statua della Libertà. Garantiamo - il successo sarà assicurato. Beh, o se non il successo, allora i sorrisi dei colleghi e il riconoscimento dell\'originalità - di sicuro. Sì, e suggerire al management che è tempo di andare in vacanza sarà anche utile - basta impostare la valigia o l\'aereo come cursore - e molto probabilmente volerai molto presto.',
    'eda_i_napitki_descr' => 'Un set di cursori sotto forma di prodotti è un\'incredibile collezione di immagini luminose, gustose e stuzzicanti che sicuramente piaceranno a tutti e saranno una fantastica aggiunta al browser. Hai mai cliccato su broccoli o patatine fritte? Hai questa opportunità: basta scaricare un nuovo set di cursori e impostarli al posto di una noiosa freccia bianca. I cursori "Cibo" sono realizzati sia sotto forma di un puntatore triangolare standard, sia sotto forma di prodotti. Qui troverai verdure e frutta, i tuoi piatti preferiti, come pizza o hot dog, caffè, lecca-lecca e molto altro ancora, che rallegra qualsiasi giornata. Ami il caffè, ma berlo tutto il giorno non è un\'ottima idea? Integra la tua dieta con caffè virtuale, che ti rinvigorirà e ti sveglierà, oltre a regalare emozioni vivide. Un cursore ripido a forma di ciambella virtuale non danneggerà la figura, pur dando emozioni vivide e rallegria. Puoi usare i tuoi cursori preferiti o cambiare l\'immagine ogni giorno: una vasta selezione di cursori aiuterà a colorare la vita quotidiana e ad aggiungere nuovi colori alle azioni familiari.',
    'cvetnye_descr' => 'Il cursore è l\'elemento principale del browser, con il quale trascorriamo l\'intera giornata lavorativa, studiamo, comunichiamo e ci rilassiamo. La visualizzazione standard del cursore è noiosa e persino un po\' deprimente, ma comunque, per molte persone, questa forma è comoda e cambiarla sarà scomodo. Ma per questa situazione, abbiamo una soluzione: un set di cursori dai colori vivaci e allegri che aggiungeranno varietà alla tua vita quotidiana e renderanno la risoluzione di qualsiasi problema più facile e veloce. Se stai pensando a come cambiare il colore del cursore, rispondiamo: scarica la nostra raccolta e scegli soluzioni brillanti per ogni giorno! Puoi scegliere tonalità monocromatiche in diversi colori per adattarsi all\'umore o alle specifiche del lavoro. Ad esempio, quando si lavora con documenti standard, un cursore viola si distinguerà sullo sfondo e, su uno sfondo scuro, al contrario, sarà più facile lavorare con i cursori gialli. Se desideri un\'esplosione di colore, vivacità e massima originalità, scegli un cursore arcobaleno che includa tutti i colori dello spettro: con questa icona, l\'umore sarà sicuramente buono per tutto il giorno.',
    'prank_descr' => 'Gli scherzi sul lavoro non sono sempre graditi, in quanto spesso interferiscono con il flusso di lavoro. Ma con il nuovo set di cursori “Scherzi”, puoi fare gentilmente uno scherzo ai tuoi colleghi o amici senza danneggiare il tuo lavoro o studio. Abbiamo sviluppato una speciale collezione che divertirà chiunque e darà un motivo per rilassarsi un po\' in mezzo all\'intenso processo di lavoro o all\'esecuzione di un altro compito. Per cambiare il cursore del mouse, basta scaricare il kit sul dispositivo e selezionare il design che ti piace nei parametri. Ad esempio, puoi ottenere un cursore di forma standard, ma in uno stato invertito o una freccia curva da un\'onda. Questa forma non ostacolerà affatto il processo di lavoro, ma allo stesso tempo presenterà un umore meraviglioso e ti metterà di buon umore. Cambia le impostazioni di visualizzazione del cursore in base al tuo umore o ogni giorno - e qualsiasi compito diventerà più interessante e piacevole, e la vita di tutti i giorni smetterà di causare emozioni negative. Inoltre, tali cursori possono essere utilizzati anche per progetti seri - hanno colori neutri e non si distinguono dal desktop.',
    'startovyj_nabor_descr' => 'I cursor della collezione iniziale sono un mix di forme e dimensioni standard con un aspetto luminoso e insolito. Questa è una scelta eccellente per coloro che preferiscono le forme usuali, ma vogliono portare diversità, originalità e vivacità nella vita di tutti i giorni. La collezione ha un cursore a mano e una freccia familiare in una varietà di varianti - dal logo di Google Chrome alle emoticon, puoi persino incontrare qui un drago dimenticato da tempo con cactus e nostalgia. Dimostriamo che un cursore standard può anche essere interessante e attraente. Diversi colori, forme, trame e design interessanti ti aiuteranno a scegliere il cursore a tuo gusto o a cambiarlo ogni giorno a seconda dell\'umore o dei compiti svolti. Cambiare i cursori del browser è molto semplice: basta installare l\'estensione e scaricare la collezione sul tuo dispositivo. I cursori divertenti e interessanti non solo coloreranno i giorni lavorativi, ma aiuteranno anche, ad esempio, a rendere più interessante qualsiasi presentazione e, con l\'aiuto di cursori particolarmente luminosi, a richiamare l\'attenzione sui singoli elementi del report.',
    'fortnite_descr' => 'Fortnite ha conquistato milioni di persone in tutto il mondo. Battaglie emozionanti, strategia e tattica, avventure: ha assorbito assolutamente tutto ciò che piace tanto ai giocatori. Non abbiamo potuto tirarci indietro e abbiamo sviluppato una serie di cursori nello stile del gioco che piaceranno non solo agli accaniti giocatori, ma anche a coloro che hanno sentito parlare di Fortnite per la prima volta. L\'icona del cursore di Fortnite è un\'immagine di un eroe o della sua arma, curata fin nei minimi dettagli. Qui puoi trovare immagini di volpi e pesci, maschere di inferno e cavalieri neri, impostare una freccia o una falce con punte come freccia. Siamo sicuri che nessuno resterà indifferente! Essere spaventoso o misterioso, originale o umoristico: dipende da te. Scegli il tuo stile e seguilo, oppure imposta cursori personalizzati nelle impostazioni e cambia ruolo ogni giorno. Ora sarà molto più interessante e piacevole svolgere anche lavori noiosi e monotoni: il tempo volerà velocemente in compagnia di immagini vivaci e personaggi preferiti. O forse organizzerai competizioni con i colleghi, quale eroe sarà più forte? La scelta è tua!',
    'dota_2_descr' => 'DotA2 ora non è solo un semplice gioco, è un vero e proprio mondo parallelo. Nella realtà virtuale in DotA2, puoi fare di tutto: vivere, combattere, svilupparti, viaggiare, stringere amicizie. In generale, tutto come nella vita, solo a volte più interessante. I cursori di Dota 2 sono una continuazione di una strategia che ti permetterà di ottenere emozioni vivide ed esprimerti nel mondo reale. Un nuovo set di cursori include i personaggi più sorprendenti del gioco, così come oggetti originali che non possono essere confusi con nient\'altro. Scegli un cursore che ti sarà più vicino e intraprendi un\'avventura senza lasciare il tuo posto di lavoro. Come è noioso a volte essere al lavoro o svolgere compiti educativi, ma con i cursori di gioco questo problema non ti confronterà più. Un po\' di immaginazione, un cursore brillante - e voilà, qualsiasi attività sarà un\'avventura insolita, da affrontare che non sarà difficile e interessante. Non c\'è bisogno di trattenersi. Ti piace Dota? Allora assicurati di scaricare la nostra collezione, seleziona uno o più cursori casuali contemporaneamente - e ogni nuovo giorno diventerà più luminoso, più interessante e saturo.',
    'minecraft_descr' => 'I cursor del mouse sotto forma di frecce e dita standard sono diventati noiosi per tutti da tempo. Se sei un fan dell\'insolito e dell\'originale, allora è tempo di cambiare il cursore del mouse e dargli un design più interessante. Abbiamo sviluppato una collezione di cursori nello stile del famoso gioco Minecraft, dove puoi trovare i personaggi più sorprendenti. Lupo e volpe, Alex e Creeper, spada di diamante e pesce: puoi scegliere quello che ti piace di più o installare un nuovo eroe ogni giorno. Questi sono veri cursori per i giocatori e piaceranno assolutamente a tutti: dopotutto, chi di noi non ha giocato a Minecraft? Siamo sicuri che questi semplicemente non esistano. Abbasso la noiosa vita quotidiana: è tempo di immergersi in avventure, che possono essere fatte anche senza lasciare la sedia di casa o dell\'ufficio. Sarà più interessante preparare un rapporto e ridurre il saldo con una pistola: qualsiasi compito diventerà più piacevole e non ti farà annoiare sul posto. Scarica la nuova collezione di cursori di Minecraft: impostali e anche nel giorno più grigio e noioso il tuo umore sarà sempre al meglio. E i colleghi invidieranno i tuoi risultati: è semplicemente impossibile non fare il tuo lavoro con l\'aiuto degli eroi coraggiosi di Minecraft.',
    'sports-cars_short_descr' => 'Auto potenti e alla moda costruite per la velocità e l\'agilità',
    'spider-man' => 'Spider-Man',
    'astrology-signs-zodiac' => 'Segni Zodiacali',
    'astrology-signs-zodiac_short_descr' => 'Un insieme di 12 simboli astrologici che rappresentano tratti della personalità, energie cosmiche e schemi di vita.',
    'sports-cars' => 'Auto sportive',
    'sports-cars_descr' => 'Le auto sportive sono veicoli ad alte prestazioni progettati per un\'accelerazione rapida, una maneggevolezza precisa e un\'esperienza di guida entusiasmante. Da coupé eleganti a roadster agili, questa categoria presenta alcune delle macchine più iconiche costruite per l\'emozione della strada o della pista. Ideali per gli appassionati che amano la velocità, il design e la potenza. 🏎️🔥',
    'spider-man_short_descr' => 'Eroi dell\'universo di Spider-Man',
    'starwars' => 'Star Wars',
    'spider-man_descr' => 'Una collezione di personaggi ed eroi dell\'universo di Spider-Man. Include varie versioni di Spider-Man, alleati e stili unici provenienti da fumetti, giochi e serie animate. Ogni design riflette l\'agilità, il coraggio e l\'identità visiva che definiscono il mondo di Spider-Man.',
    'astrology-signs-zodiac_descr' => 'I Segni Zodiacali ♈♉♊♋♌♍♎♏♐♑♒♓ sono dodici divisioni simboliche della fascia celeste utilizzate in astrologia. Ogni segno è associato a date specifiche, elementi (🌍 Terra, 🔥 Fuoco, 🌊 Acqua, 💨 Aria), pianeti dominanti e caratteristiche uniche della personalità. Gli astrologi usano i segni zodiacali per interpretare il comportamento, prevedere la compatibilità ed esplorare i percorsi di vita. Che tu sia un appassionato Leone 🔥 o un premuroso Pesci 🌊, il tuo segno offre approfondimenti sul tuo mondo interiore. Questa categoria include tutti e 12 i segni, i loro significati e le rappresentazioni visive.',
    'starwars_short_descr' => 'Personaggi e simboli dell\'universo di Star Wars',
    'glitter' => 'Brillantini',
    'glitter_short_descr' => 'Cursori lucenti e scintillanti con stile glitter ✨🌟',
    'starwars_descr' => 'Immergiti nella galassia lontana, lontana con questa collezione che presenta eroi leggendari, potenti signori dei Sith, droidi, ribelli e altro ancora. Da Cavalieri Jedi a soldati delle tempeste, ogni icona porta lo spirito di Star Wars alla vita sotto forma di cursore. Perfetto per i fan di ogni trilogia. 🌌',
    'glitter_descr' => 'Una collezione glamour di cursori ispirati a texture glitterate ed effetti visivi luminosi. Perfetto per chi ama un\'estetica scintillante sul proprio schermo. Questi cursori portano brillantezza, eleganza e un po\' di magia a ogni clic.',
    'roblox-2025' => 'Roblox 2025',
    'roblox-2025_short_descr' => 'Personaggi dell\'ultima ondata di Roblox 🕹️🚀',
    'roblox-2025_descr' => 'Una nuovissima collezione 2025 con personaggi iconici e moderni di Roblox. Include i classici noob, leggende horror e avatar preferiti dai fan dei giochi più popolari. Progettato in uno stile divertente e colorato, perfetto per bambini e fan di Roblox di tutte le età.',
];
