<?php

return [
    'title' => 'Cursor Style - Informativa sui cookie',
    'descr' => 'Una politica sui cookie quando visiti il nostro sito web cursor.style o l\'estensione “Cursor Style”. Alcune regole che dovresti considerare quando utilizzi il nostro prodotto.',
    'text' => '<h2> Informativa sui cookie </h2>
<p> Quando visiti il nostro sito Web cursor.style o l\'estensione "Cursor Style" nel pannello del tuo browser, o quando interagisci con i nostri rappresentanti (il "Servizio"), utilizzeremo (e consentiremo a terzi di utilizzare) web beacon, cookie, pixel tag, script, tag, API e altre tecnologie ("Tecnologie di tracciamento"). Questo è spiegato in questa politica ("Informativa sui cookie"), che fa parte della nostra <a href="/privacy"> Informativa sulla privacy </a>. </p>
<p> Le tecnologie di tracciamento ci consentono di raccogliere automaticamente informazioni su di te e sul tuo comportamento su Internet al fine di migliorare la tua navigazione sul nostro Servizio, migliorare le prestazioni del nostro Servizio e facilitare la tua esperienza nel nostro Servizio. Utilizziamo queste informazioni anche per raccogliere statistiche sull\'utilizzo del nostro Servizio, condurre analisi, fornire contenuti adatti ai tuoi interessi e amministrare i servizi per i nostri Utenti, clienti e partner. Consentiamo inoltre a terzi di raccogliere informazioni su di te utilizzando le tecnologie di tracciamento. </p>
<p> Cosa sono i cookie? I cookie sono piccoli file di testo (composti solo da lettere e numeri) che il server web inserisce sul tuo computer o dispositivo mobile quando visiti una pagina web. L\'utilizzo di un cookie può contribuire a rendere i nostri Servizi più user-friendly, ad esempio, ricordando le tue preferenze di lingua e le tue impostazioni. Puoi trovare maggiori informazioni sui cookie su <a href="http://www.allaboutcookies.org"> allaboutcookies.org </a>. </p>
<p> I cookie sono ampiamente utilizzati per le prestazioni del sito web. L\'utilizzo dei cookie ti consente di navigare in modo efficiente tra le pagine. I cookie ricordano le tue preferenze e rendono l\'interazione tra te e i Servizi più fluida ed efficiente. </p>
<p> Utilizziamo tecnologie di tracciamento quando visiti o accedi ai nostri Servizi (di solito quando visiti i nostri siti web): vengono chiamate “Tecnologie di tracciamento proprietarie”. Inoltre, le tecnologie di tracciamento sono memorizzate da altre organizzazioni di terze parti (ad esempio, i nostri fornitori di servizi di analisi, partner commerciali e inserzionisti) che pubblicano contenuti sui nostri Servizi: vengono chiamate “Tecnologie di tracciamento di terze parti”. Entrambi i tipi di tecnologie di tracciamento possono essere memorizzati sia per il periodo della tua visita ai nostri Servizi, sia per le visite ripetute. </p>
<h3> Quali tipi di tecnologie di tracciamento utilizziamo? Esistono cinque tipi principali di tecnologie di tracciamento: </h3>
<ul>
<li> <b> Tecnologie di tracciamento strettamente necessarie </b> <br> <p> Queste tecnologie di tracciamento sono necessarie per consentirti di accedere, navigare e utilizzare le funzioni dei nostri Servizi o fornire il servizio che richiedi (ad esempio, il tuo nome utente). Non abbiamo bisogno del tuo consenso per utilizzare queste tecnologie di tracciamento. Queste tecnologie di tracciamento possono essere utilizzate per scopi di sicurezza e integrità, ad esempio per identificare violazioni delle nostre policy, nonché per funzionalità di supporto o sicurezza. </p> </li>
<li> <b> Funzionalità Tecnologie di tracciamento </b> <br> <p>
Queste tecnologie di tracciamento consentono ai nostri servizi di ricordare le tue scelte (come la lingua) e di fornire funzionalità avanzate e personalizzate. Ad esempio, queste tecnologie di tracciamento vengono utilizzate per l\'autenticazione (per ricordare quando sei loggato) e supportare altre funzioni dei nostri Servizi. </p> </li>
<li> <b> Tecnologie di tracciamento delle prestazioni </b> <br> <p>
Queste tecnologie di tracciamento raccolgono informazioni sulla tua attività online (ad esempio, la durata della tua visita ai nostri Servizi), inclusi dati comportamentali e indicatori di coinvolgimento dei contenuti. Queste tecnologie di tracciamento vengono utilizzate per analisi, ricerche e statistiche (sulla base di informazioni aggregate). </p> </li>
<li> <b> Marketing o pubblicità tecnologie di tracciamento </b> <br> <p>
Queste tecnologie di tracciamento vengono utilizzate per fornirti offerte speciali e pubblicità in base ai tuoi interessi, nonché per condurre campagne di email marketing. Possono anche essere utilizzate per limitare il numero di volte in cui un annuncio viene visualizzato, nonché per misurare l\'efficacia di una campagna pubblicitaria. Di solito sono ospitati dai nostri inserzionisti (ad esempio, reti pubblicitarie) e danno loro un\'idea delle persone che vedono e interagiscono con i loro annunci, visitano i loro siti Web o utilizzano la loro app. </p> </li>
<li> <b> Social Media Tracking Technologies </b> <br> <p>
Il nostro sito Web include le funzioni dei social network, come i pulsanti Mi piace o Condividi su Facebook e Vkontakte, o servizi di accesso di terze parti. Queste funzioni vengono pubblicate da terze parti o pubblicate direttamente sui nostri Servizi. La tua interazione con queste funzionalità è regolata dall\'informativa sulla privacy dell\'azienda che fornisce queste funzionalità. </p> </li>
</ul>
<h3> I seguenti sono i cookie che puoi trovare nei nostri Servizi: </h3>
<ul>
<li> <b> Cookie Analytics </b> <br> <p> Queste tecnologie di tracciamento vengono utilizzate per raccogliere informazioni su come interagisci con i contenuti nei nostri Servizi, scopi di attribuzione (ad esempio, URL di riferimento), ecc. Utilizziamo queste informazioni per compilare report, calcolare le entrate a noi dovute e aiutarci a migliorare i Servizi e offrire prodotti e contenuti personalizzati. </p> </li>
<li> <b> Google Analytics </b> <br> <p> Questo cookie viene utilizzato per raccogliere informazioni su come i visitatori utilizzano la nostra Piattaforma. Utilizziamo queste informazioni per compilare report e per migliorare la Piattaforma. I cookie raccolgono informazioni in forma anonima, tra cui il numero di visitatori della Piattaforma, da dove sono venuti i visitatori nella Piattaforma e le pagine che hanno visitato. <br> <a href = "https://policies.google.com/privacy?hl=en" > Informativa sulla privacy </a> </p> </li>
<li> <b> Google Tag Manager </b> <br> <p> Questo cookie è associato a Google Tag Manager, che utilizziamo per caricare script sulle pagine del nostro sito Web. <br> <a href = "https: / /policies.google.com/privacy?hl=en">Informativa sulla privacy </a> </p> </li>
</ul>
<p> Si prega di notare che non riconosciamo né rispondiamo agli avvisi automatici del browser relativi alle tecnologie di tracciamento, incluse le richieste Do Not Track. Tuttavia, ci sono vari modi per gestire e controllare le impostazioni dei cookie. Ricorda che quando elimini o blocchi i cookie, alcune funzioni dei Servizi potrebbero non funzionare correttamente o in modo così efficiente. </p>
<p> La maggior parte dei browser web fornisce alcune informazioni generali sui cookie, ti consente di vedere quali cookie sono memorizzati sul tuo dispositivo, ti consente di eliminarli tutti o singolarmente e ti consente anche di bloccare o consentire l\'uso dei cookie per tutti i siti web o singolarmente siti selezionati. Puoi anche disabilitare i cookie di terze parti separatamente. Tieni presente che le impostazioni offerte dal browser o dal dispositivo si applicano spesso solo a quel particolare browser o dispositivo. </p>
<h3> Le informazioni sui cookie si trovano solitamente nella sezione Guida di un browser web. </h3>
<p> I seguenti sono link ad alcuni browser web di uso comune: </p>
<p><a href="https://support.google.com/chrome/answer/95647?hl=en"> Chrome </a> <br>
<a href="https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies"> Internet Explorer e Microsoft Edge </a> <br>
<a href="https://support.mozilla.org/en/kb/kuki-informaciya-kotoruyu-veb-sajty-hranyat-na-vas"> Mozilla Firefox </a> <br>
<a href="https://support.apple.com/ru-ru/guide/safari/sfri11471/mac"> Safari </a> </p>
<p> Puoi disattivare alcuni cookie di terze parti per il targeting / la pubblicità facendo clic sul seguente link: <a href="http://optout.networkadvertising.org/?c=1"> Disattiva la pubblicità basata sugli interessi </a>. </p>
				',
];
