<?php

return [
    'title' => 'Сursor Style - Termini di utilizzo del nostro prodotto',
    'descr' => 'I termini di utilizzo sono stipulati tra te e “Cursor Style” (“Servizio”, “noi” o “Servizio”). Questo servizio è offerto e disponibile agli utenti di età pari o superiore a 13 anni solo per uso personale e non per uso commerciale.',
    'text' => '<h2> Termini di servizio </h2>
<h3> SI PREGA DI LEGGERE QUESTI TERMINI E CONDIZIONI PRIMA DI UTILIZZARE IL SITO WEB E L\'ESTENSIONE. </h3>
<p> Questi termini di utilizzo sono stipulati tra te e "Cursor Style" ("Servizio", "noi" o "Servizio"). I seguenti termini e condizioni, insieme a qualsiasi documento che includono espressamente per riferimento (collettivamente, questi "Termini di utilizzo"), regolano l\'accesso e l\'utilizzo del sito Web cursor.style e delle sue estensioni del browser, inclusi eventuali contenuti, funzionalità e servizi offerti su o tramite il nostro servizio (insieme il “Servizio”). </p>
<p> Utilizzando il sito Web o l\'estensione, accetti e accetti di rispettare questi Termini di utilizzo. Se non accetti questi Termini di utilizzo o la nostra <a href="/privacy"> Informativa sulla privacy </a>, non dovresti accedere o utilizzare il sito Web e l\'estensione. </p>
<p> Questo servizio è offerto e disponibile agli utenti di età pari o superiore a 13 anni solo per uso personale e non per uso commerciale. Utilizzando questo Servizio, dichiari e garantisci di avere (I) 13 anni o più, (II) non ti è vietato utilizzare i siti Web in conformità con la legge applicabile e (III) utilizzi il Servizio solo per le tue esigenze personali. Se non soddisfi questi requisiti, non dovresti accedere o utilizzare il Servizio. </p>
<p> Potremmo rivedere e aggiornare questi Termini di utilizzo di volta in volta a nostra discrezione. Tutte le modifiche entrano in vigore immediatamente dopo la loro pubblicazione. L\'utilizzo continuato del Servizio dopo la pubblicazione dei Termini di utilizzo rivisti significa che accetti e accetti le modifiche. Ci si aspetta che tu visiti frequentemente questa pagina per tenerti al corrente di eventuali modifiche in quanto sono vincolanti per te. </p>
<p> Ci riserviamo il diritto di ritirare o modificare questo sito Web e l\'estensione, qualsiasi servizio o materiale che forniamo sul sito Web e l\'estensione, a nostra esclusiva discrezione, senza preavviso. Non garantiamo che il nostro sito, l\'estensione o qualsiasi contenuto in esso contenuto saranno sempre disponibili o saranno interrotti. Non saremo responsabili se per qualsiasi motivo tutto o parte del Servizio non è disponibile in qualsiasi momento o per qualsiasi periodo. Di tanto in tanto, potremmo limitare l\'accesso a determinate parti del sito Web o dell\'estensione o dell\'intero Servizio per gli utenti. </p>
<p> Sei responsabile di adottare tutte le misure necessarie per assicurarti di avere accesso al Servizio. Assicurarsi che tutte le persone che accedono al Servizio tramite la tua connessione Internet siano a conoscenza di questi Termini di utilizzo e li rispettino. Per accedere al Servizio o ad alcune delle risorse che offre, potrebbe essere richiesto di fornire determinate informazioni o altre informazioni. Accetti che tutte le informazioni che ci fornisci utilizzando questo Servizio o in altro modo, incluso ma non limitato all\'utilizzo di qualsiasi funzione interattiva nel Servizio, siano regolate dalla nostra <a href="/privacy"> Informativa sulla privacy </a> e accetti tutte le azioni che intraprendiamo in relazione alle tue informazioni. in conformità con la nostra <a href="/privacy"> Informativa sulla privacy </a>. </p>
<p> Devi essere particolarmente attento quando inserisci informazioni personali nel Servizio su un computer pubblico o condiviso in modo che gli altri non possano visualizzare o registrare le tue informazioni personali. Il sito Web, l\'estensione e tutti i suoi contenuti, funzioni e caratteristiche (inclusi, ma non limitati a, tutte le informazioni, l\'estensione, testo, immagini, immagini e cursori, nonché il loro design, selezione e posizionamento) appartengono a "Cursor Style", i suoi licenziatari o altri fornitori di tali materiali sono protetti da copyright, marchio, brevetto, segreto commerciale e altre leggi sulla proprietà intellettuale o diritti di proprietà. </p>
<p> Questi Termini di utilizzo consentono di utilizzare i siti Web solo per uso personale e non commerciale. Non devi riprodurre, distribuire, modificare, creare opere derivate, ripubblicare, scaricare, archiviare o trasmettere alcun materiale sul nostro sito Web, ad eccezione dei seguenti casi: puoi utilizzarlo per esigenze personali, puoi stampare o scaricare una copia di una quantità ragionevole pagine del sito Web e dell\'estensione o dei loro contenuti per uso personale, non commerciale e non per un\'ulteriore riproduzione, pubblicazione o distribuzione. </p>
<p> Non devi modificare le copie di alcun materiale da questo sito o estensione e dai loro contenuti. Elimina o modifica qualsiasi avviso di copyright, marchio commerciale o altri diritti di proprietà dalle copie di questo sito e dall\'estensione. Non devi avere accesso o utilizzare per scopi commerciali alcuna parte dei siti Web o delle estensioni, nonché qualsiasi servizio o materiale disponibile tramite il sito Web o l\'estensione. </p>
<p> Se desideri utilizzare qualsiasi materiale su siti Web o estensioni diverso da quelli elencati in questa sezione, invia una richiesta nella pagina di supporto del Chrome Web Store. </p>
<p> Se stampi, copi, modifichi, scarichi o altrimenti utilizzi o fornisci a qualsiasi altra persona l\'accesso a qualsiasi parte del sito Web o dell\'estensione in violazione dei Termini di utilizzo, il tuo diritto di utilizzare il sito Web e l\'estensione termina immediatamente e devi , a nostra discrezione, restituire o distruggere eventuali copie dei materiali che hai. Qualsiasi utilizzo del sito Web dell\'estensione che non è espressamente consentito da questi Termini di utilizzo viola questi Termini di utilizzo e può violare copyright, marchi e altre leggi. </p>
<p> Il nome “Cursor Style”, il logo “Cursor Style” e tutti i nomi, loghi, immagini, cursori e nomi di servizi associati, design e slogan sono marchi di “Cursor Style” o delle sue affiliate o licenziatari. Non devi utilizzare tali marchi senza il previo consenso scritto del Servizio. Tutti gli altri nomi, loghi, nomi di prodotti e servizi, design e slogan su questo sito Web e nell\'estensione sono marchi dei rispettivi proprietari. Puoi utilizzare il Servizio solo per scopi legittimi e in conformità con questi Termini di utilizzo. </p>
<h3> Accetti di NON utilizzare il Servizio: </h3>
<ul>
<li> In alcun modo che violi qualsiasi legge o regolamento federale, regionale, locale o internazionale applicabile (inclusi, a titolo esemplificativo, eventuali leggi in materia di esportazione di dati o software in Russia e in altri paesi). </li>
<li> Allo scopo di sfruttamento, danno o tentativi di utilizzare o danneggiare minori, esponendoli a contenuti inappropriati, richiedendo informazioni che li identificano o altro. </li>
<li> Per inviare, ricevere consapevolmente, scaricare, utilizzare o riutilizzare qualsiasi materiale che non sia conforme a questi Termini di utilizzo. </li>
<li> Trasmettere o acquistare l\'invio di pubblicità o materiale promozionale senza il nostro previo consenso scritto, incluse eventuali "lettere indesiderate", "catene di Sant\'Antonio" o "spam" o qualsiasi altra offerta simile. </li>
<li> Per impersonare o tentare di impersonare un dipendente di “Cursor Style”, un altro utente o qualsiasi altra persona o organizzazione (incluso, a titolo esemplificativo, l\'utilizzo di indirizzi e-mail o alias associati a uno dei precedenti). </ li >
<li> Partecipare a qualsiasi altra azione che limiti o impedisca l\'uso del Servizio o l\'uso da parte di chiunque, o che, a nostro giudizio, possa danneggiare il Servizio o gli utenti del Servizio o renderli responsabili. </li> </ul>
<h3> Inoltre, accetti di NON: </h3>
<ul>
<li> Utilizzare il Servizio in alcun modo che possa disabilitare, sovraccaricare, danneggiare o degradare il funzionamento del sito, espandere o interferire con l\'uso del Servizio da parte di qualsiasi altra parte, inclusa la loro capacità di partecipare ad azioni in tempo reale tramite il Servizio. </li>
<li> Utilizzare strumenti di automazione, processi o mezzi per accedere al Servizio per qualsiasi scopo, incluso il monitoraggio o la copia di qualsiasi materiale nel Servizio. </li>
<li> Utilizzare qualsiasi processo manuale per tenere traccia o copiare qualsiasi materiale sul Servizio o per qualsiasi altro scopo non autorizzato senza il nostro previo consenso scritto. </li>
<li> Utilizzare qualsiasi dispositivo, software o procedura che interferisca con il normale funzionamento del Servizio. </li>
<li> Introdurre virus, cavalli di Troia, worm, bombe logiche o altri materiali dannosi o tecnologicamente dannosi. </li>
<li> Provare ad ottenere l\'accesso non autorizzato, interferire, danneggiare o interrompere qualsiasi parte del Servizio, il server su cui è archiviato il Servizio o qualsiasi server, computer o database connesso al Servizio. </li>
<li> Attaccare un Servizio utilizzando un attacco denial of service o un attacco denial of service distribuito. </li> </ul>
<p> Le informazioni fornite su o tramite il Servizio sono fornite esclusivamente a scopo informativo generale. Non garantiamo l\'accuratezza, la completezza o l\'utilità di queste informazioni. Ti affidi a tali informazioni esclusivamente a tuo rischio. Decliniamo ogni responsabilità e responsabilità derivante da qualsiasi dipendenza da tali materiali da parte tua, da altri visitatori del Servizio o da chiunque possa essere informato di uno dei loro contenuti. </p>
<p> Questo Servizio include contenuti forniti da terze parti, inclusi materiali forniti da altri utenti e licenziatari di terze parti, sindacatori, aggregatori e / o servizi di reporting. Tutte le dichiarazioni e / o opinioni espresse in questi materiali, così come tutti gli articoli e le risposte alle domande e altri contenuti, ad eccezione dei contenuti forniti dal Servizio, sono esclusivamente le opinioni e le responsabilità della persona o dell\'organizzazione che fornisce questi materiali. Questi materiali non riflettono necessariamente i punti di vista del Servizio. Non siamo responsabili nei confronti dell\'utente o di terze parti per il contenuto o l\'accuratezza di qualsiasi materiale fornito da terze parti. </p>
<p> Potremmo aggiornare il contenuto del Servizio di volta in volta, ma il suo contenuto non è necessariamente completo o attuale. Qualsiasi materiale sul Servizio potrebbe essere obsoleto in qualsiasi momento e non siamo tenuti ad aggiornare tale materiale. Possiamo aggiornare, modificare, modificare informazioni e contenuti sul sito Web e nell\'estensione, apportare modifiche e aggiornamenti in base alla nostra decisione. </p>
<p> Tutte le informazioni che raccogliamo su questo Servizio sono soggette alla nostra Informativa sulla privacy. Utilizzando il Servizio, accetti tutte le azioni intraprese da noi in relazione alle tue informazioni in conformità con l’<a href="/privacy"> Informativa sulla privacy </a>. </p>
<p> Termini aggiuntivi possono essere applicati anche a determinate parti, servizi o funzionalità del Servizio. Tutti questi termini e condizioni aggiuntivi sono qui incorporati per riferimento in questi Termini di utilizzo.
Puoi collegarti al nostro sito Web o estensione se lo fai in modo onesto e legale e non danneggi la nostra reputazione o la usi, ma non dovresti impostare il collegamento in modo tale da offrire qualsiasi forma di associazione, approvazione o approvazione da parte nostra senza il nostro consenso scritto. </p>
<p> Il servizio contiene collegamenti ad altri siti e risorse forniti da terze parti, questi collegamenti sono forniti solo per tua comodità. Ciò include i collegamenti contenuti negli annunci pubblicitari, inclusi banner pubblicitari e collegamenti sponsorizzati. Non controlliamo il contenuto di questi siti o risorse e non siamo responsabili per loro o per eventuali perdite o danni che potrebbero derivare dal loro utilizzo. Se decidi di accedere a siti Web di terze parti associati a questo Servizio, lo fai a tuo rischio e in conformità con i termini di utilizzo di tali siti Web. Ci riserviamo il diritto di revocare l\'autorizzazione a collegare senza preavviso. </p>
<p> Comprendi che non possiamo e non garantiamo o garantiamo che i file disponibili per il download tramite Internet o sui siti Web non conterranno virus o altri codici dannosi. Sei responsabile dell\'implementazione di procedure e punti di controllo sufficienti per soddisfare i tuoi requisiti speciali per la protezione antivirus e l\'accuratezza dell\'input e dell\'output dei dati, nonché per il mantenimento di mezzi esterni al nostro sito per il ripristino di eventuali dati persi. NON SAREMO RESPONSABILI PER ALCUNI DANNI O LESIONI CAUSATI DA ATTACCHI DISTRIBUITI A DENIAL SERVICE, VIRUS O ALTRI MALWARE TECNOLOGICI OTTENUTI TRAMITE IL SERVIZIO O TRAMITE IL DOWNLOAD DI QUALSIASI MATERIALE PUBBLICATO SU QUESTO O SU QUALSIASI SITO WEB, CORRELATO A, POTREBBE INFETTARE O DANNEGGIARE IL TUO APPARECCHIATURA INFORMATICA, SOFTWARE INFORMATICO, DATI. </p>
<p> L\'UTILIZZO DEL SERVIZIO, DEI SUOI CONTENUTI E DI QUALSIASI SERVIZIO O ARTICOLO OTTENUTO TRAMITE I SERVIZI È A TUO ESCLUSIVO RISCHIO. IL SERVIZIO, I SUOI CONTENUTI E QUALSIASI SERVIZIO O ARTICOLO OTTENUTO TRAMITE IL SITO WEB E L\'ESTENSIONE, SONO FORNITI "COSÌ COME SONO" E "COME DISPONIBILI", SENZA ALCUNA GARANZIA. QUALSIASI PERSONA ASSOCIATA AL SERVIZIO NON FORNISCE ALCUNA GARANZIA O DICHIARAZIONE IN MERITO A COMPLETEZZA, SICUREZZA, AFFIDABILITÀ, QUALITÀ, ACCURATEZZA O ACCESSIBILITÀ DEL SERVIZIO. SENZA LIMITAZIONE, NESSUN “CURSOR STYLE” O RAPPRESENTANTI CORRELATI A “CURSOR STYLE” NON GARANTISCE CHE IL SITO, L\'ESTENSIONE, I SUOI CONTENUTI O QUALSIASI RIPARAZIONE DOVREBBERO ESSERE PRECEDENTEMENTE DISPONIBILI, CHE LA NOSTRA ESTENSIONE, UN SITO O UN SERVER CHE LA POSIZIONA, SARANNO PRIVI DI VIRUS O ALTRI COMPONENTI DANNOSI O QUESTO SITO WEB O QUALSIASI SERVIZIO O ARTICOLO ESEGUITO, PREFERENZIATO.
<p> In nessun caso il SERVIZIO, LE SUE AFFILIATE O LICENZIATARI, SERVIZI, DIPENDENTI, AGENTI, FUNZIONARI O DIRETTORI SARANNO RESPONSABILI PER DANNI DI ALCUN TIPO, NOI SERVIZIO A QUALISiasi RESPONSABILITÀ. O TALI ALTRI SITI WEB O QUALSIASI SERVIZIO O ARTICOLO OTTENUTO NEL SERVIZIO O IN ALTRI SITI WEB, COMPRESI DANNI DIRETTI, SPECIALI O CONSEQUENZIALI, INCLUSE LESIONI PERSONALI, DISTURBI EMOTIVI, DANNI O RISPARMI ATTESI, PERDITA DI UTILIZZO, DATI O ALTRE CONDIZIONI. LA DEFINIZIONE NON INFLUISCE SU ALCUNA RESPONSABILITÀ CHE NON POTREBBE ESSERE ESCLUSA O LIMITATA IN CONFORMITÀ CON LA LEGGE APPLICABILE CHE PUÒ INCLUDERE FRODE. </p>
<p> Accetti di proteggere, indennizzare e neutralizzare il “Cursor Style”, le sue affiliate, licenziatari e fornitori di servizi, nonché i suoi e i loro rispettivi funzionari, direttori, dipendenti, appaltatori, agenti, licenziatari, fornitori, cessionari e da qualsiasi reclamo e responsabilità, perdita di sentenze del tribunale, costi, spese o commissioni (incluse le spese legali) derivanti da o in relazione alla tua violazione di questi Termini di utilizzo o all\'utilizzo del Servizio, incluso ma non limitato al reato di qualsiasi utilizzo del contenuto, dei servizi e dei prodotti del sito Web o delle estensioni, ad eccezione di quanto espressamente previsto in questi Termini di utilizzo, o l\'utilizzo di qualsiasi informazione ricevuta dal Servizio. </p>
<p> Se una qualsiasi disposizione di questi Termini di utilizzo viene ritenuta non valida, illegale o inapplicabile da un tribunale o da un altro tribunale della giurisdizione competente per qualsiasi motivo, tale disposizione deve essere abrogata o limitata al minimo, in modo che il resto delle disposizioni dei Termini di utilizzo continuerà al massimo. I Termini di utilizzo, la nostra Informativa sulla privacy e le condizioni per la registrazione degli eventi costituiscono l\'unico e completo accordo tra te e “Cursor Style” in merito al Servizio e sostituiscono tutti gli accordi, accordi, dichiarazioni e garanzie precedenti e simultanei, sia scritti che orali, in merito al Servizio . </p>
<p> Tutte le recensioni, i commenti, le richieste di supporto tecnico e altri messaggi relativi al Servizio devono essere indirizzati alla pagina di supporto di “Cursor Style” nel Chrome Web Store. </p> ',
];
