version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/cursor.style
    overwrite: true

permissions:
  - object: /var/www/cursor.style
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory
  - object: /var/www/cursor.style
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file