<?php

return [
    'halo_descr' => 'Halo er en kampsport-fantasy mediefranchise skapt av Bungie. Basert på den originale trilogien med førstepersons skytespill. Handlingen dreier seg om hendelsene som foregår i livet til Master Chief, en av en gruppe supersoldater med kodenavnet Spartans, og hans følgesvenn, den kunstige intelligensen Cortana. Suksessen til spillene har ført til utvidelsen av franchisen til andre medier: Halo-universet spenner for tiden over mange bøker, grafiske romaner, tegneserier, kortfilmer, animasjoner og spillefilmer.',
    'halo_short_descr' => 'Berør artefaktmarkøren, kanskje du er den utvalgte',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'LOL Surprise-dukker forelsket seg i barn og vant deres hjerter fra de første minuttene. Og dette er ikke overraskende, fordi en slik suksess er basert på et mysterium, forventningen om et mirakel, en hyggelig overraskelse, som gleder ikke bare barn, men også foreldrene deres. Hemmeligheten bak gaven avsløres for barnet først etter den endelige utpakkingen. I alle fall er LOL-dukker et attraktivt design, intriger, et stort antall fantastiske og realistiske tilbehør og hyggelige småting, samt den høyeste kvaliteten på produksjonen og detaljeringen av leken.',
    'lol_surprise_short_descr' => 'Kule søtinger for kjennere av vakre overraskelser',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Serien handler om en konkurranse der 456 spillere, som alle er dypt i økonomisk gjeld, risikerer livet for å spille en serie med dødelige barnespill for å vinne en milliard i premie. Inne venter en fristende premie med dødelig høye innsatser. Tittelen på serien er hentet fra et tilsvarende koreansk barnespill. Hwang hadde unnfanget ideen basert på sine egne økonomiske vanskeligheter tidlig i livet, samt klasseskillet i Sør-Korea og kapitalismen.',
    'squid_game_short_descr' => 'Velg den riktige spilleransiktet når du går all-in',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter er hovedpersonen i en serie romaner av den engelske forfatteren JK Rowling. På sin ellevte bursdag får Harry vite at han er en trollmann og er bestemt for en plass på Galtvort høyere skole for hekseri og trolldom, hvor han vil praktisere magi under veiledning av rektor Albus Humlesnurr og andre skoleprofessorer. Harry oppdager også at han allerede er kjent i hele romanens magiske samfunn, og at hans skjebne er knyttet til skjebnen til Voldemort, en farlig mørk magiker.',
    'harry_potter_short_descr' => 'Hva vil du gjøre med en tryllestav fra samlingen av Harry Potter-markører',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics er et tegneserieforlag kjent for å skape kjente superhelter som Spider-Man, Iron Man, Captain America, Hulk, Thor, Avengers, Guardians of the Galaxy, X-Men, Fantastic Four og Deadpool. Marvels mest kjente skurker inkluderer Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom og Magneto. Marvel Comics og DC Comics har samarbeidet om flere crossover-prosjekter sammen og var også med på å grunnlegge det med vilje kortvarige utgivelsesmerket Amalgam Comics.',
    'marvel_comics_short_descr' => 'Superhelten bor i oss alle - velg din',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Velkommen tilbake til Cookie Kingdom i Cookie Run: Kingdom av Devsisters, det bedårende strategispillet satt i Cookie Run-universet. Nå som GingerBrave har rømt den onde heksens ovn, er det på tide for ham å bygge et lag med Cookies og legge ut på et oppdrag for å gjenoppbygge det falne Cookie Kingdom. Avslør sannheten bak Kingdom\'s fall og sett sammen en gruppe av Kingdom\'s mektigste Cookies for å beseire de mørke kreftene som ønsker å hindre GingerBrave i å oppfylle sin skjebne.',
    'cookie_run_kingdom_short_descr' => 'Små krigere rett ut av ovnen',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact er et eventyrspill i åpen verden. Dette betyr at et nytt, herlig landskap venter deg på den andre siden av elven eller fjellet, du må bare bruke energien din fornuftig. Hvis du kommer over en vandrende fe eller en merkelig mekanisme, våg og prøv å løse mysteriet deres. Men hva de lover - problemer eller en hyggelig overraskelse - bare du kan finne ut! På det enorme kontinentet Teyvat vil du besøke syv riker, finne følgesvenner med forskjellige ferdigheter og kjempe mot mektige fiender i søket etter en savnet kjær.',
    'genshin_impact_short_descr' => 'Bli elementarmester av de syv kongedømmene',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Når en eldgammel profeti slår inn og kongeriket stuper inn i vinterens favn, drar tre fryktløse helter - prinsesse Anna, modige Kristoffer og hans trofaste reinsdyr Sven - til fjells for å finne Annas søster, Elsa, som kan fjerne den iskalde forbannelsen fra landet. Underveis venter mange vanskelige overraskelser og spennende eventyr på dem. Møter med mystiske troll, møtet med en sjarmerende snømann ved navn Olaf, fjelltopper brattere enn Everest og mye magi. Heltene må motstå de mektige elementene for å redde kongeriket og de som er dem kjære.',
    'frozen_short_descr' => 'Å bryte isen er enkelt med samlingen av Frozen-markører',
    'frozen' => 'Frozen',
    'stranger_things_descr' => 'Litt over seks måneder har gått siden finalen i den tredje sesongen. Joyce, Will, Eleven og Jonathan har flyttet til California hvor jenta blir mobbet på skolen. Resten begynner å kjempe mot et nytt monster fra en parallell verden som har dukket opp i Hawkins. Han ble kalt Vecna ​​etter Dungeons & Dragons brettspillkarakteren. Det påvirker tenåringer psykologisk, og klatrer deretter mentalt inn i hodet og dreper. Parallelt lærer Joyce og Murray at Jim Hopper er i live og drar etter ham til et sovjetisk fengsel i Kamchatka. Og Eleven må tilbake og øke kreftene sine, men også lære sin viktige rolle i å skape det samme monsteret i Gokins.

Forfatterne endret ikke plottaktikken de likte de siste sesongene. I den fjerde sesongen delte de den store gruppen av hovedpersoner inn i grupper, kom opp med vanskelige oppgaver for dem, og til slutt bygde historiene deres sammen i en fantastisk avslutning. Vi tilbyr deg å forstå alle disse eventyrene i detalj ved hjelp av Stranger Things cursors-samlingen.',
    'stranger_things_short_descr' => 'Hva skjer videre? - Stranger Things 4-markører',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars er en original modus som dukket opp for første gang i Minecraft. Oppgaven til spillerne var at brukeren skulle beskytte basen og sengen sin.

Roblox bringer mer spennende spill hver dag, og BedWars er intet unntak. Og det er slik at hvis du elsker bed wars og forsvarer deg i rommet ditt, er dette tittelen for deg fordi den tar deg tilbake til barndommen, om enn digitalt denne gangen.

Alt du trenger å gjøre er å forsvare sengen din fra angripere med partneren din. Du går inn i en lobby, velger hvem du vil spille med, og voila, det er bare et spørsmål om beskyttelse.

Selvfølgelig, når det kommer til forsvar, vil du ha noen problemer, og det er visse ressurser, gjenstander og ting som vil hjelpe deg å vinne. For eksempel eksklusive skins som du finner i Bed Wars cursor-kolleksjonen.',
    'roblox_bed_wars_short_descr' => 'Beskytt sengen din med Roblox Bed Wars-markører',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'På Naruto Uzumakis fødselsdag angrep en legendarisk demon, Ni-halede Reven, en landsby kalt Konoha. Den fjerde Hokage, på bekostning av sitt liv, reddet landsbyen ved å forsegle demonen i den nyfødte Naruto, uvitende om å dømme ham til et liv med hat fra sine landsbyboere.
Til tross for sin mangel på talent på mange områder av ninjutsu, rastløshet og snobberi, drømmer Naruto om å bli Hokage, den sterkeste ninjaen i landsbyen. Ønsker anerkjennelsen han ikke fikk, jobber han hardt og trener sammen med lagkameratene Sasuke Uchiha og Sakura Haruno, samt mentoren Kakashi Hatake. Han og partnerne hans må gå gjennom mye på veien til sine kjære drømmer: kamper, kjærlighet, vennskap, svik, tørst etter makt. En samling av Naruto anime-markører vil hjelpe deg med å navigere din egen vei!',
    'naruto_anime_short_descr' => 'Gå din ninja-vei med Naruto anime-markører',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'Handlingen foregår i Taisho-perioden. Siden antikken har det vært rykter om at humanoide demoner lever i skogen, som lever av mennesker og går om natten på jakt etter et nytt offer. Men... det er bare en legende, ikke sant?..

Tanjiro Kamado er den eldste sønnen i familien, som mistet faren og tok vare på familien sin. En dag drar han til en nærliggende by for å selge trekull. Når han kommer tilbake om morgenen, oppdager gutten et forferdelig bilde foran seg: alle slektningene ble brutalt drept, og den eneste overlevende er Nezuko, en yngre søster som ble forvandlet til en demon, men som ennå ikke har mistet all sin menneskelighet.

Fra dette øyeblikket begynner Tanjiro og Nezuko en lang og farlig reise, der gutten har tenkt å finne morderen og finne en måte å helbrede søsteren sin på. Men er barna i stand til å overvinne alle vanskeligheter og komme hjem igjen? Du vet allerede svaret, og hvis ikke - sett heller markørene Demon Slayer, med karakterer fra en av de mest populære mangaene.',
    'demon_slayer_anime_short_descr' => 'Demon Slayer markører - for ekte nattejegere',
    'demon_slayer_anime' => 'Demon Slayer anime',
    'bts_descr' => 'BTS er en syv medlemmer stor guttegruppe under BigHit Music. De debuterte 13. juni 2013 med singelen "No More Dream". I Japan debuterte de 24. desember 2014 med studioalbumet Wake Up.

Gruppens navn kommer fra det koreanske uttrykket Bangtan Sonyeondan, som betyr "skuddsikre guttespeidere". Ifølge J Hope, betyr navnet bandets ønske om å blokkere stereotypier, kritikk og forventninger som er rettet mot tenåringer som kuler.

Samlingen av markører dedikert til gruppen inkluderer alle medlemmene av gruppen, her Kim Nam Joon markør (aka RM), Kim Seok Jin markør (Jin), Min Yoongi markør (Suga), Jung Ho Suk markør (J-Hope), Park Ji Min markør (Jimin), Kim Tae Hyun markør (V) og Jeon Jungkook markør (Jungkook).',
    'bts_short_descr' => 'Møt dine idoler med BTS-markører',
    'bts' => 'BTS',
    'miraculous_descr' => 'Miraculous: Tales of Ladybug and Cat Noir, bedre kjent som Miraculous Ladybug og Cat Noir, er eventyrene til superhelter fra tegnefilmen om to klassekamerater som, under masker, spiller rollen som forsvarere av Paris fra en skurk som i hver episode kommer opp med en ny måte å skade byen. Miraculous er laget i Frankrike ved hjelp av CGI og animasjon. Miraculous er ikke bare en animert serie, men også en samling tegneserier utgitt rundt om i verden. Serien er veldig elsket av det unge publikummet.

Handlingen foregår i Paris, hvor Marinette og Adrian er videregåendeelever på en moderne skole. De fikk rollen som de utvalgte i kampen mot det onde, og reddet hjembyen sin. Målet deres er å beskytte folk mot Akumas. Disse små skapningene i form av sommerfugler er i stand til å bo i en person og forvandle ham til en skurk.

Marinette kan forvandles til en marihøne, og Adrian - til en Cat Noir, men overraskende nok, når de jobber i par, kjenner de ikke hverandre igjen under maskene til superheltene.

Hjelp Cat Noir og Ladybug med å redde Paris med våre markører med favorittkarakterene dine. Hvilken karakter vil du velge for markøren? Vil det være en Miraculous Ladybug-markør, eller kanskje Tikki sin søte lille marihøne- eller Cat Noir-markør? Eller kanskje en Queen Bee med Rena Rouge-markører? Valget er ditt!',
    'miraculous_short_descr' => 'Bli med i superhelt-rekkene med samlingen av Ladybug og Cat Noir markører',
    'miraculous' => 'Miraculous: Tales of Ladybug & Cat Noir',
    'talking_tom_descr' => 'Serien følger hverdagen til Talking Tom og vennene hans. Tom og hans nerdete forretningspartner Ben utvikler stadig mobilapper og andre oppfinnelser for å oppnå berømmelse og formue og prøver å vise seg frem for verden, men dette slår alltid feil. Toms kjæreste, Angela, prøver å være sanger, uansett hva hun gjør for å oppnå det. Toms nabo, Ginger, stikker veldig ofte innom her for å gjøre sprell med ugagn i ermet. Den dumme bestevennen og romkameraten Hank er hjemmeværende og ser VELDIG på TV. Og den tidligere dissidente popstjernen Becca Sparkles har blitt Angelas nye romkamerat og ser ut til å ha forelsket seg i Hank. Uansett hvor ille ting er av alle former og størrelser, enten det er den onde administrerende direktøren, Toms mystiske nye nabo, eller bare en ulykke i Bens nye kreasjon, vil gjengen ha det gøy uansett, og alltid huske én ting som holder dem sammen: vennskap tar aldri slutt, akkurat som vår kjærlighet til karakterene i serien ikke tar slutt, så nå kan du sette deg Talking Tom-markøren eller Ben-markøren, eller kanskje Angela-markøren, Oliver-markøren!',
    'talking_tom_short_descr' => 'La oss snakke om favorittkarakteren din i Talking Tom Cursor Collection',
    'talking_tom' => 'Talking Tom og venner',
    'lego_descr' => 'The LEGO Group-selskapet ble grunnlagt tilbake i 1932 og besto da av bare 7 personer. Lego-teamets mål var å skape leker som utvikler et barns kreativitet, fantasi og oppfinnsomhet. En fantastisk fakta, siden starten i 1949, har LEGO-elementer i alle sine varianter forblitt kompatible med hverandre. Alle elementer som er laget senere er fremdeles kompatible med elementer som slippes i dag, til tross for endringer i design og form gjennom årene.

En LEGO-kloss er en base, som er en hul plastblokk som kobles til andre lignende klosser. Men Lego-sett inneholder også andre deler, hjul, figurer, plattformer og til og med elektroniske kretser med sensorer og elektriske motorer. Du kan samle modeller av biler, fly, tog, skip, bygninger, roboter. LEGO holder seg til ideen om modularitet, som tydelig demonstrerer for barn hvordan de skal løse visse problemer, utvikle fantasi, finmotorikk i hender og monteringsferdigheter. LEGO-klosser er laget med utrolig presisjon og passer perfekt sammen for fantastisk 10 mikron presisjon.

Nylig er mange populære 3D-animerte Lego-historier skapt, der karakterene fra settene kommer til liv og blir deltakere i utrolige eventyr. Hvis du vil ha en kul markør, finner du mange karakterer fra Lego TV-serien og animasjonsfilmer i vår Lego Cursors-samling. Lego Ninjago Cursor, Lego Batman Cursor, Lego Ninjago Cursor, Lego Wyldstyle Cursor og mange flere.',
    'lego_short_descr' => 'Bygg din drømme nettleser med Lego markør samlingen',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Etter vellykket Kickstarter-finansiering, i 2017, ga Team Cherry ut multiplatform PC-spillet Hollow Knight. Dette er historien om en navnløs ridder og hans oppdagelser i Hallownest-insektriket. Spillet ble med rette anerkjent som et av de beste i metroidvania-sjangeren.

Spillet i Hollow Knight er basert på utforskning av spillverdenen. Å overvinne hindringer, løse gåter og finne hemmeligheter, samt å kjempe mot fiender. Spilleren har et unikt sett med forbedringer og triks for å utforske verden og kjempe i kamper. Ved å bevege seg fra sone til sone, beseirer spilleren sjefer og får de nødvendige forbedringene for å komme videre. Som et resultat må spillere besøke de allerede passerte områdene for å finne hemmeligheter og gå gjennom historien. Og det er også spennende fordi sonene endres hver gang, og bringer nye overraskelser og opplevelser. Spillet kan spilles på forskjellige måter, fordi det er flere forskjellige veier mellom sonene. Ved å gå gjennom historien, åpner du sonekartet, men først må du få kartet.

Heltenes hovedvåpen er en spiker, som på en måte ligner et sverd, våpen kan forbedres med en smed, samt lære forskjellige ferdigheter i å bruke våpen, noe som utvider utvalget av angrep. Ved å angripe fiender, akkumulerer du en spesiell ressurs, som senere kan brukes til forbedringer eller helbredelse.
Ha det gøy med å spille Hollow Knight og ikke glem Hollow Knight-markørene våre med favorittkarakteren din. Samlingen vår inkluderer Mister Mushroom Cursor, Quirrel Cursor, Hornet Needle Cursor, Old Nail Cursor, Myla Cursor og andre.',
    'hollow-knight_short_descr' => 'Prøv å ikke gå deg vill i insektriket ved å bruke Hollow Knight samlingen av markører',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman er hovedpersonen i serien. Stikmin, tidligere uten navn, startet som en mindre tyv, med et ønske om å tjene raske penger raskt. Etter å ha rømt fra West Mesa-fengselet skjer det imidlertid mange endringer i livet hans, og han blir en berømt forbryter etter å ha stjålet den tunisiske diamanten. Henry har et valg - å bli en vellykket regjeringsagent, dusørjeger, leder av en kriminell organisasjon, cyborg, eller fortsette den kriminelle veien alene. Spillet gleder fans av sjangeren med mange eventyr og mysterier, og du finner vår nye samling av Henry Stickman-markører med sine morsomme karakterer, inkludert Henry Stickmin-markøren, Charles Calvin-markøren, Reginald Copperbottom-markøren, Right Hand-markøren, Ellie Rose-markøren og andre!',
    'henry-stickmin_short_descr' => 'Planlegg rømmingen din fra kjedsomhet med Henry Stickman Cursors Collection',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'Det svært populære nettspillet Adopt Me ble lansert i 2017 og ble det mest populære på Roblox-spillplattformen. Essensen i spillet er veldig enkel - få egg med kjæledyr og ta vare på dem.

Virituelle kjæledyr er delt inn i 5 klasser, noen av dem er svært sjeldne og dyre, mens andre er veldig enkle å få tak i. Dette er Uncommon-grupper, som Blue Dog, Common, Rare cursor, for eksempel Adopt Me Monkey musepeker, samt ultra-sjeldne, som Koala cursor, og Legendary, Dragon cursor og Accept me unicorn. Hvis spilleren har fire voksne kjæledyr av samme type, kan de kombinere til et neonkjæledyr, som Neon Horse spillpeker eller Adopt Me Neon Starfish. Ved å kombinere fire vanlige kjæledyr, kan du lage et neonkjæledyr som virkelig skinner, og fra neonkjæledyr kan du lage et mega-neonkjæledyr.

 Shopping i spillet Adopt Me! utføres med den virtuelle valutaen Roblox - den såkalte Robux, og spillet har også sin egen valuta - Bucks. Ved å ta vare på kjæledyret ditt, i tillegg til underholdning, kan du tjene bucks, bare mate ham, legge ham til sengs eller lese et eventyr, generelt sett mange interessante ting.

Nå kan fans av Roblox-spillet "Adopt Me!" dekorere spillpekeren sin med favorittkjæledyret!',
    'adopt-me_short_descr' => 'Ha det gøy med søte kjæledyr i vår Adopt Me!-samling av spillmarkører',
    'adopt-me' => 'Adopt me!',
    'among-us_descr' => 'Among Us er basert på det berømte rollespillet "Mafia". Det var planlagt at spillet skulle være eksklusivt for mobile enheter, fordi det bare hadde ett kart. Spillet ble raskt populært. Senere la utviklingsteamet til en flerspillermodus, og to ekstra kart ble utgitt i 2019.
Among Us er et top-down tredjepersonsspill som lar spilleren bevege seg i alle retninger. Fra fire til ti spillere kan spille i én runde. Ved starten av spillet blir alle i hemmelighet tildelt rollen som en forræder eller besetningsmedlem. Impostor (i russisk oversettelse "Forræder") kan gjemme seg i ventilasjonsluken, sabotere og drepe besetningsmedlemmer. Målet er å ødelegge alle besetningsmedlemmer, eller ødelegge romskipet ved sabotasje. Målet for skipets besetning er å løse forskjellige gåter som er forberedt for dem ved starten av spillet. Hvis hvert av besetningsmedlemmene fullfører alle oppgavene, vil forræderne tape. Skipets besetning kan også oppnå seier ved å eliminere forrædere under avstemningen.
Forrædere kan sabotere fra tid til annen, og hvis sammenbruddene ikke blir fikset på 30 sekunder, vil besetningen tape. Før du starter spillet, kan du velge fargen på karakteren du spiller for, blå, rød, gul, grå - hva som helst! Og ikke glem å sette deg selv den passende markøren fra den nye Among Us-samlingen!',
    'among-us_short_descr' => 'Ikke bli lurt i dette kompliserte romspillet med Among Us-markørene',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Skaperen av "Steven Universe" var Rebecca Sugar. Hun er kjent for sitt tidligere arbeid kalt Adventure Time. Den første episoden av Steven Universe ble utgitt på YouTube video plattformen våren 2013. Men på høsten begynte den amerikanske kanalen Cartoon Network å kringkaste den for sine seere. Siden den gang har 6 sesonger blitt utgitt. Den sjette lover å bli den siste.
Når det gjelder handlingen i den animerte serien, dreier den seg om Crystal Gems teamet. Det består av romvesener med karakteristiske navn: Perler, Ametyst og Granateple. Men det er en annen deltaker i den, i rollen som en vanlig gutt Stephen opptrer. Sammen leter de etter monstre og prøver å nøytralisere dem slik at de ikke overtar jorden for egen vinning. De er motarbeidet av Jasper og Peridot - budbringere fra hjemmeplaneten deres som ønsker å beseire Gems og slå på Cluster.
Hvis du er en fan av Steven Universe og vil se karakterene i den animerte serien uansett hvor du kan, installer Cursor Style-utvidelsen! Hvorfor gjøre dette? Du kan legge til en samling dedikert til "Steven Universe" og gjøre den vanlige musepekeren om til en av favorittkarakterene dine.',
    'steven_universe_short_descr' => 'Avdekk hemmelighetene til edelstener med Steven Universe-markører',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'En animert situasjonskomedie kalt "Family Guy" vant i hele sin eksistens 4 ganger Emmy Award og 3 ganger "Annie". Den animerte serien latterliggjør de ømme emnene i det amerikanske samfunnet, som: feminisme, slaveri, fedme, politikk, etc. I motsetning til andre verk, brukes innsettinger med vitser og sarkasme her. Dessuten er de i mange tilfeller ikke integrert i handlingen, men eksisterer alene.
En episode av den animerte serien er laget over 10 måneder. Hvorfor så lenge? Fordi hele animasjonen er tegnet for hånd. På grunn av dette har noen av hendelsene som dekkes av verket tid til å miste relevans. Men likevel forblir situasjonskomedien veldig interessant og vinner gunst hos seere over hele verden. Hvem liker tross alt ikke å le godt av politikere, kjendiser eller folk som begår ville påfunn og dermed overraskker eller til og med sjokkerer vanlige folk.
Liker du "Family Guy"? Du har en unik mulighet til å gjøre en normal musepeker om til hvilken som helst av karakterene i denne animerte serien! Hva trenger jeg å gjøre? Bare installer "Cursor Style"-nettleserutvidelsen, legg til en samling dedikert til "Family Guy" til den, og nyt en fabelaktig reinkarnasjon!',
    'family_guy_short_descr' => 'Family Guy-markørsamling for kjennere av spesiell humor',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Du har sikkert hørt uttrykket "Skjønnhet vil redde verden"? Så mange mennesker, spesielt jenter, er enige i denne uttalelsen. Derfor streber de etter å omgi seg med alt det vakreste og mest behagelige for øyet. Det kan være rosa tapet på soverommet, kosedyr, puter brodert med perler, dyre smykker osv. Utenfra ser det hele veldig søtt ut og til og med litt barnslig. Men hver og en av oss er et lite barn i hjertene våre, så hvorfor ikke la det vise fantasien vår?
Ømhet i oss kan forårsake mye. For eksempel de medfølende øynene til en kattunge som ønsker å bli strøket eller matet. En flerfarget regnbue som titter frem etter en vårregn og skinner med alle fargene i solen. Barnet som ble servert sjokolade, og han bestemte seg for å dele den med kjæresten sin. Det er en del grunner til å bli rørt, og vi bestemte oss for å bruke dem som markører.
Lei av den kjedelige hvite pilen i nettleseren din? Bytt den ut med noe søtt fra samlingen vår! For eksempel en rosa og hvit enhjørning, en trist tomat, en grublende sky, en piggete kaktus i form av en katt, eller hva du måtte ønske. Alt du trenger å gjøre er å installere Cursor Style-utvidelsen og legge til en samling søte markører til den. Og lenge leve verdens frelser – skjønnhet!',
    'cute_cursors_short_descr' => 'Verden vil være snillere med søte markørsamling',
    'cute_cursors' => 'Søte Markører',
    'web_media_descr' => 'I moderne virkeligheter bruker nesten alle Internett. Fra småbarn og til pensjonister. Noen surfer ved hjelp av en nettleser, en annen ser videoer på YouTube, og noen trenger nettverket for å kommunisere med sine kjære. Enhver av disse brukerne kan ikke forestille seg en dag uten World Wide Web.
Eldre mennesker sitter ofte på et sosialt nettverk som Facebook eller VK. De kommuniserer også ofte med sine barn og barnebarn på Skype. Dette er spesielt praktisk hvis barn og foreldre bor i forskjellige byer eller til og med land.
Unge mennesker foretrekker å kommunisere gjennom Viber eller Telegram, laste opp bilder på Instagram, le av FB-memer. YouTube-videoer av folks reaksjoner får millioner av visninger, akkurat som forskjellige spøker eller sosiale eksperimenter. I Tik-Tok danser hundretusener av mennesker, viser magiske triks og uttrykker seg.
Er du interessert i eller bruker du ofte en slags ressurs fra sfæren av webmedier? Vil du bli kvitt den kjedelige musepilen i nettleseren din? Installer deretter utvidelsen og endre standard markør til vår kreative! Det kan være YouTube-markør, Viber-markør, Google Chrome-markør eller andre ressurser.',
    'web_media_short_descr' => 'Lev i en moderne rytme med webmedie-markørsamlingen.',
    'web_media' => 'Web Media',
    'bobs_burgers_descr' => 'Den animerte serien Bob\'s Burgers er handlingen i animasjonsarbeidet og karakterenes karisma. Og, å dømme etter nominasjonen til Emmy-prisen og anerkjennelsen av verket som en av de beste tegneseriene i hele verden, gjorde Bob\'s Snack virkelig et inntrykk.
Handlingen i den animerte serien dreier seg om Bob Belcher-familien. Denne personen er eieren av dineren i første etasje, og i andre etasje bor han med sine kjære. Bob har en munter kone Linda og 3 barn: Gene, Louise og Tina. Gutten drømmer om en musikalsk karriere, den eldste datteren Tina er veldig snill, men klønete, og den yngste - Louise er fremdeles en kjæledegge og setter ofte familien sin i en ubehagelig situasjon. Hovedkonkurrenten til Bob\'s Burgers er Jimmy Pestos Pizzeria. Som du kanskje gjettet, heter eieren av dette pizzeriaet Jim, og han og Bob hater hverandre. Alt dette ble slått slik at det så komisk ut, ikke alvorlig. Derfor forårsaker mange av deres trefninger bare et smil.
Hvis du elsker den animerte serien “Bob\'s Burgers” og ønsker å se karakterene hans ikke bare på skjermen eller TV-en, installer utvidelsen, legg til en samling, og endre musepekeren i nettleseren til en av karakterene i denne tegneserien!',
    'bobs_burgers_short_descr' => 'Bob lager burgere, og vi lager Bob\'s Burgers-markører',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_short_descr' => 'Prøv å inhalere hele Kirby-markørsamlingen',
    'kirby' => 'Kirby',
    'undertale_descr' => 'I gamle dager var jorden bebodd ikke bare av mennesker, men også av monstre. På grunn av uenigheter mellom dem brøt det ut en krig som endte til fordel for menneskerasen. Syv magikere drev monstrene under jorden og fengslet dem for alltid der med en barriererune. Det var imidlertid bare én inngang til Mount Ebott, som barnet benyttet seg av. Det er for ham du vil spille ved å kjøre dataspillet Undertale.
Dette spillet ble utviklet av Toby Fox - en velkjent programmerer fra USA. Først kunne eiere av personlige datamaskiner som kjører Microsoft Windows og Linux OS glede seg over det, og deretter kom turen til brukere av spillkonsoller.
Hva er poenget med dette spillet? Gutten reiser gjennom underverdenen bebodd av monstre. Noen av dem er umiddelbart fiendtlige, mens andre liker å prate. Spilleren kan velge én av 2 atferder: unngå vold eller kjempe. I det første tilfellet vil det være lettere å fullføre spillet, i det andre - tvert imot er det vanskeligere. Handlingen og slutten, som kan forgrene seg og endre seg, avhenger også av dette valget.
Hvis du liker Underground Tale og ønsker å se karakterene i nettleseren din, installer utvidelsen og legg til den aktuelle samlingen av markører! Gjør en kjedelig musepeker om til en av monstrene eller hovedpersonen i Undertale!',
    'undertale_short_descr' => 'Det er på tide å komme seg ut av hullet ved å bruke Undertale-markørene',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune er et rollespill som ble utgitt for datamaskiner for et par år siden. Det ble laget av samme programmerer som utviklet Undertale. Disse to spillene er imidlertid nesten ikke like hverandre, selv om de har et par felles karakterer og steder.
Det er flere hovedpersoner i Delta Rune. Dette er en student Chris, som kan kontrolleres, og en sjarmerende monster Susie, som ikke kan kontrolleres. Begge karakterene faller inn i mørkets verden, hvor de møter en av innbyggerne - Ralsay. Han forteller dem at de faktisk er lysvesener som har et oppdrag - å stoppe strømmen av mørk energi i en dyster verden. For å gjøre dette må de spare de lokale monstrene og prøve å ikke gå i kamp med dem, selv om dette noen ganger er ganske vanskelig å gjøre.
Spilleren har et enkelt valg: enten å spare de mørke skapningene, eller angripe dem. Siden Susie ikke er en fan av halve tiltak, velger hun i mange tilfeller en kamp. Derfor har Chris ikke noe annet valg enn å støtte kjæresten sin og hjelpe henne i kampene.
Elsker du spillet Deltarune? Da kan du style musepekeren din i nettleseren for en av karakterene hennes! Du kan gjøre dette med utvidelsen vår. Installer den, legg til «Rune Delta»-samlingen og aktiver! Nå har pilen din sluttet å være den samme som alle andre, og har blitt Chris, Susie eller en av skapningene i den mørke verdenen.',
    'deltarune_short_descr' => 'Stup ut i den mørke verdenen med denne markørsamlingen',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario er en serie med dataspill utgitt av Nintendo. Det første og mest populære spillet het Super Mario Bros. Det så dagens lys i 1985. Senere ble det oppført i Guinness rekordbok. Siden den gang har mer enn 20 spill blitt utgitt, som hver har sin egen handling. I 2019 dukket en ny versjon opp kalt Super Mario Maker 2. Til tross for forbedringen i grafikken, forble stilen og karakterene de samme, og dette fremkaller nostalgi for Super Mario fra 80-tallet.
Hovedpersonen er fremdeles rørleggeren Mario. I handlingen i den siste varianten av spillet, hadde ikke prinsessens slott en stein urørt. Mario må bygge det opp igjen, etter å ha tjent før det myntene som betales til ham for oppgaver. Totalt har dette spillet mer enn 100 nivåer av ulik kompleksitet med mulighet for modifikasjon. Også i Super Mario Maker 2 er det nye spillmoduser. Du kan spille fire av dem på en gang, og så snart en er ferdig, regnes nivået som fullført. Det er også moduser som: Mario Marathon, Duel og Ninjik-løp.
Elsker du Super Mario og alt relatert til dette fantastiske spillet? Sett deretter markørene laget i stilen til denne plattformspilleren! Vi er sikre på at du vil like Mario-markøren, Luigi-markøren, Princess Peach-markøren og andre markører som presenteres i samlingen vår!',
    'super_mario_short_descr' => 'Gå gjennom soppriket med Super Mario-markørsamlingen',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls ble laget i fellesskap av Disney Television Animation Corporation og Alex Hirsch. Premieren ble utgitt i 2012 og ble vist på Disney Channel. Hele den første sesongen av den animerte serien gikk der. To år senere ble den andre sesongen utgitt, som seerne kunne se på den forrige kanalen og på Disney XD. Dessverre ventet ikke Gravity Falls-fans på den tredje og påfølgende sesongene. Skaperne bestemte seg for å begrense seg til to sesonger uten noen oppfølgere.
Når det gjelder handlingen i dette animerte bildet, så foregår all handlingen i en fiktiv by kalt Gravity Falls. To tvillinger kommer dit, hvis navn er Mabel og Dipper. De bor hos fetteren sin Stan. Han har sin egen turistbutikk med suvenirer. Når brødrene kjeder seg med å «ikke gjøre noe», går de på jakt etter eventyr. En av dem finner en merkelig dagbok i skogen, som forteller om anomaliene i denne byen. Tvillingene drar ut på leting etter forfatteren og møter uvanlige skapninger og steder. Hvis du er interessert i denne animerte serien, og du en gang var fan av karakterene, anbefaler vi vår samling av musepekere i stil med Gravity Falls!',
    'gravity_falls_short_descr' => 'Legg ut på et eventyr med Gravity Falls-markører',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Alle har hørt om en så berømt animert serie som The Simpsons. Selv de som aldri har sett på det, er klar over eksistensen av gule karakterer. Og fans er henrykte når neste sesong av favoritttegnefilmen deres kommer ut. Forresten, høsten 2019 ble 31 sesonger utgitt. Og den første dukket opp på TV-skjermene tilbake i 1989. Fox begynte å vise den og fortsetter å gjøre det på grunn av høye rangeringer og publikums sympati.
The Simpsons er en satirisk sjanger som berører relevante temaer. Dette kan være livsstilen til den gjennomsnittlige amerikaner, politiske og religiøse spørsmål, "stjerne" triks av kjendiser, feminisme, likekjønnet ekteskap. Generelt alt relatert til lokale og globale hendelser som USA deltar i.
Handlingen i den animerte serien foregår i den ikke-eksisterende byen Springfield. Faktisk er det mange byer med det navnet i Amerika. Kanskje det er derfor det ble valgt slik at publikum ikke forbandt det som skjedde på skjermene med et bestemt sted, men bare gjettet hvor dette kunne være.
Du er mest sannsynlig en fan av Simpsons. Ellers, hvorfor skulle du lese denne teksten til slutten? Og hvis det er tilfelle, så har du muligheten til å endre den kjedelige musepekeren til en peker som er laget i stilen til denne animerte serien.',
    'simpsons_short_descr' => 'En morsom liten familie med Simpsons-markører',
    'simpsons' => 'The Simpsons',
    'youtubers_descr' => 'YouTube-videoplattformen dukket opp i 2005. Til å begynne med ble videoer publisert der bare for selvuttrykk eller informere om noe. Men over tid vokste alt dette til en lønnsom virksomhet, som bringer tusenvis, og noen ganger millioner av dollar i måneden til suksessrike YouTube-brukere. Jo mer populær vlogeren (personen som leder videobloggen), jo mer kan han tjene gjennom kanalen sin.
Hvor mye tjener en fem år gammel vloger jente, hvis foreldre tar henne med til de mest interessante attraksjonene og filmer det som skjer på kamera? Det er bare hvordan et barn har det gøy i barneparker, som uttrykker følelser, hvordan man tuller rundt og alt det der. Beløpet er virkelig fantastisk - i dag har barnets kanal fått nesten 47 millioner abonnenter og begynte å generere inntekter på 5 millioner rubler i måneden.
Noen laster opp videoer der de diskuterer dataspill, noen driver med beatboxing eller arrangerer spøker for forbipasserende på gaten. Noen vier videoene sine til sensitive temaer, for eksempel forholdet mellom menn og kvinner. Jo mer YouTube-brukere liker disse opptakene, jo høyere blir populariteten til vloggeren.
Samlingen har allerede lagt til PewDiePie-markøren, Shane Dawson-markøren, Ray William Johnson-markøren, Zoella-markøren, MyLifeAsEva-markøren og andre.',
    'youtubers_short_descr' => 'En ny generasjon av stjerner er alltid pålogget i vår YouTubers-samling',
    'youtubers' => 'YouTubers',
    'pusheen_descr' => 'Nesten alle kjenner Pusheen-katten. Selv om det bare er en karakter fra en barne tegneserie oppfunnet for 10 år siden, har den millioner av fans i dag. Pusheen-katten dukket opp som en illustrasjon laget av kunstneren Claire Belton.
Et år senere fikk katten sin egen side på Tumblr.com og på noen uker fikk den en hel hær av fans - rundt 10 000 mennesker. I 2013 var Facebook ivrige etter å inkludere bilder fra Pusheen i samlinger med andre uttrykksikoner. Etter forhandlinger med skaperen ble denne ideen satt ut i livet og «eksploderte» på Internett! Bilder fra Pusheen-katten brukes i korrespondanse mer enn 10 millioner ganger om dagen!
I 2014 rettet en av de største leketøyprodusentene i USA oppmerksomheten mot denne karakteren. GUND (det var hun som oppfant teddybjørnene) lanserte et par Pusheen-modeller. Siden suksessen var enorm, ble det etter noen måneder laget en komplett samling med leker i form av denne katten.
Hvor ellers kan du møte Pusheen-katten? I gavesett fra Isaac Morris Ltd, i marshmallows fra Boomf og, selvfølgelig, i vår samling av Pusheen markører!',
    'pusheen_short_descr' => 'Legg til litt komfort i nettleseren din med Pushin-markørsamlingen',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'Den første serien med animerte verk «Rick and Morty» ble utgitt i 2013. Denne tegneserien kan direkte tilskrives 2 sjangre: science fiction og komedie. Skaperne var Dan Harmon og Justin Royland. Opprinnelig ble alle episodene vist på Cartoon Network-kanalen, og først da ble de duplisert i online-kinoer og video hosting. Hvert par år slippes nye Rick and Morty-sesonger, og i november 2019 kom den fjerde sesongen ut, som viste seg å være ikke mindre interessant enn de foregående. Handlingen i den animerte serien kretser rundt et geni og, samtidig, en gal vitenskapsmann ved navn Rick, samt hans umerkverdige barnebarn - Morty. Disse to karakterene er knyttet sammen av felles eventyr på de mest uvanlige stedene. Og de kommer dit på en flygende tallerken, i stand til å bevege seg gjennom en inter-romlig tunnel. Som du kanskje har gjettet, ligner denne animerte serien litt på filmen Tilbake til fremtiden, men likevel er det ikke dens animerte versjon. Imidlertid ble den hyllet av mange kritikere for humoristiske episoder, kreativitet og originalitet. Vil du se Rick eller Morty ikke bare i serien av dette verket, men også i nettleseren? Hvis det er tilfelle, installer utvidelsen og legg til samlingen vår dedikert til din favoritt tegneserie! Her er Rick Sanchez markør, Morty Smith markør, Portal Gun markør og selvfølgelig Mr. Meeseeks markør.',
    'rick_and_morty_short_descr' => 'Slutt å surmule, bare bruk markørene fra Rick and Morty-samlingen',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Baseballfans kan finnes hvor som helst i verden. Dette gjelder spesielt for innbyggere i land som: USA, Kina, Cuba, Sør-Korea, Japan og Venezuela. I motsetning til folkelig tro, stammer ikke baseball fra Amerika, men fra England. Den første omtalen og beskrivelsen av baseball dukket opp i det fjerne 1744, i den engelske utgaven. Etter 145 år tilegnet amerikanerne seg denne oppfinnelsen, til tross for fakta.
National League ble dannet i 1876. Hun er en del av Major League i Canada og USA. I dag er det 15 lag i National Baseball League. I den siste delen av hver sesong kommer tiden for sluttspillet, der de 4 beste lagene deltar. Så avsløres vinneren av hele National League. Deretter får vinnerlaget muligheten til å spille mot vinneren fra American League i World Series.
Er du interessert i baseball eller heier du til og med på et av lagene? Så hyl favorittlaget ditt ved å sette musepekerne i form av attributtene deres! Endre det kjedelige utseendet til pekeren i nettleseren til den kjente baseball-bedriftsidentiteten! Gjør pilen om til en spillers bat eller hjelm i et av National League-lagene, som allerede inkluderer New York Yankees-pekeren, Great Falls Dodgers-pekeren, Boston Red Sox-pekeren, Baltimore Orioles-pekeren, Oakland Athletics-pekeren.',
    'mlb_teams_short_descr' => 'MLB Teams markørkolleksjon for alle våre fans der ute.',
    'mlb_teams' => 'MLB Teams',
    'brawl_stars_descr' => 'Brawl Stars er et mobilspill i MOBA-sjangeren fra Supercell. Til tross for utgivelsen i slutten av 2018, fikk spillet stor popularitet, mye på grunn av overfloden av kampmoduser og fargerike, fantastiske helter - brawlere. Spilleren har mye å velge mellom - 32 unike karakterer, og hver av dem har sine egne evner og ferdigheter. Hver helt har også sin egen passive ferdighet, som er tilgjengelig gjennom booty kister. Spillere kan kjempe i flere moduser, for eksempel "Belønning for erobringen" - ett av de to lagene vinner, som har samlet flere stjerner ved å drepe motstandere. I "ran"-modusen er det nødvendig å bryte motstandernes pengeskap, mens man opprettholder sine egne. En interessant "Gem Grab"-modus - laget blir vinneren, laget som samler de fleste edelstener vinner. Vel, i "Collision"-modusen kjemper 10 spillere mot hverandre på kartet, der grensene reduseres på grunn av en giftig sky. Spillet er fullt av et fargerikt design som mange liker, inkludert oss, noe som inspirerte oss til å lage en egen samling av Brawl Stars-markører. Det finnes Brawl Stars Shelley-markør, Barley-markør, Penny-markør, Frank-markør, Mortis-markør og andre.',
    'brawl_stars_short_descr' => 'Velg Brawl Stars-markører og la kampen begynne',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Endre musepekeren din med to klikk! Gratis samlinger for enhver smak.',
    'all_descr' => 'Hvis du noen gang har tenkt på hvordan du kan endre en kjedelig musemarkør, så er våre markørsamlinger noe for deg! Her finner du kule tegneseriehelter, vakre markører for spillere med karakterer fra populære spill, morsomme sett med markører for praktiske vitser, fargemarkører og mange andre interessante alternativer.',
    'text_title' => 'Kule og morsomste markørsamlinger for enhver dag',
    'text_allcat_title' => 'Unike og kreative musemarkører som matcher humøret ditt',
    'text_1' => 'Du vil ikke være som alle andre? Eller bare elsker alt uvanlig? Vil du være en del av din favorittspillhelt eller tegneseriefigur? Da har du kommet til rett sted. Her finner du lyse, uvanlige sett med markører som kan erstatte den kjente og allerede ganske kjedelige hvite pilen. Musemarkøren følger oss hele dagen på jobb og studie, så den bør gi et godt humør og forberede for det positive.',
    'text_2' => 'Her finner du markører for spillere og filmentusiaster, vakre markører basert på dine favoritt tegneserier og sportsmotiver for de mest aktive menneskene. Liker du tegneserier eller kan du ikke forestille deg en eneste dag uten morsomme memes? Elsker du dyr eller drømmer du om å besøke alle verdens land? Alt er enkelt - vi har et passende markørbilde for deg også. Du kan også velge bilder avhengig av hva du jobber med. For eksempel vil en svart markør være mye mer praktisk enn hvit når du jobber med dokumenter eller tegninger, og en håndmarkør vil være mer praktisk hvis du må jobbe med små grafiske elementer. Velg ditt favorittbilde, juster størrelsen direkte i utvidelsen - og bruk det med glede, hver dag som starter med en positiv tone!',
    'install_to_preview' => 'Vennligst installer utvidelsen for å forhåndsvise',
    'install' => 'Installer',
    'add_button' => 'Legg til',
    'preview_button' => 'Forhåndsvis',
    'added_button' => 'Lagt til',
    'add_cursor' => 'Legg til markør',
    'to_your_collection' => 'til samlingen din',
    'prev_text_1' => 'Forhåndsvisning i fullskjerm',
    'prev_text_2' => 'markør',
    'cursor' => 'markør',
    'pointer' => 'peker',
    'a_title_1' => 'Cursor Style - Kule markører for nettleseren din',
    'a_title_2' => 'Kule samlinger av tematiske markører',
    'mouse_cursors' => 'Markør musepekere',
    'cursor_collection' => 'Markør samling',
    'sborka_cursorov' => 'markør samling',
    'collection_list_from_colllection' => 'Liste over markører - ',
    'nhl_teams' => 'National Hockey League',
    'neon' => 'Neon',
    'adventure_time' => 'Eventyrtid',
    'nba_teams' => 'National Basketball Association',
    'spongebob' => 'Svampebob',
    'phineas_and_ferb' => 'Phineas og Ferb',
    'fortnite_chapter_2' => 'Fortnite Kapittel 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Kjendiser',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Tegneserier',
    'igry' => 'Spill',
    'multfilmy' => 'Tegnefilmer',
    'kino_i_serialy' => 'Filmer',
    'anime' => 'Anime',
    'futbol' => 'Fotball',
    'avtomobili' => 'Biler',
    'memy' => 'Memes',
    'emodji' => 'Emoji',
    'pitomcy' => 'Kjæledyr',
    'stil_i_krasota' => 'Mote og stil',
    'prazdniki' => 'Høytider',
    'flagi' => 'Flagg',
    'vokrug_sveta' => 'Rundt om i verden',
    'eda_i_napitki' => 'Mat og drikke',
    'cvetnye' => 'Fargede',
    'prank' => 'Spøker',
    'startovyj_nabor' => 'Startsett',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Julenissen vil elske dine julemarkører',
    'nhl_teams_short_descr' => 'En samling NHL-markører for ekte fans',
    'neon_short_descr' => 'Legg til lysstyrke med en neonkolleksjon',
    'adventure_time_short_descr' => 'Læring i matte med Adventure Time-markørsamlingen',
    'nba_teams_short_descr' => 'NBA-markører som et symbol på store basketballseire',
    'spongebob_short_descr' => 'Finn ut hvem som bor på havbunnen med SpongeBob-markørkolleksjonen',
    'phineas_and_ferb_short_descr' => 'Du kommer definitivt ikke til å kjede deg med Phineas og Ferb markørsamlingen',
    'fortnite_chapter_2_short_descr' => 'Det nye kapittelet i kultspillet Fortnite',
    'pokemon_short_descr' => 'Fang dem alle hvis du kan',
    'famous_people_short_descr' => 'Inspirer markøren med ditt idol',
    'the_elder_scrools_short_descr' => 'Fordyp deg i ridderes og dragers verden',
    'halloween_short_descr' => 'Vær redd for å gå glipp av den nye Halloween-kolleksjonen',
    'nfl_teams_short_descr' => 'For ekte fotballfans',
    'five_nights_at_freddy_short_descr' => 'Prøv å ikke bli redd av disse animatronikkene',
    'komiksy_short_descr' => 'Pekere av tegneserier: velg humøret ditt i dag.',
    'igry_short_descr' => 'Virtuell virkelighet: hvem spiller du i dag?',
    'multfilmy_short_descr' => 'Favoritt tegneseriefigurer i et nytt design',
    'kino_i_serialy_short_descr' => 'Ringenes Herre av Markøren: Brorskapet på Skrivebordet',
    'anime_short_descr' => 'Alle elsker anime: hvem er din favorittkarakter?',
    'futbol_short_descr' => 'Er du en ekte sportsfan? Da må du være her',
    'avtomobili_short_descr' => 'Bilen du drømmer om: en stor flåte for profesjonelle',
    'memy_short_descr' => 'Favorittmotiver: Memes markørkolleksjon',
    'emodji_short_descr' => 'Vis ditt virkelige humør til andre - sett Cursoji!',
    'pitomcy_short_descr' => 'Lyssterke markører for alle elskere av våre mindre brødre',
    'stil_i_krasota_short_descr' => 'Originale markører for alle anledninger',
    'prazdniki_short_descr' => 'Hva er det på kalenderen? Nye Ferie-markørkolleksjon!',
    'flagi_short_descr' => 'Ser du etter eventyr: hvor drar vi i dag?',
    'vokrug_sveta_short_descr' => 'Jorden rundt på et øyeblikk: hvor skal vi i dag?',
    'eda_i_napitki_short_descr' => 'Munnvannende markører for kreativitet',
    'cvetnye_short_descr' => 'Mal livet ditt i sterke farger og dristige strøk',
    'prank_short_descr' => 'Et sett med markører for de morsomste spøkene',
    'startovyj_nabor_short_descr' => 'Et nytt blikk på kjente ting: en oppdatert serie med markører',
    'fortnite_short_descr' => 'Følg strømmerne!',
    'dota_2_short_descr' => 'Gjør din virtuelle verden som ekte!',
    'minecraft_short_descr' => 'Karakterer fra favorittspillet ditt er alltid i nærheten',
    'christmas_descr' => 'Hver av oss venter utvilsomt på den mest populære høytiden - julen. Alle kristne i verden feirer den tradisjonelt hvert år, 25. desember. En tid da familier samles rundt ett bord, deler sin glede og kjærlighet og utveksler gaver. God tid før jul pynter folk gatene med sterke girlandere, og hjemmene sine med tradisjonelle attributter. Det er vanskelig å finne en person som ikke liker julen - en morsom og mystisk høytid, fordi den er ledsaget av mange tradisjoner og ritualer, de returnerer oss til røttene til hele familien vår. På selve julaften er bokstavelig talt alt mettet med dens ånd, fra malte pepperkaker til rørende salmer. Et elegant juletre og gaver under det, en glede som er kjent for hver og en av oss fra barndommen. Vi ønsker å bli med på denne magiske høytiden, og hvem vet, kanskje julenissen vil forberede en spesiell gave til deg hvis du dekorerer markøren din med julesamlingen vår. Det er alt du trenger for dette, julenissemarkøren, juletremarkøren, pepperkake-markøren, Snømann-markøren og til og med gavepose-markøren. God jul!',
    'nhl_teams_descr' => 'National Hockey League ble dannet i 1917 - det er en profesjonell sportsorganisasjon som bringer sammen hockeyklubber fra USA og Canada. Og dette er en av de første profesjonelle hockeyligaene i verden. NHL er en av Nord-Amerikas fremste sportsligaer, sammen med NFL, NBA, Major League Baseball og MLS. Hvert år kjemper 31 lag fra 30 byer i USA og Canada om hovedtroféet - Stanley Cup, og laget som scoret flest poeng i den ordinære sesongen tildeles President\'s Cup. Det er på tide for oss å hedre dette fantastiske spillet ved å lage en samling av NHL-markører. Hvis du også liker hockey, heier du på favorittklubben din eller deltar i denne sporten selv, bare endre markøren og ikke skilles fra favorittlaget ditt, inkludert Boston Bruins-markøren, St. Louis Blues-markøren, Columbus Blue Jackets-markøren, Tampa Bay Lightning-markøren, Dallas Stars-markøren og andre klubber verdig oppriktig respekt.',
    'neon_descr' => 'Vi har laget en unik samling av neonmarkører for å legge til variasjon til hverdags internettsurfing og legge til litt lysstyrke til de fascinerende neonlysene. La deres rike farger skape den omsluttende atmosfæren i byen om natten, gi inspirasjon til å skape noe nytt. I den moderne verden kunngjør lysene i en metropol alltid nattens komme, de følger oss på hver gate, og denne gløden er fylt med energi. La det også bli fulgt av en glødende iskremmarkør, en deilig pølsemarkør, en saftig burgermarkør, en glitrende diamantmarkør og andre markører fra den nye neonkolleksjonen.',
    'adventure_time_descr' => '"Adventure Time" er en tegneserie av en fantastisk sjanger der handlingen foregår i en verden som har overlevd apokalypsen. Dette territoriet kalles Landet Ooo, som inntil nylig var en atomkrig. Men alt dette er allerede i fortiden, men alle de overlevende menneskene var utsatt for mutasjoner, og verden ble fylt med magi. Hovedpersonene i den animerte serien er Finn, en gutt på 14 år og vennen hans, en hund ved navn Jake. Gutten og hunden er veldig glad i eventyr, de hjelper stadig alle som er i trøbbel. Venner bor på et tre og tilbringer all sin tid sammen. Hvis du vil fordype deg i en eventyrverden med andre beundrere, så rop "Matematikk". Her er både Finn Boy-markøren og Jake-markøren, samt Princess Chewing Gum-markøren. Vi glemte selvfølgelig ikke Bimo-markøren, Ice King-markøren og andre.',
    'nba_teams_descr' => 'Hvis basketball er favorittspillet ditt, slik det er for oss, så er en samling av markører dedikert til NBA-lag det du trenger. NBA er en av de største sportsforeningene på det nordamerikanske kontinentet. Da vi laget denne samlingen, ble vi plaget av valget - hvilket lag vi skulle velge, fordi det er tretti av dem i NBA. Men det er lag som er legender. Dette og Chicago Bulls, satte en rekord for seire på midten av 90-tallet. Dette er Golden State Warriors, som samlet de beste ligaspillerne for et par år siden. Eller, for eksempel, Lakers, Celtics er også vanvittig kule lag. Hvis du, i likhet med oss, ser frem til kampene til dine favorittbasketballag, og ønsker å vise din støtte til laget eller spillerne, last ned vår samling av NBA-markører.',
    'spongebob_descr' => 'Den animerte serien "Svampebob Firkant" er kjent av så mange mennesker. Det var en overveldende suksess etter at Nickelodeon i 1999 bestemte seg for å lage en animert serie basert på den pedagogiske tegneserien Tide Zone, og ble til en svært lukrativ franchise. Skaperen av serien er en tidligere ansatt ved det oseanologiske laboratoriet, og det er derfor nesten alle karakterene i den animerte serien er morsomme innbyggere i havbunnen, med sine egne karakteristika og karisma. Handlingen dreier seg om den hemmelige Krabbeburger-oppskriften som bare hovedpersonen kan lage - Svampebob. Og de andre innbyggerne i havet prøver å få den, inkludert hovedantihelten Sheldon Plankton, som ikke får det hver gang. I Svampebob-markørsamlingen har vi samlet markørene til alle de bemerkelsesverdige karakterene og hendelsene i serien. For eksempel markøren til Mr. Krabs med dollaren, markøren til Patrik Stjerne, Blekkulf med klarinetten sin, markøren til maneten, markøren til Svampebob og mange andre karakterer.',
    'phineas_and_ferb_descr' => 'I den fiktive amerikanske byen Denville i det ikke-eksisterende Trishtatya bor to interessante gutter. Hver dag av ferien deres forvandles til utrolige eventyr, fordi de kan lage en berg-og-dal-bane på størrelse med en hel by eller en ekte portal til en annen planet. De deler sin fantastiske underholdning med venner. Samtidig, mens guttene har det gøy, bygger den onde forskeren Heinz Fufelschmertz en annen ond maskin som skaper kaos, med navnet som slutter på "-inator", ved hjelp av hvilken han ønsker å hevne sine barndomsforulempelser eller gripe makten i Trishtat, men Perry hindrer ham - Utkonos, den hemmelige "Agent Pi", som jobber under dekke av en guttehund. Populariteten til denne animerte serien, både blant barn og voksne, inspirerte oss til å lage en samling av Phineas og Ferb-markører slik at du kan endre musemarkøren din på karakterene fra serien. Blant dem er Phineas Flynn-markøren, Dr. Heinz Fufelschmertz-markøren, Ferb Fletcher-markøren, Candace Gertrude Flynn-markøren og Perry-nebbmarkøren.',
    'fortnite_chapter_2_descr' => 'Det andre kapittelet av Fortnite kom etter en stor begivenhet - The End, som dro alt spillerne i spillet elsket inn i et svart hull. Fortnite Kapittel 2 har nå et nytt kart, som ved første øyekast er enda villere enn det originale kartet, samt mange endringer i spillmekanikken og selvfølgelig mye nytt spillinnhold! Kjøretøy, følelser, svømmemekanikk og mye mer - alt dette i friske, interessante bilder, alt slik du elsker og setter pris på i dette kultspillet. Fordyp deg i en ny verden - velg et landingssted og utforsk en helt ny øy med 13 steder. Svømming, fiske, motorbåter - dette er et nytt vannspill. Mer moro og mindre anstrengelse - oppgrader et helt nytt kapittel 2 og ikke glem å endre markøren til nye skins og våpen. Du venter allerede på de oppdaterte skinsene Turk markør, Riptide markør, Rippley markør, Remedy markør, Toxin markør, 8-Ball markør, Fusion markør og andre!',
    'pokemon_descr' => 'Ordet "pokemon" betyr en skapning med overnaturlige krefter. De har intelligens, og noen av dem er til og med i stand til å snakke. For tiden er det allerede 802 varianter av Pokemon. I det oppfunnet Pokémon-universet kalles folk Pokémon-trenere, som de trener for kamper med andre treneres Pokémon. Og jo mer erfaren og sterkere treneren er, jo mer respekt nyter han. Heldigvis bør det bemerkes at Pokémon-kamper aldri ender med døden til disse unike skapningene. Alle Pokémon har forskjellige evner og skiller seg ut i typen element, og dens motstand mot forskjellige angrep avhenger sterkt av dette, og noen skapninger har evnen til to elementer samtidig. Etter å ha vunnet kampen, får Pokémon den verdifulle erfaringen som er nødvendig for å øke nivået og følgelig dens egenskaper. I dag er Pokémon-universet en enorm mediefranchise, og vi vil bestemme oss for å forberede en samling av markører med noen populære Pokémon. Blant dem er den mest kjente Pikachu-markøren, samt Rattata-markøren, Squirt-markøren, Bulbasaur-markøren og Charmander-markøren. Denne listen vil bli oppdatert, fordi det er så mange av dem, og hver av dem er unik på sin egen måte.',
    'famous_people_descr' => 'Blant de mange kjente folkene finner hver av oss en rollemodell eller beundrer rett og slett genialiteten, talentet og utholdenheten til disse kjendisene. Vi har forberedt en samling av kjendis-markører for å inspirere deg og minne deg om de store prestasjonene som hver av dere kan øke. Ikke alle kjente personligheter hadde en lykkelig skjebne, men de lærer oss det viktigste at du aldri trenger å trekke deg tilbake fra ditt kjære mål, til tross for vanskeligheter og problemer. Tross alt er dette hovedprinsippet for å oppnå suksess - å gå til drømmen din hver dag og til slutt bli den beste i ditt fagfelt. Kanskje i dag vil du bare endre musepekeren din, og i morgen vil hele livet ditt endres til det bedre! Samlingen vil bli kontinuerlig oppdatert med nye, verdige representanter for menneskeheten. Blant dem er selvfølgelig forskere, politikere, idrettsutøvere, representanter for kunst og mange andre. George Washington-markøren, Michael Jordan-markøren, Stephen King-markøren, Elvis Presley-markøren og Marilyn Monroe-markøren er bare begynnelsen.',
    'the_elder_scrools_descr' => 'The Elder Scrolls er en serie med datamaskinrollespill, forent av et felles, omhyggelig designet univers, som gir spilleren enorm frihet til å velge, slik at de kan besøke forskjellige områder og byer i fantasy-verdenen og utforske nye steder og oppdrag på egen hånd. Arbeidet med serien startet tilbake i 1992, og gjennom årene har spillet forent et enormt fellesskap av spillere rundt seg selv. Derfor har vi på grunn av populær etterspørsel lansert en samling av markører The Elder Scrolls, slik at du kan fordype deg i den unike atmosfæren i spillet. Den evige kampen mellom riddere og drager, hvilken side er du på? Endre markøren til en drage og bli med i hæren av ildsprutende monstre eller kjemp edelt på siden av folket ved å velge sverdkursøren og bildet av favorittkarakteren din - avgjørelsen er din! Det viktigste er at med vår nye samling er du klar for alle kamper.',
    'halloween_descr' => 'Venter på en mystisk natt på tampen av Allehelgensdag. Historien om Halloween går over to tusen år tilbake. Kanskje dette er den merkeligste høytiden som kombinerer moro og frykt, en innfødt av den keltiske kulturen. Da brente folk bål og tok på seg skumle kostymer for å holde ånder unna. Ordet "Halloween" ble først nevnt på 1500-tallet som en skotsk forkortelse av den engelske frasen All-Hallows-Even. Pave Gregor III erklærte 1. november Allehelgensdag, og kvelden før det var kjent som Eve of All Saints, og senere Halloween. På denne dagen kler folk seg ut som varulver, spøkelser og andre monstre og går til nabohusene og tilbyr å kjøpe søtsaker. Temafester, fyrverkeri, vakre lykter, gresskar og stunt skaper en unik atmosfære. Vi ønsker også å feire denne forferdelige høytiden med tilbehørskursorer og Halloween-karakterer. I vår samling kan du finne: zombie-markør, spøkelsesmarkør, svart katt-markør, gresskarmarkør og mye mer. Å endre humøret ditt er nå like enkelt som å endre markøren din med vår nye Halloween-kolleksjon.',
    'nfl_teams_descr' => 'Hva kan være bedre for en ekte amerikansk fotballfan enn en musepeker i form av symbolikken til laget han er fan av? I den moderne National Football League spiller trettito lag, delt mellom National and American Football Conferences (National Football Conference, NFC og American Football Conference, AFC). Hver av konferansene er igjen delt inn i fire divisjoner: East, North, South og West. NFL-sesongen består av før-sesongkamper, en vanlig sesong og en rekke sluttspillkamper. Den siste kampen i NFL-sesongen kalles Super Bowl og er i hovedsak den mest populære sportsbegivenheten i USA. Dette er et favorittspill for millioner av fans, og derfor har vi laget en samling av NFL-pekere slik at du ikke skiller deg fra symbolene til favorittlaget ditt. Være det New England Patriots, New York Giants, Buffalo Bills eller et annet lag, vær alltid på samme bølgelengde som idolene dine, ved å bruke pekere i form av en laglogo og hjelm. Samlingen vil bli kontinuerlig oppdatert slik at alle kan endre pekeren til bildet av favorittlaget sitt.',
    'five_nights_at_freddy_descr' => 'Det unike spillet Five Nights at Freddy\'s fikk raskt bred popularitet, og dette er ikke overraskende, fordi den enkle og samtidig fascinerende handlingen kan holde spillere på skjermene i timevis. Vi designet Five Nights at Freddy\'s-markørene etter forespørsel fra fans av spillet og var veldig fornøyde med å legemliggjøre slike interessante og morsomme karakterer. Men i motsetning til spillet, truer ingenting deg med markørene våre, så velg favorittanimatronics, enten det er Bjørn Freddy eller Kanin Bonnie eller andre. Det viktigste er at nå kommer spillet til live i nettleseren din og gir nye følelser. Vi garanterer at det ikke er spøkelser i markørene våre, men de formidler perfekt ånden i et spill som inspirerer frykt på grunn av intrikat design og plottelementer. Men hva om du gjør markørstørrelsen veldig stor? Klarer du å holde deg rolig og ikke bli skremt?',
    'komiksy_descr' => 'Det kan virke som om musepekeren er en bagatell, men ofte er det slike detaljer som kan forbedre humøret ditt, våkne opp i den grå morgenen eller bare gi lyse følelser. En samling av tegneseriemusepekere designet spesielt for alle superheltelskere. Her kan du finne absolutt hele Marvel-universet og DC Comics - fra Iron Man til Thanos, Spider-Man og Hulk. Musepekerstilen kan være enten i form av en superhelt, eller i form av karakteren hans. En musepeker er ikke bare et funksjonelt element; det er viktig i profesjonell sammenheng. For eksempel, hvis du tar opp en video fra skjermen, vil det være bedre å se et lyst, originalt bilde, og det ser mye mer interessant ut. Og selvfølgelig - hvem ville ikke ønske å bruke Infinity-hansken i det virkelige liv? Å endre musepekeren er enkelt - bare last ned utvidelsen til nettleseren din og legg til musepekeren du liker i innstillingene dine gjennom den. Du kan velge en musepeker i henhold til humøret ditt minst hver dag. Nok av de grå dagene - bli en superhelt akkurat nå!',
    'igry_descr' => 'Dataspill har lenge blitt en integrert del av livene våre. Med deres hjelp kan du fordype deg i en ny verden, delta i eventyr og bli en helt annen person. Alle har sin egen favorittleke, hvis karakterer allerede har blitt nesten familie. Et sett med markører basert på kjente dataspill er en mulighet til å fortynne det kjedelige hverdagslivet og legge til litt kreativitet, lysstyrke og moro i arbeidsflyten. Settet inneholder både bilder av spillheltene selv, og hjelpekarakterer, våpen og spillikoner. Velg det som passer humøret ditt - spillmarkører vil appellere ikke bare til spillere, men også til alle som bare er lei av grå hverdagsliv. Bare last ned settet, endre musemarkøren - og gå, for å fullføre oppgavene, ødelegge fiender og nå målene dine.',
    'multfilmy_descr' => 'Inni i enhver voksen er det fremdeles et barn som elsker tegnefilmer og fremdeles drømmer om å bli en av heltene. Vi vil hjelpe deg med å gjøre drømmene dine til virkelighet - bruk den nye samlingen av markører basert på de mest kjente og populære tegnefilmene. Tom og Jerry, Buzz Lightyear og Shrek, Gravity Falls og til og med Pokemon - du kan bli hva du vil hver dag. Velg musemarkøren i henhold til humøret ditt. Hvem er du i dag? Tankeløs og munter minion som lett løser alle problemer eller en sterk og modig Raphael, hvis mål ikke bare er å utføre bragder, men også å spise pizza? Kanskje du er den allmektige ånden som holder et helt kontor under sin kommando? I samlingen er det helter for alle - fra prinsesser til drager - det gjenstår bare å bestemme hvem som reflekterer dagens humør. Cursor Style er ikke bare et lyst bilde. Dette er en refleksjon av individualitet, selvuttrykk og rett og slett - moro, glede og positivt for hele dagen. Er det kjedelig å jobbe eller for lat til å studere? Har det blitt trist og er ikke fornøyd? Endre markøren og verden vil glitre med nye farger.',
    'kino_i_serialy_descr' => 'Filmer - er magi, mystikk og bare en flott måte å slappe av, ha det gøy og få sterke følelser. Samtidig, etter å ha sett, husker vi fortsatt favorittheltene som jeg virkelig vil møte i virkeligheten. Nå er det mulig - bare last ned den nye samlingen av markører basert på kjente filmer og TV-serier. Lyse, kule markører vil være et flott tillegg til skrivebordet, forvandle kjedelig grå hverdag til en ferie, og banale oppgaver - til et spennende eventyr. Endre markørhelten hver dag - for humør, oppgaver eller tilfeldig. Hvem vil du være i dag? Ærlige og rettferdige John Snow eller den modige, ubarmhjertige John Wick? Kanskje du har et vanskelig oppdrag foran deg, og bare Frodo kan fullføre det? Kanskje du i dag bare er en romvesen som ikke vil ha kontakt med andre? Velg en passende markør - løft humøret og vis samtidig andre hva du tenker og hvordan du planlegger å tilbringe dagen din. Prøv det - det er ikke bare morsomt, men også vanedannende - du vil definitivt ikke ønske å gå tilbake til den vanlige pilen.',
    'anime_descr' => 'Anime er en unik stil av animasjon, som til tross for sin uttalte etnisitet har blitt likt av millioner av mennesker over hele verden. Det er usannsynlig at det vil være minst én person som ikke har sett tegneserier i denne stilen. Vi har laget de kuleste anime-stilpekerne som alle fans av denne stilen vil elske. Standard pekere er kjedelige og klisjéaktige. Vis din personlighet - bruk samlingen av Anime-pekere med dine favorittkarakterer. Velg pekeren til et mørkt sverd hvis du drømmer om eventyr og modige kamper. Den søte, feite mannen Totoro vil muntre deg opp selv på den tristeste dagen, og Naruto vil motivere deg på eventyr og vise alle rundt deg at du er en mega kul. Lyse pekere vil lyse opp arbeidsdagen eller gjøre læringsprosessen mer interessant og hyggelig. Ikke begrens deg selv - bruk favorittmotivene dine selv i så små elementer som musepekeren. Endre pekere hver dag, tilpass dem til humøret ditt og vis personligheten din - med anime-stilpekere er det så enkelt.',
    'futbol_descr' => 'Fotball er en spesiell sport som inkluderer elementer av bryting, friidrett, presisjon. Generelt sett er den spektakulær, nådeløs og samler millioner av fans over hele verden. Liker du fotball eller bare elsker sport? Last ned et sett med markører i stil med det verdenskjente spillet og bevis tittelen som en lojal fan. Samlingen inneholder 24 alternativer for utforming av markører - i form av de mest populære lagene som fortjener sine titler som et desperat og vedvarende spill. Markørene er laget i to versjoner - i form av en standard trekant, dekorert i lagets farger, eller i form av en tilsvarende spillhjelm. Standard nettlesermarkør er kjedelig og ikke verdig en ekte sportsfan. Bli original og unik med samlingen vår. Last ned bilder og velg fargene til favorittlaget ditt eller tilpassede markører, hvis du bare elsker sport og heier på alle. Å følge hobbyene dine er så enkelt - du trenger ikke å komme på jobb med et skjerf eller en caps fra favorittlaget ditt, det er raskt og enkelt å endre markøren til et lyst, stilig bilde.',
    'avtomobili_descr' => 'Liker du biler og liker å se på modeller fra forskjellige produsenter? Eller har du drømt om et bestemt merke i lang tid, men har fortsatt ikke mulighet til å kjøpe det? Spesielt for deg har vi laget et lyst sett med markører "Superbiler". Her finner du klassisk Ford og stilig Bentley, lys Lamborghini og unik Ferrari. Vil du bli eieren av originalbilen? Det er enkelt - last ned samlingen vår av markører til enheten din og endre bildet av bilen minst hver dag. Markørene er designet i to versjoner - som en fullverdig bil eller som dens tegn. Velg det du liker best eller hvordan du foretrekker å jobbe. Slike bilder vil se bra ut som spillmarkører eller rett og slett som et uvanlig element på skrivebordet. Å være lys er enkelt - det er ikke nødvendig å gjøre ufattelige ting for dette eller å endre utseendet ditt. Det er nok bare å slutte å bruke vanlige gjenstander og velge det du virkelig liker. Samlingen av markører "Biler" er valget for de som ikke er redde for å bevise seg selv.',
    'memy_descr' => 'Memes har lenge vært en kjent del av livene våre. Og hvem av oss liker ikke disse romslige, interessante og originale bildene for å trosse dagen? Mange helter fra memes har ikke bare blitt populære - de har fått status som populære favoritter, og fraser og uttrykk har lenge vært inkludert i dagligtalen som veletablerte vendinger. Vi presenterer en samling av de beste markørene basert på de mest populære memes. Med deres hjelp kan du ikke bare vise din personlighet, men også uttrykke humøret ditt. Er du lei og lei av alt? Velg en sint katt som med hele sitt utseende uttrykker forargelse og fiendtlighet til alt rundt ham. Eller skinner du av sarkasme i dag og har ikke noe imot å le? Da vil Drake Bling være en utmerket akkompagnement - det vil muntre deg opp og gjøre enhver oppgave original og interessant. Installer utvidelsen, last ned samlingen vår - og velg en markørstil for hver dag. Det er ikke vanskelig å være lys og original - endre standardutformingen av ikonet til en av heltene fra memes og få et energikick for hele dagen.',
    'emodji_descr' => 'Emoji - lyse, kule ikoner, uten hvilke vi ikke lenger vanligvis kan kommunisere. Med deres hjelp trenger du ikke å beskrive humøret ditt med ord - bare velg ønsket ikon, og samtalepartneren forstår deg uten videre. I vårt nye sett med markører legemliggjorde vi ideen om emoji - det er slik morsomme og uvanlige Cursoji dukket opp som vil fargelegge verden og gjøre livet mer interessant. Ved hjelp av markører kan du ikke bare jobbe og utføre kjente oppgaver, men også vise dine kollegaer, venner og bare andre humøret ditt. En søvnig markør er perfekt for mandag morgen, og en gråtende markør vil uttrykke en holdning til ekstra ansvar. En kul markør med briller er det beste valget før feriene, og en markør med dollar i øynene er en god grunn til å antyde til sjefen om lønnsøkningen. Å bruke Cursoji er morsomt og interessant - enten det er arbeid, studier eller presentasjon. I sistnevnte tilfelle anbefales det til og med å gjøre dette hvis kollegaer har sans for humor eller bare trenger å ufarliggjøre situasjonen. Generelt sett, for enhver oppgave - bare velg riktig markør!',
    'pitomcy_descr' => 'Liker du dyr? Jada - de er så søte, morsomme og veldig morsomme. Hvorfor ikke tilbringe hele dagen sammen med en persons beste venner? Last ned Pets cursors-samlingen for deg selv og velg en venn for deg hver dag. Cursorikonet kan være søtt, som en godmodig alpakka, eller stilig, som en rosa flamingo. Eller kanskje du vil være opptatt hele dagen og velge en enhjørning som leser en avis, eller rett og slett ikke ønsker å kommunisere med noen, som en ond svart katt? For ethvert humør har vi et tilsvarende dyr. En munter mops vil muntre deg opp selv på den mest kjedelige og grå dagen, og den rosa cursoren i form av en enhjørning vil vise alle at du ikke er blottet for en følelse av skjønnhet, selv om du er en brutal skjeggmann. Hva om det ikke er noe humør, og jeg har ikke lyst til å gjøre rutineoppgaver? Oppskriften er enkel - last ned Pets-samlingen, endre musepekeren - og voila, solen skinner igjen, været er fint, og humøret er på høyeste nivå. Ikke rart de sier at dyr hjelper med å bekjempe depresjon og tristhet!',
    'stil_i_krasota_descr' => 'I den nye samlingen av markører har vi samlet et bredt utvalg av emner som forårsaker oss hyggelige følelser og løfter oss opp. Dette settet med markører kalles «Style and Beauty», fordi det er favoritttingene dine som bestemmer hverdagen vår, gir glede og motiverer oss til å gjøre viktige ting, vekker ønsket om forbedring. Er du interessert i rommet og drømmer om å dra til andre planeter? Velg en NASA-markør eller en tallerken med romvesener - kom nærmere drømmen din. Hvis du ikke kan forestille deg livet uten musikk eller er en innbitt rocker, så er markøren i stil med en el-gitar noe for deg. Pensel-, linjal- og kompassmarkøren er spesialutviklet for ingeniører - slike bilder vil bidra til å forvandle kjedelige beregninger og tegninger til originale løsninger. En tryllestav og joggesko, et skateboard og leppestift, solen og kjemiske kjegler – velg det som passer din livsstil, dine ønsker og ambisjoner – og vanlige oppgaver vil bli mer interessante, og hverdager vil bli malt i nye, sterke farger.',
    'prazdniki_descr' => 'Liker du høytider? Men hvem liker dem ikke - venner, gaver, igjen samme helg. For å gjøre ventetiden på høytidene hyggeligere, kortere og varmere, kan du ikke bare telle dagene på kalenderen, men også sette det tilsvarende ikonet som musepeker. La oss begynne med nyttår - vi vil velge et juletre, en gave eller julenissen, slik at ferien er lys og munter. Kanskje pepperkakegutt vil være nærmere - morsom, søt og alltid munter? Med ham vil det sikkert ikke være tid til å være trist og lei. Vi fortsetter å feire med cupider og muntre hjerter, og det er ikke langt til påskeharen. Et sted blant høytidene vil det være en bursdag, som vil være enda hyggeligere å vente med ballonger i stedet for standard pekerpil. Og i Halloween kan du overraske kolleger og de rundt deg med en uvanlig musepeker i form av et illevarslende gresskar eller et spøkelse. Et sett med pekere for høytidene er en mulighet til å lysne opp forventningene, stille inn på forhånd for den kommende moroa og opprettholde et utmerket humør ikke bare på tampen av feiringen, men gjennom hele året.',
    'flagi_descr' => 'Flagget er et unikt symbol som er mye brukt i alle sosiale nettverk. Vi tenkte, hvorfor ikke lage markøren til et flagg? Tross alt er det veldig lyst og uvanlig. Nå kan du tilbringe hver dag i selskap med et nytt land, og arbeidet vil ikke være så monotont og kjedelig. Musemarkører kan nå gjøres om til det nasjonale flagget til Kina eller USA, Japan eller Canada, og i ytterligere 38 flaggalternativer, og du kan velge enten den vanlige pilformen i en uvanlig farge eller markøren i form av selve flagget. Dette settet vil appellere til alle elskere av reiser. Med det kan du planlegge nye turer og drømme om lange reiser. Har du planlagt ferie? Vis alle hvilket land du vil dra til. Kanskje du bestemte deg for å lære et nytt fremmedspråk? Da vil denne markøren definitivt støtte deg og motivere deg til å studere nøye. Eller liker du bare flagg som Sheldon? I alle tilfeller vil Flag-markørkolleksjonen være et flott tillegg til skrivebordet ditt og vil flytte deg til nye oppdagelser.',
    'vokrug_sveta_descr' => 'Alle liker å reise. Hvor fantastisk det er å besøke nye land og byer, se severdighetene og ha det flott i den nye kulturen. Det er synd at vi ikke kan reise så ofte, men vi prøvde å fikse det. Settet med markører «Rundt om i verden» er en samling av de mest slående bildene, symboler for forskjellige land, ved hjelp av hvilke du selv hjemme kan føle deg som en ekte reisende. I settet vårt kan du finne Japan og Australia, Italia og Canada, USA og Mexico - de mest interessante, originale og pittoreske landene i verden. Markørbildet kan bli en standard pil, i fargene på landets flagg, eller bli en av hovedattraksjonene i staten. For eksempel kan du åpne dokumenter med det skjeve tårnet i Pisa, og lage presentasjoner ved hjelp av Frihetsgudinnen. Vi garanterer - suksess vil være sikret. Vel, eller hvis ikke suksess, så smilene til kolleger og anerkjennelse av originalitet - helt sikkert. Ja, og å antyde til ledelsen at det er på tide å dra på ferie vil også være verdt det - bare sett kofferten eller flyet som markør - og mest sannsynlig vil du fly veldig snart.',
    'eda_i_napitki_descr' => 'Et sett med markører i form av produkter er en utrolig samling av lyse, velsmakende og appetittvekkende bilder som alle definitivt vil like, og vil være et flott tillegg til nettleseren. Har du noen gang klikket på brokkoli eller pommes frites? Du har en slik mulighet - bare last ned et nytt sett med markører og sett dem i stedet for en kjedelig hvit pil. Markører "Mat" er laget både i form av en standard trekantet peker, og i form av produkter. Her finner du grønnsaker og frukt, dine favorittretter, som pizza eller pølser, kaffe, slikkepinner og mye mer, som lyser opp enhver dag. Elsker kaffe, men er det ikke så bra å drikke det hele dagen? Suppler kostholdet ditt med virtuell kaffe, som også vil styrke og vekke deg, samt gi levende følelser. En bratt markør i form av en virtuell smultring vil ikke skade figuren, samtidig som den gir levende følelser og gleder. Du kan bruke favorittmarkørene dine eller endre bildet hver dag - et stort utvalg av markører vil bidra til å fargelegge hverdagen og legge til nye farger til kjente handlinger.',
    'cvetnye_descr' => 'Markøren er hovedelementet i nettleseren, som vi bruker hele arbeidsdagen, studerer, kommuniserer og slapper av med. Standardvisningen av markøren er kjedelig og til og med litt deprimerende, men likevel er denne formen for mange praktisk, og å endre den vil være ubehagelig. Men for denne situasjonen har vi en løsning - et sett med markører i lyse, glade farger som vil legge til variasjon i hverdagen din og gjøre det enklere og raskere å løse eventuelle problemer. Hvis du tenker på hvordan du kan endre fargen på markøren, svarer vi - last ned samlingen vår og velg lyse løsninger for hver dag! Du kan velge monokrome toner i forskjellige farger som passer humøret eller spesifikasjonene til arbeidet. For eksempel, når du arbeider med standard dokumenter, vil en lilla markør skille seg ut mot bakgrunnen, og på en mørk bakgrunn vil det tvert imot være enklere å jobbe med gule markører. Hvis du vil ha en eksplosjon av farger, lysstyrke og maksimal originalitet - velg en regnbue markør som inkluderer alle spekterets farger - med dette ikonet vil humøret definitivt være bra hele dagen.',
    'prank_descr' => 'Spøker på jobben er ikke alltid velkomne, da de ofte forstyrrer arbeidsflyten. Men med det nye settet med «Pranks»-markører kan du snilt spille et puss på kollegene eller vennene dine uten å skade arbeidet eller studiene dine. Vi har utviklet en spesiell samling som vil more alle og gi en grunn til å slappe av litt midt i den travle prosessen med å jobbe eller utføre en annen oppgave. For å endre musemarkøren, bare last ned settet til enheten og velg designet du liker i parameterne. For eksempel kan du få en markør av en standard form, men i en invertert tilstand eller en pil buet av en bølge. Denne formen vil overhodet ikke hindre arbeidsprosessen, men samtidig vil den presentere et fantastisk humør og sette deg i et positivt humør. Endre visningsinnstillingene for markøren i henhold til humøret ditt eller hver dag - og enhver oppgave vil bli mer interessant og hyggelig, og hverdagen vil slutte å forårsake negative følelser. Dessuten kan slike markører brukes selv for seriøse prosjekter - de har nøytrale farger og skiller seg ikke ut fra skrivebordet.',
    'startovyj_nabor_descr' => 'Markører fra startkolleksjonen er en blanding av standard former og størrelser med et lyst, uvanlig utseende. Dette er et utmerket valg for de som foretrekker de vanlige formene, men ønsker å bringe mangfold, originalitet og lysstyrke til hverdagen. Kolleksjonen har en håndmarkør og en kjent pil i en rekke varianter - fra Google Chrome-logoen til uttrykksikoner, du kan til og med møte en for lengst glemt drage med kaktuser og nostalgi her.  Vi beviser at en standardmarkør også kan være interessant og attraktiv. Ulike farger, former, teksturer og interessant design vil hjelpe deg å velge markøren etter din smak eller endre den hver dag avhengig av humør eller oppgaver som utføres. Å endre nettlesermarkører er veldig enkelt - bare installer utvidelsen og last ned samlingen til enheten din. Morsomme, interessante markører vil ikke bare fargelegge arbeidsdagene, men også, for eksempel, bidra til å gjøre enhver presentasjon mer interessant, og ved hjelp av spesielt lyse markører, også rette oppmerksomheten mot individuelle elementer i rapporten.',
    'fortnite_descr' => 'Fortnite har erobret millioner av mennesker rundt om i verden. Spennende kamper, strategi og taktikk, eventyr - det har absorbert absolutt alt som spillere liker så godt. Vi kunne ikke holde oss unna og utviklet et sett med markører i stil med spillet som vil appellere ikke bare til ivrige spillere, men selv til de som først hørte om Fortnite. Fortnite-markørikonet er et bilde av en helt eller hans våpen, utarbeidet ned til minste detalj. Her kan du finne bilder av rever og fisk, masker av inferno og svarte riddere, sette deg en pil eller en ljå med pigger som en pil. Vi er sikre på at ingen vil forbli likegyldige! Å være skummel eller mystisk, original eller humoristisk - det er opp til deg. Velg din stil og følg den, eller sett egendefinerte markører i innstillingene og endre rollen din hver dag. Nå vil det bli mye mer interessant og hyggelig å utføre selv kjedelig og monotont arbeid - tiden vil fly raskt i et selskap med levende bilder og favorittkarakterer. Eller kanskje du vil arrangere konkurranser med kolleger, hvilken helt vil være sterkere? Valget er ditt!',
    'dota_2_descr' => 'DotA2 er nå ikke bare et enkelt spill, det er en ekte parallell verden. I virtuell virkelighet i DotA2 kan du gjøre alt - leve, kjempe, utvikle deg, reise, få venner. Generelt sett er alt som i livet, bare til tider mer interessant. Dota 2-markører er en fortsettelse av en strategi som lar deg få levende følelser og uttrykke deg selv i den virkelige verden. Et nytt sett med markører inkluderer de mest slående karakterene i spillet, samt originale gjenstander som ikke kan forveksles med noe annet. Velg en markør som vil være nærmere deg - og begi deg ut på et eventyr uten å forlate arbeidsplassen din. Hvor kjedelig er det noen ganger å være på jobb eller å utføre pedagogiske oppgaver, men med spillmarkører vil dette problemet ikke lenger konfrontere deg. Litt fantasi, en lys markør - og voila, enhver virksomhet vil være et uvanlig eventyr, som det ikke vil være vanskelig og interessant å takle. Du trenger ikke å holde deg tilbake. Liker du Dota? Da må du laste ned samlingen vår, velge en eller flere tilfeldige markører på en gang - og hver ny dag vil bli lysere, mer interessant og mettet.',
    'minecraft_descr' => 'Musepeker i form av standardpiler og fingre har for lengst blitt kjedelige for alle. Hvis du er en fan av det uvanlige og originale, så er det på tide å endre musepekeren og gi den et mer interessant design. Vi har utviklet en samling av pekere i stil med det verdensberømte Minecraft-spillet, hvor du kan finne de mest slående karakterene. Ulv og rev, Alex og Creeper, diamantsverd og fisk - du kan velge den du liker best eller installere en ny helt hver dag. Dette er ekte pekere for spillere, og absolutt alle vil like dem - tross alt, hvem av oss har ikke spilt Minecraft? Vi er sikre på at disse rett og slett ikke finnes. Ned med det kjedelige hverdagen - det er på tide å dykke ned i eventyr, som kan gjøres selv uten å forlate ditt hjem eller kontorstol. Det vil være mer interessant å forberede en rapport og redusere saldoen med en pistol - enhver oppgave vil bli mer behagelig og vil ikke la deg kjede deg på stedet. Last ned den nye Minecraft pekere samlingen - sett dem og selv på den gråeste og mest kjedelige dagen vil humøret ditt alltid være på sitt beste. Og kolleger vil misunne resultatene dine - det er rett og slett umulig å ikke gjøre jobben din ved hjelp av de modige heltene i Minecraft.',
    'christmas' => 'Jul',
    'kirby_descr' => 'Historien om videospillet "Kirby" begynte allerede på 90-tallet av forrige århundre. Det består av mange serier som ble utviklet av Nintendo og HAL Laboratory. Spillet er beregnet for barn fra ett og et halvt til 8 år. Populariteten kan bedømmes ut fra antall solgte eksemplarer. Over 34 millioner på verdensbasis.
Hovedkarakteren i Kirby er den eponymiske rosa skapningen. Den lever på en planet som heter Pop Star, og beskytter den periodisk fra forskjellige farer. Kirby kan puste inn noen objekter og fiender for å lære deres evner: nærkamp, besittelse av et sverd, pusting av ild, etc. Men den rosa pufferen ikke bare kjemper med fiender, men løser også forskjellige gåter, reiser til andre land og kan til og med fly i nivå.
Du kan spille dette videospillet på Nintendo eller Game Boy konsoller. I alle serier er det søte helter, god grafikk og morsomme lydspor. Forresten, i nesten 30 år siden utgivelsen av den første versjonen, klarte verden å se 20 Kirby-serier. Denne indikatoren, kombinert med det multimillionsstore volumet av solgte eksemplarer, hjalp spillet med å være i TOP 50 av de mest suksessrike og ettertraktede videospillene i spillindustrien.
Elsker du Kirby så mye at du ønsker å se denne karakteren hvor som helst? Bruk deretter Kirby-samlingen og gjør den vanlige musepekeren om til hovedpersonen i ditt favoritt videospill! Vi er sikre på at du vil like det nye utseendet på markøren.',
];
