<?php

return [
    'title' => 'Cursor Style - Retningslinjer for informasjonskapsler',
    'descr' => 'En retningslinje for informasjonskapsler når du besøker nettstedet vårt cursor.style eller "Cursor Style"-utvidelsen. Noen regler du bør vurdere når du bruker produktet vårt.',
    'text' => '<h2> Retningslinjer for informasjonskapsler </h2>
<p> Når du besøker nettstedet vårt cursor.style eller "Cursor Style"-utvidelsen i nettleserpanelet, eller når du samhandler med våre representanter ("Tjenesten"), vil vi bruke (og la tredjeparter bruke) web-beacons, informasjonskapsler, pikselkoder, skript, tagger, APIer og annen teknologi ("Sporingsteknologier"). Dette er forklart i disse retningslinjene ("Retningslinjer for informasjonskapsler"), som er en del av våre <a href="/privacy"> Retningslinjer for personvern </a>. </p>
<p> Sporingsteknologier lar oss automatisk samle informasjon om deg og din oppførsel på Internett for å forbedre navigasjonen din på tjenesten vår, forbedre ytelsen til tjenesten vår og lette opplevelsen din i tjenesten vår. Vi bruker også denne informasjonen til å samle statistikk om bruken av tjenesten vår, utføre analyser, levere innhold som passer dine interesser og administrere tjenester for våre brukere, kunder og partnere. Vi lar også tredjeparter samle inn informasjon om deg ved hjelp av sporingsteknologier. </p>
<p> Hva er informasjonskapsler? Informasjonskapsler er små tekstfiler (bestående av bare bokstaver og tall) som webserveren plasserer på datamaskinen eller mobilenheten din når du besøker en nettside. Bruk av en informasjonskapsel kan bidra til å gjøre tjenestene våre mer brukervennlige, for eksempel ved å huske språkinnstillingene og innstillingene dine. Du kan finne mer informasjon om informasjonskapsler på <a href="http://www.allaboutcookies.org"> allaboutcookies.org </a>. </p>
<p> Informasjonskapsler er mye brukt for nettsideytelse. Bruk av informasjonskapsler lar deg effektivt navigere mellom sider. Informasjonskapsler husker preferansene dine og gjør samspillet mellom deg og tjenestene jevnere og mer effektivt. </p>
<p> Vi bruker sporingsteknologier når du besøker eller får tilgang til tjenestene våre (vanligvis når du besøker nettstedene våre) - de kalles "Førsteparts sporingsteknologier". I tillegg lagres sporingsteknologier av andre tredjeparts organisasjoner (for eksempel våre analyseleverandører, forretningspartnere og annonsører) som legger ut innhold på tjenestene våre - de kalles "Tredjeparts sporingsteknologier". Begge typer sporingsteknologier kan lagres enten i tiden du besøker tjenestene våre, eller for gjentatte besøk. </p>
<h3> Hvilke typer sporingsteknologier bruker vi? Det er fem hovedtyper sporingsteknologier: </h3>
<ul>
<li> <b> Strengt nødvendige sporingsteknologier </b> <br> <p> Disse sporingsteknologiene er nødvendige slik at du kan logge inn, navigere og bruke funksjonene til tjenestene våre eller levere tjenesten du ber om (for eksempel brukernavnet ditt). Vi trenger ikke ditt samtykke for å bruke disse sporingsteknologiene. Disse sporingsteknologiene kan brukes til sikkerhets- og integritetsformål, for eksempel for å identifisere brudd på våre retningslinjer, samt til støtte- eller sikkerhetsfunksjoner. </p> </li>
<li> <b> Funksjonalitetssporingsteknologier </b> <br> <p>
Disse sporingsteknologiene gjør det mulig for tjenestene våre å huske valgene dine (som språk) og tilby avanserte og personlige funksjoner. For eksempel brukes disse sporingsteknologiene til autentisering (for å huske når du er logget inn) og støtte andre funksjoner i tjenestene våre. </p> </li>
<li> <b> Ytelsessporingsteknologier </b> <br> <p>
Disse sporingsteknologiene samler informasjon om din online aktivitet (for eksempel varigheten av besøket ditt på tjenestene våre), inkludert atferdsdata og indikatorer for innholdsengasjement. Disse sporingsteknologiene brukes til analyse, forskning og statistikk (basert på aggregert informasjon). </p> </li>
<li> <b> Markedsførings- eller annonseringssporings teknologier </b> <br> <p>
Disse sporingsteknologiene brukes til å gi deg spesialtilbud og reklame basert på dine interesser, samt å gjennomføre e-postmarkedsføringskampanjer. De kan også brukes til å begrense antall ganger en annonse vises, samt å måle effektiviteten av en annonsekampanje. De er vanligvis vert av våre annonsører (for eksempel annonsenettverk) og gir dem en ide om personene som ser og samhandler med annonsene deres, besøker nettstedene deres eller bruker appen deres. </p> </li>
<li> <b> Sporingsteknologier for sosiale medier </b> <br> <p>
Nettstedet vårt inkluderer funksjoner for sosiale nettverk, for eksempel Like- eller Del-knappene på Facebook og Vkontakte, eller påloggings tjenester fra tredjeparter. Disse funksjonene legges enten ut av en tredjepart eller legges ut direkte på tjenestene våre. Samspillet ditt med disse funksjonene er underlagt personvernerklæringen til selskapet som leverer disse funksjonene. </p> </li> </ul>
<h3> Følgende er informasjonskapslene du kan finne i tjenestene våre: </h3>
<ul>
<li> <b> Informasjonskapsler for analyse </b> <br> <p> Disse sporingsteknologiene brukes til å samle informasjon om hvordan du samhandler med innhold i tjenestene våre, attribusjonsformål (for eksempel henvisnings-URLer), etc. Vi bruker denne informasjonen til å utarbeide rapporter, beregne inntektene som skyldes oss, og hjelpe oss med å forbedre tjenestene og tilby personlig tilpassede produkter og innhold. </p> </li>
<li> <b> Google Analytics </b> <br> <p> Denne informasjonskapselen brukes til å samle inn informasjon om hvordan besøkende bruker plattformen vår. Vi bruker denne informasjonen til å utarbeide rapporter og forbedre plattformen. Informasjonskapsler samler inn informasjon i anonym form, inkludert antall plattformbesøkende, hvor besøkende kom til plattformen og sidene de besøkte. <br> <a href = "https://policies.google.com/privacy?hl=en" > Retningslinjer for personvern </a> </p> </li>
<li> <b> Google Tag Manager </b> <br> <p> Denne informasjonskapselen er knyttet til Google Tag Manager, som vi bruker til å laste inn skript på sidene på nettstedet vårt. <br> <a href = "https: / /policies.google.com/privacy?hl=en"> Retningslinjer for personvern </a> </p> </li>
</ul>
<p> Vær oppmerksom på at vi ikke gjenkjenner eller svarer på automatiske nettleservarsler angående sporingsteknologier, inkludert Do Not Track-forespørsler. Det finnes imidlertid forskjellige måter å administrere og administrere informasjonskapselinnstillingene dine. Husk at når du sletter eller blokkerer informasjonskapsler, kan noen funksjoner i tjenestene ikke fungere korrekt eller ikke så effektivt. </p>
<p> De fleste nettlesere gir deg generell informasjon om informasjonskapsler, lar deg se hvilke informasjonskapsler som er lagret på enheten din, lar deg slette dem alle eller individuelt, og lar deg også blokkere eller tillate bruk av informasjonskapsler for alle nettsteder eller individuelt utvalgte nettsteder. Du kan også deaktivere tredjeparts informasjonskapsler separat. Vær oppmerksom på at innstillingene som tilbys av nettleseren eller enheten ofte bare gjelder for den aktuelle nettleseren eller enheten. </p>
<h3> Informasjon om informasjonskapsler finnes vanligvis i Hjelp-delen i en nettleser. </h3>
<p> Følgende er lenker til noen ofte brukte nettlesere: </p>
<p><a href="https://support.google.com/chrome/answer/95647?hl=en"> Chrome </a> <br>
<a href="https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies"> Internet Explorer og Microsoft Edge </a> <br>
<a href="https://support.mozilla.org/en/kb/kuki-informaciya-kotoruyu-veb-sajty-hranyat-na-vas"> Mozilla Firefox </a> <br>
<a href="https://support.apple.com/ru-ru/guide/safari/sfri11471/mac"> Safari </a> </p>
<p> Du kan slå av noen tredjeparts informasjonskapsler for målretting / reklame ved å klikke på følgende lenke: <a href="http://optout.networkadvertising.org/?c=1"> Velg bort interessebasert reklame </a>. </p>
				',
];
