<?php

return [
    'title' => 'Cursor Style - Personvernregler',
    'descr' => 'I “Cursor Style,” tilgjengelig på cursor.style eller gjennom Chrome-utvidelsen, er en av våre toppprioriteter personvernet til våre besøkende. Det er i denne seksjonen at vi vil snakke om alle aspekter ved å jobbe med utvidelsen.',
    'text' => '<h2> Personvernregler </h2>
                <p> I Cursor Style, tilgjengelig på <a href="https://cursor.style"> cursor.style </a> eller gjennom Chrome-utvidelsen, er en av våre toppprioriteringer personvernet til våre besøkende. Dette dokumentet om personvernregler inneholder typene informasjon som er samlet inn og registrert av cursor.style-nettstedet, og hvordan vi bruker det. Hvis du har flere spørsmål eller trenger mer informasjon om våre personvernregler, ikke nøl med å kontakte oss. </p>
                <p>  "Cursor Style"-utvidelsen og nettstedet følger standard prosedyre for bruk av loggfiler. Disse filene registrerer besøkende når de besøker nettsteder eller bruker utvidelsen vår. Alle hosting selskaper gjør dette og er en del av hosting tjenesten analytics. Informasjon som samles inn gjennom loggfiler inkluderer Internet Protocol (IP)-adresser, nettlesertype, Internett-leverandør (ISP), dato og tidsstempel, overgangs-/utgangssider og muligens antall klikk. De er ikke knyttet til personlig identifiserbar informasjon. Hensikten med denne informasjonen er å analysere trender, administrere nettstedet og utvide, spore bevegelsen til brukere på nettstedet og utvide, og samle demografisk informasjon. </p>
                <p>  Som ethvert annet nettsted bruker cursor.style informasjonskapsler. Disse informasjonskapslene brukes til å lagre informasjon, inkludert preferansene til den besøkende og sidene på nettstedet som den besøkende besøkte eller besøkte. Denne informasjonen brukes til å optimalisere brukeropplevelsen ved å tilpasse innholdet på nettsiden vår basert på typen av besøkendes nettleser og / eller annen informasjon. Vi bruker også tredjepartsannonser på cursor.style for å støtte prosjektet og støtte nettstedet vårt. Noen av disse annonsørene kan bruke teknologier som informasjonskapsler og web beacons når de annonserer på nettstedet vårt, som også vil sende disse annonsørene (for eksempel Google gjennom Google AdSense-programmet) informasjon, inkludert IP-adressen din, Internett-leverandøren din, nettleseren som du brukte til å besøke nettstedet vårt, og i noen tilfeller, hvis du har Flash installert. Dette brukes vanligvis til geotargeting-formål (for eksempel visning av annonser for salg av varer i byen din) eller for å vise bestemte annonser basert på bestemte nettsteder som er besøkt (for eksempel å vise kjøpskunngjøringer til de som ofte besøker shoppingsteder). </ P >
                <p>  Du kan deaktivere eller selektivt deaktivere våre eller tredjeparts informasjonskapsler i nettleserinnstillingene eller ved å administrere innstillinger i programmer som Kaspersky, etc. Dette kan imidlertid påvirke hvordan du samhandler med nettstedet vårt, så vel som med andre nettsteder. Dette kan omfatte manglende evne til å logge inn på tjenester eller programmer, for eksempel å logge inn på forum eller kontoer. </p>
<p> Google er en av tredjepartsleverandørene på nettstedet vårt. Det bruker også informasjonskapsler, kjent som DART-informasjonskapsler, for å vise annonser til besøkende på nettstedet vårt basert på deres besøk på cursor.style og andre nettsteder på Internett. Besøkende kan imidlertid velge bort bruken av DART-informasjonskapsler ved å besøke Googles retningslinjer for annonsering og innholdsnettverk på <a href="https://policies.google.com/technologies/ads"> følgende adresse </a>. Noen av annonsørene på nettstedet vårt kan bruke informasjonskapsler og web beacons. Hver av våre annonseringspartnere har sine egne retningslinjer for personvern for deres retningslinjer angående brukerdata. Du kan lese mer om deres personvernregler <a href="https://policies.google.com/technologies/ads"> her </a>. </p>
                <p>  Nettstedet vårt bruker Google Analytics, en webanalysetjeneste fra Google, Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043 USA, www.google.com (“Google Analytics” eller “Google”). Google Analytics bruker informasjonskapsler som er lagret på datamaskinen din for å lette analysen av din bruk av nettstedet. Informasjon generert av disse informasjonskapslene, for eksempel tidspunkt, sted og frekvens av dine besøk på nettstedet vårt, inkludert IP-adressen din, overføres til et Google-sted i USA og blir lagret der. Google kan også overføre denne informasjonen til tredjeparter hvis det kreves av loven eller hvis tredjeparter behandler disse dataene på vegne av Google. Google sier at det aldri vil assosiere IP-adressen din med andre Google-data. Du kan forhindre innstilling av informasjonskapsler ved å endre programvareinnstillingene i nettleseren din tilsvarende, som spesifisert i disse personvernreglene. Du bør imidlertid være oppmerksom på at du på denne måten ikke vil kunne bruke alle funksjonene på nettstedet vårt fullt ut. </p>
                <p>  Google Analytics bruker også elektroniske bilder kjent som web beacons (noen ganger kalt enkelt-piksel GIF-er) og brukes med informasjonskapsler for å kompilere aggregeret statistikk for å analysere bruken av nettstedet vårt.
 Du kan finne mer informasjon om hvordan du installerer nettleserutvidelsen som du lenker til ovenfor <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> lenke </a>.
 Dette nettstedet bruker Google Tag Manager. Denne tjenesten lar deg administrere nettstedets tagger gjennom grensesnittet. Google Tag Manager implementerer bare tagger. Dette betyr at informasjonskapsler ikke er satt og ingen personlige data registreres. Google Tag Manager starter andre tagger, som igjen kan registrere data. Google Tag Manager har imidlertid ikke tilgang til disse dataene. Hvis tagger er deaktivert på domene- eller informasjonskapselnivå, lagres de for alle sporingskoder, hvis de er implementert ved hjelp av Google Tag Manager. Du kan lære mer om Google Tag Manager ved å besøke <a href="http://www.google.com/tagmanager/use-policy.html"> lenke </a>. </p>
<p>  Du kan sette deg inn i denne listen for å finne personvernreglene for hver av "Cursor Style" annonsørene. Tredjeparts annonseservere eller annonsenettverk bruker teknologier som informasjonskapsler, JavaScript eller web beacons, som brukes i deres respektive annonser og lenker, som vises i “Cursor Style” og sendes direkte til brukernes nettleser. De får automatisk IP-adressen din når dette skjer. Disse teknologiene brukes til å måle effektiviteten av annonseringskampanjene deres og / eller å tilpasse annonseringsinnholdet du ser på nettstedene du besøker. Vær oppmerksom på at “Cursor Style” ikke har tilgang til eller kontroll over disse informasjonskapslene som brukes av tredjeparts annonsører. Cursor Styles personvernregler gjelder ikke for andre annonsører eller nettsteder. Derfor anbefaler vi at du gjennomgår de relevante personvernreglene for disse tredjeparts annonseserverne for mer informasjon. Det kan omfatte deres metoder og instruksjoner om hvordan du kan velge bort visse alternativer. Du kan finne lenker til disse tredjeparts personvernreglene ovenfor eller på nettstedene til disse tredjepartstjenestene. </p>
                <p>  Du kan deaktivere informasjonskapsler i nettleserinnstillingene dine. For å lære mer om informasjonskapsler i bestemte nettlesere, kan du finne det på deres respektive nettlesernettsteder. En annen del av vår prioritet er å legge til barnbeskyttelse når du bruker Internett. Vi oppfordrer foreldre og verger til å observere, delta og / eller overvåke og lede aktivitetene deres på Internett. "Cursor Style" samler ikke bevisst inn personlig informasjon fra barn under 13 år. Hvis du tror at barnet ditt har gitt slik informasjon på nettstedet vårt, anbefaler vi på det sterkeste at du kontakter oss umiddelbart, og vi vil gjøre vårt beste for raskt å fjerne slik informasjon fra våre poster. Disse personvernreglene gjelder bare for våre online aktiviteter og er gyldige for besøkende på nettstedet vårt i forhold til informasjonen de delte og / eller samlet inn i “Cursor Style”. Disse retningslinjene gjelder ikke for informasjon som er samlet inn offline eller gjennom andre kanaler enn dette nettstedet. </p>
                <p>  Du kan lese mer om bruk av informasjonskapsler i tjenesten vår i vår <a href="/cookie-policy"> Cookie Policy </a>. </p> ',
];
