<?php

return [
    'title' => 'Cursor Style - Vilkår for bruk av produktet vårt',
    'descr' => 'Vilkårene for bruk er inngått mellom deg og “Cursor Style” (“Tjenesten”, “vi” eller “Tjenesten”). Denne tjenesten tilbys og er tilgjengelig for brukere som er 13 år og eldre, kun for personlig bruk og ikke for kommersiell bruk.',
    'text' => '<h2> Vilkår for bruk </h2>
<h3> VENNLIGST LES DISSE VILKÅRENE FØR DU BRUKER NETTSTEDET OG UTVIDELSEN. </h3>
<p> Disse bruksvilkårene er inngått mellom deg og "Cursor Style" ("Tjenesten", "vi" eller "Tjenesten"). Følgende vilkår og betingelser, sammen med alle dokumenter som de uttrykkelig inkluderer ved referanse (samlet sett, disse "Bruksvilkårene"), regulerer din tilgang til og bruk av cursor.style-nettstedet og nettleserutvidelsene, inkludert alt innhold, funksjonalitet og tjenester som tilbys på eller gjennom tjenesten vår (sammen "Tjenesten"). </p>
<p> Ved å bruke nettstedet eller utvidelsen, aksepterer du og samtykker i å overholde disse bruksvilkårene. Hvis du ikke godtar disse bruksvilkårene eller våre <a href="/privacy"> Personvernregler </a>, skal du ikke få tilgang til eller bruke nettstedet og utvidelsen. </p>
<p> Denne tjenesten tilbys og er kun tilgjengelig for brukere i alderen 13 år og eldre, kun til personlig bruk og ikke til kommersiell bruk. Ved å bruke denne tjenesten, representerer og garanterer du at du er (I) 13 år eller eldre, (II) du er ikke forhindret fra å bruke nettstedene i henhold til gjeldende lov, og (III) du bruker tjenesten kun for dine personlige behov. Hvis du ikke oppfyller disse kravene, bør du ikke få tilgang til eller bruke tjenesten. </p>
<p> Vi kan endre og oppdatere disse bruksvilkårene fra tid til annen etter eget skjønn. Alle endringer trer i kraft umiddelbart etter publiseringen. Din fortsatte bruk av tjenesten etter publiseringen av de reviderte bruksvilkårene betyr at du aksepterer og samtykker i endringene. Du forventes å besøke denne siden ofte for å holde deg orientert om eventuelle endringer, da de er bindende for deg. </p>
<p> Vi forbeholder oss retten til å trekke tilbake eller endre dette nettstedet og utvidelsen, eventuelle tjenester eller materialer som vi tilbyr på nettstedet og utvidelsen, etter eget skjønn, uten varsel. Vi garanterer ikke at nettstedet vårt, utvidelsen eller noe innhold på det alltid vil være tilgjengelig eller vil bli avbrutt. Vi vil ikke være ansvarlige hvis hele eller deler av tjenesten av en eller annen grunn ikke er tilgjengelig til enhver tid eller i løpet av en periode. Fra tid til annen kan vi begrense tilgangen til visse deler av nettstedet eller utvidelsen eller hele tjenesten for brukere. </p>
<p> Du er ansvarlig for å iverksette alle nødvendige tiltak for å sikre at du har tilgang til tjenesten. Sikre at alle personer som får tilgang til tjenesten gjennom din Internett-tilkobling er klar over disse bruksvilkårene og overholder dem. For å få tilgang til tjenesten eller noen av ressursene den tilbyr, kan du bli bedt om å oppgi visse opplysninger eller annen informasjon. Du samtykker i at all informasjon du gir oss ved hjelp av denne tjenesten eller på annen måte, inkludert, men ikke begrenset til, bruk av interaktive funksjoner i tjenesten, er underlagt våre <a href="/privacy"> Personvernregler </a>, og du samtykker i alle handlinger vi foretar angående din informasjon i samsvar med våre <a href="/privacy"> Personvernregler </a>. </p>
<p> Du må være spesielt forsiktig når du skriver inn personlig informasjon i tjenesten på en offentlig eller delt datamaskin, slik at andre ikke kan se eller registrere din personlige informasjon. Nettstedet, utvidelsen og alt innhold, funksjoner og funksjoner (inkludert, men ikke begrenset til, all informasjon, utvidelsen, tekst, bilder, bilder, og markører, samt deres design, utvelgelse og plassering) tilhører "Cursor Style", dets lisensgivere eller andre leverandører av slike materialer er beskyttet av opphavsrett, varemerke, patent, forretningshemmelighet og andre lover om immateriell eiendom eller eiendomsrettigheter. </p>
<p> Disse bruksvilkårene lar deg bruke nettstedene kun til din personlige, ikke-kommersielle bruk. Du må ikke reprodusere, distribuere, modifisere, lage avledede verk, publisere på nytt, laste ned, lagre eller overføre noe materiale på nettstedet vårt, bortsett fra følgende tilfeller: du kan bruke det til personlige behov, du kan skrive ut eller laste ned en kopi av en rimelig mengde sider på nettstedet og utvidelsen eller deres innhold til personlig, ikke-kommersiell bruk, og ikke til videre reproduksjon, publisering eller distribusjon. </p>
<p> Du må ikke endre kopier av noe materiale fra dette nettstedet eller utvidelsen og deres innhold. Slett eller endre eventuelle opphavsretts-, varemerke- eller andre eiendomsrettigheter fra kopier av dette nettstedet og utvidelsen. Du må ikke ha tilgang til eller bruke for kommersielle formål noen del av nettstedene eller utvidelsene, samt tjenester eller materialer som er tilgjengelige via nettstedet eller utvidelsen. </p>
<p> Hvis du vil bruke noe materiale på nettsteder eller utvidelser annet enn de som er oppført i denne seksjonen, send en forespørsel på støttesiden til Chrome Web Store. </p>
<p> Hvis du skriver ut, kopierer, endrer, laster ned eller på annen måte bruker eller gir noen andre tilgang til noen del av nettstedet eller utvidelsen i strid med bruksvilkårene, avsluttes din rett til å bruke nettstedet og utvidelsen umiddelbart, og du må, etter eget skjønn, returnere eller ødelegge eventuelle kopier av materialene du har. Enhver bruk av utvidelsens nettsted som ikke er uttrykkelig tillatt i disse bruksvilkårene, er i strid med disse bruksvilkårene og kan krenke opphavsrettigheter, varemerker og andre lover. </p>
<p> Navnet “Cursor Style”, logoen “Cursor Style” og alle tilknyttede navn, logoer, bilder, markører og tjenestenavn, design og slagord er varemerker for “Cursor Style” eller dets tilknyttede selskaper eller lisensgivere. Du må ikke bruke slike merker uten skriftlig forhåndstillatelse fra tjenesten. Alle andre navn, logoer, produkt- og tjenestenavn, design og slagord på dette nettstedet og i utvidelsen er varemerker for sine respektive eiere. Du kan bare bruke tjenesten til legitime formål og i samsvar med disse bruksvilkårene. </p>
<h3> Du godtar å IKKE bruke tjenesten: </h3>
<ul>
<li> På noen måte som bryter med gjeldende føderale, regionale, lokale eller internasjonale lover eller forskrifter (inkludert, men ikke begrenset til, lover angående eksport av data eller programvare til Russland og andre land). </li>
<li> I den hensikt å utnytte, skade eller forsøke å bruke eller skade mindreårige, utsette dem for upassende innhold, be om informasjon som identifiserer dem, eller på annen måte. </li>
<li> For å sende, bevisst motta, laste ned, bruke eller gjenbruke materialer som ikke er i samsvar med disse bruksvilkårene. </li>
<li> Overføre eller kjøpe sending av annonser eller reklamemateriell uten vår skriftlige forhåndsgodkjenning, inkludert "uønskede brev", "kjedebrev" eller "søppelpost" eller andre lignende tilbud. </li>
<li> For å utgi seg for eller forsøke å utgi seg for en “Cursor Style”-ansatt, en annen bruker eller en annen person eller organisasjon (inkludert, men ikke begrenset til, bruk av e-postadresser eller aliaser knyttet til noe av det ovennevnte). </li>
<li> Deltakelse i andre handlinger som begrenser eller hindrer bruken av tjenesten eller bruken av noen, eller som vi fastslår, kan skade tjenesten eller brukerne av tjenesten eller gjøre dem ansvarlige. </li> </ul>
<h3> I tillegg samtykker du IKKE til: </h3>
<ul>
<li> Bruk tjenesten på noen måte som kan deaktivere, overbelaste, skade eller forringe driften av nettstedet, utvide eller forstyrre bruken av tjenesten av noen annen part, inkludert deres evne til å delta i sanntidshandlinger gjennom tjenesten. </li>
<li> Bruk noen automatiseringsverktøy, prosesser eller midler for å få tilgang til tjenesten for noe formål, inkludert overvåking eller kopiering av noe materiale i tjenesten. </li>
<li> Bruk enhver manuell prosess for å spore eller kopiere noe materiale på tjenesten eller for andre uautoriserte formål uten vår skriftlige forhåndsgodkjenning. </li>
<li> Bruk enheter, programvare eller prosedyrer som forstyrrer den normale driften av tjenesten. </li>
<li> Introduser virus, trojanske hester, ormer, logiske bomber eller annet materiale som er skadelig eller teknologisk skadelig. </li>
<li> Prøv å få uautorisert tilgang, forstyrre, skade eller forstyrre noen del av tjenesten, serveren der tjenesten er lagret, eller en server, datamaskin eller database koblet til tjenesten. </li>
<li> Angripe en tjeneste ved hjelp av et tjenestenektangrep eller et distribuert tjenestenektangrep. </li> </ul>
<p> Informasjon som er gitt på eller gjennom tjenesten, er kun gitt for generelle informasjonsformål. Vi garanterer ikke nøyaktigheten, fullstendigheten eller nytten av denne informasjonen. Du stoler på slik informasjon utelukkende på egen risiko. Vi fraskriver oss alt ansvar og erstatningsansvar som følge av eventuell avhengighet av slike materialer fra deg, andre besøkende på tjenesten eller alle som kan bli informert om noe av deres innhold. </p>
<p> Denne tjenesten inkluderer innhold levert av tredjeparter, inkludert materialer levert av andre brukere og tredjeparts lisensgivere, syndikatorer, aggregatorer og/eller rapporteringstjenester. Alle uttalelser og/eller meninger som uttrykkes i disse materialene, samt alle artikler og svar på spørsmål og annet innhold, bortsett fra innholdet som leveres av tjenesten, er utelukkende meninger og ansvar for personen eller organisasjonen som leverer disse materialene. Disse materialene gjenspeiler ikke nødvendigvis synspunktene til tjenesten. Vi er ikke ansvarlige overfor deg eller noen tredjepart for innholdet eller nøyaktigheten av noe materiale levert av tredjeparter. </p>
<p> Vi kan oppdatere innholdet i tjenesten fra tid til annen, men innholdet er ikke nødvendigvis komplett eller aktuelt. Alt materiale på tjenesten kan være utdatert når som helst, og vi er ikke pålagt å oppdatere slikt materiale. Vi kan oppdatere, endre, endre informasjon og innhold på nettstedet og i utvidelsen, gjøre endringer og oppdateringer i henhold til vår egen beslutning. </p>
<p> All informasjon som vi samler inn på denne tjenesten er underlagt våre personvernregler. Ved å bruke tjenesten, samtykker du i alle handlinger som vi foretar i forhold til informasjonen din i samsvar med <a href="/privacy"> Personvernregler </a>. </p>
<p> Ytterligere vilkår kan også gjelde for visse deler, tjenester eller funksjoner i tjenesten. Alle slike tilleggsvilkår er herved innlemmet ved referanse i disse bruksvilkårene.
Du kan lenke til nettstedet eller utvidelsen vår hvis du gjør det på en ærlig og lovlig måte og ikke skader vårt rykte eller bruker det, men du bør ikke sette lenken på en slik måte at den tilbyr noen form for tilknytning, godkjenning eller godkjennelse fra vår side uten vårt skriftlige samtykke. </p>
<p> Tjenesten inneholder lenker til andre nettsteder og ressurser levert av tredjeparter, disse lenkene er kun gitt for enkelhets skyld. Dette inkluderer lenker i annonser, inkludert bannerannonser og sponsede lenker. Vi kontrollerer ikke innholdet på disse nettstedene eller ressursene og er ikke ansvarlige for dem eller for tap eller skade som kan skyldes bruken av dem. Hvis du bestemmer deg for å få tilgang til tredjepartsnettsteder knyttet til denne tjenesten, gjør du det på egen risiko og i samsvar med bruksvilkårene for slike nettsteder. Vi forbeholder oss retten til å tilbakekalle tillatelsen til å lenke uten forvarsel. </p>
<p> Du forstår at vi ikke kan og ikke garanterer eller garanterer at filene som er tilgjengelige for nedlasting via Internett eller på nettsteder ikke vil inneholde virus eller annen ondsinnet kode. Du er ansvarlig for implementeringen av prosedyrer og kontrollpunkter tilstrekkelige til å tilfredsstille dine spesielle krav til antivirusbeskyttelse og nøyaktigheten av datainntasting og -utgang, samt for å opprettholde midler eksterne til nettstedet vårt for å gjenopprette tapte data. VI VIL IKKE VÆRE ANSVARLIGE FOR NOEN SKADER ELLER SKADE SOM FORÅRSAKES AV DISTRIBUERT KNEKTELSE AV TJENESTEN, VIRUS ELLER ANNEN TEKNOLOGISK SKADELIG PROGRAMVARE SOM ER ERHVERVET GJENNOM TJENESTEN, ELLER VED NEDLASTING AV MATERIALE SOM ER POSTET PÅ DET, ELLER EVENTUELLE NETTSTEDER, SOM ER RELATERT TIL Å KAN INFISE ELLER SKADE DATAMASKINUTSTYRET DITT, DATAMASKINPROGRAMVAREN, DATA. </p>
<p> DU BRUKER TJENESTEN, INNHOLDET DITT OG EVENTUELLE TJENESTER ELLER ELEMENTER SOM ER ERHVERVET GJENNOM TJENESTENE PÅ EGEN RISIKO. TJENESTEN, INNHOLDET OG EVENTUELLE TJENESTER ELLER ELEMENTER SOM ER ERHVERVET GJENNOM NETTSTEDET OG UTVIDELSEN, LEVERT PÅ “SOM DEN ER” OG “SOM TILGJENGELIG” VILKÅR OG BETINGELSER, UTEN NOEN GARANTI. ENHVER PERSON TILKNYTTET TJENESTEN GIR INGEN GARANTI ELLER REPRESENTASJON MED HENSYN TIL FULLSTENDIGHET, SIKKERHET, PÅLITELIGHET, KVALITET, NØYAKTIGHET ELLER TILGJENGELIGHET AV TJENESTEN. UTEN BEGRENSNING OVER, GIR VERKEN “CURSOR STYLE” ELLER RELATERTE REPRESENTANTER TIL “CURSOR STYLE” GARANTI FOR AT NETTSTEDET, UTVIDELSEN, INNHOLDET ELLER EVENTUELLE REPARASJONER SKAL VÆRE TIDLIGERE TILGJENGELIGE, FASTSLÅTT AT VÅR UTVIDELSE, ET STED ELLER EN SERVER SOM PLASSERER DET, VIL VÆRE UTEN VIRUS ELLER ANDRE SKADELIGE KOMPONENTER ELLER DETTE NETTSTEDET ELLER EVENTUELLE TJENESTER ELLER ELEMENTER SOM UTFØRES, PREFERERT.
<p> UNDER INGEN OMSTENDIGHETER SKAL TJENESTEN, TILKNYTTEDE SELSKAPER ELLER LISENSGIVERE, TJENESTER, ANSATTE, AGENTER, TJENESTEMENNET, ELLER DIREKTØRER VÆRE ANSVARLIG FOR SKADER AV NOEN KATEGORI, VI SERVISE FOR ENHVER ERSTATNING. ELLER SÅDANNETE ANDRE NETTSTEDER ELLER EVENTUELLE TJENESTER ELLER ELEMENTER SOM ER ERHVERVET I TJENESTEN ELLER TIL ANDRE NETTSTEDER, INKLUDERT EVENTUELLE DIREKTE, SPESIELLE ELLER FØLGESKADER, INKLUDERT PERSONLIG SKADE, EMOSJONELLE FORSTYRRELSER, SKADER ELLER FORVENTET SPARING, TAP AV BRUK, DATA ELLER ANDRE BETINGELSER. DEFINISJON PÅVIRKER IKKE NOEN ANSVARLIGHET SOM IKKE KUNNE UTELUKKES ELLER BEGRENSES I HENHOLD TIL GJELDENDE LOVER SOM KAN OMFATTE SVINDEL. </p>
<p> Du samtykker i å beskytte, erstatte og avskjære “Cursor Style”, dets tilknyttede selskaper, lisensgivere og tjenesteleverandører, samt dets og deres respektive tjenestemenn, direktører, ansatte, entreprenører, agenter, lisensgivere, leverandører, tildelinger og fra krav og forpliktelser, tap av rettsavgjørelser, kostnader, utgifter eller provisjoner (inkludert advokatsalærer) som følge av eller i forbindelse med ditt brudd på disse bruksvilkårene eller bruk av tjenesten, inkludert, men ikke begrenset til, anger av enhver bruk av innholdet, tjenester og produkter på nettstedet eller utvidelsen, bortsett fra det som uttrykkelig er angitt i disse bruksvilkårene, eller din bruk av informasjon mottatt fra tjenesten. </p>
<p> Hvis en bestemmelse i disse bruksvilkårene blir funnet ugyldig, ulovlig eller ikke kan håndheves av en domstol eller annen domstol med kompetent jurisdiksjon av en eller annen grunn, bør en slik bestemmelse oppheves eller begrenses til et minimum, slik at resten av bestemmelsene i bruksvilkårene vil fortsette til det fulle. Bruksvilkårene, våre retningslinjer for personvern og vilkårene for registrering av hendelser utgjør hele og fullstendige avtalen mellom deg og “Cursor Style” angående tjenesten og erstatter alle tidligere og samtidige avtaler, avtaler, representasjoner og garantier, både skriftlige og muntlige, angående tjenesten . </p>
<p> Alle anmeldelser, kommentarer, forespørsler om teknisk støtte og andre meldinger angående tjenesten bør rettes til “Cursor Style” støtteside i Chrome Web Store. </p> ',
];
