<?php

return [
    'halo_descr' => 'Halo ir kaujas fantāzijas mediju franšīze, ko izveidoja Bungie. Balstīta uz sākotnējo pirmās personas šāvēja videospēļu triloģiju. Sižets risinās ap notikumiem, kas norisinās Master Chief dzīvē, kas ir viens no supersolātu grupas ar kodēto nosaukumu Spartieši, un viņa pavadonis, mākslīgais intelekts Cortana. Spēļu panākumi ir noveduši pie franšīzes paplašināšanās citos medijos: Halo visums pašlaik aptver daudzas grāmatas, grafiskos romānus, komiksus, īsfilmas, animācijas un pilnmetrāžas filmas.',
    'halo_short_descr' => 'Pieskarieties artefakta kursoram, varbūt jūs esat izredzētais',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'LOL Surprise lelles iemīlēja bērnus un iekaroja viņu sirdis no pirmajām minūtēm. Un tas nav pārsteidzoši, jo šāda panākuma pamatā ir noslēpumainība, brīnuma gaidīšana, patīkams pārsteigums, kas iepriecina ne tikai bērnus, bet arī viņu vecākus. Dāvanas noslēpums bērnam tiek atklāts tikai pēc pēdējās izpakošanas. Jebkurā gadījumā, LOL lelles ir pievilcīgs dizains, intriga, liels skaits pārsteidzošu un reālistisku aksesuāru un patīkamas sīkumus, kā arī rotaļlietas augstākā kvalitāte un detaļu izstrāde.',
    'lol_surprise_short_descr' => 'Forši mīluļi skaistu pārsteigumu cienītājiem',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Seriāls risinās ap konkursu, kurā 456 spēlētāji, kuriem visiem ir lieli finansiāli parādi, riskē savu dzīvību, lai spēlētu virkni nāvējošu bērnu spēļu, lai iegūtu iespēju laimēt miljardu balvu. Iekšā gaida kārdinoša balva ar nāvējoši augstām likmēm. Seriāla nosaukums ir atvasināts no līdzīga nosaukuma korejiešu bērnu spēles. Hvangs ideju bija iecerējis, pamatojoties uz savām ekonomiskajām grūtībām dzīves sākumā, kā arī uz klašu nevienlīdzību Dienvidkorejā un kapitālismu.',
    'squid_game_short_descr' => 'Izvēlieties pareizo spēlētāja seju, kad dodaties uz visu banku',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harijs Džeimss Poters ir galvenais varonis romānu sērijā, ko sarakstījis angļu rakstnieks Dž.K. Roulinga. Savā vienpadsmitajā dzimšanas dienā Harijs uzzina, ka ir burvis un ir paredzēts vietai Cūkkārpas burvju skolā, kur viņš praktizēs buršanu galvenā skolas direktora Albusa Dumidora un citu skolas profesoru vadībā. Harijs arī atklāj, ka viņš jau ir pazīstams visā romāna maģiskajā sabiedrībā un ka viņa liktenis ir saistīts ar Voldemorta, bīstama tumšā burvja, likteni.',
    'harry_potter_short_descr' => 'Ko jūs darīsiet ar burvju nūjiņu no Harija Potera kursoru kolekcijas?',
    'harry_potter' => 'Harijs Poters',
    'marvel_comics_descr' => 'Marvel Comics ir komiksu izdevniecība, kas pazīstama ar tādu ievērojamu supervaroņu kā Spider-Man, Iron Man, Captain America, Hulk, Thor, the Avengers, the Guardians of the Galaxy, the X-Men, the Fantastic Four un Deadpool radīšanu. Marvel pazīstamākie ļaundari ir Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom un Magneto. Marvel Comics un DC Comics ir sadarbojušies vairākos kopīgos projektos un arī kopīgi dibinājuši tīši īslaicīgo Amalgam Comics zīmolu.',
    'marvel_comics_short_descr' => 'Supervaronis mīt katrā no mums - izvēlies savu',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Laipni lūdzam atpakaļ Cookie Kingdom spēlē Cookie Run: Kingdom no Devsisters, burvīgā stratēģijas RPG spēlē, kas norisinās Cookie Run visumā. Tagad, kad GingerBrave ir izbēdzis no ļaunās raganas krāsns, ir pienācis laiks viņam izveidot Cookie komandu un uzsākt ceļojumu, lai atjaunotu kritušo Cookie Kingdom. Atklājiet patiesību aiz Karalistes krišanas un izveidojiet komandu ar spēcīgākajiem Karalistes Cookie, lai sakautu tumšos spēkus, kas vēlas apturēt GingerBrave no viņa likteņa piepildīšanas.',
    'cookie_run_kingdom_short_descr' => 'Mazi cīnītāji tieši no krāsns',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact ir atvērtas pasaules piedzīvojumu spēle. Tas nozīmē, ka jauna, brīnišķīga ainava jūs gaida otrā upes vai kalna pusē, jums tikai jāizmanto sava enerģija gudri. Ja jūs sastopat klejojošu feju vai dīvainu mehānismu, uzdrošinieties un mēģiniet atrisināt to noslēpumu. Bet ko tie sola - nepatikšanas vai patīkamu pārsteigumu - tikai jūs varat uzzināt! Plašajā Teyvata kontinentā jūs apmeklēsiet septiņas valstības, atradīsiet pavadoņus ar dažādām prasmēm un cīnīsieties pret spēcīgiem ienaidniekiem, meklējot pazudušo mīļoto.',
    'genshin_impact_short_descr' => 'Kļūsti par Septiņu valstību elementāro pavēlnieku',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Kad piepildās sena pareģojums un karaļvalsts iegrimst ziemas apskāvienos, trīs bezbailīgi varoņi - princese Anna, drosmīgais Kristofs un viņa uzticamais ziemeļbriedis Svens - dodas kalnos, lai atrastu Annas māsu Elzu, kura var noņemt atvēsinošo burvestību no valsts. Ceļā viņus gaida daudzi sarežģīti pārsteigumi un aizraujoši piedzīvojumi. Tikšanās ar mistiskiem troļļiem, tikšanās ar burvīgu sniegavīru vārdā Olafs, Everesam stāvākas kalnu virsotnes un daudz maģijas. Varoņiem jāpretojas varenajiem elementiem, lai glābtu karalisti un tos, kas viņiem ir dārgi.',
    'frozen_short_descr' => 'Ledus laušana ir vienkārša ar Frozen kursoru kolekciju',
    'frozen' => 'Frozen',
    'stranger_things_descr' => 'Ir pagājuši nedaudz vairāk kā seši mēneši kopš trešās sezonas fināla. Džoisa, Vils, Elvena un Džonatans ir pārcēlušies uz Kaliforniju, kur meitene tiek apcelta skolā. Pārējie sāk cīņu ar jaunu monstru no paralēlās pasaules, kas parādījusies Hokinā. Viņu nosauca Vēkna par Dungeon & Dragons galda spēles varoni. Tas ietekmē pusaudžus psiholoģiski, pēc tam garīgi iekļūst galvā un nogalina. Paralēli Džoisa un Mērijs uzzina, ka Džims Gopers ir dzīvs, un dodas viņam pakaļ uz padomju cietumu Kamčatkā. Un Elvenai būs jāatgriežas un jāpalielina savas spējas, bet arī jāuzzina sava svarīgā loma, radot to pašu monstru Gokinā.

Scenāristi nemainīja sižeta taktiku, kas viņiem patika pēdējās pāris sezonās. Ceturtajā sezonā viņi lielo galveno varoņu grupu sadalīja grupās, izdomāja sarežģītus uzdevumus viņiem un beigās uzbūvēja savus stāstus kopā pārsteidzošā noslēgumā. Mēs piedāvājam jums sīki izprast visus šos piedzīvojumus ar Stranger Things kursoru kolekcijas palīdzību.',
    'stranger_things_short_descr' => 'Kas notiks tālāk? - Stranger Things 4 kursoru modeļi',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars ir oriģināls spēles režīms, kas pirmo reizi parādījās Minecraft. Spēlētāju uzdevums bija aizsargāt savu bāzi un gultu.

Roblox katru dienu piedāvā aizraujošākas spēles, un BedWars nav izņēmums. Lieta tāda, ja jums patīk Bed Wars un jūs aizstāvat sevi savā istabā, šis ir nosaukums jums, jo tas jūs aizvedīs atpakaļ bērnībā, lai gan šoreiz digitāli.

Viss, kas jums jādara, ir aizsargāt savu gultu no uzbrucējiem kopā ar savu partneri. Jūs ieejat vestibilā, izvēlaties, ar ko spēlēt, un voilā, tas ir tikai aizsardzības jautājums.

Protams, kad runa ir par aizsardzību, jums būs dažas problēmas, un ir daži resursi, priekšmeti un lietas, kas palīdzēs jums uzvarēt. Piemēram, ekskluzīvas ādas, kuras jūs atradīsiet Bed Wars kursoru kolekcijā.',
    'roblox_bed_wars_short_descr' => 'Aizsargājiet savu gultu ar Roblox Bed Wars kursoru.',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'Naruto Uzumaki dzimšanas dienā leģendārs dēmons, Deviņastes Lapsa, uzbruka ciemam, ko sauca Konoha. Ceturtais Hokage par savu dzīvību izglāba ciemu, ieslēdzot dēmonu jaundzimušajā Naruto, nezinot, ka tas viņu nolemj naidam no saviem ciemata biedriem.
Neskatoties uz talantu trūkumu daudzās ninjutsu jomās, nemierīgumu un augstprātību, Naruto sapņo kļūt par Hokage, spēcīgāko nindzju ciemā. Vēloties atpazīstamību, ko viņš nesaņēma, viņš smagi strādā un trenējas kopā ar saviem komandas biedriem Sasuke Uchiha un Sakura Haruno, kā arī savu mentoru Kakashi Hatake. Viņam un viņa partneriem būs jāiziet daudz cauri ceļā uz saviem lolotajiem sapņiem: cīņas, mīlestība, draudzība, nodevība, varas slāpes. Naruto anime kursoru kolekcija palīdzēs tev navigēt savu ceļu!',
    'naruto_anime_short_descr' => 'Staigā savu nindzjas ceļu ar Naruto anime kursoru.',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'Darbība norisinās Taišo ēras laikā. Kopš seniem laikiem ir baumas, ka mežā dzīvo humanoīdi dēmoni, kas barojas ar cilvēkiem un staigā naktīs, meklējot jaunu upuri. Bet... tā ir tikai leģenda, vai ne?..

Tanjiro Kamado ir vecākais dēls ģimenē, kurš zaudēja savu tēvu un rūpējās par savu ģimeni. Kādu dienu viņš dodas uz tuvējo pilsētu, lai pārdotu kokogles. Atgriežoties no rīta, puisis atklāj briesmīgu ainu: visi radinieki tika brutāli nogalināti, un vienīgais izdzīvotājs ir Nezuko, jaunākā māsa, kas pārvērtusies par dēmonu, bet vēl nav zaudējusi visu savu cilvēcīgumu.

No šī brīža Tanjiro un Nezuko sāk garu un bīstamu ceļojumu, kurā puisis vēlas atrast slepkavu un atrast veidu, kā izārstēt savu māsu. Bet vai bērni spēj pārvarēt visas grūtības un atgriezties mājās? Jūs jau zināt atbildi, un, ja nē - labāk uzstādiet kursorus Demon Slayer ar varoņiem no vienas no populārākajām mangām.',
    'demon_slayer_anime_short_descr' => 'Demon Slayer kursori – īstiem nakts medniekiem.',
    'demon_slayer_anime' => 'Demon Slayer anime',
    'bts_descr' => 'BTS ir septiņu dalībnieku zēnu grupa zem BigHit Music. Viņi debitēja 2013. gada 13. jūnijā ar singlu "No More Dream". Japānā viņi debitēja 2014. gada 24. decembrī ar studijas albumu Wake Up.

Grupa nosaukums nāca no korejiešu izteiciena Bangtan Sonyeondan, kas nozīmē "bruņuša zēnu skauti". Pēc J Hope teiktā, nosaukums nozīmē grupas vēlmi bloķēt stereotipus, kritiku un cerības, kas ir vērstas uz pusaudžiem kā lodes.

Kursa rādītāju kolekcija, kas veltīta grupai, ietver visus grupas dalībniekus, šeit Kim Nam Joon kursora rādītājs (aka RM), Kim Seok Jin kursora rādītājs (Jin), Min Yoongi kursora rādītājs (Suga), Jung Ho Suk kursora rādītājs (J-Hope), Park Ji Min kursora rādītājs (Jimin), Kim Tae Hyun kursora rādītājs (V) un Jeon Jungkook kursora rādītājs (Jungkook).',
    'bts_short_descr' => 'Satiec savus elkus ar BTS kursoru izskatiem',
    'bts' => 'BTS',
    'miraculous_descr' => 'Brīnumainais: Ladybug un Cat Noir stāsti, labāk pazīstams kā Miraculous Ladybug un Cat Noir, ir supervaroņu piedzīvojumi no multfilmas par diviem klasesbiedriem, kuri zem maskām spēlē Parīzes aizstāvju lomu no ļaundara, kurš katrā sērijā izdomā jaunu veidu, kā kaitēt pilsētai. Miraculous ir veidots Francijā, izmantojot CGI un animāciju. Miraculous ir ne tikai animācijas seriāls, bet arī komiksu kolekcija, kas izdota visā pasaulē. Seriāls ir ļoti mīlēts jauno auditoriju.

Notikumi risinās Parīzē, kur Marineta un Adriāns ir vidusskolēni modernā skolā. Viņiem tika uzticēts kļūt par izredzētajiem cīņā pret ļaunumu, glābjot savu pilsētu. Viņu mērķis ir aizsargāt cilvēkus no Akumas. Šīs mazās būtnes tauriņu veidā spēj apdzīvot cilvēku un pārvērst viņu par ļaundari.

Marineta var pārvērsties par mārīti, un Adriāns - par Cat Noir, bet, kas ir pārsteidzoši, strādājot pāros, viņi neatpazīst viens otru zem supervaroņu maskām.

Palīdziet Cat Noir un Ladybug glābt Parīzi ar mūsu kursoru, kurā attēloti jūsu iecienītie varoņi. Kuru varoni izvēlēsieties kursoram? Vai tas būs Miraculous Ladybug kursors, vai varbūt Tikki burvīgā mazā mārīte vai Cat Noir kursors? Vai varbūt Queen Bee ar Rena Rouge kursoriem? Izvēle ir jūsu!',
    'miraculous_short_descr' => 'Pievienojieties supervaroņu rindām ar Lady Bug un Cat Noir kursoru kolekciju.',
    'miraculous' => 'Brīnumainā kārtā: Ladybug un Cat Noir stāsti',
    'talking_tom_descr' => 'Seriāls vēsta par runājošā Toma un viņa draugu ikdienu. Toms un viņa neveiklais biznesa partneris Bens pastāvīgi izstrādā mobilās lietotnes un citus izgudrojumus, lai sasniegtu slavu un bagātību un parādītu sevi pasaulei, taču tas vienmēr beidzas ar neveiksmi. Toma draudzene Andžela cenšas būt dziedātāja, neatkarīgi no tā, ko viņa dara, lai to sasniegtu. Toma kaimiņš Džindžers ļoti bieži iegriežas šeit, lai sarīkotu palaidnības ar velniem piedurknē. Stulbs labākais draugs un istabas biedrs Henks ir mājas sēdētājs, skatās ļOTI TV. Un bijusī disidente popzvaigzne Beka Spārkles ir kļuvusi par Andželas jauno istabas biedreni un, šķiet, ir iemīlējusies Henkā. Tomēr, lai cik slikti neietu visa veida un izmēra lietas, vai tā būtu ļaunā izpilddirektore, Toma noslēpumainais jaunais kaimiņš vai vienkārši negadījums Bena jaunajā radījumā, banda jautri pavadīs laiku neatkarīgi no tā, un vienmēr atcerēsies vienu lietu, kas viņus vieno: draudzība nekad nebeidzas, tāpat kā mūsu mīlestība pret seriāla varoņiem nebeidzas, tāpēc tagad vari iestatīt sev runājošā Toma kursoru vai Bena kursoru, vai varbūt Andželas kursoru, Olivera kursoru!',
    'talking_tom_short_descr' => 'Parunāsim par tavu iecienītāko tēlu kolekcijā Talking Tom Cursor Collection',
    'talking_tom' => 'Talking Tom un draugi',
    'lego_descr' => 'LEGO Group kompānija tika dibināta tālajā 1932. gadā, un toreiz tajā strādāja tikai 7 cilvēki. Lego komandas mērķis bija radīt rotaļlietas, kas attīsta bērna radošumu, iztēli un atjautību. Pārsteidzošs fakts, ka kopš tās rašanās 1949. gadā, LEGO elementi visās to variācijās ir palikuši savstarpēji saderīgi. Visi vēlāk radītie priekšmeti joprojām ir saderīgi ar priekšmetiem, kas tiek izlaisti šodien, neskatoties uz izmaiņām dizainā un formā gadu gaitā.

LEGO kluci ir pamatne, kas ir dobs plastmasas bloks, kas savienojas ar citiem līdzīgiem klučiem. Bet Lego komplekti satur arī citas detaļas, riteņus, figūras, platformas un pat elektroniskas shēmas ar sensoriem un elektriskiem motoriem. Jūs varat savākt automašīnu, lidmašīnu, vilcienu, kuģu, ēku, robotu modeļus. LEGO ievēro modularitātes ideju, kas skaidri demonstrē bērniem, kā atrisināt noteiktas problēmas, attīstīt iztēli, smalko roku motoriku un montāžas prasmes. LEGO kluči ir izgatavoti ar neticamu precizitāti un perfekti savietojami, nodrošinot satriecošu 10 mikronu precizitāti.

Nesen ir radīti daudzi populāri 3D animācijas Lego stāsti, kur komplektu varoņi atdzīvojas un kļūst par neticamu piedzīvojumu dalībniekiem. Ja vēlaties atdzist kursoru, mūsu Lego Kursoru kolekcijā atradīsiet daudz varoņu no Lego TV seriāliem un animācijas filmām. Lego Ninjago Kursoru, Lego Batman Kursoru, Lego Ninjago Kursoru, Lego Wayldstyle Kursoru un daudz ko citu.',
    'lego_short_descr' => 'Izveido savu sapņu pārlūku ar Lego kursoru kolekciju',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Pēc veiksmīgas Kickstarter finansēšanas, 2017. gadā, Team Cherry izlaida daudzplatformu PC spēli Hollow Knight. Šis ir stāsts par bezvārda bruņinieku un viņa atklājumiem Hallownest kukaiņu valstībā. Spēle pamatoti tika atzīta par vienu no labākajām metroidvania žanrā.

Hollow Knight spēle balstās uz spēles pasaules izpēti. Pārvarot šķēršļus, atrisinot mīklas un atklājot noslēpumus, kā arī cīņā ar ienaidniekiem. Spēlētājam ir unikāls uzlabojumu un triku komplekts pasaules izpētei un cīņai. Pārvietojoties no zonas uz zonu, spēlētājs uzvar bosus un iegūst nepieciešamos uzlabojumus, lai virzītos tālāk. Rezultātā spēlētājiem ir jāapmeklē jau izietās zonas, lai atrastu noslēpumus un izietu stāstu. Un tas ir aizraujoši arī tāpēc, ka zonas mainās katru reizi, atnesot jaunus pārsteigumus un pieredzi. Spēli var spēlēt dažādos veidos, jo starp zonām ir vairāki dažādi ceļi. Izejot cauri stāstam, jūs atverat zonas karti, bet vispirms jums ir jāiegūst karte.

Galvenais varoņa ierocis ir nagla, kas ir nedaudz līdzīga zobena veidam, ieročus var uzlabot ar kalēja palīdzību, kā arī iemācīties dažādas iemaņas, izmantojot ieročus, kas paplašina uzbrukumu daudzveidību. Uzbrūkot ienaidniekiem, jūs uzkrājat īpašu resursu, ko vēlāk var izmantot uzlabojumiem vai dziedināšanai.
Izklaidējieties, spēlējot Hollow Knight, un neaizmirstiet par mūsu Hollow Knight kursoru ar savu iecienīto varoni. Mūsu kolekcijā ietilpst Mister Mushroom kursors, Quirrel kursors, Hornet Needle kursors, Old Nail kursors, Myla kursors un citi.',
    'hollow-knight_short_descr' => 'Centieties nepazust kukaiņu valstībā, izmantojot Hollow Knight kursoru kolekciju',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henrijs Stikmens ir galvenais varonis seriālā. Stikmins, iepriekš nenosaukts, sāka kā neliels zaglis, kam bija vēlme ātri nopelnīt vieglu naudu. Tomēr pēc izbēgšanas no Rietumu Mesas cietuma viņa dzīvē notiek daudz pārmaiņu, un viņš kļūst par slavenu noziedznieku pēc Tunisijas dimanta zādzības. Henrijam ir izvēle - kļūt par veiksmīgu valdības aģentu, mednieku par galvām, noziedzīgas organizācijas vadītāju, kiborgu vai turpināt noziedzīgo ceļu vienam. Spēle iepriecina žanra fanus ar daudziem piedzīvojumiem un noslēpumiem, un jūs atradīsiet mūsu jauno kolekciju ar Henrijam Stikmenam paredzētiem kursoros ar tā smieklīgajiem varoņiem, ieskaitot Henrijam Stikmens kursoru, Čārlza Kalvina kursoru, Redžinalda Koperbotoma kursoru, Labās Rokas kursoru, Elijas Rouzas kursoru un citus!',
    'henry-stickmin_short_descr' => 'Ieplānojiet savu bēgšanu no garlaicības ar Henrija Stikmena Kursoru kolekciju',
    'henry-stickmin' => 'Harijs Stikmens',
    'adopt-me_descr' => 'Ļoti populārā tiešsaistes spēle Adopt Me tika palaista 2017. gadā un kļuva par populārāko Roblox spēļu platformā. Spēles būtība ir ļoti vienkārša - iegūt olas ar mājdzīvniekiem un rūpēties par tiem.

Virtuālie mājdzīvnieki ir sadalīti 5 klasēs, daži no tiem ir ļoti reti un dārgi, savukārt citus ir ļoti viegli iegūt. Tās ir neparastas grupas, piemēram, Zilais suns, Common, Rare kursors, piemēram, Adopt Me Monkey peles kursors, kā arī īpaši reti, piemēram, Koala kursors un Legendary, Dragon kursors un Accept me unicorn. Ja spēlētājam ir četri pieauguši viena veida mājdzīvnieki, viņi var apvienoties neona mājdzīvniekā, piemēram, Neon Horse spēles kursors vai Adopt Me Neon Starfish. Apvienojot četrus parastos mājdzīvniekus, jūs varat izveidot neona mājdzīvnieku, kas patiešām spīd, un no neona mājdzīvniekiem varat izveidot mega-neona mājdzīvnieku.

Iepirkšanās spēlē Adopt Me! tiek veikti ar virtuālo valūtu Roblox - tā saukto Robux, un spēlei ir arī sava valūta - Bucks. Rūpējoties par savu mājdzīvnieku, papildus izklaidei, varat nopelnīt bucks, vienkārši pabarojiet viņu, ielieciet viņu gulēt vai palasiet pasaku, vispār daudz interesantu lietu.

Tagad Roblox spēles "Adopt Me!" fani var izrotāt savu spēles kursoru ar iecienītāko mājdzīvnieku!',
    'adopt-me_short_descr' => 'Izklaidējieties ar jaukiem mājdzīvniekiem mūsu Adopt Me! spēles kursoru kolekcijā',
    'adopt-me' => 'Adopt me!',
    'among-us_descr' => 'Among Us pamatā ir slavenā lomu spēle "Mafia". Bija plānots, ka spēle būs ekskluzīva mobilajām ierīcēm, jo tajā bija tikai viena karte. Spēle ātri kļuva populāra. Vēlāk izstrādes komanda pievienoja daudzspēlētāju režīmu, un 2019. gadā tika izlaistas divas papildu kartes.
Among Us ir augšupvērsta trešās personas spēle, kas ļauj spēlētājam pārvietoties visos virzienos. Vienā kārtā var spēlēt no četriem līdz desmit spēlētājiem. Spēles sākumā visiem slepeni tiek piešķirta nodevēja vai apkalpes locekļa loma. Krāpnieks (krievu tulkojumā "nodevējs") var paslēpties ventilācijas lūkā, sabotēt un nogalināt apkalpes locekļus. Tā mērķis ir iznīcināt visus apkalpes locekļus vai pilnībā iznīcināt kosmosa kuģi, veicot sabotažu. Kuģa apkalpes mērķis ir atrisināt dažādas mīklas, kas viņiem sagatavotas spēles sākumā. Ja katrs apkalpes loceklis izpilda visus uzdevumus, nodevēji zaudēs. Tāpat kuģa apkalpe var gūt uzvaru, balsošanas laikā likvidējot nodevējus.
Nodevēji laiku pa laikam var veikt sabrukumus un, ja bojājumi netiek novērsti 30 sekunžu laikā, apkalpe zaudēs. Pirms spēles sākšanas varat izvēlēties spēlējamā varoņa krāsu — zilu, sarkanu, dzeltenu, pelēku — jebkuru! Un neaizmirstiet sev iestatīt atbilstošu kursoru no jaunās Among Us kolekcijas!',
    'among-us_short_descr' => 'Neļaujiet sevi apmānīt šajā sarežģītajā kosmosa spēlē ar Among Us kursoru.',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Filmas "Stīvena Visuma" veidotāja ir Rebeka Šugara. Viņa ir pazīstama ar savu iepriekšējo darbu, ko sauc par Piedzīvojumu Laiku. Pirmā Stīvena Visuma sērija tika izlaista YouTube video platformā 2013. gada pavasarī. Bet rudenī Amerikas kanāls Cartoon Network sāka to translēt saviem skatītājiem. Kopš tā laika ir izlaistas 6 sezonas. Sestā sola būt pēdējā.
Kas attiecas uz animācijas seriāla sižetu, tas risinās ap Kristāla dārgakmeņu komandu. To veido citplanētiešu būtnes ar raksturīgiem vārdiem: Pērles, Ametists un Granāts. Bet ir vēl viens dalībnieks, kura lomā darbojas parasts zēns Stīvens. Kopā viņi meklē monstrus un cenšas tos neitralizēt, lai tie neieņemtu Zemi personīgā labuma dēļ. Viņiem pretojas Džespers un Peridots - vēstneši no savas planētas, kuri vēlas uzvarēt Dārgakmeņus un ieslēgt Klasteru.
Ja esat Stīvena Visuma fans un vēlaties redzēt animācijas seriāla varoņus visur, kur vien varat, instalējiet Cursor Style paplašinājumu! Kāpēc to darīt? Jūs varat pievienot kolekciju, kas veltīta "Stīvena Visumam", un pārvērst standarta peles rādītāju par vienu no jūsu iecienītākajiem varoņiem.',
    'steven_universe_short_descr' => 'Atklājiet dārgakmeņu noslēpumus ar Steven Universe kursoru',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Animācijas seriāls ar nosaukumu "Family Guy" visas savas pastāvēšanas vēsturē 4 reizes ir ieguvis Emmy balvu un 3 reizes "Annie". Animācijas seriāls izsmej Amerikas sabiedrības sāpīgās tēmas, piemēram, feminismu, verdzību, aptaukošanos, politiku utt. Atšķirībā no citiem darbiem, šeit tiek izmantoti ielaidumi ar jokiem un sarkasmu. Turklāt daudzos gadījumos tie nav integrēti sižetā, bet eksistē paši par sevi.
Viena animācijas seriāla sērija tiek izveidota vairāk nekā 10 mēnešus. Kāpēc tik ilgi? Tāpēc, ka visa animācija tiek zīmēta ar roku. Tāpēc daži no notikumiem, ko atspoguļo darbs, paspēj zaudēt aktualitāti. Bet pat tā seriāls joprojām ir ļoti interesants un iegūst skatītāju labvēlību visā pasaulē. Galu galā, kuram gan nepatīk labi pasmieties par politiķiem, slavenībām vai cilvēkiem, kuri izdara savvaļas blēņas un tādējādi pārsteidz vai pat šokē parastos cilvēkus.
Tev patīk "Family Guy"? Jums ir unikāla iespēja pārvērst parasto peles kursoru par jebkuru no šī animācijas seriāla varoņiem! Kas man ir jādara? Vienkārši instalējiet pārlūka paplašinājumu “Cursor Style”, pievienojiet tam kolekciju, kas veltīta “Family Guy”, un izbaudiet pasakainu reinkarnāciju!',
    'family_guy_short_descr' => 'Family Guy kursoru kolekcija īpaša humora cienītājiem',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Jūs noteikti esat dzirdējuši izteicienu "Skaistums izglābs pasauli"? Tātad, daudzi cilvēki, īpaši meitenes, piekrīt šim apgalvojumam. Tāpēc viņi cenšas sevi apņemt ar visu skaistāko un acij tīkamāko. Tā var būt rozā fona tapetes guļamistabā, mīkstās rotaļlietas, spilveni, kas izšūti ar krellēm, dārgas rotaslietas utt. No malas tas viss izskatās ļoti mīļi un pat nedaudz bērnišķīgi. Bet katrs no mums savā sirdī ir mazs bērns, tāpēc kāpēc gan ļaut viņam parādīt mūsu iztēli?
Maigumu mūsos var izraisīt daudz kas. Piemēram, žēlsirdīgās kaķēna acis, kurš vēlas, lai viņu samīļotu vai pabarotu. Daudzkrāsu varavīksne, kas parādās pēc pavasara lietus un mirdz ar visām krāsām saulē. Bērns, kuram iedeva šokolādi, un viņš nolēma to dalīt ar savu draudzeni vai puisi. Ir diezgan daudz iemeslu pieskarties, un mēs nolēmām tos izmantot kā kursorus.
Vai esat noguris no garlaicīgās baltās bultiņas savā pārlūkprogrammā? Aizstājiet to ar kaut ko jautru no mūsu kolekcijas! Piemēram, rozā un balts vienradzis, bēdīgs tomāts, drūms mākonis, dzeloņains kaktuss kaķa formā vai jebkas cits, ko vēlaties. Viss, kas jums jādara, ir instalēt paplašinājumu Cursor Style un pievienot tam mīlīgu kursoru kolekciju. Un lai dzīvo pasaules glābējs - skaistums!',
    'cute_cursors_short_descr' => 'Pasaule kļūs laipnāka ar jauku kursoru kolekciju',
    'cute_cursors' => 'Jauki kursori',
    'web_media_descr' => 'Mūsdienu realitātē gandrīz visi izmanto internetu. Sākot no maziem bērniem un beidzot ar pensionāriem. Kāds pārlūko, izmantojot pārlūku, cits skatās video pakalpojumā YouTube, un kādam ir nepieciešams tīkls saziņai ar mīļiem cilvēkiem. Neviens no šiem lietotājiem nevar iedomāties dienu bez Pasaules tīmekļa.
Vecāka gadagājuma cilvēki bieži sēž sociālajā tīklā, piemēram, Facebook vai VK. Viņi bieži arī sazinās ar saviem bērniem un mazbērniem, izmantojot Skype. Tas ir īpaši ērti, ja bērni un vecāki dzīvo dažādās pilsētās vai pat valstīs.
Jaunieši labprātāk sazinās, izmantojot Viber vai Telegram, augšupielādē fotoattēlus pakalpojumā Instagram, smejas par FB mēmiem. YouTube video ar cilvēku reakcijām gūst miljoniem skatījumu, tāpat kā dažādi palaidnības vai sociālie eksperimenti. Pakalpojumā Tik-Tok simtiem tūkstošu cilvēku dejo, rāda maģijas trikus un izsaka sevi.
Vai jūs interesē vai bieži lietojat kāda veida resursu no tīmekļa mediju sfēras? Vai vēlaties atbrīvoties no garlaicīgās peles bultiņas savā pārlūkā? Tad instalējiet paplašinājumu un mainiet noklusējuma kursoru uz mūsu radošo! Tas var būt YouTube kursors, Viber kursors, Google Chrome kursors vai citi resursi.',
    'web_media_short_descr' => 'Dzīvo modernā ritmā ar web mediju kursoru kolekciju',
    'web_media' => 'Web Mediji',
    'bobs_burgers_descr' => 'Animācijas seriāls “Bobs Burgers” ir animācijas darba sižets un varoņu harizma. Un, spriežot pēc nominācijas Emmy balvai un darba atzīšanas par vienu no labākajām karikatūrām visā pasaulē, Bobs Snack patiešām radīja sajūsmu.
Animācijas seriāla sižets risinās ap Boba Belčera ģimeni. Šī persona ir ēstūža īpašnieks pirmajā stāvā, un otrajā viņš dzīvo kopā ar saviem mīļajiem. Bobam ir jautra sieva Linda un 3 bērni: Džīns, Luīze un Tīna. Zēns sapņo par muzikālo karjeru, vecākā meita Tīna ir ļoti laipna, bet neveikla, un jaunākā - Luīze joprojām ir mīlule un bieži ievieto savu ģimeni neērtā situācijā. Galvenais konkurents Boba Burgers ir Džimija Pesto picērija. Kā jūs varētu uzminēt, šīs picērijas īpašnieku sauc Džims, un viņš un Bobs viens otru ienīst. Tas viss tika atspoguļots tā, lai izskatītos komiski, nevis nopietni. Tāpēc daudzas no viņu sadursmēm izraisa tikai smaidu.
Ja jums patīk animācijas seriāls “Boba Burgers” un vēlaties redzēt viņa varoņus ne tikai monitora ekrānā vai televizorā, instalējiet paplašinājumu, pievienojiet kolekciju un mainiet peles kursoru pārlūkprogrammā uz jebkuru no šīs karikatūras varoņiem!',
    'bobs_burgers_short_descr' => 'Bobs gatavo burgerus, un mēs veidojam Boba burgeru kursorus',
    'bobs_burgers' => 'Boba burgeri',
    'kirby_descr' => 'Video spēles "Kirby" vēsture sākās jau pagājušā gadsimta 90. gados. Tā sastāv no daudzām sērijām, kuras izstrādāja Nintendo un HAL Laboratory. Spēle ir paredzēta bērniem no pusotra līdz 8 gadiem. Par tās popularitāti var spriest pēc pārdoto eksemplāru skaita. Vairāk nekā 34 miljoni visā pasaulē.
Galvenais varonis Kirby ir tāda paša nosaukuma rozā būtne. Tā dzīvo uz planētas, ko sauc Pop Star, un periodiski to aizsargā no dažādām briesmām. Kerbijs var ieelpot dažus objektus un savus ienaidniekus, lai pēc tam iemācītos viņu spējas: cīņa ar rokām, zoba valdīšana, uguns elpošana utt. Tomēr rozā pūšļa ne tikai cīnās ar ienaidniekiem, bet arī atrisina dažādas mīklas, ceļo uz citām valstīm un pat var lidot līmenī.
Tā varat spēlēt šo videospēli uz Nintendo vai Game Boy konsolēm. Visās sērijās ir jauki varoņi, laba grafika un smieklīgi skaņu celiņi. Starp citu, gandrīz 30 gadu laikā kopš pirmās versijas izlaišanas pasaule paspēja ieraudzīt 20 Kirby sērijas. Šis rādītājs kopā ar daudzmiljonu eksemplāru apjomu palīdzēja spēlei iekļūt 50 veiksmīgāko un pieprasītāko videospēļu TOP spēļu industrijā.
Vai mīliet Kirby tik ļoti, ka vēlaties redzēt šo varoni, kur vien iespējams? Tad izmantojiet Kirby kolekciju un pārvērtiet parasto peles rādītāju par jūsu iecienītākās videospēles galveno varoni! Mēs esam pārliecināti, ka jums patiks jaunais kursora izskats.',
    'kirby_short_descr' => 'Mēģiniet ieelpot visu Kirby kursoru kolekciju',
    'kirby' => 'Kirbijs',
    'undertale_descr' => 'Senos laikos uz Zemes dzīvoja ne tikai cilvēki, bet arī monstri. Nesaskaņu dēļ starp viņiem izcēlās karš, kas beidzās cilvēku rases labā. Septiņi magi ieslodzīja monstrus pazemē un tur uz visiem laikiem ieslodzīja tos ar barjeras burvestību. Tomēr bija tikai viens ieeja Mount Ebott, ko izmantoja bērns. Tieši par viņu jūs spēlēsiet, palaižot datorspēli Undertale.
Šo spēli izstrādāja Toby Fox - labi pazīstams programmētājs no ASV. Sākotnēji ar to varēja baudīt personālo datoru īpašnieki, kuri darbojas ar Microsoft Windows un Linux OS, un tad pienāca spēļu konsoles lietotāju kārta.
Kāda ir šīs spēles jēga? Zēns ceļo pa pazemes pasauli, kurā dzīvo monstri. Daži no viņiem ir uzreiz naidīgi, bet citiem patīk sarunāties. Spēlētājs var izvēlēties vienu no 2 uzvedībām: izvairīties no vardarbības vai cīnīties. Pirmajā gadījumā spēles iziešana būs vieglāka, otrajā - gluži pretēji, grūtāka. No šīs izvēles ir atkarīgs arī sižets un beigas, kas var atzaroties un mainīties.
Ja jums patīk Underground Tale un vēlaties redzēt tās varoņus savā pārlūkprogrammā, instalējiet paplašinājumu un pievienojiet atbilstošo kursoru kolekciju! Pārvērtiet garlaicīgo peles rādītāju par vienu no monstriem vai Undertale galveno varoni!',
    'undertale_short_descr' => 'Ir pienācis laiks tikt ārā no bedres, izmantojot Undertale kursorus',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune ir lomu spēle, kas tika izlaista datoriem pirms pāris gadiem. To izstrādāja tas pats programmētājs, kurš izstrādāja Undertale. Tomēr šīs divas spēles gandrīz neatšķiras viena no otras, lai gan tām ir daži kopīgi varoņi un vietas.
Deltarune ir vairāki galvenie varoņi. Šis ir skolēns Kriss, kuru var kontrolēt, un burvīgs briesmonis Sūzija, nekontrolējama. Abi varoņi iekrīt tumsas pasaulē, kur viņi satiek vienu no tās iemītniekiem - Ralsaju. Viņš viņiem stāsta, ka patiesībā viņi ir gaismas radības, kurām ir misija - apturēt tumšās enerģijas plūsmu drūmajā pasaulē. Lai to izdarītu, viņiem ir jātaupa vietējie briesmoņi un jācenšas neiesaistīties cīņā ar viņiem, lai gan tas dažreiz ir diezgan grūti izdarāms.
Spēlētājam ir vienkārša izvēle: vai nu taupīt tumšās radības, vai uzbrukt tām. Tā kā Sūzija nav puse pasākumu fane, daudzos gadījumos viņa izvēlas cīņu. Tāpēc Krisam nav citas izvēles, kā atbalstīt savu draudzeni un palīdzēt viņai cīņās.
Vai mīli spēli Deltarune? Tad stilizē savu peles kursoru pārlūkā kādu no viņas varoņiem! Jūs to varat izdarīt ar mūsu paplašinājumu. Instalējiet to, pievienojiet “Rune Delta” kolekciju un aktivizējiet! Tagad jūsu bultiņa ir pārstājusi būt tāda pati kā visiem pārējiem un ir kļuvusi par Krisu, Sūziju vai kādu no tumšās pasaules radībām.',
    'deltarune_short_descr' => 'Ienirstiet tumšajā pasaulē ar šo kursoru kolekciju',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario ir datoru spēļu sērija, ko izdevis Nintendo. Pirmā un populārākā spēle saucās Super Mario Bros. Tā ieraudzīja gaismu 1985. gadā. Vēlāk tā tika iekļauta Ginesa rekordu grāmatā. Kopš tā laika ir izlaistas vairāk nekā 20 spēles, un katrai no tām ir savs sižets. 2019. gadā parādījās jauna versija ar nosaukumu Super Mario Maker 2. Neskatoties uz grafikas uzlabojumiem, stils un varoņi palika tie paši, un tas izraisa nostaļģiju pēc 80. gadu Super Mario.
Galvenais varonis joprojām ir santehniķis Mario. Pēdējās spēles variācijas sižetā Princeses pilsēta neatstāja ne akmeni uz akmens. Mario ir jāatjauno tā, nopelnot pirms tam monētas, kas viņam tiek maksātas par uzdevumiem. Kopumā šai spēlei ir vairāk nekā 100 dažādas sarežģītības pakāpes ar iespēju modificēt. Arī spēlē Super Mario Maker 2 ir jauni spēles režīmi. Jūs varat spēlēt četrus no tiem vienlaikus, un, tiklīdz viens beidzas, līmenis tiek uzskatīts par pabeigtu. Ir arī tādi režīmi kā: Mario Maratons, Duelis un Ninjik sacensības.
Dieviniet Super Mario un visu, kas saistīts ar šo brīnišķīgo spēli? Tad iestatiet kursorus, kas izgatavoti šī platformera stilā! Mēs esam pārliecināti, ka jums patiks Mario kursors, Luidži kursors, Princeses Pīčas kursors un citi kursi, kas tiek piedāvāti mūsu kolekcijā!',
    'super_mario_short_descr' => 'Izpētiet sēņu valstību ar Super Mario kursoru kolekciju',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls ir radīts sadarbībā starp Disney Television Animation Corporation un Aleksu Hiršu. Pirmizrāde notika 2012. gadā un tika rādīta kanālā Disney Channel. Tur tika demonstrēta visa pirmā animācijas seriāla sezona. Divus gadus vēlāk tika izlaista otrā sezona, kuru skatītāji varēja vērot iepriekšējā kanālā un Disney XD. Diemžēl Gravity Falls fani nesagaidīja trešo un nākamās sezonas. Radītāji nolēma aprobežoties ar divām sezonām bez turpinājumiem.
Runājot par šīs animētās filmas sižetu, visa darbība notiek izdomātā pilsētā ar nosaukumu Gravity Falls. Tur ierodas divi dvīņi, kuru vārdi ir Meibela un Dipers. Viņi paliek pie sava brālēna Stena. Viņam ir savs tūristu suvenīru veikals. Kad brāļiem apnīk "nedarīt neko", viņi dodas piedzīvojumu meklējumos. Viens no viņiem meža atrod dīvainu dienasgrāmatu, kurā stāstīts par šīs pilsētas anomālijām. Dvīņi dodas meklēt tās autoru un sastopas ar neparastiem radījumiem un vietām. Ja jūs interesē šis animācijas seriāls, un jūs reiz bijāt tā varoņu fani, mēs iesakām jums mūsu peles kursoru kolekciju Gravity Falls stilā!',
    'gravity_falls_short_descr' => 'Dodieties piedzīvojumā ar Gravity Falls kursoru palīdzību',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Absolūti visi ir dzirdējuši par tik slavenu animācijas seriālu kā Simpsonu ģimene. Pat tie cilvēki, kuri nekad nav izskatījušies kā šie, ir apzināti par dzelteno varoņu eksistenci. Un fani ir sajūsmā, kad iznāk nākamā viņu iecienītā multfilmas sezona. Starp citu, 2019. gada rudenī tika izlaisti 31 sezonas konti. Un pirmie parādījās televīzijas ekrānos vēl 1989. gadā. Fox sāka to rādīt un joprojām turpina to darīt augsto reitingu un auditorijas simpātiju dēļ.
Simpsonu ģimene ir satīrisks žanrs, kas skar aktuālas tēmas. Tas var būt vidusmēra amerikāņa dzīvesveids, politiski un reliģiski jautājumi, slavenību triki, feminisms, viendzimuma laulības. Vispārīgi, viss, kas saistīts ar vietējiem un globāliem notikumiem, kuros piedalās Amerikas Savienotās Valstis.
Animācijas seriāla darbība notiek neeksistējošā pilsētā Springfīldā. Patiesībā Amerikā ir daudz pilsētu ar šo nosaukumu. Iespējams, tieši tāpēc tas tika izvēlēts, lai auditorija nesaistītu ekrānos notiekošo ar konkrētu lokalitāti, bet tikai minētu, kur tas varētu būt.
Jūs, visticamāk, esat Simpsonu ģimenes fans. Citādi, kāpēc jūs lasītu šo tekstu līdz galam? Un, ja tā ir, tad jums ir iespēja nomainīt garlaicīgo peles kursoru uz rādītāju, kas ir veidots šī animācijas seriāla stilā.',
    'simpsons_short_descr' => 'Jautra ģimenīte ar Simpsonu kursoru galvenajām lomām',
    'simpsons' => 'The Simpsons',
    'youtubers_descr' => 'YouTube video platforme parādījās 2005. gadā. Sākotnēji video tika publicēti tur tikai pašizpausmes vai informēšanas nolūkos. Tomēr laika gaitā tas viss pārauga ienesīgā biznesā, kas veiksmīgiem YouTube lietotājiem ienes tūkstošiem, dažreiz pat miljoniem dolāru mēnesī. Jo populārāks vlogeris (persona, kas vada video blogu), jo vairāk viņš var nopelnīt ar savu kanālu.
Cik nopelna piecus gadus veca vlogere meitene, kuras vecāki ved viņu uz visinteresantākajām atrakcijām un filmē notiekošo kamerā? Tas ir tikai veids, kā bērns izklaidējas bērnu parkos, kas pauž emocijas, kā izjokoties un visu šo lietu. Summa ir patiešām pārsteidzoša - šodien bērna kanāls ir ieguvis gandrīz 47 miljonus abonentu un sācis ģenerēt ienākumus 5 miljonu rubļu apmērā mēnesī.
Kāds augšupielādē video, kurā viņš apspriež datorspēles, kāds nodarbojas ar beiboksu vai rīko palaidnības garāmgājējiem uz ielas. Daži savus video velta sensitīvām tēmām, piemēram, vīriešu un sieviešu attiecībām. Jo vairāk YouTube lietotājiem patīk šie kadri, jo lielāka ir vlogera popularitāte.
Kolekcijai jau ir pievienots PewDiePie kursors, Shane Dawson kursors, Ray William Johnson kursors, Zoella kursors, MyLifeAsEva kursors un citi.',
    'youtubers_short_descr' => 'Jauna zvaigžņu paaudze vienmēr ir tiešsaistē mūsu YouTubers kolekcijā',
    'youtubers' => 'Jūtūberu',
    'pusheen_descr' => 'Gandrīz visi zina kaķi Pusheen. Kaut arī tas ir tikai bērnu komiksa varonis, kas izgudrots pirms 10 gadiem, viņam ir miljoniem fanu šodien. Pusheen kaķis parādījās kā ilustrācija, ko radīja māksliniece Klēra Beltona.
Pēc gada kaķis ieguva savu lapu vietnē Tumblr.com un dažu nedēļu laikā ieguva veselu fanu armiju - apmēram 10 000 cilvēku. 2013. gadā Facebook vēlējās iekļaut attēlus no Pushin kolekcijās ar citiem emocijzīmēm. Pēc sarunām ar radītāju šī ideja tika īstenota un “uzspridzināja” internetu! Attēli no Pusheen kaķa tiek izmantoti sarakstē vairāk nekā 10 miljonus reižu dienā!
2014. gadā viens no lielākajiem rotaļlietu ražotājiem Amerikas Savienotajās Valstīs pievērsa uzmanību šim varonim. GUND (tieši viņi izgudroja lācīšus) laida klajā pāris Pushin modeļus. Tā kā panākumi bija milzīgi, pēc dažiem mēnešiem tika izveidota pilna rotaļlietu kolekcija šī kaķa formā.
Kur vēl var satikt Pusheen kaķi? Dāvanu komplektos no Isaac Morris Ltd, zefīros no Boomf un, protams, mūsu Pusheen kursoru kolekcijā!',
    'pusheen_short_descr' => 'Pievieno komfortu savā pārlūkprogrammā ar Pusheen kursoru kolekciju',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'Pirmā animētā darba “Riks un Mortijs” sērija tika izlaista 2013. gadā. Šo multfilmu var tieši attiecināt uz 2 žanriem: zinātniskā fantastika un komēdija. Tās autori bija Dans Harmons un Džastins Roilands. Sākotnēji visas sērijas tika rādītas kanālā Cartoon Network, un tikai tad tās tika dublētas tiešsaistes kinoteātros un video mitināšanas vietnēs. Ik pēc dažiem gadiem tiek izlaistas jaunas Rika un Mortija sezonas, un 2019. gada novembrī iznāca ceturtā sezona, kas izrādījās ne mazāk interesanta kā iepriekšējās. Animētā seriāla sižets risinās ap ģēniju un vienlaikus traku zinātnieku vārdā Riks, kā arī viņa neuzkrītošo mazdēlu - Mortiju. Šos divus varoņus saista kopīgi piedzīvojumi visneparastākajās vietās. Un viņi tur nokļūst ar lidojošo šķīvīti, kas spēj pārvietoties caur starpplākšņu tuneli. Kā jau varējāt uzminēt, šis animācijas seriāls nedaudz atgādina filmu Atpakaļ nākotnē, bet tomēr tā nav tā animētā versija. Tomēr to atzinīgi novērtēja daudzi kritiķi par humoristiskām epizodēm, radošumu un oriģinalitāti. Vai vēlaties redzēt Riku vai Mortiju ne tikai šī darba sērijās, bet arī pārlūkprogrammā? Ja jā, instalējiet paplašinājumu un pievienojiet mūsu kolekciju, kas veltīta jūsu iecienītajai multfilmai! Šeit ir Rika Sančesa kursors, Mortija Smita kursors, Portāla lielgabala kursors un, protams, M. Mīsīksa kursors.',
    'rick_and_morty_short_descr' => 'Beidz murdēt, vienkārši izmanto kursorus no Rick and Morty kolekcijas',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Beisbola fani ir sastopami visur pasaulē. Tas īpaši attiecas uz tādu valstu iedzīvotājiem kā: ASV, Ķīna, Kuba, Dienvidkoreja, Japāna un Venecuēla. Pretēji populārajam uzskatam, beisbols neradās Amerikā, bet gan Anglijā. Pirmais pieminējums un beisbola apraksts parādījās tālajā 1744. gadā, angļu izdevumā. Pēc 145 gadiem amerikāņi šo izgudrojumu piesavinājās sev, neskatoties uz faktiem.
Nacionālā līga tika izveidota 1876. gadā. Tā ir daļa no Major League Kanādā un Amerikas Savienotajās Valstīs. Mūsdienās Nacionālajā beisbola līgā ir 15 komandas. Katras sezonas pēdējā daļā pienāk izslēgšanas spēļu laiks, kurā piedalās 4 labākās komandas. Tā tiek atklāts visas Nacionālās līgas uzvarētājs. Pēc tam uzvarētājkomanda iegūst iespēju spēlēt pret uzvarētāju no Amerikas līgas Pasaules sērijā.
Vai jūs interesē beisbols vai pat atbalstāt kādu no komandām? Tad parādiet cieņu savai iecienītajai komandai, iestatot peles kursorus tās atribūtu veidā! Mainiet garlaicīgo rādītāja izskatu pārlūkprogrammā uz pazīstamo beisbola korporatīvo identitāti! Pārvērtiet bultiņu par spēlētāja nūju vai ķiveri jebkurā no Nacionālās līgas komandām, kuras jau ietver New York Yankees kursoru, Great Falls Dodgers kursoru, Boston Red Sox kursoru, Baltimore Orioles kursoru, Oakland Athletics kursoru.',
    'mlb_teams_short_descr' => 'MLB komandu kursoru kolekcija visiem mūsu faniem.',
    'mlb_teams' => 'MLB Teams',
    'brawl_stars_descr' => 'Brawl Stars ir mobilā spēle MOBA žanrā no Supercell. Neskatoties uz izlaišanu 2018. gada beigās, spēle guva lielu popularitāti, galvenokārt pateicoties kaujas režīmu pārpilnībai un krāsainiem, fantastiskiem varoņiem - kautiņiem. Spēlētājam ir daudz ko izvēlēties - 32 unikāli varoņi, un katram no tiem ir savs spēju un prasmju kopums. Katram varonim ir arī sava pasīvā prasme, kas ir pieejama caur laupījuma lādēm. Spēlētāji var cīnīties vairākos režīmos, piemēram, "Atalgojums par sagūstīšanu" - uzvar viena no divām komandām, kura ir savākusi vairāk zvaigznes, nogalinot pretiniekus. Režīmā "aplaupīšana" ir nepieciešams salauzt pretinieku seifus, vienlaikus saglabājot savus. Interesants "Dārgakmeņu satveršanas" režīms - komanda, kas savāc visvairāk dārgakmeņu, kļūst par uzvarētāju. Nu, režīmā "Sadursme" 10 spēlētāji cīnās savā starpā kartē, kur robežas tiek samazinātas toksiska mākoņa dēļ. Spēle ir pārpilna ar krāsainu dizainu, kas daudziem patīk, tostarp mums, kas mūs iedvesmoja izveidot atsevišķu Brawl Stars kursoru kolekciju. Ir Brawl Stars Shelley kursors, Barley kursors, Penny kursors, Frank kursors, Mortis kursors un citi.',
    'brawl_stars_short_descr' => 'Izvēlieties Brawl Stars kursorus un ļaujiet cīņai sākties',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Mainiet savu peles kursoru divos klikšķos! Bezmaksas kolekcijas katrai gaumei.',
    'all_descr' => 'Ja jūs kādreiz domājāt, kā mainīt garlaicīgu peles kursoru, tad mūsu kursoru kolekcijas ir domātas jums! Šeit jūs atradīsiet foršus komiksu varoņus, skaistus kursorus spēlētājiem ar varoņiem no populārām spēlēm, jautrus kursoru komplektus praktiskiem jokiem, krāsu kursorus un daudzas citas interesantas iespējas.',
    'text_title' => 'Forši un smieklīgākie kursora kolekcijas katrai dienai',
    'text_allcat_title' => 'Unikāli un radoši peles kursori, lai atbilstu katram tavam noskaņojumam',
    'text_1' => 'Jūs nevēlaties būt kā visi citi? Vai vienkārši mīlat visu neparastu? Vēlaties būt daļa no sava iecienītā spēles varoņa vai multfilmas tēla? Tad jūs esat nonācis īstajā vietā. Šeit jūs atradīsiet spilgtus, neparastus kursoru komplektus, kas var aizstāt pazīstamo un jau diezgan garlaicīgo balto bultu. Pelītes kursors pavada mūs visu dienu darbā un mācībās, tāpēc tam vajadzētu sniegt lielisku garastāvokli un noskaņot uz pozitīvu.',
    'text_2' => 'Šeit jūs atradīsiet kursorus spēlētājiem un filmu cienītājiem, skaistus kursorus, kuru pamatā ir jūsu iecienītākās karikatūras un sporta motīvi aktīvākajiem cilvēkiem. Vai jums patīk komiksi vai nevarat iedomāties nevienu dienu bez jautriem mēmiem? Vai jūs dievinat dzīvniekus vai sapņojat apmeklēt visas pasaules valstis? Viss ir vienkārši - mums ir piemērots kursora attēls arī jums. Jūs varat arī izvēlēties attēlus atkarībā no tā, ar ko strādājat. Piemēram, melns kursoris būs daudz ērtāks nekā balts, strādājot ar dokumentiem vai zīmējumiem, un rokas kursoris būs ērtāks, ja jums jāstrādā ar maziem grafiskiem elementiem. Izvēlieties savu iecienītāko attēlu, pielāgojiet tā izmēru tieši paplašinājumā - un izmantojiet to ar prieku, katru dienu sākot ar pozitīvu noti!',
    'install_to_preview' => 'Lūdzu, instalējiet paplašinājumu, lai skatītu priekšskatījumu',
    'install' => 'Instalēt',
    'add_button' => 'Pievienot',
    'preview_button' => 'Priekšskatīt',
    'added_button' => 'Pievienots',
    'add_cursor' => 'Pievienot kursoru',
    'to_your_collection' => 'jūsu kolekcijai',
    'prev_text_1' => 'Pilnekrāna priekšskatījums',
    'prev_text_2' => 'kursors',
    'cursor' => 'kursors',
    'pointer' => 'rādītājs',
    'a_title_1' => 'Cursor Style - Forši kursoru jūsu pārlūkam',
    'a_title_2' => 'Forši tematiskie kursoru kolekcijas',
    'mouse_cursors' => 'Peles kursori',
    'cursor_collection' => 'Kursoru kolekcija',
    'sborka_cursorov' => 'Kursoru kolekcija',
    'collection_list_from_colllection' => 'Kursoru saraksts - ',
    'christmas' => 'Ziemassvētki',
    'nhl_teams' => 'Nacionālā hokeja līga',
    'neon' => 'Neons',
    'adventure_time' => 'Piedzīvojumu laiks',
    'nba_teams' => 'Nacionālā Basketbola asociācija',
    'spongebob' => 'SpongeBobs',
    'phineas_and_ferb' => 'Fineass un Ferbs',
    'fortnite_chapter_2' => 'Fortnite 2. nodaļa',
    'pokemon' => 'Pokemons',
    'famous_people' => 'Slavenības',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Komiksi',
    'igry' => 'Spēles',
    'multfilmy' => 'Multfilmas',
    'kino_i_serialy' => 'Filmas',
    'anime' => 'Anime',
    'futbol' => 'Futbols',
    'avtomobili' => 'Automašīnas',
    'memy' => 'Mēmi',
    'emodji' => 'Emocijzīmes',
    'pitomcy' => 'Mājdzīvnieki',
    'stil_i_krasota' => 'Mode un stils',
    'prazdniki' => 'Svētki',
    'flagi' => 'Karogi',
    'vokrug_sveta' => 'Apkārt pasaulei',
    'eda_i_napitki' => 'Ēdiens un dzērieni',
    'cvetnye' => 'Krāsaini',
    'prank' => 'Joki',
    'startovyj_nabor' => 'Sākuma komplekts',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Ziemassvētku kursori noteikti iepriecinās Ziemassvētku vecīti',
    'nhl_teams_short_descr' => 'NHL kursoru kolekcija īstiem faniem',
    'neon_short_descr' => 'Pievieno spilgtumu ar neona kolekciju',
    'adventure_time_short_descr' => 'Mācāmies matemātiku ar Adventure Time kursoru kolekciju',
    'nba_teams_short_descr' => 'NBA kursoru kolekcija kā liels basketbola uzvaru simbols',
    'spongebob_short_descr' => 'Uzziniet, kurš dzīvo okeāna dibenā, izmantojot Kārļa Bobeļa (SpongeBob) kursoru kolekciju',
    'phineas_and_ferb_short_descr' => 'Jūs noteikti nenoskumstosiet ar Phineas un Ferb kursoru kolekciju',
    'fortnite_chapter_2_short_descr' => 'Fortnite kulta spēles jaunā nodaļa',
    'pokemon_short_descr' => 'Notveriet visus, ja varat',
    'famous_people_short_descr' => 'Iedvesmojieties ar savu elku kursoru',
    'the_elder_scrools_short_descr' => 'Iegremdējieties bruņinieku un pūķu pasaulē',
    'halloween_short_descr' => 'Baidieties palaist garām jauno Helovīna kolekciju',
    'nfl_teams_short_descr' => 'Īstiem futbola faniem',
    'five_nights_at_freddy_short_descr' => 'Mēģiniet nebaidīties no šiem animatroniķiem.',
    'komiksy_short_descr' => 'Kursoru veidi no komiksiem: izvēlieties savu noskaņojumu šodien.',
    'igry_short_descr' => 'Virtuālā realitāte: ar ko jūs šodien spēlējat?',
    'multfilmy_short_descr' => 'Iemīļotie multfilmu varoņi jaunā dizainā',
    'kino_i_serialy_short_descr' => 'Kursora pavēlnieks: Darbvirsmas brālība',
    'anime_short_descr' => 'Visi mīl animi: kurš ir tavs mīļākais varonis?',
    'futbol_short_descr' => 'Vai tu esi īsts sporta fans? Tad tev ir jābūt šeit.',
    'avtomobili_short_descr' => 'Tava sapņu automašīna: liels autoparks profesionāļiem.',
    'memy_short_descr' => 'Iecienītākie motīvi: Mēmu kursoru kolekcija.',
    'emodji_short_descr' => 'Parādiet savu īsto noskaņojumu citiem - iestatiet Cursoji!',
    'pitomcy_short_descr' => 'Spilgti kursoru varianti visiem mūsu mazāko brāļu mīļotājiem.',
    'stil_i_krasota_short_descr' => 'Oriģināli kursori visiem dzīves gadījumiem.',
    'prazdniki_short_descr' => 'Kas ir kalendārā? Jauna svētku kursoru kolekcija!',
    'flagi_short_descr' => 'Meklējat piedzīvojumus: kurp dosimies šodien?',
    'vokrug_sveta_short_descr' => 'Apkārt pasaulei acumirklī: kurp dosimies šodien?',
    'eda_i_napitki_short_descr' => 'Garšīgi kursoru veidi radošumam',
    'cvetnye_short_descr' => 'Nokrāso savu dzīvi spilgtos toņos un drosmīgos triepienos',
    'prank_short_descr' => 'Kursoru komplekts vissmieklīgākajiem jokiem',
    'startovyj_nabor_short_descr' => 'Jauns skatījums uz pazīstamām lietām: atjaunināta kursoru sērija',
    'fortnite_short_descr' => 'Seko strīmeriem!',
    'dota_2_short_descr' => 'Padariet savu virtuālo pasauli par reālu!',
    'minecraft_short_descr' => 'Jūsu iecienītākās spēles varoņi vienmēr ir tuvumā',
    'christmas_descr' => 'Katrs no mums neapšaubāmi gaida populārākos svētkus - Ziemassvētkus. Visi pasaules kristieši tos tradicionāli svin katru gadu, 25. decembrī. Tas ir laiks, kad ģimenes pulcējas pie viena galda, dalās priekā un mīlestībā un apmainās ar dāvanām. Ilgi pirms Ziemassvētkiem cilvēki rotā ielas ar spilgtām vītnēm un savas mājas ar tradicionāliem atribūtiem. Ir grūti atrast cilvēku, kuram nepatīk Ziemassvētki - jautri un noslēpumaini svētki, jo tos pavada daudzas tradīcijas un rituāli, kas mūs atgriež pie visas mūsu ģimenes saknēm. Ziemassvētku priekšvakarā burtiski viss ir piesātināts ar to garu, sākot no krāsainiem piparkūkas līdz aizkustinošiem dziedājumiem. Eleganta Ziemassvētku eglīte un dāvanas zem tās, prieks, kas katram no mums ir pazīstams kopš bērnības. Mēs vēlamies pievienoties šiem maģiskiem svētkiem un, kas zina, varbūt Ziemassvētku vecītis sagatavos jums īpašu dāvanu, ja jūs izrotāsiet savu kursoru ar mūsu Ziemassvētku kolekciju. Šim nolūkam ir viss nepieciešamais, Ziemassvētku vecīša kursors, Ziemassvētku eglītes kursors, piparkūkas kursors, Sniegavīra kursors un pat dāvanu maisa kursors. Priecīgus Ziemassvētkus!',
    'nhl_teams_descr' => 'Nacionālā hokeja līga tika izveidota 1917. gadā - tā ir profesionāla sporta organizācija, kas apvieno hokeja klubus no ASV un Kanādas. Un šī ir viena no pirmajām profesionālajām hokeja līgām pasaulē. NHL ir viena no Ziemeļamerikas vadošajām sporta līgām, līdzās NFL, NBA, Major League Baseball un MLS. Katru gadu 31 komanda no 30 pilsētām ASV un Kanādā cīnās par galveno trofeju - Stenlija kausu, un komanda, kas regulārajā sezonā ieguvusi visvairāk punktu, saņem Prezidenta kausu. Ir pienācis laiks mums godināt šo lielisko spēli, izveidojot NHL kursoru kolekciju. Ja arī jums patīk hokejs, atbalstiet savu iecienītāko klubu vai piedalieties šajā sportā pats, vienkārši nomainiet kursoru un nešķirieties no savas iecienītās komandas, tostarp Bostonas Bruins kursoru, Sentluisas Blues kursoru, Kolumbusas Blue Jackets kursoru, Tampabejas Lightning kursoru, Dalasas Stars kursoru un citiem klubiem, kas ir cienīgi ar sirsnīgu cieņu.',
    'neon_descr' => 'Mēs esam izveidojuši unikālu neona kursoru kolekciju, lai pievienotu dažādību ikdienas interneta pārlūkošanai un pievienotu mazliet spilgtuma hipnotiskajam neona apgaismojumam. Ļaujiet viņu bagātīgajām krāsām radīt valdzinošu nakts pilsētas atmosfēru, dot iedvesmu radīt kaut ko jaunu. Mūsdienu pasaulē metropoles gaismas vienmēr paziņo par nakts iestāšanos, tās seko mums uz katras ielas, un šis spožums ir enerģijas pilns. Ļaujiet tam sekot arī spīdošam saldējuma kursoram, gardam hotdoga kursoram, sulīgam burgera kursoram, dzirkstošam dimanta kursoram un citiem kursoriem no jaunās neona kolekcijas.',
    'adventure_time_descr' => '"Piedzīvojumu Laiks" ir fantastiska žanra karikatūra, kuras darbība norisinās pasaulē, kas pārdzīvojusi apokalipsi. Šī teritorija tiek saukta par Zemi Uu, kas vēl nesen bija kodolkarš. Bet tas viss jau ir pagātnē, tomēr visi izdzīvojušie cilvēki pakļauti mutācijām, un pasaule ir piepildīta ar maģiju. Galvenie animācijas seriāla varoņi ir Finns, 14 gadus vecs zēns, un viņa draugs suns vārdā Džeiks. Zēns un suns ļoti mīl piedzīvojumus, viņi pastāvīgi palīdz visiem, kuriem ir nepatikšanas. Draugi dzīvo uz koka un pavada visu savu laiku kopā. Ja vēlaties ienirt piedzīvojumu pasaulē ar citiem cienītājiem, tad kliedziet "Matemātika". Šeit ir gan Finna zēna kursors, gan Džeika kursors, kā arī Princeses Košļājamās gumijas kursors. Protams, mēs neaizmirsām arī Bimo kursoru, Ledus karaļa kursoru un citus.',
    'nba_teams_descr' => 'Ja basketbols ir tava mīļākā spēle, kā tas ir mums, tad tev ir nepieciešama kursoru kolekcija, kas veltīta NBA komandām. NBA ir viena no labākajām Ziemeļamerikas kontinenta sporta asociācijām. Veidojot šo kolekciju, mūs mocīja izvēle - kuru komandu izvēlēties, jo NBA ir trīsdesmit. Bet ir komandas, kas ir leģendas. Šī ir Chicago Bulls, kas uzstādīja rekordu uzvaru skaitā 90. gadu vidū. Šis ir Golden State Warriors, kas pirms pāris gadiem saveda kopā labākos līgas spēlētājus. Vai, piemēram, Lakers, Celtics arī ir ārkārtīgi foršas komandas. Ja, tāpat kā mēs, gaidi savu mīļāko basketbola komandu spēles un vēlies izrādīt atbalstu komandai vai spēlētājiem, lejupielādē mūsu NBA kursoru kolekciju.',
    'spongebob_descr' => 'Animācijas sēriju "SpongeBob SquarePants" pazīst tik daudz cilvēku. Tā bija milzīgs panākums pēc tam, kad Nickelodeon 1999. gadā nolēma izveidot animācijas sēriju, kuras pamatā būtu izglītojošu komiksu sērija Tide Zone, un pārvērtās ļoti ienesīgā franšīzē. Sērijas veidotājs ir bijušais okeanoloģiskās laboratorijas darbinieks, tāpēc gandrīz visi animācijas sērijas varoņi ir smieklīgi jūras dibena iemītnieki ar savām īpatnībām un harizmu. Darbība risinās ap slepeno Krabsburgera recepti, ko var pagatavot tikai galvenais varonis - Sponge Bobs. Un pārējie jūras iedzīvotāji dienu no dienas cenšas to iegūt, ieskaitot galveno anti-varoni Šeldonu Planktonu, kuram tas neizdodas katru reizi. SpongeBob kursoru kolekcijā mēs esam apkopojuši visu sērijas ievērojamāko varoņu un notikumu kursorus. Piemēram, kungs Krabsu kursors ar dolāru, Patriks Zvaigzne kursors, Squidvords ar savu klarneti, medūzu kursors, Sponge Bob kursors un daudzi citi varoņi.',
    'phineas_and_ferb_descr' => 'Izdomātajā Amerikas pilsētā Denvilā, neeksistējošajā Trishtatjā, dzīvo divi interesanti puikas. Katra viņu brīvdienu diena pārvēršas neticamos piedzīvojumos, jo viņi var uzcelt kalniņu visu pilsētas izmērā vai īstu portālu uz citu planētu. Ar saviem pārsteidzošajiem izklaidēm viņi dalās ar draugiem. Tajā pašā laikā, kamēr puikas jautri pavada laiku, ļaunais zinātnieks Haincs Fufelšmerts būvē vēl vienu ļauno mašīnu, kas rada haosu, ar nosaukumu beigās ar "-inator", ar kuras palīdzību viņš vēlas atriebt savas bērnības pāridarījumus vai sagrābt varu Trishtatā, bet Perijs viņam traucē - pīļknābis, slepenais "Aģents Pī", strādājot puiku mājdzīvnieka aizsegā. Šī animācijas seriāla popularitāte gan bērnu, gan pieaugušo vidū ir iedvesmojusi mūs izveidot Fīneasa un Ferba kursoru kolekciju, lai jūs varētu mainīt savu peles kursoru uz seriāla varoņiem. Starp tiem ir Fīneasa Flina kursors, Dr. Hainca Fufelšmerta kursors, Ferba Flečera kursors, Kendisas Gertrūdes Flinas kursors un Perija pīļknābja kursors.',
    'fortnite_chapter_2_descr' => 'Fortnite otrā nodaļa atnāca pēc grandioza notikuma - Beigām, kas ievilka visu, ko spēlētāji spēlē mīlēja, melnajā caurumā. Fortnite 2. nodaļai tagad ir jauna karte, kas pirmajā acu uzmetienā ir vēl savvaļīgāka par oriģinālo karti, kā arī daudz izmaiņu spēles mehānikā un, protams, daudz jauna spēļu satura! Transportlīdzekļi, emocijas, peldēšanas mehānika un vēl daudz vairāk - tas viss svaigos, interesantos attēlos, viss tā, kā jūs mīlat un novērtējat šajā kulta spēlē. Iegremdējieties jaunā pasaulē - izvēlieties nolaišanās vietu un izpētiet pilnīgi jaunu salu ar 13 lokācijām. Peldēšana, zveja, motorlaivas - šī ir jauna ūdens spēle. Vairāk jautrības un mazāk pūļu - uzlabojiet pilnīgi jaunu 2. nodaļu un neaizmirstiet mainīt kursoru uz jauniem skinu un ieročiem. Jūs jau gaida atjauninātie skinu Turk kursors, Riptide kursors, Rippley kursors, Remedy kursors, Toxin kursors, 8-Ball kursors, Fusion kursors un citi!',
    'pokemon_descr' => 'Vārds "pokemon" nozīmē būtni ar pārdabiskām spējām. Tiem ir intelekts, un daži no tiem pat spēj runāt. Pašlaik jau ir 802 Pokemon šķirnes. Izgudrotajā Pokémon pasaulē cilvēki tiek saukti par Pokémon treneriem, kurus viņi apmāca cīņām ar citiem treneriem Pokémon. Un jo pieredzējušāks un spēcīgāks treneris, jo lielāku cieņu viņš izpelnās. Par laimi, jāatzīmē, ka Pokémon cīņas nekad nebeidzas ar šo unikālo būtņu nāvi. Visiem Pokémon ir atšķirīgas spējas un atšķiras pēc elementa veida, un tā izturība pret dažādiem uzbrukumiem no tā spēcīgi atkarīga, un dažām būtnēm ir divu elementu spēja vienlaikus. Pēc cīņas uzvarēšanas Pokémon iegūst vērtīgu pieredzi, kas nepieciešama, lai paaugstinātu līmeni un attiecīgi savas īpašības. Mūsdienās Pokémon pasaule ir milzīga mediju franšīze, un mēs nolēmām jums sagatavot kursoru kolekciju ar dažiem populāriem Pokémon. Starp tiem pazīstamākais ir Pikachu kursors, kā arī Rattata kursors, Squirt kursors, Bulbasaur kursors un Charmander kursors. Šis saraksts tiks atjaunināts, jo to ir tik daudz, un katrs no tiem ir unikāls savā veidā.',
    'famous_people_descr' => 'Starp daudzajiem slaveniem cilvēkiem katrs no mums atrod paraugu vai vienkārši apbrīno šo slavenību ģēniju, talantu un neatlaidību. Mēs esam sagatavojuši slavenību kursoru kolekciju, lai jūs iedvesmotu un atgādinātu par lielajiem sasniegumiem, ko katrs no jums var palielināt. Ne visiem slaveniem cilvēkiem ir bijis laimīgs liktenis, bet viņi māca mums galveno lietu, ka nekad nav jāatkāpjas no sava lolotā mērķa, neskatoties uz grūtībām un problēmām. Galu galā, šis ir galvenais panākumu sasniegšanas princips - iet uz savu sapni katru dienu un beidzot kļūt par labāko savā jomā. Varbūt šodien jūs vienkārši vēlaties mainīt savu peles kursoru, un rīt visa jūsu dzīve mainīsies uz labo pusi! Kolekcija tiks pastāvīgi atjaunināta ar jauniem, cienījamiem cilvēces pārstāvjiem. Starp tiem, protams, zinātnieki, politiķi, sportisti, mākslas pārstāvji un daudzi citi. Džordža Vašingtona kursors, kursors, Maikla Džordana, Stīvena Kinga kursors, Elvisa Preslija kursors un Merilinas Monro kursors ir tikai sākums.',
    'the_elder_scrools_descr' => 'The Elder Scrolls ir datorspēļu lomu spēļu sērija, ko vieno kopīgs, rūpīgi izstrādāts Visums, kas spēlētājam nodrošina milzīgu izvēles brīvību, ļaujot apmeklēt dažādas fantāzijas pasaules vietas un pilsētas un izpētīt jaunas vietas un misijas pēc saviem ieskatiem. Darbs pie sērijas sākās jau 1992. gadā, un gadu gaitā spēle ir apvienojusi sev apkārt milzīgu spēlētāju kopienu. Tāpēc pēc pieprasījuma mēs esam izlaiduši kursoru kolekciju The Elder Scrolls, lai jūs varētu iegremdēties unikālajā spēles atmosfērā. Mūžīgā bruņinieku un pūķu cīņa, kurā pusē jūs esat? Nomainiet kursoru uz pūķi un pievienojieties uguni spļaujošo briesmoņu armijai vai cīnieties cēli cilvēku pusē, izvēloties zobena kursoru un sava iecienītākā varoņa attēlu - lēmums ir jūsu! Galvenais ir tas, ka ar mūsu jauno kolekciju jūs esat gatavi jebkurām cīņām.',
    'halloween_descr' => 'Gaidot mistisku nakti Visu Svēto dienas priekšvakarā. Helovīna vēsture sniedzas vairāk nekā divus tūkstošus gadu atpakaļ. Iespējams, šis ir dīvainākais svētku salikums, apvienojot jautrību un bailes, kas ir ķeltu kultūras dzimtene. Tad cilvēki dedzināja ugunskurus un uzvilka biedējošus tērpus, lai aizbiedētu spokus. Vārds "Helovīns" pirmo reizi tika pieminēts 16. gadsimtā kā skotu saīsinājums no angļu frāzes All-Hallows-Even. Pāvests Gregorijs III pasludināja 1. novembri par Visu Svēto dienu, un vakars pirms tam bija pazīstams kā Visu Svēto vakars, un vēlāk Helovīns. Šajā dienā cilvēki valkā vilkaču, spoku un citu monstriju tērpus un dodas uz kaimiņu mājām, piedāvājot pirkt saldumus. Tematiskās ballītes, uguņošana, skaistas laternas, ķirbji un triki rada unikālu atmosfēru. Mēs arī vēlamies svinēt šos šausminošos svētkus ar aksesuāru kursoriem un Helovīna varoņiem. Mūsu kolekcijā jūs varat atrast: zombiju kursoru, spoku kursoru, melnā kaķa kursoru, ķirbja kursoru un daudz ko citu. Mainīt savu noskaņojumu tagad ir tikpat viegli kā mainīt savu kursoru ar mūsu jauno Helovīna kolekciju.',
    'nfl_teams_descr' => 'Kas varētu būt labāks īstam amerikāņu futbola fanam nekā peles kursors komandas simbolikas veidā, par kuru viņš ir fans? Mūsdienu Nacionālajā Futbola Līgā spēlē trīsdesmit divas komandas, kas sadalītas starp Nacionālo un Amerikāņu Futbola Konferencēm (Nacionālā Futbola Konference, NFC un Amerikāņu Futbola Konference, AFC). Savukārt katra no konferencēm ir iedalīta četros divīzijos: Austrumu, Ziemeļu, Dienvidu un Rietumu. NFL sezona sastāv no pirmssezonas spēlēm, regulārās sezonas un izslēgšanas spēļu sērijas. NFL sezonas finālmaču sauc par Super Bowl, un būtībā tas ir populārākais sporta notikums Amerikas Savienotajās Valstīs. Šī ir iecienīta spēle miljoniem fanu, un tāpēc mēs esam izveidojuši NFL kursoru kolekciju, lai jūs neatvadītos no savas iecienītākās komandas simboliem. Neatkarīgi vai tā ir New England Patriots, New York Giants, Buffalo Bills vai cita komanda, vienmēr esiet uz viena viļņa garuma ar saviem elkiem, izmantojot mūsu kursorus komandas logotipa un ķiveres veidā. Kolekcija tiks pastāvīgi atjaunināta, lai ikviens varētu mainīt kursoru uz savas iecienītākās komandas attēlu.',
    'five_nights_at_freddy_descr' => 'Tiešām unikālā spēle Five Nights at Freddy\'s ātri vien ieguva plašu popularitāti, un tas nav pārsteidzoši, jo tās vienkāršais un tajā pašā laikā aizraujošais sižets spēj noturēt spēlētājus pie ekrāniem stundām ilgi. Mēs izstrādājām Five Nights at Freddy\'s kursorus pēc spēles fanu lūguma un bijām ļoti priecīgi iemiesot tik interesantus un smieklīgus varoņus. Bet atšķirībā no spēles, nekas tev nedraud ar mūsu kursoru, tāpēc droši izvēlies savus iecienītākos animatronikus, vai tas būtu Lācis Fredijs vai Trusis Bonijs vai citi. Galvenais ir tas, ka tagad spēle atdzīvojas tavā pārlūkā un dāvā svaigas emocijas. Mēs garantējam, ka mūsu kursoros nav spoku, bet tie lieliski atspoguļo spēles garu, kas iedvesmo bailes, pateicoties dizaina sarežģītībai un sižeta elementiem. Bet ko darīt, ja tu padari kursoru ļoti lielu? Vai vari palikt mierīgs un nebaidīties?',
    'komiksy_descr' => 'Šķiet, ka peles kursors ir sīkums, bet bieži vien tieši šādas detaļas var uzlabot garastāvokli, pamodināt pelēkajā rītā vai vienkārši sniegt spilgtas emocijas. Komiksu kursoru kolekcija paredzēta tieši visiem supervaroņu cienītājiem. Šeit jūs varat atrast pilnīgi visu Marvel Universe un DC Comics - no Iron Man līdz Thanos, Spider-Man un Hulk. Kursoru stils var būt gan supervaroņa formā, gan viņa varoņa formā. Kursors nav tikai funkcionāls elements; tas ir svarīgs profesionālā nozīmē. Piemēram, ja jūs ierakstāt video no ekrāna, būs labāk redzēt spilgtu, oriģinālu attēlu, un tas izskatās daudz interesantāk. Un, protams, - kurš gan nevēlētos izmantot bezgalības cimdu reālajā dzīvē? Peles kursora maiņa ir vienkārša - vienkārši lejupielādējiet paplašinājumu savā pārlūkprogrammā un pievienojiet jums tīkamo kursoru saviem iestatījumiem, izmantojot to. Jūs varat izvēlēties kursoru atbilstoši savam garastāvoklim vismaz katru dienu. Pietiek ar pelēkajām dienām - kļūstiet par supervaroni tieši tagad!',
    'igry_descr' => 'Datorspēles jau sen ir kļuvušas par neatņemamu mūsu dzīves sastāvdaļu. Ar to palīdzību varat ienirt jaunā pasaulē, piedalīties piedzīvojumos un kļūt par pilnīgi citu cilvēku. Katram ir sava mīļākā spēle, kuras varoņi jau ir kļuvuši gandrīz par ģimeni. Kursoru komplekts, kura pamatā ir labi zināmas datorspēles, ir iespēja atšķaidīt garlaicīgo ikdienu un pievienot nedaudz radošuma, spilgtuma un jautrības darba plūsmai. Komplektā ir gan pašu spēļu varoņu attēli, gan palīgvaroņi, ieroči un spēļu ikonas. Izvēlieties to, kas atbilst jūsu noskaņojumam - spēļu kursori patiks ne tikai spēlētājiem, bet arī visiem, kuri vienkārši ir noguruši no pelēkās ikdienas. Vienkārši lejupielādējiet komplektu, mainiet peles kursoru - un dodieties veikt uzdevumus, iznīcināt ienaidniekus un sasniegt savus mērķus.',
    'multfilmy_descr' => 'Ikvienā pieaugušajā joprojām mīt bērns, kurš mīl multfilmas un joprojām sapņo kļūt par vienu no varoņiem. Mēs palīdzēsim piepildīt jūsu sapņus - izmantojiet jauno kursoru kolekciju, kas balstīta uz slavenākajām un iecienītākajām multfilmām. Toms un Džerijs, Bazz Lightyear un Šreks, Grāvītēji un pat Pokemoni - jūs varat kļūt par to, ko vēlaties katru dienu. Izvēlieties peles kursoru atbilstoši savam noskaņojumam. Kas jūs esat šodien? Bezrūpīgs un jautrs minjons, kas viegli atrisina jebkuras problēmas, vai spēcīgs un drosmīgs Rafaels, kura mērķis ir ne tikai paveikt varoņdarbus, bet arī apēst picu? Varbūt jūs esat visvarenais džins, kurš savā pakļautībā tur visu biroju? Kolekcijā ir varoņi ikvienam - no princesēm līdz pūķiem - atliek tikai izlemt, kurš atspoguļo šodienas noskaņojumu. Cursor Style ir ne tikai spilgts attēls. Tā ir individualitātes, pašizpausmes un vienkārši - jautrības, prieka un pozitīvisma atspoguļojums visai dienai. Vai ir garlaicīgi strādāt vai pārāk slinki mācīties? Vai ir kļuvis skumji un nav prieka? Mainiet kursoru, un pasaule mirdzēs ar jaunām krāsām.',
    'kino_i_serialy_descr' => 'Filmas - tās ir maģija, mistika un vienkārši lielisks veids, kā atpūsties, izklaidēties un gūt spilgtas emocijas. Tajā pašā laikā pēc skatīšanās mēs joprojām atceramies iemīļotos varoņus, kurus ļoti vēlamies satikt realitātē. Tagad tas ir iespējams - vienkārši lejupielādējiet jauno kursoru kolekciju, kas balstīta uz slavenām filmām un TV šoviem. Spilgti, forši kursori būs lielisks papildinājums darbvirsmai, pārvērtīs garlaicīgo pelēko ikdienu svētkos, un banālos uzdevumus - aizraujošā piedzīvojumā. Mainiet kursoru varoni katru dienu - pēc noskaņojuma, uzdevumiem vai nejauši. Kas jūs būsiet šodien? Godīgais un taisnīgais Džons Snou vai drosmīgais, nelokāmais Džons Viks? Varbūt jums priekšā ir grūts uzdevums, un tikai Frodo var to paveikt? Varbūt šodien jūs esat tikai citplanētietis, kurš nevēlas kontaktēties ar citiem? Izvēlieties piemērotu kursoru - paceliet garastāvokli un tajā pašā laikā parādiet citiem, ko domājat un kā plānojat pavadīt savu dienu. Pamēģiniet - tas ir ne tikai jautri, bet arī atkarību izraisoši - jūs noteikti nevēlēsieties atgriezties pie parastās bultiņas.',
    'anime_descr' => 'Anime ir unikāls animācijas stils, ko, neskatoties uz tā izteikto etniskumu, ir baudījuši miljoniem cilvēku visā pasaulē. Ir maz ticams, ka būs vismaz viens cilvēks, kurš nebūs skatījies multfilmas šajā stilā. Mēs izveidojām foršākos anime stila kursorus, kas patiks visiem šī stila faniem. Standarta kursoru lietošana ir garlaicīga un banāla. Parādiet savu personību – izmantojiet Anime kursoru kolekciju ar saviem mīļākajiem varoņiem. Izvēlieties tumša zoba kursoru, ja sapņojat par piedzīvojumiem un drosmīgām cīņām. Gudrais resnais vīrs Totoro jūs iepriecinās pat visbēdīgākajā dienā, un Naruto motivēs jūs piedzīvojumiem un parādīs apkārtējiem, ka jūs esat mega foršs. Spilgti kursori padarīs darba dienu gaišāku vai padarīs mācību procesu interesantāku un patīkamāku. Neierobežojiet sevi – izmantojiet savus iecienītākos motīvus pat tādos mazos elementos kā peles kursors. Mainiet kursorus katru dienu, pielāgojiet tos savam noskaņojumam un parādiet savu personību – ar anime stila kursoru to ir tik vienkārši.',
    'futbol_descr' => 'Futbols ir īpašs sporta veids, kas ietver cīņas, vieglatlētikas un precizitātes elementus. Vispārīgi, tas ir iespaidīgs, nežēlīgs un pulcē miljoniem fanu visā pasaulē. Vai jums patīk futbols vai vienkārši patīk sports? Tad lejupielādējiet kursoru komplektu pasaulslavenās spēles stilā un pierādiet lojāla fana titulu. Kolekcija satur 24 variantus kursoru dizainam - vispopulārāko komandu formā, kas ir pelnījušas savus titulus kā izmisīga un neatlaidīga spēle. Kursori ir izgatavoti divos variantos - standarta trīsstūra formā, kas ir dekorēta komandas krāsās, vai piemērotas spēles ķiveres formā. Standarta pārlūkprogrammas kursors ir garlaicīgs un nav cienīgs īstam sporta fanam. Kļūsti oriģināls un unikāls ar mūsu kolekciju. Lejupielādējiet attēlus un izvēlieties savas mīļākās komandas krāsas vai pielāgotus kursorus, ja jums vienkārši patīk sports un jūs atbalstāt visus. Sekot saviem hobijiem ir tik vienkārši - jums nav jāierodas darbā ar šalli vai cepuri jūsu mīļākās komandas krāsās, ir ātri un viegli nomainīt kursoru uz spilgtu, stilīgu attēlu.',
    'avtomobili_descr' => 'Vai jums patīk automašīnas un patīk skatīties modeļus no dažādiem ražotājiem? Vai arī jūs jau ilgu laiku sapņojat par kādu konkrētu zīmolu, bet joprojām nav iespējas to iegādāties? Īpaši jums mēs esam izveidojuši spilgtu kursoru komplektu "Supermašīnas". Šeit jūs atradīsiet klasisku Ford un stilīgu Bentley, spilgti Lamborghini un unikālu Ferrari. Vai vēlaties kļūt par oriģinālās automašīnas īpašnieku? Tas ir vienkārši - lejupielādējiet mūsu kursoru kolekciju savā ierīcē un mainiet automašīnas attēlu vismaz katru dienu. Kursori ir izstrādāti divos variantos - kā pilnvērtīga automašīna vai kā tās zīme. Izvēlieties to, kas jums patīk vislabāk vai kā vēlaties strādāt. Šādi attēli izskatīsies lieliski kā spēļu kursori vai vienkārši kā neparasts darbvirsmas elements. Būt spilgtam ir vienkārši - tam nav nepieciešams darīt neiedomājamas lietas vai mainīt savu izskatu. Pietiek tikai pārtraukt ikdienišķu objektu izmantošanu un izvēlēties to, kas jums patīk patiesi. Kursoru kolekcija "Automašīnas" ir izvēle tiem, kuri nebaidās sevi apliecināt.',
    'memy_descr' => 'Mēmas jau sen ir bijušas pazīstama mūsu dzīves sastāvdaļa. Un kuram no mums nepatīk šie ietilpīgie, interesantie un oriģinālie attēli, lai atspēkotu dienu? Daudzi mēmu varoņi ir kļuvuši ne tikai populāri - viņi ir ieguvuši populāru favorītu statusu, un frāzes un izteicieni jau sen ir iekļauti sarunvalodā kā iedibināti pavērsieni. Mēs piedāvājam labāko kursoru kolekciju, kas balstīta uz populārākajiem mēmiem. Ar to palīdzību jūs varat ne tikai parādīt savu personību, bet arī izteikt savu noskaņojumu. Vai jūs visi esat noguruši un apnicis viss? Izvēlieties dusmīgu kaķi, kurš ar visu savu izskatu pauž sašutumu un naidīgumu pret visu apkārtni. Vai arī jūs šodien mirdzat ar sarkasmu un nevēlaties smieties? Tad Drake Bling būs lielisks pavadījums - tas jūs uzmundrinās un padarīs jebkuru uzdevumu oriģinālu un interesantu. Instalējiet paplašinājumu, lejupielādējiet mūsu kolekciju - un izvēlieties kursoru stilu katrai dienai. Būt spilgtam un oriģinālam nav grūti - nomainiet standarta ikonas dizainu uz vienu no mēmu varoņiem un saņemiet enerģijas lādiņu visai dienai.',
    'emodji_descr' => 'Emocijas - spilgti, forši ikonas, bez kurām mēs vairs nevaram ierasti sazināties. Ar to palīdzību jums nav jāapraksta savs garastāvoklis vārdos - vienkārši izvēlieties vēlamo ikonu, un sarunu biedrs jūs sapratīs bez liekiem piepūliem. Mūsu jaunajā kursoru komplektā mēs iemiesojām emociju ideju - tieši tā parādījās smieklīgi un neparasti Kursoji, kas krāsos pasauli un padarīs dzīvi interesantāku. Ar kursu palīdzību jūs varat ne tikai strādāt un veikt pazīstamus uzdevumus, bet arī parādīt saviem kolēģiem, draugiem un vienkārši citiem savu garastāvokli. Miega kursors ir ideāli piemērots pirmdienas rītam, un raudošais kursors paudīs attieksmi pret papildu pienākumiem. Foršs kursors ar brillēm ir labākā izvēle pirms svētkiem, un kursors ar dolariem acīs ir labs iemesls, lai norādītu priekšniekam par algas paaugstināšanu. Kursoju izmantošana ir jautra un interesanta - vai tā būtu darbs, mācības vai prezentācija. Pēdējā gadījumā to pat iesaka darīt, ja kolēģiem ir humora izjūta vai vienkārši jāatrisina situācija. Kopumā jebkuram uzdevumam - vienkārši izvēlieties pareizo kursu!',
    'pitomcy_descr' => 'Vai tev patīk dzīvnieki? Protams - viņi ir tik mīļi, smieklīgi un ļoti jautri. Kāpēc gan nepavadīt visu dienu, ko pavada cilvēka labākie draugi? Lejupielādējiet sev mājdzīvnieku kursoru kolekciju un izvēlieties draugu sev katru dienu. Kursora ikona var būt mīļa, piemēram, labsirdīga alpaka, vai stilīga, piemēram, rozā flamingo. Vai varbūt jūs būsiet aizņemts visu dienu un izvēlēsieties vienradzi, kas lasa avīzi, vai vienkārši nevēlaties ar nevienu kontaktēties, kā ļauns melns kaķis? Jebkuram noskaņojumam mums ir atbilstošs dzīvnieks. Priecīgs pugs jūs uzmundrinās pat visgarlaicīgākajā un pelēkākajā dienā, un rozā kursoru vienradža formā parādīs visiem, ka jums nav atņemta skaistuma izjūta, pat esot brutālam bārdainam vīrietim. Ko darīt, ja nav noskaņojuma un man negribas darīt ikdienas darbus? Recepte ir vienkārša – lejupielādējiet Mājdzīvnieku kolekciju, mainiet peles kursoru – un voila, saule spīd atkal, laiks ir lielisks, un noskaņojums ir visaugstākajā līmenī. Nav brīnums, ka saka, ka dzīvnieki palīdz cīnīties ar depresiju un skumjām!',
    'stil_i_krasota_descr' => 'Jaunajā kursoru kolekcijā mēs esam apkopojuši plašu priekšmetu klāstu, kas rada mums patīkamas emocijas un pacilājošu noskaņojumu. Šis kursoru komplekts saucas “Stils un Skaistums”, jo tie ir tavi iecienītie lietas, kas nosaka mūsu ikdienas dzīvi, sniedz prieku un motivē mūs darīt svarīgas lietas, rosina vēlmi pēc pilnveidošanās. Vai Tev patīk kosmoss un sapņoji doties uz citām planētām? Izvēlies NASA kursoru vai citplanētiešu šķīvi - pietuvojies savam sapnim. Ja nevari iedomāties dzīvi bez mūzikas vai esi apsēsts rokeris, tad elektriskās ģitāras stila kursors ir domāts tieši Tev. Ota, lineāls un kompasa kursors ir īpaši izstrādāts inženieriem - šādi attēli palīdzēs pārvērst garlaicīgus aprēķinus un rasējumus oriģinālos risinājumos. Burvju nūjiņa un sporta apavi, skrituļdēlis un lūpu krāsa, saule un ķīmiskie konusi - izvēlies to, kas atbilst tavam dzīvesveidam, tavām vēlmēm un tieksmēm - un parastie uzdevumi kļūs interesantāki, un darba dienas tiks iekrāsotas jaunās, spilgtās krāsās.',
    'prazdniki_descr' => 'Vai patīk svētki? Bet kuram tie nepatīk - draugi, dāvanas, atkal tie paši brīvdienas. Lai gaidīšana svētkiem būtu patīkamāka, īsāka un siltāka, jūs varat ne tikai skaitīt dienas kalendārā, bet arī iestatīt atbilstošu ikonu kā peles kursoru. Sāksim ar Jauno gadu - izvēlēsimies egli, dāvanu vai Ziemassvētku vecīti, lai svētki būtu spilgti un jautri. Varbūt piparkūku vīriņš būs tuvāks - smieklīgs, jauks un vienmēr jestrs? Ar viņu noteikti nebūs laika būt skumjiem un garlaicīgiem. Turpinām svinēt ar kupidiem un jautrām sirdīm, un nav tālu līdz Lieldienu zaķim. Kaut kur starp svētkiem būs dzimšanas diena, kura būs vēl patīkamāk gaidīt ar baloniem standarta kursora bultiņas vietā. Un Helovīnā jūs varat pārsteigt kolēģus un apkārtējos ar neparastu peles kursoru draudīgā ķirbja vai spoka formā. Kursoru komplekts svētkiem ir iespēja atdzīvināt gaidīšanu, iepriekš noskaņoties gaidāmajiem jautrībām un uzturēt lielisku noskaņojumu ne tikai svētku priekšvakarā, bet visa gada garumā.',
    'flagi_descr' => 'Karogs ir unikāls simbols, ko plaši izmanto visos sociālajos tīklos. Mēs domājām, kāpēc gan nepadarīt kursoru par karogu? Galu galā tas ir patiešām spilgts un neparasts. Tagad jūs varat pavadīt katru dienu kompānijā ar jaunu valsti, un darbs nebūs tik vienmuļš un garlaicīgs. Pelēm paredzētos kursorus tagad var veidot kā Ķīnas vai ASV, Japānas vai Kanādas nacionālo karogu, un vēl 38 karogu variantos, un jūs varat izvēlēties vai nu standarta bultiņas formu neparastā krāsā, vai arī kursoru karoga formas veidā. Šis komplekts patiks visiem ceļojumu mīļotājiem. Ar to jūs varat plānot jaunas ekskursijas un sapņot par gariem ceļojumiem. Vai esat ieplānojis atvaļinājumu? Parādiet visiem, uz kuru valsti vēlaties doties. Varbūt jūs nolēmāt apgūt jaunu svešvalodu? Tad šis kursors noteikti jūs atbalstīs un motivēs rūpīgi mācīties. Vai varbūt jūs, tāpat kā Šeldons, vienkārši mīlat karogus? Visos gadījumos Flags kursora kolekcija būs lielisks papildinājums jūsu darbvirsmai un pārvietos jūs uz jauniem atklājumiem.',
    'vokrug_sveta_descr' => 'Visi mīl ceļot. Cik brīnišķīgi ir apmeklēt jaunas valstis un pilsētas, apskatīt apskates objektus un lieliski pavadīt laiku jaunā kultūrā. Žēl, ka nevaram ceļot tik bieži, bet mēs mēģinājām to novērst. Kursoru komplekts “Apkārt pasaulei” ir visspilgtāko attēlu, dažādu valstu simbolu kolekcija, ar kuru palīdzību pat mājās sēžot var justies kā īsts ceļotājs. Mūsu komplektā varat atrast Japānu un Austrāliju, Itāliju un Kanādu, ASV un Meksiku - interesantākās, oriģinālākās un gleznainākās valstis pasaulē. Kursoru attēls var kļūt par standarta bultiņu, valsts karoga krāsās, vai arī kļūt par vienu no galvenajiem valsts apskates objektiem. Piemēram, jūs varat atvērt dokumentus ar Pizas torni un veidot prezentācijas, izmantojot Brīvības statuju. Mēs garantējam - panākumi būs nodrošināti. Nu, vai ja ne panākumi, tad kolēģu smaids un oriģinalitātes atzīšana - noteikti. Jā, un mājieni vadībai, ka ir pienācis laiks doties atvaļinājumā, arī būs vērts - vienkārši iestatiet koferi vai lidmašīnu kā kursoru - un, visticamāk, jūs drīz lidosiet.',
    'eda_i_napitki_descr' => 'Kursoru komplekts produktu veidā ir neticama spilgtu, garšīgu un muti laistošu attēlu kolekcija, kas noteikti patiks ikvienam un būs lielisks papildinājums pārlūkam. Vai esat kādreiz noklikšķinājuši uz brokoļiem vai frī kartupeļiem? Jums ir šāda iespēja - vienkārši lejupielādējiet jaunu kursoru komplektu un iestatiet tos garlaicīgas baltas bultiņas vietā. Kursori "Ēdiens" ir veidoti gan standarta trīsstūra rādītāja formā, gan produktu formā. Šeit atradīsiet dārzeņus un augļus, savus iecienītākos ēdienus, piemēram, picu vai hotdogus, kafiju, ledenes un daudz ko citu, kas uzmundrina jebkuru dienu. Mīlat kafiju, bet vai to dzert visu dienu nav pārāk labi? Papildiniet savu diētu ar virtuālo kafiju, kas arī uzmundrinās un pamodinās jūs, kā arī sniegs spilgtas emocijas. Stāvs kursors virtuālā virtuļa formā nekaitēs figūrai, vienlaikus sniedzot spilgtas emocijas un uzmundrinājumu. Jūs varat izmantot savus iecienītākos kursorus vai mainīt attēlu katru dienu - liels kursoru daudzums palīdzēs krāsot ikdienas dzīvi un pievienot jaunas krāsas pazīstamām darbībām.',
    'cvetnye_descr' => 'Kursoris ir galvenais pārlūka elements, ar kuru mēs pavadām visu darba dienu, mācāmies, komunicējam un atpūšamies. Standarta kursora skats ir garlaicīgs un pat nedaudz nomācošs, taču daudziem šī forma ir ērta, un to mainīt būs neērti. Bet šai situācijai mums ir risinājums - spilgtu, priecīgu krāsu kursora komplekts, kas piešķirs daudzveidību jūsu ikdienas dzīvei un padarīs jebkuru problēmu risināšanu vieglāku un ātrāku. Ja domājat, kā nomainīt kursora krāsu, atbildam - lejupielādējiet mūsu kolekciju un izvēlieties spilgtus risinājumus katru dienu! Varat izvēlēties monohromus toņus dažādās krāsās, lai tie atbilstu noskaņojumam vai darba specifikai. Piemēram, strādājot ar standarta dokumentiem, purpursarkans kursoris izcelsies uz fona, un uz tumša fona, gluži pretēji, būs vieglāk strādāt ar dzelteniem kursorus. Ja vēlaties krāsu eksploziju, spilgtumu un maksimālu oriģinalitāti - izvēlieties varavīksnes kursoru, kas ietver visas spektra krāsas - ar šo ikonu noskaņojums noteikti būs lielisks visas dienas garumā.',
    'prank_descr' => 'Joki darbā ne vienmēr ir laipni gaidīti, jo tie bieži traucē darba plūsmu. Bet ar jauno “Joku” kursoru komplektu jūs varat laipni izjokot savus kolēģus vai draugus, nekaitējot savam darbam vai mācībām. Mēs esam izstrādājuši īpašu kolekciju, kas izklaidēs ikvienu un dos iemeslu nedaudz atpūsties rosīgajā darba vai cita uzdevuma veikšanas procesā. Lai mainītu peles kursoru, vienkārši lejupielādējiet komplektu ierīcē un izvēlieties vēlamo dizainu parametros. Piemēram, jūs varat iegūt standarta formas kursoru, bet apgrieztā stāvoklī vai bultiņu, kas izliekta ar vilni. Šī forma nekādā veidā netraucēs darba procesam, bet tajā pašā laikā prezentēs brīnišķīgu noskaņojumu un iestatīs jūs pozitīvā noskaņojumā. Mainiet kursora displeja iestatījumus atbilstoši savam noskaņojumam vai katru dienu - un jebkurš uzdevums kļūs interesantāks un patīkamāks, un ikdienas dzīve vairs neizraisīs negatīvas emocijas. Turklāt šādus kursorus var izmantot pat nopietniem projektiem - tiem ir neitrālas krāsas un tie neizceļas no darbvirsmas.',
    'startovyj_nabor_descr' => 'Kursoru no sākuma kolekcijas ir standarta formu un izmēru sajaukums ar spilgtu, neparastu izskatu. Šī ir lieliska izvēle tiem, kam patīk parastās formas, bet vēlas ienest daudzveidību, oriģinalitāti un spilgtumu ikdienā. Kolekcijā ir roku kursors un pazīstama bultiņa dažādās variācijās - no Google Chrome logotipa līdz emocijzīmēm, jūs pat varat satikt šeit sen aizmirstu pūķi ar kaktusiem un nostaļģiju. Mēs pierādām, ka standarta kursors var būt arī interesants un pievilcīgs. Dažādas krāsas, formas, faktūras un interesants dizains palīdzēs jums izvēlēties kursoru pēc savas gaumes vai mainīt to katru dienu atkarībā no noskaņojuma vai veicamajiem uzdevumiem. Mainīt pārlūkprogrammas kursorus ir ļoti vienkārši - vienkārši instalējiet paplašinājumu un lejupielādējiet kolekciju savā ierīcē. Smieklīgi, interesanti kursi ne tikai izkrāsos darba dienas, bet arī, piemēram, palīdzēs padarīt jebkuru prezentāciju interesantāku, un ar īpaši spilgtu kursoru palīdzību arī pievērst uzmanību atsevišķiem ziņojuma elementiem.',
    'fortnite_descr' => 'Fortnite ir iekarojis miljoniem cilvēku visā pasaulē. Aizraujošas cīņas, stratēģija un taktika, piedzīvojumi - tas ir absorbējis pilnīgi visu, kas spēlētājiem tik ļoti patīk. Mēs nevarējām palikt malā un izstrādājām kursoru komplektu spēles stilā, kas patiks ne tikai dedzīgiem spēlētājiem, bet pat tiem, kuri pirmo reizi dzirdējuši par Fortnite. Fortnite kursora ikona ir varoņa vai viņa ieroča attēls, kas ir izstrādāts līdz mazākajai detaļai. Šeit jūs varat atrast lapsu un zivju attēlus, inferno un melno bruņinieku maskas, iestatīt sev bultu vai sirpi ar smailiem kā bultu. Mēs esam pārliecināti, ka neviens nepaliks vienaldzīgs! Būt biedējošam vai noslēpumainam, oriģinālam vai humoristiskam - tas ir atkarīgs no jums. Izvēlieties savu stilu un sekojiet tam vai iestatiet pielāgotus kursorus iestatījumos un mainiet savu lomu katru dienu. Tagad pat garlaicīgs un vienmuļš darbs kļūs daudz interesantāks un patīkamāks - laiks paskries ātri kompānijā ar spilgtiem attēliem un iecienītiem varoņiem. Vai varbūt jūs sarīkosiet sacensības ar kolēģiem, kurš varonis būs spēcīgāks? Izvēle ir jūsu!',
    'dota_2_descr' => 'DotA2 tagad ir ne tikai vienkārša spēle, tā ir reāla paralēlā pasaule. Virtuālajā realitātē DotA2 var darīt visu - dzīvot, cīnīties, attīstīties, ceļot, iegūt draugus. Vispār, viss ir kā dzīvē, tikai reizēm interesantāk. Dota 2 kursori ir stratēģijas turpinājums, kas ļaus jums iegūt spilgtas emocijas un izpausties reālajā pasaulē. Jaunais kursoru komplekts ietver spilgtākos spēles varoņus, kā arī oriģinālus priekšmetus, kurus nevarēs sajaukt ar neko citu. Izvēlieties kursoru, kas būs tuvāks jums - un dodieties piedzīvojumā, neatstājot savu darba vietu. Cik garlaicīgi dažreiz ir būt darbā vai veikt izglītojošus uzdevumus, bet ar spēles kursoriem šī problēma vairs nesaskarsies ar jums. Nedaudz iztēles, spilgts kursors - un voila, jebkurš bizness būs neparasts piedzīvojums, ar kuru tikt galā nebūs grūti un interesanti. Nav jāierobežo sevi. Vai jums patīk Dota? Tad noteikti lejupielādējiet mūsu kolekciju, atlasiet vienu vai vairākus nejaušus kursorus uzreiz - un katra jaunā diena kļūs gaišāka, interesantāka un piesātinātāka.',
    'minecraft_descr' => 'Peles kursoru standarta bultu un pirkstu veidā ir kļuvuši garlaicīgi visiem. Ja jūs esat neparastā un oriģinālā cienītājs, tad ir pienācis laiks mainīt peles kursoru un piešķirt tam interesantāku dizainu. Mēs esam izstrādājuši kursoru kolekciju pasaulslavenās Minecraft spēles stilā, kurā jūs varat atrast vissavdabīgākos varoņus. Vilks un lapsa, Alekss un Krīpers, dimanta zobens un zivs - jūs varat izvēlēties to, kas jums patīk visvairāk, vai katru dienu instalēt jaunu varoni. Tie ir īsti kursi spēlētājiem, un tie patiks pilnīgi visiem - galu galā, kurš no mums nav spēlējis Minecraft? Mēs esam pārliecināti, ka tādu vienkārši nav. Nost ar garlaicīgo ikdienu - ir pienācis laiks ienirt piedzīvojumos, ko var izdarīt pat neizejot no mājām vai biroja krēsla. Būs interesantāk sagatavot atskaiti un samazināt atlikumu ar ieroci - jebkurš uzdevums kļūs patīkamāks un neļaus jums garlaikoties uz vietas. Lejupielādējiet jauno Minecraft kursoru kolekciju - iestatiet tos, un pat pelēkākajā un garlaicīgākajā dienā jūsu garastāvoklis vienmēr būs vislabākais. Un kolēģi apskaudīs jūsu rezultātus - vienkārši nav iespējams nedarīt savu darbu ar Minecraft drosmīgo varoņu palīdzību.',
    'astrology-signs-zodiac' => 'Zodiaka zīmes',
    'astrology-signs-zodiac_short_descr' => '12 astroloģisko zīmju komplekts, kas attēlo personības īpašības, kosmiskās enerģijas un dzīves modeļus.',
    'sports-cars' => 'Sporta automašīnas',
    'sports-cars_short_descr' => 'Spēcīgi un stilīgi auto, kas radīti ātrumam un veiklībai',
    'spider-man' => 'Zirnekļcilvēks',
    'spider-man_short_descr' => 'Varoņi no Zirnekļcilvēka visuma',
    'starwars' => 'Zvaigžņu Kari',
    'sports-cars_descr' => 'Sporta automašīnas ir augstas veiktspējas transportlīdzekļi, kas paredzēti straujai paātrināšanai, asai vadāmībai un aizraujošai braukšanas pieredzei. No gludiem kupejām līdz veiklām rodsterām, šajā kategorijā ir dažas no ikoniskākajām mašīnām, kas būvētas ceļa vai trases saviļņojumam. Ideāli piemērots entuziastiem, kuriem patīk ātrums, dizains un jauda. 🏎️🔥',
    'spider-man_descr' => 'Rakstzīmju un varoņu kolekcija no Zirnekļcilvēka Visuma. Ietver dažādas Zirnekļcilvēka versijas, sabiedrotos un unikālus stilus no komiksu grāmatām, spēlēm un animācijas seriāliem. Katrs dizains atspoguļo veiklību, drosmi un vizuālo identitāti, kas definē Zirnekļcilvēka pasauli.',
    'astrology-signs-zodiac_descr' => 'Zodiaka zīmes ♈♉♊♋♌♍♎♏♐♑♒♓ ir divpadsmit simboliski debesjuma joslas dalījumi, kurus izmanto astroloģijā. Katra zīme ir saistīta ar noteiktiem datumiem, elementiem (🌍 Zeme, 🔥 Uguns, 🌊 Ūdens, 💨 Gaiss), valdošajām planētām un unikālām personības īpašībām. Astrologi izmanto zodiaka zīmes, lai interpretētu uzvedību, paredzētu savietojamību un izpētītu dzīves ceļus. Neatkarīgi no tā, vai jūs esat kaislīgs Lauva 🔥 vai pārdomāts Zivs 🌊, jūsu zīme piedāvā ieskatu jūsu iekšējā pasaulē. Šajā kategorijā ietilpst visas 12 zīmes, to nozīmes un vizuālie attēlojumi.',
    'starwars_descr' => 'Ienirstiet galaktikā tālu, tālu prom ar šo kolekciju, kurā ir leģendāri varoņi, spēcīgi Sītu lordi, droīdi, dumpinieki un daudz kas cits. No Džedi bruņiniekiem līdz stormtrooperiem, katra ikona atdzīvina Zvaigžņu karu garu kursoru veidā. Ideāli piemērots visu triloģiju faniem. 🌌',
    'starwars_short_descr' => 'Varoņi un simboli no Star Wars universa',
    'glitter' => 'Spīdumi',
    'glitter_short_descr' => 'Spīdīgi un mirdzoši kursori ar spīdumu stilu ✨🌟',
    'roblox-2025' => 'Roblox 2025',
    'roblox-2025_short_descr' => 'Tēli no jaunākā Roblox viļņa 🕹️🚀',
    'glitter_descr' => 'Glamūrīga kursoru kolekcija, kuras iedvesmojusi mirdzoša tekstūra un spīdošs vizuālais izskats. Lieliski piemērots tiem, kam patīk dzirkstošs estētisms uz sava ekrāna. Šie kursori katrā klikšķī ienes mirdzumu, eleganci un mazliet maģijas.',
    'roblox-2025_descr' => 'Pavisam jauna 2025 kolekcija ar ikoniskiem un moderniem Roblox varoņiem. Ietver klasiskos noobus, šausmu leģendas un fanu iecienītus avatarus no populārām spēlēm. Dizains ir jautrs un krāsains stils, kas ir lieliski piemērots bērniem un visu vecumu Roblox faniem.',
];
