<?php

return [
    'title' => 'Cursor Style - Mūsu produkta lietošanas noteikumi',
    'descr' => 'Lietošanas noteikumi ir noslēgti starp jums un “Cursor Style” (“Pakalpojums”, “mēs” vai “Pakalpojums”). Šis pakalpojums tiek piedāvāts un ir pieejams tikai lietotājiem, kas ir 13 gadus veci un vecāki, tikai personīgai lietošanai un nevis komerciālai lietošanai.',
    'text' => '<h2> Pakalpojuma noteikumi </h2>
<h3> LŪDZU, IZLASIET ŠOS NOTEIKUMUS UN NOSACĪJUMUS PIRMS TĪMEKĻA VIETNES UN PAPLAŠINĀJUMA LIETOŠANAS. </h3>
<p> Šie lietošanas noteikumi ir noslēgti starp jums un "Cursor Style" ("Pakalpojums", "mēs" vai "Pakalpojums"). Turpmākie noteikumi un nosacījumi kopā ar visiem dokumentiem, uz kuriem tie tieši atsaucas (kopā saukti par “Lietošanas noteikumiem”), regulē jūsu piekļuvi un šīs vietnes un pārlūka paplašinājumu izmantošanu, tostarp jebkuru saturu, funkcionalitāti un pakalpojumus, kas tiek piedāvāti šajā vai caur mūsu pakalpojumu (kopā “Pakalpojums”). </p>
<p> Lietojot vietni vai paplašinājumu, jūs piekrītat un piekrītat ievērot šos Lietošanas noteikumus. Ja nepiekrītat šiem lietošanas noteikumiem vai mūsu <a href="/privacy"> Privātuma politikai </a>, jums nevajadzētu piekļūt vai izmantot vietni un paplašinājumu. </p>
<p> Šis pakalpojums tiek piedāvāts un ir pieejams tikai lietotājiem vecumā no 13 gadiem personīgai lietošanai, nevis komerciālai lietošanai. Izmantojot šo Pakalpojumu, jūs apliecināt un garantējat, ka esat (I) 13 gadus vai vecāks, (II) jums nav aizliegts izmantot vietnes saskaņā ar piemērojamo likumu, un (III) jūs izmantojat Pakalpojumu tikai personiskajām vajadzībām. Ja neatbilstat šīm prasībām, jums nevajadzētu piekļūt vai izmantot Pakalpojumu. </p>
<p> Mēs varam laiku pa laikam pārskatīt un atjaunināt šos Lietošanas noteikumus pēc saviem ieskatiem. Visas izmaiņas stājas spēkā nekavējoties pēc to publicēšanas. Jūsu turpmākā Pakalpojuma izmantošana pēc pārskatīto Lietošanas noteikumu publicēšanas nozīmē, ka jūs piekrītat izmaiņām un piekrītat tām. Jums ir paredzēts bieži apmeklēt šo lapu, lai uzzinātu par visām izmaiņām, jo tās ir jums saistošas. </p>
<p> Mēs paturam tiesības pēc saviem ieskatiem bez iepriekšēja brīdinājuma atsaukt vai grozīt šo vietni un paplašinājumu, visus pakalpojumus vai materiālus, ko mēs piedāvājam vietnē un paplašinājumā. Mēs negarantējam, ka mūsu vietne, paplašinājums vai jebkurš tajā esošais saturs vienmēr būs pieejami vai tiks pārtraukti. Mēs nebūsim atbildīgi, ja jebkāda iemesla dēļ viss vai jebkura daļa no Pakalpojuma nebūs pieejama jebkurā laikā vai jebkurā periodā. Laiku pa laikam mēs varam ierobežot piekļuvi noteiktām vietnes vai paplašinājuma daļām vai visam Pakalpojumam lietotājiem. </p>
<p> Jūs esat atbildīgs par visu nepieciešamo pasākumu veikšanu, lai nodrošinātu piekļuvi Pakalpojumam. Nodrošinot, lai visas personas, kuras piekļūst Pakalpojumam, izmantojot jūsu interneta savienojumu, zina par šiem Lietošanas noteikumiem un tos ievēro. Lai piekļūtu Pakalpojumam vai dažiem tā piedāvātajiem resursiem, jums var būt jāsniedz noteikta informācija vai cita informācija. Jūs piekrītat, ka visu informāciju, ko jūs mums iesniedzat, izmantojot šo Pakalpojumu vai citādi, tostarp, bet neaprobežojoties ar jebkuru interaktīvo funkciju izmantošanu Pakalpojumā, regulē mūsu <a href="/privacy"> Privātuma politika </a>, un jūs piekrītat visām darbībām, kuras mēs veicam attiecībā uz jūsu informāciju. saskaņā ar mūsu <a href="/privacy"> Privātuma politiku </a>. </p>
<p> Jums jābūt īpaši uzmanīgam, ievadot personisko informāciju Pakalpojumā publiskā vai koplietotā datorā, lai citi nevarētu skatīt vai ierakstīt jūsu personisko informāciju. Vietne, paplašinājums un viss tā saturs, funkcijas un funkcijas (tostarp, bet neaprobežojoties ar visu informāciju, paplašinājumu, tekstu, attēliem, attēliem un kursoru, kā arī to dizainu, atlasi un izvietojumu) pieder "Cursor Style", tā licences devējiem vai citiem šādu materiālu piegādātājiem, ir aizsargāti ar autortiesībām, preču zīmēm, patentes, tirdzniecības noslēpumiem un citiem intelektuālā īpašuma likumiem vai īpašuma tiesībām. </p>
<p> Šie Lietošanas noteikumi ļauj jums izmantot vietnes tikai personiskai, nekomerciālai lietošanai. Jūs nedrīkstat reproducēt, izplatīt, modificēt, veidot atvasinātus darbus, atkārtoti publicēt, lejupielādēt, glabāt vai pārsūtīt materiālus mūsu vietnē, izņemot šādus gadījumus: jūs varat to izmantot personiskām vajadzībām, jūs varat izdrukāt vai lejupielādēt vienu saprātīgu daudzumu vietnes un paplašinājuma lapu vai to saturu personiskai, nekomerciālai lietošanai un nevis turpmākai reproducēšanai, publicēšanai vai izplatīšanai. </p>
<p> Jūs nedrīkstat mainīt nevienu materiālu kopiju no šīs vietnes vai paplašinājuma un to saturu. Dzēst vai mainīt jebkuru autortiesību, preču zīmju vai citu patentētu paziņojumu no šīs vietnes un paplašinājuma kopijām. Jums nedrīkst būt piekļuve vai izmantošana jebkādiem komerciāliem nolūkiem nevienai vietņu vai paplašinājumu daļai, kā arī jebkādiem pakalpojumiem vai materiāliem, kas pieejami, izmantojot vietni vai paplašinājumu. </p>
<p> Ja vēlaties izmantot jebkuru materiālu vietnēs vai paplašinājumos, kas nav norādīti šajā sadaļā, nosūtiet pieprasījumu Chrome Web Store atbalsta lapā. </p>
<p> Ja izdrukājat, kopējat, modificējat, lejupielādējat vai citādi izmantojat vai nodrošināt jebkurai citai personai piekļuvi jebkurai vietnes vai paplašinājuma daļai, pārkāpjot Lietošanas noteikumus, jūsu tiesības izmantot vietni un paplašinājumu nekavējoties tiek pārtrauktas, un jums ir pienākums pēc mūsu ieskatiem atgriezt vai iznīcināt jebkuras materiālu kopijas, kas jums ir. Jebkura paplašinājuma vietnes izmantošana, kas nav nepārprotami atļauta ar šiem Lietošanas noteikumiem, pārkāpj šos Lietošanas noteikumus un var pārkāpt autortiesības, preču zīmes un citus likumus. </p>
<p> Nosaukums “Cursor Style”, logotips “Cursor Style” un visi saistītie nosaukumi, logotipi, attēli, kursori un pakalpojuma nosaukumi, dizaini un saukļi ir “Cursor Style” vai tā filiāļu vai licences devēju preču zīmes. Jūs nedrīkstat izmantot šādas zīmes bez iepriekšējas rakstiskas Pakalpojuma atļaujas. Visi citi nosaukumi, logotipi, produktu un pakalpojumu nosaukumi, dizaini un saukļi šajā vietnē un paplašinājumā ir to attiecīgo īpašnieku preču zīmes. Jūs varat izmantot Pakalpojumu tikai likumīgiem mērķiem un saskaņā ar šiem Lietošanas noteikumiem. </p>
<h3> Jūs piekrītat NEIZMANTOT Pakalpojumu: </h3>
<ul>
<li> Jebkādā veidā, kas pārkāpj jebkādus piemērojamos federālos, reģionālos, vietējos vai starptautiskos likumus vai noteikumus (tostarp, bet neaprobežojoties ar jebkuriem likumiem par datu vai programmatūras eksportu uz Krieviju un citām valstīm). </li>
<li> Izmantošanas, kaitējuma vai mēģinājumiem izmantot vai kaitēt nepilngadīgajiem, pakļaujot viņus nepiemērotam saturam, pieprasot informāciju, kas viņus identificē, vai citādi. </li>
<li> Nosūtīt, apzināti saņemt, lejupielādēt, izmantot vai atkārtoti izmantot materiālus, kas neatbilst šiem Lietošanas noteikumiem. </li>
<li> Pārsūtīt vai iegādāties jebkādu reklāmas vai reklāmas materiālu nosūtīšanu bez mūsu iepriekšējas rakstiskas piekrišanas, ieskaitot jebkuras “nelaipnas vēstules”, “ķēdes vēstules” vai “spam” vai citus līdzīgus piedāvājumus. </li>
<li> Lai imitētu vai mēģinātu imitēt “Cursor Style” darbinieku, citu lietotāju vai jebkuru citu personu vai organizāciju (tostarp, bet neaprobežojoties ar e-pasta adrešu vai iesauku izmantošanu, kas saistītas ar jebkuru no iepriekšminētajiem). </li>
<li> Piedalīšanās jebkurās citās darbībās, kas ierobežo vai kavē Pakalpojuma vai neviena izmantošanu vai kuras, kā mēs nosakām, var kaitēt Pakalpojumam vai Pakalpojuma lietotājiem vai padarīt tos atbildīgus. </li> </ul>
<h3> Turklāt jūs piekrītat NE: </h3>
<ul>
<li> Izmantot Pakalpojumu jebkādā veidā, kas var atspējot, pārslogot, sabojāt vai degradēt vietnes darbību, paplašināt vai traucēt jebkuras citas puses Pakalpojuma izmantošanu, ieskaitot viņu spēju piedalīties reāllaika darbībās, izmantojot Pakalpojumu. </li>
<li> Izmantot jebkādus automatizācijas rīkus, procesu vai līdzekļus, lai piekļūtu Pakalpojumam jebkādiem mērķiem, ieskaitot jebkura materiāla uzraudzību vai kopēšanu Pakalpojumā. </li>
<li> Izmantot jebkuru manuālu procesu, lai izsekotu vai kopētu jebkuru materiālu Pakalpojumā vai citiem neatļautiem mērķiem bez mūsu iepriekšējas rakstiskas piekrišanas. </li>
<li> Izmantot jebkuru ierīci, programmatūru vai procedūras, kas traucē normālai Pakalpojuma darbībai. </li>
<li> Ieviest vīrusus, Trojas zirgus, tārpus, loģiskās bumbas vai citus materiālus, kas ir kaitīgi vai tehnoloģiski kaitīgi. </li>
<li> Mēģināt iegūt nesankcionētu piekļuvi, traucēt, sabojāt vai pārtraukt jebkuru Pakalpojuma daļu, serveri, kurā tiek glabāts Pakalpojums, vai jebkuru serveri, datoru vai datu bāzi, kas ir savienota ar Pakalpojumu. </li>
<li> Uzbrukt pakalpojumam, izmantojot pakalpojuma atteikuma uzbrukumu vai izplatītu pakalpojuma atteikuma uzbrukumu. </li> </ul>
<p> Informācija, kas sniegta pakalpojumā vai caur to, tiek sniegta tikai vispārīgai informatīvai nolūkam. Mēs negarantējam šīs informācijas precizitāti, pilnīgumu vai lietderību. Jūs paļaujaties uz šādu informāciju tikai uz savu risku. Mēs atsakāmies no visas atbildības un saistībām, kas rodas no jūsu atkarības no šādiem materiāliem, citiem Pakalpojuma apmeklētājiem vai jebkura, kas var būt informēts par jebkuru to saturu. </p>
<p> Šis pakalpojums ietver saturu, ko nodrošina trešās puses, ieskaitot materiālus, ko nodrošina citi lietotāji un trešo pušu licences devēji, sindikatori, agregātori un / vai ziņošanas pakalpojumi. Visi paziņojumi un / vai atzinumi, kas izteikti šajos materiālos, kā arī visi raksti un atbildes uz jautājumiem un cits saturs, izņemot Pakalpojuma nodrošināto saturu, ir tikai šo materiālu sniedzējas personas vai organizācijas viedokļi un atbildības. Šie materiāli ne vienmēr atspoguļo Pakalpojuma viedokļus. Mēs neesam atbildīgi jums vai jebkurai trešai personai par jebkura trešo personu sniegto materiālu saturu vai precizitāti. </p>
<p> Mēs varam laiku pa laikam atjaunināt Pakalpojuma saturu, bet tā saturs ne vienmēr ir pilnīgs vai aktuāls. Jebkurš materiāls Pakalpojumā jebkurā laikā var būt novecojis, un mums nav pienākums atjaunināt šādu materiālu. Mēs varam atjaunināt, modificēt, mainīt informāciju un saturu vietnē un paplašinājumā, veikt jebkuras izmaiņas un atjauninājumus pēc saviem ieskatiem. </p>
<p> Visa informācija, ko mēs apkopojam par šo pakalpojumu, ir pakļauta mūsu Privātuma politikai. Izmantojot Pakalpojumu, jūs piekrītat visām mūsu veiktajām darbībām attiecībā uz jūsu informāciju saskaņā ar <a href="/privacy"> Privātuma politiku </a>. </p>
<p> Papildu noteikumi var attiekties arī uz noteiktām Pakalpojuma daļām, pakalpojumiem vai funkcijām. Visi šādi papildu noteikumi un nosacījumi ar šo atsauci ir iekļauti šajos Lietošanas noteikumos.
Jūs varat izveidot saiti uz mūsu vietni vai paplašinājumu, ja to darāt godīgā un likumīgā veidā un nekaitējat mūsu reputācijai vai neizmantosiet to, bet jums nevajadzētu iestatīt saiti tā, lai piedāvātu jebkādu asociācijas, apstiprinājuma vai apstiprinājuma veidu no mūsu puses bez mūsu rakstiskas piekrišanas. </p>
<p> Pakalpojumā ir saites uz citām vietnēm un resursiem, ko nodrošina trešās puses, šīs saites ir paredzētas tikai jūsu ērtībai. Tas ietver saites, kas ietvertas reklāmās, ieskaitot reklāmkarogu reklāmas un sponsorētās saites. Mēs nekontrolējam šo vietņu vai resursu saturu un neesam atbildīgi par tiem vai par jebkādiem zaudējumiem vai bojājumiem, kas var rasties to izmantošanas rezultātā. Ja jūs nolemjat piekļūt jebkurām trešo pušu vietnēm, kas saistītas ar šo Pakalpojumu, jūs to darāt uz savu risku un saskaņā ar šādu vietņu lietošanas noteikumiem. Mēs paturam tiesības atsaukt atļauju saitei bez iepriekšēja brīdinājuma. </p>
<p> Jūs saprotat, ka mēs nevaram un negarantējam, ka faili, kas pieejami lejupielādei caur internetu vai vietnēs, nesaturēs vīrusus vai citu ļaunprātīgu kodu. Jūs esat atbildīgs par procedūru un kontroles punktu ieviešanu, kas ir pietiekami, lai apmierinātu jūsu īpašās prasības pretvīrusu aizsardzībai un datu ievades un izvades precizitātei, kā arī ārēju līdzekļu uzturēšanai mūsu vietnei, lai atjaunotu visus zaudētos datus. MĒS NEESAM ATBILDĪGI PAR NEKĀDIEM BOJĀJUMIEM VAI TRAUMĀM, KO IZRAISĪJIS PAKALPOJUMA ATTEIKUMA UZBRUKUMS, VĪRUSI VAI CITA SLĖDPRĀTĪGA TEHNOLOĢIJA, KAS IR IERĪKOTA CAUR PAKALPOJUMU, VAI IZMANTOJOT JEBKĀDA MATERIĀLA LEJUPIELĀDĒŠANU, KAS IR IESNIEGTS ŠAJĀ VAI JEBKURĀM TĪMEKĻA VIETNĒM, KAS VAR SASTĀDĪT VAI BOJĀT JŪSU DATORU IEKĀRTAS, DATORPROGRAMMATŪRU, DATU. </p>
<p>  JŪS IZMANTOJIET PAKALPOJUMU, TĀ SATURU UN JEBKĀDUS PAKALPOJUMUS VAI PRECES, KAS IEGŪTAS, IZMANTOJOT PAKALPOJUMUS, TIKAI UZ SAVU RISKU. PAKALPOJUMS, TĀ SATURS UN JEBKĀDI PAKALPOJUMI VAI PRECES, KAS IEGŪTI, IZMANTOJOT VIETNI UN PAPLAŠINĀJUMU, TIEK SNIEGTI “TĀDI, KĀDI IR” UN “KĀ PIEEJAMI” NOTEIKUMIEM UN NOSACĪJUMIEM, BEZ JEBKĀDAS GARANTIJAS. JEBKURA PERSONA, KAS SAISTĪTA AR PAKALPOJUMU, NESNIEDZ NEKĀDU GARANTIJU VAI APLIECINĀJUMU ATTIECĪBĀ UZ PAKALPOJUMA PILNĪGUMU, DROŠĪBU, UZTICAMĪBU, KVALITĀTI, PRECIZITĀTI VAI PIEEJAMĪBU. BEZ IEROBEŽOJUMIEM, NE “CURSOR STYLE” NE ARĪ AR “CURSOR STYLE” SAISTĪTIE PĀRSTĀVJI NEGĀRANTĒ, KA VIETNĒ, PAPLAŠINĀJUMAM, TĀ SATURAM VAI JEBKURAI REMONTAM, KA IR JĀBŪT IEPRIEKŠ PIEEJAMIEM, IR ATJAUNOTI, KA MŪSU PAPLAŠINĀJUMS, VIETNE VAI SERVERIS, KAS TO IEVIEŠ, BŪS BEZ VĪRUSIEM VAI CITIEM KAITĪGIEM KOMPONENTIEM VAI ŠĪ TĪMEKĻA VIETNIS VAI JEBKURŠ PAKALPOJUMS VAI PRECES TIEK VEIKTAS, IEKĻAUJOT. </p>
<p>  NEKĀDOS APSTĀKĻOS PAKALPOJUMS, TĀ SAISTĪTIE UZŅĒMUMI VAI LICENCES DEVĒJI, PAKALPOJUMI, DARBINIEKI, AĢENTI, AMATPERSONAS VAI DIREKTORI NEBŪS ATBILDĪGI PAR JEBKĀDA VEIDA KAITĒJUMIEM, KO MĒS VARAM PAKALPOJUMAM, NEKĀDA ATBILDĪBA. VAI TĀS VAI CITAS TĪMEKĻA VIETNES VAI JEBKURUS PAKALPOJUMUS VAI PRECES, KAS IEGŪTAS PAKALPOJUMĀ VAI CITĀS TĪMEKĻA VIETNĒS, T.SK. JEBKĀDUS TIEŠUS, ĪPAŠUS VAI IZRIETOŠOS KAITĒJUMUS, IESKAITOT PERSONISKUS KAITĒJUMUS, EMOCIONĀLOS TRUCINĀJUMUS, ZAUDĒJUMUS VAI PLĀNOTOS IETAUPĪJUMUS, LIETOŠANAS ZAUDĒJUMUS, DATUS VAI CITUS APSTĀKŠUS. DEFINĪCIJA NEATTIECAS UZ NEKĀDU ATBILDĪBU, KAD NEVARĒTU IZSLĒGT VAI IEROBEŽOT SASKAŅĀ AR PIEMĒROJAMU LIKUMU, KAS VAR IETVERT KRĀPŠANU. </p>
<p> Jūs piekrītat aizsargāt, atbrīvot un atbrīvot “Cursor Style”, tā filiāles, licences devējus un pakalpojumu sniedzējus, kā arī tā un to attiecīgos darbiniekus, direktorus, darbiniekus, darbuzņēmējus, aģentus, licences devējus, piegādātājus, cedentus un no jebkādām prasībām un saistībām, tiesas spriedumiem par zaudējumiem, izmaksām, izdevumiem vai komisijām (tostarp advokāta honorāriem), kas rodas vai ir saistītas ar jūsu šo Lietošanas noteikumu vai Pakalpojuma izmantošanas pārkāpumu, tostarp, bet neaprobežojoties ar jebkādu vietnes satura, pakalpojumu un produktu atkārtotu iegādi vai paplašinājumiem, izņemot gadījumus, kas skaidri paredzēti šajos Lietošanas noteikumos, vai jūsu izmantošanu jebkuras informācijas, kas tiek saņemta no Pakalpojuma. </p>
<p> Ja tiesa vai cita kompetenta jurisdikcijas tiesa jebkāda iemesla dēļ atzīst par spēkā neesošu, nelikumīgu vai neizpildāmu jebkuru šo Lietošanas noteikumu noteikumu, šis noteikums jāatceļ vai jāierobežo līdz minimumam, lai pārējie Lietošanas noteikumu noteikumi turpinātos pēc pilniem. Lietošanas noteikumi, mūsu Privātuma politika un nosacījumi par pasākumu reģistrāciju ir vienīgais un pilnīgs līgums starp jums un "Cursor Style" attiecībā uz Pakalpojumu un aizstāj visus iepriekšējos un vienlaicīgos līgumus, līgumus, apliecinājumus un garantijas, gan rakstiskas, gan mutiskas, attiecībā uz Pakalpojumu . </p>
<p> Visi pārskati, komentāri, tehniskā atbalsta pieprasījumi un citi ziņojumi par Pakalpojumu jāadresē "Cursor Style" atbalsta lapā Chrome Web Store. </p> ',
];
