<?php

return[
    'title' => 'Сursor Style - Terms of use of our product',
    'descr' => 'Terms of use are entered between you and “Cursor Style” (“Service”, “we” or “Service”). This service is offered and available to users aged 13 years and older only for personal use and not for commercial use.',
    'text' => '<h2> Terms of Service </h2>
<h3> PLEASE READ THESE TERMS AND CONDITIONS BEFORE USING THE WEBSITE AND EXTENSION. </h3>
<p> These terms of use are entered between you and "Cursor Style" ("Service", "we" or "Service"). The following terms and conditions, together with any documents that they expressly include by reference (collectively, these "Terms of Use"), govern your access and use of the cursor.style website and its browser extensions, including any content, functionality and services offered on or through our service (together the “Service”). </p>
<p> By using the website or extension, you accept and agree to abide by these Terms of Use. If you do not agree to these Terms of Use or our <a href="/privacy"> Privacy Policy </a>, you should not access or use the Website and the Extension. </p>
<p> This service is offered and available to users aged 13 years and older only for personal use and not for commercial use. Using this Service, you represent and warrant that you are (I) 13 years old or older, (II) you are not prohibited from using the Websites in accordance with applicable law, and (III) you use the Service only for your personal needs. If you do not meet these requirements, you should not access or use the Service. </p>
<p> We may revise and update these Terms of Use from time to time at our discretion. All changes take effect immediately after their publication. Your continued use of the Service after the publication of the revised Terms of Use means that you accept and agree to the changes. You are expected to visit this page frequently to keep abreast of any changes as they are binding on you. </p>
<p> We reserve the right to withdraw or amend this Website and the Extension, any services or materials that we provide on the Website and the Extension, at our sole discretion, without notice. We do not guarantee that our site, extension or any content on it will always be available or will be interrupted. We will not be liable if for any reason all or any part of the Service is unavailable at any time or during any period. From time to time, we may restrict access to certain parts of the Website or the Extension or the entire Service for users. </p>
<p> You are responsible for taking all necessary measures to ensure that you have access to the Service. Ensuring that all persons who access the Service through your Internet connection are aware of these Terms of Use and comply with them. In order to access the Service or some of the resources it offers, you may be asked to provide certain information or other information. You agree that all information that you provide to us using this Service or otherwise, including but not limited to the use of any interactive features in the Service, is governed by our <a href="/privacy"> Privacy Policy </a> , and you agree to all actions that we take regarding your information. in accordance with our <a href="/privacy"> Privacy Policy </a>. </p>
<p> You must be especially careful when entering personal information into the Service on a public or shared computer so that others cannot view or record your personal information. The website, the extension and all its contents, functions and features (including, but not limited to, all information, the extension, text, images, images, images and cursors, as well as their design, selection and placement) belong to the "Cursor Style", its licensors or other suppliers of such materials are protected by copyright, trademark, patent, trade secret and other intellectual property laws or property rights. </p>
<p> These Terms of Use allow you to use the Websites only for your personal, non-commercial use. You must not reproduce, distribute, modify, create derivative works, republish, download, store or transmit any materials on our Website, except for the following cases: you can use it for personal needs, you can print or download one copy of a reasonable amount pages of the Website and the Extension or their contents for personal, non-commercial use, and not for further reproduction, publication or distribution. </p>
<p> You must not modify copies of any materials from this site or extension and their contents. Delete or modify any copyright, trademark, or other proprietary notices from copies of this site and the extension. You must not have access to or use for any commercial purpose any part of the Websites or extensions, as well as any services or materials available through the Website or the Extension. </p>
<p> If you want to use any material on Websites or Extensions other than those listed in this section, send a request on the support page of the Chrome Web Store. </p>
<p> If you print, copy, modify, download, or otherwise use or provide any other person access to any part of the Website or the Extension in violation of the Terms of Use, your right to use the Website and the Extension immediately terminates, and you must , at our discretion, return or destroy any copies of the materials that you have. Any use of the extension’s website that is not expressly permitted by these Terms of Use is in violation of these Terms of Use and may violate copyrights, trademarks and other laws. </p>
<p> The name “Cursor Style”, the logo “Cursor Style” and all associated names, logos, images, cursors and service names, designs and slogans are trademarks of “Cursor Style” or its affiliates or licensors. You must not use such marks without the prior written permission of the Service. All other names, logos, product and service names, designs and slogans on this website and in the extension are trademarks of their respective owners. You may use the Service only for legitimate purposes and in accordance with these Terms of Use. </p>
<h3> You agree NOT to use the Service: </h3>
<ul>
<li> In any way that violates any applicable federal, regional, local or international laws or regulations (including, but not limited to, any laws regarding the export of data or software to Russia and other countries). </li>
<li> For the purpose of exploitation, harm, or attempts to use or harm minors, exposing them to inappropriate content, requesting information that identifies them, or otherwise. </li>
<li> To send, knowingly receive, download, use or reuse any materials that do not comply with these Terms of Use. </li>
<li> Transmit or purchase the sending of any advertisements or promotional materials without our prior written consent, including any "unsolicited letters", "chain letters" or "spam" or any other similar offers. </li>
<li> In order to impersonate or attempt to impersonate a “Cursor Style” an employee, another user, or any other person or organization (including but not limited to using email addresses or aliases associated with any of the above). </ li >
<li> Participation in any other actions that limit or impede the use of the Service or the use of anyone, or which, as we determine, may harm the Service or the users of the Service or make them liable. </li> </ul>
<h3> In addition, you agree NOT: </h3>
<ul>
<li> Use the Service in any way that can disable, overload, damage or degrade the operation of the site, expand or interfere with the use of the Service by any other party, including their ability to participate in real-time actions through the Service. </li>
<li> Use any automation tools, process or means to access the Service for any purpose, including monitoring or copying any material in the Service. </li>
<li> Use any manual process to track or copy any material on the Service or for any other unauthorized purposes without our prior written consent. </li>
<li> Use any device, software or procedures that interfere with the normal operation of the Service. </li>
<li> Introduce any viruses, trojan horses, worms, logic bombs or other materials that are harmful or technologically harmful. </li>
<li> Try to gain unauthorized access, interfere, damage or disrupt any part of the Service, the server on which the Service is stored, or any server, computer or database connected to the Service. </li>
<li> Attack a Service using a denial of service attack or a distributed denial of service attack. </li> </ul>
<p> Information provided on or through the Service is provided solely for general informational purposes. We do not guarantee the accuracy, completeness or usefulness of this information. You rely on such information solely at your own risk. We disclaim all responsibility and liability arising from any dependence on such materials by you, any other visitors to the Service or anyone who may be informed of any of their contents. </p>
<p> This Service includes content provided by third parties, including materials provided by other users and third-party licensors, syndicators, aggregators and / or reporting services. All statements and / or opinions expressed in these materials, as well as all articles and answers to questions and other content, except for the content provided by the Service, are solely the opinions and responsibilities of the person or organization providing these materials. These materials do not necessarily reflect the views of the Service. We are not liable to you or any third party for the content or accuracy of any materials provided by third parties. </p>
<p> We may update the content of the Service from time to time, but its content is not necessarily complete or current. Any material on the Service may be out of date at any time, and we are not required to update such material. We can update, modify, modify information and content on the Website and in the Extension, make any changes and updates according to our own decision. </p>
<p> All information that we collect on this Service is subject to our Privacy Policy. By using the Service, you agree to all actions taken by us in relation to your information in accordance with the <a href="/privacy"> Privacy Policy </a>. </p>
<p> Additional terms may also apply to certain parts, services or features of the Service. All such additional terms and conditions are hereby incorporated by reference into these Terms of Use.
You can link to our website or extension if you do so in an honest and lawful way and do not damage our reputation or use it, but you should not set the link in such a way as to offer any form of association, endorsement or endorsement on our part without our written consent. </p>
<p> The service contains links to other sites and resources provided by third parties, these links are provided only for your convenience. This includes links contained in advertisements, including banner ads and sponsored links. We do not control the content of these sites or resources and are not responsible for them or for any loss or damage that may result from their use. If you decide to access any third-party websites associated with this Service, you do so at your own risk and in accordance with the terms of use of such websites. We reserve the right to revoke permission to link without prior notice. </p>
<p> You understand that we cannot and do not guarantee or guarantee that the files available for download via the Internet or on Websites will not contain viruses or other malicious code. You are responsible for the implementation of procedures and control points sufficient to satisfy your special requirements for anti-virus protection and the accuracy of data input and output, as well as for maintaining means external to our site for recovering any lost data. WE WILL NOT BE LIABLE FOR ANY DAMAGES OR INJURY CAUSED distributed denial SERVICE, viruses or other technology-malware OBTAINED THROUGH THE SERVICE, OR BY DOWNLOADING OF ANY MATERIAL POSTED ON THIS, OR ANY WEB SITES, RELATED TO MAY INFECT OR DAMAGE YOUR COMPUTER EQUIPMENT, COMPUTER SOFTWARE, DATA. </p>
<p> YOU USE THE SERVICE, ITS CONTENT AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE SERVICES AT YOUR SOLE RISK. THE SERVICE, ITS CONTENTS AND ANY SERVICES OR ITEMS OBTAINED THROUGH THE WEBSITE AND EXTENSION, ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” TERMS AND CONDITIONS, WITHOUT ANY WARRANTY. ANY PERSON ASSOCIATED WITH THE SERVICE DOES NOT PROVIDE ANY WARRANTY OR REPRESENTATION WITH RESPECT TO COMPLETENESS, SAFETY, RELIABILITY, QUALITY, ACCURACY OR ACCESSIBILITY OF THE SERVICE. WITHOUT LIMITATION ABOVE, NO “CURSOR STYLE” NOR RELATED TO A “CURSOR STYLE” REPRESENTATIVES DOES NOT WARRANT THAT THE SITE, THE EXTENSION, ITS CONTENT OR ANY REPAIR SHOULD BE PREVIOUSLY AVAILABLE FIXED THAT OUR EXTENSION, A SITE OR A SERVER WHICH PLACES IT, WILL BE WITHOUT VIRUSES OR OTHER HARMFUL COMPONENTS OR THIS WEB SITE OR ANY SERVICES OR ITEMS PERFORMED, PREFERENCED.
<p> Under no circumstances shall the SERVICE, ITS AFFILIATES OR OR LICENSORS, SERVICES, EMPLOYEES, AGENTS, OFFICIALS or DIRECTORS BE RESPONSIBLE FOR DAMAGES OF ANY KIND, WE SERVICE TO ANY LIABILITY. OR SUCH OTHER WEBSITES OR ANY SERVICES OR ITEMS OBTAINED IN THE SERVICE OR TO OTHER WEB sITES, INCLUDING ANY DIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES, INCLUDING PERSONAL INJURY, emotional disorders, DAMAGES OR EXPECTED SAVINGS, LOSS OF USE, DATA OR OTHER CONDITIONS . DEFINITION DOES NOT AFFECT ANY RESPONSIBILITY WHICH COULD NOT BE EXCLUDED OR LIMITED IN ACCORDANCE WITH APPLICABLE LAW WHICH MAY INCLUDE FRAUD. </p>
<p> You agree to protect, indemnify and defuse the “Cursor Style”, its affiliates, licensors and service providers, as well as its and their respective officers, directors, employees, contractors, agents, licensors, suppliers, assigns and from any claims and liabilities, loss of court decisions, costs, expenses or commissions (including attorney fees) arising from or in connection with your violation of these Terms of use or use of the Service, including but not limited to repenting of any use of the content, services and products of the Website or the Extensions, except as expressly provided in these Terms of Use, or your use of any information received from the Service. </p>
<p> If any provision of these Terms of Use is found to be invalid, illegal or unenforceable by a court or other tribunal of competent jurisdiction for any reason, such a provision should be repealed or limited to a minimum, so that the rest of the provisions of the Terms of Use will continue to the fullest. The Terms of Use, our Privacy Policy and the conditions for registering events constitute the sole and complete agreement between you and the "Cursor Style" regarding the Service and supersede all previous and simultaneous agreements, agreements, representations and warranties, both written and oral, regarding the Service . </p>
<p> All reviews, comments, technical support requests, and other messages regarding the Service should be directed to the "Cursor Style" support page in the Chrome Web Store. </p> '
];
