<?php

return [
    'title' => 'Cursor Style - Politique de confidentialité',
    'descr' => 'Dans « Cursor Style », disponible sur cursor.style ou via l\'extension Chrome, l\'une de nos principales priorités est la confidentialité de nos visiteurs. C\'est dans cette section que nous parlerons de tous les aspects du fonctionnement de l\'extension.',
    'text' => '<h2> Politique de confidentialité </h2>
                <p> Dans le "Cursor Style", disponible sur <a href="https://cursor.style"> cursor.style </a> ou via l\'extension Chrome, l\'une de nos principales priorités est la confidentialité de nos visiteurs. Ce document de politique de confidentialité contient les types d\'informations collectées et enregistrées par le site Web cursor.style et la manière dont nous les utilisons. Si vous avez des questions supplémentaires ou si vous avez besoin de plus d\'informations sur notre politique de confidentialité, n\'hésitez pas à nous contacter. </p>
                <p> L\'extension "Cursor Style" et le site Web suivent la procédure standard d\'utilisation des fichiers journaux. Ces fichiers enregistrent les visiteurs lorsqu\'ils visitent des sites Web ou utilisent notre extension. Toutes les sociétés d\'hébergement le font et font partie de l\'analyse des services d\'hébergement. Les informations collectées via les fichiers journaux incluent les adresses de protocole Internet (IP), le type de navigateur, le fournisseur d\'accès Internet (FAI), l\'horodatage, les pages de transition / de sortie et éventuellement le nombre de clics. Ils ne sont associés à aucune information personnellement identifiable. Le but de ces informations est d\'analyser les tendances, d\'administrer le site et de l\'étendre, de suivre le mouvement des utilisateurs sur le site et de l\'étendre, et de collecter des informations démographiques. </p>
                <p> Comme tout autre site, cursor.style utilise des cookies. Ces cookies sont utilisés pour stocker des informations, y compris les préférences du visiteur et les pages du site Web que le visiteur a visitées ou visitées. Ces informations sont utilisées pour optimiser l\'expérience utilisateur en personnalisant le contenu de notre page Web en fonction du type de navigateur du visiteur et / ou d\'autres informations. Nous utilisons également des publicités tierces sur cursor.style pour prendre en charge le projet et soutenir notre site Web. Certains de ces annonceurs peuvent utiliser des technologies telles que les cookies et les balises Web lorsqu\'ils font de la publicité sur notre site Web, ce qui enverra également à ces annonceurs (par exemple, Google via le programme Google AdSense) des informations, y compris votre adresse IP, votre fournisseur d\'accès Internet, le navigateur que vous avez utilisé pour visiter notre site et, dans certains cas, si vous avez Flash installé. Ceci est généralement utilisé à des fins de ciblage géographique (par exemple, afficher des publicités pour la vente de biens dans votre ville) ou pour afficher certaines publicités basées sur certains sites Web visités (par exemple, afficher des annonces d\'achat à ceux qui visitent fréquemment des sites d\'achat). </ P >
                <p> Vous pouvez désactiver ou désactiver sélectivement nos cookies ou ceux de tiers dans les paramètres du navigateur ou en gérant les paramètres dans des programmes tels que Kaspersky, etc. Cependant, cela peut affecter la façon dont vous interagissez avec notre site, ainsi qu\'avec d\'autres sites. Cela peut inclure l\'impossibilité de se connecter à des services ou programmes, tels que la connexion à des forums ou des comptes. </p>
<p> Google est l\'un des fournisseurs tiers sur notre site. Il utilise également des cookies, appelés cookies DART, pour diffuser des publicités aux visiteurs de notre site en fonction de leurs visites sur cursor.style et d\'autres sites sur Internet. Cependant, les visiteurs peuvent désactiver l\'utilisation des cookies DART en visitant la politique de confidentialité de Google Advertising and Content Network à <a href="https://policies.google.com/technologies/ads"> l\'adresse suivante </a>. Certains des annonceurs sur notre site Web peuvent utiliser des cookies et des balises Web. Chacun de nos partenaires publicitaires a sa propre politique de confidentialité concernant ses politiques concernant les données utilisateur. Vous pouvez en savoir plus sur leurs politiques de confidentialité <a href="https://policies.google.com/technologies/ads"> ici </a>. </p>
                <p> Notre site Web utilise Google Analytics, un service d\'analyse Web de Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com («Google Analytics» ou «Google»). Google Analytics utilise des cookies qui sont stockés sur votre ordinateur pour faciliter l\'analyse de votre utilisation du site Web. Les informations générées par ces cookies, telles que l\'heure, le lieu et la fréquence de vos visites sur notre site Web, y compris votre adresse IP, sont transférées vers un emplacement Google aux États-Unis et y sont stockées. Google peut également transférer ces informations à des tiers si la loi l\'exige ou si des tiers traitent ces données pour le compte de Google. Google déclare qu\'il n\'associera jamais votre adresse IP à d\'autres données Google. Vous pouvez empêcher la configuration des cookies en modifiant les paramètres de votre logiciel de navigation en conséquence, comme spécifié dans cette politique de confidentialité. Cependant, vous devez savoir que de cette manière, vous ne pourrez pas utiliser pleinement toutes les fonctions de notre site Web. </p>
                <p> Google Analytics utilise également des images électroniques connues sous le nom de balises Web (parfois appelées GIF à un seul pixel) et sont utilisées avec des cookies pour compiler des statistiques agrégées afin d\'analyser l\'utilisation de notre site.
Vous pouvez trouver plus d\'informations sur la façon d\'installer le module complémentaire de navigateur auquel vous vous connectez ci-dessus <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> lien </a>.
Ce site utilise Google Tag Manager. Ce service vous permet de gérer les balises de site via l\'interface. Google Tag Manager implémente uniquement les balises. Cela signifie que les cookies ne sont pas définis et qu\'aucune donnée personnelle n\'est enregistrée. Google Tag Manager lance d\'autres balises, qui à leur tour peuvent enregistrer des données. Cependant, Google Tag Manager n\'a pas accès à ces données. Si les balises ont été désactivées au niveau du domaine ou des cookies, elles sont enregistrées pour toutes les balises de suivi, si elles sont implémentées à l\'aide de Google Tag Manager. Vous pouvez en savoir plus sur Google Tag Manager en visitant <a href="http://www.google.com/tagmanager/use-policy.html"> lien </a>. </p>
<p> Vous pouvez vous familiariser avec cette liste pour trouver la politique de confidentialité de chacun des partenaires publicitaires "Cursor Style". Les serveurs publicitaires ou réseaux publicitaires tiers utilisent des technologies telles que les cookies, JavaScript ou les balises Web, qui sont utilisées dans leurs publicités et liens respectifs, qui sont affichés dans le “Cursor Style” et envoyés directement au navigateur des utilisateurs. Ils obtiennent automatiquement votre adresse IP lorsque cela se produit. Ces technologies sont utilisées pour mesurer l\'efficacité de leurs campagnes publicitaires et / ou pour personnaliser le contenu publicitaire que vous voyez sur les sites Web que vous visitez. Veuillez noter que le "Cursor Style" n\'a pas accès ni contrôle sur ces cookies qui sont utilisés par des annonceurs tiers. La politique de confidentialité de Cursor Style ne s\'applique pas aux autres annonceurs ou sites Web. Par conséquent, nous vous recommandons de consulter les politiques de confidentialité pertinentes de ces serveurs publicitaires tiers pour plus d\'informations. Cela peut inclure leurs méthodes et instructions sur la façon de désactiver certaines options. Vous pouvez trouver des liens vers ces politiques de confidentialité tierces ci-dessus ou sur les sites Web de ces services tiers. </p>
                <p> Vous pouvez désactiver les cookies dans les paramètres de votre navigateur. Pour en savoir plus sur la gestion des cookies dans des navigateurs Web spécifiques, vous pouvez le trouver sur leurs sites Web de navigateur respectifs. Une autre partie de notre priorité est d\'ajouter une protection des enfants lors de l\'utilisation d\'Internet. Nous encourageons les parents et les tuteurs à observer, à participer et / ou à surveiller et à diriger leurs activités sur Internet. "Cursor Style" ne collecte pas sciemment d\'informations personnelles auprès d\'enfants de moins de 13 ans. Si vous pensez que votre enfant a fourni de telles informations sur notre site Web, nous vous recommandons vivement de nous contacter immédiatement et nous ferons de notre mieux pour supprimer rapidement ces informations de nos dossiers. Cette politique de confidentialité s\'applique uniquement à nos activités en ligne et est valable pour les visiteurs de notre site Web en relation avec les informations qu\'ils ont partagées et / ou collectées dans le "Cursor Style". Cette politique ne s\'applique pas aux informations collectées hors ligne ou via des canaux autres que ce site Web. </p>
                <p> Vous pouvez en savoir plus sur l\'utilisation des cookies dans notre service dans notre <a href="/cookie-policy"> Politique de cookies </a>. </p> ',
];
