<?php

return [
    'title' => 'Cursor Style - Privatlivspolitik',
    'descr' => 'I “Cursor Style”, der er tilgængelig på cursor.style eller gennem Chrome-udvidelsen, er en af ​​vores topprioriteter privatlivet for vores besøgende. Det er i dette afsnit, at vi vil tale om alle aspekter af arbejdet med udvidelsen.',
    'text' => '<h2> Privatlivspolitik </h2>
                <p> I Cursor Style, tilgængelig på <a href="https://cursor.style"> cursor.style </a> eller gennem Chrome-udvidelsen, er en af ​​vores topprioriteter vores besøgendes privatliv. Dette dokument om beskyttelse af personlige oplysninger indeholder de typer oplysninger, der indsamles og registreres af websitet cursor.style, og hvordan vi bruger det. Hvis du har yderligere spørgsmål eller har brug for mere information om vores fortrolighedspolitik, så tøv ikke med at kontakte os. </p>
                <p> Udvidelsen "Cursor Style" og webstedet følger standardproceduren for brug af logfiler. Disse filer registrerer besøgende, når de besøger websteder eller bruger vores udvidelse. Alle hostingfirmaer gør dette og er en del af webhoteltjenestens analyse. Oplysninger, der indsamles gennem logfiler, inkluderer Internet Protocol (IP)-adresser, browsertype, Internetudbyder (ISP), dato og tidsstempel, overgangs-/exit-sider og muligvis antallet af klik. De er ikke forbundet med nogen personligt identificerbare oplysninger. Formålet med disse oplysninger er at analysere tendenser, administrere webstedet og udvide, spore brugernes bevægelse på webstedet og udvide og indsamle demografiske oplysninger. </p>
                <p> Som alle andre websteder bruger cursor.style cookies. Disse cookies bruges til at gemme oplysninger, herunder den besøgendes præferencer og de sider på webstedet, som den besøgende besøgte eller besøgte. Disse oplysninger bruges til at optimere brugeroplevelsen ved at tilpasse indholdet på vores webside baseret på typen af ​​den besøgendes browser og/eller andre oplysninger. Vi bruger også tredjepartsannoncer på cursor.style for at støtte projektet og understøtte vores hjemmeside. Nogle af disse annoncører kan bruge teknologier som cookies og web beacons, når de annoncerer på vores hjemmeside, hvilket også sender disse annoncører (f.eks. Google gennem Google AdSense-programmet) oplysninger, herunder din IP-adresse, din internetudbyder, den browser, du brugte til at besøge vores websted, og i nogle tilfælde, hvis du har Flash installeret. Dette bruges normalt til geotargeting-formål (f.eks. visning af annoncer for salg af varer i din by) eller til at vise bestemte annoncer baseret på bestemte besøgte websteder (f.eks. visning af købsmeddelelser til dem, der ofte besøger shopping-websteder). </ P >
                <p> Du kan deaktivere eller selektivt deaktivere vores eller tredjeparts cookies i browserindstillingerne eller ved at administrere indstillinger i programmer som Kaspersky osv. Dette kan dog påvirke, hvordan du interagerer med vores websted samt med andre websteder. Dette kan omfatte manglende evne til at logge ind på tjenester eller programmer, såsom at logge ind på fora eller konti. </p>
<p> Google er en af ​​tredjepartsudbyderne på vores websted. Den bruger også cookies, kendt som DART-cookies, til at vise annoncer til besøgende på vores websted baseret på deres besøg på cursor.style og andre websteder på internettet. Besøgende kan dog fravælge brugen af ​​DART-cookies ved at besøge Googles privatlivspolitik for annoncerings- og indholdsnetværk på <a href="https://policies.google.com/technologies/ads"> følgende adresse </a>. Nogle af annoncørerne på vores websted kan bruge cookies og web beacons. Hver af vores annonceringspartnere har sin egen privatlivspolitik for sine politikker vedrørende brugerdata. Du kan læse mere om deres privatlivspolitikker <a href="https://policies.google.com/technologies/ads"> her </a>. </p>
                <p> Vores websted bruger Google Analytics, en webtjeneste fra Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com (“Google Analytics” eller “Google”). Google Analytics bruger cookies, der gemmes på din computer for at lette analysen af ​​din brug af webstedet. Oplysninger genereret af disse cookies, såsom tidspunkt, sted og hyppighed af dine besøg på vores websted, inklusive din IP-adresse, overføres til et Google-sted i USA og gemmes der. Google kan også overføre disse oplysninger til tredjeparter, hvis det kræves af loven, eller hvis tredjeparter behandler disse data på vegne af Google. Google oplyser, at det aldrig vil knytte din IP-adresse til andre Google-data. Du kan forhindre indstillingen af ​​cookies ved at ændre dine browserindstillinger i overensstemmelse hermed, som specificeret i denne privatlivspolitik. Du bør dog være opmærksom på, at du på denne måde ikke vil være i stand til fuldt ud at bruge alle funktionerne på vores websted. </p>
                <p> Google Analytics bruger også elektroniske billeder kendt som web beacons (undertiden kaldet enkeltpixel-GIF\'er) og bruges sammen med cookies til at udarbejde aggregeret statistik for at analysere brugen af ​​vores websted.
Du kan finde mere information om, hvordan du installerer browser-tilføjelsen, som du linker til ovenfor <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> link </a>.
 Dette websted bruger Google Tag Manager. Denne tjeneste giver dig mulighed for at administrere webstedsmærker via grænsefladen. Google Tag Manager implementerer kun tags. Det betyder, at der ikke er sat cookies, og ingen personlige data registreres. Google Tag Manager lancerer andre tags, som til gengæld kan registrere data. Google Tag Manager har dog ikke adgang til disse data. Hvis tags er blevet deaktiveret på domæne- eller cookieniveau, gemmes de for alle sporingsmærker, hvis de implementeres ved hjælp af Google Tag Manager. Du kan lære mere om Google Tag Manager ved at besøge <a href="http://www.google.com/tagmanager/use-policy.html"> link </a>. </p>
<p> Du kan gøre dig bekendt med denne liste for at finde privatlivspolitikken for hver af "Cursor Style" annonceringspartnere. Tredjeparts-annonce servere eller -netværk bruger teknologier som cookies, JavaScript eller web beacons, som bruges i deres respektive annoncer og links, som vises i “Cursor Style” og sendes direkte til brugernes browser. De får automatisk din IP-adresse, når dette sker. Disse teknologier bruges til at måle effektiviteten af ​​deres reklamekampagner og/eller til at personalisere det annonceringsindhold, du ser på de websteder, du besøger. Bemærk, at "Cursor Style" ikke har adgang til eller kontrol over disse cookies, der bruges af tredjepartsannoncører. Cursor Style-beskyttelsespolitikken gælder ikke for andre annoncører eller websteder. Derfor anbefaler vi, at du gennemgår de relevante privatlivspolitikker for disse tredjeparts-ad-servere for mere information. Det kan omfatte deres metoder og instruktioner om, hvordan man fravælger visse muligheder. Du kan finde links til disse tredjeparts privatlivspolitikker ovenfor eller på webstederne for disse tredjepartstjenester. </p>
                <p> Du kan deaktivere cookies i dine browserindstillinger. For at lære mere om cookie-administration i specifikke webbrowsere, kan du finde det på deres respektive browser-websteder. En anden del af vores prioritet er at tilføje børnebeskyttelse, når du bruger internettet. Vi opmuntrer forældre og værger til at observere, deltage i og/eller overvåge og lede deres aktiviteter på internettet. "Cursor Style" indsamler ikke bevidst personlige oplysninger fra børn under 13 år. Hvis du mener, at dit barn har givet sådanne oplysninger på vores websted, anbefaler vi på det kraftigste, at du kontakter os straks, og vi vil gøre vores bedste for hurtigt at fjerne sådanne oplysninger fra vores registre. Denne privatlivspolitik gælder kun for vores onlineaktiviteter og er gyldig for besøgende på vores websted i forhold til de oplysninger, de delte og/eller indsamlede i "Cursor Style". Denne politik gælder ikke for nogen oplysninger, der indsamles offline eller gennem andre kanaler end dette websted. </p>
                <p> Du kan læse mere om brugen af ​​cookies i vores Service i vores <a href="/cookie-policy"> Cookie-politik </a>. </p> ',
];
