<?php

return [
    'title' => 'Сursor Style - Vilkår for brug af vores produkt',
    'descr' => 'Betingelserne for brug indgås mellem dig og “Cursor Style” (“Tjeneste”, “vi” eller “Tjenesten”). Denne tjeneste tilbydes og er tilgængelig for brugere på 13 år og derover, kun til personlig brug og ikke til kommerciel brug.',
    'text' => '<h2> Servicevilkår </h2>
<h3> LÆS DISSE VILKÅR OG BETINGELSER, FØR DU BRUGER HJEMMESIDEN OG UDVIDELSEN. </h3>
<p> Disse brugsbetingelser indgås mellem dig og "Cursor Style" ("Tjeneste", "vi" eller "Tjeneste"). Følgende vilkår og betingelser sammen med alle dokumenter, som de udtrykkeligt inkluderer ved henvisning (samlet set disse "Brugsvilkår"), regulerer din adgang til og brug af cursor.style-webstedet og dets browserudvidelser, inklusive ethvert indhold, funktionalitet og tjenester, der tilbydes på eller gennem vores tjeneste (sammen "Tjenesten"). </p>
<p> Ved at bruge webstedet eller udvidelsen accepterer og accepterer du at overholde disse brugsbetingelser. Hvis du ikke accepterer disse brugsbetingelser eller vores <a href="/privacy"> Fortrolighedspolitik </a>, bør du ikke få adgang til eller bruge webstedet og udvidelsen. </p>
<p> Denne tjeneste tilbydes og er kun tilgængelig for brugere på 13 år og derover til personlig brug og ikke til kommerciel brug. Ved at bruge denne tjeneste erklærer og garanterer du, at du er (I) 13 år eller ældre, (II) du er ikke forbudt at bruge webstederne i overensstemmelse med gældende lovgivning, og (III) du bruger tjenesten kun til dine personlige behov. Hvis du ikke opfylder disse krav, bør du ikke få adgang til eller bruge Tjenesten. </p>
<p> Vi kan revidere og opdatere disse brugsbetingelser fra tid til anden efter eget skøn. Alle ændringer træder i kraft umiddelbart efter deres offentliggørelse. Din fortsatte brug af tjenesten efter offentliggørelsen af de reviderede brugsbetingelser betyder, at du accepterer og accepterer ændringerne. Du forventes at besøge denne side ofte for at holde dig ajour med eventuelle ændringer, da de er bindende for dig. </p>
<p> Vi forbeholder os retten til at trække eller ændre dette websted og udvidelsen, eventuelle tjenester eller materialer, som vi leverer på webstedet og udvidelsen, efter eget skøn uden varsel. Vi garanterer ikke, at vores websted, udvidelse eller ethvert indhold på det altid vil være tilgængeligt, eller at det vil blive afbrudt. Vi er ikke ansvarlige, hvis hele eller en del af tjenesten af en eller anden grund ikke er tilgængelig på ethvert tidspunkt eller i en periode. Fra tid til anden kan vi begrænse adgangen til visse dele af webstedet eller udvidelsen eller hele tjenesten for brugere. </p>
<p> Du er ansvarlig for at træffe alle nødvendige foranstaltninger for at sikre, at du har adgang til tjenesten. Sørg for, at alle personer, der får adgang til tjenesten via din internetforbindelse, er opmærksomme på disse brugsbetingelser og overholder dem. For at få adgang til tjenesten eller nogle af de ressourcer, den tilbyder, kan du blive bedt om at give visse oplysninger eller andre oplysninger. Du accepterer, at alle oplysninger, som du giver os ved hjælp af denne tjeneste eller på anden måde, inklusive, men ikke begrænset til, brugen af alle interaktive funktioner i tjenesten, er omfattet af vores <a href="/privacy"> Fortrolighedspolitik </a>, og du accepterer alle handlinger, som vi træffer vedrørende dine oplysninger. i overensstemmelse med vores <a href="/privacy"> Fortrolighedspolitik </a>. </p>
<p> Du skal være særlig forsigtig, når du indtaster personlige oplysninger i tjenesten på en offentlig eller delt computer, så andre ikke kan se eller registrere dine personlige oplysninger. Webstedet, udvidelsen og alt dets indhold, dets funktioner og funktioner (inklusive, men ikke begrænset til, alle oplysninger, udvidelsen, tekst, billeder, billeder og cursors samt deres design, valg og placering) tilhører "Cursor Style", dets licensgivere eller andre leverandører af sådanne materialer er beskyttet af ophavsret, varemærke, patent, forretningshemmelighed og andre intellektuelle ejendomslove eller ejendomsrettigheder. </p>
<p> Disse brugsbetingelser giver dig mulighed for kun at bruge webstederne til din personlige, ikke-kommercielle brug. Du må ikke gengive, distribuere, ændre, oprette afledte værker, genudgive, downloade, gemme eller overføre materialer på vores websted, undtagen i følgende tilfælde: du kan bruge det til personlige behov, du kan udskrive eller downloade en kopi af et rimeligt antal sider på webstedet og udvidelsen eller deres indhold til personlig, ikke-kommerciel brug og ikke til videre reproduktion, offentliggørelse eller distribution. </p>
<p> Du må ikke ændre kopier af materialer fra dette websted eller udvidelse og deres indhold. Slet eller ændr eventuelle meddelelser om ophavsret, varemærker eller andre proprietære meddelelser fra kopier af dette websted og udvidelsen. Du må ikke have adgang til eller bruge nogen del af webstederne eller udvidelserne, såvel som tjenester eller materialer, der er tilgængelige via webstedet eller udvidelsen, til kommercielle formål. </p>
<p> Hvis du vil bruge ethvert materiale på websteder eller udvidelser ud over dem, der er angivet i dette afsnit, skal du sende en anmodning på supportsiden i Chrome Webshop. </p>
<p> Hvis du udskriver, kopierer, ændrer, downloader eller på anden måde bruger eller giver enhver anden person adgang til nogen del af webstedet eller udvidelsen i strid med brugsbetingelserne, ophører din ret til at bruge webstedet og udvidelsen straks, og du skal efter vores skøn returnere eller ødelægge eventuelle kopier af de materialer, du har. Enhver brug af udvidelsens websted, der ikke udtrykkeligt er tilladt i disse brugsbetingelser, er i strid med disse brugsbetingelser og kan krænke ophavsret, varemærker og andre love. </p>
<p> Navnet “Cursor Style”, logoet “Cursor Style” og alle tilknyttede navne, logoer, billeder, cursors og servicenavne, designs og slogans er varemærker tilhørende “Cursor Style” eller dets tilknyttede selskaber eller licensgivere. Du må ikke bruge sådanne mærker uden forudgående skriftlig tilladelse fra tjenesten. Alle andre navne, logoer, produkt- og servicenavne, designs og slogans på dette websted og i udvidelsen er varemærker tilhørende deres respektive ejere. Du må kun bruge tjenesten til legitime formål og i overensstemmelse med disse brugsbetingelser. </p>
<h3> Du accepterer IKKE at bruge Tjenesten: </h3>
<ul>
<li> På nogen måde, der overtræder gældende føderale, regionale, lokale eller internationale love eller forskrifter (herunder, men ikke begrænset til, eventuelle love vedrørende eksport af data eller software til Rusland og andre lande). </li>
<li> Med det formål at udnytte, skade eller forsøge at bruge eller skade mindreårige, udsætte dem for upassende indhold, anmode om oplysninger, der identificerer dem eller på anden måde. </li>
<li> For at sende, bevidst modtage, downloade, bruge eller genbruge materialer, der ikke overholder disse brugsbetingelser. </li>
<li> Overføre eller købe afsendelse af reklamer eller salgsfremmende materialer uden vores forudgående skriftlige samtykke, inklusive "uønskede breve", "kædebreve" eller "spam" eller andre lignende tilbud. </li>
<li> For at udgive sig for eller forsøge at udgive sig for en “Cursor Style”-medarbejder, en anden bruger eller enhver anden person eller organisation (herunder, men ikke begrænset til, at bruge e-mailadresser eller aliaser forbundet med noget af det ovenstående). </li>
<li> Deltagelse i andre handlinger, der begrænser eller hindrer brugen af Tjenesten eller brugen af nogen, eller som vi afgør, kan skade Tjenesten eller brugerne af Tjenesten eller gøre dem ansvarlige. </li> </ul>
<h3> Derudover accepterer du IKKE: </h3>
<ul>
<li> Brug tjenesten på nogen måde, der kan deaktivere, overbelaste, beskadige eller forringe webstedets funktion, udvide eller forstyrre brugen af tjenesten af enhver anden part, herunder deres evne til at deltage i realtids handlinger gennem tjenesten. </li>
<li> Brug eventuelle automatiseringsværktøjer, processer eller midler til at få adgang til tjenesten med ethvert formål, herunder overvågning eller kopiering af materiale i tjenesten. </li>
<li> Brug enhver manuel proces til at spore eller kopiere materiale på tjenesten eller til andre uautoriserede formål uden vores forudgående skriftlige samtykke. </li>
<li> Brug enheder, software eller procedurer, der forstyrrer tjenestens normale funktion. </li>
<li> Indføre vira, trojanske heste, orme, logiske bomber eller andre materialer, der er skadelige eller teknologisk skadelige. </li>
<li> Prøv at få uautoriseret adgang, forstyrre, skade eller afbryde enhver del af tjenesten, den server, hvor tjenesten er gemt, eller enhver server, computer eller database, der er forbundet til tjenesten. </li>
<li> Angribe en tjeneste ved hjælp af et nægtelse af serviceangreb eller et distribueret nægtelse af serviceangreb. </li> </ul>
<p> Oplysninger, der leveres på eller gennem tjenesten, leveres udelukkende til generelle informationsformål. Vi garanterer ikke nøjagtigheden, fuldstændigheden eller anvendeligheden af disse oplysninger. Du er afhængig af sådanne oplysninger udelukkende på din egen risiko. Vi fraskriver os ethvert ansvar og erstatningsansvar som følge af enhver afhængighed af sådanne materialer af dig, andre besøgende på tjenesten eller nogen, der måtte være informeret om noget af deres indhold. </p>
<p> Denne tjeneste inkluderer indhold leveret af tredjeparter, inklusive materialer leveret af andre brugere og tredjepartslicensgivere, syndikatorer, aggregatorer og / eller rapporteringstjenester. Alle erklæringer og / eller meninger, der er udtrykt i disse materialer, såvel som alle artikler og svar på spørgsmål og andet indhold, undtagen det indhold, der leveres af tjenesten, er udelukkende meninger og ansvar for den person eller organisation, der leverer disse materialer. Disse materialer afspejler ikke nødvendigvis Tjenestens synspunkter. Vi er ikke ansvarlige over for dig eller nogen tredjepart for indholdet eller nøjagtigheden af materialer leveret af tredjeparter. </p>
<p> Vi kan opdatere indholdet af tjenesten fra tid til anden, men indholdet er ikke nødvendigvis komplet eller aktuelt. Ethvert materiale på tjenesten kan være forældet til enhver tid, og vi er ikke forpligtede til at opdatere sådant materiale. Vi kan opdatere, ændre, ændre oplysninger og indhold på webstedet og i udvidelsen, foretage ændringer og opdateringer i henhold til vores egen beslutning. </p>
<p> Alle oplysninger, som vi indsamler på denne tjeneste, er underlagt vores fortrolighedspolitik. Ved at bruge tjenesten accepterer du alle handlinger, der er udført af os i forhold til dine oplysninger i overensstemmelse med <a href="/privacy"> Fortrolighedspolitikken </a>. </p>
<p> Yderligere vilkår kan også gælde for visse dele, tjenester eller funktioner i tjenesten. Alle sådanne yderligere vilkår og betingelser er hermed inkorporeret ved henvisning til disse brugsbetingelser.
Du kan linke til vores websted eller udvidelse, hvis du gør det på en ærlig og lovlig måde og ikke skader vores omdømme eller bruger det, men du bør ikke angive linket på en sådan måde, at du tilbyder nogen form for tilknytning, påtegning eller godkendelse fra vores side uden vores skriftlige samtykke. </p>
<p> Tjenesten indeholder links til andre websteder og ressourcer leveret af tredjeparter, disse links leveres kun for din bekvemmelighed. Dette inkluderer links indeholdt i reklamer, inklusive bannerannoncer og sponsorerede links. Vi kontrollerer ikke indholdet af disse websteder eller ressourcer og er ikke ansvarlige for dem eller for ethvert tab eller skade, der måtte følge af deres brug. Hvis du beslutter at få adgang til tredjepartswebsteder, der er forbundet med denne tjeneste, gør du det på egen risiko og i overensstemmelse med brugsbetingelserne for sådanne websteder. Vi forbeholder os retten til at tilbagekalde tilladelse til at linke uden forudgående varsel. </p>
<p> Du forstår, at vi ikke kan og ikke garanterer eller garanterer, at de filer, der er tilgængelige til download via internettet eller på websteder, ikke indeholder vira eller anden ondsindet kode. Du er ansvarlig for implementeringen af procedurer og kontrolpunkter, der er tilstrækkelige til at opfylde dine særlige krav til beskyttelse mod virus og nøjagtigheden af dataindtastning og -udgang samt for at opretholde midler eksterne i forhold til vores websted til genoprettelse af mistede data. VI ER IKKE ANSVARLIGE FOR SKADER ELLER SKADER FORÅRSAGET AF DISTRIBUERET TØRELSE AF SERVICE, VIRUS ELLER ANDEN TEKNOLOGI -MALWARE, DER ER ERHVERVET GENNEM TJENESTEN, ELLER VED DOWNLOAD AF MATERIALE, DER ER POSTET PÅ DETTE ELLER ETHVERT WEBSTED, DER ER RELATERET TIL AT KAN INFICERE ELLER SKADE DIN COMPUTERUDSTYR, COMPUTER SOFTWARE, DATA. </p>
<p> DU BRUGER TJENESTEN, DETS INDHOLD OG ALLE YDELSER ELLER VARER, DER ER ERHVERVET GENNEM TJENESTERNE, PÅ DIN EGEN RISIKO. TJENESTEN, DENS INDHOLD OG ALLE YDELSER ELLER VARER, DER ER ERHVERVET GENNEM HJEMMESIDEN OG UDVIDELSEN, LEVERES PÅ EN “SOM DEN ER” OG “SOM TILGÆNGELIGE” VILKÅR OG BETINGELSER, UDEN NOGEN GARANTI. ENHVER PERSON, DER ER FORBUNDET MED TJENESTEN, LEVERER INGEN GARANTI ELLER REPRÆSENTATION MED HENSYN TIL FULDFØRELSE, SIKKERHED, PÅLIDELIGHED, KVALITET, NØJAGTIGHED ELLER TILGÆNGELIGHED AF TJENESTEN. UDEN BEGRÆNSNING OVENFOR, GARANTERER “CURSOR STYLE” ELLER TILHØRENDE TIL EN “CURSOR STYLE” REPRÆSENTANTER IKKE, AT  SIDEN, UDVIDELSEN, DETS INDHOLD ELLER EN EVENTUEL REPARATION SKULLE VÆRE TIDLIGERE TILGÆNGELIGT, FASTSAT AT VORES UDVIDELSE, EN SIDE ELLER EN SERVER, SOM PLACERER DET, VIL VÆRE UDEN VIRUS ELLER ANDRE SKADELIGE KOMPONENTER, ELLER DETTE WEBSTED ELLER EVENTUELLE YDELSER ELLER VARER, DER UDFØRES, FORETRUKKET. </p>
<p> Under ingen omstændigheder er TJENESTEN, DETS TILKNYTTEDE SELSKABER ELLER ELLER LICENSGIVERE, TJENESTER, MEDARBEJDERE, AGENTER, TJENESTEMÆND ELLER DIREKTØRER ANSVARLIGE FOR SKADER AF ENHVER ART, VI YDER TIL NOGEN ANSVAR. ELLER SÅDANNE ANDRE WEBSTEDER ELLER EVENTUELLE TJENESTER ELLER VARER, DER ER ERHVERVET I TJENESTEN ELLER TIL ANDRE WEBSTEDER, INKLUSIVE ALLE DIREKTE, SÆRLIGE ELLER FØLGE SKADER, HERUNDER PERSONLIG SKADE, EMOTIONELLE FORSTYRRELSER, SKADER ELLER FORVENTET BESPARELSER, TAB AF BRUG, DATA ELLER ANDRE BETINGELSER . DEFINITION PÅVIRKER IKKE ET ANSVAR, DER IKKE KUNNE UDELUKKES ELLER BEGRÆNSES I OVERENSSTEMMELSE MED GÆLDENDE LOV, SOM KAN INKLUDERE SVIG. </p>
<p> Du accepterer at beskytte, erstatte og afværge “Cursor Style”, dets tilknyttede selskaber, licensgivere og serviceudbydere såvel som dets respektive officerer, direktører, medarbejdere, entreprenører, agenter, licensgivere, leverandører, tildeling og fra eventuelle krav og forpligtelser, tab af retslige afgørelser, omkostninger, udgifter eller provisioner (inklusive advokatsalærer), der opstår som følge af eller i forbindelse med din overtrædelse af disse brugsbetingelser eller brug af tjenesten, inklusive, men ikke begrænset til, at fortryde enhver brug af indholdet, ydelserne og produkterne på webstedet eller udvidelserne, bortset fra hvad der udtrykkeligt er angivet i disse brugsbetingelser, eller din brug af oplysninger, der er modtaget fra tjenesten. </p>
<p> Hvis en bestemmelse i disse brugsbetingelser findes ugyldig, ulovlig eller ikke kan håndhæves af en domstol eller anden domstol med kompetent jurisdiktion af en eller anden grund, bør en sådan bestemmelse ophæves eller begrænses til et minimum, så de resterende bestemmelser i brugsbetingelserne fortsætter med det fulde omfang. Brugsbetingelserne, vores fortrolighedspolitik og betingelserne for registrering af begivenheder udgør den eneste og komplette aftale mellem dig og "Cursor Style" vedrørende tjenesten og erstatter alle tidligere og samtidige aftaler, aftaler, erklæringer og garantier, både skriftlige og mundtlige, vedrørende tjenesten . </p>
<p> Alle anmeldelser, kommentarer, anmodninger om teknisk support og andre beskeder vedrørende tjenesten skal rettes til “Cursor Style” supportside i Chrome Webshop. </p> ',
];
