<?php

return [
    'halo_descr' => 'Halo là một series phim truyền thông giả tưởng chiến đấu được tạo ra bởi Bungie. Dựa trên bộ ba trò chơi điện tử bắn súng góc nhìn thứ nhất gốc. Cốt truyện xoay quanh các sự kiện diễn ra trong cuộc đời của Master Chief, một trong nhóm siêu chiến binh có mật danh Spartans, và người bạn đồng hành của anh, trí tuệ nhân tạo Cortana. Sự thành công của các trò chơi đã dẫn đến việc mở rộng nhượng quyền thương mại này sang các phương tiện truyền thông khác: vũ trụ Halo hiện bao gồm nhiều sách, tiểu thuyết đồ họa, truyện tranh, phim ngắn, phim hoạt hình và phim truyện.',
    'halo_short_descr' => 'Chạm vào con trỏ hiện vật, có lẽ bạn là người được chọn.',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'Búp bê LOL Surprise đã khiến trẻ em yêu thích và chiếm được trái tim của chúng ngay từ những phút đầu tiên. Điều này không có gì đáng ngạc nhiên, bởi vì thành công đó dựa trên một bí ẩn, sự mong đợi về một điều kỳ diệu, một bất ngờ thú vị, điều này không chỉ làm hài lòng trẻ em mà còn cả cha mẹ của chúng. Bí mật của món quà chỉ được tiết lộ cho đứa trẻ sau khi giải nén cuối cùng. Trong mọi trường hợp, búp bê LOL có thiết kế hấp dẫn, sự tò mò, một số lượng lớn các phụ kiện tuyệt vời và chân thực và những điều nhỏ nhặt thú vị, cũng như chất lượng sản xuất và chi tiết cao nhất của đồ chơi.',
    'lol_surprise_short_descr' => 'Những cô nàng dễ thương dành cho những người sành sỏi về những điều bất ngờ thú vị',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Loạt phim xoay quanh một cuộc thi nơi 456 người chơi, tất cả đều mắc nợ nần chồng chất, liều mạng sống của họ để chơi một loạt các trò chơi trẻ em chết người với cơ hội giành được một giải thưởng tỷ đô. Bên trong, một giải thưởng hấp dẫn đang chờ đợi với số tiền cược cao chết người. Tiêu đề của loạt phim được lấy từ một trò chơi trẻ em Hàn Quốc có tên tương tự. Hwang đã hình thành ý tưởng dựa trên những khó khăn kinh tế của chính mình khi còn trẻ, cũng như sự khác biệt về giai cấp ở Hàn Quốc và chủ nghĩa tư bản.',
    'squid_game_short_descr' => 'Chọn khuôn mặt người chơi phù hợp khi bạn chơi tất tay',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter là nhân vật chính của một loạt tiểu thuyết của nhà văn người Anh JK Rowling. Vào sinh nhật lần thứ mười một của mình, Harry biết rằng mình là một phù thủy và được định sẵn một vị trí tại Trường Phù Thủy Hogwarts, nơi cậu sẽ thực hành phép thuật dưới sự hướng dẫn của hiệu trưởng Albus Dumbledore và các giáo sư khác của trường. Harry cũng phát hiện ra rằng cậu đã được biết đến khắp cộng đồng phép thuật của cuốn tiểu thuyết, và số phận của cậu có liên quan đến số phận của Voldemort, một phù thủy hắc ám nguy hiểm.',
    'harry_potter_short_descr' => 'Bạn sẽ làm gì với một cây đũa phép từ bộ sưu tập con trỏ Harry Potter?',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics là một nhà xuất bản truyện tranh nổi tiếng với việc tạo ra các siêu anh hùng nổi bật như Người Nhện, Người Sắt, Captain America, Hulk, Thor, Avengers, Vệ Binh Dải Ngân Hà, X-Men, Fantastic Four và Deadpool. Những nhân vật phản diện nổi tiếng nhất của Marvel bao gồm Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom và Magneto. Marvel Comics và DC Comics đã hợp tác trong một số dự án giao thoa cùng nhau và cũng đồng sáng lập ấn phẩm Amalgam Comics được dự định tồn tại trong thời gian ngắn.',
    'marvel_comics_short_descr' => 'Siêu anh hùng sống trong mỗi chúng ta - hãy chọn của bạn',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Chào mừng bạn trở lại Vương quốc Bánh quy trong Cookie Run: Kingdom của Devsisters, game nhập vai chiến lược đáng yêu lấy bối cảnh trong vũ trụ Cookie Run. Giờ đây, GingerBrave đã trốn thoát khỏi lò nướng của mụ phù thủy độc ác, đã đến lúc anh ta xây dựng một đội Bánh quy và dấn thân vào một nhiệm vụ để xây dựng lại Vương quốc Bánh quy đã sụp đổ. Khám phá sự thật đằng sau sự sụp đổ của Vương quốc và tập hợp một đội hình gồm những Bánh quy mạnh nhất của Vương quốc để đánh bại các thế lực bóng tối muốn ngăn GingerBrave hoàn thành định mệnh của mình.',
    'cookie_run_kingdom_short_descr' => 'Chiến binh nhỏ bé vừa ra khỏi lò nướng',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact là một game phiêu lưu thế giới mở. Điều này có nghĩa là một phong cảnh mới, thú vị đang chờ bạn ở phía bên kia của dòng sông hoặc ngọn núi, bạn chỉ cần sử dụng năng lượng của mình một cách khôn ngoan. Nếu bạn bắt gặp một nàng tiên lang thang hoặc một cơ chế kỳ lạ, hãy dám và cố gắng làm sáng tỏ bí ẩn của chúng. Nhưng chúng hứa hẹn điều gì - rắc rối hay một bất ngờ thú vị - chỉ bạn mới có thể tìm ra! Trên lục địa Teyvat rộng lớn, bạn sẽ đến thăm bảy vương quốc, tìm những người bạn đồng hành với nhiều kỹ năng khác nhau và chiến đấu chống lại kẻ thù mạnh mẽ để tìm kiếm người thân đã mất tích.',
    'genshin_impact_short_descr' => 'Trở thành Bậc thầy Nguyên tố của Thất Quốc.',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Khi một lời tiên tri cổ xưa trở thành sự thật và vương quốc chìm trong vòng tay của mùa đông, ba anh hùng dũng cảm - Công chúa Anna, Kristoff dũng cảm và chú tuần lộc trung thành Sven - lên đường đến ngọn núi để tìm Elsa, chị gái của Anna, người có thể loại bỏ lời nguyền lạnh lẽo khỏi đất nước. Trên đường đi, nhiều điều bất ngờ khó khăn và những cuộc phiêu lưu thú vị đang chờ đợi họ. Gặp gỡ những con troll huyền bí, gặp gỡ người tuyết Olaf quyến rũ, những đỉnh núi dốc hơn cả Everest và rất nhiều phép thuật. Các anh hùng phải chống lại các yếu tố hùng mạnh để cứu vương quốc và những người thân yêu của họ.',
    'frozen_short_descr' => 'Phá băng thật dễ dàng với bộ sưu tập con trỏ Frozen',
    'frozen' => 'Frozen',
    'stranger_things_descr' => 'Đã hơn sáu tháng kể từ khi kết thúc mùa thứ ba. Joyce, Will, Eleven và Jonathan đã chuyển đến California, nơi cô gái đang bị bắt nạt ở trường. Những người còn lại bắt đầu chiến đấu với một con quái vật mới từ một thế giới song song đã xuất hiện ở Hawkins. Nó được đặt tên là Vecna ​​theo nhân vật trò chơi trên bàn cờ Dungeons & Dragons. Nó ảnh hưởng đến thanh thiếu niên về mặt tâm lý, sau đó leo vào đầu và giết người. Song song đó, Joyce và Murray biết rằng Jim Hopper vẫn còn sống và đi theo anh ta đến một nhà tù Xô Viết ở Kamchatka. Và Eleven sẽ phải trở lại và tăng cường sức mạnh của mình, nhưng cũng tìm hiểu vai trò quan trọng của mình trong việc tạo ra cùng một con quái vật ở Gokins.

Các nhà văn không thay đổi chiến thuật cốt truyện mà họ thích trong vài mùa qua. Trong mùa thứ tư, họ chia nhóm lớn các nhân vật chính thành các nhóm, đưa ra những nhiệm vụ khó khăn cho họ và cuối cùng xây dựng những câu chuyện của họ lại với nhau trong một kết thúc tuyệt vời. Chúng tôi cung cấp cho bạn để hiểu chi tiết tất cả những cuộc phiêu lưu này với sự trợ giúp của bộ sưu tập con trỏ Stranger Things.',
    'stranger_things_short_descr' => 'Điều gì sẽ xảy ra tiếp theo? - Con trỏ chuột Stranger Things 4',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars là một chế độ gốc xuất hiện lần đầu tiên trong Minecraft. Nhiệm vụ của người chơi là bảo vệ căn cứ và giường của họ.

Roblox mang đến nhiều trò chơi thú vị hơn mỗi ngày và BedWars không phải là ngoại lệ. Và điều quan trọng là, nếu bạn yêu thích Bed Wars và tự bảo vệ mình trong phòng, đây là tựa game dành cho bạn vì nó đưa bạn trở lại thời thơ ấu, mặc dù là kỹ thuật số lần này.

Tất cả những gì bạn cần làm là bảo vệ chiếc giường của mình khỏi những kẻ tấn công cùng với đối tác của bạn. Bạn vào sảnh, chọn người chơi cùng và voila, chỉ là vấn đề bảo vệ.

Đương nhiên, khi nói đến việc phòng thủ, bạn sẽ gặp một số vấn đề và có những tài nguyên, vật phẩm và vật dụng nhất định sẽ giúp bạn chiến thắng. Ví dụ, các skin độc quyền mà bạn sẽ tìm thấy trong bộ sưu tập con trỏ Bed Wars.',
    'roblox_bed_wars_short_descr' => 'Bảo vệ giường của bạn với con trỏ Roblox Bed Wars',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'Vào ngày sinh nhật của Naruto Uzumaki, một con quỷ huyền thoại, Cửu Vĩ Hồ, đã tấn công một ngôi làng tên là Konoha. Hokage Đệ Tứ, phải trả giá bằng mạng sống của mình, đã cứu ngôi làng bằng cách phong ấn con quỷ vào Naruto sơ sinh, vô tình đẩy cậu vào một cuộc đời bị hận thù từ những người dân làng. 
Mặc dù thiếu tài năng trong nhiều lĩnh vực nhẫn thuật, sự bồn chồn và tính kiêu ngạo, Naruto có ước mơ trở thành Hokage, ninja mạnh nhất trong làng. Khao khát sự công nhận mà cậu không có, cậu làm việc chăm chỉ và tập luyện cùng với đồng đội Sasuke Uchiha và Sakura Haruno, cũng như người cố vấn Kakashi Hatake. Cậu và những người bạn đồng hành của mình sẽ phải trải qua rất nhiều điều trên con đường đến với những giấc mơ ấp ủ: chiến đấu, tình yêu, tình bạn, sự phản bội, cơn khát quyền lực. Bộ sưu tập con trỏ anime Naruto sẽ giúp bạn định hướng con đường của riêng mình!',
    'naruto_anime_short_descr' => 'Bước trên con đường ninja của bạn với các con trỏ anime Naruto',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'Hành động diễn ra trong thời kỳ Taisho. Kể từ thời cổ đại, đã có tin đồn rằng những con quỷ hình người sống trong rừng, chúng ăn thịt người và đi lại vào ban đêm, tìm kiếm một nạn nhân mới. Nhưng... đó chỉ là một huyền thoại, phải không?..

Tanjiro Kamado là con trai cả trong gia đình, người đã mất cha và chăm sóc gia đình. Một ngày nọ, anh đến một thị trấn gần đó để bán than củi. Trở về vào buổi sáng, chàng trai phát hiện ra một cảnh tượng khủng khiếp trước mặt: tất cả người thân đều bị giết một cách tàn bạo, và người sống sót duy nhất là Nezuko, một em gái đã biến thành quỷ, nhưng vẫn chưa mất hết nhân tính.

Từ giây phút này, Tanjiro và Nezuko bắt đầu một cuộc hành trình dài và nguy hiểm, trong đó chàng trai dự định tìm ra kẻ giết người và tìm cách chữa lành cho em gái mình. Nhưng liệu những đứa trẻ có thể vượt qua mọi khó khăn và trở về nhà không? Bạn đã biết câu trả lời, và nếu không - hãy nhanh chóng cài đặt các con trỏ Demon Slayer, với các nhân vật từ một trong những bộ manga nổi tiếng nhất.',
    'demon_slayer_anime_short_descr' => 'Con trỏ Demon Slayer - dành cho những thợ săn đêm thực thụ',
    'demon_slayer_anime' => 'Anime Demon Slayer',
    'bts_descr' => 'BTS là một nhóm nhạc nam gồm bảy thành viên thuộc BigHit Music. Họ ra mắt vào ngày 13 tháng 6 năm 2013 với đĩa đơn "No More Dream". Tại Nhật Bản, họ ra mắt vào ngày 24 tháng 12 năm 2014 với album phòng thu Wake Up.

Tên của nhóm đến từ cụm từ tiếng Hàn Bangtan Sonyeondan, có nghĩa là "những hướng đạo sinh chống đạn". Theo J-Hope, cái tên này thể hiện mong muốn của ban nhạc trong việc ngăn chặn những khuôn mẫu, chỉ trích và kỳ vọng nhắm vào thanh thiếu niên như những viên đạn.

Tập hợp các con trỏ dành riêng cho nhóm bao gồm tất cả các thành viên của nhóm, ở đây là con trỏ Kim Nam Joon (hay còn gọi là RM), con trỏ Kim Seok Jin (Jin), con trỏ Min Yoongi (Suga), con trỏ Jung Ho Suk (J-Hope), con trỏ Park Ji Min (Jimin), con trỏ Kim Tae Hyun (V) và con trỏ Jeon Jungkook (Jungkook).',
    'bts_short_descr' => 'Gặp gỡ thần tượng của bạn với con trỏ BTS',
    'bts' => 'BTS',
    'miraculous_descr' => 'Miraculous: Những Chuyện Kể về Ladybug và Cat Noir, được biết đến nhiều hơn với tên Miraculous Ladybug và Cat Noir, là những cuộc phiêu lưu của các siêu anh hùng từ bộ phim hoạt hình về hai người bạn học cùng lớp, những người dưới lớp mặt nạ, đóng vai những người bảo vệ Paris khỏi một nhân vật phản diện, người mà trong mỗi tập phim đều nghĩ ra một cách mới để làm hại thành phố. Miraculous được sản xuất tại Pháp bằng cách sử dụng CGI và hoạt hình. Miraculous không chỉ là một bộ phim hoạt hình, mà còn là một bộ truyện tranh được phát hành trên toàn thế giới. Loạt phim rất được khán giả trẻ yêu thích.

Hành động diễn ra ở Paris, nơi Marinette và Adrian là học sinh trung học tại một trường hiện đại. Họ được giao vai trò trở thành người được chọn trong cuộc chiến chống lại cái ác, cứu thành phố quê hương của họ. Mục tiêu của họ là bảo vệ mọi người khỏi Akumas. Những sinh vật nhỏ bé này dưới hình dạng của những con bướm có thể cư ngụ trong một người và biến người đó thành một nhân vật phản diện.

Marinette có thể biến thành một con bọ rùa, và Adrian - thành một Cat Noir, nhưng thật ngạc nhiên, khi làm việc theo cặp, họ không nhận ra nhau dưới lớp mặt nạ của các siêu anh hùng.

Hãy giúp Cat Noir và Ladybug cứu Paris với các con trỏ của chúng tôi có các nhân vật yêu thích của bạn. Bạn sẽ chọn nhân vật nào cho con trỏ? Nó sẽ là một con trỏ Miraculous Ladybug, hoặc có lẽ là một con bọ rùa nhỏ đáng yêu của Tikki hoặc con trỏ Cat Noir? Hoặc có lẽ là một Queen Bee với các con trỏ Rena Rouge? Sự lựa chọn là của bạn!',
    'miraculous_short_descr' => 'Tham gia hàng ngũ siêu anh hùng với bộ sưu tập con trỏ Ladybug and Cat Noir',
    'miraculous' => 'Miraculous: Những chiến tích của Ladybug và Cat Noir',
    'talking_tom_descr' => 'Loạt phim theo dõi cuộc sống hàng ngày của Talking Tom và những người bạn của anh ấy. Tom và đối tác kinh doanh mọt sách Ben của anh luôn phát triển các ứng dụng di động và các phát minh khác để đạt được danh tiếng và tài sản và cố gắng thể hiện bản thân với thế giới, nhưng điều này luôn phản tác dụng. Bạn gái của Tom, Angela, cố gắng trở thành một ca sĩ, bất kể cô ấy làm gì để đạt được điều đó. Hàng xóm của Tom, Ginger, rất thường ghé vào đây để chơi khăm với sự tinh ranh trong tay áo. Người bạn thân ngu ngốc và bạn cùng phòng Hank ở nhà, xem RẤT NHIỀU TV. Và cựu ngôi sao nhạc pop bất đồng chính kiến Becca Sparkles đã trở thành bạn cùng phòng mới của Angela và dường như đã phải lòng Hank. Tuy nhiên, bất kể mọi thứ tồi tệ đến mức nào, dù là CEO độc ác, người hàng xóm bí ẩn mới của Tom hay chỉ là một tai nạn trong phát minh mới của Ben, băng đảng sẽ vui vẻ bất kể điều gì, và luôn ghi nhớ một điều gắn kết họ với nhau: tình bạn không bao giờ kết thúc, giống như tình yêu của chúng ta dành cho các nhân vật của bộ truyện không kết thúc, vì vậy bây giờ bạn có thể tự đặt con trỏ Talking Tom hoặc con trỏ Ben, hoặc có thể là con trỏ Angela, con trỏ Oliver!',
    'talking_tom_short_descr' => 'Hãy cùng nói về nhân vật yêu thích của bạn trong Bộ sưu tập con trỏ Talking Tom',
    'talking_tom' => 'Talking Tom and Friends',
    'lego_descr' => 'Công ty The LEGO Group được thành lập vào năm 1932 và khi đó chỉ có 7 người. Mục tiêu của đội Lego là tạo ra đồ chơi phát triển khả năng sáng tạo, trí tưởng tượng và sự khéo léo của trẻ. Một sự thật đáng kinh ngạc, kể từ khi thành lập vào năm 1949, các yếu tố LEGO trong tất cả các biến thể của chúng vẫn tương thích với nhau. Tất cả các mục được tạo sau này vẫn tương thích với các mục đang được phát hành ngày nay, bất chấp những thay đổi về thiết kế và hình dạng trong những năm qua.

Một viên gạch LEGO là một đế, là một khối nhựa rỗng kết nối với các viên gạch tương tự khác. Nhưng các bộ Lego cũng chứa các bộ phận khác, bánh xe, hình, bệ và thậm chí cả các mạch điện tử với cảm biến và động cơ điện. Bạn có thể thu thập các mô hình ô tô, máy bay, tàu hỏa, tàu thủy, tòa nhà, robot. LEGO tuân thủ ý tưởng về tính mô-đun, điều này cho trẻ em thấy rõ cách giải quyết một số vấn đề nhất định, phát triển trí tưởng tượng, kỹ năng vận động tinh của bàn tay và kỹ năng lắp ráp. Gạch LEGO được chế tạo với độ chính xác đáng kinh ngạc và khớp với nhau một cách hoàn hảo cho độ chính xác 10 micron tuyệt đẹp.

Gần đây, nhiều câu chuyện Lego hoạt hình 3D nổi tiếng đã được tạo ra, nơi các nhân vật từ các bộ đồ chơi trở nên sống động và trở thành những người tham gia vào những cuộc phiêu lưu đáng kinh ngạc. Nếu bạn muốn có một con trỏ thú vị, bạn sẽ tìm thấy nhiều nhân vật từ loạt phim truyền hình Lego và phim hoạt hình trong bộ sưu tập Lego Cursors của chúng tôi. Lego Ninjago Cursor, Lego Batman Cursor, Lego Ninjago Cursor, Lego Wyldstyle Cursor và nhiều hơn nữa.',
    'lego_short_descr' => 'Xây dựng trình duyệt mơ ước của bạn với bộ sưu tập con trỏ Lego',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Sau khi gây quỹ thành công trên Kickstarter, vào năm 2017, Team Cherry đã phát hành trò chơi đa nền tảng PC Hollow Knight. Đây là câu chuyện về một hiệp sĩ vô danh và những khám phá của anh ta trong vương quốc côn trùng Hallownest. Trò chơi này đã được công nhận xứng đáng là một trong những trò chơi hay nhất thuộc thể loại metroidvania.

Lối chơi của Hollow Knight dựa trên việc khám phá thế giới trò chơi. Vượt qua các chướng ngại vật, giải các câu đố và tìm kiếm bí mật, cũng như chiến đấu với kẻ thù. Người chơi có một bộ cải tiến và thủ thuật độc đáo để khám phá thế giới và chiến đấu trong các trận chiến. Di chuyển từ khu vực này sang khu vực khác, người chơi đánh bại các tên trùm và nhận được những cải tiến cần thiết để tiến xa hơn. Kết quả là, người chơi phải ghé thăm các khu vực đã đi qua để tìm bí mật và đi hết câu chuyện. Và nó cũng thú vị vì các khu vực thay đổi mỗi lần, mang đến những bất ngờ và trải nghiệm mới. Trò chơi có thể được chơi theo những cách khác nhau, bởi vì có một số con đường khác nhau giữa các khu vực. Đi qua câu chuyện, bạn mở bản đồ khu vực, nhưng trước tiên bạn cần lấy bản đồ.

Vũ khí chính của người anh hùng là một chiếc đinh, hơi giống một thanh kiếm, vũ khí có thể được cải thiện với thợ rèn, cũng như học các kỹ năng khác nhau trong việc sử dụng vũ khí, điều này mở rộng sự đa dạng của các cuộc tấn công. Bằng cách tấn công kẻ thù, bạn tích lũy một tài nguyên đặc biệt, sau này có thể được sử dụng để cải thiện hoặc chữa bệnh.
Hãy vui vẻ chơi Hollow Knight và đừng quên các con trỏ Hollow Knight của chúng tôi với nhân vật yêu thích của bạn. Bộ sưu tập của chúng tôi bao gồm Con trỏ Nấm Mister, Con trỏ Quirrel, Con trỏ Kim Hornet, Con trỏ Đinh Cũ, Con trỏ Myla và những con trỏ khác.',
    'hollow-knight_short_descr' => 'Cố gắng đừng lạc trong vương quốc của côn trùng bằng cách sử dụng bộ sưu tập con trỏ Hollow Knight',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman là nhân vật chính trong series. Stikmin, trước đây không có tên, bắt đầu là một tên trộm nhỏ, với mong muốn kiếm tiền dễ dàng một cách nhanh chóng. Tuy nhiên, sau khi vượt ngục West Mesa, nhiều thay đổi đã diễn ra trong cuộc đời anh, và anh trở thành một tên tội phạm khét tiếng sau khi đánh cắp viên kim cương Tunisian. Henry có một lựa chọn - trở thành một đặc vụ chính phủ thành công, thợ săn tiền thưởng, thủ lĩnh của một tổ chức tội phạm, người máy, hoặc tiếp tục con đường tội phạm một mình. Trò chơi làm hài lòng những người hâm mộ thể loại này với nhiều cuộc phiêu lưu và bí ẩn, và bạn sẽ tìm thấy bộ sưu tập con trỏ Henry Stickman mới của chúng tôi với những nhân vật hài hước của nó, bao gồm con trỏ Henry Stickmin, con trỏ Charles Calvin, con trỏ Reginald Copperbottom, con trỏ Right Hand, con trỏ Ellie Rose và những người khác!',
    'henry-stickmin_short_descr' => 'Lên kế hoạch trốn thoát khỏi sự buồn chán của bạn với Bộ sưu tập Con trỏ Henry Stickman',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'Trò chơi trực tuyến rất phổ biến Adopt Me được ra mắt vào năm 2017 và trở thành trò chơi phổ biến nhất trên nền tảng trò chơi Roblox. Bản chất của trò chơi rất đơn giản - nhận trứng với thú cưng và chăm sóc chúng.

Thú cưng ảo được chia thành 5 loại, một số trong số chúng rất hiếm và đắt tiền, trong khi những con khác lại rất dễ kiếm. Đây là các nhóm không phổ biến, chẳng hạn như Chó Xanh, con trỏ Chuột thông thường, con trỏ Hiếm, ví dụ, con trỏ chuột Adopt Me Khỉ, cũng như những con cực kỳ hiếm, chẳng hạn như con trỏ Koala và Huyền thoại, con trỏ Rồng và kỳ lân Accept me. Nếu người chơi có bốn thú cưng trưởng thành cùng loại, họ có thể kết hợp thành thú cưng neon, chẳng hạn như con trỏ trò chơi Neon Horse hoặc Adopt Me Neon Starfish. Bằng cách kết hợp bốn thú cưng thông thường, bạn có thể tạo ra một thú cưng neon thực sự tỏa sáng, và từ thú cưng neon, bạn có thể tạo ra một thú cưng mega-neon.

Việc mua sắm trong trò chơi Adopt Me! được thực hiện bằng tiền ảo Roblox - cái gọi là Robux, và trò chơi cũng có tiền tệ riêng - Bucks. Chăm sóc thú cưng của bạn, ngoài giải trí, bạn có thể kiếm được bucks, chỉ cần cho nó ăn, cho nó đi ngủ hoặc đọc một câu chuyện cổ tích, nói chung, rất nhiều điều thú vị.

Giờ đây, những người hâm mộ trò chơi Roblox "Adopt Me!" có thể trang trí con trỏ chuột của họ bằng thú cưng yêu thích!',
    'adopt-me_short_descr' => 'Vui vẻ với những thú cưng dễ thương trong bộ sưu tập con trỏ trò chơi Adopt Me!',
    'adopt-me' => 'Adopt me!',
    'among-us_descr' => 'Among Us dựa trên trò chơi nhập vai nổi tiếng "Mafia". Ban đầu trò chơi chỉ dành riêng cho thiết bị di động, vì nó chỉ có một bản đồ. Trò chơi nhanh chóng trở nên phổ biến. Sau đó, nhóm phát triển đã thêm chế độ nhiều người chơi và hai bản đồ bổ sung đã được phát hành vào năm 2019.
Among Us là một trò chơi góc nhìn thứ ba từ trên xuống cho phép người chơi di chuyển theo mọi hướng. Từ bốn đến mười người chơi có thể chơi trong một vòng. Khi bắt đầu trò chơi, mọi người đều được bí mật giao vai trò là kẻ phản bội hoặc thành viên phi hành đoàn. Kẻ mạo danh (trong bản dịch tiếng Nga "Kẻ phản bội") có thể trốn trong lỗ thông gió, phá hoại và giết các thành viên phi hành đoàn. Mục tiêu của nó là tiêu diệt tất cả các thành viên phi hành đoàn hoặc phá hủy tàu vũ trụ bằng hành động phá hoại. Mục tiêu của phi hành đoàn tàu là giải các câu đố khác nhau được chuẩn bị cho họ khi bắt đầu trò chơi. Nếu mỗi thành viên phi hành đoàn hoàn thành tất cả các nhiệm vụ, những kẻ phản bội sẽ thua. Ngoài ra, phi hành đoàn tàu có thể giành chiến thắng bằng cách loại bỏ những kẻ phản bội trong quá trình bỏ phiếu.
Những kẻ phản bội có thể phá hoại theo thời gian và nếu các sự cố không được khắc phục trong 30 giây, phi hành đoàn sẽ thua. Trước khi bắt đầu trò chơi, bạn có thể chọn màu sắc của nhân vật mà bạn đang chơi, xanh lam, đỏ, vàng, xám - bất cứ gì! Và đừng quên tự đặt con trỏ thích hợp từ bộ sưu tập Among Us mới!',
    'among-us_short_descr' => 'Đừng để bị lừa trong trò chơi không gian phức tạp này với các con trỏ Among Us.',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Người tạo ra "Steven Universe" là Rebecca Sugar. Cô được biết đến với tác phẩm trước đây của mình có tên là Adventure Time. Tập đầu tiên của Steven Universe được phát hành trên nền tảng video YouTube vào mùa xuân năm 2013. Nhưng vào mùa thu, kênh Cartoon Network của Mỹ bắt đầu phát sóng nó cho người xem của mình. Kể từ đó, 6 mùa đã được phát hành. Mùa thứ sáu hứa hẹn sẽ là mùa cuối cùng.
Đối với cốt truyện của loạt phim hoạt hình, nó xoay quanh đội Crystal Gems. Nó bao gồm các sinh vật ngoài hành tinh với những cái tên đặc trưng: Pearls, Amethyst và Pomegranate. Nhưng có một người tham gia khác vào nó, trong vai một cậu bé bình thường Stephen. Cùng nhau họ tìm kiếm quái vật và cố gắng vô hiệu hóa chúng để chúng không chiếm lấy Trái đất vì lợi ích cá nhân. Họ bị Jasper và Peridot phản công - những sứ giả từ hành tinh quê hương của họ, những người muốn đánh bại Gems và bật Cluster.
Nếu bạn là một fan hâm mộ của Steven Universe và muốn xem các nhân vật của bộ phim hoạt hình bất cứ nơi nào bạn có thể, hãy cài đặt tiện ích Cursor Style! Tại sao lại làm điều này? Bạn có thể thêm một bộ sưu tập dành riêng cho "Steven Universe" và biến con trỏ chuột tiêu chuẩn thành một trong những nhân vật yêu thích của bạn.',
    'steven_universe_short_descr' => 'Khám phá bí mật của Ngọc bích với các con trỏ Steven Universe',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Một bộ phim sitcom hoạt hình có tên là "Gia đình Guy" trong suốt lịch sử tồn tại của nó đã 4 lần giành giải Emmy và 3 lần giải "Annie". Loạt phim hoạt hình chế giễu các chủ đề nhức nhối của xã hội Mỹ, chẳng hạn như: nữ quyền, chế độ nô lệ, béo phì, chính trị, v.v. Không giống các tác phẩm khác, các đoạn chèn với những câu đùa và sự mỉa mai được sử dụng ở đây. Hơn nữa, trong nhiều trường hợp, chúng không được tích hợp vào cốt truyện mà tồn tại độc lập.
Một tập của loạt phim hoạt hình được tạo ra trong hơn 10 tháng. Tại sao lại lâu như vậy? Bởi vì toàn bộ hoạt hình được vẽ bằng tay. Vì lý do này, một số sự kiện được đề cập trong tác phẩm phải mất thời gian để mất đi sự liên quan. Nhưng ngay cả như vậy, bộ phim sitcom vẫn rất thú vị và được người xem trên toàn thế giới yêu thích. Rốt cuộc, ai lại không thích cười thật nhiều vào các chính trị gia, người nổi tiếng hoặc những người có những trò hề hoang dã và do đó gây ngạc nhiên hoặc thậm chí gây sốc cho những người bình thường.
Bạn có thích "Gia đình Guy" không? Bạn có một cơ hội duy nhất để biến con trỏ chuột thông thường thành bất kỳ nhân vật nào trong loạt phim hoạt hình này! Tôi cần làm gì? Chỉ cần cài đặt tiện ích mở rộng trình duyệt “Cursor Style”, thêm một bộ sưu tập dành riêng cho “Gia đình Guy” vào đó và tận hưởng một sự tái hiện tuyệt vời!',
    'family_guy_short_descr' => 'Bộ sưu tập con trỏ Family Guy dành cho những người sành về sự hài hước đặc biệt',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Chắc chắn bạn đã nghe câu nói "Vẻ đẹp sẽ cứu rỗi thế giới"? Vì vậy, nhiều người, đặc biệt là các cô gái, đồng ý với câu nói này. Do đó, họ cố gắng bao quanh bản thân bằng tất cả những gì đẹp nhất và làm hài lòng thị giác. Nó có thể là hình nền màu hồng trong phòng ngủ, đồ chơi mềm, gối thêu hạt, đồ trang sức quý giá, v.v. Nhìn từ bên ngoài, tất cả trông rất dễ thương và thậm chí hơi trẻ con. Nhưng mỗi chúng ta đều là một đứa trẻ trong tim, vậy tại sao không để nó thể hiện trí tưởng tượng của chúng ta?
Sự dịu dàng trong chúng ta có thể gây ra rất nhiều điều. Ví dụ, đôi mắt đồng cảm của một chú mèo con muốn được vuốt ve hoặc cho ăn. Một cầu vồng đa sắc, ló ra sau cơn mưa mùa xuân và lấp lánh với tất cả các màu sắc trong ánh nắng mặt trời. Đứa trẻ được đãi sô cô la, và nó quyết định chia sẻ nó với bạn gái hoặc bạn trai của mình. Có khá nhiều lý do để xúc động và chúng tôi đã quyết định sử dụng chúng làm con trỏ.
Mệt mỏi với mũi tên trắng nhàm chán trong trình duyệt của bạn? Thay thế nó bằng một thứ gì đó dễ thương từ bộ sưu tập của chúng tôi! Ví dụ, một kỳ lân màu hồng và trắng, một quả cà chua buồn bã, một đám mây đang cau có, một cây xương rồng gai có hình dạng của một con mèo, hoặc bất cứ thứ gì bạn muốn. Tất cả những gì bạn cần làm là cài đặt tiện ích mở rộng Cursor Style và thêm một bộ sưu tập con trỏ dễ thương vào đó. Và sống thật lâu, vị cứu tinh của thế giới - vẻ đẹp!',
    'cute_cursors_short_descr' => 'Thế giới sẽ trở nên tốt đẹp hơn với bộ sưu tập con trỏ dễ thương',
    'cute_cursors' => 'Con Trỏ Dễ Thương',
    'web_media_descr' => 'Trong thực tế hiện đại, hầu như ai cũng sử dụng Internet. Bắt đầu từ trẻ nhỏ và kết thúc với người đã nghỉ hưu. Người thì lướt web bằng trình duyệt, người khác xem video trên YouTube, và người khác cần Mạng để giao tiếp với những người thân yêu. Bất kỳ người dùng nào trong số này đều không thể tưởng tượng một ngày mà không có World Wide Web.
Người lớn tuổi thường ngồi trên một mạng xã hội như Facebook hoặc VK. Họ cũng thường xuyên giao tiếp với con cháu của họ trên Skype. Điều này đặc biệt tiện lợi nếu con cái và cha mẹ sống ở các thành phố khác nhau hoặc thậm chí là các quốc gia khác nhau.
Giới trẻ thích giao tiếp thông qua Viber hoặc Telegram, tải ảnh lên Instagram, cười nhạo các meme trên FB. Các video phản ứng của mọi người trên YouTube đang thu hút hàng triệu lượt xem, cũng như các trò chơi khăm hoặc thí nghiệm xã hội khác nhau. Trên Tik-Tok, hàng trăm nghìn người nhảy múa, biểu diễn ảo thuật và thể hiện bản thân.
Bạn có quan tâm hoặc thường xuyên sử dụng một loại tài nguyên nào đó từ lĩnh vực truyền thông web không? Bạn muốn loại bỏ mũi tên chuột nhàm chán trong trình duyệt của mình? Sau đó, hãy cài đặt tiện ích mở rộng và thay đổi con trỏ mặc định thành con trỏ sáng tạo của chúng tôi! Nó có thể là con trỏ YouTube, con trỏ Viber, con trỏ Google Chrome hoặc các tài nguyên khác.',
    'web_media_short_descr' => 'Sống theo nhịp điệu hiện đại với bộ sưu tập con trỏ web media',
    'web_media' => 'Web Media',
    'bobs_burgers_descr' => 'Loạt phim hoạt hình Bob’s Burgers là cốt truyện của tác phẩm hoạt hình và sức hút của các nhân vật. Và, theo đánh giá từ đề cử giải Emmy và sự công nhận của tác phẩm là một trong những phim hoạt hình hay nhất trên toàn thế giới, Bob\'s Snack thực sự đã gây được tiếng vang.
Cốt truyện của loạt phim hoạt hình xoay quanh gia đình Bob Belcher. Người này là chủ nhân của quán ăn ở tầng một, và ở tầng hai anh sống cùng những người thân yêu của mình. Bob có một người vợ vui vẻ là Linda và 3 đứa con: Gene, Louise và Tina. Cậu bé mơ ước một sự nghiệp âm nhạc, cô con gái lớn Tina rất tốt bụng, nhưng vụng về, và cô út - Louise vẫn là một cô nàng tinh ranh và thường xuyên đặt gia đình vào tình huống khó xử. Đối thủ chính của Bob’s Burgers là Tiệm bánh pizza của Jimmy Pesto. Như bạn có thể đoán, chủ sở hữu của tiệm bánh pizza này tên là Jim, và anh ta và Bob ghét nhau. Tất cả điều này đã được thể hiện để nó trông hài hước, không nghiêm túc. Vì vậy, nhiều cuộc đụng độ của họ chỉ gây ra một nụ cười.
Nếu bạn yêu thích loạt phim hoạt hình “Bob\'s Burgers” và muốn nhìn thấy các nhân vật của anh ấy không chỉ trên màn hình hoặc TV, hãy cài đặt tiện ích mở rộng, thêm một bộ sưu tập và thay đổi con trỏ chuột trong trình duyệt thành bất kỳ nhân vật nào trong phim hoạt hình này!',
    'bobs_burgers_short_descr' => 'Bob làm bánh mì kẹp thịt, và chúng tôi tạo các con trỏ Bob\'s Burgers',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'Lịch sử của trò chơi điện tử "Kirby" đã bắt đầu từ những năm 90 của thế kỷ trước. Nó bao gồm nhiều series được phát triển bởi Nintendo và HAL Laboratory. Trò chơi này dành cho trẻ em từ một tuổi rưỡi đến 8 tuổi. Mức độ phổ biến của nó có thể được đánh giá bằng số lượng bản đã bán. Hơn 34 triệu bản trên toàn thế giới.
Nhân vật chính của Kirby là sinh vật màu hồng cùng tên. Nó sống trên một hành tinh gọi là Pop Star và định kỳ bảo vệ nó khỏi nhiều mối nguy hiểm khác nhau. Kerby có thể hít vào một số đồ vật và kẻ thù của mình để sau đó học các khả năng của chúng: chiến đấu tay không, sở hữu kiếm, phun lửa, v.v. Tuy nhiên, chú bồng màu hồng không chỉ chiến đấu với kẻ thù mà còn giải các câu đố khác nhau, đi du lịch đến các quốc gia khác và thậm chí có thể bay trong các màn chơi.
Bạn có thể chơi trò chơi điện tử này trên các bảng điều khiển Nintendo hoặc Game Boy. Trong tất cả các series đều có những nhân vật dễ thương, đồ họa đẹp và nhạc nền vui nhộn. Nhân tiện, trong gần 30 năm kể từ khi phát hành phiên bản đầu tiên, thế giới đã được xem 20 series Kirby. Chỉ số này, cùng với khối lượng bản đã bán hàng triệu đô la, đã giúp trò chơi lọt vào TOP 50 trò chơi điện tử thành công và được tìm kiếm nhiều nhất trong ngành công nghiệp game.
Yêu thích Kirby đến mức bạn muốn nhìn thấy nhân vật này ở bất cứ đâu có thể? Vậy thì hãy sử dụng bộ sưu tập Kirby và biến con trỏ chuột thông thường thành nhân vật chính của trò chơi điện tử yêu thích của bạn! Chúng tôi chắc chắn rằng bạn sẽ thích giao diện mới của con trỏ.',
    'kirby_short_descr' => 'Hãy thử hít vào toàn bộ bộ sưu tập con trỏ Kirby',
    'kirby' => 'Kirby',
    'undertale_descr' => 'Vào thời cổ đại, Trái Đất không chỉ có con người mà còn có quái vật sinh sống. Do bất đồng giữa chúng, một cuộc chiến đã nổ ra, kết thúc có lợi cho loài người. Bảy nhà ảo thuật đã đẩy quái vật xuống lòng đất và giam cầm chúng ở đó mãi mãi bằng một phép thuật rào cản. Tuy nhiên, chỉ có một lối vào Mount Ebott, nơi đứa trẻ đã tận dụng. Chính vì đứa trẻ đó mà bạn sẽ chơi bằng cách chạy trò chơi máy tính Undertale.
Trò chơi này được phát triển bởi Toby Fox - một lập trình viên nổi tiếng đến từ Hoa Kỳ. Lúc đầu, chủ sở hữu máy tính cá nhân chạy hệ điều hành Microsoft Windows và Linux có thể thưởng thức nó, và sau đó là lượt của người dùng máy chơi game.
Điểm mấu chốt của trò chơi này là gì? Cậu bé đi qua thế giới ngầm nơi có quái vật sinh sống. Một số trong số chúng ngay lập tức thù địch, trong khi những kẻ khác thích nói chuyện. Người chơi có thể chọn một trong 2 hành vi: tránh bạo lực hoặc chiến đấu. Trong trường hợp đầu tiên, vượt qua trò chơi sẽ dễ dàng hơn, trong trường hợp thứ hai - ngược lại thì khó hơn. Cốt truyện và kết thúc, có thể phân nhánh và thay đổi, cũng phụ thuộc vào sự lựa chọn này.
Nếu bạn thích Underground Tale và muốn xem các nhân vật của nó trong trình duyệt của mình, hãy cài đặt tiện ích mở rộng và thêm bộ sưu tập con trỏ thích hợp! Biến con trỏ chuột nhàm chán thành một trong những con quái vật hoặc nhân vật chính của Undertale!',
    'undertale_short_descr' => 'Đã đến lúc thoát khỏi cái hố bằng cách sử dụng con trỏ Undertale.',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune là một trò chơi nhập vai được phát hành cho máy tính cách đây một vài năm. Nó được tạo ra bởi cùng một lập trình viên đã phát triển Undertale. Tuy nhiên, hai trò chơi này hầu như không giống nhau, mặc dù chúng có một vài nhân vật và địa điểm chung.
Có một số nhân vật chính trong Delta Rune. Đây là một học sinh Chris, người có thể được điều khiển, và một con quái vật quyến rũ Susie, không thể kiểm soát. Cả hai nhân vật đều rơi vào thế giới bóng tối, nơi họ gặp một trong những cư dân của nó - Ralsay. Anh ta nói với họ rằng trên thực tế, họ là những sinh vật ánh sáng có một nhiệm vụ - ngăn chặn dòng năng lượng bóng tối trong một thế giới u ám. Để làm được điều này, họ cần tha cho những con quái vật địa phương và cố gắng không tham gia vào trận chiến với chúng, mặc dù đôi khi điều này khá khó khăn để thực hiện.
Người chơi có một lựa chọn đơn giản: tha cho những sinh vật bóng tối, hoặc tấn công chúng. Vì Susie không phải là một fan hâm mộ của các biện pháp nửa vời, trong nhiều trường hợp cô ấy chọn một trận chiến. Vì vậy, Chris không còn lựa chọn nào khác ngoài việc ủng hộ bạn gái của mình và giúp đỡ cô ấy trong các trận chiến.
Yêu thích trò chơi Deltarune? Sau đó, hãy phong cách hóa con trỏ chuột của bạn trong trình duyệt cho một trong những nhân vật của cô ấy! Bạn có thể làm điều này với tiện ích mở rộng của chúng tôi. Cài đặt nó, thêm bộ sưu tập “Rune Delta” và kích hoạt! Bây giờ mũi tên của bạn đã không còn giống như mọi người khác, và đã trở thành Chris, Susie hoặc một trong những sinh vật của thế giới bóng tối.',
    'deltarune_short_descr' => 'Đắm chìm vào thế giới bóng tối với bộ sưu tập con trỏ này',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario là một series game máy tính do Nintendo phát hành. Game đầu tiên và nổi tiếng nhất có tên là Super Mario Bros. Nó ra mắt vào năm 1985. Sau đó, nó đã được liệt kê trong Sách Kỷ lục Guinness. Kể từ đó, hơn 20 game đã được phát hành, mỗi game đều có cốt truyện riêng. Vào năm 2019, một phiên bản mới xuất hiện, có tên là Super Mario Maker 2. Mặc dù đồ họa đã được cải thiện, phong cách và các nhân vật vẫn giữ nguyên, và điều này gợi lại cảm giác hoài niệm về Super Mario của thập niên 80.
Nhân vật chính vẫn là thợ sửa ống nước Mario. Trong cốt truyện của phiên bản mới nhất của game, lâu đài của Công chúa không còn một viên đá nào chưa được lật tung. Mario phải xây dựng lại nó, kiếm được những đồng xu được trả cho anh ta cho các nhiệm vụ. Tổng cộng, game này có hơn 100 cấp độ với nhiều độ khó khác nhau, có thể tùy chỉnh. Ngoài ra trong Super Mario Maker 2 còn có các chế độ chơi mới. Bạn có thể chơi bốn người cùng một lúc và ngay khi một người hoàn thành, cấp độ đó được coi là hoàn thành. Ngoài ra còn có các chế độ như: Mario Marathon, Duel và các cuộc đua Ninjik.
Bạn yêu thích Super Mario và mọi thứ liên quan đến game tuyệt vời này? Vậy thì hãy đặt con trỏ chuột được tạo theo phong cách của game platformer này! Chúng tôi chắc chắn rằng bạn sẽ thích con trỏ Mario, con trỏ Luigi, con trỏ Công chúa Peach và các con trỏ khác có trong bộ sưu tập của chúng tôi!',
    'super_mario_short_descr' => 'Đi qua vương quốc nấm với bộ sưu tập con trỏ Super Mario',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls được tạo ra chung bởi Disney Television Animation Corporation và Alex Hirsch. Buổi ra mắt được phát hành vào năm 2012 và được chiếu trên Disney Channel. Toàn bộ phần đầu tiên của loạt phim hoạt hình đã được phát sóng ở đó. Hai năm sau, phần thứ hai được phát hành, khán giả có thể xem trên kênh trước đó và trên Disney XD. Thật không may, người hâm mộ Gravity Falls đã không chờ đợi phần thứ ba và các phần tiếp theo. Những người sáng tạo đã quyết định giới hạn mình ở hai phần mà không có bất kỳ phần tiếp theo nào.
Đối với cốt truyện của bộ phim hoạt hình này, thì tất cả hành động diễn ra ở một thành phố hư cấu có tên là Gravity Falls. Hai anh em sinh đôi đến đó, tên là Mabel và Dipper. Họ ở với anh họ Stan. Anh ta có một cửa hàng bán đồ lưu niệm du lịch của riêng mình. Khi anh em cảm thấy chán vì "không làm gì", họ bắt đầu tìm kiếm cuộc phiêu lưu. Một trong số họ tìm thấy một cuốn nhật ký kỳ lạ trong rừng, kể về những điều bất thường của thị trấn này. Hai anh em sinh đôi bắt đầu tìm kiếm tác giả của nó và gặp phải những sinh vật và địa điểm khác thường. Nếu bạn quan tâm đến loạt phim hoạt hình này và bạn đã từng là người hâm mộ các nhân vật của nó, chúng tôi khuyên bạn nên xem bộ sưu tập con trỏ chuột của chúng tôi theo phong cách Gravity Falls!',
    'gravity_falls_short_descr' => 'Bắt đầu một cuộc phiêu lưu với con trỏ Gravity Falls',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Chắc chắn mọi người đều đã nghe về một bộ phim hoạt hình nổi tiếng như The Simpsons. Ngay cả những người chưa từng xem phim này cũng biết đến sự tồn tại của những nhân vật màu vàng. Và người hâm mộ rất vui mừng khi mùa tiếp theo của bộ phim hoạt hình yêu thích của họ ra mắt. Nhân tiện, vào mùa thu năm 2019, 31 mùa phim đã được phát hành. Và mùa đầu tiên xuất hiện trên màn hình TV vào năm 1989. Fox bắt đầu chiếu nó và vẫn tiếp tục làm như vậy do xếp hạng cao và sự yêu thích của khán giả.
The Simpsons là một thể loại châm biếm, chạm đến các chủ đề liên quan. Đây có thể là lối sống của người Mỹ trung bình, các vấn đề chính trị và tôn giáo, thủ đoạn "ngôi sao" của người nổi tiếng, nữ quyền, hôn nhân đồng giới. Nhìn chung, mọi thứ liên quan đến các sự kiện địa phương và toàn cầu mà Hoa Kỳ tham gia.
Hành động của bộ phim hoạt hình diễn ra ở thị trấn Springfield không tồn tại. Trên thực tế, có rất nhiều thành phố có tên đó ở Mỹ. Có lẽ đó là lý do tại sao nó được chọn để khán giả không liên kết những gì đang xảy ra trên màn hình với một địa phương cụ thể, mà chỉ đoán được điều này có thể ở đâu.
Bạn rất có thể là một fan hâm mộ của The Simpsons. Nếu không, tại sao bạn lại đọc văn bản này đến cuối? Và nếu vậy, thì bạn có cơ hội thay đổi con trỏ chuột nhàm chán thành một con trỏ được tạo theo phong cách của bộ phim hoạt hình này.',
    'simpsons_short_descr' => 'Một gia đình nhỏ vui nhộn với các con trỏ Simpsons',
    'simpsons' => 'The Simpsons',
    'youtubers_descr' => 'Nền tảng video YouTube xuất hiện vào năm 2005. Lúc đầu, các video được đăng tải chỉ vì mục đích tự thể hiện hoặc thông báo về điều gì đó. Tuy nhiên, theo thời gian, tất cả điều này đã phát triển thành một công việc kinh doanh có lợi nhuận, mang lại hàng nghìn, và đôi khi là hàng triệu đô la một tháng cho những người dùng YouTube thành công. Người làm vlog (người điều hành blog video) càng nổi tiếng, họ càng có thể kiếm được nhiều tiền hơn thông qua kênh của mình.
Một bé gái năm tuổi làm vlog kiếm được bao nhiêu, khi cha mẹ đưa bé đến những điểm tham quan thú vị nhất và quay lại những gì đang diễn ra trên camera? Chỉ là cách một đứa trẻ vui chơi trong công viên trẻ em, thể hiện cảm xúc, cách nghịch ngợm và tất cả những thứ tương tự. Số tiền thực sự đáng kinh ngạc - ngày nay, kênh của đứa trẻ đã thu hút gần 47 triệu người đăng ký và bắt đầu tạo ra thu nhập với số tiền 5 triệu rúp mỗi tháng.
Ai đó tải lên các video về cách họ thảo luận về trò chơi máy tính, ai đó beatboxing hoặc sắp xếp các trò đùa cho người qua đường trên phố. Một số người dành video của họ cho các chủ đề nhạy cảm, chẳng hạn như mối quan hệ giữa đàn ông và phụ nữ. Người dùng YouTube càng thích những thước phim này, thì mức độ phổ biến của người làm vlog càng cao.
Bộ sưu tập đã thêm con trỏ PewDiePie, con trỏ Shane Dawson, con trỏ Ray William Johnson, con trỏ Zoella, con trỏ MyLifeAsEva và những người khác.',
    'youtubers_short_descr' => 'Một thế hệ ngôi sao mới luôn trực tuyến trong bộ sưu tập YouTubers của chúng tôi',
    'youtubers' => 'YouTubers',
    'pusheen_descr' => 'Hầu hết mọi người đều biết đến chú mèo Pusheen. Mặc dù chỉ là một nhân vật trong truyện tranh thiếu nhi được phát minh 10 năm trước, nhưng chú đã có hàng triệu người hâm mộ cho đến ngày nay. Mèo Pusheen xuất hiện dưới dạng một bức tranh minh họa do nghệ sĩ Claire Belton tạo ra.
Một năm sau, chú mèo có trang riêng trên Tumblr.com và chỉ trong vài tuần đã thu hút được cả một đội quân người hâm mộ - khoảng 10.000 người. Vào năm 2013, Facebook đã háo hức đưa hình ảnh từ Pusheen vào các bộ sưu tập cùng với các biểu tượng cảm xúc khác. Sau khi đàm phán với người tạo, ý tưởng này đã được đưa vào thực tế và “gây bão” trên Internet! Hình ảnh từ mèo Pusheen được sử dụng trong trao đổi thư từ hơn 10 triệu lần mỗi ngày!
Năm 2014, một trong những nhà sản xuất đồ chơi lớn nhất tại Hoa Kỳ đã chú ý đến nhân vật này. GUND (chính cô là người đã phát minh ra gấu bông) đã cho ra mắt một cặp mô hình Pusheen. Vì thành công rất lớn, sau vài tháng, một bộ sưu tập hoàn chỉnh các đồ chơi có hình dạng chú mèo này đã được tạo ra.
Bạn có thể gặp mèo Pusheen ở đâu khác? Trong các bộ quà tặng từ Isaac Morris Ltd, trong kẹo dẻo từ Boomf và, tất nhiên, trong bộ sưu tập con trỏ Pusheen của chúng tôi!',
    'pusheen_short_descr' => 'Thêm một chút thoải mái vào trình duyệt của bạn với bộ sưu tập con trỏ Pusheen',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'Loạt phim hoạt hình đầu tiên “Rick và Morty” được phát hành vào năm 2013. Bộ phim hoạt hình này có thể được quy trực tiếp cho 2 thể loại: khoa học viễn tưởng và hài kịch. Những người tạo ra nó là Dan Harmon và Justin Royland. Ban đầu, tất cả các tập phim được trình chiếu trên kênh Cartoon Network, và sau đó chúng mới được nhân bản trong các rạp chiếu phim trực tuyến và lưu trữ video. Cứ vài năm, các mùa Rick và Morty mới lại được phát hành và vào tháng 11 năm 2019, mùa thứ tư đã ra mắt, hóa ra cũng không kém phần thú vị so với các mùa trước. Cốt truyện của bộ phim hoạt hình xoay quanh một thiên tài và đồng thời là một nhà khoa học điên tên là Rick, cũng như cháu trai tầm thường của anh - Morty. Hai nhân vật này gắn liền với nhau bằng những cuộc phiêu lưu chung ở những nơi kỳ lạ nhất. Và họ đến đó trên một chiếc đĩa bay, có khả năng di chuyển qua một đường hầm liên không gian. Như bạn có thể đoán, bộ phim hoạt hình này hơi giống bộ phim Back to the Future, nhưng nó vẫn không phải là phiên bản hoạt hình của nó. Tuy nhiên, nó đã được nhiều nhà phê bình khen ngợi vì những tập phim hài hước, sự sáng tạo và độc đáo. Bạn có muốn thấy Rick hoặc Morty không chỉ trong loạt phim này mà còn trong trình duyệt không? Nếu vậy, hãy cài đặt tiện ích mở rộng và thêm bộ sưu tập của chúng tôi dành riêng cho bộ phim hoạt hình yêu thích của bạn! Đây là con trỏ Rick Sanchez, con trỏ Morty Smith, con trỏ Súng Portal và tất nhiên là con trỏ Mr. Meeseeks.',
    'rick_and_morty_short_descr' => 'Đừng càu nhàu, chỉ cần sử dụng các con trỏ từ bộ sưu tập Rick và Morty',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Người hâm mộ bóng chày có thể được tìm thấy ở bất cứ đâu trên thế giới. Điều này đặc biệt đúng với cư dân của các quốc gia như: Hoa Kỳ, Trung Quốc, Cuba, Hàn Quốc, Nhật Bản và Venezuela. Trái với niềm tin phổ biến, bóng chày không bắt nguồn từ Mỹ, mà ở Anh. Sự đề cập và mô tả đầu tiên về bóng chày xuất hiện vào năm 1744 xa xôi, trong ấn bản tiếng Anh. Sau 145 năm, người Mỹ đã chiếm đoạt phát minh này cho riêng mình, bất chấp sự thật.
Giải Quốc gia được thành lập vào năm 1876. Nó là một phần của Giải đấu lớn ở Canada và Hoa Kỳ. Ngày nay, có 15 đội trong Giải bóng chày quốc gia. Trong phần cuối cùng của mỗi mùa giải, thời gian của vòng play-off đến, trong đó 4 đội xuất sắc nhất tham gia. Vì vậy, người chiến thắng của toàn bộ Giải Quốc gia được tiết lộ. Sau đó, đội chiến thắng có cơ hội thi đấu với đội chiến thắng đến từ Giải bóng chày Mỹ trong World Series.
Bạn có quan tâm đến bóng chày hoặc thậm chí cổ vũ cho một trong những đội không? Sau đó, hãy tri ân đội bóng yêu thích của bạn bằng cách đặt con trỏ chuột dưới dạng thuộc tính của nó! Thay đổi giao diện nhàm chán của con trỏ trong trình duyệt thành bản sắc doanh nghiệp bóng chày quen thuộc! Biến mũi tên thành gậy hoặc mũ bảo hiểm của người chơi trong bất kỳ đội nào của Giải Quốc gia, trong đó đã bao gồm con trỏ New York Yankees, con trỏ Great Falls Dodgers, con trỏ Boston Red Sox, con trỏ Baltimore Orioles, con trỏ Oakland Athletics.',
    'mlb_teams_short_descr' => 'Bộ sưu tập con trỏ Đội MLB dành cho tất cả người hâm mộ của chúng ta.',
    'mlb_teams' => 'Đội MLB',
    'brawl_stars_descr' => 'Brawl Stars là một game di động thuộc thể loại MOBA của Supercell. Mặc dù được phát hành vào cuối năm 2018, trò chơi đã đạt được sự phổ biến rộng rãi, phần lớn là do sự phong phú của các chế độ chiến đấu và các anh hùng kỳ ảo, đầy màu sắc - những người chơi. Người chơi có rất nhiều thứ để lựa chọn - 32 nhân vật độc đáo và mỗi người trong số họ có bộ kỹ năng và khả năng riêng. Mỗi anh hùng cũng có kỹ năng bị động riêng, có sẵn thông qua rương chiến lợi phẩm. Người chơi có thể chiến đấu trong một số chế độ, ví dụ, "Phần thưởng cho việc chiếm giữ" - một trong hai đội chiến thắng, đội nào thu thập được nhiều sao hơn, tiêu diệt đối thủ. Trong chế độ "cướp", cần phải phá vỡ két sắt của đối thủ, đồng thời bảo vệ của mình. Một chế độ “Gem Grab” thú vị - đội trở thành người chiến thắng, đội thu thập được nhiều ngọc nhất sẽ thắng. Chà, trong chế độ "Va chạm", 10 người chơi chiến đấu với nhau trên bản đồ, nơi các ranh giới bị thu hẹp do một đám mây độc hại. Trò chơi tràn ngập một thiết kế đầy màu sắc mà nhiều người thích, bao gồm cả chúng tôi, điều này đã truyền cảm hứng cho chúng tôi tạo ra một bộ sưu tập con trỏ Brawl Stars riêng biệt. Có con trỏ Shelley Brawl Stars, con trỏ Barley, con trỏ Penny, con trỏ Frank, con trỏ Mortis và những người khác.',
    'brawl_stars_short_descr' => 'Chọn con trỏ Brawl Stars và để trận chiến bắt đầu',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Thay đổi con trỏ chuột của bạn chỉ trong hai cú nhấp chuột! Bộ sưu tập miễn phí cho mọi sở thích.',
    'all_descr' => 'Nếu bạn từng nghĩ về cách thay đổi con trỏ chuột nhàm chán, thì bộ sưu tập con trỏ của chúng tôi là dành cho bạn! Tại đây, bạn sẽ tìm thấy những anh hùng truyện tranh ngầu lòi, con trỏ đẹp mắt dành cho game thủ với các nhân vật từ các trò chơi phổ biến, bộ con trỏ vui nhộn để chơi khăm, con trỏ màu và nhiều tùy chọn thú vị khác.',
    'text_title' => 'Bộ sưu tập con trỏ chuột thú vị và hài hước nhất cho mọi ngày',
    'text_allcat_title' => 'Con trỏ chuột độc đáo và sáng tạo để phù hợp với mọi tâm trạng của bạn',
    'text_1' => 'Bạn không muốn giống như mọi người khác? Hoặc chỉ yêu thích những thứ khác thường? Muốn trở thành một phần của anh hùng trò chơi hoặc nhân vật hoạt hình yêu thích của bạn? Vậy thì bạn đã đến đúng địa chỉ. Tại đây, bạn sẽ tìm thấy những bộ con trỏ chuột tươi sáng, khác thường có thể thay thế cho mũi tên trắng quen thuộc và đã khá nhàm chán. Con trỏ chuột đồng hành cùng chúng ta cả ngày trong công việc và học tập, vì vậy nó nên mang lại tâm trạng tuyệt vời và tạo ra sự tích cực.',
    'text_2' => 'Tại đây bạn sẽ tìm thấy các con trỏ dành cho game thủ và những người yêu thích phim ảnh, những con trỏ đẹp dựa trên các phim hoạt hình yêu thích của bạn và các động lực thể thao dành cho những người năng động nhất. Bạn có thích truyện tranh hay không thể tưởng tượng một ngày nào đó mà không có những meme hài hước? Bạn có yêu động vật hoặc mơ ước được đến thăm tất cả các quốc gia trên thế giới không? Mọi thứ đều đơn giản - chúng tôi cũng có một hình ảnh con trỏ phù hợp với bạn. Bạn cũng có thể chọn hình ảnh tùy thuộc vào những gì bạn đang làm việc. Ví dụ, một con trỏ màu đen sẽ tiện lợi hơn nhiều so với màu trắng khi làm việc với tài liệu hoặc bản vẽ và một con trỏ hình bàn tay sẽ tiện lợi hơn nếu bạn phải làm việc với các yếu tố đồ họa nhỏ. Hãy chọn hình ảnh yêu thích của bạn, điều chỉnh kích thước của nó trực tiếp trong tiện ích mở rộng - và sử dụng nó một cách vui vẻ, mỗi ngày bắt đầu với một nốt tích cực!',
    'install_to_preview' => 'Vui lòng cài đặt tiện ích để xem trước',
    'install' => 'Cài đặt',
    'add_button' => 'Thêm',
    'preview_button' => 'Xem trước',
    'added_button' => 'Đã thêm',
    'add_cursor' => 'Thêm con trỏ',
    'to_your_collection' => 'vào bộ sưu tập của bạn',
    'prev_text_1' => 'Xem trước toàn màn hình',
    'prev_text_2' => 'con trỏ',
    'cursor' => 'con trỏ',
    'pointer' => 'con trỏ',
    'a_title_1' => 'Cursor Style - Con trỏ chuột thú vị cho trình duyệt của bạn',
    'a_title_2' => 'Bộ sưu tập con trỏ chuột theo chủ đề thú vị',
    'mouse_cursors' => 'Con trỏ chuột',
    'cursor_collection' => 'Bộ sưu tập con trỏ',
    'sborka_cursorov' => 'Bộ sưu tập con trỏ',
    'collection_list_from_colllection' => 'Danh sách con trỏ - ',
    'christmas' => 'Giáng Sinh',
    'nhl_teams' => 'Giải khúc côn cầu trên băng quốc gia',
    'neon' => 'Đèn Nê-ông',
    'adventure_time' => 'Adventure Time (Giờ Phiêu Lưu)',
    'nba_teams' => 'Hiệp hội bóng rổ quốc gia',
    'spongebob' => 'SpongeBob (Bọt Biển)',
    'phineas_and_ferb' => 'Phineas and Ferb (Phineas và Ferb)',
    'fortnite_chapter_2' => 'Fortnite Chương 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Người nổi tiếng',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Truyện tranh',
    'igry' => 'Trò chơi',
    'multfilmy' => 'Hoạt hình',
    'kino_i_serialy' => 'Phim ảnh',
    'anime' => 'Anime',
    'futbol' => 'Bóng đá',
    'avtomobili' => 'Xe hơi',
    'memy' => 'Memes',
    'emodji' => 'Emoji',
    'pitomcy' => 'Thú cưng',
    'stil_i_krasota' => 'Thời trang và phong cách',
    'prazdniki' => 'Ngày lễ',
    'flagi' => 'Cờ',
    'vokrug_sveta' => 'Vòng quanh thế giới',
    'eda_i_napitki' => 'Đồ ăn và thức uống',
    'cvetnye' => 'Màu sắc',
    'prank' => 'Trò đùa',
    'startovyj_nabor' => 'Bộ khởi động',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Ông già Noel sẽ thích các con trỏ Giáng sinh của bạn',
    'nhl_teams_short_descr' => 'Một bộ sưu tập các con trỏ NHL dành cho người hâm mộ thực thụ',
    'neon_short_descr' => 'Thêm độ sáng với bộ sưu tập neon',
    'adventure_time_short_descr' => 'Học Toán cùng bộ sưu tập con trỏ Adventure Time',
    'nba_teams_short_descr' => 'Con trỏ NBA là biểu tượng của những chiến thắng bóng rổ vĩ đại',
    'spongebob_short_descr' => 'Khám phá ai sống dưới đáy biển với bộ sưu tập con trỏ SpongeBob',
    'phineas_and_ferb_short_descr' => 'Chắc chắn bạn sẽ không cảm thấy nhàm chán với bộ sưu tập con trỏ Phineas and Ferb',
    'fortnite_chapter_2_short_descr' => 'Chương mới của trò chơi đình đám Fortnite',
    'pokemon_short_descr' => 'Bắt lấy tất cả nếu bạn có thể',
    'famous_people_short_descr' => 'Truyền cảm hứng từ con trỏ thần tượng của bạn',
    'the_elder_scrools_short_descr' => 'Đắm mình trong thế giới của hiệp sĩ và rồng',
    'halloween_short_descr' => 'Hãy sợ bỏ lỡ bộ sưu tập Halloween mới',
    'nfl_teams_short_descr' => 'Dành cho những người hâm mộ bóng đá thực thụ',
    'five_nights_at_freddy_short_descr' => 'Cố gắng đừng sợ những animatronics này',
    'komiksy_short_descr' => 'Con trỏ theo truyện tranh: chọn tâm trạng của bạn ngày hôm nay.',
    'igry_short_descr' => 'Thực tế ảo: hôm nay bạn đang chơi ai?',
    'multfilmy_short_descr' => 'Các nhân vật hoạt hình yêu thích trong một thiết kế mới',
    'kino_i_serialy_short_descr' => 'Chúa tể của con trỏ: Hiệp hội của Màn hình nền',
    'anime_short_descr' => 'Mọi người đều yêu thích anime: nhân vật yêu thích của bạn là ai?',
    'futbol_short_descr' => 'Bạn có phải là một người hâm mộ thể thao thực sự? Vậy thì bạn cần phải ở đây.',
    'avtomobili_short_descr' => 'Chiếc xe trong mơ của bạn: một đội xe lớn cho các chuyên gia.',
    'memy_short_descr' => 'Động cơ yêu thích: Bộ sưu tập con trỏ Meme.',
    'emodji_short_descr' => 'Thể hiện tâm trạng thật của bạn với mọi người – cài đặt Cursoji!',
    'pitomcy_short_descr' => 'Các con trỏ sáng tạo dành cho những người yêu tất cả các bạn nhỏ bé của chúng ta.',
    'stil_i_krasota_short_descr' => 'Các con trỏ độc đáo cho mọi dịp.',
    'prazdniki_short_descr' => 'Có gì trên lịch đây? Bộ Sưu Tập Con Trỏ Ngày Lễ Mới!',
    'flagi_short_descr' => 'Tìm kiếm cuộc phiêu lưu: hôm nay chúng ta đi đâu?',
    'vokrug_sveta_short_descr' => 'Vòng quanh thế giới trong chớp mắt: hôm nay chúng ta sẽ đi đâu?',
    'eda_i_napitki_short_descr' => 'Các con trỏ ngon miệng cho sự sáng tạo',
    'cvetnye_short_descr' => 'Tô điểm cuộc sống của bạn bằng những màu sắc tươi sáng và nét vẽ táo bạo',
    'prank_short_descr' => 'Một bộ con trỏ cho những trò đùa vui nhộn nhất',
    'startovyj_nabor_short_descr' => 'Một cái nhìn mới mẻ về những thứ quen thuộc: một bộ con trỏ được cập nhật',
    'fortnite_short_descr' => 'Theo dõi các streamer!',
    'dota_2_short_descr' => 'Biến thế giới ảo của bạn thành hiện thực!',
    'minecraft_short_descr' => 'Các nhân vật trong trò chơi yêu thích của bạn luôn ở gần bạn',
    'christmas_descr' => 'Chắc hẳn mỗi chúng ta đều đang mong chờ kỳ nghỉ lễ phổ biến nhất - Giáng sinh. Tất cả các tín đồ Cơ đốc giáo trên thế giới truyền thống kỷ niệm nó hàng năm, vào ngày 25 tháng 12. Một thời điểm mà các gia đình tụ họp tại một bàn ăn, chia sẻ niềm vui và tình yêu thương, trao đổi quà tặng. Rất lâu trước Giáng sinh, mọi người trang trí đường phố bằng những vòng hoa rực rỡ, và nhà của họ bằng những biểu tượng truyền thống. Thật khó để tìm thấy một người không thích Giáng sinh - một ngày lễ vui vẻ và bí ẩn, bởi vì nó đi kèm với nhiều truyền thống và nghi lễ, chúng đưa chúng ta trở lại cội nguồn của cả gia đình. Vào đêm Giáng sinh, theo nghĩa đen, mọi thứ đều thấm nhuần tinh thần của nó, từ bánh gừng được vẽ đến những bài thánh ca xúc động. Cây thông Noel thanh lịch và những món quà dưới nó, một niềm vui quen thuộc với mỗi chúng ta từ thời thơ ấu. Chúng tôi muốn tham gia vào kỳ nghỉ lễ kỳ diệu này và, ai biết được, có lẽ ông già Noel sẽ chuẩn bị một món quà đặc biệt cho bạn nếu bạn trang trí con trỏ của mình bằng bộ sưu tập Giáng sinh của chúng tôi. Có mọi thứ bạn cần cho việc này, con trỏ ông già Noel, con trỏ cây thông Noel, con trỏ bánh gừng, con trỏ người tuyết và thậm chí cả con trỏ túi quà. Giáng sinh vui vẻ!',
    'nhl_teams_descr' => 'National Hockey League được thành lập vào năm 1917 - đây là một tổ chức thể thao chuyên nghiệp tập hợp các câu lạc bộ khúc côn cầu từ Hoa Kỳ và Canada. Và đây là một trong những giải đấu khúc côn cầu chuyên nghiệp đầu tiên trên thế giới. NHL là một trong những giải đấu thể thao hàng đầu Bắc Mỹ, cùng với NFL, NBA, Major League Baseball và MLS. Mỗi năm, 31 đội từ 30 thành phố ở Hoa Kỳ và Canada tranh giành chiếc cúp chính - Stanley Cup, và đội ghi được nhiều điểm nhất trong mùa giải thông thường sẽ được trao tặng Presidential Cup. Đã đến lúc chúng ta tôn vinh trò chơi tuyệt vời này bằng cách tạo ra một bộ sưu tập con trỏ chuột NHL. Nếu bạn cũng thích khúc côn cầu, hãy cổ vũ cho câu lạc bộ yêu thích của bạn hoặc tự mình tham gia môn thể thao này, chỉ cần thay đổi con trỏ chuột và không chia tay với đội bóng yêu thích của bạn, bao gồm con trỏ chuột Boston Bruins, con trỏ chuột St. Louis Blues, con trỏ chuột Columbus Blue Jackets, con trỏ chuột Tampa Bay Lightning, con trỏ chuột Dallas Stars và các câu lạc bộ khác xứng đáng được tôn trọng chân thành.',
    'neon_descr' => 'Chúng tôi đã tạo ra một bộ sưu tập con trỏ neon độc đáo để thêm sự đa dạng cho việc lướt internet hàng ngày và thêm một chút sáng sủa cho ánh đèn neon đầy mê hoặc. Hãy để những màu sắc phong phú của chúng tạo ra bầu không khí bao trùm của thành phố về đêm, mang lại cảm hứng để tạo ra những điều mới. Trong thế giới hiện đại, ánh đèn của một đô thị luôn báo hiệu sự xuất hiện của màn đêm, chúng theo chúng ta trên mọi con phố và ánh sáng này tràn đầy năng lượng. Hãy để nó cũng được theo sau bởi con trỏ kem phát sáng, con trỏ xúc xích ngon miệng, con trỏ burger ngon ngọt, con trỏ kim cương lấp lánh và các con trỏ khác từ bộ sưu tập neon mới.',
    'adventure_time_descr' => '"Adventure Time" là một bộ phim hoạt hình thuộc thể loại giả tưởng, trong đó hành động diễn ra trong một thế giới đã sống sót sau ngày tận thế. Lãnh thổ này được gọi là Land Ooo, nơi đã từng trải qua một cuộc chiến tranh hạt nhân. Nhưng tất cả điều này đã ở trong quá khứ, tuy nhiên, tất cả những người sống sót đều bị đột biến và thế giới tràn ngập phép thuật. Nhân vật chính của bộ phim hoạt hình là Finn, một cậu bé 14 tuổi và người bạn của cậu, một con chó tên là Jake. Cậu bé và chú chó rất thích phiêu lưu, họ luôn giúp đỡ bất cứ ai gặp khó khăn. Hai người bạn sống trên một cái cây và dành toàn bộ thời gian bên nhau. Nếu bạn muốn đắm mình vào một thế giới phiêu lưu với những người hâm mộ khác,hãy hét lên "Mathematics". Ở đây có cả con trỏ Finn Boy và con trỏ Jake, cũng như con trỏ Princess Chewing gum. Tất nhiên, chúng tôi không quên con trỏ Bimo, con trỏ Ice King và những người khác.',
    'nba_teams_descr' => 'Nếu bóng rổ là trò chơi yêu thích của bạn, giống như của chúng tôi, thì bộ sưu tập con trỏ dành riêng cho các đội NBA là thứ bạn cần. NBA là một trong những hiệp hội thể thao hàng đầu của lục địa Bắc Mỹ. Khi chúng tôi tạo ra bộ sưu tập này, chúng tôi đã bị hành hạ bởi sự lựa chọn - chọn đội nào, vì có ba mươi đội trong NBA. Nhưng có những đội là huyền thoại. Đây là Chicago Bulls, lập kỷ lục về số trận thắng vào giữa những năm 90. Đây là Golden State Warriors, đã tập hợp những cầu thủ giỏi nhất giải đấu cách đây vài năm. Hoặc, ví dụ, Lakers, Celtics cũng là những đội cực kỳ tuyệt vời. Nếu bạn, giống như chúng tôi, mong chờ các trận đấu của các đội bóng rổ yêu thích của bạn và muốn thể hiện sự ủng hộ của bạn đối với đội hoặc các cầu thủ, hãy tải xuống bộ sưu tập con trỏ NBA của chúng tôi.',
    'spongebob_descr' => 'Loạt phim hoạt hình "SpongeBob SquarePants" được rất nhiều người biết đến. Nó đã thành công vang dội sau khi Nickelodeon vào năm 1999 quyết định tạo ra một loạt phim hoạt hình dựa trên truyện tranh giáo dục Tide Zone, và nó đã trở thành một thương hiệu rất sinh lợi. Người tạo ra bộ phim là một cựu nhân viên của phòng thí nghiệm hải dương học, đó là lý do tại sao gần như tất cả các nhân vật trong phim hoạt hình đều là những cư dân vui nhộn của đáy biển, với những đặc điểm và sức hút riêng. Hành động xoay quanh công thức Krabsburger bí mật mà chỉ nhân vật chính mới có thể nấu - Sponge Bob. Và những cư dân khác của biển cả ngày đang cố gắng để có được nó, bao gồm cả nhân vật phản diện chính Sheldon Plankton, người không đạt được nó mỗi lần. Trong bộ sưu tập con trỏ SpongeBob, chúng tôi đã thu thập các con trỏ của tất cả các nhân vật và sự kiện đáng chú ý của bộ phim. Ví dụ, con trỏ của Mr. Krabs với đồng đô la, con trỏ của Patrick Star, Squidward với chiếc clarinet của anh ấy, con trỏ của sứa, con trỏ của Sponge Bob và nhiều nhân vật khác.',
    'phineas_and_ferb_descr' => 'Trong thành phố hư cấu Denville của Trishtatya không tồn tại ở Mỹ, có hai cậu bé thú vị sinh sống. Mỗi ngày trong kỳ nghỉ của họ biến thành những cuộc phiêu lưu đáng kinh ngạc, bởi vì họ có thể tạo ra một tàu lượn có kích thước bằng cả một thành phố hoặc một cánh cổng thực sự đến một hành tinh khác. Họ chia sẻ những trò giải trí tuyệt vời của mình với bạn bè. Đồng thời, trong khi các cậu bé đang vui vẻ, nhà khoa học độc ác Heinz Fufelschmertz đang chế tạo một cỗ máy độc ác khác gây ra sự hỗn loạn, với cái tên kết thúc bằng "-inator", với sự giúp đỡ của nó, hắn muốn trả thù những bất bình thời thơ ấu hoặc giành quyền lực ở Trishtat, nhưng Perry đang cản trở hắn - Utkonos, "Đặc vụ Pi" bí mật, hoạt động dưới vỏ bọc là thú cưng của các cậu bé. Sự phổ biến của bộ phim hoạt hình này, cả ở trẻ em và người lớn, đã truyền cảm hứng cho chúng tôi tạo ra một bộ sưu tập con trỏ Phineas và Ferb để bạn có thể thay đổi con trỏ chuột của mình thành các nhân vật trong sê-ri. Trong số đó có con trỏ Phineas Flynn, con trỏ Tiến sĩ Heinz Fufelschmertz, con trỏ Ferb Fletcher, con trỏ Candace Gertrude Flynn và con trỏ mỏ vịt Perry.',
    'fortnite_chapter_2_descr' => 'Chương thứ hai của Fortnite đã đến sau một sự kiện lớn - The End, đã kéo mọi thứ mà người chơi trong trò chơi yêu thích vào một hố đen. Fortnite Chapter 2 hiện có một bản đồ mới, thoạt nhìn còn hoang dã hơn cả bản đồ gốc, cũng như nhiều thay đổi trong cơ chế trò chơi và tất nhiên là rất nhiều nội dung trò chơi mới! Phương tiện, cảm xúc, cơ chế bơi lội và nhiều thứ khác - tất cả đều có trong những hình ảnh tươi mới, thú vị, tất cả đều như bạn yêu thích và đánh giá cao trong trò chơi văn hóa này. Đắm mình trong một thế giới mới - chọn một địa điểm hạ cánh và khám phá một hòn đảo hoàn toàn mới với 13 địa điểm. Bơi lội, câu cá, thuyền máy - đây là một gameplay mới dưới nước. Vui hơn và ít tốn sức hơn - nâng cấp một chương 2 hoàn toàn mới và đừng quên thay đổi con trỏ thành các skin và vũ khí mới. Bạn đã chờ đợi giao diện con trỏ Turk, con trỏ Riptide, con trỏ Rippley, con trỏ Remedy, con trỏ Toxin, con trỏ 8-Ball, con trỏ Fusion và những con trỏ khác!',
    'pokemon_descr' => 'Từ "pokemon" có nghĩa là một sinh vật có siêu năng lực. Chúng có trí thông minh, và một số thậm chí có thể nói chuyện. Hiện tại, đã có 802 loại Pokemon. Trong vũ trụ Pokémon được tạo ra, mọi người được gọi là huấn luyện viên Pokémon, những người huấn luyện chúng để chiến đấu với Pokémon của các huấn luyện viên khác. Và huấn luyện viên càng có kinh nghiệm và mạnh mẽ, họ càng nhận được nhiều sự tôn trọng. Rất may, cần lưu ý rằng các trận chiến của Pokemon không bao giờ kết thúc bằng cái chết của những sinh vật độc đáo này. Tất cả Pokemon đều có khả năng khác nhau và khác nhau về loại nguyên tố, và khả năng chống lại các đòn tấn công khác nhau của nó phụ thuộc rất nhiều vào điều này, và một số sinh vật có khả năng của hai nguyên tố cùng một lúc. Sau khi giành chiến thắng trong trận chiến, Pokemon sẽ nhận được kinh nghiệm quý báu cần thiết để tăng cấp và theo đó là các đặc điểm của nó. Ngày nay, vũ trụ Pokémon là một nhượng quyền thương mại truyền thông khổng lồ và chúng tôi sẽ quyết định chuẩn bị cho bạn một bộ sưu tập con trỏ với một số Pokémon phổ biến. Trong số đó, nổi tiếng nhất là con trỏ Pikachu, cũng như con trỏ Rattata, con trỏ Squirt, con trỏ Bulbasaur và con trỏ Charmander. Danh sách này sẽ được cập nhật, bởi vì có rất nhiều chúng và mỗi loài đều độc đáo theo cách riêng của nó.',
    'famous_people_descr' => 'Trong số nhiều người nổi tiếng, mỗi người chúng ta đều tìm thấy một hình mẫu hoặc đơn giản là ngưỡng mộ thiên tài, tài năng và sự kiên trì của những người nổi tiếng này. Chúng tôi đã chuẩn bị một bộ sưu tập con trỏ người nổi tiếng để truyền cảm hứng cho bạn và nhắc nhở bạn về những thành tựu to lớn mà mỗi người trong số các bạn có thể gia tăng. Không phải tất cả những người nổi tiếng đều có một số phận hạnh phúc, nhưng họ dạy chúng ta điều chính là bạn không bao giờ cần phải rút lui khỏi mục tiêu ấp ủ của mình, bất chấp những khó khăn và vấn đề. Rốt cuộc, đây là nguyên tắc chính để đạt được thành công - đi đến ước mơ của bạn mỗi ngày và cuối cùng, trở thành người giỏi nhất trong lĩnh vực của bạn. Có lẽ hôm nay bạn chỉ muốn thay đổi con trỏ chuột của mình và ngày mai cả cuộc đời bạn sẽ thay đổi theo chiều hướng tốt hơn! Bộ sưu tập sẽ liên tục được cập nhật với những đại diện xứng đáng mới của nhân loại. Trong số đó, tất nhiên, có các nhà khoa học, chính trị gia, vận động viên, đại diện của nghệ thuật và nhiều người khác. Con trỏ George Washington, con trỏ Michael Jordan, con trỏ Stephen King, con trỏ Elvis Presley và con trỏ Marilyn Monroe chỉ là sự khởi đầu.',
    'the_elder_scrools_descr' => 'The Elder Scrolls là một series game nhập vai trên máy tính, được thống nhất bởi một vũ trụ được thiết kế tỉ mỉ, cung cấp cho người chơi sự tự do lựa chọn to lớn, cho phép họ ghé thăm các khu vực và thành phố khác nhau của thế giới giả tưởng và khám phá những địa điểm và nhiệm vụ mới theo cách của riêng họ. Công việc trên series bắt đầu từ năm 1992 và trong những năm qua, trò chơi đã đoàn kết một cộng đồng người chơi khổng lồ xung quanh nó. Do đó, theo yêu cầu của công chúng, chúng tôi đã phát hành một bộ sưu tập con trỏ The Elder Scrolls, vì vậy bạn có thể đắm mình trong bầu không khí độc đáo của trò chơi. Cuộc chiến vĩnh cửu của các hiệp sĩ và rồng, bạn đứng về phía nào? Thay đổi con trỏ thành một con rồng và tham gia vào đội quân quái vật phun lửa hoặc chiến đấu một cách cao thượng về phía con người bằng cách chọn con trỏ kiếm và hình ảnh nhân vật yêu thích của bạn - quyết định là của bạn! Điều chính là, với bộ sưu tập mới của chúng tôi, bạn đã sẵn sàng cho mọi trận chiến.',
    'halloween_descr' => 'Chờ đợi một đêm huyền bí vào đêm trước Lễ hội All Saints. Lịch sử của Halloween đã có từ hơn hai ngàn năm trước. Có lẽ đây là ngày lễ kỳ lạ nhất kết hợp giữa sự vui vẻ và sợ hãi, một người bản địa của văn hóa Celtic. Khi đó, mọi người đốt lửa trại và mặc những bộ trang phục đáng sợ để xua đuổi ma quỷ. Từ "Halloween" lần đầu tiên được nhắc đến vào thế kỷ 16, là một từ viết tắt của Scotland trong cụm từ tiếng Anh All-Hallows-Even. Giáo hoàng Gregory III đã tuyên bố ngày 1 tháng 11 là Ngày Các Thánh, và buổi tối trước đó được gọi là Đêm trước Lễ Các Thánh, và sau này là Halloween. Vào ngày này, mọi người mặc trang phục người sói, ma và những con quái vật khác và đến các ngôi nhà lân cận, đề nghị mua kẹo. Các bữa tiệc theo chủ đề, pháo hoa, đèn lồng đẹp, bí ngô và pha nguy hiểm tạo nên một bầu không khí độc đáo. Chúng tôi cũng muốn kỷ niệm ngày lễ kinh hoàng này với các con trỏ phụ kiện và các nhân vật Halloween. Trong bộ sưu tập của chúng tôi, bạn có thể tìm thấy: con trỏ zombie, con trỏ ma, con trỏ mèo đen, con trỏ bí ngô và nhiều hơn nữa. Thay đổi tâm trạng của bạn bây giờ dễ dàng như thay đổi con trỏ của bạn với bộ sưu tập Halloween mới của chúng tôi.',
    'nfl_teams_descr' => 'Còn gì tuyệt vời hơn cho một người hâm mộ bóng đá Mỹ đích thực ngoài một con trỏ chuột dưới dạng biểu tượng của đội mà người đó là một fan hâm mộ? Trong Liên đoàn Bóng đá Quốc gia hiện đại, ba mươi hai đội chơi, được chia giữa Hội nghị Bóng đá Quốc gia và Mỹ (Hội nghị Bóng đá Quốc gia, NFC và Hội nghị Bóng đá Mỹ, AFC). Đổi lại, mỗi hội nghị được chia thành bốn khu vực: Đông, Bắc, Nam và Tây. Mùa giải NFL bao gồm các trận đấu trước mùa giải, một mùa giải thông thường và một loạt các trận đấu play-off. Trận đấu cuối cùng của mùa giải NFL được gọi là Super Bowl và về bản chất là sự kiện thể thao phổ biến nhất ở Hoa Kỳ. Đây là một trò chơi yêu thích đối với hàng triệu người hâm mộ và do đó, chúng tôi đã tạo ra một bộ sưu tập các con trỏ NFL để bạn không chia tay với các biểu tượng của đội yêu thích của mình. Dù là New England Patriots, New York Giants, Buffalo Bills hay một đội khác, luôn ở cùng tần số với thần tượng của bạn, sử dụng con trỏ của chúng tôi dưới dạng logo và mũ bảo hiểm của đội. Bộ sưu tập sẽ liên tục được cập nhật để mọi người có thể thay đổi con trỏ thành hình ảnh của đội yêu thích của họ.',
    'five_nights_at_freddy_descr' => 'Trò chơi độc đáo Five Nights at Freddy\'s nhanh chóng trở nên phổ biến rộng rãi và điều này không có gì đáng ngạc nhiên, bởi vì cốt truyện đơn giản nhưng đồng thời hấp dẫn của nó có thể giữ người chơi trên màn hình hàng giờ. Chúng tôi đã thiết kế các con trỏ Five Nights at Freddy\'s theo yêu cầu của những người hâm mộ trò chơi và rất vui khi thể hiện những nhân vật thú vị và hài hước như vậy. Nhưng không giống như trong trò chơi, không có gì đe dọa bạn với các con trỏ của chúng tôi, vì vậy hãy thoải mái chọn animatronics yêu thích của bạn, cho dù đó là Bear Freddy hay Rabbit Bonnie hoặc những người khác. Điều chính là bây giờ trò chơi trở nên sống động trong trình duyệt của bạn và mang lại những cảm xúc mới mẻ. Chúng tôi đảm bảo rằng không có ma trong các con trỏ của chúng tôi, nhưng chúng truyền tải hoàn hảo tinh thần của một trò chơi gây sợ hãi do sự phức tạp của thiết kế và các yếu tố cốt truyện. Nhưng điều gì sẽ xảy ra nếu bạn đặt kích thước con trỏ rất lớn? Bạn có thể giữ bình tĩnh và không sợ hãi không?',
    'komiksy_descr' => 'Có vẻ như con trỏ chuột là một điều nhỏ nhặt, nhưng thường thì chính những chi tiết như vậy có thể cải thiện tâm trạng của bạn, đánh thức bạn vào buổi sáng xám xịt hoặc chỉ đơn giản là mang lại những cảm xúc tươi sáng. Một bộ sưu tập các con trỏ truyện tranh được thiết kế đặc biệt cho tất cả những người yêu thích siêu anh hùng. Tại đây, bạn có thể tìm thấy tất cả các nhân vật của Vũ trụ Marvel và DC Comics - từ Iron Man đến Thanos, Spider-Man và Hulk. Kiểu con trỏ có thể ở dạng một siêu anh hùng hoặc ở dạng nhân vật của anh ta. Con trỏ không chỉ là một yếu tố chức năng; nó quan trọng theo nghĩa chuyên môn. Ví dụ, nếu bạn đang ghi lại một video từ màn hình, sẽ tốt hơn nếu bạn nhìn thấy một hình ảnh tươi sáng, độc đáo và nó trông thú vị hơn nhiều. Và tất nhiên - ai mà không muốn sử dụng găng tay vô cực trong đời thực? Thay đổi con trỏ chuột rất đơn giản - chỉ cần tải xuống tiện ích mở rộng cho trình duyệt của bạn và thêm con trỏ bạn thích vào cài đặt của bạn thông qua nó. Bạn có thể chọn một con trỏ theo tâm trạng của mình ít nhất mỗi ngày. Đủ những ngày xám xịt - hãy trở thành một siêu anh hùng ngay bây giờ!',
    'igry_descr' => 'Trò chơi điện tử từ lâu đã trở thành một phần không thể thiếu trong cuộc sống của chúng ta. Với sự trợ giúp của chúng, bạn có thể đắm mình trong một thế giới mới, tham gia vào những cuộc phiêu lưu và trở thành một người hoàn toàn khác. Mọi người đều có món đồ chơi yêu thích của riêng mình, mà các nhân vật của nó đã trở thành gần như gia đình. Một bộ con trỏ dựa trên các trò chơi điện tử nổi tiếng là một cơ hội để pha loãng cuộc sống hàng ngày nhàm chán và thêm một chút sáng tạo, tươi sáng và vui vẻ vào quy trình làm việc. Bộ này chứa cả hình ảnh của chính các anh hùng trong game, cũng như các nhân vật phụ, vũ khí và biểu tượng trò chơi. Hãy chọn những gì phù hợp với tâm trạng của bạn - con trỏ trò chơi sẽ thu hút không chỉ những game thủ, mà còn với tất cả những ai chỉ đơn giản là mệt mỏi với cuộc sống hàng ngày xám xịt. Chỉ cần tải xuống bộ này, thay đổi con trỏ chuột - và đi, để hoàn thành các nhiệm vụ trong trò chơi, tiêu diệt kẻ thù và đạt được mục tiêu của bạn.',
    'multfilmy_descr' => 'Bên trong mỗi người lớn vẫn còn một đứa trẻ yêu thích phim hoạt hình, và vẫn mơ ước trở thành một trong những anh hùng. Chúng tôi sẽ giúp biến ước mơ của bạn thành hiện thực - sử dụng bộ sưu tập con trỏ mới dựa trên các phim hoạt hình nổi tiếng và được yêu thích nhất. Tom và Jerry, Buzz Lightyear và Shrek, Gravity Falls và thậm chí cả Pokemon - bạn có thể trở thành bất cứ thứ gì bạn muốn mỗi ngày. Chọn con trỏ chuột theo tâm trạng của bạn. Hôm nay bạn là ai? Minion liều lĩnh và vui vẻ, dễ dàng giải quyết mọi vấn đề hay Raphael mạnh mẽ và dũng cảm, người có mục tiêu không chỉ là hoàn thành những chiến công mà còn là ăn pizza? Có lẽ bạn là thần đèn toàn năng, người nắm giữ cả một văn phòng dưới sự chỉ huy của mình? Trong bộ sưu tập có những anh hùng dành cho tất cả mọi người - từ công chúa đến rồng - chỉ cần quyết định ai phản ánh tâm trạng của bạn ngày hôm nay. Cursor Style không chỉ là một hình ảnh tươi sáng. Đây là sự phản ánh cá tính, thể hiện bản thân và đơn giản - niềm vui, sự thích thú và tích cực cho cả ngày. Làm việc có nhàm chán hay lười học quá? Đã trở nên buồn bã và không vui vẻ? Thay đổi con trỏ và thế giới sẽ lấp lánh với những màu sắc mới.',
    'kino_i_serialy_descr' => 'Phim - là phép thuật, sự huyền bí và chỉ là một cách tuyệt vời để thư giãn, vui vẻ và có được những cảm xúc sống động. Đồng thời, sau khi xem, chúng ta vẫn nhớ những anh hùng yêu thích mà tôi thực sự muốn gặp trong đời thực. Giờ đây, điều đó là có thể - chỉ cần tải xuống bộ sưu tập con trỏ mới dựa trên các bộ phim và chương trình truyền hình nổi tiếng. Các con trỏ sáng và thú vị sẽ là một sự bổ sung tuyệt vời cho máy tính để bàn, biến cuộc sống thường ngày xám xịt nhàm chán thành một ngày lễ và các công việc tầm thường - thành một cuộc phiêu lưu thú vị. Thay đổi anh hùng con trỏ mỗi ngày - theo tâm trạng, nhiệm vụ hoặc ngẫu nhiên. Hôm nay bạn sẽ là ai? John Snow trung thực và công bằng hay John Wick táo bạo, không ngừng nghỉ? Có lẽ bạn có một nhiệm vụ khó khăn ở phía trước và chỉ Frodo mới có thể hoàn thành nó? Có lẽ hôm nay bạn chỉ là một người ngoài hành tinh không muốn liên lạc với người khác? Chọn một con trỏ phù hợp - nâng cao tinh thần của bạn và đồng thời cho người khác thấy bạn nghĩ gì và bạn dự định dành ngày của mình như thế nào. Hãy thử nó - nó không chỉ vui mà còn gây nghiện - bạn chắc chắn sẽ không muốn quay lại mũi tên thông thường.',
    'anime_descr' => 'Anime là một phong cách hoạt hình độc đáo, mặc dù mang đậm bản sắc dân tộc, nhưng đã được hàng triệu người trên thế giới yêu thích. Khó có thể có ít nhất một người chưa từng xem phim hoạt hình theo phong cách này. Chúng tôi đã tạo ra những con trỏ kiểu anime tuyệt vời nhất mà tất cả những người hâm mộ phong cách này sẽ yêu thích. Các con trỏ tiêu chuẩn thật nhàm chán và sến súa. Hãy thể hiện cá tính của bạn - sử dụng bộ sưu tập con trỏ Anime với các nhân vật yêu thích của bạn. Chọn con trỏ một thanh kiếm bóng tối nếu bạn mơ ước về những cuộc phiêu lưu và những trận chiến dũng cảm. Chú Totoro béo dễ thương sẽ cổ vũ bạn ngay cả vào những ngày buồn nhất, và Naruto sẽ thúc đẩy bạn trong những cuộc phiêu lưu và cho mọi người xung quanh thấy rằng bạn là một người cực ngầu. Những con trỏ sáng sẽ làm bừng sáng ngày làm việc hoặc làm cho quá trình học tập trở nên thú vị và thú vị hơn. Đừng tự giới hạn mình - hãy sử dụng các họa tiết yêu thích của bạn ngay cả trong những yếu tố nhỏ như con trỏ chuột. Thay đổi con trỏ mỗi ngày, điều chỉnh chúng theo tâm trạng của bạn và thể hiện cá tính của bạn - với con trỏ kiểu anime, điều đó thật đơn giản.',
    'futbol_descr' => 'Bóng đá là một môn thể thao đặc biệt bao gồm các yếu tố của đấu vật, điền kinh, độ chính xác. Nhìn chung, nó rất ngoạn mục, tàn nhẫn và thu hút hàng triệu người hâm mộ trên toàn thế giới. Bạn có thích bóng đá hay chỉ yêu thích thể thao? Sau đó, hãy tải xuống một bộ con trỏ theo phong cách của trò chơi nổi tiếng thế giới và chứng minh danh hiệu một người hâm mộ trung thành. Bộ sưu tập chứa 24 tùy chọn để thiết kế con trỏ - dưới dạng các đội phổ biến nhất xứng đáng với danh hiệu của họ như một trò chơi liều lĩnh và bền bỉ. Con trỏ được thực hiện trong hai phiên bản - dưới dạng một hình tam giác tiêu chuẩn, được trang trí bằng màu sắc của đội, hoặc dưới dạng một chiếc mũ bảo hiểm trò chơi tương ứng. Con trỏ trình duyệt tiêu chuẩn thật nhàm chán và không xứng đáng với một người hâm mộ thể thao thực thụ. Hãy trở nên độc đáo và khác biệt với bộ sưu tập của chúng tôi. Tải xuống hình ảnh và chọn màu sắc của đội yêu thích của bạn hoặc con trỏ tùy chỉnh, nếu bạn chỉ yêu thích thể thao và cổ vũ cho mọi người. Theo đuổi sở thích của bạn thật đơn giản - bạn không cần phải đến làm việc với một chiếc khăn quàng cổ hoặc mũ của đội yêu thích của mình, thật nhanh chóng và dễ dàng để thay đổi con trỏ thành một hình ảnh sáng sủa, phong cách.',
    'avtomobili_descr' => 'Bạn có thích ô tô và thích nhìn vào các mẫu xe từ các nhà sản xuất khác nhau không? Hoặc bạn đã mơ ước về một thương hiệu cụ thể trong một thời gian dài, nhưng vẫn chưa có cơ hội mua nó? Đặc biệt dành cho bạn, chúng tôi đã tạo ra một bộ con trỏ sáng sủa "Siêu xe". Tại đây, bạn sẽ tìm thấy Ford cổ điển và Bentley sành điệu, Lamborghini sáng và Ferrari độc đáo. Bạn có muốn trở thành chủ sở hữu của chiếc xe nguyên bản không? Nó rất đơn giản - hãy tải xuống bộ sưu tập con trỏ của chúng tôi vào thiết bị của bạn và thay đổi hình ảnh của chiếc xe ít nhất mỗi ngày. Con trỏ được thiết kế theo hai phiên bản - dưới dạng một chiếc xe hoàn chỉnh hoặc dưới dạng dấu hiệu của nó. Chọn những gì bạn thích nhất hoặc cách bạn thích làm việc. Những hình ảnh như vậy sẽ trông tuyệt vời như con trỏ trò chơi hoặc đơn giản là một yếu tố khác thường của màn hình nền. Để trở nên nổi bật thật đơn giản - không cần phải làm những điều không tưởng vì điều này hoặc thay đổi ngoại hình của bạn. Chỉ cần ngừng sử dụng các đối tượng tầm thường và chọn những gì bạn thực sự thích. Bộ sưu tập con trỏ "Xe hơi" là sự lựa chọn cho những người không ngại thể hiện bản thân.',
    'memy_descr' => 'Meme đã là một phần quen thuộc trong cuộc sống của chúng ta từ lâu. Và ai trong số chúng ta không thích những hình ảnh dung lượng lớn, thú vị và độc đáo này để chọc tức ngày hôm đó? Nhiều anh hùng meme đã không chỉ trở nên phổ biến - họ đã có được vị thế là những mục yêu thích phổ biến, và các cụm từ và biểu hiện đã từ lâu được đưa vào lời nói thông tục cũng như những thay đổi đã được thiết lập. Chúng tôi xin giới thiệu một bộ sưu tập các con trỏ tốt nhất dựa trên các meme phổ biến nhất. Với sự trợ giúp của chúng, bạn không chỉ có thể thể hiện cá tính của mình mà còn thể hiện tâm trạng của bạn. Bạn có cảm thấy mệt mỏi và chán ngán mọi thứ không? Chọn một con mèo giận dữ, với tất cả vẻ bề ngoài của nó, thể hiện sự phẫn nộ và thù địch với mọi thứ xung quanh anh ta. Hay bạn tỏa sáng với sự mỉa mai ngày hôm nay và không ngại cười? Sau đó, Drake Bling sẽ là một sự đồng hành tuyệt vời - nó sẽ cổ vũ bạn và làm cho bất kỳ nhiệm vụ nào trở nên độc đáo và thú vị. Cài đặt tiện ích mở rộng, tải xuống bộ sưu tập của chúng tôi - và chọn kiểu con trỏ cho mỗi ngày. Không khó để trở nên nổi bật và độc đáo - hãy thay đổi thiết kế tiêu chuẩn của biểu tượng thành một trong những anh hùng của meme và nhận được một nguồn năng lượng cho cả ngày.',
    'emodji_descr' => 'Biểu tượng cảm xúc - những biểu tượng tươi sáng, thú vị, nếu thiếu chúng thì chúng ta không thể giao tiếp theo thói quen được nữa. Với sự trợ giúp của chúng, bạn không cần phải mô tả tâm trạng của mình bằng lời nói - chỉ cần chọn biểu tượng mong muốn và người đối thoại hiểu bạn ngay. Trong bộ con trỏ mới của chúng tôi, chúng tôi đã thể hiện ý tưởng về biểu tượng cảm xúc - đó là cách Cursoji vui nhộn và khác thường đã xuất hiện, nó sẽ tô điểm cho thế giới và làm cho cuộc sống trở nên thú vị hơn. Với sự trợ giúp của các khóa học, bạn không chỉ có thể làm việc và thực hiện các nhiệm vụ quen thuộc, mà còn có thể thể hiện tâm trạng của mình với đồng nghiệp, bạn bè và những người khác. Một con trỏ buồn ngủ là hoàn hảo cho sáng thứ Hai, và một con trỏ khóc sẽ thể hiện thái độ về các trách nhiệm bổ sung. Một con trỏ ngầu với kính là lựa chọn tốt nhất trước kỳ nghỉ, và một con trỏ với đô la trong mắt là một lý do chính đáng để gợi ý với người đứng đầu về việc tăng lương. Sử dụng Cursoji rất vui và thú vị - dù là công việc, học tập hay thuyết trình. Trong trường hợp sau, thậm chí còn được khuyến khích làm điều này nếu đồng nghiệp có khiếu hài hước hoặc chỉ cần xoa dịu tình hình. Nói chung, đối với bất kỳ nhiệm vụ nào - chỉ cần chọn khóa học phù hợp!',
    'pitomcy_descr' => 'Bạn có thích động vật không? Chắc chắn rồi - chúng rất dễ thương, vui nhộn và rất hài hước. Tại sao không dành cả ngày đồng hành cùng những người bạn tốt nhất của con người? Tải xuống bộ sưu tập Cursors về Thú cưng cho riêng bạn và chọn một người bạn cho bạn mỗi ngày. Biểu tượng con trỏ có thể dễ thương, như một con lạc đà không bướu tốt bụng, hoặc sành điệu, như một con hồng hạc màu hồng. Hoặc có thể bạn sẽ bận rộn cả ngày và chọn một con kỳ lân đang đọc báo, hoặc đơn giản là không muốn giao tiếp với ai, như một con mèo đen độc ác? Đối với bất kỳ tâm trạng nào, chúng tôi đều có một con vật tương ứng. Một con chó pug vui vẻ sẽ cổ vũ bạn ngay cả trong những ngày tồi tệ và xám xịt nhất, và con trỏ màu hồng có hình dạng của một con kỳ lân sẽ cho mọi người thấy rằng bạn không thiếu cảm giác về vẻ đẹp, ngay cả khi là một người đàn ông râu ria thô lỗ. Điều gì sẽ xảy ra nếu không có tâm trạng và tôi không muốn làm những công việc thường ngày? Công thức rất đơn giản - hãy tải xuống bộ sưu tập Thú cưng, thay đổi con trỏ chuột - và thì đấy, mặt trời lại chiếu sáng, thời tiết đẹp và tâm trạng ở mức cao nhất. Không có gì ngạc nhiên khi người ta nói rằng động vật giúp chống lại bệnh trầm cảm và nỗi buồn!',
    'stil_i_krasota_descr' => 'Trong bộ sưu tập con trỏ mới, chúng tôi đã thu thập nhiều chủ đề khác nhau mang đến cho chúng ta những cảm xúc dễ chịu và sự phấn chấn. Bộ con trỏ này được gọi là “Phong cách và Vẻ đẹp”, bởi vì đó là những thứ yêu thích của bạn quyết định cuộc sống hàng ngày của chúng ta, mang lại niềm vui và thúc đẩy chúng ta làm những điều quan trọng, khơi dậy mong muốn được cải thiện. Bạn có thích không gian và mơ ước được đến các hành tinh khác? Chọn con trỏ NASA hoặc đĩa người ngoài hành tinh - đến gần hơn với ước mơ của bạn. Nếu bạn không thể hình dung cuộc sống mà không có âm nhạc hoặc là một rocker cố cựu, thì con trỏ theo phong cách đàn guitar điện là dành cho bạn. Con trỏ bút vẽ, thước kẻ và compa đã được phát triển đặc biệt cho các kỹ sư - những hình ảnh như vậy sẽ giúp biến các phép tính và bản vẽ nhàm chán thành các giải pháp độc đáo. Một cây đũa phép và giày thể thao, một ván trượt và son môi, mặt trời và hình nón hóa học - hãy chọn những gì phù hợp với lối sống, mong muốn và khát vọng của bạn - và các nhiệm vụ thông thường sẽ trở nên thú vị hơn, và những ngày làm việc sẽ được tô điểm bằng những màu sắc tươi sáng mới.',
    'prazdniki_descr' => 'Thích ngày lễ? Nhưng ai mà không thích chúng - bạn bè, quà tặng, lại là cuối tuần. Để làm cho việc chờ đợi những ngày lễ trở nên dễ chịu hơn, ngắn hơn và ấm áp hơn, bạn không chỉ có thể đếm ngày trên lịch mà còn đặt biểu tượng tương ứng làm con trỏ chuột. Hãy bắt đầu với Năm mới - chúng ta sẽ chọn một cây thông Noel, một món quà hoặc Ông già Noel, để kỳ nghỉ trở nên tươi sáng và vui vẻ. Có lẽ người bánh gừng sẽ gần gũi hơn - vui nhộn, dễ thương và luôn vui vẻ? Với anh ấy chắc chắn sẽ không có thời gian để buồn và chán. Chúng ta tiếp tục ăn mừng với những thần tình yêu và những trái tim vui vẻ, và không xa thỏ Phục Sinh. Ở đâu đó trong số các ngày lễ, sẽ có một ngày sinh nhật, điều này sẽ càng dễ chịu hơn khi chờ đợi với những quả bóng bay thay vì mũi tên con trỏ tiêu chuẩn. Và trong Halloween, bạn có thể làm ngạc nhiên đồng nghiệp và những người xung quanh bằng một con trỏ chuột khác thường dưới dạng một quả bí ngô đáng ngại hoặc một con ma. Bộ con trỏ cho các ngày lễ là một cơ hội để làm sáng lên sự mong đợi, điều chỉnh trước cho niềm vui sắp tới và duy trì một tâm trạng tuyệt vời không chỉ vào đêm trước lễ kỷ niệm mà còn trong suốt cả năm.',
    'flagi_descr' => 'Lá cờ là một biểu tượng độc đáo được sử dụng rộng rãi trong tất cả các mạng xã hội. Chúng tôi nghĩ, tại sao không biến con trỏ thành một lá cờ? Rốt cuộc, nó thực sự tươi sáng và khác thường. Giờ đây, bạn có thể dành mỗi ngày trong một công ty với một quốc gia mới và công việc sẽ không còn đơn điệu và nhàm chán. Con trỏ chuột giờ đây có thể được tạo thành quốc kỳ của Trung Quốc hoặc Hoa Kỳ, Nhật Bản hoặc Canada và trong 38 tùy chọn cờ khác và bạn có thể chọn hình dạng mũi tên tiêu chuẩn với một màu sắc khác thường hoặc con trỏ có hình dạng của chính lá cờ. Bộ này sẽ thu hút tất cả những người yêu thích du lịch. Với nó, bạn có thể lên kế hoạch cho những chuyến đi mới và mơ ước những chuyến đi dài ngày. Bạn đã lên kế hoạch cho một kỳ nghỉ? Hãy cho mọi người thấy bạn muốn đến quốc gia nào. Có lẽ bạn đã quyết định học một ngôn ngữ nước ngoài mới? Sau đó, con trỏ này chắc chắn sẽ hỗ trợ bạn và thúc đẩy bạn học tập cẩn thận. Hoặc bạn, giống như Sheldon, chỉ yêu thích cờ? Trong mọi trường hợp, bộ sưu tập con trỏ Flags sẽ là một sự bổ sung tuyệt vời cho máy tính để bàn của bạn và sẽ đưa bạn đến những khám phá mới.',
    'vokrug_sveta_descr' => 'Ai cũng thích đi du lịch. Thật tuyệt vời khi đến thăm những quốc gia và thành phố mới, xem các điểm tham quan và có một khoảng thời gian tuyệt vời trong một nền văn hóa mới. Thật đáng tiếc là chúng ta không thể đi du lịch thường xuyên, nhưng chúng tôi đã cố gắng khắc phục điều đó. Bộ con trỏ “Vòng quanh thế giới” là một bộ sưu tập các hình ảnh, biểu tượng nổi bật nhất của các quốc gia khác nhau, với sự trợ giúp của nó, ngay cả khi ngồi ở nhà, bạn vẫn có thể cảm thấy như một nhà du lịch thực thụ. Trong bộ công cụ của chúng tôi, bạn có thể tìm thấy Nhật Bản và Úc, Ý và Canada, Hoa Kỳ và Mexico - những quốc gia thú vị, độc đáo và đẹp như tranh vẽ nhất trên thế giới. Hình ảnh con trỏ có thể trở thành một mũi tên tiêu chuẩn, với màu sắc của quốc kỳ của đất nước, hoặc trở thành một trong những điểm thu hút chính của bang. Ví dụ, bạn có thể mở tài liệu bằng Tháp nghiêng Pisa, và thực hiện các bài thuyết trình bằng Tượng Nữ thần Tự do. Chúng tôi đảm bảo - thành công sẽ được đảm bảo. Vâng, hoặc nếu không thành công, thì nụ cười của đồng nghiệp và sự công nhận về sự độc đáo - chắc chắn. Vâng, và gợi ý với ban quản lý rằng đã đến lúc đi nghỉ cũng sẽ rất đáng giá - chỉ cần đặt vali hoặc máy bay làm con trỏ - và rất có thể bạn sẽ sớm được bay thôi.',
    'eda_i_napitki_descr' => 'Một bộ con trỏ ở dạng sản phẩm là một bộ sưu tập đáng kinh ngạc gồm những hình ảnh tươi sáng, ngon miệng và hấp dẫn mà mọi người chắc chắn sẽ thích và sẽ là một sự bổ sung tuyệt vời cho trình duyệt. Bạn đã bao giờ nhấp vào bông cải xanh hoặc khoai tây chiên chưa? Bạn có cơ hội như vậy - chỉ cần tải xuống một bộ con trỏ mới và đặt chúng thay vì một mũi tên trắng nhàm chán. Con trỏ "Đồ ăn" được tạo ra cả ở dạng con trỏ hình tam giác tiêu chuẩn và ở dạng sản phẩm. Tại đây, bạn sẽ tìm thấy các loại rau và trái cây, các món ăn yêu thích của bạn, chẳng hạn như pizza hoặc xúc xích, cà phê, kẹo mút và nhiều thứ khác, giúp bạn vui vẻ cả ngày. Yêu cà phê, nhưng uống nó cả ngày không tốt lắm phải không? Bổ sung chế độ ăn uống của bạn với cà phê ảo, nó cũng sẽ tiếp thêm sinh lực và đánh thức bạn, cũng như mang lại những cảm xúc sống động. Một con trỏ dốc ở dạng bánh rán ảo sẽ không gây hại cho vóc dáng, trong khi mang lại những cảm xúc sống động và vui vẻ. Bạn có thể sử dụng các con trỏ yêu thích của mình hoặc thay đổi hình ảnh mỗi ngày - nhiều lựa chọn con trỏ sẽ giúp tô màu cho cuộc sống hàng ngày và thêm màu sắc mới cho các hành động quen thuộc.',
    'cvetnye_descr' => 'Con trỏ là yếu tố chính của trình duyệt, với nó chúng ta dành cả ngày làm việc, học tập, giao tiếp và thư giãn. Giao diện tiêu chuẩn của con trỏ thật nhàm chán và thậm chí có phần gây chán nản, nhưng đối với nhiều người, hình thức này lại tiện lợi và việc thay đổi nó sẽ gây khó chịu. Nhưng đối với tình huống này, chúng tôi có một giải pháp - một bộ con trỏ với màu sắc tươi sáng, vui vẻ sẽ thêm sự đa dạng vào cuộc sống hàng ngày của bạn và giúp giải quyết mọi vấn đề dễ dàng và nhanh hơn. Nếu bạn đang nghĩ về cách thay đổi màu của con trỏ, chúng tôi trả lời - hãy tải xuống bộ sưu tập của chúng tôi và chọn các giải pháp tươi sáng cho mọi ngày! Bạn có thể chọn tông màu đơn sắc với các màu khác nhau để phù hợp với tâm trạng hoặc tính chất công việc. Ví dụ, khi làm việc với các tài liệu chuẩn, con trỏ màu tím sẽ nổi bật trên nền, và trên nền tối, ngược lại, sẽ dễ dàng làm việc hơn với các con trỏ màu vàng. Nếu bạn muốn bùng nổ màu sắc, độ sáng và tính độc đáo tối đa - hãy chọn một con trỏ cầu vồng bao gồm tất cả các màu của dải quang phổ - với biểu tượng này, tâm trạng chắc chắn sẽ tốt trong suốt cả ngày.',
    'prank_descr' => 'Những trò đùa tại nơi làm việc không phải lúc nào cũng được chào đón, vì chúng thường cản trở luồng công việc. Nhưng với bộ con trỏ “Trò đùa” mới, bạn có thể chơi khăm đồng nghiệp hoặc bạn bè một cách tử tế mà không làm ảnh hưởng đến công việc hoặc việc học của mình. Chúng tôi đã phát triển một bộ sưu tập đặc biệt sẽ khiến bất kỳ ai thích thú và làm cho họ có lý do để thư giãn một chút giữa quá trình làm việc bận rộn hoặc thực hiện một nhiệm vụ khác. Để thay đổi con trỏ chuột, chỉ cần tải xuống bộ công cụ vào thiết bị và chọn thiết kế bạn thích trong các thông số. Ví dụ, bạn có thể có được con trỏ có hình dạng tiêu chuẩn, nhưng ở trạng thái đảo ngược hoặc mũi tên cong bằng một gợn sóng. Hình thức này hoàn toàn không cản trở quá trình làm việc, mà đồng thời nó sẽ thể hiện tâm trạng tuyệt vời và đặt bạn trong một tâm trạng tích cực. Thay đổi cài đặt hiển thị của con trỏ theo tâm trạng của bạn hoặc mỗi ngày - và bất kỳ nhiệm vụ nào sẽ trở nên thú vị và thú vị hơn, và cuộc sống hàng ngày sẽ không còn gây ra những cảm xúc tiêu cực. Hơn nữa, những con trỏ như vậy có thể được sử dụng ngay cả cho các dự án nghiêm túc - chúng có màu sắc trung tính và không nổi bật so với màn hình nền.',
    'startovyj_nabor_descr' => 'Con trỏ từ bộ sưu tập khởi đầu là sự kết hợp của các hình dạng và kích cỡ tiêu chuẩn với vẻ ngoài tươi sáng, khác thường. Đây là một lựa chọn tuyệt vời cho những ai thích các hình thức thông thường, nhưng muốn mang lại sự đa dạng, độc đáo và tươi sáng cho cuộc sống hàng ngày. Bộ sưu tập có một con trỏ hình bàn tay và một mũi tên quen thuộc trong nhiều biến thể - từ logo Google Chrome đến biểu tượng cảm xúc, bạn thậm chí có thể gặp ở đây một con rồng với xương rồng và nỗi nhớ đã bị lãng quên từ lâu. Chúng tôi chứng minh rằng một con trỏ tiêu chuẩn cũng có thể thú vị và hấp dẫn. Màu sắc, hình dạng, kết cấu và thiết kế thú vị khác nhau sẽ giúp bạn chọn con trỏ theo sở thích của mình hoặc thay đổi nó mỗi ngày tùy thuộc vào tâm trạng hoặc các tác vụ được thực hiện. Thay đổi con trỏ trình duyệt rất đơn giản - chỉ cần cài đặt tiện ích mở rộng và tải xuống bộ sưu tập vào thiết bị của bạn. Con trỏ vui nhộn, thú vị không chỉ tô điểm cho những ngày làm việc mà còn, ví dụ, giúp làm cho bất kỳ bài thuyết trình nào trở nên thú vị hơn và với sự trợ giúp của các con trỏ đặc biệt tươi sáng, cũng thu hút sự chú ý đến các yếu tố riêng lẻ của báo cáo.',
    'fortnite_descr' => 'Fortnite đã chinh phục hàng triệu người trên khắp thế giới. Những trận chiến thú vị, chiến lược và chiến thuật, những cuộc phiêu lưu - nó đã hấp thụ hoàn toàn mọi thứ mà người chơi thích rất nhiều. Chúng tôi không thể đứng ngoài và đã phát triển một bộ con trỏ theo phong cách của trò chơi sẽ thu hút không chỉ những game thủ cuồng nhiệt mà còn cả những người lần đầu tiên nghe về Fortnite. Biểu tượng con trỏ Fortnite là hình ảnh của một anh hùng hoặc vũ khí của anh ta, được gia công đến từng chi tiết nhỏ nhất. Tại đây, bạn có thể tìm thấy hình ảnh của cáo và cá, mặt nạ của hỏa ngục và hiệp sĩ đen, tự đặt cho mình một mũi tên hoặc một lưỡi hái có gai làm mũi tên. Chúng tôi chắc chắn rằng sẽ không ai thờ ơ! Để trở nên đáng sợ hoặc bí ẩn, độc đáo hoặc hài hước - tùy thuộc vào bạn. Chọn phong cách của bạn và làm theo nó hoặc đặt các con trỏ tùy chỉnh trong cài đặt và thay đổi vai trò của bạn mỗi ngày. Giờ đây, việc thực hiện ngay cả những công việc tẻ nhạt và đơn điệu sẽ trở nên thú vị và dễ chịu hơn nhiều - thời gian sẽ trôi qua nhanh chóng trong công ty với những hình ảnh sống động và những nhân vật yêu thích. Hoặc có lẽ bạn sẽ tổ chức các cuộc thi với đồng nghiệp, anh hùng nào sẽ mạnh hơn? Sự lựa chọn là của bạn!',
    'dota_2_descr' => 'DotA2 giờ đây không chỉ là một trò chơi đơn giản, nó là một thế giới song song thực sự. Trong thực tế ảo trong DotA2, bạn có thể làm mọi thứ - sống, chiến đấu, phát triển, du lịch, kết bạn. Nhìn chung, mọi thứ đều như trong cuộc sống, chỉ có điều đôi khi thú vị hơn. Con trỏ Dota 2 là sự tiếp nối của một chiến lược sẽ cho phép bạn có được những cảm xúc sống động và thể hiện bản thân trong thế giới thực. Một bộ con trỏ mới bao gồm các nhân vật nổi bật nhất trong trò chơi, cũng như các vật phẩm độc đáo không thể nhầm lẫn với bất cứ thứ gì khác. Chọn một con trỏ gần gũi với bạn hơn - và bắt tay vào một cuộc phiêu lưu mà không cần rời khỏi nơi làm việc của bạn. Đôi khi thật nhàm chán khi ở nơi làm việc hoặc thực hiện các nhiệm vụ giáo dục, nhưng với các con trỏ trò chơi, vấn đề này sẽ không còn đe dọa bạn nữa. Một chút tưởng tượng, một con trỏ sáng - và thì đấy, bất kỳ công việc kinh doanh nào cũng sẽ là một cuộc phiêu lưu bất thường, đối phó với nó sẽ không khó khăn và thú vị. Không cần phải kìm nén bản thân. Bạn có thích Dota không? Sau đó, hãy chắc chắn tải xuống bộ sưu tập của chúng tôi, chọn một hoặc một vài con trỏ ngẫu nhiên cùng một lúc - và mỗi ngày mới sẽ trở nên tươi sáng hơn, thú vị hơn và bão hòa hơn.',
    'minecraft_descr' => 'Con trỏ chuột ở dạng mũi tên và ngón tay tiêu chuẩn từ lâu đã trở nên nhàm chán đối với mọi người. Nếu bạn là người hâm mộ của sự khác thường và độc đáo, thì đã đến lúc thay đổi con trỏ chuột và mang đến cho nó một thiết kế thú vị hơn. Chúng tôi đã phát triển một bộ sưu tập con trỏ theo phong cách của trò chơi Minecraft nổi tiếng thế giới, nơi bạn có thể tìm thấy những nhân vật nổi bật nhất. Sói và cáo, Alex và Creeper, kiếm kim cương và cá - bạn có thể chọn một trong những nhân vật mà bạn thích nhất hoặc cài đặt một anh hùng mới mỗi ngày. Đây là những con trỏ thực sự dành cho game thủ và tuyệt đối mọi người sẽ thích chúng - sau tất cả, ai trong chúng ta chưa từng chơi Minecraft chứ? Chúng tôi chắc chắn rằng những điều này đơn giản là không tồn tại. Đập tan cuộc sống hàng ngày nhàm chán - đã đến lúc lao mình vào những cuộc phiêu lưu, điều này có thể được thực hiện ngay cả khi không rời khỏi nhà hoặc ghế văn phòng của bạn. Sẽ thú vị hơn khi chuẩn bị một báo cáo và giảm số dư bằng súng - bất kỳ nhiệm vụ nào cũng sẽ trở nên dễ chịu hơn và sẽ không cho phép bạn cảm thấy nhàm chán tại chỗ. Tải xuống bộ sưu tập con trỏ Minecraft mới - cài đặt chúng và ngay cả vào ngày xám xịt và nhàm chán nhất, tâm trạng của bạn sẽ luôn ở mức tốt nhất. Và các đồng nghiệp sẽ ghen tị với kết quả của bạn - đơn giản là không thể không hoàn thành công việc của bạn với sự giúp đỡ của những anh hùng dũng cảm của Minecraft.',
    'sports-cars_short_descr' => 'Những chiếc xe hơi mạnh mẽ và phong cách được chế tạo để có tốc độ và sự nhanh nhẹn.',
    'spider-man' => 'Spider-Man',
    'astrology-signs-zodiac' => 'Các cung hoàng đạo',
    'astrology-signs-zodiac_short_descr' => 'Một bộ 12 biểu tượng chiêm tinh đại diện cho các đặc điểm tính cách, năng lượng vũ trụ và mô hình cuộc sống.',
    'sports-cars' => 'Sports Cars',
    'sports-cars_descr' => 'Xe thể thao là những phương tiện hiệu suất cao được thiết kế để tăng tốc nhanh, xử lý sắc bén và trải nghiệm lái xe thú vị. Từ những chiếc coupe bóng bẩy đến những chiếc roadster nhanh nhẹn, danh mục này có một số cỗ máy mang tính biểu tượng nhất được chế tạo cho cảm giác hồi hộp trên đường hoặc đường đua. Lý tưởng cho những người đam mê tốc độ, thiết kế và sức mạnh. 🏎️🔥',
    'spider-man_short_descr' => 'Anh hùng từ vũ trụ Spider-Man',
    'starwars' => 'Star Wars',
    'spider-man_descr' => 'Một bộ sưu tập các nhân vật và anh hùng từ vũ trụ Spider-Man. Bao gồm các phiên bản khác nhau của Spider-Man, đồng minh và các phong cách độc đáo từ khắp truyện tranh, trò chơi và sê-ri hoạt hình. Mỗi thiết kế phản ánh sự nhanh nhẹn, lòng dũng cảm và bản sắc trực quan xác định thế giới Spider-Man.',
    'astrology-signs-zodiac_descr' => 'Các cung Hoàng Đạo ♈♉♊♋♌♍♎♏♐♑♒♓ là mười hai phân chia biểu tượng của vòng đai thiên thể được sử dụng trong chiêm tinh học. Mỗi cung được liên kết với ngày cụ thể, các yếu tố (🌍 Đất, 🔥 Lửa, 🌊 Nước, 💨 Khí), hành tinh cai trị và các đặc điểm tính cách độc đáo. Các nhà chiêm tinh sử dụng các cung hoàng đạo để giải thích hành vi, dự đoán khả năng tương thích và khám phá con đường sống. Cho dù bạn là một Sư Tử 🔥 đam mê hay một Song Ngư 🌊 ​​​​sâu sắc, cung của bạn đều cung cấp cái nhìn sâu sắc về thế giới nội tâm của bạn. Danh mục này bao gồm tất cả 12 cung, ý nghĩa của chúng và các biểu diễn trực quan.',
    'starwars_descr' => 'Hòa mình vào thiên hà xa xôi với bộ sưu tập này, có các anh hùng huyền thoại, lãnh chúa Sith hùng mạnh, người máy, phiến quân và hơn thế nữa. Từ Hiệp sĩ Jedi đến stormtrooper, mỗi biểu tượng đều mang tinh thần của Star Wars vào cuộc sống dưới dạng con trỏ. Hoàn hảo cho người hâm mộ của mọi bộ ba phần.  🌌',
    'starwars_short_descr' => 'Các nhân vật và biểu tượng từ vũ trụ Star Wars',
    'glitter' => 'Lấp lánh',
    'glitter_short_descr' => 'Các con trỏ lấp lánh và lóng lánh theo phong cách ✨🌟',
    'roblox-2025' => 'Roblox 2025',
    'roblox-2025_short_descr' => 'Các nhân vật từ làn sóng Roblox mới nhất 🕹️🚀',
    'glitter_descr' => 'Một bộ sưu tập con trỏ đầy quyến rũ lấy cảm hứng từ các kết cấu lấp lánh và hình ảnh rực rỡ. Hoàn hảo cho những ai yêu thích vẻ đẹp thẩm mỹ lấp lánh trên màn hình của họ. Những con trỏ này mang đến sự lóng lánh, thanh lịch và một chút phép thuật cho mọi cú nhấp chuột.',
    'roblox-2025_descr' => 'Một bộ sưu tập 2025 hoàn toàn mới với các nhân vật Roblox mang tính biểu tượng và hiện đại. Bao gồm những người mới bắt đầu cổ điển, huyền thoại kinh dị và các hình đại diện được người hâm mộ yêu thích từ các trò chơi phổ biến. Được thiết kế theo phong cách vui nhộn và đầy màu sắc, hoàn hảo cho trẻ em và người hâm mộ Roblox ở mọi lứa tuổi.',
];
