<?php

return [
    'title' => 'Cursor Style - Chính sách Cookie',
    'descr' => 'Chính sách cookie khi bạn truy cập trang web cursor.style hoặc tiện ích mở rộng “Cursor Style”. Một số quy tắc bạn nên xem xét khi sử dụng sản phẩm của chúng tôi.',
    'text' => '<h2> Chính Sách Cookie </h2>
<p> Khi bạn truy cập trang web cursor.style của chúng tôi hoặc tiện ích mở rộng "Cursor Style" trong bảng điều khiển trình duyệt của bạn, hoặc khi bạn tương tác với đại diện của chúng tôi ("Dịch vụ"), chúng tôi sẽ sử dụng (và cho phép bên thứ ba sử dụng) đèn hiệu web, cookie, thẻ pixel, tập lệnh, thẻ, API và các công nghệ khác ("Công nghệ theo dõi"). Điều này được giải thích trong chính sách này ("Chính sách Cookie"), một phần trong <a href="/privacy"> Chính sách Bảo mật </a> của chúng tôi. </p>
<p> Công nghệ theo dõi cho phép chúng tôi tự động thu thập thông tin về bạn và hành vi của bạn trên Internet để cải thiện điều hướng của bạn trên Dịch vụ của chúng tôi, cải thiện hiệu suất của Dịch vụ của chúng tôi và tạo điều kiện thuận lợi cho trải nghiệm của bạn trong Dịch vụ của chúng tôi. Chúng tôi cũng sử dụng thông tin này để thu thập số liệu thống kê về việc sử dụng Dịch vụ của chúng tôi, tiến hành phân tích, cung cấp nội dung phù hợp với sở thích của bạn và quản lý các dịch vụ cho Người dùng, khách hàng và đối tác của chúng tôi. Chúng tôi cũng cho phép bên thứ ba thu thập thông tin về bạn bằng cách sử dụng công nghệ theo dõi. </p>
<p> Cookie là gì? Cookie là các tệp văn bản nhỏ (chỉ bao gồm các chữ cái và số) mà máy chủ web đặt trên máy tính hoặc thiết bị di động của bạn khi bạn truy cập một trang web. Việc sử dụng cookie có thể giúp các Dịch vụ của chúng tôi thân thiện hơn với người dùng, ví dụ, ghi nhớ tùy chọn và cài đặt ngôn ngữ của bạn. Bạn có thể tìm thêm thông tin về cookie tại <a href="http://www.allaboutcookies.org"> allaboutcookies.org </a>. </p>
<p> Cookie được sử dụng rộng rãi để có hiệu suất trang web. Việc sử dụng cookie cho phép bạn điều hướng hiệu quả giữa các trang. Cookie ghi nhớ các tùy chọn của bạn và làm cho sự tương tác giữa bạn và Dịch vụ mượt mà và hiệu quả hơn. </p>
<p> Chúng tôi sử dụng công nghệ theo dõi khi bạn truy cập hoặc truy cập Dịch vụ của chúng tôi (thường là khi bạn truy cập các trang web của chúng tôi) - chúng được gọi là “Công nghệ theo dõi của Bên thứ nhất”. Ngoài ra, công nghệ theo dõi được lưu trữ bởi các tổ chức bên thứ ba khác (ví dụ: nhà cung cấp dịch vụ phân tích, đối tác kinh doanh và nhà quảng cáo của chúng tôi) đăng nội dung trên Dịch vụ của chúng tôi - chúng được gọi là “Công nghệ theo dõi của Bên thứ ba”. Cả hai loại công nghệ theo dõi này đều có thể được lưu trữ trong thời gian bạn truy cập Dịch vụ của chúng tôi hoặc cho các lần truy cập lặp lại. </p>
<h3> Chúng tôi sử dụng những loại công nghệ theo dõi nào? Có năm loại công nghệ theo dõi chính: </h3>
<ul>
<li> <b> Công nghệ theo dõi hoàn toàn cần thiết </b> <br> <p> Những công nghệ theo dõi này là cần thiết để bạn có thể đăng nhập, điều hướng và sử dụng các chức năng của Dịch vụ của chúng tôi hoặc cung cấp dịch vụ bạn yêu cầu (ví dụ: tên người dùng của bạn). Chúng tôi không cần sự đồng ý của bạn để sử dụng các công nghệ theo dõi này. Những công nghệ theo dõi này có thể được sử dụng cho mục đích bảo mật và tính toàn vẹn, ví dụ: để xác định các vi phạm chính sách của chúng tôi, cũng như cho các tính năng hỗ trợ hoặc bảo mật. </p> </li>
<li> <b> Công nghệ theo dõi chức năng </b> <br> <p>
Những công nghệ theo dõi này cho phép các dịch vụ của chúng tôi ghi nhớ các lựa chọn của bạn (như ngôn ngữ) và cung cấp các tính năng nâng cao và được cá nhân hóa. Ví dụ, những công nghệ theo dõi này được sử dụng để xác thực (để ghi nhớ khi bạn đăng nhập) và hỗ trợ các chức năng khác của Dịch vụ của chúng tôi. </p> </li>
<li> <b> Công nghệ theo dõi hiệu suất </b> <br> <p>
Những công nghệ theo dõi này thu thập thông tin về hoạt động trực tuyến của bạn (ví dụ: thời lượng bạn truy cập Dịch vụ của chúng tôi), bao gồm dữ liệu hành vi và các chỉ báo về mức độ tương tác nội dung. Những công nghệ theo dõi này được sử dụng để phân tích, nghiên cứu và thống kê (dựa trên thông tin tổng hợp). </p> </li>
<li> <b> Công nghệ theo dõi tiếp thị hoặc quảng cáo </b> <br> <p>
Những công nghệ theo dõi này được sử dụng để cung cấp cho bạn các ưu đãi đặc biệt và quảng cáo dựa trên sở thích của bạn, cũng như để tiến hành các chiến dịch tiếp thị qua email. Chúng cũng có thể được sử dụng để hạn chế số lần xem quảng cáo, cũng như để đo lường hiệu quả của một chiến dịch quảng cáo. Chúng thường được lưu trữ bởi các nhà quảng cáo của chúng tôi (ví dụ: mạng quảng cáo) và cho họ ý tưởng về những người xem và tương tác với quảng cáo của họ, truy cập trang web của họ hoặc sử dụng ứng dụng của họ. </p> </li>
<li> <b> Công nghệ theo dõi truyền thông xã hội </b> <br> <p>
Trang web của chúng tôi bao gồm các chức năng của mạng xã hội, chẳng hạn như các nút Thích hoặc Chia sẻ trên Facebook và Vkontakte hoặc các dịch vụ đăng nhập của bên thứ ba. Những chức năng này được đăng bởi bên thứ ba hoặc được đăng trực tiếp lên Dịch vụ của chúng tôi. Tương tác của bạn với các tính năng này được điều chỉnh bởi tuyên bố về quyền riêng tư của công ty cung cấp các tính năng này. </p> </li>
</ul>
<h3> Sau đây là các cookie bạn có thể tìm thấy trong Dịch vụ của chúng tôi: </h3>
<ul>
<li> <b> Phân tích Cookie </b> <br> <p> Các công nghệ theo dõi này được sử dụng để thu thập thông tin về cách bạn tương tác với nội dung trong Dịch vụ của chúng tôi, mục đích phân bổ (ví dụ: URL giới thiệu), v.v. Chúng tôi sử dụng thông tin này để biên dịch báo cáo, tính toán thu nhập đến hạn của chúng tôi và giúp chúng tôi cải thiện Dịch vụ và cung cấp các sản phẩm và nội dung được cá nhân hóa. </p> </li>
<li> <b> Google Analytics </b> <br> <p> Cookie này được sử dụng để thu thập thông tin về cách khách truy cập sử dụng Nền tảng của chúng tôi. Chúng tôi sử dụng thông tin này để biên dịch báo cáo và cải thiện Nền tảng. Cookie thu thập thông tin ở dạng ẩn danh, bao gồm số lượng khách truy cập Nền tảng, nơi khách truy cập đến Nền tảng và các trang họ đã truy cập. <br> <a href = "https://policies.google.com/privacy?hl=en" > Chính sách Bảo mật </a> </p> </li>
<li> <b> Trình quản lý thẻ của Google </b> <br> <p> Cookie này được liên kết với Trình quản lý thẻ của Google mà chúng tôi sử dụng để tải các tập lệnh trên các trang của trang web của chúng tôi. <br> <a href = "https: / /policies.google.com/privacy?hl=en">Chính sách Bảo mật </a> </p> </li>
</ul>
<p> Xin lưu ý rằng chúng tôi không nhận ra hay đáp ứng các cảnh báo tự động của trình duyệt liên quan công nghệ theo dõi, bao gồm các yêu cầu Không theo dõi. Tuy nhiên, có nhiều cách khác nhau để quản lý và quản lý cài đặt cookie của bạn. Hãy nhớ rằng khi xóa hoặc chặn cookie, một số chức năng của Dịch vụ có thể không hoạt động chính xác hoặc không hiệu quả. </p>
<p> Hầu hết các trình duyệt web cung cấp cho bạn một số thông tin chung về cookie, cho phép bạn xem cookie nào được lưu trữ trên thiết bị của bạn, cho phép bạn xóa tất cả hoặc riêng lẻ, đồng thời cho phép bạn chặnHoặc cho phép việc sử dụng cookie cho tất cả các trang web hoặc các trang web được chọn riêng lẻ. Bạn cũng có thể tắt riêng cookie của bên thứ ba. Xin lưu ý rằng các cài đặt do trình duyệt hoặc thiết bị cung cấp thường chỉ áp dụng cho trình duyệt hoặc thiết bị cụ thể đó. </p>
<h3> Thông tin cookie thường được tìm thấy trong phần Trợ giúp của trình duyệt web. </h3>
<p> Sau đây là các liên kết đến một số trình duyệt web được sử dụng phổ biến: </p>
<p><a href="https://support.google.com/chrome/answer/95647?hl=en"> Chrome </a> <br>
<a href="https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies"> Internet Explorer và Microsoft Edge </a> <br>
<a href="https://support.mozilla.org/en/kb/kuki-informaciya-kotoruyu-veb-sajty-hranyat-na-vas"> Mozilla Firefox </a> <br>
<a href="https://support.apple.com/ru-ru/guide/safari/sfri11471/mac"> Safari </a> </p>
<p> Bạn có thể tắt một số cookie của bên thứ ba để nhắm mục tiêu/quảng cáo bằng cách nhấp vào liên kết sau: <a href="http://optout.networkadvertising.org/?c=1"> Rút lui khỏi quảng cáo dựa trên sở thích </a>. </p>
				',
];
