<?php

return [
    'title' => 'Cursor Style - Chính sách bảo mật',
    'descr' => 'Trong “Cursor Style,” có sẵn trên cursor.style hoặc thông qua tiện ích mở rộng Chrome, một trong những ưu tiên hàng đầu của chúng tôi là quyền riêng tư của khách truy cập. Trong phần này, chúng tôi sẽ nói về tất cả các khía cạnh của việc làm việc với tiện ích mở rộng.',
    'text' => '<h2> Chính Sách Bảo Mật </h2>
                <p> Trong  Cursor Style, có sẵn tại <a href="https://cursor.style"> cursor.style </a> hoặc thông qua tiện ích mở rộng Chrome, một trong những ưu tiên hàng đầu của chúng tôi là quyền riêng tư của khách truy cập. Tài liệu Chính sách Bảo mật này chứa các loại thông tin được thu thập và ghi lại bởi trang web cursor.style và cách chúng tôi sử dụng nó. Nếu bạn có thêm câu hỏi hoặc cần thêm thông tin về Chính sách Bảo mật của chúng tôi, đừng ngần ngại liên hệ với chúng tôi. </p>
                <p> Tiện ích mở rộng "Cursor Style" và trang web tuân theo quy trình tiêu chuẩn để sử dụng các tệp nhật ký. Các tệp này đăng ký khách truy cập khi họ truy cập các trang web hoặc sử dụng tiện ích mở rộng của chúng tôi. Tất cả các công ty lưu trữ đều làm điều này và là một phần của phân tích dịch vụ lưu trữ. Thông tin thu thập được thông qua các tệp nhật ký bao gồm địa chỉ Giao thức Internet (IP), loại trình duyệt, Nhà cung cấp dịch vụ Internet (ISP), dấu thời gian và ngày tháng, trang chuyển đổi / thoát và có thể là số lần nhấp. Chúng không được liên kết với bất kỳ thông tin nhận dạng cá nhân nào. Mục đích của thông tin này là để phân tích xu hướng, quản lý trang web và mở rộng, theo dõi chuyển động của người dùng trên trang web và mở rộng, đồng thời thu thập thông tin nhân khẩu học. </p>
                <p> Giống như bất kỳ trang web nào khác, cursor.style sử dụng cookie. Các cookie này được sử dụng để lưu trữ thông tin, bao gồm tùy chọn của khách truy cập và các trang trên trang web mà khách truy cập đã truy cập hoặc đã truy cập. Thông tin này được sử dụng để tối ưu hóa trải nghiệm người dùng bằng cách tùy chỉnh nội dung trang web của chúng tôi dựa trên loại trình duyệt của khách truy cập và / hoặc các thông tin khác. Chúng tôi cũng sử dụng quảng cáo của bên thứ ba trên cursor.style để hỗ trợ dự án và hỗ trợ trang web của chúng tôi. Một số nhà quảng cáo này có thể sử dụng các công nghệ như cookie và đèn hiệu web khi họ quảng cáo trên trang web của chúng tôi, điều này cũng sẽ gửi cho các nhà quảng cáo này (ví dụ: Google thông qua chương trình Google AdSense) thông tin, bao gồm địa chỉ IP của bạn, nhà cung cấp Internet của bạn, trình duyệt mà bạn đã sử dụng để truy cập trang web của chúng tôi và trong một số trường hợp, nếu bạn đã cài đặt Flash. Điều này thường được sử dụng cho các mục đích nhắm mục tiêu theo địa lý (ví dụ: hiển thị quảng cáo để bán hàng hóa trong thành phố của bạn) hoặc để hiển thị một số quảng cáo nhất định dựa trên một số trang web đã truy cập (ví dụ: hiển thị thông báo mua hàng cho những người thường xuyên truy cập các trang web mua sắm). </p>
                <p> Bạn có thể tắt hoặc tắt chọn lọc cookie của chúng tôi hoặc cookie của bên thứ ba trong cài đặt trình duyệt hoặc bằng cách quản lý cài đặt trong các chương trình như Kaspersky, v.v. Tuy nhiên, điều này có thể ảnh hưởng đến cách bạn tương tác với trang web của chúng tôi, cũng như với các trang web khác. Điều này có thể bao gồm việc không thể đăng nhập vào các dịch vụ hoặc chương trình, chẳng hạn như đăng nhập vào diễn đàn hoặc tài khoản. </p>
<p> Google là một trong những nhà cung cấp bên thứ ba trên trang web của chúng tôi. Nó cũng sử dụng cookie, được gọi là cookie DART, để phân phát quảng cáo cho khách truy cập trang web của chúng tôi dựa trên lượt truy cập của họ vào cursor.style và các trang web khác trên Internet. Tuy nhiên, khách truy cập có thể chọn không sử dụng cookie DART bằng cách truy cập chính sách bảo mật của Mạng nội dung và quảng cáo của Google tại <a href="https://policies.google.com/technologies/ads"> địa chỉ sau </a>. Một số nhà quảng cáo trên trang web của chúng tôi có thể sử dụng cookie và đèn hiệu web. Mỗi đối tác quảng cáo của chúng tôi đều có chính sách bảo mật riêng cho các chính sách liên quan đến dữ liệu người dùng. Bạn có thể đọc thêm về Chính sách Bảo mật của họ <a href="https://policies.google.com/technologies/ads"> tại đây </a>. </p>
                <p> Trang web của chúng tôi sử dụng Google Analytics, một dịch vụ phân tích web của Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com (“Google Analytics” hoặc “Google”). Google Analytics sử dụng cookie được lưu trữ trên máy tính của bạn để tạo điều kiện phân tích việc bạn sử dụng trang web. Thông tin được tạo bởi các cookie này, chẳng hạn như thời gian, địa điểm và tần suất bạn truy cập trang web của chúng tôi, bao gồm địa chỉ IP của bạn, được chuyển đến một địa điểm của Google ở Hoa Kỳ và được lưu trữ ở đó. Google cũng có thể chuyển thông tin này cho bên thứ ba nếu luật pháp yêu cầu hoặc nếu bên thứ ba xử lý dữ liệu này thay mặt Google. Google tuyên bố rằng họ sẽ không bao giờ liên kết địa chỉ IP của bạn với dữ liệu Google khác. Bạn có thể ngăn chặn việc cài đặt cookie bằng cách thay đổi cài đặt phần mềm trình duyệt của mình cho phù hợp, như được chỉ định trong Chính sách Bảo mật này. Tuy nhiên, bạn nên biết rằng bằng cách này, bạn sẽ không thể sử dụng đầy đủ tất cả các chức năng của trang web của chúng tôi. </p>
                <p> Google Analytics cũng sử dụng các hình ảnh điện tử được gọi là đèn hiệu web (đôi khi được gọi là GIF một điểm ảnh) và được sử dụng với cookie để tổng hợp số liệu thống kê để phân tích việc sử dụng trang web của chúng tôi.
Bạn có thể tìm thêm thông tin về cách cài đặt tiện ích bổ sung trình duyệt mà bạn liên kết ở trên <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> liên kết </a>.
Trang web này sử dụng Google Tag Manager. Dịch vụ này cho phép bạn quản lý thẻ trang web thông qua giao diện. Google Tag Manager chỉ triển khai các thẻ. Điều này có nghĩa là cookie không được đặt và không có dữ liệu cá nhân nào được ghi lại. Google Tag Manager khởi chạy các thẻ khác và những thẻ này có thể ghi lại dữ liệu. Tuy nhiên, Google Tag Manager không có quyền truy cập vào dữ liệu này. Nếu các thẻ đã bị tắt ở cấp miền hoặc cookie, chúng sẽ được lưu cho tất cả các thẻ theo dõi, nếu được triển khai bằng Google Tag Manager. Bạn có thể tìm hiểu thêm về Google Tag Manager bằng cách truy cập <a href="http://www.google.com/tagmanager/use-policy.html"> liên kết </a>. </p>
<p> Bạn có thể làm quen với danh sách này để tìm Chính sách Bảo mật cho từng đối tác quảng cáo của "Cursor Style". Các máy chủ quảng cáo hoặc mạng quảng cáo của bên thứ ba sử dụng các công nghệ như cookie, JavaScript hoặc đèn hiệu web, được sử dụng trong các quảng cáo và liên kết tương ứng của họ, được hiển thị trong “Cursor Style” và được gửi trực tiếp đến trình duyệt của người dùng. Họ tự động nhận địa chỉ IP của bạn khi điều này xảy ra. Các công nghệ này được sử dụng để đo lường hiệu quả của các chiến dịch quảng cáo của họ và / hoặc để cá nhân hóa nội dung quảng cáo mà bạn nhìn thấy trên các trang web bạn truy cập. Vui lòng lưu ý rằng “Cursor Style” không có quyền truy cập hoặc kiểm soát các cookie này được sử dụng bởi các nhà quảng cáo bên thứ ba. Chính sách bảo mật của Cursor Style không áp dụng cho các nhà quảng cáo hoặc trang web khác. Do đó, chúng tôi khuyên bạn nên xem lại các chính sách bảo mật có liên quan của các máy chủ quảng cáo của bên thứ ba này để biết thêm thông tin. Nó có thể bao gồm các phương pháp và hướng dẫn của họ về cách chọn không tham gia các tùy chọn nhất định. Bạn có thể tìm các liên kết đến Chính sách Bảo mật của Bên thứ Ba này ở trên hoặc trên các trang web của các dịch vụ bên thứ ba này. </p>
                <p> Bạn có thể tắt cookie trong cài đặt trình duyệt của mình. Để tìm hiểu thêm về quản lý cookie trong các trình duyệt web cụ thể, bạn có thể tìm thấy nó trên các trang web trình duyệt tương ứng của họ. Một phần khác trong những ưu tiên của chúng tôi là thêm sự bảo vệ trẻ em khi sử dụng Internet. Chúng tôi khuyến khích cha mẹ và người giám hộ quan sát, tham gia và / hoặc giám sát và chỉ đạo các hoạt động của họ trên Internet.  "Cursor Style" không cố tình thu thập thông tin cá nhân từ trẻ em dưới 13 tuổi. Nếu bạn nghĩ rằng con bạn đã cung cấp thông tin đó trên trang web của chúng tôi, chúng tôi thực sự khuyên bạn nên liên hệ với chúng tôi ngay lập tức và chúng tôi sẽ cố gắng hết sức để nhanh chóng xóa thông tin đó khỏi hồ sơ của chúng tôi. Chính sách Bảo mật này chỉ áp dụng cho các hoạt động trực tuyến của chúng tôi và có hiệu lực đối với khách truy cập trang web của chúng tôi liên quan đến thông tin mà họ chia sẻ và / hoặc thu thập trong “Cursor Style”. Chính sách này không áp dụng cho bất kỳ thông tin nào được thu thập ngoại tuyến hoặc thông qua các kênh khác ngoài trang web này. </p>
                <p> Bạn có thể đọc thêm về việc sử dụng cookie trong Dịch vụ của chúng tôi trong <a href="/cookie-policy"> Chính sách Cookie </a> của chúng tôi. </p> ',
];
