<?php

return [
    'title' => 'Сursor Style - Điều khoản sử dụng sản phẩm của chúng tôi',
    'descr' => 'Điều khoản sử dụng được thiết lập giữa bạn và “Cursor Style” (“Dịch vụ”, “chúng tôi” hoặc “Dịch vụ”). Dịch vụ này được cung cấp và dành cho người dùng từ 13 tuổi trở lên chỉ sử dụng cho mục đích cá nhân và không sử dụng cho mục đích thương mại.',
    'text' => '<h2> Điều Khoản Dịch Vụ </h2>
<h3> VUI LÒNG ĐỌC CÁC ĐIỀU KHOẢN VÀ ĐIỀU KIỆN NÀY TRƯỚC KHI SỬ DỤNG TRANG WEB VÀ TIỆN ÍCH MỞ RỘNG. </h3>
<p> Các điều khoản sử dụng này được thỏa thuận giữa bạn và "Cursor Style" ("Dịch vụ", "chúng tôi" hoặc "Dịch vụ"). Các điều khoản và điều kiện sau đây, cùng với bất kỳ tài liệu nào mà chúng bao gồm rõ ràng bằng cách tham chiếu (gọi chung là “Điều khoản sử dụng” này), quản lý việc bạn truy cập và sử dụng trang web cursor.style và các tiện ích mở rộng trình duyệt của nó, bao gồm mọi nội dung, chức năng và dịch vụ được cung cấp trên hoặc thông qua dịch vụ của chúng tôi (gọi chung là “Dịch vụ”). </p>
<p> Bằng cách sử dụng trang web hoặc tiện ích mở rộng, bạn chấp nhận và đồng ý tuân thủ các Điều khoản sử dụng này. Nếu bạn không đồng ý với các Điều khoản sử dụng này hoặc <a href="/privacy"> Chính sách bảo mật </a> của chúng tôi, bạn không nên truy cập hoặc sử dụng Trang web và Tiện ích mở rộng. </p>
<p> Dịch vụ này chỉ được cung cấp và khả dụng cho người dùng từ 13 tuổi trở lên chỉ cho mục đích sử dụng cá nhân và không sử dụng cho mục đích thương mại. Bằng cách sử dụng Dịch vụ này, bạn tuyên bố và đảm bảo rằng bạn (I) từ 13 tuổi trở lên, (II) bạn không bị cấm sử dụng Trang web theo luật hiện hành và (III) bạn chỉ sử dụng Dịch vụ cho nhu cầu cá nhân của mình. Nếu bạn không đáp ứng các yêu cầu này, bạn không nên truy cập hoặc sử dụng Dịch vụ. </p>
<p> Chúng tôi có thể sửa đổi và cập nhật các Điều khoản sử dụng này theo thời gian theo quyết định của chúng tôi. Tất cả các thay đổi có hiệu lực ngay sau khi chúng được công bố. Việc bạn tiếp tục sử dụng Dịch vụ sau khi công bố các Điều khoản sử dụng đã sửa đổi có nghĩa là bạn chấp nhận và đồng ý với các thay đổi. Bạn dự kiến sẽ truy cập trang này thường xuyên để theo kịp mọi thay đổi vì chúng ràng buộc bạn. </p>
<p> Chúng tôi có quyền rút tiền hoặc sửa đổi Trang web và Tiện ích mở rộng này, bất kỳ dịch vụ hoặc tài liệu nào mà chúng tôi cung cấp trên Trang web và Tiện ích mở rộng, theo quyết định riêng của chúng tôi, mà không cần thông báo. Chúng tôi không đảm bảo rằng trang web, tiện ích mở rộng của chúng tôi hoặc bất kỳ nội dung nào trên đó sẽ luôn khả dụng hoặc sẽ bị gián đoạn. Chúng tôi sẽ không chịu trách nhiệm nếu vì bất kỳ lý do gì mà tất cả hoặc bất kỳ phần nào của Dịch vụ không khả dụng tại bất kỳ thời điểm nào hoặc trong bất kỳ khoảng thời gian nào. Theo thời gian, chúng tôi có thể hạn chế quyền truy cập vào một số phần nhất định của Trang web hoặc Tiện ích mở rộng hoặc toàn bộ Dịch vụ cho người dùng. </p>
<p> Bạn chịu trách nhiệm thực hiện tất cả các biện pháp cần thiết để đảm bảo rằng bạn có quyền truy cập vào Dịch vụ. Đảm bảo rằng tất cả những người truy cập Dịch vụ thông qua kết nối Internet của bạn đều nhận thức được các Điều khoản sử dụng này và tuân thủ chúng. Để truy cập Dịch vụ hoặc một số tài nguyên mà nó cung cấp, bạn có thể được yêu cầu cung cấp thông tin nhất định hoặc thông tin khác. Bạn đồng ý rằng tất cả thông tin mà bạn cung cấp cho chúng tôi bằng cách sử dụng Dịch vụ này hoặc cách khác, bao gồm nhưng không giới hạn việc sử dụng bất kỳ tính năng tương tác nào trong Dịch vụ, được chi phối bởi <a href="/privacy"> Chính sách bảo mật </a> của chúng tôi và bạn đồng ý với tất cả các hành động mà chúng tôi thực hiện liên quan đến thông tin của bạn. theo <a href="/privacy"> Chính sách bảo mật </a> của chúng tôi. </p>
<p> Bạn phải đặc biệt cẩn thận khi nhập thông tin cá nhân vào Dịch vụ trên máy tính công cộng hoặc dùng chung để những người khác không thể xem hoặc ghi lại thông tin cá nhân của bạn. Trang web, tiện ích mở rộng và tất cả nội dung, chức năng và tính năng của nó (bao gồm, nhưng không giới hạn, tất cả thông tin, tiện ích mở rộng, văn bản, hình ảnh, hình ảnh, hình ảnh và con trỏ, cũng như thiết kế, lựa chọn và vị trí của chúng) thuộc về "Cursor Style", người cấp phép của nó hoặc các nhà cung cấp khác của các tài liệu đó được bảo vệ bởi luật bản quyền, thương hiệu, bằng sáng chế, bí mật thương mại và các luật hoặc quyền sở hữu trí tuệ khác. </p>
<p> Các Điều khoản sử dụng này cho phép bạn chỉ sử dụng Trang web cho mục đích cá nhân, phi thương mại của bạn. Bạn không được sao chép, phân phối, sửa đổi, tạo ra tác phẩm phái sinh, tái xuất bản, tải xuống, lưu trữ hoặc truyền tải bất kỳ tài liệu nào trên Trang web của chúng tôi, ngoại trừ các trường hợp sau: bạn có thể sử dụng nó cho nhu cầu cá nhân, bạn có thể in hoặc tải xuống một bản sao của một số lượng hợp lý các trang của Trang web và Tiện ích mở rộng hoặc nội dung của chúng cho mục đích sử dụng cá nhân, phi thương mại và không để tái sản xuất, xuất bản hoặc phân phối thêm. </p>
<p> Bạn không được sửa đổi các bản sao của bất kỳ tài liệu nào từ trang web hoặc tiện ích mở rộng này và nội dung của chúng. Xóa hoặc sửa đổi bất kỳ thông báo bản quyền, nhãn hiệu hoặc thông báo độc quyền nào khác khỏi các bản sao của trang web và tiện ích mở rộng này. Bạn không được truy cập hoặc sử dụng cho bất kỳ mục đích thương mại nào bất kỳ phần nào của Trang web hoặc tiện ích mở rộng, cũng như bất kỳ dịch vụ hoặc tài liệu nào có sẵn thông qua Trang web hoặc Tiện ích mở rộng. </p>
<p> Nếu bạn muốn sử dụng bất kỳ tài liệu nào trên Trang web hoặc Tiện ích mở rộng nào khác với những tài liệu được liệt kê trong phần này, hãy gửi yêu cầu trên trang hỗ trợ của Cửa hàng Chrome trực tuyến. </p>
<p> Nếu bạn in, sao chép, sửa đổi, tải xuống hoặc sử dụng hoặc cung cấp cho bất kỳ người nào khác quyền truy cập vào bất kỳ phần nào của Trang web hoặc Tiện ích mở rộng vi phạm các Điều khoản sử dụng, quyền sử dụng Trang web và Tiện ích mở rộng của bạn sẽ chấm dứt ngay lập tức và bạn phải , theo quyết định của chúng tôi, trả lại hoặc tiêu hủy bất kỳ bản sao nào của tài liệu mà bạn có. Bất kỳ việc sử dụng trang web của tiện ích mở rộng nào mà không được phép rõ ràng theo các Điều khoản sử dụng này đều vi phạm các Điều khoản sử dụng này và có thể vi phạm bản quyền, nhãn hiệu và các luật khác. </p>
<p> Tên “Cursor Style”, logo “Cursor Style” và tất cả tên, logo, hình ảnh, con trỏ và tên dịch vụ, thiết kế và khẩu hiệu liên quan là nhãn hiệu của “Cursor Style” hoặc các chi nhánh hoặc người cấp phép của nó. Bạn không được sử dụng các nhãn hiệu đó mà không có sự cho phép trước bằng văn bản của Dịch vụ. Tất cả các tên, logo, tên sản phẩm và dịch vụ, thiết kế và khẩu hiệu khác trên trang web này và trong tiện ích mở rộng là nhãn hiệu của chủ sở hữu tương ứng của chúng. Bạn chỉ có thể sử dụng Dịch vụ cho các mục đích hợp pháp và theo các Điều khoản sử dụng này. </p>
<h3> Bạn đồng ý KHÔNG sử dụng Dịch vụ: </h3>
<ul>
<li> Bằng bất kỳ cách nào vi phạm bất kỳ luật hoặc quy định liên bang, khu vực, địa phương hoặc quốc tế hiện hành nào (bao gồm, nhưng không giới hạn, bất kỳ luật nào liên quan đến việc xuất dữ liệu hoặc phần mềm sang Nga và các quốc gia khác). </li>
<li> Với mục đích khai thác, làm hại hoặc cố gắng sử dụng hoặc gây hại cho trẻ vị thành niên, để chúng tiếp xúc với nội dung không phù hợp, yêu cầu thông tin nhận dạng chúng hoặc cách khác. </li>
<li> Để gửi, cố ý nhận, tải xuống, sử dụng hoặc tái sử dụng bất kỳ tài liệu nào không tuân thủ các Điều khoản sử dụng này. </li>
<li> Truyền hoặc mua việc gửi bất kỳ quảng cáo hoặc tài liệu quảng cáo nào mà không có sự đồng ý trước bằng văn bản của chúng tôi, bao gồm bất kỳ “thư không được yêu cầu”, “thư dây chuyền” hoặc “thư rác” hoặc bất kỳ lời đề nghị tương tự nào khác. </li>
<li> Để mạo danh hoặc cố gắng mạo danh một nhân viên của “Cursor Style”, một người dùng khác hoặc bất kỳ người hoặc tổ chức nào khác (bao gồm nhưng không giới hạn việc sử dụng địa chỉ email hoặc bí danh liên kết với bất kỳ mục nào ở trên). </li>
<li> Tham gia vào bất kỳ hành động nào khác hạn chế hoặc cản trở việc sử dụng Dịch vụ hoặc việc sử dụng của bất kỳ ai hoặc theo quyết định của chúng tôi, có thể gây hại cho Dịch vụ hoặc người dùng Dịch vụ hoặc khiến họ phải chịu trách nhiệm pháp lý. </li> </ul>
<h3> Ngoài ra, bạn đồng ý KHÔNG: </h3>
<ul>
<li> Sử dụng Dịch vụ theo bất kỳ cách nào có thể vô hiệu hóa, quá tải, làm hỏng hoặc làm suy giảm hoạt động của trang web, mở rộng hoặc can thiệp vào việc sử dụng Dịch vụ của bất kỳ bên nào khác, bao gồm khả năng của họ tham gia vào các hành động theo thời gian thực thông qua Dịch vụ. </li>
<li> Sử dụng bất kỳ công cụ tự động hóa, quy trình hoặc phương tiện nào để truy cập Dịch vụ cho bất kỳ mục đích nào, bao gồm giám sát hoặc sao chép bất kỳ tài liệu nào trong Dịch vụ. </li>
<li> Sử dụng bất kỳ quy trình thủ công nào để theo dõi hoặc sao chép bất kỳ tài liệu nào trên Dịch vụ hoặc cho bất kỳ mục đích trái phép nào khác mà không có sự đồng ý trước bằng văn bản của chúng tôi. </li>
<li> Sử dụng bất kỳ thiết bị, phần mềm hoặc quy trình nào cản trở hoạt động bình thường của Dịch vụ. </li>
<li> Giới thiệu bất kỳ vi-rút, ngựa thành Troy, sâu, bom logic hoặc các tài liệu khác có hại hoặc có hại về công nghệ. </li>
<li> Cố gắng truy cập trái phép, can thiệp, làm hỏng hoặc phá vỡ bất kỳ phần nào của Dịch vụ, máy chủ nơi Dịch vụ được lưu trữ hoặc bất kỳ máy chủ, máy tính hoặc cơ sở dữ liệu nào được kết nối với Dịch vụ. </li>
<li> Tấn công Dịch vụ bằng cách sử dụng một cuộc tấn công từ chối dịch vụ hoặc một cuộc tấn công từ chối dịch vụ phân tán. </li> </ul>
<p> Thông tin được cung cấp trên hoặc thông qua Dịch vụ chỉ được cung cấp cho mục đích thông tin chung. Chúng tôi không đảm bảo tính chính xác, đầy đủ hoặc hữu ích của thông tin này. Bạn dựa vào thông tin đó chỉ chịu rủi ro của riêng bạn. Chúng tôi từ chối mọi trách nhiệm và nghĩa vụ phát sinh từ bất kỳ sự phụ thuộc nào vào các tài liệu đó của bạn, bất kỳ khách truy cập nào khác vào Dịch vụ hoặc bất kỳ ai có thể được thông báo về bất kỳ nội dung nào của họ. </p>
<p> Dịch vụ này bao gồm nội dung do bên thứ ba cung cấp, bao gồm các tài liệu do những người dùng khác và người cấp phép, nhà cung cấp, người tổng hợp và / hoặc dịch vụ báo cáo của bên thứ ba cung cấp. Tất cả các tuyên bố và / hoặc ý kiến được thể hiện trong các tài liệu này, cũng như tất cả các bài viết và câu trả lời cho các câu hỏi và nội dung khác, ngoại trừ nội dung do Dịch vụ cung cấp, chỉ là ý kiến và trách nhiệm của người hoặc tổ chức cung cấp các tài liệu này. Các tài liệu này không nhất thiết phản ánh quan điểm của Dịch vụ. Chúng tôi không chịu trách nhiệm với bạn hoặc bất kỳ bên thứ ba nào về nội dung hoặc tính chính xác của bất kỳ tài liệu nào do bên thứ ba cung cấp. </p>
<p> Chúng tôi có thể cập nhật nội dung của Dịch vụ theo thời gian, nhưng nội dung của nó không nhất thiết phải đầy đủ hoặc hiện tại. Bất kỳ tài liệu nào trên Dịch vụ có thể đã lỗi thời tại bất kỳ thời điểm nào và chúng tôi không có nghĩa vụ phải cập nhật tài liệu đó. Chúng tôi có thể cập nhật, sửa đổi, sửa đổi thông tin và nội dung trên Trang web và trong Tiện ích mở rộng, thực hiện bất kỳ thay đổi và cập nhật nào theo quyết định của riêng chúng tôi. </p>
<p> Tất cả thông tin mà chúng tôi thu thập trên Dịch vụ này đều phải tuân theo Chính sách bảo mật của chúng tôi. Bằng cách sử dụng Dịch vụ, bạn đồng ý với tất cả các hành động do chúng tôi thực hiện liên quan đến thông tin của bạn theo <a href="/privacy"> Chính sách bảo mật </a>. </p>
<p> Các điều khoản bổ sung cũng có thể áp dụng cho một số phần, dịch vụ hoặc tính năng nhất định của Dịch vụ. Tất cả các điều khoản và điều kiện bổ sung đó bằng văn bản này được kết hợp bằng cách tham chiếu vào các Điều khoản sử dụng này.
Bạn có thể liên kết đến trang web hoặc tiện ích mở rộng của chúng tôi nếu bạn thực hiện theo cách trung thực và hợp pháp và không làm tổn hại đến danh tiếng của chúng tôi hoặc sử dụng nó, nhưng bạn không nên đặt liên kết theo cách cung cấp bất kỳ hình thức liên kết, xác nhận hoặc xác nhận nào từ phía chúng tôi mà không có sự đồng ý bằng văn bản của chúng tôi. </p>
<p> Dịch vụ có chứa các liên kết đến các trang web và tài nguyên khác do bên thứ ba cung cấp, các liên kết này chỉ được cung cấp để bạn thuận tiện. Điều này bao gồm các liên kết có trong quảng cáo, bao gồm quảng cáo biểu ngữ và liên kết được tài trợ. Chúng tôi không kiểm soát nội dung của các trang web hoặc tài nguyên này và không chịu trách nhiệm về chúng hoặc về bất kỳ tổn thất hoặc thiệt hại nào có thể phát sinh từ việc sử dụng chúng. Nếu bạn quyết định truy cập bất kỳ trang web nào của bên thứ ba có liên quan đến Dịch vụ này, bạn làm như vậy là tự chịu rủi ro và theo các điều khoản sử dụng của các trang web đó. Chúng tôi có quyền thu hồi quyền liên kết mà không cần thông báo trước. </p>
<p> Bạn hiểu rằng chúng tôi không thể và không đảm bảo hoặc bảo đảm rằng các tệp có sẵn để tải xuống qua Internet hoặc trên Trang web sẽ không chứa vi-rút hoặc mã độc hại khác. Bạn chịu trách nhiệm thực hiện các quy trình và điểm kiểm soát đầy đủ để đáp ứng các yêu cầu đặc biệt của bạn về bảo vệ chống vi-rút và tính chính xác của việc nhập và xuất dữ liệu, cũng như duy trì các phương tiện bên ngoài trang web của chúng tôi để khôi phục bất kỳ dữ liệu nào bị mất. CHÚNG TÔI SẼ KHÔNG CHỊU TRÁCH NHIỆM VỀ BẤT KỲ THIỆT HẠI HOẶC THƯƠNG TÍCH NÀO GÂY RA bởi cuộc tấn công từ chối dịch vụ phân tán, vi-rút hoặc phần mềm độc hại công nghệ khác được LẤY QUA DỊCH VỤ, HOẶC DO TẢI XUỐNG BẤT KỲ TÀI LIỆU NÀO ĐƯỢC ĐĂNG TRÊN ĐÂY HOẶC BẤT KỲ TRANG WEB NÀO, LIÊN QUAN ĐẾ CÓ THỂ LÂY NHIỄM HOẶC GÂY HỎNG THIẾT BỊ MÁY TÍNH, PHẦN MỀM MÁY TÍNH, DỮ LIỆU CỦA BẠN. </p>
<p> BẠN SỬ DỤNG DỊCH VỤ, NỘI DUNG CỦA NÓ VÀ BẤT KỲ DỊCH VỤ HOẶC MỤC NÀO CÓ ĐƯỢC QUA CÁC DỊCH VỤ HOÀN TOÀN DO BẠN CHỊU RỦI RO. DỊCH VỤ, NỘI DUNG CỦA NÓ VÀ BẤT KỲ DỊCH VỤ HOẶC MỤC NÀO CÓ ĐƯỢC THÔNG QUA TRANG WEB VÀ TIỆN ÍCH MỞ RỘNG, ĐƯỢC CUNG CẤP TRÊN CƠ SỞ “NGUYÊN TRẠNG” VÀ “KHI CÓ SẴN”, KHÔNG CÓ BẤT KỲ BẢO HÀNH NÀO. BẤT KỲ NGƯỜI NÀO LIÊN QUAN ĐẾN DỊCH VỤ KHÔNG CUNG CẤP BẤT KỲ BẢO HÀNH HOẶC ĐẠI DIỆN NÀO ĐỐI VỚI SỰ HOÀN THIỆN, AN TOÀN, ĐỘ TIN CẬY, CHẤT LƯỢNG, ĐỘ CHÍNH XÁC HOẶC KHẢ NĂNG TRUY CẬP CỦA DỊCH VỤ. KHÔNG GIỚI HẠN Ở TRÊN, KHÔNG CÓ “CURSOR STYLE” CŨNG NHƯ CÁC ĐẠI DIỆN LIÊN QUAN ĐẾN “CURSOR STYLE”KHÔNG ĐẢM BẢO RẰNG TRANG WEB, TIỆN ÍCH MỞ RỘNG, NỘI DUNG HOẶC BẤT KỲ SỬA CHỮA NÀO KHÁC PHẢI ĐƯỢC SỬA CHỮA TRƯỚC KHI CÓ SẴN RẰNG TIỆN ÍCH MỞ RỘNG, MỘT TRANG WEB HOẶC MỘT MÁY CHỦ NƠI NÓ ĐƯỢC ĐẶT, SẼ KHÔNG CÓ VI-RÚT HOẶC CÁC THÀNH PHẦN CÓ HẠI KHÁC HOẶC TRANG WEB NÀY HOẶC BẤT KỲ DỊCH VỤ HOẶC MỤC NÀO ĐƯỢC THỰC HIỆN, ĐƯỢC ƯA CHUỘNG.
<p> Trong mọi trường hợp, DỊCH VỤ, CÁC CHI NHÁNH CỦA NÓ HOẶC CÁC NHÀ CẤP PHÉP, DỊCH VỤ, NHÂN VIÊN, ĐẠI DIỆN, CÁN BỘ hoặc GIÁM ĐỐC KHÔNG CHỊU TRÁCH NHIỆM VỀ THIỆT HẠI DƯỚI BẤT KỲ HÌNH THỨC NÀO, CHÚNG TÔI DỊCH VỤ VỚI BẤT KỲ TRÁCH NHIỆM PHÁP LÝ NÀO. HOẶC CÁC TRANG WEB KHÁC HOẶC BẤT KỲ DỊCH VỤ HOẶC MỤC NÀO CÓ ĐƯỢC TRONG DỊCH VỤ HOẶC ĐẾN CÁC TRANG WEB KHÁC, BAO GỒM BẤT KỲ THIỆT HẠI TRỰC TIẾP, ĐẶC BIỆT HOẶC DO HẬU QUẢ, BAO GỒM THƯƠNG TÍCH CÁ NHÂN, rối loạn cảm xúc, THIỆT HẠI HOẶC TIẾT KIỆM DỰ KIẾN, MẤT SỬ DỤNG, DỮ LIỆU HOẶC CÁC ĐIỀU KIỆN KHÁC. Định nghĩa KHÔNG ẢNH HƯỞNG BẤT KỲ TRÁCH NHIỆM NÀO CÓ THỂ KHÔNG BỊ LOẠI TRỪ HOẶC GIỚI HẠN THEO LUẬT HIỆN HÀNH CÓ THỂ BAO GỒM LỪA ĐẢO. </p>
<p> Bạn đồng ý bảo vệ, bồi thường và làm sai lệch “Cursor Style”, các chi nhánh, người cấp phép và nhà cung cấp dịch vụ, cũng như các cán bộ, giám đốc, nhân viên, nhà thầu, đại lý, người cấp phép, nhà cung cấp, người được chỉ định của họ và từ bất kỳ khiếu nại và trách nhiệm pháp lý nào, mất quyết định của tòa án, chi phí, chi phí hoặc hoa hồng (bao gồm phí luật sư) phát sinh từ hoặc liên quan đến việc bạn vi phạm các Điều khoản sử dụng này hoặc việc sử dụng Dịch vụ của bạn, bao gồm nhưng không giới hạn, việc chấp nhận sự đồng thuận của bất kỳ việc sử dụng nội dung, dịch vụ và sản phẩm của Trang web hoặc Tiện ích mở rộng nào, trừ khi được quy định rõ ràng trong các Điều khoản sử dụng này hoặc việc bạn sử dụng bất kỳ thông tin nào nhận được từ Dịch vụ. </p>
<p> Nếu bất kỳ điều khoản nào trong các Điều khoản sử dụng này được tòa án hoặc tòa án có thẩm quyền khác tuyên là vô hiệu, bất hợp pháp hoặc không thể thi hành vì bất kỳ lý do gì, thì điều khoản đó phải bị bãi bỏ hoặc giới hạn ở mức tối thiểu, để phần còn lại của các điều khoản của Điều khoản sử dụng sẽ tiếp tục đầy đủ nhất. Điều khoản sử dụng, Chính sách bảo mật của chúng tôi và các điều kiện để đăng ký sự kiện cấu thành thỏa thuận duy nhất và đầy đủ giữa bạn và "Cursor Style" liên quan đến Dịch vụ và thay thế tất cả các thỏa thuận, thỏa thuận, tuyên bố và bảo đảm trước đây và đồng thời, bằng văn bản và bằng lời nói, liên quan đến Dịch vụ . </p>
<p> Tất cả các đánh giá, nhận xét, yêu cầu hỗ trợ kỹ thuật và các tin nhắn khác liên quan đến Dịch vụ phải được chuyển đến trang hỗ trợ của “Cursor Style” trong Cửa hàng Chrome trực tuyến. </p> ',
];
