<?php

return [
    'halo_descr' => 'Halo je bojová fantasy mediálna franšíza, ktorú vytvorila spoločnosť Bungie. Založená na pôvodnej trilógii videohier z pohľadu prvej osoby. Dej sa točí okolo udalostí, ktoré sa odohrávajú v živote Master Chiefa, jedného zo skupiny super-vojakov s kódovým označením Spartani, a jeho spoločníčky, umelej inteligencie Cortany. Úspech hier viedol k rozšíreniu franšízy do iných médií: vesmír Halo v súčasnosti zahŕňa mnoho kníh, grafických románov, komiksov, krátkych filmov, animácií a celovečerných filmov.',
    'halo_short_descr' => 'Dotknite sa kurzora artefaktu, možno ste ten vyvolený',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'Bábiky LOL Surprise si zamilovali deti a získali si ich srdcia už od prvých minút. A to ani neprekvapuje, pretože taký úspech je založený na tajomstve, očakávaní zázraku, príjemnom prekvapení, ktoré poteší nielen deti, ale aj ich rodičov. Tajomstvo darčeka sa dieťaťu odhalí až po konečnom rozbaľovaní. V každom prípade, bábiky LOL sú atraktívny dizajn, intriga, veľké množstvo úžasných a realistických doplnkov a príjemných drobností, ako aj najvyššia kvalita výroby a detailov hračky.',
    'lol_surprise_short_descr' => 'Skvelé roztomilosti pre znalcov krásnych prekvapení',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Séria sa točí okolo súťaže, v ktorej 456 hráčov, všetci hlboko zadlžení, riskujú svoje životy, aby hrali sériu smrteľných detských hier s cieľom vyhrať miliardovú cenu. Vnútri čaká lákavá cena so smrteľne vysokými stávkami. Názov seriálu vychádza z rovnomennej kórejskej detskej hry. Hwang vymyslel túto myšlienku na základe svojich vlastných ekonomických problémov v mladosti, ako aj triednych rozdielov v Južnej Kórei a kapitalizme.',
    'squid_game_short_descr' => 'Vyberte si správnu tvár hráča, keď idete na všetko',
    'squid_game' => 'Hra na kalmára',
    'harry_potter_descr' => 'Harry James Potter je hlavnou postavou série románov anglickej spisovateľky JK Rowlingovej. Na svoje jedenáste narodeniny sa Harry dozvedá, že je čarodejník a je určený pre miesto v Rokfortskej strednej škole čarodejníckej, kde bude praktizovať mágiu pod vedením riaditeľa Albusa Dumbledora a ďalších profesorov školy. Harry tiež zisťuje, že je už známy v celej magickej komunite románu a že jeho osud je spojený s osudom Voldemorta, nebezpečného temného mága.',
    'harry_potter_short_descr' => 'Čo urobíš s čarovnou paličkou zo zbierky kurzorov Harryho Pottera',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics je vydavateľstvo komiksov známe vytvorením pozoruhodných superhrdinov ako Spider-Man, Iron Man, Captain America, Hulk, Thor, Avengers, Guardians of the Galaxy, X-Men, Fantastická štvorka a Deadpool. Medzi najznámejších darebákov Marvelu patria Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom a Magneto. Marvel Comics a DC Comics spolupracovali na niekoľkých crossover projektoch a tiež spoluzaložili zámerne krátkodobú edíciu Amalgam Comics.',
    'marvel_comics_short_descr' => 'Superhrdina žije v každom z nás - vyber si toho svojho',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Vitajte späť v Kráľovstvo sušienok v Cookie Run: Kingdom od Devsisters, rozkošnej strategickej RPG zasadenéj vo vesmíre Cookie Run. Teraz, keď GingerBrave unikol zo zlej čarodejníckej rúry, je čas, aby zostavil tím Sušienok a vydal sa na výpravu na obnovu padnutého Kráľovstva sušienok. Odhaľte pravdu o páde Kráľovstva a dajte dokopy tím najmocnejších Sušienok z Kráľovstva, aby ste porazili temné sily, ktoré chcú zabrániť GingerBraveovi v splnení jeho osudu.',
    'cookie_run_kingdom_short_descr' => 'Malí bojovníci priamo z rúry',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact je dobrodružná hra s otvoreným svetom. To znamená, že vás na druhej strane rieky alebo hory čaká nová, nádherná krajina, stačí len múdro využívať svoju energiu. Ak narazíte na túlavú vílu alebo zvláštny mechanizmus, odvážte sa a pokúste sa rozlúštiť ich záhadu. Ale čo sľubujú - problémy alebo príjemné prekvapenie - to môžete zistiť len vy! Na rozsiahlej pevnine Teyvat navštívite sedem kráľovstiev, nájdete spoločníkov s rôznymi schopnosťami a budete bojovať proti mocným nepriateľom pri hľadaní stratenej milovanej osoby.',
    'genshin_impact_short_descr' => 'Staňte sa elementárnym majstrom siedmich kráľovstiev',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Keď sa naplní staroveká veštba a kráľovstvo sa ponorí do objatia zimy, traja nebojácni hrdinovia - princezná Anna, statočný Kristoff a jeho verný sob Sven - sa vydávajú do hôr, aby našli Anninu sestru Elsu, ktorá dokáže z krajiny odstrániť ľadové kúzlo. Cestou na nich čaká množstvo ťažkých prekvapení a vzrušujúcich dobrodružstiev. Stretnutie s mystickými trolmi, stretnutie s očarujúcim snehuliakom menom Olaf, horské štíty strmšie ako Everest a množstvo mágie. Hrdinovia musia odolávať mocným živlom, aby zachránili kráľovstvo a tých, ktorí sú im drahí.',
    'frozen_short_descr' => 'Prelomenie ľadu je jednoduché so zbierkou kurzorov z Ľadového kráľovstva.',
    'frozen' => 'Ľadové kráľovstvo',
    'stranger_things_descr' => 'Ubehlo o niečo viac ako šesť mesiacov od finále tretej sezóny. Joyce, Will, Eleven a Jonathan sa presťahovali do Kalifornie, kde je dievča šikanované v škole. Zvyšok začína bojovať s novým monštrom z paralelného sveta, ktoré sa objavilo v Hawkine. Bol pomenovaný Vecna ​​po postave z doskovej hry Dungeons & Dragons. Psychologicky ovplyvňuje tínedžerov, potom mentálne vlieza do hlavy a zabíja. Paralelne sa Joyce a Murray dozvedajú, že Jim Gopper je nažive a idú za ním do sovietskeho väzenia v Kamčatke. A Eleven sa bude musieť vrátiť a zvýšiť svoje schopnosti, ale tiež sa dozvedieť svoju dôležitú úlohu pri vytváraní toho istého monštra v Gokins.

Scenáristi nezmenili taktiku deja, ktorá sa im páčila posledných pár sezón. V štvrtej sezóne rozdelili rozsiahlu skupinu hlavných postáv do skupín, vymysleli pre nich náročné úlohy a na konci spojili ich príbehy dohromady v úžasnom závere. Ponúkame vám, aby ste pochopili všetky tieto dobrodružstvá do detailov pomocou zbierky kurzorov Stranger Things.',
    'stranger_things_short_descr' => 'Čo sa stane ďalej? - Kurzory zo Stranger Things 4',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars je originálny režim, ktorý sa prvýkrát objavil v Minecraft. Úlohou hráčov bolo, aby si používateľ chránil svoju základňu a posteľ.

Roblox prináša každý deň vzrušujúcejšie hry a BedWars nie je výnimkou. A ide o to, že ak máte radi bed wars a bránite sa vo svojej izbe, toto je ten titul pre vás, pretože vás vracia do detstva, aj keď tentokrát digitálne.

Jediné, čo musíte urobiť, je brániť svoju posteľ pred útočníkmi so svojím partnerom. Vstúpite do lobby, vyberiete si, s kým budete hrať, a voila, je to len otázka ochrany.

Samozrejme, pokiaľ ide o obranu, budete mať určité problémy a existujú určité zdroje, predmety a položky, ktoré vám pomôžu vyhrať. Napríklad exkluzívne skiny, ktoré nájdete v kolekcii kurzorov Bed Wars.',
    'roblox_bed_wars_short_descr' => 'Chráňte svoju posteľ pomocou kurzorov Roblox Bed Wars',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'V deň narodenín Naruta Uzumakiho zaútočil na dedinu Konoha legendárny démon, Líška s deviatimi chvostami. Štvrtý Hokage obetoval svoj život, aby zachránil dedinu zapečatením démona v novonarodenom Narutovi, čím ho nevedomky odsúdil na život nenávisti od ostatných dedinčanov.
Napriek nedostatku talentu v mnohých oblastiach ninjutsu, nepokojnosti a namyslenosti, má Naruto sen stať sa Hokage, najsilnejším ninjom v dedine. Túžiaci po uznaní, ktorého sa mu nedostalo, tvrdo pracuje a trénuje spolu so svojimi spoluhráčmi Sasuke Uchiha a Sakura Haruno, ako aj so svojím mentorom Kakashi Hatake. On a jeho partneri si budú musieť prejsť mnohým na ceste k ich vytúženým snom: bitkami, láskou, priateľstvom, zradou, túžbou po moci. Kolekcia kurzorov z anime Naruto vám pomôže navigovať vašu vlastnú cestu!',
    'naruto_anime_short_descr' => 'Prejdite svoju nindžovskú cestu s kurzormi z anime Naruto',
    'naruto_anime' => 'Anime Naruto',
    'demon_slayer_anime_descr' => 'Akcia sa odohráva počas éry Taisho. Od staroveku sa šírili fámy, že v lese žijú humanoidní démoni, ktorí sa živia ľuďmi a potulujú sa v noci a hľadajú novú obeť. Ale... je to len legenda, však?..

Tanjiro Kamado je najstarší syn v rodine, ktorý stratil otca a staral sa o svoju rodinu. Jedného dňa ide do blízkeho mesta predať uhlie. Keď sa ráno vracia, chlapec objaví pred sebou strašný obraz: všetci príbuzní boli brutálne zabití a jediná preživšia je Nezuko, mladšia sestra premenená na démona, ale ktorá ešte nestratila všetku svoju ľudskosť.

Od tohto momentu začínajú Tanjiro a Nezuko dlhú a nebezpečnú cestu, na ktorej chlapec má v úmysle nájsť vraha a nájsť spôsob, ako vyliečiť svoju sestru. Ale dokážu deti prekonať všetky ťažkosti a vrátiť sa domov? Odpoveď už poznáte, a ak nie - radšej si nastavte kurzory Demon Slayer s postavami z jednej z najpopulárnejších mang.',
    'demon_slayer_anime_short_descr' => 'Kurzory z anime Zabitý démon - pre skutočných nočných lovcov',
    'demon_slayer_anime' => 'Anime Zabitý démon',
    'bts_descr' => 'BTS je sedemčlenná chlapčenská skupina pod BigHit Music. Debutovali 13. júna 2013 so singlom "No More Dream". V Japonsku debutovali 24. decembra 2014 so štúdiovým albumom Wake Up.

Názov skupiny pochádza z kórejského výrazu Bangtan Sonyeondan, čo znamená "chlapčenskí skauti odolní voči guľkám". Podľa J Hope, názov symbolizuje túžbu kapely blokovať stereotypy, kritiky a očakávania, ktoré sú zamerané na teenagerov ako guľky.

Kolekcia kurzorov venovaná skupine zahŕňa všetkých členov skupiny, tu kurzor Kim Nam Joon (aka RM), kurzor Kim Seok Jin (Jin), kurzor Min Yoongi (Suga), kurzor Jung Ho Suk (J-Hope), kurzor Park Ji Min (Jimin), kurzor Kim Tae Hyun (V) a kurzor Jeon Jungkook (Jungkook).',
    'bts_short_descr' => 'Stretnite sa so svojimi idolmi s kurzormi BTS',
    'bts' => 'BTS',
    'miraculous_descr' => 'Zázračné: Príbehy Lienky a Čierneho Mačiatka, známejšie ako Zázračná Lienka a Čierny Mačiatko, sú dobrodružstvá superhrdinov z kresleného seriálu o dvoch spolužiakoch, ktorí pod maskami hrajú úlohu obrancov Paríža pred záporákom, ktorý v každej epizóde vymyslí nový spôsob, ako ublížiť mestu. Zázračné sa vyrába vo Francúzsku pomocou CGI a animácie. Zázračné nie je len animovaný seriál, ale aj zbierka komiksov vydaných po celom svete. Seriál je veľmi obľúbený u mladého obecenstva.

Dej sa odohráva v Paríži, kde Marinette a Adrian sú študentmi strednej školy v modernej škole. Dostali úlohu stať sa vyvolenými v boji proti zlu, zachraňovať svoje rodné mesto. Ich cieľom je chrániť ľudí pred Akumami. Tieto malé tvory v podobe motýľov sú schopné obsadiť osobu a premeniť ju na záporáka.

Marinette sa môže premeniť na Lienku a Adrian - na Čierneho Mačiatko, ale prekvapivo, pracujúc v pároch, sa pod maskami superhrdinov navzájom nepoznávajú.

Pomôžte Čiernemu Mačiatku a Lienke zachrániť Paríž s našimi kurzormi, ktoré obsahujú vaše obľúbené postavy. Ktorú postavu si vyberiete pre kurzor? Bude to kurzor Zázračnej Lienky, alebo možno roztomilá malá Lienka Tikki alebo kurzor Čierneho Mačiatka? Alebo možno Včelia Kráľovná s Kurzormi Rena Rouge? Výber je na vás!',
    'miraculous_short_descr' => 'Pridajte sa k radom superhrdinov s kolekciou kurzorov Lady Bug a Cat Noir',
    'miraculous' => 'Miraculous: Čarovná Lienka a Čierny Kocúr',
    'talking_tom_descr' => 'Séria sleduje každodenný život Hovoriaceho Toma a jeho priateľov. Tom a jeho uletený obchodný partner Ben neustále vyvíjajú mobilné aplikácie a ďalšie vynálezy, aby dosiahli slávu a bohatstvo a snažili sa predviesť svetu, ale to sa vždy obráti proti nim. Tomova priateľka Angela sa snaží byť speváčkou, nech už na to urobí čokoľvek. Tomov sused Ginger sem veľmi často zbehne robiť žarty s diabolstvom v rukáve. Hlúpy najlepší kamarát a spolubývajúci Hank je ten, čo zostáva doma, sleduje VEĽMI TV. A bývalá disidentská popová hviezda Becca Sparkles sa stala Angelinou novou spolubývajúcou a zdá sa, že sa zamilovala do Hanka. Bez ohľadu na to, aké zlé sú veci všetkých tvarov a veľkostí, či už je to zlý generálny riaditeľ, Tomov záhadný nový sused alebo len nehoda v Benovom novom výtvore, partia sa bude baviť bez ohľadu na to a vždy si zapamätá jednu vec, ktorá ich drží pohromade: priateľstvo nikdy nekončí, rovnako ako nekončí ani naša láska k postavám zo seriálu, takže si teraz môžete nastaviť kurzor Hovoriaceho Toma alebo kurzor Bena, alebo možno kurzor Angely, kurzor Olivera!',
    'talking_tom_short_descr' => 'Poďme sa porozprávať o vašej obľúbenej postave v kolekcii kurzorov Talking Tom',
    'talking_tom' => 'Talking Tom a priatelia',
    'lego_descr' => 'Spoločnosť The LEGO Group bola založená v roku 1932 a vtedy pozostávala len zo 7 ľudí. Cieľom tímu Lego bolo vytvárať hračky, ktoré rozvíjajú detskú kreativitu, fantáziu a vynaliezavosť. Úžasný fakt, od svojho vzniku v roku 1949 zostali LEGO prvky vo všetkých ich variantoch navzájom kompatibilné. Všetky položky vytvorené neskôr sú stále kompatibilné s položkami, ktoré sa vydávajú dnes, napriek zmenám v dizajne a tvare v priebehu rokov.

LEGO tehlička je základňa, čo je dutý plastový blok, ktorý sa spája s inými podobnými tehlami. Ale Lego súpravy obsahujú aj ďalšie časti, kolesá, figúrky, platformy a dokonca aj elektronické obvody so senzormi a elektromotormi. Môžete zbierať modely áut, lietadiel, vlakov, lodí, budov, robotov. LEGO dodržiava myšlienku modularity, ktorá deťom jasne ukazuje, ako riešiť určité problémy, rozvíjať predstavivosť, jemnú motoriku rúk a montážne zručnosti. LEGO tehličky sú vyrobené s neuveriteľnou presnosťou a dokonale do seba zapadajú pre ohromujúcu presnosť 10 mikrónov.

Nedávno bolo vytvorených mnoho populárnych 3D animovaných Lego príbehov, kde postavy zo súprav ožívajú a stávajú sa účastníkmi neuveriteľných dobrodružstiev. Ak chcete cool kurzor, v našej kolekcii Lego Kurzorov nájdete mnoho postáv z televíznych seriálov a animovaných filmov Lego. Lego Ninjago Kurzory, Lego Batman Kurzor, Lego Ninjago Kurzory, Lego Wyldstyle Kurzor a mnoho ďalších.',
    'lego_short_descr' => 'Postavte si svoj vysnívaný prehliadač so sadou Lego kurzorov',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Po úspešnom financovaní na platforme Kickstarter v roku 2017 vydal tím Team Cherry multiplatformovú PC hru Hollow Knight. Toto je príbeh bezejmenného rytiera a jeho objavov v hmyzom kráľovstve Hallownest. Hra bola právom uznaná ako jedna z najlepších v žánri metroidvania.

Hrateľnosť Hollow Knight je založená na prieskume herného sveta. Prekonávanie prekážok, riešenie hádaniek a hľadanie tajomstiev, ako aj boj s nepriateľmi. Hráč má jedinečnú sadu vylepšení a trikov na objavovanie sveta a boj v bitkách. Presúvaním sa zo zóny do zóny hráč poráža bossy a získava potrebné vylepšenia na ďalší postup. Výsledkom je, že hráči musia navštíviť už prejdené oblasti, aby našli tajomstvá a prešli príbehom. A je to tiež vzrušujúce, pretože zóny sa zakaždým menia, prinášajúc nové prekvapenia a zážitky. Hru je možné hrať rôznymi spôsobmi, pretože medzi zónami existuje niekoľko rôznych ciest. Prechádzaním príbehom otvárate mapu zóny, ale najprv musíte získať mapu.

Hlavnou zbraňou hrdinu je klinec, ktorý sa trochu podobá meču, zbrane sa dajú vylepšovať u kováča, ako aj naučiť sa rôzne zručnosti v používaní zbraní, čo rozširuje rozmanitosť útokov. Útočením na nepriateľov akumulujete špeciálny zdroj, ktorý sa neskôr dá použiť na vylepšenia alebo liečenie.
Bavte sa pri hraní hry Hollow Knight a nezabudnite na naše kurzory Hollow Knight s vašou obľúbenou postavou. Naša kolekcia obsahuje kurzor Pán Hríb, kurzor Quirrel, kurzor Ihla sršňa, kurzor Starý klinec, kurzor Myla a ďalšie.',
    'hollow-knight_short_descr' => 'Snažte sa nestratiť v kráľovstve hmyzu použitím kolekcie kurzorov Hollow Knight',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman je hlavná postava v sérii. Stikmin, predtým bez mena, začínal ako drobný zlodej, s túžbou rýchlo zarobiť ľahké peniaze. Po úteku z väznice West Mesa sa v jeho živote odohráva veľa zmien a stáva sa známym zločincom po ukradnutí Tuniského Diamantu. Henry má na výber - stať sa úspešným vládnym agentom, lovcom odmien, vodcom zločineckej organizácie, cyborgom alebo pokračovať v kriminálnej dráhe sám. Hra poteší fanúšikov žánru mnohými dobrodružstvami a záhadami a v našej novej kolekcii kurzorov Henry Stickmin nájdete jeho vtipné postavy, vrátane kurzora Henry Stickmin, kurzora Charles Calvin, kurzora Reginald Copperbottom, kurzora Right Hand, kurzora Ellie Rose a ďalších!',
    'henry-stickmin_short_descr' => 'Naplánujte si útek od nudy s kolekciou kurzorov Henry Stickmin',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'Veľmi populárna online hra Adopt Me bola spustená v roku 2017 a stala sa najpopulárnejšou na hernej platforme Roblox. Podstatou hry je veľmi jednoduchá - získať vajíčka so zvieratkami a starať sa o ne.

Virtuálne zvieratká sú rozdelené do 5 tried, niektoré z nich sú veľmi vzácne a drahé, zatiaľ čo iné sa dajú získať veľmi ľahko. Sú to bežné skupiny ako Modrý pes, Bežný, Vzácny kurzor, napríklad kurzor myši Adopt Me Monkey, ako aj ultra vzácne, ako je kurzor Koala a Legendárny, kurzor Dragon a Accept me unicorn. Ak má hráč štyri dospelé zvieratká rovnakého typu, môžu sa spojiť do neónového zvieratka, ako je herný kurzor Neon Horse alebo Adopt Me Hviezdica Neon. Kombináciou štyroch bežných zvieratiek môžete vytvoriť neónové zvieratko, ktoré skutočne svieti, a zónnych zvieratiek môžete vytvoriť mega-neónové zvieratko.

Nakupovanie v hre Adopt Me! sa uskutočňuje s virtuálnou menou Roblox - takzvaný Robux, a hra má tiež vlastnú menu - Bucks. Starať sa o svoje zvieratko, okrem zábavy, môžete zarobiť peniaze, stačí ho nakŕmiť, uložiť do postele alebo prečítať rozprávku, vo všeobecnosti, veľa zaujímavých vecí.

Teraz fanúšikovia hry Roblox "Adopt Me!" si môžu ozdobiť svoj herný kurzor obľúbeným zvieratkom!',
    'adopt-me_short_descr' => 'Užite si zábavu so zladkými zvieratkami v našej kolekcii herných kurzorov Adopt Me!',
    'adopt-me' => 'Adopt me!',
    'among-us_descr' => 'Among Us je založený na slávnej role-playing hre "Mafia". Bolo plánované, že hra bude exkluzívna pre mobilné zariadenia, pretože mala len jednu mapu. Hra sa rýchlo stala populárnou. Neskôr vývojový tím pridal multiplayerový režim a v roku 2019 boli vydané dve ďalšie mapy.
Among Us je hra z pohľadu tretej osoby zhora, ktorá umožňuje hráčovi pohybovať sa vo všetkých smeroch. V jednom kole môže hrať od štyroch do desiatich hráčov. Na začiatku hry je každému tajne priradená rola zradcu alebo člena posádky. Podvodník (v ruskom preklade "Zradca") sa môže schovávať v ventilačných otvoroch, sabotovať a zabíjať členov posádky. Jeho cieľom je zničiť všetkých členov posádky alebo zničiť vesmírnu loď sabotážou. Cieľom posádky lode je vyriešiť rôzne hádanky pripravené pre nich na začiatku hry. Ak každý z členov posádky splní všetky úlohy, zradcovia prehrajú. Tiež posádka lode môže dosiahnuť víťazstvo elimináciou zradcov počas hlasovania.
Zradcovia môžu z času na čas sabotovať a ak sa poruchy neopravia do 30 sekúnd, posádka prehrá. Pred začatím hry si môžete zvoliť farbu postavy, za ktorú hráte, modrú, červenú, žltú, sivú - akúkoľvek! A nezabudnite si nastaviť príslušný kurzor z novej kolekcie Among Us!',
    'among-us_short_descr' => 'Nenechajte sa oklamať v tejto zložitej vesmírnej hre s kurzormi z Among Us',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Tvorcom "Steven Universe" bola Rebecca Sugar. Je známa svojou predchádzajúcou prácou s názvom Adventure Time. Prvá epizóda Steven Universe bola vydaná na video platforme YouTube na jar roku 2013. Ale na jeseň ju americký kanál Cartoon Network začal vysielať pre svojich divákov. Odvtedy bolo vydaných 6 sérií. Šiesta sľubuje, že bude finálna.
Čo sa týka zápletky animovaného seriálu, točí sa okolo tímu Crystal Gems. Skladá sa z mimozemských tvorov s charakteristickými menami: Pearls, Amethyst a Pomegranate. Ale je tu ešte jeden účastník, v úlohe ktorého pôsobí obyčajný chlapec Stephen. Spoločne hľadajú príšery a snažia sa ich neutralizovať, aby neprevzali Zem pre osobný prospech. Stoja proti nim Jasper a Peridot - poslovia z ich domovskej planéty, ktorí chcú poraziť Gems a zapnúť Cluster.
Ak ste fanúšikom Steven Universe a chcete vidieť postavy z animovaného seriálu, kde len môžete, nainštalujte si rozšírenie Cursor Style! Prečo to urobiť? Môžete pridať kolekciu venovanú "Steven Universe" a zmeniť štandardný ukazovateľ myši na jednu z vašich obľúbených postáv.',
    'steven_universe_short_descr' => 'Odhaľte tajomstvo drahokamov s kurzormi Steven Universe.',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Animovaný sitcom s názvom "Family Guy" počas celej svojej existencie 4-krát vyhral cenu Emmy Award a 3-krát cenu "Annie". Animovaný seriál si robí posmech z bolestivých tém americkej spoločnosti, ako sú: feminizmus, otroctvo, obezita, politika atď. Na rozdiel od iných diel sa tu používajú vložky so žartami a iróniou. Navyše, v mnohých prípadoch nie sú integrované do deja, ale existujú samé o sebe.
Jedna epizóda animovaného seriálu sa vytvára viac ako 10 mesiacov. Prečo tak dlho? Pretože celá animácia je kreslená ručne. Z tohto dôvodu majú niektoré udalosti, ktoré dielo pokrýva, čas stratiť svoju relevantnosť. Ale aj napriek tomu zostáva sitcom veľmi zaujímavý a získava si priazeň divákov po celom svete. Koniec koncov, kto by sa nerád dobre zasmial na politikoch, celebritách alebo ľuďoch, ktorí robia divoké kúsky a tým prekvapujú alebo dokonca šokujú bežných ľudí.
Máte radi "Family Guy"? Máte jedinečnú príležitosť premeniť normálny kurzor myši na ktorúkoľvek z postáv tohto animovaného seriálu! Čo musím urobiť? Stačí nainštalovať rozšírenie prehliadača “Cursor Style”, pridať doň zbierku venovanú “Family Guy” a vychutnať si báječnú reinkarnáciu!',
    'family_guy_short_descr' => 'Kolekcia kurzorov Family Guy pre znalcov špeciálneho humoru',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Určite ste počuli výraz "Krása zachráni svet"? Veľa ľudí, najmä dievčatá, s týmto tvrdením súhlasí. Preto sa snažia obklopiť sa všetkým, čo je najkrajšie a príjemné pre oči. Môžu to byť ružové tapety v spálni, mäkké hračky, vankúše vyšívané korálikmi, drahé šperky atď. Z vonku to všetko vyzerá veľmi roztomilo a dokonca trochu detinsky. Ale každý z nás je v srdciach trochu dieťa, tak prečo mu nedovoliť ukázať našu fantáziu?
Nežnosť v nás môže vyvolať veľa vecí. Napríklad súcitné oči mačiatka, ktoré sa chce pomaznať alebo nakŕmiť. Viacfarebná dúha, ktorá sa objaví po jarnom daždi a trbliece sa všetkými farbami na slnku. Dieťa, ktoré dostalo čokoládu a rozhodlo sa podeliť sa s ňou so svojou priateľkou alebo priateľom. Existuje dosť dôvodov na dojemnosť a my sme sa rozhodli použiť ich ako kurzory.
Už vás nebaví nudná biela šípka vo vašom prehliadači? Nahraďte ju niečím roztomilým z našej zbierky! Napríklad ružovým a bielym jednorožcom, smutným paradajkom, zamračeným oblakom, pichľavým kaktusom v tvare mačky alebo čímkoľvek, čo chcete. Stačí nainštalovať rozšírenie Cursor Style a pridať doň zbierku roztomilých kurzorov. A nech žije spasiteľka sveta - krása!',
    'cute_cursors_short_descr' => 'Svet bude láskavejší s kolekciou roztomilých kurzorov.',
    'cute_cursors' => 'Roztomilé Kurzorz',
    'web_media_descr' => 'V moderných realitách používa internet takmer každý. Počnúc batoľatami a končiac dôchodcami. Niekto prehliada web pomocou prehliadača, iný sleduje videá na YouTube a niekto potrebuje sieť na komunikáciu s blízkymi. Každý z týchto používateľov si nevie predstaviť deň bez World Wide Web.
Starší ľudia často sedia na sociálnej sieti ako Facebook alebo VK. Tiež často komunikujú so svojimi deťmi a vnúčatami na Skype. To je obzvlášť výhodné, ak deti a rodičia žijú v rôznych mestách alebo dokonca krajinách.
Mladí ľudia uprednostňujú komunikáciu cez Viber alebo Telegram, nahrávajú fotografie na Instagram, smejú sa z FB mémov. YouTube videá reakcií ľudí získavajú milióny pozretí, rovnako ako rôzne žarty alebo sociálne experimenty. V Tik-Tok tancujú státisíce ľudí, ukazujú triky a vyjadrujú sa.
Zaujíma vás alebo často používate nejaký druh zdroja zo sféry webových médií? Chcete sa zbaviť nudnej šípky myši vo vašom prehliadači? Potom si nainštalujte rozšírenie a zmeňte predvolený kurzor na náš kreatívny! Môže to byť kurzor YouTube, kurzor Viber, kurzor Google Chrome alebo iné zdroje.',
    'web_media_short_descr' => 'Žite v modernom rytme so zbierkou kurzorov webových médií',
    'web_media' => 'Webové médiá',
    'bobs_burgers_descr' => 'Animovaný seriál Bob\'s Burgers je dej animovaného diela a charizma postáv. A súdiac podľa nominácie na cenu Emmy a uznania diela ako jednej z najlepších karikatúr na celom svete, Bob\'s Snack naozaj spôsobil rozruch.
Herecký dej animovaného seriálu sa točí okolo rodiny Boba Belchera. Tento človek je majiteľom bufetu na prvom poschodí a na druhom poschodí býva so svojimi blízkymi. Bob má veselú manželku Lindu a 3 deti: Gene, Louise a Tina. Chlapec sníva o hudobnej kariére, najstaršia dcéra Tina je veľmi milá, ale nemotorná, a najmladšia - Louise je ešte mrška a často stavia svoju rodinu do nepríjemnej situácie. Hlavným konkurentom spoločnosti Bob’s Burgers je pizzeria Jimmyho Pesta. Ako ste asi uhádli, majiteľ tejto pizzerie sa volá Jim a on a Bob sa navzájom nenávidia. To všetko bolo zbité tak, aby to vyzeralo komicky, nie vážne. Preto mnoho ich potýčok spôsobuje len úsmev.
Ak máte radi animovaný seriál „Bob\'s Burgers“ a chcete vidieť jeho postavy nielen na obrazovke monitora alebo televízora, nainštalujte si rozšírenie, pridajte zbierku a zmeňte kurzor myši v prehliadači na ktorúkoľvek z postáv v tejto karikatúre!',
    'bobs_burgers_short_descr' => 'Bob robí burgery a my robíme kurzory Bob\'s Burgers.',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'História videohry "Kirby" sa začala už v 90. rokoch minulého storočia. Skladá sa z mnohých sérií, ktoré boli vyvinuté spoločnosťami Nintendo a HAL Laboratory. Hra je určená pre deti od jeden a pol roka do 8 rokov. O jej popularite možno usudzovať podľa počtu predaných kusov. Celosvetovo viac ako 34 miliónov.
Hlavnou postavou Kirbyho je rovnomenné ružové stvorenie. Žije na planéte zvanej Pop Star a pravidelne ju chráni pred rôznymi nebezpečenstvami. Kerby môže vdýchnuť niektoré predmety a svojich nepriateľov, aby sa potom naučil ich schopnosti: boj zblízka, ovládanie meča, dýchanie ohňa atď. Ružový puf však nielenže bojuje s nepriateľmi, ale aj rieši rôzne hádanky, cestuje do iných krajín a môže sa dokonca vznášať v úrovni.
Túto videohru môžete hrať na konzolách Nintendo alebo Game Boy. Vo všetkých sériách sú roztomilí hrdinovia, dobrá grafika a vtipné soundtracky. Mimochodom, za takmer 30 rokov od vydania prvej verzie sa svet mohol dočkať 20 sérií Kirbyho. Tento ukazovateľ v spojení s multimiliónovým objemom predaných kusov pomohol hre dostať sa do TOP 50 najúspešnejších a najžiadanejších videohier v hernom priemysle.
Máte radi Kirbyho tak, že by ste chceli vidieť túto postavu všade, kde to je možné? Potom použite kolekciu Kirby a premeňte bežný ukazovateľ myši na hlavnú postavu vašej obľúbenej videohry! Sme si istí, že sa vám nový vzhľad kurzora bude páčiť.',
    'kirby_short_descr' => 'Skúste vdýchnuť celú kolekciu kurzorov Kirby',
    'kirby' => 'Kirby',
    'undertale_descr' => 'V dávnych dobách Zem obývali nielen ľudia, ale aj monštrá. Kvôli nezhodám medzi nimi vypukla vojna, ktorá sa skončila v prospech ľudskej rasy. Sedem mágov vyhnalo príšery pod zem a navždy ich tam uväznilo s bariérovým zaklínadlom. Bol však iba jeden vchod na horu Ebott, čo dieťa využilo. Práve zaňho budete hrať spustením počítačovej hry Undertale.
Hru vyvinul Toby Fox - známy programátor zo Spojených štátov. Najprv si ju mohli vychutnať majitelia osobných počítačov s operačným systémom Microsoft Windows a Linux, potom prišli na rad používatelia herných konzol.
O čo v tejto hre ide? Chlapec cestuje podsvetím obývaným monštrami. Niektoré z nich sú okamžite nepriateľské, zatiaľ čo iné sa radi rozprávajú. Hráč si môže vybrať jedno z 2 správaní: vyhýbať sa násiliu alebo bojovať. V prvom prípade bude prechod hrou jednoduchší, v druhom - naopak ťažší. Dej a koniec, ktorý sa môže vetviť a meniť, tiež závisí od tejto voľby.
Ak máte radi Underground Tale a chcete vidieť jeho postavy vo svojom prehliadači, nainštalujte si rozšírenie a pridajte príslušnú zbierku kurzorov! Premeňte nudný ukazovateľ myši na jedno z monštier alebo hlavnú postavu Undertale!',
    'undertale_short_descr' => 'Je čas dostať sa z diery pomocou kurzorov z hry Undertale',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune je RPG hra vydaná pre počítače pred pár rokmi. Vytvoril ju rovnaký programátor, ktorý vyvinul Undertale. Tieto dve hry sa však od seba takmer nelíšia, hoci majú zopár spoločných postáv a lokácií.
V Deltarune je niekoľko hlavných postáv. Je to študent Chris, ktorého možno ovládať, a očarujúca príšera Susie, nekontrolovaná. Obe postavy padajú do sveta temnoty, kde sa stretnú s jedným z jeho obyvateľov - Ralsayom. Hovorí im, že v skutočnosti sú to svetelné bytosti, ktoré majú poslanie - zastaviť tok tmavej energie v pochmúrnom svete. Na to musia šetriť miestne príšery a snažiť sa nezapájať do bitiek s nimi, hoci je to niekedy dosť ťažké.
Hráč má jednoduchú voľbu: buď ušetriť temné tvory, alebo na nich zaútočiť. Keďže Susie nie je fanúšikom polovičatých opatrení, v mnohých prípadoch si vyberie bitku. Preto Chris nemá na výber, ale musí podporovať svoju priateľku a pomáhať jej v bojoch.
Máte radi hru Deltarune? Potom si štylizujte kurzor myši v prehliadači pre jednu z jej postáv! Môžete to urobiť pomocou nášho rozšírenia. Nainštalujte ho, pridajte kolekciu „Rune Delta“ a aktivujte! Teraz vaša šípka prestala byť rovnaká ako všetci ostatní a stala sa z nej Chris, Susie alebo jedno z tvorov temného sveta.',
    'deltarune_short_descr' => 'Ponorte sa do temného sveta s touto zbierkou kurzorov',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario je séria počítačových hier vydaných spoločnosťou Nintendo. Prvá a najpopulárnejšia hra sa volala Super Mario Bros. Uzrela svetlo sveta v roku 1985. Neskôr bola zapísaná do Guinnessovej knihy rekordov. Odvtedy bolo vydaných viac ako 20 hier, z ktorých každá má svoj vlastný dej. V roku 2019 sa objavila nová verzia s názvom Super Mario Maker 2. Napriek zlepšeniu grafiky zostal štýl a postavy rovnaké, čo evokuje nostalgiu za Super Mariom 80. rokov.
Hlavným hrdinom je stále inštalatér Mario. V deji poslednej variácie hry nemal princeznin zámok kameň na kameni. Mario ho musí prestavať, predtým si zarobil mince, ktoré sa mu platia za úlohy. Celkovo má táto hra viac ako 100 úrovní rôznej zložitosti s možnosťou modifikácie. Tiež v Super Mario Maker 2 sú nové herné režimy. Môžete hrať štyri z nich naraz a hneď ako jeden skončí, úroveň sa považuje za dokončenú. K dispozícii sú aj režimy ako: Mario Marathon, Duel a Ninjik races.
Milujete Super Mario a všetko, čo súvisí s touto úžasnou hrou? Potom si nastavte kurzory vyrobené v štýle tejto platformovej hry! Sme si istí, že sa vám budú páčiť kurzor Mario, kurzor Luigi, kurzor Princess Peach a ďalšie kurzory, ktoré sú prezentované v našej zbierke!',
    'super_mario_short_descr' => 'Prejdite hubovým kráľovstvom so zbierkou kurzorov Super Mario',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls bol vytvorený spoločne spoločnosťou Disney Television Animation Corporation a Alex Hirsch. Premiéra bola vydaná v roku 2012 a bola vysielaná na Disney Channel. Celá prvá sezóna animovaného seriálu sa tam točila. O dva roky neskôr bola vydaná druhá sezóna, ktorú diváci mohli sledovať na predchádzajúcom kanáli a na Disney XD. Fanúšikovia Gravity Falls sa, žiaľ, nedočkali tretej a ďalších sezón. Tvorcovia sa rozhodli obmedziť sa na dve sezóny bez akýchkoľvek pokračovaní.
Čo sa týka zápletky tohto animovaného obrázku, potom sa všetka akcia odohráva vo fiktívnom mestečku menom Gravity Falls. Prichádzajú tam dve dvojčatá, ktorých mená sú Mabel a Dipper. Zostávajú so svojím bratrancom Stanom. Má svoj vlastný turistický obchod so suvenírmi. Keď sa bratia nudia "nerobiť nič", vydávajú sa hľadať dobrodružstvo. Jeden z nich nájde v lese zvláštny denník, ktorý rozpráva o anomáliách tohto mesta. Dvojčatá sa vydávajú hľadať jeho autora a stretávajú nezvyčajné tvory a miesta. Ak vás tento animovaný seriál zaujíma a kedysi ste boli fanúšikmi jeho postáv, odporúčame vám našu kolekciu kurzorov myši v štýle Gravity Falls!',
    'gravity_falls_short_descr' => 'Vydajte sa na dobrodružstvo s kurzormi Gravity Falls',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Úplne každý počul o tak slávnom animovanom seriáli ako Simpsonovci. Dokonca aj tí ľudia, ktorí sa na to nikdy nepozreli, vedia o existencii žltých postáv. A fanúšikovia sú nadšení, keď vyjde ďalšia sezóna ich obľúbenej karikatúry. Mimochodom, na jeseň roku 2019 bolo vydaných 31 sezón. A prvá sa objavila na televíznych obrazovkách už v roku 1989. Fox ju začal vysielať a stále v tom pokračuje vďaka vysokým hodnoteniam a sympatiám divákov.
Simpsonovci sú satirický žáner, ktorý sa dotýka relevantných tém. Môže to byť životný štýl priemerného Američana, politické a náboženské otázky, "hviezdne" triky celebrít, feminizmus, manželstvá osôb rovnakého pohlavia. Všeobecne všetko, čo súvisí s lokálnymi a globálnymi udalosťami, na ktorých sa zúčastňujú Spojené štáty.
Dej animovaného seriálu sa odohráva v neexistujúcom meste Springfield. V skutočnosti je v Amerike veľa miest s týmto názvom. Možno práve preto bol vybraný, aby si publikum nespájalo to, čo sa deje na obrazovkách, so špecifickou lokalitou, ale len hádalo, kde by sa to mohlo odohrávať.
S najväčšou pravdepodobnosťou ste fanúšikom Simpsonovcov. V opačnom prípade, prečo by ste čítali tento text až do konca? A ak áno, máte možnosť zmeniť znudený kurzor myši na ukazovateľ, ktorý je vyrobený v štýle tohto animovaného seriálu.',
    'simpsons_short_descr' => 'Zábavná, malá rodina s kurzormi Simpsonovcov.',
    'simpsons' => 'Simpsonovci',
    'youtubers_descr' => 'Platforma YouTube sa objavila v roku 2005. Spočiatku sa tam videá publikovali len kvôli sebavyjadreniu alebo informovaniu o niečom. Postupom času sa to však rozrástlo na ziskový biznis, ktorý úspešným používateľom YouTube prináša tisíce, a niekedy aj milióny dolárov mesačne. Čím populárnejší vloger (osoba, ktorá vedie videoblog), tým viac môže zarobiť prostredníctvom svojho kanála.
Koľko zarába päťročné dievča-vloggerka, ktorej rodičia ju berú na najzaujímavejšie atrakcie a natáčajú, čo sa deje pred kamerou? Je to len to, ako sa dieťa baví v detských parkoch, čo vyjadruje emócie, ako sa potrápne a podobne. Suma je naozaj úžasná - dnes má detský kanál takmer 47 miliónov odberateľov a začal generovať príjem vo výške 5 miliónov rubľov mesačne.
Niekto nahráva videá, kde diskutuje o počítačových hrách, niekto robí beatbox alebo si robí žarty z okoloidúcich na ulici. Niektorí venujú svoje videá citlivým témam, ako napríklad vzťahom medzi mužmi a ženami. Čím viac sa používateľom YouTube tieto videá páčia, tým väčšia je popularita vlogera.
Do zbierky už boli pridané kurzory PewDiePie, kurzory Shane Dawson, kurzory Ray William Johnson, kurzory Zoella, kurzory MyLifeAsEva a ďalšie.',
    'youtubers_short_descr' => 'Nová generácia hviezd je vždy online v našej kolekcii YouTuberi',
    'youtubers' => 'YouTuberi',
    'pusheen_descr' => 'Takmer každý pozná mačku Pusheen. Hoci je to iba postava z detského komiksu, ktorá bola vymyslená pred 10 rokmi, má dnes milióny fanúšikov. Mačka Pusheen sa objavila ako ilustrácia, ktorú vytvorila umelkyňa Claire Belton.
O rok neskôr mačka získala vlastnú stránku na Tumblr.com a v priebehu niekoľkých týždňov získala celú armádu fanúšikov - asi 10 000 ľudí. V roku 2013 bola spoločnosť Facebook dychtivá zahrnúť obrázky z Pusheen do kolekcií s ostatnými emotikonmi. Po rokovaniach s tvorcom sa táto myšlienka uviedla do praxe a „vybuchla“ internetom! Obrázky z mačky Pusheen sa používajú v korešpondencii viac ako 10 miliónovkrát za deň!
V roku 2014 venoval tejto postave pozornosť jeden z najväčších výrobcov hračiek v Spojených štátoch. GUND (bola to práve ona, kto vynašiel plyšové medvede) uviedol na trh pár modelov Pusheen. Keďže úspech bol obrovský, o niekoľko mesiacov neskôr bola vytvorená kompletná kolekcia hračiek v podobe tejto mačky.
Kde inde môžete stretnúť mačku Pusheen? V darčekových súpravách od Isaac Morris Ltd, v marshmallow od Boomf a, samozrejme, v našej kolekcii kurzorov Pusheen!',
    'pusheen_short_descr' => 'Pridajte si trochu pohodlia do prehliadača s kolekciou kurzorov Pusheen',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'Prvá séria animovaného diela „Rick a Morty“ bola vydaná v roku 2013. Tento kreslený seriál sa dá priamo pripísať k 2 žánrom: sci-fi a komédia. Jeho tvorcami boli Dan Harmon a Justin Royland. Spočiatku sa všetky série vysielali na kanáli Cartoon Network a až potom sa duplikovali v online kinách a video hostingoch. Každých pár rokov vychádzajú nové série Ricka a Mortyho a v novembri 2019 vyšla štvrtá séria, ktorá sa ukázala byť rovnako zaujímavou ako tie predchádzajúce. Dej animovaného seriálu sa točí okolo génia a zároveň šialeného vedca menom Rick, ako aj jeho nevýrazného vnuka - Mortyho. Tieto dve postavy spájajú spoločné dobrodružstvá na tých najneobvyklejších miestach. A dostanú sa tam na lietajúcom tanieri, ktorý je schopný pohybovať sa cez medzi-priestorový tunel. Ako ste už asi uhádli, tento animovaný seriál sa trochu podobá filmu Návrat do budúcnosti, ale stále to nie je jeho animovaná verzia. Avšak, bol chválený mnohými kritikmi za humorné epizódy, kreativitu a originalitu. Chcete vidieť Ricka alebo Mortyho nielen v seriáli tohto diela, ale aj v prehliadači? Ak áno, nainštalujte si rozšírenie a pridajte našu kolekciu venovanú vášmu obľúbenému kreslenému seriálu! Tu je kurzor Ricka Sancheza, kurzor Mortyho Smitha, kurzor Portálovej pištole a samozrejme kurzor Mr. Meeseeksa.',
    'rick_and_morty_short_descr' => 'Prestaň hundrať, jednoducho použi kurzory z kolekcie Rick and Morty',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Fanúšikovia bejzbalu sa nachádzajú kdekoľvek na svete. To platí najmä pre obyvateľov krajín ako: USA, Čína, Kuba, Južná Kórea, Japonsko a Venezuela. Na rozdiel od populárnej viery, bejzbal nepochádza z Ameriky, ale z Anglicka. Prvá zmienka a popis bejzbalu sa objavil v roku 1744, v anglickom vydaní. Po 145 rokoch si Američania privlastnili tento vynález pre seba, napriek faktom.
National League bola založená v roku 1876. Je súčasťou Major League v Kanade a Spojených štátoch. Dnes je v National Baseball League 15 tímov. V záverečnej časti každej sezóny prichádza čas play-off, ktorého sa zúčastňujú 4 najlepšie tímy. Takže sa odhaľuje víťaz celej National League. Potom víťazný tím dostáva príležitosť hrať proti víťazovi z American League vo World Series.
Máte záujem o bejzbal, alebo dokonca fandíte jednému z tímov? Potom vzdajte hold svojmu obľúbenému tímu nastavením kurzorov myši v podobe jeho atribútov! Zmeňte nudný vzhľad ukazovateľa v prehliadači na známu bejzbalovú firemnú identitu! Premeňte šípku na pálku alebo prilbu hráča v niektorom z tímov National League, ktoré už zahŕňajú kurzor New York Yankees, kurzor Great Falls Dodgers, kurzor Boston Red Sox, kurzor Baltimore Orioles, kurzor Oakland Athletics.',
    'mlb_teams_short_descr' => 'Kolekcia kurzorov tímov MLB pre všetkých našich fanúšikov.',
    'mlb_teams' => 'Tímy MLB',
    'brawl_stars_descr' => 'Brawl Stars je mobilná hra v žánri MOBA od spoločnosti Supercell. Napriek vydaniu koncom roku 2018 si hra získala veľkú popularitu, a to najmä vďaka množstvu bojových režimov a farebných, fantastických hrdinov - bitkárov. Hráč má z čoho vyberať - 32 jedinečných postáv a každá z nich má vlastnú sadu schopností a zručností. Každý hrdina má tiež svoju vlastnú pasívnu schopnosť, ktorá je k dispozícii prostredníctvom truhlíkov s korisťou. Hráči môžu bojovať vo viacerých režimoch, napríklad "Odmena za zajatie" - víťazí jeden z dvoch tímov, ktorý nazbieral viac hviezd zabíjaním súperov. V režime "lúpež" je potrebné rozbiť trezory súperov a zároveň si chrániť tie vlastné. Zaujímavý režim „Grab Gem“ - tím sa stáva víťazom, tím, ktorý nazbiera najviac drahokamov, vyhráva. No a v režime "Kolízia" proti sebe na mape bojuje 10 hráčov, kde sú hranice zmenšované v dôsledku toxického oblaku. Hra oplýva farebným dizajnom, ktorý sa mnohým ľuďom páči, vrátane nás, čo nás inšpirovalo k vytvoreniu samostatnej zbierky kurzorov Brawl Stars. K dispozícii je kurzor Brawl Stars Shelley, kurzor Barley, kurzor Penny, kurzor Frank, kurzor Mortis a ďalšie.',
    'brawl_stars_short_descr' => 'Vyberte si kurzory Brawl Stars a nechajte bitku začať',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Zmeňte si kurzor myši dvoma kliknutiami! Bezplatné kolekcie pre každý vkus.',
    'all_descr' => 'Ak ste niekedy premýšľali nad tým, ako zmeniť nudný kurzor myši, potom sú naše zbierky kurzorov pre vás! Tu nájdete superhrdinov z komiksov, krásne kurzory pre hráčov s postavami z populárnych hier, zábavné sady kurzorov pre praktické žarty, farebné kurzory a mnoho ďalších zaujímavých možností.',
    'text_title' => 'Super zbierky kurzorov pre každý deň',
    'text_allcat_title' => 'Unikátne a kreatívne kurzory myši, ktoré zodpovedajú každej vašej nálade',
    'text_1' => 'Nechcete byť ako všetci ostatní? Alebo jednoducho milujete všetko nezvyčajné? Chcete byť súčasťou svojho obľúbeného herného hrdinu alebo kreslenej postavičky? Potom ste na správnej adrese. Tu nájdete rozsiahle, nezvyčajné sady kurzorov, ktoré môžu nahradiť známu a už dosť nudnú bielu šípku. Kurzor myši nás sprevádza celý deň v práci a štúdiu, takže by mal navodiť skvelú náladu a nastaviť na pozitívne.',
    'text_2' => 'Tu nájdete kurzory pre hráčov a milovníkov filmov, krásne kurzory podľa vašich obľúbených kreslených filmov a športových motívov pre najaktívnejších ľudí. Máte radi komiksy alebo si neviete predstaviť jediný deň bez vtipných mémov? Milujete zvieratá alebo snívate o návšteve všetkých krajín sveta? Všetko je jednoduché - aj pre vás máme vhodný obrázok kurzora. Obrázky si môžete vybrať aj v závislosti od toho, s čím pracujete. Napríklad čierny kurzor bude oveľa pohodlnejší ako biely pri práci s dokumentmi alebo kresbami a kurzor ruky bude pohodlnejší, ak musíte pracovať s malými grafickými prvkami. Vyberte si svoj obľúbený obrázok, upravte jeho veľkosť priamo v rozšírení - a používajte ho s potešením, každý deň začínajúc pozitívnou notou!',
    'install_to_preview' => 'Pre zobrazenie ukážky nainštalujte rozšírenie',
    'install' => 'Inštalovať',
    'add_button' => 'Pridať',
    'preview_button' => 'Náhľad',
    'added_button' => 'Pridané',
    'add_cursor' => 'Pridať kurzor',
    'to_your_collection' => 'do vašej zbierky',
    'prev_text_1' => 'Ukážka na celú obrazovku',
    'prev_text_2' => 'kurzora',
    'cursor' => 'kurzor',
    'pointer' => 'ukazovateľ',
    'a_title_1' => 'Cursor Style - Super kurzory pre váš prehliadač',
    'a_title_2' => 'Super kolekcie tematických kurzorov',
    'mouse_cursors' => 'kurzory myši',
    'cursor_collection' => 'Kolekcia kurzorov',
    'sborka_cursorov' => 'kolekcia kurzorov',
    'collection_list_from_colllection' => 'Zoznam kurzorov - ',
    'christmas' => 'Vianoce',
    'nhl_teams' => 'Národná hokejová liga',
    'neon' => 'Neón',
    'adventure_time' => 'Dobrodružný čas',
    'nba_teams' => 'Národná basketbalová asociácia',
    'spongebob' => 'Spongebob',
    'phineas_and_ferb' => 'Phineas a Ferb',
    'fortnite_chapter_2' => 'Fortnite Kapitola 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Slávni ľudia',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Komiksy',
    'igry' => 'Hry',
    'multfilmy' => 'Karikatúry',
    'kino_i_serialy' => 'Filmy',
    'anime' => 'Anime',
    'futbol' => 'Futbal',
    'avtomobili' => 'Autá',
    'memy' => 'Mémy',
    'emodji' => 'Emoji',
    'pitomcy' => 'Domáce zvieratá',
    'stil_i_krasota' => 'Móda a štýl',
    'prazdniki' => 'Sviatky',
    'flagi' => 'Vlajky',
    'vokrug_sveta' => 'Okolo sveta',
    'eda_i_napitki' => 'Jedlo a nápoje',
    'cvetnye' => 'Farebné',
    'prank' => 'Žarty',
    'startovyj_nabor' => 'Štartovacia sada',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Santa bude milovať vaše vianočné kurzory',
    'nhl_teams_short_descr' => 'Kolekcia kurzorov NHL pre skutočných fanúšikov',
    'neon_short_descr' => 'Pridajte jas s neónovou kolekciou',
    'adventure_time_short_descr' => 'Učenie matematiky s kolekciou kurzorov Adventure Time',
    'nba_teams_short_descr' => 'Kurzory NBA ako symbol veľkých basketbalových víťazstiev',
    'spongebob_short_descr' => 'Zistite, kto žije na morskom dne, s kurzormi zo zbierky SpongeBob',
    'phineas_and_ferb_short_descr' => 'S touto kolekciou kurzorov Phineas a Ferb sa určite nudiť nebudete.',
    'fortnite_chapter_2_short_descr' => 'Nová kapitola kultovej hry Fortnite.',
    'pokemon_short_descr' => 'Chyť ich všetky, ak dokážeš.',
    'famous_people_short_descr' => 'Inšpirujte sa kurzorom svojho idolu',
    'the_elder_scrools_short_descr' => 'Ponorte sa do sveta rytierov a drakov',
    'halloween_short_descr' => 'Bojte sa premeškať novú Halloweensku kolekciu',
    'nfl_teams_short_descr' => 'Pre skutočných futbalových fanúšikov',
    'five_nights_at_freddy_short_descr' => 'Snažte sa nezľaknúť týchto animatronikov.',
    'komiksy_short_descr' => 'Kurzory z komiksov: vyberte si svoju náladu na dnes.',
    'igry_short_descr' => 'Virtuálna realita: za koho dnes hráte?',
    'multfilmy_short_descr' => 'Obľúbené kreslené postavičky v novom dizajne',
    'kino_i_serialy_short_descr' => 'Pán Kurzorov: Spoločenstvo pracovnej plochy',
    'anime_short_descr' => 'Všetci milujú anime: ktorá je tvoja obľúbená postava?',
    'futbol_short_descr' => 'Ste skutočný športový fanúšik? Potom musíte byť tu',
    'avtomobili_short_descr' => 'Auto vašich snov: rozsiahla flotila pre profesionálov',
    'memy_short_descr' => 'Obľúbené motívy: Kolekcia kurzorov Mémov',
    'emodji_short_descr' => 'Ukážte svoj skutočný náladu ostatným – nastavte si Cursoji!',
    'pitomcy_short_descr' => 'Svetlé kurzory pre všetkých milovníkov našich menších bratov',
    'stil_i_krasota_short_descr' => 'Originálne kurzory pre všetky príležitosti',
    'prazdniki_short_descr' => 'Čo je v kalendári? Nová kolekcia kurzorov pre sviatky!',
    'flagi_short_descr' => 'Hľadáte dobrodružstvo: kam ideme dnes?',
    'vokrug_sveta_short_descr' => 'Do kola sveta za okamih: kam sa dnes vyberieme?',
    'eda_i_napitki_short_descr' => 'Slintajúce kurzory pre kreativitu',
    'cvetnye_short_descr' => 'Vyfarbite svoj život jasnými farbami a odvážnymi ťahmi',
    'prank_short_descr' => 'Sada kurzorov pre najzábavnejšie žarty',
    'startovyj_nabor_short_descr' => 'Nový pohľad na známe veci: aktualizovaná séria kurzorov',
    'fortnite_short_descr' => 'Sledujte streamerov!',
    'dota_2_short_descr' => 'Vylepšite svoj virtuálny svet ako skutočný!',
    'minecraft_short_descr' => 'Postavy vašej obľúbenej hry sú vždy nablízku',
    'christmas_descr' => 'Každý z nás nepochybne čaká na najobľúbenejší sviatok - Vianoce. Všetci kresťania sveta ich tradične oslavujú každý rok, 25. decembra. Čas, kedy sa rodiny zhromažďujú pri jednom stole, zdieľajú svoju radosť a lásku a vymieňajú si darčeky. Dlho pred Vianocami ľudia zdobia ulice jasnými girlandami a svoje domovy tradičnými atribútmi. Je ťažké nájsť človeka, ktorý by nemal rád Vianoce - zábavný a tajomný sviatok, pretože ho sprevádza mnoho tradícií a rituálov, ktoré nás vracajú ku koreňom celej našej rodiny. V predvečer Vianoc je doslova všetko nasýtené jeho duchom, od maľovaných perníkov až po dojímavé spevy. Elegantný vianočný stromček a darčeky pod ním, radosť známa každému z nás od detstva. Chceme sa pripojiť k tomuto magickému sviatku a kto vie, možno Santa Claus pripraví pre vás špeciálny darček, ak si ozdobíte kurzor našou vianočnou kolekciou. Je tu všetko, čo potrebujete, kurzor Santa Clausa, kurzor vianočného stromčeka, kurzor perníčka, kurzor snehuliaka a dokonca aj kurzor darčekovej tašky. Veselé Vianoce!',
    'nhl_teams_descr' => 'Národná hokejová liga vznikla v roku 1917 – je to profesionálna športová organizácia, ktorá spája hokejové kluby z USA a Kanady. A toto je jedna z prvých profesionálnych hokejových líg na svete. NHL je jednou z popredných severoamerických športových líg, spolu s NFL, NBA, Major League Baseball a MLS. Každý rok 31 tímov z 30 miest v USA a Kanade bojuje o hlavnú trofej - Stanley Cup, a tím, ktorý získa najviac bodov v základnej časti, získava Presidential Cup. Je čas, aby sme si uctili túto skvelú hru vytvorením kolekcie kurzorov NHL. Ak máte radi hokej, fandíte svojmu obľúbenému klubu alebo sa sami venujete tomuto športu, len zmeňte kurzor a nerozlučujte sa so svojím obľúbeným tímom, vrátane kurzora Boston Bruins, kurzora St. Louis Blues, kurzora Columbus Blue Jackets, kurzora Tampa Bay Lightning, kurzora Dallas Stars a ďalších klubov hodných úprimnej úcty.',
    'neon_descr' => 'Vytvorili sme jedinečnú kolekciu neónových kurzorov, aby sme pridali rozmanitosť každodennému surfovaniu po internete a vniesli trochu jasu do fascinujúcich neónových svetiel. Nech ich bohaté farby vytvoria pohlcujúcu atmosféru mesta v noci, nech dajú inšpiráciu k vytvoreniu niečoho nového. V modernom svete svetlá metropoly vždy oznamujú príchod noci, sledujú nás na každej ulici a táto žiara je plná energie. Nech ju nasleduje aj žiariaci kurzor zmrzliny, kurzor lahodného hot dogu, kurzor šťavnatého burgeru, kurzor trblietavého diamantu a ďalšie kurzory z novej neónovej kolekcie.',
    'adventure_time_descr' => '"Dobrodružstvo s Fínom a Jekom" je karikatúra fantastického žánru, v ktorej sa akcia odohráva vo svete, ktorý prežil apokalypsu. Toto územie sa nazýva Krajina Ooo, ktorá donedávna bola nukleárnou vojnou. Ale to všetko je už minulosťou, avšak všetci preživší ľudia podliehali mutáciám a svet sa naplnil mágiou. Hlavné postavy animovaného seriálu sú Fín, chlapec vo veku 14 rokov a jeho priateľ pes menom Jek. Chlapec a pes majú veľmi radi dobrodružstvo, neustále pomáhajú všetkým, ktorí majú problémy. Kamaráti žijú na strome a trávia spolu všetok svoj čas. Ak sa chcete ponoriť do dobrodružného sveta s ďalšími obdivovateľmi, tak zakričte "Matematika". Tu je kurzor Fína a Jeka, ako aj kurzor Princeznej Žuvačky. Samozrejme, nezabudli sme ani na kurzor Bima, kurzor Ľadového kráľa a iných.',
    'nba_teams_descr' => 'Ak je basketbal vašou obľúbenou hrou, tak ako je to aj pre nás, potom je pre vás zbierka kurzorov venovaných tímom NBA to, čo potrebujete. NBA je jednou z najlepších športových asociácií na severoamerickom kontinente. Keď sme túto zbierku vytvárali, trápil nás výber - ktorý tím zvoliť, pretože v NBA ich je tridsať. Ale sú tímy, ktoré sú legendami. Toto je Chicago Bulls, ktorý v polovici 90. rokov stanovil rekord vo víťazstvách. Toto je Golden State Warriors, ktorý pred pár rokmi spojil najlepších hráčov ligy. Alebo, napríklad, Lakers, Celtics sú tiež šialene skvelé tímy. Ak sa rovnako ako my tešíte na zápasy svojich obľúbených basketbalových tímov a chcete prejaviť podporu tímu alebo hráčom, stiahnite si našu zbierku kurzorov NBA.',
    'spongebob_descr' => 'Animovaný seriál "SpongeBob SquarePants" je známy mnohým ľuďom. Bol to ohromujúci úspech po tom, čo sa Nickelodeon v roku 1999 rozhodol vytvoriť animovaný seriál na základe vzdelávacieho komiksu Tide Zone, a zmenil sa na veľmi lukratívnu franšízu. Tvorcom seriálu je bývalý zamestnanec oceánologického laboratória, a preto sú takmer všetky postavy v animovanom seriáli vtipní obyvatelia morského dna, so svojimi vlastnosťami a charizmou. Dej sa točí okolo tajného receptu na Krabsburger, ktorý môže uvariť len hlavná postava - Sponge Bob. A ostatní obyvatelia mora sa ho snažia získať, vrátane hlavného anti-hrdinu Sheldona Planktona, ktorému sa to vždy nepodarí. V kolekcii kurzorov SpongeBob sme zhromaždili kurzory všetkých významných postáv a udalostí zo série. Napríklad kurzor pána Krabsa s dolárom, kurzor Patrika Hviezdicu, Squidwarda s jeho klarinetom, kurzor medúzy, kurzor Sponge Boba a mnoho ďalších postáv.',
    'phineas_and_ferb_descr' => 'Vo fiktívnom americkom meste Denville neexistujúceho Trishtatya žijú dvaja zaujímaví chlapci. Každý deň ich dovolenky sa mení na neuveriteľné dobrodružstvá, pretože dokážu postaviť horskú dráhu veľkú ako celé mesto alebo skutočný portál na inú planétu. O svoje úžasné zábavy sa delia s priateľmi. Zároveň, zatiaľ čo sa chlapci bavia, zlý vedec Heinz Fufelschmertz stavia ďalší zlý stroj, ktorý vytvára chaos, s názvom končiacim sa na "-inator", pomocou ktorého sa chce pomstiť za krivdy z detstva alebo sa zmocniť moci v Trishtate, ale prekazí mu ho Perry - Utkonos, tajný "Agent Pi", pracujúci v prestrojení za domáceho maznáčika chlapcov. Popularita tohto animovaného seriálu, a to ako medzi deťmi, tak aj medzi dospelými, nás inšpirovala k vytvoreniu zbierky kurzorov Phineas a Ferb, aby ste si mohli zmeniť kurzor myši na postavy zo seriálu. Medzi nimi sú kurzor Phineas Flynn, kurzor Dr. Heinz Fufelschmertz, kurzor Ferb Fletcher, kurzor Candace Gertrude Flynn a kurzor Perry vtákopysk.',
    'fortnite_chapter_2_descr' => 'Druhá kapitola Fortnite prišla po veľkej udalosti - The End, ktorá vtiahla všetko, čo hráči v hre milovali, do čiernej diery. Fortnite Kapitola 2 má teraz novú mapu, ktorá je na prvý pohľad ešte divokejšia ako pôvodná mapa, ako aj mnoho zmien v hernej mechanike a samozrejme veľa nového herného obsahu! Vozidlá, emócie, plavecká mechanika a oveľa viac - to všetko v čerstvom, zaujímavom obraze, všetko tak, ako to v tejto kultovej hre milujete a oceňujete. Ponorte sa do nového sveta - vyberte si miesto pristátia a preskúmajte úplne nový ostrov s 13 lokáciami. Plávanie, rybolov, motorové člny - toto je nová vodná hrateľnosť. Viac zábavy a menej námahy - vylepšite úplne novú kapitolu 2 a nezabudnite zmeniť kurzor na nové skiny a zbrane. Už na vás čakajú aktualizované skiny Turk kurzor, Riptide kurzor, Rippley kurzor, Remedy kurzor, Toxin kurzor, 8-Ball kurzor, Fusion kurzor a ďalšie!',
    'pokemon_descr' => 'Slovo "pokemon" znamená tvora s nadprirodzenými schopnosťami. Majú inteligenciu a niektorí z nich sú dokonca schopní hovoriť. V súčasnosti existuje už 802 druhov Pokémonov. Vo vymyslenom vesmíre Pokémonov sa ľudia nazývajú tréneri Pokémonov, ktorých trénujú na súboje s Pokémonmi iných trénerov. A čím skúšenejší a silnejší je tréner, tým väčšiu úctu si užíva. Je potrebné poznamenať, že súboje Pokémonov sa nikdy nekončia smrťou týchto jedinečných tvorov. Všetci Pokémoni majú rôzne schopnosti a líšia sa typom prvku, a jeho odolnosť voči rôznym útokom na tom silne závisí, pričom niektoré tvory majú schopnosť dvoch prvkov naraz. Po výhre v boji získa Pokémon cenné skúsenosti, ktoré sú potrebné na zvýšenie úrovne a v dôsledku toho aj jeho charakteristík. Dnes je vesmír Pokémonov rozsiahla mediálna franšíza a rozhodli sme sa pre vás pripraviť zbierku kurzorov s niektorými populárnymi Pokémonmi. Medzi nimi je najznámejší kurzor Pikachu, ako aj kurzor Rattata, kurzor Squirt, kurzor Bulbasaur a kurzor Charmander. Tento zoznam bude aktualizovaný, pretože ich je toľko a každý z nich je jedinečný svojím vlastným spôsobom.',
    'famous_people_descr' => 'Medzi mnohými slávnymi ľuďmi si každý z nás nájde vzor alebo jednoducho obdivuje génia, talent a vytrvalosť týchto celebrít. Pripravili sme kolekciu kurzorov celebrít, aby vás inšpirovala a pripomenula vám skvelé úspechy, ktoré môže každý z vás zvýšiť. Nie všetci slávni jedinci mali šťastný osud, ale učia nás hlavnú vec, že sa nikdy nemusíte odchyľovať od svojho milovaného cieľa, napriek ťažkostiam a problémom. Koniec koncov, toto je hlavná zásada dosahovania úspechu - chodiť za svojím snom každý deň a nakoniec sa stať najlepšími vo svojom odbore. Možno si dnes len chcete zmeniť kurzor myši a zajtra sa celý váš život zmení k lepšiemu! Kolekcia bude neustále aktualizovaná o nových, dôstojných predstaviteľov ľudstva. Medzi nimi, samozrejme, vedci, politici, športovci, predstavitelia umenia a mnohí ďalší. Kurzory Georgea Washingtona, Michaela Jordana, Stephena Kinga, Elvisa Presleyho a Marilyn Monroe sú len začiatkom.',
    'the_elder_scrools_descr' => 'The Elder Scrolls je séria počítačových RPG hier, ktoré spája spoločný, precízne navrhnutý vesmír, ktorý hráčovi poskytuje obrovskú slobodu voľby, čo mu umožňuje navštíviť rôzne oblasti a mestá fantasy sveta a preskúmať nové miesta a misie na vlastnú päsť. Práce na sérii sa začali už v roku 1992 a v priebehu rokov hra okolo seba zjednotila obrovskú komunitu hráčov. Preto sme na základe požiadaviek vydali kolekciu kurzorov The Elder Scrolls, aby ste sa mohli ponoriť do jedinečnej atmosféry hry. Večný boj rytierov a drakov, na ktorej strane stojíte? Zmeňte kurzor na draka a pripojte sa k armáde šľahajúcich príšer alebo statočne bojujte na strane ľudí výberom kurzora meča a obrazu svojej obľúbenej postavy - rozhodnutie je na vás! Hlavná vec je, že s našou novou kolekciou ste pripravení na akýkoľvek boj.',
    'halloween_descr' => 'Čakanie na mystickú noc na Silvestra. História Halloweenu siaha viac ako dva tisíc rokov. Možno je to najpodivnejší sviatok, ktorý kombinuje zábavu a strach, pôvodom z keltskej kultúry. Ľudia vtedy pálili ohne a obliekali si strašidelné kostýmy, aby odohnali duchov. Slovo "Halloween" sa prvýkrát spomínalo v 16. storočí ako škótska skratka anglickej frázy All-Hallows-Even. Pápež Gregor III. vyhlásil 1. november za Sviatok všetkých svätých a predvečer toho bol známy ako Eve of All Saints a neskôr Halloween. V tento deň si ľudia obliekajú kostýmy vlkolakov, duchov a iných príšer a chodia do susedných domov, ponúkajúc kúpu sladkostí. Tematické večierky, ohňostroje, krásne lampáše, tekvice a kaskadérske kúsky vytvárajú jedinečnú atmosféru. Aj my chceme tento strašný sviatok osláviť s pomocou kurzorov a postáv z Halloweenu. V našej kolekcii nájdete: kurzor zombie, kurzor duch, kurzor čierna mačka, kurzor tekvica a oveľa viac. Zmeniť náladu je teraz rovnako jednoduché ako zmeniť kurzor s našou novou halloweenskou kolekciou.',
    'nfl_teams_descr' => 'Čo by mohlo byť lepšie pre skutočného fanúšika amerického futbalu než kurzor myši v podobe symbolizmu tímu, pre ktorý je fanúšikom? V modernej Národnej futbalovej lige hrá tridsaťdva tímov, rozdelených medzi National a American Football Conferences (National Football Conference, NFC a American Football Conference, AFC). Každá z konferencií je rozdelená na štyri divízie: East, North, South a West. Sezóna NFL sa skladá zo zápasov pred sezónou, pravidelnej sezóny a série playoff zápasov. Posledný zápas sezóny NFL sa nazýva Super Bowl a je v podstate najpopulárnejším športovým podujatím v Spojených štátoch. Toto je obľúbená hra pre milióny fanúšikov, a preto sme vytvorili kolekciu NFL kurzorov, aby ste sa nerozišli so symbolmi svojho obľúbeného tímu. Či už ide o New England Patriots, New York Giants, Buffalo Bills alebo iný tím, buďte vždy na rovnakej vlnovej dĺžke so svojimi idolmi pomocou našich kurzorov vo forme loga a helmy tímu. Kolekcia bude neustále aktualizovaná, aby si každý mohol zmeniť kurzor na obrázok svojho obľúbeného tímu.',
    'five_nights_at_freddy_descr' => 'Skutočne unikátna hra Five Nights at Freddy\'s si rýchlo získala širokú popularitu, čo nie je prekvapujúce, pretože jej jednoduchý a zároveň fascinujúci dej dokáže udržať hráčov na obrazovkách celé hodiny. Cursory Five Nights at Freddy\'s sme navrhli na žiadosť fanúšikov hry a boli sme veľmi radi, že sme mohli v stelesniť také zaujímavé a vtipné postavy. Ale na rozdiel od hry vám s našimi kurzormi nič nehrozí, takže si bez obáv vyberte svojich obľúbených animatronikov, či už je to Medveď Freddy alebo Zajačik Bonnie, alebo iní. Hlavné je, že teraz hra ožíva vo vašom prehliadači a prináša čerstvé emócie. Garantujeme, že v našich kurzoroch nie sú žiadni duchovia, ale dokonale sprostredkúvajú ducha hry, ktorá inšpiruje strach vďaka zložitosti dizajnu a prvkov deja. Ale čo ak urobíte veľkosť kurzora veľmi veľkú? Dokážete zostať pokojní a nebáť sa?',
    'komiksy_descr' => 'Zdá sa, že kurzor myši je maličkosť, ale často sú to práve takéto detaily, ktoré vám môžu zlepšiť náladu, prebudiť vás v sivé ráno alebo len dať jasné emócie. Kolekcia komiksových kurzorov navrhnutá špeciálne pre všetkých milovníkov superhrdinov. Tu nájdete úplne celý Marvel Universe a DC Comics - od Iron Mana po Thanosa, Spider-Mana a Hulka. Štýl kurzora môže byť buď vo forme superhrdinu, alebo vo forme jeho charakteru. Kurzor nie je len funkčný prvok; je dôležitý v profesionálnom zmysle. Ak napríklad nahrávate video z obrazovky, bude lepšie vidieť jasný, originálny obrázok, a vyzerá to oveľa zaujímavejšie. A samozrejme - kto by nechcel použiť rukavicu nekonečna v reálnom živote? Zmena kurzora myši je jednoduchá - stačí stiahnuť rozšírenie do prehliadača a pridať kurzor, ktorý sa vám páči, do nastavení prostredníctvom neho. Môžete si vybrať kurzor podľa svojej nálady aspoň každý deň. Dosť šedých dní - staňte sa superhrdinom práve teraz!',
    'igry_descr' => 'Počítačové hry sa už dávno stali neoddeliteľnou súčasťou našich životov. S ich pomocou sa môžete ponoriť do nového sveta, zúčastniť sa dobrodružstiev a stať sa úplne inou osobou. Každý má svoju obľúbenú hračku, ktorej postavy sa už stali takmer rodinou. Súbor kurzorov založený na dobre známych počítačových hrách je príležitosť zriediť nudný každodenný život a pridať do pracovného postupu trochu kreativity, jasu a zábavy. Súbor obsahuje obrázky samotných hrdinov hier, ale aj pomocných postáv, zbraní a ikon hier. Vyberte si, čo sa hodí k vašej nálade - herné kurzory oslovia nielen hráčov, ale aj všetkých, ktorí sú jednoducho unavení zo sivého každodenného života. Stačí si stiahnuť sadu, zmeniť kurzor myši - a ísť, plniť questové úlohy, ničiť nepriateľov a dosahovať svoje ciele.',
    'multfilmy_descr' => 'Vnútri každého dospelého je stále dieťa, ktoré miluje kreslené filmy a stále sníva o tom, že sa stane jedným z hrdinov. Pomôžeme vám splniť si sny - použite novú kolekciu kurzorov založených na najznámejších a najobľúbenejších kreslených filmoch. Tom a Jerry, Buzz Lightyear a Shrek, Gravity Falls a dokonca aj Pokemon - môžete sa stať tým, kým chcete, každý deň. Vyberte si kurzor myši podľa svojej nálady. Kto ste dnes? Bezstarostný a veselý poskok, ktorý ľahko rieši akékoľvek problémy, alebo silný a odvážny Raphael, ktorého cieľom je nielen dosahovať činy, ale aj jesť pizzu? Možno ste všemocný džin, ktorý má pod svojou kontrolou celú kanceláriu? V kolekcii sú hrdinovia pre každého - od princezien po drakov - stačí sa len rozhodnúť, kto odráža dnešnú náladu. Cursor Style nie je len jasný obrázok. Je to odraz individuality, sebavyjadrenia a jednoducho - zábavy, radosti a pozitivity na celý deň. Je to nudné pracovať alebo príliš lenivé študovať? Stalo sa to smutným a nie je to šťastné? Zmeňte kurzor a svet sa rozžiari novými farbami.',
    'kino_i_serialy_descr' => 'Filmy - sú mágia, mysticizmus a len skvelý spôsob, ako relaxovať, zabávať sa a získať živé emócie. Zároveň si po sledovaní stále pamätáme obľúbených hrdinov, ktorých naozaj chcem stretnúť v skutočnosti. Teraz je to možné - stačí si stiahnuť novú kolekciu kurzorov založených na slávnych filmoch a televíznych reláciách. Jasné, skvelé kurzory budú skvelým doplnkom na pracovnej ploche, premenia nudný šedý všedný život na sviatok a banálne úlohy - na vzrušujúce dobrodružstvo. Zmeňte kurzor hrdinu každý deň - pre náladu, úlohy alebo náhodne. Kým budete dnes? Čestný a spravodlivý John Snow alebo odvážny, neúprosný John Wick? Možno máte pred sebou ťažkú ​​misie a iba Frodo ju môže dokončiť? Možno ste dnes len mimozemšťan, ktorý nechce nadviazať kontakt s ostatnými? Vyberte si vhodný kurzor - zdvihnite si náladu a zároveň ukážte ostatným, čo si myslíte a ako plánujete stráviť deň. Vyskúšajte to - je to nielen zábava, ale aj návykové - rozhodne sa nebudete chcieť vrátiť k obvyklej šípke.',
    'anime_descr' => 'Anime je jedinečný štýl animácie, ktorý si napriek svojej výraznej etnickej príslušnosti obľúbili milióny ľudí na celom svete. Je nepravdepodobné, že by existoval aspoň jeden človek, ktorý by nepozeral kreslené filmy v tomto štýle. Vytvorili sme najúžasnejšie anime štýlové kurzory, ktoré si zamilujú všetci fanúšikovia tohto štýlu. Štandardné kurzory sú nudné a gýčovité. Ukážte svoju osobnosť – použite kolekciu anime kurzorov so svojimi obľúbenými postavami. Vyberte si kurzor tmavého meča, ak snívate o dobrodružstve a statočných bitkách. Roztomilý tučniak Totoro vás rozveselí aj v najsmutnejší deň a Naruto vás bude motivovať na dobrodružstvá a ukáže všetkým naokolo, že ste mega cool. Jasné kurzory rozjasnia pracovný deň alebo urobia proces učenia zaujímavejším a príjemnejším. Neobmedzujte sa – používajte svoje obľúbené motívy aj v takých malých prvkoch, ako je kurzor myši. Zmeňte kurzory každý deň, prispôsobte ich svojej nálade a ukážte svoju osobnosť – s anime štýlovými kurzormi je to také jednoduché.',
    'futbol_descr' => 'Futbal je špeciálny šport, ktorý zahŕňa prvky zápasenia, atletiky a presnosti. Vo všeobecnosti je veľkolepý, nemilosrdný a zhromažďuje milióny fanúšikov po celom svete. Máte radi futbal alebo len milujete šport? Potom si stiahnite sadu kurzorov v štýle svetoznámej hry a dokážte titul lojálneho fanúšika. Kolekcia obsahuje 24 možností pre dizajn kurzorov – v podobe najpopulárnejších tímov, ktoré si zaslúžia svoje tituly ako zúfalá a vytrvalá hra. Kursozy sú vyrobené v dvoch verziách - vo forme štandardného trojuholníka, vyzdobeného vo farbách tímu, alebo vo forme zodpovedajúcej hernej prilby. Štandardný kurzor prehliadača je nudný a nie je hoden skutočného športového fanúšika. Staňte sa originálni a jedineční s našou kolekciou. Stiahnite si obrázky a vyberte si farby svojho obľúbeného tímu alebo vlastné kurzory, ak len milujete šport a fandíte všetkým. Sledovanie svojich koníčkov je také jednoduché - nemusíte chodiť do práce v šatke alebo čiapke svojho obľúbeného tímu, je ľahké a rýchle zmeniť kurzor na jasný, štýlový obrázok.',
    'avtomobili_descr' => 'Máte radi autá a radi sa pozeráte na modely od rôznych výrobcov? Alebo už dlho snívate o konkrétnej značke, ale stále nemáte možnosť si ju kúpiť? Špeciálne pre vás sme vytvorili svetlú sadu kurzorov "Supercars". Nájdete tu klasický Ford a štýlový Bentley, výrazné Lamborghini a unikátne Ferrari. Chcete sa stať majiteľom originálneho auta? Je to jednoduché - stiahnite si našu zbierku kurzorov do svojho zariadenia a zmeňte obraz auta aspoň každý deň. KurzorY sú navrhnuté v dvoch verziách - ako plnohodnotné auto alebo ako jeho znak. Vyberte si, čo sa vám najviac páči, alebo ako radšej pracujete. Takéto obrázky budú vyzerať skvele ako herné kurzory alebo jednoducho ako nezvyčajný prvok pracovnej plochy. Byť jasný je jednoduché - nie je na to potrebné robiť nepredstaviteľné veci alebo meniť svoj vzhľad. Stačí prestať používať všedné predmety a vybrať si to, čo sa vám skutočne páči. Zbierka kurzorov "Autá" je voľbou pre tých, ktorí sa neboja preukázať.',
    'memy_descr' => 'Mémy sú už dlho známa súčasť našich životov. A kto z nás nemá rád tieto rozsiahle, zaujímavé a originálne obrázky, aby sa napriek dňu? Mnohí hrdinovia mémov sa nestali len populárnymi - získali status populárnych favoritov a frázy a výrazy sú už dlho zahrnuté v hovorovej reči ako zavedené obraty. Predstavujeme kolekciu najlepších kurzorov založených na najpopulárnejších mémoch. S ich pomocou môžete nielen ukázať svoju osobnosť, ale aj vyjadriť svoju náladu. Ste všetci unavení a unudení zo všetkého? Vyberte si nahnevanú mačku, ktorá svojím vzhľadom vyjadruje rozhorčenie a nepriateľstvo voči všetkému okolo seba. Alebo dnes žiariš sarkazmom a nevadí ti smiech? Potom bude Drake Bling vynikajúcou sprevádzajúcou osobou - rozveselí vás a urobí akúkoľvek úlohu originálnou a zaujímavou. Nainštalujte si rozšírenie, stiahnite si našu kolekciu - a vyberte si štýl kurzora na každý deň. Nie je ťažké byť jasný a originálny - zmeňte štandardný dizajn ikony na jedného z hrdinov mémov a získajte energetickú podporu na celý deň.',
    'emodji_descr' => 'Emoji - jasné, cool ikony, bez ktorých už nedokážeme bežne komunikovať. S ich pomocou nemusíte popisovať svoju náladu slovami - stačí vybrať požadovanú ikonu a interlokútor vám rozumie bez ďalších okolkov. V našej novej sade kurzorov sme stelesnili myšlienku emoji - takto sa objavili zábavné a neobvyklé Cursoji, ktoré sfarbia svet a urobia život zaujímavejším. Pomocou kurzorov môžete nielen pracovať a vykonávať známe úlohy, ale aj ukázať svojim kolegom, priateľom a len ostatným svoju náladu. Ospalý kurzor je ideálny na pondelkové ráno a plačúci kurzor vyjadrí postoj k dodatočným povinnostiam. Cool kurzor s okuliarmi je najlepšia voľba pred sviatkami a kurzor s dolármi v očiach je dobrý dôvod naznačiť vedúcemu o zvýšení platu. Používanie Cursoji je zábavné a zaujímavé - či už ide o prácu, štúdium alebo prezentáciu. V druhom prípade sa to dokonca odporúča, ak majú kolegovia zmysel pre humor alebo je jednoducho potrebné uvoľniť situáciu. Všeobecne platí, že pre akúkoľvek úlohu - stačí zvoliť správny kurzor!',
    'pitomcy_descr' => 'Máte radi zvieratá? Iste - sú tak roztomilé, vtipné a veľmi zábavné. Prečo nestráviť celý deň v spoločnosti najlepších priateľov človeka? Stiahnite si kolekciu kurzorov Zvieratká pre seba a vyberte si priateľa na každý deň. Ikona kurzora môže byť roztomilá, ako dobrosrdečná alpaka, alebo štýlová, ako ružový plameniak. Alebo možno budete celý deň zaneprázdnení a vyberiete si jednorožca čítajúceho noviny, alebo sa jednoducho s nikým nechcete stretávať, ako zlý čierny kocúr? Pre akúkoľvek náladu máme príslušné zviera. Veselý mopslík vás rozveselí aj v ten najnudnejší a najšedivejší deň a ružový kurzor v tvare jednorožca všetkým ukáže, že nie ste zbavení zmyslu pre krásu, aj keď ste brutálny bradatý muž. Čo ak nemám náladu a nechce sa mi robiť rutinné úlohy? Recept je jednoduchý - stiahnite si kolekciu Zvieratká, zmeňte kurzor myši - a voila, slnko opäť svieti, počasie je pekné a nálada je na najvyššej úrovni. Niet divu, že sa hovorí, že zvieratá pomáhajú bojovať proti depresii a smútku!',
    'stil_i_krasota_descr' => 'V novej kolekcii kurzorov sme zhromaždili najrôznejšie predmety, ktoré v nás vyvolávajú príjemné emócie a povznášajú. Táto sada kurzorov sa nazýva „Štýl a krása“, pretože sú to vaše obľúbené veci, ktoré určujú náš každodenný život, prinášajú radosť a motivujú nás k dôležitým veciam, prebúdzajú túžbu po zlepšení. Máte radi vesmír a snívate o cestovaní na iné planéty? Vyberte si kurzor NASA alebo tanier s mimozemšťanmi - priblížte sa svojmu snu. Ak si neviete predstaviť život bez hudby alebo ste zarytý rocker, potom je pre vás kurzor v štýle elektrickej gitary. Kresliaca ceruzka, pravítko a kurzor s kompasom boli špeciálne vyvinuté pre inžinierov - takéto obrázky pomôžu premeniť nudné výpočty a kresby na originálne riešenia. Kúzelná palička a tenisky, skateboard a rúž, slnko a chemické kužele - vyberte si to, čo sa hodí k vášmu životnému štýlu, vašim túžbam a ambíciám - a obyčajné úlohy budú zaujímavejšie a pracovné dni budú namaľované novými, jasnými farbami.',
    'prazdniki_descr' => 'Máte radi sviatky? Ale kto ich nemá rád - priatelia, darčeky, znova ten istý víkend. Aby bolo čakanie na sviatky príjemnejšie, kratšie a teplejšie, môžete počítať dni na kalendári, ale aj nastaviť zodpovedajúcu ikonu ako kurzor myši. Poďme začať s Novým rokom - vyberieme si vianočný stromček, darček alebo Santu Clausa, aby bol sviatok jasný a veselý. Možno bude bližšie perníkový panáčik - vtipný, roztomilý a vždy veselý? S ním určite nebude čas na smútok a nudu. Pokračujeme v oslave s kupidmi a veselými srdcami a už nie je ďaleko k Veľkonočnému zajačikovi. Niekde medzi sviatkami budú narodeniny, na ktoré bude ešte príjemnejšie čakať s balónikmi namiesto štandardnej šípky kurzora. A na Halloween môžete prekvapiť kolegov a ľudí okolo vás nezvyčajným kurzorom myši v podobe zlovestnej tekvice alebo ducha. Súbor kurzorov pre sviatky je príležitosťou na rozjasnenie očakávania, predbežné naladenie na nadchádzajúcu zábavu a udržanie si vynikajúcej nálady nielen v predvečer oslavy, ale počas celého roka.',
    'flagi_descr' => 'Zástava je jedinečný symbol, ktorý sa široko používa vo všetkých sociálnych sieťach. Pomysleli sme si, prečo neurobiť kurzor vlajkou? Koniec koncov, je to naozaj jasné a nezvyčajné. Teraz môžete tráviť každý deň v spoločnosti s novou krajinou a práca nebude taká monotónna a nudná. Kurzory myši sa teraz môžu premeniť na štátnu vlajku Číny alebo USA, Japonska alebo Kanady a v ďalších 38 možnostiach vlajok si môžete vybrať buď štandardný tvar šípky v nezvyčajnej farbe, alebo kurzor v tvare samotnej vlajky. Táto sada osloví všetkých milovníkov cestovania. Pomocou nej si môžete naplánovať nové výlety a snívať o dlhých cestách. Máte naplánovanú dovolenku? Ukážte všetkým, do ktorej krajiny sa chcete ísť. Možno ste sa rozhodli naučiť nový cudzí jazyk? Potom vás tento kurzor určite podporí a motivuje vás k starostlivému štúdiu. Alebo, rovnako ako Sheldon, jednoducho milujete vlajky? Vo všetkých prípadoch bude kolekcia kurzorov Vlajky skvelým doplnkom na vašu pracovnú plochu a presunie vás k novým objavom.',
    'vokrug_sveta_descr' => 'Každý rád cestuje. Aké úžasné je navštíviť nové krajiny a mestá, vidieť pamiatky a skvele sa zabaviť v novej kultúre. Je škoda, že nemôžeme cestovať tak často, ale pokúsili sme sa to napraviť. Súprava kurzorov "Around the World" je kolekcia najvýraznejších obrázkov, symbolov rôznych krajín, pomocou ktorých sa aj sediac doma môžete cítiť ako skutočný cestovateľ. V našej súprave nájdete Japonsko a Austráliu, Taliansko a Kanadu, USA a Mexiko - najzaujímavejšie, originálne a malebné krajiny sveta. Obrázok kurzora sa môže stať štandardnou šípkou, vo farbách vlajky krajiny, alebo sa stať jednou z hlavných atrakcií štátu. Napríklad môžete otvárať dokumenty so Šikmou vežou v Pise a robiť prezentácie pomocou Sochy slobody. Zaručujeme - úspech bude zaistený. No, alebo ak nie úspech, tak úsmevy kolegov a uznanie originality - určite. Áno, a naznačenie vedeniu, že je čas ísť na dovolenku, bude tiež stáť za to - stačí nastaviť kufor alebo lietadlo ako kurzor - a s najväčšou pravdepodobnosťou budete čoskoro lietať.',
    'eda_i_napitki_descr' => 'Sada kurzorov vo forme produktov je neuveriteľná zbierka jasných, chutných a ústami zalievajúcich obrázkov, ktoré sa budú páčiť úplne každému a budú skvelým doplnkom prehliadača. Klikli ste už niekedy na brokolicu alebo hranolky? Máte takúto príležitosť - stačí si stiahnuť novú sadu kurzorov a nastaviť ich namiesto nudnej bielej šípky. Kurzorov "Jedlo" sú vyrobené vo forme štandardného trojuholníkového ukazovateľa, ale aj vo forme produktov. Nájdete tu zeleninu a ovocie, vaše obľúbené jedlá, ako je pizza alebo hot dogy, káva, lízanky a oveľa viac, čo rozveselí každý deň. Milujete kávu, ale piť ju celý deň nie je až také dobré? Doplňte svoju stravu virtuálnou kávou, ktorá vás tiež povzbudí a prebudí, ako aj poskytne živé emócie. Strmý kurzor vo forme virtuálneho šišky nepoškodí postavu a zároveň poskytne živé emócie a rozveselí. Môžete použiť svoje obľúbené kurzory alebo meniť obrázok každý deň - rozsiahly výber kurzorov pomôže zafarbiť každodenný život a pridať nové farby do známych činností.',
    'cvetnye_descr' => 'Kurzor je hlavný prvok prehliadača, s ktorým trávime celý pracovný deň, študujeme, komunikujeme a relaxujeme. Štandardný vzhľad kurzora je nudný a dokonca trochu deprimujúci, ale predsa len, pre mnohých ľudí je táto forma pohodlná a zmena by bola nepríjemná. Ale pre túto situáciu máme riešenie - sadu kurzorov v jasných, veselých farbách, ktoré prinesú rozmanitosť do vášho každodenného života a uľahčia a urýchlia riešenie akýchkoľvek problémov. Ak premýšľate, ako zmeniť farbu kurzora, odpovedáme - stiahnite si našu kolekciu a vyberte si jasné riešenia na každý deň! Môžete si vybrať monochromatické tóny v rôznych farbách, aby vyhovovali nálade alebo špecifikám práce. Napríklad pri práci so štandardnými dokumentmi bude fialový kurzor vynikať na pozadí a na tmavom pozadí sa naopak ľahšie pracuje so žltými kurzormi. Ak chcete explóziu farieb, jasu a maximálnej originality - vyberte si dúhový kurzor, ktorý obsahuje všetky farby spektra - s touto ikonou bude nálada počas celého dňa určite v poriadku.',
    'prank_descr' => 'Žarty v práci nie sú vždy vítané, pretože často zasahujú do pracovného postupu. Ale s novou sadou kurzorov „Žarty“ môžete láskavo zahrať nejaký žart na svojich kolegov alebo priateľov bez toho, aby ste poškodili svoju prácu alebo štúdium. Vyvinuli sme špeciálnu kolekciu, ktorá pobaví každého a poskytne dôvod na trochu relaxu uprostred rušného procesu práce alebo vykonávania ďalšej úlohy. Ak chcete zmeniť kurzor myši, stačí stiahnuť súpravu do zariadenia a vybrať dizajn, ktorý sa vám páči, v parametroch. Môžete napríklad získať kurzor štandardného tvaru, ale v obrátenom stave alebo šípku zakrivenú vlnou. Táto forma nijako neprekáža procesu práce, ale zároveň predstaví úžasnú náladu a naladí vás pozitívne. Zmeňte nastavenia zobrazenia kurzora podľa svojej nálady alebo každý deň – a každá úloha sa stane zaujímavejšou a príjemnejšou a každodenný život prestane vyvolávať negatívne emócie. Okrem toho sa takéto kurzory dajú použiť aj pre seriózne projekty – majú neutrálne farby a nevytŕčajú z pracovnej plochy.',
    'startovyj_nabor_descr' => 'Kurzory zo štartovacej kolekcie sú zmesou štandardných tvarov a veľkostí so svetlým, nezvyčajným vzhľadom. Toto je vynikajúca voľba pre tých, ktorí preferujú obvyklé formy, ale chcú vniesť rozmanitosť, originalitu a jas do každodenného života. Kolekcia má kurzor ruky a známu šípku v rôznych variáciách - od loga Google Chrome až po emotikony, môžete tu dokonca stretnúť dávno zabudnutého draka s kaktusmi a nostalgiou. Dokazujeme, že štandardný kurzor môže byť tiež zaujímavý a atraktívny. Rôzne farby, tvary, textúry a zaujímavý dizajn vám pomôžu vybrať si kurzor podľa chuti alebo ho meniť každý deň v závislosti od nálady alebo vykonávaných úloh. Zmena kurzorov prehliadača je veľmi jednoduchá - stačí si nainštalovať rozšírenie a stiahnuť kolekciu do svojho zariadenia. Vtipné, zaujímavé kurzory nielenže zafarbia pracovné dni, ale tiež, napríklad, pomôžu urobiť akúkoľvek prezentáciu zaujímavejšou, a pomocou obzvlášť jasných kurzorov tiež upútať pozornosť na jednotlivé prvky správy.',
    'fortnite_descr' => 'Fortnite si podmanil milióny ľudí po celom svete. Vzrušujúce bitky, stratégia a taktika, dobrodružstvá - pohltil úplne všetko, čo sa hráčom tak páči. Nemohli sme zostať bokom a vyvinuli sme sadu kurzorov v štýle hry, ktorá osloví nielen vášnivých hráčov, ale aj tých, ktorí o Fortnite počuli prvýkrát. Ikona kurzora Fortnite je obraz hrdinu alebo jeho zbrane, prepracovaný do najmenších detailov. Tu nájdete obrázky líšok a rýb, masky inferno a čiernych rytierov, nastavte si šípku alebo kosu s hrotmi ako šípku. Sme si istí, že nikto nezostane ľahostajný! Byť strašidelný alebo tajomný, originálny alebo humorný - je len na vás. Vyberte si svoj štýl a riaďte sa ním alebo si nastavte vlastné kurzy v nastaveniach a zmeňte svoju úlohu každý deň. Teraz bude oveľa zaujímavejšie a príjemnejšie vykonávať aj únavnú a monotónnu prácu - čas ubehne rýchlo v spoločnosti živých obrázkov a obľúbených postáv. Alebo si možno zariadite súťaže s kolegami, ktorý hrdina bude silnejší? Voľba je na vás!',
    'dota_2_descr' => 'DotA2 už nie je len jednoduchá hra, je to skutočný paralelný svet. Vo virtuálnej realite v DotA2 môžete robiť všetko - žiť, bojovať, rozvíjať sa, cestovať, spriateliť sa. Všeobecne platí, že všetko je ako v živote, len niekedy zaujímavejšie. Kurzorom Dota 2 je pokračovanie stratégie, ktorá vám umožní získať živé emócie a vyjadriť sa v reálnom svete. Nová sada kurzorov obsahuje najvýraznejšie postavy v hre, ako aj originálne predmety, ktoré si nemožno s ničím iným pomýliť. Vyberte si kurzor, ktorý vám bude bližší - a vydajte sa na dobrodružstvo bez toho, aby ste opustili svoje pracovisko. Aké nudné je niekedy byť v práci alebo plniť vzdelávacie úlohy, ale s hernými kurzormi vás tento problém už nekonfrontuje. Trochu fantázie, jasný kurzor - a voilà, akýkoľvek podnik bude nezvyčajným dobrodružstvom, s ktorým sa bude ľahko a zaujímavo vyrovnať. Nie je potrebné sa obmedzovať. Máte radi Dotu? Potom si určite stiahnite našu zbierku, vyberte si jeden alebo niekoľko náhodných kurzorov naraz - a každý nový deň bude jasnejší, zaujímavejší a sýtejší.',
    'minecraft_descr' => 'Myšacie kurzory vo forme štandardných šípok a prstov sa už dávno každému zunovali. Ak ste fanúšikom nezvyčajného a originálneho, potom je čas zmeniť kurzor myši a dať mu zaujímavejší dizajn. Vyvinuli sme kolekciu kurzorov v štýle svetoznámej hry Minecraft, kde nájdete najvýraznejšie postavy. Vlk a líška, Alex a Creeper, diamantový meč a ryba - môžete si vybrať ten, ktorý sa vám najviac páči, alebo si každý deň nainštalovať nového hrdinu. Toto sú skutočné kurzory pre hráčov a absolútne sa budú páčiť všetkým - veď kto z nás nehral Minecraft? Sme si istí, že jednoducho neexistujú. Dosť nudného každodenného života - je čas ponoriť sa do dobrodružstiev, ktoré sa dajú robiť aj bez toho, aby ste opustili svoj domov alebo kancelársku stoličku. Bude zaujímavejšie pripraviť správu a znížiť zostatok so zbraňou - akákoľvek úloha bude príjemnejšia a nedovolí vám, aby ste sa nudili na mieste. Stiahnite si novú kolekciu kurzorov Minecraft - nastavte ich a aj v ten najsivejší a najnudnejší deň bude vaša nálada vždy najlepšia. A kolegovia budú závidieť vaše výsledky - je jednoducho nemožné nerobiť svoju prácu pomocou statočných hrdinov Minecraftu.',
];
