<?php

return [
    'title' => 'Cursor Style - Zásady ochrany osobných údajov',
    'descr' => 'V rozšírení “Cursor Style,” dostupnom na cursor.style alebo prostredníctvom rozšírenia pre Chrome, je jednou z našich najvyšších priorít súkromie našich návštevníkov. V tejto sekcii budeme hovoriť o všetkých aspektoch práce s rozšírením.',
    'text' => '<h2> Zásady ochrany osobných údajov </h2>
                <p> V "Cursor Style", dostupnom na <a href="https://cursor.style"> cursor.style </a> alebo prostredníctvom rozšírenia pre Chrome, je jednou z našich najvyšších priorít súkromie našich návštevníkov. Tento dokument Zásad ochrany osobných údajov obsahuje typy informácií, ktoré sú zhromažďované a zaznamenávané webovou stránkou cursor.style, a spôsob, akým ich používame. Ak máte ďalšie otázky alebo potrebujete viac informácií o našich Zásadách ochrany osobných údajov, neváhajte nás kontaktovať. </p>
                <p> Rozšírenie "Cursor Style" a webová stránka dodržiavajú štandardný postup pri používaní súborov protokolu. Tieto súbory registrujú návštevníkov, keď navštívia webové stránky alebo používajú naše rozšírenie. Všetky hostingové spoločnosti to robia a sú súčasťou analytiky hostingovej služby. Informácie zhromaždené prostredníctvom protokolových súborov zahŕňajú adresy internetového protokolu (IP), typ prehliadača, poskytovateľa internetových služieb (ISP), dátum a časovú pečiatku, prechodové / výstupne stránky a prípadne počet kliknutí. Nie sú spojené s žiadnymi osobne identifikovateľnými informáciami. Účelom týchto informácií je analyzovať trendy, spravovať stránku a rozširovať ju, sledovať pohyb používateľov na stránke a rozširovať ju a zhromažďovať demografické informácie. </p>
                <p> Rovnako ako akákoľvek iná stránka, cursor.style používa súbory cookie. Tieto súbory cookie sa používajú na ukladanie informácií, vrátane preferencií návštevníka a stránok na webovej stránke, ktoré návštevník navštívil alebo navštívil. Tieto informácie sa používajú na optimalizáciu používateľského zážitku prispôsobením obsahu našej webovej stránky na základe typu prehliadača návštevníka a / alebo iných informácií. Používame tiež reklamy tretích strán na cursor.style na podporu projektu a podporu našej webovej stránky. Niektorí z týchto inzerentov môžu pri inzercii na našej webovej stránke používať technológie ako súbory cookie a webové majáky, ktoré tiež zašlú týmto inzerentom (napríklad spoločnosti Google prostredníctvom programu Google AdSense) informácie, vrátane vašej IP adresy, vášho poskytovateľa internetu, prehliadača, ktorý ste použili na návštevu našej stránky, a v niektorých prípadoch, ak máte nainštalovaný Flash. To sa zvyčajne používa na účely geotargetingu (napríklad zobrazenie reklám na predaj tovaru vo vašom meste) alebo na zobrazovanie určitých reklám na základe určitých navštívených webových stránok (napríklad zobrazenie oznámení o nákupe tým, ktorí často navštevujú nákupné stránky). </ P >
                <p> Súbory cookie môžete zakázať alebo selektívne zakázať naše alebo súbory cookie tretích strán v nastaveniach prehliadača alebo spravovaním nastavení v programoch ako Kaspersky atď. To však môže ovplyvniť spôsob, akým interagujete s našou stránkou, ako aj s inými stránkami. To môže zahŕňať nemožnosť prihlásiť sa do služieb alebo programov, napríklad prihlásenie sa do fór alebo účtov. </p>
<p> Google je jedným z poskytovateľov tretích strán na našej stránke. Používa tiež súbory cookie, známe ako súbory cookie DART, na zobrazovanie reklám návštevníkom našej stránky na základe ich návštev cursor.style a ďalších stránok na internete. Návštevníci sa však môžu zriecť používania súborov cookie DART návštevou zásad ochrany osobných údajov služby Reklama a obsahová sieť služby Google na <a href="https://policies.google.com/technologies/ads"> nasledujúcej adrese </a>. Niektorí z inzerentov na našej webovej stránke môžu používať súbory cookie a webové majáky. Každý z našich reklamných partnerov má svoje vlastné zásady ochrany osobných údajov pre svoje zásady týkajúce sa údajov používateľov. O ich Zásadách ochrany osobných údajov sa môžete dozvedieť viac <a href="https://policies.google.com/technologies/ads"> tu </a>. </p>
                <p> Naša webová stránka používa službu Google Analytics, službu webovej analýzy spoločnosti Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com („Google Analytics“ alebo „Google“). Google Analytics používa súbory cookie, ktoré sú uložené vo vašom počítači, aby uľahčili analýzu vášho používania webovej stránky. Informácie generované týmito súbormi cookie, ako je čas, miesto a frekvencia vašich návštev na našej webovej stránke, vrátane vašej IP adresy, sa prenášajú na miesto spoločnosti Google v USA a tam sa ukladajú. Spoločnosť Google môže tieto informácie prenášať aj tretím stranám, ak to vyžaduje zákon alebo ak tieto tretie strany spracúvajú tieto údaje v mene spoločnosti Google. Spoločnosť Google uvádza, že nikdy nespája vašu IP adresu s inými údajmi spoločnosti Google. Inštalácii  súborov cookie môžete zabrániť zmenou nastavení softvéru prehliadača, ako je uvedené v týchto Zásadách ochrany osobných údajov. Mali by ste si však byť vedomí toho, že týmto spôsobom nebudete môcť naplno využívať všetky funkcie našej webovej stránky. </p>
                <p> Google Analytics tiež používa elektronické obrázky známe ako webové majáky (niekedy nazývané jednoduché pixlové GIF) a používajú sa so súbormi cookie na zostavovanie agregovanej štatistiky na analýzu používania našej stránky.
Ďalšie informácie o tom, ako nainštalovať doplnok prehliadača, ktorý ste prepojili vyššie, nájdete na <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> odkaze </a>.
Táto stránka používa nástroj Google Tag Manager. Táto služba vám umožňuje spravovať značky stránok prostredníctvom rozhrania. Google Tag Manager implementuje iba značky. To znamená, že súbory cookie sa nenastavujú a žiadne osobné údaje sa nezaznamenávajú. Google Tag Manager spúšťa ďalšie značky, ktoré môžu zase zaznamenávať údaje. Nástroj Google Tag Manager však nemá prístup k týmto údajom. Ak boli značky deaktivované na úrovni domény alebo súboru cookie, uložia sa pre všetky značky sledovania, ak sa implementujú pomocou nástroja Google Tag Manager. Viac informácií o nástroji Google Tag Manager nájdete na <a href="http://www.google.com/tagmanager/use-policy.html"> odkaze </a>. </p>
<p> Môžete sa oboznámiť s týmto zoznamom, aby ste našli Zásady ochrany osobných údajov pre každého z reklamných partnerov "Cursor Style". Reklamné servery alebo reklamné siete tretích strán používajú technológie ako súbory cookie, JavaScript alebo webové majáky, ktoré sa používajú v ich príslušných reklamách a odkazoch, ktoré sa zobrazujú v "Cursor Style" a odosielajú sa priamo do prehliadača používateľov. Týmto automaticky získajú vašu IP adresu. Tieto technológie sa používajú na meranie efektívnosti ich reklamných kampaní a / alebo na personalizáciu reklamného obsahu, ktorý vidíte na navštívených webových stránkach. Upozorňujeme, že "Cursor Style" nemá prístup ani kontrolu nad týmito súbormi cookie, ktoré používajú inzerenti tretích strán. Zásady ochrany osobných údajov služby Cursor Style sa nevzťahujú na iných inzerentov ani webové stránky. Preto odporúčame, aby ste si pre viac informácií prečítali príslušné zásady ochrany osobných údajov týchto reklamných serverov tretích strán. Môže to zahŕňať ich metódy a pokyny, ako sa odhlásiť z určitých možností. Odkazy na tieto Zásady ochrany osobných údajov tretích strán nájdete vyššie alebo na webových stránkach týchto služieb tretích strán. </p>
                <p> Súbory cookie môžete zakázať v nastaveniach prehliadača. Ak sa chcete dozvedieť viac o správe súborov cookie v konkrétnych webových prehliadačoch, nájdete to na ich príslušných webových stránkach prehliadačov. Ďalšou súčasťou našej priority je pridanie ochrany detí pri používaní internetu. Odporúčame rodičom a opatrovníkom, aby sledovali, zúčastňovali sa a / alebo monitorovali a riadili svoje aktivity na internete. ""Cursor Style"" vedome nezhromažďuje osobné údaje od detí mladších ako 13 rokov. Ak si myslíte, že vaše dieťa poskytlo takéto informácie na našej webovej stránke, dôrazne vám odporúčame, aby ste nás okamžite kontaktovali a my urobíme všetko pre to, aby sme tieto informácie z našich záznamov rýchlo odstránili. Tieto Zásady ochrany osobných údajov sa vzťahujú iba na naše online aktivity a sú platné pre návštevníkov našej webovej stránky vo vzťahu k informáciám, ktoré zdieľali a / alebo zhromaždili v "Cursor Style". Tieto zásady sa nevzťahujú na žiadne informácie zhromaždené offline alebo prostredníctvom kanálov iných ako táto webová stránka. </p>
                <p> Viac informácií o používaní súborov cookie v našich Službách si môžete prečítať v našich <a href="/cookie-policy"> Zásadách používania súborov cookie </a>. </p> ',
];
