<?php

return [
    'halo_descr' => 'Halo to seria medialna fantasy z walką, stworzona przez Bungie. Oparta na oryginalnej trylogii strzelanek pierwszoosobowych. Fabuła koncentruje się wokół wydarzeń mających miejsce w życiu Master Chiefa, jednego z grupy supersoldatów o kryptonimie Spartans, i jego towarzyszki, sztucznej inteligencji Cortany. Sukces gier doprowadził do rozszerzenia franczyzy na inne media: uniwersum Halo obejmuje obecnie wiele książek, powieści graficznych, komiksów, krótkich filmów, animacji i filmów fabularnych.',
    'halo_short_descr' => 'Dotknij kursora artefaktu, może jesteś wybrańcem',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'Laleczki LOL Surprise pokochały dzieci i zdobyły ich serca od pierwszych minut. I to nie jest zaskakujące, ponieważ sukces ten opiera się na tajemnicy, oczekiwaniu na cud, miłej niespodziance, która zachwyca nie tylko dzieci, ale i ich rodziców. Tajemnica prezentu zostaje ujawniona dziecku dopiero po ostatecznym rozpakowaniu. W każdym razie lalki LOL to atrakcyjny design, intryga, duża liczba niesamowitych i realistycznych akcesoriów i miłych drobiazgów, a także najwyższa jakość produkcji i szczegółowości zabawki.',
    'lol_surprise_short_descr' => 'Fajne ślicznotki dla koneserów pięknych niespodzianek',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Serial opowiada o konkursie, w którym 456 graczy, z których wszyscy mają ogromne długi finansowe, ryzykują życie, aby zagrać w serię śmiertelnych gier dla dzieci, aby wygrać nagrodę w wysokości miliarda. W środku czeka kusząca nagroda z zabójczym ryzykiem. Tytuł serialu zaczerpnięto z podobnie nazwanej koreańskiej gry dla dzieci. Hwang wpadł na pomysł w oparciu o własne zmagania ekonomiczne na początku życia, a także o nierówności społeczne w Korei Południowej i kapitalizmie.',
    'squid_game_short_descr' => 'Wybierz właściwą twarz gracza, gdy grasz va banque',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter jest głównym bohaterem serii powieści angielskiej pisarki J.K. Rowling. W swoje jedenaste urodziny, Harry dowiaduje się, że jest czarodziejem i jest przeznaczony do nauki w Szkole Magii i Czarodziejstwa w Hogwarcie, gdzie będzie praktykował magię pod okiem dyrektora Albusa Dumbledore\'a i innych profesorów szkoły. Harry odkrywa również, że jest już znany w całym magicznym świecie powieści i że jego los jest powiązany z losem Voldemorta, niebezpiecznego, mrocznego maga.',
    'harry_potter_short_descr' => 'Co zrobisz z magiczną różdżką z kolekcji kursorów Harry\'ego Pottera',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics to wydawnictwo komiksowe znane z tworzenia znanych superbohaterów, takich jak Spider-Man, Iron Man, Kapitan Ameryka, Hulk, Thor, Avengers, Strażnicy Galaktyki, X-Men, Fantastyczna Czwórka i Deadpool. Najbardziej znani złoczyńcy Marvela to między innymi Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom i Magneto. Marvel Comics i DC Comics współpracowały razem przy kilku wspólnych projektach crossover oraz współzałożyły celowo krótkotrwały imprint Amalgam Comics.',
    'marvel_comics_short_descr' => 'Superbohater żyje w każdym z nas - wybierz swojego',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Witamy ponownie w Cookie Kingdom w Cookie Run: Kingdom od Devsisters, uroczej strategii RPG osadzonej we wszechświecie Cookie Run. Teraz, gdy GingerBrave uciekł z piekarnika złej wiedźmy, nadszedł czas, aby zbudował drużynę ciasteczek i wyruszył na wyprawę w celu odbudowy upadłego Cookie Kingdom. Odkryj prawdę o upadku Królestwa i zbierz oddział najpotężniejszych ciasteczek w Królestwie, aby pokonać mroczne siły, które chcą powstrzymać GingerBrave przed wypełnieniem przeznaczenia.',
    'cookie_run_kingdom_short_descr' => 'Mali wojownicy prosto z pieca',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact to gra przygodowa z otwartym światem. Oznacza to, że nowy, zachwycający krajobraz czeka na ciebie po drugiej stronie rzeki lub góry, wystarczy, że mądrze wykorzystasz swoją energię. Jeśli natkniesz się na błąkającą się wróżkę lub dziwny mechanizm, odważ się i spróbuj rozwikłać ich tajemnicę. Ale co obiecują - kłopoty czy miłą niespodziankę - tylko ty możesz się dowiedzieć! Na rozległym kontynencie Teyvat odwiedzisz siedem królestw, znajdziesz towarzyszy o różnych umiejętnościach i będziesz walczyć z potężnymi wrogami w poszukiwaniu zaginionej ukochanej osoby.',
    'genshin_impact_short_descr' => 'Zostań Władcą Żywiołów Siedmiu Królestw',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Kiedy spełnia się starożytna przepowiednia i królestwo pogrąża się w objęciach zimy, trzech nieustraszonych bohaterów - księżniczka Anna, dzielny Kristoff i jego wierny renifer Sven - udają się w góry, aby odnaleźć siostrę Anny, Elsę, która potrafi zdjąć mrożące zaklęcie z kraju. Po drodze czeka ich wiele trudnych niespodzianek i ekscytujących przygód. Spotkanie mistycznych trolli, poznanie uroczego bałwana o imieniu Olaf, szczyty górskie bardziej strome niż Everest i mnóstwo magii. Bohaterowie muszą przeciwstawić się potężnym żywiołom, aby ocalić królestwo i tych, którzy są dla nich drodzy.',
    'frozen_short_descr' => 'Przełamanie lodu jest proste z kolekcją kursorów Frozen',
    'frozen' => 'Frozen',
    'stranger_things_descr' => 'Minęło nieco ponad sześć miesięcy od finału trzeciego sezonu. Joyce, Will, Eleven i Jonathan przeprowadzili się do Kalifornii, gdzie dziewczyna jest prześladowana w szkole. Reszta zaczyna walczyć z nowym potworem z równoległego świata, który pojawił się w Hawkins. Został nazwany Vecną ​​po postaci z gry planszowej Dungeons & Dragons. Wpływa na nastolatków psychologicznie, następnie mentalnie wnika w głowę i zabija. Równolegle, Joyce i Murray dowiadują się, że Jim Hopper żyje i ruszają za nim do radzieckiego więzienia na Kamczatce. A Eleven będzie musiała wrócić i zwiększyć swoje moce, ale także poznać swoją ważną rolę w tworzeniu tego samego potwora w Gokins.

Scenarzyści nie zmienili taktyki fabularnej, która spodobała im się w ostatnich kilku sezonach. W czwartym sezonie podzielili dużą grupę głównych bohaterów na grupy, wymyślili dla nich trudne zadania i na końcu zbudowali ich historie razem w niesamowitym zakończeniu. Oferujemy Ci szczegółowe zrozumienie wszystkich tych przygód za pomocą kolekcji kursorów Stranger Things.',
    'stranger_things_short_descr' => 'Co będzie dalej? - Kursory ze Stranger Things 4',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars to oryginalny tryb, który pojawił się po raz pierwszy w Minecraft. Zadaniem graczy było, aby użytkownik chronił swoją bazę i łóżko.

Roblox codziennie przynosi bardziej ekscytujące gry i BedWars nie jest wyjątkiem. Rzecz w tym, że jeśli kochasz bed wars i bronisz się w swoim pokoju, to jest to tytuł dla ciebie, ponieważ przenosi cię z powrotem do dzieciństwa, choć tym razem w formie cyfrowej.

Wszystko, co musisz zrobić, to bronić swojego łóżka przed napastnikami ze swoim partnerem. Wchodzisz do lobby, wybierasz z kim grać i voila, to tylko kwestia ochrony.

Oczywiście, jeśli chodzi o obronę, będziesz mieć pewne problemy i istnieją pewne zasoby, przedmioty i przedmioty, które pomogą ci wygrać. Na przykład ekskluzywne skiny, które znajdziesz w kolekcji kursorów Bed Wars.',
    'roblox_bed_wars_short_descr' => 'Chroń swoje łóżko za pomocą kursorów z Roblox Bed Wars',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'W dniu urodzin Naruto Uzumakiego legendarny demon, Lis o Dziewięciu Ogonach, zaatakował wioskę Konoha. Czwarty Hokage, kosztem własnego życia, uratował wioskę, pieczętując demona w nowo narodzonym Naruto, nieświadomie skazując go na życie pełne nienawiści od współmieszkańców.
Pomimo braku talentu w wielu dziedzinach ninjutsu, niepokoju i zarozumiałości, Naruto marzy o tym, by zostać Hokage, najsilniejszym ninja w wiosce. Pragnąc uznania, którego nie otrzymał, ciężko pracuje i trenuje wraz ze swoimi kolegami z drużyny, Sasuke Uchiha i Sakura Haruno, a także swoim mentorem Kakashi Hatake. On i jego partnerzy będą musieli przejść przez wiele na drodze do swoich ukochanych marzeń: bitwy, miłość, przyjaźń, zdrada, pragnienie władzy. Kolekcja kursorów z anime Naruto pomoże Ci nawigować po własnej ścieżce!',
    'naruto_anime_short_descr' => 'Podążaj ścieżką ninja z kursorami z anime Naruto',
    'naruto_anime' => 'Anime Naruto',
    'demon_slayer_anime_descr' => 'Akcja rozgrywa się w erze Taisho. Od czasów starożytnych krążyły pogłoski, że w lesie żyją humanoidalne demony, które żywią się ludźmi i chodzą w nocy, szukając nowej ofiary. Ale... to tylko legenda, prawda?..

Tanjiro Kamado jest najstarszym synem w rodzinie, który stracił ojca i opiekował się rodziną. Pewnego dnia idzie do pobliskiego miasteczka, aby sprzedać węgiel drzewny. Wracając rano, chłopak odkrywa przed sobą straszny obraz: wszyscy krewni zostali brutalnie zabici, a jedyną ocalałą jest Nezuko, młodsza siostra, która zmieniła się w demona, ale która jeszcze nie straciła całej swojej ludzkości.

Od tego momentu Tanjiro i Nezuko rozpoczynają długą i niebezpieczną podróż, w której chłopiec zamierza znaleźć zabójcę i znaleźć sposób na wyleczenie siostry. Ale czy dzieci są w stanie pokonać wszystkie trudności i wrócić do domu? Znasz już odpowiedź, a jeśli nie - raczej ustaw kursory Demon Slayer, z postaciami z jednej z najpopularniejszych mang.',
    'demon_slayer_anime_short_descr' => 'Kursory z Demon Slayer - dla prawdziwych nocnych łowców',
    'demon_slayer_anime' => 'Anime Demon Slayer',
    'bts_descr' => 'BTS to siedmioosobowy boysband spod szyldu BigHit Music. Zadebiutowali 13 czerwca 2013 roku singlem "No More Dream". W Japonii zadebiutowali 24 grudnia 2014 roku albumem studyjnym Wake Up.

Nazwa grupy pochodzi od koreańskiego wyrażenia Bangtan Sonyeondan, co oznacza "harcerzy nieprzepuszczających kul". Według J Hope\'a nazwa oznacza pragnienie zespołu, by blokować stereotypy, krytykę i oczekiwania skierowane do nastolatków jak kule.

Kolekcja kursorów poświęcona grupie zawiera wszystkich członków zespołu, tutaj kursor Kim Nam Joon (aka RM), kursor Kim Seok Jin (Jin), kursor Min Yoongi (Suga), kursor Jung Ho Suk (J-Hope), kursor Park Ji Min (Jimin), kursor Kim Tae Hyun (V) i kursor Jeon Jungkook (Jungkook).',
    'bts_short_descr' => 'Spotkaj się ze swoimi idolami dzięki kursorom BTS',
    'bts' => 'BTS',
    'miraculous_descr' => 'Miraculous: Biedronka i Czarny Kot, lepiej znane jako Miraculous: Biedronka i Czarny Kot, to przygody superbohaterów z kreskówki o dwójce uczniów, którzy pod maskami wcielają się w obrońców Paryża przed złoczyńcą, który w każdym odcinku wymyśla nowy sposób na zaszkodzenie miastu. Miraculous jest tworzone we Francji przy użyciu CGI i animacji. Miraculous to nie tylko serial animowany, ale także kolekcja komiksów wydawanych na całym świecie. Serial jest bardzo lubiany przez młodą widownię. 

Akcja rozgrywa się w Paryżu, gdzie Marinette i Adrien są uczniami liceum w nowoczesnej szkole. Otrzymali rolę zostania wybrańcami w walce ze złem, ratującymi swoje rodzinne miasto. Ich celem jest ochrona ludzi przed Akumami. Te małe stworzenia w postaci motyli potrafią zamieszkiwać człowieka i zamieniać go w złoczyńcę. 

Marinette może zmienić się w Biedronkę, a Adrien - w Czarnego Kota, ale co zaskakujące, pracując w parach, nie rozpoznają się nawzajem pod maskami superbohaterów. 

Pomóż Czarnemu Kotowi i Biedronce uratować Paryż z naszymi kursorami przedstawiającymi Twoje ulubione postacie. Którą postać wybierzesz dla kursora? Czy będzie to kursor Biedronki, a może urocza Tikki albo kursor Czarnego Kota? A może Królowa Pszczół z kursorami Rena Rouge? Wybór należy do Ciebie!',
    'miraculous_short_descr' => 'Dołącz do szeregów superbohaterów z kolekcją kursorów Biedronki i Czarnego Kota',
    'miraculous' => 'Miraculous: Biedronka i Czarny Kot',
    'talking_tom_descr' => 'Seria opowiada o codziennym życiu Gadającego Toma i jego przyjaciół. Tom i jego kujonowaty partner w interesach Ben nieustannie opracowują aplikacje mobilne i inne wynalazki, aby osiągnąć sławę i bogactwo i spróbować pokazać się światu, ale to zawsze kończy się niepowodzeniem. Dziewczyna Toma, Angela, stara się być piosenkarką, bez względu na to, co robi, aby to osiągnąć. Sąsiad Toma, Ginger, bardzo często wpada tu, żeby robić psikusy z psotą w zanadrzu. Głupi najlepszy przyjaciel i współlokator Hank siedzi w domu, ogląda BARDZO telewizję. A była dysydentka gwiazda pop Becca Sparkles została nową współlokatorką Angeli i wydaje się, że zakochała się w Hanku. Jednak bez względu na to, jak źle się sprawy mają, niezależnie od kształtów i rozmiarów, czy to zły dyrektor generalny, tajemniczy nowy sąsiad Toma, czy po prostu wypadek w nowym wynalazku Bena, gang będzie się dobrze bawił bez względu na wszystko i zawsze pamięta o jednej rzeczy, która ich trzyma razem: przyjaźń nigdy się nie kończy, tak jak nasza miłość do postaci z serii się nie kończy, więc teraz możesz ustawić sobie kursor Gadającego Toma lub kursor Bena, a może kursor Angeli, kursor Olivera!',
    'talking_tom_short_descr' => 'Porozmawiajmy o Twojej ulubionej postaci z kolekcji kursorów Talking Tom',
    'talking_tom' => 'Talking Tom and Friends',
    'lego_descr' => 'Firma The LEGO Group została założona w 1932 roku i liczyła wtedy zaledwie 7 osób. Celem zespołu Lego było tworzenie zabawek, które rozwijają kreatywność, wyobraźnię i pomysłowość dziecka. Niesamowitym faktem jest, że od momentu powstania w 1949 roku elementy LEGO we wszystkich wariantach pozostały ze sobą kompatybilne. Wszystkie przedmioty stworzone później są nadal kompatybilne z przedmiotami, które są wydawane dzisiaj, pomimo zmian w designie i kształcie na przestrzeni lat.

Klocki LEGO to podstawa, czyli pusty plastikowy klocek, który łączy się z innymi podobnymi klockami. Ale zestawy Lego zawierają również inne części, koła, figurki, platformy, a nawet obwody elektroniczne z czujnikami i silnikami elektrycznymi. Możesz zbierać modele samochodów, samolotów, pociągów, statków, budynków, robotów. LEGO trzyma się idei modułowości, co wyraźnie pokazuje dzieciom, jak rozwiązywać pewne problemy, rozwijać wyobraźnię, małą motorykę rąk i umiejętności składania. Klocki LEGO są wykonane z niesamowitą precyzją i idealnie do siebie pasują, co daje oszałamiającą precyzję 10 mikronów.

Ostatnio powstało wiele popularnych animowanych w 3D historii Lego, w których postacie z zestawów ożywają i stają się uczestnikami niesamowitych przygód. Jeśli chcesz fajny kursor, w naszej kolekcji Kursorów Lego znajdziesz wiele postaci z seriali telewizyjnych i filmów animowanych Lego. Kursor Lego Ninjago, Kursor Lego Batman, Kursor Lego Ninjago, Kursor Lego Wyldstyle i wiele innych.',
    'lego_short_descr' => 'Zbuduj swoją przeglądarkę marzeń z kolekcją kursorów Lego',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Po udanym finansowaniu na Kickstarterze, w 2017 roku, Team Cherry wydało wieloplatformową grę PC Hollow Knight. To historia bezimiennego rycerza i jego odkryć w owadzim królestwie Hallownest. Gra została słusznie uznana za jedną z najlepszych w gatunku metroidvania.

Rozgrywka w Hollow Knight opiera się na eksploracji świata gry. Pokonywanie przeszkód, rozwiązywanie zagadek i znajdowanie sekretów, a także walka z wrogami. Gracz ma unikalny zestaw ulepszeń i trików do eksploracji świata i walki w bitwach. Przechodząc z strefy do strefy, gracz pokonuje bossów i zdobywa niezbędne ulepszenia, aby przejść dalej. W rezultacie, gracze muszą odwiedzać już zaliczone obszary, aby znaleźć sekrety i przejść fabułę. I to także ekscytujące, ponieważ strefy zmieniają się za każdym razem, przynosząc nowe niespodzianki i doświadczenia. W grę można grać na różne sposoby, ponieważ istnieje kilka różnych ścieżek między strefami. Przechodząc przez fabułę, otwierasz mapę strefy, ale najpierw musisz zdobyć mapę.

Główną bronią bohatera jest gwóźdź, który jest nieco podobny do miecza, broń można ulepszać u kowala, a także uczyć się różnych umiejętności w posługiwaniu się bronią, co poszerza różnorodność ataków. Atakując wrogów, gromadzisz specjalny zasób, który można później wykorzystać do ulepszeń lub leczenia.
Miłej zabawy w Hollow Knight i nie zapomnij o naszych kursorach Hollow Knight z twoją ulubioną postacią. Nasza kolekcja zawiera Kursor Pan Grzyb, Kursor Quirrel, Kursor Igła Hornet, Kursor Stary Gwóźdź, Kursor Myla i inne.',
    'hollow-knight_short_descr' => 'Postaraj się nie zgubić w królestwie owadów, używając zestawu kursorów Hollow Knight',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman jest głównym bohaterem serialu. Stikmin, wcześniej bezimienny, zaczynał jako drobny złodziej, z pragnieniem szybkiego zarobku. Jednak po ucieczce z więzienia West Mesa, w jego życiu zachodzi wiele zmian i staje się sławnym przestępcą po kradzieży Tuniskiego Diamentu. Henry ma wybór - zostać skutecznym agentem rządowym, łowcą nagród, przywódcą organizacji przestępczej, cyborgiem lub kontynuować samodzielną drogę przestępczą. Gra zachwyca fanów gatunku wieloma przygodami i tajemnicami, a w naszej nowej kolekcji kursorów Henry Stickman znajdziesz zabawne postacie, w tym kursor Henry Stickmin, kursor Charles Calvin, kursor Reginald Copperbottom, kursor Prawa Ręka, kursor Ellie Rose i innych!',
    'henry-stickmin_short_descr' => 'Zaplanuj swoją ucieczkę od nudy z kolekcją kursorów Henry\'ego Stickmina',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'Bardzo popularna gra online Adopt Me została uruchomiona w 2017 roku i stała się najpopularniejsza na platformie do gier Roblox. Esencja gry jest bardzo prosta - zdobądź jajka ze zwierzakami i opiekuj się nimi.

Wirtualne zwierzaki dzielą się na 5 klas, niektóre z nich są bardzo rzadkie i drogie, podczas gdy inne są bardzo łatwe do zdobycia. Są to grupy Niepopularne, takie jak Niebieski Pies, Powszechne, Rzadkie kursory, na przykład kursor myszy Adopt Me Małpa, a także ultra-rzadkie, takie jak kursor Koala i Legendarne, kursor Smok i Zaakceptuj mnie jednorożec. Jeśli gracz ma cztery dorosłe zwierzaki tego samego typu, mogą one połączyć się w neonowego zwierzaka, takiego jak kursor gry Neon Horse lub Adopt Me Neon Rozgwiazda. Łącząc cztery zwykłe zwierzaki, możesz stworzyć neonowego zwierzaka, który naprawdę lśni, a z neonowych zwierzaków możesz stworzyć mega-neonowego zwierzaka.

Zakupy w grze Adopt Me! są realizowane z wirtualną walutą Roblox - tak zwanymi Robuxami, a gra ma również własną walutę - Bucks. Opiekując się swoim zwierzakiem, oprócz rozrywki, możesz zarobić bucksy, po prostu go nakarmić, położyć spać lub przeczytać bajkę, ogólnie rzecz biorąc, wiele ciekawych rzeczy.

Teraz fani gry Roblox "Adopt Me!" mogą ozdobić swój kursor gry ulubionym zwierzakiem!',
    'adopt-me_short_descr' => 'Baw się dobrze ze słodkimi zwierzakami w naszej kolekcji kursorów z gry Adopt Me!',
    'adopt-me' => 'Adopt Me!',
    'among-us_descr' => 'Among Us bazuje na słynnej grze fabularnej "Mafia". Planowano, że gra będzie dostępna tylko na urządzeniach mobilnych, ponieważ miała tylko jedną mapę. Gra szybko zyskała popularność. Później zespół deweloperski dodał tryb wieloosobowy, a w 2019 roku wydano dwie dodatkowe mapy.
Among Us to gra z perspektywy trzeciej osoby z góry, która pozwala graczowi poruszać się we wszystkich kierunkach. Od czterech do dziesięciu graczy może grać w jednej rundzie. Na początku gry każdemu zostaje potajemnie przydzielona rola zdrajcy lub członka załogi. Impostor (w rosyjskim tłumaczeniu "Zdrajca") może ukrywać się w włazach wentylacyjnych, sabotować i zabijać członków załogi. Jego celem jest zniszczenie wszystkich członków załogi lub zniszczenie statku kosmicznego przez sabotaż. Celem załogi statku jest rozwiązywanie różnych zagadek przygotowanych dla nich na początku gry. Jeśli każdy z członków załogi ukończy wszystkie zadania, zdrajcy przegrają. Ponadto załoga statku może odnieść zwycięstwo eliminując zdrajców podczas głosowania.
Zdrajcy mogą od czasu do czasu sabotować, a jeśli awarie nie zostaną naprawione w ciągu 30 sekund, załoga przegra. Przed rozpoczęciem gry możesz wybrać kolor postaci, dla której grasz, niebieski, czerwony, żółty, szary - cokolwiek! I nie zapomnij ustawić odpowiedniego kursora z nowej kolekcji Among Us!',
    'among-us_short_descr' => 'Nie daj się zwieść w tej zawiłej kosmicznej grze z kursorami Among Us',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Twórcą serialu "Steven Universe" była Rebecca Sugar. Jest ona znana z wcześniejszej pracy, jaką jest Pora na przygodę!. Pierwszy odcinek Steven Universe ukazał się na platformie wideo YouTube wiosną 2013 roku. Jesienią tego samego roku amerykański kanał Cartoon Network rozpoczął jego nadawanie dla swoich widzów. Od tego czasu wydano 6 sezonów. Szósty zapowiada się jako finałowy.
Jeśli chodzi o fabułę serialu animowanego, to krąży ona wokół drużyny Kryształowych Klejnotów. Składa się ona z kosmicznych stworzeń o charakterystycznych imionach: Perły, Ametyst i Granat. Jest w nim jeszcze jeden uczestnik, w roli którego występuje zwyczajny chłopiec, Stephen. Razem szukają potworów i starają się je zneutralizować, by nie zawładnęły Ziemią dla własnych korzyści. Przeciw nim stają Jasper i Peridot - wysłannicy z ich rodzinnej planety, którzy chcą pokonać Klejnoty i uruchomić Cluster.
Jeśli jesteś fanem Steven Universe i chcesz widzieć postacie z serialu animowanego gdzie tylko się da, zainstaluj rozszerzenie Cursor Style! Po co to robić? Możesz dodać kolekcję poświęconą "Steven Universe" i zamienić standardowy wskaźnik myszy w jedną z ulubionych postaci.',
    'steven_universe_short_descr' => 'Odkryj sekret klejnotów z kursorami Steven Universe',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Animowany sitcom o nazwie "Family Guy" w całej historii swojego istnienia 4 razy zdobył nagrodę Emmy i 3 razy "Annie". Serial animowany wyśmiewa bolesne tematy amerykańskiego społeczeństwa, takie jak: feminizm, niewolnictwo, otyłość, polityka itp. W przeciwieństwie do innych dzieł, tutaj używane są wstawki z żartami i sarkazmem. Co więcej, w wielu przypadkach nie są one zintegrowane z fabułą, ale istnieją same w sobie.
Jeden odcinek serialu animowanego powstaje ponad 10 miesięcy. Dlaczego tak długo? Ponieważ cała animacja jest rysowana ręcznie. Z tego powodu część wydarzeń poruszanych w dziele ma czas, by stracić na aktualności. Mimo to sitcom pozostaje bardzo interesujący i zyskuje uznanie widzów na całym świecie. W końcu, kto nie lubi dobrze pośmiać się z polityków, celebrytów lub ludzi, którzy popełniają dzikie wybryki i tym samym zadziwiają, a nawet szokują zwykłych ludzi.
Lubisz "Family Guy"? Masz niepowtarzalną okazję, aby zamienić normalny kursor myszy w dowolną z postaci tego serialu animowanego! Co muszę zrobić? Wystarczy zainstalować rozszerzenie przeglądarki “Cursor Style”, dodać do niego kolekcję poświęconą “Family Guy” i cieszyć się wspaniałą reinkarnacją!',
    'family_guy_short_descr' => 'Kolekcja kursorów Family Guy dla koneserów specyficznego humoru',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Na pewno słyszałeś wyrażenie "Piękno ocali świat"? Zatem wiele osób, zwłaszcza dziewczyn, zgadza się z tym stwierdzeniem. Dlatego starają się otaczać wszystkim, co najpiękniejsze i przyjemne dla oka. Mogą to być różowe tapety w sypialni, miękkie zabawki, poduszki haftowane koralikami, cenna biżuteria itp. Z zewnątrz wszystko wygląda bardzo uroczo, a nawet trochę dziecinnie. Ale każdy z nas jest w głębi serca małym dzieckiem, więc dlaczego nie pozwolić mu pokazać naszej wyobraźni?
Czułość w nas może wywołać wiele rzeczy. Na przykład współczujące oczy kotka, który chce być pogłaskany lub nakarmiony. Wielokolorowa tęcza, wyglądająca po wiosennym deszczu i mieniąca się wszystkimi kolorami w słońcu. Dziecko, które poczęstowano czekoladą i postanowiło podzielić się nią z dziewczyną lub chłopakiem. Powodów do wzruszeń jest całkiem sporo i postanowiliśmy użyć ich jako kursorów.
Masz dość nudnej białej strzałki w swojej przeglądarce? Zastąp ją czymś uroczym z naszej kolekcji! Na przykład różowym i białym jednorożcem, smutnym pomidorem, ponurą chmurą, kolczastym kaktusem w kształcie kota lub czymkolwiek innym chcesz. Wszystko, co musisz zrobić, to zainstalować rozszerzenie Cursor Style i dodać do niego kolekcję uroczych kursorów. I niech żyje zbawca świata - piękno!',
    'cute_cursors_short_descr' => 'Świat będzie milszy z kolekcją uroczych kursorów',
    'cute_cursors' => 'Urocze Kursory',
    'web_media_descr' => 'We współczesnych realiach prawie każdy korzysta z Internetu. Począwszy od małych dzieci, a skończywszy na emerytach. Jedni surfują, korzystając z przeglądarki, inni oglądają filmy na YouTube, a jeszcze inni potrzebują sieci do komunikacji z bliskimi. Żaden z tych użytkowników nie wyobraża sobie dnia bez World Wide Web.
Osoby starsze często siedzą w sieciach społecznościowych, takich jak Facebook czy VK. Często komunikują się także ze swoimi dziećmi i wnukami na Skype. Jest to szczególnie wygodne, jeśli dzieci i rodzice mieszkają w różnych miastach, a nawet krajach.
Młodzi ludzie wolą komunikować się za pośrednictwem Viber lub Telegram, przesyłać zdjęcia na Instagram, śmiać się z memów na FB. Filmy z reakcjami ludzi na YouTube zyskują miliony wyświetleń, podobnie jak różne dowcipy czy eksperymenty społeczne. Na Tik-Toku setki tysięcy ludzi tańczą, pokazują sztuczki magiczne i wyrażają siebie.
Interesuje Cię lub po prostu często korzystasz z jakiegoś rodzaju zasobów ze sfery web media? Chcesz pozbyć się nudnej strzałki myszy w swojej przeglądarce? Następnie zainstaluj rozszerzenie i zmień domyślny kursor na nasz kreatywny! Może to być kursor YouTube, kursor Viber, kursor Google Chrome lub inne zasoby.',
    'web_media_short_descr' => 'Żyj w nowoczesnym rytmie z kolekcją kursorów mediów internetowych',
    'web_media' => 'Media internetowe',
    'bobs_burgers_descr' => 'Serial animowany Bob\'s Burgers to fabuła animacji i charyzma postaci. I, sądząc po nominacji do nagrody Emmy i uznaniu dzieła za jedną z najlepszych kreskówek na całym świecie, Bob\'s Snack naprawdę zrobił furorę.
Fabuła serialu animowanego obraca się wokół rodziny Boba Belchera. Ten człowiek jest właścicielem jadłodajni na parterze, a na drugim piętrze mieszka z bliskimi. Bob ma wesołą żonę Lindę i 3 dzieci: Gene\'a, Louise i Tinę. Chłopiec marzy o karierze muzycznej, najstarsza córka Tina jest bardzo miła, ale niezręczna, a najmłodsza - Louise wciąż jest szelmem i często stawia swoją rodzinę w niezręcznej sytuacji. Głównym konkurentem Bob\'s Burgers jest Pizzeria Jimmy\'ego Pesto. Jak można się domyślić, właściciel tej pizzerii nazywa się Jim i on oraz Bob nienawidzą się nawzajem. Wszystko to zostało pokazane tak, aby wyglądało komicznie, a nie poważnie. Dlatego wiele z ich potyczek wywołuje tylko uśmiech.
Jeśli kochasz serial animowany „Bob\'s Burgers” i chcesz widzieć jego bohaterów nie tylko na ekranie monitora lub telewizora, zainstaluj rozszerzenie, dodaj kolekcję i zmień kursor myszy w przeglądarce na którąkolwiek z postaci z tej kreskówki!',
    'bobs_burgers_short_descr' => 'Bob robi burgery, a my robimy kursory Bob\'s Burgers',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'Historia gry wideo "Kirby" rozpoczęła się już w latach 90. ubiegłego wieku. Składa się z wielu serii, które zostały opracowane przez Nintendo i HAL Laboratory. Gra jest przeznaczona dla dzieci od półtora roku do 8 lat. O jej popularności można sądzić po liczbie sprzedanych egzemplarzy. Ponad 34 miliony na całym świecie.
Głównym bohaterem Kirby\'ego jest tytułowa różowa istota. Mieszka na planecie o nazwie Pop Star i okresowo chroni ją przed różnymi niebezpieczeństwami. Kirby potrafi wciągać niektóre przedmioty i swoich wrogów, aby następnie uczyć się ich umiejętności: walki wręcz, władania mieczem, zionienia ogniem itp. Jednak różowy pęcherz nie tylko walczy z wrogami, ale także rozwiązuje różne zagadki, podróżuje do innych krajów, a nawet potrafi latać na poziomie.
W tę grę wideo można grać na konsolach Nintendo lub Game Boy. We wszystkich seriach występują uroczy bohaterowie, dobra grafika i zabawne ścieżki dźwiękowe. Nawiasem mówiąc, przez prawie 30 lat od wydania pierwszej wersji, świat zdołał zobaczyć 20 serii Kirby\'ego. Ten wskaźnik, w połączeniu z wielomilionowym wolumenem sprzedanych egzemplarzy, pomógł grze znaleźć się w TOP 50 najbardziej udanych i poszukiwanych gier wideo w branży gier.
Kochasz Kirby\'ego tak bardzo, że chciałbyś widzieć tę postać gdziekolwiek to możliwe? Następnie użyj kolekcji Kirby i zamień zwykły wskaźnik myszy w główną postać swojej ulubionej gry wideo! Jesteśmy pewni, że spodoba ci się nowy wygląd kursora.',
    'kirby_short_descr' => 'Spróbuj wchłonąć całą kolekcję kursorów Kirby\'ego.',
    'kirby' => 'Kirby',
    'undertale_descr' => 'W dawnych czasach Ziemia była zamieszkana nie tylko przez ludzi, ale także przez potwory. Z powodu nieporozumień między nimi wybuchła wojna, która zakończyła się zwycięstwem rasy ludzkiej. Siedmiu magów zapędziło potwory pod ziemię i uwięziło je tam na zawsze zaklęciem bariery. Jednak istniało tylko jedno wejście na Górę Ebott, z którego skorzystało dziecko. To właśnie nim będziesz grać, uruchamiając grę komputerową Undertale.
Ta gra została opracowana przez Toby Foxa - znanego programistę ze Stanów Zjednoczonych. Początkowo mogli się nią cieszyć właściciele komputerów osobistych z systemem Microsoft Windows i Linux OS, a następnie przyszła kolej na użytkowników konsol do gier.
Na czym polega ta gra? Chłopiec podróżuje przez podziemia zamieszkane przez potwory. Niektóre z nich od razu są wrogo nastawione, podczas gdy inne lubią rozmawiać. Gracz może wybrać jedno z 2 zachowań: unikać przemocy lub walczyć. W pierwszym przypadku przejście gry będzie łatwiejsze, w drugim - wręcz przeciwnie, trudniejsze. Fabuła i zakończenie, które mogą się rozgałęziać i zmieniać, zależą również od tego wyboru.
Jeśli lubisz Underground Tale i chciałbyś zobaczyć jego postacie w swojej przeglądarce, zainstaluj rozszerzenie i dodaj odpowiednią kolekcję kursorów! Zmień nudny wskaźnik myszy w jednego z potworów lub głównego bohatera Undertale!',
    'undertale_short_descr' => 'Czas wydostać się z dziury, używając kursorów z gry Undertale',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune to gra fabularna wydana na komputery kilka lat temu. Została stworzona przez tego samego programistę, który opracował Undertale. Jednak te dwie gry prawie się od siebie nie różnią, mimo że mają kilka wspólnych postaci i lokacji.
W Delta Rune jest kilka głównych postaci. Jest to uczeń Chris, którym można sterować, i urocza potworzyca Susie, nie do opanowania. Obie postaci wpadają do świata ciemności, gdzie spotykają jednego z jego mieszkańców - Ralsaya. Mówi im, że tak naprawdę są stworzeniami światła, które mają misję - powstrzymać przepływ ciemnej energii w ponurym świecie. Aby to zrobić, muszą oszczędzać lokalne potwory i starać się nie wdawać z nimi w bitwy, chociaż czasami jest to dość trudne.
Gracz ma prosty wybór: albo oszczędzić mroczne stworzenia, albo je zaatakować. Ponieważ Susie nie jest fanką półśrodków, w wielu przypadkach wybiera bitwę. Dlatego Chris nie ma innego wyjścia, jak tylko wesprzeć swoją dziewczynę i pomóc jej w bitwach.
Kochasz grę Deltarune? Następnie wystylizuj kursor myszy w przeglądarce dla jednej z jej postaci! Możesz to zrobić za pomocą naszego rozszerzenia. Zainstaluj je, dodaj kolekcję „Rune Delta” i aktywuj! Teraz twoja strzałka przestała być taka jak wszyscy inni i stała się Chrisem, Susie lub jednym ze stworzeń ciemnego świata.',
    'deltarune_short_descr' => 'Zanurz się w mrocznym świecie z tą kolekcją kursorów',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario to seria gier komputerowych wydanych przez Nintendo. Pierwsza i najpopularniejsza gra nazywała się Super Mario Bros. Zobaczyła światło dzienne w 1985 roku. Później została wpisana do Księgi Rekordów Guinnessa. Od tego czasu wydano ponad 20 gier, z których każda ma własną fabułę. W 2019 roku pojawiła się nowa wersja o nazwie Super Mario Maker 2. Pomimo ulepszenia grafiki, styl i postacie pozostały takie same, co budzi nostalgię za Super Mario z lat 80.
Bohaterem jest wciąż hydraulik Mario. W fabule ostatniej wariacji gry zamek Księżniczki nie miał kamienia na kamieniu. Mario musi go odbudować, zarabiając wcześniej monety, które są mu płacone za zadania. W sumie ta gra ma ponad 100 poziomów o różnym stopniu trudności z możliwością modyfikacji. Również w Super Mario Maker 2 istnieją nowe tryby gry. Możesz grać w cztery z nich naraz i gdy jeden się skończy, poziom jest uważany za ukończony. Istnieją również takie tryby jak: Mario Marathon, Pojedynek i wyścigi Ninjki.
Uwielbiasz Super Mario i wszystko, co związane z tą wspaniałą grą? Ustaw więc kursory wykonane w stylu tej platformówki! Jesteśmy pewni, że spodoba ci się kursor Mario, kursor Luigi, kursor Księżniczki Peach i inne kursory, które są prezentowane w naszej kolekcji!',
    'super_mario_short_descr' => 'Przejdź przez Grzybowe Królestwo z kolekcją kursorów Super Mario',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Wodospady Grawitacji zostały stworzone wspólnie przez Disney Television Animation Corporation i Alexa Hirscha. Premiera miała miejsce w 2012 roku i była emitowana na kanale Disney Channel. Cały pierwszy sezon serialu animowanego był tam nadawany. Dwa lata później ukazał się drugi sezon, który widzowie mogli oglądać na poprzednim kanale i na Disney XD. Niestety, fani Wodospadów Grawitacji nie doczekali się trzeciego i kolejnych sezonów. Twórcy zdecydowali się ograniczyć do dwóch sezonów bez żadnych sequeli.
Jeśli chodzi o fabułę tego animowanego obrazu, to cała akcja rozgrywa się w fikcyjnym mieście o nazwie Wodospady Grawitacji (Gravity Falls). Przyjeżdżają tam bliźniaki, którzy nazywają się Mabel i Dipper. Zatrzymują się u swojego kuzyna Stana. Ma on własny sklep z pamiątkami turystycznymi. Kiedy rodzeństwo nudzi się "nierobieniem niczego", wyruszają w poszukiwaniu przygód. Jeden z nich znajduje w lesie dziwny dziennik, który opowiada o anomaliach tego miasteczka. Bliźniaki wyruszają na poszukiwanie jego autora i spotykają niezwykłe stworzenia i miejsca. Jeśli interesuje Cię ta animowana seria i kiedyś byłeś fanem jej postaci, polecamy Ci naszą kolekcję kursorów myszy w stylu Wodospadów Grawitacji!',
    'gravity_falls_short_descr' => 'Wyrusz na przygodę z kursorami ze Wodogrzmotów Małych',
    'gravity_falls' => 'Wodogrzmoty Małe',
    'simpsons_descr' => 'Absolutnie wszyscy słyszeli o tak znanym serialu animowanym jak Simpsonowie. Nawet ci, którzy nigdy tego nie oglądali, wiedzą o istnieniu żółtych postaci. Fani cieszą się, gdy wychodzi kolejny sezon ich ulubionej kreskówki. Nawiasem mówiąc, jesienią 2019 roku ukazało się 31 sezonów. A pierwszy pojawił się na ekranach telewizorów w 1989 roku. Fox zaczął go pokazywać i nadal to robi ze względu na wysokie wyniki oglądalności i sympatię widowni.
Simpsonowie to gatunek satyryczny, który porusza aktualne tematy. Może to być styl życia przeciętnego Amerykanina, kwestie polityczne i religijne, "gwiazdorskie" sztuczki celebrytów, feminizm, małżeństwa osób tej samej płci. Ogólnie rzecz biorąc, wszystko, co związane z wydarzeniami lokalnymi i globalnymi, w których uczestniczą Stany Zjednoczone.
Akcja serialu animowanego rozgrywa się w nieistniejącym miasteczku Springfield. W rzeczywistości w Ameryce jest wiele miast o tej nazwie. Być może dlatego właśnie zostało to wybrane, aby widzowie nie kojarzyli tego, co dzieje się na ekranach, z konkretną miejscowością, ale jedynie domyślali się, gdzie to może być.
Najprawdopodobniej jesteś fanem Simpsonów. W przeciwnym razie, dlaczego miałbyś czytać ten tekst do końca? A jeśli tak, to masz okazję zmienić znudzony kursor myszy na wskaźnik, który jest wykonany w stylu tego serialu animowanego.',
    'simpsons_short_descr' => 'Zabawna mała rodzina z kursorami Simpsonów',
    'simpsons' => 'Simpsonowie',
    'youtubers_descr' => 'Platforma wideo YouTube pojawiła się w 2005 roku. Początkowo filmy publikowano tam tylko w celu autoekspresji lub informowania o czymś. Z czasem jednak wszystko to przerodziło się w dochodowy biznes, który przynosi tysiące, a czasami miliony dolarów miesięcznie odnoszącym sukcesy użytkownikom YouTube. Im bardziej popularny vloger (osoba prowadząca vloga), tym więcej może zarobić dzięki swojemu kanałowi.
Ile zarabia pięcioletnia dziewczynka vlogerka, której rodzice zabierają ją do najciekawszych atrakcji i kręcą to, co się dzieje na kamerze? To po prostu jak dziecko bawi się w parkach dla dzieci, co wyraża emocje, jak się wygłupia i tym podobne. Kwota jest naprawdę niesamowita - dziś kanał dziecka zyskał prawie 47 milionów subskrybentów i zaczął generować dochód w wysokości 5 milionów rubli miesięcznie.
Ktoś przesyła filmy, w których omawia gry komputerowe, ktoś robi beatbox lub organizuje żarty dla przechodniów na ulicy. Niektórzy poświęcają swoje filmy wrażliwym tematom, takim jak relacje między mężczyznami i kobietami. Im bardziej użytkownicy YouTube lubią te ujęcia, tym większa popularność vlogera.
Kolekcja dodała już kursor PewDiePie, kursor Shane Dawson, kursor Ray William Johnson, kursor Zoella, kursor MyLifeAsEva i inne.',
    'youtubers_short_descr' => 'Nowa generacja gwiazd jest zawsze online w naszej kolekcji YouTubers',
    'youtubers' => 'YouTubersi',
    'pusheen_descr' => 'Prawie wszyscy znają kota Pusheen. Mimo że jest tylko postacią z dziecięcego komiksu wymyślonego 10 lat temu, ma dziś miliony fanów. Kot Pusheen pojawił się jako ilustracja stworzona przez artystkę Claire Belton.
Rok później kot zyskał własną stronę na Tumblr.com i w ciągu kilku tygodni zyskał całą armię fanów - około 10 000 osób. W 2013 roku Facebook chciał włączyć obrazy z Pushin do kolekcji z innymi emotikonami. Po negocjacjach z twórcą, pomysł ten został wprowadzony w życie i „rozsadził” Internet! Zdjęcia z kota Pusheen są używane w korespondencji ponad 10 milionów razy dziennie!
W 2014 roku jeden z największych producentów zabawek w Stanach Zjednoczonych zwrócił uwagę na tę postać. GUND (to ona wymyśliła misie) wprowadziła na rynek parę modeli Pushin. Ponieważ sukces był ogromny, po kilku miesiącach powstała pełna kolekcja zabawek w postaci tego kota.
Gdzie jeszcze można spotkać kota Pusheen? W zestawach prezentowych od Isaac Morris Ltd, w piankach od Boomf i oczywiście w naszej kolekcji kursorów Pusheen!',
    'pusheen_short_descr' => 'Dodaj trochę komfortu w swojej przeglądarce z kolekcją kursorów Pusheen',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'Pierwsza seria animacji „Rick i Morty” została wydana w 2013 roku. Ta kreskówka może być bezpośrednio przypisana do 2 gatunków: science fiction i komedii. Jej twórcami byli Dan Harmon i Justin Royland. Początkowo wszystkie serie były pokazywane na kanale Cartoon Network, a dopiero potem powielane w kinach online i hostingach wideo. Co kilka lat wydawane są nowe sezony Ricka i Morty\'ego, a w listopadzie 2019 roku ukazał się czwarty sezon, który okazał się nie mniej interesujący niż poprzednie. Fabuła serialu animowanego obraca się wokół geniusza i jednocześnie szalonego naukowca o imieniu Rick, a także jego niepozornego wnuka - Morty\'ego. Obie te postacie łączy wspólna przygoda w najbardziej niezwykłych miejscach. Dostają się tam na latającym spodku, zdolnym do poruszania się przez tunel międzyprzestrzenny. Jak się domyślacie, ten serial animowany jest trochę podobny do filmu Powrót do przyszłości, ale jednak nie jest jego animowaną wersją. Został jednak pochlebnie oceniony przez wielu krytyków za humorystyczne odcinki, kreatywność i oryginalność. Chcesz zobaczyć Ricka lub Morty\'ego nie tylko w serialu tego dzieła, ale także w przeglądarce? Jeśli tak, zainstaluj rozszerzenie i dodaj naszą kolekcję poświęconą Twojej ulubionej kreskówce! Oto kursor Ricka Sancheza, kursor Morty\'ego Smitha, kursor Portal Gun i oczywiście kursor Mr. Meeseeks.',
    'rick_and_morty_short_descr' => 'Przestań marudzić, po prostu użyj kursorów z kolekcji Rick and Morty',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Fanów baseballu można spotkać na całym świecie. Dotyczy to zwłaszcza mieszkańców takich krajów jak: USA, Chiny, Kuba, Korea Południowa, Japonia i Wenezuela. Wbrew obiegowej opinii, baseball nie powstał w Ameryce, ale w Anglii. Pierwsza wzmianka i opis baseballu pojawiły się w odległym 1744 roku, w angielskim wydaniu. Po 145 latach Amerykanie przywłaszczyli sobie ten wynalazek, pomimo faktów.
National League została utworzona w 1876 roku. Jest częścią Major League w Kanadzie i Stanach Zjednoczonych. Obecnie w National Baseball League występuje 15 drużyn. W końcowej części każdego sezonu nadchodzi pora play-off, w których bierze udział 4 najlepsze drużyny. Tak więc wyłaniany jest zwycięzca całej National League. Następnie zwycięska drużyna otrzymuje możliwość gry przeciwko zwycięzcy z American League w World Series.
Interesujesz się baseballem, a może kibicujesz którejś z drużyn? Oddaj hołd swojej ulubionej drużynie, ustawiając kursory myszy w postaci jej atrybutów! Zmień nudny wygląd wskaźnika w przeglądarce na znajomą tożsamość korporacyjną baseballu! Zamień strzałkę w kij lub kask zawodnika w którejkolwiek z drużyn National League, które obejmują już kursor New York Yankees, kursor Great Falls Dodgers, kursor Boston Red Sox, kursor Baltimore Orioles, kursor Oakland Athletics.',
    'mlb_teams_short_descr' => 'Kolekcja kursorów drużyn MLB dla wszystkich naszych fanów.',
    'mlb_teams' => 'Drużyny MLB',
    'brawl_stars_descr' => 'Brawl Stars to gra mobilna z gatunku MOBA od Supercell. Pomimo premiery pod koniec 2018 roku, gra zyskała ogromną popularność, głównie dzięki obfitości trybów walki i barwnym, fantastycznym bohaterom - Brawlerom. Gracz ma w czym wybierać - 32 unikalne postacie, z których każda ma własny zestaw umiejętności i zdolności. Każdy bohater ma również własną umiejętność pasywną, która jest dostępna poprzez skrzynie z łupami. Gracze mogą walczyć w kilku trybach, na przykład w "Nagroda za zdobycie" - wygrywa jeden z dwóch zespołów, który zebrał więcej gwiazd, zabijając przeciwników. W trybie "napad" konieczne jest rozbicie sejfów przeciwników, jednocześnie zabezpieczając własne. Ciekawy tryb "Gem Grab" - zwycięża drużyna, która zbierze najwięcej klejnotów. Cóż, w trybie "Starcie" 10 graczy walczy ze sobą na mapie, gdzie granice są zmniejszane z powodu trującego obłoku. Gra obfituje w kolorowy design, który wielu osobom się podoba, w tym nam, co zainspirowało nas do stworzenia osobnej kolekcji kursorów Brawl Stars. Dostępne są kursory Brawl Stars Shelley, Barley, Penny, Frank, Mortis i inne.',
    'brawl_stars_short_descr' => 'Wybierz kursory z Brawl Stars i rozpocznij bitwę',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Zmień kursor myszy w dwóch kliknięciach! Darmowe kolekcje na każdy gust.',
    'all_descr' => 'Jeśli kiedykolwiek myślałeś o tym, jak zmienić nudny kursor myszy, to nasze kolekcje kursorów są dla Ciebie! Tutaj znajdziesz fajnych bohaterów komiksów, piękne kursory dla graczy z postaciami z popularnych gier, zabawne zestawy kursorów do żartów, kolorowe kursory i wiele innych ciekawych opcji.',
    'text_title' => 'Fajne i najśmieszniejsze kolekcje kursorów na każdy dzień',
    'text_allcat_title' => 'Unikalne i kreatywne kursory myszki, które pasują do każdego nastroju',
    'text_1' => 'Nie chcesz być jak wszyscy inni? A może po prostu kochasz wszystko niezwykłe? Chcesz być częścią swojego ulubionego bohatera z gry lub postaci z kreskówki? Trafiłeś we właściwe miejsce. Tutaj znajdziesz jasne, niezwykłe zestawy kursorów, które mogą zastąpić znany i już dość nudny biały grot. Kursor myszy towarzyszy nam cały dzień w pracy i nauce, więc powinien dawać świetny nastrój i nastawić pozytywnie.',
    'text_2' => 'Tutaj znajdziesz kursory dla graczy i miłośników filmów, piękne kursory oparte na Twoich ulubionych kreskówkach i motywach sportowych dla najbardziej aktywnych osób. Lubisz komiksy lub nie wyobrażasz sobie dnia bez zabawnych memów? Uwielbiasz zwierzęta lub marzysz o odwiedzeniu wszystkich krajów świata? Wszystko jest proste - mamy odpowiedni obraz kursora również dla Ciebie. Możesz także wybrać obrazy w zależności od tego, z czym pracujesz. Na przykład, czarny kursor będzie znacznie wygodniejszy niż biały podczas pracy z dokumentami lub rysunkami, a kursor w kształcie dłoni będzie wygodniejszy, jeśli musisz pracować z małymi elementami graficznymi. Wybierz swój ulubiony obraz, dostosuj jego rozmiar bezpośrednio w rozszerzeniu - i używaj go z przyjemnością, każdego dnia zaczynając z pozytywnym nastawieniem!',
    'install_to_preview' => 'Zainstaluj rozszerzenie, aby wyświetlić podgląd',
    'install' => 'Zainstaluj',
    'add_button' => 'Dodaj',
    'preview_button' => 'Podgląd',
    'added_button' => 'Dodano',
    'add_cursor' => 'Dodaj kursor',
    'to_your_collection' => 'do twojej kolekcji',
    'prev_text_1' => 'Podgląd na pełnym ekranie',
    'prev_text_2' => 'kursora',
    'cursor' => 'kursor',
    'pointer' => 'wskaźnik',
    'a_title_1' => 'Cursor Style - Fajne kursory do Twojej przeglądarki',
    'a_title_2' => 'Fajne kolekcje tematycznych kursorów',
    'mouse_cursors' => 'kursory myszy',
    'cursor_collection' => 'Kolekcja kursorów',
    'sborka_cursorov' => 'kolekcja kursorów',
    'collection_list_from_colllection' => 'Lista kursorów - ',
    'christmas' => 'Boże Narodzenie',
    'nhl_teams' => 'National Hockey League',
    'neon' => 'Neon',
    'adventure_time' => 'Pora na Przygodę!',
    'nba_teams' => 'National Basketball Association',
    'spongebob' => 'SpongeBob',
    'phineas_and_ferb' => 'Fineasz i Ferb',
    'fortnite_chapter_2' => 'Fortnite Rozdział 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Znane Osobistości',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Komiksy',
    'igry' => 'Gry',
    'multfilmy' => 'Kreskówki',
    'kino_i_serialy' => 'Filmy i seriale',
    'anime' => 'Anime',
    'futbol' => 'Piłka nożna',
    'avtomobili' => 'Samochody',
    'memy' => 'Memy',
    'emodji' => 'Emoji',
    'pitomcy' => 'Zwierzęta domowe',
    'stil_i_krasota' => 'Moda i styl',
    'prazdniki' => 'Święta',
    'flagi' => 'Flagi',
    'vokrug_sveta' => 'Dookoła świata',
    'eda_i_napitki' => 'Jedzenie i napoje',
    'cvetnye' => 'Kolorowe',
    'prank' => 'Żarty',
    'startovyj_nabor' => 'Zestaw startowy',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Mikołaj pokocha Twoje bożonarodzeniowe kursory',
    'nhl_teams_short_descr' => 'Kolekcja kursorów NHL dla prawdziwych fanów',
    'neon_short_descr' => 'Dodaj jasności z neonową kolekcją',
    'adventure_time_short_descr' => 'Nauka matematyki z kolekcją kursorów Adventure Time',
    'nba_teams_short_descr' => 'Kursory NBA jako symbol wielkich zwycięstw koszykówki',
    'spongebob_short_descr' => 'Dowiedz się, kto mieszka na dnie oceanu z kolekcją kursorów SpongeBob',
    'phineas_and_ferb_short_descr' => 'Z pewnością nie będziesz się nudzić z kolekcją kursorów z Fineasza i Ferba',
    'fortnite_chapter_2_short_descr' => 'Nowy rozdział kultowej gry Fortnite',
    'pokemon_short_descr' => 'Złap je wszystkie, jeśli potrafisz',
    'famous_people_short_descr' => 'Zainspiruj się kursorem swojego idola',
    'the_elder_scrools_short_descr' => 'Zanurz się w świecie rycerzy i smoków',
    'halloween_short_descr' => 'Bój się przegapić nową kolekcję Halloween',
    'nfl_teams_short_descr' => 'Dla prawdziwych fanów futbolu amerykańskiego',
    'five_nights_at_freddy_short_descr' => 'Spróbuj się nie przestraszyć tych animatroników.',
    'komiksy_short_descr' => 'Kursory z komiksów: wybierz swój dzisiejszy nastrój.',
    'igry_short_descr' => 'Wirtualna rzeczywistość: w kogo dzisiaj grasz?',
    'multfilmy_short_descr' => 'Ulubione postacie z kreskówek w nowym designie',
    'kino_i_serialy_short_descr' => 'Władca Kursora: Drużyna z Pulpitu',
    'anime_short_descr' => 'Wszyscy kochają anime: która postać jest Twoją ulubioną?',
    'futbol_short_descr' => 'Jesteś prawdziwym fanem sportu? W takim razie musisz tu być',
    'avtomobili_short_descr' => 'Samochód twoich marzeń: duża flota dla profesjonalistów',
    'memy_short_descr' => 'Ulubione motywy: Kolekcja kursorów z memami',
    'emodji_short_descr' => 'Pokaż innym swój prawdziwy nastrój - ustaw Kursacji!',
    'pitomcy_short_descr' => 'Jasne kursory dla wszystkich miłośników naszych mniejszych braci',
    'stil_i_krasota_short_descr' => 'Oryginalne kursory na każdą okazję',
    'prazdniki_short_descr' => 'Co jest w kalendarzu? Nowa Kolekcja Kursorów Świątecznych!',
    'flagi_short_descr' => 'Szukasz przygody: gdzie idziemy dzisiaj?',
    'vokrug_sveta_short_descr' => 'W mgnieniu oka dookoła świata: dokąd dziś się wybieramy?',
    'eda_i_napitki_short_descr' => 'Pyszne kursory dla kreatywności',
    'cvetnye_short_descr' => 'Pomaluj swoje życie jasnymi kolorami i odważnymi pociągnięciami',
    'prank_short_descr' => 'Zestaw kursorów dla najzabawniejszych żartów',
    'startovyj_nabor_short_descr' => 'Nowe spojrzenie na znane rzeczy: zaktualizowana seria kursorów',
    'fortnite_short_descr' => 'Śledź streamerów!',
    'dota_2_short_descr' => 'Uczyń swój wirtualny świat prawdziwym!',
    'minecraft_short_descr' => 'Postacie z twojej ulubionej gry zawsze w pobliżu',
    'christmas_descr' => 'Każdy z nas niewątpliwie czeka na najbardziej popularne święto - Boże Narodzenie. Wszyscy chrześcijanie na całym świecie tradycyjnie obchodzą je każdego roku, 25 grudnia. Czas, kiedy rodziny zbierają się przy jednym stole, dzielą się radością i miłością i wymieniają prezentami. Na długo przed Bożym Narodzeniem ludzie dekorują ulice jasnymi girlandami, a swoje domy tradycyjnymi atrybutami. Trudno znaleźć osobę, która nie lubi Bożego Narodzenia - wesołego i tajemniczego święta, ponieważ towarzyszy mu wiele tradycji i rytuałów, które przywracają nas do korzeni całej naszej rodziny. W wigilię Bożego Narodzenia dosłownie wszystko jest nasycone jego duchem, od malowanych pierników po wzruszające pieśni. Elegancka choinka i prezenty pod nią, radość znana każdemu z nas z dzieciństwa. Chcemy dołączyć do tego magicznego święta i, kto wie, może Święty Mikołaj przygotuje dla Ciebie specjalny prezent, jeśli ozdobisz swój kursor naszą bożonarodzeniową kolekcją. Jest tu wszystko, czego potrzebujesz, kursor Świętego Mikołaja, kursor choinki, kursor piernika, kursor bałwana, a nawet kursor torby z prezentami. Wesołych Świąt!',
    'nhl_teams_descr' => 'National Hockey League zostało założone w 1917 roku - jest to profesjonalna organizacja sportowa, która łączy kluby hokejowe z USA i Kanady. I jest to jedna z pierwszych profesjonalnych lig hokejowych na świecie. NHL jest jedną z wiodących lig sportowych w Ameryce Północnej, obok NFL, NBA, Major League Baseball i MLS. Co roku 31 drużyn z 30 miast w USA i Kanadzie walczy o główne trofeum - Puchar Stanleya, a drużyna, która zdobyła najwięcej punktów w sezonie zasadniczym, otrzymuje Puchar Prezydencki. Nadszedł czas, aby uczcić tę wspaniałą grę, tworząc kolekcję kursorów NHL. Jeśli również lubisz hokej, kibicuj swojemu ulubionemu klubowi lub sam uczestnicz w tym sporcie, po prostu zmień kursor i nie rozstawaj się ze swoją ulubioną drużyną, w tym z kursorem Boston Bruins, kursorem St. Louis Blues, kursorem Columbus Blue Jackets, kursorem Tampa Bay Lightning, kursorem Dallas Stars i innymi klubami godnymi szczerego szacunku.',
    'neon_descr' => 'Stworzyliśmy unikalną kolekcję neonowych kursorów, aby dodać różnorodności do codziennego surfowania po internecie i dodać trochę jasności do hipnotyzujących neonów. Niech ich bogate kolory stworzą otaczającą atmosferę miasta w nocy, dają inspirację do tworzenia czegoś nowego. We współczesnym świecie światła metropolii zawsze zapowiadają nadejście nocy, podążają za nami na każdej ulicy, a ten blask jest wypełniony energią. Niech towarzyszy temu również świecący kursor w kształcie loda, pyszny kursor hot doga, soczysty kursor burgera, błyszczący kursor diamentu i inne kursory z nowej neonowej kolekcji.',
    'adventure_time_descr' => '"Pora na Przygodę!" to kreskówka fantastycznej proweniencji, w której akcja rozgrywa się w świecie, który przeżył apokalipsę. Terytorium to nazywane jest Ziemią Ooo, która do niedawna była areną wojny nuklearnej. Ale to wszystko już przeszłość, jednak wszyscy ocaleni ludzie ulegli mutacjom, a świat wypełniła magia. Głównymi bohaterami serialu animowanego są Finn, 14-letni chłopiec i jego przyjaciel, pies o imieniu Jake. Chłopiec i pies uwielbiają przygody, nieustannie pomagają wszystkim, którzy są w tarapatach. Przyjaciele mieszkają na drzewie i spędzają razem cały czas. Jeśli chcesz zanurzyć się w świecie przygód z innymi wielbicielami, krzyknij "Matematyka". Oto zarówno kursor Finna, jak i kursor Jake\'a, a także kursor Księżniczki Bąbelgum. Oczywiście nie zapomnieliśmy o kursorze Bimo, kursorze Króla Lodu i innych.',
    'nba_teams_descr' => 'Jeśli koszykówka jest Twoją ulubioną grą, tak jak i naszą, to kolekcja kursorów dedykowana drużynom NBA jest tym, czego potrzebujesz. NBA to jedno z najlepszych stowarzyszeń sportowych na kontynencie północnoamerykańskim. Kiedy tworzyliśmy tę kolekcję, dręczył nas wybór - którą drużynę wybrać, ponieważ w NBA jest ich trzydzieści. Ale są zespoły, które są legendami. To i Chicago Bulls, ustanowili rekord zwycięstw w połowie lat 90. To Golden State Warriors, którzy kilka lat temu zebrali najlepszych graczy ligi. Albo na przykład Lakers, Celtics to również szalenie fajne drużyny. Jeśli, tak jak my, nie możesz się doczekać meczów swoich ulubionych drużyn koszykarskich i chcesz okazać swoje wsparcie drużynie lub zawodnikom, pobierz naszą kolekcję kursorów NBA.',
    'spongebob_descr' => 'Serial animowany "SpongeBob SquarePants" jest znany tak wielu osobom. Odniósł ogromny sukces po tym, jak Nickelodeon w 1999 roku zdecydowało się stworzyć serial animowany oparty na edukacyjnym komiksie Tide Zone, i przekształcił się w bardzo dochodową franczyzę. Twórcą serialu jest były pracownik laboratorium oceanologicznego, dlatego prawie wszystkie postacie w serialu animowanym to zabawni mieszkańcy dna morskiego, z własnymi cechami i charyzmą. Akcja koncentruje się wokół tajnego przepisu na Kraboburgery, które potrafi ugotować tylko główny bohater - Sponge Bob. A pozostali mieszkańcy morza dzień w dzień próbują go zdobyć, w tym główny antybohater Sheldon Plankton, któremu nie udaje się to za każdym razem. W kolekcji kursorów SpongeBob zebraliśmy kursory wszystkich znanych postaci i wydarzeń z serialu. Na przykład kursor Pana Kraba z dolarem, kursor Patryka Star, Skalmara ze swoim klarnetem, kursor meduzy, kursor Sponge Boba i wiele innych postaci.',
    'fortnite_chapter_2_descr' => 'Drugi rozdział Fortnite nadszedł po wielkim wydarzeniu - Końcu, które wciągnęło wszystko, co gracze w grze uwielbiali, w czarną dziurę. Fortnite Rozdział 2 ma teraz nową mapę, która na pierwszy rzut oka jest jeszcze bardziej dzika niż oryginalna mapa, a także wiele zmian w mechanice gry i oczywiście mnóstwo nowej zawartości! Pojazdy, emocje, mechanika pływania i wiele więcej - wszystko to w świeżych, interesujących wizerunkach, tak jak uwielbiasz i cenisz w tej kultowej grze. Zanurz się w nowym świecie - wybierz miejsce lądowania i eksploruj zupełnie nową wyspę z 13 lokacjami. Pływanie, łowienie ryb, łodzie motorowe - to nowa rozgrywka wodna. Więcej zabawy i mniej wysiłku - ulepsz zupełnie nowy rozdział 2 i nie zapomnij zmienić kursora na nowe skórki i broń. Czekają już na ciebie zaktualizowane skórki kursora Turk, kursora Riptide, kursora Rippley, kursora Remedy, kursora Toxin, kursora 8-Ball, kursora Fusion i inne!',
    'pokemon_descr' => 'Słowo "pokemon" oznacza stworzenie o nadprzyrodzonych mocach. Posiadają inteligencję, a niektóre z nich są nawet w stanie mówić. Obecnie istnieje już 802 odmiany Pokemonów. W wymyślonym uniwersum Pokémon, ludzie nazywani są trenerami Pokémon, których szkolą do walk z Pokemonami innych trenerów. I im bardziej doświadczony i silniejszy trener, tym większym szacunkiem się cieszy. Na szczęście należy zauważyć, że walki Pokemonów nigdy nie kończą się śmiercią tych unikalnych stworzeń. Wszystkie Pokemony mają różne zdolności i różnią się typem żywiołu, a jego odporność na różne ataki silnie od tego zależy, a niektóre stworzenia posiadają zdolność dwóch żywiołów jednocześnie. Po wygranej walce Pokemon zdobywa cenne doświadczenie, które jest niezbędne do podniesienia poziomu i, co za tym idzie, jego cech. Dziś uniwersum Pokémon jest ogromną franczyzą medialną i postanowiliśmy przygotować dla Ciebie kolekcję kursorów z niektórymi popularnymi Pokémonami. Wśród nich najsłynniejszy jest kursor Pikachu, a także kursor Rattata, kursor Squirt, kursor Bulbasaur i kursor Charmander. Lista ta będzie aktualizowana, ponieważ jest ich tak wiele i każdy z nich jest wyjątkowy na swój sposób.',
    'famous_people_descr' => 'Wśród wielu znanych osób każdy z nas znajduje wzór do naśladowania lub po prostu podziwia geniusz, talent i wytrwałość tych celebrytów. Przygotowaliśmy kolekcję kursorów celebrytów, aby Cię zainspirować i przypomnieć o wielkich osiągnięciach, które każdy z Was może zwiększyć. Nie wszystkie znane osobistości miały szczęśliwy los, ale uczą nas najważniejszej rzeczy, że nigdy nie trzeba wycofywać się ze swojego cennego celu, pomimo trudności i problemów. W końcu to główna zasada osiągania sukcesu - codziennie dążyć do swojego marzenia i w końcu stać się najlepszym w swojej dziedzinie. Być może dzisiaj chcesz po prostu zmienić kursor myszy, a jutro całe Twoje życie zmieni się na lepsze! Kolekcja będzie stale aktualizowana o nowych, godnych przedstawicieli ludzkości. Wśród nich oczywiście naukowcy, politycy, sportowcy, przedstawiciele sztuki i wielu innych. Kursor George\'a Washingtona, kursor Michaela Jordana, kursor Stephena Kinga, kursor Elvisa Presleya i kursor Marilyn Monroe to dopiero początek.',
    'the_elder_scrools_descr' => 'The Elder Scrolls to seria komputerowych gier RPG, zjednoczona wspólnym, starannie zaprojektowanym uniwersum, która zapewnia graczowi ogromną swobodę wyboru, pozwalając na odwiedzanie różnych obszarów i miast fantasy i eksplorację nowych miejsc i misji na własną rękę. Prace nad serią rozpoczęły się w 1992 roku i przez lata gra zjednoczyła wokół siebie ogromną społeczność graczy. Dlatego, na życzenie graczy, wydaliśmy kolekcję kursorów The Elder Scrolls, abyś mógł zanurzyć się w wyjątkowej atmosferze gry. Wieczna bitwa rycerzy i smoków, po której stronie stoisz? Zmień kursor na smoka i dołącz do armii ziejących ogniem potworów lub walcz szlachetnie po stronie ludzi, wybierając kursor miecza i wizerunek swojej ulubionej postaci - decyzja należy do ciebie! Najważniejsze jest to, że z naszą nową kolekcją jesteś gotowy na wszelkie bitwy.',
    'halloween_descr' => 'Czekając na mistyczną noc w wigilię Wszystkich Świętych. Historia Halloween sięga ponad dwóch tysięcy lat. Być może to najdziwniejsze święto łączące zabawę i strach, wywodzące się z kultury celtyckiej. Wtedy ludzie palili ogniska i zakładali straszne kostiumy, aby odpędzić duchy. Słowo "Halloween" po raz pierwszy pojawiło się w XVI wieku jako szkockie skrót angielskiego wyrażenia All-Hallows-Even. Papież Grzegorz III ustanowił 1 listopada Dniem Wszystkich Świętych, a wieczór przed tym dniem znany był jako Wigilia Wszystkich Świętych, a później Halloween. W tym dniu ludzie noszą kostiumy wilkołaków, duchów i innych potworów i chodzą do sąsiednich domów, oferując kupno słodyczy. Imprezy tematyczne, fajerwerki, piękne lampiony, dynie i wyczyny tworzą wyjątkową atmosferę. My również chcemy uczcić to straszne święto akcesoriami, kursorami i postaciami z Halloween. W naszej kolekcji znajdziesz: kursor zombie, kursor ducha, kursor czarnego kota, kursor dyni i wiele więcej. Zmiana nastroju jest teraz tak prosta, jak zmiana kursora dzięki naszej nowej kolekcji Halloween.',
    'nfl_teams_descr' => 'Co może być lepszego dla prawdziwego fana futbolu amerykańskiego niż kursor myszy w postaci symboliki drużyny, której jest fanem? W nowoczesnej National Football League gra trzydzieści dwa zespoły, podzielone pomiędzy National and American Football Conferences (National Football Conference, NFC i American Football Conference, AFC). Z kolei każda z konferencji podzielona jest na cztery dywizje: East, North, South i West. Sezon NFL składa się z gier przedsezonowych, sezonu zasadniczego i serii gier play-off. Finałowy mecz sezonu NFL nazywa się Super Bowl i jest w zasadzie najpopularniejszym wydarzeniem sportowym w Stanach Zjednoczonych. To ulubiona gra milionów fanów i dlatego stworzyliśmy kolekcję kursorów NFL, abyś nie rozstawał się z symbolami swojej ulubionej drużyny. Czy to New England Patriots, New York Giants, Buffalo Bills czy inny zespół, zawsze bądź na tej samej fali co Twoi idole, używając naszych kursorów w postaci logo i hełmu drużyny. Kolekcja będzie stale aktualizowana, aby każdy mógł zmienić kursor na wizerunek swojej ulubionej drużyny.',
    'five_nights_at_freddy_descr' => 'Wyjątkowa gra Five Nights at Freddy\'s szybko zyskała szeroką popularność i nie jest to zaskakujące, ponieważ jej prosta, a zarazem fascynująca fabuła może zatrzymać graczy przed ekranami na długie godziny. Zaprojektowaliśmy kursory Five Nights at Freddy\'s na prośbę fanów gry i byliśmy bardzo zadowoleni z możliwości wcielenia takich ciekawych i zabawnych postaci. Ale w przeciwieństwie do gry, nic Ci nie grozi z naszymi kursorami, więc śmiało wybierz swoje ulubione animatroniki, czy to Niedźwiedź Freddy, Królik Bonnie czy inne. Najważniejsze jest to, że teraz gra ożywa w Twojej przeglądarce i daje świeże emocje. Gwarantujemy, że w naszych kursorach nie ma duchów, ale doskonale oddają ducha gry, która budzi strach ze względu na zawiłości projektu i elementy fabuły. Ale co jeśli ustawisz bardzo duży rozmiar kursora? Czy potrafisz zachować spokój i się nie przestraszyć?',
    'komiksy_descr' => 'Wydawałoby się, że kursor myszy to drobiazg, ale często to właśnie takie detale potrafią poprawić nastrój, obudzić w szary poranek lub po prostu dać jasne emocje. Kolekcja kursorów komiksowych zaprojektowana specjalnie dla wszystkich miłośników superbohaterów. Tutaj znajdziesz absolutnie cały Wszechświat Marvela i DC Comics - od Iron Mana po Thanosa, Spider-Mana i Hulka. Styl kursora może być albo w formie superbohatera, albo w formie jego charakteru. Kursor to nie tylko element funkcjonalny; jest ważny w sensie zawodowym. Na przykład, jeśli nagrywasz wideo z ekranu, lepiej będzie widzieć jasny, oryginalny obraz, co wygląda o wiele ciekawiej. I oczywiście - kto nie chciałby używać rękawicy nieskończoności w prawdziwym życiu? Zmiana kursora myszy jest prosta - wystarczy pobrać rozszerzenie do przeglądarki i dodać kursor, który lubisz, do ustawień za jego pośrednictwem. Możesz wybierać kursor zgodnie ze swoim nastrojem przynajmniej każdego dnia. Dość szarych dni - zostań superbohaterem już teraz!',
    'igry_descr' => 'Gry komputerowe od dawna stały się integralną częścią naszego życia. Z ich pomocą możesz zanurzyć się w nowym świecie, brać udział w przygodach i stać się zupełnie inną osobą. Każdy ma swoją ulubioną zabawkę, której postacie stały się już prawie rodziną. Zestaw kursorów oparty na znanych grach komputerowych to okazja, aby rozcieńczyć nudną codzienność i dodać trochę kreatywności, jasności i zabawy do przepływu pracy. Zestaw zawiera zarówno obrazy samych bohaterów gier, jak i postacie pomocnicze, broń i ikony gier. Wybierz to, co pasuje do Twojego nastroju - kursory do gier spodobają się nie tylko graczom, ale także wszystkim, którzy są po prostu zmęczeni szarą codziennością. Wystarczy pobrać zestaw, zmienić kursor myszy - i ruszyć, aby wykonać zadania, niszczyć wrogów i osiągać swoje cele.',
    'multfilmy_descr' => 'W każdym dorosłym wciąż drzemie dziecko, które kocha kreskówki i wciąż marzy, by stać się jednym z bohaterów. Pomożemy spełnić Twoje marzenia - użyj nowej kolekcji kursorów opartych na najsłynniejszych i ulubionych kreskówkach. Tom i Jerry, Buzz Astral i Shrek, Wodogrzmoty Małe, a nawet Pokemon - możesz stać się tym, kim chcesz każdego dnia. Wybierz kursor myszy zgodnie ze swoim nastrojem. Kim jesteś dzisiaj? Beztroskim i wesołym Minionkiem, który z łatwością rozwiązuje wszelkie problemy, czy silnym i odważnym Rafałem, którego celem jest nie tylko dokonywanie wyczynów, ale także jedzenie pizzy? Może jesteś wszechmocnym dżinem, który dowodzi całym biurem? W kolekcji są bohaterowie dla każdego - od księżniczek po smoki - pozostaje tylko zdecydować, kto odzwierciedla dzisiejszy nastrój. Cursor Style to nie tylko jasny obraz. To odzwierciedlenie indywidualności, autoekspresji i po prostu - zabawa, radość i pozytywna energia na cały dzień. Nudno Ci w pracy lub za bardzo Ci się nie chce uczyć? Stało się smutno i nie jesteś szczęśliwy? Zmień kursor, a świat zabłyśnie nowymi kolorami.',
    'kino_i_serialy_descr' => 'Filmy - to magia, mistycyzm i po prostu świetny sposób na relaks, dobrą zabawę i uzyskanie żywych emocji. Jednocześnie po obejrzeniu wciąż pamiętamy ulubionych bohaterów, których naprawdę chcemy spotkać w rzeczywistości. Teraz to możliwe – wystarczy pobrać nową kolekcję kursorów opartych na słynnych filmach i serialach telewizyjnych. Jasne, fajne kursory będą doskonałym dodatkiem do pulpitu, zamienią nudną szarą codzienność w święto, a banalne zadania – w ekscytującą przygodę. Zmieniaj bohatera kursora każdego dnia – dla nastroju, zadań lub losowo. Kim będziesz dzisiaj? Uczciwym i sprawiedliwym Johnem Snowem czy odważnym, nieustępliwym Johnem Wickiem? Może czeka Cię trudna misja i tylko Frodo może ją ukończyć? Może dziś jesteś po prostu kosmitą, który nie chce nawiązywać kontaktu z innymi? Wybierz odpowiedni kursor – popraw sobie nastrój i jednocześnie pokaż innym, co myślisz i jak zamierzasz spędzić dzień. Spróbuj – to nie tylko zabawa, ale też uzależniające – na pewno nie będziesz chciał wrócić do zwykłej strzałki.',
    'anime_descr' => 'Anime to unikalny styl animacji, który pomimo swojej wyraźnej etniczności, cieszy się popularnością wśród milionów ludzi na całym świecie. Mało prawdopodobne, aby znalazła się choć jedna osoba, która nie oglądała kreskówek w tym stylu. Stworzyliśmy najfajniejsze kursory w stylu anime, które pokochają wszyscy fani tego stylu. Standardowe kursory są nudne i oklepane. Pokaż swoją osobowość - użyj kolekcji kursorów Anime ze swoimi ulubionymi postaciami. Wybierz kursor ciemnego miecza, jeśli marzysz o przygodach i odważnych bitwach. Uroczy grubas Totoro rozweseli Cię nawet w najsmutniejszy dzień, a Naruto zmotywuje Cię do przygód i pokaże wszystkim wokół, że jesteś mega fajny. Jasne kursory rozjaśnią dzień pracy lub sprawią, że proces uczenia się będzie bardziej interesujący i przyjemny. Nie ograniczaj się - używaj swoich ulubionych motywów nawet w tak małych elementach jak kursor myszy. Zmieniaj kursory każdego dnia, dopasowuj je do nastroju i pokazuj swoją osobowość - z kursorami w stylu anime to proste.',
    'futbol_descr' => 'Piłka nożna to wyjątkowy sport, który zawiera elementy zapasów, lekkoatletyki, precyzji. Ogólnie rzecz biorąc, jest spektakularny, bezlitosny i gromadzi miliony fanów na całym świecie. Lubisz piłkę nożną czy po prostu kochasz sport? Pobierz zestaw kursorów w stylu światowej sławy gry i udowodnij tytuł lojalnego fana. Kolekcja zawiera 24 opcje projektowania kursorów - w formie najpopularniejszych drużyn, które zasługują na swoje tytuły jako zacięta i wytrwała gra. Kursory wykonane są w dwóch wersjach - w formie standardowego trójkąta, ozdobionego w barwach drużyny, lub w formie odpowiedniego hełmu do gry. Standardowy kursor przeglądarki jest nudny i niegodny prawdziwego fana sportu. Bądź oryginalny i niepowtarzalny z naszą kolekcją. Pobierz obrazy i wybierz kolory swojej ulubionej drużyny lub niestandardowe kursory, jeśli po prostu kochasz sport i kibicujesz wszystkim. Podążanie za swoimi hobby jest takie proste - nie musisz przychodzić do pracy w szaliku lub czapce swojej ulubionej drużyny, szybko i łatwo zmieniasz kursor na jasny, stylowy obraz.',
    'avtomobili_descr' => 'Czy lubisz samochody i lubisz oglądać modele różnych producentów? A może od dawna marzysz o konkretnej marce, ale nadal nie masz możliwości jej kupić? Specjalnie dla Ciebie stworzyliśmy jasny zestaw kursorów "Supercars". Znajdziesz tu klasycznego Forda i stylowe Bentley, jasne Lamborghini i unikalne Ferrari. Chcesz zostać właścicielem oryginalnego samochodu? To proste - pobierz naszą kolekcję kursorów na swoje urządzenie i zmieniaj wizerunek samochodu przynajmniej codziennie. Kursory zostały zaprojektowane w dwóch wersjach - jako pełnoprawny samochód lub jako jego znak. Wybierz to, co lubisz najbardziej lub jak wolisz pracować. Takie obrazy będą świetnie wyglądać jako kursory do gier lub po prostu jako niezwykły element pulpitu. Bycie jasnym jest proste - nie trzeba do tego robić niewyobrażalnych rzeczy ani zmieniać wyglądu. Wystarczy po prostu przestać używać pospolitych przedmiotów i wybrać to, co naprawdę lubisz. Kolekcja kursorów "Samochody" to wybór dla tych, którzy nie boją się udowodnić, kim są.',
    'memy_descr' => 'Memy są od dawna znaną częścią naszego życia. A kto z nas nie lubi tych pojemnych, interesujących i oryginalnych obrazów, żeby złościć dzień? Wielu bohaterów memów stało się nie tylko popularnych - zyskało status popularnych ulubieńców, a frazy i wyrażenia od dawna znalazły się w języku potocznym jako dobrze ugruntowane zwroty. Prezentujemy kolekcję najlepszych kursorów opartych na najpopularniejszych memach. Z ich pomocą możesz nie tylko pokazać swoją osobowość, ale także wyrazić swój nastrój. Czy jesteś zmęczony i znudzony wszystkim? Wybierz wściekłego kota, który całym swoim wyglądem wyraża oburzenie i wrogość wobec wszystkiego wokół. A może dzisiaj błyszczysz sarkazmem i nie masz nic przeciwko śmianiu się? Wtedy Drake Bling będzie doskonałym akompaniamentem - rozweseli Cię i sprawi, że każde zadanie będzie oryginalne i interesujące. Zainstaluj rozszerzenie, pobierz naszą kolekcję - i wybierz styl kursora na każdy dzień. Nie jest trudno być jasnym i oryginalnym - zmień standardowy wygląd ikony na jednego z bohaterów memów i zyskaj zastrzyk energii na cały dzień.',
    'emodji_descr' => 'Emoji - jasne, fajne ikony, bez których nie możemy już zwyczajowo komunikować się. Z ich pomocą nie musisz opisywać swojego nastroju słowami - po prostu wybierz żądaną ikonę, a rozmówca zrozumie Cię bez zbędnych słów. W naszym nowym zestawie kursorów ucieleśniliśmy ideę emoji - tak powstały zabawne i niezwykłe Cursoji, które ubarwią świat i uczynią życie bardziej interesującym. Z pomocą kursora możesz nie tylko pracować i wykonywać znane zadania, ale także pokazać swoim kolegom, przyjaciołom i po prostu innym swój nastrój. Senny kursor jest idealny na poniedziałkowy poranek, a płaczący kursor wyrazi stosunek do dodatkowych obowiązków. Fajna kursor z okularami to najlepszy wybór przed świętami, a kursor z dolcami w oczach to dobry powód, aby zasugerować szefowi podwyżkę. Używanie Cursoji to świetna zabawa - czy to praca, nauka czy prezentacja. W tym ostatnim przypadku, jest to nawet zalecane, jeśli koledzy mają poczucie humoru lub po prostu potrzebują rozładować sytuację. Ogólnie rzecz biorąc, dla każdego zadania - po prostu wybierz odpowiedni kursor!',
    'pitomcy_descr' => 'Czy lubisz zwierzęta? Z pewnością - są takie słodkie, zabawne i bardzo śmieszne. Dlaczego nie spędzić całego dnia w towarzystwie najlepszych przyjaciół człowieka? Pobierz kolekcję kursorów Zwierzęta dla siebie i wybierz przyjaciela dla siebie na każdy dzień. Ikona kursora może być słodka, jak poczciwa alpaka, lub stylowa, jak różowy flaming. A może będziesz zajęty cały dzień i wybierzesz jednorożca czytającego gazetę, lub po prostu nie chcesz z nikim rozmawiać, jak zły czarny kot? Na każdy nastrój mamy odpowiednie zwierzę. Wesoły mops rozweseli Cię nawet w najbardziej nudny i szary dzień, a różowy kursor w kształcie jednorożca pokaże wszystkim, że nie jesteś pozbawiony poczucia piękna, nawet będąc brutalnym brodatym mężczyzną. Co jeśli nie ma nastroju i nie chce mi się wykonywać rutynowych zadań? Przepis jest prosty - pobierz kolekcję Zwierzęta, zmień kursor myszy - i voila, słońce znów świeci, pogoda dopisuje, a nastrój jest na najwyższym poziomie. Nic dziwnego, że mówi się, że zwierzęta pomagają zwalczać depresję i smutek!',
    'stil_i_krasota_descr' => 'W nowej kolekcji kursorów zebraliśmy szeroką gamę tematów, które wywołują w nas przyjemne emocje i podnoszą na duchu. Ten zestaw kursorów nazywa się „Styl i Uroda”, ponieważ to Twoje ulubione rzeczy determinują nasze codzienne życie, dają radość i motywują nas do robienia ważnych rzeczy, budzą pragnienie ulepszeń. Czy interesujesz się kosmosem i marzysz o podróży na inne planety? Wybierz kursor NASA lub talerz z kosmitami - zbliż się do swojego marzenia. Jeśli nie wyobrażasz sobie życia bez muzyki lub jesteś zagorzałym rockmanem, to kursor w stylu gitary elektrycznej jest dla Ciebie. Pędzel, linijka i kompas zostały specjalnie opracowane dla inżynierów - takie obrazy pomogą zamienić nudne obliczenia i rysunki w oryginalne rozwiązania. Magiczna różdżka i trampki, deskorolka i szminka, słońce i stożki chemiczne - wybierz to, co pasuje do Twojego stylu życia, Twoich pragnień i aspiracji - a zwykłe zadania staną się bardziej interesujące, a dni robocze zostaną pomalowane nowymi, jasnymi kolorami.',
    'prazdniki_descr' => 'Lubisz święta? Kto ich nie lubi - przyjaciele, prezenty, znowu ten sam weekend. Aby oczekiwanie na święta było przyjemniejsze, krótsze i cieplejsze, możesz nie tylko odliczać dni na kalendarzu, ale także ustawić odpowiednią ikonę jako kursor myszy. Zacznijmy od Nowego Roku - wybierzemy choinkę, prezent lub Świętego Mikołaja, aby święto było jasne i radosne. Może ludzik z piernika będzie bliżej - zabawny, słodki i zawsze wesoły? Z nim na pewno nie będzie czasu na smutek i nudę. Kontynuujemy świętowanie z amorami i wesołymi sercami, a do Wielkanocnego Zajączka już niedaleko. Gdzieś wśród świąt znajdą się urodziny, na które będzie jeszcze przyjemniej czekać z balonami zamiast standardowej strzałki kursora. A w Halloween możesz zaskoczyć kolegów i osoby wokół niezwykłym kursorem myszy w postaci złowrogiej dyni lub ducha. Zestaw kursorów na święta to okazja, aby rozjaśnić oczekiwanie, nastroić się z wyprzedzeniem na nadchodzącą zabawę i utrzymać doskonały nastrój nie tylko w przeddzień uroczystości, ale przez cały rok.',
    'flagi_descr' => 'Flaga to wyjątkowy symbol, który jest szeroko używany we wszystkich sieciach społecznościowych. Pomyśleliśmy, dlaczego nie zrobić z kursora flagi? W końcu jest naprawdę jasna i niezwykła. Teraz możesz spędzać każdy dzień w towarzystwie nowego kraju, a praca nie będzie tak monotonna i nudna. Kursory myszy mogą być teraz wykonane jako flaga narodowa Chin lub USA, Japonii lub Kanady i w 38 innych opcjach flag, a możesz wybrać albo standardowy kształt strzałki w niezwykłym kolorze, albo kursor w kształcie samej flagi. Ten zestaw przypadnie do gustu wszystkim miłośnikom podróży. Dzięki niemu możesz planować nowe wycieczki i marzyć o długich podróżach. Zaplanowałeś wakacje? Pokaż wszystkim, do którego kraju chcesz pojechać. Może zdecydowałeś się nauczyć nowego języka obcego? W takim razie ten kursor z pewnością Cię wesprze i zmobilizuje do uważnej nauki. A może, tak jak Sheldon, po prostu uwielbiasz flagi? We wszystkich przypadkach kolekcja Flag będzie wspaniałym dodatkiem do Twojego pulpitu i przeniesie Cię do nowych odkryć.',
    'vokrug_sveta_descr' => 'Wszyscy lubią podróżować. Jak wspaniale jest odwiedzać nowe kraje i miasta, zwiedzać zabytki i dobrze się bawić w nowej kulturze. Szkoda, że ​​nie możemy podróżować tak często, ale staraliśmy się to naprawić. Zestaw kursorów „Dookoła świata” to kolekcja najbardziej uderzających obrazów, symboli różnych krajów, za pomocą których nawet siedząc w domu można poczuć się jak prawdziwy podróżnik. W naszym zestawie można znaleźć Japonię i Australię, Włochy i Kanadę, USA i Meksyk - najciekawsze, oryginalne i malownicze kraje świata. Obraz kursora może stać się standardową strzałką, w kolorach flagi kraju, lub stać się jedną z głównych atrakcji turystycznych państwa. Na przykład możesz otwierać dokumenty z Krzywą Wieżą w Pizie i robić prezentacje, używając Statuy Wolności. Gwarantujemy - sukces będzie zapewniony. Cóż, a jeśli nie sukces, to uśmiechy kolegów i uznanie oryginalności - na pewno. Tak, i sugerowanie zarządowi, że czas iść na wakacje, będzie również warte zachodu - wystarczy ustawić walizkę lub samolot jako kursor - i najprawdopodobniej polecisz bardzo szybko.',
    'eda_i_napitki_descr' => 'Zestaw kursorów w postaci produktów to niesamowita kolekcja jasnych, smacznych i apetycznych obrazków, które z pewnością spodobają się wszystkim i będą świetnym dodatkiem do przeglądarki. Czy kiedykolwiek kliknąłeś na brokuł lub frytki? Masz taką możliwość - wystarczy pobrać nowy zestaw kursorów i ustawić je zamiast nudnej białej strzałki. Kursory "Jedzenie" są wykonane zarówno w postaci standardowego trójkątnego wskaźnika, jak i w postaci produktów. Znajdziesz tu warzywa i owoce, ulubione dania, takie jak pizza czy hot dogi, kawę, lizaki i wiele więcej, co poprawia nastrój każdego dnia. Uwielbiasz kawę, ale picie jej przez cały dzień nie jest takie dobre? Uzupełnij swoją dietę wirtualną kawą, która również pobudzi i obudzi Cię, a także da żywe emocje. Ostry kursor w postaci wirtualnego pączka nie zaszkodzi figurze, a jednocześnie da żywe emocje i poprawi nastrój. Możesz używać swoich ulubionych kursorów lub zmieniać obraz codziennie - duży wybór kursorów pomoże urozmaicić codzienne życie i dodać nowe kolory do znajomych czynności.',
    'cvetnye_descr' => 'Kursor jest głównym elementem przeglądarki, z którym spędzamy cały dzień pracy, nauki, komunikacji i relaksu. Standardowy widok kursora jest nudny, a nawet nieco przygnębiający, ale dla wielu osób ta forma jest wygodna i zmiana jej będzie niewygodna. Ale dla tej sytuacji mamy rozwiązanie - zestaw kursorów w jasnych, wesołych kolorach, które dodadzą różnorodności do Twojego codziennego życia i sprawią, że rozwiązywanie wszelkich problemów będzie łatwiejsze i szybsze. Jeśli zastanawiasz się, jak zmienić kolor kursora, odpowiadamy - pobierz naszą kolekcję i wybierz jasne rozwiązania na każdy dzień! Możesz wybrać monochromatyczne tony w różnych kolorach, aby dopasować je do nastroju lub specyfiki pracy. Na przykład, podczas pracy ze standardowymi dokumentami, fioletowy kursor będzie się wyróżniał na tle, a na ciemnym tle, wręcz przeciwnie, łatwiej będzie pracować z żółtymi kursorami. Jeśli chcesz eksplozji koloru, jasności i maksymalnej oryginalności - wybierz tęczowy kursor, który zawiera wszystkie kolory spektrum - z tą ikoną nastrój na pewno będzie dobry przez cały dzień.',
    'prank_descr' => 'Żarty w pracy nie zawsze są mile widziane, ponieważ często zakłócają przepływ pracy. Ale z nowym zestawem kursorów „Pranks” możesz uprzejmie zrobić psikusa swoim kolegom lub przyjaciołom, nie szkodząc swojej pracy ani nauce. Opracowaliśmy specjalną kolekcję, która rozbawi każdego i da powód do odprężenia się pośród pracowitego procesu pracy lub wykonywania innego zadania. Aby zmienić kursor myszy, wystarczy pobrać zestaw na urządzenie i wybrać żądany projekt w parametrach. Na przykład możesz uzyskać kursor w standardowym kształcie, ale w stanie odwróconym lub strzałkę zakrzywioną przez falę. Ta forma wcale nie przeszkodzi w procesie pracy, ale jednocześnie zaprezentuje wspaniały nastrój i wprawi w pozytywny nastrój. Zmień ustawienia wyświetlania kursora zgodnie ze swoim nastrojem lub każdego dnia - a każde zadanie stanie się bardziej interesujące i przyjemne, a codzienne życie przestanie powodować negatywne emocje. Co więcej, takie kursory mogą być używane nawet do poważnych projektów - mają neutralne kolory i nie wyróżniają się na tle pulpitu.',
    'startovyj_nabor_descr' => 'Kursory z kolekcji startowej to mieszanka standardowych kształtów i rozmiarów o jasnym, nietypowym wyglądzie. To doskonały wybór dla tych, którzy wolą zwykłe formy, ale chcą wnieść różnorodność, oryginalność i jasność do codziennego życia. Kolekcja zawiera kursor dłoni i znajomą strzałkę w różnych wariantach - od logo Google Chrome po emotikony, można tu nawet spotkać dawno zapomnianego smoka z kaktusami i nostalgią. Udowadniamy, że standardowy kursor też może być interesujący i atrakcyjny. Różne kolory, kształty, tekstury i interesujący design pomogą Ci wybrać kursor do gustu lub zmieniać go codziennie w zależności od nastroju lub wykonywanych zadań. Zmiana kursorów przeglądarki jest bardzo prosta - wystarczy zainstalować rozszerzenie i pobrać kolekcję na swoje urządzenie. Śmieszne, ciekawe kursory nie tylko ubarwią dni robocze, ale także na przykład pomogą uczynić każdą prezentację bardziej interesującą, a za pomocą szczególnie jasnych kursorów zwrócą uwagę na poszczególne elementy raportu.',
    'fortnite_descr' => 'Fortnite podbiło miliony ludzi na całym świecie. Ekscytujące bitwy, strategia i taktyka, przygody - pochłonęło absolutnie wszystko, co gracze tak bardzo lubią. Nie mogliśmy pozostać obojętni i opracowaliśmy zestaw kursorów w stylu gry, który spodoba się nie tylko zapalonym graczom, ale nawet tym, którzy po raz pierwszy usłyszeli o Fortnite. Ikona kursora Fortnite to wizerunek bohatera lub jego broni, dopracowany w najdrobniejszych szczegółach. Tutaj możesz znaleźć wizerunki lisów i ryb, maski inferno i czarnych rycerzy, ustawić sobie strzałę lub kosę z kolcami jako strzałkę. Jesteśmy pewni, że nikt nie pozostanie obojętny! By być strasznym lub tajemniczym, oryginalnym lub humorystycznym - to zależy od ciebie. Wybierz swój styl i podążaj za nim lub ustaw niestandardowe kursory w ustawieniach i zmieniaj swoją rolę każdego dnia. Teraz wykonywanie nawet żmudnej i monotonnej pracy stanie się o wiele bardziej interesujące i przyjemne - czas minie szybko w towarzystwie żywych obrazów i ulubionych postaci. A może urządzisz konkursy z kolegami, który bohater będzie silniejszy? Wybór należy do ciebie!',
    'dota_2_descr' => 'DotA2 to nie tylko zwykła gra, to prawdziwy równoległy świat. W wirtualnej rzeczywistości w DotA2 możesz robić wszystko - żyć, walczyć, rozwijać się, podróżować, zawierać znajomości. Ogólnie rzecz biorąc, wszystko jest jak w życiu, tylko czasami bardziej interesujące. Kursory Dota 2 to kontynuacja strategii, która pozwoli Ci uzyskać żywe emocje i wyrazić siebie w realnym świecie. Nowy zestaw kursorów zawiera najbardziej uderzające postacie w grze, a także oryginalne przedmioty, których nie da się pomylić z niczym innym. Wybierz kursor, który będzie Ci bliższy - i wyrusz na przygodę bez opuszczania miejsca pracy. Jak nudno jest czasem być w pracy lub wykonywać zadania edukacyjne, ale z kursoremi z gier ten problem już Cię nie spotka. Trochę wyobraźni, jasny kursor - i voila, każde zadanie będzie niezwykłą przygodą, z którą poradzenie sobie będzie łatwe i interesujące. Nie musisz się powstrzymywać. Lubisz Dota? W takim razie koniecznie pobierz naszą kolekcję, wybierz jeden lub kilka losowych kursorów naraz - a każdy nowy dzień stanie się jaśniejszy, bardziej interesujący i nasycony.',
    'minecraft_descr' => 'Kursory myszy w postaci standardowych strzałek i palców dawno już znudziły się wszystkim. Jeśli jesteś fanem niezwykłego i oryginalnego, to czas zmienić kursor myszy i nadać mu bardziej interesujący wygląd. Opracowaliśmy kolekcję kursorów w stylu światowej sławy gry Minecraft, gdzie możesz znaleźć najbardziej uderzające postacie. Wilk i lis, Alex i Creeper, diamentowy miecz i ryba - możesz wybrać ten, który najbardziej Ci się podoba lub instalować nowego bohatera każdego dnia. To prawdziwe kursory dla graczy, które przypadną do gustu absolutnie wszystkim - w końcu, kto z nas nie grał w Minecraft? Jesteśmy pewni, że takich po prostu nie ma. Precz z nudną codziennością - czas zanurzyć się w przygodach, co można zrobić nawet nie wychodząc z domu czy krzesła w biurze. Przygotowywanie raportu i zmniejszanie salda z pistoletem będzie bardziej interesujące - każde zadanie stanie się przyjemniejsze i nie pozwoli Ci się nudzić w miejscu. Pobierz nową kolekcję kursorów Minecraft - ustaw je i nawet w najbardziej szary i nudny dzień Twój nastrój zawsze będzie najlepszy. A koledzy będą zazdrościć Twoich wyników - po prostu nie da się nie wykonać swojej pracy z pomocą dzielnych bohaterów Minecraft.',
    'phineas_and_ferb_descr' => 'W fikcyjnym amerykańskim mieście Denville w nieistniejącym Trishtatya mieszkają dwaj interesujący chłopcy. Każdy dzień ich wakacji zamienia się w niesamowite przygody, ponieważ potrafią zbudować kolejkę górską wielkości całego miasta lub prawdziwy portal do innej planety. Dzielą się swoją niesamowitą rozrywką z przyjaciółmi. Jednocześnie, gdy chłopcy się bawią, zły naukowiec Heinz Fufelschmertz buduje kolejną złą maszynę, która tworzy chaos, a jej nazwa kończy się na "-inator", za pomocą której chce pomścić swoje krzywdy z dzieciństwa lub przejąć władzę w Trishtat, ale przeszkadza mu Perry - Utkonos, tajny "Agent Pi", pracujący pod przykrywką zwierzaka chłopców. Popularność tego serialu animowanego, zarówno wśród dzieci, jak i dorosłych, zainspirowała nas do stworzenia kolekcji kursorów Phineas i Ferb, dzięki czemu możesz zmienić kursor myszy na postacie z serialu. Wśród nich znajdują się kursor Phineasa Flynna, kursor dr. Heinza Fufelschmertza, kursor Ferba Fletchera, kursor Candace Gertrude Flynn i kursor dziobak Perry.',
    'astrology-signs-zodiac' => 'Znaki Zodiaku',
    'astrology-signs-zodiac_short_descr' => 'Zestaw 12 symboli astrologicznych reprezentujących cechy osobowości, energie kosmiczne i wzorce życiowe.',
    'sports-cars' => 'Samochody sportowe',
    'sports-cars_short_descr' => 'Potężne i stylowe samochody zbudowane z myślą o prędkości i zwinności',
    'spider-man' => 'Spider-Man',
    'sports-cars_descr' => 'Samochody sportowe to wysokowydajne pojazdy zaprojektowane z myślą o szybkim przyspieszeniu, ostrym prowadzeniu i ekscytującym doświadczeniu jazdy. Od eleganckich coupe po zwinne roadstery, ta kategoria zawiera niektóre z najbardziej kultowych maszyn stworzonych dla dreszczyku emocji na drodze lub torze. Idealne dla entuzjastów, którzy kochają prędkość, design i moc. 🏎️🔥',
    'spider-man_short_descr' => 'Bohaterowie z uniwersum Spider-Mana',
    'starwars' => 'Star Wars',
    'spider-man_descr' => 'Kolekcja postaci i bohaterów z uniwersum Spider-Mana. Zawiera różne wersje Spider-Mana, sojuszników i unikalne style z komiksów, gier i seriali animowanych. Każdy projekt odzwierciedla zwinność, odwagę i identyfikację wizualną, która definiuje świat Spider-Mana.',
    'astrology-signs-zodiac_descr' => 'Znaki Zodiaku ♈♉♊♋♌♍♎♏♐♑♒♓ to dwanaście symbolicznych podziałów pasa niebieskiego używanych w astrologii. Każdy znak powiązany jest z określonymi datami, żywiołami (🌍 Ziemia, 🔥 Ogień, 🌊 Woda, 💨 Powietrze), planetami rządzącymi i unikalnymi cechami charakteru. Astrologowie używają znaków zodiaku do interpretacji zachowań, przewidywania zgodności i eksploracji ścieżek życiowych. Niezależnie od tego, czy jesteś namiętnym Lwem 🔥 czy zamyśloną Rybą 🌊, twój znak oferuje wgląd w twój wewnętrzny świat. Ta kategoria zawiera wszystkie 12 znaków, ich znaczenia i wizualne reprezentacje.',
    'starwars_descr' => 'Zanurz się w odległej galaktyce dzięki tej kolekcji, w której znajdziesz legendarnych bohaterów, potężnych lordów Sithów, droidy, rebeliantów i wiele więcej. Od Rycerzy Jedi po szturmowców, każda ikona ożywia ducha Gwiezdnych Wojen w formie kursora. Idealny dla fanów każdej trylogii. 🌌',
    'starwars_short_descr' => 'Postacie i symbole ze świata Gwiezdnych Wojen',
    'glitter' => 'Brokat',
    'glitter_short_descr' => 'Błyszczące i iskrzące kursory w stylu brokatu ✨🌟',
    'glitter_descr' => 'Efektowna kolekcja kursorów inspirowana błyszczącymi teksturami i świecącymi efektami wizualnymi. Idealna dla tych, którzy uwielbiają lśniącą estetykę na swoim ekranie. Kursory te wnoszą blask, elegancję i odrobinę magii do każdego kliknięcia.',
    'roblox-2025' => 'Roblox 2025',
    'roblox-2025_short_descr' => 'Postacie z najnowszej fali Roblox 🕹️🚀',
    'roblox-2025_descr' => 'Zupełnie nowa kolekcja 2025 z kultowymi i nowoczesnymi postaciami z Roblox. Zawiera klasycznych noobów, legendy horroru i ulubione awatary fanów z popularnych gier. Zaprojektowana w zabawnym i kolorowym stylu, idealnym dla dzieci i fanów Roblox w każdym wieku.',
];
