<?php

return [
    'title' => 'Cursor Style - Polityka dotycząca plików cookie',
    'descr' => 'Polityka dotycząca plików cookie podczas odwiedzania naszej strony internetowej cursor.style lub rozszerzenia „Cursor Style”. Kilka zasad, które należy wziąć pod uwagę podczas korzystania z naszego produktu.',
    'text' => '<h2> Polityka dotycząca plików cookie </h2>
<p> Kiedy odwiedzasz naszą stronę internetową cursor.style lub rozszerzenie "Cursor Style" w panelu przeglądarki, lub gdy wchodzisz w interakcje z naszymi przedstawicielami ("Usługa"), używamy (i zezwalamy stronom trzecim na używanie) sygnałów nawigacyjnych, plików cookie, znaczników pikselowych, skryptów, tagów, interfejsów API i innych technologii ("Technologie Śledzenia"). Jest to wyjaśnione w niniejszej polityce ("Polityka dotycząca plików cookie"), która stanowi część naszej <a href="/privacy"> Polityki prywatności </a>. </p>
<p> Technologie śledzenia pozwalają nam automatycznie zbierać informacje o Tobie i Twoim zachowaniu w Internecie w celu ulepszenia Twojej nawigacji w naszej Usłudze, poprawy wydajności naszej Usługi i ułatwienia Twojego doświadczenia w naszej Usłudze. Używamy tych informacji również do gromadzenia statystyk dotyczących korzystania z naszej Usługi, przeprowadzania analiz, dostarczania treści, które pasują do Twoich zainteresowań, oraz administrowania usługami dla naszych Użytkowników, klientów i partnerów. Zezwalamy również stronom trzecim na zbieranie informacji o Tobie za pomocą technologii śledzenia. </p>
<p> Czym są pliki cookie? Pliki cookie to małe pliki tekstowe (składające się tylko z liter i cyfr), które serwer WWW umieszcza na Twoim komputerze lub urządzeniu mobilnym podczas odwiedzania strony internetowej. Używanie pliku cookie może pomóc w uczynieniu naszych Usług bardziej przyjaznymi dla użytkownika, na przykład pamiętając Twoje preferencje językowe i ustawienia. Więcej informacji o plikach cookie można znaleźć na stronie <a href="http://www.allaboutcookies.org"> allaboutcookies.org </a>. </p>
<p> Pliki cookie są powszechnie używane do wydajności strony internetowej. Używanie plików cookie pozwala na sprawne poruszanie się między stronami. Pliki cookie zapamiętują Twoje preferencje i sprawiają, że interakcja między Tobą a Usługami jest płynniejsza i bardziej efektywna. </p>
<p> Używamy technologii śledzenia, gdy odwiedzasz lub uzyskujesz dostęp do naszych Usług (zazwyczaj podczas odwiedzania naszych stron internetowych) - nazywane są one „Technologiami Śledzenia Pierwszej Strony”. Ponadto technologie śledzenia są przechowywane przez inne organizacje zewnętrzne (na przykład naszych dostawców usług analitycznych, partnerów biznesowych i reklamodawców), które publikują treści w naszych Usługach - nazywane są one „Technologiami Śledzenia Stron Trzecich”. Oba typy technologii śledzenia mogą być przechowywane albo przez czas Twojej wizyty w naszych Usługach, albo dla powtarzających się wizyt. </p>
<h3> Jakich rodzajów technologii śledzenia używamy? Istnieje pięć głównych typów technologii śledzenia: </h3>
<ul>
<li> <b> Ściśle niezbędne technologie śledzenia </b> <br> <p> Te technologie śledzenia są niezbędne, abyś mógł się zalogować, nawigować i korzystać z funkcji naszych Usług lub świadczyć usługę, której żądasz (na przykład Twoje imię użytkownika). Nie potrzebujemy Twojej zgody na korzystanie z tych technologii śledzenia. Technologie te mogą być używane do celów bezpieczeństwa i integralności, na przykład do identyfikacji naruszeń naszych zasad, a także do obsługi lub funkcji bezpieczeństwa. </p> </li>
<li> <b> Funkcjonalne technologie śledzenia </b> <br> <p>
Te technologie śledzenia umożliwiają naszym usługom zapamiętywanie Twoich wyborów (jak język) i zapewnianie zaawansowanych i spersonalizowanych funkcji. Na przykład, te technologie śledzenia są wykorzystywane do uwierzytelniania (aby zapamiętać, kiedy jesteś zalogowany) i wspierać inne funkcje naszych Usług. </p> </li>
<li> <b> Technologie śledzenia wydajności </b> <br> <p>
Te technologie śledzenia zbierają informacje o Twojej aktywności online (na przykład, czas trwania wizyty w naszych Usługach), w tym dane behawioralne i wskaźniki zaangażowania w treść. Te technologie śledzenia są wykorzystywane do analiz, badań i statystyk (w oparciu o zagregowane informacje). </p> </li>
<li> <b> Marketingowe lub reklamowe technologie śledzenia </b> <br> <p>
Te technologie śledzenia służą do dostarczania Ci ofert specjalnych i reklam opartych na Twoich zainteresowaniach, a także do prowadzenia kampanii e-mail marketingowych. Mogą być również używane do ograniczania liczby wyświetleń reklamy, a także do mierzenia skuteczności kampanii reklamowej. Zazwyczaj są one hostowane przez naszych reklamodawców (na przykład sieci reklamowe) i dają im wyobrażenie o osobach, które widzą i wchodzą w interakcję z ich reklamami, odwiedzają ich strony internetowe lub korzystają z ich aplikacji. </p> </li>
<li> <b> Technologie śledzenia mediów społecznościowych </b> <br> <p>
Nasza strona internetowa zawiera funkcje sieci społecznościowych, takie jak przyciski Lubię to or Razem na Facebooku i Vkontakte lub usługi logowania stron trzecich. Te funkcje są albo publikowane przez stronę trzecią, albo publikowane bezpośrednio w naszych Usługach. Interakcja z tymi funkcjami podlega oświadczeniu o ochronie prywatności firmy, która zapewnia te funkcje. </p> </li>
</ul>
<h3> Poniżej znajdują się pliki cookie, które można znaleźć w naszych Usługach: </h3>
<ul>
<li> <b> Pliki cookie analityczne </b> <br> <p> Te technologie śledzenia służą do zbierania informacji o tym, jak wchodzisz w interakcję z treściami w naszych Usługach, do celów atrybucji (na przykład adresy URL odsyłaczy) itp. Używamy tych informacji do sporządzania raportów, obliczania dochodu należnego nam i pomagania nam w ulepszaniu Usług i oferowaniu spersonalizowanych produktów i treści. </p> </li>
<li> <b> Google Analytics </b> <br> <p> Ten plik cookie służy do zbierania informacji o tym, jak odwiedzający korzystają z naszej Platformy. Używamy tych informacji do tworzenia raportów i ulepszania Platformy. Pliki cookie zbierają informacje w formie anonimowej, w tym liczbę odwiedzających Platformę, skąd odwiedzający przyszli na Platformę i które strony odwiedzili. <br> <a href = "https://policies.google.com/privacy?hl=en" > Polityka prywatności </a> </p> </li>
<li> <b> Google Tag Manager </b> <br> <p> Ten plik cookie jest powiązany z Google Tag Manager, którego używamy do ładowania skryptów na stronach naszej witryny. <br> <a href = "https: / /policies.google.com/privacy?hl=en">Polityka prywatności </a> </p> </li>
</ul>
<p> Pamiętaj, że nie rozpoznajemy ani nie odpowiadamy na automatyczne alerty przeglądarki dotyczące technologii śledzenia, w tym żądań Nie śledź. Istnieją jednak różne sposoby zarządzania i kontrolowania ustawień plików cookie. Pamiętaj, że podczas usuwania lub blokowania plików cookie niektóre funkcje Usług mogą nie działać poprawnie lub nie tak wydajnie. </p>
<p> Większość przeglądarek internetowych dostarcza ogólnych informacji o plikach cookie, pozwala zobaczyć, które pliki cookie są przechowywane na Twoim urządzeniu, pozwala je wszystkie lub pojedynczo usunąć, a także pozwala blokować lub zezwalać na używanie plików cookie dla wszystkich stron internetowych lub indywidualnie wybranych witryn. Możesz także osobno wyłączyć pliki cookie innych firm. Pamiętaj, że ustawienia oferowane przez przeglądarkę lub urządzenie często dotyczą tylko tej konkretnej przeglądarki lub urządzenia. </p>
<h3> Informacje o plikach cookie można zazwyczaj znaleźć w sekcji Pomoc przeglądarki internetowej. </h3>
<p> Poniżej znajdują się linki do kilku popularnych przeglądarek internetowych: </p>
<p><a href="https://support.google.com/chrome/answer/95647?hl=en"> Chrome </a> <br>
<a href="https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies"> Internet Explorer i Microsoft Edge </a> <br>
<a href="https://support.mozilla.org/en/kb/kuki-informaciya-kotoruyu-veb-sajty-hranyat-na-vas"> Mozilla Firefox </a> <br>
<a href="https://support.apple.com/ru-ru/guide/safari/sfri11471/mac"> Safari </a> </p>
<p> Możesz wyłączyć niektóre pliki cookie stron trzecich do targetowania / reklam poprzez kliknięcie w poniższy link: <a href="http://optout.networkadvertising.org/?c=1"> Rezygnacja z reklam opartych na zainteresowaniach </a>. </p>
				',
];
