<?php

return [
    'title' => 'Сursor Style - Warunki użytkowania naszego produktu',
    'descr' => 'Warunki użytkowania są zawierane między Tobą a „Cursor Style” („Usługa”, „my” lub „Serwis”). Ta usługa jest oferowana i dostępna dla użytkowników w wieku 13 lat i starszych tylko do użytku osobistego, a nie do użytku komercyjnego.',
    'text' => '<h2> Warunki świadczenia usług </h2>
<h3> PROSIMY O ZAPOZNANIE SIĘ Z NINIEJSZYMI WARUNKAMI PRZED KORZYSTANIEM ZE STRONY INTERNETOWEJ I ROZSZERZENIA. </h3>
<p> Niniejsze warunki użytkowania są zawierane między użytkownikiem a "Cursor Style" ("Usługa", "my" lub "Usługa"). Następujące warunki, wraz z wszelkimi dokumentami, które wyraźnie obejmują przez odniesienie (łącznie „Warunki użytkowania”), regulują dostęp i korzystanie z witryny cursor.style i jej rozszerzeń przeglądarki, w tym wszelkich treści, funkcjonalności i usług oferowanych w lub za pośrednictwem naszej usługi (łącznie „Usługa”). </p>
<p> Korzystając ze strony internetowej lub rozszerzenia, akceptujesz i zgadzasz się przestrzegać niniejszych Warunków użytkowania. Jeśli nie zgadzasz się z niniejszymi Warunkami użytkowania lub naszą <a href="/privacy"> Polityką prywatności </a>, nie powinieneś uzyskiwać dostępu do witryny i rozszerzenia ani z nich korzystać. </p>
<p> Ta usługa jest oferowana i dostępna tylko dla użytkowników w wieku 13 lat i starszych, wyłącznie do użytku osobistego, a nie do użytku komercyjnego. Korzystając z tej Usługi, oświadczasz i gwarantujesz, że (I) masz 13 lat lub więcej, (II) nie masz zakazu korzystania ze Stron internetowych zgodnie z obowiązującym prawem oraz (III) korzystasz z Usługi tylko dla swoich osobistych potrzeb. Jeśli nie spełniasz tych wymagań, nie powinieneś uzyskiwać dostępu do Usługi ani z niej korzystać. </p>
<p> Możemy od czasu do czasu, według własnego uznania, zmieniać i aktualizować niniejsze Warunki użytkowania. Wszystkie zmiany wchodzą w życie natychmiast po ich opublikowaniu. Dalsze korzystanie z Usługi po opublikowaniu zmienionych Warunków użytkowania oznacza, że akceptujesz zmiany i zgadzasz się na nie. Oczekuje się, że będziesz często odwiedzać tę stronę, aby być na bieżąco ze wszelkimi zmianami, ponieważ są one dla Ciebie wiążące. </p>
<p> Zastrzegamy sobie prawo do wycofania lub zmiany tej Witryny i Rozszerzenia, wszelkich usług lub materiałów, które zapewniamy w Witrynie i Rozszerzeniu, według własnego uznania, bez powiadomienia. Nie gwarantujemy, że nasza witryna, rozszerzenie lub jakakolwiek zawartość będzie zawsze dostępna lub będzie działała nieprzerwanie. Nie ponosimy odpowiedzialności, jeśli z jakiegokolwiek powodu całość lub jakakolwiek część Usługi będzie niedostępna w dowolnym momencie lub w jakimkolwiek okresie. Od czasu do czasu możemy ograniczyć dostęp do niektórych części Witryny lub Rozszerzenia lub całej Usługi dla użytkowników. </p>
<p> Jesteś odpowiedzialny za podjęcie wszelkich niezbędnych środków w celu zapewnienia dostępu do Usługi. Zapewnienie, że wszystkie osoby, które uzyskują dostęp do Usługi za pośrednictwem Twojego połączenia internetowego, są świadome niniejszych Warunków użytkowania i ich przestrzegają. Aby uzyskać dostęp do Usługi lub niektórych oferowanych przez nią zasobów, możesz zostać poproszony o podanie pewnych informacji lub innych danych. Zgadzasz się, że wszystkie informacje, które nam przekazujesz za pomocą tej Usługi lub w inny sposób, w tym między innymi korzystanie z jakichkolwiek interaktywnych funkcji w Usłudze, podlegają naszej <a href="/privacy"> Polityce prywatności </a> i zgadzasz się na wszystkie działania, które podejmujemy w odniesieniu do Twoich informacji, zgodnie z naszą <a href="/privacy"> Polityką prywatności </a>. </p>
<p> Musisz zachować szczególną ostrożność podczas wprowadzania danych osobowych do Usługi na publicznym lub współdzielonym komputerze, aby inni nie mogli przeglądać ani rejestrować Twoich danych osobowych. Witryna, rozszerzenie i wszystkie jej treści, funkcje i cechy (w tym, ale nie wyłącznie, wszelkie informacje, rozszerzenie, tekst, obrazy, obrazy i kursory, a także ich projektowanie, wybór i umieszczanie) należą do "Cursor Style", jej licencjodawców lub innych dostawców takich materiałów są chronione prawem autorskim, znakiem towarowym, patentem, tajemnicą handlową i innymi prawami własności intelektualnej lub prawami własności. </p>
<p> Niniejsze Warunki użytkowania pozwalają na korzystanie ze Stron internetowych wyłącznie do użytku osobistego, niekomercyjnego. Nie wolno powielać, rozpowszechniać, modyfikować, tworzyć dzieł pochodnych, publikować ponownie, pobierać, przechowywać ani przesyłać żadnych materiałów w naszej Witrynie, z wyjątkiem następujących przypadków: możesz używać go do celów osobistych, możesz wydrukować lub pobrać jedną kopię rozsądnej ilości stron Witryny i Rozszerzenia lub ich zawartości do użytku osobistego, niekomercyjnego, a nie do dalszego powielania, publikacji lub dystrybucji. </p>
<p> Nie wolno modyfikować kopii jakichkolwiek materiałów z tej witryny lub rozszerzenia i ich zawartości. Usuwać ani modyfikować żadnych informacji o prawach autorskich, znakach towarowych ani innych informacji o prawach własności z kopii tej witryny i rozszerzenia. Nie wolno mieć dostępu ani używać w celach komercyjnych żadnej części Witryn internetowych lub rozszerzeń, a także wszelkich usług lub materiałów dostępnych za pośrednictwem Witryny lub Rozszerzenia. </p>
<p> Jeśli chcesz użyć jakiegokolwiek materiału w Witrynach internetowych lub Rozszerzeniach innych niż te wymienione w tej sekcji, wyślij żądanie na stronie pomocy sklepu Chrome Web Store. </p>
<p> Jeśli drukujesz, kopiujesz, modyfikujesz, pobierasz lub w inny sposób używasz lub dajesz jakiejkolwiek innej osobie dostęp do jakiejkolwiek części Witryny lub Rozszerzenia z naruszeniem Warunków użytkowania, Twoje prawo do korzystania z Witryny i Rozszerzenia natychmiast wygasa i musisz, według naszego uznania, zwrócić lub zniszczyć wszelkie kopie materiałów, które masz. Jakiekolwiek korzystanie z witryny rozszerzenia, które nie jest wyraźnie dozwolone przez niniejsze Warunki użytkowania, stanowi naruszenie niniejszych Warunków użytkowania i może naruszać prawa autorskie, znaki towarowe i inne prawa. </p>
<p> Nazwa „Cursor Style”, logo „Cursor Style” oraz wszystkie powiązane nazwy, logo, obrazy, kursory i nazwy usług, projekty i hasła są znakami towarowymi „Cursor Style” lub jego podmiotów stowarzyszonych lub licencjodawców. Nie wolno używać takich znaków bez uprzedniej pisemnej zgody Usługi. Wszystkie inne nazwy, logo, nazwy produktów i usług, projekty i hasła na tej stronie internetowej i w rozszerzeniu są znakami towarowymi ich odpowiednich właścicieli. Możesz korzystać z Usługi tylko w uzasadnionych celach i zgodnie z niniejszymi Warunkami użytkowania. </p>
<h3> Zgadzasz się NIE używać Usługi: </h3>
<ul>
<li> W jakikolwiek sposób, który narusza jakiekolwiek obowiązujące przepisy federalne, regionalne, lokalne lub międzynarodowe (w tym, ale nie wyłącznie, wszelkie przepisy dotyczące eksportu danych lub oprogramowania do Rosji i innych krajów). </li>
<li> W celu eksploatacji, krzywdzenia lub prób użycia lub krzywdzenia nieletnich, narażania ich na nieodpowiednie treści, żądania informacji, które ich identyfikują lub w inny sposób. </li>
<li> Do wysyłania, świadomego otrzymywania, pobierania, używania lub ponownego używania jakichkolwiek materiałów, które nie są zgodne z niniejszymi Warunkami użytkowania. </li>
<li> Przesyłać lub kupować wysyłanie jakichkolwiek reklam lub materiałów promocyjnych bez naszej uprzedniej pisemnej zgody, w tym wszelkich „niezamówionych listów”, „listów łańcuszkowych” lub „spam” lub jakichkolwiek innych podobnych ofert. </li>
<li> W celu podszywania się lub próby podszywania się pod pracownika „Cursor Style”, innego użytkownika lub jakąkolwiek inną osobę lub organizację (w tym, ale nie wyłącznie, używanie adresów e-mail lub aliasów powiązanych z którymkolwiek z powyższych). </ li >
<li> Udział w jakichkolwiek innych działaniach, które ograniczają lub utrudniają korzystanie z Usługi lub korzystanie z niej przez kogokolwiek, lub które, jak ustalimy, mogą zaszkodzić Usłudze lub użytkownikom Usługi lub narazić ich na odpowiedzialność. </li> </ul>
<h3> Ponadto zgadzasz się NIE: </h3>
<ul>
<li> Używać Usługi w jakikolwiek sposób, który może wyłączyć, przeciążyć, uszkodzić lub pogorszyć działanie witryny, rozszerzyć lub zakłócić korzystanie z Usługi przez jakąkolwiek inną stronę, w tym jej możliwość udziału w działaniach w czasie rzeczywistym za pośrednictwem Usługi. </li>
<li> Używać jakichkolwiek narzędzi automatyzacji, procesów lub środków w celu uzyskania dostępu do Usługi w jakimkolwiek celu, w tym monitorowania lub kopiowania materiału w Usłudze. </li>
<li> Używać jakichkolwiek procesów ręcznych do śledzenia lub kopiowania jakiegokolwiek materiału w Usłudze lub w innych nieautoryzowanych celach bez naszej uprzedniej pisemnej zgody. </li>
<li> Używać jakichkolwiek urządzeń, oprogramowania lub procedur, które zakłócają normalne działanie Usługi. </li>
<li> Wprowadzać jakichkolwiek wirusów, koni trojańskich, robaków, bomb logicznych lub innych materiałów, które są szkodliwe lub szkodliwe technologicznie. </li>
<li> Próbować uzyskać nieautoryzowany dostęp, ingerować, uszkadzać lub zakłócać działanie jakiejkolwiek części Usługi, serwera, na którym przechowywana jest Usługa, lub dowolnego serwera, komputera lub bazy danych połączonej z Usługą. </li>
<li> Atakować Usługę za pomocą ataku typu „odmowa usługi” lub rozproszonego ataku typu „odmowa usługi”. </li> </ul>
<p> Informacje dostarczone w Usłudze lub za jej pośrednictwem są dostarczane wyłącznie w celach informacyjnych. Nie gwarantujemy dokładności, kompletności ani użyteczności tych informacji. Polegasz na takich informacjach wyłącznie na własne ryzyko. Zrzekamy się wszelkiej odpowiedzialności wynikającej z jakiegokolwiek polegania na takich materiałach przez Ciebie, innych odwiedzających Usługę lub kogokolwiek, kto może zostać poinformowany o jakiejkolwiek z ich treści. </p>
<p> Ta Usługa obejmuje treści dostarczane przez osoby trzecie, w tym materiały dostarczane przez innych użytkowników i zewnętrznych licencjodawców, syndykatorów, agregatorów i / lub usługi raportowania. Wszystkie oświadczenia i / lub opinie wyrażone w tych materiałach, a także wszystkie artykuły i odpowiedzi na pytania i inne treści, z wyjątkiem treści dostarczonych przez Usługę, są wyłącznie opiniami i odpowiedzialnością osoby lub organizacji dostarczającej te materiały. Materiały te niekoniecznie odzwierciedlają poglądy Usługi. Nie ponosimy odpowiedzialności wobec Ciebie ani żadnej strony trzeciej za treść ani dokładność jakichkolwiek materiałów dostarczonych przez osoby trzecie. </p>
<p> Możemy od czasu do czasu aktualizować zawartość Usługi, ale jej zawartość nie musi być kompletna ani aktualna. Jakikolwiek materiał w Usłudze może być w dowolnym momencie nieaktualny i nie jesteśmy zobowiązani do aktualizacji takich materiałów. Możemy aktualizować, modyfikować, modyfikować informacje i treść na stronie internetowej i w Rozszerzeniu, wprowadzać wszelkie zmiany i aktualizacje zgodnie z naszą własną decyzją. </p>
<p> Wszystkie informacje, które zbieramy w tej Usłudze, podlegają naszej Polityce prywatności. Korzystając z Usługi, akceptujesz wszystkie działania podejmowane przez nas w odniesieniu do Twoich informacji zgodnie z <a href="/privacy"> Polityką prywatności </a>. </p>
<p> Dodatkowe warunki mogą również dotyczyć niektórych części, usług lub funkcji Usługi. Wszystkie takie dodatkowe warunki są niniejszym włączone przez odniesienie do niniejszych Warunków użytkowania.
Możesz utworzyć link do naszej witryny internetowej lub rozszerzenia, jeśli zrobisz to w uczciwy i zgodny z prawem sposób i nie zaszkodzisz naszej reputacji ani jej nie wykorzystasz, ale nie powinieneś ustawiać linku w taki sposób, aby oferować jakąkolwiek formę powiązania, poparcia lub poparcia z naszej strony bez naszej pisemnej zgody. </p>
<p> Usługa zawiera linki do innych witryn i zasobów dostarczonych przez osoby trzecie, linki te są podane tylko dla Twojej wygody. Obejmuje to linki zawarte w reklamach, w tym banery reklamowe i linki sponsorowane. Nie kontrolujemy zawartości tych witryn ani zasobów i nie ponosimy za nie odpowiedzialności ani za jakiekolwiek straty lub szkody, które mogą wynikać z ich wykorzystania. Jeśli zdecydujesz się uzyskać dostęp do jakichkolwiek witryn osób trzecich powiązanych z tą Usługą, robisz to na własne ryzyko i zgodnie z warunkami użytkowania takich witryn. Zastrzegamy sobie prawo do cofnięcia pozwolenia na link bez uprzedniego powiadomienia. </p>
<p> Rozumiesz, że nie możemy i nie gwarantujemy ani nie gwarantujemy, że pliki dostępne do pobrania przez Internet lub na Stronach internetowych nie będą zawierać wirusów lub innego złośliwego kodu. Jesteś odpowiedzialny za wdrożenie procedur i punktów kontrolnych wystarczających do zaspokojenia Twoich specjalnych wymagań dotyczących ochrony antywirusowej i dokładności wprowadzania i wyprowadzania danych, a także za utrzymywanie środków zewnętrznych wobec naszej witryny w celu odzyskania utraconych danych. NIE PONOSIMY ODPOWIEDZIALNOŚCI ZA JAKIEKOLWIEK SZKODY LUB OBRAŻENIA SPOWODOWANE ROZPROWADZONĄ ODPOWIEDZIALNOŚCIĄ SERWISU, WIRUSAMI LUB INNYM ZŁOŚLIWYM OPROGRAMOWANIEM OTRZYMANYM ZA POŚREDNICTWEM USŁUGI LUB POPRZEZ POBRANIE JAKIEGOKOLWIEK MATERIAŁU OPUBLIKOWANEGO NA TEJ LUB JAKIEKOLWIEK STRONACH INTERNETOWYCH, ZWIĄZANYCH Z MOGĄ ZAINFEKOWAĆ LUB USZKODZIĆ TWÓJ SPRZĘT KOMPUTEROWY, OPROGRAMOWANIE KOMPUTEROWE, DANE. </p>
<p> UŻYWASZ USŁUGI, JEJ TREŚCI I WSZELKICH USŁUG LUB ELEMENTÓW UZYSKANYCH ZA POŚREDNICTWEM USŁUG WYŁĄCZNIE NA WŁASNE RYZYKO. USŁUGA, JEJ TREŚCI I WSZELKIE USŁUGI LUB ELEMENTY UZYSKANE ZA POŚREDNICTWEM WITRYNY I ROZSZERZENIA SĄ DOSTARCZANE W STANIE „TAK JAK JEST” I „W MIARĘ DOSTĘPNOŚCI” BEZ ŻADNEJ GWARANCJI. KAŻDA OSOBA ZWIĄZANA Z USŁUGĄ NIE UDZIELA ŻADNEJ GWARANCJI ANI OŚWIADCZENIA W ODNIESIENIU DO KOMPLETNOŚCI, BEZPIECZEŃSTWA, NIEZAWODNOŚCI, JAKOŚCI, DOKŁADNOŚCI LUB DOSTĘPNOŚCI USŁUGA. BEZ OGRANICZEŃ POWYŻSZYCH, ŻADEN „CURSOR STYLE” ANI ZWIĄZANE Z „CURSOR STYLE” PRZEDSTAWICIELE NIE GWARANTUJĄ, ŻE STRONA, ROZSZERZENIE, JEJ TREŚĆ LUB JAKAKOLWIEK NAPRAWA POWIN NY BYĆ WCZEŚNIE DOSTĘPNE USTA LONE, ŻE NASZE ROZSZERZENIE, STRONA LUB SERWER, KTÓRY JĄ UMIESZCZA, BĘDZIE BEZ WIRUSÓW LUB INNYCH SZKODLIWYCH SKŁADNIKÓW LUB TEJ STRONY INTERNETOWEJ LUB WSZELKICH USŁUG LUB ELEMENTÓW WYKONYWANYCH, PREFEROWA NYCH.
<p> W ŻADNYM WYPADKU SERWIS, JEGO PODMIOTY POWIĄZANE LUB LICENCJODAWCY, USŁUGI, PRACOWNICY, AGENCI, FUNKCJONARIUSZE LUB DYREKTORZY NIE PONOSZĄ ODPOWIEDZIALNOŚCI ZA SZKODY JAKIEGOKOLWIEK RODZAJU, ŚWIADCZYMY USŁUGI ODPOWIEDZIALNOŚCI. LUB TAKIE INNE STRONY INTERNETOWE LUB JAKIEKOLWIEK USŁUGI LUB ELEMENTY UZYSKANE W USŁUDZE LUB DO INNYCH STRON INTERNETOWYCH, W TYM WSZELKIE SZKODY BEZPOŚREDNIE, SZCZEGÓLNE LUB WTÓRNE, W TYM OBRAŻENIA CIAŁA, zaburzenia emocjonalne, SZKODY LUB OCZEKIWANE OSZCZĘDNOŚCI, UTRATA UŻYTKOWANIA, DANYCH LUB INNYCH WARUNKÓW. DEFINICJA NIE WPŁYWA NA ŻADNĄ ODPOWIEDZIALNOŚĆ, KTÓREJ NIE MOŻNA WYKLUCZYĆ LUB OGRANICZYĆ ZGODNIE Z OBOWIĄZUJĄCYM PRAWEM, KTÓRE MOŻE OBEJMOWAĆ OSZUSTWO. </p>
<p> Zgadzasz się chronić, zabezpieczać i rozpraszać „Cursor Style”, jego podmioty stowarzyszone, licencjodawców i dostawców usług, a także jego i ich odpowiednich oficerów, dyrektorów, pracowników, wykonawców, agentów, licencjodawców, dostawców, cesjonariuszy i odszkodowania od wszelkich roszczeń i zobowiązań, utraty decyzji sądowych, kosztów, wydatków lub prowizji (w tym honorariów adwokackich) wynikających z lub w związku z Twoim naruszeniem niniejszych Warunków użytkowania użytkowania Usługi, w tym między innymi, odrzucenia wykorzystania jakiejkolwiek zawartości, usług i produktów Witryny lub Rozszerzeń, z wyjątkiem przypadków wyraźnie przewidzianych w niniejszych Warunkach użytkowania, lub korzystania z jakichkolwiek informacji otrzymanych z Usługi. </p>
<p> Jeżeli którekolwiek z postanowień niniejszych Warunków użytkowania zostanie uznane za nieważne, niezgodne z prawem lub niewykonalne przez sąd lub inny trybunał właściwej jurysdykcji z jakiegokolwiek powodu, takie postanowienie powinno zostać uchylone lub ograniczone do minimum, tak aby pozostała część postanowień Warunków użytkowania nadal obowiązywała w pełni. Warunki użytkowania, nasza Polityka prywatności i warunki rejestracji zdarzeń stanowią jedyną i pełną umowę między Tobą a „Cursor Style” dotyczącą Usługi i zastępują wszystkie wcześniejsze i jednoczesne umowy, umowy, oświadczenia i gwarancje, zarówno pisemne, jak i ustne dotyczące Usługi . </p>
<p> Wszystkie recenzje, komentarze, prośby o pomoc techniczną i inne wiadomości dotyczące Usługi należy kierować do strony pomocy technicznej „Cursor Style” w sklepie Chrome Web Store. </p> ',
];
