<?php

return [
    'title' => 'Cursor Style - Privaatsuspoliitika',
    'descr' => 'Rakenduses “Cursor Style,” mis on saadaval aadressil cursor.style või Chrome\'i laienduse kaudu, on üks meie peamisi prioriteete meie külastajate privaatsus. Just selles jaotises räägime kõigist laiendusega töötamise aspektidest.',
    'text' => '<h2> Privaatsuspoliitika </h2>
                <p> Programmis Cursor Style, mis on saadaval aadressil <a href="https://cursor.style"> cursor.style </a> või Chrome\'i laienduse kaudu, on meie külastajate privaatsus üks meie prioriteete. See privaatsuspoliitika dokument sisaldab teavet, mida cursor.style veebisait kogub ja salvestab, ning seda, kuidas me seda kasutame. Kui teil on lisaküsimusi või vajate lisateavet meie privaatsuspoliitika kohta, ärge kõhelge meiega ühendust võtmast. </p>
                <p> Laiendus "Cursor Style" ja veebisait järgivad logifailide kasutamise standardset protseduuri. Need failid registreerivad külastajad veebisaitide külastamisel või meie laienduse kasutamisel. Kõik hostimisfirmad teevad seda ja kuuluvad hostimisteenuse analüüsi. Logifailide kaudu kogutud teave sisaldab Interneti-protokolli (IP) aadresse, brauseri tüüpi, Interneti-teenuse pakkujat (ISP), kuupäeva ja kellaaja templit, ülemineku-/väljumislehti ja võib-olla ka klõpsude arvu. Need ei ole seotud isikut tuvastava teabega. Selle teabe eesmärk on analüüsida suundumusi, hallata saiti ja laiendada, jälgida kasutajate liikumist saidil ja laiendada ning koguda demograafilist teavet. </p>
                <p> Nagu iga teine ​​sait, kasutab ka cursor.style küpsiseid. Neid küpsiseid kasutatakse teabe salvestamiseks, sealhulgas külastaja eelistused ja veebisaidi lehed, mida külastaja külastas või külastas. Seda teavet kasutatakse kasutajakogemuse optimeerimiseks, kohandades meie veebilehe sisu vastavalt külastaja brauseri tüübile ja/või muule teabele. Kasutame projekti toetuseks ja meie veebisaidi toetamiseks ka kolmandate osapoolte reklaame saidil cursor.style. Mõned neist reklaamijatest võivad meie veebisaidil reklaamimisel kasutada selliseid tehnoloogiaid nagu küpsised ja veebimajakad, mis saadavad ka teavet nendele reklaamijatele (näiteks Google\'ile Google AdSense\'i programmi kaudu), sealhulgas teie IP-aadressi, teie Interneti-teenuse pakkuja, brauser, mida kasutasite meie saidi külastamiseks, ja mõnel juhul, kui teil on Flash installitud. Seda kasutatakse tavaliselt geosihtimise eesmärgil (näiteks reklaamide kuvamine kaupade müügiks teie linnas) või teatud reklaamide kuvamiseks teatud külastatud veebisaitide põhjal (näiteks ostukuulutuste kuvamine neile, kes külastavad sageli ostusaite). </p>
                <p> Saate meie või kolmandate osapoolte küpsised brauseri seadetes keelata või selektiivselt keelata või hallata seadeid programmides nagu Kaspersky jne. See võib siiski mõjutada teie suhtlust meie saidiga, aga ka teiste saitidega. See võib hõlmata võimet logida sisse teenustesse või programmidesse, nagu foorumitesse või kontodesse sisselogimine. </p>
<p> Google on üks kolmandatest osapooltest meie saidil. Samuti kasutab see küpsiseid, tuntud kui DART-küpsised, et serveerida reklaame meie saidi külastajatele vastavalt nende külastustele veebisaidile cursor.style ja muudele saitidele Internetis. Külastajad saavad siiski loobuda DART-küpsiste kasutamisest, külastades Google\'i reklaami- ja sisuvahendite privaatsuspoliitikat aadressil <a href="https://policies.google.com/technologies/ads"> järgmisel aadressil </a>. Mõned meie veebisaidi reklaamijad võivad kasutada küpsiseid ja veebimajakaid. Igal meie reklaamipartneril on oma privaatsuspoliitika oma kasutajaandmete kohta. Privaatsuspoliitikat saate lugeda <a href="https://policies.google.com/technologies/ads"> siit </a>. </p>
                <p> Meie veebisait kasutab Google Analyticsi, Google, Inc. veebianalüüsiteenust, aadressil 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com (“Google Analytics” või “Google”). Google Analytics kasutab teie arvutisse salvestatud küpsiseid, et hõlbustada teie veebisaidi kasutamise analüüsi. Nende küpsiste loodud teave, näiteks teie külastuste aeg, koht ja sagedus meie veebisaidil, sealhulgas teie IP-aadress, edastatakse Google\'i asukohta USA-s ja salvestatakse sinna. Google võib seda teavet edastada ka kolmandatele isikutele, kui see on seadusega nõutud või kui kolmandad isikud töötlevad neid andmeid Google\'i nimel. Google väidab, et ei seosta kunagi teie IP-aadressi teiste Google\'i andmetega. Saate vältida küpsiste seadistamist, muutes vastavalt oma brauseritarkvara seadeid, nagu on ette nähtud käesolevas privaatsuspoliitikas. Siiski peaksite olema teadlik, et sel viisil ei saa te meie veebisaidi kõiki funktsioone täielikult kasutada. </p>
                <p> Google Analytics kasutab ka elektroonilisi pilte, mis on tuntud kui veebimajakad (mõnikord nimetatakse neid ühe piksli GIF-ideks) ja mida kasutatakse koos küpsistega, et koostada koondstatistikat meie saidi kasutamise analüüsimiseks.
Saate lisateavet brauseri lisandmooduli installimise kohta, millele ülaltoodud link viitab <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> lingilt </a>.
See sait kasutab Google Tag Managerit. See teenus võimaldab teil saidi silte liidese kaudu hallata. Google Tag Manager rakendab ainult silte. See tähendab, et küpsiseid ei seata ja isikuandmeid ei salvestata. Google Tag Manager käivitab muid silte, mis omakorda võivad andmeid salvestada. Google Tag Manageril pole aga juurdepääsu nendele andmetele. Kui sildid on domeeni või küpsise tasemel keelatud, salvestatakse need kõikide jälgimissiltide jaoks, kui need on rakendatud Google Tag Manageri abil. Lisateavet Google Tag Manageri kohta leiate aadressilt <a href="http://www.google.com/tagmanager/use-policy.html"> link </a>. </p>
<p> Saate tutvuda selle loendiga, et leida iga "Cursor Style" reklaamipartneri privaatsuspoliitika. Kolmandate osapoolte reklaamiserverid või reklaamivõrgud kasutavad selliseid tehnoloogiaid nagu küpsised, JavaScript või veebimajakad, mida kasutatakse nende vastavates reklaamides ja linkides, mis kuvatakse „Cursor Style” ja saadetakse otse kasutajate brauseritesse. Nad saavad automaatselt teie IP-aadressi, kui see juhtub. Neid tehnoloogiaid kasutatakse reklaamikampaaniate tõhususe mõõtmiseks ja/või veebisaitidel, mida külastate, nähtava reklaami sisu isikupärastamiseks. Pange tähele, et „Cursor Style” ei pääse ligi ega kontrolli nende küpsiste üle, mida kasutavad kolmandate osapoolte reklaamijad. The Cursor Style privaatsuspoliitika ei kehti teiste reklaamijate või veebisaitide kohta. Seetõttu soovitame teil lisateabe saamiseks tutvuda nende kolmandate osapoolte reklaamiserverite asjakohaste privaatsuspoliitikatega. See võib sisaldada nende meetodeid ja juhiseid, kuidas loobuda teatud valikutest. Lingid nende kolmandate osapoolte privaatsuspoliitikatele leiate ülaltoodud või nende kolmandate osapoolte teenuste veebisaitidelt. </p>
                <p> Saate küpsised oma brauseri seadetes keelata. Konkreetsetes veebibrauserites küpsiste haldamise kohta lisateabe saamiseks leiate selle nende vastavatelt brauserite veebisaitidelt. Teine osa meie prioriteedist on laste kaitse lisamine Interneti kasutamisel. Julgustame vanemaid ja eestkostjaid jälgima, osalema ja/või jälgima ja suunama nende tegevust Internetis. „Cursor Style” ei kogu teadlikult alla 13-aastaste laste isiklikku teavet. Kui arvate, et teie laps on meie veebisaidil sellist teavet esitanud, soovitame tungivalt meiega viivitamatult ühendust võtta ja teeme kõik endast oleneva, et selline teave meie andmetest kiiresti eemaldada. See privaatsuspoliitika kehtib ainult meie veebitegevuste kohta ja on kehtiv meie veebisaidi külastajate kohta seoses teabega, mida nad jagasid ja/või kogusid „Cursor Style” kohta. See poliitika ei kehti võrguühenduseta kogutud teabe ega selle veebisaidiga kaasnevate kanalite kaudu. </p>
                <p> Küpsiste kasutamise kohta meie teenuses saate lugeda meie <a href="/cookie-policy"> küpsiste poliitikast </a>. </p> ',
];
