<?php

return [
    'title' => 'Cursor Style - Meie toote kasutustingimused',
    'descr' => 'Kasutustingimused on sõlmitud teie ja “Cursor Style” (“Teenus”, “meie” või “Teenus”) vahel. Seda teenust pakutakse ja see on kättesaadav kasutajatele vanuses 13 aastat ja vanematele ainult isiklikuks kasutamiseks, mitte äriliseks kasutamiseks.',
    'text' => '<h2> Kasutustingimused </h2>
<h3> PALUN LUGEGE KÄESOLEVAD TINGIMUSED ENNE VEEBILEHE JA LAIENDI KASUTAMIST. </h3>
<p> Käesolevad kasutustingimused sõlmitakse teie ja "Cursor Style" ("Teenus", "meie" või "Teenus") vahel. Järgmised tingimused koos kõigi dokumentidega, millele nad otseselt viitavad (koos nimetatud "Kasutustingimused"), reguleerivad teie juurdepääsu ja kasutamist veebisaidile cursor.style ja selle brauseri laiendustele, sealhulgas mis tahes sisule, funktsionaalsusele ja teenustele, mida pakutakse meie teenuses või selle kaudu (koos "Teenus"). </p>
<p> Veebisaidi või laienduse kasutamisega nõustute nende kasutustingimustega ja nõustute neid järgima. Kui te ei nõustu nende kasutustingimuste või meie <a href="/privacy"> Privaatsuspoliitikaga </a>, ei tohiks te veebisaidile ja laiendusele ligi pääseda ega neid kasutada. </p>
<p> Seda teenust pakutakse ja see on kättesaadav ainult 13-aastastele ja vanematele kasutajatele ainult isiklikuks kasutamiseks, mitte äriliseks kasutamiseks. Seda teenust kasutades kinnitate ja garanteerite, et olete (I) 13-aastane või vanem, (II) teil ei ole kohaldatava seaduse kohaselt keelatud veebisaite kasutada ja (III) kasutate teenust ainult oma isiklike vajaduste jaoks. Kui te neid nõudeid ei täida, ei tohiks te teenusele ligi pääseda ega seda kasutada. </p>
<p> Me võime neid kasutustingimusi oma äranägemise järgi aeg-ajalt muuta ja uuendada. Kõik muudatused jõustuvad pärast avaldamist kohe. Teenuse jätkuv kasutamine pärast muudetud kasutustingimuste avaldamist tähendab, et nõustute muudatustega ja nõustute neid järgima. Teil palutakse seda lehte sageli külastada, et olla teadlik kõigist muudatustest, kuna need on teie jaoks siduvad. </p>
<p> Me jätame endale õiguse seda veebisaiti ja laiendust, kõiki teenuseid või materjale, mida me veebisaidil ja laienduses pakume, oma äranägemise järgi ja ilma ette teatamata tagasi võtta või muuta. Me ei garanteeri, et meie sait, laiendus või selle sisu on alati saadaval või et see ei katke. Me ei vastuta, kui teenus tervikuna või osaliselt mingil põhjusel igal ajal või mingil perioodil ei ole saadaval. Aeg-ajalt võime kasutajatele piirata juurdepääsu teatud veebisaidi osadele või laiendusele või kogu teenusele. </p>
<p> Teie vastutate kõigi vajalike meetmete võtmise eest, et tagada teil juurdepääs teenusele. Tagada, et kõik isikud, kes pääsevad teenusele teie Interneti-ühenduse kaudu, on nendest kasutustingimustest teadlikud ja neid järgivad. Teenusele või mõnele selle pakutavale ressursile juurdepääsuks võidakse teil paluda esitada teatud teavet või muud teavet. Nõustute, et kogu teavet, mida te meile selle teenuse või muul viisil esitate, sealhulgas, kuid mitte ainult, mis tahes interaktiivsete funktsioonide kasutamist teenuses, reguleerib meie <a href="/privacy"> Privaatsuspoliitika </a> ja nõustute kõigi meetmetega, mida me teie teabe osas võtame. kooskõlas meie <a href="/privacy"> Privaatsuspoliitikaga </a>. </p>
<p> Peate olema eriti ettevaatlik, kui sisestate isikuandmeid teenusesse avalikus või jagatud arvutis, et teised ei saaks teie isikuandmeid vaadata ega salvestada. Veebisait, laiendus ja kogu selle sisu, funktsioonid ja funktsioonid (sealhulgas, kuid mitte ainult, kogu teave, laiendus, tekst, pildid, pildid ja kursorid, samuti nende kujundus, valik ja paigutus) kuuluvad "Cursor Style\'ile", selle litsentsisaajatele või muudele selliste materjalide tarnijatele, on kaitstud autoriõiguse, kaubamärgi, patendi, äriseaduse ja muude intellektuaalomandi seaduste või omandiõigustega. </p>
<p> Need kasutustingimused võimaldavad teil kasutada veebisaite ainult teie isiklikuks, mitteäriliseks kasutamiseks. Te ei tohi paljundada, levitada, muuta, luua tuletatud teoseid, uuesti avaldada, alla laadida, salvestada ega edastada materjale meie veebisaidil, välja arvatud järgmistel juhtudel: saate seda kasutada isiklike vajaduste jaoks, saate printida või alla laadida ühe mõistliku arvu lehti veebisaidist ja laiendusest või nende sisust isiklikuks, mitteäriliseks kasutamiseks, mitte edasiseks paljundamiseks, avaldamiseks või levitamiseks. </p>
<p> Te ei tohi muuta materjalide koopiaid sellelt saidilt või laiendusest ja nende sisust. Kustutage või muutke autoriõiguse, kaubamärgi või muid omandiõiguse teateid selle saidi ja laienduse koopiatelt. Teil ei tohi olla juurdepääsu veebisaitidele või laiendustele ega kasutada neid ärilistel eesmärkidel, samuti teenuseid või materjale, mis on veebisaidi või laienduse kaudu kättesaadavad. </p>
<p> Kui soovite kasutada veebisaitidel või laiendustes mingeid materjale peale nende, mis on selles jaotises loetletud, saatke taotlus Chrome\'i veebipoe tugilehele. </p>
<p> Kui prindite, kopeerite, muudate, laadite alla või muul viisil kasutate või annate mõnele teisele isikule juurdepääsu veebisaidi või laienduse mõnele osale, mis rikub kasutustingimusi, lõpeb teie õigus veebisaidi ja laienduse kasutamisele kohe ning peate meie äranägemise järgi tagastama või hävitama kõik materjalide koopiad, mis teil on. Igasugune laienduse veebisaidi kasutamine, mis ei ole nende kasutustingimustega otseselt lubatud, rikub neid kasutustingimusi ja võib rikkuda autoriõigusi, kaubamärke ja muid seadusi. </p>
<p> Nimi “Cursor Style”, logo “Cursor Style” ja kõik seotud nimed, logod, pildid, kursorid ja teenuse nimed, kujundused ja loosungid on “Cursor Style” või selle sidusettevõtete või litsentsisaajate kaubamärgid. Te ei tohi neid märke kasutada ilma teenuse eelneva kirjaliku loata. Kõik muud nimed, logod, toote- ja teenusenimed, kujundused ja loosungid sellel veebisaidil ja laienduses on nende vastavate omanike kaubamärgid. Te võite teenust kasutada ainult seaduslikel eesmärkidel ja kooskõlas nende kasutustingimustega. </p>
<h3> Te nõustute, et TE EI KASUTA teenust: </h3>
<ul>
<li> Mil viisil, mis rikub kohaldatavaid föderaalseid, piirkondlikke, kohalikke või rahvusvahelisi seadusi või määrusi (sealhulgas, kuid mitte ainult, andmete või tarkvara ekspordi seadusi Venemaale ja teistesse riikidesse). </li>
<li> Eesmärgiga kasutada, kahjustada või püüda kasutada või kahjustada alaealisi, paigutades nad sobimatu sisu ette, taotledes nende tuvastamiseks teavet või muul viisil. </li>
<li> Saata, teadlikult vastu võtta, alla laadida, kasutada või uuesti kasutada materjale, mis ei vasta nendele kasutustingimustele. </li>
<li> Edastada või osta reklaamide või reklaammaterjalide saatmist ilma meie eelneva kirjaliku nõusolekuta, sealhulgas mingeid "soovimatuid kirju", "ahelkirju" või "rämpsposti" või muid sarnaseid pakkumisi. </li>
<li> Selleks, et teeselda või püüda teeselda “Cursor Style” töötajat, teist kasutajat või mõnda muud isikut või organisatsiooni (sealhulgas, kuid mitte ainult, kasutades e-posti aadresse või hüüdnimesid, mis on seotud mõne eelnimetatuga). </li>
<li> Osaleda mis tahes muudes meetmetes, mis piiravad või takistavad teenuse või kellegi teise kasutamist või mis meie arvates võivad kahjustada teenust või teenuse kasutajaid või muuta neid vastutavaks. </li> </ul>
<h3> Lisaks nõustud TE EI TEE: </h3>
<ul>
<li> Kasutada teenust mis tahes viisil, mis võib keelata, ülekoormata, kahjustada või halvendada saidi tööd, laiendada või sekkuda teenuse kasutamisse ühegi teise osapoole poolt, sealhulgas nende võime osaleda reaalajas toimingutes teenuse kaudu. </li>
<li> Kasutage mis tahes automatiseerimisvahendeid, protsessi või vahendeid teenusele juurdepääsemiseks mis tahes eesmärgil, sealhulgas teenuses oleva materjali jälgimiseks või kopeerimiseks. </li>
<li> Kasutage mis tahes käsitsi protsessi materjali jälgimiseks või kopeerimiseks teenuses või muudel volitamata eesmärkidel ilma meie eelneva kirjaliku nõusolekuta. </li>
<li> Kasutage seadet, tarkvara või protseduure, mis häirivad teenuse normaalset toimimist. </li>
<li> Tutvustada viiruseid, Trooja hobuseid, usse, loogikapomme või muid materjale, mis on kahjulikud või tehnoloogiliselt kahjulikud. </li>
<li> Püüda saada volitamata juurdepääsu, sekkuda, kahjustada või katkestada teenuse mis tahes osa, serverit, kus teenus on salvestatud, või mõnda serverit, arvutit või andmebaasi, mis on teenusega ühendatud. </li>
<li> Rünnata teenust teenuse keelamise rünnakuga või hajutatud teenuse keelamise rünnakuga. </li> </ul>
<p> Teenuses või selle kaudu esitatud teave on ette nähtud ainult üldiseks teavitamiseks. Me ei garanteeri selle teabe täpsust, täielikkust ega kasulikkust. Sa tugined sellele teabele ainult omal vastutusel. Me loobume kogu vastutusest ja vastutusest, mis tuleneb teie, teenuse teiste külastajate või kellegi usaldusest sellistele materjalidele, kes võivad olla teadlikud nende sisust. </p>
<p> See teenus sisaldab kolmandate osapoolte pakutavat sisu, sealhulgas materjale, mida pakuvad teised kasutajad ja kolmandate osapoolte litsentsisaajad, sündikaatorid, agregaatorid ja/või aruandlusteenused. Kõik nendes materjalides väljendatud avaldused ja/või arvamused, samuti kõik artiklid ja vastused küsimustele ja muu sisu, välja arvatud teenuse pakutav sisu, on ainult nende materjalide esitaja isiku või organisatsiooni arvamused ja vastutus. Need materjalid ei pruugi tingimata kajastada teenuse seisukohti. Me ei vastuta teie ega ühegi kolmanda osapoole ees kolmandate osapoolte pakutavate materjalide sisu või täpsuse eest. </p>
<p> Me võime teenuse sisu aeg-ajalt uuendada, kuid selle sisu ei pruugi olla tingimata täielik ega ajakohane. Mis tahes materjal teenuses võib igal ajal aegunud olla ja me ei ole kohustatud sellist materjali uuendama. Me võime veebisaidil ja laienduses olevat teavet ja sisu uuendada, muuta, muuta kõiki muudatusi ja värskendusi vastavalt meie enda otsusele. </p>
<p> Kogu teave, mille me sellel teenusel kogume, kehtib meie Privaatsuspoliitika kohta. Teenuse kasutamisega nõustute kõigi meie poolt teie teabe kohta tehtud toimingutega vastavalt <a href="/privacy"> Privaatsuspoliitikale </a>. </p>
<p> Mõnede teenuse osade, teenuste või funktsioonide suhtes võivad kehtida ka lisatingimused. Kõik sellised lisatingimused on siinkohal viitega kaasatud käesolevasse kasutustingimustesse.
Te võite linkida meie veebisaidile või laiendusele, kui teete seda ausalt ja seaduslikult ning ei kahjusta meie mainet ega kasuta seda, kuid te ei tohiks linki seada nii, et pakuksite mingit seost, kinnitust või toetust meie poolt ilma meie kirjaliku nõusolekuta. </p>
<p> Teenus sisaldab linke teistele saitidele ja ressurssidele, mida pakuvad kolmandad osapooled, need lingid on esitatud ainult teie mugavuse huvides. See hõlmab linke, mis sisalduvad reklaamides, sealhulgas bännerreklaamides ja sponsoreeritud linkides. Me ei kontrolli nende saitide või ressursside sisu ega vastuta nende ega nende kasutamisest tulenevate kahjude eest. Kui otsustate pääseda juurde selle teenusega seotud kolmandate osapoolte veebisaitidele, teete seda omal vastutusel ja vastavalt selliste veebisaitide kasutustingimustele. Me jätame endale õiguse tühistada luba linkida ilma eelneva teatamiseta. </p>
<p> Sa mõistad, et me ei saa ja ei garanteeri, et Interneti kaudu või veebisaitidel allalaadimiseks saadaval olevad failid ei sisalda viirusi ega muid pahatahtlikke koode. Teie vastutate protseduuride ja kontrollpunktide rakendamise eest, mis on piisavad teie erivajaduste rahuldamiseks viirusetõrje ja andmete sisestamise ja väljundi täpsuse osas, samuti vahendite säilitamise eest, mis on välised meie saidilt, et taastada kõik kadunud andmed. ME EI VÕTA VASTUTUST KAHJUDE VÕI VIGASTUSTE EEST, MIS ON PÕHJUSTATUD TEENUSE KEELAMISE RÜNNAKUST, VIIRUSTEST VÕI MUUDEST TEHNOLOOGILISEST RÜNNAKUTEST, MIS ON SAADUD TEENUSE KAUDU VÕI MIS TAHES MATERJALI ALLALAADIMISEGA, MIS ON POSTITATUD SELLELE SAIDILE VÕI MIS TAHES VEEBISAIDILE, MIS VÕIBTEIE ARVUTISEADMEID, ARVUTITARKVARA, ANDMEID NAKATADA VÕI KAHJUSTADA. </p>
<p> TE KASUTATE TEENUST, SELLE SISU JA KÕIKI TEENUSEID VÕI OBJEKTE, MIS ON SAADUD TEENUSTE KAUDU, AINULT OMA VASTUTUSEL. TEENUS, SELLE SISU JA KÕIK TEENUSED VÕI OBJEKTID, MIS ON SAADUD VEEBISAIDI JA LAIENDUSE TEEL, ON ESITATUD “NAGU ON” JA “NAGU SAADAVAL” TINGIMUSTEL, ILMA IGASUGUSE GARANTII TA. IGA TEENUSEGA SEOTUD ISIK EI ANNA MINGIT GARANTIID VÕI ESITUST SEOSES TEENUSE TÄIELIKKUSE, OHUTUSE, USALDUSVÄÄRSUSE, KVALITEEDI, TÄPSUSE VÕI KÄTTESAADAVUSEGA. ILMA ÜLE KUI EESPOOL, EI ANNA “CURSOR STYLE” EGA SELLEGA SEOTUD “CURSOR STYLE” ESINDAJAD EI GARANTEERI, ET SAIT, LAIENDUS, SELLE SISU VÕI MINGI REMONT PEAKS OLEMA VAREM KÄTTESAADAV, ON KORRAS, ET MEIE LAIENDUS, SAIT VÕI SERVER, MIS SEDA PAIGUTAB, ON ILMA VIIRUSTETA VÕI MUUDE KAHJULIKE KOMPONENTIDETA VÕI SEE VEEBISAIT VÕI MINGID TEENUSED VÕI OBJEKTID, MIDA TEHAKSE, ON EELISTATUD.
<p> MITTE MINGIL JUHUL EI VASTUTA TEENUS, SELLE PARTNERID VÕI LITSENTSIANDJAD, TEENUSED, TÖÖTAJAD, ESINDAJAD, AMETNIKUD VÕI JUHATUSE LIISIKUD MIS TAHES KAHJUDE EEST, MEIE TEENUS MINGI VASTUTUSEGA. VÕI SELLISTE MUUDE VEEBISAITIDE VÕI MINGI TEENUSE VÕI KAUBA EEST, MIS ON SAADUD TEENUSES VÕI MUUD VEEBISAIDIDEL, SEALHULGAS OTSESED, ERILISEVÕI JÄRGNEVAD KAHJUD, SEALHULGAS ISIKLIK VIGASTUS, EMOSHOKK, KAHJUD VÕI OODATAV SÄÄST, KASUTAMISE KAOTUS, ANDMED VÕI MUUD TINGIMUSED. MÄÄRATLUS EI MÕJUTA MINGIT VASTUTUST, MIDA EI VÕI VÄLISTADA VÕI PIIRATA VASTAVALT KOHALDATAVALE SEOONUSELE, MIS VÕIB SISALDADA PETTUST. </p>
<p> Te nõustute kaitsma, hüvitama ja summutama “Cursor Style\'i”, selle sidusettevõtteid, litsentsisaajaid ja teenusepakkujaid, samuti selle ja nende vastavaid ohvitsere, juhte, töötajaid, alltöövõtjaid, agente, litsentsisaajaid, tarnijaid, ülesandeid ja kõiki nõudeid ja kohustusi, kohtuotsuse kaotust, kulusid, kulutusi või komisjonitasusid (sealhulgas advokaatide tasusid), mis tulenevad või on seotud teie kasutustingimuste või teenuse kasutamise rikkumisega, sealhulgas, kuid mitte ainult, mis tahes sisu, teenuste ja veebisaidi või laienduste toodete kasutamise tagasilükkamine, välja arvatud juhul, kui see on nende kasutustingimustega selgelt ette nähtud, või teie poolt teenusest saadud teabe kasutamine. </p>
<p> Kui mõni nendest kasutustingimustest on kohtu või muu pädeva jurisdiktsiooni tribunaali poolt mis tahes põhjusel tühine, ebaseaduslik või jõustamatu, tuleks see säte tühistada või piirata miinimumini, et ülejäänud kasutustingimuste sätted jääksid täielikult kehtima. Kasutustingimused, meie privaatsuspoliitika ja tingimused sündmuste registreerimiseks moodustavad ainus ja täieliku kokkuleppe teie ja "Cursor Style" vahel seoses Teenusega ja asendavad kõiki varasemaid ja samaaegseid lepinguid, kokkuleppeid, esitusi ja garantiisid, nii kirjalikke kui ka suulisi, seoses Teenusega. </p>
<p> Kõik arvustused, kommentaarid, tehnilise toe taotlused ja muud Teenusega seotud sõnumid tuleks suunata Chrome\'i veebipoe "Cursor Style" tugilehele. </p> ',
];
