<?php

return [
    'halo_descr' => 'Halo este o franciză media de fantezie de luptă creată de Bungie. Bazată pe trilogia originală de jocuri video de tip first-person shooter. Plotul se învârte în jurul evenimentelor care au loc în viața lui Master Chief, unul dintre un grup de super-soldați cu numele de cod Spartans, și a însoțitorului său, inteligența artificială Cortana. Succesul jocurilor a dus la extinderea francizei în alte medii: universul Halo cuprinde în prezent multe cărți, romane grafice, benzi desenate, scurtmetraje, animații și filme de lung metraj.',
    'halo_short_descr' => 'Atinge cursorul artefact, poate ești alesul.',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'Păpușile LOL Surprise s-au îndrăgostit de copii și le-au cucerit inimile din primele minute. Și acest lucru nu este surprinzător, deoarece un astfel de succes se bazează pe o mister, așteptarea unui miracol, o surpriză plăcută, care încântă nu numai copiii, ci și părinții lor. Secretul cadoului este dezvăluit copilului doar după despachetarea finală. În orice caz, păpușile LOL sunt un design atractiv, intrigă, un număr mare de accesorii uimitoare și realiste și lucruri mici plăcute, precum și cea mai înaltă calitate a producției și detalierea jucăriei.',
    'lol_surprise_short_descr' => 'Cutie cool pentru cunoscătorii de surprize frumoase',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Serialul se învârte în jurul unui concurs în care 456 de jucători, care se află cu toții în datorii financiare mari, își riscă viața pentru a juca o serie de jocuri mortale pentru copii pentru șansa de a câștiga un premiu de un miliard. În interior, așteaptă un premiu tentant cu mize letale mari. Titlul serialului este inspirat de un joc pentru copii coreean cu un nume similar. Hwang a conceput ideea bazată pe propriile sale dificultăți economice la începutul vieții, precum și pe discrepanța de clasă din Coreea de Sud și capitalism.',
    'squid_game_short_descr' => 'Alege fața jucătorului potrivit când dai all-in',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter este protagonistul unei serii de romane de scriitoarea engleză JK Rowling. La a unsprezecea aniversare, Harry află că este un vrăjitor și este destinat unui loc la Hogwarts School of Wizardry, unde va practica magia sub îndrumarea directorului Albus Dumbledore și a altor profesori ai școlii. Harry descoperă, de asemenea, că este deja cunoscut în întreaga comunitate magică a romanului și că soarta lui este legată de soarta lui Voldemort, un magician întunecat periculos.',
    'harry_potter_short_descr' => 'Ce vei face cu o baghetă magică din colecția de cursoare Harry Potter',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics este o editură de benzi desenate, cunoscută pentru crearea de supereroi notabili precum Spider-Man, Iron Man, Captain America, Hulk, Thor, Răzbunătorii, Gardienii Galaxiei, X-Men, Fantastic Four și Deadpool. Principalii răufăcători Marvel includ Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom și Magneto. Marvel Comics și DC Comics au colaborat la mai multe proiecte crossover și au co-fondat, de asemenea, marca Amalgam Comics, intenționat de scurtă durată.',
    'marvel_comics_short_descr' => 'Supereroul trăiește în fiecare dintre noi - alege-l pe al tău',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Bine ai revenit în Regatul Cookie în Cookie Run: Kingdom de la Devsisters, adorabilul RPG de strategie plasat în universul Cookie Run. Acum că Omul de Turtă Dulce a scăpat de cuptorul vrăjitoarei rele, este timpul să își construiască o echipă de Cookie-uri și să pornească într-o călătorie pentru a reconstrui Regatul Cookie căzut. Descoperă adevărul din spatele căderii Regatului și formează o echipă cu cele mai puternice Cookie-uri ale Regatului pentru a învinge forțele întunecate care vor să-l oprească pe Omul de Turtă Dulce să-și împlinească destinul.',
    'cookie_run_kingdom_short_descr' => 'Mici războinici scoși direct din cuptor',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact este un joc de aventură open world. Asta înseamnă că o nouă, încântătoare peisaj vă așteaptă pe cealaltă parte a râului sau muntelui, trebuie doar să vă folosiți energia cu înțelepciune. Dacă dați peste o zână rătăcitoare sau un mecanism ciudat, îndrăzniți și încercați să le dezlegați misterul. Dar ce promit acestea - necazuri sau o surpriză plăcută - doar voi puteți afla! Pe vastul continent Teyvat, veți vizita șapte regate, veți găsi însoțitori cu diverse abilități și veți lupta împotriva inamicilor puternici în căutarea unei persoane dragi dispărute.',
    'genshin_impact_short_descr' => 'Deveniți Maestrul Elemental al Celor Șapte Regate',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Când o profeție antică devine realitate și regatul se prăbușește în brațele iernii, trei eroi neînfricați - Prințesa Anna, curajosul Kristoff și renul său credincios Sven - merg la munți pentru a o găsi pe sora Annei, Elsa, care poate înlătura vraja înghețată de pe țară. Pe parcurs, multe surprize dificile și aventuri palpitante îi așteaptă. Întâlnirea cu troli mistici, întâlnirea cu un om de zăpadă fermecător pe nume Olaf, vârfuri de munte mai abrupte decât Everestul și multă magie. Eroii trebuie să reziste elementelor puternice pentru a salva regatul și pe cei dragi lor.',
    'frozen_short_descr' => 'Spargerea gheții este ușoară cu colecția de cursoare Frozen',
    'frozen' => 'Frozen',
    'stranger_things_descr' => 'Au trecut puțin mai mult de șase luni de la finalul sezonului trei. Joyce, Will, Eleven și Jonathan s-au mutat în California, unde fata este hărțuită la școală. Restul încep să lupte cu un nou monstru dintr-o lume paralelă care a apărut în Hawkins. El a fost numit Vecna ​​după personajul jocului de masă Dungeons & Dragons. Afectează adolescenții psihologic, apoi urcă mental în cap și ucide. În paralel, Joyce și Murray află că Jim Gopper este viu și merg după el într-o închisoare sovietică din Kamchatka. Și Eleven va trebui să se întoarcă și să-și crească puterile, dar și să-și învețe rolul important în crearea aceluiași monstru în Gokins.

Scriitorii nu au schimbat tacticile complotului care le-au plăcut în ultimele sezoane. În cel de-al patrulea sezon, au împărțit grupul mare de personaje principale în grupuri, au venit cu sarcini dificile pentru ei și, la final, și-au construit poveștile împreună într-un final uimitor. Vă oferim să înțelegeți în detaliu toate aceste aventuri cu ajutorul colecției de cursoare Stranger Things.',
    'stranger_things_short_descr' => 'Ce se va întâmpla în continuare? - Cursoare Stranger Things 4',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars este un mod original care a apărut pentru prima dată în Minecraft. Sarcina jucătorilor era ca utilizatorul să-și protejeze baza și patul.

Roblox aduce jocuri mai interesante în fiecare zi, iar BedWars nu face excepție. Și ideea este că, dacă iubești Bed Wars și te aperi în camera ta, acesta este titlul pentru tine, deoarece te duce înapoi la copilărie, deși digital de data aceasta.

Tot ce trebuie să faci este să-ți aperi patul de atacatori cu partenerul tău. Intri într-un lobby, alegi cu cine să te joci și voila, este doar o chestiune de protecție.

Desigur, când vine vorba de apărare, vei avea unele probleme și există anumite resurse, articole și obiecte care te vor ajuta să câștigi. De exemplu, skin-uri exclusive pe care le vei găsi în colecția de cursore Bed Wars.',
    'roblox_bed_wars_short_descr' => 'Protejează-ți patul cu cursoare Roblox Bed Wars',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'De ziua de naștere a lui Naruto Uzumaki, un demon legendar, Vulpea cu Nouă Cozi, a atacat un sat numit Konoha. Al Patrulea Hokage, cu prețul vieții sale, a salvat satul sigilând demonul în nou-născutul Naruto, condamnându-l fără să știe la o viață de ură din partea sătenilor săi.
În ciuda lipsei sale de talent în multe domenii ale ninjutsu-ului, a neliniștii și a aroganței, Naruto are un vis de a deveni Hokage, cel mai puternic ninja din sat. Dorind recunoașterea pe care nu a primit-o, el muncește din greu și se antrenează alături de coechipierii săi Sasuke Uchiha și Sakura Haruno, precum și de mentorul său Kakashi Hatake. El și partenerii săi vor trebui să treacă prin multe pe drumul spre visele lor dragi: bătălii, dragoste, prietenie, trădare, sete de putere. O colecție de cursoare anime Naruto vă va ajuta să vă navigați propria cale!',
    'naruto_anime_short_descr' => 'Pășește pe calea ta ninja cu cursoarele anime Naruto',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'Acțiunea are loc în timpul erei Taisho. Din cele mai vechi timpuri, au existat zvonuri că demoni umanoizi trăiesc în pădure, care se hrănesc cu oameni și umblă noaptea, căutând o nouă victimă. Dar... este doar o legendă, nu?

Tanjiro Kamado este fiul cel mare din familie, care și-a pierdut tatăl și a avut grijă de familia sa. Într-o zi, merge într-un oraș din apropiere pentru a vinde cărbune. Întorcându-se dimineața, băiatul descoperă o imagine teribilă în fața lui: toți rudele au fost uciși cu brutalitate, iar singura supraviețuitoare este Nezuko, o soră mai mică transformată într-un demon, dar care nu și-a pierdut încă toată umanitatea.

Din acest moment, Tanjiro și Nezuko încep o călătorie lungă și periculoasă, în care băiatul intenționează să găsească ucigașul și să găsească o modalitate de a-și vindeca sora. Dar sunt copiii capabili să depășească toate dificultățile și să se întoarcă acasă? Știți deja răspunsul, iar dacă nu - mai degrabă setați cursoarele Demon Slayer, cu personaje din una dintre cele mai populare manga.',
    'demon_slayer_anime_short_descr' => 'Cursori Demon Slayer - pentru adevărații vânători de noapte',
    'demon_slayer_anime' => 'Anime Demon Slayer',
    'bts_descr' => 'BTS este un grup format din șapte membri sub conducerea BigHit Music. Au debutat pe 13 iunie 2013 cu single-ul "No More Dream". În Japonia, au debutat pe 24 decembrie 2014 cu albumul de studio Wake Up.

Numele grupului provine din expresia coreeană Bangtan Sonyeondan, care înseamnă "scouți de băieți antiglonț". Conform lui J Hope, numele semnifică dorința trupei de a bloca stereotipurile, criticile și așteptările care sunt îndreptate către adolescenți ca gloanțele.

Colecția de cursoare dedicate grupului îi include pe toți membrii grupului, aici cursorul Kim Nam Joon (alias RM), cursorul Kim Seok Jin (Jin), cursorul Min Yoongi (Suga), cursorul Jung Ho Suk (J-Hope), cursorul Park Ji Min (Jimin), cursorul Kim Tae Hyun (V) și cursorul Jeon Jungkook (Jungkook).',
    'bts_short_descr' => 'Întâlnește-ți idolii cu cursoarele BTS',
    'bts' => 'BTS',
    'miraculous_descr' => 'Miraculous: Aventurile Buburuzei și Motanului Noir, mai bine cunoscut sub numele de Miraculous Buburuza și Motan Noir, sunt aventurile supereroilor din desenul animat despre doi colegi de clasă care, sub măști, joacă rolul de apărători ai Parisului de un personaj negativ care, în fiecare episod, găsește o nouă modalitate de a face rău orașului. Miraculous este realizat în Franța folosind CGI și animație. Miraculous nu este doar un serial animat, ci și o colecție de benzi desenate lansate în întreaga lume. Serialul este foarte iubit de tineri.

Acțiunea are loc în Paris, unde Marinette și Adrian sunt elevi de liceu într-o școală modernă. Li s-a dat rolul de a deveni cei aleși în lupta împotriva răului, salvând orașul natal. Scopul lor este de a proteja oamenii de Akuma. Aceste mici creaturi sub formă de fluturi sunt capabile să locuiască o persoană și să o transforme într-un personaj negativ.

Marinette se poate transforma într-o buburuză, iar Adrian - într-un Motan Noir, dar, surprinzător, lucrând în perechi, nu se recunosc unul pe celălalt sub măștile de supereroi.

Ajutați Motanul Noir și Buburuza să salveze Parisul cu cursoarele noastre cu personajele preferate. Ce personaj veți alege pentru cursor? Va fi un cursor Miraculous Buburuza sau poate adorabila Buburuză Tikki sau cursorul Motan Noir? Sau poate o Regina Albinelor cu cursoare Rena Rouge? Alegerea este a ta!',
    'miraculous_short_descr' => 'Alăturați-vă rândurilor supereroilor cu colecția de cursoare Lady Bug și Cat Noir',
    'miraculous' => 'Miraculous: Poveștile Buburuzei și Motanului Noir',
    'talking_tom_descr' => 'Seria urmărește viața de zi cu zi a lui Talking Tom și a prietenilor săi. Tom și partenerul său de afaceri, tocilarul Ben, dezvoltă în mod constant aplicații mobile și alte invenții pentru a obține faimă și avere și încearcă să se arate lumii, dar acest lucru se întoarce întotdeauna împotriva lor. Iubita lui Tom, Angela, încearcă să fie cântăreață, indiferent de ceea ce face pentru a reuși. Vecinul lui Tom, Ginger, apare foarte des aici pentru a face farse cu răutate sub mânecă. Cel mai bun prieten prost și coleg de cameră Hank este casnic, se uită la FOARTE MULT TV. Iar fosta vedetă pop disidentă Becca Sparkles a devenit noua colegă de cameră a Angelei și pare să se fi îndrăgostit de Hank. Cu toate acestea, indiferent cât de proaste sunt lucrurile de toate formele și mărimile, fie că este vorba de CEO-ul malefic, de noul vecin misterios al lui Tom sau doar de un accident în noua creație a lui Ben, gașca se va distra indiferent de ce, și își va aminti mereu un singur lucru care îi ține împreună: prietenia nu se termină niciodată, la fel cum nu se termină nici dragostea noastră pentru personajele seriei, așa că acum vă puteți seta cursorul Talking Tom sau cursorul Ben, sau poate cursorul Angela, cursorul Oliver!',
    'talking_tom_short_descr' => 'Să vorbim despre personajul tău preferat din Colecția de cursoare Talking Tom',
    'talking_tom' => 'Talking Tom și Prietenii',
    'lego_descr' => 'Compania LEGO Group a fost fondată în 1932 și atunci era formată din doar 7 persoane. Scopul echipei Lego a fost de a crea jucării care să dezvolte creativitatea, imaginația și ingeniozitatea unui copil. Un fapt uimitor, de la înființarea sa în 1949, elementele LEGO în toate variantele lor au rămas compatibile între ele. Toate articolele create ulterior sunt încă compatibile cu articolele care sunt lansate astăzi, în ciuda modificărilor de design și formă de-a lungul anilor.

O cărămidă LEGO este o bază, care este un bloc de plastic gol care se conectează la alte cărămizi similare. Dar seturile Lego conțin și alte piese, roți, figurine, platforme și chiar circuite electronice cu senzori și motoare electrice. Puteți colecta modele de mașini, avioane, trenuri, nave, clădiri, roboți. LEGO aderă la ideea de modularitate, ceea ce demonstrează clar copiilor cum să rezolve anumite probleme, să dezvolte imaginația, abilitățile motorii fine ale mâinilor și abilitățile de asamblare. Cărămizile LEGO sunt fabricate cu o precizie incredibilă și se potrivesc perfect pentru o precizie uimitoare de 10 microni.

Recent, au fost create multe povești Lego animate 3D populare, în care personajele din seturi prind viață și devin participanți la aventuri incredibile. Dacă doriți un cursor cool, veți găsi multe personaje din serialele TV Lego și filmele de animație în colecția noastră de Cursori Lego. Cursor Lego Ninjago, Cursor Lego Batman, Cursor Lego Ninjago, Cursor Lego Wyldstyle și multe altele.',
    'lego_short_descr' => 'Construiți-vă browserul de vis cu colecția de cursoare Lego',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'După finanțarea Kickstarter de succes, în 2017, Team Cherry a lansat jocul multiplatformă pentru PC Hollow Knight. Aceasta este povestea unui cavaler fără nume și a descoperirilor sale în regatul insectelor Hallownest. Jocul a fost pe bună dreptate recunoscut ca fiind unul dintre cele mai bune din genul metroidvania.

Modul de joc al lui Hollow Knight se bazează pe explorarea lumii jocului. Depășirea obstacolelor, rezolvarea puzzle-urilor și găsirea secretelor, precum și lupta cu inamicii. Jucătorul are un set unic de îmbunătățiri și trucuri pentru explorarea lumii și lupta în bătălii. Trecând dintr-o zonă în alta, jucătorul învinge șefii și obține îmbunătățirile necesare pentru a avansa mai departe. Drept urmare, jucătorii trebuie să viziteze zonele deja parcurse pentru a găsi secrete și a parcurge povestea. Și este, de asemenea, interesant pentru că zonele se schimbă de fiecare dată, aducând surprize și experiențe noi. Jocul poate fi jucat în diferite moduri, deoarece există mai multe căi diferite între zone. Trecând prin poveste, deschizi harta zonei, dar mai întâi trebuie să obții harta.

Principala armă a eroului este un cui, care este oarecum similar cu o sabie, armele pot fi îmbunătățite cu un fierar, precum și să învețe diferite abilități în utilizarea armelor, ceea ce extinde varietatea atacurilor. Atacând inamicii, acumulezi o resursă specială, care poate fi utilizată ulterior pentru îmbunătățiri sau vindecare.
Distrează-te jucând Hollow Knight și nu uita să folosești cursoarele noastre Hollow Knight cu personajul tău preferat. Colecția noastră include Cursorul Mister Mushroom, Cursorul Quirrel, Cursorul Hornet Needle, Cursorul Old Nail, Cursorul Myla și altele.',
    'hollow-knight_short_descr' => 'Încearcă să nu te pierzi în regatul insectelor folosind colecția de cursuri Hollow Knight',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman este personajul principal din serie. Stikmin, anterior fără nume, a început ca un hoț minor, cu dorința de a face bani ușori rapid. Cu toate acestea, după ce a evadat din închisoarea West Mesa, multe schimbări au loc în viața lui și devine un criminal celebru după ce fură Diamantul Tunisian. Henry are de ales - să devină un agent guvernamental de succes, un vânător de recompense, liderul unei organizații criminale, un cyborg sau să continue calea criminală singur. Jocul încântă fanii genului cu multe aventuri și mistere, și veți găsi noua noastră colecție de cursuri Henry Stickman cu personajele sale amuzante, inclusiv cursorul Henry Stickmin, cursorul Charles Calvin, cursorul Reginald Copperbottom, cursorul Right Hand, cursorul Ellie Rose și altele!',
    'henry-stickmin_short_descr' => 'Planifică-ți evadarea din plictiseală cu Colecția de cursoare Henry Stickman',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'Jocul online foarte popular Adopt Me a fost lansat în 2017 și a devenit cel mai popular pe platforma de jocuri Roblox. Esența jocului este foarte simplă - obține ouă cu animale de companie și ai grijă de ele.

Animalele de companie virtuale sunt împărțite în 5 clase, unele dintre ele sunt foarte rare și scumpe, în timp ce altele sunt foarte ușor de obținut. Acestea sunt grupuri Neobișnuite, cum ar fi Câinele Albastru, cursul Comun, Rar, de exemplu, cursorul de mouse Adopt Me Monkey, precum și cele ultra-rare, cum ar fi cursorul Koala și cursorul Legendar, Dragon și Unicorn Adopt Me. Dacă jucătorul are patru animale de companie adulte de același tip, le poate combina într-un animal de companie neon, cum ar fi cursul de joc Neon Horse sau Adopt Me Neon Starfish. Combinând patru animale de companie obișnuite, poți face un animal de companie neon care strălucește cu adevărat, iar din animalele de companie neon poți crea un animal de companie mega-neon.

Cumpărăturile în jocul Adopt Me! sunt efectuate cu moneda virtuală Roblox - așa-numitul Robux, iar jocul are, de asemenea, propria sa monedă - Bucks. Având grijă de animalul tău de companie, pe lângă divertisment, poți câștiga dolari, doar hrănește-l, pune-l la culcare sau citește-i o poveste, în general, o mulțime de lucruri interesante.

Acum, fanii jocului Roblox "Adopt Me!" își pot decora cursorul de joc cu animalul de companie preferat!',
    'adopt-me_short_descr' => 'Distrați-vă cu animale de companie drăguțe în colecția noastră Adopt Me! de cursuri de joc',
    'adopt-me' => 'Adopt me!',
    'among-us_descr' => 'Among Us este bazat pe celebrul joc de rol "Mafia". S-a planificat ca versiunea inițială a jocului să fie exclusivă pentru dispozitivele mobile, deoarece avea o singură hartă. Jocul a devenit rapid popular. Ulterior, echipa de dezvoltare a adăugat un mod multiplayer, iar în 2019 au fost lansate două hărți suplimentare.
Among Us este un joc văzut de sus în perspectiva a treia persoană, care permite jucătorului să se miște în toate direcțiile. De la patru la zece jucători pot juca într-o rundă. La începutul jocului, fiecare este secret atribuit rolul de trădător sau membru al echipajului. Impostor (în traducerea rusă "Trădător") se poate ascunde în gurile de ventilație, sabota și ucide membrii echipajului. Scopul său este de a distruge toți membrii echipajului sau de a distruge nava spațială prin sabotaj. Scopul echipajului navei este de a rezolva diverse puzzle-uri pregătite pentru ei la începutul jocului. Dacă fiecare dintre membrii echipajului își îndeplinește toate sarcinile, trădătorii vor pierde. De asemenea, echipajul navei poate obține victoria eliminând trădătorii în timpul votului.
Trădătorii pot sabota din când în când, iar dacă defecțiunile nu sunt remediate în 30 de secunde, echipajul va pierde. Înainte de a începe jocul, poți alege culoarea personajului pentru care joci, albastru, roșu, galben, gri - orice! Și nu uita să-ți setezi cursorul corespunzător din noua colecție Among Us!',
    'among-us_short_descr' => 'Nu te lăsa păcălit în acest joc spațial complicat cu cursoarele Among Us.',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Creatorul serialului "Steven Universe" a fost Rebecca Sugar. Ea este cunoscută pentru munca ei anterioară, numită Adventure Time. Primul episod al serialului Steven Universe a fost lansat pe platforma video YouTube în primăvara anului 2013. Dar în toamnă, canalul american Cartoon Network a început să-l difuzeze pentru telespectatorii săi. De atunci, au fost lansate 6 sezoane. Al șaselea promite să fie final.
În ceea ce privește intriga serialului de animație, aceasta se învârte în jurul echipei Crystal Gems. Aceasta este alcătuită din creaturi extraterestre cu nume caracteristice: Pearls, Amethyst și Pomegranate. Dar mai este un participant, în rolul căruia acționează un băiat obișnuit, Stephen. Împreună, ei caută monștri și încearcă să-i neutralizeze, astfel încât aceștia să nu preia controlul Pământului pentru câștig personal. Li se opun Jasper și Peridot - mesageri de pe planeta lor natală care vor să învingă Gems și să pornească Cluster.
Dacă ești fan Steven Universe și vrei să vezi personajele serialului de animație oriunde poți, instalează extensia Cursor Style! De ce să faci asta? Poți adăuga o colecție dedicată serialului "Steven Universe" și să transformi indicatorul standard al mouse-ului într-unul dintre personajele tale preferate.',
    'steven_universe_short_descr' => 'Descoperiți secretul gemelor cu cursoarele Steven Universe',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Un sitcom animat numit "Family Guy" în întreaga istorie a existenței sale a câștigat de 4 ori premiul Emmy și de 3 ori "Annie". Seria animată ridiculizează subiectele sensibile ale societății americane, cum ar fi: feminismul, sclavia, obezitatea, politica etc. Spre deosebire de alte lucrări, inserțiile cu glume și sarcasm sunt folosite aici. Mai mult, în multe cazuri, acestea nu sunt integrate în complot, ci există de la sine.
Un episod din seria animată este creat în peste 10 luni. De ce atât de mult? Pentru că întreaga animație este desenată manual. Din această cauză, unele dintre evenimentele acoperite de lucrare au timp să-și piardă relevanța. Dar chiar și așa, sitcomul rămâne foarte interesant și câștigă favoarea spectatorilor din întreaga lume. La urma urmei, cui nu-i place să râdă bine de politicieni, celebrități sau oameni care comit șotii sălbatice și, prin urmare, surprind sau chiar șochează oamenii obișnuiți.
Îți place "Family Guy"? Ai o oportunitate unică de a transforma un cursor normal al mouse-ului în oricare dintre personajele acestei serii animate! Ce trebuie să fac? Doar instalați extensia de browser “Cursor Style”, adăugați-i o colecție dedicată lui “Family Guy” și bucurați-vă de o reîncarnare fabuloasă!',
    'family_guy_short_descr' => 'Colecție de cursoare Family Guy pentru cunoscătorii de umor special.',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Cu siguranță ați auzit expresia "Frumusețea va salva lumea"? Deci, mulți oameni, în special fetele, sunt de acord cu această afirmație. Prin urmare, se străduiesc să se înconjoare cu tot ce este mai frumos și plăcut ochiului. Poate fi tapet roz în dormitor, jucării moi, perne brodate cu mărgele, bijuterii prețioase etc. Din exterior, totul arată foarte drăguț și chiar un pic copilăresc. Dar fiecare dintre noi este un mic copil în inimile noastre, deci de ce să nu-l lăsăm să-și arate imaginația?
Ne poate provoca tandrețe o mulțime de lucruri. De exemplu, ochii compătimitori ai unei pisici care vrea să fie mângâiată sau hrănită. Un curcubeu multicolor, care apare după o ploaie de primăvară și strălucește cu toate culorile în soare. Copilul căruia i s-a oferit ciocolată și a decis să o împartă cu prietena sau prietenul său. Există destul de multe motive pentru emoție și am decis să le folosim ca cursoare.
Te-ai săturat de săgeata albă plictisitoare din browserul tău? Înlocuiește-o cu ceva drăguț din colecția noastră! De exemplu, un unicorn roz și alb, o roșie tristă, un nor posomorât, un cactus țepos în formă de pisică sau orice dorești. Tot ce trebuie să faci este să instalezi extensia Cursor Style și să adaugi o colecție de cursoare drăguțe la ea. Și trăiască salvatorul lumii -frumusețea!',
    'cute_cursors_short_descr' => 'Lumea va fi mai bună cu colecția de cursoare drăguțe',
    'cute_cursors' => 'Cursoare Drăguțe',
    'web_media_descr' => 'În realitățile moderne, aproape toată lumea folosește Internetul. Începând de la copii mici și terminând cu pensionarii. Cineva navighează folosind un browser, altcineva vizionează videoclipuri pe YouTube, iar altcineva are nevoie de Rețea pentru a comunica cu cei dragi. Oricare dintre acești utilizatori nu își poate imagina o zi fără World Wide Web.
Oamenii mai în vârstă stau adesea pe o rețea socială precum Facebook sau VK. De asemenea, comunică adesea cu copiii și nepoții lor pe Skype. Acest lucru este deosebit de convenabil dacă copiii și părinții locuiesc în orașe diferite sau chiar în țări diferite.
Tinerii preferă să comunice prin Viber sau Telegram, să încarce fotografii pe Instagram, să râdă la memele FB. Videoclipurile de pe YouTube cu reacțiile oamenilor câștigă milioane de vizualizări, la fel ca diverse farse sau experimente sociale. În Tik-Tok, sute de mii de oameni dansează, arată trucuri de magie și se exprimă.
Sunteți interesat sau folosiți adesea un fel de resursă din sfera media web? Vrei să scapi de săgeata plictisitoare a mouse-ului din browserul tău? Atunci instalează extensia și schimbă cursorul implicit cu cel creativ al nostru! Poate fi un cursor YouTube, cursor Viber, cursor Google Chrome sau alte resurse.',
    'web_media_short_descr' => 'Trăiește într-un ritm modern cu colecția de cursoare web media',
    'web_media' => 'Web Media',
    'bobs_burgers_descr' => 'Seria animată Bob’s Burgers este intriga muncii de animație și carisma personajelor. Și, judecând după nominalizarea la Premiul Emmy și recunoașterea muncii ca fiind unul dintre cele mai bune desene animate din întreaga lume, Bob\'s Snack a făcut cu adevărat furori.
Intriga seriei animate se învârte în jurul familiei Bob Belcher. Această persoană este proprietarul unei cafenele la primul etaj, iar la al doilea etaj locuiește cu cei dragi. Bob are o soție veselă, Linda, și 3 copii: Gene, Louise și Tina. Băiatul visează la o carieră muzicală, fiica cea mare Tina este foarte amabilă, dar stângace, iar cea mai mică - Louise este încă o ștrengăriță și adesea își pune familia într-o poziție inconfortabilă. Principalul concurent al lui Bob’s Burgers este Pizzeria Jimmy Pesto. După cum ați putea ghici, proprietarul acestei pizzerii se numește Jim, iar el și Bob se urăsc. Toate acestea au fost bătute astfel încât să pară comice, nu serioase. Prin urmare, multe dintre înfruntările lor provoacă doar un zâmbet.
Dacă iubiți seria animată „Bob\'s Burgers” și doriți să vedeți personajele sale nu doar pe ecranul monitorului sau al televizorului, instalați extensia, adăugați o colecție și schimbați cursorul mouse-ului din browser cu oricare dintre personajele din acest desen animat!',
    'bobs_burgers_short_descr' => 'Bob face burgeri, iar noi facem cursoare Bob\'s Burgers',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'Istoria jocului video "Kirby" a început deja în anii \'90 ai secolului trecut. Acesta constă din multe serii care au fost dezvoltate de Nintendo și HAL Laboratory. Jocul este destinat copiilor de la un an și jumătate până la 8 ani. Popularitatea sa poate fi judecată după numărul de exemplare vândute. Peste 34 de milioane în întreaga lume.
Personajul principal al lui Kirby este creatura roz omonimă. Trăiește pe o planetă numită Pop Star și o protejează periodic de diverse pericole. Kerby poate respira în unele obiecte și inamicii săi pentru a învăța apoi abilitățile lor: lupta corp la corp, posesia unei săbii, respirația de foc etc. Cu toate acestea, pufosul roz nu numai că se luptă cu inamicii, ci și rezolvă diverse puzzle-uri, călătorește în alte țări și poate chiar zbura în nivel.
Puteți juca acest joc video pe console Nintendo sau Game Boy. În toate seriile sunt eroi drăguți, grafică bună și coloane sonore amuzante. Apropo, de aproape 30 de ani de la lansarea primei versiuni, lumea a reușit să vadă 20 de serii Kirby. Acest indicator, împreună cu volumul de milioane de dolari de exemplare vândute, a ajutat jocul să fie în TOP 50 al celor mai de succes și căutate jocuri video din industria jocurilor.
Îți place Kirby încât ai dori să vezi acest personaj oriunde este posibil? Atunci folosește colecția Kirby și transformă indicatorul normal al mouse-ului în personajul principal al jocului tău video preferat! Suntem siguri că îți va plăcea noua înfățișare a cursorului.',
    'kirby_short_descr' => 'Încearcă să inhalezi întreaga colecție de cursoare Kirby',
    'kirby' => 'Kirby',
    'undertale_descr' => 'În vremuri străvechi, Pământul era locuit nu numai de oameni, ci și de monștri. Din cauza neînțelegerilor dintre ei, a izbucnit un război, care s-a încheiat în favoarea rasei umane. Șapte magicieni au alungat monștrii sub pământ și i-au închis acolo pentru totdeauna cu o vrajă de barieră. Cu toate acestea, exista o singură intrare în Muntele Ebott, de care a profitat copilul. Pentru el veți juca rulând jocul pe calculator Undertale.
Acest joc a fost dezvoltat de Toby Fox - un programator binecunoscut din Statele Unite. La început, proprietarii de computere personale care rulează Microsoft Windows și Linux OS s-au putut bucura de el, apoi a venit rândul utilizatorilor de console de jocuri.
Care este ideea acestui joc? Băiatul călătorește prin lumea subterană locuită de monștri. Unii dintre ei sunt imediat ostili, în timp ce alții le place să vorbească. Jucătorul poate alege unul dintre cele 2 comportamente: evită violența sau luptă. În primul caz, trecerea jocului va fi mai ușoară, în al doilea - dimpotrivă, este mai dificil. De această alegere depind și complotul și finalul, care se pot ramifica și schimba.
Dacă vă place Underground Tale și doriți să vedeți personajele sale în browserul dvs., instalați extensia și adăugați colecția corespunzătoare de cursoare! Schimbați un indicator de mouse plictisitor într-unul dintre monștrii sau personajul principal al Undertale!',
    'undertale_short_descr' => 'Este timpul să ieși din groapă folosind cursoarele din Undertale',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune este un joc de rol lansat pentru computere acum câțiva ani. A fost creat de același programator care a dezvoltat Undertale. Cu toate acestea, cele două jocuri nu sunt aproape deloc asemănătoare, deși au câteva personaje și locații comune.
Există mai multe personaje principale în Delta Rune. Acesta este un elev Chris, care poate fi controlat, și un monstru fermecător Susie, incontrolabil. Ambele personaje cad în lumea întunericului, unde îl întâlnesc pe unul dintre locuitorii săi - Ralsay. El le spune că, de fapt, sunt creaturi de lumină care au o misiune - să oprească fluxul de energie întunecată într-o lume sumbră. Pentru a face asta, trebuie să cruțe monștrii locali și să încerce să nu se angajeze în luptă cu ei, deși acest lucru este uneori destul de dificil de făcut.
Jucătorul are o alegere simplă: fie cruță creaturile întunecate, fie le atacă. Deoarece Susie nu este fanul măsurilor pe jumătate, în multe cazuri ea alege o luptă. Prin urmare, Chris nu are de ales decât să-și susțină iubita și să o ajute în bătălii.
Iubești jocul Deltarune? Atunci stilizează-ți cursorul mouse-ului în browser pentru unul dintre personajele ei! Poți face asta cu extensia noastră. Instalează-l, adaugă colecția „Rune Delta” și activează! Acum săgeata ta a încetat să mai fie la fel ca toți ceilalți și a devenit Chris, Susie sau una dintre creaturile lumii întunecate.',
    'deltarune_short_descr' => 'Scufundă-te în lumea întunecată cu această colecție de cursoare',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario este o serie de jocuri pe calculator lansate de Nintendo. Primul și cel mai popular joc se numea Super Mario Bros. A văzut lumina zilei în 1985. Ulterior, a fost listat în Cartea Recordurilor Guinness. De atunci, au fost lansate peste 20 de jocuri, fiecare dintre ele având propria poveste. În 2019, a apărut o nouă versiune numită Super Mario Maker 2. În ciuda îmbunătățirii graficii, stilul și personajele au rămas aceleași, iar acest lucru evocă nostalgie pentru Super Mario din anii 80.
Personajul principal este încă instalatorul Mario. În intriga ultimei variații a jocului, castelul Prințesei nu a avut piatră neîntoarsă. Mario trebuie să-l reconstruiască, câștigând în prealabil monedele care îi sunt plătite pentru sarcini. În total, acest joc are peste 100 de niveluri de complexitate variată, cu posibilitatea de modificare. De asemenea, în Super Mario Maker 2 există noi moduri de joc. Puteți juca patru dintre ele simultan și, de îndată ce unul se termină, nivelul este considerat finalizat. Există, de asemenea, moduri precum: Maratoanele lui Mario, Duel și cursele Ninjik.
Adorați Super Mario și tot ce este legat de acest joc minunat? Atunci setați cursoarele realizate în stilul acestui platformer! Suntem siguri că vă vor plăcea cursorul Mario, cursorul Luigi, cursorul Prințesei Peach și alte cursoare care sunt prezentate în colecția noastră!',
    'super_mario_short_descr' => 'Treceți prin regatul ciupercilor cu colecția de cursoare Super Mario',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls a fost creat în comun de către Disney Television Animation Corporation și Alex Hirsch. Premiera a fost lansată în 2012 și a fost difuzată pe Disney Channel. Întregul prim sezon al serialului de animație s-a rotit acolo. Doi ani mai târziu, a fost lansat cel de-al doilea sezon, pe care telespectatorii l-au putut urmări pe canalul anterior și pe Disney XD. Din păcate, fanii Gravity Falls nu au așteptat al treilea și sezoanele ulterioare. Creatorii au decis să se limiteze la două sezoane fără nicio continuare.
În ceea ce privește intriga acestei imagini animate, atunci toată acțiunea are loc într-un oraș fictiv numit Gravity Falls. Doi gemeni vin acolo, ai căror nume sunt Mabel și Dipper. Ei stau cu vărul lor Stan. El are propriul său magazin de suveniruri turistice. Când frații se plictisesc de "a nu face nimic", merg în căutare de aventură. Unul dintre ei găsește un jurnal ciudat în pădure, care povestește despre anomaliile acestui oraș. Gemenii pornesc în căutarea autorului său și întâlnesc creaturi și locuri neobișnuite. Dacă sunteți interesați de acest serial animat și ați fost cândva fani ai personajelor sale, vă recomandăm colecția noastră de cursoare de mouse în stilul Gravity Falls!',
    'gravity_falls_short_descr' => 'Pornește într-o aventură cu cursoare Gravity Falls',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Absolut toată lumea a auzit de o serie animată atât de celebră precum The Simpsons. Chiar și cei care nu s-au uitat la ea sunt conștienți de existența personajelor galbene. Iar fanii sunt încântați când apare următorul sezon al desenului lor animat preferat. Apropo, în toamna lui 2019, au fost lansate 31 de sezoane. Iar primul a apărut pe ecranele televizoarelor în 1989. Fox a început să-l arate și continuă să o facă datorită ratingurilor ridicate și simpatiei publicului.
 The Simpsons este un gen satiric care abordează subiecte relevante. Acesta poate fi stilul de viață al americanului de rând, probleme politice și religioase, trucurile „stelare” ale celebrităților, feminismul, căsătoriile între persoane de același sex. În general, tot ce ține de evenimentele locale și globale la care participă Statele Unite.
 Acțiunea seriei de animație are loc în orașul inexistent Springfield. De fapt, există o mulțime de orașe cu acest nume în America. Poate că de aceea a fost ales, astfel încât publicul să nu asocieze ceea ce se întâmplă pe ecrane cu o localitate specifică, ci doar să ghicească unde ar putea fi asta.
 Cel mai probabil ești un fan al lui The Simpsons. Altfel, de ce ai citi acest text până la capăt? Și dacă este așa, atunci ai ocazia să schimbi cursorul plictisitor al mouse-ului cu un indicator realizat în stilul acestei serii animate.',
    'simpsons_short_descr' => 'O familie mică și amuzantă cu cursuri Simpsons',
    'simpsons' => 'The Simpsons',
    'youtubers_descr' => 'Platforma video YouTube a apărut în 2005. La început, videoclipuri au fost publicate acolo doar de dragul auto-exprimării sau informării despre ceva. Cu toate acestea, de-a lungul timpului, toate acestea au crescut într-o afacere profitabilă, care aduce mii și, uneori, milioane de dolari pe lună utilizatorilor YouTube de succes. Cu cât vloggerul (persoana care conduce blogul video) este mai popular, cu atât poate câștiga mai mult prin canalul său.
Cât câștigă o fetiță vlogger de cinci ani, ai cărei părinți o duc la cele mai interesante atracții și filmează ce se întâmplă pe cameră? Este doar modul în care un copil se distrează în parcurile pentru copii, care exprimă emoții, cum să facă prostii și toate celelalte. Suma este cu adevărat uimitoare - astăzi, canalul copilului a câștigat aproape 47 de milioane de abonați și a început să genereze venituri în valoare de 5 milioane de ruble pe lună.
Cineva încarcă videoclipuri în care discută jocuri pe calculator, cineva face beatbox sau aranjează farse trecătorilor pe stradă. Unii își dedică videoclipurile unor subiecte sensibile, cum ar fi relația dintre bărbați și femei. Cu cât utilizatorii YouTube apreciază mai mult aceste filmări, cu atât este mai mare popularitatea vloggerului.
Colecția a adăugat deja cursorul PewDiePie, cursorul Shane Dawson, cursorul Ray William Johnson, cursorul Zoella, cursorul MyLifeAsEva și altele.',
    'youtubers_short_descr' => 'O nouă generație de vedete este mereu online în colecția noastră YouTubers',
    'youtubers' => 'YouTubers',
    'pusheen_descr' => 'Aproape toată lumea cunoaște pisica Pusheen. Chiar dacă este doar un personaj dintr-o carte de benzi desenate pentru copii inventată acum 10 ani, are milioane de fani astăzi. Pisica Pusheen a apărut ca o ilustrație creată de artista Claire Belton.
Un an mai târziu, pisica și-a dobândit propria pagină pe Tumblr.com și în câteva săptămâni a câștigat o întreagă armată de fani - aproximativ 10.000 de oameni. În 2013, Facebook a dorit să includă imagini de la Pusheen în colecții cu alte emoticoane. După negocieri cu creatorul, această idee a fost pusă în practică și a „explodat” internetul! Imaginile de la pisica Pusheen sunt folosite în corespondență de peste 10 milioane de ori pe zi!
În 2014, unul dintre cei mai mari producători de jucării din Statele Unite și-a îndreptat atenția către acest personaj. GUND (ea a fost cea care a inventat ursuleții de pluș) a lansat o pereche de modele Pusheen. Deoarece succesul a fost uriaș, după câteva luni a fost creată o colecție completă de jucării sub forma acestei pisici.
Unde altundeva o puteți întâlni pe pisica Pusheen? În seturi de cadouri de la Isaac Morris Ltd, în bezele de la Boomf și, desigur, în colecția noastră de cursoare Pusheen!',
    'pusheen_short_descr' => 'Adaugă un pic de confort în browserul tău cu colecția de cursori Pusheen',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'Prima serie a lucrării animate „Rick and Morty” a fost lansată în 2013. Acest desen animat poate fi atribuit direct la 2 genuri: science fiction și comedie. Creatorii săi au fost Dan Harmon și Justin Royland. Inițial, toate seriile au fost difuzate pe canalul Cartoon Network și abia apoi au fost duplicate în cinematografele online și gazduirea video. La câțiva ani, sunt lansate noi sezoane Rick and Morty, iar în noiembrie 2019 a apărut al patrulea sezon, care s-a dovedit a fi la fel de interesant ca și cele anterioare. Intriga serialului animat se rotește în jurul unui geniu și, în același timp, un om de știință nebun pe nume Rick, precum și nepotul său neobișnuit - Morty. Aceste două personaje sunt conectate de aventuri comune în cele mai neobișnuite locuri. Și ajung acolo într-o farfurie zburătoare, capabilă să se deplaseze printr-un tunel interspațial. După cum ați ghicit, această serie animată seamănă puțin cu filmul Back to the Future, dar totuși nu este versiunea sa animată. Cu toate acestea, a fost lăudat de mulți critici pentru episoadele umoristice, creativitate și originalitate. Vrei să-l vezi pe Rick sau Morty nu doar în serialul acestei lucrări, ci și în browser? Dacă da, instalați extensia și adăugați colecția noastră dedicată desenului tău animat preferat! Iată cursorul Rick Sanchez, cursorul Morty Smith, cursorul Portal Gun și, desigur, cursorul Mr. Meeseeks.',
    'rick_and_morty_short_descr' => 'Nu mai mormăi, folosește cursoarele din colecția Rick and Morty',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Fanii de baseball pot fi găsiți oriunde în lume. Acest lucru este valabil mai ales pentru locuitorii din țări precum: SUA, China, Cuba, Coreea de Sud, Japonia și Venezuela. Contrar credinței populare, baseball-ul nu a apărut în America, ci în Anglia. Prima mențiune și descriere a baseball-ului a apărut în îndepărtatul an 1744, în ediția engleză. După 145 de ani, americanii și-au însușit această invenție pentru ei, în ciuda faptelor.
Liga Națională a fost formată în 1876. Face parte din Major League în Canada și Statele Unite. Astăzi, există 15 echipe în National Baseball League. În ultima parte a fiecărui sezon, vine timpul play-off-urilor, la care participă cele mai bune 4 echipe. Deci, este dezvăluit câștigătorul întregii Ligi Naționale. Apoi, echipa câștigătoare are ocazia să joace împotriva câștigătorului din Liga Americană în World Series.
Vă interesează baseball-ul sau chiar țineți cu una dintre echipe? Atunci aduceți un omagiu echipei voastre preferate setând cursoarele mouse-ului sub forma atributelor sale! Schimbați aspectul plictisitor al indicatorului din browser cu identitatea corporativă familiară a baseball-ului! Transformă săgeata într-o bâtă sau o cască de jucător în oricare dintre echipele din Liga Națională, care includ deja cursorul New York Yankees, cursorul Great Falls Dodgers, cursorul Boston Red Sox, cursorul Baltimore Orioles, cursorul Oakland Athletics.',
    'mlb_teams_short_descr' => 'Colecție de cursoare Echipe MLB pentru toți fanii noștri.',
    'mlb_teams' => 'Echipe MLB',
    'brawl_stars_descr' => 'Brawl Stars este un joc mobil din genul MOBA de la Supercell. În ciuda lansării sale la sfârșitul anului 2018, jocul a câștigat o mare popularitate, în mare parte datorită abundenței de moduri de luptă și eroilor colorați, fantastici - brawlers. Jucătorul are de unde alege - 32 de personaje unice și fiecare dintre ele are propriul set de abilități și competențe. Fiecare erou are, de asemenea, propria abilitate pasivă, care este disponibilă prin cuferele de pradă. Jucătorii pot lupta în mai multe moduri, de exemplu, "Recompensă pentru captură" - una dintre cele două echipe câștigă, cea care a colectat mai multe stele, ucigând adversari. În modul "jaf", este necesar să spargă seiful adversarilor, menținându-le pe ale lor. Un mod interesant "Gem Grab" - echipa devine câștigătoare, echipa care colectează cele mai multe pietre prețioase câștigă. Ei bine, în modul "Collision", 10 jucători se lupta între ei pe hartă, unde marginile sunt reduse din cauza unui nor toxic. Jocul este plin de un design colorat care place multor oameni, inclusiv nouă, ceea ce ne-a inspirat să creăm o colecție separată de cursori Brawl Stars. Există cursorul Brawl Stars Shelley, cursorul Barley, cursorul Penny, cursorul Frank, cursorul Mortis și altele.',
    'brawl_stars_short_descr' => 'Alege cursoare Brawl Stars și lasă bătălia să înceapă',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Schimbă-ți cursorul mouse-ului în două clicuri! Colecții gratuite pentru toate gusturile.',
    'all_descr' => 'Dacă te-ai gândit vreodată cum să schimbi un cursor de mouse plictisitor, atunci colecțiile noastre de cursori sunt pentru tine! Aici vei găsi eroi de benzi desenate cool, cursori frumoși pentru jucători cu personaje din jocuri populare, seturi distractive de cursori pentru farse, cursori colorați și multe alte opțiuni interesante.',
    'text_title' => 'Colecții de cursuri cool și amuzante pentru fiecare zi',
    'text_allcat_title' => 'Cursori de mouse unici și creativi pentru a se potrivi cu starea ta de spirit',
    'text_1' => 'Nu vrei să fii ca toți ceilalți? Sau pur și simplu iubești tot ce este neobișnuit? Vrei să faci parte din eroul tău preferat de joc sau din personajul de desene animate? Atunci ai ajuns la locul potrivit. Aici vei găsi seturi de cursori luminoși, neobișnuiți, care pot înlocui săgeata albă familiară și deja destul de plictisitoare. Cursorul mouse-ului ne însoțește toată ziua la muncă și la școală, așa că ar trebui să ofere o dispoziție excelentă și să ne pregătească pentru pozitiv.',
    'text_2' => 'Aici veți găsi cursoare pentru gameri și cinefili, cursoare frumoase bazate pe desenele animate preferate și motive sportive pentru cei mai activi oameni. Vă plac benzile desenate sau nu vă puteți imagina o singură zi fără meme-uri amuzante? Adorați animalele sau visați să vizitați toate țările lumii? Totul este simplu - avem o imagine de cursor potrivită și pentru dumneavoastră. De asemenea, puteți selecta imagini în funcție de ceea ce lucrați. De exemplu, un cursor negru va fi mult mai convenabil decât unul alb atunci când lucrați cu documente sau desene, iar un cursor de mână va fi mai convenabil dacă trebuie să lucrați cu elemente grafice mici. Alegeți imaginea preferată, ajustați dimensiunea acesteia direct în extensie - și utilizați-o cu plăcere, în fiecare zi, începând cu o notă pozitivă!',
    'install_to_preview' => 'Vă rugăm să instalați extensia pentru a previzualiza',
    'install' => 'Instalează',
    'add_button' => 'Adaugă',
    'preview_button' => 'Previzualizare',
    'added_button' => 'Adăugat',
    'add_cursor' => 'Adaugă cursor',
    'to_your_collection' => 'la colecție',
    'prev_text_1' => 'Previzualizare ecran complet',
    'prev_text_2' => 'cursor',
    'cursor' => 'cursor',
    'pointer' => 'indicator',
    'a_title_1' => 'Cursor Style - Cursorare cool pentru browserul tău',
    'a_title_2' => 'Colecții cool de cursoare tematice',
    'mouse_cursors' => 'cursuri mouse',
    'cursor_collection' => 'Colecție de cursoare',
    'sborka_cursorov' => 'colecție de cursoare',
    'collection_list_from_colllection' => 'Listă de cursoare - ',
    'christmas' => 'Crăciun',
    'nhl_teams' => 'Liga Națională de Hochei',
    'neon' => 'Neon',
    'adventure_time' => 'Să-nceapă Aventura',
    'nba_teams' => 'Asociația Națională de Baschet',
    'spongebob' => 'SpongeBob',
    'phineas_and_ferb' => 'Phineas și Ferb',
    'fortnite_chapter_2' => 'Fortnite Capitolul 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Vedete',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'Liga Națională de Fotbal',
    'five_nights_at_freddy' => 'Cinci nopți la Freddy',
    'komiksy' => 'Benzi desenate',
    'igry' => 'Jocuri',
    'multfilmy' => 'Desene animate',
    'kino_i_serialy' => 'Filme și seriale',
    'anime' => 'Anime',
    'futbol' => 'Fotbal',
    'avtomobili' => 'Mașini',
    'memy' => 'Meme',
    'emodji' => 'Emoji',
    'pitomcy' => 'Animale de companie',
    'stil_i_krasota' => 'Modă și stil',
    'prazdniki' => 'Sărbători',
    'flagi' => 'Steaguri',
    'vokrug_sveta' => 'În jurul lumii',
    'eda_i_napitki' => 'Mâncare și băuturi',
    'cvetnye' => 'Colorate',
    'prank' => 'Glume',
    'startovyj_nabor' => 'Kit de pornire',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Moș Crăciun va adora cursoarele tale de Crăciun',
    'nhl_teams_short_descr' => 'O colecție de cursoare NHL pentru fanii adevărați',
    'neon_short_descr' => 'Adaugă strălucire cu o colecție neon',
    'adventure_time_short_descr' => 'Învățând Matematică cu colecția de cursoare Adventure Time',
    'nba_teams_short_descr' => 'Cursori NBA ca un simbol al marilor victorii în baschet',
    'spongebob_short_descr' => 'Află cine locuiește pe fundul oceanului cu colecția de cursori SpongeBob',
    'phineas_and_ferb_short_descr' => 'Cu siguranță nu te vei plictisi cu colecția de cursori Phineas și Ferb',
    'fortnite_chapter_2_short_descr' => 'Noul capitol al jocului cult Fortnite',
    'pokemon_short_descr' => 'Prinde-le pe toate dacă poți',
    'famous_people_short_descr' => 'Inspirați-vă cursorul idolului dumneavoastră',
    'the_elder_scrools_short_descr' => 'Cufundați-vă în lumea cavalerilor și a dragonilor',
    'halloween_short_descr' => 'Fii Speriat să ratezi noua colecție de Halloween',
    'nfl_teams_short_descr' => 'Pentru fanii adevărați ai fotbalului american',
    'five_nights_at_freddy_short_descr' => 'Încearcă să nu te sperii de acești animatronici',
    'komiksy_short_descr' => 'Cursori după benzi desenate: alege-ți starea de spirit astăzi.',
    'igry_short_descr' => 'Realitate virtuală: cu cine te joci astăzi?',
    'multfilmy_short_descr' => 'Personaje de desene animate preferate într-un design nou',
    'kino_i_serialy_short_descr' => 'Stăpânul Cursorului: Frăția Desktopului',
    'anime_short_descr' => 'Toată lumea iubește anime: care este personajul tău preferat?',
    'futbol_short_descr' => 'Ești un fan adevărat al sportului? Atunci trebuie să fii aici.',
    'avtomobili_short_descr' => 'Mașina visurilor tale: o flotă mare pentru profesioniști.',
    'memy_short_descr' => 'Motive preferate: Colecția de cursoare Memes',
    'emodji_short_descr' => 'Arată-le celorlalți adevărata ta stare - setează Cursoji!',
    'pitomcy_short_descr' => 'Cursori luminoși pentru toți iubitorii fraților noștri mai mici',
    'stil_i_krasota_short_descr' => 'Cursori originali pentru toate ocaziile',
    'prazdniki_short_descr' => 'Ce se află pe calendar? Noua colecție de cursoare de sărbători!',
    'flagi_short_descr' => 'Căutați aventură: unde mergem astăzi?',
    'vokrug_sveta_short_descr' => 'În jurul lumii într-o clipă: unde mergem astăzi?',
    'eda_i_napitki_short_descr' => 'Cursori delicioși pentru creativitate',
    'cvetnye_short_descr' => 'Pictează-ți viața în culori vii și tușe îndrăznețe',
    'prank_short_descr' => 'Un set de cursoare pentru cele mai amuzante farse',
    'startovyj_nabor_short_descr' => 'O nouă perspectivă asupra lucrurilor familiare: o serie actualizată de cursoare',
    'fortnite_short_descr' => 'Urmează streamerii!',
    'dota_2_short_descr' => 'Fă ca lumea ta virtuală să devină reală!',
    'minecraft_short_descr' => 'Personajele jocului tău preferat sunt mereu prin apropiere',
    'christmas_descr' => 'Fiecare dintre noi așteaptă, fără îndoială, cea mai populară sărbătoare - Crăciunul. Toți creștinii din lume o sărbătoresc în mod tradițional în fiecare an, pe 25 decembrie. Un moment în care familiile se adună la o masă, își împărtășesc bucuria și dragostea și fac schimb de cadouri. Cu mult înainte de Crăciun, oamenii decorează străzile cu ghirlande strălucitoare, iar casele lor cu atribute tradiționale. Este greu să găsești o persoană căreia să nu-i placă Crăciunul - o sărbătoare distractivă și misterioasă, deoarece este însoțită de multe tradiții și ritualuri, care ne readuc la rădăcinile întregii noastre familii. În ajunul Crăciunului, literalmente totul este saturat de spiritul său, de la turtă dulce pictată până la cântece emoționante. Un brad de Crăciun elegant și cadouri sub el, o bucurie familiară fiecăruia dintre noi din copilărie. Vrem să ne alăturăm acestei sărbători magice și, cine știe, poate Moș Crăciun vă va pregăti un cadou special dacă vă decorați cursorul cu colecția noastră de Crăciun. Există tot ce aveți nevoie pentru asta, cursorul Moș Crăciun, cursorul bradului de Crăciun, cursorul turtă dulce, cursorul om de zăpadă și chiar cursorul pungii de cadouri. Crăciun Fericit!',
    'nhl_teams_descr' => 'National Hockey League a fost formată în 1917 - este o organizație sportivă profesionistă care reunește cluburi de hochei din SUA și Canada. Și aceasta este una dintre primele ligi profesioniste de hochei din lume. NHL este una dintre cele mai importante ligi sportive din America de Nord, împreună cu NFL, NBA, Major League Baseball și MLS. În fiecare an, 31 de echipe din 30 de orașe din SUA și Canada luptă pentru principalul trofeu - Cupa Stanley, iar echipa care a marcat cele mai multe puncte în sezonul regulat este premiată cu Cupa Președintelui. Este timpul să onorăm acest joc grozav creând o colecție de cursoare NHL. Dacă și ție îți place hocheiul, susține clubul tău preferat sau participă la acest sport, schimbă doar cursorul și nu te despărți de echipa ta preferată, inclusiv cursorul Boston Bruins, cursorul St. Louis Blues, cursorul Columbus Blue Jackets, cursorul Tampa Bay Lightning, cursorul Dallas Stars și alte cluburi demne de respect sincer.',
    'neon_descr' => 'Am creat o colecție unică de cursoare neon pentru a adăuga varietate navigării zilnice pe internet și pentru a adăuga un pic de strălucire luminilor neon hipnotizante. Lăsați culorile lor bogate să creeze atmosfera captivantă a orașului noaptea, să ofere inspirație pentru a crea ceva nou. În lumea modernă, luminile unei metropole anunță întotdeauna începutul nopții, ne urmăresc pe fiecare stradă, iar această strălucire este plină de energie. Lăsați-o să fie urmată și de un cursor de înghețată strălucitoare, un cursor de hot dog delicios, un cursor de burger suculent, un cursor de diamant sclipitor și alte cursoare din noua colecție neon.',
    'adventure_time_descr' => '"Adventure Time" este un desen animat de genul fantastic în care acțiunea are loc într-o lume care a supraviețuit apocalipsei. Acest teritoriu se numește Land Ooo, care până de curând a fost un război nuclear. Dar toate acestea sunt deja în trecut, cu toate acestea, toți oamenii supraviețuitori au fost supuși mutațiilor, iar lumea a fost umplută de magie. Personajele principale ale serialului de animație sunt Finn, un băiat de 14 ani și prietenul său, un câine pe nume Jake. Băiatul și câinele sunt foarte pasionați de aventuri, ei ajută constant pe toți cei care au probleme. Prietenii locuiesc într-un copac și își petrec tot timpul împreună. Dacă vrei să te scufunzi într-o lume a aventurilor cu alți admiratori, atunci strigă "Mathematics". Aici sunt atât cursorul Finn Boy, cât și cursorul Jake, precum și cursorul Prințesei Gumă. Desigur, nu am uitat de cursorul Bimo, cursorul Ice King și altele.',
    'nba_teams_descr' => 'Dacă baschetul este jocul tău preferat, la fel ca și al nostru, atunci o colecție de cursoare dedicate echipelor NBA este ceea ce ai nevoie. NBA este una dintre asociațiile sportive de top de pe continentul nord-american. Când am creat această colecție, am fost chinuiți de alegere - ce echipă să alegem, pentru că sunt treizeci dintre ele în NBA. Dar sunt echipe care sunt legende. Aceasta și Chicago Bulls, au stabilit un record de victorii la mijlocul anilor \'90. Aceasta este Golden State Warriors, care a reunit cei mai buni jucători de ligă acum câțiva ani. Sau, de exemplu, Lakers, Celtics sunt, de asemenea, echipe nebunește de tari. Dacă, la fel ca și noi, așteptați cu nerăbdare meciurile echipelor voastre preferate de baschet și doriți să vă arătați sprijinul pentru echipă sau jucători, descărcați colecția noastră de cursoare NBA.',
    'spongebob_descr' => 'Serialul de animație "SpongeBob Pantaloni Pătrați" este cunoscut de atât de mulți oameni. A fost un succes copleșitor după ce Nickelodeon în 1999 a decis să creeze un serial de animație bazat pe banda desenată educațională Tide Zone și s-a transformat într-o franciză foarte profitabilă. Creatorul seriei este un fost angajat al laboratorului oceanologic, motiv pentru care aproape toate personajele din serialul de animație sunt locuitori amuzanți ai fundului mării, cu propriile lor caracteristici și carismă. Acțiunea se învârte în jurul rețetei secrete Krabsburger pe care doar personajul principal o poate găti - Sponge Bob. Iar ceilalți locuitori ai mării zi încearcă să o obțină, inclusiv principalul anti-erou Sheldon Plankton, care nu o obține de fiecare dată. În colecția de cursori SpongeBob, am adunat cursorii tuturor personajelor și evenimentelor notabile ale seriei. De exemplu, cursorul lui Mr. Krabs cu dolarul, cursorul lui Patrick Star, Squidward cu clarinetul său, cursorul meduzei, cursorul lui Sponge Bob și multe alte personaje.',
    'phineas_and_ferb_descr' => 'În orașul american fictiv Denville din neexistentul Trishtatya, trăiesc doi băieți interesanți. Fiecare zi de vacanță a lor se transformă în aventuri incredibile, deoarece pot construi un montagne russe de mărimea unui întreg oraș sau un portal real către o altă planetă. Ei împărtășesc divertismentul lor uimitor cu prietenii. În același timp, în timp ce băieții se distrează, savantul malefic Heinz Fufelschmertz construiește o altă mașinărie malefică care creează haos, cu numele care se termină în "-inator", cu ajutorul căreia vrea să-și răzbune nemulțumirile din copilărie sau să preia puterea în Trishtat, dar Perry, - Agentul Pi" secret, care lucrează sub acoperirea unui animal de companie al băieților, îl împiedică. Popularitatea acestui serial animat, atât în rândul copiilor, cât și al adulților, ne-a inspirat să creăm o colecție de cursoare Phineas și Ferb, astfel încât să puteți schimba cursorul mouse-ului pe personajele din serie. Printre acestea se numără cursorul Phineas Flynn, cursorul Dr. Heinz Fufelschmertz, cursorul Ferb Fletcher, cursorul Candace Gertrude Flynn și cursorul Perry ornitorincul.',
    'fortnite_chapter_2_descr' => 'Al doilea capitol din Fortnite a venit după un eveniment grandios - Sfârșitul, care a tras tot ce iubeau jucătorii în joc într-o gaură neagră. Fortnite Capitolul 2 are acum o hartă nouă, care la prima vedere este chiar mai sălbatică decât harta originală, precum și multe schimbări în mecanica jocului și, desigur, o mulțime de conținut nou de joc! Vehicule, emoții, mecanici de înot și multe altele - toate acestea în imagini proaspete și interesante, totul așa cum iubiți și apreciați în acest joc cult. Scufundați-vă într-o lume nouă - alegeți un loc de aterizare și explorați o insulă complet nouă cu 13 locații. Înot, pescuit, bărci cu motor - acesta este un nou gameplay pe apă. Mai multă distracție și mai puțin efort - îmbunătățiți un capitol 2 complet nou și nu uitați să schimbați cursorul la skin-uri și arme noi. Deja vă așteaptă skin-urile actualizate cursor Turk, cursor Riptide, cursor Rippley, cursor Remedy, cursor Toxin, cursor 8-Ball, cursor Fusion și altele!',
    'pokemon_descr' => 'Cuvântul "pokemon" înseamnă o creatură cu puteri supranaturale. Ei au inteligență și unii dintre ei sunt chiar capabili să vorbească. În prezent, există deja 802 varietăți de Pokemon. În universul inventat Pokémon, oamenii sunt numiți antrenori Pokémon, pe care îi antrenează pentru bătălii cu Pokémon de alți antrenori. Și cu cât antrenorul este mai experimentat și mai puternic, cu atât se bucură de mai mult respect. Din fericire, trebuie menționat că luptele Pokemon nu se termină niciodată cu moartea acestor creaturi unice. Toți Pokémon au abilități diferite și diferă în tipul de element, iar rezistența sa la diferite atacuri depinde puternic de acest lucru, iar unele creaturi au capacitatea a două elemente simultan. După câștigarea bătăliei, Pokemon primește experiența valoroasă necesară pentru a crește nivelul și, în consecință, caracteristicile sale. Astăzi, universul Pokémon este o franciză media uriașă și vom decide să pregătim pentru tine o colecție de cursoare cu unele Pokemon populare. Printre acestea, cel mai faimos este cursorul Pikachu, precum și cursorul Rattata, cursorul Squirt, cursorul Bulbasaur și cursorul Charmander. Această listă va fi actualizată, deoarece sunt atât de multe și fiecare dintre ele este unic în felul său.',
    'famous_people_descr' => 'Printre mulți oameni celebri, fiecare dintre noi găsește un model sau pur și simplu admiră geniul, talentul și perseverența acestor celebrități. Am pregătit o colecție de cursore ale celebrităților pentru a te inspira și a-ți aminti de marile realizări pe care fiecare dintre voi le puteți amplifica. Nu toate personalitățile celebre au avut o soartă fericită, dar ele ne învață lucrul principal că nu trebuie niciodată să te retragi de la scopul tău prețuit, în ciuda dificultăților și problemelor. La urma urmei, acesta este principiul principal al atingerii succesului - să mergi spre visul tău în fiecare zi și, în cele din urmă, să devii cel mai bun în domeniul tău. Poate că astăzi vrei doar să schimbi cursorul mouse-ului, iar mâine întreaga ta viață se va schimba spre bine! Colecția va fi actualizată constant cu noi reprezentanți valoroși ai umanității. Printre aceștia, desigur, oameni de știință, politicieni, sportivi, reprezentanți ai artei și mulți alții. Cursorul George Washington, cursorul Michael Jordan, cursorul Stephen King, cursorul Elvis Presley și cursorul Marilyn Monroe sunt doar începutul.',
    'the_elder_scrools_descr' => 'The Elder Scrolls este o serie de jocuri de rol pentru computer, unite de un univers comun, meticulos proiectat, care oferă jucătorului o libertate enormă de alegere, permițându-i să viziteze diferite zone și orașe ale lumii fantastice și să exploreze locuri și misiuni noi pe cont propriu. Lucrul la serie a început în 1992 și, de-a lungul anilor, jocul a unit o comunitate uriașă de jucători în jurul său. Prin urmare, la cererea populară, am lansat o colecție de cursore The Elder Scrolls, astfel încât să vă puteți cufunda în atmosfera unică a jocului. Bătălia eternă a cavalerilor și dragonilor, de partea cui sunteți? Schimbați cursorul cu un dragon și alăturați-vă armatei de monștri care scuipă foc sau luptați nobil de partea oamenilor, alegând cursorul sabiei și imaginea personajului tău preferat - decizia este a ta! Principalul lucru este că, cu noua noastră colecție, sunteți pregătit pentru orice bătălie.',
    'halloween_descr' => 'Așteptând o noapte mistică în ajunul Zilei Tuturor Sfinților. Istoria Halloween-ului datează de peste două mii de ani. Poate că aceasta este cea mai ciudată sărbătoare care combină distracția și frica, o nativă a culturii celtice. Atunci oamenii ardeau focuri de tabără și purtau costume înfricoșătoare pentru a alunga fantomele. Cuvântul "Halloween" a fost menționat pentru prima dată în secolul al XVI-lea ca o abreviere scoțiană a expresiei englezești All-Hallows-Even. Papa Grigore al III-lea a declarat 1 noiembrie Ziua Tuturor Sfinților, iar seara precedentă a fost cunoscută drept Ajunul Tuturor Sfinților, și mai târziu Halloween. În această zi, oamenii poartă costume de vârcolaci, fantome și alți monștri și merg la casele vecine, oferind să cumpere dulciuri. Petrecerile tematice, artificiile, felinarele frumoase, dovlecii și cascadoriile creează o atmosferă unică. De asemenea, dorim să sărbătorim această sărbătoare teribilă cu cursori de accesorii și personaje de Halloween. În colecția noastră puteți găsi: cursor zombie, cursor fantomă, cursor pisică neagră, cursor dovleac și multe altele. Schimbarea stării de spirit este acum la fel de ușoară ca schimbarea cursorului cu noua noastră colecție de Halloween.',
    'nfl_teams_descr' => 'Ce ar putea fi mai bun pentru un adevărat fan al fotbalului american decât un cursor al mouse-ului sub forma simbolismului echipei pentru care este fan? În moderna National Football League, joacă treizeci și două de echipe, împărțite între Conferințele Națională și Americană de Fotbal (National Football Conference, NFC și American Football Conference, AFC). La rândul său, fiecare dintre conferințe este împărțită în patru divizii: Est, Nord, Sud și Vest. Sezonul NFL constă din meciuri de pre-sezon, un sezon regulat și o serie de meciuri de playoff. Meciul final al sezonului NFL se numește Super Bowl și este, în esență, cel mai popular eveniment sportiv din Statele Unite. Acesta este un joc preferat pentru milioane de fani și, prin urmare, am creat o colecție de cursoare NFL, astfel încât să nu vă despărțiți de simbolurile echipei preferate. Fie că este New England Patriots, New York Giants, Buffalo Bills sau o altă echipă, fiți întotdeauna pe aceeași lungime de undă cu idolii voștri, folosind cursoarele noastre sub forma unui sigiliu și a unei căști de echipă. Colecția va fi actualizată constant, astfel încât toată lumea să poată schimba cursorul cu imaginea echipei lor preferate.',
    'five_nights_at_freddy_descr' => 'Jocul cu adevărat unic Five Nights at Freddy\'s a câștigat rapid o popularitate largă și acest lucru nu este surprinzător, deoarece intriga sa simplă și în același timp fascinantă poate ține jucătorii pe ecrane ore întregi. Am proiectat cursorele Five Nights at Freddy\'s la cererea fanilor jocului și am fost foarte bucuroși să întruchipăm personaje atât de interesante și amuzante. Dar, spre deosebire de joc, nimic nu te amenință cu cursorele noastre, așa că nu ezita să-ți alegi animatronica preferată, fie că este Bear Freddy sau Rabbit Bonnie sau altele. Principalul lucru este că acum jocul prinde viață în browserul tău și oferă emoții proaspete. Vă garantăm că nu există fantome în cursorele noastre, dar acestea redau perfect spiritul unui joc care inspiră frică datorită complexităților designului și elementelor de complot. Dar ce se întâmplă dacă mărești foarte mult dimensiunea cursorului? Poți să rămâi calm și să nu te sperii?',
    'komiksy_descr' => 'S-ar părea că cursorul mouse-ului este o fleac, dar adesea sunt astfel de detalii care vă pot îmbunătăți starea de spirit, trezi dimineața gri sau pur și simplu oferi emoții luminoase. O colecție de cursoare de benzi desenate concepute special pentru toți iubitorii de supereroi. Aici puteți găsi absolut tot Marvel Universe și DC Comics - de la Iron Man la Thanos, Spider-Man și Hulk. Stilul cursorului poate fi fie sub forma unui supererou, fie sub forma personajului său. Un cursor nu este doar un element funcțional; este important într-un sens profesional. De exemplu, dacă înregistrați un videoclip de pe ecran, va fi mai bine să vedeți o imagine luminoasă, originală și arată mult mai interesant. Și, desigur - cine nu ar vrea să folosească mănușa infinitului în viața reală? Schimbarea cursorului mouse-ului este simplă - doar descărcați extensia în browser și adăugați cursorul dorit la setările dvs. prin intermediul acesteia. Puteți alege un cursor în funcție de starea dvs. de spirit cel puțin în fiecare zi. Destul zilele gri - deveniți un supererou chiar acum!',
    'igry_descr' => 'Jocurile pe calculator au devenit de mult o parte integrantă a vieții noastre. Cu ajutorul lor, te poți scufunda într-o lume nouă, poți participa la aventuri și poți deveni o persoană complet diferită. Fiecare are propria jucărie preferată, ale cărei personaje au devenit deja aproape familie. Un set de cursoare bazate pe jocuri pe calculator binecunoscute este o oportunitate de a dilua viața de zi cu zi plictisitoare și de a adăuga un pic de creativitate, strălucire și distracție fluxului de lucru. Setul conține atât imagini ale eroilor jocurilor înșiși, cât și personaje auxiliare, arme și icoane de joc. Alege ce se potrivește stării tale de spirit - cursoarele de joc vor atrage nu numai jucătorii, ci și pe toți cei care sunt pur și simplu obosiți de viața de zi cu zi gri. Doar descarcă setul, schimbă cursorul mouse-ului - și mergi, pentru a finaliza sarcini de căutare, a distruge inamicii și a-ți atinge obiectivele.',
    'multfilmy_descr' => 'Înăuntrul fiecărui adult se află încă un copil care iubește desenele animate și încă visează să devină unul dintre eroi. Vă vom ajuta să vă îndepliniți visele - folosiți noua colecție de cursuri bazate pe cele mai faimoase și preferate desene animate. Tom și Jerry, Buzz Lightyear și Shrek, Gravity Falls și chiar Pokemon - puteți deveni ceea ce doriți în fiecare zi. Selectați cursorul mouse-ului în funcție de starea de spirit. Cine ești tu astăzi? Un minion nesăbuit și vesel care rezolvă cu ușurință orice problemă sau un Rafael puternic și curajos, al cărui scop nu este doar să realizeze fapte, ci și să mănânce pizza? Poate că ești geniul atotputernic care deține un întreg birou sub comanda sa? În colecție există eroi pentru toată lumea - de la prințese la dragoni - nu rămâne decât să decideți cine reflectă starea de spirit de astăzi. Stilul cursorului nu este doar o imagine luminoasă. Aceasta este o reflectare a individualității, auto-exprimării și pur și simplu - distracție, bucurie și pozitivitate pentru întreaga zi. E plictisitor să lucrezi sau ești prea leneș să înveți? A devenit trist și nu ești fericit? Schimbă cursorul și lumea va străluci cu culori noi.',
    'kino_i_serialy_descr' => 'Filme - au magie, misticism și sunt o modalitate excelentă de a te relaxa, de a te distra și de a obține emoții vii. În același timp, după vizionare, încă ne amintim de eroii favoriți pe care chiar vreau să-i întâlnim în realitate. Acum este posibil - doar descărcați noua colecție de cursoare bazate pe filme și emisiuni TV celebre. Cursoarele luminoase și cool vor fi un adaos excelent la desktop, vor transforma viața de zi cu zi gri și plictisitoare într-o sărbătoare, iar sarcinile banale - într-o aventură palpitantă. Schimbați eroii cursorului în fiecare zi - după starea de spirit, sarcini sau aleatoriu. Cine vei fi astăzi? Onestul și corectul John Snow sau îndrăznețul și neobositul John Wick? Poate că aveți o misiune dificilă în față și numai Frodo o poate finaliza? Poate că astăzi sunteți doar un extraterestru care nu vrea să ia legătura cu ceilalți? Alegeți un cursor potrivit - ridicați-vă moralul și, în același timp, arătați-le și altora ce gândiți și cum intenționați să vă petreceți ziua. Încercați-l - nu este doar distractiv, ci și captivant - cu siguranță nu veți mai dori să vă întoarceți la săgeata obișnuită.',
    'anime_descr' => 'Anime este un stil unic de animație, care, în ciuda etniei sale pronunțate, a fost plăcut de milioane de oameni din întreaga lume. Este puțin probabil să existe cel puțin o persoană care nu a vizionat desene animate în acest stil. Am creat cele mai tari cursoare în stil anime pe care toți fanii acestui stil le vor adora. Cursoarele standard sunt plictisitoare și siropoase. Arată-ți personalitatea - folosește colecția de cursoare Anime cu personajele tale preferate. Alege cursorul unei săbii întunecate dacă visezi la aventură și bătălii curajoase. Grăsanul drăguț Totoro te va înveseli chiar și în cea mai tristă zi, iar Naruto te va motiva în aventuri și va arăta tuturor din jurul tău că ești mega cool. Cursoarele luminoase vor însenina ziua de lucru sau vor face procesul de învățare mai interesant și mai plăcut. Nu te limita - folosește motivele tale preferate chiar și în elemente atât de mici precum cursorul mouse-ului. Schimbă cursoarele în fiecare zi, adaptează-le la starea ta de spirit și arată-ți personalitatea - cu cursoare în stil anime este atât de simplu.',
    'futbol_descr' => 'Fotbalul este un sport special care include elemente de lupte, atletism, precizie. În general, este spectaculos, nemilos și adună milioane de fani în întreaga lume. Îți place fotbalul sau pur și simplu iubești sportul? Atunci descarcă un set de cursoare în stilul jocului renumit mondial și dovedește titlul de fan loial. Colecția conține 24 de opțiuni pentru proiectarea cursoarelor - sub forma celor mai populare echipe care își merită titlurile ca un joc disperat și persistent. Cursoarele sunt realizate în două versiuni - sub forma unui triunghi standard, decorat în culorile echipei, sau sub forma unei căști corespunzătoare jocului. Cursorul standard al browserului este plictisitor și nu este demn de un adevărat fan al sportului. Deveniți original și unic cu colecția noastră. Descărcați imagini și alegeți culorile echipei preferate sau cursoare personalizate, dacă pur și simplu iubiți sportul și încurajați pe toată lumea. Urmarea hobby-urilor tale este atât de simplă - nu trebuie să vii la serviciu cu o eșarfă sau o șapcă a echipei tale preferate, este rapid și ușor să schimbi cursorul cu o imagine luminoasă și elegantă.',
    'avtomobili_descr' => 'Îți plac mașinile și îți place să te uiți la modele de la diferiți producători? Sau visezi de multă vreme la o anumită marcă, dar încă nu ai ocazia să o achiziționezi? Special pentru tine, am creat un set vibrant de cursoare "Supercars". Aici vei găsi Ford-uri clasice și Bentley-uri elegante, Lamborghini-uri luminoase și Ferrari-uri unice. Vrei să devii proprietarul unei mașini originale? Este simplu - descarcă colecția noastră de cursoare pe dispozitivul tău și schimbă imaginea mașinii cel puțin în fiecare zi. Cursoarele sunt proiectate în două versiuni - ca o mașină completă sau ca semnul ei. Alege ce îți place mai mult sau cum preferi să lucrezi. Astfel de imagini vor arăta grozav ca cursoare de joc sau pur și simplu ca un element neobișnuit al desktopului. A fi strălucitor este simplu - nu este necesar să faci lucruri de neimaginat pentru asta sau să-ți schimbi aspectul. Este suficient doar să nu mai folosești obiecte banale și să alegi ceea ce îți place cu adevărat. Colecția de cursoare "Mașini" este alegerea pentru cei cărora nu le este frică să se afirme.',
    'memy_descr' => 'Meme-urile au fost de mult o parte familiară a vieții noastre. Și cine dintre noi nu apreciază aceste imagini generoase, interesante și originale care înfruntă ziua? Mulți eroi ai meme-urilor au devenit nu doar populari - au dobândit statutul de favoriți populari, iar frazele și expresiile au fost incluse de mult în vorbirea colocvială ca expresii bine stabilite. Vă prezentăm o colecție cu cele mai bune cursoare bazate pe cele mai populare meme-uri. Cu ajutorul lor, puteți nu numai să vă demonstrați personalitatea, ci și să vă exprimați starea de spirit. Sunteți toți obosiți și sătui de toate? Alegeți o pisică furioasă care, cu toată aparența ei, exprimă indignare și ostilitate față de tot ce o înconjoară. Sau străluciți de sarcasm astăzi și nu aveți nimic împotriva râsului? Atunci Drake Bling va fi un acompaniament excelent - vă va binedispune și va face orice sarcină originală și interesantă. Instalați extensia, descărcați colecția noastră - și alegeți un stil de cursor nou pentru fiecare zi. Nu este dificil să fii strălucitor și original - schimbați designul standard al icoanei cu unul dintre eroii meme-urilor și obțineți un impuls de energie pentru întreaga zi.',
    'emodji_descr' => 'Emoji - iconi strălucitoare și cool, fără de care nu mai putem comunica în mod obișnuit. Cu ajutorul lor, nu trebuie să-ți descrii starea de spirit în cuvinte - doar selectezi iconița dorită și interlocutor te înțelege fără alte explicații. În noul nostru set de cursuri, am întruchipat ideea de emoji - adică așa au apărut Cursoji amuzanți și neobișnuiți care vor colora lumea și vor face viața mai interesantă. Cu ajutorul cursurilor, poți nu doar să lucrezi și să îndeplinești sarcini familiare, dar și să le arăți colegilor, prietenilor și doar altora starea ta de spirit. Un cursor somnoros este perfect pentru dimineața de luni, iar un cursor care plânge va exprima o atitudine față de responsabilitățile suplimentare. Un cursor cool cu ochelari este cea mai bună alegere înainte de sărbători, iar un cursor cu dolari în ochi este un motiv bun să-i faci aluzie șefului despre creșterea salariului. Folosirea Cursoji este distractivă și interesantă - fie că este vorba de muncă, studiu sau prezentare. În ultimul caz, chiar este recomandat să faci asta dacă colegii au simțul umorului sau doar trebuie să detensionezi situația. În general, pentru orice sarcină - doar alege cursul potrivit!',
    'pitomcy_descr' => 'Îți plac animalele? Cu siguranță - sunt atât de drăguțe, amuzante și foarte haioase. De ce să nu petreci întreaga zi însoțit de cei mai buni prieteni ai unei persoane? Descarcă colecția de cursori Animale de companie pentru tine și alege un prieten pentru tine în fiecare zi. Pictograma cursorului poate fi drăguță, precum o alpaca blândă, sau elegantă, precum un flamingo roz. Sau poate vei fi ocupat toată ziua și vei alege un unicorn citind un ziar, sau pur și simplu nu vrei să comunici cu nimeni, precum o pisică neagră malefică? Pentru orice dispoziție, avem un animal corespunzător. Un pug vesel te va înveseli chiar și în cea mai plictisitoare și gri zi, iar cursorul roz în formă de unicorn va arăta tuturor că nu ești lipsit de un simț al frumuseții, chiar fiind un bărbat brutal cu barbă. Ce se întâmplă dacă nu am chef și nu am chef să fac sarcini de rutină? Rețeta este simplă - descarcă colecția Animale de companie, schimbă cursorul mouse-ului - și voilà, soarele strălucește din nou, vremea este frumoasă, iar starea de spirit este la cel mai înalt nivel. Nu e de mirare că se spune că animalele ajută la combaterea depresiei și a tristeții!',
    'stil_i_krasota_descr' => 'În noua colecție de cursoare, am adunat o mare varietate de subiecte care ne provoacă emoții plăcute și ne înveselesc. Acest set de cursoare se numește „Stil și Frumusețe”, deoarece sunt lucrurile tale preferate care ne determină viața de zi cu zi, ne dau bucurie și ne motivează să facem lucruri importante, trezesc dorința de îmbunătățire. Ești pasionat de spațiu și visezi să mergi pe alte planete? Alege un cursor NASA sau o farfurie cu extratereștri - apropie-te de visul tău. Dacă nu-ți poți imagina viața fără muzică sau ești un rocker înrăit, atunci cursorul în stilul unei chitare electrice este pentru tine. Pensula, rigla și compasul au fost special dezvoltate pentru ingineri - astfel de imagini vor ajuta la transformarea calculelor și desenelor plictisitoare în soluții originale. O baghetă magică și adidași, un skateboard și rujul, soarele și conurile chimice - alege ce se potrivește stilului tău de viață, dorințelor și aspirațiilor tale - și sarcinile obișnuite vor deveni mai interesante, iar zilele de lucru vor fi pictate în culori noi, strălucitoare.',
    'prazdniki_descr' => 'Îți plac sărbătorile? Dar cui nu-i plac - prietenii, cadourile, din nou același weekend. Pentru a face așteptarea sărbătorilor mai plăcută, mai scurtă și mai caldă, poți nu numai să numeri zilele pe calendar, ci și să setezi iconița corespunzătoare ca cursorul mouse-ului. Să începem cu Anul Nou - vom alege un brad de Crăciun, un cadou sau Moș Crăciun, astfel încât sărbătoarea să fie strălucitoare și veselă. Poate omulețul de turtă dulce va fi mai aproape - amuzant, drăguț și întotdeauna vesel? Cu el cu siguranță nu vei avea timp să fii trist și plictisit. Continuăm să sărbătorim cu cupidonii și inimile vesele, și nu este departe de Iepurașul de Paște. Undeva printre sărbători, va fi o aniversare, care va fi și mai plăcută de așteptat cu baloane în loc de săgeata cursorului standard. Și în Halloween, poți surprinde colegii și pe cei din jurul tău cu un cursor de mouse neobișnuit sub forma unei dovleci sumbre sau a unei fantome. Un set de cursoare pentru sărbători este o oportunitate de a înveseli așteptarea, de a te pregăti în prealabil pentru distracția viitoare și de a menține o stare de spirit excelentă nu numai în ajunul sărbătorii, ci pe tot parcursul anului.',
    'flagi_descr' => 'Steagul este un simbol unic, utilizat pe scară largă în toate rețelele de socializare. Ne-am gândit, de ce să nu facem cursorul un steag? La urma urmei, este cu adevărat luminos și neobișnuit. Acum puteți petrece în fiecare zi într-o companie cu o nouă țară, iar munca nu va fi atât de monotonă și plictisitoare. Cursoarele mouse-ului pot fi acum transformate în steagul național al Chinei sau al SUA, Japonia sau Canada, și în alte 38 de opțiuni de steag, și puteți alege fie forma săgeții standard într-o culoare neobișnuită, fie cursorul în forma steagului însuși. Acest set va atrage toți iubitorii de călătorii. Cu el, puteți planifica noi călătorii și visa la călătorii lungi. Ați planificat o vacanță? Arătați tuturor în ce țară doriți să mergeți. Poate că ați decis să învățați o nouă limbă străină? Atunci acest cursor vă va susține cu siguranță și vă motivează să studiați cu atenție. Sau, ca Sheldon, iubiți doar steagurile? În toate cazurile, colecția de cursori Flags va fi o mare plus pentru desktopul dvs. și vă va muta către noi descoperiri.',
    'vokrug_sveta_descr' => 'Tuturor le place să călătorească. Cât de minunat este să vizitezi țări și orașe noi, să vezi atracțiile turistice și să te distrezi de minune în noua cultură. Păcat că nu putem călători atât de des, dar am încercat să remediem asta. Setul de cursoare „În jurul lumii” este o colecție a celor mai izbitoare imagini, simboluri ale diferitelor țări, cu ajutorul cărora, chiar și stând acasă, te poți simți ca un călător adevărat. În kitul nostru puteți găsi Japonia și Australia, Italia și Canada, SUA și Mexic - cele mai interesante, originale și pitorești țări din lume. Imaginea cursorului poate deveni o săgeată standard, în culorile steagului țării, sau poate deveni una dintre principalele atracții ale statului. De exemplu, puteți deschide documente cu Turnul Înclinat din Pisa și puteți face prezentări folosind Statuia Libertății. Vă garantăm - succesul va fi asigurat. Ei bine, sau dacă nu succes, atunci zâmbetele colegilor și recunoașterea originalității - cu siguranță. Da, și sugerarea conducerii că este timpul să plece în concediu va fi, de asemenea, utilă - doar setați valiza sau avionul ca cursor - și cel mai probabil veți zbura foarte curând.',
    'eda_i_napitki_descr' => 'Un set de cursoare sub formă de produse este o colecție incredibilă de imagini strălucitoare, gustoase și apetisante pe care toată lumea le va aprecia cu siguranță și va fi o mare adiție la browser. Ai dat vreodată clic pe broccoli sau cartofi prăjiți? Ai o astfel de ocazie - doar descarcă un nou set de cursoare și setează-le în loc de o săgeată albă plictisitoare. Cursoarele "Food" sunt realizate atât sub forma unui indicator triunghiular standard, cât și sub forma unor produse. Aici vei găsi legume și fructe, mâncărurile tale preferate, cum ar fi pizza sau hot dog, cafea, acadele și multe altele, care înveselesc orice zi. Iubești cafeaua, dar să o bei toată ziua nu este atât de bine? Completează-ți dieta cu cafea virtuală, care te va înviora și trezi, precum și îți va oferi emoții vii. Un cursor abrupt sub formă de gogoașă virtuală nu va dăuna siluetei, în timp ce oferă emoții vii și înveselește. Poți folosi cursoarele tale preferate sau poți schimba imaginea în fiecare zi - o selecție largă de cursoare va ajuta la colorarea vieții de zi cu zi și va adăuga culori noi acțiunilor familiare.',
    'cvetnye_descr' => 'Cursorul este elementul principal al browserului, cu care ne petrecem întreaga zi de lucru, studiem, comunicăm și ne relaxăm. Aspectul standard al cursorului este plictisitor și chiar oarecum deprimant, dar totuși, pentru mulți oameni, această formă este convenabilă, iar schimbarea ei va fi inconfortabilă. Dar pentru această situație, avem o soluție - un set de cursoare în culori vii, vesele, care vor adăuga varietate vieții tale de zi cu zi și vor face rezolvarea oricăror probleme mai ușoară și mai rapidă. Dacă te gândești cum să schimbi culoarea cursorului, răspundem – descarcă colecția noastră și alege soluții strălucitoare pentru fiecare zi! Poți alege tonuri monocrome în diferite culori, în funcție de starea de spirit sau de specificul muncii. De exemplu, atunci când lucrezi cu documente standard, un cursor mov se va evidenția pe fundal, iar pe un fundal întunecat, dimpotrivă, va fi mai ușor să lucrezi cu cursoare galbene. Dacă vrei o explozie de culoare, strălucire și originalitate maximă - alege un cursor curcubeu care include toate culorile spectrului - cu această pictogramă, starea de spirit va fi cu siguranță bună pe tot parcursul zilei.',
    'prank_descr' => 'Glumele la locul de muncă nu sunt întotdeauna binevenite, deoarece adesea interferează cu fluxul de lucru. Dar, cu noul set de cursoare „Glume”, poți face o glumă colegilor sau prietenilor tăi fără a-ți afecta munca sau studiul. Am dezvoltat o colecție specială care va amuza pe oricine și va oferi un motiv de relaxare într-un proces aglomerat de lucru sau de îndeplinire a altei sarcini. Pentru a schimba cursorul mouse-ului, pur și simplu descărcați kitul pe dispozitiv și selectați designul care vă place din parametri. De exemplu, puteți obține un cursor de formă standard, dar într-o stare inversată sau o săgeată curbă de o undă. Această formă nu va împiedica deloc procesul de lucru, dar în același timp va prezenta o dispoziție minunată și vă va pune într-o dispoziție pozitivă. Schimbați setările de afișare ale cursorului în funcție de starea dvs. de spirit sau în fiecare zi - și orice sarcină va deveni mai interesantă și mai plăcută, iar viața de zi cu zi nu va mai provoca emoții negative. Mai mult, astfel de cursoare pot fi utilizate chiar și pentru proiecte serioase - au culori neutre și nu ies în evidență de pe desktop.',
    'startovyj_nabor_descr' => 'Cursori din colecția de bază sunt un amestec de forme și dimensiuni standard, cu un aspect luminos și neobișnuit. Aceasta este o alegere excelentă pentru cei care preferă formele obișnuite, dar doresc să aducă diversitate, originalitate și strălucire în viața de zi cu zi. Colecția are un cursor sub forma unei mâini și o săgeată familiară într-o varietate de variații - de la logo-ul Google Chrome până la emoticoane, puteți întâlni chiar și un dragon demult uitat cu cactuși și nostalgie. Dovedim că un cursor standard poate fi, de asemenea, interesant și atractiv. Diferite culori, forme, texturi și un design interesant vă vor ajuta să alegeți cursorul pe gustul dumneavoastră sau să-l schimbați în fiecare zi, în funcție de dispoziție sau de sarcinile efectuate. Schimbarea cursorilor browserului este foarte simplă - doar instalați extensia și descărcați colecția pe dispozitivul dumneavoastră. Cursori amuzanți și interesanți nu numai că vor colora zilele de lucru, dar, de asemenea,, de exemplu, vor ajuta să faceți orice prezentare mai interesantă și, cu ajutorul cursorilor deosebit de luminoși, vor atrage atenția și asupra elementelor individuale ale raportului.',
    'fortnite_descr' => 'Fortnite a cucerit milioane de oameni din întreaga lume. Bătălii captivante, strategie și tactici, aventuri - a absorbit absolut tot ce le place jucătorilor atât de mult. Nu am putut sta deoparte și am dezvoltat un set de cursoare în stilul jocului care se va adresa nu numai jucătorilor înrăiți, ci chiar și celor care au auzit pentru prima dată despre Fortnite. Pictograma cursorului Fortnite este o imagine a unui erou sau a armei sale, elaborată până la cel mai mic detaliu. Aici puteți găsi imagini cu vulpi și pești, măști de inferno și cavaleri negri, setați-vă o săgeată sau o coasă cu țepi ca săgeată. Suntem siguri că nimeni nu va rămâne indiferent! Să fii înfricoșător sau misterios, original sau amuzant - depinde de tine. Alege-ți stilul și urmează-l sau setează cursoare personalizate în setări și schimbă-ți rolul în fiecare zi. Acum va deveni mult mai interesant și plăcut să efectuezi chiar și muncă plictisitoare și monotonă - timpul va zbura rapid într-o companie cu imagini vii și personaje preferate. Sau poate veți organiza concursuri cu colegii, care erou va fi mai puternic? Alegerea vă aparține!',
    'dota_2_descr' => 'DotA2 acum nu este doar un joc simplu, este o lume paralelă reală. În realitatea virtuală în DotA2, poți face totul - trăi, lupta, te dezvolta, călători, face prieteni. În general, totul este ca în viață, doar uneori mai interesant. Cursoarele Dota 2 sunt o continuare a unei strategii care îți va permite să obții emoții vii și să te exprimi în lumea reală. Un nou set de cursoare include cele mai izbitoare personaje din joc, precum și articole originale care nu pot fi confundate cu nimic altceva. Alege un cursor care va fi mai aproape de tine - și pornește într-o aventură fără a-ți părăsi locul de muncă. Cât de plictisitor este uneori să fii la serviciu sau să efectuezi sarcini educaționale, dar cu cursoarele de joc această problemă nu te va mai confrunta. Puțină imaginație, un cursor strălucitor - și voila, orice afacere va fi o aventură neobișnuită, cu care a face față nu va fi dificil și interesant. Nu este nevoie să te abții. Îți place Dota? Atunci asigură-te că descarci colecția noastră, selectează unul sau mai multe cursoare aleatorii simultan - și fiecare zi nouă va deveni mai strălucitoare, mai interesantă și mai saturată.',
    'minecraft_descr' => 'Cursori de mouse sub formă de săgeți standard și degete au devenit plictisitoare pentru toată lumea. Dacă ești fan al neobișnuitului și originalului, atunci este timpul să schimbi cursorul mouse-ului și să-i oferi un design mai interesant. Am dezvoltat o colecție de cursori în stilul celebrului joc Minecraft, unde poți găsi cele mai izbitoare personaje. Lup și vulpe, Alex și Creeper, sabie de diamant și pește - poți alege pe cel care îți place cel mai mult sau să instalezi un nou erou în fiecare zi. Aceștia sunt cursori reali pentru jucători și vor plăcea absolut tuturor - la urma urmei, cine dintre noi nu a jucat Minecraft? Suntem siguri că aceștia pur și simplu nu există. Jos cu viața de zi cu zi plictisitoare - este timpul să te scufunzi în aventuri, ceea ce se poate face chiar și fără a părăsi scaunul de acasă sau de la birou. Va fi mai interesant să pregătești un raport și să reduci soldul cu o armă - orice sarcină va deveni mai plăcută și nu te va lăsa să te plictisești pe loc. Descarcă noua colecție de cursuri Minecraft - setează-le și chiar și în cea mai gri și mai plictisitoare zi, starea ta de spirit va fi întotdeauna la cel mai bun nivel. Și colegii vor invidia rezultatele tale - este pur și simplu imposibil să nu-ți faci treaba cu ajutorul eroilor curajoși din Minecraft.',
    'astrology-signs-zodiac' => 'Semne zodiacale',
    'sports-cars_short_descr' => 'Mașini puternice și elegante, construite pentru viteză și agilitate',
    'spider-man' => 'Spider-Man',
    'astrology-signs-zodiac_short_descr' => 'Un set de 12 simboluri astrologice care reprezintă trăsături de personalitate, energii cosmice și tipare de viață.',
    'sports-cars' => 'Mașini sport',
    'sports-cars_descr' => 'Mașinile sport sunt vehicule de înaltă performanță concepute pentru accelerație rapidă, manevrabilitate precisă și o experiență de condus incitantă. De la coupe-uri elegante la roadstere agile, această categorie prezintă unele dintre cele mai iconice mașini construite pentru senzația drumului sau a pistei. Ideal pentru pasionații care ador viteza, designul și puterea. 🏎️🔥',
    'spider-man_short_descr' => 'Eroi din universul Spider-Man',
    'starwars' => 'Star Wars',
    'spider-man_descr' => 'O colecție de personaje și eroi din universul Spider-Man. Include diverse versiuni ale lui Spider-Man, aliați și stiluri unice din benzi desenate, jocuri și seriale animate. Fiecare design reflectă agilitatea, curajul și identitatea vizuală care definește lumea Spider-Man.',
    'astrology-signs-zodiac_descr' => 'Semnele zodiacale ♈♉♊♋♌♍♎♏♐♑♒♓ sunt douăsprezece diviziuni simbolice ale centurii cerești folosite în astrologie. Fiecare semn este asociat cu date specifice, elemente (🌍 Pământ, 🔥 Foc, 🌊 Apă, 💨 Aer), planete conducătoare și caracteristici unice de personalitate. Astrologii folosesc zodiile pentru a interpreta comportamentul, a prezice compatibilitatea și a explora căile vieții. Indiferent dacă ești un Leu pasional 🔥 sau un Pești contemplativ 🌊, semnul tău oferă o perspectivă asupra lumii tale interioare. Această categorie include toate cele 12 semne, semnificațiile lor și reprezentările vizuale.',
    'roblox-2025' => 'Roblox 2025',
    'roblox-2025_short_descr' => 'Personaje din cea mai recentă serie Roblox 🕹️🚀',
    'starwars_descr' => 'Scufundă-te în galaxia foarte, foarte îndepărtată cu această colecție care prezintă eroi legendari, puternici lorzi Sith, droizi, rebeli și multe altele. De la Cavaleri Jedi la stormtrooperi, fiecare pictogramă aduce spiritul Războiului Stelelor la viață sub formă de cursor. Perfect pentru fanii fiecărei trilogii. 🌌',
    'starwars_short_descr' => 'Personaje și simboluri din universul Războiul Stelelor',
    'glitter' => 'Sclipici',
    'glitter_short_descr' => 'Cursori strălucitori și sclipitori cu stil de sclipici ✨🌟',
    'glitter_descr' => 'O colecție plină de farmec de cursoare inspirate de texturi sclipitoare și efecte vizuale strălucitoare. Perfectă pentru cei care iubesc o estetică strălucitoare pe ecranul lor. Aceste cursoare aduc sclipire, eleganță și un pic de magie la fiecare clic.',
    'roblox-2025_descr' => 'O colecție complet nouă din 2025, cu personaje iconice și moderne Roblox. Include noobi clasici, legende horror și avatare preferate de fani din jocurile populare. Conceput într-un stil distractiv și colorat, perfect pentru copii și fanii Roblox de toate vârstele.',
];
