<?php

return [
    'title' => 'Cursor Style - Politica de Cookie-uri',
    'descr' => 'O politică privind cookie-urile atunci când vizitați site-ul web cursor.style sau extensia „Cursor Style”. Câteva reguli pe care ar trebui să le luați în considerare atunci când utilizați produsul nostru.',
    'text' => '<h2> Politica de cookie-uri </h2>
<p> Când vizitați site-ul nostru web cursor.style sau extensia "Cursor Style" în panoul browserului dvs., sau când interacționați cu reprezentanții noștri (denumirea colectivă "Serviciul"), vom folosi (și vom permite terților să folosească) balize web, cookie-uri, etichete pixel, scripturi, tag-uri, API-uri și alte tehnologii ("Tehnologii de urmărire"). Acest lucru este explicat în această politică ("Politica de cookie-uri"), care face parte din <a href="/privacy"> Politica de confidențialitate </a>. </p>
<p> Tehnologiile de urmărire ne permit să colectăm automat informații despre dvs. și comportamentul dvs. pe Internet pentru a îmbunătăți navigarea în Serviciul nostru, a îmbunătăți performanța Serviciului nostru și a facilita experiența dvs. în Serviciul nostru. De asemenea, folosim aceste informații pentru a colecta statistici despre utilizarea Serviciului nostru, pentru a efectua analize, pentru a livra conținut care se potrivește intereselor dvs. și pentru a administra servicii pentru Utilizatorii, clienții și partenerii noștri. De asemenea, permitem terților să colecteze informații despre dvs. folosind tehnologii de urmărire. </p>
<p> Ce sunt cookie-urile? Cookie-urile sunt fișiere text mici (constând doar din litere și numere) pe care serverul web le plasează pe computerul sau dispozitivul dvs. mobil atunci când vizitați o pagină web. Utilizarea unui cookie poate contribui la îmbunătățirea funcționalității Serviciilor noastre, de exemplu, memorarea preferințelor și setărilor dvs. de limbă. Puteți găsi mai multe informații despre cookie-uri la <a href="http://www.allaboutcookies.org"> allaboutcookies.org </a>. </p>
<p> Cookie-urile sunt utilizate pe scară largă pentru performanța site-urilor web. Utilizarea cookie-urilor vă permite să navigați eficient între pagini. Cookie-urile vă rețin preferințele și fac interacțiunea dintre dvs. și Servicii mai ușoară și mai eficientă. </p>
<p> Folosim tehnologii de urmărire când vizitați sau accesați Serviciile noastre (de obicei, când vizitați site-urile noastre web) - acestea se numesc „Tehnologii de urmărire de primă parte”. În plus, tehnologiile de urmărire sunt stocate de alte organizații terțe (de exemplu, furnizorii noștri de servicii analitice, parteneri de afaceri și agenți de publicitate) care postează conținut pe Serviciile noastre - acestea se numesc „Tehnologii de urmărire terțe”. Ambele tipuri de tehnologii de urmărire pot fi stocate fie pentru timpul vizitei dvs. la Serviciile noastre, fie pentru vizite repetate. </p>
<h3> Ce tipuri de tehnologii de urmărire folosim? Există cinci tipuri principale de tehnologii de urmărire: </h3>
<ul>
<li> <b> Tehnologii de urmărire strict necesare </b> <br> <p> Aceste tehnologii de urmărire sunt necesare pentru a vă putea conecta, naviga și utiliza funcțiile Serviciilor noastre sau pentru a furniza serviciul pe care îl solicitați (de exemplu, numele de utilizator). Nu avem nevoie de acordul dvs. pentru a utiliza aceste tehnologii de urmărire. Aceste tehnologii de urmărire pot fi utilizate în scopuri de securitate și integritate, de exemplu, pentru a identifica încălcările politicilor noastre, precum și pentru funcții de asistență sau securitate. </p> </li>
<li> <b> Tehnologii de urmărire a funcționalității </b> <br> <p>
Aceste tehnologii de urmărire permit serviciilor noastre să-și amintească opțiunile dvs. (cum ar fi limba) și să ofere funcții avansate și personalizate. De exemplu, aceste tehnologii de urmărire sunt utilizate pentru autentificare (pentru a reține când sunteți conectat) și pentru a susține alte funcții ale Serviciilor noastre. </p> </li>
<li> <b> Tehnologii de urmărire a performanței </b> <br> <p>
Aceste tehnologii de urmărire colectează informații despre activitatea dvs. online (de exemplu, durata vizitei dvs. la Serviciile noastre), inclusiv date comportamentale și indicatori ai implicării conținutului. Aceste tehnologii de urmărire sunt utilizate pentru analize, cercetare și statistici (bazate pe informații agregate). </p> </li>
<li> <b> Tehnologii de urmărire pentru marketing sau publicitate </b> <br> <p>
Aceste tehnologii de urmărire sunt utilizate pentru a vă oferi oferte speciale și publicitate bazate pe interesele dvs., precum și pentru a efectua campanii de marketing prin e-mail. Ele pot fi, de asemenea, utilizate pentru a limita numărul de vizualizări ale unei reclame, precum și pentru a măsura eficacitatea unei campanii publicitare. Acestea sunt de obicei găzduite de agenții noștri de publicitate (de exemplu, rețele de publicitate) și le oferă o idee despre persoanele care văd și interacționează cu reclamele lor, vizitează site-urile lor web sau folosesc aplicația lor. </p> </li>
<li> <b> Tehnologii de urmărire a rețelelor sociale </b> <br> <p>
Site-ul nostru web include funcții ale rețelelor sociale, cum ar fi butoanele Like sau Share pe Facebook și Vkontakte, sau servicii de conectare terțe. Aceste funcții sunt fie postate de o terță parte, fie postate direct pe Serviciile noastre. Interacțiunea dvs. cu aceste funcții este guvernată de declarația de confidențialitate a companiei care oferă aceste funcții. </p> </li> </ul>
<h3> Următoarele sunt cookie-urile pe care le puteți găsi în Serviciile noastre: </h3>
<ul>
<li> <b> Cookie-uri analitice </b> <br> <p> Aceste tehnologii de urmărire sunt utilizate pentru a colecta informații despre modul în care interacționați cu conținutul din Serviciile noastre, în scopuri de atribuire (de exemplu, URL-uri de recomandare) etc. Folosim aceste informații pentru a compila rapoarte, a calcula veniturile datorate nouă și a ne ajuta să îmbunătățim Serviciile și să oferim produse și conținut personalizate. </p> </li>
<li> <b> Google Analytics </b> <br> <p> Acest cookie este utilizat pentru a colecta informații despre modul în care vizitatorii folosesc Platforma noastră. Folosim aceste informații pentru a compila rapoarte și pentru a îmbunătăți Platforma. Cookie-urile colectează informații în formă anonimă, inclusiv numărul de vizitatori ai Platformei, de unde au venit vizitatorii pe Platformă și paginile pe care le-au vizitat. <br> <a href = "https://policies.google.com/privacy?hl=en" > Politica de confidențialitate </a> </p> </li>
<li> <b> Google Tag Manager </b> <br> <p> Acest cookie este asociat cu Google Tag Manager, pe care îl folosim pentru a încărca scripturi pe paginile site-ului nostru web. <br> <a href = "https: / /policies.google.com/privacy?hl=en">Politica de confidențialitate </a> </p> </li>
</ul>
<p> Vă rugăm să rețineți că nu recunoaștem și nici nu răspundem la alertele automate ale browserului cu privire la tehnologiile de urmărire, inclusiv solicitările Do Not Track. Cu toate acestea, există diverse modalități de gestionare și gestionare a setărilor cookie-urilor. Amintiți-vă că, la ștergerea sau blocarea cookie-urilor, unele funcții ale Serviciilor pot să nu funcționeze corect sau nu atât de eficient. </p>
<p> Majoritatea browserelor web vă oferă unele informații generale despre cookie-uri, vă permit să vedeți ce cookie-uri sunt stocate pe dispozitivul dvs., vă permit să le ștergeți pe toate sau pe cele individuale și, de asemenea, vă permit să blocați sau să permiteți utilizarea cookie-urilor pentru toate site-urile web sau site-uri selectate individual. De asemenea, puteți dezactiva separat cookie-urile terțe. Vă rugăm să rețineți că setările oferite de browser sau dispozitiv se aplică adesea numai pentru acel browser sau dispozitiv anume. </p>
<h3> Informațiile despre cookie-uri se găsesc de obicei în secțiunea Ajutor a unui browser web. </h3>
<p> Următoarele sunt link-uri către unele browsere web utilizate frecvent: </p>
<p><a href="https://support.google.com/chrome/answer/95647?hl=en"> Chrome </a> <br>
<a href="https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies"> Internet Explorer și Microsoft Edge </a> <br>
<a href="https://support.mozilla.org/en/kb/kuki-informaciya-kotoruyu-veb-sajty-hranyat-na-vas"> Mozilla Firefox </a> <br>
<a href="https://support.apple.com/ru-ru/guide/safari/sfri11471/mac"> Safari </a> </p>
<p> Puteți dezactiva unele cookie-uri terțe pentru direcționare / publicitate făcând clic pe următorul link: <a href="http://optout.networkadvertising.org/?c=1"> Renunțați la publicitatea bazată pe interese </a>. </p>
				',
];
