<?php

return [
    'title' => 'Cursor Style - Politica de confidențialitate',
    'descr' => 'În „Cursor Style”, disponibil pe cursor.style sau prin extensia Chrome, una dintre prioritățile noastre principale este confidențialitatea vizitatorilor noștri. În această secțiune vom vorbi despre toate aspectele legate de utilizarea extensiei.',
    'text' => '<h2> Politica de confidențialitate </h2>
                <p> În Cursor Style, disponibil la <a href="https://cursor.style"> cursor.style </a> sau prin extensia Chrome, una dintre principalele noastre priorități este confidențialitatea vizitatorilor noștri. Acest document de politică de confidențialitate conține tipurile de informații care sunt colectate și înregistrate de către site-ul cursor.style și modul în care le utilizăm. Dacă aveți întrebări suplimentare sau aveți nevoie de mai multe informații despre politica noastră de confidențialitate, nu ezitați să ne contactați. </p>
                <p> Extensia "Cursor Style" și site-ul web respectă procedura standard de utilizare a fișierelor jurnal. Aceste fișiere înregistrează vizitatorii atunci când vizitează site-uri web sau utilizează extensia noastră. Toate companiile de găzduire fac acest lucru și fac parte din analizele serviciului de găzduire. Informațiile colectate prin fișierele jurnal includ adresele de protocol Internet (IP), tipul de browser, furnizorul de servicii de internet (ISP), data și ora, paginile de tranziție / ieșire și, eventual, numărul de clicuri. Acestea nu sunt asociate cu nicio informație de identificare personală. Scopul acestor informații este de a analiza tendințele, de a administra site-ul și de a extinde, de a urmări mișcarea utilizatorilor pe site și de a extinde și de a colecta informații demografice. </p>
                <p> Ca orice alt site, cursor.style folosește cookie-uri. Aceste cookie-uri sunt utilizate pentru a stoca informații, inclusiv preferințele vizitatorului și paginile de pe site-ul web pe care vizitatorul le-a vizitat sau le-a vizitat. Aceste informații sunt utilizate pentru a optimiza experiența utilizatorului prin personalizarea conținutului paginii noastre web pe baza tipului de browser al vizitatorului și / sau a altor informații. De asemenea, folosim reclame de la terți pe cursor.style pentru a susține proiectul și a susține site-ul nostru web. Unii dintre acești agenți de publicitate pot utiliza tehnologii precum cookie-uri și web beacons atunci când fac publicitate pe site-ul nostru web, care vor trimite, de asemenea, acestor agenți de publicitate (de exemplu, Google prin programul Google AdSense) informații, inclusiv adresa dvs. IP, furnizorul dvs. de internet, browserul pe care l-ați utilizat pentru a vizita site-ul nostru și, în unele cazuri, dacă aveți Flash instalat. Acest lucru este de obicei utilizat în scopuri de geotargetare (de exemplu, afișarea anunțurilor pentru vânzarea de bunuri în orașul dvs.) sau pentru afișarea anumitor anunțuri pe baza anumitor site-uri web vizitate (de exemplu, afișarea anunțurilor de cumpărare pentru cei care vizitează frecvent site-uri de cumpărături). </ P >
                <p> Puteți dezactiva sau dezactiva selectiv cookie-urile noastre sau cookie-urile terțe în setările browserului sau gestionând setările din programe precum Kaspersky etc. Cu toate acestea, acest lucru poate afecta modul în care interacționați cu site-ul nostru, precum și cu alte site-uri. Aceasta poate include imposibilitatea de a vă conecta la servicii sau programe, cum ar fi conectarea la forumuri sau conturi. </p>
<p> Google este unul dintre furnizorii terți de pe site-ul nostru. De asemenea, folosește cookie-uri, cunoscute sub numele de cookie-uri DART, pentru a difuza anunțuri vizitatorilor site-ului nostru pe baza vizitelor lor pe cursor.style și pe alte site-uri de pe Internet. Cu toate acestea, vizitatorii pot renunța la utilizarea cookie-urilor DART vizitând politica de confidențialitate a rețelei de publicitate și conținut Google la <a href="https://policies.google.com/technologies/ads"> următoarea adresă </a>. Unii dintre agenții de publicitate de pe site-ul nostru web pot utiliza cookie-uri și semnalizatoare web. Fiecare dintre partenerii noștri de publicitate are propria politică de confidențialitate pentru politicile sale cu privire la datele utilizatorilor. Puteți citi mai multe despre Politicile lor de confidențialitate <a href="https://policies.google.com/technologies/ads"> aici </a>. </p>
                <p> Site-ul nostru web utilizează Google Analytics, un serviciu de analiză web al Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com („Google Analytics” sau „Google”). Google Analytics utilizează cookie-uri care sunt stocate pe computerul dvs. pentru a facilita analiza utilizării site-ului web. Informațiile generate de aceste cookie-uri, cum ar fi ora, locul și frecvența vizitelor dvs. pe site-ul nostru web, inclusiv adresa dvs. IP, sunt transferate într-o locație Google din SUA și stocate acolo. De asemenea, Google poate transfera aceste informații unor terți, dacă acest lucru este impus de lege sau dacă terții prelucrează aceste date în numele Google. Google declară că nu va asocia niciodată adresa dvs. IP cu alte date Google. Puteți împiedica setarea cookie-urilor modificând setările software-ului browserului dvs. în consecință, așa cum este specificat în această Politică de confidențialitate. Cu toate acestea, trebuie să fiți conștient că, în acest fel, nu veți putea utiliza pe deplin toate funcțiile site-ului nostru web. </p>
                <p> Google Analytics folosește, de asemenea, imagini electronice cunoscute sub numele de web beacons (uneori numite GIF-uri cu un singur pixel) și sunt utilizate cu cookie-uri pentru a compila statistici agregate pentru a analiza utilizarea site-ului nostru.
Puteți găsi mai multe informații despre modul de instalare a add-on-ului browserului pe care îl conectați mai sus <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> link </a>.
Acest site utilizează Google Tag Manager. Acest serviciu vă permite să gestionați etichete de site prin interfață. Google Tag Manager implementează doar etichete. Aceasta înseamnă că cookie-urile nu sunt setate și nu sunt înregistrate date personale. Google Tag Manager lansează alte tag-uri, care la rândul lor pot înregistra date. Cu toate acestea, Google Tag Manager nu are acces la aceste date. Dacă etichetele au fost dezactivate la nivel de domeniu sau cookie, acestea sunt salvate pentru toate etichetele de urmărire, dacă sunt implementate folosind Google Tag Manager. Puteți afla mai multe despre Google Tag Manager vizitând <a href="http://www.google.com/tagmanager/use-policy.html"> link </a>. </p>
<p> Puteți citi această listă pentru a găsi Politica de confidențialitate pentru fiecare dintre partenerii de publicitate "Cursor Style". Serverele de anunțuri terțe sau rețelele de anunțuri utilizează tehnologii precum cookie-uri, JavaScript sau web beacons, care sunt utilizate în reclamele și linkurile lor respective, care sunt afișate în „Cursor Style” și trimise direct browserelor utilizatorilor. Acestea vă obțin automat adresa IP atunci când se întâmplă acest lucru. Aceste tehnologii sunt utilizate pentru a măsura eficacitatea campaniilor lor publicitare și / sau pentru a personaliza conținutul publicitar pe care îl vedeți pe site-urile web pe care le vizitați. Vă rugăm să rețineți că „Cursor Style” nu are acces sau control asupra acestor cookie-uri care sunt utilizate de agenții de publicitate terți. Politica de confidențialitate Cursor Style nu se aplică altor agenți de publicitate sau site-uri web. Prin urmare, vă recomandăm să consultați politicile de confidențialitate relevante ale acestor servere de anunțuri terțe pentru mai multe informații. Acesta poate include metodele și instrucțiunile lor cu privire la modul de renunțare la anumite opțiuni. Puteți găsi linkuri către aceste Politici de confidențialitate ale terților mai sus sau pe site-urile web ale acestor servicii terțe. </p>
                <p> Puteți dezactiva cookie-urile în setările browserului. Pentru a afla mai multe despre gestionarea cookie-urilor în browserele web specifice, o puteți găsi pe site-urile web ale browserelor respective. O altă parte a priorității noastre este de a adăuga protecție pentru copii atunci când utilizați Internetul. Încurajăm părinții și tutorii să observe, să participe și / sau să monitorizeze și să direcționeze activitățile lor pe Internet. "Cursor Style" nu colectează cu bună știință informații personale de la copii cu vârsta sub 13 ani. Dacă credeți că copilul dvs. a furnizat astfel de informații pe site-ul nostru web, vă recomandăm insistent să ne contactați imediat și vom face tot posibilul pentru a elimina rapid astfel de informații din înregistrările noastre. Această politică de confidențialitate se aplică numai activităților noastre online și este valabilă pentru vizitatorii site-ului nostru web în legătură cu informațiile pe care le-au împărtășit și / sau le-au colectat în „Cursor Style”. Această politică nu se aplică niciunei informații colectate offline sau prin alte canale decât acest site web. </p>
                <p> Puteți citi mai multe despre utilizarea cookie-urilor în Serviciul nostru în <a href="/cookie-policy"> Politica noastră privind cookie-urile </a>. </p> ',
];
