<?php

return [
    'title' => 'Cursor Style - Gizlilik Politikası',
    'descr' => 'Chrome eklentisi aracılığıyla veya cursor.style adresinde bulunan “Cursor Style”da, en önemli önceliklerimizden biri ziyaretçilerimizin gizliliğidir. Bu bölümde, eklentiyle çalışmanın tüm yönleri hakkında konuşacağız.',
    'text' => '<h2> Gizlilik Politikası </h2>
                <p> <a href="https://cursor.style"> cursor.style </a> adresinde veya Chrome uzantısı aracılığıyla kullanılabilen Cursor Style\'da, en büyük önceliklerimizden biri ziyaretçilerimizin gizliliğidir. Bu Gizlilik Politikası belgesi, cursor.style web sitesi tarafından toplanan ve kaydedilen bilgilerin türlerini ve bunları nasıl kullandığımızı içerir. Gizlilik Politikamız hakkında ek sorularınız varsa veya daha fazla bilgiye ihtiyacınız varsa, bizimle iletişime geçmekten çekinmeyin. </p>
                <p> "Cursor Style" uzantısı ve web sitesi, günlük dosyalarını kullanmak için standart prosedürü izler. Bu dosyalar, ziyaretçiler web sitelerini ziyaret ettiğinde veya uzantımızı kullandığında kaydedilir. Tüm barındırma şirketleri bunu yapar ve barındırma hizmeti analizinin bir parçasıdır. Günlük dosyaları aracılığıyla toplanan bilgiler arasında İnternet Protokolü (IP) adresleri, tarayıcı türü, İnternet Servis Sağlayıcısı (ISP), tarih ve saat damgası, geçiş / çıkış sayfaları ve muhtemelen tıklama sayısı bulunur. Kişisel olarak tanımlanabilir herhangi bir bilgiyle ilişkilendirilmezler. Bu bilgilerin amacı, eğilimleri analiz etmek, siteyi yönetmek ve genişletmek, sitedeki kullanıcıların hareketini izlemek ve genişletmek ve demografik bilgiler toplamaktır. </p>
                <p> Diğer tüm siteler gibi, cursor.style de çerezleri kullanır. Bu çerezler, ziyaretçinin tercihleri ve ziyaretçinin ziyaret ettiği veya ziyaret ettiği web sitesindeki sayfalar dahil olmak üzere bilgileri depolamak için kullanılır. Bu bilgiler, web sayfamızın içeriğini ziyaretçinin tarayıcısının türüne ve / veya diğer bilgilere göre özelleştirerek kullanıcı deneyimini optimize etmek için kullanılır. Ayrıca projeyi desteklemek ve web sitemizi desteklemek için cursor.style\'da üçüncü taraf reklamları kullanıyoruz. Bu reklamverenlerden bazıları, web sitemizde reklam verdiklerinde çerezler ve web işaretleri gibi teknolojiler kullanabilir ve bu da bu reklamverenlere (örneğin, Google AdSense programı aracılığıyla Google) IP adresiniz, İnternet sağlayıcınız, sitelerimizi ziyaret etmek için kullandığınız tarayıcı ve bazı durumlarda Flash yüklüyse bilgilerinizi de gönderecektir. Bu genellikle coğrafi hedefleme amacıyla (örneğin, şehrinizdeki mal satışları için reklamları görüntülemek) veya belirli ziyaret edilen web sitelerine göre belirli reklamları görüntülemek için (örneğin, alışveriş sitelerini sık sık ziyaret edenlere satın alma duyuruları görüntülemek) kullanılır. </ P >
                <p> Tarayıcı ayarlarında veya Kaspersky vb. programlardaki ayarları yöneterek çerezlerimizi veya üçüncü taraf çerezlerini devre dışı bırakabilir veya seçerek devre dışı bırakabilirsiniz. Ancak bu, sitemizle ve diğer sitelerle nasıl etkileşim kurduğunuzu etkileyebilir. Bu, forumlara veya hesaplara giriş yapmak gibi hizmetlere veya programlara giriş yapamama sorununu içerebilir. </p>
<p> Google, sitemizdeki üçüncü taraf sağlayıcılardan biridir. Ayrıca, cursor.style ve İnternet\'teki diğer siteleri ziyaretlerine göre sitemizin ziyaretçilerine reklam sunmak için DART çerezleri olarak bilinen çerezleri kullanır. Ancak ziyaretçiler, <a href="https://policies.google.com/technologies/ads"> aşağıdaki adresi </a> ziyaret ederek Google Reklamcılık ve İçerik Ağı gizlilik politikasını kullanarak DART çerezlerinin kullanımını devre dışı bırakabilirler. Web sitemizdeki reklamverenlerden bazıları çerez ve web işaretleri kullanabilir. Reklam ortaklarımızın her birinin, kullanıcı verilerine ilişkin politikaları için kendi gizlilik politikası vardır. Gizlilik Politikaları hakkında daha fazla bilgiyi <a href="https://policies.google.com/technologies/ads"> buradan </a> okuyabilirsiniz. </p>
                <p> Web sitemiz, Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com (“Google Analytics” veya “Google”) şirketinin bir web analiz hizmeti olan Google Analytics\'i kullanır. Google Analytics, web sitesini kullanımınızı analiz etmeyi kolaylaştırmak için bilgisayarınızda depolanan çerezleri kullanır. Web sitemize yaptığınız ziyaretlerin zamanı, yeri ve sıklığı dahil olmak üzere IP adresiniz gibi bu çerezler tarafından oluşturulan bilgiler, ABD\'deki bir Google konumuna aktarılır ve orada saklanır. Google ayrıca, yasa gerektirdiği takdirde veya üçüncü taraflar bu verileri Google adına işlerse bu bilgileri üçüncü taraflara aktarabilir. Google, IP adresinizi diğer Google verileriyle asla ilişkilendirmeyeceğini belirtir. Bu Gizlilik Politikasında belirtildiği gibi, tarayıcı yazılımı ayarlarınızı buna göre değiştirerek çerezlerin ayarlanmasını engelleyebilirsiniz. Ancak, bu şekilde web sitemizin tüm işlevlerini tam olarak kullanamayacağınızı unutmamalısınız. </p>
                <p> Google Analytics ayrıca, bazen tek piksellik GIF\'ler olarak adlandırılan web işaretleri olarak bilinen elektronik görüntüleri de kullanır ve sitemizin kullanımını analiz etmek için toplanan istatistikleri derlemek için çerezlerle birlikte kullanılır.
Yukarıdaki <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> bağlantıya </a> bağladığınız tarayıcı eklentisini nasıl yükleyeceğiniz hakkında daha fazla bilgiyi bulabilirsiniz.
Bu site, Google Etiket Yöneticisi\'ni kullanır. Bu hizmet, site etiketlerini arayüz aracılığıyla yönetmenize olanak tanır. Google Etiket Yöneticisi yalnızca etiketleri uygular. Bu, çerezlerin ayarlanmadığı ve hiçbir kişisel verinin kaydedilmediği anlamına gelir. Google Etiket Yöneticisi, sırayla veri kaydedebilecek diğer etiketleri başlatır. Ancak Google Etiket Yöneticisi, bu verilere erişemez. Etiketler alan veya çerez düzeyinde devre dışı bırakılmışsa, Google Etiket Yöneticisi kullanılarak uygulanmışsa tüm izleme etiketleri için kaydedilirler. <a href="http://www.google.com/tagmanager/use-policy.html"> bağlantısını </a> ziyaret ederek Google Etiket Yöneticisi hakkında daha fazla bilgi edinebilirsiniz. </p>
<p> "Cursor Style" reklam ortaklarının her birinin Gizlilik Politikasını bulmak için bu listeyi inceleyebilirsiniz. Üçüncü taraf reklam sunucuları veya reklam ağları, "Cursor Style"\'da görüntülenen ve doğrudan kullanıcının tarayıcısına gönderilen ilgili reklamlarında ve bağlantılarında kullanılan çerezler, JavaScript veya web işaretleri gibi teknolojileri kullanır. Bu olduğunda otomatik olarak IP adresinizi alırlar. Bu teknolojiler, reklam kampanyalarının etkinliğini ölçmek ve / veya ziyaret ettiğiniz web sitelerinde gördüğünüz reklam içeriğini kişiselleştirmek için kullanılır. Lütfen "Cursor Style"\'ın, üçüncü taraf reklamverenler tarafından kullanılan bu çerezlere erişimi veya kontrolü olmadığını unutmayın. Cursor Style gizlilik politikası, diğer reklamverenler veya web siteleri için geçerli değildir. Bu nedenle, daha fazla bilgi için bu üçüncü taraf reklam sunucularının ilgili gizlilik politikalarını gözden geçirmenizi öneririz. Belirli seçeneklerden nasıl vazgeçileceğine ilişkin yöntemlerini ve talimatlarını içerebilir. Bu Üçüncü Taraf Gizlilik Politikalarına veya bu üçüncü taraf hizmetlerin web sitelerine yukarıdan bağlantılar bulabilirsiniz. </p>
                <p> Tarayıcı ayarlarınızdaki çerezleri devre dışı bırakabilirsiniz. Belirli web tarayıcılarında çerez yönetimi hakkında daha fazla bilgi edinmek için ilgili tarayıcı web sitelerinde bulabilirsiniz. Önceliğimizin diğer bir parçası, İnternet\'i kullanırken çocuk koruması eklemektir. Ebeveynleri ve vasileri, İnternet\'teki faaliyetlerini gözlemlemeye, katılmaya ve / veya izlemeye ve yönlendirmeye teşvik ediyoruz. "Cursor Style", 13 yaşın altındaki çocuklardan bilerek kişisel bilgi toplamaz. Çocuğunuzun web sitemizde bu tür bilgileri sağladığını düşünüyorsanız, derhal bizimle iletişime geçmenizi şiddetle tavsiye ederiz ve bu tür bilgileri kayıtlarımızdan hızla kaldırmak için elimizden geleni yapacağız. Bu Gizlilik Politikası yalnızca çevrimiçi faaliyetlerimiz için geçerlidir ve "Cursor Style"\'da paylaştıkları ve / veya topladıkları bilgilerle ilgili olarak web sitemizi ziyaret edenler için geçerlidir. Bu politika, çevrimdışı veya bu web sitesi dışındaki kanallar aracılığıyla toplanan hiçbir bilgi için geçerli değildir. </p>
                <p> Hizmetimizde çerezlerin kullanımı hakkında daha fazlasını <a href="/cookie-policy"> Çerez Politikamızda </a> okuyabilirsiniz. </p> ',
];
