<?php

return [
    'title' => 'Cursor Style - Ürünümüzün kullanım koşulları',
    'descr' => 'Kullanım koşulları sizinle “Cursor Style” (“Hizmet”, “biz” veya “Hizmet”) arasında girilmiştir. Bu hizmet yalnızca 13 yaş ve üzeri kullanıcılara kişisel kullanım için sunulmakta ve ticari kullanım için sunulmamaktadır.',
    'text' => '<h2> Hizmet Şartları </h2>
<h3> LÜTFEN WEB SİTESİNİ VE UZANTISINI KULLANMADAN ÖNCE BU ŞARTLAR VE KOŞULLARI OKUYUN. </h3>
<p> Bu kullanım şartları, siz ve "Cursor Style" ("Hizmet", "biz" veya "Hizmet") arasında girilmiştir. Aşağıdaki hüküm ve koşullar, atıfta bulunularak açıkça dahil ettikleri herhangi bir belgeyle birlikte (topluca, bu "Kullanım Şartları"), cursor.style web sitesine ve tarayıcı uzantılarına, hizmetimiz üzerinden veya aracılığıyla sunulan herhangi bir içerik, işlevsellik ve hizmetler dahil olmak üzere (topluca “Hizmet”) erişiminizi ve kullanımınızı yönetir. </p>
<p> Web sitesini veya uzantısını kullanarak, bu Kullanım Şartlarına uymayı kabul ve taahhüt edersiniz. Bu Kullanım Şartlarını veya <a href="/privacy"> Gizlilik Politikamızı </a>kabul etmiyorsanız, Web Sitesine ve Uzantıya erişmemeli veya kullanmamalısınız. </p>
<p> Bu hizmet, yalnızca kişisel kullanım için ve ticari kullanım için değil, yalnızca 13 yaş ve üzeri kullanıcılara sunulmaktadır ve mevcuttur. Bu Hizmeti kullanarak, (I) 13 yaş veya daha büyüksünüz, (II) yürürlükteki yasalara uygun olarak Web Sitelerini kullanmanız yasaklanmamıştır ve (III) Hizmeti yalnızca kişisel ihtiyaçlarınız için kullanıyorsunuz. Bu gereksinimleri karşılamıyorsanız, Hizmete erişmemeli veya kullanmamalısınız. </p>
<p> Bu Kullanım Şartlarını zaman zaman kendi takdirimize bağlı olarak revize edebilir ve güncelleyebiliriz. Tüm değişiklikler, yayınlandıktan hemen sonra yürürlüğe girer. Revize edilmiş Kullanım Şartlarının yayınlanmasından sonra Hizmeti kullanmaya devam etmeniz, değişiklikleri kabul ettiğiniz ve bunlara uyduğunuz anlamına gelir. Size karşı bağlayıcı oldukları için, herhangi bir değişiklikten haberdar olmak için bu sayfayı sık sık ziyaret etmeniz beklenir. </p>
<p> Bu Web Sitesini ve Uzantıyı, Web Sitesinde ve Uzantıda sağladığımız herhangi bir hizmet veya materyali, tamamen kendi takdirimize bağlı olarak, bildirimde bulunmaksızın geri çekme veya değiştirme hakkını saklı tutarız. Sitemizin, uzantımızın veya üzerindeki herhangi bir içeriğin her zaman erişilebilir olacağını veya kesintiye uğrayacağını garanti etmiyoruz. Herhangi bir nedenle Hizmetin tamamının veya herhangi bir bölümünün herhangi bir zamanda veya herhangi bir süre boyunca kullanılamaması durumunda sorumlu olmayacağız. Zaman zaman, Web Sitesinin veya Uzantının veya tüm Hizmetin belirli bölümlerine kullanıcıların erişimini kısıtlayabiliriz. </p>
<p> Hizmete erişiminizin olduğundan emin olmak için gerekli tüm önlemleri almaktan siz sorumlusunuz. İnternet bağlantınız aracılığıyla Hizmete erişen tüm kişilerin bu Kullanım Şartlarından haberdar olmalarını ve bunlara uymalarını sağlamak. Hizmete veya sunduğu bazı kaynaklara erişmek için, belirli bilgiler veya diğer bilgileri sağlamanız istenebilir. Bu Hizmeti veya başka bir şekilde kullanarak bize sağladığınız tüm bilgilerin, etkileşimli özelliklerin kullanımı dahil ancak bunlarla sınırlı olmamak üzere, <a href="/privacy"> Gizlilik Politikamız </a>tarafından yönetildiğini ve bilgilerinizle ilgili olarak aldığımız tüm eylemleri kabul ettiğinizi kabul edersiniz. <a href="/privacy"> Gizlilik Politikamıza </a>uygundur. </p>
<p> Kişisel bilgilerinizi başkalarının kişisel bilgilerinizi görüntüleyememesi veya kaydetmemesi için genel veya paylaşımlı bir bilgisayara Hizmete girerken özellikle dikkatli olmalısınız. Web sitesi, uzantı ve tüm içeriği, işlevleri ve özellikleri (ancak bunlarla sınırlı olmamak üzere, tüm bilgiler, uzantı, metin, resim, resim, resim ve imleçler ve ayrıca bunların tasarımı, seçimi ve yerleşimi dahil) "Cursor Style", lisans verenleri veya bu tür materyallerin diğer tedarikçilerine, telif hakkı, ticari marka, patent, ticari sır ve diğer fikri mülkiyet yasaları veya mülkiyet hakları tarafından korunmaktadır. </p>
<p> Bu Kullanım Şartları, Web Sitelerini yalnızca kişisel, ticari olmayan kullanımınız için kullanmanıza izin verir. Aşağıdaki durumlar dışında, Web Sitemizdeki herhangi bir materyali çoğaltmamalı, dağıtmamalı, değiştirmemeli, türev çalışmalar oluşturmamalı, yeniden yayınlamamalı, indirmemeli, saklamamalı veya iletmemelisiniz: Kişisel ihtiyaçlarınız için kullanabilirsiniz, makul miktarda bir kopyasını yazdırabilir veya indirebilirsiniz. Web Sitesi ve Uzantı sayfaları veya kişisel, ticari olmayan kullanım için ve daha fazla çoğaltma, yayınlama veya dağıtım için değildir. </p>
<p> Bu siteden veya uzantıdan ve içeriklerinden herhangi bir materyalin kopyalarını değiştirmemelisiniz. Bu sitenin ve uzantının kopyalarından herhangi bir telif hakkını, ticari markayı veya diğer tescilli bildirimleri silin veya değiştirin. Web Sitelerinin veya uzantıların herhangi bir bölümüne veya Web Sitesi veya Uzantı aracılığıyla kullanılabilen herhangi bir hizmet veya materyale ticari herhangi bir amaçla erişmemeli veya kullanmamalısınız. </p>
<p> Web Sitelerindeki veya Uzantılardaki bu bölümde listelenenler dışında herhangi bir materyali kullanmak istiyorsanız, Chrome Web Mağazasının destek sayfasında bir talep gönderin. </p>
<p> Kullanım Şartlarını ihlal ederek Web Sitesinin veya Uzantının herhangi bir bölümünü yazdırır, kopyalar, değiştirir, indirir veya başka bir kişiye erişim sağlar veya bu Kullanım Şartlarını ihlal ederse, Web Sitesini ve Uzantıyı kullanma hakkınız derhal sona erer ve takdirimize bağlı olarak aldığınız materyallerin herhangi bir kopyasını iade etmeli veya imha etmelisiniz. Uzantının web sitesinin bu Kullanım Şartlarında açıkça izin verilmediği şekilde herhangi bir kullanımı, bu Kullanım Şartlarını ihlal eder ve telif haklarını, ticari markaları ve diğer yasaları ihlal edebilir. </p>
<p> "Cursor Style" adı, "Cursor Style" logosu ve tüm ilgili adlar, logolar, resimler, imleçler ve hizmet adları, tasarımları ve sloganları, "Cursor Style" veya bağlı kuruluşlarının veya lisans verenlerinin ticari markalarıdır. Bu tür işaretleri Hizmetin önceden yazılı izni olmadan kullanmamalısınız. Bu web sitesindeki ve uzantıdaki diğer tüm adlar, logolar, ürün ve hizmet adları, tasarımlar ve sloganlar, ilgili sahiplerinin ticari markalarıdır. Hizmeti yalnızca yasal amaçlarla ve bu Kullanım Şartlarına uygun olarak kullanabilirsiniz. </p>
<h3> Hizmeti ŞUNLARI YAPMAMAYA kabul ediyorsunuz: </h3>
<ul>
<li> Herhangi bir geçerli federal, bölgesel, yerel veya uluslararası yasayı veya düzenlemeyi (Rusya ve diğer ülkelere veri veya yazılım ihracatıyla ilgili herhangi bir yasa dahil ancak bunlarla sınırlı olmamak üzere) ihlal edecek herhangi bir şekilde. </li>
<li> Küçüklere istismar, zarar verme veya onlara zarar verme girişiminde bulunmak, onları uygunsuz içeriğe maruz bırakmak, onları tanımlayan bilgi talep etmek veya başka bir şekilde. </li>
<li> Bu Kullanım Şartlarına uymayan herhangi bir materyali göndermek, bilerek almak, indirmek, kullanmak veya yeniden kullanmak. </li>
<li> Önceden yazılı iznimiz olmadan herhangi bir reklam veya tanıtım materyalinin, herhangi bir "istenmeyen mektuplar", "zincir mektuplar" veya "spam" veya diğer benzer tekliflerin gönderilmesini veya satın alınmasını iletmek. </li>
<li> Bir "Cursor Style" veya bir çalışanı, başka bir kullanıcıyı veya başka herhangi bir kişiyi veya kuruluşu (yukarıdakilerden herhangi biriyle ilgili e-posta adresleri veya takma adlar kullanmak dahil ancak bunlarla sınırlı olmamak üzere) taklit etmek veya taklit etmeye çalışmak için. </ li >
<li> Hizmetin veya herhangi birinin kullanımını sınırlayan veya engelleyen veya bizim belirlediğimiz Hizmete veya Hizmetin kullanıcılarına zarar verebilecek veya onları sorumlu tutabilecek diğer eylemlere katılım. </li> </ul>
<h3> Ek olarak, ŞUNLARI YAPMAMAYA kabul ediyorsunuz: </h3>
<ul>
<li> Sitenin işleyişini devre dışı bırakabilecek, aşırı yükleyebilecek, hasar verebilecek veya bozabilecek, Hizmetin herhangi bir tarafça kullanımını engelleyebilecek veya engelleyebilecek herhangi bir şekilde Hizmeti kullanmak, gerçek zamanlı eylemlere Hizmet aracılığıyla katılma yetenekleri dahil. </li>
<li> Hizmetteki herhangi bir materyali izlemek veya kopyalamak dahil olmak üzere herhangi bir amaçla Hizmete erişmek için herhangi bir otomasyon aracı, işlem veya araç kullanmak. </li>
<li> Önceden yazılı iznimiz olmadan, Hizmetteki herhangi bir materyali izlemek veya kopyalamak veya başka herhangi bir yetkisiz amaç için herhangi bir manuel işlem kullanmak. </li>
<li> Hizmetin normal işleyişine müdahale eden herhangi bir cihaz, yazılım veya prosedür kullanmak. </li>
<li> Herhangi bir virüs, Truva atı, solucan, mantık bombası veya diğer zararlı veya teknolojik olarak zararlı materyalleri sunmak. </li>
<li> Hizmetin, Hizmetin depolandığı sunucunun veya Hizmete bağlı herhangi bir sunucu, bilgisayar veya veritabanının herhangi bir bölümüne yetkisiz erişim elde etmeye, müdahale etmeye, zarar vermeye veya bunlara zarar vermeye çalışmak. </li>
<li> Bir hizmet reddi saldırısı veya dağıtılmış bir hizmet reddi saldırısı kullanarak bir Hizmete saldırmak. </li> </ul>
<p> Hizmet üzerinden veya aracılığıyla sağlanan bilgiler yalnızca genel bilgilendirme amaçlıdır. Bu bilgilerin doğruluğunu, eksiksizliğini veya kullanışlılığını garanti etmiyoruz. Bu tür bilgilere yalnızca kendi sorumluluğunuzda güveniyorsunuz. Bu materyallerden, Sizin herhangi bir Hizmet ziyaretçisinin veya herhangi bir içeriğinden haberdar olabilecek herhangi birinin veya başka birinin herhangi birinin herhangi bir bağımlılığından kaynaklanan tüm sorumluluk ve yükümlülükleri reddediyoruz. </p>
<p> Bu Hizmet, diğer kullanıcılar ve üçüncü taraf lisans verenler, sendikacılar, toplayıcılar ve / veya raporlama hizmetleri tarafından sağlanan materyaller dahil olmak üzere üçüncü taraflarca sağlanan içeriği içerir. Bu materyallerde ifade edilen tüm ifadeler ve / veya görüşler ve ayrıca Hizmet tarafından sağlanan içerik hariç olmak üzere, bu materyalleri sağlayan kişinin veya kuruluşun görüşleri ve sorumluluklarıdır. Bu materyaller, Hizmetin görüşlerini mutlaka yansıtmaz. Üçüncü şahıslar tarafından sağlanan herhangi bir materyalin içeriğinden veya doğruluğundan size veya herhangi bir üçüncü tarafa karşı sorumlu değiliz. </p>
<p> Hizmetin içeriğini zaman zaman güncelleyebiliriz, ancak içeriği mutlaka eksiksiz veya güncel değildir. Hizmetteki herhangi bir materyal herhangi bir zamanda güncel olmayabilir ve bu tür materyali güncellemek zorunda değiliz. Web Sitesindeki ve Uzantıdaki bilgileri ve içeriği kendi kararımıza göre güncelleyebilir, değiştirebilir, değiştirebiliriz. </p>
<p> Bu Hizmet üzerinde topladığımız tüm bilgiler, Gizlilik Politikamıza tabidir. Hizmeti kullanarak, bilgilerinizle ilgili olarak tarafımızca yapılan tüm eylemleri <a href="/privacy"> Gizlilik Politikasına </a> uygun olarak kabul edersiniz. </p>
<p> Ek şartlar da Hizmetin belirli bölümleri, hizmetleri veya özellikleri için geçerli olabilir. Bu tür tüm ek hüküm ve koşullar işbu belge ile referans yoluyla bu Kullanım Şartlarına dahil edilmiştir.
Web sitemize veya uzantımıza, bunu dürüst ve yasal bir şekilde yapmanız ve itibarımıza zarar vermemeniz veya kullanmamanız ve bizim yazılı iznimiz olmadan tarafımızdan herhangi bir ilişki, onay veya onay biçimi sunacak şekilde bağlantıyı ayarlamamanız koşuluyla bağlantı verebilirsiniz. </p>
<p> Hizmet, üçüncü taraflarca sağlanan diğer sitelere ve kaynaklara bağlantılar içerir, bu bağlantılar yalnızca size kolaylık sağlamak için sağlanır. Bu, banner reklamlar ve sponsorlu bağlantılar dahil olmak üzere reklamlarda bulunan bağlantıları içerir. Bu sitelerin veya kaynakların içeriğini kontrol etmiyoruz ve bunlardan veya kullanımından kaynaklanabilecek herhangi bir kayıp veya hasardan sorumlu değiliz. Bu Hizmetle ilgili herhangi bir üçüncü taraf web sitesine erişmeye karar verirseniz, bunu kendi sorumluluğunuzda ve bu tür web sitelerinin kullanım şartlarına uygun olarak yaparsınız. Önceden haber vermeksizin bağlantı iznini iptal etme hakkını saklı tutarız. </p>
<p> İnternet üzerinden veya Web Sitelerinde indirilmek üzere sunulan dosyaların virüs veya diğer kötü amaçlı kodlar içermeyeceğini veya içermeyeceğini garanti edemeyeceğimizi ve garanti edemeyeceğimizi anlıyorsunuz. Anti-virüs koruması ve veri girişi ve çıkışının doğruluğu ile ilgili özel gereksinimlerinizi karşılamak için yeterli prosedürlerin ve kontrol noktalarının uygulanmasından ve herhangi bir kayıp veriyi kurtarmak için sitemize harici araçları korumaktan siz sorumlusunuz. HİZMET ARACILIĞI İLE ELDE EDİLEN VİRÜSLER VEYA DİĞER TEKNOLOJİ-KÖTÜ AMAÇLI YAZILIM, VEYA BUNUN ÜZERİNE VEYA BU WEB SİTELERİNE İLİŞKİNİ KAYNAKLI KESİŞMİŞ VEYA VERİLERİN DAĞITILMASI, BİLGİSAYAR EKİPMANINIZA, BİLGİSAYAR YAKINLARINA, BİLGİSAYAR YAZILIMLARINA, VERİLERİNİZE ZARAR VEREBİLECEĞİNİ VEYA ZARAR VEREBİLİRSİNİZ. </p>
<p> HİZMETİ, İÇERİKLERİNİ VE HİZMETLER ARACILIĞIYLA ELDE EDİLEN HERHANGİ BİR HİZMETİ VEYA ÖĞEYİ KENDİ RİSKİNİZLE KULLANIRSINIZ. HİZMET, İÇERİKLERİ VE WEB SİTESİ VE UZANTISI ARACILIĞIYLA ELDE EDİLEN HERHANGİ BİR HİZMET VEYA ÖĞELER, HİÇBİR GARANTİ OLMADAN “OLDUĞU GİBİ” VE “MEVCUT OLDUĞU GİBİ” ŞARTLARINDA SAĞLANMAKTADIR. HİZMETLE İLGİLİ HERHANGİ BİR KİŞİ, HİZMETİN EKSİKSİZLİĞİ, GÜVENLİĞİ, GÜVENİLİRLİĞİ, KALİTESİ, DOĞRULUĞU VEYA ERİŞİLEBİLİRLİĞİ İLE İLGİLİ HİÇBİR GARANTİ VEYA BEYAN SAĞLAMAZ. YUKARIDAKİ SINIRLAMA OLMAKSIZIN, HİÇBİR “CURSOR STYLE” NE DE “CURSOR STYLE” İLGİLİ TEMSİLCİLER SİTENİN, UZANTININ, İÇERİĞİNİN VEYA HERHANGİ BİR ONARIMIN, ÖNCEDEN MEVCUT OLMASINI, HERHANGİ BİR UZANTIMIZ, SİTEMİZ VEYA VİRÜSLER VEYA DİĞER ZARARLI BİLEŞENLER OLMADAN OLMASINI VEYA BU WEB SİTESİNİ VEYA HERHANGİ BİR HİZMETİ VEYA YER ELDE EDİLEN, TERCİH EDİLEN. 
<p> HİÇBİR KOŞULDA, HİZMET, BAĞLI KURULUŞLARI VEYA LİSANSA SAHİPLERİ, HİZMETLER, ÇALIŞANLARI, ACENTELERİ, YETKİLİLERİ VEYA YÖNETMENLERİ, HİZMETE KARŞI HERHANGİ BİR YÜKÜMLÜLÜĞE VEYA MÜKELLEFİYETE HİZMETTE HERHANGİ BİR ZARARDAN SORUMLU TUTULMAYACAKTIR. VEYA BU VEYA DİĞER WEB SİTELERİ VEYA HİÇBİR HİZMETTE VEYA HİZMETTE ELDE EDİLEN ÖĞELER, KİŞİSEL YARALANMA, DUYGUSAL BOZUKLUKLAR, ZARARLAR VEYA BEKLENEN TASARRUFLAR, KULLANIM KAYBI, VERİ VEYA DİĞER KOŞULLAR DAHİL OLMAK ÜZERE DOĞRUDAN, ÖZEL VEYA DOLAYLI ZARARLAR DAHİLDİR. TANIM, DOLANDIRICILIK İÇEREBİLECEK YÜRÜRLÜKTEKİ YASAYA UYGUN OLARAK HARİÇ TUTULAMAYACAK VEYA SINIRLANDIRILAMAYACAK HERHANGİ BİR SORUMLULUĞU ETKİLEMEZ. </p>
<p> “Cursor Style”, bağlı kuruluşlarını, lisans verenlerini ve hizmet sağlayıcılarını ve yanı sıra ve ilgili memurlarını, yöneticilerini, çalışanlarını, yüklenicilerini, acentelerini, lisans verenlerini, tedarikçilerini, atamalarını korumayı, tazmin etmeyi ve temizlemeyi kabul ediyorsunuz. bu Kullanım Şartlarını ihlal etmenizden veya Hizmeti kullanmanızdan kaynaklanan veya bununla bağlantılı olarak ortaya çıkan her türlü iddia ve yükümlülük, mahkeme kararı, maliyet, masraf veya komisyon (avukatlık ücretleri dahil) tarafından, içerik, hizmet ve ürünlerin Kullanım Şartlarında açıkça belirtilenler dışında, Web Sitesi veya Uzantıların kullanımı veya Hizmetten alınan herhangi bir bilginin kullanılması dahil olmak üzere. </p>
<p> Bu Kullanım Şartlarının herhangi bir hükmünün, herhangi bir nedenden dolayı bir mahkeme veya yetkili yargı organı tarafından geçersiz, yasa dışı veya uygulanamaz bulunması durumunda, bu tür bir hüküm, Kullanım Şartlarının geri kalan hükümlerinin tamamını sağlamak için en aza indirgenmeli veya sınırlandırılmalıdır. Kullanım Şartları, Gizlilik Politikamız ve etkinlikleri kaydetme koşulları, Hizmet ile ilgili olarak siz ve "Cursor Style" arasındaki tek ve eksiksiz anlaşmayı oluşturur ve Hizmet ile ilgili tüm önceki ve eşzamanlı anlaşmaların, anlaşmaların, beyanların ve garantilerin, hem yazılı hem de sözlü hallerinin yerini alır. </p>
<p> Hizmetle ilgili tüm incelemeler, yorumlar, teknik destek talepleri ve diğer mesajlar, Chrome Web Mağazasındaki "Cursor Style" destek sayfasına yönlendirilmelidir. </p> ',
];
