<?php

return [
    'halo_descr' => 'A Halo a Bungie által létrehozott harci fantasy médiatörténet. Az eredeti trilógián alapuló, első személyű lövöldözős video játékok. A cselekmény Master Chief, a Spartan fedőnevű szuperkatonák egy csoportjának egyik tagja, valamint társa, az Cortana mesterséges intelligencia életében zajló események körül forog. A játékok sikere a franchise kiterjesztéséhez vezetett más médiákba: a Halo univerzum jelenleg számos könyvet, képregényt, rövidfilmet, animációt és mozifilmet ölel fel.',
    'halo_short_descr' => 'Érintsd meg az artefaktum kurzort, talán te vagy a kiválasztott.',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'A LOL Surprise babák beleszerettek a gyerekekbe, és megnyerték a szívüket az első perctől kezdve. És ez nem meglepő, mert az ilyen siker egy rejtélyre, a csoda, a kellemes meglepetés várására épül, ami nemcsak a gyerekeket, hanem a szüleiket is elragadtatja. Az ajándék titka csak a végső kicsomagolás után válik láthatóvá a gyermek számára. Mindenesetre, a LOL babák vonzó designnal, intrikával, nagyszámú csodálatos és realisztikus kiegészítővel és kellemes apróságokkal, valamint a játékok legmagasabb minőségével és részletességével rendelkeznek.',
    'lol_surprise_short_descr' => 'Király kis csajok a gyönyörű meglepetések kedvelőinek.',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'A sorozat egy versenyről szól, amelyben 456 játékos, mindannyian mély adósságban, életüket kockáztatják egy sor halálos gyermekjátékkal, hogy megnyerjék a milliárdos nyereményt. Odabent csábító díj vár halálos tétellel. A sorozat címe egy hasonló nevű koreai gyermekjátéktól származik. Hwang az ötletet a saját korai életében tapasztalt gazdasági nehézségei, valamint a Dél-Koreában és a kapitalizmusban tapasztalható osztálykülönbségek alapján fogalmazta meg.',
    'squid_game_short_descr' => 'Válaszd a megfelelő játékos arcát, amikor mindent felteszel',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter egy sorozat főszereplője, amelyet a brit író, JK Rowling írt. Tizenegyedik születésnapján Harry megtudja, hogy varázsló, és a Roxfort Boszorkány- és Varázslóképző Szakiskolába szánják, ahol varázslást gyakorol Albus Dumbledore igazgató és más iskolai professzorok irányításával. Harry azt is felfedezi, hogy már ismert a regény varázsló közösségében, és sorsa Voldemorttal, egy veszélyes sötét mágus sorsával kapcsolódik össze.',
    'harry_potter_short_descr' => 'Mit fogsz tenni a Harry Potter kurzorok gyűjteményének varázspálcájával?',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'A Marvel Comics egy képregénykiadó, amely olyan figyelemre méltó szuperhősöket hozott létre, mint Pókember, Vasember, Amerika Kapitány, Hulk, Thor, a Bosszúállók, a Galaxis Őrzői, az X-Men, a Fantasztikus Négyes és Deadpool. A Marvel legismertebb gonosztevői közé tartozik a Zöld Manó, Vörös Koponya, Loki, Thanos, Ultron, Doctor Doom és Magneto. A Marvel Comics és a DC Comics több crossover projekten is együttműködött, és közösen alapították a szándékosan rövid életű Amalgam Comics kiadót.',
    'marvel_comics_short_descr' => 'A szuperhős mindannyiunkban ott lakozik - válaszd ki a tiédet',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Üdvözöllek újra a Cookie Királyságban a Devsisters Cookie Run: Kingdomjában, az imádnivaló stratégiai RPG-ben, amelyet a Cookie Run univerzumában játszanak. Most, hogy a GingerBrave megszökött a gonosz boszorkány sütőjéből, ideje, hogy csapatot toborozzon a Süteményekből, és egy küldetésre induljon, hogy újjáépítse a bukott Sütemény Királyságot. Fedezd fel az igazságot a Királyság bukása mögött, és állíts össze egy csapatot a Királyság legerősebb Süteményeiből, hogy legyőzd a sötét erőket, amelyek meg akarják akadályozni GingerBrave-et abban, hogy beteljesítse a sorsát.',
    'cookie_run_kingdom_short_descr' => 'Kis harcosok egyenesen a sütőből',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'A Genshin Impact egy nyitott világú kalandjáték. Ez azt jelenti, hogy egy új, gyönyörű táj vár rád a folyó vagy a hegy túloldalán, csak okosan kell használnod az energiádat. Ha egy kóbor tündérre vagy egy furcsa mechanizmusra bukkansz, merj próbálkozni és megfejteni a titkukat. De hogy mit ígérnek - bajt vagy kellemes meglepetést - csak te fedezheted fel! Teyvat hatalmas kontinensén hét királyságot fogsz meglátogatni, társakat találsz különböző képességekkel, és hatalmas ellenségekkel küzdesz egy eltűnt szeretted keresésében.',
    'genshin_impact_short_descr' => 'Légy a Hét Királyság Elementáris Mestere',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Amikor egy ősi prófécia valóra válik, és a királyság a tél ölelésébe zuhan, három rettenthetetlen hős - Anna hercegnő, a bátor Kristoff és hűséges rénszarvasa, Sven - a hegyekbe indulnak, hogy megtalálják Anna húgát, Elzát, aki eltávolíthatja a dermesztő varázslatot az országból. Útközben sok nehéz meglepetés és izgalmas kaland vár rájuk. Találkozás misztikus trollokkal, találkozás egy Olaf nevű bájos hóemberrel, az Everestnél meredekebb hegycsúcsok és rengeteg varázslat. A hősöknek ellen kell állniuk a hatalmas elemeknek, hogy megmentsék a királyságot és azokat, akik drágák nekik.',
    'frozen_short_descr' => 'A Jégvarázs kurzorok gyűjteményével könnyű a jeget megtörni',
    'frozen' => 'Jégvarázs',
    'stranger_things_descr' => 'Több mint hat hónap telt el a harmadik évad fináléja óta. Joyce, Will, Eleven és Jonathan Kaliforniába költöztek, ahol a lányt az iskolában bántják. A többiek egy új szörnyeteggel kezdenek harcolni egy párhuzamos világból, ami Hawkins-ban jelent meg. Vecnának nevezték el a Dungeons & Dragons társasjáték karakter után. Pszichológiailag hat a tinédzserekre, majd mentálisan belemászik a fejükbe és megöli őket. Párhuzamosan Joyce és Murray megtudják, hogy Jim Gopper életben van, és utána mennek a szovjet börtönbe Kamcsatkában. Elevennek pedig vissza kell térnie és növelnie a képességeit, de meg kell tanulnia a fontos szerepét is a szörnyeteg megteremtésében Gokins-ban.

A forgatókönyvírók nem változtattak a cselekménytaktikán, ami az utóbbi néhány évadban tetszett nekik. A negyedik évadban a nagyszámú főszereplőt csoportokra osztották, nehéz feladatokat találtak ki nekik, a végén pedig lenyűgöző befejezésben építették össze történeteiket. Javasoljuk, hogy a Stranger Things kurzorok gyűjteményével részletesen értsék meg ezeket a kalandokat.',
    'stranger_things_short_descr' => 'Mi fog történni legközelebb? - Stranger Things 4 kurzorok',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'A Bed Wars egy eredeti mód, ami először a Minecraftban jelent meg. A játékosok feladata a felhasználó bázisának és ágyának védelme volt.

A Roblox minden nap izgalmasabb játékokat hoz, és a BedWars sem kivétel. A lényeg, hogy ha szereted a Bed Warst és megvédenéd magad a szobádban, akkor ez a cím neked való, mert visszavisz a gyerekkorba, bár ezúttal digitálisan.

Csak annyit kell tenned, hogy megvédd az ágyadat a támadóktól a partnereddel. Belépsz egy váróterembe, kiválasztod, kivel játszol, és kész, már csak a védelem kérdése.

Természetesen a védekezés során lesznek problémáid, és vannak bizonyos erőforrások, tárgyak és elemek, amelyek segítenek a győzelemben. Például exkluzív skinek, amelyeket a Bed Wars kurzorgyűjteményben találsz.',
    'roblox_bed_wars_short_descr' => 'Védje meg ágyát Roblox Bed Wars kurzorokkal',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'Naruto Uzumaki születésnapján egy legendás démon, a Kilencfarkú Róka megtámadott egy Konoha nevű falut. A Negyedik Hokage életének árán megmentette a falut, a démont a nemrég született Narutóba zárva, akit akaratlanul is gyűlöletre ítélt a falubeliek részéről.
A ninjutsu sok területén mutatott tehetségtelensége, nyugtalansága és nagyképűsége ellenére Narutónak álma, hogy Hokage, a falu legerősebb nindzsája legyen. A kiérdemlésre vágyva, amit nem kapott meg, keményen dolgozik és edz a csapattársaival, Sasuke Uchiha-val és Sakura Harunóval, valamint mentorával, Kakashi Hatakéval. Ők és társai sokat kelljenek át a dédelgetett álmaik felé vezető úton: csatákat, szerelmet, barátságot, árulást, a hatalom szomját. A Naruto anime kurzorok gyűjteménye segít eligazodni a saját utadon!',
    'naruto_anime_short_descr' => 'Járja a nindzsa útját Naruto anime kurzorokkal',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'Az akció a Taisho-korszakban játszódik. Ősi idők óta olyan pletykák keringenek, hogy humanoid démonok élnek az erdőben, akik emberekkel táplálkoznak, és éjszaka járnak, új áldozatot keresve. De... ez csak egy legenda, nem igaz?

Tanjiro Kamado a család legidősebb fia, aki elvesztette apját, és gondoskodott a családjáról. Egy nap elmegy egy közeli városba, hogy szenet adjon el. Reggel visszatérve a srác egy szörnyű képet fedez fel maga előtt: minden rokonát brutálisan meggyilkolták, és az egyetlen túlélő Nezuko, egy fiatalabb testvér, aki démonná változott, de még nem veszítette el minden emberségét.

Ettől a pillanattól kezdve Tanjiro és Nezuko egy hosszú és veszélyes utazásba kezdenek, amelyben a fiú szándékozik megtalálni a gyilkost, és megtalálni a módját, hogy meggyógyítsa a húgát. De vajon a gyerekek képesek legyőzni az összes nehézséget, és hazatérni? Már tudod a választ, és ha nem - inkább állítsd be a Demon Slayer kurzorait, a legnépszerűbb mangák egyikének karaktereivel.',
    'demon_slayer_anime_short_descr' => 'Demon Slayer kurzorok - az igazi éjszakai vadászoknak',
    'demon_slayer_anime' => 'Demon Slayer anime',
    'bts_descr' => 'A BTS a BigHit Music kiadó alatt működő hét tagú fiúcsapat. 2013. június 13-án debütáltak a "No More Dream" kislemezzel. Japánban 2014. december 24-én debütáltak a Wake Up stúdióalbummal.

A csapat neve a koreai Bangtan Sonyeondan kifejezésből ered, ami "golyóálló cserkészeket" jelent. J Hope szerint a név azt jelzi, hogy a zenekar el akarja blokkolni a tinédzserekre irányuló sztereotípiákat, kritikákat és elvárásokat, mint a golyók.

Az együttesnek szentelt kurzorok gyűjteménye a csoport összes tagját tartalmazza, itt van Kim Nam Joon kurzor (a.k.a. RM), Kim Seok Jin kurzor (Jin), Min Yoongi kurzor (Suga), Jung Ho Suk kurzor (J-Hope), Park Ji Min kurzor (Jimin), Kim Tae Hyun kurzor (V) és Jeon Jungkook kurzor (Jungkook).',
    'bts_short_descr' => 'Találkozz az idoljaiddal a BTS kurzorokkal',
    'bts' => 'BTS',
    'miraculous_descr' => 'A Miraculous: A Napsugár és a Fekete Macska történetei, melyek Miraculous – Napsugár és Fekete Macska néven ismertebbek, egy rajzfilmsorozat szuperhőseinek kalandjai két osztálytársról, akik maszkok alatt Párizs védelmezőinek szerepét játsszák egy gonosztevővel szemben, aki minden epizódban új módot talál a város ártására. A Miraculous Franciaországban készült CGI-vel és animációval. A Miraculous nemcsak egy animációs sorozat, hanem egy képregénygyűjtemény is, amelyet világszerte kiadtak. A sorozatot a fiatal közönség nagyon szereti.

A cselekmény Párizsban játszódik, ahol Marinette és Adrian középiskolások egy modern iskolában. Megkapták azt a szerepet, hogy a gonosz elleni harcban kiválasztottak legyenek, megmentve szülővárosukat. Céljuk, hogy megvédjék az embereket a gonosztól. Ezek a pillangók formájában megjelenő kis lények képesek egy embert megszállni, és gonosztevővé változtatni.

Marinette pillangóvá, Adrian pedig Fekete Macskává tud átváltozni, de meglepő módon, párosban dolgozva sem ismerik fel egymást a szuperhősök maszkja alatt.

Segíts a Fekete Macskának és a Napsugárnak megmenteni Párizst kedvenc karaktereiddel ellátott kurzorainkkal. Melyik karaktert választod kurzornak? Napsugár kurzor lesz, vagy talán Tikki imádnivaló kis Napsugár- vagy Fekete Macska kurzora? Vagy talán egy Queen Bee Rena Rouge kurzorokkal? A választás a tiéd!',
    'miraculous_short_descr' => 'Csatlakozz a szuperhősök soraihoz a Lady Bug és a Macska Noir kurzorok gyűjteményével',
    'miraculous' => 'Miraculous – A kisasszony és a fekete macska kalandjai',
    'talking_tom_descr' => 'A sorozat a Beszélő Tom és barátai mindennapjait követi. Tom és a stréber üzlettársa, Ben, folyamatosan mobilalkalmazásokat és egyéb találmányokat fejleszt a hírnév és a gazdagság elérése érdekében, megpróbálva megmutatni magukat a világnak, de ez mindig visszaüt. Tom barátnője, Angela énekesnő akar lenni, bármit is tesz ennek érdekében. Tom szomszédja, Ginger nagyon gyakran ugrik át ide huncutságokkal a tarsolyában. A hülye legjobb barát és lakótárs, Hank otthon ragad, NAGYON TV-t néz. És a volt disszidens popsztár, Becca Sparkles Angela új lakótársa lett, és úgy tűnik, beleszeretett Hankbe. Mindazonáltal, bármennyire is rosszak a dolgok minden formában és méretben, legyen az a gonosz vezérigazgató, Tom rejtélyes új szomszédja, vagy csak egy baleset Ben új kreációjában, a banda bármi történjék szórakozik, és mindig emlékezni fognak egy dologra, ami összetartja őket: a barátság sosem ér véget, ahogy a sorozat karaktereinek szeretete sem, így most beállíthatod magadnak a Beszélő Tom kurzort vagy a Ben kurzort, vagy esetleg az Angela kurzort, Oliver kurzort!',
    'talking_tom_short_descr' => 'Beszéljünk a kedvenc karakteredről a Talking Tom Cursor Collection-ben',
    'talking_tom' => 'Talking Tom and Friends',
    'lego_descr' => 'A LEGO Csoport vállalat 1932-ben alakult, és akkoriban csak 7 emberből állt. A Lego csapat célja olyan játékok létrehozása volt, amelyek fejlesztik a gyermekek kreativitását, képzelőerejét és leleményességét. Elképesztő tény, hogy 1949-es indulása óta a LEGO elemek minden változatukban kompatibilisek maradtak egymással. Minden később létrehozott elem még mindig kompatibilis a ma kiadott elemekkel, a tervezés és a forma változásai ellenére.

A LEGO tégla egy alap, amely egy üreges műanyag blokk, amely más hasonló téglákhoz kapcsolódik. De a Lego készletek más alkatrészeket, kerekeket, figurákat, platformokat és még elektronikus áramköröket is tartalmaznak érzékelőkkel és elektromos motorokkal. Autók, repülőgépek, vonatok, hajók, épületek, robotok modelljeit gyűjtheted. A LEGO a modularitás gondolatát követi, ami világosan megmutatja a gyermekeknek, hogyan oldhatnak meg bizonyos problémákat, hogyan fejleszthetik a képzelőerejüket, a kéz finom motorikus készségeit és az összeszerelési készségeket. A LEGO téglákat hihetetlenül precízen készítik, és tökéletesen illeszkednek egymáshoz, lenyűgöző 10 mikronos pontossággal.

Nemrégiben sok népszerű 3D-s animált Lego történet készült, ahol a készletek karaktereik életre kelnek, és hihetetlen kalandok résztvevőivé válnak. Ha egy menő kurzort szeretnél, akkor a Lego TV-sorozatok és animációs filmek számos karakterét megtalálhatod a Lego Kurzorkollekciónkban. Lego Ninjago Kurzor, Lego Batman Kurzor, Lego Ninjago Kurzor, Lego Wyldstyle Kurzor és még sok más.',
    'lego_short_descr' => 'Építsd meg álmaid böngészőjét a Lego kurzorok gyűjteményével',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'A sikeres Kickstarter-finanszírozás után, 2017-ben a Team Cherry kiadta a multiplatform PC-s játékot, a Hollow Knightot. Ez egy névtelen lovag története, és a Hallownest rovarbirodalomban tett felfedezései. A játékot joggal ismerték el a metroidvania műfaj egyik legjobbjaként.

A Hollow Knight játékmenete a játékvilág felfedezésén alapul. Akadályok leküzdése, rejtvények megoldása és titkok felfedezése, valamint ellenségekkel való küzdelem. A játékos egyedi fejlesztésekkel és trükkökkel rendelkezik a világ felfedezéséhez és a csatákban való küzdelemhez. Zónáról zónára haladva a játékos legyőzi a főnököket, és megkapja a szükséges fejlesztéseket a további előrehaladáshoz. Ennek eredményeként a játékosoknak vissza kell térniük a már korábban átlépett területekre, hogy titkokat találjanak és végigvigyék a történetet. És ez izgalmas is, mivel a zónák minden alkalommal változnak, új meglepetéseket és élményeket hozva. A játék többféleképpen játszható, mert a zónák között több különböző út létezik. A történeten keresztül haladva megnyitod a zónatérképet, de először meg kell szerezni a térképet.

Hős fő fegyvere a köröm, ami némileg hasonlít egy kardhoz, a fegyverek kovácsműhelyen fejleszthetők, valamint különböző fegyverhasználati képességek is megtanulhatók, ami kibővíti a támadások változatosságát. Az ellenségek megtámadásával egy speciális erőforrást halmozol, amelyet később fejlesztésekre vagy gyógyításra lehet felhasználni.
Jó szórakozást a Hollow Knighttal, és ne felejtsd el a Hollow Knight kurzorainkat a kedvenc karaktereddel. Kollekciónk tartalmazza a Mister Mushroom kurzort, a Quirrel kurzort, a Hornet Needle kurzort, az Old Nail kurzort, a Myla kurzort és másokat.',
    'hollow-knight_short_descr' => 'Próbáld meg nem elveszni a rovarok birodalmában a Hollow Knight kurzor-kollekció használatával.',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman a sorozat főszereplője. A korábban névtelen Stikmin, kisebb tolvajként kezdte pályafutását, azzal a vággyal, hogy gyorsan könnyű pénzhez jusson. A West Mesa börtönből való megszökése után azonban sok változás következik be az életében, és híres bűnözővé válik, miután ellopja a tunéziai gyémántot. Henrynek választania kell - sikeres kormányügynökké, fejvadásszá, bűnszervezet vezetőjévé, cyborggá válni, vagy a bűnözői utat egyedül folytatni. A játék sok kalanddal és rejtéllyel örvendezteti meg a műfaj rajongóit, és meg fogja találni a Henry Stickman kurzorok új gyűjteményét vicces karaktereivel, beleértve a Henry Stickmin kurzort, Charles Calvin kurzort, Reginald Copperbottom kurzort, Jobb kéz kurzort, Ellie Rose kurzort és másokat!',
    'henry-stickmin_short_descr' => 'Tervezd meg a menekülésedet a unalom elől a Henry Stickman Cursors kollekcióval',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'A nagyon népszerű online játék, az Adopt Me 2017-ben indult, és a Roblox játékplatform legnépszerűbbjévé vált. A játék lényege nagyon egyszerű - szerezzen tojásokat háziállatokkal, és gondoskodjon róluk.

A virtuális háziállatok 5 osztályba sorolhatók, némelyikük nagyon ritka és drága, míg másokat nagyon könnyű megszerezni. Ezek a ritka csoportok, mint például a kék kutya, a common, ritka kurzor, például az Adopt Me majom egérkurzor, valamint az ultraritkák, mint például a Koala kurzor, és a Legendás, Sárkány kurzor és az Accept me unikornis. Ha a játékosnak négy felnőtt háziállata van ugyanabból a típusból, kombinálhatók egy neon háziállattá, mint például a Neon Horse játék kurzor vagy az Adopt Me Neon Starfish. Négy normál háziállat kombinálásával készíthet egy neon háziállatot, amely igazán ragyog, a neon háziállatokból pedig egy mega-neon háziállatot is létrehozhat.

Vásárlás a játékban, az Adopt Me! a virtuális Roblox pénznemmel - az úgynevezett Robux-szal -, a játéknak pedig saját valutája van - Bucks. A háziállat gondozása a szórakozáson kívül buckokat is kereshet, csak etesse, fektesse le vagy olvasson mesét, általában sok érdekes dolgot.

Most a Roblox "Adopt Me!" játék rajongói kedvenc háziállatukkal díszíthetik a játék kurzorját!',
    'adopt-me_short_descr' => 'Érezd jól magad aranyos háziállatokkal az Adopt Me! játék kurzorok gyűjteményében',
    'adopt-me' => 'Adopt me!',
    'among-us_descr' => 'Az Among Us a híres "Mafia" szerepjátékra épül. A játékot eredetileg mobil eszközökre tervezték, mivel csak egy térképe volt. A játék gyorsan népszerűvé vált. Később a fejlesztőcsapat hozzáadott egy többjátékos módot, és 2019-ben két további térkép jelent meg.
Az Among Us egy felülről lefelé irányított, harmadik személyű játék, amely lehetővé teszi a játékos számára, hogy minden irányba mozogjon. Négy-tíz játékos játszhat egy körben. A játék elején mindenki titokban egy áruló vagy egy legénységi tag szerepét kapja. A csaló (az orosz fordításban "Áruló") elrejthet a szellőzőnyílásban, szabotálhat és megölheti a legénység tagjait. A célja az, hogy elpusztítsa az összes legénységi tagot, vagy szabotázs útján tönkretegye az űrhajót. A hajó legénységének célja, hogy megoldja a játék elején nekik készített különböző rejtvényeket. Ha a legénység minden tagja elvégzi az összes feladatot, az árulók veszítenek. A hajó legénysége győzelmet arathat az árulók szavazás során történő likvidálásával is.
Az árulók időnként szabotálhatnak, és ha a meghibásodásokat nem javítják ki 30 másodpercen belül, akkor a legénység veszít. A játék megkezdése előtt kiválaszthatod a karaktered színét, amiért játszol, kék, piros, sárga, szürke - bármi! És ne felejtsd el beállítani a megfelelő kurzort az új Among Us kollekcióból!',
    'among-us_short_descr' => 'Ne tévesszen meg a bonyolult űr játék, ezekkel az Among Us kurzorokkal.',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'A "Steven Universe" alkotója Rebecca Sugar volt. Ismert a korábbi munkájáról, a Kalandtúrák-ról. A Steven Universe első epizódja 2013 tavaszán jelent meg a YouTube videómegosztó platformon. De ősszel az amerikai Cartoon Network csatorna elkezdte sugározni a nézőinek. Azóta 6 évad jelent meg. A hatodik a befejezőnek ígérkezik.
Az animációs sorozat cselekménye a Kristály Gyöngyök csapat köré összpontosul. Idegen lényekből áll, jellegzetes nevekkel: Gyöngyök, Ametiszt és Gránát. De van egy másik résztvevő is, akinek a szerepében egy átlagos fiú, Stephen lép fel. Együtt szörnyeket keresnek és megpróbálják semlegesíteni őket, nehogy a személyes javukra elfoglalják a Földet. Jasper és Peridot ellenzik őket - a szülőbolygójuk küldöttei, akik meg akarják verni a Gyöngyöket és bekapcsolni a Klasztert.
Ha a Steven Universe rajongója vagy, és szeretnéd látni az animációs sorozat karaktereit, bárhol is légy, telepítsd a Cursor Style kiterjesztést! Miért csináld ezt? Hozzáadhatsz egy "Steven Universe"-nek szentelt gyűjteményt, és az alapértelmezett egérmutatót az egyik kedvenc karaktereddé változtathatod.',
    'steven_universe_short_descr' => 'Fedezd fel a gyémántok titkát a Steven Universe kurzorokkal',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Egy "Family Guy" nevű animációs szituációs komédia a teljes létezése során 4 alkalommal nyerte el az Emmy-díjat, és 3 alkalommal az "Annie" díjat. Az animációs sorozat az amerikai társadalom érzékeny témáit figurázza ki, mint például: a feminizmus, a rabszolgaság, az elhízás, a politika stb. Más művekkel ellentétben itt tréfás betéteket és szarkazmust használnak. Sőt, sok esetben nem a cselekménybe integrálják őket, hanem önállóan léteznek.
Egy animációs sorozat epizód elkészítése több mint 10 hónapot vesz igénybe. Miért ennyi? Mert az egész animációt kézzel rajzolják. Éppen ezért a műben feldolgozott események egy része elveszíti a relevanciáját. De ennek ellenére a szituációs komédia nagyon érdekes marad, és világszerte elnyeri a nézők tetszését. Hiszen ki nem szeret jót nevetni a politikusokon, a hírességeken vagy azokon az embereken, akik vad csínyeket követnek el, és ezáltal meglepik, vagy akár meg is döbbentik az átlagembereket.
Szereted a "Family Guy"-t? Egyedülálló lehetőséged van arra, hogy egy normál egérmutatót ennek az animációs sorozatnak bármelyik karakterévé változtasd! Mit kell tennem? Csak telepítsd a “Cursor Style” böngészőbővítményt, adj hozzá egy “Family Guy”-nak szentelt gyűjteményt, és élvezd a mesés reinkarnációt!',
    'family_guy_short_descr' => 'A Family Guy kurzorok gyűjteménye a különleges humor kedvelőinek.',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Biztosan hallottad a mondást: "A szépség megváltja a világot"? Sokan, különösen a lányok, egyetértenek ezzel az állítással. Ezért arra törekszenek, hogy a legszebb és legszemrevalóbb dolgokkal vegyék körül magukat. Lehet rózsaszín tapéta a hálószobában, puha játékok, gyöngyökkel hímzett párnák, értékes ékszerek stb. Kívülről mindez nagyon aranyosnak és egy kicsit gyerekesnek tűnik. De mindannyian egy kicsit gyerekek vagyunk a szívünkben, miért ne engednénk meg neki, hogy megmutassa a képzeletünket?
A gyengédség sok mindent kiválthat bennünk. Például egy kiscica együttérző szemei, aki szeretne simogatást vagy ételt. A színes szivárvány, amely egy tavaszi eső után kukucskál elő, és minden színben csillog a napon. A gyerek, akit megkínáltak csokoládéval, és úgy döntött, megosztja a barátnőjével vagy barátjával. Rengeteg oka van az érintettségnek, és úgy döntöttünk, hogy ezeket használjuk kurzorként.
Unod már az unalmas fehér nyilat a böngésződben? Cseréld le valami aranyosra a gyűjteményünkből! Például rózsaszín-fehér unikornisra, szomorú paradicsomra, mélázó felhőre, tüskés kaktuszra macska formájában, vagy amire csak szeretnéd. Mindössze annyit kell tenned, hogy telepíted a Cursor Style kiterjesztést, és hozzáadsz egy aranyos kurzorok gyűjteményt. És éljen a világ megmentője - a szépség!',
    'cute_cursors_short_descr' => 'A világ kedvesebb lesz az aranyos kurzorok gyűjteményével',
    'cute_cursors' => 'Aranyos kurzorok',
    'web_media_descr' => 'A modern valóságban szinte mindenki használja az internetet. A kisgyerekektől a nyugdíjasokig. Van, aki böngészőt használ, mások a YouTube-on néznek videókat, és valakinek a hálózat a szeretteivel való kapcsolattartáshoz szükséges. Ezen felhasználók egyike sem tudja elképzelni a napot a World Wide Web nélkül.
Az idősebb emberek gyakran ülnek a Facebook vagy a VK közösségi hálózaton. Gyakran kommunikálnak gyerekeikkel és unokáikkal a Skype-on. Ez különösen kényelmes, ha a gyerekek és a szülők különböző városokban vagy akár országokban élnek.
A fiatalok inkább a Viberen vagy a Telegramon kommunikálnak, Instagramra töltenek fel fotókat, a Facebook mémeken nevetnek. A reakciókat mutató YouTube videók milliók nézettségét szerzik meg, akárcsak a különféle tréfák vagy szociális kísérletek. A Tik-Tokon emberek százezrei táncolnak, mutatnak bűvészkedéseket és fejezik ki magukat.
Érdekel vagy gyakran használ valamilyen erőforrást a webes média szférájából? Meg szeretnél szabadulni az unalmas egérmutatótól a böngésződben? Akkor telepítsd a kiterjesztést, és cseréld a default kurzort a kreatívunkra! Lehet YouTube kurzor, Viber kurzor, Google Chrome kurzor, vagy más erőforrások.',
    'web_media_short_descr' => 'Élj modern ritmusban a webes média kurzorok gyűjteményével',
    'web_media' => 'Webes média',
    'bobs_burgers_descr' => 'A Bob\'s Burgers animációs sorozat az animációs munka cselekménye és a karakterek karizmája. És az Emmy-díjra való jelölés és a mű elismerése alapján a világ egyik legjobb rajzfilmjeként, a Bob\'s Snack valóban nagyot szólt.
Az animációs sorozat cselekménye a Bob Belcher család körül forog. Ez a személy az első emeleten található vendéglő tulajdonosa, a másodikon pedig a szeretteivel él. Bobnak van egy vidám felesége, Linda, és 3 gyereke: Gene, Louise és Tina. A fiú zenei karrierről álmodik, a legidősebb lány, Tina nagyon kedves, de ügyetlen, a legfiatalabb - Louise pedig még mindig egy kis ördög, és gyakran kényelmetlen helyzetbe hozza a családját. A Bob\'s Burgers fő versenytársa Jimmy Pesto\'s Pizzeria. Ahogy sejtheted, a pizzeria tulajdonosát Jimnek hívják, és ő és Bob gyűlölik egymást. Mindez úgy lett megcsinálva, hogy komikusnak tűnjön, nem komolynak. Ezért sok összetűzésük csak mosolyt vált ki.
Ha szereted a "Bob\'s Burgers" animációs sorozatot, és szeretnéd látni a karaktereit nem csak a monitor képernyőjén vagy a TV-n, telepítsd a kiterjesztést, adj hozzá egy gyűjteményt, és változtasd meg az egérmutatót a böngészőben a rajzfilm bármelyik karakterére!',
    'bobs_burgers_short_descr' => 'Bob hamburgereket készít, és mi a Bob\'s Burgers kurzorokat készítjük.',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'A "Kirby" videojáték története már a múlt század 90-es éveiben kezdődött. Számos sorozatból áll, amelyeket a Nintendo és a HAL Laboratory fejlesztett. A játék egy és fél évtől 8 éves korig tartó gyermekek számára készült. Népzerűségéről a forgalmazott példányok száma árulkodik. Több mint 34 millió világszerte.
Kirby főszereplője az azonos nevű rózsaszín lény. A Pop Star nevű bolygón él, és időről időre megvédi azt a különféle veszélyektől. Kirby belélegezhet bizonyos tárgyakat és ellenségeit, hogy aztán megtanulja képességeiket: kéz-kéz elleni harc, kard birtoklása, tűzlélegzés stb. A rózsaszín puff azonban nemcsak az ellenségekkel harcol, hanem különféle rejtvényeket is megold, más országokba utazik, és akár a szinten is repülhet.
Ezt a videojátékot Nintendo vagy Game Boy konzolokon lehet játszani. Minden sorozatban aranyos hősök, jó grafika és vicces filmzenék vannak. Mellesleg, az első verzió megjelenése óta eltelt csaknem 30 év alatt a világ 20 Kirby-sorozatot tudott megtekinteni. Ez a mutató, a forgalmazott példányok több millió példányszámával együtt segített a játéknak a játékipar 50 legsikeresebb és legkeresettebb videojátékának TOP-jába kerülni.
Szereted Kirbyt, hogy szeretnéd ezt a karaktert látni, ahol csak lehet? Akkor használd a Kirby-gyűjteményt, és változtasd a normál egérmutatót kedvenc videojátékod főszereplőjévé! Biztosak vagyunk benne, hogy tetszeni fog a kurzor új megjelenése.',
    'kirby_short_descr' => 'Próbáld meg beszippantani az egész Kirby kurzor gyűjteményt',
    'kirby' => 'Kirby',
    'undertale_descr' => 'Régi időkben a Földet nemcsak emberek, hanem szörnyek is lakták. Köztük nézeteltérések miatt háború tört ki, ami az emberi faj javára ért véget. Hét mágus a szörnyeket a föld alá kergette, és örökre bebörtönözte őket egy gátló varázsigével. Azonban csak egy bejárat volt a Mount Ebott-hoz, amivel a gyermek élt. Ő érte fogsz játszani az Undertale számítógépes játékot futtatva.
Ezt a játékot Toby Fox fejlesztette - egy jól ismert programozó az Egyesült Államokból. Először a Microsoft Windows és Linux operációs rendszert futtató személyi számítógépek tulajdonosai élvezhették, majd a játék konzolok felhasználóinak sora következett.
Milyen a játék lényege? A fiú a szörnyek által lakott alvilágban utazik. Némelyikük azonnal ellenséges, míg mások szeretnek beszélgetni. A játékos 2 viselkedés közül választhat: elkerüli az erőszakot vagy harcol. Az első esetben a játék könnyebb lesz, a másodikban - éppen ellenkezőleg, nehezebb. A cselekmény és a befejezés, amely elágazhat és változhat, szintén ettől a választástól függ.
Ha szereted az Underground Tale-t, és szeretnéd látni a karaktereit a böngésződben, telepítsd a kiterjesztést, és add hozzá a megfelelő kurzorgyűjteményt! Változtasd a unalmas egérmutatót az Undertale szörnyei vagy főszereplőjének egyikévé!',
    'undertale_short_descr' => 'Itt az ideje, hogy kijuss a lyukból az Undertale kurzorok használatával.',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'A Deltarune egy szerepjáték, amelyet a számítógépekre adtak ki pár évvel ezelőtt. Ugyanaz a programozó készítette, aki az Undertale-t fejlesztette. Azonban ez a két játék szinte nem hasonlít egymásra, bár van néhány közös karakterük és helyszínük.
A Delta Rune-ban több főszereplő is van. Ez a Chris diák, akit irányíthatunk, és egy bájos szörny, Susie, aki irányíthatatlan. Mindkét karakter a sötétség világába esik, ahol találkoznak az egyik lakójával - Ralsay-vel. Ő elmondja nekik, hogy valójában ők a fény lényei, akiknek egy küldetésük van - megállítani a sötét energia áramlását egy komor világban. Ehhez meg kell kímélniük a helyi szörnyeket, és megpróbálniuk nem harcolni velük, bár ez néha eléggé nehéz. A játékos egyszerű választás előtt áll: vagy megkíméli a sötét lényeket, vagy megtámadja őket. Mivel Susie nem a félszívűség híve, sok esetben ő a harcot választja. Ezért Chris-nek nincs más választása, mint támogatni a barátnőjét, és segíteni neki a harcokban.
Szereted a Deltarune játékot? Akkor stilizáld a webböngésződben az egérmutatót az egyik karakterére! Ezt a kiterjesztésünkkel megteheted. Telepítsd, add hozzá a “Rune Delta” kollekciót, és aktiváld! Mostantól a nyíl nem ugyanolyan, mint a többié, hanem Chris, Susie vagy a sötét világ egyik teremtménye lett.',
    'deltarune_short_descr' => 'Merülj el a sötét világban ezzel a kurzor-gyűjteménnyel',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'A Super Mario a Nintendo által kiadott számítógépes játékok sorozata. Az első és legnépszerűbb játékot Super Mario Bros.-nak hívták. 1985-ben látott napvilágot. Később bekerült a Guinness Rekordok Könyvébe. Azóta több mint 20 játék jelent meg, amelyek mindegyike a saját cselekményével rendelkezik. 2019-ben egy új verzió jelent meg Super Mario Maker 2 néven. A grafika javulása ellenére a stílus és a karakterek ugyanazok maradtak, ami nosztalgiaérzést kelt a 80-as évek Super Mario-ja iránt.
A főszereplő még mindig Mario, a szerelő. A játék utolsó variációjának cselekményében a hercegnő kastélya nem maradt kő kövön. Mario-nak újjá kell építenie, miután megszerezte az érméket, amelyeket a feladatokért fizetnek neki. Összesen ez a játék több mint 100 különböző nehézségű pályával rendelkezik a módosítás lehetőségével. A Super Mario Maker 2-ben új játékmódok is vannak. Négyet játszhatsz egyszerre, és amint az egyik befejeződik, a pálya teljesítettnek számít. Vannak még olyan módok is, mint a: Mario Maraton, Párharc és Ninjik versenyei.
Imádod a  Super Mario-t és mindent, ami ehhez a csodálatos játékhoz kapcsolódik? Akkor állítsd be a  platformer stílusában készült kurzorokat! Biztosak vagyunk benne, hogy tetszeni fog a Mario kurzor, Luigi kurzor, Princess Peach kurzor és a többi kurzor, amely a gyűjteményünkben szerepel!',
    'super_mario_short_descr' => 'Menj át a gombakirályságon a Super Mario kurzorok gyűjteményével',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'A Gravity Falls-t a Disney Television Animation Corporation és Alex Hirsch közösen hozta létre. A premier 2012-ben volt, és a Disney Channel-en mutatták be. Az animációs sorozat teljes első évada ott pörgött. Két évvel később a második évad is megjelent, amelyet a nézők az előző csatornán és a Disney XD-n is megtekinthettek. Sajnos a Gravity Falls rajongók nem várták meg a harmadik és az azt követő évadokat. Az alkotók úgy döntöttek, hogy két évadra korlátozzák magukat, mindenféle folytatás nélkül.
Ami ennek az animációs képnek a cselekményét illeti, a cselekmény egy Gravity Falls nevű kitalált városban játszódik. Két iker érkezik oda, Mabel és Dipper. A nagybátyjuknál, Stan-nél szállnak meg. Neki van egy saját turista ajándékboltja. Amikor a testvérek megunják a "semmittevést", kalandot keresnek. Az egyikük egy furcsa naplót talál az erdőben, amely a város anomáliáiról mesél. Az ikrek útnak indulnak, hogy megkeressék a szerzőjét, és szokatlan lényekkel és helyekkel találkoznak. Ha érdekli ez az animációs sorozat, és egykor a karakterei rajongója volt, ajánljuk a Gravity Falls stílusú egérmutatók gyűjteményét!',
    'gravity_falls_short_descr' => 'Indulj kalandra a Gravity Falls kurzoraival.',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Mindenki hallott már egy ilyen híres animációs sorozatról, mint a Simpson család. Még azok az emberek is tisztában vannak a sárga karakterek létezésével, akik soha nem nézték. A rajongók pedig el vannak ragadtatva, amikor a kedvenc rajzfilmjük következő évada megjelenik. Egyébként 2019 őszén 31 évad jelent meg. És az első 1989-ben jelent meg a televízió képernyőin. A Fox elkezdte sugározni, és a magas nézettség és a közönség szimpátiája miatt még mindig folytatja ezt.
A Simpson család egy szatírikus műfaj, amely releváns témákat érint. Ez lehet az átlag amerikai életstílusa, politikai és vallási kérdések, a hírességek "csillagos" trükkjei, a feminizmus, az azonos neműek házassága. Általánosságban minden, ami a helyi és globális eseményekhez kapcsolódik, amelyekben az Egyesült Államok részt vesz.
Az animációs sorozat cselekménye a nem létező Springfield városában játszódik. Valójában rengeteg város van ezzel a névvel Amerikában. Talán ezért választották ezt, hogy a közönség ne kösse össze a képernyőkön történteket egy konkrét településsel, hanem csak kitalálja, hol lehet ez.
Nagy valószínűséggel a Simpson család rajongója vagy. Egyébként miért olvasnád el ezt a szöveget a végéig? És ha igen, akkor lehetőséged van arra, hogy a megunott egérkurzorodat egy olyan mutatóra cseréld, amely ebben az animációs sorozat stílusában készült.',
    'simpsons_short_descr' => 'Egy szórakoztató kis család, a Simpson-család kurzoraival.',
    'simpsons' => 'A Simpson család',
    'youtubers_descr' => 'A YouTube videomegosztó platform 2005-ben jelent meg. Kezdetben a videókat csak önkifejezés vagy valamiről való tájékoztatás céljából tették közzé. Azonban idővel mindez jövedelmező üzletté nőtte ki magát, ami sikeres YouTube-felhasználók számára havonta több ezer, olykor több millió dollárt is hoz. Minél népszerűbb a vloger (a személy, aki a videoblogot vezeti), annál többet kereshet a csatornáján keresztül.
Mennyit keres egy ötéves vloger kislány, akinek a szülei a legérdekesebb látványosságokba viszik, és a kamerán rögzítik a történéseket? Arról van szó, hogy a gyerek hogyan szórakozik a játszótereken, milyen érzelmeket fejez ki, hogyan bolondozik, és minden ilyesmi. Az összeg tényleg elképesztő - a gyerek csatornája ma már közel 47 millió feliratkozót szerzett, és havonta 5 millió rubel bevételt kezdett generálni.
Vannak, akik videókat töltenek fel, ahol számítógépes játékokat vitatnak meg, valaki beatboxozik vagy tréfákat rendez az utcán járókelőknek. Vannak, akik érzékeny témáknak, például a férfiak és nők közötti kapcsolatnak szentelik a videóikat. Minél jobban tetszenek ezek a felvételek a YouTube-felhasználóknak, annál nagyobb a vloger népszerűsége.
A gyűjtemény már tartalmazza a PewDiePie kurzort, a Shane Dawson kurzort, a Ray William Johnson kurzort, a Zoella kurzort, a MyLifeAsEva kurzort és másokat.',
    'youtubers_short_descr' => 'A YouTubers kollekciónkban a sztárok új generációja mindig online.',
    'youtubers' => 'YouTuberek',
    'pusheen_descr' => 'Majdnem mindenki ismeri a Pusheen macskát. Annak ellenére, hogy csak egy tíz évvel ezelőtt kitalált gyerekkönyv karakteréről van szó, ma is több millió rajongója van. A Pusheen macska egy Claire Belton művész által készített illusztrációként jelent meg.
Egy évvel később a macska saját oldalt kapott a Tumblr.com-on, és néhány hét alatt rajongók egész seregét gyűjtötte maga köré - mintegy 10 000 embert. 2013-ban a Facebook is szívesen belefoglalta a Pushin képeket a más emotikonokkal készített gyűjteményekbe. A készítővel folytatott tárgyalások után ez az ötlet megvalósult, és „felrobbantotta” az internetet! A Pusheen macskáról készült képeket naponta több mint 10 millió alkalommal használják a levelezésben!
2014-ben az Egyesült Államok egyik legnagyobb játékgyártója figyelt fel erre a karakterre. A GUND (amely a macik feltalálója volt) egy pár Pushin modellt dobott piacra. Mivel a siker hatalmas volt, néhány hónap után egy teljes játékgyűjteményt hoztak létre ebben a macska formájában.
Hol találkozhatunk még a Pusheen macskával? Az Isaac Morris Ltd. ajándékkészleteiben, a Boomf pillecukraiban, és természetesen a Pusheen kurzorok gyűjteményében!',
    'pusheen_short_descr' => 'Tegyen egy kis kényelmet a böngészőjébe a Pusheen kurzor gyűjteménnyel.',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'A 2013-as „Rick és Morty” animációs sorozatot sorolhatjuk a sci-fi és a vígjáték műfajába. Készítői Dan Harmon és Justin Royland voltak. Eleinte a Cartoon Network csatornán mutatták be, majd online mozikban és videómegosztókon is elérhetővé vált. Néhány évente új Rick és Morty évadok jelennek meg, 2019 novemberében a negyedik évad is megjelent, ami nem kevesebb érdekességet tartogatott, mint az előzőek. Az animációs sorozat cselekménye egy zseniális, ugyanakkor őrült tudós, Rick, és unokája, a különös Morty köré összpontosul. Különleges helyeken kalandoznak együtt. Egy repülő csészealjjal utaznak, mely képes áthaladni a tér-idő alagutakon. Mint kitalálhattad, ez az animációs sorozat egy kicsit a Vissza a jövőbe című filmhez hasonlít, de mégsem az animációs változata. Sok kritikus dicsérte humoros epizódjaiért, kreativitásáért and eredetiségéért. Szeretnéd Rick-et vagy Morty-t nem csak a sorozatban látni, hanem a böngésződben is? Ha igen, telepítsd a kiterjesztést és add hozzá a kedvenc rajzfilmedhez kötődő gyűjteményünket! Itt van a Rick Sanchez kurzor, a Morty Smith kurzor, a Portálfegyver kurzor és természetesen a Mr. Meeseeks kurzor.',
    'rick_and_morty_short_descr' => 'Ne zsörtölődj, csak használd a kurzorokat a Rick és Morty kollekcióból!',
    'rick_and_morty' => 'Rick és Morty',
    'mlb_teams_descr' => 'A baseball-rajongók a világon bárhol megtalálhatók. Ez különösen igaz az olyan országok lakóira, mint az USA, Kína, Kuba, Dél-Korea, Japán és Venezuela. A közhittel ellentétben a baseball nem Amerikában, hanem Angliában született. A baseball első említése és leírása a távoli 1744-ben jelent meg, az angol kiadásban. 145 év után az amerikaiak magukénak tulajdonították ezt a találmányt, a tények ellenére.
A National League 1876-ban alakult meg. Része a Major League-nek Kanadában és az Egyesült Államokban. Ma 15 csapat van a National Baseball League-ben. Minden szezon végén eljön a rájátszás ideje, amelyben a 4 legjobb csapat vesz részt. Így derül ki az egész National League győztese. Ekkor a győztes csapat lehetőséget kap arra, hogy az American League győztesével játsszon a World Series-en.
Érdekel a baseball, vagy akár szurkolsz is valamelyik csapatnak? Akkor tisztelegj kedvenc csapatod előtt azzal, hogy az egérmutatót a jellegzetességeinek formájára állítod! Változtasd meg az unalmas mutató kinézetét a böngészőben az ismerős baseball-arculattá! Alakítsd a nyilat egy játékos ütőjévé vagy sisakjává a National League bármely csapatában, amelyek már magukban foglalják a New York Yankees kurzort, a Great Falls Dodgers kurzort, a Boston Red Sox kurzort, a Baltimore Orioles kurzort, az Oakland Athletics kurzort.',
    'mlb_teams_short_descr' => 'MLB Teams kurzorok gyűjteménye a rajongóink számára.',
    'mlb_teams' => 'MLB Teams',
    'brawl_stars_descr' => 'A Brawl Stars a Supercell MOBA zsánerbe tartozó mobiljátéka. A 2018 végén történt megjelenés ellenére a játék nagy népszerűségre tett szert, nagymértékben a harci módok bősége és a színes, fantasztikus hősök - a bunyósok - miatt. A játékosnak bőven van miből választania - 32 egyedi karakter és mindegyiknek megvan a maga képességei és készségei. Minden hősnek van egy passzív képessége is, amely a zsákmány ládákban érhető el. A játékosok több módban küzdhetnek meg, például a "Díjazás a zsákmányért" - a két csapat közül az nyer, amelyik több csillagot gyűjtött, ellenfelek megölésével. A "rablás" módban az ellenfelek széfjeit kell betörni, miközben a sajátjukat védik. Egy érdekes "Ékkő-rablás" mód - a csapat válik győztessé, amelyik a legtöbb ékkövet gyűjti. Nos, a "Ütközés" módban 10 játékos küzd meg egymással a térképen, ahol a határokat egy mérgező felhő miatt csökkentik. A játék tele van színes dizájnnal, ami sok embernek tetszik, beleértve minket is, ami arra ösztönzött minket, hogy létrehozzunk egy külön Brawl Stars kurzor gyűjteményt. Vannak Brawl Stars Shelley kurzor, Barley kurzor, Penny kurzor, Frank kurzor, Mortis kurzor és mások.',
    'brawl_stars_short_descr' => 'Válaszd a Brawl Stars kurzorokat, és kezdődhet a csata!',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Változtasd meg az egér kurzorát két kattintással! Ingyenes gyűjtemények minden ízléshez.',
    'all_descr' => 'Ha valaha azon gondolkodtál, hogyan változtathatod meg az unalmas egérkurzort, akkor a kurzorkollekcióink neked valók! Itt klassz képregényhősöket, gyönyörű kurzorokat találsz a gamerek számára a népszerű játékok karaktereivel, vicces kurzorkészleteket a praktikus tréfákhoz, színes kurzorokat és sok más érdekes opciót.',
    'text_title' => 'Menő és legviccesebb kurzor gyűjtemények mindennapra',
    'text_allcat_title' => 'Egyedi és kreatív egérkurzorok, hogy passzoljanak minden hangulatodhoz',
    'text_1' => 'Nem szeretnél olyan lenni, mint mindenki más? Vagy csak szereted a különleges dolgokat? Szeretnél kedvenc játékod hősének vagy rajzfilm szereplőjének a része lenni? Akkor jó helyen jársz. Itt ragyogó, szokatlan kurzor készleteket találsz, amelyek felválthatják az ismerős és már eléggé unalmas fehér nyilat. Az egérkurzor egész nap kísér minket a munka és a tanulás során, ezért nagyszerű hangulatot kell adnia, és pozitívra kell hangolnia.',
    'text_2' => 'Itt játékosoknak és filmrajongóknak való kurzorokat talál, gyönyörű kurzorokat kedvenc rajzfilmjei alapján és sport motívumokat a legaktívabb embereknek. Szereted a képregényeket vagy nem tudsz egyetlen napot sem elképzelni vicces mémek nélkül? Imádod az állatokat, vagy arról álmodsz, hogy a világ összes országát meglátogatod? Minden egyszerű - nálad is van megfelelő kurzorkép. Képeket is választhatsz attól függően, hogy mivel dolgozol. Például a fekete kurzor sokkal kényelmesebb lesz, mint a fehér, ha dokumentumokkal vagy rajzokkal dolgozol, a kéz kurzor pedig kényelmesebb lesz, ha apró grafikus elemekkel kell dolgoznod. Válassza ki kedvenc képét, állítsa be a méretét közvetlenül a bővítményben - és használja örömmel, minden nap egy pozitív jeggyel kezdve!',
    'install_to_preview' => 'Kérjük, telepítse a bővítményt az előnézethez',
    'install' => 'Telepítés',
    'add_button' => 'Hozzáadás',
    'preview_button' => 'Előnézet',
    'added_button' => 'Hozzáadva',
    'add_cursor' => 'Kurzor hozzáadása',
    'to_your_collection' => 'a gyűjteményéhez',
    'prev_text_1' => 'Teljes képernyős előnézet',
    'prev_text_2' => 'kurzor',
    'cursor' => 'kurzor',
    'pointer' => 'mutató',
    'a_title_1' => 'Cursor Style - Klassz kurzorok a böngésződhöz',
    'a_title_2' => 'Klassz tematikus kurzorok gyűjteménye',
    'mouse_cursors' => 'egérkurzorok',
    'cursor_collection' => 'Kurzor gyűjtemény',
    'sborka_cursorov' => 'kurzor gyűjtemény',
    'collection_list_from_colllection' => 'Kurzorok listája - ',
    'christmas' => 'Karácsony',
    'nhl_teams' => 'National Hockey League',
    'neon' => 'Neon',
    'adventure_time' => 'Kalandra fel!',
    'nba_teams' => 'National Basketball Association',
    'spongebob' => 'SpongyaBob',
    'phineas_and_ferb' => 'Phineas és Ferb',
    'fortnite_chapter_2' => 'Fortnite 2. fejezet',
    'pokemon' => 'Pokémon',
    'famous_people' => 'Hírességek',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Képregények',
    'igry' => 'Játékok',
    'multfilmy' => 'Rajzfilmek',
    'kino_i_serialy' => 'Filmek',
    'anime' => 'Anime',
    'futbol' => 'Labdarúgás',
    'avtomobili' => 'Autók',
    'memy' => 'Mémek',
    'emodji' => 'Emoji',
    'pitomcy' => 'Háziállatok',
    'stil_i_krasota' => 'Divat és stílus',
    'prazdniki' => 'Ünnepek',
    'flagi' => 'Zászlók',
    'vokrug_sveta' => 'A világ körül',
    'eda_i_napitki' => 'Ételek és italok',
    'cvetnye' => 'Színes',
    'prank' => 'Huncutságok',
    'startovyj_nabor' => 'Kezdő készlet',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'A Mikulás imádni fogja a karácsonyi kurzoraidat',
    'nhl_teams_short_descr' => 'NHL kurzorok gyűjteménye igazi rajongóknak',
    'neon_short_descr' => 'Adj a képernyődhöz ragyogást egy neon kollekcióval',
    'adventure_time_short_descr' => 'Matekozás az Adventure Time kurzor kollekcióval',
    'nba_teams_short_descr' => 'NBA kurzorok a nagyszerű kosárlabda győzelmek szimbólumaként',
    'spongebob_short_descr' => 'Tudd meg ki lakik az óceán fenekén a Spongyabob kurzorok gyűjteményével!',
    'phineas_and_ferb_short_descr' => 'Biztosan nem fogsz unatkozni Phineas és Ferb kurzor gyűjteményével.',
    'fortnite_chapter_2_short_descr' => 'A Fortnite kultjáték új fejezete.',
    'pokemon_short_descr' => 'Kapd el mindet, ha tudod.',
    'famous_people_short_descr' => 'Inspirálja az idol kurzorát',
    'the_elder_scrools_short_descr' => 'Merüljön el a lovagok és sárkányok világában',
    'halloween_short_descr' => 'Féljen attól, hogy lemarad az új Halloween kollekcióról',
    'nfl_teams_short_descr' => 'Az igazi futballrajongóknak',
    'five_nights_at_freddy_short_descr' => 'Próbálj meg nem megijedni ezektől az animatronikáktól.',
    'komiksy_short_descr' => 'Kurzorok képregényekből: válaszd ki a hangulatodat ma.',
    'igry_short_descr' => 'Virtuális valóság: kivel játszol ma?',
    'multfilmy_short_descr' => 'Kedvenc rajzfilmfigurák új designban',
    'kino_i_serialy_short_descr' => 'A kurzor ura: A Desktop testvérisége',
    'anime_short_descr' => 'Mindenki szereti az animét: ki a kedvenc karaktered?',
    'futbol_short_descr' => 'Igazi sportrajongó vagy? Akkor itt a helyed',
    'avtomobili_short_descr' => 'Az álmaid autója: egy nagy flotta a profik számára',
    'memy_short_descr' => 'Kedvenc motívumok: Mém kurzorok gyűjteménye',
    'emodji_short_descr' => 'Mutasd meg a valódi hangulatod másoknak - állítsd be a Cursojit!',
    'pitomcy_short_descr' => 'Világos kurzorok minden kis testvérünk szerelmeseinek',
    'stil_i_krasota_short_descr' => 'Eredeti kurzorok minden alkalomra',
    'prazdniki_short_descr' => 'Mi van a naptárban? Új Ünnepi Kurzorok Gyűjtemény!',
    'flagi_short_descr' => 'Kalandra vágyom: hová megyünk ma?',
    'vokrug_sveta_short_descr' => 'A világ körül egy pillanat alatt: hová megyünk ma?',
    'eda_i_napitki_short_descr' => 'Szájat vizet hozó kurzorok a kreativitáshoz',
    'cvetnye_short_descr' => 'Fesd az életedet élénk színekkel és merész vonásokkal',
    'prank_short_descr' => 'Egy sor kurzor a legviccesebb tréfákhoz',
    'startovyj_nabor_short_descr' => 'Új nézőpont a már ismert dolgokra: a kurzorok frissített sorozata',
    'fortnite_short_descr' => 'Kövesd a streamereket!',
    'dota_2_short_descr' => 'Tedd a virtuális világodat valódivá!',
    'minecraft_short_descr' => 'Kedvenc játékod karaktereit mindig a közeledben tarthatod',
    'christmas_descr' => 'Mindannyian kétségtelenül a legnépszerűbb ünnepet várjuk - a karácsonyt. A világ összes kereszténye hagyományosan minden évben, december 25-én ünnepli. Egy olyan időszak, amikor a családok egy asztal köré gyűlnek, megosztják örömüket és szeretetüket, és ajándékokat cserélnek. Jóval karácsony előtt az emberek fényes girlandokkal díszítik az utcákat, otthonaikat pedig a hagyományos kellékekkel. Nehéz olyan embert találni, aki nem szereti a karácsonyt - egy szórakoztató és titokzatos ünnepet, mert sok hagyomány és rituálé kíséri, amelyek visszavisznek minket az egész családunk gyökereihez. Karácsony estéjén szó szerint minden át van itatva a szellemével, a festett mézeskalácstól a megható énekekig. Egy elegáns karácsonyfa és az alatta lévő ajándékok, egy gyermekkori öröm, amelyet mindannyian ismerünk. Szeretnénk csatlakozni ehhez a varázslatos ünnephez, és ki tudja, talán a Mikulás különleges ajándékot készít neked, ha karácsonyi kollekciónkkal díszíted kurzorodat. Ehhez minden megvan, amire szükséged van, a Mikulás kurzor, a karácsonyfa kurzor, a mézeskalács kurzor, a Hóember kurzor, sőt még az ajándékcsomag kurzor is. Boldog Karácsonyt!',
    'nhl_teams_descr' => 'A National Hockey League 1917-ben alakult - egy professzionális sport szervezet, amely egyesíti az USA-ból és Kanadából származó jégkorongklubokat. És ez a világ egyik első professzionális jégkorongligája. Az NHL Észak-Amerika egyik legkiemelkedőbb sportligája, az NFL, az NBA, a Major League Baseball és az MLS mellett. Minden évben 30 amerikai és kanadai város 31 csapata küzd a fő trófeáért - a Stanley Kupáért, és a legtöbb pontot szerző csapat a rendszeres szezonban megkapja az Elnöki Kupát. Itt az ideje, hogy tisztelegjünk ennek a nagyszerű játéknak azzal, hogy létrehozunk egy NHL kurzorok gyűjteményét. Ha Ön is szereti a hokit, szurkoljon kedvenc klubjának, vagy vegyen részt ebben a sportban, csak változtassa meg a kurzort, és ne szakadjon el kedvenc csapatától, beleértve a Boston Bruins kurzort, a St. Louis Blues kurzort, a Columbus Blue Jackets kurzort, a Tampa Bay Lightning kurzort, a Dallas Stars kurzort és más, a szívből jövő tiszteletet érdemlő klubokat.',
    'neon_descr' => 'Egyedi neon kurzormintákat hoztunk létre, hogy változatosságot vigyünk a mindennapi internetezésbe, és egy kis ragyogást adjunk a lenyűgöző neonfényekhez. Engedje, hogy gazdag színeik megteremtsék az éjszakai város burkoló hangulatát, adjanak ihletet valami új létrehozásához. A modern világban a metropolisz fényei mindig az éjszaka beköszöntét hirdetik, minden utcán követnek minket, és ez a ragyogás energiával van tele. Kísérje ezt egy ragyogó fagylalt kurzor, egy finom hot dog kurzor, egy szaftos hamburger kurzor, egy csillogó gyémánt kurzor és más kurzorok az új neon kollekcióból.',
    'adventure_time_descr' => 'A "Kalandra vár" egy fantasztikus zsánert képviselő rajzfilm, melynek cselekménye egy apokalipszist túlélő világban játszódik. Ez a terület a Land Ooo, mely nemrég még egy nukleáris háború színtere volt. De mindez már a múlté, azonban a túlélő emberek mutációknak voltak kitéve, a világ pedig megtelt varázslattal. Az animációs sorozat főszereplői Finn, egy 14 éves fiú, és barátja, Jake, a kutya. A fiú és a kutya nagyon szeretik a kalandokat, folyamatosan segítenek mindenkinek, aki bajban van. A barátok egy fán élnek, és minden idejüket együtt töltik. Ha szeretnél elmerülni a kalandok világában a többi rajongóval, akkor kiáltsd: "Matematika!". Itt van a Finn fiú kurzor, a Jake kurzor, valamint a Cukorka Hercegnő kurzor. Természetesen nem feledkeztünk meg a Bimo kurzorról, a Jégkirály kurzorról és másokról.',
    'nba_teams_descr' => 'Ha a kosárlabda a kedvenc játékod, ahogy nekünk is, akkor egy NBA csapatoknak szentelt kurzorgyűjteményre van szükséged. Az NBA az észak-amerikai kontinens egyik legjobb sportegyesülete. Amikor létrehoztuk ezt a gyűjteményt, a választás gyötört minket – melyik csapatot válasszuk, mert harminc van belőlük az NBA-ben. De vannak olyan csapatok, amelyek legendák. Ez a Chicago Bulls, amely a 90-es évek közepén rekordot döntött a győzelmek terén. Ez a Golden State Warriors, amely néhány évvel ezelőtt összehozta a legjobb bajnoki játékosokat. Vagy például a Lakers, Celtics is őrülten menő csapatok. Ha Ön is, mint mi, várja a kedvenc kosárlabdacsapatainak meccseit, és támogatását szeretné kifejezni a csapat vagy a játékosok felé, töltse le az NBA-kurzorok gyűjteményét.',
    'spongebob_descr' => 'A "SpongyaBob Kockanadrág" rajzfilmsorozatot oly sokan ismerik. Óriási siker volt, miután a Nickelodeon 1999-ben úgy döntött, hogy egy rajzfilmsorozatot készít az oktatási célú Tide Zone képregény alapján, és nagyon jövedelmező franchise-zá vált. A sorozat alkotója a tengerészeti laboratórium egykori alkalmazottja, ezért a rajzfilmsorozat szinte minden karaktere a tengerfenék vicces lakója, sajátos jellemzőkkel és karizmával. A cselekmény a titkos Krabbyburger recept körül forog, amelyet csak a főszereplő tud elkészíteni - SpongyaBob. A tenger többi lakója pedig igyekszik megszerezni, beleértve a fő antihőst, Sheldon Plankton-t, akinek minden alkalommal nem sikerül. A SpongyaBob kurzorgyűjteményben összegyűjtöttük a sorozat összes figyelemreméltó karakterének és eseményének kurzorait. Például Mr. Krabs kurzora a dollárral, Patrick Star kurzora, Tunyacsáp klarinéttel, a medúza kurzora, SpongyaBob kurzora és sok más karakter.',
    'phineas_and_ferb_descr' => 'A kitalált amerikai Denville városában, a nem létező Trishtatyában két érdekes fiú él. A vakációjuk minden napja hihetetlen kalandokba torkollik, mert képesek egy egész várost betöltő hullámvasutat vagy egy igazi portált készíteni egy másik bolygóra. Csodálatos szórakozásukat megosztják barátaikkal. Ugyanakkor, miközben a fiúk szórakoznak, a gonosz tudós, Heinz Fufelschmertz egy újabb gonosz gépet épít, ami káoszt okoz, és a "-inator"-ral végződik, amellyel bosszút akar állni gyermekkori sérelmeiért, vagy hatalmat akar szerezni Trishtatban, de Perry akadályozza őt - Utkonos, a titkos "P ügynök", a fiúk háziállata álcájában. A rajzfilmsorozat népszerűsége a gyerekek és a felnőttek körében egyaránt arra inspirált minket, hogy létrehozzunk egy Phineas és Ferb kurzormintát, hogy megváltoztathassa az egér kurzorát a sorozat karaktereire. Közöttük van a Phineas Flynn kurzor, a Dr. Heinz Fufelschmertz kurzor, a Ferb Fletcher kurzor, a Candace Gertrude Flynn kurzor és a Perry kacsacsőrű kurzor.',
    'fortnite_chapter_2_descr' => 'A Fortnite második fejezete egy nagyszabású esemény - A Vég - után érkezett, amely mindent, amit a játékosok szerettek a játékban, egy fekete lyukba rántott. A Fortnite 2. fejezete most egy új térképpel rendelkezik, amely első pillantásra még vadabb, mint az eredeti térkép, valamint számos változtatás a játékmechanikában, és természetesen sok új játék tartalom! Járművek, érzelmek, úszási mechanika és még sok más - mindez friss, érdekes képekben, mindaz, amit szeretsz és értékelsz ebben a kultikus játékban. Merülj el egy új világban - válassz egy leszállási helyet, és fedezz fel egy teljesen új szigetet 13 helyszínnel. Úszás, horgászat, motorcsónakok - ez egy új vízi játékmenet. Több szórakozás és kevesebb erőfeszítés - fejleszd a teljesen új 2. fejezetet, és ne felejtsd el megváltoztatni a kurzort új skinekre és fegyverekre. Már várnak rád a frissített skin-ek: Turk kurzor, Riptide kurzor, Rippley kurzor, Remedy kurzor, Toxin kurzor, 8-Ball kurzor, Fusion kurzor és mások!',
    'pokemon_descr' => 'A "pokemon" szó egy természetfeletti képességekkel rendelkező lényt jelent. Intelligenciával rendelkeznek, és némelyikük még beszélni is képes. Jelenleg már 802 féle Pokémon létezik. A kitalált Pokémon-univerzumban az embereket Pokémon-edzőknek hívják, akiket a más edzők Pokémonjaival vívott csatákra képeznek. És minél tapasztaltabb és erősebb az edző, annál nagyobb a tisztelet, amit élvez. Szerencsére meg kell jegyezni, hogy a Pokémon-harcok soha nem végződnek ezen egyedi lények halálával. Minden Pokémonnak különböző képességei vannak, és az elemek típusa szerint eltérnek, és a különböző támadásokkal szembeni ellenállása nagymértékben ettől függ, és egyes lények egyszerre két elem képességével rendelkeznek. A csata megnyerése után a Pokémon megkapja az értékes tapasztalatot, ami a szint emeléséhez, és ennek megfelelően a jellemzőihez szükséges. A Pokémon-univerzum ma egy hatalmas média franchise, és úgy döntöttünk, hogy elkészítünk Önnek egy kurzorgyűjteményt néhány népszerű Pokémonnal. Közülük a leghíresebb a Pikachu kurzor, valamint a Rattata kurzor, a Squirt kurzor, a Bulbasaur kurzor és a Charmander kurzor. Ez a lista frissülni fog, mert annyi van belőlük, és mindegyikük a maga módján egyedi.',
    'famous_people_descr' => 'A sok híres ember közül mindannyian találunk egy példaképet, vagy egyszerűen csak csodáljuk ezeknek a hírességeknek a zsenialitását, tehetségét és kitartását. Összeállítottunk egy hírességeket ábrázoló kurzor-gyűjteményt, hogy inspiráljunk, és emlékeztessünk a nagyszerű eredményekre, melyeket mindegyikünk elérhet. Nem minden híres személyiségnek volt boldog sorsa, de ők tanítanak meg minket a legfontosabb dologra, hogy soha nem szabad visszariadni a dédelgetett céltól, a nehézségek és problémák ellenére sem. Végül is, ez a siker elérésének fő elve - nap mint nap a vágyad felé haladni, és végül a legjobb lenni a saját területeden. Talán ma csak az egér kurzorját szeretnéd megváltoztatni, és holnap az egész életed jobbra fordul! A gyűjtemény folyamatosan frissül új, méltó emberi képviselőkkel. Köztük természetesen tudósok, politikusok, sportolók, művészeti képviselők és sokan mások. A George Washington kurzor, a Michael Jordan kurzor, a Stephen King kurzor, az Elvis Presley kurzor és a Marilyn Monroe kurzor csak a kezdet.',
    'the_elder_scrools_descr' => 'Az Elder Scrolls egy számítógépes szerepjáték-sorozat, amelyet egy közös, aprólékosan megtervezett univerzum egyesít, amely óriási szabadságot biztosít a játékosnak a választásban, lehetővé téve számukra, hogy felkeressék a fantáziavilág különböző területeit és városait, és saját maguk fedezzenek fel új helyeket és küldetéseket. A sorozat munkálatai 1992-ben kezdődtek, és az évek során a játék a játékosok hatalmas közösségét egyesítette maga körül. Ezért a nagy igények miatt kiadtuk az The Elder Scrolls kurzorok gyűjteményét, így elmerülhet a játék egyedi légkörében. A lovagok és sárkányok örök csatája, kinek az oldalán állsz? Változtasd a kurzort sárkányra, és csatlakozz a tűzokádó szörnyek seregéhez, vagy harcolj nemesen az emberek oldalán a kard mutató kiválasztásával és kedvenc karaktered képével - a döntés a tiéd! A lényeg, hogy új gyűjteményünkkel készen állsz minden csatára.',
    'halloween_descr' => 'Egy misztikus éjszakára várva, a Mindenszentek előestéjén. A Halloween története több mint kétezer évre nyúlik vissza. Talán ez a legfurcsább ünnep, amely a mókát és a félelmet ötvözi, a kelta kultúra szülötte. Akkoriban az emberek máglyákat égettek és ijesztő jelmezeket öltöttek, hogy elűzzék a szellemeket. A "Halloween" szót először a 16. században említették, mint az angol All-Hallows-Even skót rövidítését. III. Gergely pápa november 1-jét Mindenszentek napjává nyilvánította, az előtte levő estét pedig All Saints Eve-ként, később Halloween-ként ismerték. Ezen a napon az emberek vérfarkasok, szellemek és más szörnyek jelmezeit viselik, és a szomszédos házakhoz mennek, édességet kérve. Tematikus partik, tűzijátékok, gyönyörű lámpások, tökök és mutatványok egyedülálló hangulatot teremtenek. Mi is szeretnénk megünnepelni ezt a szörnyű ünnepet a kiegészítő kurzorokkal és a Halloween karakterekkel. A kollekciónkban a következőket találhatod: zombi kurzor, szellem kurzor, fekete macska kurzor, tök kurzor és még sok más. A hangulatod megváltoztatása most épp olyan egyszerű, mint a kurzorod megváltoztatása az új Halloween kollekciónkkal.',
    'nfl_teams_descr' => 'Mi lehetne jobb egy igazi amerikai futball rajongó számára, mint egy egérmutató a szurkolt csapat szimbólumaként? A modern National Football League-ben harminckét csapat játszik, a National és American Football Conference-ek között (National Football Conference, NFC és American Football Conference, AFC). A konferenciák négy divízióra oszlanak: Kelet, Észak, Dél és Nyugat. Az NFL szezonja a felkészülési mérkőzésekből, a rendes szezonból és a rájátszásból áll. Az NFL szezonjának döntőjét Super Bowl-nak nevezik, lényegében a legnépszerűbb sportesemény az Egyesült Államokban. Ez a kedvenc játéka rajongók millióinak, ezért létrehoztunk egy NFL mutató gyűjteményt, hogy ne szakadjon el kedvenc csapatának jelképeitől. Legyen az New England Patriots, New York Giants, Buffalo Bills vagy egy másik csapat, mindig legyen egy hullámhosszon a bálványaival, a csapat logójának és sisakjának formájában. A gyűjtemény folyamatosan frissülni fog, hogy mindenki a kedvenc csapatának képére válthassa a kurzort.',
    'five_nights_at_freddy_descr' => 'Az igazán egyedi Five Nights at Freddy\'s játék gyorsan nagy népszerűségre tett szert, és ez nem meglepő, hiszen egyszerű és egyben lenyűgöző cselekménye órákig a képernyőn tarthatja a játékosokat. A Five Nights at Freddy\'s kurzorokat a játék rajongóinak kérésére terveztük, és nagyon örültünk, hogy ilyen érdekes és vicces karaktereket testesíthetünk meg. De ellentétben a játékkal, kurzoraink nem fenyegetnek semmivel, ezért bátran választhatod kedvenc animatronjaidat, legyen az Medve Freddy vagy Nyuszi Bonnie vagy mások. A lényeg, hogy most a játék életre kel a böngésződben, és friss érzelmeket ad. Garantáljuk, hogy nincsenek szellemek a kurzorainkban, de tökéletesen közvetítik a félelmet keltő játék szellemét a dizájn és a cselekmény elemeinek bonyolultsága miatt. De mi van, ha nagyon nagyra állítod a kurzor méretét? Tudsz nyugodt maradni, és nem megijedni?',
    'komiksy_descr' => 'Úgy tűnik, hogy az egérmutató egy apróság, de gyakran az ilyen részletek javíthatják a hangulatodat, felébreszthetnek a szürke reggelen, vagy csak élénk érzelmeket adhatnak. A képregény kurzorok gyűjteményét kifejezetten minden szuperhős szerelmesének tervezték. Itt megtalálhatod a Marvel Univerzum és a DC Comics minden elemét - a Vasembertől a Thanosig, a Pókembertől a Hulkkig. A kurzor stílusa lehet szuperhős formájában, vagy a karakterének formájában. A kurzor nem csak egy funkcionális elem; professzionális értelemben is fontos. Például, ha videót rögzítesz a képernyőről, jobb, ha egy fényes, eredeti képet látsz, és ez sokkal érdekesebbnek tűnik. És persze - ki ne akarná a végtelen kesztyűjét használni a valóságban? Az egérmutató megváltoztatása egyszerű - csak töltsd le a bővítményt a böngésződhöz, és add hozzá a beállításaidhoz a tetsző kurzort. Kiválaszthatsz kurzort a hangulatodnak megfelelően, akár minden nap. Elég a szürke napok - légy szuperhős most!',
    'igry_descr' => 'A számítógépes játékok már régóta életünk szerves részévé váltak. Segítségükkel elmerülhetünk egy új világban, részt vehetünk kalandokban, és teljesen más emberré válhatunk. Mindenkinek megvan a kedvenc játéka, melynek karaktereiből már szinte családtagok lettek. A jól ismert számítógépes játékok alapján készült kurzorok egy készlete lehetőséget ad az unalmas mindennapok feloldására, egy kis kreativitás, vidámság és szórakozás hozzáadására a munkafolyamathoz. A készlet a játék hősök maguknak a képeit, valamint a segédkaraktereket, fegyvereket és a játékikonokat is tartalmazza. Válassza ki, ami a hangulatának megfelel - a játék kurzorok nem csak a játékosoknak fognak tetszeni, hanem mindenkinek, aki egyszerűen belefáradt a szürke hétköznapokba. Csak töltse le a készletet, változtassa meg az egérkurzorát - és már mehet is, teljesíteni a küldetéseket, elpusztítani az ellenségeket és elérni a céljait.',
    'multfilmy_descr' => 'Minden felnőttben még mindig ott él egy gyermek, aki szereti a rajzfilmeket, és még mindig arról álmodik, hogy egyike lesz a hősöknek. Segítünk valóra váltani álmait - használja az új kurzorkollekciót, amely a leghíresebb és legkedveltebb rajzfilmeken alapul. Tom és Jerry, Buzz Lightyear és Shrek, Rejtélyek városa és még Pokémon is - minden nap az lehetsz, aki akarsz. Válassza ki az egérkurzort a hangulatának megfelelően. Ki vagy ma? Egy vakmerő és vidám minyon, aki könnyedén megoldja a problémákat, vagy egy erős és bátor Raphael, akinek célja nemcsak a hőstettek végrehajtása, hanem a pizza elfogyasztása is? Talán te vagy a mindenható dzsinn, aki egy egész irodát tart irányítása alatt? A gyűjteményben mindenki számára vannak hősök - a hercegnőktől a sárkányokig - csak el kell dönteni, hogy kinek a hangulatát tükrözi a mai nap. A Cursor Style nem csak egy szép kép. Ez az individualitás, az önkifejezés, és egyszerűen - a móka, az öröm és a pozitív energia tükröződése az egész napra. Unalmas a munka, vagy túl lusta vagy a tanuláshoz? Szomorú lettél, és nem vagy boldog? Változtasd meg a kurzort, és a világ új színekben fog ragyogni.',
    'kino_i_serialy_descr' => 'Filmek - varázslat, misztikum és egy nagyszerű módja a kikapcsolódásnak, a szórakozásnak és az élénk érzelmek szerzésének. Ugyanakkor a nézés után még emlékszünk a kedvenc hősökre, akikkel nagyon szeretnénk találkozni a valóságban. Most lehetséges - csak töltse le az új kurzorkollekciót, mely híres filmeken és TV-műsorokon alapul. Az élénk, klassz kurzorok nagyszerű kiegészítői lesznek az asztalnak, a unalmas szürke mindennapokat ünnepivé, a banális feladatokat pedig izgalmas kalanddá változtatják. Cserélje a kurzor hősét minden nap - a hangulatának, a feladatoknak megfelelően vagy véletlenszerűen. Ki leszel ma? Őszinte és becsületes John Snow, vagy a bátor, könyörtelen John Wick? Talán nehéz küldetés előtt áll, és csak Frodo tudja teljesíteni? Talán ma csak egy idegen vagy, aki nem akar kapcsolatba lépni másokkal? Válasszon egy megfelelő kurzort - derítse fel a hangulatát, és ezzel egyidejűleg mutassa meg másoknak, mit gondol és hogyan tervezi eltölteni a napját. Próbálja ki - nemcsak szórakoztató, de addiktív is - biztosan nem akar visszatérni a szokásos nyílhoz.',
    'anime_descr' => 'Az anime egy egyedi animációs stílus, amely a kiejtett etnikum ellenére is emberek millióinak tetszett szerte a világon. Valószínűtlen, hogy lenne legalább egy ember, aki ne nézett volna ebben a stílusban készült rajzfilmet. Létrehoztuk a legmenőbb anime stílusú kurzorokat, amelyeket minden stílus rajongó imádni fog. A standard kurzorok unalmasak és közhelyesek. Mutasd meg a személyiséged - használd az Anime kurzorok gyűjteményét a kedvenc karaktereiddel. Válassz egy sötét kard kurzort, ha kalandokról és bátor csatákról álmodozol. Az aranyos kövér Totoro felvidít még a legszomorúbb napon is, és Naruto motiválni fog a kalandokra, és megmutatja mindenkinek, hogy te egy nagyméretű király vagy. Az élénk kurzorok felderítik a munkanapot, vagy érdekesebbé és élvezetesebbé teszik a tanulási folyamatot. Ne korlátozd magad - használd a kedvenc motívumaidat még olyan kis elemekben is, mint az egérkurzor. Cseréld a kurzorokat minden nap, hangold őket a hangulatodhoz, és mutasd meg a személyiséged - anime stílusú kurzorokkal ez ennyire egyszerű.',
    'futbol_descr' => 'A futball egy különleges sport, amely a birkózás, az atlétika és a pontosság elemeit foglalja magában. Általánosságban elmondható, hogy látványos, könyörtelen, és rajongók millióit gyűjti maga köré a világon. Szereted a futballt, vagy csak szereted a sportot? Akkor töltsd le a kurzorok készletét a világhírű játék stílusában, és bizonyítsd, hogy hűséges rajongó vagy. A gyűjtemény 24 lehetőséget tartalmaz a kurzorok tervezéséhez - a legnépszerűbb csapatok formájában, amelyek megérdemlik a címüket, mint kétségbeesett és kitartó játék. A kurzorok két változatban készülnek - egy szabványos háromszög formájában, a csapat színeivel díszítve, vagy egy megfelelő játékos sisak formájában. A szabványos böngésző kurzor unalmas, és nem méltó egy igazi sportrajongóhoz. Légy eredeti és egyedi a kollekciónkkal. Töltsd le a képeket, és válaszd ki kedvenc csapatod színeit, vagy egyéni kurzorokat, ha csak szereted a sportot, és mindenkinek szurkolsz. Könnyű követni a hobbijaidat - nem kell sálban vagy a kedvenc csapatod sapkájában munkába menned, gyorsan és egyszerűen megváltoztathatod a kurzort egy élénk, stílusos képre.',
    'avtomobili_descr' => 'Szereti az autókat, és szívesen nézegeti a különböző gyártók modelljeit? Vagy régóta egy bizonyos márkáról álmodozik, de még mindig nincs lehetősége megvásárolni? Kifejezetten Önnek hoztuk létre a "Szuperautók" kurzorok fényes készletét. Itt megtalálja a klasszikus Fordot és a stílusos Bentleyt, a fényes Lamborghinit és az egyedi Ferrarit. Szeretne az eredeti autó tulajdonosává válni? Egyszerű - töltse le a kurzorok gyűjteményét a készülékére, és változtassa meg az autó képét legalább minden nap. A kurzorok két verzióban készülnek - egy teljes értékű autóként vagy annak jelzésként. Válassza ki, hogy mi tetszik a legjobban, vagy hogy hogyan szeret a leginkább dolgozni. Az ilyen képek nagyszerűen fognak kinézni játék kurzorként vagy egyszerűen az asztal szokatlan elemeként. Fényesnek lenni egyszerű - ehhez nem szükséges elképzelhetetlen dolgokat tenni, vagy megváltoztatni a megjelenését. Elég csak abbahagyni a közhelyes tárgyak használatát, és kiválasztani azt, amit igazán szeret. A "Autók" kurzorok gyűjteménye azok választása, akik nem félnek bizonyítani önmagukat.',
    'memy_descr' => 'A mémek régóta az életünk ismerős részét képezik. És ki ne szeretné ezeket a tágas, érdekes és eredeti képeket a nap ellenére? A mémek sok hőse nem csak népszerűvé vált – a népszerű kedvencek státuszát szerezték, a kifejezések és mondatok pedig régóta a köznyelvi beszédbe épültek be, mint bevált fordulatok. Bemutatunk egy gyűjteményt a legjobb kurzorokból, amelyek a legnépszerűbb mémeken alapulnak. Segítségükkel nemcsak a személyiségedet mutathatod meg, hanem a hangulatodat is kifejezheted. Mindentől fáradt és kimerült vagy? Válassz egy dühös macskát, aki egész megjelenésével felháborodást és ellenszenvet fejez ki mindennel szemben. Vagy ma szarkazmussal ragyogsz, és nem bánod, ha nevetsz? Akkor a Drake Bling kiváló kísérő lesz – felvidít, és bármilyen feladatot eredetivé és érdekessé tesz. Telepítsd a bővítményt, töltsd le a gyűjteményünket – és válassz kurzorstílust minden napra. Nem nehéz fényes és eredeti lenni – változtasd a ikon alapértelmezett dizájnját a mémek egyik hősére, és energiabombát kapsz egész napra.',
    'emodji_descr' => 'Emoji - világos, cool ikonok, melyek nélkül már nem tudunk megszokott módon kommunikálni. Segítségükkel nem kell szavakkal leírnod a hangulatodat - csak válaszd ki a kívánt ikont, és a beszélgetőtársad minden további nélkül megért. Új kurzorkészletünkben testesítettük meg az emoji ötletét - így jelentek meg a mókás és szokatlan Cursojik, melyek színesebbé teszik a világot és érdekesebbé az életet. A kurzorok segítségével nemcsak dolgozhatsz és végezheted a megszokott feladatokat, hanem megmutathatod munkatársaidnak, barátaidnak és másoknak a hangulatodat. Az alvós kurzor tökéletes hétfő reggelre, a sírós kurzor pedig a többletfeladatokkal kapcsolatos hozzáállást fejezi ki. A menő szemüveges kurzor a legjobb választás az ünnepek előtt, a dollárjelekkel teli szemű kurzor pedig jó ok arra, hogy utalást tegy a főnöknek a béremelésre. A Cursojik használata szórakoztató és érdekes - legyen szó munkáról, tanulásról vagy bemutatóról. Ez utóbbi esetben még ajánlott is, ha a kollégáknak van humorérzéke, vagy csak oldani kell a helyzetet. Összességében bármilyen feladathoz - csak válaszd ki a megfelelő kurzort!',
    'pitomcy_descr' => 'Szereted az állatokat? Biztosan – olyan aranyosak, viccesek és nagyon mókásak. Miért ne töltenéd az egész napot egy ember legjobb barátainak társaságában? Töltsd le a Háziállatok kurzorokat a magad számára, és válassz egy barátot magadnak minden nap. A kurzor ikon lehet aranyos, mint egy jószívű alpaka, vagy stílusos, mint egy rózsaszín flamingó. Vagy esetleg egész nap elfoglalt leszel, és egy újságot olvasó unikornist választasz, vagy egyszerűen nem akarsz senkivel sem kommunikálni, mint egy gonosz fekete macska? Bármilyen hangulathoz megvan a megfelelő állatunk. Egy vidám mopsz még a legunalmasabb és legszürkébb napon is felvidít, a rózsaszín kurzor unikornis alakban pedig mindenkinek megmutatja, hogy nem vagy híján a szépségérzéknek, még egy brutális szakállas férfi is. Mi van akkor, ha nincs hangulat, és nem érzem úgy, hogy rutinfeladatokat kellene végeznem? A recept egyszerű - töltsd le a Háziállatok kollekciót, változtasd meg az egérkurzort - és lám, újra süt a nap, szép az idő, és a hangulat a legmagasabb szinten van. Nem csoda, hogy azt mondják, hogy az állatok segítenek a depresszió és a szomorúság leküzdésében!',
    'stil_i_krasota_descr' => 'Az új kurzor kollekcióban rengeteg olyan témát gyűjtöttünk össze, amelyek kellemes érzelmeket váltanak ki belőlünk, és felvidítanak. Ez a kurzorcsomag a „Stílus és szépség” nevet kapta, mert ezek a kedvenc dolgaitok, amelyek meghatározzák a mindennapi életünket, örömet okoznak, és motiválnak bennünket a fontos dolgok megtételére, a fejlődés iránti vágyat ébresztik bennünk. Rajongsz a világűr iránt, és arró álmodsz, hogy más bolygókra utazol? Válassz egy NASA kurzort vagy egy idegen tányért - közelebb kerülsz az álmodhoz. Ha nem tudod elképzelni az életet zene nélkül, vagy egy igazi rocker vagy, akkor az elektromos gitár stílusú kurzor neked való. A kefe, a vonalzó és a körző kurzort kifejezetten mérnökök számára fejlesztettük ki - ezek a képek segítenek az unalmas számításokat és rajzokat eredeti megoldásokká varázsolni. Egy varázspálca és sportcipő, egy gördeszka és rúzs, a nap és kémiai kúpok - válassz azt, ami illik az életstílusodhoz, a vágyaidhoz és a törekvéseidhez - és a mindennapi feladatok érdekesebbé válnak, a munkanapok pedig új, ragyogó színekben fognak pompázni.',
    'prazdniki_descr' => 'Szereted az ünnepeket? De ki nem szereti őket – a barátok, az ajándékok, ismét a hétvége. Hogy az ünnepek várása kellemesebb, rövidebb és melegebb legyen, nem csak a naptárban számolhatod a napokat, hanem a megfelelő ikont is beállíthatod egérkurzorodként. Kezdjük az újévvel – válasszunk karácsonyfát, ajándékot vagy Mikulást, hogy az ünnep fényes és vidám legyen. Talán a mézeskalács ember közelebb lesz – vicces, aranyos és mindig vidám? Vele biztosan nem lesz idő szomorúnak és unatkozónak lenni. Folytatjuk az ünneplést Cupidókkal és vidám szívekkel, és nincs messze a Húsvéti Nyuszi. Valahol az ünnepek között lesz egy születésnap, amelyet még kellemesebb lesz várni lufikkal a standard kurzormutató helyett. Halloweenkor pedig meglepheted a kollégáidat és a körülötted lévőket egy szokatlan egérkurzorral egy baljós tök vagy egy szellem formájában. Az ünnepekhez való kurzorok egy sorozata lehetőséget ad a várakozás felvidítására, az elkövetkező szórakozásra való előre hangolódásra, és a kiváló hangulat fenntartására nemcsak az ünnep előestéjén, hanem egész évben.',
    'flagi_descr' => 'A zászló egy egyedi szimbólum, amelyet széles körben használnak az összes közösségi hálózaton. Azt gondoltuk, miért ne csinálnánk a kurzorból zászlót? Végül is, nagyon élénk és szokatlan. Mostantól minden nap egy új országgal töltheted, és a munka nem lesz olyan monoton és unalmas. Az egérkurzorok mostantól Kína vagy az USA, Japán vagy Kanada nemzeti zászlajává tehetők, és további 38 zászló opcióval, és választhatod a standard nyíl alakot szokatlan színben, vagy a zászló alakú kurzort. Ez a készlet minden utazás szerelmesének tetszeni fog. Ezzel új utakat tervezhetsz, és hosszú utazásokról álmodozhatsz. Terveztél egy nyaralást? Mutasd meg mindenkinek, hogy melyik országba szeretnél menni. Talán úgy döntöttél, hogy új idegen nyelvet tanulsz? Akkor ez a kurzor mindenképpen támogatni fog, és motivál, hogy alaposan tanulj. Vagy te, mint Sheldon, egyszerűen szereted a zászlókat? Minden esetben a Zászlók kurzorkollekció nagyszerű kiegészítője lesz az asztalodnak, és új felfedezésekre ösztönöz.',
    'vokrug_sveta_descr' => 'Mindenki szeret utazni. Milyen csodálatos új országokat és városokat meglátogatni, látnivalókat látni és nagyszerűen érezni magunkat az új kultúrában. Kár, hogy nem olyan gyakran tudunk utazni, de megpróbáltuk ezt kijavítani. A „Világ körüli” egérkurzor készlet a legfeltűnőbb képek gyűjteménye, a különböző országok szimbólumai, amelyek segítségével még otthon ülve is igazi utazónak érezheti magát. Készletünkben megtalálhatja Japánt és Ausztráliát, Olaszországot és Kanadát, az USA-t és Mexikót - a világ legérdekesebb, eredeti és festői országait. Az egérkurzor képe lehet egy standard nyíl, az ország zászlójának színeiben, vagy az állam egyik fő látványosságává válhat. Például dokumentumokat nyithat a pisai ferde toronnyal, és prezentációkat készíthet a Szabadság-szobor segítségével. Garantáljuk - a siker biztosított lesz. Nos, vagy ha nem a siker, akkor a kollégák mosolya és az eredetiség elismerése - biztosan. Igen, és a vezetésnek való utalás, hogy ideje nyaralni menni, szintén megéri - csak állítsa be a bőröndöt vagy a repülőgépet kurzornak - és valószínűleg hamarosan repülni fog.',
    'eda_i_napitki_descr' => 'Az élelmiszerek formájában készült kurzorok egy hihetetlen gyűjteménye a fényes, ízletes és étvágygerjesztő képeknek, amelyek mindenkinek tetszeni fognak, és nagyszerű kiegészítői lesznek a böngészőnek. Klikkeltél már brokkolira vagy sült krumplira? Van egy ilyen lehetőséged - csak töltsd le az új kurzorokat, és állítsd be őket az unalmas fehér nyíl helyett. Az "Étel" kurzorok mind a standard háromszög alakú mutató, mind a termékek formájában készülnek. Itt zöldségeket és gyümölcsöket találhattok, a kedvenc ételeiteket, mint például a pizza vagy a hot dog, kávét, nyalókákat és még sok mást, ami feldobja a napot. Szereted a kávét, de egész nap inni nem olyan jó? Egészítsd ki az étrended virtuális kávéval, ami szintén felélénkít és felébreszt, valamint élénk érzelmeket ad. A virtuális fánk formájú meredek kurzor nem árt az alaknak, miközben élénk érzelmeket ad és felvidít. Használhatod a kedvenc kurzoraidat, vagy naponta cserélheted a képet - a nagyszámú kurzor segít megszínezni a mindennapokat, és új színeket adni a megszokott műveletekhez.',
    'cvetnye_descr' => 'A kurzor a böngésző fő eleme, amellyel a teljes munkanapot töltjük, tanulunk, kommunikálunk és kikapcsolódunk. A kurzor alapértelmezett képe unalmas, sőt kissé nyomasztó, de mégis sok ember számára ez a forma kényelmes, és a megváltoztatása kényelmetlen lesz. De erre a helyzetre van megoldásunk - egy sor élénk, vidám színű kurzor, amelyek változatosságot visznek a mindennapjaidba, és könnyebbé, gyorsabbá teszik a problémák megoldását. Ha azon gondolkodik, hogyan változtasd meg a kurzor színét, azt válaszoljuk - töltsd le a gyűjteményünket, és válassz fényes megoldásokat minden napra! Választhatsz monokróm tónusokat különböző színekben, hogy passzoljanak a hangulatodhoz vagy a munkád sajátosságaihoz. Például a szabványos dokumentumokkal való munka során egy lila kurzor ki fog tűnni a háttérből, a sötét háttéren pedig éppen fordítva, könnyebb lesz a sárga kurzorokkal dolgozni. Ha a színek robbanására, ragyogásra és maximális eredetiségre vágysz - válassz szivárvány kurzort, amely a spektrum összes színét tartalmazza - ezzel az ikonnal a hangulatod minden bizonnyal rendben lesz egész nap.',
    'prank_descr' => 'A munkahelyi tréfák nem mindig örvendetesek, mivel gyakran zavarják a munkafolyamatot. De az új "Tréfák" kurzor-készlettel kedvesen megtréfálhatja kollégáit vagy barátait anélkül, hogy károsítaná a munkáját vagy a tanulását. Kifejlesztettünk egy speciális gyűjteményt, amely mindenkit megnevettet, és okot ad a lazításra a munka vagy más feladatok elvégzésének forgalmas folyamata közepette. A kurzor megváltoztatásához csak töltse le a készletet a készülékre, és válassza ki a kívánt dizájnt a paraméterekben. Például kaphat egy szabványos formájú kurzort, de invertált állapotban vagy egy hullámban meghajlított nyíllal. Ez a forma egyáltalán nem akadályozza a munkafolyamatot, ugyanakkor csodálatos hangulatot teremt, és pozitív hangulatba hozza. Módosítsa a kurzor megjelenítési beállításait a hangulatának megfelelően, vagy minden nap - és bármely feladat érdekesebbé és élvezetesebbé válik, a mindennapi élet pedig nem okoz többé negatív érzelmeket. Sőt, ilyen kurzorok még komoly projektekhez is használhatók - semleges színeik vannak, és nem tűnnek ki az asztalról.',
    'startovyj_nabor_descr' => 'A kezdő kollekció kurzorai a standard formák és méretek keverékei élénk, szokatlan megjelenéssel. Ez egy kiváló választás azok számára, akik a szokásos formákat részesítik előnyben, de szeretnének sokszínűséget, eredetiséget és élénkséget vinni a mindennapi életbe. A kollekcióban megtalálható a kéz kurzor és egy ismerős nyíl számos változatban - a Google Chrome logótól az emojikig, még egy rég elfeledett sárkánnyal is találkozhatunk kaktuszokkal és nosztalgiával. Bebizonyítjuk, hogy egy standard kurzor is lehet érdekes és vonzó. A különböző színek, formák, textúrák és érdekes design segítenek kiválasztani a kurzort az ízlésednek megfelelően, vagy naponta változtatni a hangulatodtól vagy az elvégzendő feladatoktól függően. A böngésző kurzorok cseréje nagyon egyszerű - csak telepítsd a kiterjesztést és töltsd le a kollekciót a készülékedre. A vicces, érdekes kurzorok nemcsak megszínezik a munkanapokat, hanem például segítenek egy prezentációt is érdekesebbé tenni, és a különösen élénk kurzorok segítségével a jelentés egyes elemeire is felhívják a figyelmet.',
    'fortnite_descr' => 'A Fortnite meghódította a világon a rajongók millióit. Izgalmas csaták, stratégia és taktika, kalandok – mindent magába foglal, amit a játékosok annyira szeretnek. Mi sem maradtunk ki ebből, és fejlesztettünk egy sor kurzort a játék stílusában, ami nemcsak a lelkes játékosoknak fog tetszeni, hanem azoknak is, akik először hallanak a Fortniteról. A Fortnite kurzor ikon egy hős vagy a fegyverének a képe, a legapróbb részletekig kidolgozva. Találhatsz róka- és hal képeket, pokolmaszkokat és fekete lovagokat, nyílként nyilat vagy tüskés kaszát állíthatsz be. Biztosak vagyunk benne, hogy senki sem marad közömbös! Legyél ijesztő vagy titokzatos, eredeti vagy humoros – ez csak rajtad múlik. Válaszd ki a stílusodat és kövesd, vagy állíts be egyéni kurzorokat a beállításokban, és változtasd a szerepedet minden nap. Most sokkal érdekesebbé és kellemesebbé válik a fárasztó és egyhangú munka is – gyorsan elrepül az idő a élénk képekkel és a kedvenc karakterekkel való társaságban. Vagy talán versenyeket rendezel a kollégáiddal, melyik hős a legerősebb? A választás a tiéd!',
    'dota_2_descr' => 'A DotA2 már nem csak egy egyszerű játék, hanem egy igazi párhuzamos világ. A virtuális valóságban a DotA2-ben mindent megtehetsz - élhetsz, harcolhatsz, fejlődhetsz, utazhatsz, barátkozhatsz. A dolgok általában úgy vannak, mint az életben, csak néha érdekesebbek. A Dota 2 kurzorok egy stratégia folytatásai, amelyek lehetővé teszik, hogy élénk érzelmeket élj át, és kifejezd magad a valóságban. Az új kurzorcsomag a játék legfeltűnőbb karaktereit, valamint eredeti tárgyakat tartalmaz, amelyeket semmi mással nem lehet összetéveszteni. Válassz egy kurzort, amely közelebb áll hozzád - és indulj kalandra anélkül, hogy elhagynád a munkahelyedet. Milyen unalmas néha a munkában lenni vagy oktatási feladatokat elvégezni, de a játékkurzorokkal ez a probléma már nem fog szembesülni veled. Egy kis képzelőerő, egy élénk kurzor - és lám, bármely üzlet szokatlan kaland lesz, amellyel megbirkózni nem lesz nehéz és érdekes. Nem kell visszatartanod magad. Szereted a Dotát? Akkor feltétlenül töltsd le a kollekciónkat, válassz ki egyet vagy több véletlenszerű kurzort egyszerre - és minden új nap fényesebbé, érdekesebbé és telítettebbé válik.',
    'minecraft_descr' => 'Az egérmutatók a szabványos nyilak és ujjak formájában már régóta unalmassá váltak mindenkinek. Ha Ön a szokatlan és eredeti dolgok rajongója, akkor itt az ideje megváltoztatni az egérmutatót, és érdekesebb dizájnt adni neki. Kifejlesztettünk egy egérmutató-kollekciót a világhírű Minecraft játék stílusában, ahol megtalálhatja a legfeltűnőbb karaktereket. Farkas és róka, Alex és Creeper, gyémánt kard és hal - kiválaszthatja a leginkább tetszőt, vagy telepíthet egy új hőst minden nap. Ezek igazi egérmutatók a játékosok számára, és abszolút mindenkinek tetszeni fognak - hiszen ki ne játszott volna a Minecrafttal? Biztosak vagyunk benne, hogy ezek egyszerűen nem léteznek. Le a unalmas mindennapokkal - itt az ideje belemerülni a kalandokba, melyeket akár otthonról vagy az irodai székből sem kell otthagyni. Érdekesebb lesz egy jelentést elkészíteni és csökkenteni az egyenleget egy puskával - bármelyik feladat kellemesebbé válik, és nem fogja hagyni, hogy unatkozzon a helyén. Töltse le az új Minecraft egérmutató-kollekciót - állítsa be őket, és még a legszürkébb és legunalmasabb napon is mindig a legjobb lesz a hangulata. A kollégák pedig irigykedni fognak az eredményekre - egyszerűen lehetetlen nem elvégezni a munkáját a Minecraft bátor hőseinek segítségével.',
    'astrology-signs-zodiac' => 'Zodiákus jelek',
    'sports-cars_short_descr' => 'Erőteljes és stílusos autók, melyek sebességre és agilitásra lettek tervezve',
    'spider-man' => 'Pókember',
    'astrology-signs-zodiac_short_descr' => '12 asztrológiai szimbólumkészlet a személyiségjegyek, a kozmikus energiák és az életminták ábrázolására.',
    'sports-cars' => 'Sportkocsik',
    'spider-man_short_descr' => 'Hősök a Pókember univerzumából.',
    'starwars' => 'Star Wars',
    'sports-cars_descr' => 'A sportkocsik nagy teljesítményű járművek, melyeket gyors gyorsulásra, éles irányíthatóságra és izgalmas vezetési élményre terveztek. A letisztult kupéktól az agilis roadsterekig, ez a kategória a legikonikusabb gépeket vonultatja fel, amelyeket az út vagy a pálya izgalmára építettek. Ideális azoknak a rajongóknak, akik szeretik a sebességet, a dizájnt és az erőt. 🏎️🔥',
    'spider-man_descr' => 'A Pókember univerzum karaktereinek és hőseinek gyűjteménye. Tartalmazza a Pókember különböző verzióit, szövetségeseit és egyedi stílusait a képregényekből, játékokból és animációs sorozatokból. Minden dizájn tükrözi azt a mozgékonyságot, bátorságot és vizuális identitást, ami a Pókember világát jellemzi.',
    'astrology-signs-zodiac_descr' => 'A Kos jegyek ♈♉♊♋♌♍♎♏♐♑♒♓ tizenkét szimbolikus felosztása az égi övnek, amelyet az asztrológiában használnak. Minden jegyhez meghatározott dátumok, elemek (🌍 Föld, 🔥 Tűz, 🌊 Víz, 💨 Levegő), uralkodó bolygók és egyedi személyiségjegyek tartoznak. Az asztrológusok a horoszkóp jegyeit használják viselkedések értelmezésére, a kompatibilitás előrejelzésére és az életutak felfedezésére. Akár szenvedélyes Oroszlán 🔥 vagy átgondolt Halak 🌊 vagy, a jegyed betekintést nyújt a belső világodba. Ez a kategória mind a 12 jegyet, azok jelentéseit és vizuális ábrázolásait tartalmazza.',
    'starwars_descr' => 'Merülj el a messzi-messzi galaxisban ezzel a gyűjteménnyel, amely legendás hősöket, hatalmas Sith nagyurakat, droidokat, lázadókat és még sok mást tartalmaz. A Jedi lovagoktól a rohamosztagosokig, mindegyik ikon életre kelti a Star Wars szellemét kurzor formájában. Tökéletes minden trilógia rajongói számára. 🌌',
    'starwars_short_descr' => 'A Star Wars univerzum karaktereit és szimbólumait tartalmazza',
    'glitter' => 'Csillogás',
    'glitter_short_descr' => 'Fényes és csillogó kurzorok csillogó stílussal ✨🌟',
    'roblox-2025' => 'Roblox 2025',
    'roblox-2025_short_descr' => 'Karakterek a legújabb Roblox hullámból 🕹️🚀',
    'glitter_descr' => 'A csillogó textúrák és ragyogó látványvilág által inspirált kurzorok elbűvölő gyűjteménye. Tökéletes azok számára, akik a képernyőjükön a csillogó esztétikát szeretik. Ezek a kurzorok csillogást, eleganciát és egy kis varázslatot hoznak minden kattintásba.',
    'roblox-2025_descr' => 'Egy vadonatúj 2025-ös kollekció, amely ikonikus és modern Roblox karaktereket tartalmaz. Klasszikus noobokat, horror legendákat és rajongók kedvenc avatárait tartalmazza a népszerű játékokból. Szórakoztató és színes stílusban tervezték, tökéletes a gyerekeknek és a Roblox rajongóknak minden korosztályból.',
];
