<?php

return [
    'title' => 'Cursor Style - Adatvédelmi nyilatkozat',
    'descr' => 'A „Cursor Style” alkalmazásban, amely a cursor.style webhelyen vagy a Chrome-bővítményen keresztül érhető el, legfontosabb prioritásaink egyike a látogatóink adatainak védelme. Ebben a részben a bővítménnyel való munkavégzés minden aspektusáról fogunk beszélni.',
    'text' => '<h2> Adatvédelmi irányelvek </h2>
                <p> A Cursor Style-ban, a <a href="https://cursor.style"> cursor.style </a> címen vagy a Chrome kiterjesztésen keresztül, egyik legfontosabb prioritásunk a látogatóink adatvédelme. Ez az Adatvédelmi irányelvek dokumentum tartalmazza azokat az információtípusokat, amelyeket a cursor.style weboldal gyűjt és rögzít, valamint azt, hogy hogyan használjuk fel azokat. Ha további kérdései vannak, vagy további információra van szüksége az adatvédelmi irányelveinkkel kapcsolatban, ne habozzon kapcsolatba lépni velünk. </p>
                <p> A "Cursor Style" bővítmény és a weboldal a naplófájlok használatának szabványos eljárását követi. Ezek a fájlok regisztrálják a látogatókat, amikor weboldalakat látogatnak vagy a bővítményünket használják. Ezt minden tárhelyszolgáltató megteszi, és a tárhelyszolgáltatási elemzés része. A naplófájlokon keresztül gyűjtött információk közé tartoznak az Internet Protocol (IP) címek, a böngésző típusa, az Internet Service Provider (ISP), a dátum és az időbélyegző, az átmeneti / kilépési oldalak és esetleg a kattintások száma. Ezek nem kapcsolódnak semmilyen személyazonosító információhoz. Ezen információk célja a trendek elemzése, a webhely adminisztrálása és bővítése, a felhasználók webhelyen történő mozgásának nyomon követése és bővítése, valamint demográfiai információk gyűjtése. </p>
                <p> Mint minden más webhely, a cursor.style is használ sütiket. Ezeket a sütiket információk tárolására használják, beleértve a látogató preferenciáit és a weboldal azon oldalait, amelyeket a látogató meglátogatott vagy meglátogatott. Ezeket az információkat a felhasználói élmény optimalizálására használják, a weboldalunk tartalmának testreszabásával a látogató böngészőjének típusa és / vagy egyéb információk alapján. Harmadik féltől származó hirdetéseket is használunk a cursor.style oldalon a projekt támogatásához és a weboldalunk támogatásához. Néhány hirdető felhasználhat olyan technológiákat, mint a sütik és a webjelzők, amikor hirdet a weboldalunkon, amelyek ezeket a hirdetőket (például a Google-t a Google AdSense programon keresztül) is elküldik információkat, beleértve az IP-címét, az internetszolgáltatóját, a böngészőt, amelyet a webhelyünk látogatásához használt, és bizonyos esetekben, ha telepítve van a Flash. Ezt általában geocélzási célokra használják (például áruk eladására vonatkozó hirdetések megjelenítése a városában) vagy bizonyos hirdetések megjelenítésére bizonyos meglátogatott webhelyek alapján (például vásárlási bejelentések megjelenítése azoknak, akik gyakran látogatják a bevásárlóoldalakat). </ P >
                <p> Letilthatja vagy szelektíven letilthatja a mi vagy a harmadik féltől származó sütiket a böngésző beállításaiban, vagy a beállítások kezelésével az olyan programokban, mint a Kaspersky stb. Ez azonban befolyásolhatja a webhelyünkkel és más webhelyekkel való interakcióját. Ez magában foglalhatja annak a képtelenségét, hogy bejelentkezzen olyan szolgáltatásokba vagy programokba, mint például a fórumokba vagy a fiókokba való bejelentkezés. </p>
<p> A Google a webhelyünk egyik harmadik féltől származó szolgáltatója. Sütiket is használ, más néven DART cookie-kat, hogy hirdetéseket jelenítsen meg a webhelyünk látogatóinak, a cursor.style és más webhelyeken tett látogatásaik alapján. A látogatók azonban kiléphetnek a DART sütik használatából a Google Advertising and Content Network adatvédelmi irányelveinek meglátogatásával a <a href="https://policies.google.com/technologies/ads"> következő címen </a>. A weboldalunkon szereplő hirdetők némelyike ​​használhat sütiket és webjelzőket. Minden hirdetési partnerünk saját adatvédelmi irányelvekkel rendelkezik a felhasználói adatokra vonatkozó irányelveivel kapcsolatban. További információt olvashat adatvédelmi irányelveikről <a href="https://policies.google.com/technologies/ads"> itt </a>. </p>
                <p> Weboldalunk a Google Analytics szolgáltatást használja, a Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com („Google Analytics” vagy „Google”) webanalitikai szolgáltatását. A Google Analytics sütiket használ, amelyek a számítógépén tárolódnak, hogy megkönnyítsék a weboldal használatának elemzését. Az ezekből a sütikből származó információkat, mint például a webhelyünk meglátogatásának idejét, helyét és gyakoriságát, beleértve az IP-címét is, a Google amerikai helyére továbbítják, és ott tárolják. A Google az információkat harmadik feleknek is továbbíthatja, ha a törvény megköveteli, vagy ha harmadik felek feldolgozzák ezeket az adatokat a Google nevében. A Google azt állítja, hogy soha nem társítja az IP-címét más Google-adatokkal. Megakadályozhatja a sütik beállítását a böngésző szoftver beállításainak ennek megfelelő módosításával, az Adatvédelmi irányelvekben leírtak szerint. Azonban tudnia kell, hogy ily módon nem tudja teljes mértékben használni weboldalunk összes funkcióját. </p>
                <p> A Google Analytics elektronikus képeket is használ, amelyeket webjelzőknek (néha egypixeles GIF-eknek) hívnak, és sütikkel használják az összesített statisztikák összeállításához webhelyünk használatának elemzéséhez.
A fent megadott linkhez a böngésző kiegészítőjének telepítésével kapcsolatos további információkat a <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> linken </a> találhat. Ez az oldal a Google Tag Manager szolgáltatást használja. Ez a szolgáltatás lehetővé teszi a webhely címkéinek kezelését a felületen keresztül. A Google Tag Manager csak címkéket valósít meg. Ez azt jelenti, hogy a sütik nincsenek beállítva, és a személyes adatok nem kerülnek rögzítésre. A Google Tag Manager más címkéket indít, amelyek viszont adatokat rögzíthetnek. A Google Tag Manager azonban nem fér hozzá ezekhez az adatokhoz. Ha a címkék le lettek tiltva a tartomány vagy a süti szintjén, akkor azok a Google Tag Manager segítségével megvalósított összes nyomkövető címkéhez mentésre kerülnek. A Google Tag Manager szolgáltatásról a <a href="http://www.google.com/tagmanager/use-policy.html"> linken </a> tájékozódhat. </p>
<p> Megismerkedhet ezzel a listával, hogy megtalálja az egyes "Cursor Style" hirdetési partnerek Adatvédelmi irányelveit. A harmadik féltől származó hirdetésszerverek vagy hirdetési hálózatok olyan technológiákat használnak, mint a sütik, a JavaScript vagy a webjelzők, amelyeket a "Cursor Style" programban megjelenített hirdetésükben és linkjeikben használnak, és amelyeket közvetlenül a felhasználók böngészőjébe küldenek. Az IP-címét automatikusan megkapják, amikor ez megtörténik. Ezeket a technológiákat hirdetési kampányaik hatékonyságának mérésére és / vagy a látogatott webhelyeken látható hirdetési tartalom személyre szabására használják. Kérjük, vegye figyelembe, hogy a "Cursor Style" nem fér hozzá és nem is ellenőrzi azokat a sütiket, amelyeket a harmadik féltől származó hirdetők használnak. A Cursor Style adatvédelmi irányelvei nem vonatkoznak más hirdetőkre vagy weboldalakra. Ezért azt javasoljuk, hogy a további információkért tekintse át ezeknek a harmadik féltől származó hirdetésszervereknek a releváns adatvédelmi irányelveit. Ez magában foglalhatja módszereiket és utasításaikat a bizonyos beállítások lemondásához. A fenti vagy a harmadik felek szolgáltatásainak weboldalai hivatkozásokat találnak ezekhez a harmadik felek adatvédelmi irányelveihez. </p>
                <p> Letilthatja a sütiket a böngésző beállításaiban. Ha többet szeretne megtudni a sütik kezeléséről az egyes webböngészőkben, azt megtalálja a böngésző weboldalain. Beprioritásunk másik része a gyermekvédelem hozzáadása az internet használatához. Arra ösztönözzük a szülőket és a gondviselőket, hogy figyeljék, vegyenek részt és / vagy figyeljék és irányítsák tevékenységeiket az interneten. A "Cursor Style" nem tudatosan gyűjt személyes adatokat a 13 év alatti gyermekektől. Ha úgy gondolja, hogy a gyermeke ilyen információkat adott meg a webhelyünkön, nyomatékosan javasoljuk, hogy azonnal lépjen kapcsolatba velünk, és mindent megteszünk annak érdekében, hogy az ilyen információkat a lehető leghamarabb eltávolítsuk a nyilvántartásunkból. Ez az Adatvédelmi irányelvek csak az online tevékenységeinkre vonatkoznak, és érvényesek a weboldalunk látogatóira vonatkozóan az "Cursor Style" szolgáltatásban megosztott és / vagy gyűjtött információkkal kapcsolatban. Ez a politika nem vonatkozik a nem online módon vagy a webhelyen kívüli csatornákon gyűjtött információkra. </p>
                <p> A sütik használatáról a Szolgáltatásunkban az <a href="/cookie-policy"> Süti szabályzatunkban </a> olvashat bővebben. </p> ',
];
