<?php

return [
    'title' => 'Cursor Style - Term of use of our product',
    'descr' => 'A felhasználási feltételek Ön és a „Cursor Style” („Szolgáltatás”, „mi” vagy „Szolgáltató”) között jönnek létre. Ezt a szolgáltatást kizárólag 13 éves vagy annál idősebb felhasználók számára kínáljuk és érhető el, kizárólag személyes használatra, nem kereskedelmi célra.',
    'text' => '<h2> Felhasználási feltételek </h2>
<h3> KÉRJÜK, OLVASSA EL A JELEN FELTÉTELEKET, MIELŐTT HASZNÁLJA A WEBOLDALT ÉS A BŐVÍTMÉNYT. </h3>
<p> A jelen felhasználási feltételek a Ön és a "Cursor Style" ("Szolgáltatás", "mi" vagy "Szolgáltató") között jönnek létre. A következő feltételek, valamint a hivatkozással kifejezetten beillesztett dokumentumok (a továbbiakban együttesen: "Felhasználási feltételek") a cursor.style weboldalhoz és böngészőbővítményeihez való hozzáférését és használatát szabályozzák, beleértve a szolgáltatásunkon vagy azon keresztül kínált tartalmakat, funkcionalitást és szolgáltatásokat (együttesen "Szolgáltatás"). </p>
<p> A weboldal vagy a bővítmény használatával elfogadja és beleegyezik, hogy betartja ezeket a Felhasználási feltételeket. Ha nem ért egyet a Felhasználási feltételekkel vagy adatvédelmi irányelveinkkel, akkor nem szabad a Weboldalt és a Bővítményt elérnie vagy használnia. </p>
<p> Ezt a szolgáltatást csak személyes használatra kínáljuk és érhető el a 13 éves és annál idősebb felhasználók számára, nem kereskedelmi célokra. A Szolgáltatás használatával Ön kijelenti és szavatolja, hogy (I) 13 éves vagy idősebb, (II) a Weboldalak használata nem tilos az alkalmazandó jogszabályok szerint, és (III) a Szolgáltatást csak személyes igényeinek megfelelően használja. Ha nem felel meg ezeknek a követelményeknek, akkor nem szabad a Szolgáltatást elérnie vagy használnia. </p>
<p> Időnként saját belátásunk szerint felülvizsgálhatjuk és frissíthetjük a Felhasználási feltételeket. Minden változtatás a közzétételük után azonnal hatályba lép. A Felhasználási feltételek felülvizsgált változtatásainak közzétételét követően a Szolgáltatás további használata azt jelenti, hogy elfogadja és beleegyezik a változásokba. Elvárjuk, hogy gyakran látogassa meg ezt az oldalt, hogy naprakész maradjon az esetleges változásokkal kapcsolatban, mivel azok kötelező érvényűek Önre nézve. </p>
<p> Fenntartjuk a jogot, hogy a Weboldalt és a Bővítményt, a Weboldalon és a Bővítményben nyújtott bármely szolgáltatást vagy anyagot saját belátásunk szerint, előzetes értesítés nélkül visszavonjuk vagy módosítsuk. Nem garantáljuk, hogy webhelyünk, bővítményünk vagy annak tartalma mindig elérhető lesz, vagy nem lesz megszakítás. Nem vállalunk felelősséget, ha bármilyen okból a Szolgáltatás egésze vagy egy része bármikor vagy bármely időszakban nem érhető el. Időnként korlátozhatjuk a Weboldal vagy a Bővítés bizonyos részeinek vagy a teljes Szolgáltatásnak a felhasználók számára való hozzáférését. </p>
<p> Ön felelős minden szükséges intézkedés meghozataláért, hogy biztosítsa a Szolgáltatáshoz való hozzáférését. Biztosítani kell, hogy minden olyan személy, aki az Ön internetkapcsolatán keresztül ér el a Szolgáltatást, tisztában legyen a Felhasználási feltételekkel, és betartsa azokat. A Szolgáltatáshoz vagy az általa kínált néhány erőforráshoz való hozzáféréshez megkérhetik Önt, hogy adjon meg bizonyos információkat vagy egyéb adatokat. Ön beleegyezik abba, hogy a Szolgáltatáson keresztül vagy más módon, ideértve, de nem kizárólagosan a Szolgáltatás bármely interaktív funkciójának használatát is, biztosított minden információt az <a href="/privacy"> Adatvédelmi irányelvek </a> szabályozza, és Ön beleegyezik a az Önnel kapcsolatos összes intézkedést az <a href="/privacy"> Adatvédelmi irányelvek </a> szerint teszünk. </p>
<p> Különösen óvatosnak kell lennie, amikor személyes adatokat ad meg a Szolgáltatásba egy nyilvános vagy megosztott számítógépen, hogy mások ne láthassák vagy rögzíthessék személyes adatait. A weboldal, a bővítmény és annak minden tartalma, funkciója és funkciója (beleértve, de nem kizárólag, minden információt, a bővítményt, szöveget, képeket, képeket és kurzorokat, valamint azok tervezését, kiválasztását és elhelyezését) a "Cursor Style", annak engedélyeseinek vagy az ilyen anyagok más beszállítóinak tulajdonát képezik. Ezek a szerzői jog, a védjegyek, a szabadalmak, a kereskedelmi titkok és egyéb szellemi tulajdonra vonatkozó törvények vagy tulajdonjogok védelme alatt állnak. </p>
<p> Ezek a Felhasználási feltételek lehetővé teszik, hogy a Weboldalakat csak személyes, nem kereskedelmi célokra használja. Tilos reprodukálni, terjeszteni, módosítani, származékos műveket létrehozni, újra közzétenni, letölteni, tárolni vagy továbbítani a Weboldalunkon található anyagokat, kivéve a következő eseteket: használhatja személyes igényeinek, kinyomtathatja vagy letöltheti a Weboldal és a Bővítmény ésszerű mennyiségű oldalát vagy tartalmukat, személyes, nem kereskedelmi használatra, nem pedig a további reprodukcióra, közzétételre vagy terjesztésre. </p>
<p> Nem módosíthatja az oldalról vagy a bővítményről származó anyagok másolatait és azok tartalmát. Törölni vagy módosítani kell az ezen az oldalon és a bővítményen lévő szerzői jogra, védjegyre vagy egyéb tulajdonjogi közleményekre vonatkozó információkat. A Weboldalakhoz vagy bővítményekhez, valamint a Weboldalon vagy a Bővítményben elérhető szolgáltatásokhoz vagy anyagokhoz nem férhet hozzá, és nem használhatja azokat kereskedelmi célokra. </p>
<p> Ha a Weboldalakon vagy a Bővítményeken található anyagokat szeretné más módon felhasználni, mint ebben a szakaszban, küldjön kérelmet a Chrome Web Store támogatási oldalára. </p>
<p> Ha nyomtatja, másolja, módosítja, letölti vagy más módon használja, vagy más személynek biztosít a Weboldal vagy a Bővítmény bármely részéhez hozzáférést a Felhasználási feltételek megsértésével, akkor a Weboldal és a Bővítmény használatára való joga azonnal megszűnik, és Önnek a mi belátásunk szerint vissza kell adnia vagy meg kell semmisítenie az Ön által birtokolt anyagok másolatait. A bővítmény weboldalának olyan használata, amelyet a jelen Felhasználási feltételek kifejezetten nem engedélyeznek, a Felhasználási feltételek megsértését jelenti, és szerzői jogokat, védjegyeket és egyéb törvényeket sérthet. </p>
<p> A "Cursor Style" név, a "Cursor Style" logó és az összes kapcsolódó név, logó, kép, kurzor és szolgáltatásnév, formatervezés és szlogen a "Cursor Style" vagy leányvállalatainak vagy licencbeadóinak védjegyei. Nem használhatja az ilyen jeleket a Szolgáltató előzetes írásbeli engedélye nélkül. A weboldalon és a bővítményben szereplő összes többi név, logó, termék- és szolgáltatásnév, formatervezés és szlogen a megfelelő tulajdonosok védjegye. A Szolgáltatást csak legális célokra és a jelen Felhasználási feltételeknek megfelelően használhatja. </p>
<h3> Ön EGYETÉRT AZZAL, HOGY NEM HASZNÁLJA A SZOLGÁLTATÁST: </h3>
<ul>
<li> Bármilyen módon, amely megsérti a hatályos szövetségi, regionális, helyi vagy nemzetközi törvényeket vagy rendeleteket (beleértve, de nem kizárólag, az adatok vagy a szoftver Oroszországba és más országokba történő exportjára vonatkozó törvényeket). </li>
<li> Kiskorúak kizsákmányolása, kártétele, vagy kísérletek a kiskorúak kihasználására vagy károsítására, nem megfelelő tartalomnak kitéve őket, azonosító információkat kérve tőlük vagy más módon. </li>
<li> Küldésre, szándékos fogadásra, letöltésre, használatra vagy újra felhasználásra minden olyan anyagot, amely nem felel meg a Felhasználási feltételeknek. </li>
<li> Minden hirdetés vagy promóciós anyag küldése vagy megvásárlása előzetes írásbeli hozzájárulásunk nélkül, beleértve a "kéretlen leveleket", "láncleveleket" vagy a "spam"-et, vagy bármilyen más hasonló ajánlatot. </li>
<li> A "Cursor Style" alkalmazottjának, egy másik felhasználónak vagy bármely más személynek vagy szervezetnek (ideértve, de nem kizárólagosan a fentihez kapcsolódó e-mail címeket vagy álneveket) a megszemélyesítése vagy megkísérlése. </li>
<li> Minden egyéb olyan cselekményben való részvétel, amely korlátozza vagy akadályozza a Szolgáltatás vagy bárki más használatát, vagy amely, amint mi megállapítjuk, károsíthatja a Szolgáltatást vagy a Szolgáltatás felhasználóit, vagy felelőssé teheti őket. </li> </ul>
<h3> Ezenkívül Ön EGYETÉRT AZZAL, HOGY NEM: </h3>
<ul>
<li> A Szolgáltatást semmilyen olyan módon nem használja, amely letilthatja, túlterhelheti, károsíthatja vagy rontja az oldal működését, bővítheti vagy zavarhatja a Szolgáltatás más felek általi használatát, beleértve a valós idejű műveletekben való részvételi képességüket a Szolgáltatáson keresztül. </li>
<li> A Szolgáltatáshoz való hozzáféréshez, a Szolgáltatás bármely anyagának megfigyeléséhez vagy másolásához semmilyen automatizálási eszközt, folyamatot vagy eszközt nem használ. </li>
<li> Semmilyen manuális eljárást ne használjon a Szolgáltatásban lévő anyagok nyomon követéséhez vagy másolásához, vagy bármilyen más jogosulatlan célra, előzetes írásbeli hozzájárulásunk nélkül. </li>
<li> Ne használjon semmilyen olyan eszközt, szoftvert vagy eljárást, amely zavarja a Szolgáltatás normális működését. </li>
<li> Ne vezessen be vírusokat, trójaiakat, férgeket, logikai bombákat vagy egyéb olyan anyagokat, amelyek károsak vagy technológiailag károsak. </li>
<li> Ne kíséreljen meg jogosulatlan hozzáférést szerezni, beavatkozni, károsítani vagy megzavarni a Szolgáltatás bármely részét, a kiszolgálót, amelyen a Szolgáltatás tárolva van, vagy a Szolgáltatáshoz csatlakoztatott, bármely kiszolgálót, számítógépet vagy adatbázist. </li>
<li> Ne támadja meg a Szolgáltatást a szolgáltatás megtagadásának támadásával vagy a szolgáltatás terjesztett tagadásának támadásával. </li> </ul>
<p> A Szolgáltatáson vagy azon keresztül megadott információk kizárólag általános tájékoztatási célokat szolgálnak. Nem garantáljuk ezen információk pontosságát, teljességét vagy hasznosságát. Kizárólag a saját kockázatára támaszkodik az ilyen információkra. Elhárítunk minden felelősséget, amely az ilyen anyagok Ön általi, a Szolgáltatás más látogatói vagy bárki más általi függéséből ered, akiket tájékoztatni lehetett a tartalmukról. </p>
<p> Ez a Szolgáltatás harmadik felek által biztosított tartalmat tartalmaz, ideértve a más felhasználók és a harmadik fél engedélyezőinek, szindikátorainak, gyűjtőinek és / vagy jelentési szolgáltatásainak nyújtott anyagokat. Az ezekben az anyagokban kifejezett összes állítás és / vagy vélemény, valamint az összes cikk és a kérdésekre adott válaszok és egyéb tartalom, a Szolgáltató által biztosított tartalom kivételével, kizárólag a Szolgáltatót biztosító személy vagy szervezet véleménye és felelőssége. Ezek az anyagok nem feltétlenül tükrözik a Szolgáltató nézeteit. Nem vagyunk felelősek Önnel vagy harmadik féllel szemben a harmadik felek által biztosított anyagok tartalmáért vagy pontosságáért. </p>
<p> Időről időre frissíthetjük a Szolgáltatás tartalmát, de tartalma nem feltétlenül teljes vagy aktuális. A Szolgáltatásban szereplő bármely anyag bármikor elavult lehet, és nem vagyunk kötelesek az ilyen anyagokat frissíteni. Saját döntésünk szerint frissíthetjük, módosíthatjuk, módosíthatjuk a Weboldalon és a Bővítményben található információkat és tartalmakat, bármilyen változtatást és frissítést végezhetünk. </p>
<p> A Szolgáltatáson összegyűjtött összes információra vonatkoznak az Adatvédelmi Szabályzatunk. A Szolgáltatás használatával Ön beleegyezik az összes, az információival kapcsolatban általunk tett intézkedésbe az <a href="/privacy"> Adatvédelmi Szabályzat </a> szerint. </p>
<p> A Szolgáltatás bizonyos részeire, szolgáltatásaira vagy funkcióira kiegészítő feltételek is vonatkozhatnak. Az összes ilyen kiegészítő feltétel jelen hivatkozással beépül a Felhasználási feltételekbe.
A weboldalunkra vagy a bővítményünkre akkor mutathat, ha ezt tisztességes és törvényes módon teszi, és nem sérti hírnevünket, vagy nem használja azt, de nem szabad a linket oly módon beállítani, hogy a mi részünkről semmilyen formában kapcsolatot, jóváhagyást vagy támogatást ajánljon fel írásbeli engedélyünk nélkül. </p>
<p> A Szolgáltatás harmadik felek által biztosított más webhelyekre és forrásokra mutató linkeket tartalmaz, ezeket a linkeket csak a kényelme érdekében biztosítjuk. Ez magában foglalja a hirdetésekben, ideértve a banner hirdetéseket és a szponzorált linkeket is. Nem ellenőrizzük ezeknek az oldalaknak vagy forrásoknak a tartalmát, és nem vagyunk felelősek azokért, vagy azok használatából eredő veszteségekért vagy károkért. Ha úgy dönt, hogy hozzáfér a Szolgáltatáshoz kapcsolódó, harmadik félhez tartozó webhelyekhez, akkor ezt a saját felelősségére és az ilyen webhelyek felhasználási feltételeinek megfelelően teszi. Fenntartjuk a jogot, hogy előzetes értesítés nélkül visszavonjuk a csatlakozási engedélyt. </p>
<p> Ön megérti, hogy nem tudunk és nem garantálhatjuk, hogy az interneten vagy a weboldalakon keresztül letölthető fájlok nem tartalmaznak vírusokat vagy más rosszindulatú kódot. Ön felelős az eljárások végrehajtásáért és az elegendő ellenőrzési pontokért, hogy megfeleljen az Ön különleges követelményeinek a vírusvédelmi és az adatok bevitele és kimenete pontosságának, valamint az elveszett adatok helyreállítására szolgáló, a webhelyünktől független eszközök fenntartásáért. NEM FELELÜNK SEMMILYEN KÁROSODÁSOKÉRT VAGY SÉRÜLÉSEKÉRT, AMELYEKET A SZOLGÁLTATÁSON KERESZTÜL SZERZETT SZOLGÁLTATÁS MEGTILTA, VÍRUSOK VAGY MÁS TECHNOLÓGIAI KÁROSÍTÁSOK, VAGY BÁRMILYEN ANYAG WEBHEZ TÖRTÉNŐ LETÖLTÉSÉVEL, VAGY BÁRMILYEN HONLAP, AMELYEKET AZ ÖN SZÁMÍTÓGÉPES BERENDEZÉSEIT, SZÁMÍTÁSGÉPES SZOFTVEREIT, ADATAIT MEGREMET. </p>
<p> ÖN A SZOLGÁLTATÁST, ANNAK TARTALMÁT ÉS A SZOLGÁLTATÁSOKON KERESZTÜL KAPOTT BÁRMELY SZOLGÁLTATÁSÁT VAGY TÉTELÉT KIZÁRÓLAG SAJÁT KOCKÁZATÁRA HASZNÁLJA. A SZOLGÁLTATÁST, ANNAK TARTALMÁT ÉS A WEBOLDALON ÉS A BŐVÍTMÉNYBEN KERESZTÜL NYÚJTOTT SZOLGÁLTATÁSOKAT VAGY TÉTELEKET “AHOGY VAN” ÉS “AHOGY RENDELKEZÉSRE ÁLL” FELTÉTELEKKEL NYÚJTJUK, GARANCIA NÉLKÜL. A SZOLGÁLTATÁSSAL KAPCSOLATOS SEMMILYEN SZEMÉLY NEM BIZTOSÍT GARANCIÁT VAGY NYILATKOZATOT A SZOLGÁLTATÁS TELJESSÉGÉRE, BIZTONSÁGÁRA, MEGBÍZHATÓSÁGÁRA, MINŐSÉGÉRE, PONTOSSÁGÁVAL VAGY ELÉRHETŐSÉGÉRE VONATKOZÓAN. A FENTI KORLÁTOZÁS NÉLKÜL A "CURSOR STYLE" VAGY A "CURSOR STYLE" KAPCSOLÓDÓ KÉPVISELŐI NEM GARANTÁLJÁK, HOGY AZ OLDAL, A BŐVÍTMÉNY, ANNAK TARTALMA VAGY BÁRMELY JAVÍTÁSA ELÉRHETŐ LESZ BEFEJEZETT, HOGY A BŐVÍTMÉNYÜNKET, A WEBHEZ VAGY A KISZOLGÁLÓHOZ, AMELYEKET HELYEZ, VÍRUSOK VAGY EGYÉB KÁROS ALKATRÉSZEK NÉLKÜL LEHET, VAGY EZ A WEBHELY VAGY BÁRMELY SZOLGÁLTATÁS VAGY TÉTEL VÉGREHAJTÁSA, ELŐNYÖS.
<p> A SZOLGÁLTATÓ, ANNAK PARTNEREI VAGY LICENCADÓI, SZOLGÁLTATÓI, ALKALMAZOTTAI, ÜGYNÖKEI, TISZTVISELŐI VAGY IGAZGATÓI SEMMILYEN KÖRÜLMÉNYEK KÖZÖTT NEM FELELŐSEK SEMMILYEN KÁROKÉRT, SZOLGÁLTATÁST SEMMILYEN FELELŐSÉGÉRT. VAGY EGYÉB WEBOLDAL VAGY A SZOLGÁLATOS SZOLGÁLTATÁSBAN VAGY TÉTELEKBEN, A SZOLGÁLTATÁSBAN VAGY MÁS WEBHELYEKEN, BELEÉRTVE A KÖZVETLEN, KÜLÖNLEGES VAGY KÖVETKEZŐ KÁROKAT, BELEÉRTVE A SZEMÉLYI SÉRÜLÉST, ÉRZELMI ZAVAROKAT, KÁR VAGY VÁRTMEGTAKARÍTÁSOK, HASZNÁLAT VESZTÉSE, ADATOK VAGY EGYÉB FELTÉTELEK. A MEGHATÁROZÁS NEM ÉRINTI SEMMILYEN OLYAN FELELŐSSÉGET, AMELYET A JOGSZABÁLYOK SZERINT NEM LEHET KIZÁRNI VAGY KORLÁTOZNI, MELY TARTALMAZHATJA A CSLÁST. </p>
<p> Ön vállalja, hogy megvédi, kártalanítja és megvédi a "Cursor Style", leányvállalatait, engedélyezőit és szolgáltatóit, valamint tisztségviselőit, igazgatóit, alkalmazottait, vállalkozóit, ügynökeit, engedélyezőit, szállítóit, megbízottjait minden követelésből és kötelezettségből, a bírósági határozatokból eredő veszteségből, a költségekből, a kiadásokból vagy jutalékokból (beleértve az ügyvédi díjakat) a Felhasználási feltételek vagy a Szolgáltatás megsértéséből vagy a Szolgáltatás használatából eredően, ideértve, de nem kizárólagosan a weboldal tartalmának, a szolgáltatásoknak és a termékeknek a felhasználását, a Bővítmények, kivéve a Felhasználási feltételekben kifejezetten kikötött módon, vagy a Szolgáltatásból kapott információ felhasználásában. </p>
<p> Ha a jelen Felhasználási feltételek bármely rendelkezését bármely illetékes joghatóság bírósága vagy más bírósága érvénytelennek, jogellenesnek vagy nem érvényesíthetőnek ítéli, akkor az ilyen  elrendelést meg kell semmisíteni vagy minimálisra kell korlátozni, hogy a Felhasználási feltételek többi rendelkezése a lehető legteljesebb mértékben folytatódhasson. A Felhasználási feltételek, az Adatvédelmi irányelveink és az események regisztrálására vonatkozó feltételek képezik az Ön és a "Cursor Style" közötti teljes és egyező megállapodást a Szolgáltatásra vonatkozóan, és felülírják a Szolgáltatással kapcsolatos összes korábbi és egyidejű megállapodást, megállapodást, nyilatkozatot és garanciát, írásban és szóban egyaránt. </p>
<p> A Szolgáltatással kapcsolatos összes véleményt, megjegyzést, technikai támogatási kérést és egyéb üzenetet a "Cursor Style" támogatási oldalára kell irányítani a Chrome Web Áruházban. </p> ',
];
