<?php

return [
    'halo_descr' => 'Halo on Bungien luoma taistelufantasia-mediasarja. Perustuu alkuperäiseen ensimmäisen persoonan ammuntapeli -trilogiaan. Juoni keskittyy tapahtumiin, jotka tapahtuvat Master Chiefin, yhden super-sotilaiden ryhmän, koodinimeltään Spartanit, ja hänen kumppaninsa, tekoäly Cortanan, elämässä. Pelien menestys on johtanut sarjan laajenemiseen muuhun mediaan: Halo-universumi kattaa tällä hetkellä monia kirjoja, graafisia romaaneja, sarjakuvia, lyhyitä elokuvia, animaatioita ja elokuvia.',
    'halo_short_descr' => 'Kosketa artefakti osoitinta, kenties sinä olet valittu',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'LOL Surprise -nuket rakastuivat lapsiin ja valloittivat heidän sydämensä ensimmäisestä minuutista lähtien. Eikä tämä ole yllättävää, sillä tällainen menestys perustuu mysteeriin, ihmeen odotukseen, miellyttävään yllätykseen, joka ilahduttaa paitsi lapsia, myös heidän vanhempiaan. Lahjan salaisuus paljastetaan lapselle vasta viimeisen purkamisen jälkeen. Joka tapauksessa LOL-nuket ovat houkutteleva muotoilu, juonittelu, suuri määrä hämmästyttäviä ja realistisia lisävarusteita ja miellyttäviä pieniä asioita sekä lelun korkein laatu ja yksityiskohtaisuus.',
    'lol_surprise_short_descr' => 'Hienoja söpöläisiä kauniiden yllätysten ystäville',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Sarja pyörii kilpailun ympärillä, jossa 456 pelaajaa, jotka kaikki ovat syvässä taloudellisessa velassa, riskeeraavat henkensä pelatakseen sarjan tappavia lasten pelejä saadakseen mahdollisuuden voittaa miljardin palkinnon. Sisällä odottaa houkutteleva palkinto tappavilla panoksilla. Sarjan nimi tulee samannimisestä korealaisesta lasten pelistä. Hwang oli saanut idean omien taloudellisten vaikeuksien pohjalta elämänsä varhaisessa vaiheessa sekä luokkaeroista Etelä-Koreassa ja kapitalismista.',
    'squid_game_short_descr' => 'Valitse oikea pelaajan naama, kun pelaat all-in',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter on brittiläisen kirjailijan J. K. Rowlingin romaanisarjan päähenkilö. Yhdestoista syntymäpäivänään Harry saa tietää olevansa velho ja että hänen kohtalonsa on päästä Tylypahkan Velhokouluun, jossa hän harjoittaa taikuutta rehtori Albus Dumbledoren ja muiden koulun professorien ohjauksessa. Harry saa myös tietää, että hänet tunnetaan jo romaanin taikamaailmassa ja että hänen kohtalonsa on yhteydessä Voldemortin, vaarallisen pimeän taikurin kohtaloon.',
    'harry_potter_short_descr' => 'Mitä teet Harry Potter -kursoreiden kokoelman taikasauvalla?',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics on sarjakuvien julkaisija, joka tunnetaan merkittävien supersankareiden, kuten Hämähäkkimiehen, Iron Manin, Kapteeni Amerikan, Hulkin, Thorin, Kostajien, Galaksin Vartijoiden, X-Menin, Ihmenelosien ja Deadpoolin, luomisesta. Marvelin tunnetuimpiin roistoihin kuuluvat Vihreä Menninkäinen, Punakallo, Loki, Thanos, Ultron, Tohtori Tuho ja Magneto. Marvel Comics ja DC Comics ovat tehneet yhteistyötä useissa crossover-projekteissa ja perustivat myös yhdessä tarkoituksellisesti lyhytikäisen Amalgam Comics -painatuksen.',
    'marvel_comics_short_descr' => 'Supersankari asuu meissä jokaisessa - valitse omasi',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Tervetuloa takaisin Keksivaltakuntaan Cookie Run: Kingdomissa, jonka on tehnyt Devsisters, ihastuttava strateginen roolipeli, joka sijoittuu Cookie Run -universumiin. Nyt kun Inkiväärirohkea on paennut ilkeän noidan uunista, on aika hänen rakentaa Keksien joukkue ja lähteä matkalle rakentamaan uudelleen sortunut Keksivaltakunta. Paljasta totuus valtakunnan tuhosta ja kokoa joukkue valtakunnan mahtavimmista Kekseistä voittamaan pimeät voimat, jotka haluavat estää Inkiväärirohkeaa täyttämästä kohtaloaan.',
    'cookie_run_kingdom_short_descr' => 'Pieniä sotureita suoraan uunista',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact on avoimen maailman seikkailupeli. Tämä tarkoittaa, että uusi, ihastuttava maisema odottaa sinua joen tai vuoren toisella puolella, sinun tarvitsee vain käyttää energiaasi viisaasti. Jos kohtaat vaeltavan keijun tai omituisen mekanismin, uskalla ja yritä selvittää heidän mysteerinsä. Mutta mitä he lupaavat - vaikeuksia vai miellyttävän yllätyksen - vain sinä voit selvittää! Teyvatin laajalla mantereella vierailet seitsemässä valtakunnassa, löydät kumppaneita erilaisilla taidoilla ja taistelet voimakkaita vihollisia vastaan kadonneen rakkaasi etsinnässä.',
    'genshin_impact_short_descr' => 'Ryhdy seitsemän valtakunnan Elementtien Mestariksi',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Kun muinainen ennustus toteutuu ja valtakunta vajoaa talven syleilyyn, kolme pelotonta sankaria - prinsessa Anna, urhea Kristoff ja hänen uskollinen poronsa Sven - lähtevät vuorille etsimään Annan siskoa Elsaa, joka voi poistaa jäätävän loitsun maasta. Matkan varrella heitä odottaa monia vaikeita yllätyksiä ja jännittäviä seikkailuja. Tapaaminen mystisten peikkojen, ihastuttavan lumiukko Olafin tapaaminen, Everestin jyrkemmät vuorenhuiput ja paljon taikaa. Sankarit joutuvat vastustamaan mahtavia elementtejä pelastaakseen valtakunnan ja ne, jotka ovat heille rakkaita.',
    'frozen_short_descr' => 'Jään murskaaminen on helppoa Frozen-kursorikokoelmalla',
    'frozen' => 'Frozen',
    'stranger_things_descr' => 'On kulunut hieman yli kuusi kuukautta kolmannen kauden finaalista. Joyce, Will, Eleven ja Jonathan ovat muuttaneet Kaliforniaan, jossa tyttöä kiusataan koulussa. Loput alkavat taistella uutta hirviötä vastaan ​​rinnakkaismaailmasta, joka on ilmestynyt Hawkinsiin. Hänet nimettiin Vecnaksi Dungeons & Dragons -lautapelihahmon mukaan. Se vaikuttaa teini-ikäisiin psykologisesti, sitten tunkeutuu päähän ja tappaa. Samalla Joyce ja Murray saavat tietää, että Jim Hopper on elossa ja lähtevät hänen peräänsä neuvostoliittolaiseen vankilaan Kamtšatkaan. Ja Elevenin on palattava ja lisättävä voimiaan, mutta myös opittava tärkeä roolinsa saman hirviön luomisessa Gokinsissa.

Kirjoittajat eivät muuttaneet juonitaktiikkaa, josta he pitivät viime kausina. Neljännellä kaudella he jakoivat suuren päähenkilöiden ryhmän ryhmiin, keksivät heille vaikeita tehtäviä ja lopuksi rakensivat tarinansa yhteen upeassa lopussa. Tarjoamme sinulle mahdollisuuden ymmärtää kaikki nämä seikkailut yksityiskohtaisesti Stranger Things -kursori -kokoelman avulla.',
    'stranger_things_short_descr' => 'Mitä seuraavaksi tapahtuu? - Stranger Things 4 -kursoreita',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars on alkuperäinen pelitila, joka ilmestyi ensimmäisen kerran Minecraftissa. Pelaajien tehtävänä oli suojata tukikohtaansa ja sänkyään.

Roblox tuo lisää jännittäviä pelejä joka päivä, eikä BedWars ole poikkeus. Ja juttu on, että jos rakastat sotasänkyjä ja puolustat itseäsi huoneessasi, tämä on juuri sinulle sopiva peli, koska se vie sinut takaisin lapsuuteen, tosin digitaalisesti tällä kertaa.

Sinun tarvitsee vain puolustaa sänkyäsi hyökkääjiltä kumppanisi kanssa. Astut aulaan, valitset kenen kanssa pelaat, ja voila, kyse on vain suojelusta.

Toki, kun on kyse puolustuksesta, sinulla on joitain ongelmia ja on tiettyjä resursseja, esineitä ja tavaroita, jotka auttavat sinua voittamaan. Esimerkiksi eksklusiivisia skinejä, jotka löydät Bed Wars -kursorikokoelmasta.',
    'roblox_bed_wars_short_descr' => 'Suojaa sänkysi Roblox Bed Wars -kursoreilla',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'Naruto Uzumakin syntymäpäivänä legendaarinen demoni, Yhdeksänhäntäinen Kettu, hyökkäsi Konoha-nimiseen kylään. Neljäs Hokage pelasti kylän ja uhrasi henkensä sinetöimällä demonin vastasyntyneeseen Narutoon, tietämättään tuomiten hänet vihan elämään kyläläistensä taholta.
Huolimatta lahjakkuuden puutteesta monilla ninjutsu-aloilla, levottomuudesta ja ylimielisyydestä, Narutolla on unelma tulla Hokageksi, kylän vahvimmaksi ninjaksi. Haluten tunnustusta, jota hän ei saanut, hän työskentelee kovasti ja harjoittelee yhdessä joukkuetovereidensa Sasuke Uchiha ja Sakura Haruno kanssa sekä mentorinsa Kakashi Hataken kanssa. Hänen ja kumppaneidensa on käytävä läpi paljon matkalla kohti vaalittuja unelmiaan: taisteluita, rakkautta, ystävyyttä, petosta, vallanhimoa. Naruto-animen kursorien kokoelma auttaa sinua navigoimaan omalla polullasi!',
    'naruto_anime_short_descr' => 'Kulje ninja-polkuasi Naruto-animen kursoreilla',
    'naruto_anime' => 'Naruto-anime',
    'demon_slayer_anime_short_descr' => 'Demon Slayer -kursoreita, todellisille yön metsästäjille',
    'demon_slayer_anime' => 'Demon Slayer anime',
    'bts_descr' => 'BTS on seitsemänjäseninen poikabändi, joka on BigHit Musicin alaisuudessa. He debytoivat 13. kesäkuuta 2013 singlellä "No More Dream". Japanissa he debytoivat 24. joulukuuta 2014 studioalbumilla Wake Up.

Ryhmän nimi tulee korealaisesta ilmaisusta Bangtan Sonyeondan, joka tarkoittaa "luodinkestäviä poikalastaulaisia". J-Hopen mukaan nimi merkitsee yhtyeen halua estää ennakkoluulot, kritiikki ja odotukset, jotka kohdistuvat teini-ikäisiin kuin luodit.

Ryhmälle omistettu kursori-kokoelma sisältää kaikki ryhmän jäsenet, tässä Kim Nam Joon -kursori (alias RM), Kim Seok Jin -kursori (Jin), Min Yoongi -kursori (Suga), Jung Ho Suk -kursori (J-Hope), Park Ji Min -kursori (Jimin), Kim Tae Hyun -kursori (V) ja Jeon Jungkook -kursori (Jungkook).',
    'bts_short_descr' => 'Tapaa idolisi BTS-kursoreilla.',
    'bts' => 'BTS',
    'miraculous_descr' => 'Miraculous: Tales of Ladybug and Cat Noir, paremmin tunnettu nimellä Miraculous Ladybug and Cat Noir, on seikkailu supersankareista piirrossarjassa kahdesta luokkatoverista, jotka naamioiden alla näyttelevät Pariisin puolustajia konnalta, joka jokaisessa jaksossa keksii uuden tavan vahingoittaa kaupunkia. Miraculous on tehty Ranskassa CGI:tä ja animaatiota käyttäen. Miraculous ei ole vain animaatiosarja, vaan myös kokoelma sarjakuvia, joita on julkaistu ympäri maailmaa. Sarja on hyvin rakastettu nuoren yleisön keskuudessa.

Toiminta tapahtuu Pariisissa, jossa Marinette ja Adrian ovat lukion opiskelijoita modernissa koulussa. Heille on annettu tehtävä tulla valituiksi taistelussa pahaa vastaan, pelastaen kotikaupunkinsa. Heidän tavoitteenaan on suojella ihmisiä Akumilta. Nämä pienet perhosen muotoiset olennot pystyvät asuttamaan ihmisen ja muuttamaan hänet konnaksi.

Marinette voi muuttua ladybugiksi ja Adrian - Cat Noiriksi, mutta yllättäen, työskennellessään pareittain, he eivät tunnista toisiaan supersankarien naamioiden alla.

Auta Cat Noiria ja Ladybugia pelastamaan Pariisi kursoreillamme, joissa on suosikkihahmosi. Minkä hahmon valitset kursoriksi? Onko se Miraculous Ladybug -kursori, vai ehkä Tikki\'s suloinen pieni Ladybug tai Cat Noir -kursori? Tai ehkä Queen Bee Rena Rouge -kursoreilla? Valinta on sinun!',
    'miraculous_short_descr' => 'Liity supersankareiden joukkoon Lady Bug- ja Cat Noir- kursoreiden kokoelmalla',
    'miraculous' => 'Miraculous: Tales of Ladybug & Cat Noir',
    'talking_tom_descr' => 'Sarja seuraa Talking Tomin ja hänen ystäviensä jokapäiväistä elämää. Tom ja hänen nörttimäinen liikekumppaninsa Ben kehittävät jatkuvasti mobiilisovelluksia ja muita keksintöjä saavuttaakseen mainetta ja vaurautta ja yrittävät näyttää itsensä maailmalle, mutta tämä kääntyy aina itseään vastaan. Tomin tyttöystävä Angela yrittää olla laulaja, teki hän mitä tahansa sen saavuttamiseksi. Tomin naapuri Ginger piipahtaa hyvin usein täällä tekemässä kepposia ilkikurisena. Tyhmä paras ystävä ja kämppis Hank on kotona oleva, KATSOO ERITTÄIN TV:tä. Ja entinen toisinajattelija poptähti Becca Sparkles on tullut Angelan uudeksi kämppikseksi ja näyttää rakastuneen Hankiin. Kuitenkaan riippumatta siitä, kuinka huonosti asiat ovat kaikissa muodoissa ja koossa, olipa kyseessä paha CEO, Tomin salaperäinen uusi naapuri tai vain vahinko Benin uudessa luomuksessa, jengi pitää hauskaa riippumatta siitä, ja muistaa aina yhden asian, joka pitää heidät yhdessä: ystävyys ei koskaan pääty, aivan kuten rakkautemme sarjan hahmoja kohtaan ei pääty, joten nyt voit asettaa itsellesi Talking Tom -kursoriin tai Ben-kursoriin tai ehkä Angela-kursoriin, Oliver-kursoriin!',
    'talking_tom_short_descr' => 'Puhutaanpa suosikkihahmostasi Talking Tom Cursor -kokoelmassa',
    'talking_tom' => 'Talking Tom and Friends',
    'lego_descr' => 'LEGO Group -yritys perustettiin vuonna 1932 ja silloin siinä oli vain 7 ihmistä. Legon tiimin tavoitteena oli luoda leluja, jotka kehittävät lapsen luovuutta, mielikuvitusta ja kekseliäisyyttä. Hämmästyttävä tosiasia, että LEGO-elementit kaikissa muunnelmissaan ovat olleet yhteensopivia keskenään vuodesta 1949 lähtien. Kaikki myöhemmin luodut esineet ovat edelleen yhteensopivia nykyään julkaistavien esineiden kanssa, huolimatta suunnittelun ja muodon muutoksista vuosien varrella.

LEGO-tiili on pohja, joka on ontto muovipalikka, joka kiinnittyy muihin samankaltaisiin tiiliin. Mutta LEGO-sarjat sisältävät myös muita osia, pyöriä, figuureja, alustoja ja jopa elektroniikkapiirejä antureilla ja sähkömoottoreilla. Voit kerätä malleja autoista, lentokoneista, junista, laivoista, rakennuksista, roboteista. LEGO noudattaa modulariteetin ajatusta, joka osoittaa selvästi lapsille kuinka ratkaista tiettyjä ongelmia, kehittää mielikuvitusta, käsien hienomotorisia taitoja ja kokoonpanotaitoja. LEGO-tiilet valmistetaan uskomattomalla tarkkuudella ja ne sopivat täydellisesti yhteen upeaan 10 mikronin tarkkuuteen.

Viime aikoina on luotu monia suosittuja 3D-animoituja Lego-tarinoita, joissa sarjojen hahmot heräävät henkiin ja tulevat uskomattomien seikkailujen osallistujiksi. Jos haluat hienon kursorin, löydät monia hahmoja Lego-tv-sarjoista ja animaatioelokuvista Lego Cursors -kokoelmastamme. Lego Ninjago Cursor, Lego Batman Cursor, Lego Ninjago Cursor, Lego Wyldstyle Cursor ja monia muita.',
    'lego_short_descr' => 'Rakenna unelma selaimesi Lego-kursoreilla',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Onnistuneen Kickstarter-rahoituksen jälkeen Team Cherry julkaisi vuonna 2017 monialustaisen PC-pelin Hollow Knight. Tämä on tarina nimetömästä ritarista ja hänen löydöistään Hallownestin hyönteiskunnassa. Peli tunnustettiin ansaitusti yhdeksi parhaista metroidvania-genressä.

Hollow Knightin pelattavuus perustuu pelimaailman tutkimiseen. Esteiden voittaminen, pulmien ratkaiseminen ja salaisuuksien löytäminen sekä vihollisten taisteleminen. Pelaajalla on ainutlaatuinen joukko parannuksia ja temppuja maailman tutkimiseen ja taisteluihin. Liikkuessaan vyöhykkeeltä toiselle pelaaja voittaa pomoja ja saa tarvittavat parannukset edetäkseen pidemmälle. Tämän seurauksena pelaajien täytyy vierailla jo läpäistyillä alueilla löytääkseen salaisuuksia ja käydäkseen läpi tarinan. Ja se on myös jännittävää, koska vyöhykkeet muuttuvat joka kerta tuoden uusia yllätyksiä ja kokemuksia. Peliä voi pelata eri tavoilla, koska vyöhykkeiden välillä on useita eri polkuja. Tarinan läpäisemisen jälkeen avaat vyöhykekartan, mutta ensin sinun on hankittava kartta.

Sankarin pääase on naula, joka on jossain määrin samanlainen kuin miekka. Aseita voi parantaa sepällä, ja aseiden käytössä voi oppia erilaisia taitoja, mikä laajentaa hyökkäysten monimuotoisuutta. Hyökkäämällä vihollisia vastaan keräät erityistä resurssia, jota voidaan myöhemmin käyttää parannuksiin tai parantumiseen.
Hauskaa Hollow Knightin pelaamista ja älä unohda Hollow Knight -kursoreitamme suosikkihahmosi kanssa. Kokoelmamme sisältää Mister Mushroom -kursorin, Quirrel-kursorin, Hornet Needle -kursorin, Old Nail -kursorin, Myla-kursorin ja muita.',
    'hollow-knight_short_descr' => 'Yritä olla eksymättä hyönteisten valtakuntaan käyttämällä Hollow Knight -kursorikokoelmaa.',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman on sarjan päähenkilö. Aiemmin nimeämätön Stikmin aloitti pikkurikollisena, haluten tehdä helposti nopeasti rahaa. Kuitenkin päästyään pakoon West Mesa -vankilasta, tapahtuu monia muutoksia hänen elämässään, ja hänestä tulee kuuluisa rikollinen varastettuaan Tunisian timantin. Henryllä on valinta - ryhtyä menestyväksi hallituksen agentiksi, palkkionmetsästäjäksi, rikollisjärjestön johtajaksi, kyborgiksi tai jatkaa rikollisen polkua yksin. Peli ilahduttaa genren faneja monilla seikkailuilla ja mysteereillä, ja löydät uuden Henry Stickman -kursoreiden kokoelmamme sen hauskoilla hahmoilla, mukaan lukien Henry Stickmin -kursori, Charles Calvin -kursori, Reginald Copperbottom -kursori, Right Hand -kursori, Ellie Rose -kursori ja muut!',
    'henry-stickmin_short_descr' => 'Suunnittele pakosi tylsyyttä Henry Stickman -kokoelmalla kursoreita',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'Erittäin suosittu verkkopeli Adopt Me julkaistiin vuonna 2017 ja siitä tuli suosituin Roblox-pelialustalla. Pelin ydin on hyvin yksinkertainen - hanki munia lemmikkieläinten kanssa ja pidä niistä huolta.

Virtuaaliset lemmikit on jaettu 5 luokkaan, joista jotkut ovat hyvin harvinaisia ja kalliita, kun taas toiset on hyvin helppo saada. Nämä ovat epätavallisia ryhmiä, kuten Blue Dog, yleinen, harvinainen kohdistin, esimerkiksi Adopt Me Monkey -hiiren kohdistin, sekä erittäin harvinaisia, kuten Koala-kohdistin, ja legendaarisia, Dragon-kohdistin ja Accept me -yksisarvinen. Jos pelaajalla on neljä saman tyyppistä aikuista lemmikkieläintä, he voivat yhdistää ne neon-lemmikiksi, kuten Neon Horse -pelikohdistimeksi tai Adopt Me Neon Starfishiksi. Yhdistämällä neljä tavallista lemmikkiä voit tehdä neon-lemmikin, joka todella loistaa, ja neon-lemmikeistä voit luoda mega-neon-lemmikin.

Ostokset pelissä Adopt Me! suoritetaan virtuaalisella valuutalla Roblox - niin sanotulla Robuxilla, ja pelissä on myös oma valuuttansa - Bucks. Huolehtimalla lemmikistäsi voit viihteen lisäksi ansaita buckseja, vain ruoki hänet, laita hänet nukkumaan tai lue satu, yleensä paljon mielenkiintoisia asioita.

Nyt Roblox-pelin "Adopt Me!" fanit voivat koristella pelin kohdistimensa suosikkilemmikillään!',
    'adopt-me_short_descr' => 'Pidä hauskaa söpöjen lemmikkien kanssa Adopt Me! -pelikursorien kokoelmassamme',
    'adopt-me' => 'Adopt Me!',
    'among-us_descr' => 'Among Us perustuu kuuluisaan roolipeliin "Mafia". Oli suunniteltu, että peli olisi yksinoikeudella mobiililaitteille, koska siinä oli vain yksi kartta. Pelistä tuli nopeasti suosittu. Myöhemmin kehitystiimi lisäsi moninpelitilan, ja kaksi lisäkarttaa julkaistiin vuonna 2019.
Among Us on ylhäältä kuvattu kolmannen persoonan peli, jonka avulla pelaaja voi liikkua kaikkiin suuntiin. Yhdessä kierroksessa voi pelata neljästä kymmeneen pelaajaa. Pelin alussa kaikille on salaa annettu petturin tai miehistön jäsenen rooli. Huijari (venäjän käännöksessä "Petturi") voi piiloutua ilmanvaihtoluukkuun, sabotoida ja tappaa miehistön jäseniä. Hänen tavoitteenaan on tuhota kaikki miehistön jäsenet tai tuhota avaruusalus sabotaasilla. Laivan miehistön tavoitteena on ratkaista erilaisia heille pelin alussa valmistettuja pulmia. Jos jokainen miehistön jäsen suorittaa kaikki tehtävät, pettäjät häviävät. Myös laivan miehistö voi saavuttaa voiton poistamalla petturit äänestyksen aikana.
Petturit voivat aika ajoin sabotoida, ja jos vikoja ei korjata 30 sekunnissa, miehistö häviää. Ennen pelin aloittamista voit valita pelaamasi hahmon värin, sininen, punainen, keltainen, harmaa - ihan mitä vaan! Ja älä unohda asettaa itsellesi sopivaa osoitinta uudesta Among Us -kokoelmasta!',
    'among-us_short_descr' => 'Älä anna hämätä itseäsi tässä mutkikkaassa avaruuspelissä Among Us -kursoreilla',
    'among-us' => 'Among Us',
    'steven_universe_descr' => '"Steven Universe" -sarjan luoja oli Rebecca Sugar. Hänet tunnetaan aiemmasta työstään nimeltä Adventure Time. Steven Universe -sarjan ensimmäinen jakso julkaistiin YouTube-videopalvelussa keväällä 2013. Mutta syksyllä amerikkalainen Cartoon Network -kanava alkoi lähettää sitä katsojilleen. Siitä lähtien on julkaistu 6 tuotantokautta. Kuudes lupaa olla viimeinen.
Sarjan juoni pyörii Crystal Gems -ryhmän ympärillä. Se koostuu muukalaisolennoista, joilla on luonteenomaiset nimet: Helmet, Amethyst ja Granaatti. Mutta Mukana on vielä yksi osallistuja, tavallisen pojan Stephenin roolissa. Yhdessä he etsivät hirviöitä ja yrittävät neutraloida ne, jotta ne eivät valloittaisi Maata omaksi hyödykseen. Heitä vastaan taistelevat Jasper ja Peridot - lähettiläitä kotimaastaan, jotka haluavat voittaa Gemsit ja käynnistää Clusterin.
Jos olet Steven Universe -fani ja haluat nähdä animaatiosarjan hahmot missä vain, asenna Cursor Style -laajennus! Miksi tämä? Voit lisätä "Steven Universe" -kokoelman ja muuttaa tavallisen hiiren osoittimen yhdeksi suosikkihahmoistasi.',
    'steven_universe_short_descr' => 'Paljasta timanttien salaisuus Steven Universen kursoreilla',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Animoitu komediasarja "Family Guy" on koko olemassaolonsa aikana voittanut Emmy-palkinnon 4 kertaa ja "Annie"-palkinnon 3 kertaa. Animaatiosarja pilkkaa amerikkalaisen yhteiskunnan kipeitä aiheita, kuten: feminismiä, orjuutta, liikalihavuutta, politiikkaa jne. Toisin kuin muissa teoksissa, täällä käytetään vitsejä ja sarkasmia. Lisäksi monissa tapauksissa ne eivät ole integroituneet juoneen, vaan ne ovat olemassa omillaan.
Yksi jakso animoitua sarjaa luodaan yli 10 kuukaudessa. Miksi niin kauan? Koska koko animaatio piirretään käsin. Tämän vuoksi joillakin teoksen käsittelemillä tapahtumilla on aikaa menettää merkityksensä. Mutta silti komediasarja pysyy erittäin mielenkiintoisena ja saa katsojien suosion ympäri maailmaa. Kuka ei loppujen lopuksi tykkäisi nauraa hyvin poliitikoille, julkkiksille tai ihmisille, jotka tekevät villejä temppuja ja yllättävät tai jopa järkyttävät tavallisia ihmisiä.
Tykkäätkö "Family Guysta"? Sinulla on ainutlaatuinen mahdollisuus muuttaa normaali hiiren kursori miksi tahansa tämän animaatiosarjan hahmoksi! Mitä minun tarvitsee tehdä? Asenna vain “Cursor Style” -selainlaajennus, lisää siihen “Family Guy” -kokoelma ja nauti satumaisesta jälleensyntymästä!',
    'family_guy_short_descr' => 'Family Guy -kursoreiden kokoelma huumorin ystäville',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Olet varmasti kuullut sanonnan "Kauneus pelastaa maailman"? Niinpä monet ihmiset, erityisesti tytöt, ovat samaa mieltä tästä väitteestä. Siksi he pyrkivät ympäröimään itsensä kaikella kauneimmalla ja silmää hivelevimmällä. Se voi olla vaaleanpunainen tapetti makuuhuoneessa, pehmoleluja, helmillä kirjailtuja tyynyjä, arvokkaita koruja jne. Ulkoapäin se kaikki näyttää hyvin söpöltä ja jopa vähän lapselliselta. Mutta jokainen meistä on pieni lapsi sydämessämme, joten miksi emme antaisi hänen näyttää mielikuvituksemme?
Hellyys voi aiheuttaa meissä paljon. Esimerkiksi myötätuntoiset kissanpennun silmät, jotka haluavat tulla silittäviksi tai ruokituksi. Monivärinen sateenkaari, joka kurkistaa esiin kevät-sateen jälkeen ja kimmeltää kaikilla väreillään auringossa. Lapsi, jolle tarjottiin suklaata, ja hän päätti jakaa sen tyttö- tai poikaystävänsä kanssa. Koskettavia syitä on melko paljon, ja päätimme käyttää niitä kursoreina.
Oletko kyllästynyt tylsään valkoiseen nuoleen selaimessasi? Korvaa se jollain söpöllä kokoelmastamme! Esimerkiksi vaaleanpunainen ja valkoinen yksisarvinen, surullinen tomaatti, mietteliäs pilvi, piikikäs kaktus kissan muodossa tai mitä tahansa muuta haluat. Sinun tarvitsee vain asentaa Cursor Style -laajennus ja lisätä siihen kokoelma söpöjä kursoreita. Ja pitkä elämä maailman pelastajalle - kauneudelle!',
    'cute_cursors_short_descr' => 'Maailma on ystävällisempi söpöjen kursoreiden kokoelmalla',
    'cute_cursors' => 'Söpöt kursorit',
    'web_media_descr' => 'Nykypäivän todellisuudessa lähes kaikki käyttävät Internetiä. Alkuen taaperoista ja päättyen eläkeläisiin. Joku surffaa käyttäen selainta, toinen katsoo videoita YouTubessa ja joku tarvitsee verkkoa kommunikoidakseen rakkaiden kanssa. Kukaan näistä käyttäjistä ei voi kuvitella päivää ilman World Wide Webiä.
Vanhemmat ihmiset istuvat usein sosiaalisessa verkostossa kuten Facebook tai VK. He kommunikoivat usein myös lastensa ja lastenlastensa kanssa Skypessä. Tämä on erityisen kätevää, jos lapset ja vanhemmat asuvat eri kaupungeissa tai jopa maissa.
Nuoret ihmiset mieluummin kommunikoivat Viberin tai Telegramin kautta, lataavat valokuvia Instagramiin, nauravat FB-meemeille. YouTube-videot ihmisten reaktioista keräävät miljoonia katselukertoja, aivan kuten erilaiset pilat tai sosiaaliset kokeet. Tik-Tokissa sadat tuhannet ihmiset tanssivat, näyttävät taikatemppuja ja ilmaisevat itseään.
Oletko kiinnostunut tai käytätkö usein jonkinlaista resurssia verkkoympäristöstä? Haluatko päästä eroon tylsästä hiiren osoittimesta selaimessasi? Asenna silloin laajennus ja vaihda oletusosoitin luovaksemme! Se voi olla YouTube-osoitin, Viber-osoitin, Google Chrome -osoitin tai muita resursseja.',
    'web_media_short_descr' => 'Elä modernissa rytmissä web-media kursoreiden kokoelmalla',
    'web_media' => 'Web Media',
    'bobs_burgers_descr' => 'Animaatiosarja Bob\'s Burgers on animaatiotyön juoni ja hahmojen karisma. Ja päätellen Emmy-palkintoehdokkuudesta ja työn tunnustamisesta yhdeksi maailman parhaista sarjakuvista, Bob\'s Snack teki todella vaikutuksen.
Animaatiosarjan juoni pyörii Bob Belcherin perheen ympärillä. Tämä henkilö on ravintolan omistaja ensimmäisessä kerroksessa, ja toisessa kerroksessa hän asuu rakkaittensa kanssa. Bobilla on iloinen vaimo Linda ja 3 lasta: Gene, Louise ja Tina. Poika haaveilee musiikkiurasta, vanhin tytär Tina on hyvin ystävällinen, mutta kömpelö, ja nuorin - Louise on edelleen rettelöitsijä ja saattaa usein perheensä epämukavaan asemaan. Bob’s Burgersin pääkilpailija on Jimmy Peston pizzeria. Kuten ehkä arvaat, tämän pizzerian omistajan nimi on Jim, ja hän ja Bob vihaavat toisiaan. Kaikki tämä on lyöty niin, että se näyttää koomiselta, ei vakavalta. Siksi monet heidän yhteenotoistaan aiheuttavat vain hymyn.
Jos rakastat animaatiosarjaa “Bob\'s Burgers” ja haluat nähdä sen hahmot paitsi näytöllä tai televisiossa, asenna laajennus, lisää kokoelma ja vaihda selaimen hiiren kohdistin johonkin tämän sarjakuvan hahmoon!',
    'bobs_burgers_short_descr' => 'Bob tekee burgereita, ja me teemme Bob\'s Burgers -kursoreita',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'Videopelin "Kirbyn" historia alkoi jo viime vuosisadan 90-luvulla. Se koostuu monista sarjoista, jotka Nintendo ja HAL Laboratory kehittivät. Peli on tarkoitettu lapsille puolestatoista 8 vuoteen. Sen suosiota voidaan arvioida myytyjen kopioiden määrän perusteella. Yli 34 miljoonaa maailmanlaajuisesti.
Kirbyn päänäyttelijä on samanniminen vaaleanpunainen olento. Se asuu Pop Star -nimisellä planeetalla ja suojelee sitä toistuvasti erilaisilta vaaroilta. Kerby voi hengittää joitain esineitä ja vihollisiaan oppiakseen sitten heidän kykyjään: lähitaistelu, miekan hallinta, tulen hengitys jne. Vaaleanpunainen pallo ei kuitenkaan vain taistele vihollisia vastaan, vaan ratkaisee myös erilaisia ​​pulmia, matkustaa muihin maihin ja voi jopa lentää tasolla.
Tätä videopeliä voi pelata Nintendo- tai Game Boy -konsoleilla. Kaikissa sarjoissa on söpöjä sankareita, hyvä grafiikka ja hauskoja ääniraitoja. Muuten, lähes 30 vuoden aikana ensimmäisen version julkaisusta maailma on nähnyt 20 Kirby-sarjaa. Tämä indikaattori yhdessä miljoonien dollarien kopioiden myynnin volyymin kanssa auttoi peliä pääsemään peliteollisuuden 50 menestyneimmän ja halutuimman videopelin joukkoon.
Rakastatko Kirbyä niin, että haluaisit nähdä tämän hahmon kaikkialla? Käytä sitten Kirby-kokoelmaa ja muuta tavallinen hiiren osoitin suosikkivideopelisi päähahmoksi! Olemme varmoja, että pidät kursorin uudesta ulkoasusta.',
    'kirby_short_descr' => 'Yritä imeä koko Kirby-kursori kokoelma',
    'kirby' => 'Kirby',
    'undertale_descr' => 'Muinaisina aikoina maapallolla asui ihmisten lisäksi myös hirviöitä. Heidän välisistä erimielisyyksistä johtuen puhkesi sota, joka päättyi ihmiskunnan eduksi. Seitsemän taikuria ajoivat hirviöt maan alle ja vangitsivat heidät sinne ikuisesti muuriloitsulla. Mount Ebottiin oli kuitenkin vain yksi sisäänkäynti, jota lapsi käytti hyväkseen. Häntä varten pelaat Undertale-tietokonepeliä.
Tämän pelin kehitti Toby Fox - tunnettu ohjelmoija Yhdysvalloista. Aluksi siitä pystyivät nauttimaan Microsoft Windows- ja Linux-käyttöjärjestelmiä käyttävien henkilökohtaisten tietokoneiden omistajat, ja sitten vuoro tuli pelikonsoleiden käyttäjille.
Mikä on tämän pelin pointti? Poika matkustaa alamaailmassa, jossa asuu hirviöitä. Jotkut heistä ovat heti vihamielisiä, kun taas toiset pitävät puhumisesta. Pelaaja voi valita yhden kahdesta käyttäytymistavasta: välttää väkivaltaa tai taistella. Ensimmäisessä tapauksessa pelin läpäisy on helpompaa, toisessa - päinvastoin vaikeampaa. Myös juoni ja lopetus, jotka voivat haarautua ja muuttua, riippuvat tästä valinnasta.
Jos pidät Underground Talesta ja haluat nähdä sen hahmot selaimessasi, asenna laajennus ja lisää sopiva kursorikokoelma! Muuta tylsä hiiren osoitin yhdeksi hirviöistä tai Undertalen päähenkilöksi!',
    'undertale_short_descr' => 'On aika päästä pois kuopasta käyttämällä Undertale-kursoreita',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune on roolipeli, joka julkaistiin tietokoneille muutama vuosi sitten. Sen loi sama ohjelmoija, joka kehitti Undertalen. Nämä kaksi peliä eivät kuitenkaan ole juuri lainkaan samanlaisia, vaikka niillä onkin muutama yhteinen hahmo ja sijainti.
Deltarunessa on useita päähenkilöitä. He ovat opiskelija Chris, jota voidaan ohjata, ja hurmaava hirviö Susie, jota ei voi ohjata. Molemmat hahmot putoavat pimeyden maailmaan, jossa he tapaavat yhden sen asukkaista - Ralsayn. Hän kertoo heille, että he ovatkin valo-olentoja, joilla on tehtävä - pysäyttää pimeän energian virtaus synkässä maailmassa. Tätä varten heidän on säästettävä paikallisia hirviöitä ja yritettävä olla käymättä taisteluun heidän kanssaan, vaikka tämä on joskus melko vaikeaa.
Pelaajalla on yksinkertainen valinta: joko säästää pimeät olennot tai hyökätä heidän kimppuunsa. Koska Susie ei ole puolivillaisen kannattaja, hän valitsee monissa tapauksissa taistelun. Siksi Chrisillä ei ole muuta vaihtoehtoa kuin tukea tyttöystäväänsä ja auttaa häntä taisteluissa.
Rakastatko Deltarune-peliä? Muokkaa sitten hiiren osoitin selaimessasi jollekin sen hahmoista! Voit tehdä tämän laajennuksemme avulla. Asenna se, lisää "Rune Delta" -kokoelma ja aktivoi! Nyt nuolesi ei ole enää samanlainen kuin kaikki muut, vaan siitä on tullut Chris, Susie tai yksi pimeän maailman olennoista.',
    'deltarune_short_descr' => 'Sukella pimeään maailmaan tällä kursori kokoelmalla',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario on Nintendon julkaisema tietokonepelisarja. Ensimmäinen ja suosituin peli oli nimeltään Super Mario Bros. Se näki päivänvalon vuonna 1985. Myöhemmin se listattiin Guinnessin ennätysten kirjaan. Siitä lähtien on julkaistu yli 20 peliä, joista jokaisella on oma juonensa. Vuonna 2019 ilmestyi uusi versio nimeltä Super Mario Maker 2. Huolimatta grafiikan parantumisesta, tyyli ja hahmot pysyivät samoina, mikä herättää nostalgiaa 80-luvun Super Mariolle.
Päähenkilö on edelleen putkimies Mario. Pelin viimeisimmässä versiossa Prinsessan linnaa ei jätetty kiveä kääntämättä. Marion täytyy rakentaa se uudelleen ansaitsemalla ensin kolikot, jotka hänelle maksetaan tehtävistä. Yhteensä tässä pelissä on yli 100 eritasoista kenttää, joita voi muokata. Myös Super Mario Maker 2:ssa on uusia pelimuotoja. Voit pelata neljää niistä kerralla, ja heti kun yksi päättyy, taso katsotaan suoritetuksi. On myös sellaisia ​​tiloja kuin: Mario Marathon, Duel ja Ninjik-kilpailut.
Rakastatko Super Mariota ja kaikkea tähän ihanaan peliin liittyvää? Aseta sitten tämän tasohyppelyn tyyliin tehdyt kursori! Olemme varmoja, että pidät Mario-kursorista, Luigi-kursorista, Prinsessa Peach -kursorista ja muista kokoelmassamme esitellyistä kursoreista!',
    'super_mario_short_descr' => 'Kulje sienivaltakunnan läpi Super Mario -kursori kokoelmalla.',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Fallsin loi yhdessä Disney Television Animation Corporation ja Alex Hirsch. Ensi-ilta oli vuonna 2012, ja se esitettiin Disney Channel -kanavalla. Koko animaatiosarjan ensimmäinen kausi pyöri siellä. Kaksi vuotta myöhemmin julkaistiin toinen kausi, jota katsojat saattoivat katsoa edellisellä kanavalla ja Disney XD:llä. Valitettavasti Gravity Fallsin fanit eivät odottaneet kolmatta ja seuraavia kausia. Luojat päättivät rajoittua kahteen kauteen ilman jatko-osia.
Mitkä ovat tämän animaation juonenkäänteet, niin kaikki toiminta tapahtuu kuvitteellisessa kaupungissa nimeltä Gravity Falls. Sinne saapuu kaksi kaksosta, joiden nimet ovat Mabel ja Dipper. He asuvat serkkunsa Stanin luona. Hänellä on oma turisti- ja matkamuistomyymälä. Kun veljillä on tylsää "ei mitään tekemistä", he lähtevät seikkailun etsintään. Yksi heistä löytää metsästä oudon päiväkirjan, joka kertoo tämän kaupungin poikkeavuuksista. Kaksoset lähtevät etsimään sen kirjoittajaa ja kohtaavat epätavallisia olentoja ja paikkoja. Jos olet kiinnostunut tästä animaatiosarjasta ja olit joskus sen hahmojen fani, suosittelemme hiirikursoriemme kokoelmaamme Gravity Fallsin tyyliin!',
    'gravity_falls_short_descr' => 'Lähde seikkailulle Gravity Falls -kursoreilla',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Aivan kaikki ovat kuulleet niin kuuluisasta animaatiosarjasta kuin Simpsonit. Jopa ne ihmiset, jotka eivät ole koskaan katsoneet sitä, ovat tietoisia keltaisten hahmojen olemassaolosta. Ja fanit ovat iloissaan, kun heidän suosikkisarjansa seuraava tuotantokausi ilmestyy. Muuten, syksyllä 2019 julkaistiin 31 tuotantokausi. Ja ensimmäinen ilmestyi televisiossa jo vuonna 1989. Fox alkoi näyttää sitä ja jatkaa sitä edelleen korkeiden arvosanojen ja yleisön sympatien vuoksi.
Simpsonit on satiirinen genre, joka käsittelee ajankohtaisia aiheita. Tämä voi olla tavallisen amerikkalaisen elämäntapa, poliittiset ja uskonnolliset kysymykset, julkkisten "tähtijutut", feminismi, samaa sukupuolta olevien avioliitot. Yleisesti ottaen kaikki, mikä liittyy paikallisiin ja maailmanlaajuisiin tapahtumiin, joihin Yhdysvallat osallistuu.
Animaatiosarjan toiminta tapahtuu kuvitteellisessa Springfieldin kaupungissa. Itse asiassa Amerikassa on paljon kaupunkeja, joilla on tuo nimi. Ehkä siksi se valittiin, jotta yleisö ei yhdistäisi ruuduilla tapahtuvaa tiettyyn paikkakuntaan, vaan vain arvaistaisi, missä tämä voisi olla.
Olet luultavasti Simpsonien fani. Muuten, miksi lukisit tämän tekstin loppuun? Ja jos olet, sinulla on mahdollisuus vaihtaa tylsä hiiren kohdistin osoittimeen, joka on tehty tämän animaatiosarjan tyyliin.',
    'simpsons_short_descr' => 'Hauska pieni perhe, pääosassa Simpsonit -kursori',
    'simpsons' => 'The Simpsons',
    'youtubers_descr' => 'YouTube-videopalvelu ilmestyi vuonna 2005. Aluksi videoita julkaistiin siellä vain itsensä ilmaisun vuoksi tai tiedottamaan jostakin. Kuitenkin ajan myötä kaikki tämä kasvoi kannattavaksi liiketoiminnaksi, joka tuo tuhansia ja joskus miljoonia dollareita kuukaudessa menestyneille YouTube-käyttäjille. Mitä suositumpi vloggaaja (henkilö, joka pitää videoblogia), sitä enemmän hän voi ansaita kanavansa kautta.
Kuinka paljon viisivuotias vloggaajatytön ansaitsee, jonka vanhemmat vievät hänet mielenkiintoisimpiin nähtävyyksiin ja kuvaavat kameralla tapahtuvaa? Se on vain sitä, miten lapsi pitää hauskaa lasten puistoissa, mikä ilmaisee tunteita, miten pelleillä ja kaikkea sellaista. Summa on todella hämmästyttävä - tänään lapsikanavalla on lähes 47 miljoonaa tilaajaa ja se on alkanut tuottaa tuloja 5 miljoonan ruplan verran kuukaudessa.
Joku lataa videoita, joissa hän keskustelee tietokonepeleistä, joku tekee beatboxingia tai järjestää kepposia ohikulkijoille kadulla. Jotkut omistavat videoinsa arkaluonteisille aiheille, kuten miesten ja naisten välisille suhteille. Mitä enemmän YouTube-käyttäjät pitävät näistä otoksista, sitä suurempi on vloggaajan suosio.
Kokoelmaan on jo lisätty PewDiePie-kursori, Shane Dawson -kursori, Ray William Johnson -kursori, Zoella-kursori, MyLifeAsEva-kursori ja muut.',
    'youtubers_short_descr' => 'Uusi tähtisukupolvi on aina verkossa YouTubers-kokoelmassamme',
    'youtubers' => 'YouTubettajat',
    'pusheen_descr' => 'Melkein kaikki tuntevat Pusheen-kissan. Vaikka se on vain 10 vuotta sitten keksityn lasten sarjakuvan hahmo, sillä on nykyään miljoonia faneja. Pusheen-kissa ilmestyi taiteilija Claire Beltonin luomana kuvituksena.
Vuotta myöhemmin kissa sai oman sivunsa Tumblr.comissa ja sai muutamassa viikossa kokonaisen fanijoukon - noin 10 000 ihmistä. Vuonna 2013 Facebook halusi sisällyttää kuvia Pusheenista kokoelmiin muiden hymiöiden kanssa. Neuvottelujen jälkeen luojan kanssa tämä idea toteutettiin ja se "räjäytti" Internetin! Kuvat Pusheen-kissasta ovat käytössä kirjeenvaihdossa yli 10 miljoonaa kertaa päivässä!
Vuonna 2014 yksi Yhdysvaltojen suurimmista leluvalmistajista kiinnitti huomionsa tähän hahmoon. GUND (se keksi nallekarhut) julkaisi parin Pusheen-mallia. Koska menestys oli valtava, muutaman kuukauden jälkeen luotiin täydellinen lelukokoelma tämän kissan muodossa.
Missä muualla voit tavata Pusheen-kissan? Isaac Morris Ltd:n lahjaseteissä, Boomfin vaahtokarkeissa ja tietenkin Pusheen-kursoreiden kokoelmassamme!',
    'pusheen_short_descr' => 'Lisää mukavuutta selaimeesi Pusheen-kursorialbumilla',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'Ensimmäinen animaatiosarja "Rick and Morty" julkaistiin vuonna 2013. Tämän piirrossarjan voi suoraan liittää kahteen genreen: scifiin ja komediaan. Sen luojat olivat Dan Harmon ja Justin Royland. Aluksi kaikki sarjat esitettiin Cartoon Network -kanavalla, ja vasta sitten ne monistettiin online-elokuvateattereissa ja videoalustoilla. Muutaman vuoden välein julkaistaan uusia Rick and Morty -kausia, ja marraskuussa 2019 ilmestyi neljäs kausi, joka osoittautui yhtä mielenkiintoiseksi kuin edellisetkin. Animaatiosarjan juoni pyörii nerokkaan ja samalla hullun tiedemiehen Rickin sekä hänen huomiota herättämättömän pojanpoikansa Mortyn ympärillä. Näitä kahta hahmoa yhdistävät yhteiset seikkailut mitä epätavallisemmissa paikoissa. Ja he pääsevät sinne lentävällä lautasella, joka pystyy liikkumaan inter-avaruustunneleissa. Kuten olet ehkä arvannut, tämä animaatiosarja muistuttaa hieman elokuvaa Takaisin tulevaisuuteen, mutta se ei kuitenkaan ole sen animoitu versio. Monet kriitikot kuitenkin ylistivät sitä humoristisista jaksoista, luovuudesta ja omaperäisyydestä. Haluatko nähdä Rickin tai Mortyn sarjan lisäksi myös selaimessasi? Jos haluat, asenna laajennus ja lisää kokoelmamme suosikkipiirrossarjaasi! Tässä on Rick Sanchezin kohdistin, Morty Smithin kohdistin, Portal Gunin kohdistin ja tietysti Mr. Meeseeksin kohdistin.',
    'rick_and_morty_short_descr' => 'Lopeta valittaminen, käytä vain Rick and Morty -kokoelman kursoreita',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Baseball-fanit löytyvät kaikkialta maailmasta. Tämä pätee erityisesti maiden, kuten USA:n, Kiinan, Kuuban, Etelä-Korean, Japanin ja Venezuelan asukkaisiin. Toisin kuin yleisesti uskotaan, baseball ei ole peräisin Amerikasta, vaan Englannista. Ensimmäinen maininta ja kuvaus baseballista ilmestyi vuonna 1744 englanninkielisessä painoksessa. 145 vuoden jälkeen amerikkalaiset omivat tämän keksinnön itselleen, huolimatta tosiasioista.
National League perustettiin vuonna 1876. Se on osa Major League -liigaa Kanadassa ja Yhdysvalloissa. Nykyään National Baseball League -liigassa on 15 joukkuetta. Jokaisen kauden viimeisellä osuudella tulee pudotuspelien aika, johon osallistuu 4 parasta joukkuetta. Siten selviää koko National Leaguen voittaja. Sitten voittajajoukkue saa mahdollisuuden pelata American Leaguen voittajaa vastaan World Series -pelissä.
Oletko kiinnostunut baseballista tai kannustatko jopa jotakin joukkuetta? Osoita sitten kunniaa suosikkijoukkueellesi asettamalla hiiren kursori sen ominaisuuksien muodossa! Muuta selaimen tylsä osoittimen ilme tutuksi baseball-tunnukseksi! Muuta nuoli pelaajan mailaksi tai kypäräksi missä tahansa National League -joukkueessa, joihin kuuluvat jo New York Yankees -kursori, Great Falls Dodgers -kursori, Boston Red Sox -kursori, Baltimore Orioles -kursori, Oakland Athletics -kursori.',
    'mlb_teams_short_descr' => 'MLB Teams -kursorikokoelma kaikille faneillemme.',
    'mlb_teams' => 'MLB Teams',
    'brawl_stars_descr' => 'Brawl Stars on Supercellin mobiilipeli MOBA-genrestä. Huolimatta julkaisusta vuoden 2018 lopussa, peli saavutti suurta suosiota, pääasiassa taistelutilojen runsauden ja värikkäiden, fantastisten sankareiden - riitelijöiden - ansiosta. Pelaajalla on runsaasti valinnanvaraa - 32 ainutlaatuista hahmoa ja jokaisella heistä on omat kykynsä ja taitonsa. Jokaisella sankarilla on myös oma passiivinen taitonsa, joka on saatavilla saalisarkkujen kautta. Pelaajat voivat taistella useissa tiloissa, esimerkiksi "Palkinto kaappauksesta" - yksi kahdesta joukkueesta voittaa, joka on kerännyt enemmän tähtiä tappamalla vastustajia. "Ryöstö"-tilassa on välttämätöntä rikkoa vastustajien tallelokeroita pitäen samalla huolta omista. Mielenkiintoinen "Jalokivien kaappaus" -tila - joukkueesta tulee voittaja, joukkue joka kerää eniten jalokiviä voittaa. No, "Kohtaamis"-tilassa 10 pelaajaa taistelee keskenään kartalla, jossa rajat pienenevät myrkyllisen pilven vuoksi. Peli on täynnä värikästä suunnittelua, josta monella ihmisellä on pitänyt, mukaan lukien meillä, mikä innoitti meitä luomaan erillisen Brawl Stars -kursoreiden kokoelman. On olemassa Brawl Stars Shelley -kursori, Barley -kursori, Penny -kursori, Frank -kursori, Mortis -kursori ja muita.',
    'brawl_stars_short_descr' => 'Valitse Brawl Stars -kursoreita ja anna taistelun alkaa',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Vaihda hiiren osoitintasi kahdella klikkauksella! Ilmaisia kokoelmia jokaiseen makuun.',
    'all_descr' => 'Jos olet koskaan miettinyt, kuinka muuttaa tylsää hiiren osoitinta, niin kursorikokoelmamme ovat juuri sinua varten! Täältä löydät hienoja sarjakuvien sankareita, kauniita kursoreita pelaajille suosittujen pelien hahmoilla, hauskoja kursorisettejä kepposille, värikursoreita ja monia muita mielenkiintoisia vaihtoehtoja.',
    'text_title' => 'Hienoja ja hauskimpia kursori kokoelmia joka päivälle',
    'text_allcat_title' => 'Ainutlaatuisia ja luovia hiiren kursoreita jokaiseen mielialaasi',
    'text_1' => 'Etkö halua olla kuin kaikki muut? Tai rakastatko vain kaikkea epätavallista? Haluatko olla osa suosikkipelisi sankaria tai sarjakuvahahmoa? Silloin olet tullut oikeaan osoitteeseen. Täältä löydät kirkkaita, epätavallisia kursoreita, jotka voivat korvata tutun ja jo aika tylsän valkoisen nuolen. Hiiren kursori seuraa meitä koko päivän työssä ja opiskelussa, joten sen pitäisi antaa hieno tunnelma ja virittää positiiviseen.',
    'text_2' => 'Täältä löydät kursoreita pelaajille ja elokuvien ystäville, kauniita kursoreita suosikkisarjakuvien pohjalta ja urheilumotiiveja aktiivisimmille ihmisille. Pidätkö sarjakuvista tai et voi kuvitella yhtäkään päivää ilman hauskoja meemejä? Rakastatko eläimiä tai unelmoitko vierailla kaikissa maailman maissa? Kaikki on yksinkertaista - meillä on sopiva kursori-kuva myös sinulle. Voit myös valita kuvia sen mukaan, minkä kanssa työskentelet. Esimerkiksi musta kursori on paljon kätevämpi kuin valkoinen asiakirjojen tai piirrosten parissa työskennellessä, ja käsi-kursori on kätevämpi, jos sinun on työskenneltävä pienien graafisten elementtien kanssa. Valitse suosikkikuvasi, säädä sen koko suoraan laajennuksessa - ja käytä sitä mielihyvin, joka päivä positiivisella asenteella!',
    'install_to_preview' => 'Asenna laajennus, jotta voit esikatsella',
    'install' => 'Asenna',
    'add_button' => 'Lisää',
    'preview_button' => 'Esikatsele',
    'added_button' => 'Lisätty',
    'add_cursor' => 'Lisää kohdistin',
    'to_your_collection' => 'kokoelmaasi',
    'prev_text_1' => 'Koko näytön esikatselu',
    'prev_text_2' => 'kohdistin',
    'cursor' => 'kohdistin',
    'pointer' => 'osoitin',
    'a_title_1' => 'Cursor Style - Hienoja kursoreita selaimellesi',
    'a_title_2' => 'Hienoja kokoelmia temaattisia kursoreita',
    'mouse_cursors' => 'hiirikursoreita',
    'cursor_collection' => 'Kursorikokoelma',
    'sborka_cursorov' => 'kursorikokoelma',
    'collection_list_from_colllection' => 'Luettelo kursoreista - ',
    'christmas' => 'Joulu',
    'nhl_teams' => 'National Hockey League',
    'neon' => 'Neon',
    'adventure_time' => 'Adventure Time',
    'nba_teams' => 'National Basketball Association',
    'spongebob' => 'Paavo Pesusieni',
    'phineas_and_ferb' => 'Fineas ja Ferb',
    'fortnite_chapter_2' => 'Fortnite Chapter 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Julkkikset',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Sarjakuvat',
    'igry' => 'Pelit',
    'multfilmy' => 'Sarjakuvat',
    'kino_i_serialy' => 'Elokuvat',
    'anime' => 'Anime',
    'futbol' => 'Jalkapallo',
    'avtomobili' => 'Autot',
    'memy' => 'Meemit',
    'emodji' => 'Emoji',
    'pitomcy' => 'Lemmikit',
    'stil_i_krasota' => 'Muoti ja tyyli',
    'prazdniki' => 'Juhlat',
    'flagi' => 'Liput',
    'vokrug_sveta' => 'Maailman ympäri',
    'eda_i_napitki' => 'Ruoka ja juomat',
    'cvetnye' => 'Värilliset',
    'prank' => 'Pilat',
    'startovyj_nabor' => 'Aloituspakkaus',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Joulupukki rakastaa joulukursoreitasi',
    'nhl_teams_short_descr' => 'NHL kursoreiden kokoelma todellisille faneille',
    'neon_short_descr' => 'Lisää kirkkautta neon-kokoelmalla',
    'adventure_time_short_descr' => 'Matematiikan opiskelua Adventure Time -kursoreiden kokoelmalla',
    'nba_teams_short_descr' => 'NBA-kursorit suuren koripallovoiton symbolina',
    'spongebob_short_descr' => 'Selvitä kuka asuu merenpohjassa Spongebob-kursorikokoelmalla',
    'phineas_and_ferb_short_descr' => 'Et varmasti kyllästy Phineas ja Ferb -kursori kokoelman kanssa',
    'fortnite_chapter_2_short_descr' => 'Fortnite -kulttipelin uusi luku',
    'pokemon_short_descr' => 'Pyydystä ne kaikki jos pystyt',
    'famous_people_short_descr' => 'Inspiroi idolihiiren osoittimellasi',
    'the_elder_scrools_short_descr' => 'Uppou ritarien ja lohikäärmeiden maailmaan',
    'halloween_short_descr' => 'Älä pelkää missata uutta Halloween-kokoelmaa',
    'nfl_teams_short_descr' => 'Oikeille jalkapallofaneille',
    'five_nights_at_freddy_short_descr' => 'Yritä olla säikähtämättä näitä animatroneja',
    'komiksy_short_descr' => 'Kursorit sarjakuvista: valitse mieliala tänään.',
    'igry_short_descr' => 'Virtuaalitodellisuus: ketä pelaat tänään?',
    'multfilmy_short_descr' => 'Suosikkisarjakuvahahmot uudessa designissa',
    'kino_i_serialy_short_descr' => 'Kursoriherra: Työpöydän veljeskunta',
    'anime_short_descr' => 'Kaikki rakastavat animea: kuka on sinun suosikkihahmosi?',
    'futbol_short_descr' => 'Oletko todellinen urheilufani? Silloin sinun täytyy olla täällä',
    'avtomobili_short_descr' => 'Unelmiesi auto: suuri laivasto ammattilaisille',
    'memy_short_descr' => 'Suosikkiaiheet: Meemikursorien kokoelma',
    'emodji_short_descr' => 'Näytä todellinen mielialasi muille - aseta Cursoji!',
    'pitomcy_short_descr' => 'Kirkkaat kursorit kaikille pienempien veljiemme ystäville',
    'stil_i_krasota_short_descr' => 'Alkuperäiset kursorit kaikkiin tilanteisiin',
    'prazdniki_short_descr' => 'Mitä kalenterissa on? Uusia Juhlat Osoittimet -kokoelma!',
    'flagi_short_descr' => 'Etsitkö seikkailua: minne menemme tänään?',
    'vokrug_sveta_short_descr' => 'Ympäri maailman hetkessä: minne olemme menossa tänään?',
    'eda_i_napitki_short_descr' => 'Suussa sulavat kursoriit luovuuteen',
    'cvetnye_short_descr' => 'Maalaa elämäsi kirkkailla väreillä ja rohkeilla vedoilla',
    'prank_short_descr' => 'Kursorisarja hauskimpia kepposia varten.',
    'startovyj_nabor_short_descr' => 'Uusi näkemys tutuista asioista: päivitetty kursorisarja.',
    'fortnite_short_descr' => 'Seuraa striimaajia!',
    'dota_2_short_descr' => 'Tee virtuaalimaailmastasi todellinen!',
    'minecraft_short_descr' => 'Suosikkipelisi hahmot ovat aina lähellä',
    'christmas_descr' => 'Jokainen meistä odottaa epäilemättä suosituinta juhlaa - joulua. Kaikki maailman kristityt juhlivat sitä perinteisesti joka vuosi, joulukuun 25. päivänä. Aika, jolloin perheet kokoontuvat yhden pöydän ääreen, jakavat iloaan ja rakkauttaan ja vaihtavat lahjoja. Kauan ennen joulua ihmiset koristavat kadut kirkkailla seppeleillä ja kotinsa perinteisillä tunnusmerkeillä. On vaikea löytää henkilöä, joka ei pitäisi joulusta - hauskasta ja salaperäisestä juhlasta, sillä sitä säestävät monet perinteet ja rituaalit, jotka palauttavat meidät koko perheemme juurille. Jouluaattona kirjaimellisesti kaikki on kyllästetty sen hengessä, maalatuista piparkakuista koskettaviin lauluihin. Tyylikäs joulukuusi ja sen alla olevat lahjat, ilo, joka on tuttu jokaiselle meistä lapsuudesta lähtien. Haluamme liittyä tähän taianomaiseen juhlaan ja, kuka tietää, ehkä joulupukki valmistaa sinulle erityisen lahjan, jos koristat osoittimesi jouluisella kokoelmallamme. Siihen on kaikki mitä tarvitset, joulupukin osoitin, joulukuusen osoitin, piparkakun osoitin, lumiukon osoitin ja jopa lahjapussin osoitin. Hyvää Joulua!',
    'nhl_teams_descr' => 'National Hockey League perustettiin vuonna 1917 - se on ammattimainen urheilujärjestö, joka kokoaa yhteen jääkiekkoseuroja Yhdysvalloista ja Kanadasta. Ja tämä on yksi maailman ensimmäisistä ammattilaisjääkiekkoliigoista. NHL on yksi Pohjois-Amerikan johtavista urheiluliigoista yhdessä NFL:n, NBA:n, Major League Baseballin ja MLS:n kanssa. Joka vuosi 31 joukkuetta 30 kaupungista Yhdysvalloissa ja Kanadassa taistelee pääpalkinnosta - Stanley Cupista, ja runkosarjan eniten pisteitä tehnyt joukkue palkitaan Presidential Cup -palkinnolla. On aika kunnioittaa tätä upeaa peliä luomalla NHL-kursoreiden kokoelma. Jos pidät myös jääkiekosta, kannusta suosikkiseuraasi tai osallistu itse tähän urheilulajiin, vaihda vain kursori ja älä eroa suosikkijoukkueestasi, mukaan lukien Boston Bruins -kursori, St. Louis Blues -kursori, Columbus Blue Jackets -kursori, Tampa Bay Lightning -kursori, Dallas Stars -kursori ja muut seurat, jotka ansaitsevat vilpittömän kunnioituksen.',
    'neon_descr' => 'Olemme luoneet ainutlaatuisen kokoelman neonkursoreita monipuolistamaan jokapäiväistä internet-surffausta ja tuomaan hieman kirkkautta lumoaviin neonvaloihin. Anna niiden runsaiden värien luoda kaupungin ympäröivä tunnelma yöllä ja inspiroida luomaan jotain uutta. Nykyaikaisessa maailmassa suurkaupungin valot ilmoittavat aina yön alkamisesta, ne seuraavat meitä jokaisella kadulla, ja tämä hehku on täynnä energiaa. Olkoon sitä myös seuraamassa hehkuva jäätelökursori, herkullinen hodarikursori, mehukas hampurilaiskursori, kimalteleva timanttikursori ja muita kursoreita uudesta neonkokoelmasta.',
    'adventure_time_descr' => '"Adventure Time" on sarjakuva fantastisesta genrestä, jossa toiminta tapahtuu maailmassa, joka on selvinnyt apokalypsistä. Tätä aluetta kutsutaan Land Oooksi, joka vielä äskettäin oli ydinsodan tuhovoimien alla. Mutta kaikki tämä on jo menneisyyttä, kuitenkin kaikki selviytyneet ihmiset joutuivat mutaatioille, ja maailma täyttyi taikuudella. Animaatiosarjan päähenkilöt ovat Finn, 14-vuotias poika ja hänen ystävänsä Jake-niminen koira. Poika ja koira pitävät kovasti seikkailusta, he auttavat jatkuvasti kaikkia, jotka ovat vaikeuksissa. Ystävät asuvat puussa ja viettävät kaiken aikansa yhdessä. Jos haluat uppoutua seikkailumaailmaan muiden ihailijoiden kanssa, huuda "Matematiikka". Tässä ovat sekä Finn-pojan kohdistin että Jake-kohdistin, sekä Prinsessa Purukumi -kohdistin. Toki emme unohtaneet Bimo-kohdistinta, Jääkuningas-kohdistinta ja muita.',
    'nba_teams_descr' => 'Jos koripallo on suosikkipelisi, kuten se on meidänkin, silloin NBA-joukkueille omistettu kursorikokoelma on sitä mitä tarvitset. NBA on yksi Pohjois-Amerikan mantereen huippu-urheiluliitoista. Kun loimme tämän kokoelman, meitä piinasi valinta - minkä joukkueen valita, koska niitä on NBA:ssa kolmekymmentä. Mutta on joukkueita, jotka ovat legendoja. Tämä ja Chicago Bulls, asettivat voitoille ennätyksen 90-luvun puolivälissä. Tämä on Golden State Warriors, joka toi yhteen liigan parhaat pelaajat pari vuotta sitten. Tai esimerkiksi Lakers, Celtics ovat myös järjettömän hienoja joukkueita. Jos sinä, kuten mekin, odotat innolla suosikkikoripallojoukkueidesi otteluita ja haluat osoittaa tukesi joukkueelle tai pelaajille, lataa NBA-kursorikokoelmamme.',
    'spongebob_descr' => 'Animaatiosarja "Paavo Pesusieni" tunnetaan niin monien ihmisten keskuudessa. Se oli valtava menestys sen jälkeen, kun Nickelodeon päätti vuonna 1999 luoda animaatiosarjan Tide Zone -opetussarjakuvan pohjalta, ja siitä tuli erittäin tuottoisa franchising. Sarjan luoja on entinen valtameritieteellisen laboratorion työntekijä, minkä vuoksi melkein kaikki animaatiosarjan hahmot ovat hauskoja merenpohjan asukkaita, joilla on omat ominaispiirteensä ja karismansa. Toiminta pyörii salaisen Krabbyburger-reseptin ympärillä, jonka vain päähenkilö osaa valmistaa - Paavo Pesusieni. Ja muut meren asukkaat yrittävät saada sen, mukaan lukien pää-antiro Sheldon Plankton, joka ei saa sitä joka kerta. Paavo Pesusieni -kursoreiden kokoelmassa olemme keränneet kaikkien sarjan huomattavien hahmojen ja tapahtumien kursorit. Esimerkiksi herra Rapusen kursori dollarin kanssa, Patrik Tähtösen kursori, Jalmari hänen klarinettinsa kanssa, meduusan kursori, Paavo Pesusienen kursori ja monia muita hahmoja.',
    'phineas_and_ferb_descr' => 'Kuvitteellisessa yhdysvaltalaisessa Denvillen kaupungissa olematonta Trishtatyaa, asuu kaksi mielenkiintoista poikaa. Jokainen heidän lomapäivänsä muuttuu uskomattomiksi seikkailuiksi, koska he voivat rakentaa koko kaupungin kokoisen vuoristoradan tai todellisen portaalin toiselle planeetalle. He jakavat hämmästyttävää viihdettään ystäviensä kanssa. Samalla kun pojat pitävät hauskaa, paha tiedemies Heinz Fufelschmertz rakentaa toista pahaa konetta, joka luo kaaosta, ja jonka nimi päättyy "-inator", jonka avulla hän haluaa kostaa lapsuuden vääryydet tai kaapata vallan Trishtatyssa, mutta Perry estää häntä - Utkonos, salainen "Agentti Pi", joka työskentelee poikien lemmikin suojassa. Tämän animaatiosarjan suosio sekä lasten että aikuisten keskuudessa innoitti meitä luomaan kokoelman Phineas and Ferb -kursoreita, jotta voit vaihtaa hiirikursorisi sarjan hahmoihin. Niiden joukossa ovat Phineas Flynn -kursori, Dr. Heinz Fufelschmertz -kursori, Ferb Fletcher -kursori, Candace Gertrude Flynn -kursori ja Perry-ankkakuonokursori.',
    'fortnite_chapter_2_descr' => 'Fortniten toinen luku tuli suuren tapahtuman jälkeen - The End, joka veti kaiken, mitä pelaajat pelissä rakastivat, mustaan aukkoon. Fortnite Luvulla 2 on nyt uusi kartta, joka ensi silmäyksellä on vielä villimpi kuin alkuperäinen kartta, minkä lisäksi pelimekaniikassa on monia muutoksia ja tietysti paljon uutta pelisisältöä! Ajoneuvot, tunteet, uintimekaniikka ja paljon muuta - kaikki tämä tuoreina, mielenkiintoisina kuvina, aivan kuten rakastat ja arvostat tässä kulttipelissä. Uppoudu uuteen maailmaan - valitse laskeutumispaikka ja tutki täysin uutta saarta 13 sijainnilla. Uiminen, kalastus, moottoriveneet - tämä on uusi vesipeli. Hauskempaa ja vähemmän vaivaa - päivitä täysin uusi luku 2 äläkä unohda vaihtaa kohdistinta uusiin skineihin ja aseisiin. Sinua odottavat jo päivitetyt skinit Turk-kohdistin, Riptide-kohdistin, Rippley-kohdistin, Remedy-kohdistin, Toxin-kohdistin, 8-Ball-kohdistin, Fusion-kohdistin ja muut!',
    'pokemon_descr' => 'Sana "pokemon" tarkoittaa olentoa yliluonnollisilla voimilla. Heillä on älyä, ja jotkut heistä pystyvät jopa puhumaan. Tällä hetkellä on jo 802 erilaista Pokemon-lajia. Keksityssä Pokémon-universumissa ihmisiä kutsutaan Pokémon-kouluttajiksi, joita he kouluttavat taisteluita varten muiden kouluttajien Pokémoneja vastaan. Ja mitä kokeneempi ja vahvempi valmentaja on, sitä enemmän kunnioitusta hän nauttii. Onneksi on huomattava, että Pokémon-taistelut eivät koskaan pääty näiden ainutlaatuisten olentojen kuolemaan. Kaikilla Pokémoneilla on erilaiset kyvyt ja ne eroavat elementtityypistä, ja sen vastustuskyky eri hyökkäyksille riippuu vahvasti tästä, ja joillakin olennoilla on kahden elementin kyky kerralla. Voitettuaan taistelun Pokemon saa arvokasta kokemusta, joka on välttämätöntä tason nostamiseksi ja vastaavasti sen ominaisuuksien parantamiseksi. Nykyään Pokémon-universumi on valtava mediafranchise, ja päätämme valmistella sinulle kokoelman kursoreita joillakin suosituilla Pokémoneilla. Niistä tunnetuin on Pikachu-kursori sekä Rattata-kursori, Squirt-kursori, Bulbasaur-kursori ja Charmander-kursori. Tätä luetteloa päivitetään, koska niitä on niin paljon ja jokainen niistä on ainutlaatuinen omalla tavallaan.',
    'famous_people_descr' => 'Monien kuuluisien ihmisten joukosta jokainen meistä löytää roolimallin tai yksinkertaisesti ihailee näiden julkkisten neroutta, lahjakkuutta ja sinnikkyyttä. Olemme laatineet kokoelman julkkiskursoreita inspiroimaan sinua ja muistuttamaan sinua suurista saavutuksista, joita jokainen teistä voi lisätä. Kaikilla kuuluisuuksilla ei ole ollut onnellista kohtaloa, mutta he opettavat meille pääasian, että sinun ei koskaan tarvitse vetäytyä vaalimastasi tavoitteesta, vaikeuksista ja ongelmista huolimatta. Loppujen lopuksi tämä on menestyksen pääperiaate - mennä unelmaasi joka päivä ja lopulta tulla parhaaksi omalla alallasi. Ehkä tänään haluat vain vaihtaa hiiren kohdistimesi, ja huomenna koko elämäsi muuttuu paremmaksi! Kokoelmaa päivitetään jatkuvasti uusilla, ihmisyyden arvoisilla edustajilla. Heidän joukossaan ovat tietysti tiedemiehet, poliitikot, urheilijat, taiteen edustajat ja monet muut. George Washington -kohdistin, Michael Jordan -kohdistin, Stephen King -kohdistin, Elvis Presley -kohdistin ja Marilyn Monroe -kohdistin ovat vasta alkua.',
    'the_elder_scrools_descr' => 'The Elder Scrolls on tietokoneroolipelien sarja, jota yhdistää yhteinen, huolellisesti suunniteltu maailmankaikkeus, joka tarjoaa pelaajalle valtavan valinnanvapauden, jonka avulla he voivat vierailla eri alueilla ja kaupungeissa fantasiamaailmassa ja tutkia uusia paikkoja ja tehtäviä itsenäisesti. Työ sarjan parissa alkoi jo vuonna 1992, ja vuosien varrella peli on yhdistänyt ympärilleen valtavan pelaajayhteisön. Siksi olemme suuren kysynnän vuoksi julkaisseet The Elder Scrolls -kursoreiden kokoelman, jotta voit uppoutua pelin ainutlaatuiseen tunnelmaan. Ritarien ja lohikäärmeiden ikuinen taistelu, kummalla puolella sinä olet? Vaihda kohdistin lohikäärmeeksi ja liity tulenhenkäilijöiden armeijaan tai taistele jaloasti ihmisten puolella valitsemalla miekkakohdistin ja suosikkihahmosi kuva – päätös on sinun! Pääasia on, että olet uuden kokoelmamme kanssa valmis mihin tahansa taisteluihin.',
    'halloween_descr' => 'Odotatko mystistä yötä Pyhäinpäivän aattona? Halloweenin historia ulottuu yli kahdentuhannen vuoden taakse. Ehkä tämä on oudoin juhla, joka yhdistää hauskanpidon ja pelon, ja joka on kelttiläisen kulttuurin oma. Silloin ihmiset polttivat kokkoja ja pukeutuivat pelottaviin asuihin karkottaakseen aaveita. Sanaa "Halloween" mainittiin ensimmäisen kerran 1500-luvulla skotlantilaisena lyhenteenä englanninkielisestä ilmauksesta All-Hallows-Even. Paavi Gregorius III julisti marraskuun 1. päivän Pyhäinpäiväksi, ja edellistä iltaa kutsuttiin Pyhäin aatoksi ja myöhemmin Halloweeniksi. Tänä päivänä ihmiset pukeutuvat ihmissusien, aaveiden ja muiden hirviöiden asuihin ja menevät naapuritaloihin tarjoten ostaa makeisia. Teemajuhlat, ilotulitteet, kauniit lyhdyt, kurpitsat ja temput luovat ainutlaatuisen tunnelman. Haluamme myös juhlistaa tätä kauheaa juhlaa asusteiden kursoreilla ja Halloween-hahmoilla. Kokoelmastamme löydät: zombi-kursorin, aave-kursorin, musta kissan kursorin, kurpitsa-kursorin ja paljon muuta. Mielialan vaihtaminen on nyt yhtä helppoa kuin kursorin vaihtaminen uuden Halloween-kokoelmamme avulla.',
    'nfl_teams_descr' => 'Mikä voisi olla parempaa todelliselle amerikkalaisen jalkapallon fanille kuin hiiren kohdistin joukkueen symboliikan muodossa, jota hän kannattaa? Nykyaikaisessa National Football Leaguessa pelaa kolmekymmentäkaksi joukkuetta, jotka on jaettu National- ja American Football -konferensseihin (National Football Conference, NFC ja American Football Conference, AFC). Kukin konferenssi on jaettu neljään divisioonaan: Itä, Pohjoinen, Etelä ja Länsi. NFL-kausi koostuu harjoituskauden peleistä, runkosarjasta ja pudotuspeleistä. NFL-kauden viimeistä ottelua kutsutaan Super Bowliksi, ja se on olennaisesti suosituin urheilutapahtuma Yhdysvalloissa. Tämä on miljoonien fanien suosikkipeli, ja siksi olemme luoneet NFL-kohdistimia sisältävän kokoelman, jotta et luopuisi suosikkijoukkueesi symboleista. Olipa kyseessä New England Patriots, New York Giants, Buffalo Bills tai jokin muu joukkue, ole aina samalla aaltopituudella idoleidesi kanssa käyttämällä kohdistimiamme joukkueen logon ja kypärän muodossa. Kokoelmaa päivitetään jatkuvasti, jotta jokainen voi vaihtaa kohdistimen suosikkijoukkueensa kuvaan.',
    'five_nights_at_freddy_descr' => 'Todella ainutlaatuinen peli Five Nights at Freddy\'s saavutti nopeasti suurta suosiota, eikä tämä ole yllättävää, sillä sen yksinkertainen ja samalla kiehtova juoni voi pitää pelaajat ruuduilla tuntikausia. Suunnittelimme Five Nights at Freddy\'s -kursoreita pelin fanien pyynnöstä ja olimme erittäin iloisia voidessamme ilmentää niin mielenkiintoisia ja hauskoja hahmoja. Mutta toisin kuin pelissä, mikään ei uhkaa sinua kursoreillamme, joten valitse vapaasti suosikkianimatronisi, olipa se sitten Bear Freddy tai Rabbit Bonnie tai muut. Pääasia on, että nyt peli herää henkiin selaimessasi ja antaa uusia tunteita. Takaamme, että kursoreissamme ei ole haamuja, mutta ne välittävät täydellisesti pelin hengen, joka herättää pelkoa suunnittelun ja juonielementtien monimutkaisuuden vuoksi. Mutta mitä jos teet kursorin koosta hyvin suuren? Pystytkö pysymään rauhallisena etkä pelästymään?',
    'komiksy_descr' => 'Vaikuttaisi siltä, että hiiren kohdistin on pieni asia, mutta usein juuri sellaiset yksityiskohdat voivat parantaa mielialaasi, herättää harmaana aamuna tai yksinkertaisesti antaa kirkkaita tunteita. Kokoelma sarjakuvien kohdistimia, jotka on suunniteltu erityisesti kaikille supersankareiden ystäville. Täältä löydät ehdottomasti koko Marvel-universumin ja DC Comicsin - Iron Manista Thanosiin, Spider-Manista ja Hulkista. Hiiren kohdistin voi olla joko supersankarin muodossa tai hänen hahmonsa muodossa. Kohdistin ei ole vain toiminnallinen elementti; se on tärkeä ammatillisessa mielessä. Esimerkiksi, jos tallennat videota näytöltä, on parempi nähdä kirkas, alkuperäinen kuva, ja se näyttää paljon mielenkiintoisemmalta. Ja tietenkin - kuka ei haluaisi käyttää äärettömyyden hansikasta tosielämässä? Hiiren kohdistimen vaihtaminen on helppoa - lataa vain laajennus selaimeesi ja lisää haluamasi kohdistin asetuksiisi sen kautta. Voit valita kohdistimen mielialasi mukaan vaikka joka päivä. Riittää harmaat päivät - tule supersankariksi heti!',
    'igry_descr' => 'Tietokonepelit ovat jo pitkään olleet olennainen osa elämäämme. Niiden avulla voit uppoutua uuteen maailmaan, osallistua seikkailuihin ja tulla täysin erilaiseksi henkilöksi. Jokaisella on oma suosikkilelunsa, jonka hahmoista on jo tullut melkein perhettä. Kokoelma tunnettuihin tietokonepeleihin perustuvia kursoreita on mahdollisuus laimentaa tylsää jokapäiväistä elämää ja lisätä hieman luovuutta, kirkkautta ja hauskuutta työnkulkuun. Sarja sisältää sekä kuvia pelihahmojen itsestään että apuhahmoja, aseita ja pelikuvakkeita. Valitse mikä sopii mielialaasi - pelikursorit miellyttävät pelaajien lisäksi myös kaikkia, jotka ovat yksinkertaisesti väsyneitä harmaaseen arkeen. Lataa vain sarja, vaihda hiiren kohdistin - ja menoksi, suorittamaan tehtäviä, tuhoamaan vihollisia ja saavuttamaan tavoitteesi.',
    'multfilmy_descr' => 'Jokaisessa aikuisessa on yhä lapsi, joka rakastaa sarjakuvia ja haaveilee yhä tulevansa yhdeksi sankareista. Autamme tekemään unelmistasi totta - käytä uutta kursori kokoelmaa, joka perustuu tunnetuimpiin ja suosituimpiin sarjakuviin. Tom ja Jerry, Buzz Lightyear ja Shrek, Gravity Falls ja jopa Pokemon - voit tulla siksi, mitä haluat joka päivä. Valitse hiiren kursori mielialasi mukaan. Kenenä olet tänään? Riemukas ja iloinen kätyri, joka ratkaisee helposti kaikki ongelmat, vai vahva ja urhea Raphael, jonka tavoitteena on paitsi suoritukset, myös pizzan syöminen? Ehkä olet kaikkivoipa henki, joka pitää kokonaista toimistoa komennossaan? Kokoelmassa on sankareita jokaiselle - prinsessoista lohikäärmeisiin - jää vain päättää, kuka heijastaa tämän päivän mielialaa. Cursor Style ei ole vain kirkas kuva. Tämä on heijastus yksilöllisyydestä, itsensä ilmaisusta ja yksinkertaisesti - hauskuudesta, ilosta ja positiivisuudesta koko päivän. Onko tylsää työskennellä tai liian laiskaa opiskella? Onko tullut surullinen ja ei ole onnellinen? Vaihda kursori ja maailma säihkyy uusilla väreillä.',
    'kino_i_serialy_descr' => 'Elokuvat - ovat taikaa, mystiikkaa ja loistava tapa rentoutua, pitää hauskaa ja saada eläviä tunteita. Samalla elokuvan katselun jälkeen muistamme edelleen suosikkisankarimme, jotka haluaisimme todella tavata todellisuudessa. Nyt se on mahdollista - lataa vain uusi kokoelma kursoreita, jotka perustuvat kuuluisiin elokuviin ja TV-ohjelmiin. Kirkkaat, hienot kursorit ovat loistava lisä työpöydälle, muuttavat tylsän harmaan arjen juhlaksi ja banaalit tehtävät - jännittäväksi seikkailuksi. Vaihda hiiren osoittimen sankaria joka päivä - mielialan, tehtävien tai satunnaisesti mukaan. Kuka sinä olet tänään? Rehellinen ja oikeudenmukainen John Snow tai rohkea, säälimätön John Wick? Ehkä sinulla on edessäsi vaikea tehtävä, ja vain Frodo voi suorittaa sen? Ehkä tänään olet vain muukalainen, joka ei halua ottaa yhteyttä muihin? Valitse sopiva kursori - piristä mielialaasi ja samalla näytä muille mitä ajattelet ja miten aiot viettää päiväsi. Kokeile - se ei ole vain hauskaa, vaan myös koukuttavaa - et varmasti halua palata tavalliseen nuoleen.',
    'anime_descr' => 'Anime on ainutlaatuinen animaatiotyyli, jota huolimatta sen selvästä etnisyydestä, miljoilla ihmisillä on ollut ilo katsella ympäri maailmaa. On epätodennäköistä, että olisi edes yhtä ihmistä, joka ei olisi katsonut piirrettyjä tässä tyylissä. Loimme hienoimmat anime-tyyliset kohdistimet, joita kaikki tämän tyylin fanit rakastavat. Vakiokohdistimet ovat tylsiä ja kliseisiä. Näytä persoonallisuutesi - käytä Anime-kohdistimien kokoelmaa suosikkihahmojesi kanssa. Valitse tumman miekan kohdistin, jos unelmoit seikkailuista ja rohkeista taisteluista. Söpö lihava mies Totoro piristää sinua jopa surullisimpana päivänä, ja Naruto motivoi sinua seikkailuihin ja näyttää kaikille ympärilläsi, että olet megahieno. Kirkkaat kohdistimet piristävät työpäivää tai tekevät oppimisprosessista mielenkiintoisempaa ja nautittavampaa. Älä rajoita itseäsi - käytä suosikkiaiheitasi jopa niin pienissä elementeissä kuin hiiren kohdistin. Vaihda kohdistimia joka päivä, mukauta niitä mielialaasi ja näytä persoonallisuutesi - anime-tyylisten kohdistimien kanssa se on niin yksinkertaista.',
    'futbol_descr' => 'Jalkapallo on erikoislaji, joka sisältää painin, yleisurheilun ja tarkkuuden elementtejä. Yleensä ottaen se on näyttävä, armoton ja kerää miljoonia faneja ympäri maailman. Pidätkö jalkapallosta vai rakastatko vain urheilua? Lataa sitten Cursor Stylen kursorit maailmankuulun pelin tyyliin ja todista olevasi uskollinen fani. Kokoelma sisältää 24 vaihtoehtoa kursoreiden suunnitteluun - suosituimpien joukkueiden muodossa, jotka ansaitsevat tittelinsä epätoivoisena ja sitkeänä pelinä. Kursorit on tehty kahdessa versiossa - vakiokolmion muodossa, koristeltuna joukkueen väreillä, tai vastaavan pelikypärän muodossa. Tavallinen selaimen kursori on tylsä eikä sen arvoinen, joka on todellinen urheilufani. Tule omaperäiseksi ja ainutlaatuiseksi kokoelmamme avulla. Lataa kuvat ja valitse suosikkijoukkueesi värit tai mukautetut kursorit, jos rakastat vain urheilua ja kannustat kaikkia. Harrastustesi seuraaminen on niin yksinkertaista - sinun ei tarvitse tulla töihin suosikkijoukkueesi huivissa tai pipossa, on nopeaa ja helppoa vaihtaa kursori kirkkaaseen, tyylikkääseen kuvaan.',
    'avtomobili_descr' => 'Pidätkö autoista ja nautitko erilaisten valmistajien mallien katselusta? Tai oletko haaveillut tietystä merkistä pitkään, mutta sinulla ei vieläkään ole mahdollisuutta ostaa sitä? Erityisesti sinulle olemme luoneet kirkkaan kursori-sarjan "Superautot". Täältä löydät klassisia Fordeja ja tyylikkäitä Bentleyitä, kirkkaita Lamborghinejä ja ainutlaatuisia Ferrarereita. Haluatko tulla alkuperäisen auton omistajaksi? Se on yksinkertaista - lataa kursori-kokoelmamme laitteellesi ja vaihda auton kuvaa vähintään joka päivä. Kursorit on suunniteltu kahdessa versiossa - täysimittaisena autona tai sen merkkinä. Valitse mitä pidät eniten tai miten haluat työskennellä. Tällaiset kuvat näyttävät upeilta pelikursoreina tai yksinkertaisesti epätavallisena elementtinä työpöydällä. Kirkkaana oleminen on yksinkertaista - tätä varten ei ole välttämätöntä tehdä uskomattomia asioita tai muuttaa ulkonäköäsi. Riittää, että lakkaat käyttämästä tavanomaisia esineitä ja valitset sen, mistä todella pidät. Kursorikokoelma "Autot" on valinta niille, jotka eivät pelkää todistaa itseään.',
    'memy_descr' => 'Meemit ovat jo pitkään olleet tuttu osa elämäämme. Ja kuka meistä ei pitäisi näistä tilavista, mielenkiintoisista ja omaperäisistä kuvista piristääkseen päivää? Monet meemien sankarit eivät ole vain tulleet suosituiksi - he ovat saavuttaneet suosittujen suosikkien aseman, ja lauseita ja ilmauksia on jo pitkään sisällytetty puhekieleen vakiintuneina ilmauksina. Esittelemme kokoelman parhaita kursoreita, jotka perustuvat suosituimpiin meemeihin. Niiden avulla voit paitsi osoittaa persoonallisuuttasi, myös ilmaista mielialaasi. Oletko kaikki väsynyt ja kyllästynyt kaikkeen? Valitse vihainen kissa, joka kaikella olemuksellaan ilmaisee närkästystä ja vihamielisyyttä kaikkea ympärillään olevaa kohtaan. Vai loistatko tänään sarkasmilla etkä pahastu nauramisesta? Silloin Drake Bling on erinomainen säestys - se piristää sinua ja tekee mistä tahansa tehtävästä omaperäisen ja mielenkiintoisen. Asenna laajennus, lataa kokoelmamme – ja valitse kursorityyli jokaiselle päivälle. Ei ole vaikeaa olla kirkas ja omaperäinen - vaihda ikonien vakiomuoto yhdeksi meemisankareista ja saa energiapiikki koko päiväksi.',
    'emodji_descr' => 'Emoji - kirkkaat, hienot kuvakkeet, ilman joita emme enää tavallisesti osaa kommunikoida. Niiden avulla sinun ei tarvitse kuvailla mielialaasi sanoin - valitse vain haluamasi kuvake ja keskustelukumppanisi ymmärtää sinua ilman muuta. Uudessa kursori-sarjassamme ilmensimme emoji-ideaa - juuri niin hauskoja ja epätavallisia Cursoji-kursoreita ilmestyi, jotka värittävät maailmaa ja tekevät elämästä mielenkiintoisempaa. Kursoreiden avulla voit paitsi työskennellä ja suorittaa tuttuja tehtäviä, myös näyttää kollegoillesi, ystävillesi ja muillekin mielialaasi. Unelias kursori sopii täydellisesti maanantaiaamuun, ja itkevä kursori ilmaisee asennetta lisävastuita kohtaan. Hieno kursori silmälaseilla on paras valinta ennen lomia, ja kursori silmät buckseilla on hyvä syy vihjailla päällikölle palkankorotuksesta. Cursojien käyttäminen on hauskaa ja mielenkiintoista - olipa kyseessä työ, opiskelu tai esitys. Jälkimmäisessä tapauksessa sitä suositellaan jopa tekemään, jos kollegoilla on huumorintajua tai heidän on vain lievennettävä tilannetta. Yleisesti ottaen, mihin tahansa tehtävään - valitse vain oikea kursori!',
    'pitomcy_descr' => 'Pidätkö eläimistä? Toki - ne ovat niin söpöjä, hauskoja ja todella hauskoja. Miksi et viettäisi koko päivää ihmisen parhaiden ystävien seurassa? Lataa Lemmikkieläimet -kursorikokoelma itsellesi ja valitse ystäväsi joka päivä. Kursorikuvake voi olla söpö, kuten hyväntahtoinen alpakka, tai tyylikäs, kuten vaaleanpunainen flamingo. Tai ehkä olet kiireinen koko päivän ja valitset sanomalehteä lukevan yksisarvisen, tai et yksinkertaisesti halua olla missään tekemisissä kenenkään kanssa, kuten paha musta kissa? Jokaiselle mielialalle meillä on sopiva eläin. Iloinen mopsi piristää sinua jopa tylsimpänä ja harmaana päivänä, ja vaaleanpunainen kursorikuvake yksisarvisen muodossa näyttää kaikille, että sinulta ei puutu kauneudentajua, vaikka olisitkin brutaali parta mies. Entä jos ei ole mielialaa, enkä halua tehdä rutiinitehtäviä? Resepti on yksinkertainen - lataa Lemmikkieläimet-kokoelma, vaihda hiiren kursori - ja voila, aurinko paistaa taas, sää on hieno ja mieliala on korkeimmalla tasolla. Ei ihme, että sanotaan, että eläimet auttavat taistelemaan masennusta ja surua vastaan!',
    'stil_i_krasota_descr' => 'Uudessa kursoreiden kokoelmassa olemme keränneet laajan valikoiman aiheita, jotka aiheuttavat meille miellyttäviä tunteita ja kohottavat mielialaamme. Tämä kursoreiden joukko on nimeltään "Tyyli ja Kauneus", koska se sisältää suosikkijuttujasi, jotka määrittävät jokapäiväistä elämäämme, antavat iloa ja motivoivat meitä tekemään tärkeitä asioita, herättävät halun parantaa itseämme. Oletko kiinnostunut avaruudesta ja haaveiletko matkustamisesta muille planeetoille? Valitse NASA-kursori tai alien-lautanen - pääset lähemmäksi unelmaasi. Jos et voi kuvitella elämää ilman musiikkia tai olet vannoutunut rokkaaja, silloin sähkökitaran tyylinen kursori on sinua varten. Sivellin, viivain ja kompassikursori on kehitetty erityisesti insinööreille - tällaiset kuvat auttavat muuttamaan tylsät laskelmat ja piirustukset alkuperäisiksi ratkaisuiksi. Taikasauva ja lenkkarit, rullalauta ja huulipuna, aurinko ja kemialliset keilat - valitse se mikä sopii elämäntyyliisi, toiveisiisi ja päämääriisi - ja tavalliset tehtävät muuttuvat mielenkiintoisemmiksi, ja työpäivät saavat uusia, kirkkaita värejä.',
    'prazdniki_descr' => 'Pidätkö juhlapäivistä? Mutta kuka niistä ei pidä - ystävistä, lahjoista, taas sama viikonloppu. Jotta juhlapäivien odotus olisi miellyttävämpää, lyhyempää ja lämpimämpää, voit paitsi laskea päiviä kalenterissa, myös asettaa vastaavan kuvakkeen hiiren kursoriksi. Aloitetaan uudesta vuodesta - valitsemme joulukuusen, lahjan tai joulupukin, jotta juhla olisi kirkas ja iloinen. Ehkä piparimies on lähempänä - hauska, söpö ja aina iloinen? Hänen kanssaan ei varmasti ole aikaa olla surullinen ja tylsistynyt. Juhlimme edelleen cupidojen ja iloisten sydänten kanssa, ja pääsiäispupuun ei ole pitkä matka. Joidenkin juhlapäivien joukossa on syntymäpäivä, jota on vieläkin miellyttävämpää odottaa ilmapallojen kanssa tavallisen kursorinuolen sijaan. Ja Halloweenina voit yllättää kollegat ja ympärilläsi olevat epätavallisella hiiren kursorilla, joka on synkkä kurpitsa tai kummitus. Kursorisarja juhlapäiville on mahdollisuus piristää odotusta, virittäytyä etukäteen tulevaan hauskanpitoon ja ylläpitää erinomaista tunnelmaa paitsi juhlapäivänä, myös ympäri vuoden.',
    'flagi_descr' => 'Lippu on ainutlaatuinen symboli, jota käytetään laajalti kaikissa sosiaalisissa verkostoissa. Ajattelimme, miksi emme tekisi kursorista lippua? Loppujen lopuksi se on todella kirkas ja epätavallinen. Nyt voit viettää jokaisen päivän uuden maan seurassa, eikä työ ole enää niin yksitoikkoista ja tylsää. Hiirikursorit voidaan nyt tehdä Kiinan tai USA:n, Japanin tai Kanadan kansallislipuiksi, ja lisäksi on 38 muuta lippuvaihtoehtoa, ja voit valita joko tavallisen nuolen muodon epätavallisessa värissä tai kursorin itse lipun muodossa. Tämä setti vetoaa kaikkiin matkustamisen ystäviin. Sen avulla voit suunnitella uusia matkoja ja haaveilla pitkistä matkoista. Oletko suunnitellut lomaa? Näytä kaikille, mihin maahan haluat mennä. Ehkä olet päättänyt oppia uuden vieraan kielen? Silloin tämä kursori ehdottomasti tukee sinua ja motivoi sinua opiskelemaan huolellisesti. Vai rakastatko sinäkin lippuja niin kuin Sheldon? Kaikissa tapauksissa Flags-kursorikokoelma on hieno lisä työpöydällesi ja vie sinut kohti uusia löytöjä.',
    'vokrug_sveta_descr' => 'Kaikki tykkäävät matkustamisesta. On mahtavaa vierailla uusissa maissa ja kaupungeissa, nähdä nähtävyyksiä ja pitää hauskaa uudessa kulttuurissa. On sääli, että voimme matkustaa niin harvoin, mutta yritimme korjata sen. Kursorisarja “Around the World” on kokoelma silmiinpistävimmistä kuvista, eri maiden symboleista, joiden avulla voit tuntea itsesi oikeaksi matkustajaksi jopa kotona istuessasi. Sarjastamme löydät Japanin ja Australian, Italian ja Kanadan, USA:n ja Meksikon - maailman mielenkiintoisimmat, omaperäisimmät ja värikkäimmät maat. Kursorikuva voi olla tavallinen nuoli, maan lipun väreissä, tai siitä voi tulla yksi valtion päänähtävyyksistä. Voit esimerkiksi avata asiakirjoja Pisan tornilla ja tehdä esityksiä Vapaudenpatsaalla. Takaamme - menestys on taattu. No, tai jos ei menestystä, niin kollegoiden hymyt ja omaperäisyyden tunnustaminen - varmasti. Kyllä, ja vihjaaminen johdolle, että on aika lähteä lomalle, on myös sen arvoista - aseta vain matkalaukku tai lentokone kursoriksi - ja hyvinkin lentänet pian.',
    'eda_i_napitki_descr' => 'Sarja kursoreita tuotteiden muodossa on uskomaton kokoelma kirkkaita, maukkaita ja suussa sulavia kuvia, joista kaikki varmasti pitävät ja jotka ovat upea lisäys selaimeen. Oletko koskaan klikannut parsakaalia tai ranskalaisia? Sinulla on tällainen mahdollisuus - lataa vain uusi kursoriarja ja aseta ne tylsän valkoisen nuolen sijaan. Kursori "Ruoka" on tehty sekä tavallisen kolmion muotoisen osoittimen muodossa että tuotteiden muodossa. Täältä löydät vihanneksia ja hedelmiä, suosikkiruokiasi, kuten pizzaa tai hot dogeja, kahvia, tikkareita ja paljon muuta, mikä piristää jokaista päivää. Rakastatko kahvia, mutta sen juominen koko päivän ei ole niin hyväksi? Täydennä ruokavaliotasi virtuaalisella kahvilla, joka myös virkistää ja herättää sinut sekä antaa eläviä tunteita. Jyrkkä kursori virtuaalisen donitsin muodossa ei vahingoita hahmoa, samalla kun se antaa eläviä tunteita ja piristää. Voit käyttää suosikkikursoreitasi tai vaihtaa kuvaa joka päivä - laaja valikoima kursoreita auttaa värittämään jokapäiväistä elämää ja lisäämään uusia värejä tuttuihin toimintoihin.',
    'cvetnye_descr' => 'Kohdistin on selaimen pääelementti, jonka kanssa vietämme koko työpäivän, opiskelemme, kommunikoimme ja rentoudumme. Kohdistimen vakiomalli on tylsä ​​ja jopa hieman masentava, mutta silti monille ihmisille tämä muoto on kätevä, ja sen muuttaminen tulee olemaan epämukavaa. Mutta tähän tilanteeseen meillä on ratkaisu - joukko kohdistimia kirkkaissa, iloisissa väreissä, jotka lisäävät vaihtelua jokapäiväiseen elämääsi ja tekevät minkä tahansa ongelman ratkaisemisesta helpompaa ja nopeampaa. Jos mietit, miten kohdistimen väriä voi muuttaa, vastaamme - lataa kokoelmamme ja valitse kirkkaita ratkaisuja joka päivälle! Voit valita yksivärisiä sävyjä eri väreissä mielialan tai työn erityispiirteiden mukaan. Esimerkiksi työskennellessäsi tavallisten asiakirjojen kanssa purppuranvärinen kohdistin erottuu taustasta, ja tummalla taustalla taas on helpompi työskennellä keltaisilla kohdistimilla. Jos haluat värien räjähdyksen, kirkkautta ja maksimaalista omaperäisyyttä - valitse sateenkaarinen kohdistin, joka sisältää kaikki spektrin värit - tällä kuvakkeella mieliala on ehdottomasti hyvä koko päivän.',
    'prank_descr' => 'Vitsailu työpaikalla ei ole aina toivottavaa, koska se usein häiritsee työnkulkua. Mutta uuden “Prankki”-kursori-sarjan avulla voit ystävällisesti tehdä kepposen kollegoillesi tai ystävillesi vahingoittamatta työtäsi tai opiskeluasi. Olemme kehittäneet erityisen kokoelman, joka huvittaa ketä tahansa ja antaa syyn rentoutua hieman kiireisen työn tai muun tehtävän keskellä. Vaihtaaksesi hiiren kursoria, lataa vain sarja laitteellesi ja valitse haluamasi design asetuksista. Esimerkiksi voit saada standardimuotoisen kursorin, mutta käänteisessä tilassa tai aallolla kaareutuneen nuolen. Tämä muoto ei lainkaan estä työntekoa, mutta samalla se tarjoaa upean mielialan ja asettaa sinut positiiviselle tuulelle. Muuta kursorin näyttöasetuksia mielialasi mukaan tai joka päivä - ja mikä tahansa tehtävä muuttuu mielenkiintoisemmaksi ja nautittavammaksi, ja arki lakkaa aiheuttamasta negatiivisia tunteita. Lisäksi tällaisia kursoreita voidaan käyttää jopa vakaviin projekteihin - niillä on neutraalit värit, eivätkä ne erotu työpöydältä.',
    'startovyj_nabor_descr' => 'Aloituskokoelman osoittimet ovat yhdistelmä vakiomuotoja ja -kokoja kirkkaalla, epätavallisella ulkoasulla. Tämä on erinomainen valinta niille, jotka pitävät tavanomaisista muodoista, mutta haluavat tuoda monimuotoisuutta, omaperäisyyttä ja kirkkautta arkeen. Kokoelmassa on käsiosoitin ja tuttu nuoli monissa eri variaatioissa - Google Chrome -logosta hymiöihin, voit jopa tavata täällä kauan sitten unohdetun lohikäärmeen kaktuksineen ja nostalgian. Todistamme, että vakiotyyppinen osoitin voi olla myös mielenkiintoinen ja houkutteleva. Eri värit, muodot, tekstuurit ja mielenkiintoinen muotoilu auttavat sinua valitsemaan makuusi sopivan osoittimen tai vaihtamaan sitä joka päivä mielialasi tai suoritettavien tehtävien mukaan. Selaimen osoittimen vaihtaminen on hyvin yksinkertaista - asenna vain laajennus ja lataa kokoelma laitteellesi. Hauskat, mielenkiintoiset osoittimet eivät vain väritä työpäiviä, vaan esimerkiksi auttavat tekemään esittelystä mielenkiintoisemman ja erityisesti kirkkaiden osoittimien avulla myös kiinnittämään huomiota raportin yksittäisiin elementteihin.',
    'fortnite_descr' => 'Fortnite on valloittanut miljoonia ihmisiä ympäri maailman. Jännittäviä taisteluita, strategiaa ja taktiikkaa, seikkailuja - se on imenyt itseensä aivan kaiken, mistä pelaajat pitävät niin paljon. Emme voineet jäädä sivusta seuraamaan ja kehitimme joukon kursoreita pelin tyyliin, jotka miellyttävät paitsi innokkaita pelaajia, myös niitäkin, jotka kuulivat Fortnitesta ensimmäistä kertaa. Fortnite-kursori-ikoni on kuva sankarista tai hänen aseestaan, joka on viimeistelty pienintä yksityiskohtaa myöden. Täältä löydät kuvia ketuista ja kaloista, infernon ja mustien ritarien naamioista, aseta itsellesi nuoli tai piikkimäinen viikate nuoleksi. Olemme varmoja, että kukaan ei jää välinpitämättömäksi! Ollaksesi pelottava tai salaperäinen, omaperäinen tai humoristinen - se on sinun päätettävissäsi. Valitse tyylisi ja seuraa sitä tai aseta mukautetut kursorit asetuksissa ja vaihda roolisi joka päivä. Nyt tylsän ja yksitoikkoisen työn tekeminen muuttuu paljon kiinnostavammaksi ja miellyttävämmäksi - aika lentää nopeasti värikkäiden kuvien ja suosikkihahmojen seurassa. Tai ehkä järjestät kilpailuja työtovereiden kanssa, mikä sankari on vahvempi? Valinta on sinun!',
    'dota_2_descr' => 'DotA2 ei ole enää pelkästään yksinkertainen peli, vaan todellinen rinnakkaismaailma. Virtuaalitodellisuudessa DotA2:ssa voit tehdä kaiken - elää, taistella, kehittyä, matkustaa, saada ystäviä. Yleisesti ottaen kaikki on kuin elämässä, vain ajoittain mielenkiintoisempaa. Dota 2 -kursori on jatkoa strategialle, jonka avulla saat eläviä tunteita ja voit ilmaista itseäsi todellisessa maailmassa. Uusi kursorisarja sisältää pelin silmiinpistävimmät hahmot sekä alkuperäisiä esineitä, joita ei voi sekoittaa mihinkään muuhun. Valitse kursori, joka on sinulle läheisempi - ja lähde seikkailuun poistumatta työpaikaltasi. Kuinka tylsää onkaan joskus olla töissä tai suorittaa opetus tehtäviä, mutta pelikurssoreilla tämä ongelma ei enää kohtaa sinua. Pieni mielikuvitus, kirkas kursori - ja voila, mikä tahansa asia on epätavallinen seikkailu, jonka selviytyminen ei ole vaikeaa ja mielenkiintoista. Ei tarvitse pidätellä itseäsi. Pidätkö Dotasta? Lataa silloin ihmeessä kokoelmamme, valitse yksi tai useampi satunnainen kursori kerralla - ja jokaisesta uudesta päivästä tulee kirkkaampi, mielenkiintoisempi ja kylläisempi.',
    'minecraft_descr' => 'Hiiren osoittimet tavallisina nuolina ja sormina ovat jo kauan sitten tulleet kaikille tylsiksi. Jos olet epätavallisen ja omaperäisen ystävä, on aika vaihtaa hiiren osoitin ja antaa sille mielenkiintoisempi muotoilu. Olemme kehittäneet kokoelman osoittimia maailmankuulun Minecraft-pelin tyyliin, josta löydät silmiinpistävimmät hahmot. Susi ja kettu, Alex ja Creeper, timanttimiekka ja kala - voit valita itsellesi mieluisimman tai asentaa uuden sankarin joka päivä. Nämä ovat todellisia osoittimia pelaajille, ja aivan kaikki pitävät niistä - loppujen lopuksi, kuka meistä ei ole pelannut Minecraftia? Olemme varmoja, että niitä ei yksinkertaisesti ole. Pois tylsästä arjesta - on aika sukeltaa seikkailuihin, joita voi tehdä jopa poistumatta kotoa tai toimistotuolista. On mielenkiintoisempaa valmistella raportti ja pienentää saldoa aseella - mikä tahansa tehtävä muuttuu miellyttävämmäksi eikä anna sinun ikävystyä paikallasi. Lataa uusi Minecraft-osoittimien kokoelma - asenna ne ja jopa harmaimpana ja tylsimpänä päivänä mielialasi on aina parhaimmillaan. Ja kollegat kadehtivat tuloksiasi - on yksinkaisesti mahdotonta olla tekemättä työtäsi Minecraftin urheiden sankareiden avulla.',
    'demon_slayer_anime_descr' => 'Toiminta sijoittuu Taisho-kaudelle. Muinaisista ajoista lähtien on liikkunut huhuja, että humanoididemoneita asuu metsässä, jotka syövät ihmisiä ja kulkevat öisin etsimässä uutta uhria. Mutta... se on vain legenda, eikö niin?..

Tanjiro Kamado on perheen vanhin poika, joka menetti isänsä ja huolehti perheestään. Eräänä päivänä hän menee läheiseen kaupunkiin myymään puuhiiltä. Palattuaan aamulla kaveri löytää edestään kauhean kuvan: kaikki sukulaiset oli murhattu raa\'asti, ja ainoa selviytyjä on Nezuko, nuorempi sisko, joka on muuttunut demoniksi, mutta joka ei ole vielä menettänyt kaikkea inhimillisyyttään.

Tästä hetkestä alkaen Tanjiro ja Nezuko aloittavat pitkän ja vaarallisen matkan, jossa poika aikoo löytää tappajan ja löytää keinon parantaa sisarensa. Mutta pystyvätkö lapset selviytymään kaikista vaikeuksista ja palaamaan kotiin? Tiedät jo vastauksen, ja jos et - aseta pikaisesti Demon Slayer -kursorit, jotka sisältävät hahmoja yhdestä suosituimmista mangasarjoista.',
];
