<?php

return [
    'title' => 'Сursor Style - Tuotteemme käyttöehdot',
    'descr' => 'Käyttöehdot ovat sinun ja "Cursor Style" ("Palvelu", "me" tai "Palvelu") välillä. Tätä palvelua tarjotaan ja se on saatavilla vain vähintään 13-vuotiaille käyttäjille henkilökohtaiseen käyttöön, ei kaupalliseen käyttöön.',
    'text' => '<h2> Palveluehdot </h2>
<h3> LUE NÄMÄ EHDOT ENNEN VERKKOSIVUSTON JA LAAJENNUSEN KÄYTTÖÄ. </h3>
<p> Nämä käyttöehdot on tehty sinun ja "Cursor Style" (“Palvelu”, “me” tai “Palvelu”) välillä. Seuraavat ehdot sekä kaikki asiakirjat, jotka ne nimenomaisesti sisällyttävät viittauksella (yhdessä nämä “Käyttöehdot”), säätelevät pääsyäsi ja käyttöäsi cursor.style -sivustoon ja sen selainlaajennuksiin, mukaan lukien kaikki sisältö, toiminnallisuus ja palvelut, joita tarjotaan palvelumme kautta (yhdessä “Palvelu”). </p>
<p> Käyttämällä verkkosivustoa tai laajennusta hyväksyt ja suostut noudattamaan näitä käyttöehtoja. Jos et hyväksy näitä käyttöehtoja tai <a href="/privacy"> Tietosuojakäytäntöämme </a>, sinun ei pitäisi käyttää verkkosivustoa ja laajennusta. </p>
<p> Tätä palvelua tarjotaan ja se on saatavilla vain 13-vuotiaille ja sitä vanhemmille käyttäjille henkilökohtaiseen käyttöön, ei kaupalliseen käyttöön. Käyttämällä tätä Palvelua vakuutat ja takaat, että olet (I) 13-vuotias tai vanhempi, (II) sinulla ei ole lakia, joka kieltäisi sinua käyttämästä verkkosivustoa, (III) käytät Palvelua vain henkilökohtaiseen käyttöön. Jos et täytä näitä vaatimuksia, sinun ei pitäisi käyttää Palvelua. </p>
<p> Voimme muuttaa ja päivittää näitä käyttöehtoja ajoittain oman harkintamme mukaan. Kaikki muutokset tulevat voimaan välittömästi julkaisun jälkeen. Jatkuva Palvelun käyttö muutettujen käyttöehtojen julkaisemisen jälkeen tarkoittaa, että hyväksyt ja suostut muutoksiin. Sinun odotetaan käyvän tällä sivulla usein pysyäksesi ajan tasalla mahdollisista muutoksista, koska ne sitovat sinua. </p>
<p> Pidätämme oikeuden peruuttaa tai muuttaa tätä verkkosivustoa ja laajennusta, kaikkia palveluja tai materiaaleja, joita tarjoamme verkkosivustolla ja laajennuksessa, oman harkintamme mukaan, ilman ennakkoilmoitusta. Emme takaa, että sivustomme, laajennuksemme tai mikään sen sisältö on aina saatavilla tai että se ei keskeydy. Emme ole vastuussa, jos jostain syystä kaikki tai osa Palvelusta ei ole saatavilla milloin tahansa tai minkä tahansa ajanjakson aikana. Ajoittain saatamme rajoittaa pääsyä tiettyihin verkkosivuston tai laajennuksen osiin tai koko Palveluun käyttäjille. </p>
<p> Olet vastuussa kaikkien tarvittavien toimenpiteiden tekemisestä varmistaaksesi, että sinulla on pääsy Palveluun. Varmistamalla, että kaikki henkilöt, jotka käyttävät Palvelua Internet-yhteytesi kautta, ovat tietoisia näistä käyttöehdoista ja noudattavat niitä. Saadaksesi pääsyn Palveluun tai joihinkin sen resursseista sinua voidaan pyytää antamaan tiettyjä tietoja tai muita tietoja. Hyväksyt, että kaikki tiedot, jotka annat meille käyttämällä tätä Palvelua tai muuten, mukaan lukien mutta ei rajoittuen kaikkien vuorovaikutteisten ominaisuuksien käyttöön Palvelussa, on <a href="/privacy"> Tietosuojakäytäntömme </a> alainen, ja hyväksyt kaikki toimenpiteet, joita toteutamme tietojesi suhteen. <a href="/privacy"> Tietosuojakäytäntöämme </a> mukaisesti. </p>
<p> Sinun tulee olla erityisen varovainen, kun syötät henkilökohtaisia tietoja Palveluun julkisella tai jaetulla tietokoneella, jotta muut eivät voi nähdä tai tallentaa henkilökohtaisia tietojasi. Verkkosivusto, laajennus ja kaikki sen sisältö, toiminnot ja ominaisuudet (mukaan lukien, mutta ei rajoittuen, kaikki tiedot, laajennus, teksti, kuvat, ja osoittimet, sekä niiden suunnittelu, valinta ja sijoittelu) kuuluvat “Cursor Style”, sen lisenssinantajille tai muille tällaisten materiaalien toimittajille, joilla tekijänoikeus, tavaramerkki, patentti, liikesalaisuus ja muut immateriaalioikeuksia tai omistusoikeuksia suojaavat lait. </p>
<p> Nämä käyttöehdot antavat sinulle luvan käyttää verkkosivustoja vain henkilökohtaiseen, ei-kaupalliseen käyttöön. Et saa jäljentää, jakaa, muokata, luoda johdannaisia teoksia, julkaista uudelleen, ladata, tallentaa tai lähettää mitään materiaaleja verkkosivustollamme, paitsi seuraavissa tapauksissa: voit käyttää sitä henkilökohtaisiin tarpeisiisi, voit tulostaa tai ladata yhden kopion kohtuullisesta määrästä verkkosivuston ja laajennuksen tai niiden sisällön sivuja henkilökohtaiseen, ei-kaupalliseen käyttöön eikä edelleen jäljentämiseen, julkaisuun tai jakeluun. </p>
<p> Et saa muokata kopioita mistään materiaaleista tältä sivustolta tai laajennuksesta ja niiden sisällöstä. Poistaa tai muokata tekijänoikeus-, tavaramerkki- tai muita omistusoikeusilmoituksia tämän sivuston ja laajennuksen kopioista. Sinulla ei saa olla pääsyä verkkosivustojen tai laajennusten tai niiden osaan tai käyttää niitä kaupallisiin tarkoituksiin, samoin kuin mitään verkkosivuston tai laajennuksen kautta saatavilla olevia palveluja tai materiaaleja. </p>
<p> Jos haluat käyttää jotain verkkosivustojen tai laajennusten materiaalia, joka ei ole tässä osiossa, lähetä pyyntö Chrome Web Storen tukisivulla. </p>
<p> Jos tulostat, kopioit, muokkaat, lataat tai muutoin käytät tai tarjoat muille henkilöille pääsyn mihinkään verkkosivuston tai laajennuksen osaan käyttöehtoja rikkoen, oikeutesi käyttää verkkosivustoa ja laajennusta päättyy välittömästi, ja sinun on meidän harkintamme mukaan palautettava tai hävitettävä kaikki kopiot materiaaleista, joita sinulla on. Minkä tahansa laajennuksen verkkosivuston käyttö, jota nämä käyttöehdot eivät nimenomaisesti salli, rikkoo näitä käyttöehtoja ja voi loukata tekijänoikeuksia, tavaramerkkejä ja muita lakeja. </p>
<p> Nimi “Cursor Style”, logo “Cursor Style” ja kaikki siihen liittyvät nimet, logot, kuvat, osoittimet ja palvelunimet, mallit ja iskulauseet ovat “Cursor Style” tai sen tytäryhtiöiden tai lisenssinantajien tavaramerkkejä. Et saa käyttää tällaisia merkkejä ilman palvelun etukäteen antamaa kirjallista lupaa. Kaikki muut tämän verkkosivuston ja laajennuksen nimet, logot, tuotteiden ja palveluiden nimet, mallit ja iskulauseet ovat omistajien omistettuja tavaramerkkejä. Voit käyttää Palvelua vain laillisiin tarkoituksiin ja näiden käyttöehtojen mukaisesti. </p>
<h3>  Suostut olemaan käyttämättä Palvelua: </h3>
<ul>
<li> Millään tavalla, joka rikkoo kaikkia soveltuvia liittovaltion, alueellisia, paikallisia tai kansainvälisiä lakeja tai määräyksiä (mukaan lukien, mutta ei rajoittuen, kaikki lait tietojen tai ohjelmistojen viennistä Venäjälle ja muihin maihin). </li>
<li> Hyödyntämistä, vahingoittamista tai yrityksiä käyttää tai vahingoittaa alaikäisiä, altistaa heidät sopimattomalle sisällölle, pyytää tietoja, jotka tunnistavat heidät tai muutoin. </li>
<li> Lähettää, tietoisesti saada, ladata, käyttää tai käyttää uudelleen materiaaleja, jotka eivät ole näiden käyttöehtojen mukaisia. </li>
<li> Lähettää tai ostaa mainosten tai mainosmateriaalien lähettämistä ilman etukäteen antamaamme kirjallista suostumusta, mukaan lukien kaikki “pyytämättömät kirjeet”, “ketjukirjeet” tai “roskaposti” tai muut vastaavat tarjoukset. </li>
<li> Jotta voidaan esiintyä tai yrittää esiintyä “Cursor Style” -työntekijänä, toisena käyttäjänä tai muuna henkilönä tai organisaationa (mukaan lukien, mutta ei rajoittuen, sähköpostiosoitteiden tai lempinimien käyttöön, jotka liittyvät mihinkään edellä mainituista). </li>
<li> Osallistuminen muihin toimiin, jotka rajoittavat tai estävät Palvelun tai kenenkään käytön tai jotka, kuten me määritämme, voivat vahingoittaa Palvelua tai Palvelun käyttäjiä tai asettaa heidät vastuuseen. </li> </ul>
<h3> Lisäksi SIINÄ SUOSTUT NOT: </h3>
<ul>
<li> Käyttää Palvelua millään tavalla, joka voi poistaa käytöstä, ylikuormittaa, vahingoittaa tai heikentää sivuston toimintaa, laajentaa tai häiritä minkään muun osapuolen Palvelun käyttöä, mukaan lukien heidän mahdollisuutensa osallistua reaaliaikaisiin toimintoihin Palvelun kautta. </li>
<li> Käyttää automaatiotyökaluja, prosesseja tai keinoja päästäkseen Palveluun mihin tahansa tarkoitukseen, mukaan lukien Palvelun materiaalien valvonta tai kopiointi. </li>
<li> Käyttää mitään manuaalista prosessia materiaalin seurantaan tai kopiointiin Palvelussa tai muihin luvattomiin tarkoituksiin ilman etukäteen antamaamme kirjallista suostumusta. </li>
<li> Käyttää laitteita, ohjelmistoja tai menettelytapoja, jotka häiritsevät Palvelun normaalia toimintaa. </li>
<li> Esitellä viruksia, troijalaisia hevosia, matoja, logiikkapommeja tai muita materiaaleja, jotka ovat haitallisia tai teknologisesti haitallisia. </li>
<li> Yrittää saada luvaton pääsy, häiritä, vahingoittaa tai häiritä mitä tahansa Palvelun osaa, palvelinta, jolla Palvelu on tallennettu, tai mitään palvelinta, tietokonetta tai tietokantaa, joka on yhteydessä Palveluun. </li>
<li> Hyökätä Palveluun palvelunestohyökkäyksellä tai hajautetulla palvelunestohyökkäyksellä. </li> </ul>
<p> Palvelussa tai sen kautta annetut tiedot annetaan vain yleisiin tiedotustarkoituksiin. Emme takaa tämän tiedon tarkkuutta, täydellisyyttä tai hyödyllisyyttä. Luot tällaisiin tietoihin yksin omalla vastuullasi. Vapautamme kaiken vastuun ja vastuun, joka johtuu siitä, että sinä, muut Palvelun vierailijat tai kukaan, jolla voi olla tietoa sen sisällöstä, luottaa tällaisiin materiaaleihin. </p>
<p> Tähän Palveluun sisältyy kolmansien osapuolten tarjoamaa sisältöä, mukaan lukien muiden käyttäjien ja kolmansien osapuolten lisenssinantajien, syndikaattoreiden, aggregaattien ja/tai raportointipalvelujen toimittamat materiaalit. Kaikki näissä materiaaleissa esitetyt lausunnot ja/tai mielipiteet sekä kaikki artikkelit ja vastaukset kysymyksiin ja muu sisältö, lukuun ottamatta Palvelun tarjoamaa sisältöä, ovat yksinomaan näiden materiaalien tarjoavan henkilön tai organisaation mielipiteitä ja vastuita. Nämä materiaalit eivät välttämättä kuvasta Palvelun näkemyksiä. Emme ole vastuussa sinulle tai kolmannelle osapuolelle kolmansien osapuolten tarjoamien materiaalien sisällöstä tai tarkkuudesta. </p>
<p> Voimme ajoittain päivittää Palvelun sisältöä, mutta sen sisältö ei välttämättä ole täydellinen tai ajantasainen. Mikä tahansa Palvelun materiaali voi olla vanhentunut milloin tahansa, emmekä ole velvollisia päivittämään tällaista materiaalia. Voimme päivittää, muokata, muuttaa tietoja ja sisältöä verkkosivustolla ja laajennuksessa, tehdä muutoksia ja päivityksiä oman päätöksemme mukaisesti. </p>
<p> Kaikki tämän Palvelun kautta keräämämme tiedot ovat Tietosuojakäytäntömme alaisia. Käyttämällä Palvelua suostut kaikkiin toimiin, joita teemme tietojesi suhteen <a href="/privacy"> Tietosuojakäytännön </a> mukaisesti. </p>
<p> Lisäehdot voivat koskea myös tiettyjä Palvelun osia, palveluita tai ominaisuuksia. Kaikki tällaiset lisäehdot sisällytetään täten viitteellä näihin käyttöehtoihin. Voit linkittää verkkosivustoomme tai laajennukseemme, jos teet sen rehellisesti ja lainmukaisesti etkä vahingoita mainettamme tai käytä sitä, mutta sinun ei pitäisi asettaa linkkiä tavalla, joka tarjoaa minkäänlaista assosiaatiota, hyväksyntää tai tukea puoleltamme ilman kirjallista suostumustamme. </p>
<p> Palvelu sisältää linkkejä muille sivustoille ja resursseille, jotka kolmannet osapuolet tarjoavat, nämä linkit annetaan vain avuksesi. Tähän sisältyvät mainoksissa olevat linkit, mukaan lukien bannerimainokset ja sponsoroidut linkit. Emme hallitse näiden sivustojen tai resurssien sisältöä eivätkä ole niistä vastuussa tai mistään menetyksistä tai vahingoista, jotka voivat johtua niiden käytöstä. Jos päätät päästä Palveluun liittyville kolmansien osapuolten verkkosivustoille, teet sen omalla vastuullasi näiden verkkosivustojen käyttöehtojen mukaisesti. Pidätämme oikeuden peruuttaa luvan linkittää ilman ennakkoilmoitusta. </p>
<p> Ymmärrät, että me emme voi emmekä takaa tai takaa, että Internetin tai verkkosivustojen kautta ladattavissa olevat tiedostot eivät sisällä viruksia tai muuta haitallista koodia. Olet vastuussa menettelyjen ja tarkastuspisteiden toteuttamisesta, jotka riittävät täyttämään erityiset vaatimuksesi virustorjunnasta ja tietojen syötön ja tulostuksen tarkkuudesta, sekä säilyttämään ulkoiset välineet sivustollemme kaikkien kadonneiden tietojen palauttamiseksi. EMME OLE VASTUUSSA MISTÄÄN VAHINGOISTA TAI VAMMOISTA, JOTKA AIHEUTUVAT PALVELUN KAUTTA HANKITUISTA JAKELUSTA, VIRUKSISTA TAI MUISTA TEKNISTEN HAITTAOHJELMISTEN, TAI LATTAAMASTA MISTÄÄN TÄHÄN TAI MUILLE VERKKOSIVUSTOILLE JULKAISTUSTA MATERIAALISTA, JOTKA VOIVAT Tartuttaa TAI VAHINGOITTAA TIETOKONELASI, TIETOKONEOHJELMISTOJA TAI TIETOJA. </p>
<p> KÄYTÄT PALVELUA, SEN SISÄLTÖJÄ JA KAIKKIA PALVELUN KAUTTA HANKITTUJA PALVELUITA TAI KOHTEITA OMAN VASTUULLASI. PALVELU, SEN SISÄLLÖT JA KAIKKI VERKKOSIVUSTON JA LAAJENNUSTEN KAUTTA HANKITUT PALVELUT TAI KOHTEET TARJOTAAN “SELLAISENAAN” JA “SAATAVILLA” -EHTOINA, ILMAN MITÄÄN TAKUUTA. MIKÄÄN HENKILÖ, JOKA ON YHTEYDESSÄ PALVELUUN, EI ANNA MITÄÄN TAKUUTA TAI VAKUUTUSTA PALVELUN TÄYDELLISYYDESTÄ, TURVALLISUUDESTA, LUOTETTAVUUDESTA, LAADUSTA, TARKKUUDESTA TAI SAATAVUUDESTA. ILMAN YLLÄ OLEVAA RAJOITUSTA, EI “CURSOR STYLE” EIKÄ NIIN KAIKKESI “CURSOR STYLE” -ASETUKSIIN LIITTYVÄT EDUSTAJAT EIVÄT TAKAA SITÄ, ETTÄ SIVUSTO, LAAJENNUS, SEN SISÄLTÖ TAI MIKÄÄN KORJAUS PITÄISI AIEMMIN OLLA SAATAVILLA, KORJATA, ETTÄ LAAJENNUKSEMME, SIVUSTO TAI PALVELIN, JOKA SIJOITTAA SEN, ON ILMAN VIRUKSIA TAI MUITA HAITALLISIA KOMPONENTTEJA TAI TÄMÄ VERKKOSIVUSTO TAI MITÄÄN SUORITETUISTA PALVELUISTA TAI KOHTEISTA, ENNALTA MÄÄRÄTTYNÄ.
<p> Missään olosuhteissa PALVELU, SEN SIDOSYRITYKSET TAI LISENSSINANTAJAT, PALVELUT, TYÖNTEKIJÄT, EDUSTAJAT, VIRKAMIEHET tai JOHTajat EIVÄT OLE VASTUUSSA MISTÄÄN VAHINGOISTA, JOTKA PALVELU VASTAA MITÄÄN VAHINGONKORVAUSVELVOITUKSESTA. TAI MUISTA VERKKOSIVUSTOISTA TAI MISTÄÄN PALVELUSSA TAI MUILLA VERKKOSIVUSTOILLA HAETUISTA TAVAROISTA TAI KOHTEISTA, MUKAAN LUKIEN MITÄÄN SUORIA, ERITYISIÄ TAI VÄLILLISIÄ VAHINKOJA, MUKAAN LUKIEN HENKILÖVAHINKOJA, tunne-elämällisiä häiriöitä, VAHINGONKORVAUKSESTA TAI ODOTUSSAVUKSISTA, KÄYTÖN, TIETOJEN TAI MUUN EHTOJEN. MÄÄRITELMÄ EI VAIKUTA MIHINKÄÄN VASTUUSEEN, JOTA EI VOA SULKEA TAI RAJOITTAA SOVELLETTAVAN LAIN MUKAISESTI, JOHON VOI KUULUA PETOS. </p>
<p> Suostut suojaamaan, korvaamaan ja puhdistamaan “Cursor Style”, sen tytäryhtiöt, lisenssinantajat ja palveluntarjoajat sekä sen ja niiden vastaavat virkamiehet, johtajat, työntekijät, urakoitsijat, edustajat, lisenssinantajat, toimittajat, tehtävät ja kaikista vaateista ja vastuista, oikeudenkäyntien menetyksistä, kustannuksista, kuluista tai palkkioista (mukaan lukien asianajajapalkkiot), jotka johtuvat tai liittyvät näiden käyttöehtojen rikkomiseen tai Palvelun käyttöön, mukaan lukien mutta ei rajoittuen sisällön, palvelujen ja verkkosivuston tai laajennusten tuotteiden käytöstä, paitsi näissä käyttöehdoissa nimenomaisesti määriteltyyn tai tietojen käytön, jotka Palvelusta saatu. </p>
<p> Jos jokin näistä käyttöehdoista todetaan pätemättömäksi, laittomaksi tai täytäntöönpanukelvottomaksi tuomioistuimen tai muun toimivaltaisen tuomioistuimen toimesta mistä tahansa syystä, tällainen määräys on kumottava tai rajoitettava vähimmäismäärään, jotta käyttöehtojen muut määräykset jatkuvat kokonaisuudessaan. Käyttöehdot, Tietosuojakäytäntömme ja tapahtumien rekisteröintiehdot muodostavat ainoan ja täydellisen sopimuksen sinun ja ”Cursor Style” -yrityksen välillä Palvelusta ja korvaavat kaikki aiemmat ja samanaikaiset sopimukset, sopimukset, vakuudet ja takuut, sekä kirjalliset että suulliset, Palvelusta. </p>
<p> Kaikki arvostelut, kommentit, teknisen tuen pyynnöt ja muut Palvelua koskevat viestit tulee osoittaa “Cursor Style” -tukisivulle Chrome Web Storessa. </p> ',
];
