<?php

return [
    'halo_descr' => 'Halo ni franchise ya vyombo vya habari vya fantasy ya mapigano iliyoundwa na Bungie. Inategemea trilogy ya asili ya michezo ya video ya mchezo wa risasi wa mtu wa kwanza. Njama inazunguka matukio yanayotokea katika maisha ya Master Chief, mmoja wa kikundi cha wanajeshi wakuu waliopewa jina la Spartans, na rafiki yake, akili bandia Cortana. Mafanikio ya michezo yamesababisha upanuzi wa franchise katika vyombo vingine vya habari: ulimwengu wa Halo kwa sasa unajumuisha vitabu vingi, riwaya za picha, katuni, filamu fupi, uhuishaji, na filamu za kipengele.',
    'halo_short_descr' => 'Gusa kishale cha artifact, labda wewe ndiye mteule',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'Wanasesere wa LOL Surprise waliangukia kwa mapenzi na watoto na walishinda mioyo yao kutoka dakika za kwanza. Na hili halishangazi, kwa sababu mafanikio kama haya yanategemea siri, matarajio ya muujiza, mshangao mzuri, ambao unafurahisha sio tu watoto, bali pia wazazi wao. Siri ya zawadi hiyo inafunuliwa kwa mtoto tu baada ya kufungua mwisho. Kwa hali yoyote, wanasesere wa LOL ni muundo wa kuvutia, fitina, idadi kubwa ya vifaa vya kushangaza na vya kweli na mambo madogo mazuri, na pia ubora wa juu wa utengenezaji na maelezo ya toy.',
    'lol_surprise_short_descr' => 'Wapenzi wazuri kwa wataalamu wa mambo ya kushangaza mazuri',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Mfululizo huo unahusu shindano ambapo wachezaji 456, ambao wote wamo katika deni kubwa la kifedha, huhatarisha maisha yao kucheza mfululizo wa michezo ya watoto hatari kwa nafasi ya kushinda zawadi ya bilioni. Ndani yake, zawadi ya kuvutia inawasubiri na hatari kubwa za mauti. Kichwa cha mfululizo huo kinatokana na mchezo wa watoto wa Korea uliopewa jina sawa. Hwang alikuwa amechukua wazo hilo kulingana na mapambano yake ya kiuchumi mapema maishani mwake, na vilevile tofauti ya darasa nchini Korea Kusini na ubepari.',
    'squid_game_short_descr' => 'Chagua uso sahihi wa mchezaji unapocheza kamari yote',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter ni mhusika mkuu wa mfululizo wa riwaya na mwandishi wa Kiingereza JK Rowling. Siku yake ya kumi na moja ya kuzaliwa, Harry anajifunza kwamba yeye ni mchawi na ameelezwa kwa mahali katika Shule ya Uchawi ya Hogwarts, ambapo atafanya uchawi chini ya uongozi wa mkuu wa shule Albus Dumbledore na maprofesa wengine wa shule. Harry pia anagundua kuwa tayari anajulikana katika jamii ya kichawi ya riwaya hiyo, na kwamba hatima yake imeunganishwa na hatima ya Voldemort, mchawi mkuu wa giza hatari.',
    'harry_potter_short_descr' => 'Utafanya nini na wand wa kichawi kutoka kwa mkusanyiko wa kielekezi cha Harry Potter?',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics ni kampuni ya kuchapisha katuni inayojulikana kwa kuunda mashujaa wakubwa maarufu kama Spider-Man, Iron Man, Captain America, Hulk, Thor, the Avengers, the Guardians of the Galaxy, the X-Men, the Fantastic Four, na Deadpool. Waharibifu wanaojulikana zaidi wa Marvel ni pamoja na Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom, na Magneto. Marvel Comics na DC Comics wameshirikiana katika miradi kadhaa ya mseto pamoja na pia kuanzisha alama ya Amalgam Comics iliyokaa kwa muda mfupi kwa makusudi.',
    'marvel_comics_short_descr' => 'Shujaa anaishi ndani ya kila mmoja wetu - chagua wako',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Karibu tena kwenye Ufalme wa Cookie katika Cookie Run: Kingdom na Devsisters, mchezo wa kupendeza wa mkakati wa RPG uliowekwa katika ulimwengu wa Cookie Run. Sasa kwa kuwa GingerBrave amemtoroka mchawi mwovu, ni wakati wake wa kujenga timu ya Cookies na kuanza jitihada ya kujenga upya Ufalme wa Cookie ambao umeanguka. Fichua ukweli nyuma ya anguko la Ufalme na weka pamoja kikosi cha Cookies wenye nguvu zaidi wa Ufalme ili kuwashinda nguvu za giza ambazo zinataka kumzuia GingerBrave asitimize hatma yake.',
    'cookie_run_kingdom_short_descr' => 'Wapiganaji wadogo sawa moja kwa moja kutoka kwenye tanuri',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact ni mchezo wa matukio ya ulimwengu wazi. Hii inamaanisha kuwa mazingira mapya na ya kupendeza yanakungoja upande mwingine wa mto au mlima, unahitaji tu kutumia nguvu zako kwa busara. Ukikutana na mzungu wa hadithi anayezurura au utaratibu wa ajabu, thubutu na jaribu kuchambua siri yao. Lakini wanachoahidi - shida au mshangao mzuri - ni wewe tu unaweza kujua! Kwenye bara kubwa la Teyvat, utatembelea falme saba, utapata masahaba wenye ujuzi mbalimbali, na kupigana dhidi ya maadui wenye nguvu kutafuta mpendwa aliyepotea.',
    'genshin_impact_short_descr' => 'Kuwa Mwalimu wa Kimsingi wa Falme Saba',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Wakati unabii wa zamani unatimia na ufalme unazama katika kumbatio la majira ya baridi, mashujaa watatu wasioogopa - Princess Anna, Kristoff jasiri na kulungu wake mwaminifu Sven - huenda milimani kumtafuta dada wa Anna, Elsa, ambaye anaweza kuondoa uchawi wa kutisha kutoka nchini. Njiani, mambo mengi ya kushangaza na matukio ya kusisimua yanawasubiri. Kukutana na majini wa ajabu, kukutana na mtu wa theluji mrembo anayeitwa Olaf, vilele vya milima vilivyopinda kuliko Everest na uchawi mwingi. Mashujaa wanapaswa kupinga nguvu kubwa ili kuokoa ufalme na wale ambao ni wapenzi kwao.',
    'frozen_short_descr' => 'Kuvunja barafu ni rahisi na mkusanyiko wa kielekezi cha Frozen',
    'frozen' => 'Frozen',
    'stranger_things_descr' => 'Zaidi ya miezi sita imepita tangu fainali ya msimu wa tatu. Joyce, Will, Eleven na Jonathan wamehamia California ambapo msichana ananyanyaswa shuleni. Wengine wanaanza kupambana na monster mpya kutoka ulimwengu sambamba ulioonekana huko Hawkins. Aliitwa Vecna ​​baada ya mhusika wa mchezo wa bodi ya Dungeons & Dragons. Inawaathiri vijana kisaikolojia, kisha kiakili huingia akilini na kuua. Sambamba, Joyce na Murray wanagundua kwamba Jim Gopper yupo hai na wanamfuata hadi gerezani la Soviet huko Kamchatka. Na Eleven atalazimika kurudi na kuongeza nguvu zake, lakini pia kujifunza jukumu lake muhimu katika kuunda monster huyo huyo huko Gokins.

Waandishi hawakubadilisha mbinu ya njama waliyoipenda misimu michache iliyopita. Katika msimu wa nne, waligawanya kundi kubwa la wahusika wakuu katika vikundi, walikuja na kazi ngumu kwao, na mwishoni walijenga hadithi zao pamoja katika mwisho wa kushangaza. Tunakupa uelewe matukio haya yote kwa undani kwa msaada wa mkusanyiko wa kisa cha Stranger Things.',
    'stranger_things_short_descr' => 'Nini kitatokea kinachofuata? - Visahihishi vya Stranger Things 4',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_short_descr' => 'Linda kitanda chako na kielekezi cha Roblox Bed Wars',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'Siku ya kuzaliwa ya Naruto Uzumaki, pepo wa hadithi, Mbweha Mwenye Mkia Tisa, alishambulia kijiji kinachoitwa Konoha. Hokage wa Nne, kwa gharama ya maisha yake, aliokoa kijiji kwa kumfunga pepo huyo kwa Naruto mchanga, bila kujua akimfanya asumbuke na chuki kutoka kwa wanakijiji wenzake.
Licha ya ukosefu wake wa talanta katika maeneo mengi ya ninjutsu, kutotulia na kujivuna, Naruto ana ndoto ya kuwa Hokage, ninja hodari zaidi katika kijiji hicho. Akitamani kutambuliwa ambako hakupata, anafanya kazi kwa bidii na kufanya mazoezi pamoja na wenzake Sasuke Uchiha na Sakura Haruno, pamoja na mshauri wake Kakashi Hatake. Yeye na washirika wake watapaswa kupitia mengi njiani kuelekea ndoto zao walizozipenda: vita, mapenzi, urafiki, usaliti, kiu ya nguvu. Mkusanyiko wa kielekezi cha Naruto anime utakusaidia kuzunguka njia yako mwenyewe!',
    'naruto_anime_short_descr' => 'Tembea njia yako ya ninja na kielekezi cha Naruto anime',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'Hatua hufanyika wakati wa enzi ya Taisho. Tangu zamani, kumekuwa na uvumi kwamba mapepo ya humanoid huishi msituni, ambayo hula watu na kutembea usiku, wakitafuta mwathirika mpya. Lakini... ni hadithi tu, sivyo?..

Tanjiro Kamado ni mtoto mkubwa wa kiume katika familia yake, ambaye alimpoteza baba yake na alishughulikia familia yake. Siku moja anaenda mjini jirani kuuza mkaa. Akirudi asubuhi, kijana anagundua picha ya kutisha mbele yake: jamaa wote waliuawa kikatili, na manusura pekee ni Nezuko, dada mdogo aliyebadilishwa kuwa pepo, lakini ambaye bado hajapoteza ubinadamu wake wote.

Kuanzia wakati huu, Tanjiro na Nezuko wanaanza safari ndefu na hatari, ambayo kijana anakusudia kumtafuta muuaji na kujua jinsi ya kumponya dada yake. Lakini je, watoto wanaweza kushinda matatizo yote na kurudi nyumbani? Tayari unajua jibu, na ikiwa sivyo - badala yake weka visaidizi vya Demon Slayer, na wahusika kutoka kwa moja ya manga maarufu.',
    'demon_slayer_anime_short_descr' => 'Vigezo vya Demon Slayer - kwa wawindaji wa usiku halisi',
    'demon_slayer_anime' => 'Anime ya Demon Slayer',
    'bts_short_descr' => 'Kutana na sanamu zako ukitumia kielekezi cha BTS',
    'bts' => 'BTS',
    'miraculous_descr' => 'Miraculous: Hadithi za Ladybug na Cat Noir, inayojulikana zaidi kama Miraculous Ladybug na Cat Noir, ni matukio ya mashujaa kutoka katika katuni kuhusu wanafunzi wawili wa darasa ambao, chini ya barakoa, wanacheza nafasi ya watelezaji wa Paris kutoka kwa mtu mbaya ambaye katika kila kipindi huja na njia mpya ya kuumiza jiji. Miraculous imetengenezwa nchini Ufaransa kwa kutumia CGI na uhuishaji. Miraculous sio tu mfululizo wa uhuishaji, bali pia mkusanyiko wa vichekesho vilivyotolewa ulimwenguni kote. Mfululizo huu unapendwa sana na hadhira changa.

Kitendo hicho hufanyika huko Paris, ambapo Marinette na Adrian ni wanafunzi wa shule ya upili katika shule ya kisasa. Walipewa jukumu la kuwa mteule katika mapambano dhidi ya uovu, kuokoa mji wao. Lengo lao ni kuwalinda watu dhidi ya Akumas. Viumbe hawa wadogo katika mfumo wa vipepeo wana uwezo wa kukaa ndani ya mtu na kumfanya kuwa mtu mbaya.

Marinette anaweza kubadilika kuwa ladybug, na Adrian - kuwa Cat Noir, lakini kwa kushangaza, wakifanya kazi kwa jozi, hawajuani chini ya barakoa za mashujaa.

Msaidie Cat Noir na Ladybug kuokoa Paris na kielekezi chetu kilicho na wahusika unaowapenda. Ni mhusika gani utachagua kwa kielekezi? Je, kitakuwa kielekezi cha Miraculous Ladybug, au labda ladybug mdogo mzuri wa Tikki au kielekezi cha Cat Noir? Au labda Malkia Bee na kielekezi cha Rena Rouge? Uchaguzi ni wako!',
    'miraculous_short_descr' => 'Jiunge na safu ya mashujaa wakuu na mkusanyiko wa vibonye vya Lady Bug na Cat Noir',
    'miraculous' => 'Miraculous: Tales of Ladybug & Cat Noir',
    'talking_tom_descr' => 'Mfululizo huu unafuata maisha ya kila siku ya Talking Tom na marafiki zake. Tom na mshirika wake wa biashara mwerevu Ben wanatengeneza programu za simu na uvumbuzi mwingine ili kupata umaarufu na bahati na kujaribu kujionyesha kwa ulimwengu, lakini hii daima huishia vibaya. Mpenzi wa Tom, Angela, anajitahidi kuwa mwimbaji, haijalishi anafanya nini ili kufanikisha hilo. Jirani wa Tom, Ginger mara nyingi huja hapa kucheza michezo ya mzaha. Rafiki bora mvivu na anayeishi naye Hank hukaa nyumbani, anatazama TV SANA. Na nyota wa zamani wa pop Becca Sparkles amekuwa mshirika mpya wa Angela na anaonekana kuangukia kwa Hank. Hata hivyo, haijalishi mambo ni mabaya vipi, ya maumbo na ukubwa wote, iwe ni Mkurugenzi Mtendaji mwovu, jirani mpya wa ajabu wa Tom, au ajali tu katika ubunifu mpya wa Ben, genge litafurahi haijalishi nini, na daima kumbuka jambo moja linalowaweka pamoja: urafiki haukomi, kama tu upendo wetu kwa wahusika wa mfululizo huu haukomi, kwa hivyo sasa unaweza kujiwekea kielekezi cha Talking Tom au kielekezi cha Ben, au labda kielekezi cha Angela, kielekezi cha Oliver!',
    'talking_tom_short_descr' => 'Hebu tuzungumze kuhusu mhusika unayempenda katika Mkusanyiko wa Kielekezi cha Talking Tom',
    'talking_tom' => 'Talking Tom and Friends',
    'lego_descr' => 'Kampuni ya LEGO Group ilianzishwa mnamo 1932 na wakati huo ilikuwa na watu 7 tu. Lengo la timu ya Lego lilikuwa kuunda vifaa vya kuchezea ambavyo vinakuza ubunifu, mawazo, na ujanja wa mtoto. Jambo la kushangaza, tangu kuanzishwa kwake mnamo 1949, vifaa vya LEGO katika aina zake zote vimesalia kuendana. Vitu vyote vilivyoundwa baadaye bado vinaendana na vitu ambavyo vinatolewa leo, licha ya mabadiliko katika muundo na umbo kwa miaka.

Mkopo wa LEGO ni msingi, ambao ni kizuizi cha plastiki mashimo ambacho kinaunganishwa na matofali mengine kama hayo. Lakini seti za Lego pia zina sehemu zingine, magurudumu, takwimu, majukwaa, na hata saketi za elektroniki zenye sensorer na motors za umeme. Unaweza kukusanya mifano ya magari, ndege, treni, meli, majengo, roboti. LEGO inashikilia wazo la ushirika, ambalo linaonyesha wazi kwa watoto jinsi ya kutatua shida fulani, kukuza mawazo, ujuzi mzuri wa mikono na ujuzi wa mkutano. Matofali ya LEGO yametengenezwa kwa usahihi wa ajabu na yanafaa pamoja kikamilifu kwa usahihi wa ajabu wa mikroni 10.

 Hivi majuzi, hadithi nyingi maarufu za Lego za 3D zimeundwa, ambapo wahusika kutoka seti huja hai na kuwa washiriki wa matukio ya ajabu. Ikiwa unataka kizamua kizuri, utapata wahusika wengi kutoka kwa safu ya Runinga ya Lego na filamu za katuni katika mkusanyiko wetu wa Lego Cursors. Lego Ninjago Cursor, Lego Batman Cursor, Lego Ninjago Cursor, Lego Wyldstyle Cursor na mengi zaidi.',
    'lego_short_descr' => 'Jenga kivinjari chako cha ndoto ukitumia mkusanyiko wa kielekezi cha Lego',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Baada ya ufadhili mzuri wa Kickstarter, mnamo 2017, Team Cherry ilitoa mchezo wa jukwaa mbalimbali la PC Hollow Knight. Hii ni hadithi ya knight asiye na jina na uvumbuzi wake katika ufalme wa wadudu wa Hallownest. Mchezo huo uilitambuliwa kwa haki kama mmoja wa bora katika aina ya metroidvania.

Uchezaji wa Hollow Knight unategemea uchunguzi wa ulimwengu wa mchezo. Kushinda vikwazo, kutatua mafumbo na kutafuta siri, pamoja na kupigana na maadui. Mchezaji ana seti ya kipekee ya uboreshaji na mbinu za kuchunguza ulimwengu na kupigana katika vita. Akisonga kutoka eneo moja hadi jingine, mchezaji huwashinda wakubwa na kupata uboreshaji muhimu ili kusonga mbele zaidi. Matokeo yake, wachezaji wanapaswa kutembelea maeneo yaliyopita tayari ili kutafuta siri na kupitia hadithi. Na pia ni ya kusisimua kwa sababu maeneo hubadilika kila wakati, ikileta mshangao na uzoefu mpya. Mchezo unaweza kuchezwa kwa njia tofauti, kwa sababu kuna njia kadhaa tofauti kati ya maeneo. Unapopitia hadithi, unafungua ramani ya eneo, lakini kwanza unahitaji kupata ramani.

Silaha kuu ya shujaa ni msumari, ambao unafanana na upanga, silaha zinaweza kuboreshwa na mhunzi, na vile vile kujifunza ujuzi tofauti katika kutumia silaha, ambayo huongeza aina ya mashambulizi. Kwa kushambulia maadui, unakusanya rasilimali maalum, ambayo baadaye inaweza kutumika kwa uboreshaji au uponyaji.
Furahia kucheza Hollow Knight na usisahau kutoa cursors zetu za Hollow Knight na mhusika unayempenda. Mkusanyiko wetu unajumuisha Cursor ya Mister Mushroom, Cursor ya Quirrel, Cursor ya Sindano ya Hornet, Cursor ya Msumari Mzee, Cursor ya Myla, na zingine.',
    'hollow-knight_short_descr' => 'Jaribu kutopotea katika ufalme wa wadudu kwa kutumia mkusanyiko wa kielekezi cha Hollow Knight',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman ndiye mhusika mkuu katika mfululizo huo. Stikmin, ambaye hapo awali hakuwa na jina, alianza kama mwizi mdogo, akiwa na hamu ya kupata pesa rahisi haraka. Hata hivyo, baada ya kutoroka kutoka gerezani la West Mesa, mabadiliko mengi yanatokea katika maisha yake, na anakuwa mhalifu maarufu baada ya kuiba Almasi ya Tunisia. Henry ana chaguo - kuwa wakala wa serikali aliyefanikiwa, mwindaji wa fadhila, kiongozi wa shirika la uhalifu, cyborg, au kuendelea na njia ya uhalifu peke yake. Mchezo unawafurahisha mashabiki wa aina hii na matukio na mafumbo mengi, na utapata mkusanyiko wetu mpya wa viboreshaji vya Henry Stickman na wahusika wake wa kuchekesha, ikiwa ni pamoja na kiboreshaji cha Henry Stickmin, kiboreshaji cha Charles Calvin, kiboreshaji cha Reginald Copperbottom, kiboreshaji cha Mkono wa Kulia, kiboreshaji cha Ellie Rose na wengine!',
    'henry-stickmin_short_descr' => 'Panga kutoroka kwako kutoka kwa kuchoka na Mkusanyiko wa Visahihisha vya Henry Stickman',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'Mchezo maarufu sana wa mtandaoni wa Adopt Me ulizinduliwa mwaka wa 2017 na ukawa maarufu zaidi kwenye jukwaa la michezo la Roblox. Kiini cha mchezo huu ni rahisi sana - pata mayai yenye wanyama vipenzi na uwatunze.

Wanyama vipenzi pepe wamegawanywa katika madarasa 5, baadhi yao ni nadra sana na ghali, ilhali wengine ni rahisi sana kupata. Haya ni makundi yasiyo ya kawaida, kama vile Mbwa wa Bluu, Kawaida, kielekezi cha panya cha Nadra kama vile, kwa mfano, kielekezi cha panya cha Adopt Me Monkey, na pia ambazo ni nadra sana, kama vile kielekezi cha Koala, na Hadithi, kielekezi cha Dragon na Unikoni ya Adopt me. Ikiwa mchezaji ana wanyama vipenzi wazima wanne wa aina moja, wanaweza kuunganisha kwenye mnyama kipenzi wa neon, kama vile kielekezi cha mchezo cha Neon Horse au Adopt Me Neon Starfish. Kwa kuchanganya wanyama vipenzi wanne wa kawaida, unaweza kutengeneza mnyama kipenzi wa neon ambaye huangaza kweli, na kutoka kwa wanyama vipenzi wa neon unaweza kuunda mnyama kipenzi mkuu wa neon.

Ununuzi katika mchezo wa Adopt Me! hufanyika kwa sarafu pepe ya Roblox - kinachoitwa Robux, na mchezo pia una sarafu yake mwenyewe - Bucks. Kutunza mnyama wako kipenzi, pamoja na burudani, unaweza kupata pesa, mlisha tu, mweke kitandani au soma hadithi ya hadithi, kwa ujumla, mambo mengi ya kuvutia.

Sasa mashabiki wa mchezo wa Roblox "Adopt Me!" wanaweza kupamba kielekezi chao cha mchezo na mnyama kipenzi wanayempend!',
    'adopt-me_short_descr' => 'Furahia na wanyama kipenzi wazuri katika mkusanyiko wetu wa kielekezi cha mchezo wa Adopt Me!',
    'adopt-me' => 'Adopt me!',
    'among-us_descr' => 'Among Us inategemea mchezo maarufu wa kuigiza "Mafia". Ilipangwa kuwa mchezo huo utakuwa wa kipekee kwa vifaa vya mkononi, kwa sababu ulikuwa na ramani moja tu. Mchezo ulikua maarufu haraka. Baadaye, timu ya maendeleo iliongeza modi ya wachezaji wengi, na ramani mbili za ziada zilitolewa mnamo 2019.
Among Us ni mchezo wa mtu wa tatu kutoka juu unaomruhusu mchezaji kusonga pande zote. Wachezaji wanne hadi kumi wanaweza kucheza katika raundi moja. Mwanzoni mwa mchezo, kila mtu anapewa siri jukumu la msaliti au mwanachama wa wafanyakazi. Msaliti (katika tafsiri ya Kirusi "Msaliti") anaweza kujificha kwenye sehemu ya uingizaji hewa, kuhujumu na kuua wanachama wa wafanyakazi. Lengo lake ni kuharibu wanachama wote wa wafanyakazi, au kuharibu chombo cha anga kwa kuhujumu. Lengo la wafanyakazi wa meli ni kutatua mafumbo mbalimbali yaliyotayarishwa kwao mwanzoni mwa mchezo. Ikiwa kila mmoja wa wanachama wa wafanyakazi atamaliza kazi zote, wasaliti watashindwa. Pia, wafanyakazi wa meli wanaweza kupata ushindi kwa kuwaondoa wasaliti wakati wa kura.
Wasaliti wanaweza kuhujumu mara kwa mara na ikiwa hitilafu hazitatatuliwa kwa sekunde 30, wafanyakazi watashindwa. Kabla ya kuanza mchezo, unaweza kuchagua rangi ya mhusika unayechezea, bluu, nyekundu, njano, kijivu - chochote! Na usisahau kujiwekea kielekezi kinachofaa kutoka kwa mkusanyiko mpya wa Among Us!',
    'among-us_short_descr' => 'Usidanganywe katika mchezo huu tata wa anga na kielekezi cha Among Us',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Muumunaji wa "Steven Universe" alikuwa Rebecca Sugar. Anajulikana kwa kazi yake ya awali iitwayo Adventure Time. Kipindi cha kwanza cha Steven Universe kilizinduliwa kwenye jukwaa la video la YouTube katika majira ya kuchipua ya 2013. Lakini katika msimu wa vuli, kituo cha Kimarekani cha Cartoon Network kilianza kuirusha kwa watazamaji wake. Tangu wakati huo, misimu 6 imetolewa. Ya sita inaahidi kuwa ya mwisho.
Kwa upande wa mchezo wa mfululizo wa uhuishaji, inahusu timu ya Crystal Gems. Inaundwa na viumbe wa kigeni wenye majina ya kipekee: Pearls, Amethyst na Pomegranate. Lakini kuna mshiriki mwingine humo, katika jukumu ambalo mvulana wa kawaida Stephen anafanya. Pamoja wanatafuta monsters na kujaribu kuziondoa ili zisichukue Dunia kwa manufaa ya kibinafsi. Wanapingwa na Jasper na Peridot - wajumbe kutoka sayari yao ya nyumbani ambao wanataka kuwashinda Gems na kuwasha Cluster.
Ikiwa wewe ni shabiki wa Steven Universe na unataka kuona wahusika wa mfululizo wa uhuishaji popote unapoonekana, sakinisha kiendelezi cha Cursor Style! Kwa nini ufanye hivi? Unaweza kuongeza mkusanyiko uliojitolea kwa "Steven Universe" na kugeuza kielekezi cha panya cha kawaida kuwa mmoja wa wahusika unaowapenda.',
    'steven_universe_short_descr' => 'Fichua siri ya vito na kishale cha Steven Universe',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Mchekeshaji wa uhuishaji unaoitwa "Family Guy" katika historia yake yote ya kuwepo kwake mara 4 alishinda Tuzo ya Emmy na mara 3 "Annie". Mfululizo wa uhuishaji unadhihaki mada chungu za jamii ya Amerika, kama vile: ufeministi, utumwa, unene kupita kiasi, siasa, n.k. Tofauti na kazi nyingine, viingizi vyenye vichekesho na kejeli hutumiwa hapa. Zaidi ya hayo, katika visa vingi havijaunganishwa katika njama, lakini huwepo wenyewe.
Sehemu moja ya mfululizo wa uhuishaji inaundwa kwa zaidi ya miezi 10. Kwa nini muda mrefu sana? Kwa sababu uhuishaji wote huchorwa kwa mkono. Kwa sababu hii, baadhi ya matukio yaliyofunikwa na kazi yana muda wa kupoteza umuhimu. Lakini hata hivyo, mchekeshaji bado ni wa kupendeza sana na anapata upendeleo wa watazamaji ulimwenguni kote. Baada ya yote, ni nani hapendi kucheka vizuri kwa wanasiasa, watu mashuhuri au watu wanaofanya vituko vya porini na hivyo kushangaza au hata kuwashangaza watu wa kawaida.
Je, unapenda "Family Guy"? Una fursa ya kipekee ya kugeuza kishale cha panya cha kawaida kuwa mmoja wa wahusika wa mfululizo huu wa uhuishaji! Ninahitaji kufanya nini? Ingiza tu kiendelezi cha kivinjari cha “Cursor Style”, ongeza mkusanyiko uliowekwa kwa “Family Guy” kwake, na ufurahie kuzaliwa upya kwa hadithi!',
    'family_guy_short_descr' => 'Mkusanyiko wa kielekezi cha Family Guy kwa wataalamu wa ucheshi maalum',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Hakika umesikia usemi "Uzuri utauokoa ulimwengu"? Kwa hiyo, watu wengi, haswa wasichana, wanakubaliana na taarifa hii. Kwa hivyo, wanajitahidi kujizunguka na kila kitu kizuri zaidi na cha kupendeza kwa macho. Inaweza kuwa karatasi ya rangi ya pinki chumbani, vinyago laini, mito iliyochorwa na shanga, vito vya thamani, nk. Kutoka nje, yote yanaonekana ya kupendeza sana na hata ya kitoto kidogo. Lakini kila mmoja wetu ni mtoto mdogo mioyoni mwetu, kwa nini tusimruhusu aonyeshe mawazo yetu?
Upole ndani yetu unaweza kusababisha mengi. Kwa mfano, macho ya huruma ya paka ambaye anataka kupigwa au kulishwa. Upinde wa mvua wa rangi nyingi, ukichungulia baada ya mvua ya masika na kung\'aa na rangi zote kwenye jua. Mtoto ambaye alitibiwa chokoleti, na akaamua kuishiriki na mpenzi wake wa kike au wa kiume. Kuna sababu chache sana za kugusa, na tuliamua kuzitumia kama kielekezi.
Umechoka na mshale mweupe wa kuchosha katika kivinjari chako? Badilisha na kitu kizuri kutoka kwa mkusanyiko wetu! Kwa mfano, nyati ya pinki na nyeupe, nyanya ya huzuni, wingu la kutafakari, cactus ya miiba katika sura ya paka, au chochote unachotaka. Unachohitaji kufanya ni kusakinisha kiendelezi cha Cursor Style na kuongeza mkusanyiko wa kielekezi kizuri kwake. Na uzuri wa ulimwengu uishi kwa muda mrefu - uzuri!',
    'cute_cursors_short_descr' => 'Ulimwengu utakuwa mkarimu zaidi na mkusanyiko wa kielekezi cha kupendeza',
    'cute_cursors' => 'Vionyeshi Vizuri',
    'web_media_descr' => 'Katika hali halisi za kisasa, karibu kila mtu hutumia mtandao. Kuanzia watoto wachanga na kuishia na wastaafu. Mtu huendesha mtandao kwa kutumia kivinjari, mwingine hutazama video kwenye YouTube, na mtu fulani anahitaji Mtandao ili kuwasiliana na wapendwa wao. Yeyote kati ya watumiaji hawa hawezi kufikiria siku bila Mtandao Mpana wa Ulimwengu.
Watu wazee mara nyingi hukaa kwenye mtandao wa kijamii kama Facebook au VK. Pia huwasiliana mara kwa mara na watoto wao na wajukuu wao kwenye Skype. Hii ni rahisi sana ikiwa watoto na wazazi wanaishi katika miji tofauti au hata nchi tofauti.
Vijana wanapendelea kuwasiliana kupitia Viber au Telegram, kupakia picha kwenye Instagram, kucheka vichekesho vya FB. Video za YouTube za athari za watu zinapata mamilioni ya maoni, kama vile mizaha mbalimbali au majaribio ya kijamii. Katika Tik-Tok, mamia ya maelfu ya watu wanacheza, wanaonyesha hila za kichawi na kujieleza.
Je, unapendezwa au unatumia tu aina fulani ya rasilimali kutoka eneo la vyombo vya habari vya wavuti? Unataka kuondoa mshale wa panya unaochosha katika kivinjari chako? Kisha sakinisha kiendelezi na ubadilishe kielekezi chaguomsingi kwa ubunifu wetu! Inaweza kuwa kielekezi cha YouTube, kielekezi cha Viber, kielekezi cha Google Chrome, au rasilimali nyingine.',
    'web_media_short_descr' => 'Ishi kwa mdundo wa kisasa ukiwa na mkusanyiko wa kielekezi cha vyombo vya habari.',
    'web_media' => 'Vyombo vya Habari vya Mtandao',
    'bobs_burgers_descr' => 'Mfululizo wa uhuishaji wa Bob’s Burgers ni njama ya kazi ya uhuishaji na ukarism ulimwenguni. Na, kwa kuzingatia uteuzi wa Tuzo la Emmy na utambuzi wa kazi kama mojawapo ya katuni bora zaidi ulimwenguni kote, Bob\'s Snack alifanya kweli splash.
Njama ya mfululizo wa uhuishaji inazunguka familia ya Bob Belcher. Mtu huyu ndiye mmiliki wa mgahawa kwenye ghorofa ya kwanza, na kwenye ghorofa ya pili anaishi na wapendwa wake. Bob ana mke mchangamfu Linda na watoto 3: Gene, Louise na Tina. Mvulana anatamani kazi ya muziki, binti mkubwa Tina ni mwema sana, lakini hana urahisi, na mdogo - Louise bado ni mcheshi na mara nyingi huweka familia yake katika nafasi isiyofaa. Mshindani mkuu wa Bob’s Burgers ni Pizzeria ya Jimmy Pesto. Kama unavyoweza kudhani, mmiliki wa pizzeria hii anaitwa Jim, na yeye na Bob wanachukiana. Yote haya yalipigwa kwa njia ambayo yalionekana ya vichekesho, sio kwa uzito. Kwa hivyo, migogoro yao mingi husababisha tu tabasamu.
Ikiwa unapenda mfululizo wa uhuishaji “Bob\'s Burgers” na unataka kuona wahusika wake sio tu kwenye skrini ya kufuatilia au Runinga, sakinisha kiendelezi, ongeza mkusanyiko, na ubadilishe kishale cha panya kwenye kivinjari kwa mhusika yeyote katika katuni hii!',
    'bobs_burgers_short_descr' => 'Bob anatengeneza baga, na sisi tunatengeneza kursoru za Bob\'s Burgers',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'Historia ya mchezo wa video "Kirby" ilianza tayari katika miaka ya 90 ya karne iliyopita. Inajumuisha mfululizo mwingi ambao ulitengenezwa na Nintendo na Maabara ya HAL. Mchezo unalenga watoto kutoka mwaka mmoja na nusu hadi miaka 8. Umaarufu wake unaweza kuhukumiwa na idadi ya nakala zilizouzwa. Zaidi ya milioni 34 ulimwenguni.
Mhusika mkuu wa Kirby ni kiumbe wa pinki aliye na jina moja. Anaishi kwenye sayari inayoitwa Pop Star, na mara kwa mara hulinda kutoka kwa hatari mbalimbali. Kerby anaweza kuvuta pumzi katika vitu vingine na adui zake ili kisha kujifunza uwezo wao: mapigano ya mikono, umiliki wa upanga, kupumua kwa moto, n.k. Hata hivyo, roho nyekundu sio tu hupigana na maadui, lakini pia hutatua mafumbo mbalimbali, husafiri kwenda nchi nyingine na anaweza hata kuruka katika kiwango.
Unaweza kucheza mchezo huu wa video kwenye koni za Nintendo au Game Boy. Katika mfululizo wote kuna mashujaa wazuri, picha nzuri na nyimbo za kuchekesha. Kwa njia, kwa karibu miaka 30 tangu kutolewa kwa toleo la kwanza, ulimwengu ulifaulu kuona mfululizo 20 wa Kirby. Kiashiria hiki, pamoja na kiasi cha mamilioni ya dola za nakala zilizouzwa, kilisaidia mchezo kuwa katika TOP 50 ya michezo ya video iliyofanikiwa na inayotafutwa sana katika tasnia ya michezo.
Unampenda Kirby kwa hivyo ungependa kumwona mhusika huyu popote inapowezekana? Kisha tumia mkusanyiko wa Kirby na ubadilishe kielekezi cha panya cha kawaida kuwa mhusika mkuu wa mchezo wako wa video unaopenda! Tuna hakika kwamba utapenda muonekano mpya wa kielekezi.',
    'kirby_short_descr' => 'Jaribu kuvuta pumzi mkusanyiko mzima wa kursor ya Kirby',
    'kirby' => 'Kirby',
    'undertale_descr' => 'Zamani za kale, Dunia ilikuwa inakaliwa sio tu na watu, bali pia na wanyama. Kwa sababu ya kutokuelewana kati yao, vita vilizuka, ambavyo viliisha kwa manufaa ya wanadamu. Wafalme saba waliwafukuza wanyama chini ya ardhi na kuwafunga huko milele kwa spell ya kizuizi. Hata hivyo, kulikuwa na mlango mmoja tu wa Mlima Ebott, ambao mtoto alitumia. Ni kwa ajili yake kwamba utacheza kwa kuendesha mchezo wa kompyuta wa Undertale.
Mchezo huu uliandaliwa na Toby Fox - mwandishi programu maarufu kutoka Marekani. Mwanzoni, wamiliki wa kompyuta binafsi zinazoendesha Microsoft Windows na Linux OS wanaweza kuufurahia, na kisha zamu ya watumiaji wa consoles za michezo ilifika.
Lengo la mchezo huu ni nini? Wavulana husafiri kupitia ulimwengu wa chini ya ardhi unaokaliwa na wanyama. Baadhi yao wanakuwa na chuki mara moja, wakati wengine wanapenda kuzungumza. Mchezaji anaweza kuchagua moja ya tabia 2: kuepuka vurugu au kupigana. Katika kesi ya kwanza, kupita mchezo itakuwa rahisi, katika pili - kinyume chake ni vigumu zaidi. Plot na mwisho, ambayo inaweza matawi na kubadilika, pia inategemea uchaguli huu.
Ikiwa unapenda Underground Tale na ungependa kuona wahusika wake katika kivinjari chako, sakinisha ugani na ongeza mkusanyiko unaofaa wa viboreshaji! Geuza kielekezi cha panya kinachosumbua kuwa mmoja wa wanyama au mhusika mkuu wa Undertale!',
    'undertale_short_descr' => 'Ni wakati wa kutoka nje ya shimo kwa kutumia kielekezi cha Undertale',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune ni mchezo wa kuigiza nafasi uliotolewa kwa kompyuta miaka michache iliyopita. Ilitengenezwa na mpangaji programu huyo huyo aliyeunda Undertale. Walakini, michezo hii miwili karibu haifanani kwa kila mmoja, ingawa wana wahusika na maeneo kadhaa ya kawaida.
Kuna wahusika wakuu kadhaa katika Delta Rune. Huyu ni mwanafunzi Chris, ambaye anaweza kudhibitiwa, na monster mchanga Susie, asiyeweza kudhibitiwa. Wahusika wote wawili huanguka katika ulimwengu wa giza, ambapo wanakutana na mmoja wa wakaazi wake - Ralsay. Anawaambia kuwa kwa kweli wao ni viumbe vya nuru ambao wana dhamira - kukomesha mtiririko wa nishati nyeusi katika ulimwengu wa huzuni. Ili kufanya hivyo, wanahitaji kuokoa monsters za eneo hilo na kujaribu kutoshiriki katika vita nao, ingawa hii wakati mwingine ni ngumu sana kufanya.
Mchezaji ana chaguo rahisi: ama kuokoa viumbe vya giza, au kuwashambulia. Kwa kuwa Susie sio shabiki wa hatua za nusu, katika hali nyingi anachagua vita. Kwa hivyo, Chris hana chaguo ila kumsaidia mpenzi wake na kumsaidia katika vita.
Unapenda mchezo wa Deltarune? Kisha weka mtindo wa kishale chako cha panya kwenye kivinjari kwa mmoja wa wahusika wake! Unaweza kufanya hivyo na kiendelezi chetu. Isakinishe, ongeza mkusanyiko wa “Rune Delta” na uiwashe! Sasa mshale wako umeacha kuwa sawa na kila mtu mwingine, na umekuwa Chris, Susie au mmoja wa viumbe wa ulimwengu mweusi.',
    'deltarune_short_descr' => 'Zama katika ulimwengu mweusi na mkusanyiko huu wa kielekezi',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario ni mfululizo wa michezo ya kompyuta iliyotolewa na Nintendo. Mchezo wa kwanza na maarufu zaidi uliitwa Super Mario Bros. Iliona mwangaza mnamo 1985. Baadaye iliorodheshwa katika Kitabu cha Rekodi cha Guinness. Tangu wakati huo, michezo zaidi ya 20 imetolewa, kila moja ikiwa na njama yake. Mnamo 2019, toleo jipya lilionekana linaloitwa Super Mario Maker 2. Licha ya uboreshaji katika picha, mtindo na wahusika walibaki sawa, na hii inatokeza nostalgia kwa Super Mario wa miaka ya 80.
Mhusika mkuu bado ni seremala Mario. Katika njama ya lahaja ya mwisho ya mchezo, kasri la Princess halikuwa na jiwe lisilogeuzwa. Mario lazima aliijenge tena, akiwa amepata kabla yake sarafu ambazo zinalipwa kwake kwa kazi. Kwa jumla, mchezo huu una viwango zaidi ya 100 vya ugumu mbalimbali na uwezekano wa mabadiliko. Pia katika Super Mario Maker 2 kuna modes mpya za mchezo. Unaweza kucheza wanne kati yao mara moja na mara tu moja inapomaliza, kiwango kinazingatiwa kukamilika. Pia kuna modes kama vile: Mario Marathon, Duel na mbio za Ninjik.
Unapenda Super Mario na kila kitu kinachohusiana na mchezo huu mzuri? Kisha weka visaidizi vilivyotengenezwa kwa mtindo wa jukwaa hili! Tuna hakika kuwa utapenda kisaidizi cha Mario, kisaidizi cha Luigi, kisaidizi cha Princess Peach na visaidizi vingine ambavyo vinawasilishwa katika mkusanyiko wetu!',
    'super_mario_short_descr' => 'Songa kupitia ufalme wa uyoga na mkusanyiko wa kursor za Super Mario',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls iliundwa kwa pamoja na Shirika la Uandishi wa Habari la Televisheni la Disney na Alex Hirsch. Uzinduzi ulitolewa mwaka wa 2012 na ulionyeshwa kwenye Disney Channel. Msimu mzima wa kwanza wa mfululizo wa uhuishaji ulikuwa ukizunguka huko. Miaka miwili baadaye, msimu wa pili ulitoka, ambao watazamaji waliweza kuutazama kwenye chaneli iliyotangulia na kwenye Disney XD. Kwa bahati mbaya, mashabiki wa Gravity Falls hawakusubiri misimu ya tatu na inayofuata. Waumbaji waliamua kujizuia na misimu miwili bila muendelezo wowote.
Pia kuhusu njama ya picha hii ya uhuishaji, basi hatua zote hufanyika katika mji wa kubuni unaoitwa Gravity Falls. Mapacha wawili huja huko, ambao majina yao ni Mabel na Dipper. Wanakaa na binamu yao Stan. Ana duka lake mwenyewe la zawadi za watalii. Wakati kaka wamechoka na "kutofanya chochote", huenda kutafuta matukio. Mmoja wao anapata diary ya ajabu msituni, ambayo inasimulia kuhusu mambo ya ajabu ya mji huu. Mapacha wanaelekea kutafuta mwandishi wake na kukutana na viumbe na sehemu zisizo za kawaida. Ikiwa una nia ya mfululizo huu wa uhuishaji, na ulikuwa shabiki wa wahusika wake, tunakupendekeza mkusanyiko wetu wa vishale vya panya kwa mtindo wa Gravity Falls!',
    'gravity_falls_short_descr' => 'Anza safari na kielekezi cha panya cha Gravity Falls',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Kila mtu amesikia kuhusu mfululizo maarufu wa uhuishaji kama The Simpsons. Hata watu ambao hawajawahi kuonekana kama hii wanajua kuwepo kwa wahusika wa njano. Na mashabiki wanafurahishwa wakati msimu ufuatao wa katuni wanayoipenda unapotoka. Kwa njia, katika msimu wa vuli wa 2019, akaunti za msimu wa 31 zilitolewa. Na ya kwanza ilionekana kwenye skrini za televisheni nyuma mwaka 1989. Fox walianza kuionyesha na bado wanaendelea kuifanya kutokana na alama za juu na huruma ya hadhira.
The Simpsons ni aina ya kejeli ambayo inagusa mada muhimu. Hii inaweza kuwa mtindo wa maisha wa wastani wa Kimarekani, masuala ya kisiasa na kidini, hila za "nyota" za watu mashuhuri, uanaharakati wa wanawake, ndoa ya watu wa jinsia moja. Kwa ujumla, kila kitu kinachohusiana na matukio ya mitaa na kimataifa ambayo Marekani inashiriki.
Kitendo cha mfululizo wa uhuishaji kinafanyika katika mji usio na akili wa Springfield. Kwa kweli, kuna miji mingi yenye jina hilo nchini Amerika. Labda ndiyo sababu ilichaguliwa ili hadhira isihusishwe na kile kilichoendelea kwenye skrini na eneo maalum, lakini ilikisia tu wapi hii inaweza kuwa.
Uwezekano mkubwa wewe ni shabiki wa Simpsons. Vinginevyo, kwa nini ungesoma maandishi haya hadi mwisho? Na ikiwa ndivyo, basi una fursa ya kubadilisha kielekezi cha panya kilicho choka kuwa kielekezi ambacho kimetengenezwa kwa mtindo wa mfululizo huu wa uhuishaji.',
    'simpsons_short_descr' => 'Familia ndogo ya kufurahisha yenye vibonye vya Simpsons',
    'simpsons' => 'The Simpsons',
    'youtubers_descr' => 'Jukwaa la video la YouTube lilionekana mwaka 2005. Mwanzoni, video zilichapishwa hapo kwa ajili ya kujieleza au kutoa taarifa kuhusu kitu. Hata hivyo, baada ya muda, yote haya yalikua na kuwa biashara yenye faida, ambayo huleta maelfu ya, na wakati mwingine mamilioni ya dola kwa mwezi kwa watumiaji wa YouTube waliofaulu. Kadiri mwandishi wa vlog (mtu anayeendesha blogu ya video) alivyo maarufu, ndivyo anavyoweza kupata mapato kupitia kituo chake.
Je, mwandishi wa vlog wa miaka mitano anapata kiasi gani, ambaye wazazi wake humpeleka kwenye vivutio vya kuvutia zaidi na kupiga risasi kinachoendelea kwenye kamera? Ni jinsi gani mtoto anafurahi katika mbuga za watoto, ambayo huonyesha hisia, jinsi ya kufanya mambo ya upuuzi na mambo hayo yote. Kiasi hicho ni cha kushangaza sana - leo kituo cha mtoto kimepata karibu waliojisajili milioni 47 na kuanza kutoa mapato kwa kiasi cha rubles milioni 5 kwa mwezi.
Mtu fulani hupakia video ambapo anazungumzia michezo ya kompyuta, mtu fulani hufanya beatboxing au hupanga mizaha kwa wapita njia barabarani. Wengine huweka video zao kwa mada nyeti, kama vile uhusiano kati ya wanaume na wanawake. Kadiri watumiaji wa YouTube wanavyopenda picha hizi, ndivyo umaarufu wa mwandishi wa vlog unavyozidi kuwa mkubwa.
Mkusanyiko tayari umeongeza kishale cha PewDiePie, kishale cha Shane Dawson, kishale cha Ray William Johnson, kishale cha Zoella, kishale cha MyLifeAsEva na wengine.',
    'youtubers_short_descr' => 'Kizazi kipya cha nyota daima kiko mtandaoni katika mkusanyiko wetu wa YouTubers',
    'youtubers' => 'YouTubers',
    'pusheen_short_descr' => 'Ongeza faraja kwenye kivinjari chako ukitumia mkusanyiko wa kielekezi cha Pusheen',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'Mfululizo wa kwanza wa kazi ya uhuishaji “Rick and Morty” ulitolewa mwaka 2013. Katuni hii inaweza kuhusishwa moja kwa moja na aina 2: sayansi ya kubuni na ucheshi. Waumbaji wake walikuwa Dan Harmon na Justin Royland. Awali, mfululizo mfululizo wote ulionyeshwa kwenye kituo cha Cartoon Network, na kisha tu ziliigwa katika sinema za mtandaoni na upokeaji video. Kila baada ya miaka michache, misimu mipya ya Rick and Morty inatolewa, na mnamo Novemba 2019 msimu wa nne ulitoka, ambao ulibainika kuwa sio wa kuvutia kuliko yale yaliyotangulia. Njama ya mfululizo huu wa uhuishaji inazunguka mwanasayansi mwerevu na, wakati huo huo, mwanasayansi mwendawazimu anayeitwa Rick, pamoja na mjukuu wake asiyefahamika - Morty. Wahusika hawa wawili wanaunganishwa na matukio ya pamoja katika maeneo ya kawaida sana. Na wanafika huko kwenye sahani ya kuruka, yenye uwezo wa kusonga kupitia handaki la kati-. Kama ulivyodhania, mfululizo huu wa uhuishaji ni kama sinema ya Back to the Future, lakini bado sio toleo lake la uhuishaji. Hata hivyo, alisifiwa na wakosoaji wengi kwa matukio ya ucheshi, ubunifu, na asili. Unataka kumwona Rick au Morty sio tu katika mfululizo wa kazi hii, lakini pia kwenye kivinjari? Ikiwa ndivyo, sakinisha kiendelezi na uongeze mkusanyiko wetu uliowekwa kwa katuni yako unayopenda! Hapa kuna kielekezi cha Rick Sanchez, kielekezi cha Morty Smith, kielekezi cha Portal Gun na bila shaka kielekezi cha Mr. Meeseeks.',
    'rick_and_morty_short_descr' => 'Acha kunung\'unika, tumia tu kielekezi kutoka kwa mkusanyiko wa Rick and Morty',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Mashabiki wa besiboli wanaweza kupatikana popote ulimwenguni. Hii ni kweli hasa kwa wakaaji wa nchi kama vile: USA, China, Cuba, Korea Kusini, Japan na Venezuela. Kinyume na imani maarufu, besiboli haikuanzia Amerika, bali Uingereza. Mwanzo wa kwanza na maelezo ya besiboli yalionekana katika mwaka wa 1744 uliopita, katika toleo la Kiingereza. Baada ya miaka 145, Waamerika waliichukua uvumbuzi huu, licha ya ukweli.
Ligi ya Kitaifa iliundwa mnamo 1876. Yeye ni sehemu ya Ligi Kuu nchini Canada na Marekani. Leo, kuna timu 15 katika Ligi ya Kitaifa ya Besiboli. Katika sehemu ya mwisho ya kila msimu, wakati wa michezo ya mtoano unakuja, ambayo timu 4 bora zinashiriki. Kwa hivyo mshindi wa Ligi yote ya Kitaifa anafunuliwa. Kisha timu iliyoshinda inapata fursa ya kucheza dhidi ya mshindi kutoka Ligi ya Amerika katika Mfululizo wa Dunia.
Je, unapenda besiboli au hata unashabikia mojawapo ya timu? Kisha lipa heshima kwa timu yako unayoipenda kwa kuweka vishale vya panya kwa namna ya sifa zake! Badilisha mwonekano wa kuchosha wa kielekezi kwenye kivinjari kuwa utambulisho wa kampuni wa besiboli unaojulikana! Geuza mshale kuwa popo la mchezaji au kofia katika timu yoyote ya Ligi ya Kitaifa, ambayo tayari inajumuisha kishale cha New York Yankees, kishale cha Great Falls Dodgers, kishale cha Boston Red Sox, kishale cha Baltimore Orioles, kishale cha Oakland Athletics.',
    'mlb_teams_short_descr' => 'Mkusanyiko wa kielekezi cha Timu za MLB kwa mashabiki wetu wote huko nje.',
    'mlb_teams' => 'Timu za MLB',
    'brawl_stars_descr' => 'Brawl Stars ni mchezo wa simu ya mkononi katika aina ya MOBA kutoka Supercell. Licha ya kutolewa mwishoni mwa mwaka wa 2018, mchezo huo ulipata umaarufu mkubwa, haswa kutokana na wingi wa aina za vita na mashujaa wenye rangi, wa ajabu - brawlers. Mchezaji ana mengi ya kuchagua - wahusika 32 wa kipekee na kila mmoja wao ana seti yake ya uwezo na ujuzi. Kila shujaa pia ana ustadi wake wa kipekee, ambao unapatikana kupitia masanduku ya nyara. Wachezaji wanaweza kupigana katika aina kadhaa, kwa mfano, "Tuzo kwa kukamata" - moja ya timu mbili inashinda, ambaye amekusanya nyota zaidi, akiwaua wapinzani. Katika hali ya "wizi", ni muhimu kuvunja masanduku ya pesa ya wapinzani, wakati wa kutunza yao wenyewe. Njia ya kuvutia ya “Gem Grab” - timu inakuwa mshindi, timu ambayo inakusanya vito vingi inashinda. Vizuri, katika modi ya "Mgongano", wachezaji 10 wanapigana kati yao kwenye ramani, ambapo mipaka imepunguzwa kwa sababu ya wingu lenye sumu. Mchezo huo umejaa muundo wa rangi ambao watu wengi wanapenda, pamoja nasi, ambao ulituhimiza kuunda mkusanyiko tofauti wa viboreshaji vya Brawl Stars. Kuna kiboreshaji cha Brawl Stars Shelley, kiboreshaji cha Barley, kiboreshaji cha Penny, kiboreshaji cha Frank, kiboreshaji cha Mortis na wengine.',
    'brawl_stars_short_descr' => 'Chagua kielekezi cha Brawl Stars na acha vita vianze',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Badilisha kielekezi chako cha kipanya kwa mibofyo miwili! Makusanyo ya bure kwa kila ladha.',
    'all_descr' => 'Ikiwa umewahi kufikiria jinsi ya kubadilisha kielekezi cha panya kinachosumbua, basi mkusanyiko wetu wa kielekezi ni kwa ajili yako! Hapa utapata mashujaa wazuri wa vitabu vya katuni, vielekezi vizuri kwa wachezaji na wahusika kutoka kwa michezo maarufu, seti za vielekezi vya kufurahisha kwa mzaha, vielekezi vyenye rangi na chaguzi nyingine nyingi za kupendeza.',
    'text_title' => 'Mikusanyiko ya kichekesho na baridi ya kielekezi kwa kila siku',
    'text_allcat_title' => 'Vielekezi vya panya vya kipekee na vya ubunifu ili kuendana na hali yako kila wakati',
    'text_1' => 'Hutaki kuwa kama kila mtu mwingine? Au unapenda tu kila kitu kisicho cha kawaida? Unataka kuwa sehemu ya shujaa wa mchezo unaopenda au mhusika mcheshi? Basi umefika mahali pazuri. Hapa utapata seti angavu, zisizo za kawaida za kishale zinazoweza kuchukua nafasi ya mshale mweupe unaojulikana na tayari kuchosha. Kishale cha panya kinafuatana nasi siku nzima kazini na shuleni, kwa hivyo kinapaswa kutoa mhemko mzuri na kujiandaa kwa chanya.',
    'text_2' => 'Hapa utapata kielekezi cha panya kwa wachezaji na wapenzi wa filamu, vionyeshi maridadi vya panya kulingana na katuni unazopenda na motisha za michezo kwa watu wanaofanya kazi zaidi. Unapenda vichekesho au huwezi kufikiria siku moja bila meme za kuchekesha? Unapenda wanyama au una ndoto ya kutembelea nchi zote duniani? Kila kitu ni rahisi - tuna picha ya kielekezi cha panya inayofaa kwako pia. Unaweza pia kuchagua picha kulingana na kile unachofanya nacho kazi. Kwa mfano, kielekezi cha panya cheusi kitakuwa rahisi zaidi kuliko cheupe wakati wa kufanya kazi na hati au michoro, na kielekezi cha panya cha mkono kitakuwa rahisi zaidi ikiwa unapaswa kufanya kazi na vipengee vidogo vya picha. Chagua picha unayopenda, rekebisha saizi yake moja kwa moja katika kiendelezi - na uitumie kwa furaha, kila siku kuanzia na noti chanya!',
    'install_to_preview' => 'Tafadhali sakinisha kiendelezi ili kukagua',
    'install' => 'Sakinisha',
    'add_button' => 'Ongeza',
    'preview_button' => 'Hakiki',
    'added_button' => 'Imeongezwa',
    'add_cursor' => 'Ongeza kielekezi',
    'to_your_collection' => 'kwenye mkusanyiko wako',
    'prev_text_1' => 'Hakiki ya skrini nzima',
    'prev_text_2' => 'kielekezi',
    'cursor' => 'kielekezi',
    'pointer' => 'kielekezo',
    'a_title_1' => 'Cursor Style - Vionyeshi vya kupendeza kwa kivinjari chako',
    'a_title_2' => 'Mikusanyiko mizuri ya vionyeshi vya mandhari',
    'mouse_cursors' => 'vionyeshi vya mshale',
    'cursor_collection' => 'Mkusanyiko wa Vionyeshi',
    'sborka_cursorov' => 'mkusanyiko wa vionyeshi',
    'collection_list_from_colllection' => 'Orodha ya vionyeshi - ',
    'christmas' => 'Krismasi',
    'nhl_teams' => 'Ligi ya Taifa ya Hoki ya Barafu',
    'neon' => 'Neoni',
    'adventure_time' => 'Muda wa Matukio',
    'nba_teams' => 'Chama cha Taifa cha Mpira wa Kikapu',
    'spongebob' => 'Spongebob',
    'phineas_and_ferb' => 'Phineas na Ferb',
    'fortnite_chapter_2' => 'Fortnite Sura ya 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Watu Mashuhuri',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'Ligi ya Soka ya Kitaifa',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Vichekesho',
    'igry' => 'Michezo',
    'multfilmy' => 'Katuni',
    'kino_i_serialy' => 'Filamu',
    'anime' => 'Anime',
    'futbol' => 'Soka',
    'avtomobili' => 'Magari',
    'memy' => 'Meme',
    'emodji' => 'Emoji',
    'pitomcy' => 'Wanyama Kipenzi',
    'stil_i_krasota' => 'Mitindo na urembo',
    'prazdniki' => 'Sikukuu',
    'flagi' => 'Bendera',
    'vokrug_sveta' => 'Kote Ulimwenguni',
    'eda_i_napitki' => 'Chakula na vinywaji',
    'cvetnye' => 'Zenye rangi',
    'prank' => 'Pranki',
    'startovyj_nabor' => 'Seti ya kuanzia',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Santa atapenda kiona mshale chako cha Krismasi',
    'nhl_teams_short_descr' => 'Mkusanyiko wa kishale cha NHL kwa mashabiki halisi',
    'neon_short_descr' => 'Ongeza mwangaza na mkusanyiko wa neon',
    'adventure_time_short_descr' => 'Kujifunza Hesabu na mkusanyiko wa kishale cha Adventure Time',
    'nba_teams_short_descr' => 'Kielekezi cha NBA kama ishara ya ushindi mkubwa wa mpira wa kikapu',
    'spongebob_short_descr' => 'Gundua ni nani anayeishi chini ya bahari na mkusanyiko wa vielekezi vya SpongeBob.',
    'phineas_and_ferb_short_descr' => 'Hakika hautachoka na mkusanyiko wa kielekezi cha Phineas and Ferb',
    'fortnite_chapter_2_short_descr' => 'Sura mpya ya mchezo wa ibada wa Fortnite',
    'pokemon_short_descr' => 'Wakamate wote ikiwa unaweza',
    'famous_people_short_descr' => 'Vuvia alama ya kielekezi ya sanamu yako',
    'the_elder_scrools_short_descr' => 'Jijumuishe katika ulimwengu wa mashujaa na mazimwi',
    'halloween_short_descr' => 'Ogopa kukosa mkusanyiko mpya wa Halloween',
    'nfl_teams_short_descr' => 'Kwa mashabiki wa kweli wa mpira wa miguu',
    'five_nights_at_freddy_short_descr' => 'Jaribu kutokuwa na hofu ya wanyama hawa wa uhuishaji',
    'komiksy_short_descr' => 'Vihisishaji vya katuni: chagua hali yako leo.',
    'igry_short_descr' => 'Uhalisia pepe: unacheza nani leo?',
    'multfilmy_short_descr' => 'Wahusika uwapendao wa katuni katika muundo mpya',
    'kino_i_serialy_short_descr' => 'Bwana wa Kisorosoro: Udugu wa Eneo-kazi',
    'anime_short_descr' => 'Kila mtu anapenda anime: ni nani mhusika unayempenda?',
    'futbol_short_descr' => 'Je, wewe ni shabiki halisi wa michezo? Basi unahitaji kuwa hapa.',
    'avtomobili_short_descr' => 'Gari la ndoto zako: kundi kubwa kwa wataalamu.',
    'memy_short_descr' => 'Motifu zinazopendwa: Mkusanyiko wa kielekezi cha Memes.',
    'emodji_short_descr' => 'Onyesha hisia zako za kweli kwa wengine - weka Cursoji!',
    'pitomcy_short_descr' => 'Visindikizi vyenye mwangaza kwa wapenzi wote wa ndugu zetu wadogo',
    'stil_i_krasota_short_descr' => 'Visindikizi asili kwa hafla zote',
    'prazdniki_short_descr' => 'Kuna nini kwenye kalenda? Mkusanyiko Mpya wa Visahihishi vya Sikukuu!',
    'flagi_short_descr' => 'Unatafuta matukio: tunaenda wapi leo?',
    'vokrug_sveta_short_descr' => 'Koteleta ulimwenguni kwa papo hapo: tunaenda wapi leo?',
    'eda_i_napitki_short_descr' => 'Kielekezi kinachobana mdomo kwa ubunifu',
    'cvetnye_short_descr' => 'Paka rangi maisha yako kwa rangi angavu na mistari shupavu',
    'prank_short_descr' => 'Seti ya kursor za mizaha ya kuchekesha zaidi',
    'startovyj_nabor_short_descr' => 'Mwonekano mpya wa mambo ya kawaida: mfululizo wa kursor zilizosasishwa',
    'fortnite_short_descr' => 'Wafuasi wa watoaji matangazo!',
    'dota_2_short_descr' => 'Fanya ulimwengu wako pepe kuwa wa kweli!',
    'minecraft_short_descr' => 'Wahusika wa mchezo unaopenda wako karibu kila wakati',
    'christmas_descr' => 'Kila mmoja wetu bila shaka anasubiri sikukuu maarufu zaidi - Krismasi. Wakristo wote duniani kwa jadi huadhimisha kila mwaka, Desemba 25. Wakati ambapo familia hukusanyika kwenye meza moja, wanashiriki furaha na upendo wao na kubadilishana zawadi. Muda mrefu kabla ya Krismasi, watu hupamba mitaa na mapambo angavu, na nyumba zao na sifa za jadi. Ni vigumu kupata mtu ambaye hapendi Krismasi - sikukuu ya kufurahisha na ya ajabu, kwa sababu inaambatana na mila na desturi nyingi, hurudisha sisi kwenye mizizi ya familia yetu nzima. Katika usiku wa Krismasi, kila kitu kimelowa roho yake, kutoka kwa gingerbread iliyochorwa hadi nyimbo za kugusa. Mti wa Krismasi wa kifahari na zawadi chini yake, furaha inayojulikana kwa kila mmoja wetu kutoka utoto. Tunataka kujiunga na likizo hii ya kichawi na, nani anajua, labda Santa atakuandalia zawadi maalum ikiwa utapamba kielekezi chako na mkusanyiko wetu wa Krismasi. Kuna kila kitu unachohitaji kwa hili, kielekezi cha Santa Claus, kielekezi cha mti wa Krismasi, kielekezi cha gingerbread, kielekezi cha Snowman, na hata kielekezi cha mfuko wa zawadi. Krismasi Njema!',
    'nhl_teams_descr' => 'Ligi ya Taifa ya Hoki (NHL) iliundwa mwaka wa 1917 - ni shirika la michezo la kitaalamu ambalo linaleta pamoja vilabu vya hoki kutoka Marekani na Kanada. Na huu ni mmoja wa ligi za kwanza za hoki za kitaalamu duniani. NHL ni moja ya ligi za michezo bora za Amerika Kaskazini, pamoja na NFL, NBA, Ligi Kuu ya Baseball na MLS. Kila mwaka, timu 31 kutoka miji 30 ya Marekani na Kanada zinapigania nyara kuu - Kombe la Stanley, na timu ambayo ilifunga alama nyingi zaidi katika msimu wa kawaida hupewa Kombe la Rais. Ni wakati wetu wa kuheshimu mchezo huu mkubwa kwa kuunda mkusanyiko wa kursor za NHL. Ikiwa pia unapenda hoki, shabikia klabu yako unayoipenda au shiriki katika mchezo huu mwenyewe, badilisha tu kursor na usitengane na timu yako unayoipenda, ikiwa ni pamoja na kursor ya Boston Bruins, kursor ya St. Louis Blues, kursor ya Columbus Blue Jackets, kursor ya Tampa Bay Lightning, kursor ya Dallas Stars na vilabu vingine vinavyostahili heshima ya dhati.',
    'neon_descr' => 'Tumeunda mkusanyiko wa kipekee wa vifuatishaji vya neon ili kuongeza aina kwenye urambazaji wa kila siku wa mtandao na kuongeza mwangaza kidogo kwa taa za neon za kuvutia. Waache rangi zao tajiri ziumbe anga la jiji usiku, watoe msukumo wa kuunda kitu kipya. Katika ulimwengu wa kisasa, taa za jiji kubwa daima hutangaza mwanzo wa usiku, zinatufuata kila mtaa na mwanga huu umejaa nguvu. Acha pia ifuatwe na kifuati cha aiskrimu ya kumeta, kifuati cha mbwa moto kitamu, kifuati cha burger ya juisi, kifuati cha almasi cha kumeta na vifuatishaji vingine kutoka mkusanyiko mpya wa neon.',
    'adventure_time_descr' => '"Adventure Time" ni katuni ya aina ya ajabu ambayo hatua yake inafanyika katika ulimwengu ambao umezuiwa na apocalypse. Eneo hili linaitwa Land Ooo, ambalo hadi hivi karibuni lilikuwa vita vya nyuklia. Lakini yote haya tayari yamepita, hata hivyo, watu wote waliosalia walikuwa chini ya mabadiliko, na ulimwengu ulijazwa na uchawi. Wahusika wakuu wa mfululizo wa uhuishaji ni Finn, mvulana wa miaka 14 na rafiki yake mbwa anayeitwa Jake. Mvulana na mbwa wanapenda sana adventure, daima wanasaidia kila mtu ambaye yuko katika shida. Marafiki wanaishi kwenye mti na hutumia wakati wao wote pamoja. Ikiwa unataka kujiingiza katika ulimwengu wa adventure na wapenzi wengine, basi piga kelele "Hisabati". Hapa kuna kielekezi cha Finn Boy na kielekezi cha Jake, pamoja na kielekezi cha Princess Chewing gum. Bila shaka, hatukusahau kuhusu kielekezi cha Bimo, kielekezi cha Ice King na wengine.',
    'nba_teams_descr' => 'Ikiwa mpira wa kikapu ndio mchezo unaoupenda, kama ilivyo kwetu, basi mkusanyiko wa vibambo vilivyowekwa kwa timu za NBA ndicho unachohitaji. NBA ni moja ya vyama vikuu vya michezo vya bara la Amerika Kaskazini. Tulipounda mkusanyiko huu, tuliteswa na chaguo - timu gani ya kuchagua, kwa sababu kuna thelathini kati yao katika NBA. Lakini kuna timu ambazo ni hadithi. Hii na Chicago Bulls, weka rekodi ya ushindi katikati ya miaka ya 90. Hawa ni Golden State Warriors, ambao waliwaleta pamoja wachezaji bora wa ligi miaka michache iliyopita. Au, kwa mfano, Lakers, Celtics pia ni timu za ajabu. Ikiwa, kama sisi, unangojea mechi za timu zako za mpira wa kikapu unazozipenda, na unataka kuonyesha msaada wako kwa timu au wachezaji, pakua mkusanyiko wetu wa vibambo vya NBA.',
    'spongebob_descr' => 'Mfululizo wa uhuishaji "SpongeBob SquarePants" unajulikana kwa watu wengi. Ulikuwa mafanikio makubwa baada ya Nickelodeon mwaka wa 1999 kuamua kuunda mfululizo wa uhuishaji kulingana na strip ya katuni ya elimu ya Tide Zone, na kuwa franchise yenye faida kubwa. Muumbaji wa mfululizo huo ni mfanyakazi wa zamani wa maabara ya oceanological, ndiyo maana karibu wahusika wote kwenye mfululizo wa uhuishaji ni wakaaji wa bahari ya kuchekesha, wenye sifa zao na ukarimu wao. Kitendo kinazunguka karibu na mapishi ya siri ya Krabsburger ambayo ni mhusika mkuu pekee anayeweza kupika - Sponge Bob. Na wakaaji wengine wa bahari siku wanajaribu kuipata, ikiwa ni pamoja na shujaa mkuu wa Sheldon Plankton, ambaye haipati kila wakati. Katika mkusanyiko wa vibambo vya SpongeBob, tumekusanya vibambo vya wahusika wote mashuhuri na matukio ya mfululizo. Kwa mfano, kibambo cha Bwana Krabs na dola, kibambo cha Patrick Star, Squidward na zumari yake, kibambo cha jellyfish, kibambo cha Sponge Bob na wahusika wengine wengi.',
    'phineas_and_ferb_descr' => 'Katika jiji la kufikirika la Kimarekani la Denville la Trishtatya isiyoonekana, wavulana wawili wa kupendeza wanaishi. Kila siku ya likizo yao inageuka kuwa matukio ya ajabu, kwa sababu wanaweza kutengeneza roller coaster saizi ya jiji zima au bandari halisi ya sayari nyingine. Wanashiriki burudani zao za kushangaza na marafiki. Wakati huo huo, wakati wavulana wanafurahia, mwanasayansi mbaya Heinz Fufelschmertz anajenga mashine nyingine mbaya ambayo inazalisha machafuko, na jina linaloishia na "-inator", kwa msaada wake anataka kulipiza malalamiko yake ya utotoni au kutwaa madaraka huko Trishtat, lakini Perry anamsumbua - Utkonos, siri "Wakala Pi", anayefanya kazi chini ya kivuli cha mnyama wa wavulana. Umaarufu wa mfululizo huu wa uhuishaji, kati ya watoto na watu wazima, ulituhimiza kuunda mkusanyiko wa kielekezi cha Phineas na Ferb ili uweze kubadilisha kielekezi chako cha panya kwenye wahusika kutoka kwa mfululizo. Miongoni mwao ni kielekezi cha Phineas Flynn, kielekezi cha Dr. Heinz Fufelschmertz, kielekezi cha Ferb Fletcher, kielekezi cha Candace Gertrude Flynn, na kielekezi cha kinywa cha bata cha Perry.',
    'fortnite_chapter_2_descr' => 'Sura ya pili ya Fortnite ilikuja baada ya tukio kubwa - Mwisho, ambalo lilisukuma kila kitu ambacho wachezaji kwenye mchezo walipenda kwenye shimo jeusi. Fortnite Sura ya 2 sasa ina ramani mpya, ambayo kwa mtazamo wa kwanza ni ya porini zaidi kuliko ramani asili, pamoja na mabadiliko mengi katika mbinu za mchezo na bila shaka maudhui mengi mapya ya mchezo! Magari, hisia, mbinu za kuogelea na mengi zaidi - haya yote katika picha mpya za kuvutia, yote kama unavyopenda na kuthamini katika mchezo huu wa ibada. Jizamishe katika ulimwengu mpya - chagua tovuti ya kutua na uchunguze kisiwa kipya kabisa na maeneo 13. Kuogelea, uvuvi, boti za magari - huu ni mchezo mpya wa maji. Furaha zaidi na juhudi ndogo - boresha sura mpya kabisa ya 2 na usisahau kubadilisha kielekezi kuwa ngozi na silaha mpya. Tayari unangojea ngozi zilizosasishwa Turk kielekezi, Riptide kielekezi, Rippley kielekezi, Remedy kielekezi, Toxin kielekezi, 8-Ball kielekezi, Fusion kielekezi na zingine!',
    'pokemon_descr' => 'Neno "pokemon" linamaanisha kiumbe chenye nguvu za ajabu. Wana akili, na baadhi yao hata wanaweza kuzungumza. Kwa sasa, tayari kuna aina 802 za Pokemon. Katika ulimwengu wa Pokemon uliovumbuliwa, watu wanaitwa wakufunzi wa Pokémon, ambao wanawafunza kwa mapambano na Pokémon wa wakufunzi wengine. Na kadiri kocha anavyokuwa na uzoefu na nguvu, ndivyo anavyofurahia heshima zaidi. Kwa bahati nzuri, inapaswa kuzingatiwa kuwa vita vya Pokemon havifikii kamwe kifo cha viumbe hawa wa kipekee. Pokémon wote wana uwezo tofauti na wanatofautiana katika aina ya kipengele, na upinzani wake kwa mashambulizi tofauti unategemea sana hii, na viumbe wengine wana uwezo wa vipengele viwili mara moja. Baada ya kushinda vita, Pokemon anapata uzoefu muhimu ambao ni muhimu kuongeza kiwango na, ipasavyo, sifa zake. Leo, ulimwengu wa Pokémon ni franchise kubwa ya media na tutaamua kukuandalia mkusanyiko wa visaidizi na Pokémon maarufu. Miongoni mwao, maarufu zaidi ni kielekezi cha Pikachu, pamoja na kielekezi cha Rattata, kielekezi cha Squirt, kielekezi cha Bulbasaur, na kielekezi cha Charmander. Orodha hii itasasishwa, kwa sababu kuna wengi wao na kila mmoja wao ni wa kipekee kwa njia yake.',
    'famous_people_descr' => 'Miongoni mwa watu mashuhuri wengi, kila mmoja wetu anapata kielelezo au anastaajabia tu fikra, talanta na uvumilivu wa watu hawa mashuhuri. Tumetayarisha mkusanyiko wa kielekezi cha watu mashuhuri kukuhimiza na kukukumbusha mafanikio makubwa ambayo kila mmoja wenu anaweza kuongeza. Sio watu wote mashuhuri walikuwa na hatima ya furaha, lakini wanatufundisha jambo kuu kwamba huna haja ya kurudi nyuma kutoka kwa lengo lako unalolifurahia, licha ya matatizo na shida. Baada ya yote, huu ndio kanuni kuu ya kufikia mafanikio - kwenda kwenye ndoto yako kila siku na, hatimaye, kuwa bora katika eneo lako. Labda leo unataka tu kubadilisha kielekezi chako cha panya, na kesho maisha yako yote yatabadilika kuwa bora! Mkusanyiko utasasishwa kila mara na wawakilishi wapya, wanaostahili wa ubinadamu. Miongoni mwao, bila shaka, wanasayansi, wanasiasa, wanariadha, wawakilishi wa sanaa na wengine wengi. Kielekezi cha George Washington, kielekezi cha Michael Jordan, kielekezi cha Stephen King, kielekezi cha Elvis Presley na kielekezi cha Marilyn Monroe ni mwanzo tu.',
    'the_elder_scrools_descr' => 'The Elder Scrolls ni mfululizo wa michezo ya kuigiza ya kompyuta, iliyounganishwa na ulimwengu wa kawaida, uliobuniwa kwa uangalifu, ambao humpa mchezaji uhuru mkubwa wa kuchagua, unaomruhusu kutembelea maeneo na miji tofauti ya ulimwengu wa fantasy na kuchunguza maeneo mapya na misheni peke yao. Kazi ya mfululizo ilianza nyuma mwaka wa 1992 na kwa miaka mingi mchezo umeunganisha jumuiya kubwa ya wachezaji karibu yenyewe. Kwa hivyo, kwa mahitaji maarufu, tumetoa mkusanyiko wa visaidizi vya The Elder Scrolls, ili uweze kujiingiza kwenye mazingira ya kipekee ya mchezo. Vita vya milele vya mashujaa na majoka, upande gani upo? Badilisha kiashiria kuwa joka na ujiunge na jeshi la wanyama wanaopumua moto au pigana kwa heshima upande wa watu kwa kuchagua kiashiria cha upanga na picha ya mhusika unayempenda - uamuzi ni wako! Jambo kuu ni kwamba na mkusanyiko wetu mpya, uko tayari kwa vita yoyote.',
    'halloween_descr' => 'Unasubiri usiku mystiki kwenye usiku wa Siku ya Watakatifu Wote. Historia ya Halloween inarudi nyuma zaidi ya miaka elfu mbili. Labda huu ni sikukuu ya ajabu inayochanganya furaha na hofu, asili ya utamaduni wa Celtic. Kisha watu walichoma mioto ya kulipuka na kuvaa mavazi ya kutisha ili kujikinga na vizuka. Neno "Halloween" lilitajwa kwa mara ya kwanza katika karne ya 16 kama ufupisho wa Scotland wa maneno ya Kiingereza All-Hallows-Even. Papa Gregory III alitangaza Novemba 1 Siku ya Watakatifu Wote, na jioni kabla ya hapo ilijulikana kama Hawa wa Watakatifu Wote, na baadaye Halloween. Siku hii, watu huvaa mavazi ya werewolves, vizuka na monsters wengine na kwenda kwenye nyumba za jirani, wakitoa kununua pipi. Sherehe zenye mada, fataki, taa nzuri, maboga na foleni hutengeneza mazingira ya kipekee. Pia tunataka kusherehekea sikukuu hii ya kutisha na visaidizi vya kishale na wahusika wa Halloween. Katika mkusanyiko wetu unaweza kupata: kishale cha zombie, kishale cha mzuka, kishale cha paka mweusi, kishale cha boga na mengi zaidi. Kubadilisha hisia zako sasa ni rahisi kama kubadilisha kishale chako na mkusanyiko wetu mpya wa Halloween.',
    'nfl_teams_descr' => 'Nini kinaweza kuwa bora kwa shabiki wa kweli wa mpira wa miguu wa Marekani kuliko kielekezi cha panya katika mfumo wa uashiria wa timu ambayo yeye ni shabiki? Katika Ligi ya kisasa ya Soka ya Kitaifa, timu thelathini na mbili zinashiriki, zimegawanywa kati ya Mikutano ya Soka ya Kitaifa na ya Amerika (Mkutano wa Soka wa Kitaifa, NFC na Mkutano wa Soka wa Amerika, AFC). Kwa upande mwingine, kila moja ya mikutano imegawanywa katika mgawanyiko nne: Mashariki, Kaskazini, Kusini na Magharibi. Msimu wa NFL una michezo ya kabla ya msimu, msimu wa kawaida na mfululizo wa michezo ya mchujo. Mechi ya mwisho ya msimu wa NFL inaitwa Super Bowl na kimsingi ni tukio maarufu zaidi la michezo nchini Marekani. Huu ni mchezo unaopendwa na mamilioni ya mashabiki na kwa hivyo tumeunda mkusanyiko wa vionyeshi vya NFL ili usiachane na alama za timu yako uipendayo. Iwe New England Patriots, New York Giants, Buffalo Bills au timu nyingine, daima kuwa kwenye wimbi moja na sanamu zako, kwa kutumia vionyeshi vyetu katika mfumo wa nembo ya timu na kofia ya chuma. Mkusanyiko utasasishwa kila mara ili kila mtu aweze kubadilisha kielekezi kwa picha ya timu anayoipenda.',
    'five_nights_at_freddy_descr' => 'Mchezo wa kipekee kabisa wa Five Nights at Freddy\'s ulipata umaarufu haraka na hii haishangazi, kwa sababu njama yake rahisi na wakati huo huo ya kuvutia inaweza kuwaweka wachezaji kwenye skrini kwa masaa. Tuliunda kielekezi cha Five Nights at Freddy\'s kwa ombi la mashabiki wa mchezo na tulifurahi sana kuwakilisha wahusika wa kufurahisha na wa kuvutia. Lakini tofauti na mchezo, hakuna chochote kinachokutisha na viashiria vyetu, kwa hivyo jisikie huru kuchagua herufi zako uzipendazo za animatronics, iwe ni Bear Freddy au Rabbit Bonnie au wengine. Jambo kuu ni kwamba sasa mchezo unakuja hai kwenye kivinjari chako na unatoa mhemko mpya. Tunahakikisha kuwa hakuna vizuka katika viashiria vyetu, lakini zinaonyesha kikamilifu roho ya mchezo ambao unahamasisha hofu kutokana na ugumu wa muundo na mambo ya njama. Lakini vipi ikiwa utafanya saizi ya kielekezi kuwa kubwa sana? Je, unaweza kuwa mtulivu na usishituke?',
    'komiksy_descr' => 'Inaonekana kuwa kishale cha mshale ni jambo dogo, lakini mara nyingi ni maelezo kama hayo ambayo yanaweza kuboresha hali yako, kuamka asubuhi ya kijivu au kutoa tu hisia angavu. Mkusanyiko wa vishale vya kitabu cha katuni iliyoundwa mahsusi kwa wapenzi wote wa mashujaa. Hapa unaweza kupata kabisa Marvel Universe na DC Comics - kutoka Iron Man hadi Thanos, Spider-Man na Hulk. Mtindo wa kishale unaweza kuwa ama kwa namna ya shujaa, au kwa namna ya tabia yake. Kishale sio tu kipengele cha kazi; ni muhimu kwa maana ya kitaaluma. Kwa mfano, ikiwa unarekodi video kutoka skrini, itakuwa bora kuona picha angavu na ya asili, na inaonekana ya kuvutia zaidi. Na bila shaka - ni nani ambaye hatataka kutumia glavu ya infinity katika maisha halisi? Kubadilisha kishale cha mshale ni rahisi - pakua tu kiendelezi kwenye kivinjari chako na ongeza kishale unachopenda kwenye mipangilio yako kupitia hicho. Unaweza kuchagua kishale kulingana na hali yako angalau kila siku. Siku za kijivu zinatosha - kuwa shujaa sasa hivi!',
    'igry_descr' => 'Michezo ya kompyuta kwa muda mrefu imekuwa sehemu muhimu ya maisha yetu. Kwa msaada wao, unaweza kujitumbukiza katika ulimwengu mpya, kushiriki katika matukio na kuwa mtu tofauti kabisa. Kila mtu ana toy yake mwenyewe anayoipenda, ambaye wahusika wake tayari wamekuwa karibu na familia. Seti ya vifaa vya kusaidia vya kusogeza kulingana na michezo ya kompyuta inayojulikana ni fursa ya kuchanganya maisha ya kila siku yenye kuchosha na kuongeza ubunifu kidogo, mwangaza na furaha kwenye utiririshaji wa kazi. Seti hiyo ina picha za mashujaa wa mchezo wenyewe, na wahusika wasaidizi, silaha na ikoni za mchezo. Chagua kile kinachofaa hisia zako - vifaa vya kusaidia vya kusogeza vya mchezo vitavutia sio tu kwa wachezaji, bali pia kwa kila mtu ambaye amechoka tu na maisha ya kila siku ya kijivu. Pakua tu seti, badilisha kisaidizi chako cha kusogeza panya - na uende, kukamilisha kazi za harakati, kuangamiza maadui na kufikia malengo yako.',
    'multfilmy_descr' => 'Ndani ya kila mtu mzima bado kuna mtoto anayependa katuni, na bado anaota kuwa mmoja wa mashujaa. Tutasaidia kutimiza ndoto zako - tumia mkusanyiko mpya wa vishale vya kielekezi kulingana na katuni maarufu na zinazopendwa zaidi. Tom na Jerry, Buzz Lightyear na Shrek, Gravity Falls na hata Pokemon - unaweza kuwa unachotaka kila siku. Chagua kishale cha kielekezi cha panya kulingana na hali yako. Wewe ni nani leo? Msaidizi asiyejali na mwenye furaha ambaye hutatua shida yoyote kwa urahisi au Raphael mwenye nguvu na jasiri, ambaye lengo lake sio tu kutekeleza matendo, lakini pia kula pizza? Labda wewe ni jini mwenye uwezo wote ambaye anashikilia ofisi nzima chini ya amri yake? Katika mkusanyiko kuna mashujaa kwa kila mtu - kutoka kwa kifalme hadi majoka - inabaki tu kuamua ni nani anayeonyesha hali ya leo. Mtindo wa kielekezi sio tu picha angavu. Hii ni tafakari ya upekee, kujieleza na tu - furaha, shangwe na chanya kwa siku nzima. Je, inachosha kufanya kazi au mvivu sana kusoma? Je, imekuwa huzuni na haifurahishi? Badilisha kishale cha kielekezi na ulimwengu utang\'aa na rangi mpya.',
    'kino_i_serialy_descr' => 'Sinema - ni uchawi, misticism na njia nzuri tu ya kupumzika, kuwa na furaha na kupata hisia wazi. Wakati huo huo, baada ya kutazama, bado tunakumbuka mashujaa tunaowapenda ambao nataka sana kukutana nao katika uhalisia. Sasa inawezekana - pakua tu mkusanyiko mpya wa vishale kulingana na sinema maarufu na vipindi vya Runinga. Vishale vyenye kung\'aa, vyema vitakuwa nyongeza nzuri kwa eneo-kazi, kugeuza maisha ya kila siku yenye kuchosha kuwa ya likizo, na kazi za kawaida - kuwa matukio ya kusisimua. Badilisha shujaa wa kishale kila siku - kwa mhemko, kazi au bila mpangilio. Utakuwa nani leo? John Snow mkweli na mwadilifu au John Wick mjasiri asiyezuiliwa? Labda una misheni ngumu mbele yako na Frodo pekee ndiye anayeweza kuikamilisha? Labda leo wewe ni mgeni tu ambaye hataki kuwasiliana na wengine? Chagua kishale kinachofaa - inua roho yako na wakati huo huo onyesha wengine unachofikiria na jinsi unavyopanga kutumia siku yako. Jaribu - sio ya kufurahisha tu, bali pia inazoeza - hakika hutaki kurudi kwenye mshale wa kawaida.',
    'anime_descr' => 'Anime ni mtindo wa kipekee wa uhuishaji, ambao, licha ya asili yake ya kikabila, umefurahiwa na mamilioni ya watu duniani kote. Haiwezekani kwamba kutakuwa na angalau mtu mmoja ambaye hajatazama katuni kwa mtindo huu. Tumeunda visogeza vya mtindo wa anime bora kabisa ambavyo mashabiki wote wa mtindo huu watapenda. Visogeza vya kawaida ni vya kuchosha na vya kijinga. Onyesha utu wako - tumia mkusanyiko wa visogeza vya Anime na wahusika unaowapenda. Chagua kisogeza cha upanga mweusi ikiwa unaota mambo ya kusisimua na mapambano ya kishujaa. Mtu mzuri mnene Totoro atakufurahisha hata siku ya huzuni zaidi, na Naruto atakuhimiza kwenye matukio na kuwaonyesha kila mtu karibu nawe kuwa wewe ni mtu mkuu sana. Visogeza vyenye kung\'aa vitaangaza siku ya kazi au kufanya mchakato wa kujifunza uwe wa kupendeza na kufurahisha zaidi. Usijizuii - tumia motifu zako uzipendazo hata katika vitu vidogo kama vile kisogeza cha panya. Badilisha visogeza kila siku, zizoeze kulingana na hali yako na uonyeshe utu wako - na visogeza vya mtindo wa anime ni rahisi sana.',
    'futbol_descr' => 'Soka ni mchezo maalum unaojumuisha mambo ya mieleka, riadha, usahihi. Kwa ujumla, ni wa kuvutia, hauna huruma na hukusanya mamilioni ya mashabiki kote ulimwenguni. Je, unapenda soka au unapenda michezo tu? Kisha pakua seti ya visaidizi katika mtindo wa mchezo maarufu ulimwenguni na uthibitishe jina la shabiki mwaminifu. Mkusanyiko una chaguzi 24 za kubuni visaidizi - kwa namna ya timu maarufu sana ambazo zinastahili majina yao kama mchezo wa kukata tamaa na usio na msimamo. Visaidizi vimetengenezwa katika matoleo mawili - kwa namna ya pembetatu ya kawaida, iliyopambwa kwa rangi za timu, au kwa namna ya kofia ya mchezo inayofanana. Kielekezi cha kivinjari cha kawaida ni cha kuchosha na hakifai shabiki wa kweli wa michezo. Kuwa wa asili na wa kipekee na mkusanyiko wetu. Pakua picha na uchague rangi za timu unayoipenda au visaidizi maalum, ikiwa unapenda michezo tu na kuwashangilia kila mtu. Kufuata mambo yako ya kujifurahisha ni rahisi sana - sio lazima uje kazini na skafu au kofia ya timu unayoipenda, ni haraka na rahisi kubadilisha kielekezi kuwa picha angavu, maridadi.',
    'avtomobili_descr' => 'Je, unapenda magari na unafurahia kuangalia mifano kutoka kwa watengenezaji tofauti? Au umekuwa ukiota kuhusu chapa fulani kwa muda mrefu, lakini bado huna fursa ya kuinunua? Hasa kwa ajili yako, tumetengeneza seti angavu ya kielekezi "Supercars". Hapa utapata Ford ya kawaida na Bentley ya maridadi, Lamborghini angavu na Ferrari ya kipekee. Je, unataka kuwa mmiliki wa gari asilia? Ni rahisi - pakua mkusanyiko wetu wa kielekezi kwenye kifaa chako na ubadilishe picha ya gari angalau kila siku. Vielekezi vimeundwa kwa matoleo mawili - kama gari kamili au kama alama yake. Chagua unachopenda zaidi au jinsi unavyopendelea kufanya kazi. Picha kama hizo zitaonekana nzuri kama vielekezi vya mchezo au kama kipengele kisicho cha kawaida cha eneo-kazi. Kuwa angavu ni rahisi - sio lazima kufanya mambo yasiyowezekana kwa hili au kubadilisha muonekano wako. Inatosha tu kuacha kutumia vitu vya kawaida na kuchagua unachopenda sana. Mkusanyiko wa vielekezi "Magari" ni chaguo kwa wale wasioogopa kujithibitisha.',
    'memy_descr' => 'Meme zimekuwa sehemu ya kawaida ya maisha yetu kwa muda mrefu. Na ni nani kati yetu hapendi picha hizi zenye uwezo, za kuvutia na za asili kinyume na siku? Mashujaa wengi wa meme wamekuwa sio tu maarufu - wamepata hadhi ya vipenzi maarufu, na misemo na maneno yamejumuishwa kwa muda mrefu katika hotuba za kawaida pamoja na zamu zilizowekwa vyema. Tunawasilisha mkusanyiko wa vishale bora kulingana na meme maarufu. Kwa msaada wao, sio tu unaweza kuonyesha utu wako, bali pia kueleza hisia zako. Je, umechoka na uchovu wa kila kitu? Chagua paka mwenye hasira ambaye, na muonekano wake wote, anaonyesha ghadhabu na uadui kwa kila kitu kilicho karibu naye. Au je, unameta na kejeli leo na huna akili ya kucheka? Basi Drake Bling atakuwa mwandamani bora - atakufurahisha na kufanya kazi yoyote kuwa ya asili na ya kuvutia. Sakinisha kiendelezi, pakua mkusanyiko wetu - na uchague mtindo wa kishale kwa kila siku. Sio vigumu kuwa mwangavu na wa asili - badilisha muundo wa kawaida wa ikoni kuwa mmoja wa mashujaa wa meme na upate nguvu kwa siku nzima.',
    'emodji_descr' => 'Emoji - aikoni angavu, poa, bila ambayo hatuwezi tena kuwasiliana. Kwa msaada wao, hauitaji kueleza hisia zako kwa maneno - chukua tu ikoni unayotaka na mzungumzaji anakuelewa bila shida yoyote. Kwenye seti yetu mpya ya kielekezi, tulijumuisha wazo la emoji - ndivyo Cursoji ya kuchekesha na ya kawaida ilionekana itakayopaka rangi ulimwengu na kufanya maisha kuvutia zaidi. Kwa msaada wa kozi, unaweza sio tu kufanya kazi na kufanya majukumu ya kawaida, lakini pia kuwaonyesha wenzako, marafiki na wengine tu hisia zako. Kielekezi cha usingizi ni bora kwa Jumatatu asubuhi, na kielekezi cha kulia kitaonyesha tabia kuhusu majukumu ya ziada. Kielekezi poa chenye miwani ndicho chaguo bora kabla ya likizo, na kielekezi chenye pesa machoni ni sababu nzuri ya kumuashiria mkuu kuhusu ongezeko la mishahara. Kutumia Cursoji ni furaha na ya kuvutia - iwe ni kazi, masomo au wasilisho. Katika kesi ya mwisho, inashauriwa hata kufanya hivyo ikiwa wenzako wana ucheshi au wanahitaji tu kupunguza hali hiyo. Kwa ujumla, kwa kazi yoyote - chagua tu kozi inayofaa!',
    'pitomcy_descr' => 'Je, unapenda wanyama? Hakika - wao ni warembo sana, wanafurahisha na wanafurahisha sana. Kwa nini usitumie siku nzima ukisindikizwa na marafiki bora wa mtu? Pakua mkusanyiko wa visahihishi vya Wanyama kipenzi mwenyewe na uchague rafiki kwako kila siku. Aikoni ya kielekezi inaweza kuwa nzuri, kama alpaka mkarimu, au maridadi, kama flamingo wa pinki. Au labda utakuwa na shughuli nyingi siku nzima na uchague nyati akisoma gazeti, au usitake tu kuwasiliana na mtu yeyote, kama paka mweusi mwovu? Kwa hali yoyote, tuna mnyama anayefaa. Pug mchangamfu atakufurahisha hata siku ya kuchosha na ya kijivu zaidi, na kielekezi cha pinki chenye umbo la nyati kitaonyesha kila mtu kuwa wewe sio mnyimivu wa hisia ya urembo, hata ukiwa mtu katili mwenye ndevu. Vipi ikiwa hakuna mhemko, na sijisikii kufanya kazi za kawaida? Mapishi ni rahisi - pakua mkusanyiko wa Wanyama kipenzi, badilisha kielekezi cha panya - na voila, jua linang\'aa tena, hali ya hewa ni nzuri, na mhemko uko katika kiwango cha juu zaidi. Si ajabu wanasema kwamba wanyama husaidia kupambana na unyogovu na huzuni!',
    'stil_i_krasota_descr' => 'Katika mkusanyiko mpya wa kielekezi, tumekusanya aina mbalimbali za mada ambazo husababisha hisia nzuri na kutuinua. Seti hii ya vielekezi inaitwa "Mtindo na Urembo", kwa sababu ni mambo unayopenda ambayo huamua maisha yetu ya kila siku, hutupa furaha na kutuhamasisha kufanya mambo muhimu, huamsha hamu ya kuboresha. Je, unapenda sana anga na unaota kwenda kwenye sayari nyingine? Chagua kielekezi cha NASA au sahani ya wageni - karibia ndoto yako. Ikiwa huwezi kufikiria maisha bila muziki au wewe ni mpenzi wa roki, basi kielekezi cha mtindo wa gitaa la umeme ni chako. Kielekezi cha brashi, rula na dira kimetengenezwa haswa kwa wahandisi - picha kama hizo zitasaidia kubadilisha hesabu na michoro za kuchosha kuwa suluhisho asili. Fimbo ya uchawi na viatu vya michezo, skateboard na lipstick, jua na koni za kemikali - chagua kile kinachofaa mtindo wako wa maisha, matamanio yako na matarajio yako - na kazi za kawaida zitakuwa za kuvutia zaidi, na siku za kazi zitapambwa kwa rangi mpya, angavu.',
    'prazdniki_descr' => 'Kama likizo? Lakini nani hawapendi - marafiki, zawadi, tena wikendi hiyohiyo. Ili kufanya kungojea likizo kupendeza zaidi, kufupisha na kupasha joto, unaweza sio tu kuhesabu siku kwenye kalenda, lakini pia kuweka ikoni inayolingana kama kielekezi cha panya. Tuanze na Mwaka Mpya - tutachagua mti wa Krismasi, zawadi au Santa Claus, ili likizo iwe angavu na ya furaha. Labda mtu wa gingerbread atakuwa karibu - mcheshi, mzuri na mwenye furaha kila wakati? Pamoja naye hakika hakutakuwa na wakati wa kuwa na huzuni na kuchoka. Tunaendelea kusherehekea na upendo na mioyo ya furaha, na sio mbali na Sungura wa Pasaka. Mahali fulani kati ya likizo, kutakuwa na siku ya kuzaliwa, ambayo itafurahisha zaidi kusubiri na balloons badala ya mshale wa kielekezi cha kawaida. Na katika Halloween, unaweza kuwashangaza wenzako na wale walio karibu nawe na kielekezi cha panya kisicho cha kawaida kwa namna ya malenge yenye kutisha au mzimu. Seti ya vielekezi vya likizo ni fursa ya kupamba matarajio, kuweka mapema kwa furaha inayokuja na kudumisha hali nzuri sio tu usiku wa sherehe, lakini kwa mwaka mzima.',
    'flagi_descr' => 'Bendera ni alama ya kipekee ambayo inatumika sana katika mitandao yote ya kijamii. Tulifikiria, kwa nini tusifanye kishale kuwa bendera? Baada ya yote, ni mkali sana na isiyo ya kawaida. Sasa unaweza kutumia kila siku katika kampuni na nchi mpya, na kazi haitakuwa monotonus na boring. Vionyeshi vya panya sasa vinaweza kufanywa kuwa bendera ya taifa ya Uchina au USA, Japan au Kanada, na katika chaguzi nyingine 38 za bendera, na unaweza kuchagua ama sura ya kawaida ya mshale katika rangi isiyo ya kawaida au kishale katika sura ya bendera yenyewe. Seti hii itawavutia wapenzi wote wa kusafiri. Kwa hiyo, unaweza kupanga safari mpya na kuota safari ndefu. Je! Umepanga likizo? Waonyeshe wote nchi gani unataka kwenda. Labda umeamua kujifunza lugha mpya ya kigeni? Kisha kishale hiki hakika kitakusaidia na kukuhimiza kusoma kwa uangalifu. Au wewe, kama Sheldon, unapenda tu bendera? Katika kesi zote, mkusanyiko wa kishale cha Bendera utakuwa nyongeza nzuri kwa eneo-kazi lako na itakupeleka kwenye uvumbuzi mpya.',
    'vokrug_sveta_descr' => 'Kila mtu anapenda kusafiri. Jinsi inavyopendeza kutembelea nchi na miji mipya, kuona vivutio na kuwa na wakati mzuri katika utamaduni mpya. Ni huruma kwamba hatuwezi kusafiri mara nyingi, lakini tulijaribu kulirekebisha. Mkusanyiko wa kielekezi cha "Around the World" ni mkusanyiko wa picha zinazovutia zaidi, alama za nchi tofauti, kwa msaada wake hata kukaa nyumbani unaweza kujisikia kama msafiri halisi. Katika vifaa vyetu unaweza kupata Japan na Australia, Italia na Canada, USA na Mexico - nchi za kupendeza, za asili na za kupendeza zaidi duniani. Picha za kielekezi zinaweza kuwa mshale wa kawaida, katika rangi za bendera ya nchi hiyo, au kuwa moja ya vivutio vikuu vya serikali. Kwa mfano, unaweza kufungua hati na Mnara wa Pisa, na kufanya mawasilisho kwa kutumia Sanamu ya Uhuru. Tunahakikisha - mafanikio yatatimizwa. Naam, au kama sio mafanikio, basi tabasamu la wenzako na utambuzi wa uhalisi - kwa hakika. Ndiyo, na kudokeza kwa usimamizi kwamba ni wakati wa kwenda likizo pia itakuwa na thamani - weka tu suti au ndege kama kielekezi - na uwezekano mkubwa utakuwa ukiruka hivi karibuni.',
    'eda_i_napitki_descr' => 'Seti ya viboreshaji kwa namna ya bidhaa ni mkusanyiko wa ajabu wa picha angavu, za kitamu na za kupendeza ambazo kila mtu atapenda na zitakuwa nyongeza nzuri kwa kivinjari. Umewahi kubofya kwenye brokoli au viazi vya kukaanga? Una fursa kama hiyo - pakua tu seti mpya ya viboreshaji na uziweke badala ya mshale mweupe unaochosha. Viboreshaji "Chakula" vimetengenezwa kwa namna ya kielekezi cha kawaida cha pembetatu, na kwa namna ya bidhaa. Hapa utapata mboga na matunda, sahani zako uzipendazo, kama vile pizza au hot dog, kahawa, lollipops na mengi zaidi, ambayo huchangamsha siku yoyote. Unapenda kahawa, lakini kuitumia siku nzima si nzuri? Ongeza mlo wako na kahawa pepe, ambayo pia itachangamsha na kukuamsha, na pia kutoa hisia kali. Kielekezi kikali kwa namna ya donut pepe hakitaharibu sura yako, wakati kinatoa hisia kali na kukuchangamsha. Unaweza kutumia viboreshaji unavyopenda au kubadilisha picha kila siku - uteuzi mkubwa wa viboreshaji utasaidia kuchangamsha maisha ya kila siku na kuongeza rangi mpya kwa vitendo vinavyojulikana.',
    'cvetnye_descr' => 'Kishalezo ndicho kipengele kikuu cha kivinjari, ambacho tunatumia siku nzima ya kazi, kusoma, kuwasiliana na kupumzika. Mwonekano wa kawaida wa kishalezo ni wa kuchosha na hata wa kusikitisha, lakini bado, kwa watu wengi, umbo hili ni rahisi, na kulibadilisha kutakuwa na usumbufu. Lakini kwa hali hii, tuna suluhisho - seti ya vishalezo katika rangi angavu, za kufurahisha ambazo zitaongeza aina mbalimbali katika maisha yako ya kila siku na kufanya kutatua matatizo yoyote kuwa rahisi na haraka. Ikiwa unafikiria jinsi ya kubadilisha rangi ya kishalezo, tunajibu - pakua mkusanyiko wetu na uchague suluhisho angavu kwa kila siku! Unaweza kuchagua toni za rangi moja katika rangi tofauti ili kukidhi hali yako au maalum ya kazi. Kwa mfano, unapofanya kazi na hati za kawaida, kishalezo cha zambarau kitajitokeza dhidi ya mandharinyuma, na kwenye mandharinyuma meusi, kinyume chake, itakuwa rahisi kufanya kazi na vishalezo vya manjano. Ikiwa unataka mlipuko wa rangi, mwangaza na asili ya juu - chagua kishalezo cha upinde wa mvua ambacho kinajumuisha rangi zote za wigo - na ikoni hii, hali hakika itakuwa nzuri siku nzima.',
    'prank_descr' => 'Vichekesho kazini havipendwi kila wakati, kwani mara nyingi huingilia kati mtiririko wa kazi. Lakini kwa seti mpya ya kielekezi cha "Pranks", unaweza kuwafanyia mzaha wenzako au marafiki zako bila kuharibu kazi yako au masomo yako. Tumeunda mkusanyiko maalum ambao utawaburudisha mtu yeyote na kutoa sababu ya kupumzika kidogo katikati ya mchakato wa kazi au kutekeleza kazi nyingine. Ili kubadilisha kielekezi cha panya, pakua tu kifaa kwenye kifaa na uchague muundo unaopenda katika vigezo. Kwa mfano, unaweza kupata kielekezi cha umbo la kawaida, lakini katika hali iliyo kinyume au mshale uliopindwa na wimbi. Fomu hii haitaingilia kati mchakato wa kazi, lakini wakati huo huo itawasilisha hali nzuri na kukubadilisha katika hali nzuri. Badilisha mipangilio ya kuonyesha ya kielekezi kulingana na hali yako au kila siku - na kazi yoyote itakuwa ya kupendeza zaidi na ya kufurahisha, na maisha ya kila siku yatakoma kusababisha hisia hasi. Zaidi ya hayo, vionyeshi kama hivyo vinaweza kutumika hata kwa miradi mikubwa - zina rangi zisizoegemea upande wowote na hazitoki kwenye eneo-kazi.',
    'startovyj_nabor_descr' => 'Vihisishi kutoka kwa mkusanyiko wa wanaoanza ni mchanganyiko wa maumbo na ukubwa wa kawaida na mwonekano angavu, usio wa kawaida. Hili ni chaguo bora kwa wale wanaopendelea aina za kawaida, lakini wanataka kuongeza utofauti, asili na mwangaza katika maisha ya kila siku. Mkusanyiko una kishale cha mkono na kishale kinachojulikana katika anuwai ya tofauti - kutoka kwa nembo ya Google Chrome hadi hisia, unaweza hata kukutana hapa na joka lililosahaulika kwa muda mrefu lenye cactus na nostalgia. Tunathibitisha kuwa kishale cha kawaida kinaweza pia kuwa cha kuvutia na cha kuvutia. Rangi tofauti, maumbo, textures na muundo wa kuvutia zitakusaidia kuchagua kishale kwa ladha yako au kukibadilisha kila siku kulingana na hali ya akili au majukumu yanayofanywa. Kubadilisha viashiria vya kivinjari ni rahisi sana - sakinisha tu kiendelezi na upakue mkusanyiko kwenye kifaa chako. Viashirio vya kuchekesha, vya kupendeza havitapaka rangi siku za kazi tu, bali pia, kwa mfano, kusaidia kufanya wasilisho lolote liwe la kupendeza zaidi, na kwa msaada wa viashiria vyenye kung\'aa hasa, pia vuta hisia kwa vipengele vya kibinafsi vya ripoti.',
    'fortnite_descr' => 'Fortnite imewashinda mamilioni ya watu ulimwenguni kote. Vita vya kusisimua, mkakati na mbinu, matukio - imefyonza kabisa kila kitu ambacho wachezaji wanapenda sana. Hatuwezi kukaa mbali na kukuza seti ya kielekezi katika mtindo wa mchezo ambao utawavutia sio tu wachezaji waaminifu, bali hata wale ambao walisikia kwanza kuhusu Fortnite. Ikoni ya kielekezi ya Fortnite ni picha ya shujaa au silaha yake, iliyofanyiwa kazi kwa undani mdogo zaidi. Hapa unaweza kupata picha za mbweha na samaki, vinyago vya moto na mashujaa weusi, jiwekee mshale au mundu na miiba kama mshale. Tuna uhakika kwamba hakuna mtu atakayebaki tofauti! Kuwa wa kutisha au wa ajabu, wa asili au wa kuchekesha - ni juu yako. Chagua mtindo wako na fuata au weka kielekezi maalum katika mipangilio na ubadilishe jukumu lako kila siku. Sasa itakuwa ya kuvutia zaidi na ya kupendeza kufanya hata kazi ya kuchosha na ya kuchosha - wakati utapita haraka katika kampuni yenye picha wazi na wahusika uwapendao. Au labda utapanga mashindano na wenzako, shujaa gani atakuwa na nguvu? Uchaguzi ni wako!',
    'dota_2_descr' => 'DotA2 sasa sio mchezo rahisi tu, ni ulimwengu halisi sambamba. Katika uhalisia pepe katika DotA2, unaweza kufanya kila kitu - kuishi, kupigana, kuendeleza, kusafiri, kufanya urafiki. Kwa ujumla, kila kitu ni kama katika maisha, isipokuwa nyakati zingine ni za kuvutia zaidi. Vihusishi vya Dota 2 ni mwendelezo wa mkakati ambao utakuwezesha kupata hisia kali na kujieleza katika ulimwengu wa kweli. Seti mpya ya vihusishi inajumuisha wahusika wanaovutia zaidi kwenye mchezo, pamoja na vitu asili ambavyo haviwezi kuchanganywa na chochote kingine. Chagua kihariri ambacho kitakuwa karibu nawe - na uanze adventure bila kuacha mahali pa kazi pako. Ni boring sana wakati mwingine kuwa kazini au kutekeleza majukumu ya kielimu, lakini kwa vihusishi vya mchezo tatizo hili halitakusumbui tena. Mawazo kidogo, kiharizi angavu - na voila, biashara yoyote itakuwa adventure isiyo ya kawaida, ambayo kukabiliana nayo haitakuwa ngumu na ya kuvutia. Hakuna haja ya kujizuia. Unapenda Dota? Kisha hakikisha unapakua mkusanyiko wetu, chagua vihusishi kimoja au kadhaa bila mpangilio - na kila siku mpya itakuwa angavu, ya kuvutia zaidi na iliyojaa.',
    'minecraft_descr' => 'Vimishalezo vya panya katika mfumo wa mishale ya kawaida na vidole vimekuwa vya kuchosha kwa kila mtu kwa muda mrefu. Ikiwa wewe ni shabiki wa mambo ya ajabu na ya asili, basi ni wakati wa kubadilisha kishale cha panya na kuipa muundo wa kupendeza zaidi. Tumeunda mkusanyiko wa vimishale katika mtindo wa mchezo maarufu wa Minecraft duniani, ambapo unaweza kupata wahusika wazuri zaidi. Mbwa mwitu na mbweha, Alex na Creeper, upanga wa almasi na samaki - unaweza kuchagua ule unaoupenda zaidi au kusakinisha shujaa mpya kila siku. Hivi ni vimishale halisi kwa wachezaji, na kila mtu atawapenda kabisa - baada ya yote, ni nani kati yetu ambaye hajacheza Minecraft? Tuna uhakika kuwa hizi hazipo kabisa. Chini na maisha ya kila siku ya kuchosha - ni wakati wa kujiingiza katika matukio, ambayo yanaweza kufanywa hata bila kuondoka nyumbani kwako au kiti cha ofisi. Itakuwa ya kupendeza zaidi kuandaa ripoti na kupunguza usawa na bunduki - kazi yoyote itakuwa ya kupendeza zaidi na haitakuacha uchoke mahali. Pakua mkusanyiko mpya wa vimishale vya Minecraft - viweke na hata siku yenye kijivu na kuchosha zaidi, mhemko wako utakuwa bora kila wakati. Na wenzako watatamani matokeo yako - haiwezekani tu kufanya kazi yako kwa msaada wa mashujaa jasiri wa Minecraft.',
    'bts_descr' => 'BTS ni kundi la wavulana lenye wanachama saba chini ya BigHit Music. Walionekana kwa mara ya kwanza mnamo Juni 13, 2013 na wimbo mmoja "No More Dream". Nchini Japan, walionekana kwa mara ya kwanza mnamo Desemba 24, 2014 na albamu ya studio Wake Up.

Jina la kundi linatoka kwa usemi wa Kikorea Bangtan Sonyeondan, ambalo linamaanisha "skauti wa wavulana wasiopitika risasi". Kulingana na J Hope, jina linamaanisha hamu ya bendi ya kuzuia aina za watu, ukosoaji na matarajio ambayo yanalenga vijana kama risasi.

Mkusanyiko wa vishale vilivyojitolea kwa kundi linajumuisha wanachama wote wa kundi, hapa kishale cha Kim Nam Joon (aka RM), kishale cha Kim Seok Jin (Jin), kishale cha Min Yoongi (Suga), kishale cha Jung Ho Suk (J-Hope), kishale cha Park Ji Min (Jimin), kishale cha Kim Tae Hyun (V) na kishale cha Jeon Jungkook (Jungkook).',
    'roblox_bed_wars_descr' => 'Bed Wars ni hali ya asili ambayo ilionekana kwa mara ya kwanza katika Minecraft. Kazi ya wachezaji ilikuwa kwa mtumiaji kulinda msingi wao na kitanda.

Roblox huleta michezo ya kusisimua zaidi kila siku na BedWars sio ubaguzi. Na jambo ni, ikiwa unapenda vita vya kitanda na kujilinda katika chumba chako, huu ndio kichwa kwako kwa sababu kinakurudisha utotoni, ingawa kwa njia ya dijiti wakati huu.

Unachohitaji kufanya ni kulinda kitanda chako kutoka kwa washambuliaji na mpenzi wako. Unaingia katika chumba cha kupanga, chagua nani mcheze naye, na voila, ni suala la ulinzi tu.

Bila shaka, linapokuja suala la ulinzi, utakuwa na matatizo fulani na kuna rasilimali, vitu na vitu fulani ambavyo vitakusaidia kushinda. Kwa mfano, ngozi za kipekee ambazo utapata katika mkusanyiko wa kursor ya Bed Wars.',
    'pusheen_descr' => 'Karibu kila mtu anajua paka wa Pushin. Ingawa ni mhusika tu wa kitabu cha katuni cha watoto kilichobuniwa miaka 10 iliyopita, ana mamilioni ya mashabiki leo. Paka wa Pusheen alionekana kama kielelezo kilichoundwa na msanii Claire Belton.
Mwaka mmoja baadaye, paka huyo alipata ukurasa wake kwenye Tumblr.com na katika wiki chache alipata jeshi lote la mashabiki - takriban watu 10,000. Mnamo mwaka wa 2013, Facebook alikuwa akitamani kujumuisha picha kutoka Pushin katika makusanyo pamoja na hisia zingine. Baada ya mazungumzo na muundaji, wazo hili lilitumika na \'kulipua\' mtandao! Picha kutoka kwa paka wa Pusheen hutumiwa katika mawasiliano zaidi ya mara milioni 10 kwa siku!
Mnamo 2014, mmoja wa watengenezaji wakubwa wa vifaa vya kuchezea nchini Merika alielekeza umakini wake kwa mhusika huyu. GUND (ilikuwa yeye ambaye alibuni vinyago vya teddy) alizindua jozi ya mifano ya Pushin. Kwa kuwa mafanikio yalikuwa makubwa, baada ya miezi michache mkusanyiko kamili wa vinyago kwa namna ya paka huyu uliundwa.
Unaweza kukutana na paka wa Pusheen wapi pengine? Katika seti za zawadi kutoka kwa Isaac Morris Ltd, katika marshmallow kutoka Boomf na, kwa kweli, katika mkusanyiko wetu wa kiteuzi cha Pusheen!',
    'astrology-signs-zodiac' => 'Ishara za Zodiac',
    'sports-cars_short_descr' => 'Magari yenye nguvu na maridadi yaliyoundwa kwa kasi na wepesi',
    'spider-man' => 'Spider-Man',
    'astrology-signs-zodiac_short_descr' => 'Seti ya alama 12 za unajimu zinazowakilisha sifa za utu, nguvu za ulimwengu, na mifumo ya maisha.',
    'sports-cars' => 'Magari ya Michezo',
    'sports-cars_descr' => 'Magari ya michezo ni magari yenye utendaji wa hali ya juu yaliyoundwa kwa ajili ya kuongeza kasi ya haraka, utunzaji mkali, na uzoefu wa kuendesha gari wa kusisimua. Kutoka kwa magari maridadi ya coupe hadi magari ya roadster ya agile, kategoria hii ina mashine kadhaa za kipekee zilizojengwa kwa furaha ya barabara au wimbo. Bora kwa wapenzi wanaopenda kasi, muundo, na nguvu. 🏎️🔥',
    'spider-man_short_descr' => 'Mashujaa kutoka ulimwengu wa Spider-Man',
    'starwars' => 'Star Wars',
    'astrology-signs-zodiac_descr' => 'Alama za Zodiac ♈♉♊♋♌♍♎♏♐♑♒♓ ni mgawanyiko kumi na mbili wa mfumo wa anga unaotumika katika unajimu. Kila alama inahusishwa na tarehe maalum, vipengele (🌍 Dunia, 🔥 Moto, 🌊 Maji, 💨 Hewa), sayari zinazotawala, na sifa za kipekee za utu. Wanajimu hutumia alama za zodiac kufasiri tabia, kutabiri upatanifu, na kuchunguza njia za maisha. Ikiwa wewe ni Leo 🔥 mwenye shauku au Pisces 🌊 mwenye mawazo, alama yako inatoa ufahamu katika ulimwengu wako wa ndani. Kategoria hii inajumuisha alama zote 12, maana zake, na uwakilishi wa taswira.',
    'spider-man_descr' => 'Mkusanyiko wa wahusika na mashujaa kutoka kwa ulimwengu wa Spider-Man. Inajumuisha matoleo mbalimbali ya Spider-Man, washirika, na mitindo ya kipekee kutoka kwa katuni, michezo, na mfululizo wa uhuishaji. Kila muundo unaonyesha wepesi, ujasiri, na utambulisho wa kuonekana unaoelezea ulimwengu wa Spider-Man.',
    'starwars_descr' => 'Jitumbukize kwenye galaksi mbali sana, mbali sana na mkusanyiko huu unaoonyesha mashujaa wa hadithi, mabwana wenye nguvu wa Sith, droids, waasi, na zaidi. Kuanzia Jedi Knights hadi stormtroopers, kila ikoni huleta roho ya Star Wars katika umbo la kishale. Ni kamili kwa mashabiki wa kila trilogy. 🌌',
    'starwars_short_descr' => 'Wahusika na alama kutoka ulimwengu wa Star Wars',
    'glitter' => 'Mng\'ao',
    'glitter_short_descr' => 'Vionyeshi vyenye kung\'aa na mng\'ao na mtindo wa mng\'ao ✨🌟',
    'roblox-2025' => 'Roblox 2025',
    'roblox-2025_short_descr' => 'Wahusika kutoka wimbi jipya zaidi la Roblox 🕹️🚀',
    'glitter_descr' => 'Mkusanyiko wa kupendeza wa kielekezi kilichoongozwa na maumbo ya kung\'aa na taswira zinazong\'aa. Ni kamili kwa wale wanaopenda urembo unaometa kwenye skrini zao. Vielekezi hivi huleta kung\'aa, umaridadi, na uchawi kidogo kwa kila mbofyo.',
    'roblox-2025_descr' => 'Mkusanyiko mpya kabisa wa 2025 unaojumuisha wahusika wa Roblox mashuhuri na wa kisasa. Inajumuisha wageni wa zamani, hadithi za kutisha, na avatari zinazopendwa na mashabiki kutoka michezo maarufu. Imeundwa kwa mtindo wa kufurahisha na wa kupendeza kamili kwa watoto na mashabiki wa Roblox wa rika zote.',
];
