<?php

return [
    'title' => 'Cursor Style - Sera ya Faragha',
    'descr' => 'Katika “Cursor Style,” inayopatikana kwenye cursor.style au kupitia kiendelezi cha Chrome, kipaumbele chetu kikuu ni faragha ya wageni wetu. Ni katika sehemu hii ambapo tutazungumzia mambo yote ya kufanya kazi na kiendelezi.',
    'text' => '<h2> Sera ya Faragha </h2>
                <p> Katika Cursor Style, inayopatikana katika <a href="https://cursor.style"> cursor.style </a> au kupitia kiendelezi cha Chrome, mojawapo ya vipaumbele vyetu vya juu ni faragha ya wageni wetu. Hati hii ya Sera ya Faragha ina aina za habari ambazo zimekusanywa na kurekodiwa na tovuti ya cursor.style, na jinsi tunavyoitumia. Ikiwa una maswali ya ziada au unahitaji habari zaidi kuhusu Sera yetu ya Faragha, usisite kuwasiliana nasi. </p>
                <p> Kiendelezi cha "Cursor Style" na tovuti hufuata utaratibu wa kawaida wa kutumia faili za kumbukumbu. Faili hizi husajili wageni wanapotembelea tovuti au kutumia kiendelezi chetu. Kampuni zote za uandaaji hufanya hivyo na ni sehemu ya uchanganuzi wa huduma ya uandaaji. Habari iliyokusanywa kupitia faili za kumbukumbu ni pamoja na anwani za Itifaki ya Mtandao (IP), aina ya kivinjari, Mtoa Huduma wa Mtandao (ISP), muhuri wa tarehe na saa, kurasa za mpito / kutoka, na uwezekano wa idadi ya mibofyo. Hazihusiani na habari yoyote inayoweza kutambulika kibinafsi. Madhumuni ya habari hii ni kuchanganua mitindo, kusimamia tovuti na kupanua, kufuatilia harakati za watumiaji kwenye tovuti na kupanua, na kukusanya habari za idadi ya watu. </p>
                <p> Kama tovuti nyingine yoyote, cursor.style hutumia kuki. Vidakuzi hivi hutumiwa kuhifadhi habari, pamoja na mapendeleo ya mgeni na kurasa kwenye wavuti ambazo mgeni alitembelea au kutembelea. Habari hii hutumiwa kuboresha utumiaji wa watumiaji kwa kubinafsisha yaliyomo kwenye ukurasa wetu wa wavuti kulingana na aina ya kivinjari cha mgeni na / au habari nyingine. Tunatumia pia matangazo ya watu wengine kwenye cursor.style ili kusaidia mradi na kusaidia tovuti yetu. Wafanyabiashara hawa wengine wanaweza kutumia teknolojia kama vile kuki na taa za wavuti wanapotangaza kwenye wavuti yetu, ambayo pia itatuma watangazaji hawa (kwa mfano, Google kupitia programu ya Google AdSense) habari, pamoja na anwani yako ya IP, mtoa huduma wako wa mtandao, kivinjari ambacho umetumia kutembelea tovuti yetu, na katika hali nyingine, ikiwa una Flash imewekwa. Hii kawaida hutumiwa kwa madhumuni ya geotargeting (kwa mfano, kuonyesha matangazo ya uuzaji wa bidhaa katika jiji lako) au kwa kuonyesha matangazo fulani kulingana na tovuti fulani zilizotembelewa (kwa mfano, kuonyesha matangazo ya ununuzi kwa wale ambao hutembelea tovuti za ununuzi mara kwa mara). </ P >
                <p> Unaweza kulemaza au kuchagua kuki zetu au za watu wengine katika mipangilio ya kivinjari au kwa kusimamia mipangilio katika programu kama vile Kaspersky, nk. Walakini, hii inaweza kuathiri jinsi unavyoingiliana na tovuti yetu, na pia na tovuti zingine. Hii inaweza kujumuisha kutoweza kuingia kwenye huduma au programu, kama vile kuingia katika vikao au akaunti. </p>
<p> Google ni mmoja wa watoa huduma wengine kwenye tovuti yetu. Pia hutumia kuki, zinazojulikana kama kuki za DART, kuwahudumia wageni matangazo kwenye tovuti yetu kulingana na ziara zao cursor.style na tovuti zingine kwenye Mtandao. Walakini, wageni wanaweza kuchagua kutotumia kuki za DART kwa kutembelea sera ya faragha ya Google Advertising and Content Network kwa <a href="https://policies.google.com/technologies/ads"> anwani ifuatayo </a>. Baadhi ya watangazaji kwenye wavuti yetu wanaweza kutumia kuki na taa za wavuti. Kila mmoja wa washirika wetu wa utangazaji ana sera yake ya faragha kwa sera zake kuhusu data ya watumiaji. Unaweza kusoma zaidi juu ya Sera zao za Faragha <a href="https://policies.google.com/technologies/ads"> hapa </a>. </p>
                <p> Wavuti yetu hutumia Google Analytics, huduma ya uchambuzi wa wavuti ya Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com (“Google Analytics” au “Google”). Google Analytics hutumia kuki ambazo zimehifadhiwa kwenye kompyuta yako ili kuwezesha uchambuzi wa matumizi yako ya wavuti. Habari iliyotengenezwa na kuki hizi, kama vile wakati, mahali na mzunguko wa ziara zako kwenye wavuti yetu, pamoja na anwani yako ya IP, huhamishiwa kwa eneo la Google nchini USA na kuhifadhiwa hapo. Google inaweza pia kuhamisha habari hii kwa watu wengine ikiwa inahitajika na sheria au ikiwa watu wengine wanachakata data hii kwa niaba ya Google. Google inasema kuwa haitawahi kuhusisha anwani yako ya IP na data nyingine ya Google. Unaweza kuzuia uwekaji wa kuki kwa kubadilisha mipangilio ya programu yako ya kivinjari ipasavyo, kama ilivyobainishwa katika Sera hii ya Faragha. Walakini, unapaswa kufahamu kuwa kwa njia hii hautaweza kutumia kikamilifu vitendaji vyote vya wavuti yetu. </p>
                <p> Google Analytics pia hutumia picha za elektroniki zinazojulikana kama taa za wavuti (wakati mwingine huitwa picha za saizi ya moja) na hutumiwa na kuki kukusanya takwimu zilizojumuishwa ili kuchambua utumiaji wa tovuti yetu.
Unaweza kupata habari zaidi juu ya jinsi ya kusanikisha kiambatanisho cha kivinjari ambacho unasanifu hapo juu <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> kiungo </a>.
Tovuti hii hutumia Meneja wa Lebo ya Google. Huduma hii hukuruhusu kudhibiti lebo za tovuti kupitia kielelezo. Google Tag Manager hutekeleza lebo tu. Hii inamaanisha kuwa kuki hazijawekwa na hakuna data ya kibinafsi iliyorekodiwa. Google Tag Manager huendesha lebo zingine, ambazo zinaweza kurekodi data. Walakini, Meneja wa Lebo ya Google hana ufikiaji wa data hii. Ikiwa lebo zimezimwa katika kiwango cha uwanja au kuki, zimehifadhiwa kwa lebo zote za ufuatiliaji, ikiwa zinatumika kutumia Meneja wa Lebo ya Google. Unaweza kujifunza zaidi kuhusu Meneja wa Lebo ya Google kwa kutembelea <a href="http://www.google.com/tagmanager/use-policy.html"> kiungo </a>. </p>
<p> Unaweza kujizoea na orodha hii ili kupata Sera ya Faragha kwa kila mmoja wa washirika wa utangazaji wa "Cursor Style". Seva za matangazo za mtu wa tatu au mitandao ya matangazo hutumia teknolojia kama vile kuki, JavaScript au taa za wavuti, ambazo hutumiwa katika matangazo na viungo vyao, ambavyo vinaonyeshwa katika "Cursor Style" na kutumwa moja kwa moja kwa kivinjari cha watumiaji. Wao hupata kiatomati anwani yako ya IP wakati hii inatokea. Teknolojia hizi hutumiwa kupima ufanisi wa kampeni zao za utangazaji na / au kubinafsisha yaliyomo kwenye utangazaji unayoona kwenye wavuti unazotembelea. Tafadhali kumbuka kuwa "Cursor Style" haina ufikiaji au udhibiti wa kuki hizi ambazo hutumiwa na watangazaji wengine. Sera ya faragha ya Cursor Style haitumiki kwa watangazaji wengine au tovuti. Kwa hivyo, tunapendekeza kwamba uhakiki sera husika za faragha za seva hizi za matangazo za mtu wa tatu kwa habari zaidi. Inaweza kujumuisha njia zao na maagizo juu ya jinsi ya kujiondoa kwa chaguzi fulani. Unaweza kupata viungo kwa Sera hizi za Faragha za Watu wa Tatu hapo juu au kwenye wavuti za huduma hizi za mtu wa tatu. </p>
                <p> Unaweza kulemaza kuki katika mipangilio ya kivinjari chako. Ili kujifunza zaidi juu ya usimamizi wa kuki katika vivinjari maalum vya wavuti, unaweza kuipata kwenye tovuti zao za kivinjari. Sehemu nyingine ya kipaumbele chetu ni kuongeza ulinzi wa watoto wakati wa kutumia Mtandao. Tunawahimiza wazazi na walezi kutazama, kushiriki na / au kufuatilia na kuelekeza shughuli zao kwenye Mtandao. "Cursor Style" haikusanyi habari za kibinafsi kutoka kwa watoto walio chini ya umri wa miaka 13. Ikiwa unafikiria kuwa mtoto wako ametoa habari kama hiyo kwenye wavuti yetu, tunapendekeza sana kwamba uwasiliane nasi mara moja na tutafanya bidii yetu kuondoa habari kama hiyo haraka kutoka kwa rekodi zetu. Sera hii ya Faragha inatumika tu kwa shughuli zetu mkondoni na ni halali kwa wageni kwenye wavuti yetu kuhusiana na habari ambazo walishiriki na / au kukusanya katika "Cursor Style". Sera hii haitumiki kwa habari yoyote iliyokusanywa nje ya mkondo au kupitia njia zingine isipokuwa wavuti hii. </p>
                <p> Unaweza kusoma zaidi kuhusu matumizi ya kuki katika Huduma yetu katika yetu <a href="/cookie-policy"> Sera ya Kuki </a>. </p> ',
];
