<?php

return [
    'title' => 'Cursor Style - Masharti ya matumizi ya bidhaa zetu',
    'descr' => 'Masharti ya matumizi yameingizwa kati yako na “Cursor Style” (“Huduma”, “sisi” au “Huduma”). Huduma hii inatolewa na inapatikana kwa watumiaji walio na umri wa miaka 13 na zaidi tu kwa matumizi ya kibinafsi na sio kwa matumizi ya kibiashara.',
    'text' => '<h2> Sheria na Masharti </h2>
<h3> TAFADHALI SOMA MASHARTI NA MASHARTI HAYA KABLA YA KUTUMIA TOVUTI NA ZANA. </h3>
<p> Masharti haya ya matumizi yameingizwa kati yako na "Cursor Style" ("Huduma", "sisi" au "Huduma"). Sheria na masharti yafuatayo, pamoja na hati zozote ambazo zinajumuisha wazi kwa kumbukumbu (kwa pamoja, hizi "Masharti ya Matumizi"), zinaongoza ufikiaji wako na matumizi ya tovuti ya cursor.style na zana zake za kivinjari, pamoja na yaliyomo, utendaji na huduma yoyote inayotolewa kwenye au kupitia huduma yetu (pamoja "Huduma"). </p>
<p> Kwa kutumia tovuti au zana, unakubali na kukubali kuzingatia Masharti haya ya Matumizi. Ikiwa haukubali Masharti haya ya Matumizi au yetu <a href="/privacy"> Sera ya Faragha </a>, haupaswi kupata au kutumia Tovuti na Zana. </p>
<p> Huduma hii inatolewa na inapatikana kwa watumiaji wenye umri wa miaka 13 na zaidi tu kwa matumizi ya kibinafsi na sio kwa matumizi ya kibiashara. Kwa kutumia Huduma hii, unawakilisha na unahakikisha kuwa wewe ni (I) miaka 13 au zaidi, (II) haujazuiwa kutumia Tovuti kulingana na sheria inayofaa, na (III) unatumia Huduma tu kwa mahitaji yako ya kibinafsi. Ikiwa hukidhi mahitaji haya, haupaswi kupata au kutumia Huduma. </p>
<p> Tunaweza kurekebisha na kusasisha Sheria hizi za Matumizi mara kwa mara kwa hiari yetu. Mabadiliko yote huanza kutumika mara moja baada ya kuchapishwa kwao. Uendelezaji wako wa matumizi ya Huduma baada ya kuchapishwa kwa Sheria za Matumizi zilizorekebishwa inamaanisha kuwa unakubali na unakubali mabadiliko. Unatarajiwa kutembelea ukurasa huu mara kwa mara ili kuendelea na mabadiliko yoyote kwani yanakufunga. </p>
<p> Tunahifadhi haki ya kuondoa au kurekebisha Tovuti hii na Zana, huduma yoyote au vifaa tunavyotoa kwenye Tovuti na Zana, kwa hiari yetu, bila taarifa. Hatuhakikishi kuwa tovuti yetu, zana au yaliyomo yoyote juu yake yatapatikana kila wakati au yatakatizwa. Hatuwezi kuwajibika ikiwa kwa sababu yoyote yote au sehemu yoyote ya Huduma haipatikani wakati wowote au wakati wowote. Mara kwa mara, tunaweza kuzuia ufikiaji wa sehemu fulani za Tovuti au Zana au Huduma nzima kwa watumiaji. </p>
<p> Unawajibika kuchukua hatua zote muhimu ili kuhakikisha kuwa una ufikiaji wa Huduma. Kuhakikisha kuwa watu wote wanaopata Huduma kupitia unganisho lako la Mtandao wanajua Masharti haya ya Matumizi na kuyatekeleza. Ili kufikia Huduma au baadhi ya rasilimali zinazotoa, unaweza kuulizwa kutoa habari fulani au habari nyingine. Unakubali kuwa habari zote unazotupa kwa kutumia Huduma hii au vinginevyo, pamoja na lakini sio mdogo kwa matumizi ya huduma yoyote ya maingiliano katika Huduma, inasimamiwa na yetu <a href="/privacy"> Sera ya Faragha </a>, na unakubali hatua zote tunazochukua kuhusu habari yako. kulingana na yetu <a href="/privacy"> Sera ya Faragha </a>. </p>
<p> Lazima uwe mwangalifu haswa wakati wa kuingiza habari za kibinafsi kwenye Huduma kwenye kompyuta ya umma au iliyoshirikiwa ili wengine wasiweze kutazama au kurekodi habari zako za kibinafsi. Tovuti, zana na yaliyomo yote, kazi na huduma (pamoja na, lakini sio mdogo, habari zote, zana, maandishi, picha, picha na kielekezi cha kipanya, pamoja na muundo wao, uteuzi na uwekaji) ni mali ya "Cursor Style", walipa leseni wake au wasambazaji wengine wa vifaa kama hivyo wanalindwa na hakimiliki, alama ya biashara, patent, siri ya biashara na sheria zingine za milki ya akili au haki za mali. </p>
<p> Masharti haya ya Matumizi hukuruhusu kutumia Tovuti tu kwa matumizi yako ya kibinafsi, yasiyo ya kibiashara. Haupaswi kutengeneza tena, kusambaza, kurekebisha, kuunda kazi zinazotokana, kuchapisha tena, kupakua, kuhifadhi au kusambaza vifaa vyovyote kwenye Tovuti yetu, isipokuwa kwa kesi zifuatazo: unaweza kuitumia kwa mahitaji ya kibinafsi, unaweza kuchapisha au kupakua nakala moja ya kurasa za kiasi zinazofaa za Tovuti na Zana au yaliyomo kwa matumizi ya kibinafsi, yasiyo ya kibiashara, na sio kwa utengenezaji zaidi, uchapishaji au usambazaji. </p>
<p> Haupaswi kurekebisha nakala za vifaa vyovyote kutoka kwa tovuti hii au zana na yaliyomo. Futa au urekebishe hakimiliki yoyote, alama ya biashara, au arifa zingine za wamiliki kutoka kwa nakala za tovuti hii na zana. Sio lazima uwe na ufikiaji au utumie kwa madhumuni yoyote ya kibiashara sehemu yoyote ya Tovuti au zana, na pia huduma yoyote au vifaa vinavyopatikana kupitia Tovuti au Zana. </p>
<p> Ikiwa unataka kutumia nyenzo yoyote kwenye Tovuti au Zana isipokuwa zile zilizoorodheshwa katika sehemu hii, tuma ombi kwenye ukurasa wa usaidizi wa Duka la Wavuti la Chrome. </p>
<p> Ikiwa unachapisha, kunakili, kurekebisha, kupakua, au vinginevyo unatumia au kumpa mtu mwingine yeyote ufikiaji wa sehemu yoyote ya Tovuti au Zana kukiuka Masharti ya Matumizi, haki yako ya kutumia Tovuti na Zana inasitishwa mara moja, na lazima , kwa hiari yetu, kurudisha au kuharibu nakala zozote za vifaa ulivyo navyo. Matumizi yoyote ya tovuti ya zana ambayo haijaruhusiwa wazi na Masharti haya ya Matumizi ni kinyume cha Masharti haya ya Matumizi na yanaweza kukiuka hakimiliki, alama za biashara na sheria nyingine. </p>
<p> Jina “Cursor Style”, nembo ya “Cursor Style” na majina yote yanayohusiana, nembo, picha, kielekezi cha kipanya na majina ya huduma, miundo na kauli mbiu ni alama za biashara za “Cursor Style” au washirika wake au walipa leseni. Haupaswi kutumia alama kama hizo bila idhini ya maandishi ya Huduma. Majina mengine yote, nembo, jina la bidhaa na huduma, miundo na kauli mbiu kwenye wavuti hii na kwenye zana ni alama za biashara za wamiliki wao. Unaweza kutumia Huduma tu kwa madhumuni halali na kulingana na Masharti haya ya Matumizi. </p>
<h3> Unakubali KUTOTUMIA Huduma: </h3>
<ul>
<li> Kwa njia yoyote ambayo inakiuka sheria au kanuni zozote za shirikisho, mkoa, eneo au kimataifa (pamoja na, lakini sio mdogo kwa, sheria yoyote kuhusu usafirishaji wa data au programu kwa Urusi na nchi zingine). </li>
<li> Kwa madhumuni ya unyonyaji, madhara, au majaribio ya kutumia au kuwadhuru watoto, kuwaweka katika maudhui yasiyofaa, kuomba habari inayowatambulisha, au vinginevyo. </li>
<li> Kutuma, kupokea kwa makusudi, kupakua, kutumia au kutumia tena vifaa vyovyote ambavyo havafuati Masharti haya ya Matumizi. </li>
<li> Kusambaza au kununua kutuma matangazo yoyote au vifaa vya utangazaji bila idhini yetu ya maandishi ya awali, pamoja na "barua zisizohitajika", "barua za mnyororo" au "barua taka" au ofa zingine zozote kama hizo. </li>
<li> Ili kujifanya au kujaribu kujifanya mfanyakazi wa “Cursor Style”, mtumiaji mwingine, au mtu mwingine yeyote au shirika (pamoja na lakini sio mdogo kwa kutumia anwani za barua pepe au majina bandia yanayohusiana na yoyote ya hapo juu). </ li >
<li> Ushiriki katika hatua nyingine yoyote ambayo inazungua au kuzuia matumizi ya Huduma au matumizi ya mtu yeyote, au ambayo, kama tunavyoamua, inaweza kudhuru Huduma au watumiaji wa Huduma au kuwafanya wawajibike. </li> </ul>
<h3> Kwa kuongezea, unakubali SIO: </h3>
<ul>
<li> Tumia Huduma kwa njia yoyote ambayo inaweza kulemaza, kuzidi, kuharibu au kudhoofisha utendaji wa tovuti, kupanua au kuingiliana na matumizi ya Huduma na mtu mwingine yeyote, pamoja na uwezo wao wa kushiriki katika hatua za wakati halisi kupitia Huduma. </li>
<li> Tumia zana zozote za otomatiki, mchakato, au njia ya kufikia Huduma kwa madhumuni yoyote, pamoja na ufuatiliaji au kunakili nyenzo yoyote kwenye Huduma. </li>
<li> Tumia mchakato wowote wa mwongozo wa kufuatilia au kunakili nyenzo yoyote kwenye Huduma au kwa madhumuni mengine yoyote yasiyoruhusiwa bila idhini yetu ya maandishi ya awali. </li>
<li> Tumia kifaa chochote, programu au taratibu ambazo zinapingana na utendaji wa kawaida wa Huduma. </li>
<li> Kuanzisha virusi vyovyote, farasi wa Trojan, minyoo, mabomu ya kimantiki au vifaa vingine ambavyo ni hatari au ni hatari kiteknolojia. </li>
<li> Jaribu kupata ufikiaji usioruhusiwa, kuingiliana, kuharibu au kusumbua sehemu yoyote ya Huduma, seva ambayo Huduma imehifadhiwa, au seva yoyote, kompyuta au hifadhidata iliyounganishwa na Huduma. </li>
<li> Shambulia Huduma kwa kutumia shambulio la kunyimwa huduma au shambulio la kunyimwa huduma lililosambazwa. </li> </ul>
<p> Habari iliyotolewa kwenye au kupitia Huduma hutolewa tu kwa madhumuni ya habari ya jumla. Hatuhakikishi usahihi, ukamilifu au ufanisi wa habari hii. Unategemea habari kama hiyo tu kwa hatari yako mwenyewe. Tunakataa jukumu na dhima yote inayotokana na utegemezi wowote wa vifaa kama hivyo na wewe, wageni wengine wowote kwenye Huduma au mtu yeyote ambaye anaweza kufahamishwa juu ya yaliyomo. </p>
<p> Huduma hii ni pamoja na yaliyomo yanayotolewa na watu wengine, pamoja na vifaa vilivyotolewa na watumiaji wengine na walipa leseni wa wahusika wengine, wasambazaji, wasambazaji na / au huduma za kuripoti. Taarifa zote na / au maoni yaliyotolewa katika vifaa hivi, na vile vile nakala zote na majibu ya maswali na yaliyomo mengine, isipokuwa kwa yaliyomo yaliyotolewa na Huduma, ni maoni na majukumu ya mtu au shirika linalotoa vifaa hivi. Vifaa hivi havionyeshi maoni ya Huduma. Hatuwezi kuwajibika kwako au kwa mtu mwingine yeyote kwa yaliyomo au usahihi wa vifaa vyovyote iliyotolewa na watu wengine. </p>
<p> Tunaweza kusasisha yaliyomo ya Huduma mara kwa mara, lakini yaliyomo yake sio lazima yakamilike au ya sasa. Nyenzo yoyote kwenye Huduma inaweza kuwa ya zamani wakati wowote, na hatufanyiwi kusasisha nyenzo kama hii. Tunaweza kusasisha, kurekebisha, kurekebisha habari na yaliyomo kwenye Tovuti na kwenye Zana, kufanya mabadiliko yoyote na sasisho kulingana na uamuzi wetu wenyewe. </p>
<p> Habari zote tunazokusanya kwa Huduma hii iko chini ya Sera yetu ya Faragha. Kwa kutumia Huduma, unakubali vitendo vyote vilivyochukuliwa na sisi kuhusiana na habari yako kulingana na <a href="/privacy"> Sera ya Faragha </a>. </p>
<p> Masharti ya ziada yanaweza pia kutumika kwa sehemu, huduma au huduma fulani za Huduma. Masharti na masharti yote ya ziada yanajumuishwa hapa kwa kumbukumbu katika Masharti haya ya Matumizi.
Unaweza kuunganisha kwenye tovuti yetu au zana ikiwa unafanya hivyo kwa njia ya uaminifu na ya kisheria na hauharibu sifa yetu au kuitumia, lakini haifai kuweka kiunga kwa njia ya kutoa aina yoyote ya ushirika, idhini au idhini kwa upande wetu bila idhini yetu ya maandishi. </p>
<p> Huduma ina viungo kwa tovuti zingine na rasilimali zilizotolewa na watu wengine, viungo hivi hutolewa tu kwa urahisi wako. Hii ni pamoja na viungo vilivyomo kwenye matangazo, pamoja na matangazo ya bango na viungo vilivyofadhiliwa. Hatuwezi kudhibiti yaliyomo kwenye tovuti hizi au rasilimali na hatuwajibiki kwao au kwa upotezaji wowote au uharibifu unaoweza kusababishwa na matumizi yao. Ikiwa unaamua kupata tovuti yoyote ya watu wengine inayohusishwa na Huduma hii, unafanya hivyo kwa hatari yako mwenyewe na kulingana na masharti ya matumizi ya tovuti kama hizo. Tunahifadhi haki ya kubatilisha ruhusa ya kuunganisha bila taarifa ya awali. </p>
<p> Unaelewa kwamba hatuwezi na hatuhakikishi au kuhakikisha kuwa faili zinazopatikana kwa kupakuliwa kupitia mtandao au kwenye Tovuti hazitakuwa na virusi au nambari nyingine hasidi. Unawajibika kwa utekelezaji wa taratibu na vituo vya udhibiti vya kutosha kukidhi mahitaji yako maalum ya ulinzi wa anti-virusi na usahihi wa uingizaji wa data na pato, na pia kwa kudumisha njia za nje ya tovuti yetu ili kuokoa tena data yoyote iliyopotea. HATUTAWajibika KWA UHARIBIFU WOWOTE AU MAJERUHI YALIYOSABABISHWA NA huduma KUNYIMWA, VIRUSI AU TEKNOLOJIA NYINGINE-MALWARE ILIYOPATIKANA KUPITIA HUDUMA, AU KWA KUPAKUA VYOMBO VYOTE VILIVYOZUNGUMZWA KWA HII, AU TOVUTI YOYOTE, ZILIZOHUSIANISHWA NA ZINAWEZA KUATHIRI AU KUHARIBU KOMPYUTA YAKO, PROGRAMU YA KOMPYUTA, DATA. </p>
<p> UNATUMIA HUDUMA, YALIYOMO YAKE NA HUDUMA ZOTE ZILIZO PATA KUPITIA HUDUMA KWA HATARI YAKO MWENYEWE. HUDUMA, YALIYOMO YAKE NA HUDUMA ZOTE ZILIZO PATA KUPITIA TOVUTI NA ZANA, ZINATOLEWA KWA MASHARTI YA “KAMA ILIVYO” NA “KAMA INAPATIKANA”, BILA UHAKIKI WOWOTE. MTU YEYOTE ANAYEHUSISHWA NA HUDUMA HAATOI UHAKIKI WOWOTE AU UWAKILISHAJI KWA KUHUSU UKAMILIFU, USALAMA, UAMINIFU, UBORA, USAHIHI AU UFANISI WA HUDUMA. BILA YA KUZUIA HAPO JUU, HAKUNA “CURSOR STYLE” WALA INAYOHUSIANA NA “CURSOR STYLE” WAKILISHI HAKIKI KWAMBA TAA, ZANA, YALIYOMO YAKE AU TAIFA YOYOTE INAFANYIKA. IMEWEKWA. ILIWEZO, KUFUATANA, INAYOONGEA. KWA KUJALI. </p>
<p> Chini ya hali yoyote huduma, washirika wake au WAMILIKI WA LESENI, HUDUMA, WAFANYAKAZI, WAKALA, MAAFISA au WAKURUGENZI WATAWAJIBIKA KWA UHARIBIFU WA AINA YOYOTE, TUNATOA HUDUMA KWA DHIMA YOYOTE. AU TOVUTI ZINGINE au HUDUMA ZOTE AU VIFAA VILIVYOPATIKANA KATIKA HUDUMA AU KWA KILA TOVUTI, PAMOJA NA UHARIBIFU WOWOTE WA MOJA KWA MOJA, MAALUM AU WA KUTOKEA, PAMOJA NA MAJERUHI YA BINAFSI, MATATIZO YA KIHEMA, UHARIBIFU AU AKIYO YA JIRANI, UPOTEVU WA MATUMIZI, DATA AU MASHARTI MENGINE. UFUNDISHAJI HAUATHIRI DHIMA YOYOTE AMBAYO HAIWEZI KUTOLEWA AU KUPUNGUZWA KWA MUJIBU WA SHERIA INAYOTUMIKA AMBAYO INAWEZA KUJUMUISHA UDANGANYIFU. </p>
<p> Unakubali kulinda, kulipa fidia na kumfuta “Cursor Style”, washirika wake, walipa leseni na watoa huduma, na vile vile na wao maafisa wao, wakurugenzi, wafanyikazi, wakandarasi, mawakala, walipa leseni, wasambazaji, waliopwa na kutoka kwa madai yoyote na dhima, upotezaji wa maamuzi ya mahakama, gharama, gharama au tume (pamoja na ada ya wakili) inayotokana na au kuhusiana na ukiukaji wako wa Masharti haya ya matumizi au matumizi ya Huduma, pamoja na lakini sio mdogo kwa, kuripoti utumiaji wowote wa yaliyomo, huduma na bidhaa za Tovuti au Zana, isipokuwa kama ilivyoonyeshwa wazi katika Masharti haya ya Matumizi, au matumizi yako ya habari yoyote iliyopokelewa kutoka kwa Huduma. </p>
<p> Ikiwa kifungu chochote cha Masharti haya ya Matumizi kinapatikana kuwa batili, haramu au haitekelezeki na korti au mahakama nyingine yenye mamlaka kwa sababu yoyote, kifungu kama hicho kinapaswa kufutwa au kupunguzwa kwa kiwango cha chini, ili kwamba mapumziko ya vifungu vya Sheria na Masharti yataendelea kikamilifu. Masharti ya Matumizi, Sera yetu ya Faragha na hali ya kujiandikisha kwa hafla huunda makubaliano pekee na kamili kati yako na "Cursor Style" kuhusu Huduma na hubadilisha mikataba yote ya awali na ya wakati huo huo, makubaliano, uwakilishi na dhamana, iliyoandikwa na ya mdomo, kuhusu Huduma. </p>
<p> Mapitio yote, maoni, maombi ya msaada wa kiufundi, na ujumbe mwingine kuhusu Huduma unapaswa kuelekezwa kwa ukurasa wa usaidizi wa "Cursor Style" katika Duka la Wavuti la Chrome. </p> ',
];
