<?php

return [
    'halo_descr' => 'Halo je bojová fantasy mediální franšíza vytvořená společností Bungie. Založeno na původní trilogii videoher z pohledu první osoby. Děj se točí kolem událostí odehrávajících se v životě Master Chiefa, jednoho ze skupiny supervojáků s kódovým označením Spartan, a jeho společníka, umělé inteligence Cortany. Úspěch her vedl k rozšíření franšízy do dalších médií: vesmír Halo v současnosti zahrnuje mnoho knih, grafických románů, komiksů, kraťasů, animací a celovečerních filmů.',
    'halo_short_descr' => 'Dotkněte se kurzoru artefaktu, možná jste ten vyvolený',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'Panenky LOL Surprise se zamilovaly do dětí a získaly si jejich srdce od prvních minut. A to není překvapivé, protože takový úspěch je založen na tajemství, očekávání zázraku, příjemném překvapení, které potěší nejen děti, ale i jejich rodiče. Tajemství dárku se dítěti odhalí až po konečném rozbalení. V každém případě jsou panenky LOL atraktivním designem, intrikami, velkým množstvím úžasných a realistických doplňků a příjemných drobností, stejně jako nejvyšší kvalitou výroby a detailů hračky.',
    'lol_surprise_short_descr' => 'Roztomilé holčičky pro znalce krásných překvapení',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Série se točí kolem soutěže, kde 456 hráčů, kteří se všichni nacházejí v hlubokých finančních dluzích, riskují své životy, aby si zahráli sérii smrtících dětských her o šanci vyhrát miliardovou cenu. Uvnitř čeká lákavá cena se smrtelně vysokými sázkami. Název série vychází ze stejnojmenné korejské dětské hry. Hwang koncipoval myšlenku na základě vlastních ekonomických problémů na začátku svého života, stejně jako na nerovnosti ve společnosti v Jižní Koreji a kapitalismu.',
    'squid_game_short_descr' => 'Vyberte si správnou tvář hráče, když jdete All-In.',
    'squid_game' => 'Hra na oliheň',
    'harry_potter_descr' => 'Harry James Potter je hlavní postavou série románů anglické spisovatelky J. K. Rowlingové. V den svých jedenáctých narozenin se Harry dozvídá, že je čaroděj a je předurčen pro místo v Bradavické škole čar a kouzel, kde bude praktikovat magii pod vedením ředitele Albuse Brumbála a dalších školních profesorů. Harry také zjistí, že je již známý v celé magické komunitě románu a že jeho osud je spojen s osudem Voldemorta, nebezpečného temného mága.',
    'harry_potter_short_descr' => 'Co uděláte s kouzelnou hůlkou ze sbírky kurzorů Harryho Pottera?',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics je vydavatelství komiksů známé pro vytváření pozoruhodných superhrdinů jako Spider-Man, Iron Man, Captain America, Hulk, Thor, Avengers, Guardians of the Galaxy, X-Men, Fantastic Four a Deadpool. Marvelovi nejznámější padouši zahrnují Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom a Magneto. Marvel Comics a DC Comics spolupracovaly na několika crossover projektech a také spoluzaložily záměrně krátkodobý imprint Amalgam Comics.',
    'marvel_comics_short_descr' => 'Superhrdina žije v každém z nás – vyberte si toho svého',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Vítejte zpět v Cookie Kingdom ve hře Cookie Run: Kingdom od Devsisters, rozkošném strategickém RPG zasazeném do vesmíru Cookie Run. Nyní, když GingerBrave unikl zlé čarodějčině troubě, je čas, aby sestavil tým Sušenek a vydal se na cestu za obnovením padlého Cookie Kingdom. Odhalte pravdu o pádu Království a dejte dohromady tým nejsilnějších Sušenek Království, abyste porazili temné síly, které chtějí zabránit GingerBravovi ve splnění jeho osudu.',
    'cookie_run_kingdom_short_descr' => 'Malí bojovníci přímo z pece',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact je dobrodružná hra s otevřeným světem. To znamená, že nová, úchvatná krajina na vás čeká na druhé straně řeky nebo hory, jen musíte moudře využívat svou energii. Pokud narazíte na putující vílu nebo zvláštní mechanismus, odvažte se a pokuste se rozluštit jejich záhadu. Ale co slibují - potíže nebo příjemné překvapení - to můžete zjistit jen vy! Na rozlehlém kontinentu Teyvat navštívíte sedm království, najdete společníky s různými dovednostmi a budete bojovat proti mocným nepřátelům při hledání ztraceného milovaného.',
    'genshin_impact_short_descr' => 'Staňte se elementárním mistrem Sedmi království.',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Když se splní starověké proroctví a království se ponoří do náruče zimy, vydávají se tři nebojácní hrdinové - princezna Anna, statečný Kristoff a jeho věrný sob Sven - do hor, aby našli Annuinu sestru Elsu, která dokáže odstranit mrazivé kouzlo zemi. Cestou na ně čeká mnoho obtížných překvapení a vzrušujících dobrodružství. Setkání s mystickými trolly, setkání s okouzlujícím sněhulákem Olafem, horské štíty strmější než Everest a spousta magie. Hrdinové musí odolat mocným živlům, aby zachránili království a ty, kteří jsou jim drazí.',
    'frozen_short_descr' => 'Prolomit led je snadné se sbírkou kurzorů Ledové království',
    'frozen' => 'Ledové Království',
    'stranger_things_descr' => 'Uplynulo o něco více než šest měsíců od finále třetí sezóny. Joyce, Will, Jedenáctka a Jonathan se přestěhovali do Kalifornie, kde je dívka šikanována ve škole. Zbytek začíná bojovat s novým monstrem z paralelního světa, které se objevilo v Hawkingsu. Byl pojmenován Vecna ​​po postavě z deskové hry Dungeons & Dragons. Psychicky ovlivňuje teenagery, poté mentálně vlezou do hlavy a zabíjí. Souběžně s tím se Joyce a Murray dozvídají, že Jim Gopper je naživu, a vydávají se za ním do sovětského vězení v Kamčatce. A Jedenáctka se bude muset vrátit a zvýšit své síly, ale také se dozvědět o své důležité roli při vytváření stejného monstra v Gokinsu.

Spisovatelé nezměnili taktiky zápletky, které se jim v posledních pár sezónách líbily. Ve čtvrté sezóně rozdělili velkou skupinu hlavních postav na skupiny, vymysleli pro ně obtížné úkoly a na konci sestavili své příběhy společně v úžasném závěru. Nabízíme vám, abyste do detailu pochopili všechna tato dobrodružství s pomocí kolekce kurzorů Stranger Things.',
    'stranger_things_short_descr' => 'Co se stane dál? - Kurzor pro Stranger Things 4',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars je originální režim, který se poprvé objevil v Minecraftu. Úkolem hráčů bylo, aby uživatel chránil svou základnu a postel.

Roblox přináší každý den více vzrušujících her a BedWars není výjimkou. A jde o to, že pokud máte rádi bed wars a bráníte se ve svém pokoji, je to titul pro vás, protože vás vrací do dětství, i když tentokrát digitálně.

Stačí si s partnerem bránit postel před útočníky. Vstoupíte do lobby, vyberete si, s kým chcete hrát, a voila, je to jen otázka ochrany.

Samozřejmě, pokud jde o obranu, budete mít nějaké problémy a existují určité zdroje, předměty a předměty, které vám pomohou vyhrát. Například exkluzivní skiny, které najdete v kolekci kurzoru Bed Wars.',
    'roblox_bed_wars_short_descr' => 'Chraňte svou postel s kurzory z Roblox Bed Wars',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'Na narozeniny Naruta Uzumakiho zaútočil na vesnici Konoha legendární démon, liška s devíti ocasy. Čtvrtý Hokage za cenu svého života zachránil vesnici zapečetěním démona do novorozeného Naruta, nevědomky ho odsoudil k životu nenávisti ze strany jeho vesničanů.
Navzdory nedostatku talentu v mnoha oblastech ninjutsu, neklidu a povýšenosti má Naruto sen stát se Hokage, nejsilnějším ninjou ve vesnici. Toužící po uznání, kterého se mu nedostalo, tvrdě pracuje a trénuje po boku svých spoluhráčů Sasukeho Uchiha a Sakury Haruno a také svého mentora Kakashiho Hatakeho. On a jeho partneři si budou muset projít spoustou věcí na cestě ke svým drahocenným snům: bitvy, láska, přátelství, zrada, touha po moci. Sbírka kurzorů Naruto anime vám pomůže navigovat vaši vlastní cestu!',
    'naruto_anime_short_descr' => 'Vydejte se svou nindžovskou cestou s kurzory z anime Naruto',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'Děj se odehrává v éře Taisho. Od pradávna se šíří zvěsti, že v lese žijí humanoidní démoni, kteří se živí lidmi a v noci hledají novou oběť. Ale... je to jen legenda, že?..

Tanjiro Kamado je nejstarší syn v rodině, který ztratil otce a staral se o svou rodinu. Jednoho dne jde do nedalekého města prodávat dřevěné uhlí. Po návratu ráno chlapec před sebou objeví strašný obraz: všichni příbuzní byli brutálně zabiti a jediná přeživší je Nezuko, mladší sestra proměněná v démona, ale která ještě neztratila veškerou svou lidskost.

Od této chvíle začíná Tanjiro a Nezuko dlouhá a nebezpečná cesta, na které chlapec hodlá najít vraha a najít způsob, jak vyléčit svou sestru. Ale jsou děti schopny překonat všechny obtíže a vrátit se domů? Odpověď již znáte, a pokud ne - spíše si nastavte kurzory Demon Slayer, s postavami z jedné z nejpopulárnějších mang.',
    'demon_slayer_anime_short_descr' => 'Kurzory Zabití démonů - pro opravdové noční lovce',
    'demon_slayer_anime' => 'Anime Zabití démonů',
    'bts_descr' => 'BTS je sedmičlenná chlapecká skupina pod BigHit Music. Debutovali 13. června 2013 singlem "No More Dream". V Japonsku debutovali 24. prosince 2014 studiovým albem Wake Up.

Název skupiny pochází z korejského výrazu Bangtan Sonyeondan, což znamená "neprůstřelní skauti". Podle J Hope název znamená touhu kapely blokovat stereotypy, kritiky a očekávání, která jsou zaměřena na teenagery jako kulky.

Kolekce kurzorů věnovaných skupině zahrnuje všechny členy skupiny, zde kurzoru Kim Nam Joon (aka RM), kurzoru Kim Seok Jin (Jin), kurzoru Min Yoongiho (Suga), kurzoru Jung Ho Suka (J-Hope), kurzoru Park Ji Min (Jimin), kurzoru Kim Tae Hyun (V) a kurzoru Jeon Jungkook (Jungkook).',
    'bts_short_descr' => 'Seznamte se se svými idoly s kurzory BTS',
    'bts' => 'BTS',
    'miraculous_descr' => 'Kouzelná Beruška a Černý Kocour, známé také jako Miraculous: Tales of Ladybug and Cat Noir, jsou dobrodružství superhrdinů z kresleného seriálu o dvou spolužácích, kteří pod maskami hrají roli obránců Paříže před padouchem, který v každém díle vymýšlí nový způsob, jak poškodit město. Miraculous je vyroben ve Francii pomocí CGI a animace. Miraculous není jen animovaný seriál, ale také sbírka komiksů vydaných po celém světě. Seriál je velmi oblíbený u mladého publika.

Děj se odehrává v Paříži, kde jsou Marinette a Adrian středoškolskými studenty na moderní škole. Dostali roli stát se vyvolenými v boji proti zlu a zachránit své rodné město. Jejich cílem je chránit lidi před Akumami. Tato malá stvoření v podobě motýlů jsou schopna obývat osobu a proměnit ji v padoucha.

Marinette se může proměnit v Berušku a Adrian - v Černého Kocoura, ale překvapivě, pracujíce ve dvojici, se pod maskami superhrdinů nepoznávají.

Pomozte Černému Kocourovi a Berušce zachránit Paříž s našimi kurzory s vašimi oblíbenými postavami. Kterou postavu si vyberete pro kurzor? Bude to kurzor Kouzelné Berušky, nebo třeba rozkošná malá Beruška od Tikki nebo kurzor Černého Kocoura? Nebo třeba královna Bee s kurzory Rena Rouge? Volba je na vás!',
    'miraculous_short_descr' => 'Přidejte se do řad superhrdinů se sadou kurzorů Lady Bug a Cat Noir.',
    'miraculous' => 'Kouzelná Beruška a Černý Kocour',
    'talking_tom_descr' => 'Série sleduje každodenní život Talking Toma a jeho přátel. Tom a jeho nerdí obchodní partner Ben neustále vyvíjejí mobilní aplikace a další vynálezy, aby dosáhli slávy a bohatství a snaží se ukázat světu, ale to se vždy obrátí proti nim. Tomova přítelkyně, Angela, se snaží být zpěvačkou, bez ohledu na to, co pro to udělá. Tomův soused, Ginger, sem velmi často zaskakuje, aby si zahrál žerty s lumpárnami v rukávu. Hloupý nejlepší přítel a spolubydlící Hank je zůstává doma, sleduje HODNĚ TV. A bývalá disidentská popová hvězda Becca Sparkles se stala novou spolubydlící Angely a zdá se, že se zamilovala do Hanka. Bez ohledu na to, jak špatné jsou věci všech tvarů a velikostí, ať už je to zlý generální ředitel, Tomův záhadný nový soused, nebo jen nehoda v Benově novém výtvoru, parta se bude bavit bez ohledu na to, a vždy si pamatujte jednu věc, která je drží pohromadě: přátelství nikdy nekončí, stejně jako naše láska k postavám seriálu nekončí, takže si teď můžete nastavit kurzor Talking Toma nebo kurzor Bena, nebo možná kurzor Angely, kurzor Olivera!',
    'talking_tom_short_descr' => 'Pojďme si povídat o vaší oblíbené postavě v kolekci kurzorů Talking Tom.',
    'talking_tom' => 'Talking Tom a přátelé',
    'lego_descr' => 'Společnost The LEGO Group byla založena již v roce 1932 a tehdy se skládala pouze ze 7 lidí. Cílem týmu Lego bylo vytvářet hračky, které rozvíjejí dětskou kreativitu, představivost a vynalézavost. Úžasná skutečnost, že od svého vzniku v roce 1949 zůstaly LEGO prvky ve všech svých variantách navzájem kompatibilní. Všechny položky vytvořené později jsou stále kompatibilní s položkami, které se vydávají dnes, navzdory změnám designu a tvaru v průběhu let.

LEGO kostka je základ, což je dutý plastový blok, který se spojuje s dalšími podobnými kostkami. Ale Lego sady obsahují také další díly, kola, figurky, platformy a dokonce i elektronické obvody se senzory a elektrickými motory. Můžete sbírat modely aut, letadel, vlaků, lodí, budov, robotů. LEGO se drží myšlenky modularity, která dětem jasně ukazuje, jak řešit určité problémy, rozvíjet představivost, jemnou motoriku rukou a dovednosti sestavování. LEGO kostky jsou vyrobeny s neuvěřitelnou přesností a dokonale do sebe zapadají pro úžasných 10 mikronů přesnosti.

Nedávno bylo vytvořeno mnoho populárních 3D animovaných Lego příběhů, kde postavy ze sad ožívají a stávají se účastníky neuvěřitelných dobrodružství. Pokud chcete skvělý kurzor, najdete v naší kolekci Lego kurzorů mnoho postav z televizních seriálů a animovaných filmů Lego. Lego Ninjago Kurzory, Lego Batman Kurzory, Lego Ninjago Kurzory, Lego Wyldstyle Kurzory a mnoho dalších.',
    'lego_short_descr' => 'Postavte si svůj vysněný prohlížeč se sbírkou kurzorů Lego',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Po úspěšném financování na Kickstarteru v roce 2017 vydal Team Cherry multiplatformní PC hru Hollow Knight. Toto je příběh bezejmenného rytíře a jeho objevů v hmyzím království Hallownest. Hra byla právem uznána jako jedna z nejlepších v žánru metroidvania.

Hratelnost Hollow Knight je založena na průzkumu herního světa. Překonávání překážek, řešení hádanek a hledání tajemství, stejně jako boj s nepřáteli. Hráč má jedinečnou sadu vylepšení a triků pro průzkum světa a boj v bitvách. Přesunem ze zóny do zóny hráč poráží bossy a získává potřebná vylepšení, aby se dostal dál. Výsledkem je, že hráči musí navštívit již projité oblasti, aby našli tajemství a prošli příběhem. A je to také vzrušující, protože zóny se pokaždé mění a přinášejí nová překvapení a zážitky. Hru lze hrát různými způsoby, protože mezi zónami existuje několik různých cest. Procházením příběhem si otevřete mapu zóny, ale nejprve musíte mapu získat.

Hlavní zbraní hrdiny je hřeb, který je poněkud podobný meči, zbraně lze vylepšit u kováře a také se naučit různým dovednostem v používání zbraní, což rozšiřuje rozmanitost útoků. Útočením na nepřátele hromadíte speciální zdroj, který lze později použít pro vylepšení nebo léčení.
Bavte se hraním Hollow Knight a nezapomeňte na naše Hollow Knight kurzory s vaší oblíbenou postavou. Naše kolekce obsahuje kurzor Mister Mushroom, kurzor Quirrel, kurzor Hornet Needle, kurzor Old Nail, kurzor Myla a další.',
    'hollow-knight_short_descr' => 'Neztratte se v říši hmyzu s kolekcí kurzorů Hollow Knight',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickmin je hlavní postavou série. Stikmin, dříve bezejmenný, začínal jako menší zloděj, s touhou rychle a snadno vydělat peníze. Po útěku z věznice West Mesa však v jeho životě dochází k mnoha změnám a stává se slavným zločincem po krádeži Tunisanského diamantu. Henry má na výběr - stát se úspěšným vládním agentem, lovcem odměn, vůdcem zločinecké organizace, kyborgem, nebo pokračovat v kriminální stezce sám. Hra potěší fanoušky žánru mnoha dobrodružstvími a záhadami a v naší nové kolekci kurzorů Henry Stickmin najdete jeho vtipné postavičky, včetně kurzoru Henry Stickmin, kurzoru Charles Calvin, kurzoru Reginald Copperbottom, kurzoru Pravá ruka, kurzoru Ellie Rose a dalších!',
    'henry-stickmin_short_descr' => 'Naplánujte si svůj útěk od nudy s kolekcí kurzorů Henry Stickmin',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'Velmi populární online hra Adopt Me byla spuštěna v roce 2017 a stala se nejpopulárnější na herní platformě Roblox. Podstata hry je velmi jednoduchá - získat vejce se zvířátky a starat se o ně.

Virtuální mazlíčci se dělí do 5 tříd, některé z nich jsou velmi vzácné a drahé, zatímco jiné se dají získat velmi snadno. Jedná se o neobvyklé skupiny, jako je například Blue Dog, Common, Rare kurzor, například kurzor myši Adopt Me Monkey, a také ultra-vzácné, jako je kurzor Koala, a Legendární, kurzor Dragon a Accept me unicorn. Pokud má hráč čtyři dospělé mazlíčky stejného typu, mohou se spojit do neonového mazlíčka, jako je třeba kurzor hry Neon Horse nebo Adopt Me Neon Starfish. Spojením čtyř běžných mazlíčků můžete vytvořit neonového mazlíčka, který se opravdu leskne, a z neonových mazlíčků můžete vytvořit mega-neonového mazlíčka.

Nákupy ve hře Adopt Me! se provádějí pomocí virtuální měny Roblox - takzvané Robux, a hra má také vlastní měnu - Bucks. Starostí o vašeho mazlíčka, kromě zábavy, můžete vydělávat bucks, jen ho nakrmit, uložit do postele nebo přečíst pohádku, obecně hodně zajímavých věcí.

Nyní si fanoušci hry Roblox "Adopt Me!" mohou ozdobit svůj herní kurzor oblíbeným mazlíčkem!',
    'adopt-me_short_descr' => 'Bavte se s roztomilými mazlíčky v naší Adopt Me! kolekci herních kurzorů',
    'adopt-me' => 'Adopt me!',
    'among-us_descr' => 'Among Us je založen na slavné hře na hrdiny "Mafie". Bylo plánováno, že hra bude exkluzivně pro mobilní zařízení, protože měla pouze jednu mapu. Hra se rychle stala populární. Později vývojový tým přidal režim pro více hráčů a v roce 2019 byly vydány dvě další mapy.
Among Us je hra z ptačí perspektivy, která umožňuje hráči pohyb ve všech směrech. V jednom kole může hrát od čtyř do deseti hráčů. Na začátku hry je každému tajně přidělena role zrádce nebo člena posádky. Impostor (v ruském překladu "zrádce") se může skrývat v ventilačním otvoru, sabotovat a zabíjet členy posádky. Jeho cílem je zničit všechny členy posádky nebo zničit kosmickou loď sabotáží. Cílem posádky lodi je vyřešit různé hádanky připravené pro ně na začátku hry. Pokud každý z členů posádky splní všechny úkoly, zrádci prohrají. Posádka lodi může také dosáhnout vítězství eliminací zrádců během hlasování.
Zrádci mohou čas od času sabotovat, a pokud se poruchy neopraví do 30 sekund, posádka prohraje. Před spuštěním hry si můžete vybrat barvu postavy, za kterou hrajete, modrou, červenou, žlutou, šedou - cokoliv! A nezapomeňte si nastavit vhodný kurzor z nové kolekce Among Us!',
    'among-us_short_descr' => 'Nenechte se zmást v této složité vesmírné hře s kurzory Among Us',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Tvůrce "Steven Universe" byla Rebecca Sugar. Je známá svou předchozí prací s názvem Adventure Time. První epizoda Steven Universe byla zveřejněna na platformě YouTube na jaře 2013. Ale na podzim ji americký kanál Cartoon Network začal vysílat pro své diváky. Od té doby bylo vydáno 6 sérií. Šestá slibuje, že bude poslední.
Co se týče děje animovaného seriálu, točí se kolem týmu Crystal Gems. Skládá se z mimozemských tvorů s charakteristickými jmény: Pearls, Amethyst a Pomegranate. Ale je tu ještě jeden účastník, v roli kterého vystupuje obyčejný chlapec Stephen. Společně hledají monstra a snaží se je neutralizovat, aby se zmocnili Země pro osobní prospěch. Stojí proti nim Jasper a Peridot - poslové z jejich domovské planety, kteří chtějí porazit Gems a zapnout Cluster.
Pokud jste fanouškem Steven Universe a chcete vidět postavy z animovaného seriálu, kdekoli můžete, nainstalujte si rozšíření Cursor Style! Proč to dělat? Můžete přidat kolekci věnovanou "Steven Universe" a proměnit standardní ukazatel myši v jednu z vašich oblíbených postav.',
    'steven_universe_short_descr' => 'Odhalte tajemství drahokamů s kurzory Steven Universe',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Animovaný sitcom s názvem "Family Guy" za celou dobu své existence 4krát získal cenu Emmy a 3krát cenu "Annie". Animovaný seriál zesměšňuje bolestivé problémy americké společnosti, jako jsou: feminismus, otroctví, obezita, politika atd. Na rozdíl od jiných děl se zde používají vsuvky s vtipy a sarkasmem. Navíc v mnoha případech nejsou integrovány do zápletky, ale existují samy o sobě.
Jedna epizoda animovaného seriálu se vytváří přes 10 měsíců. Proč tak dlouho? Protože je celá animace kreslena ručně. Kvůli tomu mají některé události, které dílo pokrývá, čas ztratit relevanci. Ale i tak zůstává sitcom velmi zajímavý a získává přízeň diváků po celém světě. Koneckonců, kdo se nerad dobře zasměje politikům, celebritám nebo lidem, kteří se dopouštějí divokých kousků a tím překvapují nebo dokonce šokují obyčejné lidi.
Máte rádi "Family Guy"? Máte jedinečnou příležitost proměnit normální kurzor myši na jakoukoli z postav tohoto animovaného seriálu! Co musím udělat? Stačí nainstalovat rozšíření prohlížeče „Cursor Style“, přidat do něj kolekci věnovanou "Family Guy" a užít si báječnou reinkarnaci!',
    'family_guy_short_descr' => 'Kolekce kurzorů Family Guy pro znalce specifického humoru',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Jistě jste slyšeli výraz "Krása zachrání svět"? Mnoho lidí, zejména dívek, s tímto tvrzením souhlasí. Proto se snaží obklopit vším tím nejkrásnějším a oku lahodícím. Může to být růžová tapeta v ložnici, plyšové hračky, polštáře vyšívané korálky, drahé šperky atd. Zvenku to všechno vypadá velmi roztomile a dokonce trochu dětinsky. Ale každý z nás je v srdci trochu dítě, tak proč ho nenechat projevit naši fantazii?
Něžnost v nás toho může způsobit hodně. Například soucitné oči koťátka, které se chce nechat pohladit nebo nakrmit. Duhová duha, vykukující po jarním dešti a třpytící se všemi barvami na slunci. Dítě, které dostalo čokoládu, a rozhodlo se ji sdílet se svou kamarádkou nebo kamarádem. Důvodů pro dojemnost je docela dost, a my jsme se rozhodli je použít jako kurzory.
Už vás nebaví nudná bílá šipka ve vašem prohlížeči? Nahraďte ji něčím roztomilým z naší kolekce! Například růžovým a bílým jednorožcem, smutným rajčetem, zamračeným mrakem, pichlavým kaktusem ve tvaru kočky nebo čímkoli chcete. Jediné, co musíte udělat, je nainstalovat rozšíření Cursor Style a přidat do něj sbírku roztomilých kurzorů. A ať žije spasitel světa - krása!',
    'cute_cursors_short_descr' => 'Svět bude laskavější s kolekcí roztomilých kurzorů',
    'cute_cursors' => 'Roztomilé Kurzor',
    'web_media_short_descr' => 'Žijte v moderním rytmu se sbírkou kurzorů webových médií',
    'web_media' => 'Webová média',
    'bobs_burgers_descr' => 'Animovaný seriál Bob\'s Burgers je zápletkou animovaného díla a charismatem postav. A soudě dle nominace na cenu Emmy a uznání díla jako jedné z nejlepších karikatur na celém světě, Bob\'s Snack opravdu udělal rozruch.
Zápletka animovaného seriálu se točí kolem rodiny Boba Belchera. Tato osoba je majitelem restaurace v prvním patře a ve druhém patře žije se svými blízkými. Bob má veselou ženu Lindu a 3 děti: Gene, Louise a Tinu. Chlapec sní o hudební kariéře, nejstarší dcera Tina je velmi laskavá, ale neohrabaná a nejmladší - Louise je stále mrcha a často dostává svou rodinu do nepříjemné situace. Hlavním konkurentem Bob’s Burgers je pizzerie Jimmyho Pesta. Jak asi tušíte, majitel této pizzerie se jmenuje Jim a on a Bob se nenávidí. To všechno bylo zpracováno tak, aby to vypadalo komicky, ne vážně. Proto i mnoho jejich potyček vyvolává pouze úsměv.
Pokud máte rádi animovaný seriál „Bob\'s Burgers“ a chcete jeho postavy vidět nejen na obrazovce monitoru nebo televize, nainstalujte si rozšíření, přidejte kolekci a změňte kurzor myši v prohlížeči na některou z postav této karikatury!',
    'bobs_burgers_short_descr' => 'Bob dělá burgery a my děláme kurzory Bob\'s Burgers',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'Historie videohry "Kirby" začala již v 90. letech minulého století. Skládá se z mnoha sérií, které vyvinuly společnosti Nintendo a HAL Laboratory. Hra je určena pro děti od jednoho a půl do 8 let. O její popularitě lze soudit podle počtu prodaných kopií. Přes 34 milionů po celém světě.
Hlavní postavou Kirbyho je stejnojmenná růžová bytost. Žije na planetě zvané Pop Star a periodicky ji chrání před různými nebezpečími. Kirby dokáže nadechnout některé objekty a své nepřátele tak, aby se pak naučil jejich schopnosti: boj zblízka, ovládnutí meče, dýchání ohně atd. Růžový nafukovací míček však nejen bojuje s nepřáteli, ale také řeší různé hádanky, cestuje do jiných zemí a může dokonce létat po úrovních.
Tuto videohru můžete hrát na konzolích Nintendo nebo Game Boy. Ve všech sériích jsou roztomilí hrdinové, dobrá grafika a vtipné soundtracky. Mimochodem, za téměř 30 let od vydání první verze svět stihl spatřit 20 sérií Kirbyho. Tento ukazatel ve spojení s mnohamilionovým objemem prodaných kopií pomohl hře dostat se do TOP 50 nejúspěšnějších a nejvyhledávanějších videoher v herním průmyslu.
Milujete Kirbyho natolik, že byste tuto postavu rádi viděli, kde to jen jde? Potom použijte kolekci Kirby a proměňte běžný ukazatel myši v hlavního hrdinu vaší oblíbené videohry! Jsme si jisti, že se vám nový vzhled kurzoru bude líbit.',
    'kirby_short_descr' => 'Zkuste nasát celou sbírku kurzorů Kirby',
    'kirby' => 'Kirby',
    'undertale_descr' => 'V dávných dobách Zemi neobývali pouze lidé, ale i monstra. Kvůli neshodám mezi nimi vypukla válka, která skončila ve prospěch lidské rasy. Sedm mágů vyhnalo monstra pod zem a navždy je tam uvěznilo kouzlem bariéry. K Mount Ebott byl však jen jeden vchod, čehož dítě využilo. Za něj budete hrát spuštěním počítačové hry Undertale.
Tuto hru vyvinul Toby Fox - známý programátor ze Spojených států. Zpočátku si ji mohli užívat majitelé osobních počítačů se systémem Microsoft Windows a Linux, a poté přišla řada na uživatele herních konzolí.
O co v této hře jde? Chlapec cestuje podsvětím obydleným monstry. Některé z nich jsou okamžitě nepřátelské, zatímco jiné si rádi povídají. Hráč si může vybrat jedno ze 2 chování: vyhnout se násilí nebo bojovat. V prvním případě bude projití hry snazší, v druhém - naopak obtížnější. Děj a konec, který se může větvit a měnit, závisí také na této volbě.
Pokud se vám líbí Underground Tale a chcete vidět jeho postavy ve svém prohlížeči, nainstalujte si rozšíření a přidejte příslušnou sbírku kurzorů! Proměňte nudný ukazatel myši na jedno z monster nebo hlavní postavu Undertale!',
    'undertale_short_descr' => 'Je čas dostat se z díry pomocí kurzorů z Undertale',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune je role-playing hra vydaná pro počítače před pár lety. Vytvořil ji stejný programátor, který vyvinul Undertale. Nicméně, tyto dvě hry si nejsou téměř podobné, i když mají pár společných postav a lokací.
V Deltarune je několik hlavních postav. Jde o studenta Chrise, který se dá ovládat, a okouzlující monstrum Susie, které se ovládat nedá. Obě postavy spadnou do světa temnoty, kde potkají jednoho z jeho obyvatel - Ralseie. Ten jim řekne, že ve skutečnosti jsou tvory světla, kteří mají za úkol zastavit tok temné energie v ponurém světě. Aby to dokázali, musí šetřit místní monstra a snažit se s nimi nepouštět do boje, i když to je někdy dost těžké.
Hráč má jednoduchou volbu: buď temné tvory ušetřit, nebo je napadnout. Jelikož Susie není fanouškem polovičatých řešení, v mnoha případech si vybere boj. Proto Chris nemá na výběr a musí podpořit svou přítelkyni a pomáhat jí v bitvách.
Milujete hru Deltarune? Pak si stylizujte kurzor myši v prohlížeči na jednu z jejích postav! Můžete to udělat s naším rozšířením. Nainstalujte si ho, přidejte kolekci “Rune Delta” a aktivujte! Nyní vaše šipka přestala být stejná jako všichni ostatní a stala se Chrisem, Susie nebo jedním z tvorů temného světa.',
    'deltarune_short_descr' => 'Ponořte se do temného světa s touto kolekcí kurzorů',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario je série počítačových her vydaných společností Nintendo. První a nejpopulárnější hra se jmenovala Super Mario Bros. Světlo světa spatřila v roce 1985. Později se dostala do Guinnessovy knihy rekordů. Od té doby bylo vydáno více než 20 her, z nichž každá má svůj vlastní děj. V roce 2019 se objevila nová verze s názvem Super Mario Maker 2. Navzdory vylepšení grafiky zůstal styl a postavy stejné, což vyvolává nostalgii po Super Mario z 80. let.
Hlavním hrdinou je stále instalatér Mario. V ději poslední variace hry nezůstal zámek princezny kámen na kameni. Mario ho musí přestavět, poté, co si před tím vydělal mince, které se mu platí za úkoly. Celkem má tato hra více než 100 úrovní různé obtížnosti s možností úprav. Také v Super Mario Maker 2 existují nové herní režimy. Můžete hrát čtyři z nich najednou a jakmile jeden skončí, úroveň se považuje za dokončenou. Existují také režimy jako: Mario Marathon, Duel a závody Ninjik.
Milujete Super Mario a vše, co souvisí s touto úžasnou hrou? Pak si nastavte kurzory vyrobené ve stylu tohoto platformeru! Jsme si jisti, že se vám bude líbit kurzor Maria, kurzor Luigiho, kurzor princezny Peach a další kurzory, které jsou prezentovány v naší sbírce!',
    'super_mario_short_descr' => 'Procházejte houbovým královstvím se sbírkou kurzorů Super Mario',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls byl vytvořen společně společností Disney Television Animation Corporation a Alexem Hirschem. Premiéra byla vydána v roce 2012 a byla promítána na Disney Channel. Celá první sezóna animovaného seriálu se tam točila. O dva roky později byla vydána druhá sezóna, kterou diváci mohli sledovat na předchozím kanálu a na Disney XD. Fanoušci Gravity Falls se bohužel nedočkali třetí a dalších sezón. Tvůrci se rozhodli omezit se na dvě sezóny bez jakýchkoli pokračování.
Co se týče zápletky tohoto animovaného obrázku, pak se veškerá akce odehrává ve fiktivním městě zvaném Gravity Falls. Přicházejí sem dvojčata, která se jmenují Mabel a Dipper. Zůstávají u svého bratrance Stana. Má vlastní turistický obchod se suvenýry. Když se bratři nudí "neděláním ničeho", jdou hledat dobrodružství. Jeden z nich najde v lese podivný deník, který vypráví o anomáliích tohoto města. Dvojčata se vydávají hledat jeho autora a setkávají se s neobvyklými tvory a místy. Pokud se o tento animovaný seriál zajímáte a byli jste kdysi fanoušky jeho postav, doporučujeme vám naši sbírku kurzorů myši ve stylu Gravity Falls!',
    'gravity_falls_short_descr' => 'Vydejte se na dobrodružství s kurzory Gravity Falls',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'O tak slavném animovaném seriálu jako Simpsonovi slyšel naprosto každý. Dokonce i ti lidé, kteří to nikdy neviděli, si jsou vědomi existence žlutých postav. A fanoušci jsou nadšeni, když vyjde další sezóna jejich oblíbeného kresleného filmu. Mimochodem, na podzim roku 2019 vyšlo 31 účtů za sezónu. A první se objevila na televizních obrazovkách již v roce 1989. Fox to začal ukazovat a stále to dělá kvůli vysokému hodnocení a sympatiím publika.
Simpsonovi jsou satirický žánr, který se dotýká relevantních témat. Může to být životní styl průměrného Američana, politické a náboženské otázky, "hvězdné" triky celebrit, feminismus, manželství osob stejného pohlaví. Obecně vše, co souvisí s místními a globálními událostmi, kterých se Spojené státy účastní.
Akce animovaného seriálu se odehrává ve neexistujícím městě Springfield. V Americe je ve skutečnosti spousta měst s tímto názvem. Možná proto byl vybrán, aby si publikum nespojovalo to, co se děje na obrazovkách se specifickou lokalitou, ale pouze uhodlo, kde by to mohlo být.
S největší pravděpodobností jste fanouškem Simpsonových. Jinak proč byste četli tento text až do konce? A pokud ano, pak máte možnost změnit nudný kurzor myši na ukazatel, který je vyroben ve stylu tohoto animovaného seriálu.',
    'simpsons_short_descr' => 'Zábavná malá rodinka se zobrazením kurzorů Simpsonových.',
    'simpsons' => 'Simpsonovi',
    'youtubers_descr' => 'Platforma YouTube se objevila v roce 2005. Zpočátku se tam videa publikovala jen kvůli sebevyjádření nebo informování o něčem. Postupem času se to všechno rozrostlo v lukrativní byznys, který úspěšným uživatelům YouTube přináší tisíce, a někdy miliony dolarů měsíčně. Čím populárnější vloger (osoba, která vede video blog), tím více si může prostřednictvím svého kanálu vydělat.
Kolik si vydělává pětiletá vlogerka, jejíž rodiče ji berou na nejzajímavější atrakce a natáčejí, co se děje na kameru? Je to prostě to, jak se dítě baví v dětských parcích, což vyjadřuje emoce, jak se blbnout a všechny tyhle věci. Částka je opravdu úžasná - dnes má dětský kanál téměř 47 milionů odběratelů a začal generovat příjem ve výši 5 milionů rublů měsíčně.
Někdo nahrává videa, kde diskutuje o počítačových hrách, někdo beatboxuje nebo pořádá vtípky pro kolemjdoucí na ulici. Někteří věnují svá videa citlivým tématům, jako je vztah mezi mužem a ženou. Čím více se uživatelům YouTube tyto záběry líbí, tím vyšší je popularita vlogera.
Kolekce již přidala kurzor PewDiePie, kurzor Shane Dawson, kurzor Ray William Johnson, kurzor Zoella, kurzor MyLifeAsEva a další.',
    'youtubers_short_descr' => 'Nová generace hvězd je vždy online v naší kolekci YouTubers',
    'youtubers' => 'YouTubers',
    'pusheen_descr' => 'Téměř každý zná kočku Pusheen. I přesto, že je to jen postava z dětského komiksu, který byl vynalezen před 10 lety, má dnes miliony fanoušků. Kočka Pusheen se objevila jako ilustrace vytvořená umělkyní Claire Belton.
O rok později získala kočka vlastní stránku na Tumblr.com a během několika týdnů získala celou armádu fanoušků - asi 10 000 lidí. V roce 2013 byl Facebook dychtivý zahrnout obrázky z Pushinu do kolekcí s dalšími emotikony. Po jednání s tvůrcem se tato myšlenka uskutečnila a „explodovala“ internet! Obrázky od kočky Pusheen se používají v korespondenci více než 10 milionkrát denně!
V roce 2014 si tuto postavu všiml jeden z největších výrobců hraček ve Spojených státech. GUND (byla to ona, kdo vymyslel medvídky) uvedla na trh pár modelů Pushin. Jelikož byl úspěch obrovský, po několika měsících byla vytvořena kompletní kolekce hraček v podobě této kočky.
Kde jinde se můžete setkat s kočkou Pusheen? V dárkových sadách od Isaac Morris Ltd, v marshmallows od Boomf a samozřejmě v naší kolekci kurzorů Pusheen!',
    'pusheen_short_descr' => 'Přidejte do svého prohlížeče trochu pohodlí s kolekcí kurzoru Pusheen',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'První série animovaného díla „Rick a Morty“ byla vydána v roce 2013. Tento kreslený seriál lze připisovat přímo ke 2 žánrům: sci-fi a komedie. Jeho tvůrci byli Dan Harmon a Justin Royland. Zpočátku se všechny série vysílaly na kanálu Cartoon Network a teprve poté se duplikovaly v online kinech a video hostingu. Každých pár let vycházejí nové série Ricka a Mortyho a v listopadu 2019 vyšla čtvrtá série, která se ukázala být neméně zajímavá než ty předchozí. Děj animovaného seriálu se točí kolem génia a zároveň šíleného vědce jménem Rick, stejně jako jeho nevýrazného vnuka - Mortyho. Tyto dvě postavy spojují společná dobrodružství na nejneobvyklejších místech. A dostanou se tam na létajícím talíři, který je schopen se pohybovat mezihvězdným tunelem. Jak jste možná uhodli, tento animovaný seriál se trochu podobá filmu Zpátky do budoucnosti, ale stále to není jeho animovaná verze. Nicméně byl chválen mnoha kritiky za humorné epizody, kreativitu a originalitu. Chcete vidět Ricka nebo Mortyho nejen v seriálu tohoto díla, ale také v prohlížeči? Pokud ano, nainstalujte si rozšíření a přidejte naši kolekci věnovanou vašemu oblíbenému kreslenému seriálu! Zde je kurzor Ricka Sáncheze, kurzor Mortyho Smithe, kurzor Portálové zbraně a samozřejmě kurzor pana Meeseekse.',
    'rick_and_morty_short_descr' => 'Přestaň bručet, a prostě používej kurzory z kolekce Rick and Morty',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Fanoušci baseballu se nacházejí kdekoli na světě. To platí zejména pro obyvatele zemí jako: USA, Čína, Kuba, Jižní Korea, Japonsko a Venezuela. Na rozdíl od všeobecného přesvědčení, baseball nevznikl v Americe, ale v Anglii. První zmínka a popis baseballu se objevily v dalekém roce 1744, v anglickém vydání. Po 145 letech si Američané tento vynález přisvojili, navzdory faktům.
National League byla založena v roce 1876. Je součástí Major League v Kanadě a Spojených státech. Dnes existuje v National Baseball League 15 týmů. V závěrečné části každé sezóny přichází čas play-off, kterého se účastní 4 nejlepší týmy. Tím se odhalí vítěz celé National League. Vítězný tým pak dostane příležitost hrát proti vítězi z American League ve World Series.
Máte zájem o baseball nebo dokonce fandíte jednomu z týmů? Poté uctěte svůj oblíbený tým nastavením kurzoru myši ve formě jeho atributů! Změňte nudný vzhled ukazatele v prohlížeči na známou baseballovou firemní identitu! Proměňte šipku na pálku nebo helmu hráče v některém z týmů National League, které již zahrnují kurzor New York Yankees, kurzor Great Falls Dodgers, kurzor Boston Red Sox, kurzor Baltimore Orioles, kurzor Oakland Athletics.',
    'mlb_teams_short_descr' => 'Kolekce kurzorů MLB týmů pro všechny naše fanoušky.',
    'mlb_teams' => 'MLB Týmy',
    'brawl_stars_descr' => 'Brawl Stars je mobilní hra v žánru MOBA od Supercell. Navzdory vydání na konci roku 2018 si hra získala velkou popularitu, a to především díky hojnosti bojových režimů a barevným, fantastickým hrdinům - rváčům. Hráč má z čeho vybírat - 32 jedinečných postav a každá z nich má svůj vlastní soubor schopností a dovedností. Každý hrdina má také svou vlastní pasivní dovednost, která je k dispozici prostřednictvím truhlic s kořistí. Hráči mohou bojovat v několika režimech, například "Odměna za dobytí" - jeden ze dvou týmů vyhrává, kdo nasbíral více hvězd zabíjením soupeřů. V režimu "loupež" je nutné rozbít trezory soupeřů a zároveň si udržet vlastní. Zajímavý režim „Gem Grab“ - vítězem se stává tým, který nasbírá nejvíce drahokamů. No, v režimu "Kolize" proti sobě na mapě bojuje 10 hráčů, kde se hranice snižují vlivem toxického mraku. Hra překypuje barevným designem, který se mnoha lidem líbí, včetně nás, což nás inspirovalo k vytvoření samostatné kolekce kurzorů Brawl Stars. Existují kurzor Shelley z Brawl Stars, kurzor Barley, kurzor Penny, kurzor Frank, kurzor Mortis a další.',
    'brawl_stars_short_descr' => 'Vyberte si kurzory z Brawl Stars a nechte bitvu začít',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Změňte si kurzor myši dvěma kliknutími! Bezplatné kolekce pro každý vkus.',
    'all_descr' => 'Pokud jste někdy přemýšleli, jak změnit nudný kurzor myši, pak jsou naše kolekce kurzorů pro vás! Zde najdete skvělé komiksové hrdiny, krásné kurzory pro hráče s postavami z populárních her, zábavné sady kurzorů pro praktické vtipy, barevné kurzory a mnoho dalších zajímavých možností.',
    'text_title' => 'Super a nejzábavnější sbírky kurzorů pro každý den',
    'text_allcat_title' => 'Unikátní a kreativní kurzory myši, které se hodí ke každé vaší náladě',
    'text_1' => 'Nechcete být jako všichni ostatní? Nebo prostě milujete všechno neobvyklé? Chcete být součástí svého oblíbeného herního hrdiny nebo kreslené postavičky? Pak jste na správné adrese. Zde najdete jasné, neobvyklé sady kurzorů, které mohou nahradit známou a již docela nudnou bílou šipku. Kurzorem myši nás provází celý den v práci i ve studiu, takže by měl přinášet skvělou náladu a naladit na pozitivní mysl.',
    'text_2' => 'Zde naleznete kurzory pro hráče a milovníky filmů, krásné kurzory založené na vašich oblíbených karikaturách a sportovních motivech pro nejaktivnější lidi. Máte rádi komiksy nebo si nedokážete představit jediný den bez vtipných memů? Milujete zvířata nebo sníte o návštěvě všech zemí světa? Všechno je jednoduché - máme pro vás i vhodný obrázek kurzoru. Můžete si také vybrat obrázky v závislosti na tom, s čím pracujete. Například černý kurzor bude mnohem pohodlnější než bílý při práci s dokumenty nebo kresbami a kurzor ruky bude pohodlnější, pokud musíte pracovat s malými grafickými prvky. Vyberte si svůj oblíbený obrázek, upravte jeho velikost přímo v rozšíření - a používejte jej s potěšením, každý den počínaje pozitivní notou!',
    'install_to_preview' => 'Chcete-li zobrazit náhled, nainstalujte si prosím rozšíření',
    'install' => 'Instalovat',
    'add_button' => 'Přidat',
    'preview_button' => 'Náhled',
    'added_button' => 'Přidáno',
    'add_cursor' => 'Přidat kurzor',
    'to_your_collection' => 'do vaší sbírky',
    'prev_text_1' => 'Náhled na celou obrazovku',
    'prev_text_2' => 'kurzoru',
    'cursor' => 'kurzor',
    'pointer' => 'ukazatel',
    'a_title_1' => 'Cursor Style - Super kurzory pro váš prohlížeč',
    'a_title_2' => 'Super sbírky tematických kurzorů',
    'mouse_cursors' => 'kurzory myši',
    'cursor_collection' => 'Sbírka kurzorů',
    'sborka_cursorov' => 'sbírka kurzorů',
    'collection_list_from_colllection' => 'Seznam kurzorů - ',
    'christmas' => 'Vánoce',
    'nhl_teams' => 'Národní hokejová liga',
    'neon' => 'Neon',
    'adventure_time' => 'Adventure Time',
    'nba_teams' => 'Národní basketbalová asociace',
    'spongebob' => 'Spongebob',
    'phineas_and_ferb' => 'Phineas a Ferb',
    'fortnite_chapter_2' => 'Fortnite Chapter 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Celebrity',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Komiksy',
    'igry' => 'Hry',
    'multfilmy' => 'Kreslené Filmy',
    'kino_i_serialy' => 'Filmy a Seriály',
    'anime' => 'Anime',
    'futbol' => 'Fotbal',
    'avtomobili' => 'Auta',
    'memy' => 'Memy',
    'emodji' => 'Emoji',
    'pitomcy' => 'Zvířata',
    'stil_i_krasota' => 'Móda a styl',
    'prazdniki' => 'Svátek',
    'flagi' => 'Vlajky',
    'vokrug_sveta' => 'Po celém světě',
    'eda_i_napitki' => 'Jídlo a pití',
    'cvetnye' => 'Barevné',
    'prank' => 'Žerty',
    'startovyj_nabor' => 'Startovací sada',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Santa bude milovat vaše vánoční kurzory',
    'nhl_teams_short_descr' => 'Kolekce kurzorů NHL pro opravdové fanoušky',
    'neon_short_descr' => 'Přidejte jas s neonovou kolekcí',
    'adventure_time_short_descr' => 'Učení matematiky s kolekcí kurzorů Adventure Time',
    'nba_teams_short_descr' => 'Kurzory NBA jako symbol velkých basketbalových vítězství',
    'spongebob_short_descr' => 'Zjistěte, kdo žije na dně oceánu, s kolekcí kurzorů SpongeBob',
    'phineas_and_ferb_short_descr' => 'S touto kolekcí kurzorů Phineas a Ferb se rozhodně nebudete nudit',
    'fortnite_chapter_2_short_descr' => 'Nová kapitola kultovní hry Fortnite',
    'pokemon_short_descr' => 'Chyť je všechny, pokud to dokážeš',
    'famous_people_short_descr' => 'Nechte se inspirovat kurzorem svého idolu',
    'the_elder_scrools_short_descr' => 'Ponořte se do světa rytířů a draků',
    'halloween_short_descr' => 'Bojte se, abyste nezmeškali novou halloweenskou kolekci',
    'nfl_teams_short_descr' => 'Pro opravdové fanoušky amerického fotbalu',
    'five_nights_at_freddy_short_descr' => 'Snažte se neleknout těchto animatroniků.',
    'komiksy_short_descr' => 'Kurzory z komiksů: vyberte si svou náladu pro dnešek.',
    'igry_short_descr' => 'Virtuální realita: za koho dnes hrajete?',
    'multfilmy_short_descr' => 'Oblíbené kreslené postavičky v novém designu',
    'kino_i_serialy_short_descr' => 'Pán Prstů kurzoru: Bratrstvo pracovní plochy',
    'anime_short_descr' => 'Anime miluje každý: která je vaše oblíbená postava?',
    'futbol_short_descr' => 'Jste skutečný sportovní fanoušek? Pak musíte být tady.',
    'avtomobili_short_descr' => 'Auto vašich snů: velká flotila pro profesionály.',
    'memy_short_descr' => 'Oblíbené motivy: kolekce kurzorů Memes.',
    'emodji_short_descr' => 'Ukažte své skutečné emoce ostatním - nastavte si Cursoji!',
    'pitomcy_short_descr' => 'Jasné kurzory pro všechny milovníky našich menších bratrů',
    'stil_i_krasota_short_descr' => 'Originální kurzory pro všechny příležitosti',
    'prazdniki_short_descr' => 'Co je na kalendáři? Nová kolekce kurzorů Svátků!',
    'flagi_short_descr' => 'Hledáte dobrodružství: kam dnes jdeme?',
    'vokrug_sveta_short_descr' => 'Kolem světa v mžiku: kam se dnes vydáme?',
    'eda_i_napitki_short_descr' => 'Kusadla navozující sliny pro kreativitu',
    'cvetnye_short_descr' => 'Zmalujte si život jasnými barvami a odvážnými tahy štětcem',
    'prank_short_descr' => 'Sada kurzorů pro nejvtipnější vtípky',
    'startovyj_nabor_short_descr' => 'Nový pohled na známé věci: aktualizovaná série kurzorů',
    'fortnite_short_descr' => 'Sledujte streamery!',
    'dota_2_short_descr' => 'Udělejte si svůj virtuální svět reálným!',
    'minecraft_short_descr' => 'Postavy z vaší oblíbené hry jsou vždy nablízku',
    'christmas_descr' => 'Každý z nás nepochybně čeká na nejoblíbenější svátek - Vánoce. Všichni křesťané světa je tradičně slaví každý rok, 25. prosince. Čas, kdy se rodiny scházejí u jednoho stolu, sdílejí svou radost a lásku a vyměňují si dárky. Dlouho před Vánocemi lidé zdobí ulice jasnými girlandami a své domovy tradičními atributy. Je obtížné najít osobu, která by neměla ráda Vánoce - zábavný a tajemný svátek, protože ho doprovází mnoho tradic a rituálů, které nás vracejí ke kořenům celé naší rodiny. Na Štědrý den je doslova všechno naplněno jeho duchem, od malovaných perníčků po dojemné zpěvy. Elegantní vánoční stromeček a dárky pod ním, radost známá každému z nás z dětství. Chceme se připojit k tomuto kouzelnému svátku a kdo ví, možná Santa připraví speciální dárek pro vás, pokud si ozdobíte kurzor naší vánoční kolekcí. Je zde vše, co k tomu potřebujete, kurzor Santa Clause, kurzor vánočního stromečku, kurzor perníčku, kurzor Sněhuláka a dokonce i kurzor dárkové tašky. Veselé Vánoce!',
    'nhl_teams_descr' => 'National Hockey League byla založena v roce 1917 - je to profesionální sportovní organizace, která sdružuje hokejové kluby z USA a Kanady. A to je jedna z prvních profesionálních hokejových lig na světě. NHL je jednou z předních sportovních lig Severní Ameriky, spolu s NFL, NBA, Major League Baseball a MLS. Každý rok 31 týmů z 30 měst v USA a Kanadě bojuje o hlavní trofej - Stanley Cup, a tým, který nasbírá nejvíce bodů v základní části, je oceněn Prezidentským pohárem. Je čas uctít tuto skvělou hru vytvořením sbírky kurzorů NHL. Pokud máte také rádi hokej, fanděte svému oblíbenému klubu nebo se tohoto sportu sami účastněte, stačí změnit kurzor a nerozcházet se se svým oblíbeným týmem, včetně kurzoru Boston Bruins, kurzoru St. Louis Blues, kurzoru Columbus Blue Jackets, kurzoru Tampa Bay Lightning, kurzoru Dallas Stars a dalších klubů hodných upřímné úcty.',
    'neon_descr' => 'Vytvořili jsme unikátní kolekci neonových kurzorů, abychom přidali rozmanitost každodennímu surfování po internetu a vnesli trochu jasu do fascinujících neonových světel. Nechť jejich syté barvy vytvoří hřejivou atmosféru města v noci a inspirují k tvorbě něčeho nového. V moderním světě světla metropole vždy ohlašují příchod noci, provází nás na každé ulici a toto záření je naplněno energií. Nechť vás provází také zářivý kurzor zmrzliny, lahodný kurzor hot dogu, šťavnatý kurzor burgeru, třpytivý kurzor diamantu a další kurzory z nové neonové kolekce.',
    'adventure_time_descr' => '"Adventure Time" je kreslený seriál fantastického žánru, v němž se akce odehrává ve světě, který přežil apokalypsu. Toto území se nazývá Land Ooo, které až do nedávna bylo nukleární válkou. Ale to vše je již minulostí, avšak všichni přeživší lidé podlehli mutacím a svět se naplnil magií. Hlavními postavami animovaného seriálu jsou Finn, chlapec ve věku 14 let a jeho přítel pes jménem Jake. Chlapec a pes mají velmi rádi dobrodružství, neustále pomáhají všem, kteří se dostanou do potíží. Přátelé žijí na stromě a tráví spolu veškerý čas. Pokud se chcete ponořit do dobrodružného světa s dalšími obdivovateli, pak zakřičte "Mathematics". Zde je kurzor Finna Chlapce, kurzor Jakea, stejně jako kurzor Princezny Žvýkačky. Samozřejmě jsme nezapomněli na kurzor Bimo, kurzor Ledového Krále a další.',
    'nba_teams_descr' => 'Pokud je basketbal vaší oblíbenou hrou, jako je tomu u nás, pak je pro vás kolekce kurzorů věnovaných týmům NBA přesně to, co potřebujete. NBA je jednou z nejlepších sportovních asociací severoamerického kontinentu. Když jsme tuto kolekci vytvářeli, trápila nás volba - který tým si vybrat, protože v NBA jich je třicet. Ale existují týmy, které jsou legendami. A to Chicago Bulls, které v polovině 90. let stanovili rekord v počtu vítězství. To je Golden State Warriors, kteří před pár lety spojili nejlepší hráče ligy. Nebo například Lakers, Celtics jsou také šíleně skvělé týmy. Pokud se stejně jako my těšíte na zápasy svých oblíbených basketbalových týmů a chcete podpořit tým nebo hráče, stáhněte si naši kolekci kurzorů NBA.',
    'spongebob_descr' => 'Animovaný seriál "Spongebob v kalhotách" zná tolik lidí. Byl ohromným úspěchem poté, co se Nickelodeon v roce 1999 rozhodl vytvořit animovaný seriál na základě vzdělávacího komiksu Tide Zone a proměnil se ve velmi lukrativní franšízu. Tvůrcem seriálu je bývalý zaměstnanec oceánologické laboratoře, a proto jsou téměř všechny postavy v animovaném seriálu zábavní obyvatelé mořského dna, se svými vlastními charakteristikami a charismatem. Děj se točí kolem tajného receptu na Krabby Patty, který dokáže uvařit pouze hlavní postava - Sponge Bob. A ostatní obyvatelé moře se ho snaží získat, včetně hlavního anti-hrdiny Sheldona Planktona, kterému se to pokaždé nepodaří. V kolekci kurzorů SpongeBob jsme shromáždili kurzory všech pozoruhodných postav a událostí ze seriálu. Například kurzor pana Krabse s dolarem, kurzor Patrika Hvězdice, Sépiáka s jeho klarinetem, kurzor medúzy, kurzor Sponge Boba a mnoho dalších postav.',
    'phineas_and_ferb_descr' => 'Ve fiktivním americkém městě Denville neexistujícího Trishtatya žijí dva zajímaví chlapci. Každý den jejich prázdnin se promění v neuvěřitelná dobrodružství, protože dokážou postavit horskou dráhu velikosti celého města nebo skutečný portál do jiné planety. Se svými přáteli sdílejí úžasnou zábavu. Zároveň, zatímco se chlapci baví, zlý vědec Heinz Fufelschmertz staví další zlovolný stroj, který vytváří chaos, s názvem končícím na "-inator", pomocí kterého se chce pomstít za křivdy z dětství nebo uchvátit moc v Trishtatu, ale brání mu Perry - Ptakořit, tajný "Agent P", pracující pod rouškou mazlíčka chlapců. Popularita tohoto animovaného seriálu, a to jak mezi dětmi, tak i mezi dospělými, nás inspirovala k vytvoření kolekce kurzorů Phineas a Ferb, abyste si mohli změnit kurzor myši na postavy ze seriálu. Mezi nimi jsou kurzor Phineas Flynn, kurzor Dr. Heinz Fufelschmertz, kurzor Ferb Fletcher, kurzor Candace Gertrude Flynn a kurzor Perryho ptakopyska.',
    'fortnite_chapter_2_descr' => 'Druhá kapitola Fortnite přišla po velké události - The End, která stáhla vše, co hráči ve hře milovali, do černé díry. Fortnite Kapitola 2 má nyní novou mapu, která je na první pohled ještě více divoká než původní mapa, stejně jako mnoho změn v herní mechanice a samozřejmě spousta nového herního obsahu! Vozidla, emoce, plavání a mnoho dalšího - to vše v čerstvých, zajímavých obrazech, vše tak, jak to v této kultovní hře milujete a oceňujete. Ponořte se do nového světa - vyberte si místo přistání a prozkoumejte zcela nový ostrov s 13 lokacemi. Plavání, rybaření, motorové čluny - to je nová vodní hratelnost. Více zábavy a méně úsilí - vylepšete zcela novou kapitolu 2 a nezapomeňte změnit kurzor na nové skiny a zbraně. Už na vás čekají aktualizované skiny Turk kurzor, Riptide kurzor, Rippley kurzor, Remedy kurzor, Toxin kurzor, 8-Ball kurzor, Fusion kurzor a další!',
    'pokemon_descr' => 'Slovo "pokemon" znamená tvora s nadpřirozenými schopnostmi. Mají inteligenci a někteří z nich jsou dokonce schopni mluvit. V současné době existuje již 802 druhů Pokemonů. Ve vymyšleném vesmíru Pokémonů jsou lidé nazýváni trenéry Pokémonů, které trénují pro bitvy s Pokémony jiných trenérů. A čím zkušenější a silnější trenér, tím větší úctě se těší. Naštěstí je třeba poznamenat, že boje s Pokémony nikdy nekončí smrtí těchto jedinečných tvorů. Všichni Pokémoni mají různé schopnosti a liší se typem prvku a jeho odolnost vůči různým útokům na tom silně závisí, a některé bytosti mají schopnost dvou prvků najednou. Po vítězství v bitvě získá Pokémon cenné zkušenosti, které jsou nezbytné pro zvýšení úrovně a podle toho i jeho vlastnosti. Dnes je vesmír Pokémonů obrovskou mediální franšízou a rozhodli jsme se pro vás připravit kolekci kurzorů s některými populárními Pokémony. Mezi nimi je nejznámější kurzor Pikachu, stejně jako kurzor Rattata, kurzor Squirt, kurzor Bulbasaur a kurzor Charmander. Tento seznam bude aktualizován, protože jich je tolik a každý z nich je svým způsobem jedinečný.',
    'famous_people_descr' => 'Mezi mnoha slavnými lidmi si každý z nás najde vzor nebo prostě obdivuje génia, talent a vytrvalost těchto celebrit. Připravili jsme kolekci kurzorů celebrit, abychom vás inspirovali a připomněli vám velké úspěchy, které může každý z vás zvýšit. Ne všechny slavné osobnosti měly šťastný osud, ale učí nás hlavní věc, že se nikdy nemusíte stáhnout ze svého drahocenného cíle, navzdory obtížím a problémům. Koneckonců, to je hlavní princip dosahování úspěchu - jít za svým snem každý den a nakonec se stát nejlepšími ve svém oboru. Možná si dnes jen chcete změnit kurzor myši a zítra se vám celý život změní k lepšímu! Kolekce bude neustálev aktualizována o nové, důstojné představitele lidstva. Mezi nimi samozřejmě vědci, politici, sportovci, zástupci umění a mnozí další. Kurzor George Washingtona, kurzor Michaela Jordana, kurzor Stephena Kinga, kurzor Elvise Presleyho a kurzor Marilyn Monroe jsou jen začátek.',
    'the_elder_scrools_descr' => 'The Elder Scrolls je série počítačových RPG her, spojená společným, pečlivě navrženým vesmírem, který poskytuje hráči obrovskou svobodu volby, která mu umožňuje navštívit různé oblasti a města fantasy světa a prozkoumávat nová místa a mise podle vlastního uvážení. Práce na sérii začala již v roce 1992 a v průběhu let hra spojila obrovskou komunitu hráčů kolem sebe. Proto jsme na základě oblíbenosti vydali sbírku kurzorů The Elder Scrolls, abyste se mohli ponořit do jedinečné atmosféry hry. Věčná bitva rytířů a draků, na čí straně stojíte? Změňte kurzor na draka a připojte se k armádě ohnivých monster nebo bojujte ušlechtile na straně lidí výběrem kurzoru meče a obrazu vaší oblíbené postavy - rozhodnutí je na vás! Hlavní věc je, že s naší novou kolekcí jste připraveni na jakoukoli bitvu.',
    'halloween_descr' => 'Čekání na mystickou noc na Štědrý den Všech svatých. Historie Halloweenu sahá více než dva tisíce let. Možná je to nejzvláštnější svátek kombinující zábavu a strach, rodák keltské kultury. Tehdy lidé pálili ohně a oblékali si děsivé kostýmy, aby se ubránili duchům. Slovo "Halloween" bylo poprvé zmíněno v 16. století jako skotská zkratka anglické fráze All-Hallows-Even. Papež Řehoř III. vyhlásil 1. listopad svátkem Všech svatých a večer předtím byl znám jako předvečer Všech svatých a později Halloween. V tento den si lidé oblékají kostýmy vlkodlaků, duchů a dalších monster a chodí do sousedních domů a nabízejí k nákupu sladkosti. Tematické večírky, ohňostroje, krásné lucerny, dýně a kaskadérské kousky vytvářejí jedinečnou atmosféru. I my chceme tento strašlivý svátek oslavit doplňky kurzorů a halloweenovými postavami. V naší kolekci najdete: kurzor zombie, kurzor ducha, kurzor černé kočky, kurzor dýně a mnoho dalšího. Změna nálady je nyní stejně snadná jako změna kurzoru s naší novou halloweenovou kolekcí.',
    'nfl_teams_descr' => 'Co by mohlo být pro skutečného fanouška amerického fotbalu lepšího než kurzor myši ve formě symbolu týmu, pro který je fanouškem? V moderní National Football League hraje třicet dva týmů, rozdělených mezi National Football Conference (NFC) a American Football Conference (AFC). Každá z konferencí je rozdělena do čtyř divizí: Východ, Sever, Jih a Západ. Sezóna NFL se skládá z přátelských zápasů, základní části a série zápasů play-off. Finální zápas sezóny NFL se nazývá Super Bowl a je v podstatě nejoblíbenější sportovní událostí ve Spojených státech. Je to oblíbená hra pro miliony fanoušků, a proto jsme vytvořili kolekci kurzorů NFL, abyste se nerozcházeli se symboly svého oblíbeného týmu. Ať už se jedná o New England Patriots, New York Giants, Buffalo Bills nebo jiný tým, buďte vždy na stejné vlně jako vaši idoly, pomocí našich kurzorů ve tvaru loga týmu a helmy. Kolekce bude neustále aktualizována, aby si každý mohl změnit kurzor na obrázek svého oblíbeného týmu.',
    'five_nights_at_freddy_descr' => 'Skutečně jedinečná hra Five Nights at Freddy\'s si rychle získala velkou popularitu, což není překvapivé, protože její jednoduchý a zároveň fascinující děj dokáže udržet hráče na obrazovkách celé hodiny. Kurzy Five Nights at Freddy\'s jsme navrhli na žádost fanoušků hry a byli jsme velmi rádi, že jsme mohli ztělesnit tak zajímavé a vtipné postavy. Ale na rozdíl od hry vám s našimi kurzy nic nehrozí, takže si klidně vyberte své oblíbené animatroniky, ať už to bude medvěd Freddy nebo králík Bonnie nebo jiné. Hlavní je, že teď hra ožívá ve vašem prohlížeči a dává čerstvé emoce. Zaručujeme, že v našich kurzorech nejsou žádní duchové, ale dokonale zprostředkovávají ducha hry, která inspiruje strach díky složitosti designu a dějovým prvkům. Ale co když uděláte velikost kurzoru velmi velkou? Udržíte klid a nebudete se bát?',
    'komiksy_descr' => 'Zdálo by se, že kurzor myši je maličkost, ale často jsou to právě takové detaily, které dokáží zlepšit náladu, probudit v šedé ráno nebo prostě dát jasné emoce. Kolekce komiksových kurzorů navržená speciálně pro všechny milovníky superhrdinů. Zde najdete naprosto celý Marvel Universe a DC Comics - od Iron Mana po Thanose, Spider-Mana a Hulka. Styl kurzoru může být buď ve formě superhrdiny, nebo ve formě jeho postavy. Kurzorp není jen funkční prvek; je důležitý v profesionálním smyslu. Například, pokud nahráváte video z obrazovky, bude lepší vidět jasný, originální obrázek, a vypadá mnohem zajímavěji. A samozřejmě - kdo by nechtěl používat rukavici nekonečna ve skutečném životě? Změna kurzoru myši je jednoduchá - stačí si stáhnout rozšíření do prohlížeče a přidat kurzor, který se vám líbí, do nastavení. Můžete si vybrat kurzor podle své nálady alespoň každý den. Dost šedých dnů - staňte se superhrdinou právě teď!',
    'igry_descr' => 'Počítačové hry se již dávno staly nedílnou součástí našich životů. S jejich pomocí se můžete ponořit do nového světa, účastnit se dobrodružství a stát se úplně jiným člověkem. Každý má svou oblíbenou hračku, jejíž postavy se již staly téměř rodinou. Sada kurzorů založená na známých počítačových hrách je příležitostí, jak zředit nudný všední život a přidat trochu kreativity, jasu a zábavy do pracovního postupu. Sada obsahuje jak obrázky herních hrdinů samotných, tak pomocné postavy, zbraně a herní ikony. Vyberte si, co se hodí k vaší náladě - herní kurzory osloví nejen hráče, ale i každého, kdo je prostě unavený šedým všedním životem. Stačí si stáhnout sadu, změnit kurzor myši - a jít, plnit úkolové úkoly, ničit nepřátele a dosahovat svých cílů.',
    'multfilmy_descr' => 'V každém dospělém je stále dítě, které miluje karikatury, a stále sní o tom, že se stane jedním z hrdinů. Pomůžeme vám splnit vaše sny - použijte novou kolekci kurzorů založených na nejslavnějších a nejoblíbenějších karikaturách. Tom a Jerry, Buzz Rakeťák a Shrek, Gravity Falls a dokonce i Pokémoni - můžete se stát čímkoli, co chcete, každý den. Vyberte si kurzor myši podle své nálady. Kým jste dnes? Bezstarostný a veselý mimóň, který snadno řeší jakékoli problémy, nebo silný a odvážný Rafael, jehož cílem je nejen dosáhnout skvělých činů, ale také jíst pizzu? Možná jste všemocný džin, který má pod svou kontrolou celou kancelář? V kolekci jsou hrdinové pro každého - od princezen po draky - zbývá jen rozhodnout, kdo odráží dnešní náladu. Cursor Style není jen jasný obrázek. Je to odraz individuality, sebevyjádření a jednoduše - zábava, radost a pozitivní nálada po celý den. Je nudné pracovat nebo je příliš líný se učit? Stalo se to smutné a nejsem šťastný? Změňte kurzor a svět se rozzáří novými barvami.',
    'kino_i_serialy_descr' => 'Filmy - jsou magie, mystika a jen skvělý způsob, jak relaxovat, pobavit se a získat živé emoce. Zároveň si po zhlédnutí stále pamatujeme oblíbené hrdiny, které bychom opravdu chtěli potkat ve skutečnosti. Nyní je to možné - stačí si stáhnout novou kolekci kurzorů založenou na slavných filmech a televizních pořadech. Jasné, cool kurzory budou skvělým doplňkem na plochu, promění nudný šedý všední život ve svátek a banální úkoly - ve vzrušující dobrodružství. Změňte kurzor hrdiny každý den - podle nálady, úkolů nebo náhodně. Kým budete dnes? Poctivým a spravedlivým Johnem Snowem nebo odvážným, neúprosným Johnem Wickem? Možná máte před sebou obtížnou misi a pouze Frodo ji může dokončit? Možná jste dnes jen mimozemšťan, který se nechce s ostatními stýkat? Vyberte si vhodný kurzor - zvedněte si náladu a zároveň ukažte ostatním, co si myslíte a jak plánujete strávit den. Zkuste to - je to nejen zábavné, ale také návykové - rozhodně se nebudete chtít vrátit k obvyklé šipce.',
    'anime_descr' => 'Anime je jedinečný styl animace, který si i přes svou výraznou etnickou příslušnost oblíbily miliony lidí po celém světě. Je nepravděpodobné, že by existoval alespoň jeden člověk, který nesledoval kreslené filmy v tomto stylu. Vytvořili jsme nejúžasnější anime stylové kurzory, které si zamilují všichni fanoušci tohoto stylu. Standardní kurzory jsou nudné a otřepané. Ukažte svou osobnost - použijte kolekci anime kurzorů se svými oblíbenými postavami. Vyberte si kurzor temného meče, pokud sníte o dobrodružství a statečných bitvách. Roztomilý tlustý muž Totoro vás rozveselí i v ten nejsmutnější den a Naruto vás bude motivovat k dobrodružstvím a ukáže všem kolem vás, že jste mega cool. Jasné kurzory rozzáří pracovní den nebo učiní proces učení zajímavějším a příjemnějším. Neomezujte se - používejte své oblíbené motivy i v tak malých prvcích, jako je kurzor myši. Měňte kurzory každý den, přizpůsobte je své náladě a ukažte svou osobnost - s anime stylovými kurzory je to tak jednoduché.',
    'futbol_descr' => 'Fotbal je speciální sport, který zahrnuje prvky wrestlingu, atletiky, přesnosti. Obecně je velkolepý, nemilosrdný a sbírá miliony fanoušků po celém světě. Máte rádi fotbal nebo prostě milujete sport? Pak si stáhněte sadu kurzorů ve stylu světoznámé hry a prokažte titul věrného fanouška. Kolekce obsahuje 24 možností pro design kurzorů – ve formě nejoblíbenějších týmů, které si zaslouží své tituly jako zoufalá a vytrvalá hra. Kurzor je vyroben ve dvou verzích - ve formě standardního trojúhelníku, zdobeného v barvách týmu, nebo ve formě odpovídající helmy pro hru. Standardní kurzor prohlížeče je nudný a nehodný opravdového sportovního fanouška. Staňte se originálními a jedinečnými s naší kolekcí. Stáhněte si obrázky a vyberte barvy svého oblíbeného týmu nebo vlastní kurzory, pokud prostě milujete sport a fandíte všem. Následovat své koníčky je tak jednoduché - nemusíte chodit do práce se šálou nebo čepicí svého oblíbeného týmu, je rychlé a snadné změnit kurzor na jasný, stylový obrázek.',
    'avtomobili_descr' => 'Máte rádi auta a rádi se díváte na modely různých výrobců? Nebo už dlouho sníte o určité značce, ale stále nemáte možnost si ji pořídit? Speciálně pro vás jsme vytvořili jasnou sadu kurzorů "Supercars". Zde najdete klasický Ford a stylový Bentley, jasné Lamborghini a unikátní Ferrari. Chcete se stát majitelem originálního vozu? Je to jednoduché - stáhněte si naši sbírku kurzorů do svého zařízení a změňte obraz auta alespoň každý den. Kurzorů jsou navrženy ve dvou verzích - jako plnohodnotné auto nebo jako jeho znak. Vyberte si, co se vám nejvíce líbí nebo jak preferujete pracovat. Takové obrázky budou vypadat skvěle jako herní kurzory nebo jednoduše jako neobvyklý prvek plochy. Být jasným je jednoduché - není k tomu třeba dělat nepředstavitelné věci nebo měnit svůj vzhled. Stačí přestat používat všední předměty a vybrat si to, co se vám opravdu líbí. Sbírka kurzorů "Auta" je volbou pro ty, kteří se nebojí prokázat.',
    'memy_descr' => 'Memy jsou již dlouho známou součástí našich životů. A kdo z nás nemá rád tyto obsáhlé, zajímavé a originální obrázky, které dělají den lepším? Mnoho hrdinů memů se stalo nejen populárními - získali status oblíbených, a fráze a výrazy jsou již dlouho součástí hovorového jazyka jako zavedené obraty. Představujeme kolekci nejlepších kurzorů založených na nejoblíbenějších meme. S jejich pomocí můžete nejen ukázat svou osobnost, ale také vyjádřit svou náladu. Jste všichni unavení a otrávení ze všeho? Zvolte naštvanou kočku, která svým vzhledem vyjadřuje rozhořčení a nepřátelství ke všemu kolem. Nebo dnes záříte sarkasmem a nevadí vám se smát? Pak bude Drake Bling vynikajícím doprovodem - rozveselí vás a učiní jakýkoli úkol originálním a zajímavým. Nainstalujte rozšíření, stáhněte si naši kolekci - a vyberte si styl kurzoru pro každý den. Není těžké být jasný a originální - změňte standardní design ikony na jednoho z hrdinů memů a získejte energetickou podporu na celý den.',
    'emodji_descr' => 'Emoji - jasné, skvělé ikony, bez kterých už nemůžeme běžně komunikovat. S jejich pomocí nemusíte popisovat svou náladu slovy - stačí vybrat požadovanou ikonu a protějšek vám rozumí bez dalšího. V naší nové sadě kurzorů jsme ztělesnili myšlenku emoji - tak se zrodili vtipní a neobvyklí Cursoji, kteří zbarví svět a učiní život zajímavějším. S pomocí kurzorů můžete nejen pracovat a provádět známé úkoly, ale také ukázat svým kolegům, přátelům a prostě ostatním svou náladu. Ospalý kurzor je ideální na pondělní ráno a plačící kurzor vyjádří postoj k dalším povinnostem. Skvělý kurzor s brýlemi je nejlepší volba před svátky a kurzor s dolary v očích je dobrý důvod, jak šéfovi naznačit zvýšení platu. Používat Cursoji je zábavné a zajímavé - ať už jde o práci, studium nebo prezentaci. V posledním případě se to dokonce doporučuje, pokud mají kolegové smysl pro humor nebo je prostě potřeba uvolnit situaci. Obecně platí, že pro jakýkoli úkol - stačí si vybrat ten správný kurzor!',
    'pitomcy_descr' => 'Máte rádi zvířata? Jistě - jsou tak roztomilí, zábavní a velmi vtipní. Proč nestrávit celý den ve společnosti nejlepších přátel člověka? Stáhněte si kolekci kurzorů Zvířata pro sebe a vyberte si přítele pro každý den. Ikona kurzoru může být roztomilá, jako dobromyslná alpaka, nebo stylová, jako růžový plameňák. Nebo budete možná celý den zaneprázdněni a vyberete si jednorožce čtoucího noviny, nebo se jednoduše s nikým nechcete bavit, jako zlá černá kočka? Pro jakoukoli náladu máme odpovídající zvíře. Veselý mops vás rozveselí i v ten nejnudnější a nejšedivější den a růžový kurzor ve tvaru jednorožce všem ukáže, že nejste zbaveni smyslu pro krásu, i když jste brutální vousatý muž. Co když nemám náladu a nechce se mi dělat rutinní úkoly? Recept je jednoduchý - stáhněte si kolekci Zvířata, změňte kurzor myši - a voila, slunce opět svítí, počasí je pěkné a nálada je na nejvyšší úrovni. Není divu, že se říká, že zvířata pomáhají bojovat s depresí a smutkem!',
    'stil_i_krasota_descr' => 'V nové kolekci kurzorů jsme shromáždili širokou škálu témat, která v nás vyvolávají příjemné emoce a pozvedávají náladu. Tato sada kurzorů se nazývá „Styl a krása“, protože se jedná o vaše oblíbené věci, které určují náš každodenní život, přinášejí radost a motivují nás k důležitým věcem, probouzejí touhu po zlepšení. Jste nadšeni vesmírem a sníte o cestě na jiné planety? Vyberte si kurzor NASA nebo talíř mimozemšťanů – přibližte se svému snu. Pokud si nedokážete představit život bez hudby nebo jste zatvrzelý rocker, pak je pro vás kurzor ve stylu elektrické kytary. Štětec, pravítko a kompas kurzoru byly speciálně vyvinuty pro inženýry – takové obrázky pomohou proměnit nudné výpočty a kresby v originální řešení. Kouzelná hůlka a tenisky, skateboard a rtěnka, slunce a chemické kužely – vyberte si to, co vyhovuje vašemu životnímu stylu, vašim touhám a aspiracím – a běžné úkoly budou zajímavější a pracovní dny se zbarví do nových, jasných barev.',
    'prazdniki_descr' => 'Máte rádi svátky? Ale kdo je nemá rád - přátelé, dárky, zase ten víkend. Aby bylo čekání na svátky příjemnější, kratší a teplejší, můžete si nejen počítat dny na kalendáři, ale také nastavit odpovídající ikonu jako kurzor myši. Začněme Novým rokem - vybereme si vánoční stromeček, dárek nebo Santa Clause, aby byl svátek jasný a veselý. Možná bude perníček blíž - legrační, roztomilý a vždy veselý? S ním rozhodně nebude čas na smutek a nudu. Pokračujeme v oslavách s kupidy a radostnými srdíčky a není daleko k velikonočnímu zajíčkovi. Někde mezi svátky budou narozeniny, na které bude ještě příjemnější čekat s balónky místo standardní šipky kurzoru. A na Halloween můžete překvapit kolegy a lidi kolem sebe neobvyklým kurzorem myši ve tvaru zlověstné dýně nebo ducha. Sada kurzorů pro svátky je příležitostí, jak si zpříjemnit očekávání, naladit se předem na nadcházející zábavu a udržet si vynikající náladu nejen v předvečer oslavy, ale po celý rok.',
    'flagi_descr' => 'Vlajka je jedinečný symbol, který je široce používán ve všech sociálních sítích. Pomysleli jsme si, proč neudělat kurzor vlajkou? Koneckonců je opravdu jasný a neobvyklý. Nyní můžete trávit každý den ve společnosti nové země a práce nebude tak monotónní a nudná. Kurzory myši lze nyní proměnit v národní vlajku Číny nebo USA, Japonska nebo Kanady a v dalších 38 variantách vlajek a můžete si vybrat buď standardní tvar šipky v neobvyklé barvě, nebo kurzor ve tvaru samotné vlajky. Tato sada osloví všechny milovníky cestování. S ní můžete plánovat nové cesty a snít o dlouhých cestách. Plánujete dovolenou? Ukažte všem, do které země chcete jet. Možná jste se rozhodli naučit se nový cizí jazyk? Pak vás tento kurzor rozhodně podpoří a motivuje vás k pečlivému studiu. Nebo, stejně jako Sheldon, prostě milujete vlajky? Ve všech případech bude kolekce kurzorů Flags skvělým doplňkem vašeho počítače a přesune vás k novým objevům.',
    'vokrug_sveta_descr' => 'Všichni rádi cestují. Jak úžasné je navštívit nové země a města, vidět památky a skvěle se bavit v nové kultuře. Je škoda, že nemůžeme cestovat tak často, ale pokusili jsme se to napravit. Sada kurzorů „Kolem světa“ je sbírka nejvýraznějších obrázků, symbolů různých zemí, s jejichž pomocí se i při sezení doma můžete cítit jako skutečný cestovatel. V naší sadě najdete Japonsko a Austrálii, Itálii a Kanadu, USA a Mexiko - nejzajímavější, originální a malebné země na světě. Obrázek kurzoru se může stát standardní šipkou, v barvách vlajky země, nebo se stát jednou z hlavních atrakcí státu. Můžete například otevírat dokumenty se šikmou věží v Pise a vytvářet prezentace pomocí Sochy svobody. Zaručujeme - úspěch bude zajištěn. No, nebo pokud ne úspěch, pak úsměvy kolegů a uznání originality - to určitě. Ano, a naznačit vedení, že je čas jít na dovolenou, se také vyplatí - stačí nastavit kufr nebo letadlo jako kurzor - a s největší pravděpodobností budete létat velmi brzy.',
    'eda_i_napitki_descr' => 'Sada kurzorů ve formě produktů je neuvěřitelná sbírka jasných, chutných a lákavých obrázků, které se budou určitě líbit každému a budou skvělým doplňkem prohlížeče. Kliknuli jste někdy na brokolici nebo hranolky? Máte takovou příležitost - stačí si stáhnout novou sadu kurzorů a nastavit je místo nudné bílé šipky. Kurzor "Jídlo" je vytvořen jak ve formě standardního trojúhelníkového ukazatele, tak i ve formě produktů. Zde najdete zeleninu a ovoce, vaše oblíbené pokrmy, jako je pizza nebo hotdogy, kávu, lízátka a mnoho dalšího, co zvedne náladu v kterýkoli den. Milujete kávu, ale pít ji celý den není až tak dobré? Doplňte svou stravu virtuální kávou, která vás také povzbudí a probudí, stejně jako vám dá živé emoce. Strmý kurzor ve formě virtuálního koblihu nepoškodí postavu, zatímco dává živé emoce a povzbuzuje. Můžete používat své oblíbené kurzory nebo měnit obrázek každý den - velký výběr kurzorů pomůže obarvit každodenní život a přidat nové barvy k známým akcím.',
    'cvetnye_descr' => 'Kurzor je hlavním prvkem prohlížeče, se kterým trávíme celý pracovní den, studujeme, komunikujeme a relaxujeme. Standardní zobrazení kurzoru je nudné a dokonce poněkud deprimující, ale přesto je pro mnoho lidí tato forma pohodlná a její změna bude nepříjemná. Ale pro tuto situaci máme řešení - sadu kurzorů v jasných, veselých barvách, které dodají rozmanitost vašemu každodennímu životu a usnadní a urychlí řešení jakýchkoli problémů. Pokud přemýšlíte o tom, jak změnit barvu kurzoru, odpovídáme - stáhněte si naši kolekci a vyberte si jasná řešení pro každý den! Můžete si vybrat monochromatické tóny v různých barvách tak, aby vyhovovaly náladě nebo specifikům práce. Například při práci se standardními dokumenty vynikne fialový kurzor na pozadí a na tmavém pozadí se naopak bude lépe pracovat se žlutými kurzory. Pokud chcete explozi barev, jasu a maximální originality - vyberte si duhový kurzor, který obsahuje všechny barvy spektra - s touto ikonou bude nálada po celý den rozhodně v pořádku.',
    'prank_descr' => 'Vtipy v práci nejsou vždy vítány, protože často narušují pracovní postup. Ale s novou sadou kurzorů „Žerty“ si můžete laskavě zahrát s kolegy nebo přáteli, aniž byste poškodili svou práci nebo studium. Vyvinuli jsme speciální kolekci, která pobaví každého a dá důvod k trochu relaxace uprostřed rušného procesu práce nebo plnění dalšího úkolu. Chcete-li změnit kurzor myši, stačí stáhnout sadu do zařízení a vybrat si požadovaný design v parametrech. Můžete si například pořídit kurzor standardního tvaru, ale v obráceném stavu nebo šipku zakřivenou vlnou. Tato forma v žádném případě nebrání procesu práce, ale zároveň přináší skvělou náladu a navodí pozitivní náladu. Měňte nastavení zobrazení kurzoru podle své nálady nebo každý den - a jakýkoli úkol se stane zajímavějším a příjemnějším a každodenní život přestane vyvolávat negativní emoce. Navíc lze takové kurzory používat i pro vážné projekty - mají neutrální barvy a nevyniknou z plochy.',
    'startovyj_nabor_descr' => 'Kurzory ze startovací kolekce jsou směsí standardních tvarů a velikostí s jasným, neobvyklým vzhledem. To je vynikající volba pro ty, kteří preferují obvyklé tvary, ale chtějí vnést do každodenního života rozmanitost, originalitu a jas. Kolekce má kurzor ruky a známou šipku v různých variantách - od loga Google Chrome po emotikony, můžete se zde dokonce setkat s dávno zapomenutým drakem s kaktusy a nostalgií. Dokazujeme, že standardní kurzor může být také zajímavý a atraktivní. Různé barvy, tvary, textury a zajímavý design vám pomohou vybrat kurzor podle vašeho vkusu nebo ho měnit každý den v závislosti na náladě nebo prováděných úkolech. Změna kurzorů prohlížeče je velmi jednoduchá - stačí nainstalovat rozšíření a stáhnout kolekci do svého zařízení. Směšné, zajímavé kurzory nejen zbarví pracovní dny, ale také, například, pomohou učinit jakoukoli prezentaci zajímavější, a pomocí obzvláště jasných kurzorů také upoutat pozornost na jednotlivé prvky zprávy.',
    'fortnite_descr' => 'Fortnite si podmanil miliony lidí po celém světě. Vzrušující bitvy, strategie a taktika, dobrodružství - pohltilo absolutně všechno, co hráči tak milují. Nemohli jsme zůstat stranou a vyvinuli jsme sadu kurzorů ve stylu hry, která osloví nejen vášnivé hráče, ale i ty, kteří o Fortnitu slyšeli poprvé. Ikona kurzoru Fortnite je obraz hrdiny nebo jeho zbraně, propracovaný do nejmenšího detailu. Zde najdete obrázky lišek a ryb, masky inferna a černých rytířů, nastavte si šíp nebo kosu s hroty jako šipku. Jsme si jisti, že nikdo nezůstane lhostejný! Být strašidelný nebo tajemný, originální nebo humorný - je to na vás. Vyberte si svůj styl a řiďte se jím nebo si nastavte vlastní kurzory v nastavení a měňte svou roli každý den. Nyní bude mnohem zajímavější a příjemnější vykonávat i únavnou a monotónní práci - čas uteče rychle ve společnosti živých obrázků a oblíbených postav. Nebo si možná uspořádáte soutěže s kolegy, který hrdina bude silnější? Volba je na vás!',
    'dota_2_descr' => 'DotA2 teď není jen jednoduchá hra, je to skutečný paralelní svět. Ve virtuální realitě v DotA2 můžete dělat všechno - žít, bojovat, rozvíjet se, cestovat, najít si přátele. Obecně platí, že všechno je jako v životě, jen občas zajímavější. Dota 2 kurzory jsou pokračováním strategie, která vám umožní získat živé emoce a vyjádřit se ve skutečném světě. Nová sada kurzorů obsahuje nejvýraznější postavy ve hře, stejně jako originální předměty, které nelze s ničím zaměnit. Vyberte si kurzor, který vám bude bližší - a vydejte se na dobrodružství, aniž byste opustili své pracoviště. Jak nudné je někdy být v práci nebo plnit vzdělávací úkoly, ale s herními kurzory se s tímto problémem již nesetkáte. Trochu fantazie, jasný kurzor - a voilà, jakákoli činnost bude neobvyklým dobrodružstvím, se kterým si poradit nebude obtížné a zajímavé. Není třeba se omezovat. Máte rádi Dota? Pak si určitě stáhněte naši kolekci, vyberte si jeden nebo několik náhodných kurzorů najednou - a každý nový den se stane jasnějším, zajímavějším a sytějším.',
    'minecraft_descr' => 'Ukazatele myši ve formě standardních šipek a prstů se už dávno všem zunovali. Pokud jste fanouškem neobvyklého a originálního, pak je čas změnit ukazatel myši a dát mu zajímavější design. Vyvinuli jsme kolekci kurzorů ve stylu světoznámé hry Minecraft, kde najdete ty nejvýraznější postavy. Vlk a liška, Alex a Creeper, diamantový meč a ryba - můžete si vybrat ten, který se vám nejvíce líbí, nebo si každý den nainstalovat nového hrdinu. Toto jsou skutečné kurzory pro hráče a naprosto každému se budou líbit - koneckonců, kdo z nás nehrál Minecraft? Jsme si jisti, že tací prostě neexistují. Pryč se všedním životem - je čas se ponořit do dobrodružství, což lze provést i bez opuštění domova nebo kancelářské židle. Bude zajímavější připravovat zprávu a snížit saldo zbraní - jakýkoli úkol se stane příjemnějším a nedovolí vám se na místě nudit. Stáhněte si novou sbírku kurzorů Minecraft - nastavte je a i v ten nejšedivější a nejnudnější den bude vaše nálada vždy na nejlepší úrovni. A kolegové vám budou vaše výsledky závidět - s pomocí statečných hrdinů Minecraftu je prostě nemožné svou práci nedělat.',
    'web_media_descr' => 'V moderní realitě používá internet téměř každý. Počínaje batolaty a konče důchodci. Někdo surfuje pomocí prohlížeče, další sleduje videa na YouTube a někdo potřebuje síť, aby komunikoval s blízkými. Žádný z těchto uživatelů si neumí představit den bez World Wide Web.
Starší lidé často sedí na sociální síti jako Facebook nebo VK. Také často komunikují se svými dětmi a vnoučaty na Skype . To je zvláště výhodné, pokud děti a rodiče žijí v různých městech nebo dokonce zemích.
Mladí lidé dávají přednost komunikaci prostřednictvím Viber nebo Telegram, nahrávají fotografie na Instagram, smějí se FB memům. YouTube videa s reakcemi lidí získávají miliony zhlédnutí, stejně jako různé žerty nebo sociální experimenty. V Tik-Tok tančí, ukazují triky a vyjadřují se stovky tisíc lidí.
Máte zájem nebo často používáte nějaký druh zdroje ze sféry webových médií? Chcete se zbavit nudné šipky myši ve vašem prohlížeči? Poté nainstalujte rozšíření a změňte výchozí kurzor na náš kreativní! Může to být kurzor YouTube, kurzor Viber, kurzor Google Chrome nebo jiné zdroje.',
    'astrology-signs-zodiac' => 'Znamení zvěrokruhu',
    'sports-cars_short_descr' => 'Výkonná a stylová auta stvořená pro rychlost a obratnost',
    'spider-man' => 'Spider-Man',
    'astrology-signs-zodiac_short_descr' => 'Sada 12 astrologických symbolů představujících osobnostní rysy, kosmické energie a životní vzorce.',
    'sports-cars' => 'Sportovní auta',
    'sports-cars_descr' => 'Sportovní auta jsou vysoce výkonná vozidla navržená pro rychlou akceleraci, ostré ovládání a vzrušující zážitek z jízdy. Od elegantních kupé po svižné roadstery, tato kategorie představuje některé z nejikoničtějších strojů postavených pro vzrušení z cesty nebo okruhu. Ideální pro nadšence, kteří milují rychlost, design a výkon. 🏎️🔥',
    'spider-man_short_descr' => 'Hrdinové z univerza Spider-Man',
    'starwars' => 'Star Wars',
    'spider-man_descr' => 'Kolekce postav a hrdinů z pavoučího světa Spider-Mana. Zahrnuje různé verze Spider-Mana, spojence a jedinečné styly z komiksů, her a animovaných seriálů. Každý design odráží obratnost, odvahu a vizuální identitu, která definuje svět Spider-Mana.',
    'astrology-signs-zodiac_descr' => 'Znamení zvěrokruhu ♈♉♊♋♌♍♎♏♐♑♒♓ je dvanáct symbolických dělení nebeského pásu používaných v astrologii. Každé znamení je spojeno se specifickými daty, živly (🌍 Země, 🔥 Oheň, 🌊 Voda, 💨 Vzduch), vládnoucími planetami a jedinečnými charakteristikami osobnosti. Astrologové používají znamení zvěrokruhu k interpretaci chování, předpovídání kompatibility a zkoumání životních cest. Ať už jste vášnivý Lev 🔥 nebo zamyšlený Ryba 🌊, vaše znamení nabízí vhled do vašeho vnitřního světa. Tato kategorie zahrnuje všech 12 znamení, jejich významy a vizuální reprezentace.',
    'starwars_descr' => 'Ponořte se do předaleké galaxie s touto kolekcí, která obsahuje legendární hrdiny, mocné Sithské lordy, droidy, rebely a mnoho dalšího. Od rytířů Jedi po stormtroopery, každá ikona přivádí ducha Star Wars k životu ve formě kurzoru. Ideální pro fanoušky každé trilogie. 🌌',
    'starwars_short_descr' => 'Postavy a symboly z vesmíru Star Wars',
    'glitter' => 'Třpytky',
    'glitter_short_descr' => 'Lesklé a třpytivé kurzory ve stylu třpytek ✨🌟',
    'roblox-2025' => 'Roblox 2025',
    'roblox-2025_short_descr' => 'Postavy z nejnovější Roblox vlny 🕹️🚀',
    'glitter_descr' => 'Okouzlující kolekce kurzorů inspirovaná třpytivými texturami a zářivým vizuálem. Ideální pro ty, kteří milují jiskřivou estetiku na své obrazovce. Tyto kurzory přinášají třpyt, eleganci a trochu magie ke každému kliknutí.',
    'roblox-2025_descr' => 'Zcela nová kolekce z roku 2025 s ikonickými a moderními postavami z Robloxu. Zahrnuje klasické nooby, hororové legendy a oblíbené avatary z populárních her. Navrženo v zábavném a barevném stylu, který je ideální pro děti a fanoušky Robloxu všech věkových kategorií.',
];
