<?php

return [
    'title' => 'Cursor Style - Zásady ochrany osobních údajů',
    'descr' => 'V „Cursor Style,“ dostupném na cursor.style nebo prostřednictvím rozšíření pro Chrome, je jednou z našich nejvyšších priorit soukromí našich návštěvníků. V této sekci si povíme o všech aspektech práce s rozšířením.',
    'text' => '<h2> Zásady ochrany osobních údajů </h2>
                <p> V aplikaci Cursor Style, dostupné na <a href="https://cursor.style"> cursor.style </a> nebo prostřednictvím rozšíření pro Chrome, je jednou z našich nejvyšších priorit soukromí našich návštěvníků. Tento dokument Zásad ochrany osobních údajů obsahuje typy informací, které jsou shromažďovány a zaznamenávány webem cursor.style, a jak je používáme. Máte-li další otázky nebo potřebujete více informací o našich Zásadách ochrany osobních údajů, neváhejte nás kontaktovat. </p>
                <p> Rozšíření „Cursor Style“ a webové stránky se řídí standardním postupem pro používání souborů protokolu. Tyto soubory registrují návštěvníky při návštěvě webových stránek nebo používání našeho rozšíření. Všechny hostingové společnosti to dělají a jsou součástí analytiky hostingových služeb. Informace shromážděné prostřednictvím souborů protokolu zahrnují adresy Internet Protocol (IP), typ prohlížeče, poskytovatele internetových služeb (ISP), razítko data a času, přechodové / výstupní stránky a případně počet kliknutí. Nejsou spojeny s žádnými osobně identifikovatelnými informacemi. Účelem těchto informací je analyzovat trendy, spravovat a rozvíjet stránky, sledovat pohyb uživatelů na stránkách a rozvíjet je a shromažďovat demografické informace. </p>
                <p> Stejně jako jakýkoli jiný web používá cursor.style soubory cookie. Tyto soubory cookie se používají k ukládání informací, včetně preferencí návštěvníka a stránek na webových stránkách, které návštěvník navštívil nebo navštívil. Tyto informace se používají k optimalizaci uživatelské zkušenosti přizpůsobením obsahu naší webové stránky na základě typu prohlížeče návštěvníka a / nebo dalších informací. Používáme také reklamy třetích stran na cursor.style na podporu projektu a podporu našeho webu. Někteří z těchto inzerentů mohou používat technologie, jako jsou soubory cookie a webové majáky, když inzerují na našem webu, což také odešle těmto inzerentům (například Google prostřednictvím programu Google AdSense) informace, včetně vaší IP adresy, vašeho poskytovatele internetu, prohlížeče, který jste použili k návštěvě našich stránkách, a v některých případech, pokud máte nainstalovaný Flash. To se obvykle používá pro účely geotargetingu (například zobrazování reklam na prodej zboží ve vašem městě) nebo pro zobrazování určitých reklam na základě určitých navštívených webových stránek (například zobrazování oznámení o nákupu těm, kteří často navštěvují nákupní stránky). </ P >
                <p> Soubory cookie můžete deaktivovat nebo selektivně zakázat naše nebo soubory cookie třetích stran v nastavení prohlížeče nebo správou nastavení v programech jako Kaspersky atd. To však může ovlivnit vaše interakce s naším webem i s dalšími weby. To může zahrnovat nemožnost přihlásit se do služeb nebo programů, jako je přihlášení do fór nebo účtů. </p>
<p> Google je jedním z poskytovatelů třetích stran na našem webu. Používá také soubory cookie, známé jako soubory cookie DART, k zobrazování reklam návštěvníkům našich stránek na základě jejich návštěv na cursor.style a dalších stránkách na internetu. Návštěvníci se však mohou odhlásit z používání souborů cookie DART návštěvou zásad ochrany osobních údajů reklamní a obsahové sítě Google na <a href="https://policies.google.com/technologies/ads"> následující adrese </a>. Někteří z inzerentů na našem webu mohou používat soubory cookie a webové majáky. Každý z našich reklamních partnerů má své vlastní zásady ochrany osobních údajů pro své zásady týkající se údajů o uživatelích. Více informací o jejich zásadách ochrany osobních údajů si můžete přečíst <a href="https://policies.google.com/technologies/ads"> zde </a>. </p>
                <p> Naše webové stránky používají službu Google Analytics, službu webové analýzy společnosti Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com („Google Analytics“ nebo „Google“). Google Analytics používá soubory cookie, které jsou uloženy ve vašem počítači, aby usnadnily analýzu vašeho používání webu. Informace generované těmito soubory cookie, jako je čas, místo a frekvence vašich návštěv na našem webu, včetně vaší IP adresy, jsou přeneseny do umístění Google v USA a tam uloženy. Společnost Google může tyto informace také předat třetím stranám, pokud to vyžaduje zákon nebo pokud tyto třetí strany zpracovávají tato data jménem společnosti Google. Společnost Google uvádí, že nikdy nespojí vaši IP adresu s dalšími údaji společnosti Google. Nastavení souborů cookie můžete zabránit změnou nastavení softwaru prohlížeče odpovídajícím způsobem, jak je uvedeno v těchto zásadách ochrany osobních údajů. Měli byste si však být vědomi toho, že tímto způsobem nebudete moci plně využívat všechny funkce našich webových stránek. </p>
                <p> Google Analytics také používá elektronické obrázky známé jako webové majáky (někdy nazývané jednopixelové soubory GIF) a jsou používány se soubory cookie ke kompilaci agregovaných statistik pro analýzu používání našeho webu.
Více informací o tom, jak nainstalovat doplněk prohlížeče, na který odkazujete výše, najdete <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> na odkazu </a>.
Tato stránka používá Google Tag Manager. Tato služba umožňuje spravovat značky webu prostřednictvím rozhraní. Google Tag Manager implementuje pouze značky. To znamená, že se nenastavují žádné soubory cookie a nezaznamenávají se žádné osobní údaje. Google Tag Manager spouští další značky, které mohou zase zaznamenávat data. Google Tag Manager však nemá k těmto údajům přístup. Pokud byly značky zakázány na úrovni domény nebo souboru cookie, uloží se všechny pro sledování značek, pokud se implementují pomocí Google Tag Manager. Více informací o Google Tag Manager se dozvíte na stránce <a href="http://www.google.com/tagmanager/use-policy.html"> odkaz </a>. </p>
<p> Můžete se seznámit s tímto seznamem a najít Zásady ochrany osobních údajů pro každého z reklamních partnerů „Cursor Style“. Reklamní servery nebo reklamní sítě třetích stran používají technologie, jako jsou soubory cookie, JavaScript nebo webové majáky, které se používají v jejich příslušných reklamách a odkazech, které se zobrazují v „Cursor Style“ a odesílají se přímo do prohlížeče uživatele. Automaticky získáte vaši IP adresu, když se to stane. Tyto technologie se používají k měření efektivity jejich reklamních kampaní a / nebo k personalizaci reklamního obsahu, který vidíte na navštívených webových stránkách. Upozorňujeme, že „Cursor Style“ nemá přístup ani kontrolu nad těmito soubory cookie, které používají inzerenti třetích stran. Zásady ochrany osobních údajů Cursor Style se nevztahují na ostatní inzerenty nebo webové stránky. Doporučujeme proto, abyste si přečetli příslušné zásady ochrany osobních údajů těchto reklamních serverů třetích stran, kde najdete další informace. Může obsahovat jejich metody a pokyny, jak se odhlásit z určitých možností. Odkazy na tyto Zásady ochrany osobních údajů třetích stran najdete výše nebo na webových stránkách těchto služeb třetích stran. </p>
                <p> Soubory cookie můžete zakázat v nastavení prohlížeče. Chcete-li se dozvědět více o správě souborů cookie v konkrétních webových prohlížečích, najdete jej na jejich příslušných webových stránkách prohlížeče. Další částí naší priority je přidat ochranu dětí při používání internetu. Doporučujeme rodičům a opatrovníkům, aby sledovali, se zúčastnili a / nebo sledovali a řídili své aktivity na internetu. „Cursor Style“ vědomě neshromažďuje osobní údaje od dětí mladších 13 let. Pokud si myslíte, že vaše dítě poskytlo takové informace na našem webu, důrazně doporučujeme, abyste nás neprodleně kontaktovali a my uděláme maximum pro rychlé odstranění těchto informací z našich záznamů. Tyto Zásady ochrany osobních údajů se vztahují pouze na naše online aktivity a platí pro návštěvníky našich webových stránek ve vztahu k informacím, které sdíleli a / nebo shromáždili v „Cursor Style“. Tyto zásady se nevztahují na žádné informace shromážděné offline nebo prostřednictvím jiných kanálů než tento web. </p>
                <p> Více o používání souborů cookie v naší Službě si můžete přečíst v našich <a href="/cookie-policy"> Zásadách používání souborů cookie </a>. </p> ',
];
