<?php

return [
    'title' => 'Сursor Style - Podmínky použití našeho produktu',
    'descr' => 'Podmínky použití jsou uzavřeny mezi vámi a „Cursor Style“ („Služba“, „my“ nebo „Služba“). Tato služba je nabízena a dostupná uživatelům ve věku 13 let a starším pouze pro osobní použití, nikoli pro komerční účely.',
    'text' => '<h2> Podmínky služby </h2>
<h3> PŘED POUŽÍVÁNÍM WEBOVÉ STRÁNKY A ROZŠÍŘENÍ SI PŘEČTĚTE TYTO PODMÍNKY. </h3>
<p> Tyto podmínky použití jsou uzavřeny mezi vámi a "Cursor Style" ("Služba", "my" nebo "Služba"). Následující podmínky spolu s jakýmikoli dokumenty, které výslovně zahrnují odkazem (společně tyto "Podmínky použití"), upravují váš přístup a používání webových stránek cursor.style a jejích rozšíření prohlížeče, včetně jakéhokoli obsahu, funkčnosti a služeb nabízených na nebo prostřednictvím naší služby (souhrnně "Služba"). </p>
<p> Používáním webové stránky nebo rozšíření souhlasíte s těmito Podmínkami použití. Pokud s těmito Podmínkami použití nebo našimi <a href="/privacy"> Zásadami ochrany osobních údajů </a> nesouhlasíte, neměli byste na webové stránky a rozšíření vstupovat ani je používat. </p>
<p> Tato služba je nabízena a dostupná pouze uživatelům ve věku 13 let a starším, pouze pro osobní použití, nikoli pro komerční použití. Používáním této Služby prohlašujete a zaručujete, že (I) je vám 13 let nebo více, (II) nemáte zakázáno používat webové stránky v souladu s platnými zákony a (III) používáte Službu pouze pro své osobní potřeby. Pokud tyto požadavky nesplňujete, neměli byste do Služby vstupovat ani ji používat. </p>
<p> Tyto Podmínky použití můžeme čas od času podle vlastního uvážení revidovat a aktualizovat. Všechny změny vstupují v platnost okamžitě po jejich zveřejnění. Vaše další používání Služby po zveřejnění revidovaných Podmínek použití znamená, že s těmito změnami souhlasíte. Očekává se, že tuto stránku budete často navštěvovat, abyste byli informováni o jakýchkoli změnách, protože pro vás jsou závazné. </p>
<p> Vyhrazujeme si právo stáhnout nebo změnit tuto webovou stránku a Rozšíření, jakékoli služby nebo materiály, které poskytujeme na Webových stránkách a v Rozšíření, podle našeho vlastního uvážení, bez upozornění. Nezaručujeme, že naše stránky, rozšíření nebo jakýkoli obsah na nich budou vždy dostupné nebo budou nepřerušené. Neodpovídáme za to, pokud z jakéhokoli důvodu nebude celá Služba nebo její část kdykoli nebo po jakékoli období nedostupná. Čas od času můžeme omezit přístup k určitým částem webové stránky nebo Rozšíření nebo celé Službě pro uživatele. </p>
<p> Jste odpovědní za přijetí všech nezbytných opatření k zajištění toho, abyste měli přístup ke Službě. Zajištění, aby si všechny osoby, které prostřednictvím vašeho připojení k internetu přistupují ke Službě, byly vědomy těchto Podmínek použití a dodržovaly je. Abyste měli přístup ke Službě nebo některým z jejích zdrojů, můžete být požádáni o poskytnutí určitých informací nebo jiných informací. Souhlasíte s tím, že veškeré informace, které nám poskytnete pomocí této Služby nebo jiným způsobem, včetně, ale nikoli výhradně, používání jakýchkoli interaktivních funkcí ve Službě, se řídí našimi <a href="/privacy"> Zásadami ochrany osobních údajů </a> a souhlasíte se všemi kroky, které podnikneme s ohledem na vaše informace. v souladu s našimi <a href="/privacy"> Zásadami ochrany osobních údajů </a>. </p>
<p> Při zadávání osobních údajů do Služby na veřejném nebo sdíleném počítači musíte být obzvláště opatrní, aby ostatní nemohli vaše osobní údaje zobrazit nebo zaznamenat. Webová stránka, rozšíření a veškerý její obsah, funkce a vlastnosti (včetně, ale nikoli výhradně, všech informací, rozšíření, textu, obrázků, obrázků a kurzorů, jakož i jejich designu, výběru a umístění) patří společnosti "Cursor Style", jejím poskytovatelům licence nebo jiným dodavatelům těchto materiálů jsou chráněny autorským právem, ochrannou známkou, patentem, obchodním tajemstvím a dalšími zákony o duševním vlastnictví nebo majetkovými právy. </p>
<p> Tyto Podmínky použití vám umožňují používat webové stránky pouze pro vaše osobní, nekomerční použití. Nesmíte reprodukovat, distribuovat, upravovat, vytvářet odvozená díla, znovu publikovat, stahovat, ukládat nebo přenášet žádné materiály na našich Webových stránkách, s výjimkou následujících případů: můžete je použít pro osobní potřeby, můžete vytisknout nebo stáhnout jednu kopii přiměřeného množství stránky webových stránek a Rozšíření nebo jejich obsahu pro osobní, nekomerční použití, a nikoli pro další reprodukci, publikaci nebo distribuci. </p>
<p> Nesmíte upravovat kopie jakýchkoli materiálů z této stránky nebo rozšíření a jejich obsahu. Odstraňte nebo upravte jakékoli upozornění na autorská práva, ochrannou známku nebo jiná vlastnická práva z kopií této stránky a rozšíření. Nesmíte mít přístup k žádné části webových stránek nebo rozšíření, ani je používat pro žádný komerční účel, jakož i žádné služby nebo materiály dostupné prostřednictvím webových stránek nebo Rozšíření. </p>
<p> Pokud chcete použít jakýkoli materiál na webových stránkách nebo rozšířeních, který není uveden v této sekci, odešlete žádost na stránce podpory obchodu Chrome Web Store. </p>
<p> Pokud vytisknete, kopírujete, upravujete, stahujete nebo jinak používáte nebo poskytujete jiné osobě přístup k jakékoli části webové stránky nebo Rozšíření v rozporu s Podmínkami použití, vaše právo na používání webové stránky a Rozšíření okamžitě zaniká a musíte, podle našeho uvážení, vrátit nebo zničit veškeré kopie materiálů, které máte. Jakékoli použití webové stránky rozšíření, které není výslovně povoleno těmito Podmínkami použití, je v rozporu s těmito Podmínkami použití a může porušovat autorská práva, ochranné známky a další zákony. </p>
<p> Název “Cursor Style”, logo “Cursor Style” a všechna související jména, loga, obrázky, kurzory a názvy služeb, návrhy a slogany jsou ochranné známky společnosti “Cursor Style” nebo jejích přidružených společností nebo poskytovatelů licence. Tyto značky nesmíte používat bez předchozího písemného souhlasu Služby. Všechny ostatní názvy, loga, názvy produktů a služeb, návrhy a slogany na této webové stránce a v rozšíření jsou ochranné známky příslušných vlastníků. Službu můžete používat pouze pro legitimní účely a v souladu s těmito Podmínkami použití. </p>
<h3> Souhlasíte s tím, že NEBUDETE používat Službu: </h3>
<ul>
<li> Jakýmkoli způsobem, který porušuje jakékoli platné federální, regionální, místní nebo mezinárodní zákony nebo předpisy (včetně, ale nikoli výhradně, jakýchkoli zákonů týkajících se vývozu dat nebo softwaru do Ruska a dalších zemí). </li>
<li> Za účelem zneužívání, újmy nebo pokusů o zneužívání nebo újmu nezletilým, vystavení nevhodnému obsahu, vyžadování informací, které je identifikují, nebo jiným způsobem. </li>
<li> Chcete-li posílat, vědomě přijímat, stahovat, používat nebo znovu používat jakékoli materiály, které nejsou v souladu s těmito Podmínkami použití. </li>
<li> Přijímat nebo kupovat odesílání jakýchkoli reklam nebo propagačních materiálů bez našeho předchozího písemného souhlasu, včetně jakýchkoli „nevyžádaných dopisů“, „řetězových dopisů“ nebo „spamu“ nebo jakýchkoli jiných podobných nabídek. </li>
<li> S cílem vydávat se za nebo pokusit se vydávat za zaměstnance “Cursor Style”, jiného uživatele nebo jakoukoli jinou osobu nebo organizaci (včetně, ale nikoli výhradně, použití e-mailových adres nebo aliasů spojených s některým z výše uvedených). </ li >
<li> Účast na jakýchkoli jiných činnostech, které omezují nebo brání používání Služby nebo používání kohokoli, nebo které, jak určíme, mohou poškodit Službu nebo uživatele Služby nebo je učinit zodpovědnými. </li> </ul>
<h3> Dále souhlasíte, ŽE NE: </h3>
<ul>
<li> Používejte Službu jakýmkoli způsobem, který může deaktivovat, přetížit, poškodit nebo znehodnotit chod webu, rozšířit nebo narušit používání Služby jakoukoli jinou stranou, včetně jejich schopnosti účastnit se akcí v reálném čase prostřednictvím Služby. </li>
<li> Používat jakékoli automatizační nástroje, procesy nebo prostředky pro přístup ke Službě pro jakýkoli účel, včetně monitorování nebo kopírování jakéhokoli materiálu ve Službě. </li>
<li> Používat jakýkoli ruční proces ke sledování nebo kopírování jakéhokoli materiálu ve Službě nebo pro jakékoli jiné neoprávněné účely bez našeho předchozího písemného souhlasu. </li>
<li> Používat jakékoli zařízení, software nebo postupy, které narušují normální provoz Služby. </li>
<li> Zavat jakékoli viry, trojské koně, červy, logické bomby nebo jiné materiály, které jsou škodlivé nebo technologicky škodlivé. </li>
<li> Pokusit se získat neoprávněný přístup, zasahovat, poškodit nebo narušit jakoukoli část Služby, server, na kterém je Služba uložena, nebo jakýkoli server, počítač nebo databázi připojenou ke Službě. </li>
<li> Zaútočit na Službu pomocí útoku odmítnutí služby nebo distribuovaného útoku odmítnutí služby. </li> </ul>
<p> Informace poskytnuté na Službě nebo prostřednictvím Služby slouží pouze pro obecné informační účely. Nezaručujeme přesnost, úplnost ani užitečnost těchto informací. Spoléháte se na tyto informace výhradně na vlastní riziko. Zříkáme se veškeré odpovědnosti a závazků vyplývajících z jakékoli závislosti na takových materiálech vámi, jakýmikoli dalšími návštěvníky Služby nebo kýmkoli, kdo může být informován o jakémkoli jejich obsahu. </p>
<p> Tato Služba obsahuje obsah poskytovaný třetími stranami, včetně materiálů poskytovaných jinými uživateli a poskytovateli licence třetích stran, syndikátory, agregátory a / nebo zpravodajskými službami. Všechna prohlášení a / nebo názory vyjádřené v těchto materiálech, jakož i všechny články a odpovědi na otázky a další obsah, s výjimkou obsahu poskytovaného Službou, jsou výhradně názory a odpovědnost osoby nebo organizace, která tyto materiály poskytuje. Tyto materiály nemusí nutně odrážet názory Služby. Nenese odpovědnost vůči vám ani žádné třetí straně za obsah nebo přesnost jakýchkoli materiálů poskytnutých třetími stranami. </p>
<p> Obsah Služby můžeme čas od času aktualizovat, ale její obsah nemusí být nutně úplný nebo aktuální. Jakýkoli materiál ve Službě může být kdykoli zastaralý a nejsme povinni takový materiál aktualizovat. Můžeme aktualizovat, upravovat, upravovat informace a obsah na webových stránkách a v Rozšíření, provádět jakékoli změny a aktualizace podle našeho vlastního rozhodnutí. </p>
<p> Všechny informace, které shromažďujeme v této Službě, podléhají našim Zásadám ochrany osobních údajů. Používáním Služby souhlasíte se všemi akcemi, které podnikneme v souvislosti s vašimi informacemi v souladu se <a href="/privacy"> Zásadami ochrany osobních údajů </a>. </p>
<p> Dodatečné podmínky se mohou vztahovat také na určité části, služby nebo funkce Služby. Všechny tyto další podmínky jsou tímto začleněny formou odkazu do těchto Podmínek použití.
Můžete odkazovat na naše webové stránky nebo rozšíření, pokud to uděláte poctivým a zákonným způsobem a nepoškodíte naši pověst ani ji nepoužíváte, ale neměli byste nastavit odkaz tak, aby nabízel jakoukoli formu asociace, podpory nebo schválení z naší strany bez našeho písemného souhlasu. </p>
<p> Služba obsahuje odkazy na jiné stránky a zdroje poskytované třetími stranami, tyto odkazy jsou poskytovány pouze pro vaše pohodlí. To zahrnuje odkazy obsažené v reklamách, včetně bannerů a sponzorovaných odkazů. Nekontrolujeme obsah těchto stránek ani zdrojů a nejsme za ně odpovědní, ani za jakoukoli ztrátu nebo škodu, která může vyplynout z jejich použití. Pokud se rozhodnete přistupovat na jakékoli webové stránky třetích stran spojené s touto Službou, činíte tak na vlastní riziko a v souladu s podmínkami použití takových webových stránek. Vyhrazujeme si právo zrušit povolení k odkazu bez předchozího upozornění. </p>
<p> Chápete, že nemůžeme a nezaručujeme, že soubory dostupné ke stažení přes internet nebo na webových stránkách nebudou obsahovat viry nebo jiný škodlivý kód. Jste odpovědní za implementaci postupů a kontrolních bodů dostatečných k uspokojení vašich zvláštních požadavků na antivirovou ochranu a přesnost vstupu a výstupu dat, jakož i za udržování prostředků externích k našim stránkám pro obnovu ztracených dat. NEJSME ODPOVĚDNÍ ZA ŽÁDNÉ ŠKODY NEBO ZRANĚNÍ ZPŮSOBENÉ distribuované odmítnutí SLUŽBY, viry nebo other technology-malware ZÍSKANÉ PROSTŘEDNICTVÝM SLUŽBY, OR STAŽENÍ JAKÉHOKOLI MATERIÁLU ZVEŘEJNĚNÉHO NA TOTO, OR ŽÁDNÝCH WEBŮCH, SPOJENÝCH MŮŽE NAKAZIT NEBO POŠKODIT VAŠE POČÍTAČOVÉ ZAŘÍZENÍ, POČÍTAČOVÝ SOFTWARE, DATA. </p>
<p> POUŽÍVÁTE SLUŽBU, JEJÍ OBSAH A JAKÉKOLI SLUŽBY NEBO POLOŽKY ZÍSKANÉ PROSTŘEDNICTVÍM SLUŽEB NA VLASTNÍ RIZIKO. SLUŽBA, JEJÍ OBSAHY A JAKÉKOLI SLUŽBY NEBO POLOŽKY ZÍSKANÉ PROSTŘEDNICTVÍM WEBOVÝCH STRÁNEK A ROZŠÍŘENÍ JSOU POSKYTOVÁNY VE STAVU “JAKÉ JSOU” A “JAK JSOU DOSTUPNÉ”, BEZ JAKÉKOLI ZÁRUKY. JAKÁKOLI OSOBA SPOJENÁ SE SLUŽBOU NEPOSKYTUJE ŽÁDNOU ZÁRUKU ANI PROHLÁŠENÍ S OHLEDEM NA ÚPLNOST, BEZPEČNOST, SPOLEHLIVOST, KVALITU, PŘESNOST NEBO DOSTUPNOST SLUŽBY. BEZ OMEZENÍ VÝŠE, ŽÁDNÝ „Cursor Style“ ANI SOUVISEJÍCÍ ZÁSTUPCI „Cursor Style“ JE ZÁRUKOU, ŽE WEBOVÉ STRÁNKY, ROZŠÍŘENÍ, JEJÍ OBSAH NEBO JAKÉKOLI OPRAVY BY MĚLY BÝT PŘEDTÍM DOSTUPNÉ, OPRAVENÉ, ŽE NAŠE ROZŠÍŘENÍ, STRÁNKA NEBO SERVER, KTERÝ JE UMISŤUJE, BUDE BEZ VIRŮ NEBO JINÝCH ŠKODLIVÝCH KOMPONENT NEBO TATO WEBOVÁ STRÁNKA NEBO JAKÉKOLI SLUŽBY NEBO POLOŽKY VYKONANÉ, PREFERENČNÍ. 
<p> Za žádných okolností NENEBUDE SLUŽBA, JEJÍ PARTNEŘI NEBO POSKYTOVATELÉ LICENCE, SLUŽBY, ZAMĚSTNANCI, ZÁSTUPCI, ÚŘEDNÍCI nebo ŘEDITELÉ ODPOVĚDNÍ ZA ŠKODY JAKÉHOKOLI DRUHU, UVÁDÍME SLUŽBU NA JAKOUKOLI ODPOVĚDNOST. NEBO JINÉ TAKOVÉ WEBOVÉ STRÁNKY NEBO JAKÉKOLI SLUŽBY NEBO POLOŽKY POSKYTOVANÉ VE SLUŽBĚ NEBO JINÉ WEBOVÉ STRÁNKY, VČETNĚ PŘÍMÝCH, ZVLÁŠTNÍCH NEBO NÁSLEDNÝCH ŠKOD, VČETNĚ OSOBNÍCH ZRANĚNÍ, emocionálních poruch, ŠKOD NEBO OČEKÁVANÝCH ÚSPOR, ZTRÁTY POUŽÍVÁNÍ, DAT NEBO JINÝCH PODMÍNEK. DEFINICE NEOVLIVŇUJE ŽÁDNOU ODPOVĚDNOST, KTEROU NELZE VYLOUČIT NEBO OMEZIT V SOULADU S PLATNÝMI ZÁKONY, KTERÉ MOHOU ZAHRNUTI PODVOD. </p>
<p> Souhlasíte s tím, že budete chránit, odškodňovat a defuseovat společnost „Cursor Style“, její přidružené společnosti, poskytovatele licencí a poskytovatele služeb, jakož i její a jejich příslušné úředníky, ředitele, zaměstnance, dodavatele, zástupce, poskytovatele licencí, dodavatele, asignáty a veškeré nároky a závazky, ztráta soudních rozhodnutí, náklady, výdaje nebo provize (včetně odměn pro právníky) vyplývající nebo v souvislosti s vaším porušením těchto Podmínek použití nebo používáním Služby, včetně, ale nikoli výhradně, odvolání jakéhokoli použití obsahu, služeb a produktů webových stránek nebo Rozšíření, s výjimkou případů výslovně stanovených v těchto Podmínkách použití, nebo vašeho používání jakýchkoli informací získaných ze Služby. </p>
<p> Pokud se zjistí, že jakékoli ustanovení těchto Podmínek použití je z jakéhokoli důvodu neplatné, nezákonné nebo nevymahatelné soudem nebo jiným tribunálem příslušné jurisdikce, mělo by být takové ustanovení zrušeno nebo omezeno na minimum, aby ostatní ustanovení Podmínek použití pokračovala v plném rozsahu. Podmínky použití, naše Zásady ochrany osobních údajů a podmínky pro registraci událostí představují jedinou a úplnou dohodu mezi vámi a „Cursor Style“ ohledně Služby a nahrazují všechny předchozí a současné dohody, dohody, prohlášení a záruky, písemné i ústní, týkající se Služby. </p>
<p> Všechny recenze, komentáře, žádosti o technickou podporu a další zprávy týkající se Služby by měly být směrovány na stránku podpory „Cursor Style“ v obchodě Chrome Web Store. </p> ',
];
