<?php

return [
    'halo_descr' => 'Halo é uma franquia de media de fantasia de combate criada pela Bungie. Baseado na trilogia original de videojogos de tiro na primeira pessoa. A trama gira em torno dos eventos que ocorrem na vida de Master Chief, um de um grupo de super-soldados com o codinome Spartans, e sua companheira, a inteligência artificial Cortana. O sucesso dos jogos levou à expansão da franquia para outras mídias: o universo Halo atualmente abrange muitos livros, romances gráficos, banda desenhada, curtas, animações e longas-metragens.',
    'halo_short_descr' => 'Toque no cursor do artefacto, talvez seja o escolhido.',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'As bonecas LOL Surprise apaixonaram-se pelas crianças e conquistaram os seus corações desde os primeiros minutos. E isto não é surpreendente, porque tal sucesso baseia-se num mistério, na expectativa de um milagre, numa agradável surpresa, que encanta não só as crianças, mas também os seus pais. O segredo do presente é revelado à criança apenas após a desembalagem final. Em qualquer caso, as bonecas LOL são um design atrativo, intriga, um grande número de acessórios incríveis e realistas e pequenas coisas agradáveis, bem como a mais alta qualidade de produção e detalhe do brinquedo.',
    'lol_surprise_short_descr' => 'Bonecas giras para quem aprecia surpresas bonitas',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'A série gira em torno de um concurso onde 456 jogadores, todos com dívidas financeiras profundas, arriscam as suas vidas para jogar uma série de jogos infantis mortais pela chance de ganhar um prémio de mil milhões. Lá dentro, um prémio tentador aguarda com apostas mortais. O título da série deriva de um jogo infantil coreano com o mesmo nome. Hwang concebeu a ideia com base nas suas próprias dificuldades económicas no início da vida, bem como na disparidade de classes na Coreia do Sul e no capitalismo.',
    'squid_game_short_descr' => 'Escolha a cara do jogador certo quando for all-in',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter é o protagonista de uma série de romances da escritora inglesa JK Rowling. No seu décimo primeiro aniversário, Harry descobre que é um feiticeiro e está destinado a um lugar na Escola de Magia e Bruxaria de Hogwarts, onde praticará magia sob a orientação do diretor Alvo Dumbledore e outros professores da escola. Harry também descobre que já é conhecido em toda a comunidade mágica do romance, e que o seu destino está ligado ao destino de Voldemort, um perigoso mago das trevas.',
    'harry_potter_short_descr' => 'O que farás com uma varinha mágica da coleção de cursores do Harry Potter?',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'A Marvel Comics é uma editora de banda desenhada conhecida por criar super-heróis notáveis como o Homem-Aranha, Homem de Ferro, Capitão América, Hulk, Thor, os Vingadores, os Guardiões da Galáxia, os X-Men, o Quarteto Fantástico e Deadpool. Os vilões mais conhecidos da Marvel incluem o Duende Verde, Caveira Vermelha, Loki, Thanos, Ultron, Doutor Destino e Magneto. A Marvel Comics e a DC Comics colaboraram em vários projetos de crossover e também co-fundaram a editora Amalgam Comics, intencionalmente de curta duração.',
    'marvel_comics_short_descr' => 'O super-herói vive em cada um de nós - escolha o seu',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Bem-vindo de volta ao Reino Cookie em Cookie Run: Kingdom da Devsisters, o adorável RPG de estratégia ambientado no universo Cookie Run. Agora que o GingerBrave escapou do forno da bruxa malvada, é hora de ele construir uma equipa de Cookies e embarcar numa missão para reconstruir o Reino Cookie caído. Descubra a verdade por trás da queda do Reino e junte uma equipa dos Cookies mais poderosos do Reino para derrotar as forças das trevas que querem impedir o GingerBrave de realizar o seu destino.',
    'cookie_run_kingdom_short_descr' => 'Pequenos guerreiros saídos diretamente do forno',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact é um jogo de aventura em mundo aberto. Isto significa que uma nova e deliciosa paisagem espera por si do outro lado do rio ou da montanha, apenas precisa de usar a sua energia com sabedoria. Se se deparar com uma fada errante ou um mecanismo estranho, ouse e tente desvendar o seu mistério. Mas o que eles prometem - problemas ou uma surpresa agradável - só você pode descobrir! No vasto continente de Teyvat, visitará sete reinos, encontrará companheiros com várias habilidades e lutará contra inimigos poderosos em busca de um ente querido desaparecido.',
    'genshin_impact_short_descr' => 'Torne-se o Mestre Elemental dos Sete Reinos',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Quando uma antiga profecia se concretiza e o reino mergulha no abraço do inverno, três heróis destemidos - a Princesa Anna, o bravo Kristoff e a sua fiel rena Sven - vão para as montanhas para encontrar a irmã de Anna, Elsa, que pode remover o feitiço gelado do país. Ao longo do caminho, muitas surpresas difíceis e aventuras emocionantes os aguardam. Encontro com trolls místicos, conhecer um charmoso boneco de neve chamado Olaf, picos de montanha mais íngremes que o Everest e muita magia. Os heróis têm que resistir aos poderosos elementos para salvar o reino e aqueles que lhes são queridos.',
    'frozen_short_descr' => 'Partir o gelo é fácil com a coleção de cursores Frozen',
    'frozen' => 'Frozen',
    'stranger_things_descr' => 'Passaram-se pouco mais de seis meses desde o final da terceira temporada. Joyce, Will, Eleven e Jonathan mudaram-se para a Califórnia, onde a menina é intimidada na escola. O resto começa a lutar contra um novo monstro de um mundo paralelo que apareceu em Hawkins. Ele foi apelidado de Vecna, em homenagem à personagem do jogo de tabuleiro Dungeons & Dragons. Afeta os adolescentes psicologicamente, depois sobe mentalmente à cabeça e mata. Em paralelo, Joyce e Murray descobrem que Jim Hopper está vivo e vão atrás dele para uma prisão soviética em Kamchatka. E Eleven terá que voltar e aumentar seus poderes, mas também aprender seu papel importante na criação do mesmo monstro em Gokins.

Os roteiristas não mudaram as táticas de enredo que gostaram nas últimas temporadas. Na quarta temporada, eles dividiram o grande grupo de personagens principais em grupos, criaram tarefas difíceis para eles e, no final, construíram suas histórias juntas em um final incrível. Oferecemos a você a compreensão detalhada de todas essas aventuras com a ajuda da coleção de cursores Stranger Things.',
    'stranger_things_short_descr' => 'O que acontecerá a seguir? - Cursores de Stranger Things 4',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars é um modo original que apareceu pela primeira vez no Minecraft. A tarefa dos jogadores era para o utilizador proteger a sua base e cama.

Roblox traz jogos mais emocionantes todos os dias e BedWars não é exceção. E a questão é que, se adora bed wars e se defender no seu quarto, este é o título para si porque o leva de volta à infância, embora digitalmente desta vez.

Tudo o que precisa de fazer é defender a sua cama dos atacantes com o seu parceiro. Entra num lobby, escolhe com quem jogar, e pronto, é só uma questão de proteção.

Claro que, quando se trata de defesa, terá alguns problemas e existem certos recursos, itens e artigos que o ajudarão a ganhar. Por exemplo, skins exclusivas que encontrará na coleção de cursores Bed Wars.',
    'roblox_bed_wars_short_descr' => 'Proteja a sua cama com os cursores do Roblox Bed Wars',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'No aniversário de Naruto Uzumaki, um demónio lendário, a Raposa de Nove Caudas, atacou uma vila chamada Konoha. O Quarto Hokage, à custa da sua vida, salvou a vila selando o demónio no recém-nascido Naruto, sem saber, condenando-o a uma vida de ódio dos seus companheiros aldeões.
Apesar da sua falta de talento em muitas áreas do ninjutsu, inquietação e esnobismo, Naruto tem o sonho de se tornar Hokage, o ninja mais forte da aldeia. Desejando o reconhecimento que não teve, ele trabalha arduamente e treina ao lado dos seus companheiros de equipa Sasuke Uchiha e Sakura Haruno, bem como o seu mentor Kakashi Hatake. Ele e os seus parceiros terão que passar por muitas coisas no caminho para os seus sonhos queridos: batalhas, amor, amizade, traição, sede de poder. Uma coleção de cursores de anime Naruto irá ajudá-lo a navegar no seu próprio caminho!',
    'naruto_anime_short_descr' => 'Percorra o seu caminho ninja com os cursores Naruto anime',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'A ação decorre durante a era Taisho. Desde tempos antigos, houve rumores de que demónios humanoides vivem na floresta, que se alimentam de pessoas e andam à noite, à procura de uma nova vítima. Mas... é só uma lenda, certo?..

Tanjiro Kamado é o filho mais velho da família, que perdeu o pai e cuidou da sua família. Um dia, ele vai a uma cidade próxima para vender carvão. Voltando de manhã, o rapaz descobre uma imagem terrível à sua frente: todos os parentes foram brutalmente mortos, e a única sobrevivente é Nezuko, uma irmã mais nova transformada em demónio, mas que ainda não perdeu toda a sua humanidade.

A partir deste momento, Tanjiro e Nezuko começam uma longa e perigosa jornada, na qual o rapaz pretende encontrar o assassino e descobrir uma maneira de curar a sua irmã. Mas as crianças conseguem superar todas as dificuldades e voltar para casa? Já sabe a resposta, e se não - defina os cursores Demon Slayer, com personagens de um dos mangas mais populares.',
    'demon_slayer_anime_short_descr' => 'Cursores de Demon Slayer - para verdadeiros caçadores noturnos',
    'demon_slayer_anime' => 'Anime Demon Slayer',
    'bts_descr' => 'BTS é um grupo masculino de sete membros da BigHit Music. Eles estrearam em 13 de junho de 2013 com o single "No More Dream". No Japão, estrearam em 24 de dezembro de 2014 com o álbum de estúdio Wake Up.

O nome do grupo vem da expressão coreana Bangtan Sonyeondan, que significa "escuteiros à prova de balas". Segundo J Hope, o nome significa o desejo da banda de bloquear os estereótipos, críticas e expectativas que são direcionadas a adolescentes como balas.

A coleção de cursores dedicados ao grupo inclui todos os membros do grupo, aqui o cursor Kim Nam Joon (também conhecido como RM), o cursor Kim Seok Jin (Jin), o cursor Min Yoongi (Suga), o cursor Jung Ho Suk (J-Hope), o cursor Park Ji Min (Jimin), o cursor Kim Tae Hyun (V) e o cursor Jeon Jungkook (Jungkook).',
    'bts_short_descr' => 'Conheça os seus ídolos com cursores BTS',
    'bts' => 'BTS',
    'miraculous_descr' => 'Miraculous: As Aventuras de Ladybug e Cat Noir, mais conhecido como Miraculous Ladybug e Cat Noir, são as aventuras de super-heróis da série de desenhos animados sobre dois colegas de escola que, por baixo das máscaras, desempenham o papel de defensores de Paris de um vilão que em cada episódio encontra uma nova forma de prejudicar a cidade. Miraculous é feito em França, usando CGI e animação. Miraculous não é apenas uma série animada, mas também uma coleção de banda desenhada lançada em todo o mundo. A série é muito amada pelo público jovem.

A ação passa-se em Paris, onde Marinette e Adrian são estudantes do ensino médio numa escola moderna. Receberam o papel de se tornarem os escolhidos na luta contra o mal, salvando a sua cidade natal. O seu objetivo é proteger as pessoas dos Akumas. Estas pequenas criaturas em forma de borboletas conseguem habitar uma pessoa e transformá-la numa vilã.

Marinette pode transformar-se numa joaninha, e Adrian - num Cat Noir, mas, surpreendentemente, trabalhando em equipa, não se reconhecem por baixo das máscaras de super-heróis.

Ajude Cat Noir e Ladybug a salvar Paris com os nossos cursores com as suas personagens favoritas. Qual personagem escolherá para o cursor? Será um cursor Miraculous Ladybug, ou talvez a adorável joaninha Tikki ou um cursor Cat Noir? Ou talvez um cursor Queen Bee com Rena Rouge? A escolha é sua!',
    'miraculous_short_descr' => 'Junte-se às fileiras dos super-heróis com a coleção de cursores da Ladybug e Cat Noir',
    'miraculous' => 'Miraculous: As Aventuras de Ladybug e Cat Noir',
    'talking_tom_descr' => 'A série acompanha o dia a dia do Talking Tom e seus amigos. Tom e seu parceiro de negócios nerd, Ben, estão constantemente desenvolvendo aplicativos móveis e outras invenções para alcançar a fama e a fortuna e tentar se mostrar ao mundo, mas isso sempre dá errado. A namorada de Tom, Angela, tenta ser cantora, não importa o que faça para alcançar isso. O vizinho de Tom, Ginger, aparece com frequência aqui para pregar peças com travessuras na manga. O melhor amigo e colega de quarto estúpido, Hank, fica em casa, assiste MUITA TV. E a ex-estrela pop dissidente Becca Sparkles se tornou a nova colega de quarto de Angela e parece ter se apaixonado por Hank. No entanto, não importa o quão ruins sejam as coisas de todas as formas e tamanhos, seja o CEO malvado, o novo vizinho misterioso de Tom ou apenas um acidente na nova criação de Ben, a turma vai se divertir de qualquer maneira e sempre se lembrar de uma coisa que os mantém unidos: a amizade nunca termina, assim como o nosso amor pelos personagens da série não termina, então agora você pode definir o cursor do Talking Tom ou o cursor do Ben, ou talvez o cursor da Angela, o cursor do Oliver!',
    'talking_tom_short_descr' => 'Vamos falar sobre a tua personagem favorita na coleção de cursores Talking Tom',
    'talking_tom' => 'Talking Tom and Friends',
    'lego_descr' => 'A empresa The LEGO Group foi fundada em 1932 e, nessa época, era composta por apenas 7 pessoas. O objetivo da equipe Lego era criar brinquedos que desenvolvessem a criatividade, a imaginação e a engenhosidade de uma criança. Um facto incrível, desde a sua criação em 1949, os elementos LEGO em todas as suas variantes mantiveram-se compatíveis entre si. Todos os itens criados posteriormente ainda são compatíveis com os itens que estão a ser lançados hoje, apesar das mudanças no design e formato ao longo dos anos.

Um tijolo LEGO é uma base, que é um bloco de plástico oco que se conecta a outros tijolos semelhantes. Mas os conjuntos Lego também contêm outras peças, rodas, figuras, plataformas e até circuitos eletrónicos com sensores e motores elétricos. Pode colecionar modelos de carros, aviões, comboios, navios, edifícios, robôs. A LEGO adere à ideia de modularidade, que demonstra claramente às crianças como resolver certos problemas, desenvolver a imaginação, as habilidades motoras finas das mãos e as habilidades de montagem. Os tijolos LEGO são fabricados com uma precisão incrível e encaixam-se perfeitamente para uma impressionante precisão de 10 microns.

Recentemente, muitas histórias Lego animadas em 3D populares foram criadas, onde os personagens dos conjuntos ganham vida e se tornam participantes de aventuras incríveis. Se deseja um cursor fixe, encontrará muitos personagens da série de TV e filmes de animação Lego na nossa coleção de Cursors Lego. Cursor Lego Ninjago, Cursor Lego Batman, Cursor Lego Ninjago, Cursor Lego Wyldstyle e muitos mais.',
    'lego_short_descr' => 'Construa o seu browser de sonho com a coleção de cursores Lego',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Após o financiamento bem-sucedido no Kickstarter, em 2017, a Team Cherry lançou o jogo multiplataforma para PC Hollow Knight. Esta é a história de um cavaleiro sem nome e as suas descobertas no reino dos insetos de Hallownest. O jogo foi justamente reconhecido como um dos melhores do género metroidvania.

A jogabilidade de Hollow Knight baseia-se na exploração do mundo do jogo. Superar obstáculos, resolver quebra-cabeças e encontrar segredos, bem como lutar contra inimigos. O jogador tem um conjunto único de melhorias e truques para explorar o mundo e lutar em batalhas. Indo de zona para zona, o jogador derrota chefes e obtém as melhorias necessárias para avançar mais. Como resultado, os jogadores têm que visitar as áreas já percorridas para encontrar segredos e seguir a história. E também é emocionante porque as zonas mudam a cada vez, trazendo novas surpresas e experiências. O jogo pode ser jogado de diferentes maneiras, porque existem vários caminhos diferentes entre as zonas. Ao passar pela história, você abre o mapa da zona, mas primeiro precisa obter o mapa.

A principal arma do herói é uma prego, que é um pouco semelhante a uma espada, as armas podem ser melhoradas com um ferreiro, bem como aprender diferentes habilidades no uso de armas, o que amplia a variedade de ataques. Ao atacar inimigos, você acumula um recurso especial, que pode ser usado posteriormente para melhorias ou cura.
Divirta-se a jogar Hollow Knight e não se esqueça dos nossos cursores Hollow Knight com a sua personagem favorita. A nossa coleção inclui o Cursor Mister Mushroom, Cursor Quirrel, Cursor Hornet Needle, Cursor Old Nail, Cursor Myla e outros.',
    'hollow-knight_short_descr' => 'Tente não se perder no reino dos insetos usando a coleção de cursores Hollow Knight',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman é a personagem principal da série. Stickmin, anteriormente sem nome, começou como um ladrão menor, com o desejo de ganhar dinheiro fácil rapidamente. No entanto, após escapar da prisão de West Mesa, muitas mudanças ocorrem na sua vida, e ele torna-se um criminoso famoso após roubar o Diamante Tunisino. Henry tem uma escolha - tornar-se um agente governamental de sucesso, caçador de recompensas, líder de uma organização criminosa, cyborg, ou continuar o caminho criminoso sozinho. O jogo delicia os fãs do género com muitas aventuras e mistérios, e encontrará a nossa nova coleção de cursores Henry Stickman com as suas personagens engraçadas, incluindo o cursor Henry Stickmin, o cursor Charles Calvin, o cursor Reginald Copperbottom, o cursor Right Hand, o cursor Ellie Rose e outros!',
    'henry-stickmin_short_descr' => 'Planeie a sua fuga do tédio com a Coleção de cursores Henry Stickman.',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'O jogo online muito popular Adopt Me foi lançado em 2017 e tornou-se o mais popular na plataforma de jogos Roblox. A essência do jogo é muito simples - obter ovos com animais de estimação e cuidar deles.

Os animais de estimação virtuais são divididos em 5 classes, alguns deles são muito raros e caros, enquanto outros são muito fáceis de obter. Estes são grupos incomuns, como o Blue Dog, o cursor Comum, o Raro, por exemplo, o cursor do rato Adopt Me Monkey, bem como os ultra-raros, como o cursor Koala, e o Lendário, o cursor Dragon e o Accept me unicorn. Se o jogador tiver quatro animais de estimação adultos do mesmo tipo, pode combinar num animal de estimação neon, como o cursor do jogo Neon Horse ou o Adopt Me Neon Starfish. Ao combinar quatro animais de estimação normais, pode fazer um animal de estimação neon que realmente brilha, e a partir de animais de estimação neon pode criar um animal de estimação mega-neon.

As compras no jogo Adopt Me! são realizadas com a moeda virtual Roblox - os chamados Robux, e o jogo também tem a sua própria moeda - Bucks. Cuidar do seu animal de estimação, além de entretenimento, pode ganhar bucks, basta alimentá-lo, deitá-lo ou ler uma história, em geral, muitas coisas interessantes.

Agora os fãs do jogo Roblox "Adopt Me!" podem decorar o seu cursor do jogo com o animal de estimação favorito!',
    'adopt-me_short_descr' => 'Diverte-te com animais de estimação fofinhos na nossa coleção de cursores do jogo Adopt Me!',
    'adopt-me' => 'Adopt me!',
    'among-us_descr' => 'Among Us é baseado no famoso jogo de RPG "Mafia". Estava planeado que o jogo fosse exclusivo para dispositivos móveis, porque só tinha um mapa. O jogo tornou-se rapidamente popular. Mais tarde, a equipa de desenvolvimento adicionou um modo multijogador e foram lançados dois mapas adicionais em 2019.
Among Us é um jogo de terceira pessoa com vista de cima que permite ao jogador mover-se em todas as direções. De quatro a dez jogadores podem jogar numa ronda. No início do jogo, a todos é secretamente atribuído o papel de um traidor ou membro da tripulação. O Impostor (na tradução russa "Traidor") pode esconder-se na escotilha de ventilação, sabotar e matar membros da tripulação. O seu objetivo é destruir todos os membros da tripulação, ou destruir a nave espacial por sabotagem. O objetivo da tripulação da nave é resolver vários puzzles preparados para eles no início do jogo. Se cada um dos membros da tripulação completar todas as tarefas, os traidores perderão. Além disso, a tripulação da nave pode alcançar a vitória eliminando os traidores durante a votação.
Os traidores podem sabotar de tempos em tempos e se as avarias não forem corrigidas em 30 segundos, a tripulação perderá. Antes de iniciar o jogo, pode escolher a cor da personagem com que está a jogar, azul, vermelho, amarelo, cinzento - o que quiser! E não se esqueça de definir o cursor apropriado da nova coleção Among Us!',
    'among-us_short_descr' => 'Não se deixe enganar neste jogo espacial complicado com os cursores Among Us',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'A criadora de "Steven Universe" foi Rebecca Sugar. Ela é conhecida pelo seu trabalho anterior chamado Adventure Time. O primeiro episódio de Steven Universe foi lançado na plataforma de vídeo YouTube na primavera de 2013. Mas no outono, o canal americano Cartoon Network começou a transmiti-lo para os seus espectadores. Desde então, 6 temporadas foram lançadas. A sexta promete ser a final.
Quanto ao enredo da série animada, ele gira em torno da equipa Crystal Gems. Ela consiste em criaturas alienígenas com nomes característicos: Pérolas, Ametista e Romã. Mas há outro participante nela, no papel do qual atua um rapaz comum, Stephen. Juntos, eles procuram monstros e tentam neutralizá-los para que não tomem a Terra para ganho pessoal. Eles são oprimidos por Jasper e Peridot - mensageiros do seu planeta natal que querem derrotar as Gems e ligar o Cluster.
Se é fã de Steven Universe e quer ver as personagens da série animada onde quer que possa, instale a extensão Cursor Style! Porquê fazer isto? Pode adicionar uma coleção dedicada a "Steven Universe" e transformar o ponteiro do rato padrão numa das suas personagens favoritas.',
    'steven_universe_short_descr' => 'Descubra o segredo das gemas com cursores de Steven Universe',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Uma sitcom de animação chamada "Family Guy" que em toda a história de sua existência ganhou 4 vezes o Emmy Award e 3 vezes o "Annie". A série animada ridiculariza os tópicos sensíveis da sociedade americana, como: feminismo, escravidão, obesidade, política, etc. Ao contrário de outras obras, aqui são usadas inserções com piadas e sarcasmo. Além disso, em muitos casos, elas não estão integradas na trama, mas existem por conta própria.
Um episódio da série animada é criado ao longo de 10 meses. Por que tanto tempo? Porque toda a animação é desenhada à mão. Devido a isso, alguns dos eventos cobertos pela obra têm tempo para perder relevância. Mas, mesmo assim, a sitcom permanece muito interessante e conquista o favor dos espectadores em todo o mundo. Afinal, quem não gosta de rir bem de políticos, celebridades ou pessoas que cometem travessuras selvagens e, com isso, surpreendem ou até chocam pessoas comuns.
Você gosta de "Family Guy"? Você tem uma oportunidade única de transformar um cursor normal do mouse em qualquer um dos personagens desta série animada! O que preciso fazer? Basta instalar a extensão do navegador “Cursor Style”, adicionar uma coleção dedicada a “Family Guy” a ela e aproveitar uma reencarnação fabulosa!',
    'family_guy_short_descr' => 'Coleção de cursores de Family Guy para apreciadores de humor especial',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Certamente que já ouviu a expressão "A beleza salvará o mundo"? Assim, muitas pessoas, especialmente meninas, concordam com esta afirmação. Portanto, esforçam-se por rodear-se de tudo o que é mais belo e agradável aos olhos. Pode ser papel de parede rosa no quarto, brinquedos macios, almofadas bordadas com contas, joias preciosas, etc. Do exterior, tudo parece muito fofo e até um pouco infantil. Mas cada um de nós é um pouco criança no nosso coração, então por que não deixá-lo mostrar a nossa imaginação?
A ternura em nós pode causar muita coisa. Por exemplo, os olhos compassivos de um gatinho que quer ser acariciado ou alimentado. Um arco-íris multicolorido, espreitando depois de uma chuva de primavera e cintilando com todas as cores ao sol. A criança que foi presenteada com chocolate e decidiu compartilhá-lo com a sua namorada ou namorado. Há muitas razões para tocar, e decidimos usá-las como cursores.
Cansado da chata seta branca no seu navegador? Substitua-a por algo fofo da nossa coleção! Por exemplo, um unicórnio rosa e branco, um tomate triste, uma nuvem carrancuda, um cacto espinhoso em forma de gato, ou o que quiser. Tudo o que precisa é instalar a extensão Cursor Style e adicionar-lhe uma coleção de cursores fofos. E viva a salvadora do mundo - a beleza!',
    'cute_cursors_short_descr' => 'O mundo será mais gentil com a coleção de cursores fofos',
    'cute_cursors' => 'Cursores Fofos',
    'web_media_descr' => 'Nas realidades modernas, quase todos usam a Internet. A começar pelas crianças e a terminar nos aposentados. Uns navegam usando um navegador, outros assistem a vídeos no YouTube e outros precisam da Rede para comunicar com os seus entes queridos. Qualquer um destes utilizadores não consegue imaginar um dia sem a World Wide Web.
As pessoas mais velhas costumam estar numa rede social como o Facebook ou o VK. Também costumam comunicar com os seus filhos e netos no Skype. Isto é especialmente conveniente se os filhos e os pais morarem em cidades ou até países diferentes.
Os jovens preferem comunicar através do Viber ou Telegram, carregar fotos no Instagram, rir-se dos memes do FB. Os vídeos do YouTube com reações das pessoas estão a ganhar milhões de visualizações, tal como as várias partidas ou experiências sociais. No Tik-Tok, centenas de milhares de pessoas dançam, mostram truques de magia e expressam-se.
Está interessado ou simplesmente usa com frequência algum tipo de recurso da área da web media? Quer livrar-se da aborrecida seta do rato no seu navegador? Então instale a extensão e mude o cursor padrão para o nosso cursor criativo! Pode ser um cursor do YouTube, um cursor do Viber, um cursor do Google Chrome ou outros recursos.',
    'web_media_short_descr' => 'Viva ao ritmo moderno com a coleção de cursores de web media',
    'web_media' => 'Web Media',
    'bobs_burgers_descr' => 'A série animada Bob\'s Burgers é a intriga do trabalho de animação e o carisma das personagens. E, a julgar pela nomeação para o Emmy Award e pelo reconhecimento do trabalho como uma das melhores cartoons do mundo inteiro, Bob\'s Snack realmente fez sucesso.
A intriga da série animada gira em torno da família Bob Belcher. Esta pessoa é a dona da lanchonete no primeiro andar, e no segundo vive com seus entes queridos. Bob tem uma esposa alegre, Linda, e 3 filhos: Gene, Louise e Tina. O menino sonha com uma carreira musical, a filha mais velha, Tina, é muito gentil, mas desajeitada, e a mais nova - Louise ainda é uma malandra e muitas vezes coloca sua família em uma posição desconfortável. A principal concorrente do Bob\'s Burgers é a Pizzaria de Jimmy Pesto. Como você pode imaginar, o dono desta pizzaria se chama Jim, e ele e Bob se odeiam. Tudo isso foi batido para que parecesse cômico, não sério. Portanto, muitas de suas escaramuças causam apenas um sorriso.
Se você ama a série animada “Bob\'s Burgers” e quer ver seus personagens não apenas na tela do monitor ou TV, instale a extensão, adicione uma coleção e mude o cursor do mouse no navegador para qualquer um dos personagens desta cartoon!',
    'bobs_burgers_short_descr' => 'O Bob faz hambúrgueres, e nós fazemos cursores do Bob\'s Burgers',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'A história do videojogo "Kirby" começou já nos anos 90 do século passado. Consiste em muitas séries que foram desenvolvidas pela Nintendo e pelo HAL Laboratory. O jogo é destinado a crianças de um ano e meio a 8 anos. A sua popularidade pode ser julgada pelo número de cópias vendidas. Mais de 34 milhões em todo o mundo.
A personagem principal de Kirby é a criatura rosa homónima. Vive num planeta chamado Pop Star e periodicamente protege-o de vários perigos. Kirby consegue respirar alguns objetos e os seus inimigos para aprender as suas habilidades: combate corpo a corpo, posse de uma espada, respiração de fogo, etc. No entanto, o puffer rosa não só luta com os inimigos, como também resolve vários quebra-cabeças, viaja para outros países e consegue até voar em níveis.
Pode jogar este videojogo em consolas Nintendo ou Game Boy. Em todas as séries existem heróis fofos, bons gráficos e bandas sonoras engraçadas. A propósito, em quase 30 anos desde o lançamento da primeira versão, o mundo conseguiu ver 20 séries Kirby. Este indicador, juntamente com o volume multimilionário de cópias vendidas, ajudou o jogo a estar no TOP 50 dos videojogos de maior sucesso e procurados na indústria do jogo.
Adora Kirby, de forma a querer ver esta personagem onde quer que seja possível? Então use a coleção Kirby e transforme o ponteiro do rato normal na personagem principal do seu videojogo favorito! Temos a certeza de que vai gostar do novo visual do cursor.',
    'kirby_short_descr' => 'Tenta inalar toda a coleção de cursores do Kirby',
    'kirby' => 'Kirby',
    'undertale_descr' => 'Em tempos antigos, a Terra era habitada não só por pessoas, mas também por monstros. Devido a desavenças entre eles, uma guerra eclodiu, que terminou a favor da raça humana. Sete mágicos impuseram os monstros no subsolo e prenderam-nos para sempre com um feitiço de barreira. No entanto, havia apenas uma entrada para o Monte Ebott, da qual a criança se aproveitou. É por ele que você jogará executando o jogo de computador Undertale.
Este jogo foi desenvolvido por Toby Fox - um conhecido programador dos Estados Unidos. No início, proprietários de computadores pessoais executando Microsoft Windows e Linux OS podiam apreciá-lo, e depois chegou a vez dos utilizadores de consolas de jogos.
Qual é o ponto deste jogo? O menino viaja pelo submundo habitado por monstros. Alguns deles são imediatamente hostis, enquanto outros gostam de conversar. O jogador pode escolher um de 2 comportamentos: evitar a violência ou lutar. No primeiro caso, passar o jogo será mais fácil, no segundo - pelo contrário, é mais difícil. O enredo e o final, que podem ramificar-se e mudar, também dependem desta escolha.
Se você gosta de Underground Tale e gostaria de ver suas personagens no seu navegador, instale a extensão e adicione a coleção de cursores apropriada! Transforme um ponteiro do rato aborrecido em um dos monstros ou no personagem principal de Undertale!',
    'undertale_short_descr' => 'É hora de sair do buraco usando os cursores do Undertale',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune é um jogo de interpretação de papéis lançado para computadores há alguns anos. Foi criado pelo mesmo programador que desenvolveu Undertale. No entanto, estes dois jogos são quase nada semelhantes, embora tenham algumas personagens e localizações em comum.
Existem várias personagens principais em Delta Rune. Este é um estudante Chris, que pode ser controlado, e uma encantadora monstra Susie, incontrolável. Ambas as personagens caem no mundo das trevas, onde conhecem um dos seus habitantes - Ralsay. Ele diz-lhes que, de facto, são criaturas de luz que têm uma missão - parar o fluxo de energia escura num mundo sombrio. Para fazer isso, eles precisam poupar os monstros locais e tentar não entrar em batalha com eles, embora isso às vezes seja bastante difícil.
O jogador tem uma escolha simples: poupar as criaturas escuras ou atacá-las. Como Susie não é fã de meias medidas, em muitos casos ela escolhe uma batalha. Portanto, Chris não tem escolha a não ser apoiar a sua namorada e ajudá-la nas batalhas.
Adora o jogo Deltarune? Então personalize o cursor do seu rato no navegador para uma das suas personagens! Pode fazer isso com a nossa extensão. Instale-a, adicione a coleção “Rune Delta” e ative-a! Agora a sua seta deixou de ser a mesma que todos os outros e tornou-se Chris, Susie ou uma das criaturas do mundo sombrio.',
    'deltarune_short_descr' => 'Mergulhe no mundo das trevas com esta coleção de cursores',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario é uma série de jogos de computador lançada pela Nintendo. O primeiro e mais popular jogo foi chamado Super Mario Bros. Ele viu a luz em 1985. Mais tarde, foi listado no Livro dos Recordes Guinness. Desde então, foram lançados mais de 20 jogos, cada um com a sua própria trama. Em 2019, apareceu uma nova versão chamada Super Mario Maker 2. Apesar da melhoria nos gráficos, o estilo e as personagens mantiveram-se os mesmos, o que evoca nostalgia pelo Super Mario dos anos 80.
O protagonista continua a ser o canalizador Mario. Na trama da última variação do jogo, o castelo da Princesa não teve pedra sobre pedra. Mario deve reconstruí-lo, tendo antes ganho as moedas que lhe são pagas pelas tarefas. No total, este jogo tem mais de 100 níveis de várias dificuldades com possibilidade de modificação. Também no Super Mario Maker 2 existem novos modos de jogo. Pode jogar quatro deles de uma vez e assim que um terminar, o nível é considerado concluído. Existem também modos como: Maratona Mario, Duelo e corridas Ninjik.
Adora Super Mario e tudo o que está relacionado com este jogo maravilhoso? Então, defina os cursores feitos ao estilo desta plataforma! Temos a certeza que vai gostar do cursor Mario, do cursor Luigi, do cursor Princesa Peach e de outros cursores que são apresentados na nossa coleção!',
    'super_mario_short_descr' => 'Percorre o Reino do Cogumelo com a coleção de cursores do Super Mario',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls foi criado em conjunto pela Disney Television Animation Corporation e Alex Hirsch. A estreia foi lançada em 2012 e foi exibida no Disney Channel. Toda a primeira temporada da série animada foi transmitida lá. Dois anos depois, foi lançada a segunda temporada, que os espectadores puderam assistir no canal anterior e no Disney XD. Infelizmente, os fãs de Gravity Falls não esperaram pela terceira e subsequentes temporadas. Os criadores decidiram limitar-se a duas temporadas sem quaisquer sequelas.
Quanto ao enredo desta imagem animada, toda a ação se passa numa cidade fictícia chamada Gravity Falls. Dois gémeos chegam lá, chamados Mabel e Dipper. Eles estão a ficar com o seu primo Stan. Ele tem a sua própria loja de lembranças turísticas. Quando os irmãos se cansam de "não fazer nada", eles vão em busca de aventura. Um deles encontra um diário estranho na floresta, que fala sobre as anomalias desta cidade. Os gémeos partem em busca do seu autor e encontram criaturas e lugares incomuns. Se está interessado nesta série animada e já foi fã das suas personagens, recomendamos-lhe a nossa coleção de cursores de rato ao estilo de Gravity Falls!',
    'gravity_falls_short_descr' => 'Embarca numa aventura com cursores de Gravity Falls',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Absolutamente toda a gente já ouviu falar de uma série animada tão famosa como Os Simpsons. Mesmo as pessoas que nunca viram a série sabem da existência das personagens amarelas. E os fãs ficam encantados quando a próxima temporada da sua série favorita é lançada. Aliás, no outono de 2019, foram lançadas 31 temporadas. E a primeira apareceu nos ecrãs de televisão em 1989. A Fox começou a exibi-la e continua a fazê-lo devido às altas audiências e simpatia do público.
Os Simpsons é um género satírico que aborda temas relevantes. Este pode ser o estilo de vida do americano médio, questões políticas e religiosas, truques "estrelados" de celebridades, feminismo, casamento entre pessoas do mesmo sexo. Em geral, tudo relacionado com eventos locais e globais nos quais os Estados Unidos participam.
A ação da série animada decorre na inexistente cidade de Springfield. Na verdade, existem muitas cidades com esse nome na América. Talvez por isso tenha sido escolhida, para que o público não associasse o que estava a acontecer nos ecrãs a uma localidade específica, mas apenas adivinhasse onde isso poderia ser.
É muito provável que seja fã dos Simpsons. Caso contrário, por que leria este texto até ao fim? E, sendo assim, tem a oportunidade de mudar o aborrecido cursor do rato para um ponteiro que é feito no estilo desta série animada.',
    'simpsons_short_descr' => 'Uma família divertida com os cursores dos Simpsons.',
    'simpsons' => 'Os Simpsons',
    'youtubers_descr' => 'A plataforma de vídeo YouTube surgiu em 2005. No início, os vídeos eram lá publicados apenas pela expressão pessoal ou para informar sobre algo. No entanto, com o tempo, tudo isto transformou-se num negócio lucrativo, que traz milhares e, por vezes, milhões de dólares por mês aos bem-sucedidos utilizadores do YouTube. Quanto mais popular for um vlogger (a pessoa que conduz o blogue em vídeo), mais pode ganhar através do seu canal.
Quanto ganha uma menina vlogger de cinco anos, cujos pais a levam às atrações mais interessantes e filmam o que está a acontecer na câmara? É apenas como uma criança se diverte em parques infantis, que expressa emoções, como brincar e tudo esse tipo de coisas. A quantia é realmente espantosa - hoje o canal da criança ganhou quase 47 milhões de subscritores e começou a gerar rendimentos na ordem dos 5 milhões de rublos por mês.
Alguém carrega vídeos onde discute jogos de computador, alguém faz beatboxing ou organiza partidas para os transeuntes na rua. Alguns dedicam os seus vídeos a temas sensíveis, como a relação entre homens e mulheres. Quanto mais os utilizadores do YouTube gostam destes vídeos, maior é a popularidade do vlogger.
A coleção já adicionou os cursores PewDiePie, Shane Dawson, Ray William Johnson, Zoella, MyLifeAsEva e outros.',
    'youtubers_short_descr' => 'Uma nova geração de estrelas está sempre online na nossa coleção YouTubers',
    'youtubers' => 'YouTubers',
    'pusheen_descr' => 'Quase toda a gente conhece o gato Pusheen. Embora seja apenas uma personagem de uma banda desenhada infantil inventada há 10 anos, tem milhões de fãs hoje em dia. O gato Pusheen surgiu como uma ilustração criada pela artista Claire Belton.
Um ano depois, o gato adquiriu a sua própria página no Tumblr.com e em poucas semanas ganhou todo um exército de fãs - cerca de 10.000 pessoas. Em 2013, o Facebook estava ansioso por incluir imagens do Pusheen em coleções com outros emoticons. Após negociações com o criador, esta ideia foi posta em prática e "explodiu" a Internet! As imagens do gato Pusheen são usadas em correspondência mais de 10 milhões de vezes por dia!
Em 2014, um dos maiores fabricantes de brinquedos dos Estados Unidos chamou a atenção para esta personagem. A GUND (foi ela que inventou os ursinhos de peluche) lançou um par de modelos Pusheen. Como o sucesso foi enorme, ao fim de alguns meses foi criada uma coleção completa de brinquedos em forma deste gato.
Onde mais pode encontrar o gato Pusheen? Em conjuntos de oferta da Isaac Morris Ltd, em marshmallows da Boomf e, claro, na nossa coleção de cursores Pusheen!',
    'pusheen_short_descr' => 'Adicione algum conforto no seu navegador com a coleção de cursores Pusheen',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'A primeira série da obra de animação “Rick and Morty” foi lançada em 2013. Esta banda desenhada pode ser atribuída diretamente a 2 géneros: ficção científica e comédia. Os seus criadores foram Dan Harmon e Justin Royland. Inicialmente, todas as séries foram exibidas no canal Cartoon Network, e só depois foram duplicadas em cinemas online e plataformas de vídeo. A cada poucos anos, novas temporadas de Rick and Morty são lançadas, e em novembro de 2019 saiu a quarta temporada, que se revelou não menos interessante que as anteriores. A trama da série animada gira em torno de um gênio e, ao mesmo tempo, um cientista louco chamado Rick, bem como seu neto insignificante - Morty. Esses dois personagens estão conectados por aventuras conjuntas nos lugares mais incomuns. E eles chegam lá em um disco voador, capaz de se mover através de um túnel inter-espacial. Como você deve ter adivinhado, esta série animada se parece um pouco com o filme Back to the Future, mas ainda não é sua versão animada. No entanto, foi elogiado por muitos críticos pelos episódios humorísticos, criatividade e originalidade. Quer ver Rick ou Morty não apenas na série desta obra, mas também no navegador? Se sim, instale a extensão e adicione nossa coleção dedicada à sua banda desenhada favorita! Aqui estão o cursor Rick Sanchez, o cursor Morty Smith, o cursor Portal Gun e, claro, o cursor Mr. Meeseeks.',
    'rick_and_morty_short_descr' => 'Para de resmungar, usa só os cursores da coleção Rick and Morty.',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Os fãs de basebol podem ser encontrados em qualquer parte do mundo. Isso é especialmente verdade para os residentes de países como: EUA, China, Cuba, Coreia do Sul, Japão e Venezuela. Contrariamente à crença popular, o basebol não se originou na América, mas na Inglaterra. A primeira menção e descrição do basebol apareceu no distante 1744, na edição inglesa. Após 145 anos, os americanos apropriaram-se desta invenção, apesar dos factos.
A National League foi formada em 1876. Faz parte da Major League no Canadá e nos Estados Unidos. Hoje, existem 15 equipas na National Baseball League. Na parte final de cada temporada, chega a hora dos playoffs, na qual as 4 melhores equipas participam. Assim, é revelado o vencedor de toda a National League. Então, a equipa vencedora tem a oportunidade de jogar contra o vencedor da American League na World Series.
Está interessado em basebol ou até torce por uma das equipas? Então preste homenagem à sua equipa favorita, definindo os cursores do rato na forma dos seus atributos! Mude o aspeto aborrecido do ponteiro no navegador para a identidade corporativa familiar do basebol! Transforme a seta no taco ou capacete de um jogador em qualquer uma das equipas da National League, que já incluem o cursor New York Yankees, o cursor Great Falls Dodgers, o cursor Boston Red Sox, o cursor Baltimore Orioles, o cursor Oakland Athletics.',
    'mlb_teams_short_descr' => 'Colecção de cursores das equipas da MLB para todos os nossos fãs.',
    'mlb_teams' => 'Equipas da MLB',
    'brawl_stars_descr' => 'Brawl Stars é um jogo mobile do género MOBA da Supercell. Apesar do lançamento no final de 2018, o jogo ganhou grande popularidade, em grande parte devido à abundância de modos de batalha e heróis coloridos e fantásticos - os brawlers. O jogador tem muito por onde escolher - 32 personagens únicos e cada um deles tem o seu próprio conjunto de habilidades e competências. Cada herói também tem a sua própria habilidade passiva, que está disponível através de baús de espólio. Os jogadores podem lutar em vários modos, por exemplo, "Recompensa pela captura" - uma das duas equipas ganha, quem tiver recolhido mais estrelas, matando os oponentes. No modo "roubo", é necessário quebrar os cofres dos oponentes, mantendo os seus próprios. Um modo interessante de "Agarra Gemas" - a equipa torna-se a vencedora, a equipa que recolhe mais gemas ganha. Bem, no modo "Combate", 10 jogadores lutam entre si no mapa, onde as fronteiras são reduzidas devido a uma nuvem tóxica. O jogo é repleto de um design colorido que muitas pessoas gostam, incluindo nós, o que nos inspirou a criar uma coleção separada de cursores Brawl Stars. Existem o cursor Shelley do Brawl Stars, o cursor Barley, o cursor Penny, o cursor Frank, o cursor Mortis e outros.',
    'brawl_stars_short_descr' => 'Escolha cursores do Brawl Stars e deixe a batalha começar',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Mude o seu cursor do rato em dois cliques! Coleções gratuitas para todos os gostos.',
    'all_descr' => 'Se alguma vez pensou em como mudar um cursor do rato aborrecido, então as nossas coleções de cursores são para si! Aqui encontrará heróis de banda desenhada fixes, cursores bonitos para jogadores com personagens de jogos populares, conjuntos de cursores engraçados para partidas, cursores coloridos e muitas outras opções interessantes.',
    'text_title' => 'Coleções de cursores fixes e divertidas para todos os dias',
    'text_allcat_title' => 'Cursores de rato únicos e criativos para combinar com o teu humor',
    'text_1' => 'Não quer ser como toda a gente? Ou simplesmente adora tudo o que é invulgar? Quer fazer parte do seu herói de jogo ou personagem de desenho animado favorito? Então veio ao sítio certo. Aqui encontrará conjuntos de cursores brilhantes e invulgares que podem substituir a seta branca familiar e já bastante aborrecida. O cursor do rato acompanha-nos o dia inteiro no trabalho e no estudo, por isso deve dar um ótimo humor e preparar para o positivo.',
    'text_2' => 'Aqui encontrará cursores para jogadores e amantes de filmes, belos cursores baseados nos seus desenhos animados e motivos desportivos favoritos para as pessoas mais ativas. Gosta de banda desenhada ou não consegue imaginar um único dia sem memes engraçados? Adora animais ou sonha em visitar todos os países do mundo? Tudo é simples - também temos uma imagem de cursor adequada para si. Também pode selecionar imagens dependendo do que está a trabalhar. Por exemplo, um cursor preto será muito mais conveniente do que um branco ao trabalhar com documentos ou desenhos, e um cursor de mão será mais conveniente se tiver que trabalhar com pequenos elementos gráficos. Escolha a sua imagem favorita, ajuste o seu tamanho diretamente na extensão - e use-a com prazer, todos os dias começando com uma nota positiva!',
    'install_to_preview' => 'Por favor, instale a extensão para pré-visualizar',
    'install' => 'Instalar',
    'add_button' => 'Adicionar',
    'preview_button' => 'Pré-visualizar',
    'added_button' => 'Adicionado',
    'add_cursor' => 'Adicionar cursor',
    'to_your_collection' => 'à sua coleção',
    'prev_text_1' => 'Pré-visualização em ecrã completo',
    'prev_text_2' => 'cursor',
    'cursor' => 'cursor',
    'pointer' => 'ponteiro',
    'a_title_1' => 'Cursor Style - Cursores fixes para o seu navegador',
    'a_title_2' => 'Coleções fixes de cursores temáticos',
    'mouse_cursors' => 'Cursores do rato',
    'cursor_collection' => 'Coleção de cursores',
    'sborka_cursorov' => 'Coleção de cursores',
    'collection_list_from_colllection' => 'Lista de cursores - ',
    'christmas' => 'Natal',
    'nhl_teams' => 'Liga Nacional de Hóquei',
    'neon' => 'Neon',
    'adventure_time' => 'Hora de Aventuras',
    'nba_teams' => 'Associação Nacional de Basquetebol',
    'spongebob' => 'Spongebob',
    'phineas_and_ferb' => 'Phineas e Ferb',
    'fortnite_chapter_2' => 'Fortnite Capítulo 2',
    'pokemon' => 'Pokémon',
    'famous_people' => 'Celebridades',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Banda Desenhada',
    'igry' => 'Jogos',
    'multfilmy' => 'Desenhos Animados',
    'kino_i_serialy' => 'Filmes',
    'anime' => 'Anime',
    'futbol' => 'Futebol',
    'avtomobili' => 'Carros',
    'memy' => 'Memes',
    'emodji' => 'Emoji',
    'pitomcy' => 'Animais de Estimação',
    'stil_i_krasota' => 'Moda e estilo',
    'prazdniki' => 'Feriados',
    'flagi' => 'Bandeiras',
    'vokrug_sveta' => 'À volta do Mundo',
    'eda_i_napitki' => 'Comida e bebidas',
    'cvetnye' => 'Coloridos',
    'prank' => 'Brincadeiras',
    'startovyj_nabor' => 'Kit de Iniciação',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'O Pai Natal vai adorar os seus cursores de Natal',
    'nhl_teams_short_descr' => 'Uma coleção de cursores da NHL para fãs de verdade.',
    'neon_short_descr' => 'Adicione brilho com uma coleção neon.',
    'adventure_time_short_descr' => 'Aprender matemática com a coleção de cursores do Hora de Aventuras.',
    'nba_teams_short_descr' => 'Cursores da NBA como um símbolo de grandes vitórias no basquetebol',
    'spongebob_short_descr' => 'Descubra quem vive no fundo do mar com a coleção de cursores do SpongeBob',
    'phineas_and_ferb_short_descr' => 'Definitivamente não ficará aborrecido(a) com a coleção de cursores do Phineas e Ferb',
    'fortnite_chapter_2_short_descr' => 'O novo capítulo do jogo de culto Fortnite',
    'pokemon_short_descr' => 'Colecione todos se conseguir',
    'famous_people_short_descr' => 'Inspire o seu cursor num ídolo',
    'the_elder_scrools_short_descr' => 'Mergulhe no mundo de cavaleiros e dragões',
    'halloween_short_descr' => 'Tenha medo de perder a nova coleção de Halloween',
    'nfl_teams_short_descr' => 'Para verdadeiros fãs de futebol americano',
    'five_nights_at_freddy_short_descr' => 'Tente não se assustar com estes animatrónicos',
    'komiksy_short_descr' => 'Cursores de banda desenhada: escolha o seu estado de espírito hoje.',
    'igry_short_descr' => 'Realidade virtual: quem está a jogar hoje?',
    'multfilmy_short_descr' => 'As personagens de desenhos animados favoritas num novo design',
    'kino_i_serialy_short_descr' => 'O Senhor do Cursor: A Irmandade do Ambiente de Trabalho',
    'anime_short_descr' => 'Toda a gente gosta de anime: qual é a tua personagem favorita?',
    'futbol_short_descr' => 'És um verdadeiro fã de desporto? Então precisas de estar aqui',
    'avtomobili_short_descr' => 'O carro dos teus sonhos: uma grande frota para profissionais',
    'memy_short_descr' => 'Motivos favoritos: coleção de cursores de Memes',
    'emodji_short_descr' => 'Mostre o seu humor real aos outros - defina Cursoji!',
    'pitomcy_short_descr' => 'Cursores brilhantes para todos os amantes dos nossos irmãos mais peludos',
    'stil_i_krasota_short_descr' => 'Cursores originais para todas as ocasiões',
    'prazdniki_short_descr' => 'O que há no calendário? Nova coleção de cursores de feriados!',
    'flagi_short_descr' => 'À procura de aventura: para onde vamos hoje?',
    'vokrug_sveta_short_descr' => 'À volta do mundo num instante: para onde vamos hoje?',
    'eda_i_napitki_short_descr' => 'Cursores de dar água na boca para a criatividade',
    'cvetnye_short_descr' => 'Pinte a sua vida com cores vibrantes e traços arrojados',
    'prank_short_descr' => 'Um conjunto de cursores para as partidas mais divertidas.',
    'startovyj_nabor_short_descr' => 'Um novo olhar sobre coisas familiares: uma série de cursores atualizada.',
    'fortnite_short_descr' => 'Siga os streamers!',
    'dota_2_short_descr' => 'Torne o seu mundo virtual real!',
    'minecraft_short_descr' => 'As personagens do seu jogo favorito estão sempre por perto',
    'christmas_descr' => 'Cada um de nós está, sem dúvida, à espera da festa mais popular - o Natal. Todos os cristãos do mundo tradicionalmente celebram-no todos os anos, a 25 de dezembro. Uma época em que as famílias se reúnem à mesma mesa, partilham a sua alegria e amor e trocam presentes. Muito antes do Natal, as pessoas decoram as ruas com grinaldas brilhantes e as suas casas com atributos tradicionais. É difícil encontrar uma pessoa que não goste do Natal - uma festa divertida e misteriosa, porque é acompanhada por muitas tradições e rituais, que nos remetem às raízes de toda a nossa família. Na véspera de Natal, literalmente tudo está saturado com o seu espírito, desde o pão de gengibre pintado até aos cânticos tocantes. Uma elegante árvore de Natal e presentes por baixo dela, uma alegria familiar a cada um de nós desde a infância. Queremos juntar-nos a esta festa mágica e, quem sabe, talvez o Pai Natal prepare um presente especial para si se decorar o seu cursor com a nossa coleção de Natal. Há tudo o que precisa para isso, o cursor do Pai Natal, o cursor da árvore de Natal, o cursor do pão de gengibre, o cursor do Boneco de Neve e até o cursor do saco de presentes. Feliz Natal!',
    'nhl_teams_descr' => 'A Liga Nacional de Hóquei foi formada em 1917 - é uma organização desportiva profissional que reúne clubes de hóquei dos EUA e do Canadá. E esta é uma das primeiras ligas profissionais de hóquei do mundo. A NHL é uma das principais ligas desportivas da América do Norte, juntamente com a NFL, NBA, Major League Baseball e MLS. Todos os anos, 31 equipas de 30 cidades dos EUA e do Canadá lutam pelo troféu principal - a Taça Stanley, e a equipa que marcou mais pontos na época regular recebe a Taça Presidencial. É hora de honrarmos este grande jogo criando uma coleção de cursores da NHL. Se também gosta de hóquei, torça pelo seu clube favorito ou participe neste desporto, basta mudar o cursor e não se separar da sua equipa favorita, incluindo o cursor dos Boston Bruins, o cursor dos St. Louis Blues, o cursor dos Columbus Blue Jackets, o cursor dos Tampa Bay Lightning, o cursor dos Dallas Stars e outros clubes dignos de sincero respeito.',
    'neon_descr' => 'Criámos uma coleção única de cursores neon para adicionar variedade ao navegar na internet diariamente e adicionar um pouco de brilho às hipnotizantes luzes de néon. Deixe que as suas cores ricas criem a atmosfera envolvente da cidade à noite, dando inspiração para criar algo novo. No mundo moderno, as luzes de uma metrópole anunciam sempre o início da noite, seguem-nos em cada rua e este brilho é preenchido de energia. Que seja também seguido por um cursor de gelado brilhante, um cursor de cachorro-quente delicioso, um cursor de hambúrguer suculento, um cursor de diamante cintilante e outros cursores da nova coleção neon.',
    'adventure_time_descr' => '"Adventure Time" é uma série de desenhos animados de um género fantástico em que a ação decorre num mundo que sobreviveu ao apocalipse. Este território é chamado Terra de Ooo, que até recentemente foi palco de uma guerra nuclear. Mas tudo isto já passou, no entanto, todas as pessoas sobreviventes foram sujeitas a mutações, e o mundo encheu-se de magia. As personagens principais da série animada são Finn, um rapaz de 14 anos e o seu amigo, um cão chamado Jake. O rapaz e o cão adoram aventura, ajudam constantemente todos os que estão em apuros. Os amigos vivem numa árvore e passam todo o seu tempo juntos. Se quer mergulhar num mundo de aventura com outros admiradores, então grite "Matemática". Aqui estão o cursor do rapaz Finn e o cursor do Jake, bem como o cursor da Princesa Chiclete. Claro que não nos esquecemos do cursor Bimo, do cursor do Rei Gelado e outros.',
    'nba_teams_descr' => 'Se o basquetebol é o teu jogo favorito, como é para nós, então uma coleção de cursores dedicados às equipas da NBA é o que precisas. A NBA é uma das principais associações desportivas do continente americano. Quando criámos esta coleção, fomos atormentados pela escolha - que equipa escolher, porque há trinta delas na NBA. Mas existem equipas que são lendas. Esta e os Chicago Bulls, estabeleceram um recorde de vitórias em meados da década de 90. Estes são os Golden State Warriors, que reuniram os melhores jogadores da liga há alguns anos. Ou, por exemplo, os Lakers, os Celtics também são equipas incrivelmente fixes. Se, como nós, estás ansioso pelos jogos das tuas equipas de basquetebol favoritas e queres mostrar o teu apoio à equipa ou aos jogadores, transfere a nossa coleção de cursores da NBA.',
    'spongebob_descr' => 'A série animada "SpongeBob SquarePants" é conhecida por tantas pessoas. Foi um sucesso esmagador depois que a Nickelodeon decidiu, em 1999, criar uma série animada baseada na tira de banda desenhada educativa Tide Zone, e transformou-se numa franquia muito lucrativa. O criador da série é um ex-funcionário do laboratório oceanológico, e é por isso que quase todas as personagens da série animada são habitantes engraçados do fundo do mar, com as suas próprias características e carisma. A ação gira em torno da receita secreta de Krabsburger que só a personagem principal pode cozinhar - Sponge Bob. E os outros habitantes do mar estão a tentar obtê-la, incluindo o principal anti-herói Sheldon Plankton, que não consegue obtê-la todas as vezes. Na coleção de cursores SpongeBob, reunimos os cursores de todas as personagens e eventos notáveis da série. Por exemplo, o cursor do Sr. Krabs com o dólar, o cursor do Patrick Star, o Squidward com a sua clarinete, o cursor da alforreca, o cursor do Sponge Bob e muitas outras personagens.',
    'phineas_and_ferb_descr' => 'Na cidade americana fictícia de Denville, do inexistente Trishtatya, vivem dois rapazes interessantes. Cada dia das suas férias transforma-se em aventuras incríveis, porque conseguem construir uma montanha-russa do tamanho de uma cidade inteira ou um portal real para outro planeta. Partilham o seu entretenimento incrível com os amigos. Ao mesmo tempo, enquanto os rapazes se divertem, o cientista malvado Heinz Fufelschmertz está a construir outra máquina maligna que cria caos, com o nome a terminar em "-inator", com a ajuda da qual quer vingar as suas mágoas de infância ou tomar o poder em Trishtat, mas Perry está a impedi-lo - Utkonos, o secreto "Agente Pi", a trabalhar sob o disfarce do animal de estimação dos rapazes. A popularidade desta série animada, tanto entre crianças como entre adultos, inspirou-nos a criar uma coleção de cursores Phineas e Ferb para que possa alterar o seu cursor do rato nas personagens da série. Entre eles estão o cursor Phineas Flynn, o cursor Dr. Heinz Fufelschmertz, o cursor Ferb Fletcher, o cursor Candace Gertrude Flynn e o cursor Perry, o ornitorrinco.',
    'fortnite_chapter_2_descr' => 'O segundo capítulo do Fortnite veio após um grande evento - The End, que arrastou tudo o que os jogadores do jogo amavam para um buraco negro. O Fortnite Capítulo 2 agora tem um novo mapa, que à primeira vista é ainda mais selvagem do que o mapa original, bem como muitas mudanças na mecânica do jogo e, claro, muito novo conteúdo do jogo! Veículos, emoções, mecânicas de natação e muito mais - tudo isto em imagens frescas e interessantes, tudo como você ama e aprecia neste jogo de culto. Mergulhe em um novo mundo - escolha um local de aterrissagem e explore uma ilha completamente nova com 13 locais. Natação, pesca, barcos a motor - esta é uma nova jogabilidade aquática. Mais diversão e menos esforço - atualize um capítulo 2 completamente novo e não se esqueça de mudar o cursor para novas skins e armas. Você já está esperando pelas skins atualizadas Turk cursor, Riptide cursor, Rippley cursor, Remedy cursor, Toxin cursor, 8-Ball cursor, Fusion cursor e outros!',
    'pokemon_descr' => 'A palavra "pokemon" significa uma criatura com poderes sobrenaturais. Eles têm inteligência, e alguns deles são até capazes de falar. Atualmente, existem já 802 variedades de Pokémon. No universo Pokémon inventado, as pessoas são chamadas de treinadores Pokémon, que treinam para batalhas com os Pokémon de outros treinadores. E quanto mais experiente e forte for o treinador, mais respeito ele desfruta. Felizmente, deve-se notar que as lutas Pokémon nunca terminam com a morte dessas criaturas únicas. Todos os Pokémon têm diferentes habilidades e diferem no tipo de elemento, e a sua resistência a diferentes ataques depende fortemente disso, e algumas criaturas têm a capacidade de dois elementos de uma vez. Após vencer a batalha, o Pokémon recebe a valiosa experiência que é necessária para aumentar o nível e, consequentemente, as suas características. Hoje, o universo Pokémon é uma enorme franquia de mídia e decidimos preparar para si uma coleção de cursores com alguns Pokémon populares. Entre eles, o mais famoso é o cursor Pikachu, bem como o cursor Rattata, o cursor Squirt, o cursor Bulbasaur e o cursor Charmander. Esta lista será atualizada, porque existem tantos deles e cada um deles é único à sua maneira.',
    'famous_people_descr' => 'Entre as muitas pessoas famosas, cada um de nós encontra um modelo ou simplesmente admira o génio, o talento e a perseverança destas celebridades. Preparamos uma coleção de cursores de celebridades para o inspirar e lembrá-lo das grandes conquistas que cada um de vós pode aumentar. Nem todas as personalidades famosas tiveram um destino feliz, mas ensinam-nos o principal: que nunca precisa de recuar do seu objetivo almejado, apesar das dificuldades e problemas. Afinal, este é o princípio fundamental para alcançar o sucesso - ir em direção ao seu sonho todos os dias e, finalmente, tornar-se o melhor na sua área. Talvez hoje só queira mudar o cursor do rato e amanhã toda a sua vida mudará para melhor! A coleção será constantemente atualizada com novos e dignos representantes da humanidade. Entre eles, claro, cientistas, políticos, atletas, representantes da arte e muitos outros. O cursor George Washington, o cursor Michael Jordan, o cursor Stephen King, o cursor Elvis Presley e o cursor Marilyn Monroe são apenas o começo.',
    'the_elder_scrools_descr' => 'The Elder Scrolls é uma série de jogos de role-playing para computador, unidos por um universo comum, meticulosamente projetado, que oferece ao jogador uma enorme liberdade de escolha, permitindo-lhe visitar diferentes áreas e cidades do mundo de fantasia e explorar novos locais e missões por conta própria. O trabalho na série começou em 1992 e, ao longo dos anos, o jogo uniu uma enorme comunidade de jogadores em torno de si. Portanto, a pedido popular, lançamos uma coleção de cursores The Elder Scrolls, para que possa mergulhar na atmosfera única do jogo. A eterna batalha de cavaleiros e dragões, de que lado está você? Mude o cursor para um dragão e junte-se ao exército de monstros que cospem fogo ou lute nobremente do lado das pessoas, escolhendo o cursor da espada e a imagem do seu personagem favorito - a decisão é sua! O principal é que, com a nossa nova coleção, está pronto para qualquer batalha.',
    'halloween_descr' => 'À espera de uma noite mística na véspera do Dia de Todos os Santos. A história do Halloween remonta há mais de dois mil anos. Talvez esta seja a festa mais estranha, combinando diversão e medo, nativa da cultura Celta. Naquela época, as pessoas queimavam fogueiras e usavam fantasias assustadoras para afastar fantasmas. A palavra "Halloween" foi mencionada pela primeira vez no século XVI como uma abreviação escocesa da frase inglesa All-Hallows-Even. O Papa Gregório III declarou o dia 1 de novembro como Dia de Todos os Santos, e a noite anterior era conhecida como Véspera de Todos os Santos, e mais tarde Halloween. Neste dia, as pessoas usam fantasias de lobisomens, fantasmas e outros monstros e vão às casas vizinhas, oferecendo-se para comprar doces. Festas temáticas, fogos de artifício, belas lanternas, abóboras e acrobacias criam uma atmosfera única. Também queremos celebrar esta festa terrível com cursores de acessórios e personagens de Halloween. Na nossa coleção pode encontrar: cursor de zombie, cursor de fantasma, cursor de gato preto, cursor de abóbora e muito mais. Mudar o seu estado de espírito é agora tão fácil quanto mudar o seu cursor com a nossa nova coleção de Halloween.',
    'nfl_teams_descr' => 'O que poderia ser melhor para um verdadeiro fã de futebol americano do que um cursor do rato em forma de simbolismo da equipa pela qual é fã? Na moderna Liga Nacional de Futebol, trinta e duas equipas jogam, divididas entre as Conferências Nacionais e Americanas de Futebol (Conferência Nacional de Futebol, NFC e Conferência Americana de Futebol, AFC). Por sua vez, cada uma das conferências é dividida em quatro divisões: Leste, Norte, Sul e Oeste. A época da NFL consiste em jogos de pré-época, uma época regular e uma série de jogos de playoffs. A partida final da época da NFL é chamada de Super Bowl e é essencialmente o evento desportivo mais popular dos Estados Unidos. Este é um jogo favorito para milhões de fãs e, portanto, criámos uma coleção de cursores da NFL para que não se separe dos símbolos da sua equipa favorita. Sejam os New England Patriots, New York Giants, Buffalo Bills ou outra equipa, esteja sempre na mesma onda que os seus ídolos, usando os nossos cursores em forma de logótipo e capacete da equipa. A coleção será constantemente atualizada para que todos possam mudar o cursor para a imagem da sua equipa favorita.',
    'five_nights_at_freddy_descr' => 'O jogo verdadeiramente único Five Nights at Freddy\'s rapidamente ganhou grande popularidade e isso não é surpreendente, porque sua trama simples e, ao mesmo tempo, fascinante pode manter os jogadores nas telas por horas. Desenhámos os cursores Five Nights at Freddy\'s a pedido dos fãs do jogo e ficámos muito satisfeitos por incorporar personagens tão interessantes e engraçadas. Mas, ao contrário do jogo, nada o ameaça com os nossos cursores, por isso, sinta-se à vontade para escolher os seus animatrónicos favoritos, seja o Urso Freddy ou o Coelho Bonnie ou outros. O principal é que agora o jogo ganha vida no seu navegador e dá novas emoções. Garantimos que não há fantasmas nos nossos cursores, mas eles transmitem perfeitamente o espírito de um jogo que inspira medo devido às complexidades do design e elementos da trama. Mas e se aumentar muito o tamanho do cursor? Consegue manter a calma e não se assustar?',
    'komiksy_descr' => 'Poderia parecer que o cursor do rato é uma trivialidade, mas muitas vezes são esses detalhes que podem melhorar o seu humor, acordá-lo na manhã cinzenta ou simplesmente dar emoções brilhantes. Uma coleção de cursores de banda desenhada projetados especificamente para todos os amantes de super-heróis. Aqui você pode encontrar absolutamente todo o Universo Marvel e DC Comics - de Homem de Ferro a Thanos, Homem-Aranha e Hulk. O estilo do cursor pode estar na forma de um super-herói, ou na forma do seu personagem. Um cursor não é apenas um elemento funcional; é importante em um sentido profissional. Por exemplo, se você está gravando um vídeo da tela, será melhor ver uma imagem brilhante e original, e parece muito mais interessante. E claro - quem não gostaria de usar a manopla do infinito na vida real? Mudar o cursor do rato é simples - basta baixar a extensão para o seu navegador e adicionar o cursor que você gosta às suas configurações através dela. Você pode escolher um cursor de acordo com seu humor pelo menos todos os dias. Chega de dias cinzentos - torne-se um super-herói agora mesmo!',
    'igry_descr' => 'Os jogos de computador tornaram-se há muito tempo parte integrante das nossas vidas. Com eles, pode mergulhar num novo mundo, participar em aventuras e tornar-se uma pessoa completamente diferente. Cada um tem o seu brinquedo favorito, cujas personagens já se tornaram quase da família. Um conjunto de cursores com base em jogos de computador bem conhecidos é uma oportunidade para diluir a aborrecida vida quotidiana e adicionar um pouco de criatividade, brilho e diversão ao fluxo de trabalho. O conjunto contém imagens dos próprios heróis do jogo, bem como personagens auxiliares, armas e ícones do jogo. Escolha o que se adapta ao seu estado de espírito - os cursores de jogo atrairão não só os jogadores, mas também todos aqueles que estão simplesmente cansados da vida quotidiana cinzenta. Basta descarregar o conjunto, mudar o cursor do rato - e pronto, para completar as tarefas da missão, destruir os inimigos e atingir os seus objetivos.',
    'multfilmy_descr' => 'Dentro de cada adulto ainda existe uma criança que adora desenhos animados e ainda sonha em se tornar um dos heróis. Vamos ajudar a realizar seus sonhos - use a nova coleção de cursores baseada nos desenhos animados mais famosos e adorados. Tom e Jerry, Buzz Lightyear e Shrek, Gravity Falls e até Pokemon - você pode se tornar o que quiser todos os dias. Selecione o cursor do mouse de acordo com seu humor. Quem é você hoje? Um minion imprudente e alegre que resolve facilmente qualquer problema ou um Rafael forte e corajoso, cujo objetivo não é apenas realizar feitos, mas também comer pizza? Talvez você seja o gênio todo-poderoso que comanda um escritório inteiro? Na coleção, existem heróis para todos - de princesas a dragões - resta apenas decidir quem reflete o humor de hoje. O Cursor Style não é apenas uma imagem brilhante. Esta é uma reflexão da individualidade, autoexpressão e simplesmente - diversão, alegria e positividade para o dia todo. Está entediado no trabalho ou com preguiça de estudar? Ficou triste e não está feliz? Mude o cursor e o mundo brilhará com novas cores.',
    'kino_i_serialy_descr' => 'Filmes - são magia, misticismo e apenas uma ótima maneira de relaxar, se divertir e obter emoções vívidas. Ao mesmo tempo, depois de assistir, ainda nos lembramos dos heróis favoritos que realmente queremos conhecer na realidade. Agora é possível - basta baixar a nova coleção de cursores baseada em filmes e programas de TV famosos. Cursores brilhantes e legais serão uma ótima adição à área de trabalho, transformam a monótona vida cinzenta em um feriado e tarefas banais em uma aventura emocionante. Mude o herói do cursor todos os dias - para humor, tarefas ou aleatoriamente. Quem você será hoje? O honesto e justo John Snow ou o ousado e implacável John Wick? Talvez você tenha uma missão difícil pela frente e apenas Frodo possa concluí-la? Talvez hoje você seja apenas um alienígena que não quer fazer contato com os outros? Escolha um cursor adequado - levante o seu ânimo e, ao mesmo tempo, mostre aos outros o que você pensa e como planeja passar o seu dia. Experimente - não é apenas divertido, mas também viciante - você definitivamente não vai querer voltar para a seta usual.',
    'anime_descr' => 'Anime é um estilo único de animação que, apesar da sua etnicidade pronunciada, tem sido apreciado por milhões de pessoas em todo o mundo. É improvável que haja pelo menos uma pessoa que não tenha assistido a desenhos animados neste estilo. Criámos os cursores de estilo anime mais fixes que todos os fãs deste estilo vão adorar. Os cursores padrão são aborrecidos e banais. Mostre a sua personalidade - use a coleção de cursores Anime com as suas personagens favoritas. Escolha o cursor de uma espada escura se sonha com aventura e batalhas corajosas. O fofo Totoro vai alegrá-lo mesmo no dia mais triste, e Naruto irá motivá-lo nas aventuras e mostrar a todos à sua volta que você é super fixe. Os cursores brilhantes vão alegrar o dia de trabalho ou tornar o processo de aprendizagem mais interessante e agradável. Não se limite - use os seus motivos favoritos mesmo em pequenos elementos como o cursor do rato. Mude os cursores todos os dias, ajuste-os ao seu humor e mostre a sua personalidade - com os cursores de estilo anime é assim tão simples.',
    'futbol_descr' => 'Futebol é um desporto especial que inclui elementos de luta livre, atletismo e precisão. Em geral, é espetacular e implacável, reunindo milhões de fãs em todo o mundo. Gosta de futebol ou apenas adora desporto? Então, descarregue um conjunto de cursores no estilo do jogo mundialmente famoso e prove o título de fã leal. A coleção contém 24 opções para design de cursores – na forma das equipas mais populares que merecem os seus títulos como um jogo desesperado e persistente. Os cursores são feitos em duas versões – na forma de um triângulo padrão, decorado com as cores da equipa, ou na forma de um capacete correspondente ao jogo. O cursor padrão do navegador é aborrecido e não digno de um verdadeiro fã de desporto. Torne-se original e único com a nossa coleção. Descarregue imagens e escolha as cores da sua equipa favorita ou cursores personalizados, se apenas adora desporto e torce por todos. Seguir os seus hobbies é tão simples – não precisa de ir trabalhar com um cachecol ou boné da sua equipa favorita, é rápido e fácil mudar o cursor para uma imagem brilhante e com estilo.',
    'avtomobili_descr' => 'Gosta de carros e de admirar modelos de diferentes fabricantes? Ou sonha com uma marca em particular há muito tempo, mas ainda não tem oportunidade de a comprar? Especialmente para si, criámos um conjunto de cursores brilhantes "Supercarros". Aqui encontrará Ford clássicos e Bentley elegantes, Lamborghini brilhantes e Ferrari únicas. Quer tornar-se o proprietário do carro original? É simples - descarregue a nossa coleção de cursores para o seu dispositivo e altere a imagem do carro pelo menos todos os dias. Os cursores são projetados em duas versões - como um carro completo ou como o seu símbolo. Escolha o que mais gosta ou como prefere trabalhar. Tais imagens ficarão ótimas como cursores de jogos ou simplesmente como um elemento incomum da área de trabalho. Ser brilhante é simples - não é necessário fazer coisas inimagináveis ​​para isso ou mudar a sua aparência. Basta parar de usar objetos comuns e escolher o que realmente gosta. A coleção de cursores "Carros" é a escolha para quem não tem medo de se mostrar.',
    'memy_descr' => 'Os memes são há muito tempo uma parte familiar das nossas vidas. E quem de nós não gosta destas imagens espaçosas, interessantes e originais para desafiar o dia? Muitos heróis dos memes tornaram-se não apenas populares - adquiriram o estatuto de favoritos populares, e frases e expressões foram incluídas no discurso coloquial como expressões bem estabelecidas. Apresentamos uma coleção dos melhores cursores baseados nos memes mais populares. Com a sua ajuda, pode não só mostrar a sua personalidade, mas também expressar o seu humor. Está tudo cansado e farto de tudo? Escolha um gato zangado que, com toda a sua aparência, expressa indignação e hostilidade a tudo à sua volta. Ou hoje brilha com sarcasmo e não se importa de rir? Então Drake Bling será um excelente acompanhamento - vai animá-lo e tornar qualquer tarefa original e interessante. Instale a extensão, descarregue a nossa coleção - e escolha um estilo de cursor para todos os dias. Não é difícil ser brilhante e original - mude o design padrão do ícone para um dos heróis dos memes e obtenha uma injeção de energia para todo o dia.',
    'emodji_descr' => 'Emoji - ícones brilhantes e fixes, sem os quais já não conseguimos comunicar habitualmente. Com a sua ajuda, não precisa de descrever o seu humor em palavras - basta selecionar o ícone desejado e o interlocutor entende-o sem mais delongas. No nosso novo conjunto de cursores, incorporámos a ideia de emoji - foi assim que apareceram os engraçados e invulgares Cursoji que vão colorir o mundo e tornar a vida mais interessante. Com a ajuda dos cursores, pode não só trabalhar e realizar tarefas familiares, mas também mostrar aos seus colegas, amigos e simplesmente aos outros, o seu humor. Um cursor sonolento é perfeito para a manhã de segunda-feira, e um cursor a chorar vai expressar uma atitude em relação a responsabilidades adicionais. Um cursor fixe com óculos é a melhor escolha antes das férias, e um cursor com dólares nos olhos é uma boa razão para insinuar ao chefe o aumento salarial. Usar Cursoji é divertido e interessante - seja no trabalho, estudo ou apresentação. Neste último caso, é mesmo recomendado fazê-lo se os colegas tiverem sentido de humor ou simplesmente precisarem de descontrair a situação. No geral, para qualquer tarefa - basta escolher o curso certo!',
    'pitomcy_descr' => 'Gosta de animais? Certamente - eles são tão fofos, engraçados e muito divertidos. Porque não passar o dia inteiro acompanhado pelos melhores amigos do homem? Descarregue a coleção de cursores de Animais de Estimação e escolha um amigo para si todos os dias. O ícone do cursor pode ser fofo, como uma alpaca bondosa, ou elegante, como um flamingo cor-de-rosa. Ou talvez esteja ocupado o dia todo e escolha um unicórnio a ler um jornal, ou simplesmente não queira comunicar com ninguém, como um gato preto malvado? Para qualquer estado de espírito, temos um animal correspondente. Um pug alegre vai animá-lo mesmo no dia mais aborrecido e cinzento, e o cursor rosa em forma de unicórnio vai mostrar a todos que não está isento de um sentido de beleza, mesmo sendo um homem barbudo e brutal. E se não houver disposição e não tiver vontade de fazer tarefas rotineiras? A receita é simples - descarregue a coleção de Animais de Estimação, altere o cursor do rato - e pronto, o sol está a brilhar de novo, o tempo está bom e o humor está ao mais alto nível. Não admira que digam que os animais ajudam a combater a depressão e a tristeza!',
    'stil_i_krasota_descr' => 'Na nova coleção de cursores, reunimos uma grande variedade de temas que nos causam emoções agradáveis e elevação. Este conjunto de cursores chama-se “Estilo e Beleza”, porque são as suas coisas favoritas que determinam o nosso dia a dia, dão alegria e motivam-nos a fazer coisas importantes, despertando o desejo de progresso. Gosta do espaço e sonha ir para outros planetas? Escolha um cursor da NASA ou um prato de extraterrestres - aproxime-se do seu sonho. Se não consegue imaginar a vida sem música ou é um roqueiro inveterado, então o cursor no estilo de uma guitarra elétrica é para si. O cursor de pincel, régua e compasso foi especialmente desenvolvido para engenheiros - essas imagens ajudarão a transformar cálculos e desenhos aborrecidos em soluções originais. Uma varinha mágica e ténis, um skate e batom, o sol e cones químicos - escolha o que se adapta ao seu estilo de vida, aos seus desejos e aspirações - e as tarefas normais tornar-se-ão mais interessantes, e os dias de trabalho serão pintados com novas e brilhantes cores.',
    'prazdniki_descr' => 'Gosta de feriados? Mas quem não gosta deles - amigos, presentes, de novo o mesmo fim de semana. Para tornar a espera pelos feriados mais agradável, mais curta e mais quente, pode não só contar os dias no calendário, mas também definir o ícone correspondente como o cursor do rato. Vamos começar com o Ano Novo - vamos escolher uma árvore de Natal, um presente ou o Pai Natal, para que a festa seja brilhante e alegre. Talvez o homem de gengibre esteja mais perto - engraçado, fofo e sempre alegre? Com ele, certamente não haverá tempo para ficar triste e aborrecido. Continuamos a celebrar com cupidos e corações alegres, e não falta muito para o Coelho da Páscoa. Algures entre os feriados, haverá um aniversário, que será ainda mais agradável de esperar com balões em vez da seta do cursor padrão. E no Halloween, pode surpreender os colegas e aqueles que o rodeiam com um cursor de rato invulgar em forma de abóbora ameaçadora ou um fantasma. Um conjunto de cursores para os feriados é uma oportunidade para alegrar a expectativa, sintonizar-se com antecedência para a diversão que se avizinha e manter um excelente estado de espírito não só na véspera da celebração, mas durante todo o ano.',
    'flagi_descr' => 'A bandeira é um símbolo único que é amplamente utilizado em todas as redes sociais. Pensámos, porque não transformar o cursor numa bandeira? Afinal, é realmente brilhante e incomum. Agora pode passar todos os dias em companhia de um novo país, e o trabalho não será tão monótono e aborrecido. Os cursores do rato podem agora ser transformados na bandeira nacional da China ou dos EUA, Japão ou Canadá, e em outras 38 opções de bandeira, e pode escolher entre a forma de seta padrão numa cor incomum ou o cursor em forma de bandeira em si. Este conjunto apelará a todos os amantes de viagens. Com ele, pode planear novas viagens e sonhar com longas jornadas. Planeou umas férias? Mostre a todos para que país quer ir. Talvez tenha decidido aprender uma nova língua estrangeira? Então este cursor irá definitivamente apoiá-lo e motivá-lo a estudar cuidadosamente. Ou, como Sheldon, adora bandeiras? Em todos os casos, a coleção de cursores Flags será uma ótima adição ao seu ambiente de trabalho e irá movê-lo para novas descobertas.',
    'vokrug_sveta_descr' => 'Toda a gente gosta de viajar. Que maravilha é visitar novos países e cidades, ver os pontos turísticos e divertir-se na nova cultura. É pena que não possamos viajar com tanta frequência, mas tentámos resolver isso. O conjunto de cursores "À Volta do Mundo" é uma coleção das imagens mais marcantes, símbolos de diferentes países, com a ajuda dos quais, mesmo sentado em casa, pode sentir-se como um verdadeiro viajante. No nosso kit, pode encontrar o Japão e a Austrália, a Itália e o Canadá, os EUA e o México - os países mais interessantes, originais e pitorescos do mundo. A imagem do cursor pode tornar-se uma seta padrão, nas cores da bandeira do país, ou tornar-se numa das principais atrações do estado. Por exemplo, pode abrir documentos com a Torre Inclinada de Pisa e fazer apresentações usando a Estátua da Liberdade. Garantimos - o sucesso será garantido. Bem, ou se não o sucesso, então os sorrisos dos colegas e o reconhecimento da originalidade - com certeza. Sim, e insinuar à gerência que é hora de ir de férias também será útil - basta definir a mala ou o avião como cursor - e muito provavelmente estará a voar muito em breve.',
    'eda_i_napitki_descr' => 'Um conjunto de cursores em forma de produtos é uma coleção incrível de imagens brilhantes, saborosas e de dar água na boca que todos certamente vão gostar e que será uma ótima adição ao navegador. Já clicou em brócolos ou batatas fritas? Tem essa oportunidade - basta descarregar um novo conjunto de cursores e defini-los em vez de uma seta branca aborrecida. Os cursores "Comida" são feitos tanto na forma de um ponteiro triangular padrão, como na forma de produtos. Aqui encontrará vegetais e frutas, os seus pratos favoritos, como pizza ou cachorros-quentes, café, rebuçados e muito mais, o que anima qualquer dia. Adora café, mas beber o dia todo não é assim tão bom? Complemente a sua dieta com café virtual, que também o revigorará e acordará, além de dar emoções vívidas. Um cursor íngreme em forma de um donut virtual não prejudicará a figura, enquanto dá emoções vívidas e anima. Pode usar os seus cursores favoritos ou mudar a imagem todos os dias - uma grande seleção de cursores ajudará a colorir a vida cotidiana e adicionar novas cores às ações familiares.',
    'cvetnye_descr' => 'O cursor é o elemento principal do navegador, com o qual passamos todo o dia de trabalho, estudo, comunicação e lazer. A visualização padrão do cursor é aborrecida e até um pouco deprimente, mas ainda assim, para muitas pessoas, esta forma é conveniente, e mudá-la será desconfortável. Mas para esta situação, temos uma solução - um conjunto de cursores em cores brilhantes e alegres que adicionarão variedade ao seu dia a dia e tornarão a resolução de quaisquer problemas mais fácil e rápida. Se está a pensar em como mudar a cor do cursor, respondemos - descarregue a nossa coleção e escolha soluções brilhantes para todos os dias! Pode escolher tons monocromáticos em diferentes cores para se adequarem ao seu humor ou às especificidades do trabalho. Por exemplo, ao trabalhar com documentos padrão, um cursor roxo destacará-se em relação ao fundo e, num fundo escuro, pelo contrário, será mais fácil trabalhar com cursores amarelos. Se deseja uma explosão de cor, brilho e originalidade máxima - escolha um cursor arco-íris que inclui todas as cores do espectro - com este ícone, o humor estará definitivamente bom durante todo o dia.',
    'prank_descr' => 'As piadas no trabalho nem sempre são bem-vindas, pois muitas vezes interferem no fluxo de trabalho. Mas com o novo conjunto de cursores “Pranks”, pode pregar uma partida aos seus colegas ou amigos sem prejudicar o seu trabalho ou estudo. Desenvolvemos uma coleção especial que irá divertir qualquer pessoa e dar uma razão para relaxar um pouco em meio ao processo agitado de trabalho ou execução de outra tarefa. Para alterar o cursor do rato, basta descarregar o kit para o dispositivo e selecionar o design que deseja nos parâmetros. Por exemplo, pode obter um cursor com uma forma padrão, mas em estado invertido ou uma seta curvada por uma onda. Esta forma não irá de forma alguma impedir o processo de trabalho, mas ao mesmo tempo irá apresentar um humor maravilhoso e colocá-lo num estado de espírito positivo. Altere as configurações de exibição do cursor de acordo com o seu humor ou todos os dias - e qualquer tarefa se tornará mais interessante e agradável, e a vida cotidiana deixará de causar emoções negativas. Além disso, esses cursores podem ser usados ​​até mesmo para projetos sérios - eles têm cores neutras e não se destacam da área de trabalho.',
    'startovyj_nabor_descr' => 'Os cursores da coleção inicial são uma mistura de formas e tamanhos padrão com um visual brilhante e incomum. Esta é uma excelente escolha para quem prefere as formas habituais, mas quer trazer diversidade, originalidade e vivacidade para o dia a dia. A coleção tem um cursor de mão e uma seta familiar em uma variedade de variações - do logotipo do Google Chrome a emoticons, você pode até encontrar aqui um dragão há muito esquecido com cactos e nostalgia. Provamos que um cursor padrão também pode ser interessante e atraente. Diferentes cores, formas, texturas e design interessante ajudarão você a escolher o cursor ao seu gosto ou alterá-lo todos os dias, dependendo do humor ou das tarefas realizadas. Mudar os cursores do navegador é muito simples - basta instalar a extensão e baixar a coleção para o seu dispositivo. Cursores engraçados e interessantes não apenas colorirão os dias de trabalho, mas também, por exemplo, ajudarão a tornar qualquer apresentação mais interessante e, com a ajuda de cursores especialmente brilhantes, também chamarão a atenção para elementos individuais do relatório.',
    'fortnite_descr' => 'Fortnite conquistou milhões de pessoas em todo o mundo. Batalhas emocionantes, estratégia e táticas, aventuras - absorveu absolutamente tudo o que os jogadores tanto gostam. Não pudemos ficar de fora e desenvolvemos um conjunto de cursores ao estilo do jogo que irá agradar não só aos jogadores ávidos, mas até mesmo àqueles que ouviram falar do Fortnite pela primeira vez. O ícone do cursor Fortnite é uma imagem de um herói ou da sua arma, trabalhada até ao mínimo detalhe. Aqui pode encontrar imagens de raposas e peixes, máscaras de inferno e cavaleiros negros, definir uma flecha ou uma foice com picos como seta. Temos a certeza de que ninguém ficará indiferente! Ser assustador ou misterioso, original ou humorístico - depende de si. Escolha o seu estilo e siga-o ou defina cursores personalizados nas configurações e mude a sua função todos os dias. Agora, vai tornar-se muito mais interessante e agradável realizar até mesmo trabalho tedioso e monótono - o tempo passará rapidamente na companhia de imagens vívidas e personagens favoritos. Ou talvez organize competições com colegas, qual herói será mais forte? A escolha é sua!',
    'dota_2_descr' => 'DotA2 agora não é apenas um jogo simples, é um mundo paralelo real. Na realidade virtual em DotA2, pode fazer tudo - viver, lutar, desenvolver, viajar, fazer amigos. Em geral, tudo como na vida, só que por vezes mais interessante. Os cursores Dota 2 são uma continuação de uma estratégia que lhe permitirá obter emoções vívidas e expressar-se no mundo real. Um novo conjunto de cursores inclui as personagens mais marcantes do jogo, bem como itens originais que não podem ser confundidos com mais nada. Escolha um cursor que esteja mais próximo de si - e embarque numa aventura sem sair do seu local de trabalho. Como é aborrecido, por vezes, estar no trabalho ou realizar tarefas educativas, mas com os cursores do jogo este problema não se confrontará mais consigo. Um pouco de imaginação, um cursor brilhante - e pronto, qualquer negócio será uma aventura invulgar, com a qual não será difícil e interessante lidar. Não precisa de se conter. Gosta de Dota? Então, certifique-se de descarregar a nossa coleção, selecione um ou vários cursores aleatórios de uma vez - e cada novo dia tornar-se-á mais brilhante, mais interessante e saturado.',
    'minecraft_descr' => 'Os cursores do rato em forma de setas e dedos padrão tornaram-se aborrecidos para todos. Se é fã do incomum e original, então é hora de mudar o cursor do rato e dar-lhe um design mais interessante. Desenvolvemos uma coleção de cursores no estilo do mundialmente famoso jogo Minecraft, onde pode encontrar as personagens mais marcantes. Lobo e raposa, Alex e Creeper, espada de diamante e peixe - pode escolher o que mais gosta ou instalar um novo herói todos os dias. Estes são cursores reais para jogadores, e absolutamente todos vão gostar deles - afinal, qual de nós não jogou Minecraft? Temos a certeza de que estes simplesmente não existem. Abaixo com a vida quotidiana aborrecida - é hora de mergulhar em aventuras, o que pode ser feito mesmo sem sair da sua casa ou cadeira do escritório. Será mais interessante preparar um relatório e reduzir o saldo com uma arma - qualquer tarefa se tornará mais agradável e não o deixará ficar aborrecido no local. Descarregue a nova coleção de cursores Minecraft - defina-os e mesmo no dia mais cinzento e aborrecido, o seu humor estará sempre no seu melhor. E os colegas invejarão os seus resultados - é simplesmente impossível não fazer o seu trabalho com a ajuda dos bravos heróis do Minecraft.',
];
