<?php

return [
    'title' => 'Cursor Style - Política de Cookies',
    'descr' => 'Uma política de cookies quando visita o nosso website cursor.style ou a extensão “Cursor Style”. Algumas regras que deve considerar ao utilizar o nosso produto.',
    'text' => '<h2> Política de Cookies </h2>
<p> Quando visita o nosso site cursor.style ou a extensão "Cursor Style" no painel do seu navegador, ou quando interage com os nossos representantes (o "Serviço"), iremos utilizar (e permitir que terceiros utilizem) web beacons, cookies, pixel tags, scripts, tags, APIs e outras tecnologias ("Tecnologias de Rastreamento"). Isto é explicado nesta política ("Política de Cookies"), que faz parte da nossa <a href="/privacy"> Política de Privacidade </a>. </p>
<p> As tecnologias de rastreamento permitem-nos recolher automaticamente informações sobre si e o seu comportamento na Internet, a fim de melhorar a sua navegação no nosso Serviço, melhorar o desempenho do nosso Serviço e facilitar a sua experiência no nosso Serviço. Também utilizamos estas informações para recolher estatísticas sobre a utilização do nosso Serviço, conduzir análises, fornecer conteúdo que se adapte aos seus interesses e administrar serviços para os nossos Utilizadores, clientes e parceiros. Também permitimos que terceiros recolham informações sobre si utilizando tecnologias de rastreamento. </p>
<p> O que são cookies? Os cookies são pequenos ficheiros de texto (constituídos apenas por letras e números) que o servidor web coloca no seu computador ou dispositivo móvel quando visita uma página web. A utilização de um cookie pode ajudar a tornar os nossos Serviços mais fáceis de utilizar, por exemplo, recordando as suas preferências de idioma e definições. Pode encontrar mais informações sobre cookies em <a href="http://www.allaboutcookies.org"> allaboutcookies.org </a>. </p>
<p> Os cookies são amplamente utilizados para o desempenho do website. A utilização de cookies permite-lhe navegar eficientemente entre páginas. Os cookies lembram-se das suas preferências e tornam a interação entre si e os Serviços mais suave e eficiente. </p>
<p> Utilizamos tecnologias de rastreamento quando visita ou acede aos nossos Serviços (normalmente quando visita os nossos websites) - são as chamadas “Tecnologias de Rastreamento de Primeira Parte”. Além disso, as tecnologias de rastreamento são armazenadas por outras organizações terceiras (por exemplo, os nossos fornecedores de serviços de análise, parceiros de negócios e anunciantes) que publicam conteúdo nos nossos Serviços - são as chamadas “Tecnologias de Rastreamento de Terceiros”. Ambos os tipos de tecnologias de rastreamento podem ser armazenados quer durante a sua visita aos nossos Serviços, quer para visitas repetidas. </p>
<h3> Que tipos de tecnologias de rastreamento utilizamos? Existem cinco tipos principais de tecnologias de rastreamento: </h3>
<ul>
<li> <b> Tecnologias de rastreamento estritamente necessárias </b> <br> <p> Estas tecnologias de rastreamento são necessárias para que possa iniciar sessão, navegar e utilizar as funções dos nossos Serviços ou fornecer o serviço que solicita (por exemplo, o seu nome de utilizador). Não precisamos do seu consentimento para utilizar estas tecnologias de rastreamento. Estas tecnologias de rastreamento podem ser utilizadas para fins de segurança e integridade, por exemplo, para identificar violações das nossas políticas, bem como para funcionalidades de suporte ou segurança. </p> </li>
<li> <b> Tecnologias de rastreamento de funcionalidade </b> <br> <p>
Estas tecnologias de rastreamento permitem que os nossos serviços se lembrem das suas escolhas (como o idioma) e forneçam funcionalidades avançadas e personalizadas. Por exemplo, estas tecnologias de rastreamento são utilizadas para autenticação (para lembrar quando está ligado) e suportam outras funções dos nossos Serviços. </p> </li>
<li> <b> Tecnologias de rastreamento de desempenho </b> <br> <p>
Estas tecnologias de rastreamento recolhem informações sobre a sua atividade online (por exemplo, a duração da sua visita aos nossos Serviços), incluindo dados comportamentais e indicadores de envolvimento de conteúdo. Estas tecnologias de rastreamento são utilizadas para análise, pesquisa e estatísticas (com base em informações agregadas). </p> </li>
<li> <b> Tecnologias de rastreamento de marketing ou publicidade </b> <br> <p>
Estas tecnologias de rastreamento são utilizadas para lhe fornecer ofertas especiais e publicidade com base nos seus interesses, bem como para conduzir campanhas de marketing por e-mail. Também podem ser utilizadas para limitar o número de vezes que um anúncio é visualizado, bem como para medir a eficácia de uma campanha publicitária. São normalmente alojadas pelos nossos anunciantes (por exemplo, redes de anúncios) e dão-lhes uma ideia das pessoas que veem e interagem com os seus anúncios, visitam os seus websites ou utilizam a sua aplicação. </p> </li>
<li> <b> Tecnologias de rastreamento de redes sociais </b> <br> <p>
O nosso website inclui funções de redes sociais, como os botões Gosto ou Partilhar no Facebook e Vkontakte, ou serviços de login de terceiros. Estas funções são ou publicadas por terceiros ou publicadas diretamente nos nossos Serviços. A sua interação com estas funções é regida pela declaração de privacidade da empresa que fornece estas funções. </p> </li> </ul>
<h3> Seguem-se os cookies que pode encontrar nos nossos Serviços: </h3>
<ul>
<li> <b> Cookies de Análise </b> <br> <p> Estas tecnologias de rastreamento são utilizadas para recolher informações sobre como interage com o conteúdo nos nossos Serviços, fins de atribuição (por exemplo, URLs de referência), etc. Utilizamos estas informações para compilar relatórios, calcular a receita devida a nós e ajudar-nos a melhorar os Serviços e a oferecer produtos e conteúdos personalizados. </p> </li>
<li> <b> Google Analytics </b> <br> <p> Este cookie é utilizado para recolher informações sobre como os visitantes utilizam a nossa Plataforma. Utilizamos estas informações para compilar relatórios e para melhorar a Plataforma. Os cookies recolhem informações de forma anónima, incluindo o número de visitantes da Plataforma, de onde vieram os visitantes para a Plataforma e as páginas que visitaram. <br> <a href = "https://policies.google.com/privacy?hl=en" > Política de Privacidade </a> </p> </li>
<li> <b> Google Tag Manager </b> <br> <p> Este cookie está associado ao Google Tag Manager, que utilizamos para carregar scripts nas páginas do nosso website. <br> <a href = "https: / /policies.google.com/privacy?hl=en">Política de Privacidade </a> </p> </li>
</ul>
<p> Tenha em atenção que não reconhecemos nem respondemos a alertas automáticos do navegador relativamente a tecnologias de rastreamento, incluindo pedidos de Não Rastrear. No entanto, existem várias formas de gerir e controlar as suas definições de cookies. Lembre-se que ao apagar ou bloquear cookies, algumas funções dos Serviços podem não funcionar corretamente ou não tão eficientemente. </p>
<p> A maioria dos navegadores web fornece-lhe algumas informações gerais sobre cookies, permite-lhe ver quais os cookies que estão armazenados no seu dispositivo, permite-lhe apagá-los todos ou individualmente, e também permite-lhe bloquear ou permitir a utilização de cookies para todos os websites ou sites selecionados individualmente. Também pode desativar os cookies de terceiros separadamente. Tenha em atenção que as definições oferecidas pelo navegador ou dispositivo são frequentemente aplicáveis apenas a esse navegador ou dispositivo em particular. </p>
<h3> As informações sobre cookies são normalmente encontradas na secção Ajuda de um navegador web. </h3>
<p> Seguem-se links para alguns navegadores web de uso comum: </p>
<p><a href="https://support.google.com/chrome/answer/95647?hl=en"> Chrome </a> <br>
<a href="https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies"> Internet Explorer e Microsoft Edge </a> <br>
<a href="https://support.mozilla.org/en/kb/kuki-informaciya-kotoruyu-veb-sajty-hranyat-na-vas"> Mozilla Firefox </a> <br>
<a href="https://support.apple.com/ru-ru/guide/safari/sfri11471/mac"> Safari </a> </p>
<p> Pode desativar alguns cookies de terceiros para direcionamento / publicidade clicando no seguinte link: <a href="http://optout.networkadvertising.org/?c=1"> Desativar a publicidade baseada em interesses </a>. </p>
				',
];
