<?php

return [
    'title' => 'Cursor Style - Política de Privacidade',
    'descr' => 'Em “Cursor Style”, disponível em cursor.style ou através da extensão Chrome, uma das nossas principais prioridades é a privacidade dos nossos visitantes. É nesta secção que iremos falar sobre todos os aspetos de trabalhar com a extensão.',
    'text' => '<h2> Política de Privacidade </h2>
                <p> No Cursor Style, disponível em <a href="https://cursor.style"> cursor.style </a> ou através da extensão Chrome, uma das nossas principais prioridades é a privacidade dos nossos visitantes. Este documento de Política de Privacidade contém os tipos de informações que são recolhidas e registadas pelo site cursor.style e como as usamos. Se tiver perguntas adicionais ou precisar de mais informações sobre a nossa Política de Privacidade, não hesite em contactar-nos. </p>
                <p> A extensão "Cursor Style" e o site seguem o procedimento padrão para usar ficheiros de registo. Esses ficheiros registam os visitantes quando visitam sites ou usam a nossa extensão. Todas as empresas de hospedagem fazem isso e fazem parte das análises de serviço de hospedagem. As informações recolhidas através de ficheiros de registo incluem endereços de Protocolo de Internet (IP), tipo de navegador, Fornecedor de Serviços de Internet (ISP), carimbo de data e hora, páginas de transição / saída e, possivelmente, o número de cliques. Elas não estão associadas a nenhuma informação pessoalmente identificável. O objetivo desta informação é analisar tendências, administrar o site e expandir, rastrear o movimento dos utilizadores no site e expandir e recolher informações demográficas. </p>
                <p> Como qualquer outro site, o cursor.style usa cookies. Esses cookies são usados ​​para armazenar informações, incluindo as preferências do visitante e as páginas no site que o visitante visitou ou visitou. Essas informações são usadas para otimizar a experiência do utilizador, personalizando o conteúdo da nossa página web com base no tipo de navegador do visitante e / ou outras informações. Também usamos anúncios de terceiros no cursor.style para dar suporte ao projeto e dar suporte ao nosso site. Alguns desses anunciantes podem usar tecnologias como cookies e web beacons quando anunciam no nosso site, o que também enviará a esses anunciantes (por exemplo, Google através do programa Google AdSense) informações, incluindo o seu endereço IP, o seu provedor de Internet, o navegador que usou para visitar o nosso site e, em alguns casos, se tiver o Flash instalado. Isso é usado geralmente para fins de geotargeting (por exemplo, exibição de anúncios para a venda de bens na sua cidade) ou para exibição de determinados anúncios com base em determinados sites visitados (por exemplo, exibição de anúncios de compra àqueles que visitam frequentemente sites de compras). </p>
                <p> Pode desativar ou desativar seletivamente os nossos ou cookies de terceiros nas configurações do navegador ou gerenciando as configurações em programas como Kaspersky, etc. No entanto, isso pode afetar a forma como interage com o nosso site, bem como com outros sites. Isso pode incluir a incapacidade de iniciar sessão em serviços ou programas, como iniciar sessão em fóruns ou contas. </p>
<p> O Google é um dos provedores de terceiros no nosso site. Ele também usa cookies, conhecidos como cookies DART, para veicular anúncios aos visitantes do nosso site com base nas suas visitas ao cursor.style e a outros sites na Internet. No entanto, os visitantes podem desativar o uso de cookies DART visitando a política de privacidade da Rede de Conteúdo e Publicidade do Google em <a href="https://policies.google.com/technologies/ads"> o seguinte endereço </a>. Alguns dos anunciantes no nosso site podem usar cookies e web beacons. Cada um dos nossos parceiros de publicidade tem a sua própria política de privacidade para as suas políticas em relação aos dados do utilizador. Pode ler mais sobre as suas Políticas de Privacidade <a href="https://policies.google.com/technologies/ads"> aqui </a>. </p>
                <p> O nosso site usa o Google Analytics, um serviço de análise da web do Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 EUA, www.google.com (“Google Analytics” ou “Google”). O Google Analytics usa cookies que são armazenados no seu computador para facilitar a análise do seu uso do site. As informações geradas por esses cookies, como a hora, o local e a frequência das suas visitas ao nosso site, incluindo o seu endereço IP, são transferidas para um local do Google nos EUA e armazenadas lá. O Google também pode transferir essas informações a terceiros, se exigido por lei ou se terceiros processarem esses dados em nome do Google. O Google declara que nunca associará o seu endereço IP a outros dados do Google. Pode impedir a configuração de cookies alterando as configurações do software do navegador de acordo, conforme especificado nesta Política de Privacidade. No entanto, deve estar ciente de que, dessa forma, não poderá usar totalmente todas as funções do nosso site. </p>
                <p> O Google Analytics também usa imagens eletrónicas conhecidas como web beacons (às vezes chamadas de GIFs de um único pixel) e são usadas com cookies para compilar estatísticas agregadas para analisar o uso do nosso site.
Pode encontrar mais informações sobre como instalar o complemento do navegador ao qual se liga acima <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> link </a>.
Este site usa o Google Tag Manager. Este serviço permite que gerencie tags do site através da interface. O Google Tag Manager implementa apenas tags. Isso significa que nenhum cookie é definido e nenhum dado pessoal é registado. O Google Tag Manager inicia outras tags, que por sua vez podem registar dados. No entanto, o Google Tag Manager não tem acesso a esses dados. Se as tags foram desativadas no nível do domínio ou cookie, elas são salvas para todas as tags de rastreamento, se implementadas usando o Google Tag Manager. Pode saber mais sobre o Google Tag Manager visitando <a href="http://www.google.com/tagmanager/use-policy.html"> link </a>. </p>
<p> Pode familiarizar-se com esta lista para encontrar a Política de Privacidade para cada um dos parceiros de publicidade do "Cursor Style". Servidores de anúncios ou redes de publicidade de terceiros usam tecnologias como cookies, JavaScript ou web beacons, que são usados ​​nos seus respetivos anúncios e links, que são exibidos no “Cursor Style" e enviados diretamente para o navegador dos utilizadores. Eles obtêm automaticamente o seu endereço IP quando isso acontece. Essas tecnologias são usadas para medir a eficácia das suas campanhas publicitárias e / ou para personalizar o conteúdo da publicidade que vê nos sites que visita. Observe que o “Cursor Style" não tem acesso ou controlo sobre esses cookies que são usados ​​por anunciantes de terceiros. A política de privacidade do Cursor Style não se aplica a outros anunciantes ou sites. Portanto, recomendamos que reveja as políticas de privacidade relevantes desses servidores de anúncios de terceiros para obter mais informações. Pode incluir seus métodos e instruções sobre como desativar determinadas opções. Pode encontrar links para essas Políticas de Privacidade de Terceiros acima ou nos sites desses serviços de terceiros. </p>
                <p> Pode desativar cookies nas configurações do seu navegador. Para saber mais sobre o gerenciamento de cookies em navegadores da web específicos, pode encontrá-lo nos seus respetivos sites do navegador. Outra parte da nossa prioridade é adicionar proteção infantil ao usar a Internet. Incentivamos os pais e responsáveis ​​a observar, participar e / ou monitorizar e direcionar as suas atividades na Internet. O "Cursor Style" não recolhe intencionalmente informações pessoais de crianças menores de 13 anos. Se acha que o seu filho forneceu essas informações no nosso site, recomendamos vivamente que nos contacte imediatamente e faremos o possível para remover rapidamente essas informações dos nossos registos. Esta Política de Privacidade aplica-se apenas às nossas atividades online e é válida para os visitantes do nosso site em relação às informações que partilharam e / ou coletaram no “Cursor Style”. Esta política não se aplica a nenhuma informação recolhida offline ou através de canais que não este site. </p>
                <p> Pode ler mais sobre o uso de cookies no nosso Serviço na nossa <a href="/cookie-policy"> Política de Cookies </a>. </p> ',
];
