<?php

return [
    'halo_descr' => 'Halo ist eine von Bungie geschaffene Kampf-Fantasy-Medienreihe. Basierend auf der Originaltrilogie von Ego-Shooter-Videospielen. Die Handlung dreht sich um die Ereignisse im Leben von Master Chief, einem von einer Gruppe von Supersoldaten mit dem Decknamen Spartans, und seiner Begleiterin, der künstlichen Intelligenz Cortana. Der Erfolg der Spiele hat zur Ausweitung der Franchise auf andere Medien geführt: Das Halo-Universum umfasst derzeit viele Bücher, Graphic Novels, Comics, Kurzfilme, Animationen und Spielfilme.',
    'halo_short_descr' => 'Berühren Sie den Artefakt-Cursor, vielleicht sind Sie der Auserwählte',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'LOL Surprise Puppen haben sich in Kinder verliebt und ihre Herzen von den ersten Minuten an erobert. Und das ist nicht verwunderlich, denn dieser Erfolg basiert auf einem Geheimnis, der Erwartung eines Wunders, einer angenehmen Überraschung, die nicht nur Kinder, sondern auch deren Eltern begeistert. Das Geheimnis des Geschenks wird dem Kind erst nach dem endgültigen Auspacken enthüllt. Auf jeden Fall sind LOL-Puppen ein attraktives Design, Intrigen, eine große Anzahl erstaunlicher und realistischer Accessoires und angenehmer Kleinigkeiten sowie die höchste Qualität der Produktion und Detaillierung des Spielzeugs.',
    'lol_surprise_short_descr' => 'Coole Schnuckel für Liebhaber schöner Überraschungen',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Die Serie dreht sich um einen Wettbewerb, bei dem 456 Spieler, die alle tief in finanziellen Schulden stecken, ihr Leben riskieren, um eine Reihe tödlicher Kinderspiele zu spielen, mit der Chance, einen Milliardenpreis zu gewinnen. Im Inneren erwartet ein verlockender Preis mit tödlichen hohen Einsätzen. Der Titel der Serie leitet sich von einem gleichnamigen koreanischen Kinderspiel ab. Hwang hatte die Idee aufgrund seiner eigenen wirtschaftlichen Schwierigkeiten zu Beginn seines Lebens sowie der Klassenunterschiede in Südkorea und dem Kapitalismus konzipiert.',
    'squid_game_short_descr' => 'Wähle das richtige Spielergesicht, wenn du alles riskierst',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter ist die Hauptfigur einer Romanreihe der englischen Schriftstellerin JK Rowling. An seinem elften Geburtstag erfährt Harry, dass er ein Zauberer ist und für einen Platz in der Hogwarts-Schule für Hexerei und Zauberei bestimmt ist, wo er unter der Anleitung von Schulleiter Albus Dumbledore und anderen Schulprofessoren Magie praktizieren wird. Harry entdeckt auch, dass er in der gesamten magischen Gemeinschaft des Romans bereits bekannt ist und dass sein Schicksal mit dem Schicksal von Voldemort verbunden ist, einem gefährlichen dunklen Magier.',
    'harry_potter_short_descr' => 'Was wirst du mit einem Zauberstab aus der Sammlung der Harry Potter Cursor anstellen?',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics ist ein Comicverlag, der für die Erschaffung bemerkenswerter Superhelden wie Spider-Man, Iron Man, Captain America, Hulk, Thor, den Avengers, den Guardians of the Galaxy, den X-Men, den Fantastic Four und Deadpool bekannt ist. Marvels bekannteste Schurken sind unter anderem der Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom und Magneto. Marvel Comics und DC Comics haben bei mehreren Crossover-Projekten zusammengearbeitet und auch gemeinsam das absichtlich kurzlebige Imprint Amalgam Comics gegründet.',
    'marvel_comics_short_descr' => 'Der Superheld lebt in jedem von uns - wähle deinen',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Willkommen zurück im Cookie Kingdom in Cookie Run: Kingdom von Devsisters, dem bezaubernden Strategie-RPG, das im Cookie Run-Universum angesiedelt ist. Jetzt, da GingerBrave dem Ofen der bösen Hexe entkommen ist, ist es an der Zeit, dass er ein Team von Cookies aufbaut und sich auf eine Quest begibt, um das gefallene Cookie Kingdom wieder aufzubauen. Entdecken Sie die Wahrheit hinter dem Untergang des Königreichs und stellen Sie eine Truppe der mächtigsten Cookies des Königreichs zusammen, um die dunklen Mächte zu besiegen, die GingerBrave daran hindern wollen, sein Schicksal zu erfüllen.',
    'cookie_run_kingdom_short_descr' => 'Kleine Krieger direkt aus dem Ofen',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact ist ein Open-World-Adventure-Spiel. Das bedeutet, dass eine neue, entzückende Landschaft auf Sie auf der anderen Seite des Flusses oder des Berges wartet, Sie müssen nur Ihre Energie weise einsetzen. Wenn Sie auf eine umherirrende Fee oder einen seltsamen Mechanismus stoßen, wagen Sie es und versuchen Sie, ihr Geheimnis zu lüften. Aber was sie versprechen - Ärger oder eine angenehme Überraschung - können nur Sie herausfinden! Auf dem riesigen Kontinent Teyvat besuchen Sie sieben Königreiche, finden Gefährten mit verschiedenen Fähigkeiten und kämpfen gegen mächtige Feinde auf der Suche nach einem vermissten geliebten Menschen.',
    'genshin_impact_short_descr' => 'Werde zum Elementarmeister der Sieben Königreiche',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Wenn eine alte Prophezeiung wahr wird und das Königreich in die Umarmung des Winters stürzt, begeben sich drei furchtlose Helden - Prinzessin Anna, der tapfere Kristoff und sein treues Rentier Sven - in die Berge, um Annas Schwester Elsa zu finden, die den eisigen Zauber aus dem Land nehmen kann. Auf ihrem Weg erwarten sie viele schwierige Überraschungen und aufregende Abenteuer. Sie treffen mystische Trolle, begegnen einem charmanten Schneemann namens Olaf, erklimmen Bergspitzen, die steiler sind als der Everest, und erleben jede Menge Magie. Die Helden müssen den mächtigen Elementen trotzen, um das Königreich und diejenigen zu retten, die ihnen am Herzen liegen.',
    'frozen_short_descr' => 'Mit der Sammlung von Frozen-Cursorn ist das Eis zu brechen ganz einfach',
    'frozen' => 'Frozen',
    'stranger_things_descr' => 'Etwas mehr als sechs Monate sind seit dem Finale der dritten Staffel vergangen. Joyce, Will, Eleven und Jonathan sind nach Kalifornien gezogen, wo das Mädchen in der Schule gemobbt wird. Der Rest beginnt, ein neues Monster aus einer Parallelwelt zu bekämpfen, das in Hawkins aufgetaucht ist. Er wurde nach der Dungeons & Dragons-Brettspielfigur Vecna ​​genannt. Er wirkt sich psychologisch auf Teenager aus, klettert dann mental in den Kopf und tötet. Parallel dazu erfahren Joyce und Murray, dass Jim Hopper am Leben ist, und machen sich auf den Weg zu einem sowjetischen Gefängnis in Kamtschatka. Und Eleven muss zurückkehren und seine Kräfte verstärken, aber auch seine wichtige Rolle bei der Erschaffung desselben Monsters in Gokins erlernen.

Die Autoren haben die Plot-Taktik, die ihnen in den letzten Staffeln gefallen hat, nicht geändert. In der vierten Staffel teilten sie die große Gruppe der Hauptfiguren in Gruppen auf, erdachten schwierige Aufgaben für sie und bauten am Ende ihre Geschichten in einem erstaunlichen Ende zusammen. Wir bieten Ihnen an, all diese Abenteuer im Detail mithilfe der Stranger Things-Cursor-Sammlung zu verstehen.',
    'stranger_things_short_descr' => 'Was wird als Nächstes passieren? - Stranger Things 4 Cursor',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars ist ein ursprünglicher Modus, der zum ersten Mal in Minecraft erschien. Die Aufgabe der Spieler war es, ihre Basis und ihr Bett zu schützen.

Roblox bringt jeden Tag aufregendere Spiele und BedWars ist keine Ausnahme. Und die Sache ist, wenn du Bed Wars liebst und dich in deinem Zimmer verteidigst, ist dies der Titel für dich, denn er versetzt dich zurück in die Kindheit, wenn auch diesmal digital.

Alles, was du tun musst, ist, dein Bett mit deinem Partner vor Angreifern zu verteidigen. Du betrittst eine Lobby, wählst aus, mit wem du spielen möchtest, und voilà, es ist nur eine Frage des Schutzes.

Wenn es um die Verteidigung geht, wirst du natürlich einige Probleme haben und es gibt bestimmte Ressourcen, Gegenstände und Items, die dir helfen werden zu gewinnen. Zum Beispiel exklusive Skins, die du in der Bed Wars Cursor-Sammlung finden wirst.',
    'roblox_bed_wars_short_descr' => 'Beschütze dein Bett mit Roblox Bed Wars Cursorn',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'An Narutos Geburtstag griff ein legendärer Dämon, der neunschwänzige Fuchs, ein Dorf namens Konoha an. Der vierte Hokage rettete die Dorfbewohner unter Einsatz seines Lebens, indem er den Dämon in den neugeborenen Naruto versiegelte, ohne zu wissen, dass er ihn zu einem Leben voller Hass von seinen Dorfbewohnern verurteilte.
Trotz seines Mangels an Talent in vielen Bereichen des Ninjutsu, seiner Rastlosigkeit und Überheblichkeit träumt Naruto davon, Hokage zu werden, der stärkste Ninja im Dorf. Er sehnt sich nach Anerkennung, die er nicht bekommen hat, arbeitet hart und trainiert zusammen mit seinen Teamkollegen Sasuke Uchiha und Sakura Haruno sowie seinem Mentor Kakashi Hatake. Er und seine Partner müssen auf dem Weg zu ihren geschätzten Träumen viel durchmachen: Kämpfe, Liebe, Freundschaft, Verrat, Machtstreben. Eine Sammlung von Naruto-Anime-Cursorn hilft Ihnen, Ihren eigenen Weg zu finden!',
    'naruto_anime_short_descr' => 'Gehen Sie Ihren Ninja-Pfad mit Naruto-Anime-Cursorn',
    'naruto_anime' => 'Naruto-Anime',
    'demon_slayer_anime_descr' => 'Die Handlung spielt während der Taisho-Ära. Seit der Antike gibt es Gerüchte, dass humanoide Dämonen im Wald leben, die sich von Menschen ernähren und nachts umhergehen, auf der Suche nach einem neuen Opfer. Aber... es ist nur eine Legende, oder?..

Tanjiro Kamado ist der älteste Sohn der Familie, der seinen Vater verlor und sich um seine Familie kümmerte. Eines Tages geht er in eine nahegelegene Stadt, um Holzkohle zu verkaufen. Als er am Morgen zurückkehrt, entdeckt der Junge ein schreckliches Bild vor sich: Alle Verwandten wurden brutal getötet, und die einzige Überlebende ist Nezuko, eine jüngere Schwester, die sich in einen Dämon verwandelt hat, aber noch nicht ihre gesamte Menschlichkeit verloren hat.

Von diesem Moment an beginnen Tanjiro und Nezuko eine lange und gefährliche Reise, in der der Junge beabsichtigt, den Mörder zu finden und einen Weg zu finden, seine Schwester zu heilen. Aber sind die Kinder in der Lage, alle Schwierigkeiten zu überwinden und nach Hause zurückzukehren? Sie kennen die Antwort bereits, und wenn nicht - stellen Sie sich lieber die Cursor von Demon Slayer ein, mit Charakteren aus einem der beliebtesten Manga.',
    'demon_slayer_anime_short_descr' => 'Demon Slayer Cursor - für echte Nachtjäger',
    'demon_slayer_anime' => 'Demon Slayer Anime',
    'bts_descr' => 'BTS ist eine siebenköpfige Boygroup unter BigHit Music. Sie debütierten am 13. Juni 2013 mit der Single "No More Dream". In Japan debütierten sie am 24. Dezember 2014 mit dem Studioalbum Wake Up.

Der Name der Gruppe stammt von dem koreanischen Ausdruck Bangtan Sonyeondan, was so viel bedeutet wie "kugelsichere Pfadfinder". Laut J-Hope bedeutet der Name den Wunsch der Band, die Stereotypen, Kritiken und Erwartungen, die auf Teenager wie Kugeln gerichtet sind, zu blockieren.

Die Sammlung von Cursorn, die der Gruppe gewidmet sind, umfasst alle Mitglieder der Gruppe, hier Kim Nam Joon Cursor (alias RM), Kim Seok Jin Cursor (Jin), Min Yoongi Cursor (Suga), Jung Ho Suk Cursor (J-Hope), Park Ji Min Cursor (Jimin), Kim Tae Hyun Cursor (V) und Jeon Jungkook Cursor (Jungkook).',
    'bts_short_descr' => 'Triff deine Idole mit BTS-Cursorn',
    'bts' => 'BTS',
    'miraculous_descr' => 'Miraculous: Geschichten von Ladybug und Cat Noir, besser bekannt als Miraculous Ladybug und Cat Noir, sind Abenteuer von Superhelden aus dem Zeichentrickfilm über zwei Klassenkameraden, die unter Masken die Rolle der Verteidiger von Paris vor einem Bösewicht spielen, der sich in jeder Episode eine neue Möglichkeit ausdenkt, der Stadt zu schaden. Miraculous wird in Frankreich mit CGI und Animation hergestellt. Miraculous ist nicht nur eine Zeichentrickserie, sondern auch eine Sammlung von Comics, die auf der ganzen Welt veröffentlicht werden. Die Serie wird vom jungen Publikum sehr geliebt.

Die Handlung spielt in Paris, wo Marinette und Adrian Gymnasiasten an einer modernen Schule sind. Ihnen wurde die Rolle zuteil, die Auserwählten im Kampf gegen das Böse zu werden und ihre Heimatstadt zu retten. Ihr Ziel ist es, die Menschen vor Akumas zu schützen. Diese kleinen Kreaturen in Form von Schmetterlingen sind in der Lage, sich in einer Person einzunisten und sie in einen Bösewicht zu verwandeln.

Marinette kann sich in einen Marienkäfer verwandeln, und Adrian - in einen Cat Noir, aber überraschenderweise erkennen sie sich bei der Zusammenarbeit unter den Masken der Superhelden nicht gegenseitig.

Helfen Sie Cat Noir und Ladybug, Paris mit unseren Cursorn mit Ihren Lieblingscharakteren zu retten. Welchen Charakter werden Sie für den Cursor wählen? Wird es ein Miraculous Ladybug Cursor sein, oder vielleicht Tikkis entzückender kleiner Marienkäfer oder Cat Noir Cursor? Oder vielleicht ein Queen Bee mit Rena Rouge Cursorn? Die Wahl liegt bei Ihnen!',
    'miraculous_short_descr' => 'Treten Sie mit der Sammlung von Lady Bug und Cat Noir Cursorn in die Reihen der Superhelden ein',
    'miraculous' => 'Miraculous: Geschichten von Ladybug & Cat Noir',
    'talking_tom_descr' => 'Die Serie folgt dem täglichen Leben von Talking Tom und seinen Freunden. Tom und sein nerdiger Geschäftspartner Ben entwickeln ständig mobile Apps und andere Erfindungen, um Ruhm und Reichtum zu erlangen und sich der Welt zu präsentieren, aber das geht immer nach hinten los. Toms Freundin, Angela, versucht, Sängerin zu werden, egal was sie dafür tut. Toms Nachbar, Ginger, schaut hier sehr oft vorbei, um Streiche zu spielen. Der dumme beste Freund und Mitbewohner Hank ist ein Stubenhocker, der SEHR viel fernsieht. Und der ehemalige Dissidenten-Popstar Becca Sparkles ist Angelas neue Mitbewohnerin geworden und scheint sich in Hank verliebt zu haben. Aber egal wie schlimm die Dinge auch sind, ob es der böse CEO, Toms mysteriöser neuer Nachbar oder einfach nur ein Unfall in Bens neuer Erfindung ist, die Gang hat immer Spaß, und sie erinnern sich immer an eine Sache, die sie zusammenhält: Freundschaft endet nie, genau wie unsere Liebe für die Charaktere der Serie nicht endet, also kannst du dir jetzt den Talking Tom Cursor oder Ben Cursor einstellen, oder vielleicht den Angela Cursor, Oliver Cursor!',
    'talking_tom_short_descr' => 'Lass uns über deinen Lieblingscharakter in der Talking Tom Cursor Collection unterhalten',
    'talking_tom' => 'Talking Tom and Friends',
    'lego_descr' => 'Das Unternehmen LEGO Group wurde 1932 gegründet und bestand damals nur aus 7 Personen. Das Ziel des Lego-Teams war es, Spielzeuge zu entwickeln, die die Kreativität, Fantasie und den Einfallsreichtum eines Kindes fördern. Eine erstaunliche Tatsache ist, dass seit ihrer Einführung im Jahr 1949 LEGO-Elemente in all ihren Varianten miteinander kompatibel geblieben sind. Alle später erstellten Artikel sind immer noch mit Artikeln kompatibel, die heute veröffentlicht werden, trotz Veränderungen in Design und Form im Laufe der Jahre.

Ein LEGO-Stein ist eine Basis, ein hohler Kunststoffblock, der mit anderen ähnlichen Steinen verbunden wird. Aber Lego-Sets enthalten auch andere Teile, Räder, Figuren, Plattformen und sogar elektronische Schaltkreise mit Sensoren und Elektromotoren. Sie können Modelle von Autos, Flugzeugen, Zügen, Schiffen, Gebäuden und Robotern sammeln. LEGO hält sich an die Idee der Modularität, die Kindern deutlich zeigt, wie sie bestimmte Probleme lösen, ihre Fantasie, ihre Feinmotorik und ihre Montagefähigkeiten entwickeln können. LEGO-Steine werden mit unglaublicher Präzision gefertigt und passen perfekt zusammen, für eine erstaunliche Präzision von 10 Mikron.

Kürzlich wurden viele beliebte 3D-animierte Lego-Geschichten erstellt, in denen die Charaktere aus den Sets zum Leben erwachen und zu Teilnehmern unglaublicher Abenteuer werden. Wenn Sie einen coolen Cursor wollen, finden Sie in unserer Lego Cursors-Kollektion viele Charaktere aus den Lego-TV-Serien und Zeichentrickfilmen. Lego Ninjago Cursor, Lego Batman Cursor, Lego Ninjago Cursor, Lego Wyldstyle Cursor und viele mehr.',
    'lego_short_descr' => 'Baue deinen Traum-Browser mit der Lego-Cursor-Sammlung',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Nach erfolgreicher Kickstarter-Finanzierung veröffentlichte Team Cherry 2017 das Multiplattform-PC-Spiel Hollow Knight. Dies ist die Geschichte eines namenlosen Ritters und seiner Entdeckungen im Insektenreich Hallownest. Das Spiel wurde zu Recht als eines der besten im Metroidvania-Genre anerkannt.

Das Gameplay von Hollow Knight basiert auf der Erkundung der Spielwelt. Überwindung von Hindernissen, Lösen von Rätseln und Finden von Geheimnissen sowie Kämpfe gegen Feinde. Der Spieler verfügt über eine einzigartige Reihe von Verbesserungen und Tricks, um die Welt zu erkunden und in Kämpfen zu kämpfen. Von Zone zu Zone bewegend, besiegt der Spieler Bosse und erhält die notwendigen Verbesserungen, um weiter voranzukommen. Infolgedessen müssen die Spieler die bereits passierten Gebiete besuchen, um Geheimnisse zu finden und die Geschichte durchzuspielen. Und es ist auch aufregend, denn die Zonen verändern sich jedes Mal und bringen neue Überraschungen und Erlebnisse. Das Spiel kann auf verschiedene Arten gespielt werden, da es mehrere verschiedene Wege zwischen den Zonen gibt. Wenn Sie die Geschichte durchspielen, öffnen Sie die Zonenkarte, aber zuerst müssen Sie die Karte erhalten.

Die Hauptwaffe des Helden ist ein Nagel, der einem Schwert etwas ähnelt. Waffen können mit einem Schmied verbessert werden, und man kann auch verschiedene Fähigkeiten im Umgang mit Waffen erlernen, was die Vielfalt der Angriffe erweitert. Indem Sie Feinde angreifen, sammeln Sie eine spezielle Ressource, die später für Verbesserungen oder Heilung verwendet werden kann.
Viel Spaß beim Spielen von Hollow Knight und vergessen Sie nicht unsere Hollow Knight-Cursor mit Ihrem Lieblingscharakter. Unsere Sammlung umfasst den Mister Mushroom Cursor, Quirrel Cursor, Hornet Needle Cursor, Old Nail Cursor, Myla Cursor und andere.',
    'hollow-knight_short_descr' => 'Versuchen Sie sich nicht im Königreich der Insekten zu verirren, indem Sie die Hollow Knight-Sammlung von Cursorn verwenden',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman ist die Hauptfigur der Serie. Stickmin, früher unbenannt, begann als kleiner Dieb mit dem Wunsch, schnell an leichtes Geld zu kommen. Nachdem er jedoch aus dem West Mesa-Gefängnis geflohen war, fanden viele Veränderungen in seinem Leben statt, und er wurde zu einem berühmten Kriminellen, nachdem er den tunesischen Diamanten gestohlen hatte. Henry hat die Wahl - ein erfolgreicher Regierungsagent, Kopfgeldjäger, Anführer einer kriminellen Organisation, Cyborg zu werden oder den kriminellen Weg allein fortzusetzen. Das Spiel erfreut Fans des Genres mit vielen Abenteuern und Mysterien, und Sie finden unsere neue Sammlung von Henry Stickman-Cursorn mit seinen lustigen Charakteren, einschließlich des Henry Stickmin-Cursors, des Charles Calvin-Cursors, des Reginald Copperbottom-Cursors, des Right Hand-Cursors, des Ellie Rose-Cursors und anderen!',
    'henry-stickmin_short_descr' => 'Plane deine Flucht aus der Langeweile mit der Henry Stickman Cursors Collection',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'Das sehr beliebte Online-Spiel Adopt Me wurde 2017 veröffentlicht und wurde zum beliebtesten auf der Roblox-Gaming-Plattform. Die Essenz des Spiels ist sehr einfach - hol dir Eier mit Haustieren und kümmere dich um sie.

Virtuelle Haustiere sind in 5 Klassen unterteilt, einige davon sind sehr selten und teuer, während andere sehr leicht zu bekommen sind. Dies sind Ungewöhnliche Gruppen, wie der Blaue Hund, Gewöhnliche, Seltene Cursor, wie zum Beispiel der Adopt Me Affe Mauszeiger, sowie ultra-seltene, wie der Koala Cursor und Legendäre, Drachen Cursor und Akzeptiere mich Einhorn. Wenn der Spieler vier erwachsene Haustiere derselben Art hat, können sie sich zu einem Neon-Haustier kombinieren, wie dem Neon Horse Spiel-Cursor oder dem Adopt Me Neon Seestern. Durch die Kombination von vier normalen Haustieren können Sie ein Neon-Haustier herstellen, das wirklich leuchtet, und aus Neon-Haustieren können Sie ein Mega-Neon-Haustier erstellen.

Einkäufe im Spiel Adopt Me! werden mit der virtuellen Währung Roblox - den sogenannten Robux - durchgeführt, und das Spiel hat auch seine eigene Währung - Bucks. Wenn du dich um dein Haustier kümmerst, kannst du dir neben der Unterhaltung auch Bucks verdienen, indem du es einfach fütterst, ins Bett bringst oder ein Märchen vorliest, im Allgemeinen viele interessante Dinge.

Jetzt können Fans des Roblox-Spiels "Adopt Me!" ihren Spiel-Cursor mit ihrem Lieblingshaustier dekorieren!',
    'adopt-me_short_descr' => 'Viel Spaß mit süßen Haustieren in unserer Adopt Me! Sammlung von Spiel-Cursorn',
    'adopt-me' => 'Adoptiere mich!',
    'among-us_descr' => 'Among Us basiert auf dem berühmten Rollenspiel "Mafia". Geplant war, dass das Spiel exklusiv für mobile Geräte sein würde, da es nur eine Karte hatte. Das Spiel wurde schnell populär. Später fügte das Entwicklungsteam einen Multiplayer-Modus hinzu, und 2019 wurden zwei zusätzliche Karten veröffentlicht.
Among Us ist ein Top-Down-Third-Person-Spiel, das dem Spieler ermöglicht, sich in alle Richtungen zu bewegen. In einer Runde können vier bis zehn Spieler spielen. Zu Beginn des Spiels wird jedem heimlich die Rolle eines Verräters oder Crew-Mitglieds zugewiesen. Der Impostor (in der russischen Übersetzung "Verräter") kann sich in der Belüftungsklappe verstecken, Crew-Mitglieder sabotieren und töten. Sein Ziel ist es, alle Crew-Mitglieder zu vernichten oder das Raumschiff durch Sabotage zu zerstören. Das Ziel der Schiffsbesatzung ist es, verschiedene Rätsel zu lösen, die zu Beginn des Spiels für sie vorbereitet wurden. Wenn jedes der Crew-Mitglieder alle Aufgaben erledigt, verlieren die Verräter. Auch die Schiffsbesatzung kann den Sieg erringen, indem sie Verräter während der Abstimmung eliminiert.
Verräter können von Zeit zu Zeit sabotieren, und wenn die Pannen nicht in 30 Sekunden behoben werden, verliert die Crew. Vor Spielbeginn können Sie die Farbe des Charakters wählen, für den Sie spielen: blau, rot, gelb, grau - was immer Sie wollen! Und vergessen Sie nicht, sich den passenden Cursor aus der neuen Among Us-Kollektion einzurichten!',
    'among-us_short_descr' => 'Lassen Sie sich in diesem verschlungenen Weltraumspiel mit den Among Us-Cursorn nicht täuschen',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Der Schöpfer von "Steven Universe" war Rebecca Sugar. Sie ist bekannt für ihre vorherige Arbeit namens Adventure Time. Die erste Episode von Steven Universe wurde im Frühjahr 2013 auf der YouTube-Videoplattform veröffentlicht. Aber im Herbst begann der amerikanische Kanal Cartoon Network, sie für seine Zuschauer auszustrahlen. Seitdem wurden 6 Staffeln veröffentlicht. Die sechste verspricht final zu sein.
Was die Handlung der Zeichentrickserie betrifft, so dreht sie sich um das Crystal Gems-Team. Es besteht aus außerirdischen Kreaturen mit charakteristischen Namen: Perlen, Amethyst und Granatapfel. Aber es gibt noch einen weiteren Teilnehmer, in dessen Rolle der gewöhnliche Junge Stephen agiert. Gemeinsam suchen sie nach Monstern und versuchen, diese zu neutralisieren, damit sie die Erde nicht zum persönlichen Vorteil übernehmen. Ihnen entgegen stehen Jasper und Peridot - Boten von ihrem Heimatplaneten, die die Edelsteine besiegen und den Cluster einschalten wollen.
Wenn Sie ein Fan von Steven Universe sind und die Charaktere der Zeichentrickserie sehen möchten, wo immer Sie können, installieren Sie die Cursor Style Erweiterung! Warum das tun? Sie können eine Sammlung hinzufügen, die "Steven Universe" gewidmet ist, und den Standard-Mauszeiger in einen Ihrer Lieblingscharaktere verwandeln.',
    'steven_universe_short_descr' => 'Entdecke das Geheimnis der Edelsteine mit Steven Universe Cursorn',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Eine Zeichentrick-Sitcom namens "Family Guy" gewann in ihrer gesamten Geschichte 4 Mal den Emmy Award und 3 Mal den "Annie". Die Zeichentrickserie macht sich über die wunden Punkte der amerikanischen Gesellschaft lustig, wie z. B.: Feminismus, Sklaverei, Fettleibigkeit, Politik usw. Im Gegensatz zu anderen Werken werden hier Einsätze mit Witzen und Sarkasmus verwendet. Darüber hinaus sind sie in vielen Fällen nicht in die Handlung integriert, sondern existieren für sich allein.
Eine Episode der Zeichentrickserie entsteht über 10 Monate. Warum so lange? Weil die gesamte Animation von Hand gezeichnet wird. Aus diesem Grund haben einige der von der Arbeit behandelten Ereignisse Zeit, an Relevanz zu verlieren. Aber auch so bleibt die Sitcom sehr interessant und gewinnt die Gunst der Zuschauer auf der ganzen Welt. Wer lacht schließlich nicht gerne über Politiker, Prominente oder Menschen, die wilde Possen begehen und dadurch gewöhnliche Menschen überraschen oder sogar schockieren?
Magst du "Family Guy"? Sie haben eine einzigartige Gelegenheit, einen normalen Mauszeiger in eine der Figuren dieser Zeichentrickserie zu verwandeln! Was muss ich tun? Installieren Sie einfach die Browsererweiterung „Cursor Style“, fügen Sie ihr eine Sammlung hinzu, die „Family Guy“ gewidmet ist, und genießen Sie eine fabelhafte Reinkarnation!',
    'family_guy_short_descr' => 'Family Guy Cursor-Sammlung für Kenner des besonderen Humors',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Sicherlich haben Sie den Ausdruck "Schönheit wird die Welt retten" gehört? So stimmen viele Menschen, besonders Mädchen, dieser Aussage zu. Daher bemühen sie sich, sich mit allem Schönsten und Angenehmsten für das Auge zu umgeben. Es können rosafarbene Tapeten im Schlafzimmer, Kuscheltiere, mit Perlen bestickte Kissen, wertvoller Schmuck usw. sein. Von außen sieht alles sehr süß und sogar ein bisschen kindisch aus. Aber jeder von uns ist im Herzen ein kleines Kind, warum also nicht seiner Fantasie freien Lauf lassen?
Zärtlichkeit kann in uns viel auslösen. Zum Beispiel die mitfühlenden Augen eines Kätzchens, das gestreichelt oder gefüttert werden möchte. Ein mehrfarbiger Regenbogen, der nach einem Frühlingsregen hervorschaut und in allen Farben der Sonne schimmert. Das Kind, das mit Schokolade verwöhnt wurde, und beschloss, sie mit seiner Freundin oder seinem Freund zu teilen. Es gibt eine ganze Reihe von Gründen für Rührung, und wir haben beschlossen, sie als Cursor zu verwenden.
Haben Sie den langweiligen weißen Pfeil in Ihrem Browser satt? Ersetzen Sie ihn durch etwas Süßes aus unserer Sammlung! Zum Beispiel ein rosa-weißes Einhorn, eine traurige Tomate, eine brütende Wolke, ein stacheliger Kaktus in Form einer Katze oder was auch immer Sie möchten. Alles, was Sie tun müssen, ist, die Cursor Style Erweiterung zu installieren und eine Sammlung süßer Cursor hinzuzufügen. Und es lebe der Retter der Welt - die Schönheit!',
    'cute_cursors_short_descr' => 'Die Welt wird mit der niedlichen Cursorsammlung freundlicher sein',
    'cute_cursors' => 'Niedliche Cursors',
    'web_media_descr' => 'In modernen Realitäten nutzt fast jeder das Internet. Angefangen von Kleinkindern bis hin zu Rentnern. Der eine surft mit einem Browser, der andere schaut Videos auf YouTube, und wieder andere brauchen das Netzwerk, um mit ihren Lieben zu kommunizieren. Keiner dieser Nutzer kann sich einen Tag ohne das World Wide Web vorstellen.
Ältere Menschen sitzen oft in einem sozialen Netzwerk wie Facebook oder VK. Sie kommunizieren auch oft mit ihren Kindern und Enkelkindern über Skype. Dies ist besonders praktisch, wenn Kinder und Eltern in verschiedenen Städten oder sogar Ländern leben.
Junge Leute kommunizieren lieber über Viber oder Telegram, laden Fotos auf Instagram hoch, lachen über FB-Memes. YouTube-Videos mit Reaktionen von Menschen erzielen Millionen von Aufrufen, ebenso wie verschiedene Streiche oder soziale Experimente. In Tik-Tok tanzen Hunderttausende von Menschen, zeigen Zaubertricks und drücken sich aus.
Interessieren Sie sich für oder nutzen Sie oft eine Art Ressource aus dem Bereich Web-Medien? Möchten Sie den langweiligen Mauszeiger in Ihrem Browser loswerden? Dann installieren Sie die Erweiterung und ändern Sie den Standard-Cursor in unseren kreativen! Es kann ein YouTube-Cursor, ein Viber-Cursor, ein Google Chrome-Cursor oder andere Ressourcen sein.',
    'web_media_short_descr' => 'Leben Sie in einem modernen Rhythmus mit Web-Media-Cursor-Sammlungen',
    'web_media' => 'Web Media',
    'bobs_burgers_descr' => 'Die Zeichentrickserie Bob\'s Burgers ist die Handlung des Animationswerks und das Charisma der Charaktere. Und gemessen an der Nominierung für den Emmy Award und der Anerkennung des Werks als einer der besten Cartoons der ganzen Welt hat Bob\'s Snack wirklich eingeschlagen.
Die Handlung der Zeichentrickserie dreht sich um die Familie Bob Belcher. Diese Person ist der Besitzer des Diners im ersten Stock und im zweiten Stock lebt er mit seinen Lieben. Bob hat eine fröhliche Frau Linda und 3 Kinder: Gene, Louise und Tina. Der Junge träumt von einer musikalischen Karriere, die älteste Tochter Tina ist sehr lieb, aber unbeholfen, und die jüngste - Louise ist immer noch eine kleine Göre und bringt ihre Familie oft in eine unangenehme Situation. Der Hauptkonkurrent von Bob\'s Burgers ist Jimmy Pestos Pizzeria. Wie Sie sich vielleicht denken können, heißt der Besitzer dieser Pizzeria Jim, und er und Bob hassen sich. All dies wurde so dargestellt, dass es komisch und nicht ernst aussah. Daher verursachen viele ihrer Auseinandersetzungen nur ein Lächeln.
Wenn Sie die Zeichentrickserie „Bob\'s Burgers“ lieben und seine Charaktere nicht nur auf dem Bildschirm oder dem Fernseher sehen möchten, installieren Sie die Erweiterung, fügen Sie eine Sammlung hinzu und ändern Sie den Mauszeiger im Browser in einen der Charaktere dieses Cartoons!',
    'bobs_burgers_short_descr' => 'Bob macht Burger, und wir machen Bob\'s Burgers Cursor',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'Die Geschichte des Videospiels "Kirby" begann bereits in den 90er Jahren des letzten Jahrhunderts. Es besteht aus vielen Serien, die von Nintendo und HAL Laboratory entwickelt wurden. Das Spiel ist für Kinder von eineinhalb bis 8 Jahren gedacht. Seine Popularität lässt sich an der Anzahl der verkauften Exemplare ablesen. Über 34 Millionen weltweit.
Der Hauptcharakter von Kirby ist die gleichnamige rosa Kreatur. Es lebt auf einem Planeten namens Pop Star und schützt es regelmäßig vor verschiedenen Gefahren. Kerby kann einige Objekte und seine Feinde einatmen, um dann ihre Fähigkeiten zu erlernen: Nahkampf, Besitz eines Schwertes, Feuer speien usw. Der rosafarbene Kugelfisch kämpft jedoch nicht nur gegen Feinde, sondern löst auch verschiedene Rätsel, reist in andere Länder und kann sogar im Level fliegen.
Sie können dieses Videospiel auf Nintendo- oder Game Boy-Konsolen spielen. In allen Serien gibt es süße Helden, gute Grafik und lustige Soundtracks. Übrigens, seit der Veröffentlichung der ersten Version vor fast 30 Jahren konnte die Welt 20 Kirby-Serien sehen. Dieser Indikator, gepaart mit dem millionenschweren Volumen an verkauften Exemplaren, trug dazu bei, dass das Spiel in den TOP 50 der erfolgreichsten und gefragtesten Videospiele in der Spieleindustrie vertreten war.
Lieben Sie Kirby so sehr, dass Sie diesen Charakter überall sehen möchten? Dann verwenden Sie die Kirby-Collection und verwandeln Sie den regulären Mauszeiger in den Hauptcharakter Ihres Lieblingsvideospiels! Wir sind sicher, dass Ihnen das neue Aussehen des Cursors gefallen wird.',
    'kirby_short_descr' => 'Versuche, die ganze Kirby-Cursor-Sammlung einzuatmen',
    'kirby' => 'Kirby',
    'undertale_descr' => 'In der Antike wurde die Erde nicht nur von Menschen, sondern auch von Monstern bewohnt. Aufgrund von Meinungsverschiedenheiten zwischen ihnen brach ein Krieg aus, der zugunsten der menschlichen Rasse endete. Sieben Magier trieben die Monster unter die Erde und sperrten sie dort für immer mit einem Barrierezauber ein. Es gab jedoch nur einen Eingang zum Mount Ebott, den das Kind nutzte. Für ihn werden Sie spielen, indem Sie das Computerspiel Undertale ausführen.
Dieses Spiel wurde von Toby Fox entwickelt - einem bekannten Programmierer aus den Vereinigten Staaten. Zuerst konnten es Besitzer von Personalcomputern mit Microsoft Windows und Linux OS genießen, und dann kam die Reihe der Benutzer von Spielkonsolen.
Worum geht es in diesem Spiel? Der Junge reist durch die Unterwelt, die von Monstern bewohnt wird. Einige von ihnen sind sofort feindselig, während andere gerne reden. Der Spieler kann zwischen 2 Verhaltensweisen wählen: Gewalt vermeiden oder kämpfen. Im ersten Fall wird das Bestehen des Spiels einfacher, im zweiten Fall - im Gegenteil, es ist schwieriger. Die Handlung und das Ende, die sich verzweigen und verändern können, hängen auch von dieser Wahl ab.
Wenn Sie Underground Tale mögen und seine Charaktere in Ihrem Browser sehen möchten, installieren Sie die Erweiterung und fügen Sie die entsprechende Sammlung von Cursorn hinzu! Verwandeln Sie einen langweiligen Mauszeiger in eines der Monster oder den Hauptcharakter von Undertale!',
    'undertale_short_descr' => 'Es ist Zeit, mit den Undertale-Cursor aus dem Loch herauszukommen',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune ist ein Rollenspiel, das vor ein paar Jahren für Computer veröffentlicht wurde. Es wurde von dem gleichen Programmierer entwickelt, der Undertale entwickelt hat. Diese beiden Spiele ähneln sich jedoch fast nicht, obwohl sie ein paar gemeinsame Charaktere und Orte haben.
Es gibt mehrere Hauptcharaktere in Delta Rune. Dies ist ein Schüler Chris, der gesteuert werden kann, und ein bezauberndes Monster Susie, unkontrollierbar. Beide Charaktere fallen in die Welt der Dunkelheit, wo sie einen ihrer Bewohner treffen - Ralsay. Er erzählt ihnen, dass sie in Wirklichkeit Lichtkreaturen sind, die eine Mission haben - den Fluss dunkler Energie in einer düsteren Welt zu stoppen. Dazu müssen sie die lokalen Monster verschonen und versuchen, sich nicht mit ihnen in Schlachten zu verwickeln, obwohl dies manchmal recht schwierig ist.
Der Spieler hat eine einfache Wahl: Entweder die dunklen Kreaturen verschonen oder sie angreifen. Da Susie kein Fan von halben Sachen ist, wählt sie in vielen Fällen einen Kampf. Daher hat Chris keine andere Wahl, als seine Freundin zu unterstützen und ihr in den Kämpfen zu helfen.
Liebst du das Deltarune-Spiel? Dann gestalte deinen Mauszeiger im Browser für einen ihrer Charaktere! Das kannst du mit unserer Erweiterung tun. Installiere sie, füge die Sammlung „Rune Delta“ hinzu und aktiviere sie! Jetzt ist dein Pfeil nicht mehr derselbe wie alle anderen und ist zu Chris, Susie oder einer der Kreaturen der dunklen Welt geworden.',
    'deltarune_short_descr' => 'Tauche mit dieser Cursor-Sammlung in die dunkle Welt ein',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario ist eine Reihe von Computerspielen, die von Nintendo veröffentlicht wurden. Das erste und beliebteste Spiel hieß Super Mario Bros. Es erblickte 1985 das Licht der Welt. Später wurde es im Guinness-Buch der Rekorde aufgeführt. Seitdem sind mehr als 20 Spiele erschienen, jedes mit einer eigenen Handlung. Im Jahr 2019 erschien eine neue Version namens Super Mario Maker 2. Trotz der Verbesserung der Grafik blieben der Stil und die Charaktere gleich, und dies weckt Nostalgie für das Super Mario der 80er Jahre.
Der Protagonist ist immer noch der Klempner Mario. In der Handlung der letzten Variante des Spiels blieb das Schloss der Prinzessin nicht auf dem Trockenen. Mario muss es wieder aufbauen und zuvor die Münzen verdienen, die ihm für Aufgaben bezahlt werden. Insgesamt hat dieses Spiel mehr als 100 Level verschiedener Komplexität mit der Möglichkeit der Modifikation. Auch in Super Mario Maker 2 gibt es neue Spielmodi. Man kann vier davon gleichzeitig spielen und sobald einer fertig ist, gilt das Level als abgeschlossen. Es gibt auch Modi wie: Mario Marathon, Duell und Ninjik-Rennen.
Lieben Sie Super Mario und alles, was mit diesem wundervollen Spiel zu tun hat? Dann stellen Sie die Cursor im Stil dieses Platformers ein! Wir sind sicher, dass Ihnen der Mario-Cursor, der Luigi-Cursor, der Prinzessin-Peach-Cursor und andere Cursor gefallen werden, die in unserer Sammlung präsentiert werden!',
    'super_mario_short_descr' => 'Gehen Sie mit der Super Mario Cursor-Sammlung durch das Pilz-Königreich',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls wurde gemeinsam von der Disney Television Animation Corporation und Alex Hirsch erstellt. Die Premiere wurde 2012 veröffentlicht und auf dem Disney Channel gezeigt. Die gesamte erste Staffel der Zeichentrickserie wurde dort ausgestrahlt. Zwei Jahre später wurde die zweite Staffel veröffentlicht, die sich die Zuschauer auf dem vorherigen Sender und auf Disney XD ansehen konnten. Leider mussten die Gravity Falls-Fans nicht auf die dritte und die darauffolgenden Staffeln warten. Die Macher beschlossen, sich auf zwei Staffeln ohne Fortsetzungen zu beschränken.
Was die Handlung dieses Zeichentrickfilms betrifft, so spielt die gesamte Handlung in einer fiktiven Stadt namens Gravity Falls. Zwei Zwillinge kommen dorthin, deren Namen Mabel und Dipper sind. Sie wohnen bei ihrem Cousin Stan. Er hat seinen eigenen Souvenirladen für Touristen. Wenn sich die Brüder langweilen, gehen sie auf Abenteuersuche. Einer von ihnen findet im Wald ein seltsames Tagebuch, das von den Anomalien dieser Stadt erzählt. Die Zwillinge machen sich auf die Suche nach seinem Autor und begegnen ungewöhnlichen Kreaturen und Orten. Wenn Sie sich für diese Zeichentrickserie interessieren und einst Fans ihrer Charaktere waren, empfehlen wir Ihnen unsere Sammlung von Mauszeigern im Stil von Gravity Falls!',
    'gravity_falls_short_descr' => 'Begeben Sie sich mit Gravity Falls-Zeigern auf ein Abenteuer',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Nahezu jeder hat von einer so berühmten Zeichentrickserie wie Die Simpsons gehört. Selbst diejenigen, die noch nie so aussahen, wissen von der Existenz gelber Charaktere. Und die Fans freuen sich, wenn die nächste Staffel ihres Lieblingscartoons herauskommt. Übrigens, im Herbst 2019 wurden 31 Staffeln veröffentlicht. Und die erste erschien bereits 1989 auf den Fernsehbildschirmen. Fox begann, sie zu zeigen und tut dies aufgrund hoher Einschaltquoten und Sympathie des Publikums immer noch.
Die Simpsons ist ein satirisches Genre, das relevante Themen aufgreift. Dies kann der Lebensstil des durchschnittlichen Amerikaners, politische und religiöse Fragen, "starry" Tricks von Prominenten, Feminismus, gleichgeschlechtliche Ehen sein. Im Allgemeinen alles, was mit lokalen und globalen Ereignissen zu tun hat, an denen die Vereinigten Staaten teilnehmen.
Die Handlung der Zeichentrickserie spielt in der nicht existierenden Stadt Springfield. Tatsächlich gibt es in Amerika eine Menge Städte mit diesem Namen. Vielleicht wurde es deshalb so gewählt, dass das Publikum das Geschehen auf den Bildschirmen nicht mit einem bestimmten Ort in Verbindung brachte, sondern nur erraten konnte, wo dies sein könnte.
Du bist höchstwahrscheinlich ein Fan der Simpsons. Andernfalls, warum würdest du diesen Text bis zum Ende lesen? Und wenn ja, dann hast du die Möglichkeit, den gelangweilten Mauszeiger in einen Zeiger zu ändern, der im Stil dieser Zeichentrickserie gemacht wurde.',
    'simpsons_short_descr' => 'Eine lustige kleine Familie mit den Simpsons сursors.',
    'simpsons' => 'Die Simpsons',
    'youtubers_descr' => 'Die YouTube-Videoplattform erschien 2005. Zuerst wurden Videos dort nur der Selbstdarstellung oder der Information über etwas wegen veröffentlicht. Im Laufe der Zeit wuchs all dies jedoch zu einem profitablen Geschäft heran, das erfolgreichen YouTube-Benutzern Tausende und manchmal Millionen von Dollar pro Monat einbringt. Je beliebter der Vlogger (die Person, die den Videoblog führt), desto mehr kann er über seinen Kanal verdienen.
Wie viel verdient ein fünfjähriges Vlogger-Mädchen, dessen Eltern sie zu den interessantesten Attraktionen bringen und das Geschehen vor der Kamera filmen? Es ist nur, wie ein Kind Spaß in Kinderparks hat, welche Emotionen es ausdrückt, wie man herumalbert und all das. Die Summe ist wirklich erstaunlich - heute hat der Kanal des Kindes fast 47 Millionen Abonnenten gewonnen und begonnen, Einnahmen in Höhe von 5 Millionen Rubel pro Monat zu generieren.
Jemand lädt Videos hoch, in denen er Computerspiele bespricht, jemand macht Beatboxing oder veranstaltet Streiche für Passanten auf der Straße. Einige widmen ihre Videos sensiblen Themen, wie zum Beispiel der Beziehung zwischen Männern und Frauen. Je mehr YouTube-Benutzer diese Aufnahmen mögen, desto höher ist die Popularität des Vloggers.
Die Sammlung hat bereits den PewDiePie-Cursor, den Shane-Dawson-Cursor, den Ray-William-Johnson-Cursor, den Zoella-Cursor, den MyLifeAsEva-Cursor und andere hinzugefügt.',
    'youtubers_short_descr' => 'Eine neue Generation von Stars ist in unserer YouTubers-Sammlung immer online.',
    'youtubers' => 'YouTuber',
    'pusheen_descr' => 'Fast jeder kennt die Pushin-Katze. Obwohl es sich nur um eine Figur aus einem Kindercomic-Buch handelt, das vor 10 Jahren erfunden wurde, hat sie heute Millionen von Fans. Die Pusheen-Katze erschien als Illustration, die von der Künstlerin Claire Belton geschaffen wurde.
Ein Jahr später erhielt die Katze ihre eigene Seite auf Tumblr.com und gewann in wenigen Wochen eine ganze Armee von Fans - etwa 10.000 Leute. Im Jahr 2013 war Facebook bestrebt, Bilder von Pushin in Sammlungen mit anderen Emoticons aufzunehmen. Nach Verhandlungen mit dem Schöpfer wurde diese Idee in die Praxis umgesetzt und „sprengte“ das Internet! Bilder von Pusheen-Katzen werden in der Korrespondenz mehr als 10 Millionen Mal pro Tag verwendet!
Im Jahr 2014 richtete eines der größten Spielzeugunternehmen in den Vereinigten Staaten seine Aufmerksamkeit auf diese Figur. GUND (sie war es, die die Teddybären erfand) startete ein Paar Pushin-Modelle. Da der Erfolg riesig war, wurde nach ein paar Monaten eine komplette Sammlung von Spielzeugen in Form dieser Katze geschaffen.
Wo sonst können Sie die Pusheen-Katze treffen? In Geschenksets von Isaac Morris Ltd, in Marshmallows von Boomf und natürlich in unserer Sammlung von Pusheen-C cursors!',
    'pusheen_short_descr' => 'Fügen Sie Ihrem Browser etwas Komfort mit der Pushin-Cursor-Kollektion hinzu',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'Die erste Serie des Animationswerks „Rick and Morty“ wurde 2013 veröffentlicht. Dieser Zeichentrickfilm kann direkt zwei Genres zugeordnet werden: Science-Fiction und Comedy. Seine Schöpfer waren Dan Harmon und Justin Royland. Ursprünglich wurden alle Episoden auf dem Kanal Cartoon Network gezeigt, und erst dann wurden sie in Online-Kinos und Video-Hosting dupliziert. Alle paar Jahre werden neue Rick and Morty Staffeln veröffentlicht, und im November 2019 kam die vierte Staffel heraus, die sich als nicht weniger interessant als die vorherigen erwies. Die Handlung der Zeichentrickserie dreht sich um einen genialen und gleichzeitig verrückten Wissenschaftler namens Rick sowie seinen unscheinbaren Enkel Morty. Diese beiden Charaktere sind durch gemeinsame Abenteuer an den ungewöhnlichsten Orten verbunden. Und sie gelangen dorthin auf einer fliegenden Untertasse, die sich durch einen inter-räumlichen Tunnel bewegen kann. Wie Sie sich vielleicht schon gedacht haben, ähnelt diese Zeichentrickserie ein wenig dem Film Zurück in die Zukunft, aber dennoch ist sie nicht dessen animierte Version. Er wurde jedoch von vielen Kritikern für humorvolle Episoden, Kreativität und Originalität gelobt. Möchten Sie Rick oder Morty nicht nur in den Episoden dieses Werks, sondern auch im Browser sehen? Wenn ja, installieren Sie die Erweiterung und fügen Sie unsere Sammlung hinzu, die Ihrem Lieblings-Cartoon gewidmet ist! Hier ist der Rick Sanchez Cursor, der Morty Smith Cursor, der Portal Gun Cursor und natürlich der Mr. Meeseeks Cursor.',
    'rick_and_morty_short_descr' => 'Hören Sie auf zu murren, benutzen Sie einfach die Cursor aus der Rick and Morty-Sammlung',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Baseball-Fans sind auf der ganzen Welt zu finden. Dies gilt insbesondere für Einwohner von Ländern wie: USA, China, Kuba, Südkorea, Japan und Venezuela. Entgegen der landläufigen Meinung stammt Baseball nicht aus Amerika, sondern aus England. Die erste Erwähnung und Beschreibung von Baseball erschien im fernen Jahr 1744 in der englischen Ausgabe. Nach 145 Jahren haben die Amerikaner diese Erfindung für sich beansprucht, trotz der Fakten.
Die National League wurde 1876 gegründet. Sie ist Teil der Major League in Kanada und den Vereinigten Staaten. Heute gibt es 15 Teams in der National Baseball League. Am Ende jeder Saison kommt die Zeit der Playoffs, an denen die 4 besten Teams teilnehmen. So wird der Gewinner der gesamten National League ermittelt. Dann bekommt das Gewinnerteam die Möglichkeit, gegen den Gewinner aus der American League in der World Series zu spielen.
Interessieren Sie sich für Baseball oder fiebern Sie sogar für eines der Teams? Dann zollen Sie Ihrem Lieblingsteam Tribut, indem Sie die Mauszeiger in Form seiner Attribute einstellen! Ändern Sie das langweilige Aussehen des Zeigers im Browser in die vertraute Baseball-Corporate Identity! Verwandeln Sie den Pfeil in einen Schläger oder Helm eines Spielers in einem der National League-Teams, zu denen bereits der New York Yankees-Cursor, der Great Falls Dodgers-Cursor, der Boston Red Sox-Cursor und der Baltimore Orioles-Cursor gehören.',
    'mlb_teams_short_descr' => 'MLB Teams Cursor-Sammlung für alle unsere Fans da draußen.',
    'mlb_teams' => 'MLB Teams',
    'brawl_stars_descr' => 'Brawl Stars ist ein Handyspiel im MOBA-Genre von Supercell. Trotz der Veröffentlichung Ende 2018 erlangte das Spiel große Popularität, was vor allem auf die Fülle an Kampfmodi und farbenfrohen, fantastischen Helden - Brawlers - zurückzuführen ist. Der Spieler hat eine große Auswahl - 32 einzigartige Charaktere, und jeder von ihnen hat seine eigenen Fähigkeiten und Fertigkeiten. Jeder Held hat auch seine eigene passive Fähigkeit, die durch Beutetruhen verfügbar ist. Die Spieler können in mehreren Modi kämpfen, zum Beispiel "Belohnung für die Eroberung" - eines der beiden Teams gewinnt, das mehr Sterne gesammelt hat, indem es Gegner tötet. Im "Überfall"-Modus ist es notwendig, die Tresore der Gegner zu knacken, während man die eigenen verteidigt. Ein interessanter "Gem Grab"-Modus - das Team wird zum Gewinner, das Team, das die meisten Juwelen sammelt, gewinnt. Nun, im "Collision"-Modus kämpfen 10 Spieler auf der Karte gegeneinander, wobei die Grenzen aufgrund einer giftigen Wolke reduziert werden. Das Spiel ist voller farbenfrohem Design, das viele Leute mögen, einschließlich uns, was uns dazu inspirierte, eine separate Sammlung von Brawl Stars-Cursorn zu erstellen. Es gibt Brawl Stars Shelley-Cursor, Barley-Cursor, Penny-Cursor, Frank-Cursor, Mortis-Cursor und andere.',
    'brawl_stars_short_descr' => 'Wähle Brawl Stars-Cursor und lass die Schlacht beginnen',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Ändere deinen Mauszeiger mit zwei Klicks! Kostenlose Sammlungen für jeden Geschmack.',
    'all_descr' => 'Wenn Sie jemals darüber nachgedacht haben, wie Sie einen langweiligen Mauszeiger ändern können, dann sind unsere Cursor-Sammlungen genau das Richtige für Sie! Hier finden Sie coole Comic-Helden, schöne Cursor für Gamer mit Charakteren aus beliebten Spielen, lustige Cursor-Sets für praktische Witze, Farbcursor und viele andere interessante Optionen.',
    'text_title' => 'Coole und witzigste Cursor-Sammlungen für jeden Tag',
    'text_allcat_title' => 'Einzigartige und kreative Maus-Cursor passend zu jeder Stimmung',
    'text_1' => 'Du möchtest nicht so sein wie alle anderen? Oder einfach alles Ungewöhnliche lieben? Möchtest du Teil deines Lieblingsspielhelden oder deiner Lieblingszeichentrickfigur sein? Dann bist du hier genau richtig. Hier findest du helle, ungewöhnliche Sets von Cursorn, die den vertrauten und schon ziemlich langweiligen weißen Pfeil ersetzen können. Der Mauszeiger begleitet uns den ganzen Tag bei der Arbeit und beim Lernen, also sollte er für gute Laune sorgen und positiv stimmen.',
    'text_2' => 'Hier finden Sie Cursor für Gamer und Filmliebhaber, schöne Cursor basierend auf Ihren Lieblings-Cartoons und Sportmotiven für die aktivsten Leute. Mögen Sie Comics oder können Sie sich keinen einzigen Tag ohne lustige Memes vorstellen? Verehren Sie Tiere oder träumen Sie davon, alle Länder der Welt zu besuchen? Alles ist einfach - wir haben auch ein passendes Cursor-Bild für Sie. Sie können auch Bilder je nachdem auswählen, womit Sie arbeiten. Beispielsweise ist ein schwarzer Cursor viel praktischer als ein weißer, wenn Sie mit Dokumenten oder Zeichnungen arbeiten, und ein Hand-Cursor ist praktischer, wenn Sie mit kleinen grafischen Elementen arbeiten müssen. Wählen Sie Ihr Lieblingsbild aus, passen Sie seine Größe direkt in der Erweiterung an - und verwenden Sie es mit Vergnügen, jeden Tag mit einer positiven Note!',
    'install_to_preview' => 'Bitte installieren Sie die Erweiterung, um eine Vorschau anzuzeigen',
    'install' => 'Installieren',
    'add_button' => 'Hinzufügen',
    'preview_button' => 'Vorschau',
    'added_button' => 'Hinzugefügt',
    'add_cursor' => 'Cursor hinzufügen',
    'to_your_collection' => 'zu Ihrer Sammlung',
    'prev_text_1' => 'Vollbild-Vorschau',
    'prev_text_2' => 'Cursor',
    'cursor' => 'Cursor',
    'pointer' => 'Zeiger',
    'a_title_1' => 'Cursor Style - Coole Cursor für deinen Browser',
    'a_title_2' => 'Coole Sammlungen thematischer Cursor',
    'mouse_cursors' => 'Mauscursor',
    'cursor_collection' => 'Cursor-Sammlung',
    'sborka_cursorov' => 'Cursor-Sammlung',
    'collection_list_from_colllection' => 'Liste der Cursor - ',
    'christmas' => 'Weihnachten',
    'nhl_teams' => 'National Hockey League',
    'neon' => 'Neon',
    'adventure_time' => 'Adventure Time',
    'nba_teams' => 'National Basketball Association',
    'spongebob' => 'SpongeBob',
    'phineas_and_ferb' => 'Phineas and Ferb',
    'fortnite_chapter_2' => 'Fortnite Kapitel 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Berühmtheiten',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Comics',
    'igry' => 'Games',
    'multfilmy' => 'Cartoons',
    'kino_i_serialy' => 'Movies',
    'anime' => 'Anime',
    'futbol' => 'Football',
    'avtomobili' => 'Cars',
    'memy' => 'Memes',
    'emodji' => 'Emoji',
    'pitomcy' => 'Pets',
    'stil_i_krasota' => 'Modes und Stil',
    'prazdniki' => 'Feiertage',
    'flagi' => 'Flaggen',
    'vokrug_sveta' => 'Rund um die Welt',
    'eda_i_napitki' => 'Essen und Trinken',
    'cvetnye' => 'Bunt',
    'prank' => 'Streich',
    'startovyj_nabor' => 'Starter-Kit',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Der Weihnachtsmann wird Ihre Weihnachtskurse lieben',
    'nhl_teams_short_descr' => 'Eine Sammlung von NHL-Cousors für echte Fans',
    'neon_short_descr' => 'Bringe Helligkeit mit einer Neon-Sammlung',
    'adventure_time_short_descr' => 'Mathematik lernen mit der Adventure Time Cursor-Sammlung',
    'nba_teams_short_descr' => 'NBA-Cursor, als Symbol großartiger Basketballsiege',
    'spongebob_short_descr' => 'Finde heraus, wer auf dem Meeresgrund wohnt, mit der SpongeBob-Cursor-Kollektion',
    'phineas_and_ferb_short_descr' => 'Mit der Phineas und Ferb Cursor-Sammlung wird Ihnen ganz sicher nicht langweilig werden',
    'fortnite_chapter_2_short_descr' => 'Das neue Kapitel des Kultspiels Fortnite',
    'pokemon_short_descr' => 'Fang sie alle, wenn du kannst',
    'famous_people_short_descr' => 'Inspiriere deinen Idol-Cursor',
    'the_elder_scrools_short_descr' => 'Tauche ein in die Welt der Ritter und Drachen',
    'halloween_short_descr' => 'Habt Angst, die neue Halloween-Kollektion zu verpassen',
    'nfl_teams_short_descr' => 'Für echte Football-Fans',
    'five_nights_at_freddy_short_descr' => 'Versuchen Sie, sich nicht vor diesen Animatronics zu erschrecken',
    'komiksy_short_descr' => 'Cursor von Comics: Wähle deine Stimmung für heute.',
    'igry_short_descr' => 'Virtuelle Realität: Wer spielst du heute?',
    'multfilmy_short_descr' => 'Lieblings-Cartoonfiguren in einem neuen Design',
    'kino_i_serialy_short_descr' => 'Der Herr der Cursor: Die Bruderschaft des Desktops',
    'anime_short_descr' => 'Jeder liebt Anime: Wer ist deine Lieblingsfigur?',
    'futbol_short_descr' => 'Sind Sie ein echter Sportfan? Dann müssen Sie hier sein',
    'avtomobili_short_descr' => 'Das Auto Ihrer Träume: eine große Flotte für Profis',
    'memy_short_descr' => 'Lieblingsmotive: Meme-Cursor-Sammlung',
    'emodji_short_descr' => 'Zeigen Sie anderen Ihre wahre Stimmung - stellen Sie Cursoji ein!',
    'pitomcy_short_descr' => 'Helle Cursor für alle Liebhaber unserer kleineren Brüder',
    'stil_i_krasota_short_descr' => 'Originelle Cursor für alle Gelegenheiten',
    'prazdniki_short_descr' => 'Was steht im Kalender? Neue Feiertags-Cursor-Kollektion!',
    'flagi_short_descr' => 'Auf der Suche nach Abenteuern: Wo geht\'s heute hin?',
    'vokrug_sveta_short_descr' => 'In einem Augenblick um die Welt: Wohin geht es heute?',
    'eda_i_napitki_short_descr' => 'Mundwässernde Cursor für Kreativität',
    'cvetnye_short_descr' => 'Male dein Leben in leuchtenden Farben und kräftigen Strichen',
    'prank_short_descr' => 'Eine Reihe von Cursorn für die lustigsten Streiche',
    'startovyj_nabor_short_descr' => 'Ein neuer Blick auf vertraute Dinge: Eine aktualisierte Cursor-Serie',
    'fortnite_short_descr' => 'Folge den Streamern!',
    'dota_2_short_descr' => 'Gestalte deine virtuelle Welt wie echt!',
    'minecraft_short_descr' => 'Charaktere deines Lieblingsspiels sind immer in der Nähe',
    'christmas_descr' => 'Jeder von uns wartet zweifellos auf den beliebtesten Feiertag - Weihnachten. Alle Christen der Welt feiern es traditionell jedes Jahr am 25. Dezember. Eine Zeit, in der sich Familien an einem Tisch versammeln, ihre Freude und Liebe teilen und Geschenke austauschen. Lange vor Weihnachten schmücken die Menschen die Straßen mit hellen Girlanden und ihre Häuser mit traditionellen Attributen. Es ist schwer, eine Person zu finden, die Weihnachten nicht mag - ein lustiger und mysteriöser Feiertag, denn er wird von vielen Traditionen und Ritualen begleitet, die uns zu den Wurzeln unserer gesamten Familie zurückbringen. Am Weihnachtsabend ist buchstäblich alles von seinem Geist durchdrungen, von bemalten Lebkuchen bis zu berührenden Gesängen. Ein eleganter Weihnachtsbaum und Geschenke darunter, eine Freude, die jedem von uns aus der Kindheit bekannt ist. Wir möchten an diesem magischen Feiertag teilnehmen, und wer weiß, vielleicht bereitet der Weihnachtsmann ein besonderes Geschenk für Sie vor, wenn Sie Ihren Cursor mit unserer Weihnachtskollektion dekorieren. Es gibt alles, was Sie dafür brauchen, den Weihnachtsmann-Cursor, den Weihnachtsbaum-Cursor, den Lebkuchen-Cursor, den Schneemann-Cursor und sogar den Geschenktüten-Cursor. Frohe Weihnachten!',
    'nhl_teams_descr' => 'Die National Hockey League wurde 1917 gegründet - sie ist eine professionelle Sportorganisation, die Hockeyclubs aus den USA und Kanada zusammenbringt. Und das ist eine der ersten Profi-Hockeyligen der Welt. Die NHL ist zusammen mit der NFL, NBA, Major League Baseball und MLS eine der führenden Sportligen Nordamerikas. Jedes Jahr kämpfen 31 Teams aus 30 Städten in den USA und Kanada um die Haupttrophäe - den Stanley Cup, und das Team, das in der regulären Saison die meisten Punkte erzielt hat, wird mit dem Presidential Cup ausgezeichnet. Es ist Zeit für uns, dieses großartige Spiel zu ehren, indem wir eine Sammlung von NHL-Cursorn erstellen. Wenn Sie auch Hockey mögen, feuern Sie Ihren Lieblingsclub an oder nehmen Sie selbst an diesem Sport teil, ändern Sie einfach den Cursor und trennen Sie sich nicht von Ihrem Lieblingsteam, einschließlich des Boston Bruins-Cursors, des St. Louis Blues-Cursors, des Columbus Blue Jackets-Cursors, des Tampa Bay Lightning-Cursors, des Dallas Stars-Cursors und anderer Vereine, die ehrlichen Respekt verdienen.',
    'neon_descr' => 'Wir haben eine einzigartige Sammlung von Neon-Cursorn erstellt, um dem täglichen Surfen im Internet Abwechslung zu verleihen und den faszinierenden Neonlichtern ein wenig Helligkeit zu verleihen. Lassen Sie ihre satten Farben die allumfassende Atmosphäre der Stadt bei Nacht schaffen, lassen Sie sich inspirieren, etwas Neues zu schaffen. In der modernen Welt kündigen die Lichter einer Metropole immer den Einbruch der Nacht an, sie begleiten uns in jeder Straße und dieses Leuchten ist voller Energie. Lassen Sie sich auch von einem leuchtenden Eis-Cursor, einem köstlichen Hotdog-Cursor, einem saftigen Burger-Cursor, einem funkelnden Diamanten-Cursor und anderen Cursor aus der neuen Neon-Kollektion begleiten.',
    'adventure_time_descr' => '"Adventure Time" ist eine Zeichentrickserie des fantastischen Genres, in der die Handlung in einer Welt stattfindet, die eine Apokalypse überlebt hat. Dieses Gebiet heißt Land Ooo, das bis vor kurzem ein Atomkrieg war. Aber all das ist bereits Vergangenheit, jedoch waren alle überlebenden Menschen Mutationen unterworfen, und die Welt war voller Magie. Die Hauptfiguren der Zeichentrickserie sind Finn, ein 14-jähriger Junge, und sein Freund, ein Hund namens Jake. Der Junge und der Hund sind sehr abenteuerlustig, sie helfen ständig allen, die in Schwierigkeiten sind. Freunde leben auf einem Baum und verbringen die ganze Zeit zusammen. Wenn du mit anderen Bewunderern in eine Abenteuerwelt eintauchen möchtest, dann rufe "Mathematik". Hier sind sowohl der Finn-Junge-Cursor als auch der Jake-Cursor sowie der Prinzessin-Kaubonbon-Cursor. Natürlich haben wir auch den Bimo-Cursor, den Eiskönig-Cursor und andere nicht vergessen.',
    'nba_teams_descr' => 'Wenn Basketball Ihr Lieblingsspiel ist, wie es auch für uns ist, dann ist eine Sammlung von Cursorn, die den NBA-Teams gewidmet sind, genau das Richtige für Sie. Die NBA ist eine der Top-Sportverbände des nordamerikanischen Kontinents. Als wir diese Sammlung erstellten, wurden wir von der Auswahl gequält - welches Team sollten wir wählen, denn es gibt dreißig davon in der NBA. Aber es gibt Teams, die Legenden sind. Dies und die Chicago Bulls stellten Mitte der 90er Jahre einen Rekord für Siege auf. Das sind die Golden State Warriors, die vor ein paar Jahren die besten Spieler der Liga zusammenbrachten. Oder zum Beispiel Lakers, Celtics sind auch wahnsinnig coole Teams. Wenn Sie sich wie wir auf die Spiele Ihrer Lieblingsbasketballteams freuen und Ihre Unterstützung für das Team oder die Spieler zeigen möchten, laden Sie unsere Sammlung von NBA-Cursorn herunter.',
    'spongebob_descr' => 'Die Zeichentrickserie "SpongeBob Schwammkopf" ist so vielen Leuten bekannt. Sie war ein überwältigender Erfolg, nachdem Nickelodeon 1999 beschloss, eine Zeichentrickserie basierend auf dem lehrreichen Comicstrip Tide Zone zu erstellen, und sich zu einem sehr lukrativen Franchise entwickelte. Der Schöpfer der Serie ist ein ehemaliger Mitarbeiter des ozeanologischen Labors, weshalb fast alle Charaktere der Zeichentrickserie lustige Bewohner des Meeresbodens sind, mit ihren eigenen Eigenschaften und ihrem Charisma. Die Handlung dreht sich um das geheime Krabbenburger-Rezept, das nur die Hauptfigur kochen kann – SpongeBob. Und die anderen Meeresbewohner versuchen jeden Tag, es zu bekommen, einschließlich des Haupt-Antihelden Sheldon Plankton, der es jedes Mal nicht schafft. In der SpongeBob-Cursor-Sammlung haben wir die Cursor aller bemerkenswerten Charaktere und Ereignisse der Serie gesammelt. Zum Beispiel der Cursor von Mr. Krabs mit dem Dollar, der Cursor von Patrick Star, Thaddäus mit seiner Klarinette, der Cursor der Qualle, der Cursor von SpongeBob und viele andere Charaktere.',
    'phineas_and_ferb_descr' => 'In der fiktiven amerikanischen Stadt Denville des nicht existierenden Trishtatya leben zwei interessante Jungen. Jeder Tag ihres Urlaubs verwandelt sich in unglaubliche Abenteuer, denn sie können eine Achterbahn in der Größe einer ganzen Stadt oder ein echtes Portal zu einem anderen Planeten bauen. Sie teilen ihre erstaunliche Unterhaltung mit Freunden. Gleichzeitig, während die Jungen Spaß haben, baut der böse Wissenschaftler Heinz Fufelschmertz eine weitere böse Maschine, die Chaos verursacht, mit dem Namen, der auf "-inator" endet, mit Hilfe derer er seine Kindheitsbeschwerden rächen oder die Macht in Trishtat ergreifen will, aber Perry behindert ihn - Utkonos, der geheime "Agent Pi", der sich als Haustier der Jungen tarnt. Die Popularität dieser Zeichentrickserie, sowohl bei Kindern als auch bei Erwachsenen, hat uns dazu inspiriert, eine Sammlung von Phineas und Ferb-Cursors zu erstellen, damit Sie Ihren Mauszeiger auf die Charaktere aus der Serie ändern können. Unter ihnen sind der Phineas Flynn-Cursor, der Dr. Heinz Fufelschmertz-Cursor, der Ferb Fletcher-Cursor, der Candace Gertrude Flynn-Cursor und der Perry-Schnabeltier-Cursor.',
    'fortnite_chapter_2_descr' => 'Das zweite Kapitel von Fortnite kam nach einem großen Ereignis - The End, das alles, was die Spieler in dem Spiel liebten, in ein Schwarzes Loch zog. Fortnite Kapitel 2 hat jetzt eine neue Karte, die auf den ersten Blick noch wilder ist als die ursprüngliche Karte, sowie viele Änderungen in der Spielmechanik und natürlich eine Menge neuer Spielinhalte! Fahrzeuge, Emotionen, Schwimmmechaniken und vieles mehr - all das in frischen, interessanten Bildern, alles so, wie Sie es in diesem Kultspiel lieben und schätzen. Tauchen Sie ein in eine neue Welt - wählen Sie einen Landeort und erkunden Sie eine völlig neue Insel mit 13 Orten. Schwimmen, Angeln, Motorboote - das ist ein neues Wasser-Gameplay. Mehr Spaß und weniger Aufwand - verbessern Sie ein völlig neues Kapitel 2 und vergessen Sie nicht, den Cursor auf neue Skins und Waffen zu ändern. Sie warten bereits auf die aktualisierten Skins Turk-Cursor, Riptide-Cursor, Rippley-Cursor, Remedy-Cursor, Toxin-Cursor, 8-Ball-Cursor, Fusion-Cursor und andere!',
    'pokemon_descr' => 'Das Wort "Pokemon" bedeutet eine Kreatur mit übernatürlichen Kräften. Sie haben Intelligenz und einige von ihnen können sogar sprechen. Derzeit gibt es bereits 802 verschiedene Pokemon. Im erfundenen Pokémon-Universum werden Menschen Pokémon-Trainer genannt, die sie für Kämpfe mit den Pokémon anderer Trainer trainieren. Und je erfahrener und stärker der Trainer ist, desto mehr Respekt genießt er. Glücklicherweise ist anzumerken, dass Pokémon-Kämpfe nie mit dem Tod dieser einzigartigen Kreaturen enden. Alle Pokémon haben unterschiedliche Fähigkeiten und unterscheiden sich in der Art des Elements, und ihre Resistenz gegen verschiedene Angriffe hängt stark davon ab, und einige Kreaturen haben die Fähigkeit von zwei Elementen gleichzeitig. Nach dem Gewinn des Kampfes erhält das Pokémon die wertvolle Erfahrung, die erforderlich ist, um das Level und damit seine Eigenschaften zu erhöhen. Heute ist das Pokémon-Universum ein riesiges Medien-Franchise und wir haben uns entschieden, für dich eine Sammlung von Cursorn mit einigen beliebten Pokémon vorzubereiten. Darunter ist der berühmteste der Pikachu-Cursor sowie der Rattata-Cursor, der Squirt-Cursor, der Bulbasaur-Cursor und der Charmander-Cursor. Diese Liste wird ständig aktualisiert, da es so viele von ihnen gibt und jeder auf seine eigene Art einzigartig ist.',
    'famous_people_descr' => 'Unter den vielen berühmten Persönlichkeiten findet jeder von uns ein Vorbild oder bewundert einfach das Genie, das Talent und die Ausdauer dieser Prominenten. Wir haben eine Sammlung von Promi-Cursorn vorbereitet, um Sie zu inspirieren und Sie an die großartigen Leistungen zu erinnern, die jeder von Ihnen steigern kann. Nicht alle berühmten Persönlichkeiten hatten ein glückliches Schicksal, aber sie lehren uns die Hauptsache, dass Sie sich trotz der Schwierigkeiten und Probleme niemals von Ihrem geschätzten Ziel zurückziehen müssen. Schließlich ist dies das Hauptprinzip, um Erfolg zu erzielen - jeden Tag zu Ihrem Traum zu gehen und schließlich der Beste in Ihrem Bereich zu werden. Vielleicht möchten Sie heute nur Ihren Mauszeiger ändern, und morgen wird sich Ihr ganzes Leben zum Besseren verändern! Die Sammlung wird ständig um neue, würdige Vertreter der Menschheit erweitert. Darunter natürlich Wissenschaftler, Politiker, Sportler, Vertreter der Kunst und viele andere. Der George Washington Cursor, der Cursor, Michael Jordan, der Stephen King Cursor, der Elvis Presley Cursor und der Marilyn Monroe Cursor sind nur der Anfang.',
    'the_elder_scrools_descr' => 'The Elder Scrolls ist eine Reihe von Computer-Rollenspielen, die durch ein gemeinsames, sorgfältig gestaltetes Universum vereint werden und dem Spieler enorme Entscheidungsfreiheit bieten, indem sie ihm ermöglichen, verschiedene Bereiche und Städte der Fantasy-Fantasy-Welt zu besuchen und neue Orte und Missionen auf eigene Faust zu erkunden. Die Arbeiten an der Serie begannen bereits 1992 und im Laufe der Jahre hat das Spiel eine riesige Community von Spielern um sich geschart. Daher haben wir auf vielfachen Wunsch eine Sammlung von Cursorn The Elder Scrolls veröffentlicht, damit Sie in die einzigartige Atmosphäre des Spiels eintauchen können. Der ewige Kampf von Rittern und Drachen, auf welcher Seite stehen Sie? Ändern Sie den Cursor in einen Drachen und schließen Sie sich der Armee der feueratmenden Monster an oder kämpfen Sie edel auf der Seite der Menschen, indem Sie den Schwert-Cursor und das Bild Ihres Lieblingscharakters wählen - die Entscheidung liegt bei Ihnen! Die Hauptsache ist, dass Sie mit unserer neuen Sammlung für alle Kämpfe bereit sind.',
    'halloween_descr' => 'Warten auf eine mystische Nacht am Vorabend von Allerheiligen. Die Geschichte von Halloween reicht über zweitausend Jahre zurück. Vielleicht ist dies der seltsamste Feiertag, der Spaß und Angst verbindet, ein Eingeborener der keltischen Kultur. Damals brannten die Menschen Lagerfeuer und zogen gruselige Kostüme an, um Geister abzuwehren. Das Wort "Halloween" wurde erstmals im 16. Jahrhundert als schottische Abkürzung des englischen Satzes All-Hallows-Even erwähnt. Papst Gregor III. erklärte den 1. November zum Allerheiligentag, und der Abend zuvor war als Eve of All Saints und später Halloween bekannt. An diesem Tag tragen die Menschen Kostüme von Werwölfen, Geistern und anderen Monstern und gehen in Nachbarhäuser, um Süßigkeiten anzubieten. Themenpartys, Feuerwerk, schöne Laternen, Kürbisse und Stunts schaffen eine einzigartige Atmosphäre. Wir möchten diesen schrecklichen Feiertag auch mit Zubehör-Cursorn und Halloween-Charakteren feiern. In unserer Sammlung finden Sie: Zombie-Cursor, Geister-Cursor, schwarze Katzen-Cursor, Kürbis-Cursor und vieles mehr. Ihre Stimmung zu ändern, ist jetzt so einfach wie das Ändern Ihres Cursors mit unserer neuen Halloween-Kollektion.',
    'nfl_teams_descr' => 'Was gibt es für einen echten American-Football-Fan Schöneres als einen Mauszeiger in Form der Symbolik des Teams, für das er Fan ist? In der modernen National Football League spielen 32 Teams, aufgeteilt auf die National und American Football Conferences (National Football Conference, NFC und American Football Conference, AFC). Jede der Conferences ist wiederum in vier Divisionen unterteilt: East, North, South und West. Die NFL-Saison besteht aus Vorsaison-Spielen, einer regulären Saison und einer Reihe von Playoff-Spielen. Das Finalspiel der NFL-Saison heißt Super Bowl und ist im Wesentlichen das beliebteste Sportereignis in den Vereinigten Staaten. Dies ist ein Lieblingsspiel für Millionen von Fans, und daher haben wir eine Sammlung von NFL-Cursorn erstellt, damit Sie sich nicht von den Symbolen Ihres Lieblingsteams trennen müssen. Ob New England Patriots, New York Giants, Buffalo Bills oder ein anderes Team, seien Sie immer auf derselben Wellenlänge wie Ihre Idole, indem Sie unsere Cursor in Form eines Teamlogos und Helms verwenden. Die Sammlung wird ständig aktualisiert, damit jeder den Cursor auf das Bild seines Lieblingsteams ändern kann.',
    'five_nights_at_freddy_descr' => 'Das wirklich einzigartige Spiel Five Nights at Freddy\'s erlangte schnell große Popularität, und das ist nicht verwunderlich, denn seine einfache und zugleich faszinierende Handlung kann die Spieler stundenlang vor den Bildschirmen fesseln. Wir haben die Five Nights at Freddy\'s-Cursor auf Wunsch der Fans des Spiels entworfen und waren sehr erfreut, so interessante und lustige Charaktere verkörpern zu können. Aber im Gegensatz zum Spiel droht Ihnen mit unseren Cursor nichts, also wählen Sie unbesorgt Ihre Lieblings-Animatronics, sei es Bär Freddy oder Hase Bonnie oder andere. Die Hauptsache ist, dass das Spiel jetzt in Ihrem Browser zum Leben erwacht und frische Emotionen weckt. Wir garantieren, dass es in unseren Cursor keine Geister gibt, aber sie vermitteln perfekt den Geist eines Spiels, das durch die Feinheiten des Designs und der Handlungselemente Angst einflößt. Aber was ist, wenn Sie die Cursorgröße sehr groß machen? Können Sie die Ruhe bewahren und sich nicht erschrecken?',
    'komiksy_descr' => 'Es mag scheinen, dass der Mauszeiger eine Kleinigkeit ist, aber oft sind es solche Details, die Ihre Stimmung verbessern, Sie am grauen Morgen wecken oder einfach helle Emotionen hervorrufen können. Eine Sammlung von Comic-Zeigern, die speziell für alle Superhelden-Liebhaber entwickelt wurden. Hier finden Sie absolut das gesamte Marvel-Universum und DC Comics - von Iron Man bis Thanos, Spider-Man und Hulk. Der Cursor-Stil kann entweder in Form eines Superhelden oder in Form seines Charakters sein. Ein Cursor ist nicht nur ein funktionelles Element; er ist in einem professionellen Sinne wichtig. Wenn Sie beispielsweise ein Video vom Bildschirm aufnehmen, ist es besser, ein helles, originelles Bild zu sehen, und es sieht viel interessanter aus. Und natürlich - wer möchte nicht den Infinity-Handschuh im wirklichen Leben benutzen? Das Ändern des Mauszeigers ist einfach - laden Sie einfach die Erweiterung in Ihren Browser herunter und fügen Sie den gewünschten Cursor über diese Ihren Einstellungen hinzu. Sie können mindestens jeden Tag einen Cursor gemäß Ihrer Stimmung auswählen. Genug der grauen Tage - werden Sie jetzt zum Superhelden!',
    'igry_descr' => 'Computerspiele sind längst zu einem festen Bestandteil unseres Lebens geworden. Mit ihrer Hilfe können Sie in eine neue Welt eintauchen, an Abenteuern teilnehmen und eine völlig andere Person werden. Jeder hat sein eigenes Lieblingsspielzeug, dessen Charaktere schon fast zur Familie gehören. Eine Reihe von Cursorn, die auf bekannten Computerspielen basieren, ist eine Gelegenheit, den langweiligen Alltag aufzulockern und ein wenig Kreativität, Helligkeit und Spaß in den Workflow zu bringen. Das Set enthält sowohl Bilder der Spielhelden selbst als auch Zusatzcharaktere, Waffen und Spielsymbole. Wählen Sie, was zu Ihrer Stimmung passt - Spiel-Cursor werden nicht nur Gamer ansprechen, sondern auch alle, die den grauen Alltag einfach leid sind. Einfach das Set herunterladen, den Mauszeiger ändern - und los geht\'s, um Questaufgaben zu erledigen, Feinde zu vernichten und Ihre Ziele zu erreichen.',
    'multfilmy_descr' => 'In jedem Erwachsenen steckt immer noch ein Kind, das Cartoons liebt und davon träumt, einer der Helden zu werden. Wir helfen, Ihre Träume wahr werden zu lassen - verwenden Sie die neue Kollektion von Cursorn, die auf den berühmtesten und beliebtesten Cartoons basieren. Tom und Jerry, Buzz Lightyear und Shrek, Gravity Falls und sogar Pokemon - Sie können jeden Tag zu dem werden, was Sie wollen. Wählen Sie den Mauszeiger entsprechend Ihrer Stimmung. Wer sind Sie heute? Ein ungestümer und fröhlicher Minion, der jedes Problem leicht löst, oder ein starker und mutiger Raphael, dessen Ziel es ist, nicht nur Heldentaten zu vollbringen, sondern auch Pizza zu essen? Vielleicht sind Sie der allmächtige Dschinni, der ein ganzes Büro unter seinem Kommando hat? In der Sammlung gibt es Helden für jeden - von Prinzessinnen bis zu Drachen - es bleibt nur zu entscheiden, wer die heutige Stimmung widerspiegelt. Der Cursor Style ist nicht nur ein helles Bild. Dies ist ein Spiegelbild der Individualität, des Selbstausdrucks und einfach - Spaß, Freude und Positives für den ganzen Tag. Ist es langweilig zu arbeiten oder zu faul zu lernen? Ist es traurig geworden und nicht glücklich? Ändern Sie den Cursor und die Welt wird in neuen Farben funkeln.',
    'kino_i_serialy_descr' => 'Filme - sind Magie, Mystik und einfach eine großartige Möglichkeit, sich zu entspannen, Spaß zu haben und lebendige Emotionen zu erleben. Gleichzeitig erinnern wir uns nach dem Anschauen immer noch an die Lieblingshelden, die ich unbedingt in der Realität treffen möchte. Jetzt ist es möglich - laden Sie einfach die neue Sammlung von Cursorn basierend auf berühmten Filmen und Fernsehsendungen herunter. Helle, coole Cursor sind eine großartige Ergänzung zum Desktop, verwandeln den langweiligen grauen Alltag in einen Feiertag und banale Aufgaben in ein aufregendes Abenteuer. Ändern Sie den Cursorhelden jeden Tag - je nach Stimmung, Aufgabe oder zufällig. Wer werden Sie heute sein? Der ehrliche und faire John Snow oder der mutige, unerbittliche John Wick? Vielleicht haben Sie eine schwierige Mission vor sich und nur Frodo kann sie erfüllen? Vielleicht sind Sie heute nur ein Alien, der keinen Kontakt zu anderen aufnehmen möchte? Wählen Sie einen geeigneten Cursor - heben Sie Ihre Stimmung und zeigen Sie gleichzeitig anderen, was Sie denken und wie Sie Ihren Tag verbringen möchten. Probieren Sie es aus - es macht nicht nur Spaß, sondern macht auch süchtig - Sie werden definitiv nicht zum gewohnten Pfeil zurückkehren wollen.',
    'anime_descr' => 'Anime ist ein einzigartiger Animationsstil, der trotz seiner ausgeprägten ethnischen Zugehörigkeit von Millionen von Menschen auf der ganzen Welt genossen wird. Es ist unwahrscheinlich, dass es auch nur eine Person gibt, die keine Cartoons in diesem Stil gesehen hat. Wir haben die coolsten Anime-Stil-Cursor erstellt, die alle Fans dieses Stils lieben werden. Standard-Cursor sind langweilig und kitschig. Zeigen Sie Ihre Persönlichkeit - verwenden Sie die Sammlung von Anime-Cursorn mit Ihren Lieblingscharakteren. Wählen Sie den Cursor eines dunklen Schwertes, wenn Sie von Abenteuern und mutigen Kämpfen träumen. Der süße, dicke Mann Totoro wird Sie selbst am traurigsten Tag aufheitern, und Naruto wird Sie auf Abenteuer motivieren und allen um Sie herum zeigen, dass Sie mega cool sind. Helle Cursor werden den Arbeitstag aufhellen oder den Lernprozess interessanter und angenehmer gestalten. Beschränken Sie sich nicht - verwenden Sie Ihre Lieblingsmotive auch in so kleinen Elementen wie dem Mauszeiger. Ändern Sie die Cursor jeden Tag, passen Sie sie Ihrer Stimmung an und zeigen Sie Ihre Persönlichkeit - mit Anime-Stil-Cursorn ist das ganz einfach.',
    'futbol_descr' => 'Fußball ist eine besondere Sportart, die Elemente des Wrestling, der Leichtathletik und der Präzision beinhaltet. Im Allgemeinen ist er spektakulär, gnadenlos und versammelt Millionen von Fans auf der ganzen Welt. Magst du Fußball oder liebst du einfach nur Sport? Dann laden Sie eine Reihe von Cursorn im Stil des weltberühmten Spiels herunter und beweisen Sie den Titel eines treuen Fans. Die Sammlung enthält 24 Optionen zur Gestaltung von Cursorn - in Form der beliebtesten Teams, die ihre Titel als verzweifeltes und hartnäckiges Spiel verdienen. Cursor werden in zwei Versionen hergestellt - in Form eines Standarddreiecks, das in den Farben des Teams dekoriert ist, oder in Form eines entsprechenden Spielhelms. Der Standard-Browser-Cursor ist langweilig und eines echten Sportfans nicht würdig. Werden Sie originell und einzigartig mit unserer Sammlung. Laden Sie Bilder herunter und wählen Sie die Farben Ihres Lieblingsteams oder benutzerdefinierte Cursor, wenn Sie einfach nur Sport lieben und alle anfeuern. Ihren Hobbys zu folgen ist so einfach - Sie müssen nicht in einem Schal oder einer Mütze Ihres Lieblingsteams zur Arbeit kommen, es ist schnell und einfach, den Cursor in ein helles, stilvolles Bild zu ändern.',
    'avtomobili_descr' => 'Mögen Sie Autos und schauen Sie sich gerne Modelle verschiedener Hersteller an? Oder träumen Sie schon lange von einer bestimmten Marke, haben aber immer noch keine Gelegenheit, sie zu kaufen? Speziell für Sie haben wir ein helles Set von Cursorn "Supercars" erstellt. Hier finden Sie klassische Ford und stilvolle Bentley, leuchtende Lamborghini und einzigartige Ferrari. Möchten Sie der Besitzer des originalen Autos werden? Es ist einfach - laden Sie unsere Sammlung von Cursorn auf Ihr Gerät herunter und ändern Sie das Bild des Autos mindestens jeden Tag. Cursor sind in zwei Versionen gestaltet - als vollwertiges Auto oder als dessen Zeichen. Wählen Sie, was Ihnen am besten gefällt oder wie Sie am liebsten arbeiten. Solche Bilder sehen toll als Spielcursor oder einfach als ein ungewöhnliches Element des Desktops aus. Hell zu sein ist einfach - es ist nicht notwendig, dafür Unvorstellbares zu tun oder Ihr Aussehen zu verändern. Es reicht aus, einfach aufzuhören, gewöhnliche Objekte zu verwenden und das zu wählen, was Ihnen wirklich gefällt. Die Sammlung von Cursorn "Autos" ist die Wahl für diejenigen, die keine Angst haben, sich zu beweisen.',
    'memy_descr' => 'Memes sind schon lange ein vertrauter Teil unseres Lebens. Und wer von uns mag diese geräumigen, interessanten und originellen Bilder nicht, um den Tag zu verhöhnen? Viele Helden von Memes sind nicht nur populär geworden - sie haben den Status von beliebten Favoriten erlangt, und Phrasen und Ausdrücke sind schon lange in die Umgangssprache als etablierte Wendungen eingegangen. Wir präsentieren eine Sammlung der besten Cursor basierend auf den beliebtesten Memes. Mit ihrer Hilfe können Sie nicht nur Ihre Persönlichkeit zeigen, sondern auch Ihre Stimmung zum Ausdruck bringen. Sind Sie allesamt von allem müde und erschöpft? Wählen Sie eine wütende Katze, die mit ihrem ganzen Aussehen Empörung und Feindseligkeit gegenüber allem um sie herum zum Ausdruck bringt. Oder strahlen Sie heute vor Sarkasmus und haben nichts dagegen zu lachen? Dann ist Drake Bling eine ausgezeichnete Begleitung - er wird Sie aufmuntern und jede Aufgabe originell und interessant machen. Installieren Sie die Erweiterung, laden Sie unsere Sammlung herunter - und wählen Sie einen Cursor-Stil für jeden Tag. Es ist nicht schwer, hell und originell zu sein - ändern Sie das Standarddesign des Symbols in eines der Helden von Memes und erhalten Sie einen Energieschub für den ganzen Tag.',
    'emodji_descr' => 'Emoji - helle, coole Icons, ohne die wir uns nicht mehr gewohnheitsmäßig verständigen können. Mit ihrer Hilfe müssen Sie Ihre Stimmung nicht in Worten beschreiben - wählen Sie einfach das gewünschte Icon aus und der Gesprächspartner versteht Sie ohne weiteres. In unserem neuen Cursor-Set haben wir die Idee der Emoji verkörpert - so entstanden lustige und ungewöhnliche Cursoji, die die Welt farbenfroh machen und das Leben interessanter gestalten. Mit Hilfe von Kursarbeiten können Sie nicht nur arbeiten und bekannte Aufgaben ausführen, sondern auch Ihren Kollegen, Freunden und einfach anderen Ihre Stimmung zeigen. Ein verschlafener Cursor ist perfekt für Montagmorgen, und ein weinender Cursor drückt eine Einstellung zu zusätzlichen Verantwortlichkeiten aus. Ein cooler Cursor mit Brille ist die beste Wahl vor den Feiertagen, und ein Cursor mit Dollarzeichen in den Augen ist ein guter Grund, den Chef auf die Gehaltserhöhung hinzuweisen. Die Verwendung von Cursoji macht Spaß und ist interessant - sei es Arbeit, Studium oder Präsentation. Im letzteren Fall wird es sogar empfohlen, dies zu tun, wenn Kollegen Sinn für Humor haben oder einfach die Situation entschärfen müssen. Im Allgemeinen gilt: Wählen Sie für jede Aufgabe einfach den richtigen Kurs!',
    'pitomcy_descr' => 'Magst du Tiere? Sicher - sie sind so süß, lustig und sehr witzig. Warum nicht den ganzen Tag in Begleitung der besten Freunde eines Menschen verbringen? Lade die Pets-Cursor-Sammlung für dich herunter und wähle jeden Tag einen Freund für dich. Das Cursor-Symbol kann süß sein, wie ein gutmütiges Alpaka, oder stilvoll, wie ein rosa Flamingo. Oder vielleicht bist du den ganzen Tag beschäftigt und wählst ein Einhorn, das eine Zeitung liest, oder möchtest einfach nicht mit jemandem kommunizieren, wie eine böse schwarze Katze? Für jede Stimmung haben wir ein passendes Tier. Ein fröhlicher Mops wird dich auch an den langweiligsten und grauesten Tagen aufmuntern, und der rosa Cursor in Form eines Einhorns wird jedem zeigen, dass du, selbst als brutaler bärtiger Mann, nicht ohne Sinn für Schönheit bist. Was ist, wenn keine Stimmung da ist und ich keine Lust habe, Routineaufgaben zu erledigen? Das Rezept ist einfach - lade die Pets-Sammlung herunter, ändere den Maus-Cursor - und voilà, die Sonne scheint wieder, das Wetter ist gut und die Stimmung ist auf höchstem Niveau. Kein Wunder, dass man sagt, dass Tiere helfen, Depressionen und Traurigkeit zu bekämpfen!',
    'stil_i_krasota_descr' => 'In der neuen Sammlung von Cursorn haben wir eine Vielzahl von Themen zusammengestellt, die uns angenehme Emotionen auslösen und uns aufheitern. Diese Sammlung von Cursorn heißt „Stil und Schönheit“, denn es sind Ihre Lieblingsdinge, die unseren Alltag bestimmen, Freude bereiten und uns motivieren, wichtige Dinge zu tun, den Wunsch nach Verbesserung wecken. Begeistern Sie sich für den Weltraum und träumen Sie davon, zu anderen Planeten zu reisen? Wählen Sie einen NASA-Cursor oder einen Teller mit Außerirdischen - kommen Sie Ihrem Traum näher. Wenn Sie sich das Leben ohne Musik nicht vorstellen können oder ein eingefleischter Rocker sind, dann ist der Cursor im Stil einer E-Gitarre genau das Richtige für Sie. Der Pinsel-, Lineal- und Kompass-Cursor wurde speziell für Ingenieure entwickelt - solche Bilder helfen, langweilige Berechnungen und Zeichnungen in originelle Lösungen zu verwandeln. Ein Zauberstab und Turnschuhe, ein Skateboard und Lippenstift, die Sonne und chemische Kegel - wählen Sie, was zu Ihrem Lebensstil, Ihren Wünschen und Zielen passt - und gewöhnliche Aufgaben werden interessanter und Arbeitstage werden in neuen, hellen Farben gemalt.',
    'prazdniki_descr' => 'Mögen Sie Feiertage? Aber wer mag sie nicht - Freunde, Geschenke, wieder dasselbe Wochenende. Um das Warten auf die Feiertage angenehmer, kürzer und wärmer zu gestalten, können Sie nicht nur die Tage auf dem Kalender zählen, sondern auch das entsprechende Symbol als Mauszeiger einstellen. Beginnen wir mit dem neuen Jahr - wir wählen einen Weihnachtsbaum, ein Geschenk oder den Weihnachtsmann, damit der Urlaub hell und fröhlich ist. Vielleicht ist der Lebkuchenmann näher - lustig, süß und immer fröhlich? Mit ihm gibt es sicherlich keine Zeit, traurig und gelangweilt zu sein. Wir feiern weiter mit Amoretten und fröhlichen Herzen, und es ist nicht weit zum Osterhasen. Irgendwo zwischen den Feiertagen gibt es einen Geburtstag, den es mit Luftballons statt des standardmäßigen Cursorpfeils noch angenehmer zu erwarten gibt. Und an Halloween können Sie Kollegen und Menschen in Ihrer Umgebung mit einem ungewöhnlichen Mauszeiger in Form eines unheilvollen Kürbis oder eines Geistes überraschen. Eine Reihe von Cursorn für die Feiertage ist eine Gelegenheit, die Erwartung zu verschönern, sich im Voraus auf den bevorstehenden Spaß einzustimmen und eine ausgezeichnete Stimmung nicht nur am Vorabend der Feier, sondern das ganze Jahr über aufrechtzuerhalten.',
    'flagi_descr' => 'Die Fahne ist ein einzigartiges Symbol, das in allen sozialen Netzwerken weit verbreitet ist. Wir dachten, warum nicht den Cursor zu einer Flagge machen? Schließlich ist sie wirklich hell und ungewöhnlich. Jetzt können Sie jeden Tag in Gesellschaft eines neuen Landes verbringen, und die Arbeit wird nicht so eintönig und langweilig sein. Mauszeiger können jetzt in die Nationalflagge Chinas oder der USA, Japans oder Kanadas und in 38 weiteren Flaggenoptionen verwandelt werden, und Sie können entweder die Standardpfeilform in einer ungewöhnlichen Farbe oder den Cursor in Form der Flagge selbst wählen. Dieses Set wird alle Reiseliebhaber ansprechen. Mit ihm können Sie neue Reisen planen und von langen Reisen träumen. Haben Sie einen Urlaub geplant? Zeigen Sie allen, in welches Land Sie reisen möchten. Vielleicht haben Sie beschlossen, eine neue Fremdsprache zu lernen? Dann wird Sie dieser Cursor definitiv unterstützen und motiviert Sie, sorgfältig zu lernen. Oder lieben Sie, wie Sheldon, einfach nur Flaggen? In allen Fällen ist die Flags-Cursor-Sammlung eine großartige Ergänzung zu Ihrem Desktop und wird Sie zu neuen Entdeckungen bewegen.',
    'vokrug_sveta_descr' => 'Jeder reist gerne. Wie wunderbar ist es, neue Länder und Städte zu besuchen, die Sehenswürdigkeiten zu sehen und eine tolle Zeit in der neuen Kultur zu verbringen. Es ist schade, dass wir nicht so oft reisen können, aber wir haben versucht, es zu beheben. Das Set von Cursorn "Around the World" ist eine Sammlung der markantesten Bilder, Symbole verschiedener Länder, mit deren Hilfe man sich auch zu Hause wie ein echter Reisender fühlen kann. In unserem Set finden Sie Japan und Australien, Italien und Kanada, die USA und Mexiko - die interessantesten, originellsten und malerischsten Länder der Welt. Das Cursorbild kann zu einem Standardpfeil in den Farben der Flagge des Landes werden oder zu einer der Hauptattraktionen des Staates. Sie können beispielsweise Dokumente mit dem Schiefen Turm von Pisa öffnen und Präsentationen mit der Freiheitsstatue erstellen. Wir garantieren - Erfolg ist gesichert. Nun, oder wenn nicht Erfolg, dann das Lächeln der Kollegen und die Anerkennung der Originalität - sicher. Ja, und dem Management einen Hinweis zu geben, dass es Zeit ist, in den Urlaub zu fahren, lohnt sich auch - stellen Sie einfach den Koffer oder das Flugzeug als Cursor ein - und höchstwahrscheinlich fliegen Sie sehr bald.',
    'cvetnye_descr' => 'Der Cursor ist das Hauptelement des Browsers, mit dem wir den ganzen Arbeitstag verbringen, lernen, kommunizieren und uns entspannen. Die Standardansicht des Cursors ist langweilig und sogar etwas deprimierend, aber dennoch ist diese Form für viele Menschen bequem, und eine Änderung wird unangenehm sein. Aber für diese Situation haben wir eine Lösung - eine Reihe von Cursorn in hellen, fröhlichen Farben, die Ihren Alltag abwechslungsreicher machen und die Lösung von Problemen einfacher und schneller machen. Wenn Sie darüber nachdenken, wie Sie die Farbe des Cursors ändern können, antworten wir - laden Sie unsere Sammlung herunter und wählen Sie helle Lösungen für jeden Tag! Sie können monochrome Töne in verschiedenen Farben passend zur Stimmung oder den Besonderheiten der Arbeit wählen. Bei der Arbeit mit Standarddokumenten sticht beispielsweise ein violetter Cursor vom Hintergrund ab, und auf dunklem Hintergrund ist es im Gegenteil einfacher, mit gelben Cursorn zu arbeiten. Wenn Sie eine Explosion von Farbe, Helligkeit und maximaler Originalität wünschen, wählen Sie einen Regenbogen-Cursor, der alle Farben des Spektrums enthält - mit diesem Symbol ist die Stimmung den ganzen Tag über definitiv gut.',
    'prank_descr' => 'Witze am Arbeitsplatz sind nicht immer willkommen, da sie oft den Arbeitsablauf stören. Aber mit dem neuen Satz von “Pranks” Cursorn können Sie Ihren Kollegen oder Freunden einen kleinen Streich spielen, ohne Ihre Arbeit oder Ihr Studium zu schädigen. Wir haben eine spezielle Sammlung entwickelt, die jeden amüsieren und einen Grund zur Entspannung inmitten des geschäftigen Arbeits- oder Aufgabenprozesses geben wird. Um den Mauszeiger zu ändern, laden Sie einfach das Kit auf das Gerät herunter und wählen Sie das gewünschte Design in den Parametern aus. So können Sie beispielsweise einen Cursor in Standardform, aber in umgekehrter Form oder einen durch eine Welle gekrümmten Pfeil erhalten. Diese Form wird den Arbeitsprozess keineswegs behindern, aber gleichzeitig für eine wunderbare Stimmung sorgen und Sie in eine positive Stimmung versetzen. Ändern Sie die Anzeigeeinstellungen des Cursors je nach Stimmung oder jeden Tag - und jede Aufgabe wird interessanter und angenehmer, und das Alltagsleben wird keine negativen Emotionen mehr hervorrufen. Darüber hinaus können solche Cursor auch für seriöse Projekte verwendet werden - sie haben neutrale Farben und heben sich nicht vom Desktop ab.',
    'startovyj_nabor_descr' => 'Die Cursor aus der Starter-Kollektion sind eine Mischung aus Standardformen und -größen mit einem hellen, ungewöhnlichen Aussehen. Dies ist eine ausgezeichnete Wahl für diejenigen, die die üblichen Formen bevorzugen, aber Abwechslung, Originalität und Helligkeit in den Alltag bringen möchten. Die Kollektion bietet einen Hand-Cursor und einen vertrauten Pfeil in einer Vielzahl von Variationen - vom Google Chrome-Logo bis hin zu Emoticons, man kann hier sogar einen längst vergessenen Drachen mit Kakteen und Nostalgie treffen. Wir beweisen, dass ein Standard-Cursor auch interessant und attraktiv sein kann. Verschiedene Farben, Formen, Texturen und interessantes Design helfen Ihnen, den Cursor nach Ihrem Geschmack auszuwählen oder ihn jeden Tag je nach Stimmung oder auszuführenden Aufgaben zu wechseln. Das Ändern der Browser-Cursor ist ganz einfach - einfach die Erweiterung installieren und die Sammlung auf Ihr Gerät herunterladen. Lustige, interessante Cursor verschönern nicht nur die Arbeitstage, sondern helfen beispielsweise auch, jede Präsentation interessanter zu gestalten und mit Hilfe besonders heller Cursor auch die Aufmerksamkeit auf einzelne Elemente des Berichts zu lenken.',
    'fortnite_descr' => 'Fortnite hat Millionen von Menschen auf der ganzen Welt erobert. Aufregende Kämpfe, Strategie und Taktik, Abenteuer - es hat absolut alles aufgenommen, was Spieler so sehr mögen. Wir konnten nicht abseits stehen und haben eine Reihe von Cursorn im Stil des Spiels entwickelt, die nicht nur begeisterte Gamer ansprechen, sondern auch diejenigen, die zum ersten Mal von Fortnite gehört haben. Das Fortnite-Cursor-Symbol ist ein Bild eines Helden oder seiner Waffe, das bis ins kleinste Detail ausgearbeitet wurde. Hier finden Sie Bilder von Füchsen und Fischen, Masken des Infernos und schwarzer Ritter, setzen Sie sich einen Pfeil oder eine Sense mit Stacheln als Pfeil. Wir sind sicher, dass niemand gleichgültig bleiben wird! Sei gruselig oder geheimnisvoll, originell oder humorvoll - das liegt an Ihnen. Wählen Sie Ihren Stil und folgen Sie ihm oder stellen Sie in den Einstellungen benutzerdefinierte Cursor ein und ändern Sie Ihre Rolle jeden Tag. Jetzt wird es viel interessanter und angenehmer, auch mühsame und eintönige Arbeiten zu erledigen - die Zeit vergeht schnell in Gesellschaft von lebendigen Bildern und Lieblingscharakteren. Oder vielleicht veranstalten Sie Wettbewerbe mit Kollegen, welcher Held stärker sein wird? Die Wahl liegt bei Ihnen!',
    'dota_2_descr' => 'DotA2 ist jetzt nicht nur ein einfaches Spiel, es ist eine echte Parallelwelt. In der virtuellen Realität in DotA2 kannst du alles tun - leben, kämpfen, dich weiterentwickeln, reisen, Freunde finden. Im Allgemeinen ist alles wie im Leben, nur manchmal interessanter. Dota 2-Cursor sind eine Fortsetzung einer Strategie, mit der du lebendige Emotionen erhalten und dich in der realen Welt ausdrücken kannst. Ein neues Set von Cursorn enthält die markantesten Charaktere im Spiel sowie originelle Gegenstände, die man mit nichts anderem verwechseln kann. Wähle einen Cursor, der dir näher ist - und begib dich auf ein Abenteuer, ohne deinen Arbeitsplatz zu verlassen. Wie langweilig es manchmal ist, bei der Arbeit zu sein oder Lernaufgaben zu erledigen, aber mit Game-Cursorn wird dich dieses Problem nicht mehr konfrontieren. Ein wenig Fantasie, ein heller Cursor - und voilà, jede Aufgabe wird zu einem ungewöhnlichen Abenteuer, das zu bewältigen nicht schwierig und interessant sein wird. Du musst dich nicht zurückhalten. Magst du Dota? Dann lade dir unbedingt unsere Sammlung herunter, wähle einen oder mehrere zufällige Cursor auf einmal aus - und jeder neue Tag wird heller, interessanter und gesättigter.',
    'minecraft_descr' => 'Mauszeiger in Form von Standardpfeilen und Fingern sind für jeden längst langweilig geworden. Wenn Sie ein Fan des Ungewöhnlichen und Originellen sind, dann ist es an der Zeit, den Mauszeiger zu ändern und ihm ein interessanteres Design zu verleihen. Wir haben eine Sammlung von Cursorn im Stil des weltberühmten Minecraft-Spiels entwickelt, in der Sie die auffälligsten Charaktere finden können. Wolf und Fuchs, Alex und Creeper, Diamantschwert und Fisch - Sie können denjenigen auswählen, den Sie am meisten mögen, oder jeden Tag einen neuen Helden installieren. Dies sind echte Cursor für Gamer, und sie werden absolut jedem gefallen - denn wer von uns hat nicht Minecraft gespielt? Wir sind sicher, dass es diese einfach nicht gibt. Schluss mit dem langweiligen Alltag - es ist Zeit, sich in Abenteuer zu stürzen, was man sogar tun kann, ohne seinen Stuhl zu Hause oder im Büro zu verlassen. Es wird interessanter sein, einen Bericht vorzubereiten und das Guthaben mit einer Waffe zu reduzieren - jede Aufgabe wird angenehmer und lässt Sie sich nicht vor Ort langweilen. Laden Sie die neue Minecraft-Cursor-Sammlung herunter - installieren Sie sie, und selbst an den grauesten und langweiligsten Tagen ist Ihre Stimmung immer optimal. Und Kollegen werden Sie um Ihre Ergebnisse beneiden - es ist einfach unmöglich, Ihre Arbeit nicht mit Hilfe der mutigen Helden von Minecraft zu erledigen.',
    'eda_i_napitki_descr' => 'Ein Satz von Cursorn in Form von Produkten ist eine unglaubliche Sammlung von hellen, leckeren und appetitlichen Bildern, die jedem gefallen und eine großartige Ergänzung für den Browser sein werden. Haben Sie schon einmal auf Brokkoli oder Pommes Frites geklickt? Sie haben eine solche Gelegenheit - laden Sie einfach eine neue Reihe von Cursorn herunter und legen Sie sie anstelle eines langweiligen weißen Pfeils fest. Cursorn "Essen" werden sowohl in Form eines standardmäßigen dreieckigen Zeigers als auch in Form von Produkten hergestellt. Hier finden Sie Gemüse und Obst, Ihre Lieblingsgerichte wie Pizza oder Hot Dogs, Kaffee, Lutscher und vieles mehr, was jeden Tag aufheitert. Lieben Sie Kaffee, aber ist es nicht so gut, ihn den ganzen Tag zu trinken? Ergänzen Sie Ihre Ernährung mit virtuellem Kaffee, der Sie ebenfalls belebt und aufweckt und Ihnen lebendige Emotionen verleiht. Ein steiler Cursor in Form eines virtuellen Donuts schadet der Figur nicht, während er lebendige Emotionen vermittelt und aufheitert. Sie können Ihre Lieblings-Cursor verwenden oder das Bild jeden Tag ändern - eine große Auswahl an Cursorn hilft, den Alltag zu färben und vertrauten Aktionen neue Farben zu verleihen.',
];
