<?php

return [
    'title' => 'Cursor Style - Cookie-Richtlinie',
    'descr' => 'Eine Cookie-Richtlinie, wenn Sie unsere Website cursor.style oder die Erweiterung „Cursor Style“ besuchen. Einige Regeln, die Sie bei der Verwendung unseres Produkts beachten sollten.',
    'text' => '<h2> Cookie-Richtlinie </h2>
<p>Wenn Sie unsere Website cursor.style oder die Erweiterung "Cursor Style" in Ihrem Browser-Panel besuchen oder mit unseren Vertretern interagieren (die "Dienstleistung"), verwenden wir (und erlauben Dritten die Verwendung von) Web Beacons, Cookies, Pixel-Tags, Skripten, Tags, APIs und andere Technologien ("Tracking-Technologien"). Dies wird in dieser Richtlinie ("Cookie-Richtlinie") erläutert, die Teil unserer <a href="/privacy">Datenschutzrichtlinie</a> ist.</p>
<p>Tracking-Technologien ermöglichen es uns, automatisch Informationen über Sie und Ihr Verhalten im Internet zu sammeln, um Ihre Navigation auf unserer Dienstleistung zu verbessern, die Leistung unserer Dienstleistung zu verbessern und Ihre Erfahrung in unserer Dienstleistung zu erleichtern. Wir verwenden diese Informationen auch, um Statistiken über die Nutzung unserer Dienstleistung zu sammeln, Analysen durchzuführen, Inhalte zu liefern, die Ihren Interessen entsprechen, und Dienstleistungen für unsere Benutzer, Kunden und Partner zu verwalten. Wir erlauben auch Dritten, Informationen über Sie mithilfe von Tracking-Technologien zu sammeln.</p>
<p>Was sind Cookies? Cookies sind kleine Textdateien (bestehend nur aus Buchstaben und Zahlen), die der Webserver auf Ihrem Computer oder Mobilgerät ablegt, wenn Sie eine Webseite besuchen. Die Verwendung eines Cookies kann dazu beitragen, unsere Dienste benutzerfreundlicher zu gestalten, z. B. indem Ihre Spracheinstellungen und -präferenzen gespeichert werden. Weitere Informationen zu Cookies finden Sie unter <a href="http://www.allaboutcookies.org">allaboutcookies.org</a>.</p>
<p>Cookies werden häufig für die Website-Performance verwendet. Die Verwendung von Cookies ermöglicht es Ihnen, effizient zwischen Seiten zu navigieren. Cookies merken sich Ihre Präferenzen, und machen die Interaktion zwischen Ihnen und den Diensten reibungsloser und effizienter.</p>
<p>Wir verwenden Tracking-Technologien, wenn Sie unsere Dienste besuchen oder darauf zugreifen (normalerweise, wenn Sie unsere Websites besuchen) – diese werden als „First-Party Tracking Technologies“ bezeichnet. Darüber hinaus werden Tracking-Technologien von anderen Drittorganisationen (z. B. unseren Analysedienstleistern, Geschäftspartnern und Werbetreibenden) gespeichert, die Inhalte auf unseren Diensten veröffentlichen – diese werden als „Third-Party Tracking Technologies“ bezeichnet. Beide Arten von Tracking-Technologien können entweder für die Zeit Ihres Besuchs auf unseren Diensten oder für wiederholte Besuche gespeichert werden.</p>
<h3>Welche Arten von Tracking-Technologien verwenden wir? Es gibt fünf Hauptarten von Tracking-Technologien:</h3>
<ul>
<li><b>Streng notwendige Tracking-Technologien</b><br><p>Diese Tracking-Technologien sind notwendig, damit Sie sich anmelden, navigieren und die Funktionen unserer Dienste nutzen oder den von Ihnen angeforderten Dienst bereitstellen können (z. B. Ihren Benutzernamen). Wir benötigen Ihre Zustimmung nicht, um diese Tracking-Technologien zu verwenden. Diese Tracking-Technologien können für Sicherheits- und Integritätszwecke verwendet werden, z. B. um Verstöße gegen unsere Richtlinien zu identifizieren, sowie für Support- oder Sicherheitsfunktionen.</p></li>
<li><b>Funktionalitäts-Tracking-Technologien</b><br><p>Diese Tracking-Technologien ermöglichen es unseren Diensten, Ihre Auswahl (z. B. Sprache) zu speichern und erweiterte und personalisierte Funktionen bereitzustellen. Beispielsweise werden diese Tracking-Technologien für die Authentifizierung (um sich zu merken, wann Sie angemeldet sind) und zur Unterstützung anderer Funktionen unserer Dienste verwendet.</p></li>
<li><b>Performance-Tracking-Technologien</b><br><p>Diese Tracking-Technologien sammeln Informationen über Ihre Online-Aktivität (z. B. die Dauer Ihres Besuchs auf unseren Diensten), einschließlich Verhaltensdaten und Indikatoren für das Engagement von Inhalten. Diese Tracking-Technologien werden für Analysen, Forschung und Statistiken (basierend auf aggregierten Informationen) verwendet.</p></li>
<li><b>Marketing- oder Werbe-Tracking-Technologien</b><br><p>Diese Tracking-Technologien werden verwendet, um Ihnen Sonderangebote und Werbung basierend auf Ihren Interessen bereitzustellen sowie E-Mail-Marketingkampagnen durchzuführen. Sie können auch verwendet werden, um die Anzahl der Aufrufe einer Anzeige zu begrenzen sowie die Effektivität einer Werbekampagne zu messen. Sie werden in der Regel von unseren Werbetreibenden (z. B. Werbenetzwerken) gehostet und geben ihnen eine Vorstellung von den Personen, die ihre Anzeigen sehen und mit ihnen interagieren, ihre Websites besuchen oder ihre App verwenden.</p></li>
<li><b>Social-Media-Tracking-Technologien</b><br><p>Unsere Website enthält Funktionen von sozialen Netzwerken, wie z. B. die Schaltflächen „Gefällt mir“ oder „Teilen“ auf Facebook und Vkontakte oder Login-Dienste von Drittanbietern. Diese Funktionen werden entweder von einem Drittanbieter bereitgestellt oder direkt auf unseren Diensten veröffentlicht. Ihre Interaktion mit diesen Funktionen unterliegt der Datenschutzerklärung des Unternehmens, das diese Funktionen bereitstellt.</p></li>
</ul>
<h3>Im Folgenden finden Sie die Cookies, die Sie in unseren Diensten finden können:</h3>
<ul>
<li><b>Cookies Analytics</b><br><p>Diese Tracking-Technologien werden verwendet, um Informationen darüber zu sammeln, wie Sie mit Inhalten auf unseren Diensten interagieren, Zuordnungszwecke (z. B. Verweis-URLs) usw. Wir verwenden diese Informationen, um Berichte zu erstellen, das uns geschuldete Einkommen zu berechnen und uns zu helfen, die Dienste zu verbessern und personalisierte Produkte und Inhalte anzubieten.</p></li>
<li><b>Google Analytics</b><br><p>Dieses Cookie wird verwendet, um Informationen darüber zu sammeln, wie Besucher unsere Plattform nutzen. Wir verwenden diese Informationen, um Berichte zu erstellen und die Plattform zu verbessern. Cookies sammeln Informationen in anonymisierter Form, einschließlich der Anzahl der Plattformbesucher, woher Besucher auf die Plattform gekommen sind und welche Seiten sie besucht haben.<br><a href = "https://policies.google.com/privacy?hl=en">Datenschutzrichtlinie</a></p></li>
<li><b>Google Tag Manager</b><br><p>Dieses Cookie ist mit dem Google Tag Manager verknüpft, den wir verwenden, um Skripte auf den Seiten unserer Website zu laden.<br><a href = "https://policies.google.com/privacy?hl=en">Datenschutzrichtlinie</a></p></li>
</ul>
<p>Bitte beachten Sie, dass wir automatische Browserbenachrichtigungen bezüglich Tracking-Technologien, einschließlich Do-Not-Track-Anfragen, nicht erkennen oder beantworten. Es gibt jedoch verschiedene Möglichkeiten, Ihre Cookie-Einstellungen zu verwalten und zu handhaben. Denken Sie daran, dass beim Löschen oder Blockieren von Cookies einige Funktionen der Dienste möglicherweise nicht korrekt oder nicht so effizient funktionieren.</p>
<p>Die meisten Webbrowser stellen Ihnen einige allgemeine Informationen über Cookies zur Verfügung, ermöglichen es Ihnen zu sehen, welche Cookies auf Ihrem Gerät gespeichert sind, ermöglichen es Ihnen, sie alle oder einzeln zu löschen, und ermöglichen es Ihnen auch, die Verwendung von Cookies für alle Websites oder einzeln ausgewählte Websites zu blockieren oder zuzulassen. Sie können auch Cookies von Drittanbietern separat deaktivieren. Bitte beachten Sie, dass die vom Browser oder Gerät angebotenen Einstellungen häufig nur für diesen bestimmten Browser oder dieses bestimmte Gerät gelten.</p>
<h3>Cookie-Informationen finden Sie in der Regel im Hilfeabschnitt eines Webbrowsers.</h3>
<p>Im Folgenden finden Sie Links zu einigen häufig verwendeten Webbrowsern:</p>
<p><a href="https://support.google.com/chrome/answer/95647?hl=en">Chrome</a><br>
<a href="https://support.microsoft.com/de-de/help/17442/windows-internet-explorer-delete-manage-cookies">Internet Explorer und Microsoft Edge</a><br>
<a href="https://support.mozilla.org/de/kb/kuki-informaciya-kotoruyu-veb-sajty-hranyat-na-vas">Mozilla Firefox</a><br>
<a href="https://support.apple.com/de-de/guide/safari/sfri11471/mac">Safari</a></p>
<p>Sie können einige Cookies von Drittanbietern für Targeting / Werbung deaktivieren, indem Sie auf den folgenden Link klicken: <a href="http://optout.networkadvertising.org/?c=1">Opt-out of interest-based advertising</a>.</p>
				',
];
