<?php

return [
    'title' => 'Сursor Style - Nutzungsbedingungen für unser Produkt',
    'descr' => 'Nutzungsbedingungen gelten zwischen Ihnen und „Cursor Style“ („Dienst“, „wir“ oder „Service“). Dieser Dienst wird angeboten und ist Benutzern ab 13 Jahren nur für den persönlichen Gebrauch und nicht für kommerzielle Zwecke verfügbar.',
    'text' => '<h2> Nutzungsbedingungen </h2>
<h3> BITTE LESEN SIE DIESE GESCHÄFTSBEDINGUNGEN, BEVOR SIE DIE WEBSITE UND DIE ERWEITERUNG NUTZEN. </h3>
<p> Diese Nutzungsbedingungen werden zwischen Ihnen und "Cursor Style" ("Dienst", "wir" oder "Dienst") geschlossen. Die folgenden Allgemeinen Geschäftsbedingungen, zusammen mit allen Dokumenten, die sie ausdrücklich durch Verweis einbeziehen (zusammenfassend diese "Nutzungsbedingungen"), regeln Ihren Zugriff und Ihre Nutzung der Website cursor.style und ihrer Browsererweiterungen, einschließlich aller Inhalte, Funktionen und Dienste, die auf oder über unseren Dienst angeboten werden (zusammen der "Dienst"). </p>
<p> Durch die Nutzung der Website oder Erweiterung akzeptieren Sie diese Nutzungsbedingungen und erklären sich damit einverstanden. Wenn Sie diesen Nutzungsbedingungen oder unseren <a href="/privacy"> Datenschutzbestimmungen </a> nicht zustimmen, sollten Sie nicht auf die Website und die Erweiterung zugreifen oder diese nutzen. </p>
<p> Dieser Dienst wird nur für den persönlichen Gebrauch und nicht für den kommerziellen Gebrauch angeboten und steht nur Benutzern ab 13 Jahren zur Verfügung. Durch die Nutzung dieses Dienstes erklären und garantieren Sie, dass Sie (I) 13 Jahre oder älter sind, (II) es Ihnen nicht untersagt ist, die Websites in Übereinstimmung mit geltendem Recht zu nutzen, und (III) Sie den Dienst nur für Ihre persönlichen Bedürfnisse nutzen. Wenn Sie diese Anforderungen nicht erfüllen, sollten Sie nicht auf den Dienst zugreifen oder diesen nutzen. </p>
<p> Wir können diese Nutzungsbedingungen von Zeit zu Zeit nach unserem Ermessen überarbeiten und aktualisieren. Alle Änderungen treten unmittelbar nach ihrer Veröffentlichung in Kraft. Ihre fortgesetzte Nutzung des Dienstes nach der Veröffentlichung der überarbeiteten Nutzungsbedingungen bedeutet, dass Sie die Änderungen akzeptieren und ihnen zustimmen. Es wird von Ihnen erwartet, dass Sie diese Seite häufig besuchen, um über Änderungen auf dem Laufenden zu bleiben, da diese für Sie bindend sind. </p>
<p> Wir behalten uns das Recht vor, diese Website und die Erweiterung sowie alle Dienste oder Materialien, die wir auf der Website und der Erweiterung bereitstellen, nach eigenem Ermessen und ohne Vorankündigung zurückzuziehen oder zu ändern. Wir garantieren nicht, dass unsere Website, Erweiterung oder Inhalte darauf immer verfügbar sind oder unterbrochen werden. Wir haften nicht, wenn der gesamte oder ein Teil des Dienstes aus irgendeinem Grund jederzeit oder für einen bestimmten Zeitraum nicht verfügbar ist. Von Zeit zu Zeit können wir den Zugriff auf bestimmte Teile der Website oder der Erweiterung oder den gesamten Dienst für Benutzer einschränken. </p>
<p> Sie sind dafür verantwortlich, alle notwendigen Maßnahmen zu ergreifen, um sicherzustellen, dass Sie Zugriff auf den Dienst haben. Sicherstellen, dass alle Personen, die über Ihre Internetverbindung auf den Dienst zugreifen, diese Nutzungsbedingungen kennen und einhalten. Um auf den Dienst oder einige der angebotenen Ressourcen zugreifen zu können, werden Sie möglicherweise aufgefordert, bestimmte Informationen oder andere Informationen anzugeben. Sie stimmen zu, dass alle Informationen, die Sie uns über diesen Dienst oder auf andere Weise zur Verfügung stellen, einschliesslich, aber nicht beschränkt auf die Nutzung interaktiver Funktionen in dem Dienst, durch unsere <a href="/privacy"> Datenschutzbestimmungen </a> geregelt werden, und Sie stimmen allen Maßnahmen zu, die wir in Bezug auf Ihre Informationen ergreifen. in Übereinstimmung mit unseren <a href="/privacy"> Datenschutzbestimmungen </a>. </p>
<p> Sie müssen besonders vorsichtig sein, wenn Sie persönliche Informationen in den Dienst auf einem öffentlichen oder gemeinsam genutzten Computer eingeben, damit andere Ihre persönlichen Informationen nicht einsehen oder aufzeichnen können. Die Website, die Erweiterung und alle ihre Inhalte, Funktionen und Merkmale (einschliesslich, aber nicht beschränkt auf alle Informationen, die Erweiterung, Texte, Bilder, Bilder und Cursor sowie deren Design, Auswahl und Platzierung) gehören dem "Cursor Style", seinen Lizenzgebern oder anderen Anbietern solcher Materialien. Sie sind durch Urheberrechte, Marken, Patente, Geschäftsgeheimnisse und andere Gesetze oder Eigentumsrechte des geistigen Eigentums geschützt. </p>
<p> Diese Nutzungsbedingungen erlauben Ihnen die Nutzung der Websites nur für Ihren persönlichen, nicht-kommerziellen Gebrauch. Sie dürfen keine Materialien auf unserer Website reproduzieren, verteilen, modifizieren, abgeleitete Werke erstellen, neu veröffentlichen, herunterladen, speichern oder übertragen, mit Ausnahme der folgenden Fälle: Sie können sie für persönliche Bedürfnisse verwenden, Sie können eine Kopie einer angemessenen Menge an Seiten der Website und der Erweiterung oder ihrer Inhalte für den persönlichen, nicht-kommerziellen Gebrauch ausdrucken oder herunterladen, und nicht für die weitere Reproduktion, Veröffentlichung oder Verbreitung. </p>
<p> Sie dürfen Kopien von Materialien von dieser Website oder Erweiterung und deren Inhalten nicht ändern. Löschen oder ändern Sie keine Urheberrechts-, Marken- oder andere Eigentumshinweise von Kopien dieser Website und der Erweiterung. Sie dürfen für kommerzielle Zwecke keinen Zugriff auf einen Teil der Websites oder Erweiterungen sowie auf Dienste oder Materialien, die über die Website oder die Erweiterung verfügbar sind, haben oder diese nutzen. </p>
<p> Wenn Sie Material auf Websites oder Erweiterungen verwenden möchten, das nicht in diesem Abschnitt aufgeführt ist, senden Sie eine Anfrage auf der Support-Seite des Chrome Web Stores. </p>
<p> Wenn Sie Materialien auf den Websites oder Erweiterungen ausdrucken, kopieren, ändern, herunterladen oder anderweitig nutzen oder einer anderen Person Zugang gewähren, der gegen die Nutzungsbedingungen verstößt, erlischt Ihr Nutzungsrecht an der Website und der Erweiterung sofort, und Sie müssen nach unserem Ermessen alle Kopien der Materialien, die Sie haben, zurückgeben oder vernichten. Jegliche Nutzung der Website der Erweiterung, die nicht ausdrücklich in diesen Nutzungsbedingungen gestattet ist, verstösst gegen diese Nutzungsbedingungen und kann Urheberrechte, Marken und andere Gesetze verletzen. </p>
<p> Der Name “Cursor Style”, das Logo “Cursor Style” und alle zugehörigen Namen, Logos, Bilder, Cursor und Dienstnamen, Designs und Slogans sind Marken von “Cursor Style” oder seinen verbundenen Unternehmen oder Lizenzgebern. Sie dürfen solche Marken ohne vorherige schriftliche Genehmigung des Dienstes nicht verwenden. Alle anderen Namen, Logos, Produkt- und Dienstnamen, Designs und Slogans auf dieser Website und in der Erweiterung sind Marken ihrer jeweiligen Eigentümer. Sie dürfen den Dienst nur für legitime Zwecke und in Übereinstimmung mit diesen Nutzungsbedingungen verwenden. </p>
<h3> Sie erklären sich damit einverstanden, den Dienst NICHT zu nutzen: </h3>
<ul>
<li> In irgendeiner Weise, die gegen geltende Bundes-, Regional-, Lokal- oder internationale Gesetze oder Vorschriften verstösst (einschliesslich, aber nicht beschränkt auf Gesetze bezüglich des Exports von Daten oder Software nach Russland und in andere Länder). </li>
<li> Zum Zwecke der Ausbeutung, des Schadens oder der Versuche, Minderjährige auszunutzen oder zu schädigen, sie unangemessenen Inhalten auszusetzen, Informationen anzufordern, die sie identifizieren, oder anderweitig. </li>
<li> Um Materialien zu senden, wissentlich zu empfangen, herunterzuladen, zu verwenden oder wiederzuverwenden, die diesen Nutzungsbedingungen nicht entsprechen. </li>
<li> Senden oder kaufen, um Werbung oder Werbematerialien ohne unsere vorherige schriftliche Zustimmung zu senden, einschliesslich "unaufgeforderter Briefe", "Kettenbriefe" oder "Spam" oder andere ähnliche Angebote. </li>
<li> Um sich als "Cursor Style" Mitarbeiter, anderer Benutzer oder einer anderen Person oder Organisation auszugeben oder dies zu versuchen (einschliesslich, aber nicht beschränkt auf die Verwendung von E-Mail-Adressen oder Aliassen, die mit einem der oben genannten verknüpft sind). </li>
<li> Teilnahme an anderen Handlungen, die die Nutzung des Dienstes oder die Nutzung durch Dritte einschränken oder behindern oder die nach unserem Ermessen dem Dienst oder den Benutzern des Dienstes schaden oder sie haftbar machen können. </li> </ul>
<h3> Darüber hinaus erklären Sie sich NICHT einverstanden: </h3>
<ul>
<li> Den Dienst in einer Weise zu verwenden, die den Betrieb der Website deaktivieren, überlasten, beschädigen oder beeinträchtigen, erweitern oder die Nutzung des Dienstes durch Dritte beeinträchtigen kann, einschliesslich ihrer Fähigkeit, in Echtzeit über den Dienst zu agieren. </li>
<li> Verwenden Sie automatisierte Tools, Prozesse oder Mittel, um für irgendeinen Zweck auf den Dienst zuzugreifen, einschliesslich der Überwachung oder des Kopierens von Material im Dienst. </li>
<li> Verwenden Sie manuelle Prozesse, um Materialien im Dienst oder für andere unbefugte Zwecke ohne unsere vorherige schriftliche Zustimmung zu verfolgen oder zu kopieren. </li>
<li> Verwenden Sie Geräte, Software oder Verfahren, die den normalen Betrieb des Dienstes beeinträchtigen. </li>
<li> Führen Sie Viren, Trojaner, Würmer, Logikbomben oder andere Materialien ein, die schädlich oder technologisch schädlich sind. </li>
<li> Versuchen Sie, sich unbefugten Zugriff zu verschaffen, Teile des Dienstes, den Server, auf dem der Dienst gespeichert ist, oder einen Server, Computer oder eine Datenbank, die mit dem Dienst verbunden ist, zu beeinträchtigen, zu beschädigen oder zu stören. </li>
<li> Greifen Sie einen Dienst mit einem Denial-of-Service-Angriff oder einem Distributed-Denial-of-Service-Angriff an. </li> </ul>
<p> Informationen, die auf oder über den Dienst bereitgestellt werden, dienen ausschliesslich allgemeinen Informationszwecken. Wir garantieren nicht die Richtigkeit, Vollständigkeit oder Nützlichkeit dieser Informationen. Sie verlassen sich ausschliesslich auf Ihr eigenes Risiko auf solche Informationen. Wir lehnen jede Verantwortung und Haftung ab, die sich aus Ihrem Vertrauen auf solche Materialien, andere Besucher des Dienstes oder Personen ergibt, die möglicherweise von ihren Inhalten erfahren. </p>
<p> Dieser Dienst umfasst Inhalte von Dritten, einschliesslich Materialien, die von anderen Benutzern und Drittanbietern (wie Lizenzgebern, Syndikatoren, Aggregatoren und/oder Berichtsdiensten) bereitgestellt werden. Alle in diesen Materialien zum Ausdruck gebrachten Aussagen und/oder Meinungen sowie alle Artikel, Antworten auf Fragen und andere Inhalte, mit Ausnahme der vom Dienst bereitgestellten Inhalte, sind ausschliesslich die Meinungen und Verantwortlichkeiten der Person oder Organisation, die diese Materialien bereitstellt. Diese Materialien spiegeln nicht unbedingt die Ansichten des Dienstes wider. Wir haften Ihnen oder Dritten gegenüber nicht für den Inhalt oder die Richtigkeit von Materialien, die von Dritten bereitgestellt werden. </p>
<p> Wir können den Inhalt des Dienstes von Zeit zu Zeit aktualisieren, aber sein Inhalt ist nicht unbedingt vollständig oder aktuell. Jedes Material im Dienst kann jederzeit veraltet sein, und wir sind nicht verpflichtet, solches Material zu aktualisieren. Wir können Informationen und Inhalte auf der Website und in der Erweiterung aktualisieren, modifizieren, ändern und Änderungen und Aktualisierungen nach unserer eigenen Entscheidung vornehmen. </p>
<p> Alle Informationen, die wir über diesen Dienst sammeln, unterliegen unseren Datenschutzbestimmungen. Durch die Nutzung des Dienstes stimmen Sie allen von uns in Bezug auf Ihre Informationen unternommenen Handlungen in Übereinstimmung mit den <a href="/privacy"> Datenschutzbestimmungen </a> zu. </p>
<p> Zusätzliche Bedingungen können auch für bestimmte Teile, Dienste oder Funktionen des Dienstes gelten. Alle diese zusätzlichen Bedingungen werden hiermit durch Verweis in diese Nutzungsbedingungen aufgenommen.
Sie können einen Link zu unserer Website oder Erweiterung einfügen, wenn Sie dies auf ehrliche und rechtmässige Weise tun und unseren Ruf nicht schädigen oder ihn nutzen, aber Sie sollten den Link nicht so setzen, dass er in irgendeiner Form eine Assoziation, Unterstützung oder Billigung unsererseits ohne unsere schriftliche Zustimmung anbietet. </p>
<p> Der Dienst enthält Links zu anderen Websites und Ressourcen, die von Dritten bereitgestellt werden. Diese Links werden nur zu Ihrer Erleichterung bereitgestellt. Dies beinhaltet Links, die in Anzeigen enthalten sind, einschliesslich Bannerwerbung und gesponserten Links. Wir haben keine Kontrolle über den Inhalt dieser Websites oder Ressourcen und sind nicht verantwortlich für diese oder für Verluste oder Schäden, die sich aus ihrer Nutzung ergeben können. Wenn Sie sich entscheiden, auf Websites Dritter zuzugreifen, die mit diesem Dienst verknüpft sind, tun Sie dies auf eigene Gefahr und in Übereinstimmung mit den Nutzungsbedingungen dieser Websites. Wir behalten uns das Recht vor, die Erlaubnis zum Verlinken ohne vorherige Ankündigung zu widerrufen. </p>
<p> Sie verstehen, dass wir nicht garantieren oder gewährleisten können, dass die zum Download über das Internet oder auf Websites verfügbaren Dateien keine Viren oder anderen bösartigen Code enthalten. Sie sind für die Implementierung von Verfahren und Kontrollpunkten verantwortlich, die ausreichen, um Ihre besonderen Anforderungen für den Antivirenschutz und die Richtigkeit der Dateneingabe und -ausgabe zu erfüllen, sowie für die Aufrechterhaltung von Mitteln ausserhalb unserer Website zur Wiederherstellung verlorener Daten. WIR HAFTEN NICHT FÜR SCHÄDEN ODER VERLETZUNGEN, DIE DURCH EINEN DISTRIBUTED DENIAL SERVICE, VIREN ODER ANDERE TECHNOLOGIE-MALWARE VERURSACHT WERDEN, DIE ÜBER DEN DIENST ERHALTEN WERDEN, ODER DURCH DAS HERUNTERLADEN VON MATERIALIEN AUF DIESER ODER ENTSPRECHENDEN WEBSEITEN, DIE IHRE COMPUTER-AUSRÜSTUNG, -SOFTWARE, -DATEN INFIZIEREN ODER BESCHÄDIGEN KÖNNTEN. </p>
<p> SIE NUTZEN DEN DIENST, SEINE INHALTE UND ALLE DIENSTE ODER ARTIKEL, DIE ÜBER DIE DIENSTE ERHALTEN WERDEN, AUF EIGENES RISIKO. DER DIENST, SEINE INHALTE UND ALLE ÜBER DIE WEBSITE UND ERWEITERUNG ERHALTENEN DIENSTE ODER ARTIKEL WERDEN OHNE JEGLICHE GEWÄHRLEISTUNG AUF “AS IS”- UND “AS AVAILABLE”-BASIS ZUR VERFÜGUNG GESTELLT. KEINE PERSON, DIE MIT DEM DIENST VERBUNDEN IST, ÜBERNIMMT JEGLICHE GEWÄHRLEISTUNG ODER ZUSICHERUNG IN BEZUG AUF DIE VOLLSTÄNDIGKEIT, SICHERHEIT, ZUVERLÄSSIGKEIT, QUALITÄT, GENAUIGKEIT ODER ZUGÄNGLICHKEIT DES DIENSTES. OHNE EINSCHRÄNKUNG DES VORSTEHENDEN GEWÄHRLEISTEN WEDER “CURSOR STYLE” NOCH MIT “CURSOR STYLE” VERBUNDENE VERTRETER, DASS DIE WEBSITE, DIE ERWEITERUNG, IHRE INHALTE ODER JEGLICHE REPARATUR ZUVOR VERFÜGBAR SEIN SOLLTEN ODER DASS UNSERE ERWEITTERUNG, EINE WEBSITE ODER EIN SERVER, AUF DEM SIE SICH BEFINDET, OHNE VIREN ODER ANDERE SCHÄDLICHE KOMPONENTEN IST ODER DASS DIESE WEBSITE ODER JEGLICHE LEISTUNGEN ODER ARTIKEL DURCHGEFÜHRT, BEVORZUGT WERDEN.
<p> Unter keinen Umständen haften DER DIENST, SEINE VERBUNDENEN UNTERNEHMEN ODER LIZENZGEBER, DIENSTE, MITARBEITER, VERTRETER, BEAMTE ODER DIREKTOREN FÜR SCHÄDEN JEGLICHER ART, DIE WIR DEM DIENST GEGENÜBER FÜR JEGLICHE HAFTUNG GEGENÜBER. ODER SOLCHE ANDEREN WEBSEITEN ODER JEGLICHE DIENSTE ODER ARTIKEL, DIE IM DIENST ODER AUF ANDEREN WEBSITES ERHALTEN WERDEN, EINSCHLIESSLICH DIREKTER, BESONDERER ODER FOLGESCHÄDEN, EINSCHLIESSLICH KÖRPERLICHER VERLETZUNGEN, EMOTIONALER STÖRUNGEN, SCHÄDEN ODER ERWARTETER EINSPARUNGEN, NUTZUNGSAUSFALL, DATEN ODER ANDEREN BEDINGUNGEN. DIESE DEFINITION BEEINFLUSST KEINE VERANTWORTUNG, DIE GEMÄSS GELTENDEM RECHT, ZU DER AUCH BETRUG GEHÖREN KANN, NICHT AUSGESCHLOSSEN ODER BESCHRÄNKT WERDEN KANN. </p>
<p> Sie verpflichten sich, den “Cursor Style”, seine verbundenen Unternehmen, Lizenzgeber und Dienstleister sowie seine und deren jeweiligen leitenden Angestellten, Direktoren, Mitarbeiter, Auftragnehmer, Vertreter, Lizenzgeber, Lieferanten und Abtretungsempfänger vor jeglichen Ansprüchen und Verbindlichkeiten, Verlusten von Gerichtsurteilen, Kosten, Ausgaben oder Provisionen (einschliesslich Anwaltsgebühren) zu schützen, freizustellen und abzuwehren, die sich aus oder im Zusammenhang mit Ihrem Verstoss gegen diese Nutzungsbedingungen oder der Nutzung des Dienstes ergeben, einschliesslich, aber nicht beschränkt auf die Berücksichtigung jeglicher Nutzung der Inhalte, Dienste und Produkte der Website oder der Erweiterungen, ausser wie in diesen Nutzungsbedingungen ausdrücklich angegeben, oder Ihre Nutzung von Informationen, die Sie vom Dienst erhalten haben. </p>
<p> Sollte sich eine Bestimmung dieser Nutzungsbedingungen aus irgendeinem Grund für ungültig, rechtswidrig oder nicht durchsetzbar durch ein Gericht oder ein anderes zuständiges Gericht erweisen, sollte diese Bestimmung gestrichen oder auf ein Minimum beschränkt werden, so dass der Rest der Bestimmungen der Nutzungsbedingungen weiterhin in vollem Umfang bestehen bleibt. Die Nutzungsbedingungen, unsere Datenschutzbestimmungen und die Bedingungen für die Registrierung von Veranstaltungen stellen die alleinige und vollständige Vereinbarung zwischen Ihnen und dem "Cursor Style" in Bezug auf den Dienst dar und ersetzen alle vorherigen und gleichzeitigen Vereinbarungen, Übereinkünfte, Zusicherungen und Gewährleistungen, sowohl schriftliche als auch mündliche, in Bezug auf den Dienst. </p>
<p> Alle Bewertungen, Kommentare, Anfragen zum technischen Support und andere Nachrichten bezüglich des Dienstes sollten an die Support-Seite von "Cursor Style" im Chrome Web Store gerichtet werden. </p> ',
];
