<?php

return [
    'title' => 'Cursor Style - Polisi Kuki',
    'descr' => 'Satu polisi kuki apabila anda melawat laman web cursor.style atau sambungan “Cursor Style”. Beberapa peraturan yang perlu anda pertimbangkan semasa menggunakan produk kami.',
    'text' => '<h2> Polisi Kuki </h2>
<p> Apabila anda melawat laman web kami cursor.style atau sambungan "Cursor Style" dalam panel penyemak imbas anda, atau apabila anda berinteraksi dengan wakil kami ("Perkhidmatan"), kami akan menggunakan (dan membenarkan pihak ketiga menggunakan) suar web, kuki, tag piksel, skrip, tag, API dan teknologi lain ("Teknologi Penjejakan"). Ini dijelaskan dalam polisi ini ("Polisi Kuki"), yang merupakan sebahagian daripada <a href="/privacy"> Polisi Privasi </a> kami. </p>
<p> Teknologi penjejakan membolehkan kami mengumpul maklumat secara automatik tentang anda dan tingkah laku anda di Internet untuk meningkatkan navigasi anda pada Perkhidmatan kami, meningkatkan prestasi Perkhidmatan kami dan memudahkan pengalaman anda dalam Perkhidmatan kami. Kami juga menggunakan maklumat ini untuk mengumpul statistik mengenai penggunaan Perkhidmatan kami, menjalankan analisis, menyampaikan kandungan yang sesuai dengan minat anda, dan mentadbir perkhidmatan untuk Pengguna, pelanggan dan rakan kongsi kami. Kami juga membenarkan pihak ketiga mengumpul maklumat tentang anda menggunakan teknologi penjejakan. </p>
<p> Apakah kuki? Kuki adalah fail teks kecil (terdiri daripada huruf dan nombor sahaja) yang pelayan web letakkan pada komputer atau peranti mudah alih anda apabila anda melawat halaman web. Menggunakan kuki boleh membantu menjadikan Perkhidmatan kami lebih mesra pengguna, contohnya, mengingati pilihan bahasa dan tetapan anda. Anda boleh mendapatkan maklumat lanjut mengenai kuki di <a href="http://www.allaboutcookies.org"> allaboutcookies.org </a>. </p>
<p> Kuki digunakan secara meluas untuk prestasi laman web. Menggunakan kuki membolehkan anda menavigasi di antara halaman dengan cekap. Kuki mengingati pilihan anda dan menjadikan interaksi antara anda dan Perkhidmatan lebih lancar dan lebih cekap. </p>
<p> Kami menggunakan teknologi penjejakan apabila anda melawat atau mengakses Perkhidmatan kami (biasanya apabila anda melawat laman web kami) - ia dipanggil "Teknologi Penjejakan Pihak Pertama". Di samping itu, teknologi penjejakan disimpan oleh organisasi pihak ketiga yang lain (contohnya, penyedia perkhidmatan analisis kami, rakan perniagaan dan pengiklan) yang menyiarkan kandungan di Perkhidmatan kami - ia dipanggil "Teknologi Penjejakan Pihak Ketiga". Kedua-dua jenis teknologi penjejakan boleh disimpan sama ada untuk waktu lawatan anda ke Perkhidmatan kami, atau untuk lawatan berulang. </p>
<h3> Apakah jenis teknologi penjejakan yang kami gunakan? Terdapat lima jenis utama teknologi penjejakan: </h3>
<ul>
<li> <b> Teknologi penjejakan yang sangat diperlukan </b> <br> <p> Teknologi penjejakan ini diperlukan supaya anda boleh log masuk, menavigasi dan menggunakan fungsi Perkhidmatan kami atau menyediakan perkhidmatan yang anda minta (contohnya, nama pengguna anda). Kami tidak memerlukan persetujuan anda untuk menggunakan teknologi penjejakan ini. Teknologi penjejakan ini boleh digunakan untuk tujuan keselamatan dan integriti, contohnya, untuk mengenal pasti pelanggaran dasar kami, serta untuk ciri sokongan atau keselamatan. </p> </li>
<li> <b> Teknologi Penjejakan Fungsi </b> <br> <p>
Teknologi penjejakan ini membolehkan perkhidmatan kami mengingati pilihan anda (seperti bahasa) dan menyediakan ciri lanjutan dan diperibadikan. Contohnya, teknologi penjejakan ini digunakan untuk pengesahan (untuk mengingati apabila anda log masuk) dan menyokong fungsi lain Perkhidmatan kami. </p> </li>
<li> <b> Teknologi Penjejakan Prestasi </b> <br> <p>
Teknologi penjejakan ini mengumpul maklumat tentang aktiviti dalam talian anda (contohnya, tempoh lawatan anda ke Perkhidmatan kami), termasuk data tingkah laku dan petunjuk penglibatan kandungan. Teknologi penjejakan ini digunakan untuk analisis, penyelidikan dan statistik (berdasarkan maklumat agregat). </p> </li>
<li> <b> Teknologi penjejakan pemasaran atau pengiklanan </b> <br> <p>
Teknologi penjejakan ini digunakan untuk menyediakan anda tawaran istimewa dan pengiklanan berdasarkan minat anda, serta menjalankan kempen pemasaran e-mel. Mereka juga boleh digunakan untuk mengehadkan bilangan kali iklan dilihat, serta untuk mengukur keberkesanan kempen pengiklanan. Mereka biasanya dihoskan oleh pengiklan kami (contohnya, rangkaian iklan) dan memberi mereka idea tentang orang yang melihat dan berinteraksi dengan iklan mereka, melawat laman web mereka atau menggunakan aplikasi mereka. </p> </li>
<li> <b> Teknologi Penjejakan Media Sosial </b> <br> <p>
Laman web kami merangkumi fungsi rangkaian sosial, seperti butang Suka atau Kongsi di Facebook dan Vkontakte, atau perkhidmatan log masuk pihak ketiga. Fungsi ini sama ada disiarkan oleh pihak ketiga atau disiarkan secara langsung ke Perkhidmatan kami. Interaksi anda dengan ciri-ciri ini dikawal oleh penyataan privasi syarikat yang menyediakan ciri-ciri ini. </p> </li>
</ul>
<h3> Berikut ialah kuki yang boleh anda dapati dalam Perkhidmatan kami: </h3>
<ul>
<li> <b> Analitis Kuki </b> <br> <p> Teknologi penjejakan ini digunakan untuk mengumpul maklumat tentang cara anda berinteraksi dengan kandungan dalam Perkhidmatan kami, tujuan atribusi (contohnya, URL rujukan), dll. Kami menggunakan maklumat ini untuk menyusun laporan, mengira pendapatan yang disebabkan oleh kami, dan membantu kami memperbaiki Perkhidmatan dan menawarkan produk dan kandungan yang diperibadikan. </p> </li>
<li> <b> Google Analytics </b> <br> <p> Kuki ini digunakan untuk mengumpul maklumat tentang cara pelawat menggunakan Platform kami. Kami menggunakan maklumat ini untuk menyusun laporan dan untuk meningkatkan Platform. Kuki mengumpul maklumat dalam bentuk tanpa nama, termasuk bilangan pelawat Platform, dari mana pelawat datang ke Platform, dan halaman yang mereka lawati. <br> <a href = "https://policies.google.com/privacy?hl=en" > Polisi Privasi </a> </p> </li>
<li> <b> Pengurus Tag Google </b> <br> <p> Kuki ini dikaitkan dengan Pengurus Tag Google, yang kami gunakan untuk memuatkan skrip pada halaman laman web kami. <br> <a href = "https: / /policies.google.com/privacy?hl=en"> Polisi Privasi </a> </p> </li>
</ul>
<p> Sila ambil perhatian bahawa kami tidak mengiktiraf atau bertindak balas terhadap makluman penyemak imbas automatik mengenai teknologi penjejakan, termasuk permintaan Jangan Lacak. Walau bagaimanapun, terdapat pelbagai cara untuk mengurus dan mengurus tetapan kuki anda. Ingat bahawa apabila memadam atau menyekat kuki, sesetengah fungsi Perkhidmatan mungkin tidak berfungsi dengan betul atau tidak begitu cekap. </p>
<p> Kebanyakan penyemak imbas web memberikan anda beberapa maklumat umum tentang kuki, membolehkan anda melihat kuki apa yang disimpan pada peranti anda, membolehkan anda memadamkannya semua atau secara individu, dan juga membolehkan anda menyekat atau membenarkan penggunaan kuki untuk semua laman web atau laman terpilih secara individu. Anda juga boleh melumpuhkan kuki pihak ketiga secara berasingan. Sila ambil perhatian bahawa tetapan yang ditawarkan oleh penyemak imbas atau peranti selalunya hanya terpakai pada penyemak imbas atau peranti tertentu itu. </p>
<h3> Maklumat kuki biasanya terdapat di bahagian Bantuan penyemak imbas web. </h3>
<p> Berikut ialah pautan ke beberapa penyemak imbas web yang biasa digunakan: </p>
<p><a href="https://support.google.com/chrome/answer/95647?hl=en"> Chrome </a> <br>
<a href="https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies"> Internet Explorer dan Microsoft Edge </a> <br>
<a href="https://support.mozilla.org/en/kb/kuki-informaciya-kotoruyu-veb-sajty-hranyat-na-vas"> Mozilla Firefox </a> <br>
<a href="https://support.apple.com/ru-ru/guide/safari/sfri11471/mac"> Safari </a> </p>
<p> Anda boleh mematikan beberapa kuki pihak ketiga untuk penargetan / pengiklanan dengan mengklik pautan berikut: <a href="http://optout.networkadvertising.org/?c=1"> Memilih keluar daripada pengiklanan berasaskan minat </a>. </p>
				',
];
