<?php

return [
    'title' => 'Cursor Style - Polisi Privasi',
    'descr' => 'Dalam “Cursor Style,” tersedia di cursor.style atau melalui sambungan Chrome, salah satu keutamaan kami adalah privasi pelawat kami. Adalah dalam bahagian ini kami akan bercakap tentang semua aspek bekerja dengan sambungan.',
    'text' => '<h2> Polisi Privasi </h2>
                <p> Dalam Cursor Style, tersedia di <a href="https://cursor.style"> cursor.style </a> atau melalui sambungan Chrome, salah satu keutamaan kami ialah privasi pengunjung kami. Dokumen Polisi Privasi ini mengandungi jenis maklumat yang dikumpulkan dan direkodkan oleh laman web cursor.style, dan cara kami menggunakannya. Jika anda mempunyai soalan tambahan atau memerlukan maklumat lanjut mengenai Polisi Privasi kami, jangan teragak-agak untuk menghubungi kami. </p>
                <p> Sambungan "Cursor Style" dan laman web mengikuti tatacara standard untuk menggunakan fail log. Fail-fail ini mendaftarkan pelawat apabila mereka melawat laman web atau menggunakan sambungan kami. Semua syarikat hosting melakukan ini dan merupakan sebahagian daripada analisis perkhidmatan hosting. Maklumat yang dikumpulkan melalui fail log merangkumi alamat Protokol Internet (IP), jenis pelayar, Penyedia Perkhidmatan Internet (ISP), cap tarikh dan masa, halaman peralihan / keluar, dan mungkin bilangan klik. Ia tidak dikaitkan dengan sebarang maklumat yang boleh dikenal pasti secara peribadi. Tujuan maklumat ini adalah untuk menganalisis trend, mentadbir laman web dan mengembangkannya, mengesan pergerakan pengguna di laman web dan mengembangkannya, dan mengumpulkan maklumat demografi. </p>
                <p> Seperti laman web lain, cursor.style menggunakan kuki. Kuki ini digunakan untuk menyimpan maklumat, termasuk pilihan pelawat dan halaman di laman web yang dilawati atau dilawati oleh pelawat. Maklumat ini digunakan untuk mengoptimumkan pengalaman pengguna dengan menyesuaikan kandungan halaman web kami berdasarkan jenis pelayar pelawat dan / atau maklumat lain. Kami juga menggunakan iklan pihak ketiga di cursor.style untuk menyokong projek dan menyokong laman web kami. Beberapa pengiklan ini boleh menggunakan teknologi seperti kuki dan suar web apabila mereka mengiklankan di laman web kami, yang juga akan mengirimkan maklumat pengiklan ini (contohnya, Google melalui program Google AdSense), termasuk alamat IP anda, penyedia Internet anda, pelayar yang anda gunakan untuk melawat laman web kami, dan dalam beberapa kes, jika anda memasang Flash. Ini biasanya digunakan untuk tujuan penargetan geografi (contohnya, memaparkan iklan untuk penjualan barang di bandar anda) atau untuk memaparkan iklan tertentu berdasarkan laman web tertentu yang dilawati (contohnya, memaparkan pengumuman pembelian kepada mereka yang sering melawat laman web membeli-belah). </ P >
                <p> Anda boleh mematikan atau mematikan kuki kami atau pihak ketiga secara selektif dalam tetapan pelayar atau dengan menguruskan tetapan dalam program seperti Kaspersky, dan lain-lain. Namun, ini boleh mempengaruhi cara anda berinteraksi dengan laman web kami, serta dengan laman web lain. Ini mungkin termasuk ketidakupayaan untuk log masuk ke perkhidmatan atau program, seperti log masuk ke forum atau akaun. </p>
<p> Google adalah salah satu penyedia pihak ketiga di laman web kami. Ia juga menggunakan kuki, yang dikenali sebagai kuki DART, untuk memberikan iklan kepada pelawat ke laman web kami berdasarkan lawatan mereka ke cursor.style dan laman web lain di Internet. Namun, pelawat boleh memilih untuk tidak menggunakan kuki DART dengan mengunjungi dasar privasi Rangkaian Pengiklanan dan Kandungan Google di <a href="https://policies.google.com/technologies/ads"> alamat berikut </a>. Beberapa pengiklan di laman web kami boleh menggunakan kuki dan suar web. Setiap rakan pengiklanan kami mempunyai dasar privasi mereka sendiri untuk dasar mereka mengenai data pengguna. Anda boleh membaca lebih lanjut mengenai Polisi Privasi mereka <a href="https://policies.google.com/technologies/ads"> di sini </a>. </p>
                <p> Laman web kami menggunakan Google Analytics, perkhidmatan analisis web Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com (“Google Analytics” atau “Google”). Google Analytics menggunakan kuki yang disimpan di komputer anda untuk memudahkan analisis penggunaan laman web anda. Maklumat yang dihasilkan oleh kuki ini, seperti waktu, tempat dan kekerapan lawatan anda ke laman web kami, termasuk alamat IP anda, dipindahkan ke lokasi Google di AS dan disimpan di sana. Google juga boleh memindahkan maklumat ini kepada pihak ketiga jika diperlukan oleh undang-undang atau jika pihak ketiga memproses data ini bagi pihak Google. Google menyatakan bahawa ia tidak akan pernah mengaitkan alamat IP anda dengan data Google yang lain. Anda boleh mengelakkan penetapan kuki dengan mengubah tetapan perisian pelayar anda dengan sewajarnya, seperti yang dinyatakan dalam Polisi Privasi ini. Namun, anda harus sedar bahawa dengan cara ini anda tidak akan dapat menggunakan sepenuhnya semua fungsi laman web kami. </p>
                <p> Google Analytics juga menggunakan imej elektronik yang dikenali sebagai suar web (terkadang disebut GIF piksel tunggal) dan digunakan dengan kuki untuk mengumpulkan statistik agregat untuk menganalisis penggunaan laman web kami.
Anda boleh mendapatkan maklumat lebih lanjut mengenai cara memasang add-on pelayar yang anda pautkan di atas <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> pautan </a>.
Laman web ini menggunakan Google Tag Manager. Perkhidmatan ini membolehkan anda menguruskan tag laman web melalui antara muka. Pengurus Tag Google melaksanakan tag sahaja. Ini bermaksud bahawa kuki tidak ditetapkan dan tidak ada data peribadi yang direkodkan. Google Tag Manager melancarkan tag lain, yang seterusnya dapat merekodkan data. Namun, Google Tag Manager tidak mempunyai akses ke data ini. Sekiranya tag telah dilumpuhkan di peringkat domain atau kuki, ia disimpan untuk semua tag penjejakan, jika dilaksanakan menggunakan Google Tag Manager. Anda boleh mengetahui lebih lanjut mengenai Google Tag Manager dengan melayari <a href="http://www.google.com/tagmanager/use-policy.html"> pautan </a>. </p>
<p> Anda boleh membiasakan diri dengan senarai ini untuk mencari Polisi Privasi untuk setiap rakan pengiklanan "Cursor Style". Pelayan iklan pihak ketiga atau rangkaian iklan menggunakan teknologi seperti kuki, JavaScript atau suar web, yang digunakan dalam iklan dan pautan masing-masing, yang dipaparkan dalam “Cursor Style” dan dihantar terus ke pelayar pengguna. Mereka secara automatik mendapatkan alamat IP anda apabila ini berlaku. Teknologi ini digunakan untuk mengukur keberkesanan kempen pengiklanan mereka dan / atau untuk memperibadikan kandungan pengiklanan yang anda lihat di laman web yang anda lawati. Harap maklum bahawa “Cursor Style” tidak mempunyai akses atau kawalan ke atas kuki ini yang digunakan oleh pengiklan pihak ketiga. Polisi privasi Cursor Style tidak berlaku untuk pengiklan atau laman web lain. Oleh itu, kami mengesyorkan agar anda menyemak dasar privasi yang relevan dari pelayan iklan pihak ketiga ini untuk maklumat lebih lanjut. Ia mungkin merangkumi kaedah dan arahan mereka mengenai cara untuk memilih keluar dari pilihan tertentu. Anda boleh mendapatkan pautan ke Polisi Privasi Pihak Ketiga ini di atas atau di laman web perkhidmatan pihak ketiga ini. </p>
                <p> Anda boleh mematikan kuki dalam tetapan pelayar anda. Untuk mengetahui lebih lanjut mengenai pengurusan kuki dalam pelayar web tertentu, anda boleh menemuinya di laman web pelayar masing-masing. Bahagian lain dari keutamaan kami adalah untuk menambahkan perlindungan kanak-kanak semasa menggunakan Internet. Kami menggalakkan ibu bapa dan penjaga untuk memerhati, mengambil bahagian dan / atau memantau dan mengarahkan aktiviti mereka di Internet. "Cursor Style" tidak mengetahui mengumpulkan maklumat peribadi daripada kanak-kanak di bawah usia 13 tahun. Sekiranya anda fikir anak anda telah memberikan maklumat tersebut di laman web kami, kami sangat mengesyorkan agar anda menghubungi kami dengan segera dan kami akan melakukan yang terbaik untuk segera mengeluarkan maklumat tersebut daripada rekod kami. Polisi Privasi ini hanya berlaku untuk aktiviti dalam talian kami dan sah untuk pelawat ke laman web kami berkaitan dengan maklumat yang mereka kongsikan dan / atau kumpulkan dalam “Cursor Style”. Dasar ini tidak terpakai untuk sebarang maklumat yang dikumpulkan di luar talian atau melalui saluran selain daripada laman web ini. </p>
                <p> Anda boleh membaca lebih lanjut mengenai penggunaan kuki dalam Perkhidmatan kami dalam <a href="/cookie-policy"> Polisi Kuki </a> kami. </p> ',
];
