<?php

return [
    'title' => 'Сursor Style - Terma penggunaan produk kami',
    'descr' => 'Terma penggunaan dimasukkan antara anda dan “Cursor Style” (“Perkhidmatan”, “kami” atau “Perkhidmatan”). Perkhidmatan ini ditawarkan dan tersedia kepada pengguna berumur 13 tahun dan ke atas sahaja untuk kegunaan peribadi dan bukan untuk kegunaan komersial.',
    'text' => '<h2> Terma Perkhidmatan </h2>
<h3> SILA BACA TERMA DAN SYARAT INI SEBELUM MENGGUNAKAN LAMAN WEB DAN SAMBUNGAN. </h3>
<p> Terma penggunaan ini dimasukkan antara anda dan "Cursor Style" ("Perkhidmatan", "kami" atau "Perkhidmatan"). Terma dan syarat berikut, bersama dengan sebarang dokumen yang mereka nyatakan secara jelas dengan rujukan (secara kolektif, ini "Terma Penggunaan"), mengawal akses dan penggunaan anda terhadap laman web cursor.style dan sambungan pelayannya, termasuk kandungan, fungsi dan perkhidmatan yang ditawarkan pada atau melalui perkhidmatan kami (bersama "Perkhidmatan"). </p>
<p> Dengan menggunakan laman web atau sambungan, anda menerima dan bersetuju untuk mematuhi Terma Penggunaan ini. Sekiranya anda tidak bersetuju dengan Terma Penggunaan ini atau <a href="/privacy"> Polisi Privasi </a> kami, anda tidak seharusnya mengakses atau menggunakan Laman Web dan Sambungan tersebut. </p>
<p> Perkhidmatan ini ditawarkan dan tersedia hanya untuk pengguna yang berumur 13 tahun ke atas untuk kegunaan peribadi dan bukan untuk kegunaan komersial. Menggunakan Perkhidmatan ini, anda menyatakan dan memberi jaminan bahawa anda (I) berumur 13 tahun atau lebih, (II) anda tidak dilarang daripada menggunakan Laman Web sesuai dengan undang-undang yang berlaku, dan (III) anda menggunakan Perkhidmatan hanya untuk keperluan peribadi anda. Sekiranya anda tidak memenuhi syarat ini, anda tidak seharusnya mengakses atau menggunakan Perkhidmatan. </p>
<p> Kami boleh menyemak semula dan mengemas kini Terma Penggunaan ini dari semasa ke semasa mengikut budi bicara kami. Semua perubahan berkuat kuasa sebaik sahaja penerbitan mereka. Penggunaan berterusan anda terhadap Perkhidmatan selepas penerbitan Terma Penggunaan yang disemak semula bermaksud bahawa anda menerima dan bersetuju dengan perubahan tersebut. Anda dijangka melawat halaman ini dengan kerap untuk mengikuti perkembangan sebarang perubahan kerana ia mengikat anda. </p>
<p> Kami berhak untuk menarik diri atau meminda Laman Web dan Sambungan ini, sebarang perkhidmatan atau bahan yang kami sediakan di Laman Web dan Sambungan, mengikut budi bicara kami sendiri, tanpa pemberitahuan. Kami tidak menjamin bahawa laman web, sambungan atau sebarang kandungan kami di dalamnya akan sentiasa tersedia atau akan terganggu. Kami tidak akan bertanggungjawab sekiranya atas sebarang sebab semua atau sebahagian daripada Perkhidmatan tidak tersedia pada bila-bila masa atau dalam tempoh tertentu. Dari semasa ke semasa, kami boleh menyekat akses ke bahagian tertentu Laman Web atau Sambungan atau keseluruhan Perkhidmatan untuk pengguna. </p>
<p> Anda bertanggungjawab untuk mengambil semua langkah yang diperlukan untuk memastikan bahawa anda mempunyai akses ke Perkhidmatan. Memastikan bahawa semua orang yang mengakses Perkhidmatan melalui sambungan Internet anda menyedari Terma Penggunaan ini dan mematuhinya. Untuk mengakses Perkhidmatan atau sebahagian daripada sumber yang ditawarkannya, anda mungkin diminta untuk memberikan maklumat tertentu atau maklumat lain. Anda bersetuju bahawa semua maklumat yang anda berikan kepada kami dengan menggunakan Perkhidmatan ini atau sebaliknya, termasuk tetapi tidak terhad kepada penggunaan sebarang ciri interaktif dalam Perkhidmatan, dikawal oleh <a href="/privacy"> Polisi Privasi </a> kami, dan anda bersetuju dengan semua tindakan yang kami ambil mengenai maklumat anda. sesuai dengan <a href="/privacy"> Polisi Privasi </a> kami. </p>
<p> Anda mesti berhati-hati semasa memasukkan maklumat peribadi ke dalam Perkhidmatan pada komputer awam atau berkongsi supaya orang lain tidak dapat melihat atau merekod maklumat peribadi anda. Laman web, sambungan dan semua kandungannya, fungsi dan ciri (termasuk, tetapi tidak terhad kepada, semua maklumat, sambungan, teks, imej, imej, dan kursor, serta reka bentuk, pemilihan dan penempatannya) adalah milik "Cursor Style", pemberi lesen atau pembekal lain bahan tersebut dilindungi oleh hak cipta, tanda dagangan, paten, rahsia perdagangan dan undang-undang hak harta intelek atau hak harta yang lain. </p>
<p> Terma Penggunaan ini membenarkan anda menggunakan Laman Web hanya untuk penggunaan peribadi, bukan komersial anda. Anda tidak boleh mengeluarkan semula, mengedarkan, mengubah suai, membuat karya terbitan, menerbitkan semula, memuat turun, menyimpan atau mengirim sebarang bahan di Laman Web kami, kecuali untuk kes berikut: anda boleh menggunakannya untuk keperluan peribadi, anda boleh mencetak atau memuat turun satu salinan sejumlah halaman yang munasabah Laman Web dan Sambungan atau kandungannya untuk penggunaan peribadi, bukan komersial, dan bukan untuk penghasilan semula, penerbitan atau pengedaran selanjutnya. </p>
<p> Anda tidak boleh mengubah suai salinan sebarang bahan dari laman web atau sambungan ini dan kandungannya. Padam atau ubah suai sebarang hak cipta, tanda dagangan, atau notis hak milik lain daripada salinan laman web dan sambungan ini. Anda tidak boleh mempunyai akses ke atau menggunakan untuk sebarang tujuan komersial sebarang bahagian Laman Web atau sambungan, serta sebarang perkhidmatan atau bahan yang tersedia melalui Laman Web atau Sambungan. </p>
<p> Sekiranya anda mahu menggunakan sebarang bahan di Laman Web atau Sambungan selain daripada yang disenaraikan di bahagian ini, hantarkan permintaan di halaman sokongan Chrome Web Store. </p>
<p> Sekiranya anda mencetak, menyalin, mengubah suai, memuat turun, atau sebaliknya menggunakan atau menyediakan orang lain untuk mengakses sebarang bahagian Laman Web atau Sambungan yang melanggar Terma Penggunaan, hak anda untuk menggunakan Laman Web dan Sambungan segera ditamatkan, dan anda mesti, mengikut budi bicara kami, mengembalikan atau memusnahkan sebarang salinan bahan yang anda miliki. Sebarang penggunaan laman web sambungan yang tidak dibenarkan secara jelas oleh Terma Penggunaan ini melanggar Terma Penggunaan ini dan mungkin melanggar hak cipta, tanda dagangan dan undang-undang lain. </p>
<p> Nama "Cursor Style", logo "Cursor Style" dan semua nama, logo, imej, kursor dan nama perkhidmatan, reka bentuk, dan slogan yang berkaitan adalah tanda dagangan "Cursor Style" atau sekutunya atau pemberi lesennya. Anda tidak boleh menggunakan tanda sedemikian tanpa kebenaran bertulis terlebih dahulu daripada Perkhidmatan. Semua nama, logo, produk dan nama perkhidmatan, reka bentuk dan slogan lain di laman web ini dan dalam sambungan adalah tanda dagangan pemilik masing-masing. Anda hanya boleh menggunakan Perkhidmatan untuk tujuan yang sah dan sesuai dengan Terma Penggunaan ini. </p>
<h3> Anda bersetuju UNTUK TIDAK menggunakan Perkhidmatan: </h3>
<ul>
<li> Dalam sebarang cara yang melanggar sebarang undang-undang atau peraturan persekutuan, wilayah, tempatan atau antarabangsa yang terpakai (termasuk, tetapi tidak terhad kepada, sebarang undang-undang mengenai eksport data atau perisian ke Rusia dan negara lain). </li>
<li> Untuk tujuan eksploitasi, bahaya, atau percubaan untuk menggunakan atau membahayakan kanak-kanak di bawah umur, mendedahkan mereka kepada kandungan yang tidak sesuai, meminta maklumat yang mengenal pasti mereka, atau sebaliknya. </li>
<li> Untuk mengirim, mengetahui menerima, memuat turun, menggunakan atau menggunakan semula sebarang bahan yang tidak mematuhi Terma Penggunaan ini. </li>
<li> Menghantar atau membeli penghantaran sebarang iklan atau bahan promosi tanpa persetujuan bertulis kami terlebih dahulu, termasuk sebarang "surat yang tidak diminta", "surat berantai" atau "spam" atau sebarang tawaran serupa yang lain. </li>
<li> Untuk menyamar atau cuba menyamar sebagai pekerja “Cursor Style”, pengguna lain, atau mana-mana orang atau organisasi lain (termasuk tetapi tidak terhad kepada menggunakan alamat e-mel atau nama samaran yang berkaitan dengan mana-mana yang di atas). </ li >
<li> Penyertaan dalam sebarang tindakan lain yang membatasi atau menghalang penggunaan Perkhidmatan atau penggunaan sesiapa sahaja, atau yang, seperti yang kami tentukan, boleh membahayakan Perkhidmatan atau pengguna Perkhidmatan atau menjadikan mereka bertanggungjawab. </li> </ul>
<h3> Di samping itu, anda bersetuju UNTUK TIDAK: </h3>
<ul>
<li> Gunakan Perkhidmatan dalam sebarang cara yang boleh melumpuhkan, membebankan, merosakkan atau merendahkan operasi laman web, mengembangkan atau mengganggu penggunaan Perkhidmatan oleh mana-mana pihak lain, termasuk keupayaan mereka untuk mengambil bahagian dalam tindakan masa nyata melalui Perkhidmatan. </li>
<li> Gunakan sebarang alat automation, proses atau cara untuk mengakses Perkhidmatan untuk sebarang tujuan, termasuk memantau atau menyalin sebarang bahan dalam Perkhidmatan. </li>
<li> Gunakan sebarang proses manual untuk mengesan atau menyalin sebarang bahan di Perkhidmatan atau untuk sebarang tujuan lain yang tidak dibenarkan tanpa persetujuan bertulis kami terlebih dahulu. </li>
<li> Gunakan sebarang peranti, perisian atau prosedur yang mengganggu operasi normal Perkhidmatan. </li>
<li> Memperkenalkan sebarang virus, kuda Trojan, cacing, bom logik atau bahan lain yang berbahaya atau berbahaya secara teknologi. </li>
<li> Cuba mendapatkan akses yang tidak dibenarkan, mengganggu, merosakkan atau mengganggu sebarang bahagian Perkhidmatan, pelayan di mana Perkhidmatan disimpan, atau mana-mana pelayan, komputer atau pangkalan data yang disambungkan ke Perkhidmatan. </li>
<li> Serang Perkhidmatan menggunakan serangan penafian perkhidmatan atau serangan penafian perkhidmatan teragih. </li> </ul>
<p> Maklumat yang diberikan pada atau melalui Perkhidmatan diberikan semata-mata untuk tujuan maklumat umum. Kami tidak menjamin ketepatan, kesempurnaan atau kegunaan maklumat ini. Anda bergantung pada maklumat tersebut semata-mata atas risiko anda sendiri. Kami menafikan semua tanggungjawab dan liabiliti yang timbul daripada sebarang kebergantungan anda, pengunjung lain ke Perkhidmatan atau sesiapa sahaja yang mungkin dimaklumkan mengenai sebarang kandungannya, terhadap bahan tersebut. </p>
<p> Perkhidmatan ini merangkumi kandungan yang disediakan oleh pihak ketiga, termasuk bahan yang disediakan oleh pengguna lain dan pemberi lesen pihak ketiga, pemudah cara, agregator dan / atau perkhidmatan pelaporan. Semua pernyataan dan / atau pendapat yang dinyatakan dalam bahan ini, serta semua artikel dan jawapan kepada soalan dan kandungan lain, kecuali kandungan yang disediakan oleh Perkhidmatan, semata-mata pendapat dan tanggungjawab orang atau organisasi yang menyediakan bahan ini. Bahan-bahan ini tidak semestinya mencerminkan pandangan Perkhidmatan. Kami tidak bertanggungjawab kepada anda atau mana-mana pihak ketiga untuk kandungan atau ketepatan sebarang bahan yang disediakan oleh pihak ketiga. </p>
<p> Kami boleh mengemas kini kandungan Perkhidmatan dari semasa ke semasa, tetapi kandungannya tidak semestinya lengkap atau terkini. Sebarang bahan di Perkhidmatan mungkin sudah lapuk pada bila-bila masa, dan kami tidak diminta untuk mengemas kini bahan tersebut. Kami boleh mengemas kini, mengubah suai, mengubah maklumat dan kandungan di Laman Web dan dalam Sambungan, membuat sebarang perubahan dan kemas kini mengikut keputusan kami sendiri. </p>
<p> Semua maklumat yang kami kumpulkan pada Perkhidmatan ini tertakluk pada Polisi Privasi kami. Dengan menggunakan Perkhidmatan, anda bersetuju dengan semua tindakan yang diambil oleh kami berkaitan dengan maklumat anda sesuai dengan <a href="/privacy"> Polisi Privasi </a>. </p>
<p> Syarat tambahan juga mungkin berlaku untuk bahagian, perkhidmatan atau ciri Perkhidmatan tertentu. Semua syarat dan ketentuan tambahan sedemikian dengan ini dimasukkan dengan rujukan ke Terma Penggunaan ini.
Anda boleh memaut ke laman web atau sambungan kami jika anda melakukannya dengan cara yang jujur ​​dan sah dan tidak merosakkan reputasi kami atau gunakannya, tetapi anda tidak boleh menetapkan pautan sedemikian rupa untuk menawarkan sebarang bentuk perkaitan, sokongan atau pengesahan dari pihak kami tanpa kebenaran bertulis kami. </p>
<p> Perkhidmatan mengandungi pautan ke laman web dan sumber lain yang disediakan oleh pihak ketiga, pautan ini disediakan hanya untuk kemudahan anda. Ini termasuk pautan yang terdapat dalam iklan, termasuk iklan sepanduk dan pautan tajaan. Kami tidak mengawal kandungan laman web atau sumber ini dan tidak bertanggungjawab untuk mereka atau untuk sebarang kehilangan atau kerosakan yang mungkin disebabkan oleh penggunaannya. Sekiranya anda memutuskan untuk mengakses sebarang laman web pihak ketiga yang berkaitan dengan Perkhidmatan ini, anda melakukannya atas risiko anda sendiri dan sesuai dengan syarat penggunaan laman web tersebut. Kami berhak untuk membatalkan kebenaran untuk memaut tanpa notis terlebih dahulu. </p>
<p> Anda faham bahawa kami tidak dapat dan tidak menjamin atau menjamin bahawa fail yang tersedia untuk dimuat turun melalui Internet atau di Laman Web tidak akan mengandungi virus atau kod hasad lain. Anda bertanggungjawab untuk pelaksanaan prosedur dan titik kawalan yang mencukupi untuk memenuhi keperluan khas anda untuk perlindungan anti-virus dan ketepatan input dan output data, serta untuk mengekalkan cara luaran ke laman web kami untuk memulihkan sebarang data yang hilang. KAMI TIDAK AKAN BERTANGGUNGJAWAB ATAS SEBARANG KEROSAKAN ATAU KECEDERAAN YANG DISEBABKAN oleh pengedaran penafian PERKHIDMATAN, virus atau teknologi-malware LAIN YANG DIPEROLEHI MELALUI PERKHIDMATAN, ATAU DENGAN MEMUAT TURUN SEBARANG BAHAN YANG DITERBITKAN PADA INI, ATAU SEBARANG LAMAN WEB, BERKAITAN MUNGKIN, MENGINFET ATAU MEROSAKKAN PERALATAN KOMPUTER ANDA, PERISIAN KOMPUTER, DATA. </p>
<p> ANDA MENGGUNAKAN PERKHIDMATAN, KANDUNGANNYA DAN SEBARANG PERKHIDMATAN ATAU ITEM YANG DIPEROLEH MELALUI PERKHIDMATAN ATAS RISIKO ANDA SENDIRI. PERKHIDMATAN, KANDUNGANNYA DAN SEBARANG PERKHIDMATAN ATAU ITEM YANG DIPEROLEH MELALUI LAMAN WEB DAN SAMBUNGAN, DISEDIAKAN ATAS SYARAT “SEBAGAIMANA ADANYA” DAN “SEBAGAIMANA TERSEDIA”, TANPA SEBARANG WARANTI. SESIAPA YANG BERKAITAN DENGAN PERKHIDMATAN TIDAK MEMBERI SEBARANG WARANTI ATAU PERWAKILAN BERKAITAN DENGAN KELENGKAPAN, KESELAMATAN, KEBOLEHPERCAYAAN, KUALITI, KETEPATAN ATAU AKSES PERKHIDMATAN. TANPA HAD DI ATAS, TIADA WAKIL “CURSOR STYLE” MAUPUN BERKAITAN DENGAN WAKIL “CURSOR STYLE” TIDAK MENJAMIN BAHAWA LAMAN WEB, SAMBUNGAN, KANDUNGANNYA ATAU SEBARANG PEMBAIKAN HENDAKLAH SEBELUM INI TERSEDIA DITETAPKAN BAHAWA SAMBUNGAN KAMI, LAMAN WEB ATAU PELAYAN YANG MELETAKKANNYA, AKAN TANPA VIRUS ATAU KOMPONEN BERBAHAYA LAIN ATAU LAMAN WEB INI ATAU SEBARANG PERKHIDMATAN ATAU ITEM YANG DILAKSANAKAN, DIUTAMAKAN.
<p> Dalam keadaan apa pun PERKHIDMATAN, SEKUTUNYA ATAU ATAU PEMBERI LESEN, PERKHIDMATAN, PEKERJA, EJEN, PEGAWAI atau PENGARAH TIDAK BERTANGGUNGJAWAB TERHADAP KEROSAKAN APA PUN, KAMI PERKHIDMATAN TERHADAP SEBARANG LIABILITI. ATAU LAMAN WEB LAIN ITU ATAU SEBARANG PERKHIDMATAN ATAU ITEM YANG DIPEROLEH DALAM PERKHIDMATAN ATAU KE LAMAN WEB LAIN, TERMASUK SEBARANG KEROSAKAN LANGSUNG, KHAS ATAU AKIBAT, TERMASUK KECEDERAAN DIRI, gangguan emosi, KEROSAKAN ATAU SIMPANAN YANG DIJANGKA, KEHILANGAN PENGGUNAAN, DATA ATAU SYARAT LAIN. TAKRIF TIDAK MEMPENGARUHI SEBARANG TANGGUNGJAWAB YANG TIDAK BOLEH DIKECUALIKAN ATAU DIBATASKAN SESUAI DENGAN UNDANG-UNDANG YANG BERKENAAN YANG MUNGKIN TERMASUK PENIPUAN. </p>
<p> Anda bersetuju untuk melindungi, menanggung rugi dan menafikan “Cursor Style”, sekutunya, pemberi lesen dan penyedia perkhidmatan, serta pegawai, pengarah, pekerja, kontraktor, ejen, pemberi lesen, pembekal yang berkaitan dan dari sebarang tuntutan dan liabiliti, kehilangan keputusan mahkamah, kos, perbelanjaan atau komisen (termasuk yuran peguam) yang timbul daripada atau berhubung dengan pelanggaran anda terhadap Terma penggunaan ini atau penggunaan Perkhidmatan, termasuk tetapi tidak terhad kepada perwakilan sebarang penggunaan kandungan, perkhidmatan dan produk Laman Web atau Sambungan, kecuali sebagaimana yang diperuntukkan secara jelas dalam Terma Penggunaan ini, atau penggunaan anda terhadap sebarang maklumat yang diterima daripada Perkhidmatan. </p>
<p> Sekiranya sebarang peruntukan Terma Penggunaan ini didapati tidak sah, menyalahi undang-undang atau tidak dapat dikuatkuasakan oleh mahkamah atau tribunal lain yang mempunyai bidang kuasa yang kompeten atas sebarang sebab, peruntukan sedemikian harus dibatalkan atau dihadkan pada tahap minimum, supaya baki peruntukan Terma Penggunaan akan berterusan sepenuhnya. Terma Penggunaan, Polisi Privasi kami dan syarat untuk mendaftarkan acara membentuk perjanjian yang tunggal dan lengkap antara anda dan "Cursor Style" mengenai Perkhidmatan dan menggantikan semua perjanjian, perjanjian, representasi dan waranti sebelumnya dan serentak, baik secara bertulis dan lisan, mengenai Perkhidmatan. </p>
<p> Semua ulasan, komen, permintaan sokongan teknikal, dan mesej lain mengenai Perkhidmatan harus ditujukan ke halaman sokongan “Cursor Style” di Chrome Web Store. </p> ',
];
