<?php

return [
    'halo_descr' => 'Halo je franšiza medijskih vsebin s področja boja in fantazije, ki jo je ustvaril Bungie. Temelji na izvirni trilogiji videoiger streljanja v prvi osebi. Zgodba se vrti okoli dogodkov v življenju Master Chiefa, enega izmed skupine super vojakov s kodnim imenom Spartanci, in njegove spremljevalke, umetne inteligence Cortane. Uspeh iger je pripeljal do širitve franšize v druge medije: vesolje Halo trenutno obsega številne knjige, grafične romane, stripe, kratke filme, animacije in celovečerne filme.',
    'halo_short_descr' => 'Dotaknite se artefaktnega kazalca, morda ste izbrani.',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'LOL Surprise punčke so se zaljubile v otroke in jim osvojile srca od prvih minut. In to ni presenetljivo, ker takšen uspeh temelji na skrivnosti, pričakovanju čudeža, prijetnega presenečenja, ki navdušuje ne le otroke, ampak tudi njihove starše. Skrivnost darila se otroku razkrije šele po končnem odpakiranju. V vsakem primeru so LOL punčke privlačnega dizajna, intrige, velikega števila neverjetnih in realističnih dodatkov in prijetnih malenkosti, pa tudi najvišje kakovosti izdelave in detajlov igrače.',
    'lol_surprise_short_descr' => 'Kul simpatične punčke za poznavalce lepih presenečenj',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Serija se vrti okoli tekmovanja, kjer 456 igralcev, ki so vsi v globokih finančnih dolgovih, tvega svoja življenja, da bi igrali vrsto smrtonosnih otroških iger za možnost osvojitve milijarde vredne nagrade. Notri čaka mamljiva nagrada s smrtonosno visokimi stavami. Naslov serije izhaja iz istoimenske korejske otroške igre. Hwang je prišel na idejo na podlagi lastnih ekonomskih težav v zgodnjem življenju, pa tudi razrednih razlik v Južni Koreji in kapitalizmu.',
    'squid_game_short_descr' => 'Izberite pravo obrazno masko igralca, ko greste na vse ali nič.',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter je glavni junak serije romanov angleške pisateljice JK Rowling. Na svoj enajsti rojstni dan Harry izve, da je čarovnik in je namenjen na Bradavičarko, šolo čarovništva, kjer bo vadil čarovnijo pod vodstvom ravnatelja Albusa Dumbledorja in drugih šolskih profesorjev. Harry tudi odkrije, da je že znan v čarovniški skupnosti romana in da je njegova usoda povezana z usodo Mrlakensteina, nevarnega temnega čarovnika.',
    'harry_potter_short_descr' => 'Kaj boste storili s čarobno palico iz zbirke kazalcev Harryja Potterja?',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics je založba stripov, znana po ustvarjanju znanih super junakov, kot so Spider-Man, Iron Man, Captain America, Hulk, Thor, Avengers, Guardians of the Galaxy, X-Men, Fantastic Four in Deadpool. Marvelovi najbolj znani negativci vključujejo Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom in Magneto. Marvel Comics in DC Comics sta skupaj sodelovala pri več križarskih projektih in tudi skupaj ustanovila namensko kratkotrajno znamko Amalgam Comics.',
    'marvel_comics_short_descr' => 'Superjunak živi v vsakem izmed nas - izberi svojega',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Dobrodošli nazaj v Cookie Kingdom v Cookie Run: Kingdom avtorja Devsisters, ljubkem strateškem RPG-ju, postavljenem v vesolje Cookie Run. Zdaj, ko je GingerBrave pobegnil iz pečice zlobne čarovnice, je čas, da sestavi ekipo piškotkov in se poda na iskanje, da ponovno zgradi padlo Cookie Kingdom. Odkrijte resnico o propadu Kraljestva in sestavite skupino najmočnejših piškotkov Kraljestva, da premagate temne sile, ki želijo GingerBrave preprečiti izpolnitev njegove usode.',
    'cookie_run_kingdom_short_descr' => 'Mali bojevniki naravnost iz pečice',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact je pustolovska igra z odprtim svetom. To pomeni, da vas na drugi strani reke ali gore čaka nova, čudovita pokrajina, le pametno morate uporabljati svojo energijo. Če naletite na tavajočo vilo ali čuden mehanizem, si upajte in poskusite razvozlati njihovo skrivnost. Toda kaj obljubljajo - težave ali prijetno presenečenje - lahko ugotovite le vi! Na prostrani celini Teyvat boste obiskali sedem kraljestev, našli sopotnike z različnimi veščinami in se borili proti močnim sovražnikom v iskanju pogrešanega ljubljenega človeka.',
    'genshin_impact_short_descr' => 'Postanite elementarni mojster sedmih kraljestev',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Ko se starodavna prerokba uresniči in kraljestvo potone v objem zime, se trije neustrašni junaki - princesa Anna, pogumni Kristoff in njegov zvesti severni jelen Sven - odpravijo v gore, da bi našli Annino sestro Elso, ki lahko odstrani hladno uro iz dežele. Na poti jih čaka veliko težkih presenečenj in vznemirljivih dogodivščin. Srečanje mističnih trolov, srečanje s šarmantnim snežakom po imenu Olaf, gorski vrhovi, strmejši od Everesta, in veliko čarovnije. Junaki se morajo upreti mogočnim elementom, da bi rešili kraljestvo in tiste, ki so jim dragi.',
    'frozen_short_descr' => 'Zbirka kazalcev Ledeno kraljestvo omogoča enostavno lomljenje ledu!',
    'frozen' => 'Ledeno kraljestvo',
    'stranger_things_descr' => 'Minilo je nekaj več kot šest mesecev od konca tretje sezone. Joyce, Will, Eleven in Jonathan so se preselili v Kalifornijo, kjer je deklica žrtev ustrahovanja v šoli. Ostali se začnejo bojevati z novo pošastjo iz vzporednega sveta, ki se je pojavila v Hawkinsu. Imenujejo jo Vecna ​​po liku iz družabne igre Dungeons & Dragons. Psihološko vpliva na najstnike, nato pa se psihično povzpne v glavo in ubija. Vzporedno izvesta Joyce in Murray, da je Jim Gopper živ, in gresta za njim v sovjetski zapor v Kamčatki. In Eleven se bo morala vrniti in povečati svoje moči, pa tudi spoznati svojo pomembno vlogo pri ustvarjanju iste pošasti v Gokinsu.

Scenaristi niso spremenili taktike zapleta, ki jim je bila všeč v zadnjih nekaj sezonah. V četrti sezoni so veliko skupino glavnih likov razdelili na skupine, zanje prišli do težkih nalog in na koncu svoje zgodbe zgradili skupaj v neverjetnem zaključku. Ponujamo vam, da podrobno razumete vse te dogodivščine s pomočjo kolekcije kazalcev Stranger Things.',
    'stranger_things_short_descr' => 'Kaj se bo zgodilo naslednjega? - Kazalci Stranger Things 4',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars je izvirni način, ki se je prvič pojavil v Minecraftu. Naloga igralcev je bila, da uporabnik zaščiti svojo bazo in posteljo.

Roblox vsak dan prinaša bolj razburljive igre in BedWars ni nobena izjema. In stvar je v tem, da če imate radi Bed Wars in se branite v svoji sobi, je to naslov za vas, ker vas popelje nazaj v otroštvo, čeprav tokrat digitalno.

Vse kar morate storiti je braniti svojo posteljo pred napadalci s svojim partnerjem. Vstopite v čakalnico, izberete s kom boste igrali in voila, gre samo za zaščito.

Seveda, ko gre za obrambo, boste imeli nekaj težav in obstajajo določeni viri, predmeti in predmeti, ki vam bodo pomagali zmagati. Na primer, ekskluzivne preobleke, ki jih boste našli v zbirki kazalcev Bed Wars.',
    'roblox_bed_wars_short_descr' => 'Zaščitite svojo posteljo z kazalci Roblox Bed Wars',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'Na rojstni dan Narutoja Uzumakija je legendarni demon, lisica z devetimi repi, napadel vas Konoha. Četrti Hokage je za ceno svojega življenja rešil vas, tako da je demona zapečatil v novorojenega Narutoja, nevedoč ga obsodil na življenje sovraštva s strani sokrajanov.
Kljub pomanjkanju talenta na mnogih področjih ninjutsuja, nemiru in ošabnosti, Naruto sanja, da bi postal Hokage, najmočnejši ninja v vasi. V želji po priznanju, ki ga ni dobil, trdo dela in trenira skupaj s soigralcema Sasukijem Uchiha in Sakuro Haruno ter svojim mentorjem Kakashijem Hatakejem. On in njegovi partnerji bodo morali na poti do svojih dragih sanj prestati marsikaj: bitke, ljubezen, prijateljstvo, izdajstvo, žejo po moči. Zbirka kazalcev animeja Naruto vam bo pomagala krmariti po lastni poti!',
    'naruto_anime_short_descr' => 'Koračajte po svoji nindža poti z Naruto anime kurzorji',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'Akcija se odvija v obdobju Taisho. Že od antičnih časov krožijo govorice, da v gozdu živijo humanoidni demoni, ki se prehranjujejo z ljudmi in hodijo ponoči ter iščejo novo žrtev. Ampak ... to je samo legenda, kajne?..

Tanjiro Kamado je najstarejši sin v družini, ki je izgubil očeta in skrbel za svojo družino. Nekega dne gre v bližnje mesto prodajat oglje. Ko se zjutraj vrne, fant pred seboj odkrije grozljivo sliko: vsi sorodniki so bili brutalno ubiti, edina preživela pa je Nezuko, mlajša sestra, ki se je spremenila v demona, vendar še ni izgubila vse svoje človečnosti.

Od tega trenutka naprej začneta Tanjiro in Nezuko dolgo in nevarno potovanje, na katerem namerava fant najti morilca in odkriti način, kako pozdraviti svojo sestro. Toda ali lahko otroci premagajo vse težave in se vrnejo domov? Odgovor že poznate, in če ne - nastavite kazalce Demon Slayer s karakterji iz ene najpopularnejših mang.',
    'demon_slayer_anime_short_descr' => 'Kazalci Demon Slayer - za prave nočne lovce',
    'demon_slayer_anime' => 'Anime Demon Slayer',
    'bts_descr' => 'BTS je sedemčlanska fantovska skupina pod BigHit Music. Debitirali so 13. junija 2013 s singlom "No More Dream". Na Japonskem so debitirali 24. decembra 2014 s studijskim albumom Wake Up.

Ime skupine izhaja iz korejskega izraza Bangtan Sonyeondan, kar pomeni "skavti neprebojni za naboje". Po besedah J Hopea ime označuje željo skupine, da bi blokirala stereotipe, kritike in pričakovanja, ki so usmerjeni v najstnike kot nabojev.

Zbirka kazalcev, posvečenih skupini, vključuje vse člane skupine, tukaj kazalec Kim Nam Joona (aka RM), kazalec Kim Seok Jina (Jin), kazalec Min Yoongija (Suga), kazalec Jung Ho Suka (J-Hope), kazalec Park Ji Mina (Jimin), kazalec Kim Tae Hyuna (V) in kazalec Jeon Jungkooka (Jungkook).',
    'bts_short_descr' => 'Spoznajte svoje idole z kazalci BTS',
    'bts' => 'BTS',
    'miraculous_descr' => 'Miraculous: Zgodbe o Črni mački in Pikapolonici, bolj znano kot Miraculous Pikapolonica in Črna mačka, so dogodivščine superjunakov iz risanke o dveh sošolcih, ki pod maskami igrajo vlogo branilcev Pariza pred zlobnežem, ki v vsaki epizodi izumi nov način, kako škodovati mestu. Miraculous je narejen v Franciji z uporabo CGI in animacije. Miraculous ni le animirana serija, temveč tudi zbirka stripov, izdanih po vsem svetu. Serija je zelo priljubljena med mladim občinstvom.

Zgodba se odvija v Parizu, kjer sta Marinette in Adrian dijaka v sodobni šoli. Dodeljena jima je bila vloga, da postaneta izbrana v boju proti zlu in rešujeta svoje domače mesto. Njihov cilj je zaščititi ljudi pred Akumami. Ta majhna bitja v obliki metuljev lahko naseljajo osebo in jo spremenijo v zlikovca.

Marinette se lahko spremeni v pikapolonico, Adrian pa v Črno mačko, vendar se, presenetljivo, med delom v paru ne prepoznata pod maskami superjunakov.

Pomagajte Črni mački in Pikapolonici rešiti Pariz z našimi kurzorji z vašimi najljubšimi liki. Katerega lika boste izbrali za kurzor? Bo to kurzor Miraculous Pikapolonice ali morda Tikki\'s ljubka majhna Pikapolonica ali kurzor Črna mačka? Ali morda Queen Bee s kurzorji Rena Rouge? Izbira je vaša!',
    'miraculous_short_descr' => 'Pridružite se rangom superjunakov z zbirko kazalcev Lady Bug in Cat Noir.',
    'miraculous' => 'Miraculous: Zgodbe o Črni mački in Ladybug',
    'talking_tom_descr' => 'Serija spremlja vsakdanje življenje govorečega Toma in njegovih prijateljev. Tom in njegov nerodni poslovni partner Ben nenehno razvijata mobilne aplikacije in druge izume, da bi dosegla slavo in bogastvo ter se poskušata pokazati svetu, kar pa se vedno izjalovi. Tomova punca Angela poskuša biti pevka, ne glede na to, kaj počne, da bi to dosegla. Tomov sosed Ginger zelo pogosto pride sem, da bi nagajal z vragolijami. Neumnji najboljši prijatelj in sostanovalec Hank je gospodinjec, gleda ZELO TV. In nekdanja disidentska pop zvezda Becca Sparkles je postala Angelin nova sostanovalka in se zdi, da se je zaljubila v Hanka. Vendar, ne glede na to, kako hude so stvari vseh oblik in velikosti, naj bo to zlobni izvršni direktor, Tomov skrivnostni novi sosed ali le nesreča v Benovi novi stvaritvi, se bo druščina zabavala ne glede na vse in si vedno zapomnila eno stvar, ki jih drži skupaj: prijateljstvo se nikoli ne konča, tako kot se ne konča naša ljubezen do likov serije, zato si zdaj lahko nastavite kazalec Talking Tom ali kazalec Ben ali morda kazalec Angela, kazalec Oliver!',
    'talking_tom_short_descr' => 'Pogovorimo se o vašem najljubšem liku iz zbirke kazalcev Talking Tom',
    'talking_tom' => 'Talking Tom in prijatelji',
    'lego_descr' => 'Podjetje The LEGO Group je bilo ustanovljeno leta 1932 in takrat je štelo le 7 ljudi. Cilj ekipe Lego je bil ustvariti igrače, ki razvijajo otrokovo ustvarjalnost, domišljijo in iznajdljivost. Neverjetno dejstvo je, da so LEGO elementi v vseh svojih različicah, od njihovega nastanka leta 1949, ostali združljivi med seboj. Vsi predmeti, ustvarjeni kasneje, so še vedno združljivi s predmeti, ki se izdajajo danes, kljub spremembam v oblikovanju in obliki skozi leta.

LEGO kocka je osnova, ki je votel plastični blok, ki se poveže z drugimi podobnimi kockami. Toda Lego seti vsebujejo tudi druge dele, kolesa, figure, platforme in celo elektronska vezja s senzorji in električnimi motorji. Lahko sestavljate modele avtomobilov, letal, vlakov, ladij, stavb, robotov. LEGO se drži ideje modularnosti, ki otrokom jasno kaže, kako reševati določene probleme, razvijati domišljijo, fino motoriko rok in spretnosti sestavljanja. LEGO kocke so izdelane z neverjetno natančnostjo in se popolnoma prilegajo skupaj za osupljivo natančnost 10 mikronov.

Nedavno je bilo ustvarjenih veliko priljubljenih 3D animiranih Lego zgodb, kjer liki iz kompletov oživijo in postanejo udeleženci neverjetnih dogodivščin. Če želite kul kurzor, boste v naši zbirki Lego Cursors našli številne like iz Lego TV serij in animiranih filmov. Lego Ninjago Kurzsor, Lego Batman Kurzsor, Lego Ninjago Kurzsor, Lego Wyldstyle Kurzsor in še veliko več.',
    'lego_short_descr' => 'Zgradite svoj sanjski brskalnik z zbirko kazalcev Lego.',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Po uspešnem financiranju prek Kickstarterja je leta 2017 Team Cherry izdal multiplatformsko PC igro Hollow Knight. To je zgodba o brezimnem vitezu in njegovih odkritjih v kraljestvu žuželk Hallownest. Igra je bila upravičeno prepoznana kot ena najboljših v žanru metroidvania.

Igranje Hollow Knight temelji na raziskovanju sveta igre. Premagovanje ovir, reševanje ugank in iskanje skrivnosti ter boj z sovražniki. Igralec ima edinstven nabor izboljšav in trikov za raziskovanje sveta in boj v bitkah. Gibajoč se iz cone v cono, igralec premaguje šefe in dobiva potrebne izboljšave za nadaljnji napredek. Posledično morajo igralci obiskati že predelana območja, da bi našli skrivnosti in šli skozi zgodbo. In to je vznemirljivo tudi zato, ker se cone vsakič spreminjajo in prinašajo nova presenečenja in izkušnje. Igro je mogoče igrati na različne načine, saj obstaja več različnih poti med conami. Ko greste skozi zgodbo, odprete zemljevid cone, vendar morate najprej dobiti zemljevid.

Glavno orožje junaka je žebelj, ki je nekoliko podoben meču, orožje se lahko izboljša pri kovaču, prav tako se lahko naučite različnih veščin pri uporabi orožja, kar razširi raznolikost napadov. Z napadom na sovražnike kopičite poseben vir, ki ga lahko kasneje uporabite za izboljšave ali zdravljenje.
Uživajte v igranju Hollow Knight in ne pozabite na naše Hollow Knight kazalce s svojim najljubšim likom. Naša zbirka vključuje kazalec Mister Mushroom, kazalec Quirrel, kazalec igle Hornet, kazalec Old Nail, kazalec Myla in druge.',
    'hollow-knight_short_descr' => 'Poskusite se ne izgubiti v kraljestvu žuželk z uporabo kolekcije kazalcev Hollow Knight.',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman je glavni lik v seriji. Stickmin, prej brez imena, je začel kot manjši tat z željo po hitrem zaslužku. Po pobegu iz zapora West Mesa pa se v njegovem življenju zgodi veliko sprememb in postane znan kriminalec, potem ko ukrade tunizijski diamant. Henry ima izbiro - postati uspešen vladni agent, lovec na glave, vodja kriminalne organizacije, kiborg ali nadaljevati kriminalno pot sam. Igra navdušuje ljubitelje žanra s številnimi dogodivščinami in skrivnostmi, v naši novi zbirki kazalcev Henry Stickman pa boste našli njegove smešne like, vključno s kazalcem Henry Stickmin, kazalcem Charles Calvin, kazalcem Reginald Copperbottom, kazalcem Right Hand, kazalcem Ellie Rose in drugimi!',
    'henry-stickmin_short_descr' => 'Načrtujte svoj pobeg od dolgčasa z zbirko kurzorjev Henry Stickmin',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'Zelo priljubljena spletna igra Adopt Me je bila lansirana leta 2017 in je postala najbolj priljubljena na igralni platformi Roblox. Bistvo igre je zelo preprosto - pridobiti jajca z hišnimi ljubljenčki in skrbeti zanje.

Virtualni hišni ljubljenčki so razdeljeni v 5 razredov, nekateri od njih so zelo redki in dragi, medtem ko je druge zelo enostavno dobiti. To so skupine Uncommon, kot je Blue Dog, Common, Rare kazalec, na primer kazalec miške Adopt Me Monkey, pa tudi ultra-redki, kot je kazalec Koala, in Legendary, kazalec Dragon in Accept me unicorn. Če ima igralec štiri odrasle hišne ljubljenčke iste vrste, se lahko združijo v neon hišnega ljubljenčka, kot je kazalec igre Neon Horse ali Adopt Me Neon Starfish. Z združevanjem štirih navadnih hišnih ljubljenčkov lahko naredite neon hišnega ljubljenčka, ki resnično sveti, iz neon hišnih ljubljenčkov pa lahko ustvarite mega-neon hišnega ljubljenčka.

Nakupi v igri Adopt Me! se izvajajo z virtualno valuto Roblox - tako imenovano Robux, igra pa ima tudi svojo valuto - Bucks. Skrb za svojega ljubljenčka, poleg zabave, lahko zaslužite bucks, samo ga nahranite, položite spat ali preberite pravljico, na splošno, veliko zanimivih stvari.

Zdaj lahko oboževalci igre Roblox "Adopt Me!" okrasijo svoj kazalec igre z najljubšim hišnim ljubljenčkom!',
    'adopt-me_short_descr' => 'Zabavajte se s simpatičnimi hišnimi ljubljenčki v naši zbirki kazalcev iger Adopt Me!',
    'adopt-me' => 'Adopt Me!',
    'among-us_descr' => 'Among Us temelji na znani igri vlog "Mafia". Načrtovano je bilo, da bo igra ekskluzivna za mobilne naprave, ker je imela samo eno mapo. Igra je hitro postala popularna. Kasneje je razvojna ekipa dodala način za več igralcev in leta 2019 sta bili izdani dve dodatni mapi.
Among Us je igra z zornim kotom od zgoraj navzdol v tretji osebi, ki igralcu omogoča gibanje v vseh smereh. V eni rundi lahko igra od štiri do deset igralcev. Na začetku igre je vsakemu skrivoma dodeljena vloga izdajalca ali člana posadke. Izdajalec (v ruski prevedbi "Traitor") se lahko skriva v prezračevalni loputi, sabotira in ubija člane posadke. Njegov cilj je uničiti vse člane posadke ali uničiti vesoljsko plovilo s sabotažo. Cilj ladijske posadke je rešiti različne uganke, pripravljene zanje na začetku igre. Če vsak od članov posadke opravi vse naloge, bodo izdajalci izgubili. Prav tako lahko ladijska posadka doseže zmago z izločitvijo izdajalcev med glasovanjem.
Izdajalci lahko občasno sabotirajo in če se okvare ne odpravijo v 30 sekundah, bo posadka izgubila. Pred začetkom igre lahko izberete barvo lika, za katerega igrate, modro, rdečo, rumeno, sivo - kakršnokoli že! In ne pozabite si nastaviti ustrezen kurzor iz nove zbirke Among Us!',
    'among-us_short_descr' => 'Ne se pustite preslepiti v tej zapleteni vesoljski igri z kazalci Among Us',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Ustvarjalec serije "Steven Universe" je bila Rebecca Sugar. Znana je po svojem prejšnjem delu, ki se imenuje Pustolovščina. Prva epizoda Steven Universe je bila objavljena na platformi YouTube spomladi leta 2013. Jeseni pa jo je ameriški kanal Cartoon Network začel predvajati svojim gledalcem. Od takrat je bilo izdanih 6 sezon. Šesta obljublja, da bo zadnja.
Kar zadeva zaplet animirane serije, se vrti okoli ekipe Crystal Gems. Sestavljajo jo tuja bitja z značilnimi imeni: Pearls, Amethyst in Pomegranate. Ampak je še en udeleženec v njem, v vlogi katerega deluje navaden fant Stephen. Skupaj iščejo pošasti in jih poskušajo nevtralizirati, da ne bi zavzele Zemlje za osebne koristi. Proti njim stojita Jasper in Peridot - sel iz njihovega domačega planeta, ki želita premagati Gems in vključiti Cluster.
Če ste oboževalec Steven Universe in želite videti like iz animirane serije kjer koli, namestite razširitev Cursor Style! Zakaj to storiti? Dodate lahko zbirko, namenjeno "Steven Universe" in standardni kazalec miške spremenite v enega od vaših najljubših likov.',
    'steven_universe_short_descr' => 'Odkrij skrivnost draguljev s kazalci Steven Universe',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'Animirana serija z naslovom "Družinski človek" je v celotni zgodovini svojega obstoja 4-krat prejela nagrado Emmy in 3-krat nagrado "Annie". Animirana serija zasmehuje boleče teme ameriške družbe, kot so: feminizem, suženjstvo, debelost, politika itd. Za razliko od drugih del se tukaj uporabljajo vložki z šalami in sarkazmom. Poleg tega v mnogih primerih niso integrirani v zaplet, ampak obstajajo sami po sebi.
Ena epizoda animirane serije nastaja več kot 10 mesecev. Zakaj tako dolgo? Ker je vsa animacija narisana ročno. Zaradi tega nekateri dogodki, ki jih pokriva delo, izgubijo relevantnost. Ampak kljub temu je serija zelo zanimiva in pridobiva naklonjenost gledalcev po vsem svetu. Navsezadnje, kdo se ne rad dobro nasmeji politikom, zvezdnikom ali ljudem, ki počnejo norčije in s tem presenečajo ali celo šokirajo navadne ljudi.
Ali imate radi "Družinskega človeka"? Imate edinstveno priložnost, da navaden kazalec miške spremenite v katerega koli lika iz te animirane serije! Kaj moram storiti? Samo namestite razširitev brskalnika “Cursor Style”, ji dodajte zbirko, posvečeno “Družinskemu človeku”, in uživajte v neverjetni preobrazbi!',
    'family_guy_short_descr' => 'Zbirka kazalcev družine Griffin za poznavalce posebnega humorja',
    'family_guy' => 'Družinski človek',
    'cute_cursors_descr' => 'Zagotovo ste slišali izraz "Lepota bo rešila svet?" Torej, veliko ljudi, zlasti dekleta, se strinja s to izjavo. Zato se trudijo, da bi se obkrožili z vsem najlepšim in prijetnim za oko. To so lahko roza tapete v spalnici, mehke igrače, blazine, vezenine z biseri, dragocen nakit itd. Na zunaj vse skupaj izgleda zelo ljubko in celo malo otročje. Toda vsak od nas je v srcu malo otrok, zakaj mu torej ne bi dovolili, da pokaže svojo domišljijo?
Nežnost v nas lahko vzroči veliko. Na primer, sočutne oči mucka, ki želi, da ga bo nekdo pobožal ali nahranil. Večbarvna mavrica, ki pokuka po spomladanskem dežju in se blešči z vsemi barvami na soncu. Otrok, ki so ga pogostili s čokolado in se jo je odločil deliti s svojo punco ali fantom. Razlogov za ganjenost je kar nekaj in odločili smo se, da jih uporabimo kot kazalce.
Ste naveličani dolgočasne bele puščice v vašem brskalniku? Zamenjajte jo z nečim ljubkim iz naše zbirke! Na primer, roza in belim samorogom, žalostnim paradižnikom, godrnjajočim oblakom, bodečim kaktusom v obliki mačke ali čemerkoli si želite. Vse kar morate storiti je, da namestite razširitev Cursor Style in vanjo dodate zbirko ljubkih kazalcev. In naj živi rešitelj sveta - lepota!',
    'cute_cursors_short_descr' => 'Svet bo prijaznejši z zbirko ljubkih kazalcev',
    'cute_cursors' => 'Ljubki Kazalci',
    'web_media_descr' => 'V moderni realnosti skoraj vsi uporabljajo internet. Začenši z malčki in končajoč s upokojenci. Nekdo brska z brskalnikom, drugi gleda videoposnetke na YouTubu, tretji pa potrebujejo omrežje za komunikacijo z ljubljenimi. Nobeden od teh uporabnikov si ne more predstavljati dneva brez svetovnega spleta.
Starejši ljudje pogosto sedijo na družbenem omrežju, kot sta Facebook ali VK. Prav tako pogosto komunicirajo s svojimi otroki in vnuki na Skypu. To je še posebej priročno, če otroci in starši živijo v različnih mestih ali celo državah.
Mladi raje komunicirajo prek Viberja ali Telegrama, nalagajo fotografije na Instagram, se smejijo FB memom. Videoposnetki reakcij ljudi na YouTubu pridobivajo milijone ogledov, prav tako različne potegavščine ali družbeni eksperimenti. Na Tik-Toku na stotine tisoč ljudi pleše, kaže čarovniške trike in se izraža.
Vas zanima ali pogosto uporabljate neko vrsto vira iz sfere spletnih medijev? Se želite znebiti dolgočasne miškine puščice v brskalniku? Nato namestite razširitev in spremenite privzeti kazalec na naš kreativni! Lahko je kazalec za YouTube, kazalec za Viber, kazalec za Google Chrome ali drugih virov.',
    'web_media_short_descr' => 'Živite v sodobnem ritmu z zbirko kazalcev spletnih medijev',
    'web_media' => 'Spletni mediji',
    'bobs_burgers_descr' => 'Animirana serija Bob\'s Burgers je zaplet animacijskega dela in karizma likov. In sodeč po nominaciji za nagrado Emmy in priznanju dela kot ene najboljših risank na svetu, je Bob\'s Snack resnično poskrbel za odmev.
Zaplet animirane serije se vrti okoli družine Boba Belcherja. Ta oseba je lastnik restavracije v prvem nadstropju, v drugem pa živi s svojimi najdražjimi. Bob ima vedro ženo Lindo in 3 otroke: Gene, Louise in Tino. Fant sanja o glasbeni karieri, najstarejša hči Tina je zelo prijazna, a nerodna, najmlajša pa - Louise je še vedno nagajiva in pogosto spravlja svojo družino v neprijeten položaj. Glavni konkurent Bob\'s Burgers je picerija Jimmyja Pesta. Kot bi lahko ugibali, se lastnik te picerije imenuje Jim in on in Bob se sovražita. Vse to je bilo prikazano tako, da je izgledalo komično, ne resno. Zato številni njihovi spopadi povzročajo le nasmeh.
Če imate radi animirano serijo “Bob\'s Burgers” in želite videti njegove like ne le na zaslonu računalnika ali TV-ju, namestite razširitev, dodajte zbirko in spremenite kazalec miške v brskalniku na katerega koli od likov iz te risanke!',
    'bobs_burgers_short_descr' => 'Bob dela burgerje, mi pa izdelujemo kazalce Bob\'s Burgers.',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'Zgodovina video igre "Kirby" se je začela že v 90. letih prejšnjega stoletja. Sestavljena je iz številnih serij, ki so jih razvili Nintendo in HAL Laboratory. Igra je namenjena otrokom od enega leta in pol do 8 let. O njeni priljubljenosti lahko sodimo po številu prodanih izvodov. Več kot 34 milijonov po vsem svetu.
Glavni lik Kirby je istoimensko rožnato bitje. Živi na planetu z imenom Pop Star in ga občasno ščiti pred različnimi nevarnostmi. Kirby lahko vdihne nekatere predmete in svoje sovražnike, da se nato nauči njihovih sposobnosti: boj iz oči v oči, posedovanje meča, bruhanje ognja itd. Vendar se rožnati napihovalnik ne le bori s sovražniki, ampak tudi rešuje različne uganke, potuje v druge države in lahko celo leti v ravni.
To video igro lahko igrate na konzolah Nintendo ali Game Boy. V vseh serijah so ljubki junaki, dobra grafika in smešni zvočni posnetki. Mimogrede, v skoraj 30 letih od izida prve različice je svet uspel videti 20 serij Kirby. Ta indikator je skupaj z večmilijonskim obsegom prodanih izvodov pomagal, da je igra v TOP 50 najuspešnejših in iskanih videoiger v igralni industriji.
Imate radi Kirbyja, da bi radi videli ta lik kjer koli je to mogoče? Potem uporabite zbirko Kirby in spremenite običajni kazalec miške v glavnega junaka svoje najljubše video igre! Prepričani smo, da vam bo nov videz kazalca všeč.',
    'kirby_short_descr' => 'Poskusite vdihniti celotno zbirko kazalcev Kirby',
    'kirby' => 'Kirby',
    'undertale_descr' => 'V davnih časih Zemljo niso poseljevali le ljudje, temveč tudi pošasti. Zaradi nesoglasij med njimi je izbruhnila vojna, ki se je končala v prid človeške rase. Sedem čarovnikov je pognalo pošasti pod zemljo in jih tam za vedno zaprlo z urokom bariere. Vendarle je bil le en vhod v goro Ebott, kar je otrok izkoristil. Zanj boste igrali tako, da boste zagnali računalniško igro Undertale.
To igro je razvil Toby Fox - dobro znan programer iz Združenih držav. Sprva so v njej lahko uživali lastniki osebnih računalnikov, ki poganjajo operacijske sisteme Microsoft Windows in Linux, nato pa so prišli na vrsto uporabniki igralnih konzol.
Kakšen je pomen te igre? Fant potuje skozi podzemlje, ki ga poseljujejo pošasti. Nekatere so takoj sovražne, druge pa se rade pogovarjajo. Igralec lahko izbere enega od dveh načinov vedenja: izogniti se nasilju ali se boriti. V prvem primeru bo prehod igre lažji, v drugem pa ravno obratno - težji. Od te izbire sta odvisna tudi zaplet in konec, ki se lahko veja in spreminja.
Če imate radi Underground Tale in bi radi videli njegove like v svojem brskalniku, namestite razširitev in dodajte ustrezno zbirko kazalcev! Spremenite dolgočasni kazalec miške v eno od pošasti ali glavnega junaka Undertala!',
    'undertale_short_descr' => 'Čas je, da se z miškami iz igre Undertale izkopljete iz luknje',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune je igra vlog, izdana za računalnike pred nekaj leti. Ustvaril jo je isti programer, ki je razvil Undertale. Vendar si ti dve igri skoraj nista podobni, čeprav imata nekaj skupnih likov in lokacij.
V Deltarune je več glavnih likov. To je študent Chris, ki ga je mogoče nadzorovati, in očarljiva pošast Susie, ki je neobvladljiva. Oba lika padeta v svet teme, kjer srečata enega od njegovih prebivalcev - Ralsayja. Pove jim, da so pravzaprav bitja svetlobe, ki imajo poslanstvo - zaustaviti pretok temne energije v mračnem svetu. Da bi to naredili, morajo prizanesati lokalnim pošastim in se poskušati izogniti boju z njimi, čeprav je to včasih precej težko narediti.
Igralec ima preprosto izbiro: ali prizanesti temnim bitjem ali jih napasti. Ker Susie ni ljubiteljica polovičnih ukrepov, v mnogih primerih izbere bitko. Zato Chris nima druge izbire, kot da podpira svojo punco in ji pomaga v bitkah.
Ali imate radi igro Deltarune? Potem stilizirajte svoj kazalec miške v brskalniku za enega od njenih likov! To lahko storite z našo razširitvijo. Namestite jo, dodajte zbirko “Rune Delta” in jo aktivirajte! Zdaj vaša puščica ni več ista kot vsi ostali in je postala Chris, Susie ali eno od bitij temnega sveta.',
    'deltarune_short_descr' => 'Potopite se v temni svet s to zbirko kazalcev',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario je serija računalniških iger, ki jih je izdal Nintendo. Prva in najpopularnejša igra se je imenovala Super Mario Bros. Luč sveta je ugledala leta 1985. Kasneje je bila uvrščena v Guinnessovo knjigo rekordov. Od takrat je bilo izdanih več kot 20 iger, od katerih ima vsaka svojo zgodbo. Leta 2019 se je pojavila nova različica, imenovana Super Mario Maker 2. Kljub izboljšanju grafike so slog in liki ostali enaki, kar prikliče nostalgijo po Super Mariu iz 80-ih let.
Glavni junak je še vedno vodovodar Mario. V zgodbi zadnje različice igre grad princese ni ostal nepretrešen. Mario ga mora obnoviti, pri čemer mora zaslužiti kovance, ki so mu plačani za naloge. Skupaj ima ta igra več kot 100 stopenj različne zahtevnosti z možnostjo modifikacije. Tudi v Super Mario Maker 2 so novi načini igre. Hkrati lahko igrate štiri od njih in takoj ko se eden konča, se šteje, da je raven dokončana. Obstajajo tudi načini, kot so: Mario Marathon, Duel in Ninjik races.
Obožujete Super Maria in vse, kar je povezano s to čudovito igro? Potem nastavite kazalce miške, narejene v slogu tega platformerja! Prepričani smo, da vam bodo všeč kazalec Mario, kazalec Luigi, kazalec Princess Peach in drugi kazalci, ki so predstavljeni v naši zbirki!',
    'super_mario_short_descr' => 'Podajte se skozi kraljestvo gob z zbirko kazalcev Super Maria',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls je bil ustvarjen skupaj s korporacijo Disney Television Animation in Alexom Hirschem. Premiera je bila izdana leta 2012 in prikazana na Disney Channelu. Celotna prva sezona animirane serije se je tam vrtela. Dve leti kasneje je bila izdana druga sezona, ki so jo gledalci lahko spremljali na prejšnjem kanalu in na Disney XD. Žal oboževalci serije Gravity Falls niso dočakali tretje in naslednjih sezon. Ustvarjalci so se odločili, da se omejijo na dve sezoni brez nadaljevanj.
Kar zadeva zaplet te animirane slike, se vsa akcija dogaja v izmišljenem mestu, imenovanem Gravity Falls. Tja prideta dvojčka, ki jima je ime Mabel in Dipper. Ostajata pri svojem bratrancu Stanku. Ima lastno turistično trgovino s spominki. Ko se bratom prične dolgčas z "ne-počenjanjem nič", se podata v iskanje dogodivščin. Eden od njiju najde v gozdu čuden dnevnik, ki pripoveduje o anomalijah tega mesta. Dvojčka se odpravita v iskanje njegovega avtorja in naletita na nenavadna bitja in kraje. Če vas ta animirana serija zanima in ste bili nekoč oboževalci njenih likov, vam priporočamo našo zbirko kazalcev miške v slogu Gravity Falls!',
    'gravity_falls_short_descr' => 'Podajte se na avanturo s kazalci Gravity Falls',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'O takšni znani animirani seriji, kot so Simpsonovi, je slišal prav vsak. Tudi tisti, ki niso nikoli gledali, vedo za obstoj rumenih likov. In oboževalci so navdušeni, ko izide nova sezona njihovega najljubšega risanega filma. Mimogrede, jeseni 2019 je izšlo 31 sezon. Prva pa se je na televizijskih zaslonih pojavila leta 1989. Fox jo je začel predvajati in to še vedno počne zaradi visokih ocen in naklonjenosti občinstva.
Simpsonovi so satirični žanr, ki se dotika relevantnih tem. To je lahko življenjski slog povprečnega Američana, politična in verska vprašanja, "zvezdniške" trike zvezdnikov, feminizem, istospolne poroke. Na splošno vse, kar je povezano z lokalnimi in globalnimi dogodki, pri katerih sodelujejo Združene države Amerike.
Dogajanje animirane serije poteka v neobstoječem mestu Springfield. Dejansko je v Ameriki veliko mest s tem imenom. Morda je bilo zato izbrano, da občinstvo ne bi povezovalo dogajanja na zaslonih z določeno lokacijo, ampak bi le ugibalo, kje bi se to lahko zgodilo.
Najverjetneje ste oboževalec Simpsonov. V nasprotnem primeru, zakaj bi brali to besedilo do konca? Če je temu tako, imate možnost dolgočasen kazalec miške zamenjati s kazalcem, ki je narejen v slogu te animirane serije.',
    'simpsons_short_descr' => 'Zabavna majhna družina z kazalci Simpsons',
    'simpsons' => 'The Simpsons',
    'youtubers_descr' => 'Platforma za videoposnetke YouTube se je pojavila leta 2005. Sprva so bili videoposnetki tam objavljeni samo zaradi samoizražanja ali obveščanja o nečem. Vendar se je sčasoma vse to razvilo v dobičkonosno podjetje, ki uspešnim uporabnikom YouTuba prinaša na tisoče, včasih tudi milijone dolarjev na mesec. Bolj popularen kot je vlogger (oseba, ki vodi video blog), več lahko zasluži prek svojega kanala.
Koliko zasluži petletna vloggerka, katere starši jo vodijo do najzanimivejših atrakcij in snemajo dogajanje s kamero? Samo kako se otrok zabava v otroških parkih, kar izraža čustva, kako se norčuje in vse to. Znesek je res osupljiv - danes je kanal otroka pridobil skoraj 47 milijonov naročnikov in začel ustvarjati prihodek v višini 5 milijonov rubljev na mesec.
Nekdo objavlja videoposnetke, kjer razpravlja o računalniških igrah, nekdo oddaja beatbox ali prireja potegavščine mimoidočim na ulici. Nekateri posvečajo svoje videoposnetke občutljivim temam, kot je odnos med moškimi in ženskami. Bolj kot uporabniki YouTuba všečkajo te posnetke, večja je priljubljenost vloggerja.
Zbirki je že dodan kazalec PewDiePie, kazalec Shane Dawson, kazalec Ray William Johnson, kazalec Zoella, kazalec MyLifeAsEva in drugi.',
    'youtubers_short_descr' => 'Nova generacija zvezd je vedno na spletu v naši kolekciji YouTubers.',
    'youtubers' => 'YouTuberji',
    'pusheen_short_descr' => 'Dodajte nekaj udobja v svoj brskalnik s kolekcijo kazalcev Pusheen',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'Prva serija animiranega dela “Rick in Morty” je izšla leta 2013. Ta risanka se lahko pripiše neposredno k dvema žanroma: znanstvena fantastika in komedija. Njena ustvarjalca sta bila Dan Harmon in Justin Royland. Sprva so bile vse serije predvajane na kanalu Cartoon Network, šele nato so bile podvojene v spletnih kinematografih in gostovanjih videoposnetkov. Na vsake nekaj let izidejo nove sezone Ricka in Mortyja, novembra 2019 pa je izšla četrta sezona, ki se je izkazala za nič manj zanimivo kot prejšnje. Zgodba animirane serije se vrti okoli genija in hkrati norega znanstvenika po imenu Rick, pa tudi njegovega neopaznega vnuka - Mortyja. Ta dva lika povezujejo skupne pustolovščine na najbolj nenavadnih krajih. In tja prideta na letečem krožniku, ki se lahko premika skozi medprostorski tunel. Kot ste morda uganili, je ta animirana serija malo podobna filmu Nazaj v prihodnost, vendar še vedno ni njena animirana različica. Kljub temu so ga mnogi kritiki pohvalili za humorne epizode, ustvarjalnost in izvirnost. Želite videti Ricka ali Mortyja ne samo v seriji tega dela, ampak tudi v brskalniku? Če je tako, namestite razširitev in dodajte našo zbirko, posvečeno vaši najljubši risanki! Tukaj je kazalec Ricka Sancheza, kazalec Mortyja Smitha, kazalec portalske pištole in seveda kazalec gospoda Meeseeksa.',
    'rick_and_morty_short_descr' => 'Nehajte godrnjati, samo uporabite kazalce iz zbirke Rick and Morty',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Ljubitelji baseballa se najdejo po vsem svetu. To še posebej velja za prebivalce držav, kot so: ZDA, Kitajska, Kuba, Južna Koreja, Japonska in Venezuela. V nasprotju z razširjenim prepričanjem baseball ni nastal v Ameriki, ampak v Angliji. Prvi omembi in opis baseballa sta se pojavila v davnem letu 1744, v angleški izdaji. Po 145 letih so si Američani to iznajdbo prisvojili zase, kljub dejstvom.
National League je bila ustanovljena leta 1876. Je del Major lige v Kanadi in Združenih državah Amerike. Danes je v Nacionalni baseball ligi 15 ekip. V zadnjem delu vsake sezone pride čas končnice, v kateri sodelujejo 4 najboljše ekipe. Tako se razkrije zmagovalec celotne National League. Potem ima zmagovalna ekipa možnost igrati proti zmagovalcu iz American League v World Series.
Vas zanima baseball ali celo navijate za eno od ekip? Potem počastite svojo najljubšo ekipo tako, da nastavite kazalce miške v obliki njenih atributov! Spremenite dolgočasen videz kazalca v brskalniku v znano identiteto baseballa! Spremeniti puščico v igralčev kij ali čelado v kateri koli od ekip National League, ki že vključujejo kazalnik New York Yankees, kazalnik Great Falls Dodgers, kazalnik Boston Red Sox, kazalnik Baltimore Orioles, kazalnik Oakland Athletics.',
    'mlb_teams_short_descr' => 'Zbirka kazalcev ekip MLB za vse naše oboževalce.',
    'mlb_teams' => 'Ekipe MLB',
    'brawl_stars_descr' => 'Brawl Stars je mobilna igra v žanru MOBA od podjetja Supercell. Kljub izidu kone 2018, je igra pridobila veliko popularnost, predvsem zaradi obilice bojnih načinov in barvitih, fantastičnih junakov - borcev. Igralec ima veliko izbire - 32 unikatnih likov in vsak od njih ima svoj nabor sposobnosti in veščin. Vsak junak ima tudi svojo pasivno veščino, ki je na voljo prek zabojčkov s plenom. Igralci se lahko borijo v več načinih, na primer, "Nagrada za zajetje" - zmaga ena od dveh ekip, ki je zbrala več zvezd, s ubijanjem nasprotnikov. V načinu "rop" je potrebno razbiti sefe nasprotnikov, hkrati pa ohraniti svoje. Zanimiv način "Gem Grab" - ekipa postane zmagovalec, ekipa, ki zbere največ draguljev, zmaga. No, v načinu "Trk" se 10 igralcev bori med seboj na zemljevidu, kjer se meje zmanjšujejo zaradi strupenega oblaka. Igra je polna barvnega dizajna, ki je všeč mnogim ljudem, vključno z nami, kar nas je navdihnilo, da ustvarimo ločeno zbirko kazalcev Brawl Stars. Obstaja kazalec Brawl Stars Shelley, kazalec Barley, kazalec Penny, kazalec Frank, kazalec Mortis in drugi.',
    'brawl_stars_short_descr' => 'Izberite kazalce iz igre Brawl Stars in naj se bitka začne',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Spremenite kazalec miške v dveh klikih! Brezplačne zbirke za vsak okus.',
    'all_descr' => 'Če ste kdaj pomislili, kako spremeniti dolgočasen kazalec miške, potem so naše zbirke kazalcev za vas! Tukaj boste našli kul junake iz stripov, čudovite kazalce za igričarje z liki iz priljubljenih iger, zabavne komplete kazalcev za praktične šale, barvne kazalce in številne druge zanimive možnosti.',
    'text_title' => 'Kul in najbolj smešne zbirke kazalcev za vsak dan',
    'text_allcat_title' => 'Unikatni in kreativni kazalci miške, ki se ujemajo z vašim vsakim razpoloženjem',
    'text_1' => 'Nočete biti kot vsi ostali? Ali pa preprosto obožujete vse nenavadno? Želite biti del svojega najljubšega junaka iz igre ali risanega filma? Potem ste prišli na pravo mesto. Tukaj boste našli svetle, nevsakdanje komplete kazalcev, ki lahko nadomestijo znano in že precej dolgočasno belo puščico. Miškin kazalec nas spremlja ves dan pri delu in učenju, zato bi moral zagotavljati odlično razpoloženje in nas pripraviti na pozitivno.',
    'text_2' => 'Tukaj boste našli kurzorje za igralce in ljubitelje filmov, čudovite kurzorje, ki temeljijo na vaših najljubših risankah in športnih motivih za najbolj aktivne ljudi. Imate radi stripe ali si ne morete predstavljati niti enega dne brez smešnih memov? Obožujete živali ali sanjate, da bi obiskali vse države sveta? Vse je preprosto - tudi za vas imamo primerno sliko kurzorja. Prav tako lahko izberete slike glede na to, s čim delate. Na primer, črni kurzor bo veliko bolj priročen kot beli pri delu z dokumenti ali risbami, kurzor roke pa bo bolj priročen, če morate delati z majhnimi grafičnimi elementi. Izberite svojo najljubšo sliko, prilagodite njeno velikost neposredno v razširitvi - in jo z veseljem uporabljajte, vsak dan z pozitivno noto!',
    'install_to_preview' => 'Namestite razširitev za predogled',
    'install' => 'Namesti',
    'add_button' => 'Dodaj',
    'preview_button' => 'Predogled',
    'added_button' => 'Dodano',
    'add_cursor' => 'Dodaj kazalec',
    'to_your_collection' => 'v vašo zbirko',
    'prev_text_1' => 'Celozaslonski predogled',
    'prev_text_2' => 'kazalca',
    'cursor' => 'kazalec',
    'pointer' => 'kazalec',
    'a_title_1' => 'Cursor Style - Kul kazalci za vaš brskalnik',
    'a_title_2' => 'Kul zbirke tematskih kazalcev',
    'mouse_cursors' => 'Kazalci miške',
    'cursor_collection' => 'Zbirka kazalcev',
    'sborka_cursorov' => 'zbirka kazalcev',
    'collection_list_from_colllection' => 'Seznam kazalcev - ',
    'christmas' => 'Božič',
    'nhl_teams' => 'Ekipe NHL (National Hockey League)',
    'neon' => 'Neon',
    'adventure_time' => 'Pustolovščina z nadrealci',
    'nba_teams' => 'Ekipe NBA (National Basketball Association)',
    'spongebob' => 'Spuži Kvadratnik',
    'phineas_and_ferb' => 'Fineas in Ferb',
    'fortnite_chapter_2' => 'Fortnite Poglavje 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Zvezdniki',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Noč čarovnic',
    'nfl_teams' => 'Ekipe lige NFL',
    'five_nights_at_freddy' => 'Pet noči pri Freddyju',
    'komiksy' => 'Stripovski junaki',
    'igry' => 'Igre',
    'multfilmy' => 'Risanke',
    'kino_i_serialy' => 'Filmi in serije',
    'anime' => 'Anime',
    'futbol' => 'Nogomet',
    'avtomobili' => 'Avtomobili',
    'memy' => 'Memi',
    'emodji' => 'Emotikoni',
    'pitomcy' => 'Hišni ljubljenčki',
    'stil_i_krasota' => 'Moda in stil',
    'prazdniki' => 'Prazniki',
    'flagi' => 'Zastave',
    'vokrug_sveta' => 'Po svetu',
    'eda_i_napitki' => 'Hrana in pijača',
    'cvetnye' => 'Barvni',
    'prank' => 'Potegavščine',
    'startovyj_nabor' => 'Začetni komplet',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Božični kurzorji bodo všeč Božičku',
    'nhl_teams_short_descr' => 'Zbirka NHL kazalcev za prave navijače',
    'neon_short_descr' => 'Dodajte svetlost z neonsko zbirko',
    'adventure_time_short_descr' => 'Učenje matematike z zbirko kazalcev Adventure Time',
    'nba_teams_short_descr' => 'NBA kazalci kot simbol velikih košarkarskih zmag',
    'spongebob_short_descr' => 'Odkrijte, kdo živi na morskem dnu z zbirko kazalcev Spuži Kvadratnik',
    'phineas_and_ferb_short_descr' => 'Zagotovo vam ne bo dolgčas s kolekcijo kazalk Phineas in Ferb',
    'fortnite_chapter_2_short_descr' => 'Novo poglavje kultne igre Fortnite',
    'pokemon_short_descr' => 'Ujemite jih vse, če lahko',
    'famous_people_short_descr' => 'Navdihnite si kazalec vašega idola',
    'the_elder_scrools_short_descr' => 'Potopite se v svet vitezov in zmajev',
    'halloween_short_descr' => 'Bojte se zamuditi novo zbirko za noč čarovnic',
    'nfl_teams_short_descr' => 'Za prave nogometne navdušence',
    'five_nights_at_freddy_short_descr' => 'Poskusite se ne ustrašiti teh animatronikov',
    'komiksy_short_descr' => 'Kazalci po stripih: izberite svoje razpoloženje danes.',
    'igry_short_descr' => 'Navidezna resničnost: kdo ste danes vi v igri?',
    'multfilmy_short_descr' => 'Priljubljeni risani junaki v novi zasnovi',
    'kino_i_serialy_short_descr' => 'Gospodar kurzorja: bratovščina namizja',
    'anime_short_descr' => 'Vsi obožujejo anime: kdo je tvoj najljubši lik?',
    'futbol_short_descr' => 'Ste resnični ljubitelj športa? Potem morate biti tukaj.',
    'avtomobili_short_descr' => 'Avto vaših sanj: velika flota za profesionalce.',
    'memy_short_descr' => 'Najljubši motivi: Zbirka kazalcev Meme.',
    'emodji_short_descr' => 'Pokažite svoje pravo razpoloženje drugim - nastavite Cursoji!',
    'pitomcy_short_descr' => 'Svetli kazalci za vse ljubitelje naših manjših bratov',
    'stil_i_krasota_short_descr' => 'Originalni kazalci za vse priložnosti',
    'prazdniki_short_descr' => 'Kaj je na koledarju? Nova zbirka prazničnih kazalcev!',
    'flagi_short_descr' => 'Iščete avanturo: kam gremo danes?',
    'vokrug_sveta_short_descr' => 'V trenutku po vsem svetu: kam gremo danes?',
    'eda_i_napitki_short_descr' => 'Okusni kazalci za ustvarjalnost',
    'cvetnye_short_descr' => 'Pobarvajte svoje življenje v živahnih barvah in drznih potezah',
    'prank_short_descr' => 'Nabor kazalcev za najbolj smešne potegavščine',
    'startovyj_nabor_short_descr' => 'Nov pogled na znane stvari: posodobljena serija kazalcev',
    'fortnite_short_descr' => 'Sledite streamerjem!',
    'dota_2_short_descr' => 'Naj bo vaš virtualni svet kot resničen!',
    'minecraft_short_descr' => 'Likci vaše najljubše igre so vedno blizu',
    'christmas_descr' => 'Vsak od nas nedvomno čaka najbolj priljubljen praznik - božič. Vsi kristjani po svetu ga tradicionalno praznujejo vsako leto, 25. decembra. Čas, ko se družine zberejo za eno mizo, si delijo veselje in ljubezen ter izmenjujejo darila. Precej pred božičem ljudje okrašujejo ulice s svetlimi girlandami, domove pa s tradicionalnimi atributi. Težko je najti osebo, ki ne mara božiča - zabavnega in skrivnostnega praznika, saj ga spremlja veliko tradicij in obredov, ki nas vračajo k koreninam naše celotne družine. Na predvečer božiča je dobesedno vse nasičeno z njegovim duhom, od pobarvanih medenjakov do ganljivih napevov. Elegantna božična jelka in darila pod njo, veselje, ki ga pozna vsak od nas iz otroštva. Želimo se pridružiti temu čarobnemu prazniku in, kdo ve, morda vam bo Božiček pripravil posebno darilo, če okrasite svoj kazalec z našo božično zbirko. Za to je vse, kar potrebujete, kazalec Božiček, kazalec božična jelka, kazalec medenjak, kazalec Snežak in celo kazalec vreča z darili. Vesel božič!',
    'nhl_teams_descr' => 'Nacionalna hokejska liga je bila ustanovljena leta 1917 - to je profesionalna športna organizacija, ki združuje hokejske klube iz ZDA in Kanade. In to je ena prvih profesionalnih hokejskih lig na svetu. NHL je ena najpomembnejših športnih lig v Severni Ameriki, skupaj z NFL, NBA, Major League Baseball in MLS. Vsako leto se 31 ekip iz 30 mest v ZDA in Kanadi bori za glavno trofejo - Stanley Cup, ekipa, ki je v redni sezoni dosegla največ točk, pa prejme Presidential Cup. Čas je, da počastimo to odlično igro z ustvarjanjem zbirke kazalcev NHL. Če vam je hokej prav tako všeč, navijajte za svoj najljubši klub ali pa sami sodelujte v tem športu, samo spremenite kazalec in se ne ločujte od svoje najljubše ekipe, vključno s kazalcem Boston Bruins, kazalcem St. Louis Blues, kazalcem Columbus Blue Jackets, kazalcem Tampa Bay Lightning, kazalcem Dallas Stars in drugimi klubi, vrednimi iskrenega spoštovanja.',
    'neon_descr' => 'Ustvarili smo edinstveno zbirko neonskih kazalcev, da bi popestrili vsakodnevno brskanje po internetu in dodali malo svetlosti očarljivim neonskim lučem. Naj njihove bogate barve ustvarijo objemajočo atmosfero mesta ponoči in dajo navdih za ustvarjanje nečesa novega. V sodobnem svetu luči metropole vedno napovedujejo prihod noči, spremljajo nas na vsaki ulici in ta sij je poln energije. Naj ga spremlja tudi svetleči kazalec sladoleda, okusen kazalec hot doga, sočen kazalec burgerja, iskriv kazalec diamanta in drugi kazalci iz nove neonske kolekcije.',
    'adventure_time_descr' => '"Adventure Time" je risanka fantastične zvrsti, v kateri se dogajanje odvija v svetu, ki je preživel apokalipso. To ozemlje se imenuje Dežela Ooo, ki je do nedavnega bila jedrska vojna. Toda vse to je že v preteklosti, vendar so bili vsi preživeli ljudje podvrženi mutacijam in svet je bil napolnjen z magijo. Glavna lika animirane serije sta Finn, 14-letni fant, in njegov prijatelj pes po imenu Jake. Fant in pes imata zelo rada pustolovščine, nenehno pomagata vsem, ki so v težavah. Prijatelja živita na drevesu in skupaj preživljata ves svoj čas. Če se želite potopiti v pustolovski svet z drugimi oboževalci, potem zakličite "Matematika". Tukaj sta tako kazalec Finn Boy kot kazalec Jake, pa tudi kazalec Princesa Žvečilka. Seveda nismo pozabili na kazalec Bimo, kazalec Ledeni Kralj in druge.',
    'nba_teams_descr' => 'Če je košarka vaša najljubša igra, tako kot je naša, potem je zbirka kazalcev, posvečenih ekipam NBA, tisto, kar potrebujete. NBA je eno izmed najboljših športnih združenj na severnoameriški celini. Ko smo ustvarili to zbirko, nas je mučila izbira - katero ekipo izbrati, saj jih je v ligi NBA trideset. Ampak obstajajo ekipe, ki so legende. To so Chicago Bulls, ki so v sredini 90-ih postavili rekord zmag. To so Golden State Warriors, ki so pred nekaj leti združili najboljše igralce lige. Ali, na primer, Lakers, Celtics so prav tako noro kul ekipe. Če se, tako kot mi, veselite tekem svojih najljubših košarkarskih ekip in želite pokazati svojo podporo ekipi ali igralcem, prenesite našo zbirko kazalcev NBA.',
    'spongebob_descr' => 'Animirana serija "Spuži Kvadratnik" je znana tako številnim ljudem. Bilo je izjemen uspeh, potem ko se je Nickelodeon leta 1999 odločil ustvariti animirano serijo, ki temelji na izobraževalnem stripu Tide Zone, in se spremenila v zelo donosno franšizo. Ustvarjalec serije je nekdanji zaposleni v oceanološkem laboratoriju, zato so skoraj vsi liki v animirani seriji smešni prebivalci morskega dna, s svojimi lastnostmi in karizmo. Zgodba se vrti okoli skrivnega recepta Krabsburgerja, ki ga lahko skuha le glavni lik - Spuži Bob. Ostali prebivalci morja pa ga poskušajo dobiti, vključno z glavnim anti-junakom Sheldonom Planktonom, ki mu to ne uspe vsakič. V zbirki kazalcev Spuži Bob smo zbrali kazalce vseh pomembnih likov in dogodkov iz serije. Na primer, kazalec gospoda Krabsa z dolarjem, kazalec Patrika Zvezde, Jaka s svojo klarinetom, kazalec meduze, kazalec Spužija Boba in številnih drugih likov.',
    'phineas_and_ferb_descr' => 'V izmišljenem ameriškem mestu Denville v neobstoječi državi Trishtatyi živita dva zanimiva fanta. Vsak dan njunih počitnic se spremeni v neverjetne dogodivščine, saj lahko naredita tobogan velikosti celotnega mesta ali pravi portal v drug planet. Svoje neverjetne zabave delita s prijatelji. Hkrati, medtem ko se fanta zabavata, zlobni znanstvenik Heinz Fufelschmertz gradi še en zlobni stroj, ki ustvarja kaos, z imenom, ki se konča na "-inator", s pomočjo katerega se želi maščevati za svoje otroške zamere ali prevzeti oblast v Trishtatu, vendar ga ovira Perry - Utkonos, skrivni "Agent Pi", ki dela pod krinko hišnega ljubljenčka fantov. Priljubljenost te animirane serije, tako pri otrocih kot pri odraslih, nas je navdihnila, da ustvarimo zbirko kazalcev Phineas in Ferb, da lahko spremenite kazalec miške na like iz serije. Med njimi so kazalec Phineasa Flynna, kazalec dr. Heinza Fufelschmertza, kazalec Ferba Fletcherja, kazalec Candace Gertrude Flynn in kazalec rdečega kljuna Perryja.',
    'fortnite_chapter_2_descr' => 'Drugo poglavje igre Fortnite je prišlo po velikem dogodku - The End (Konec), ki je vso vsebino, ki so jo igralci v igri imeli radi, potegnilo v črno luknjo. Fortnite Chapter 2 zdaj ima novo mapo, ki je na prvi pogled še bolj divja kot originalna mapa, kot tudi številne spremembe v mehaniki igre in seveda veliko nove vsebine! Vozila, čustveni izrazi, mehanika plavanja in še veliko več - vse to v svežih, zanimivih podobah, vse kot imate radi in cenite v tej kultni igri. Potopite se v nov svet - izberite lokacijo pristanka in raziščite popolnoma nov otok s 13 lokacijami. Plavanje, ribolov, motorni čolni - to je novo vodno igranje. Več zabave in manj truda - nadgradite popolnoma novo poglavje 2 in ne pozabite spremeniti kurzorja na nove preobleke in orožje. Že vas čakajo posodobljene preobleke Turk kurzor, Riptide kurzor, Rippley kurzor, Remedy kurzor, Toxin kurzor, 8-Ball kurzor, Fusion kurzor in druge!',
    'pokemon_descr' => 'Beseda "pokemon" pomeni bitje z nadnaravnimi močmi. Imajo inteligenco in nekateri celo znajo govoriti. Trenutno obstaja že 802 različici Pokemonov. V izmišljenem vesolju Pokémon se ljudje imenujejo trenerji Pokémonov, ki jih trenirajo za bitke z drugimi trenerji Pokémonov. In bolj izkušen in močnejši kot je trener, več spoštovanja uživa. Na srečo je treba opozoriti, da se bitke Pokemonov nikoli ne končajo s smrtjo teh edinstvenih bitij. Vsi Pokémoni imajo različne sposobnosti in se razlikujejo po vrsti elementov, njihova odpornost na različne napade pa je od tega močno odvisna, nekatera bitja pa imajo sposobnost dveh elementov hkrati. Po zmagi v bitki dobi Pokemon dragocene izkušnje, ki so potrebne za dvig ravni in s tem njegovih karakteristik. Danes je vesolje Pokémonov ogromna medijska franšiza in odločili smo se, da za vas pripravimo zbirko kazalcev z nekaterimi priljubljenimi Pokémoni. Med njimi je najbolj znan kazalec Pikachu, pa tudi kazalec Rattata, kazalec Squirtle, kazalec Bulbasaur in kazalec Charmander. Ta seznam se bo posodabljal, ker jih je toliko in je vsak od njih edinstven na svoj način.',
    'famous_people_descr' => 'Med številnimi znanimi osebami vsak od nas najde vzornika ali pa preprosto občuduje genialnost, talent in vztrajnost teh zvezdnikov. Pripravili smo zbirko kazalcev slavnih osebnosti, da vas navdahnemo in vas spomnimo na velike dosežke, ki jih lahko poveča vsak od vas. Vse znane osebnosti niso imele srečne usode, vendar nas učijo glavno stvar, da vam ni treba odstopiti od svojega cenjenega cilja, kljub težavam in problemom. Konec koncev je to glavno načelo doseganja uspeha - vsak dan iti k svojim sanjam in končno postati najboljši na svojem področju. Morda želite danes samo spremeniti kazalec miške in jutri se bo vaše celotno življenje spremenilo na bolje! Zbirka se bo nenehno posodabljala z novimi, vrednimi predstavniki človeštva. Med njimi so seveda znanstveniki, politiki, športniki, predstavniki umetnosti in mnogi drugi. Kazalec Georgea Washingtona, kazalec Michaela Jordana, kazalec Stephena Kinga, kazalec Elvisa Presleyja in kazalec Marilyn Monroe so le začetek.',
    'the_elder_scrools_descr' => 'The Elder Scrolls je serija računalniških iger vlog, ki jih združuje skupno, natančno zasnovano vesolje, ki igralcu daje ogromno svobode izbire, kar mu omogoča obisk različnih območij in mest fantazijskega sveta in samostojno raziskovanje novih krajev in misij. Delo na seriji se je začelo leta 1992 in z leti je igra združila ogromno skupnost igralcev. Zato smo na željo igralcev izdali zbirko kazalcev The Elder Scrolls, da se lahko potopite v edinstveno vzdušje igre. Večna bitka vitezov in zmajev, na kateri strani ste? Spremenite kazalec v zmaja in se pridružite vojski ognjenogašenih pošasti ali pa se plemenito borite na strani ljudi tako, da izberete kazalec meča in podobo svojega najljubšega lika - odločitev je vaša! Glavna stvar je, da ste z našo novo zbirko pripravljeni na vse bitke.',
    'halloween_descr' => 'Čakanje na mistično noč na predvečer vseh svetih. Zgodovina noči čarovnic sega več kot dva tisoč let nazaj. Morda je to najčudnejši praznik, ki združuje zabavo in strah, domačin keltske kulture. Takrat so ljudje kurili kresove in si nadeli strašljive kostume, da bi pregnali duhove. Beseda "noč čarovnic" je bila prvič omenjena v 16. stoletju kot škotska okrajšava angleškega izraza All-Hallows-Even. Papež Gregor III. je 1. november razglasil za dan vseh svetih, večer pred tem pa je bil znan kot Eve of All Saints, kasneje pa noč čarovnic. Na ta dan ljudje nosijo kostume volkodlakov, duhov in drugih pošasti in hodijo v sosednje hiše in ponujajo, da kupijo sladkarije. Tematske zabave, ognjemeti, lepe luči, buče in kaskade ustvarjajo edinstveno vzdušje. Tudi mi želimo ta grozen praznik proslaviti z dodatki kazalcev in liki za noč čarovnic. V naši zbirki lahko najdete: kazalec zombija, kazalec duha, kazalec črne mačke, kazalec buče in še veliko več. Sprememba razpoloženja je zdaj tako preprosta kot menjava kazalca z našo novo kolekcijo za noč čarovnic.',
    'nfl_teams_descr' => 'Kaj bi lahko bilo boljšega za pravega ameriškega ljubitelja nogometa kot kazalec miške v obliki simbolike ekipe, katere oboževalec je? V moderni National Football League igra trideset dva moštva, razdeljena med National in American Football Conferences (National Football Conference, NFC in American Football Conference, AFC). Vsaka od konferenc je nato razdeljena na štiri divizije: Vzhod, Sever, Jug in Zahod. Sezona NFL je sestavljena iz predsezonskih tekem, redne sezone in serije tekem končnice. Finalna tekma sezone NFL se imenuje Super Bowl in je v bistvu najbolj priljubljen športni dogodek v Združenih državah Amerike. To je najljubša igra za milijone oboževalcev in zato smo ustvarili zbirko kazalcev NFL, da se ne bi ločili od simbolov svoje najljubše ekipe. Bodisi New England Patriots, New York Giants, Buffalo Bills ali katera koli druga ekipa, bodite vedno na isti valovni dolžini kot vaši idoli, tako da uporabljate naše kazalce v obliki logotipa ekipe in čelade. Zbirka se bo nenehno posodabljala, tako da lahko vsakdo spremeni kazalec v podobo svoje najljubše ekipe.',
    'five_nights_at_freddy_descr' => 'Zares edinstvena igra Five Nights at Freddy\'s je hitro pridobila veliko popularnost in to ni presenetljivo, saj lahko njena preprosta in hkrati očarljiva zgodba ohrani igralce na zaslonih ure in ure. Mi smo zasnovali kurzorje Five Nights at Freddy\'s na zahtevo oboževalcev igre in bili zelo zadovoljni, da smo lahko upodobili tako zanimive in smešne like. Toda za razliko od igre vam z našimi kurzorji nič ne grozi, zato se prosto odločite za svoje najljubše animatronike, naj bo to medved Freddy ali zajec Bonnie ali drugi. Glavna stvar je, da zdaj igra oživi v vašem brskalniku in daje sveža čustva. Jamčimo, da v naših kurzorjih ni duhov, vendar popolnoma prenašajo duh igre, ki navdihuje strah zaradi zapletenosti oblikovanja in elementov zgodbe. Toda kaj pa, če naredite velikost kurzorja zelo veliko? Se lahko umirite in se ne ustrašite?',
    'komiksy_descr' => 'Zdelo bi se, da je kazalec miške malenkost, vendar prav takšni detajli pogosto lahko izboljšajo vaše razpoloženje, vas zbudijo v sivih jutrih ali pa samo dajo svetle emocije. Zbirka kazalcev stripov, zasnovana posebej za vse ljubitelje superjunakov. Tukaj lahko najdete čisto vse iz Marvelovega vesolja in DC Comics - od Iron Mana do Thanosa, Spider-Mana in Hulka. Slog kazalca je lahko v obliki superjunaka ali v obliki njegovega znaka. Kazalec ni le funkcionalni element; je pomemben v profesionalnem smislu. Če na primer snemate video z zaslona, bo bolje videti svetlo, izvirno sliko, ki izgleda veliko bolj zanimiva. In seveda - kdo si ne bi želel uporabiti rokavice neskončnosti v resničnem življenju? Sprememba kazalca miške je preprosta - samo prenesite razširitev v vaš brskalnik in dodajte kazalec, ki vam je všeč, v vaše nastavitve prek nje. Kazalec lahko izberete glede na vaše razpoloženje vsaj vsak dan. Dovolj sivih dni - postanite superjunak zdaj!',
    'igry_descr' => 'Računalniške igre so že zdavnaj postale sestavni del našega življenja. Z njihovo pomočjo se lahko potopite v nov svet, sodelujete v dogodivščinah in postanete popolnoma drugačna oseba. Vsak ima svojo najljubšo igračo, katere liki so že skoraj postali družina. Komplet kazalcev, ki temelji na znanih računalniških igrah, je priložnost, da razredčite dolgočasno vsakdanje življenje in delovnemu procesu dodate nekaj ustvarjalnosti, živahnosti in zabave. Komplet vsebuje tako podobe samih junakov iger kot tudi pomožne like, orožje in ikone iger. Izberite tisto, kar ustreza vašemu razpoloženju - igralni kazalci bodo všeč ne le igralcem, temveč tudi vsem, ki jim je preprosto dolgčas sivega vsakdana. Samo prenesite komplet, spremenite kazalec miške - in pojdite, da dokončate naloge iskanja, uničite sovražnike in dosežete svoje cilje.',
    'multfilmy_descr' => 'V vsakem odraslem je še vedno otrok, ki obožuje risanke in še vedno sanja, da bi postal eden od junakov. Pomagali vam bomo uresničiti vaše sanje - uporabite novo zbirko kazalcev, ki temelji na najbolj znanih in priljubljenih risankah. Tom in Jerry, Buzz Svetlobno leto in Shrek, Padec gravitacije in celo Pokemon - vsak dan lahko postanete, kar želite. Izberite kazalec miške glede na svoje razpoloženje. Kdo ste danes? Drzen in vesele minjon, ki zlahka rešuje vse probleme ali močan in pogumen Raphael, katerega cilj ni le doseči podvige, ampak tudi jesti pico? Morda ste vsemogočni duh, ki ima v poveljstvu celoten urad? V zbirki so junaki za vse - od princesk do zmajev - ostane le, da se odločite, kdo odraža današnje razpoloženje. Cursor Style ni samo svetla slika. To je odraz individualnosti, samoizražanja in preprosto - zabave, veselja in pozitivnosti za cel dan. Je delo dolgočasno ali preveč leno za učenje? Ste postali žalostni in niste srečni? Spremenite kazalec in svet bo zasijal z novimi barvami.',
    'kino_i_serialy_descr' => 'Filmi - so čarobnost, mistika in odličen način za sprostitev, zabavo in pridobivanje živahnih čustev. Hkrati si po ogledu še vedno zapomnimo najljubše junake, ki bi jih radi srečali v resničnosti. Zdaj je to mogoče - samo prenesite novo zbirko kazalcev, ki temelji na znanih filmih in televizijskih serijah. Svetli, kul kazalci bodo odličen dodatek k namizju, dolgočasno sivo vsakdanje življenje spremenili v praznik, banalna opravila pa v razburljivo pustolovščino. Spremenite kazalec junaka vsak dan - za razpoloženje, naloge ali naključno. Kdo boste danes? Pošteni in pravični John Snow ali drzni, neizprosni John Wick? Morda vas čaka težka misija in jo lahko dokonča le Frodo? Morda ste danes le tujec, ki ne želi stika z drugimi? Izberite ustrezen kazalec - polepšajte si razpoloženje in hkrati pokažite drugim, kaj mislite in kako nameravate preživeti dan. Poskusite - ni samo zabavno, ampak tudi zasvoji - zagotovo se ne boste želeli vrniti k običajni puščici.',
    'anime_descr' => 'Anime je edinstven stil animacije, ki ga, kljub njegovi izraziti etničnosti, uživajo milijoni ljudi po vsem svetu. Malo verjetno je, da obstaja vsaj ena oseba, ki ni gledala risank v tem stilu. Ustvarili smo najbolj kul kurzorje v anime stilu, ki jih bodo vzljubili vsi oboževalci tega stila. Standardni kurzorji so dolgočasni in klišejski. Pokažite svojo osebnost - uporabite zbirko kurzorjev Anime z vašimi najljubšimi liki. Izberite kurzor temnega meča, če sanjate o avanturah in pogumnih bitkah. Simpatičen debelušen Totoro vas bo razveselil tudi v najžaloostnejšem dnevu, Naruto pa vas bo motiviral na avanturah in pokazal vsem okoli vas, da ste mega kul. Svetli kurzorji bodo polepšali delovni dan ali naredili učni proces bolj zanimiv in prijeten. Ne omejujte se - uporabljajte svoje najljubše motive tudi v tako majhnih elementih, kot je kurzor miške. Spreminjajte kurzorje vsak dan, jih prilagajajte svojemu razpoloženju in pokažite svojo osebnost - s kurzorji v anime stilu je to tako preprosto.',
    'futbol_descr' => 'Nogomet je poseben šport, ki vključuje elemente rokoborbe, atletike in natančnosti. Na splošno je spektakularen, neusmiljen in zbira milijone oboževalcev po vsem svetu. Imate radi nogomet ali samo ljubite šport? Nato prenesite komplet kazalcev v stilu svetovno znane igre in dokažite naziv zvestega oboževalca. Zbirka vsebuje 24 možnosti za oblikovanje kazalcev - v obliki najbolj priljubljenih ekip, ki si zaslužijo svoje naslove kot obupana in vztrajna igra. Kazalci so izdelani v dveh različicah - v obliki standardnega trikotnika, okrašenega v barvah ekipe, ali v obliki ustrezne igralne čelade. Standardni kazalec brskalnika je dolgočasen in nevreden pravega športnega navijača. Bodite izvirni in edinstveni z našo zbirko. Prenesite slike in izberite barve svoje najljubše ekipe ali kazalcev po meri, če samo ljubite šport in navijate za vse. Slediti svojim hobijem je tako preprosto - vam ni treba priti v službo v šalu ali kapi svoje najljubše ekipe, hitro in enostavno je zamenjati kazalec za svetlo, stilsko sliko.',
    'avtomobili_descr' => 'Ali imate radi avtomobile in uživate v ogledu modelov različnih proizvajalcev? Ali pa že dolgo sanjate o določeni znamki, pa je še vedno nimate možnosti kupiti? Posebej za vas smo ustvarili svetel nabor kazalcev "Superavtomobili". Tu boste našli klasični Ford in stilski Bentley, svetel Lamborghini in edinstven Ferrari. Želite postati lastnik originalnega avtomobila? Preprosto je - prenesite našo zbirko kazalcev na svojo napravo in spreminjajte podobo avtomobila vsaj vsak dan. Kazalci so oblikovani v dveh različicah - kot popoln avto ali kot njegov znak. Izberite, kaj vam je najbolj všeč ali kako želite delati. Takšne slike bodo odlično izgledale kot igralni kazalci ali preprosto kot nenavaden element namizja. Biti svetel je preprosto - za to ni treba početi nezamisljivih stvari ali spreminjati svoj videz. Dovolj je, da prenehate uporabljati vsakdanje predmete in izberete tisto, kar vam je resnično všeč. Zbirka kazalcev "Avtomobili" je izbira za tiste, ki se ne bojijo dokazati.',
    'memy_descr' => 'Memi so že dolgo poznan del našega življenja. In kdo od nas nima rad teh obsežnih, zanimivih in izvirnih slik, da bi se zoperstavil dnevu? Mnogi junaki memov niso postali le priljubljeni - pridobili so status priljubljenih favoritov, fraze in izrazi pa so že dolgo vključeni v pogovorni jezik kot uveljavljeni obrati. Predstavljamo zbirko najboljših kazalcev, ki temeljijo na najbolj priljubljenih memih. Z njihovo pomočjo lahko ne le pokažete svojo osebnost, temveč tudi izrazite svoje razpoloženje. Ste vsi utrujeni in naveličani vsega? Izberite jeznega mačka, ki z vsem svojim videzom izraža ogorčenje in sovražnost do vsega okoli sebe. Ali pa danes sijete s sarkazmom in vam ni mar smejati se? Potem bo Drake Bling odličen spremljevalec - razveselil vas bo in naredil vsako nalogo prijetno in zanimivo. Namestite razširitev, prenesite našo zbirko - in izberite slog kazalca za vsak dan. Ni težko biti svetel in izvirni - spremenite standardno zasnovo ikone v enega od junakov memov in si privoščite energijsko spodbudo za ves dan.',
    'emodji_descr' => 'Emodžiji – svetli, kul ikoni, brez katerih ne moremo več rutinsko komunicirati. Z njihovo pomočjo vam ni treba opisovati svojega razpoloženja z besedami – samo izberite želeno ikono in sogovornik vas razume brez nadaljnjih besed. V našem novem naboru kazalcev smo utelešali idejo emodžijev – tako so se pojavili smešni in nenavadni Kursoji, ki bodo obarvali svet in naredili življenje bolj zanimivo. S pomočjo kazalcev ne morete le delati in opravljati znane naloge, ampak tudi pokazati svojim sodelavcem, prijateljem in drugim svoje razpoloženje. Zaspan kazalec je popoln za ponedeljkovo jutro, jokajoči kazalec pa bo izrazil odnos do dodatnih odgovornosti. Kul kazalec z očali je najboljša izbira pred prazniki, kazalec z dolarji v očeh pa je dober razlog, da šefu namignete na povišanje plače. Uporaba Kursojev je zabavna in zanimiva – ne glede na to, ali gre za delo, študij ali predstavitev. V slednjem primeru je to celo priporočljivo storiti, če imajo kolegi smisel za humor ali pa je treba samo razbremeniti situacijo. Na splošno, za vsako nalogo - samo izberite pravi kazalec!',
    'pitomcy_descr' => 'Imate radi živali? Seveda - so tako ljubke, smešne in zelo zabavne. Zakaj ne bi preživeli cel dan v družbi najboljših prijateljev človeka? Prenesite zbirko kazalcev Pets zase in izberite prijatelja za vsak dan. Ikona kazalca je lahko ljubka, kot prijazna alpaka, ali elegantna, kot rožnati flamingo. Ali pa boste morda zaposleni ves dan in izbrali samoroga, ki bere časopis, ali pa preprosto ne želite komunicirati z nikomer, kot zlobna črna mačka? Za vsako razpoloženje imamo ustrezno žival. Vesele mops vas bo razveselil tudi na najbolj dolgočasen in siv dan, rožnati kazalec v obliki samoroga pa bo vsem pokazal, da vam ni prikrajšano za občutek lepote, čeprav ste brutalni bradati moški. Kaj pa, če ni razpoloženja in se mi ne da opravljati rutinskih nalog? Recept je preprost - prenesite zbirko Pets, spremenite kazalec miške - in voila, sonce spet sije, vreme je lepo in razpoloženje je na najvišji ravni. Nič čudnega, pravijo, da živali pomagajo v boju proti depresiji in žalosti!',
    'stil_i_krasota_descr' => 'V novi zbirki kazalcev smo zbrali najrazličnejše predmete, ki v nas vzbujajo prijetna čustva in nas dvigujejo. Ta komplet kazalcev se imenuje “Slog in lepota”, ker so to vaše najljubše stvari, ki določajo naše vsakdanje življenje, prinašajo veselje in nas motivirajo, da počnemo pomembne stvari, prebujajo željo po izboljšanju. Vas privlačijo vesolje in sanjate o odhodu na druge planete? Izberite kazalec NASA ali krožnik zunajzemljanov - približajte se svojim sanjam. Če si ne morete predstavljati življenja brez glasbe ali ste zagrizen rocker, potem je kazalec v stilu električne kitare za vas. Čopič, ravnilo in kompas so bili posebej razviti za inženirje - takšne podobe bodo pripomogle, da se dolgočasni izračuni in risbe spremenijo v izvirne rešitve. Čarobna palica in superge, rolka in šminka, sonce in kemični stožci - izberite tisto, kar ustreza vašemu življenjskemu slogu, vašim željam in težnjam - in običajne naloge bodo postale bolj zanimive, delovni dnevi pa bodo obarvani v novih, svetlih barvah.',
    'prazdniki_descr' => 'So radi praznike? Kdo pa jih ne mara - prijatelji, darila, spet isti vikendi. Da bo čakanje na praznike prijetnejše, krajše in toplejše, lahko ne le štejete dni na koledarju, ampak tudi nastavite ustrezen ikono kot kazalec miške. Začnimo z novim letom - izbrali bomo božično drevo, darilo ali Božička, da bodo prazniki svetli in veseli. Morda bo možiček iz medenjakov bližje - smešen, prikupen in vedno vesel? Z njim zagotovo ne bo časa za žalost in dolgčas. Nadaljujemo s praznovanjem s kupidi in veselimi srci, in ni daleč do velikonočnega zajčka. Nekje med prazniki bo rojstni dan, ki ga bo še bolj prijetno čakati z baloni namesto standardne puščice kazalca. In na Noč čarovnic lahko presenetite sodelavce in tiste okoli sebe z nenavadnim kazalcem miške v obliki zlovešče buče ali duha. Komplet kazalcev za praznike je priložnost, da si polepšate pričakovanje, se vnaprej pripravite na prihajajočo zabavo in ohranjate odlično razpoloženje ne le na predvečer praznovanja, ampak skozi vse leto.',
    'flagi_descr' => 'Zastava je edinstven simbol, ki se pogosto uporablja v vseh družbenih omrežjih. Pomislili smo, zakaj ne bi naredili kurzorja zastavo? Navsezadnje je res svetla in nenavadna. Zdaj lahko vsak dan preživite v družbi nove države in delo ne bo tako monotono in dolgočasno. Kurzorski kazalci miške so lahko zdaj narejeni v nacionalno zastavo Kitajske ali ZDA, Japonske ali Kanade in v še 38 drugih opcijah zastav, pri čemer lahko izberete bodisi standardno obliko puščice v nenavadni barvi ali kurzor v obliki same zastave. Ta komplet bo všeč vsem ljubiteljem potovanj. Z njim lahko načrtujete nova potovanja in sanjate o dolgih potovanjih. Ste načrtovali dopust? Pokažite vsem, v katero državo želite iti. Se morda odločate za učenje novega tujega jezika? Potem vas bo ta kurzor zagotovo podpiral in motiviral k skrbnemu učenju. Ali pa imate, tako kot Sheldon, radi zastave? V vseh primerih bo zbirka kurzorjev Zastave odličen dodatek k vaši namizni napravi in vas bo popeljala k novim odkritjem.',
    'vokrug_sveta_descr' => 'Vsakdo rad potuje. Kako čudovito je obiskati nove države in mesta, videti znamenitosti in se imeti odlično v novi kulturi. Škoda, da ne moremo potovati tako pogosto, a smo to poskušali popraviti. Komplet kazalcev “Okoli sveta” je zbirka najznamenitejših podob, simbolov različnih držav, s pomočjo katerih se lahko tudi doma počutite kot pravi popotnik. V našem kompletu lahko najdete Japonsko in Avstralijo, Italijo in Kanado, ZDA in Mehiko - najbolj zanimive, izvirne in slikovite države na svetu. Slika kazalca lahko postane standardna puščica v barvah zastave države ali pa postane ena glavnih znamenitosti države. Na primer, lahko odprete dokumente s poševnim stolpom v Pisi in naredite predstavitve z uporabo Kipa svobode. Zagotavljamo - uspeh bo zagotovljen. No, ali če ne uspeh, potem nasmehi kolegov in priznanje izvirnosti - zagotovo. Ja, in namig vodstvu, da je čas za dopust, bo prav tako koristen - samo nastavite kovček ali letalo kot kazalec - in najverjetneje boste zelo kmalu leteli.',
    'eda_i_napitki_descr' => 'Nabor kazalcev v obliki izdelkov je neverjetna zbirka svetlih, okusnih in slastnih slik, ki bodo zagotovo všeč vsem in bodo odličen dodatek k brskalniku. Ste že kdaj kliknili na brokoli ali pomfrit? Imate takšno priložnost - samo prenesite nov nabor kazalcev in jih nastavite namesto dolgočasne bele puščice. Kazalci "Hrana" so narejeni tako v obliki standardnega trikotnega kazalca kot v obliki izdelkov. Tu boste našli zelenjavo in sadje, vaše najljubše jedi, kot so pica ali hot dogi, kava, lizike in še veliko več, kar razveseljuje vsak dan. Ljubite kavo, vendar je pitje celega dne ni tako dobro? Doplnite svojo prehrano z virtualno kavo, ki vas bo prav tako poživila in zbudila, prav tako pa vam bo dala živahna čustva. Strm kazalec v obliki virtualnega krofa ne bo škodoval postavi, hkrati pa bo dal živahna čustva in razveseljeval. Uporabite lahko svoje najljubše kazalce ali spremenite sliko vsak dan - velika izbira kazalcev bo pomagala obarvati vsakdanje življenje in dodati nove barve znanih dejanj.',
    'cvetnye_descr' => 'Kazalec je glavni element brskalnika, s katerim preživimo celoten delovni dan, študiramo, komuniciramo in se sproščamo. Standardni prikaz kazalca je dolgočasen in celo nekoliko depresiven, a vseeno je za mnoge ljudi ta oblika priročna in sprememba bi bila neudobna. Toda za to situacijo imamo rešitev – nabor kazalcev v svetlih, veselih barvah, ki bo popestril vaše vsakdanje življenje in omogočil lažje in hitrejše reševanje vseh težav. Če razmišljate o tem, kako spremeniti barvo kazalca, odgovarjamo – prenesite našo zbirko in izberite svetle rešitve za vsak dan! Izberete lahko enobarvne tone v različnih barvah, ki ustrezajo razpoloženju ali specifičnosti dela. Na primer, pri delu s standardnimi dokumenti bo vijolični kazalec izstopal iz ozadja, na temnem ozadju pa boste nasprotno lažje delali z rumenimi kazalci. Če želite eksplozijo barv, svetlosti in maksimalne izvirnosti – izberite mavrični kazalec, ki vključuje vse barve spektra – s to ikono bo razpoloženje zagotovo dobro čez dan.',
    'prank_descr' => 'Šale na delovnem mestu niso vedno dobrodošle, saj pogosto ovirajo potek dela. Toda z novim naborom kazalcev “Potegavščine” se lahko prijazno pošalite s svojimi sodelavci ali prijatelji, ne da bi pri tem škodovali svojemu delu ali študiju. Razvili smo posebno zbirko, ki bo zabavala vsakogar in dala razlog za malo sprostitve sredi zasedenega procesa dela ali opravljanja druge naloge. Če želite spremeniti kazalec miške, samo prenesite komplet v napravo in izberite dizajn, ki vam je všeč, v parametrih. Na primer, lahko dobite kazalec standardne oblike, vendar v obrnjeni obliki ali puščico, upognjeno z valom. Ta oblika sploh ne bo ovirala procesa dela, hkrati pa bo predstavila čudovito razpoloženje in vas postavila v pozitivno razpoloženje. Spremenite nastavitve prikaza kazalca glede na vaše razpoloženje ali vsak dan - in vsaka naloga bo postala bolj zanimiva in prijetna, vsakdanje življenje pa ne bo več povzročalo negativnih čustev. Poleg tega se lahko takšni kazalci uporabljajo celo za resne projekte - imajo nevtralne barve in ne izstopajo iz namizja.',
    'startovyj_nabor_descr' => 'Kazalci iz začetne zbirke so mešanica standardnih oblik in velikosti s svetlim, nenavadnim videzom. To je odlična izbira za tiste, ki imajo raje običajne oblike, a želijo v vsakdanje življenje vnesti raznolikost, izvirnost in svetlost. Zbirka ima kazalec v obliki roke in znano puščico v različnih različicah - od logotipa Google Chrome do emotikonov, tukaj lahko srečate celo že zdavnaj pozabljenega zmaja s kaktusi in nostalgijo. Dokazujemo, da je lahko standardni kazalec tudi zanimiv in privlačen. Različne barve, oblike, teksture in zanimiv dizajn vam bodo pomagali izbrati kazalec po svojem okusu ali ga spreminjati vsak dan, odvisno od razpoloženja ali opravil. Spreminjanje kazalcev brskalnika je zelo preprosto - samo namestite razširitev in prenesite zbirko na svojo napravo. Smešni, zanimivi kazalci ne bodo samo obarvali delovnih dni, ampak vam bodo na primer pomagali, da bo vsaka predstavitev bolj zanimiva, s pomočjo posebej svetlih kazalcev pa boste pozornost usmerili tudi na posamezne elemente poročila.',
    'fortnite_descr' => 'Fortnite je osvojil milijone ljudi po vsem svetu. Razburljive bitke, strategija in taktika, pustolovščine - absorbiral je popolnoma vse, kar imajo igralci tako radi. Nismo mogli ostati stran in razvili smo nabor kazalcev v stilu igre, ki bo všeč ne samo zvestim igralcem, ampak tudi tistim, ki so prvič slišali za Fortnite. Ikona kazalca Fortnite je slika junaka ali njegovega orožja, izpopolnjena do najmanjše podrobnosti. Tukaj lahko najdete slike lisic in rib, maske inferna in črnih vitezov, nastavite si puščico ali koso s konicami kot puščico. Prepričani smo, da nihče ne bo ostal ravnodušen! Biti strašljiv ali skrivnosten, izviren ali humoren - odvisno je od vas. Izberite svoj stil in ga sledite ali nastavite kazalce po meri v nastavitvah in spremenite svojo vlogo vsak dan. Zdaj bo veliko bolj zanimivo in prijetno opravljati tudi dolgočasno in monotono delo - čas bo hitro minil v družbi živahnih slik in najljubših likov. Ali pa boste s sodelavci priredili tekmovanja, kateri junak bo močnejši? Izbira je vaša!',
    'dota_2_descr' => 'DotA2 zdaj ni le preprosta igra, je pravi vzporedni svet. V virtualni resničnosti v DotA2 lahko počnete vse - živite, se borite, razvijate, potujete, sklepate prijateljstva. Na splošno vse tako kot v življenju, le včasih bolj zanimivo. Kazalci Dota 2 so nadaljevanje strategije, ki vam bo omogočila, da dobite živahna čustva in se izrazite v resničnem svetu. Novi nabor kazalcev vključuje najbolj presenetljive like v igri, kot tudi izvirne predmete, ki jih ni mogoče zamenjati z ničemer drugim. Izberite kazalec, ki vam bo bližji - in se podajte na pustolovščino, ne da bi zapustili svoje delovno mesto. Kako dolgočasno je včasih biti v službi ali opravljati izobraževalne naloge, toda z igralnimi kazalci se vam ta težava ne bo več pojavila. Malo domišljije, svetel kazalec - in voila, vsak posel bo neobičajna avantura, s katero ne bo težko in zanimivo delati. Ni se vam treba zadrževati. Imate radi Doto? Potem si nujno prenesite našo zbirko, izberite enega ali več naključnih kazalcev naenkrat - in vsak nov dan bo postal svetlejši, bolj zanimiv in nasičen.',
    'minecraft_descr' => 'Mišični kazalci v obliki standardnih puščic in prstov so vsem že dolgočasni. Če ste ljubitelj nenavadnega in izvirnega, potem je čas, da spremenite mišični kazalec in mu daste bolj zanimivo obliko. Razvili smo zbirko kazalcev v slogu svetovno znane igre Minecraft, kjer lahko najdete najbolj osupljive like. Volki in lisice, Alex in Creeper, diamantni meč in ribe - lahko izberete tistega, ki vam je najbolj všeč, ali pa vsak dan namestite novega junaka. To so pravi kazalci za igralce in vsem bodo zagotovo všeč - navsezadnje, kdo od nas ni igral Minecrafta? Prepričani smo, da takih preprosto ni. Dolgčasnemu vsakdanjemu življenju - čas je, da se potopite v pustolovščine, kar lahko storite tudi ne da bi zapustili svoj dom ali pisarniški stol. Bolj zanimivo bo pripraviti poročilo in zmanjšati stanje z orožjem - vsaka naloga bo postala prijetnejša in vam ne bo pustila, da se dolgočasite na mestu. Prenesite novo zbirko kazalcev Minecraft - nastavite jih in tudi v najsivem in najbolj dolgočasnem dnevu bo vaše razpoloženje vedno na vrhuncu. In kolegi vam bodo zavidali vaše rezultate - preprosto je nemogoče ne opravljati svojega dela s pomočjo pogumnih junakov Minecrafta.',
    'pusheen_descr' => 'Skoraj vsi poznajo mačko Pusheen. Čeprav je le lik iz otroškega stripa, izumljenega pred 10 leti, ima danes na milijone oboževalcev. Mačka Pusheen se je pojavila kot ilustracija umetnice Claire Belton.
Leto kasneje je mačka dobila svojo stran na Tumblr.com in v nekaj tednih pridobila celo vojsko oboževalcev - približno 10.000 ljudi. Leta 2013 je bil Facebook zelo rad vključil slike iz Pushina v zbirke z drugimi emotikoni. Po pogajanjih z ustvarjalcem je bila ta ideja uresničena in »raznesla« internet! Slike iz mačke Pusheen se v korespondenci uporabljajo več kot 10 milijonkrat na dan!
Leta 2014 je eden največjih proizvajalcev igrač v Združenih državah Amerike posvetil svojo pozornost temu liku. GUND (ona je izumila medvedke) je lansiral par modelov Pushin. Ker je bil uspeh ogromen, je bila čez nekaj mesecev ustvarjena celotna zbirka igrač v obliki te mačke.
Kje drugje lahko srečate mačko Pusheen? V darilnih kompletih od podjetja Isaac Morris Ltd, v penastih bombonih iz Boomf in, seveda, v naši zbirki kazalcev Pusheen!',
];
