<?php

return [
    'title' => 'Сursor Style - Pogoji uporabe našega izdelka',
    'descr' => 'Pogoji uporabe so dogovor med vami in “Cursor Style” (“Storitev”, “mi” ali “Storitev”). Ta storitev je ponujena in na voljo uporabnikom, starim 13 let in več, samo za osebno uporabo in ne za komercialno uporabo.',
    'text' => '<h2> Pogoji uporabe </h2>
<h3> PROSIMO, PREBERITE TE POGOJE PRED UPORABO SPLETNE STRANI IN RAZŠIRITVE. </h3>
<p> Ti pogoji uporabe so sklenjeni med vami in "Cursor Style" ("Storitev", "mi" ali "Storitev"). Ti naslednji pogoji in določila skupaj z vsemi dokumenti, ki jih izrecno vključujejo v referenco (skupaj, ti "Pogoji uporabe"), urejajo vaš dostop in uporabo spletnega mesta cursor.style in njegovih razširitev brskalnika, vključno z vsemi vsebinami, funkcionalnostjo in storitvami, ki se ponujajo na ali prek naše storitve (skupaj "Storitev"). </p>
<p> Z uporabo spletnega mesta ali razširitve se strinjate, da se strinjate s temi Pogoji uporabe. Če se ne strinjate s temi Pogoji uporabe ali našim <a href="/privacy"> Pravilnikom o zasebnosti </a>, ne smete dostopati do spletnega mesta in razširitve ali je uporabljati. </p>
<p> Ta storitev je na voljo samo uporabnikom, starim 13 let in več, samo za osebno uporabo in ne za komercialno uporabo. Z uporabo te Storitev izjavljate in jamčite, da ste (I) stari 13 let ali več, (II) vam uporaba spletnih mest ni prepovedana v skladu z veljavnim zakonom in (III) Storitev uporabljate samo za svoje osebne potrebe. Če ne izpolnjujete teh zahtev, ne smete dostopati do Storitev ali jo uporabljati. </p>
<p> Te Pogoje uporabe lahko občasno spremenimo in posodobimo po lastni presoji. Vse spremembe začnejo veljati takoj po objavi. Vaša nadaljnja uporaba Storitev po objavi revidiranih Pogojev uporabe pomeni, da se sprejemate in strinjate s spremembami. Pričakuje se, da boste to stran pogosto obiskovali, da boste na tekočem s kakršnimi koli spremembami, saj so te za vas zavezujoče. </p>
<p> Pridržujemo si pravico, da po lastni presoji in brez predhodnega obvestila umaknemo ali spremenimo to spletno mesto in razširitev, vse storitve ali materiale, ki jih nudimo na spletnem mestu in razširitvi. Ne zagotavljamo, da bodo naše spletno mesto, razširitev ali katera koli vsebina na njem, vedno na voljo ali da bodo neprekinjeni. Ne odgovarjamo, če iz kakršnega koli razloga vsi ali kateri koli del Storitev ni na voljo kadar koli ali v katerem koli obdobju. Občasno lahko omejimo dostop do določenih delov spletnega mesta ali razširitve ali celotne Storitev za uporabnike. </p>
<p> Odgovorni ste za sprejetje vseh potrebnih ukrepov, da zagotovite dostop do Storitev. Zagotavljanje, da so vse osebe, ki dostopajo do Storitev prek vaše internetne povezave, seznanjene s temi Pogoji uporabe in jih upoštevajo. Da bi lahko dostopali do Storitev ali nekaterih virov, ki jih ponuja, boste morda morali posredovati določene podatke ali druge podatke. Strinjate se, da za vse podatke, ki nam jih posredujete s to Storitev ali na drug način, vključno z, vendar ne omejeno na, uporabo katere koli interaktivne funkcije v Storitev, velja naš <a href="/privacy"> Pravilnik o zasebnosti </a>, in se strinjate z vsemi dejanji, ki jih sprejmemo v zvezi z vašimi podatki. v skladu z našim <a href="/privacy"> Pravilnikom o zasebnosti </a>. </p>
<p> Bodite še posebej previdni pri vnosu osebnih podatkov v Storitev na javnem ali skupnem računalniku, da drugi ne morejo videti ali zabeležiti vaših osebnih podatkov. Spletno mesto, razširitev in vsa njena vsebina, funkcije in funkcije (vključno z, vendar ne omejeno na, vse informacije, razširitev, besedilo, slike, slike, slike in kazalce, kot tudi njihovo načrtovanje, izbira in umestitev) pripadajo "Cursor Style", njegovim dajalcem licence ali drugim dobaviteljem takšnih materialov so zaščiteni z avtorskimi pravicami, blagovno znamko, patentom, poslovno skrivnostjo in drugimi zakoni o intelektualni lastnini ali lastninskimi pravicami. </p>
<p> Ti Pogoji uporabe vam omogočajo uporabo spletnih mest samo za vašo osebno, nekomercialno uporabo. Materialov na našem spletnem mestu ne smete reproducirati, distribuirati, spreminjati, ustvarjati izpeljanih del, ponovno objavljati, prenašati, shranjevati ali prenašati, razen v naslednjih primerih: lahko ga uporabljate za osebne potrebe, lahko natisnete ali prenesete eno kopijo razumne količine strani spletnega mesta in razširitve ali njihove vsebine za osebno, nekomercialno uporabo in ne za nadaljnjo reprodukcijo, objavo ali distribucijo. </p>
<p> Ne smete spreminjati kopij nobenega materiala s tega spletnega mesta ali razširitve in njihove vsebine. Izbrišite ali spremenite obvestila o avtorskih pravicah, blagovnih znamkah ali drugih lastniških pravicah iz kopij tega spletnega mesta in razširitve. Ne smete imeti dostopa ali uporabljati za komercialne namene nobenega dela spletnih mest ali razširitev, pa tudi nobene storitve ali materialov, ki so na voljo prek spletnega mesta ali razširitve. </p>
<p> Če želite uporabiti kakršen koli material na Spletna mesta ali Razširitve, ki niso navedeni v tem razdelku, pošljite zahtevo na stran za podporo spletne trgovine Chrome. </p>
<p> Če natisnete, kopirate, spremenite, prenesete ali na drug način uporabite ali omogočite dostop do katerega koli dela spletnega mesta ali razširitve v nasprotju s Pogoji uporabe, se vaša pravica do uporabe spletnega mesta in razširitve takoj prekine in morate , po naši presoji, vrniti ali uničiti vse kopije materialov, ki ste jih ustvarili. Vsaka uporaba spletnega mesta razširitve, ki ni izrecno dovoljena s temi Pogoji uporabe, krši te Pogoje uporabe in lahko krši avtorske pravice, blagovne znamke in druge zakone. </p>
<p> Ime “Cursor Style”, logotip “Cursor Style” in vsa povezana imena, logotipi, slike, kazalci in imena storitev, modelov in sloganov so blagovne znamke družbe “Cursor Style” ali njenih povezanih družb ali dajalcev licence. Takšnih znamk ne smete uporabljati brez predhodnega pisnega dovoljenja Storitev. Vsa druga imena, logotipi, imena izdelkov in storitev, modeli in slogani na tem spletnem mestu in v razširitvi so blagovne znamke njihovih lastnikov. Storitev lahko uporabljate samo za zakonite namene in v skladu s temi Pogoji uporabe. </p>
<h3> Strinjate se, DA ne boste uporabljali Storitev: </h3>
<ul>
<li> Na kakršen koli način, ki krši veljavne zvezne, regionalne, lokalne ali mednarodne zakone ali predpise (vključno z, vendar ne omejeno na, vse zakone v zvezi z izvozom podatkov ali programske opreme v Rusijo in druge države). </li>
<li> Z namenom izkoriščanja, škode ali poskusov uporabe ali škode mladoletnikom, njihove izpostavljenosti neprimerni vsebini, zahtevanja informacij, ki jih identificirajo, ali na drug način. </li>
<li> Za pošiljanje, zavestno prejemanje, prenos, uporabo ali ponovno uporabo kakršnih koli materialov, ki niso v skladu s temi Pogoji uporabe. </li>
<li> Prenos ali nakup pošiljanja oglasov ali promocijskega gradiva brez našega predhodnega pisnega soglasja, vključno z vsemi "nepoklicani pismi", "verižnimi pismi" ali "nezaželeno pošto" ali drugimi podobnimi ponudbami. </li>
<li> Da bi se izdajali za ali poskušali izdajati zaposlenega “Cursor Style”, drugega uporabnika ali katero koli drugo osebo ali organizacijo (vključno z, vendar ne omejeno na, uporabo e-poštnih naslovov ali vzdevkov, povezanih s katerim koli od zgoraj navedenih). </ li >
<li> Sodelovanje pri vseh drugih dejanjih, ki omejujejo ali ovirajo uporabo Storitev ali uporabo koga, ali ki, kot ugotovimo, lahko škodijo Storitev ali uporabnikom Storitev ali jih naredijo odgovorne. </li> </ul>
<h3> Poleg tega se strinjate, DA NE boste: </h3>
<ul>
<li> Uporabljati Storitev na kakršen koli način, ki lahko onemogoči, preobremeni, poškoduje ali poslabša delovanje spletnega mesta, razširi ali posega v uporabo Storitev s strani katere koli druge stranke, vključno z njihovo zmožnostjo sodelovanja v dejanjih v realnem času prek Storitev. </li>
<li> Uporabljati kakršna koli orodja za avtomatizacijo, postopek ali sredstva za dostop do Storitev za kakršen koli namen, vključno z nadzorom ali kopiranjem katerega koli materiala v Storitev. </li>
<li> Uporaba katerega koli ročnega postopka za sledenje ali kopiranje kakršnih koli materialov o Storitev ali za kakršne koli druge nepooblaščene namene brez našega predhodnega pisnega soglasja. </li>
<li> Uporaba katere koli naprave, programske opreme ali postopkov, ki ovirajo normalno delovanje Storitev. </li>
<li> Uvesti kakršne koli viruse, trojanske konje, črve, logične bombe ali druge materiale, ki so škodljivi ali tehnološko škodljivi. </li>
<li> Poskusite pridobiti nepooblaščen dostop, posegati, poškodovati ali motiti kateri koli del Storitev, strežnika, na katerem je Storitev shranjena, ali katerega koli strežnika, računalnika ali zbirke podatkov, povezanih s Storitev. </li>
<li> Napad na Storitev z napadom zavrnitve storitve ali napadom razdeljene zavrnitve storitve. </li> </ul>
<p> Informacije, ki so na voljo na ali prek Storitev, so na voljo samo v splošne informativne namene. Ne zagotavljamo točnosti, popolnosti ali uporabnosti teh informacij. Zanašate se na takšne informacije samo na lastno odgovornost. Odpovedujemo se vsem odgovornostim in obveznostim, ki izhajajo iz kakršnega koli vaše ali katerega koli drugega obiskovalca Storitev ali katerega koli drugega, ki bi lahko bil obveščen o vsebini, pri čemer se zanašate na takšne materiale. </p>
<p> Ta Storitev vključuje vsebino, ki jo zagotavljajo tretje osebe, vključno z materiali, ki jih zagotavljajo drugi uporabniki in dajalci licence tretjih oseb, sindikati, agregatorji in / ali storitve poročanja. Vse izjave in / ali mnenja, izražena v teh materialih, kot tudi vsi članki in odgovori na vprašanja in druga vsebina, razen vsebine Storitev, so izključno mnenja in odgovornosti osebe ali organizacije, ki zagotavlja te materiale. Ti materiali nujno ne odražajo stališč Storitev. Ne odgovarjamo vam ali kateri koli tretji osebi za vsebino ali točnost katerega koli materiala, ki ga zagotavljajo tretje osebe. </p>
<p> Vsebino Storitev lahko občasno posodobimo, vendar njena vsebina ni nujno popolna ali aktualna. Vsak material na Storitev je lahko kadar koli zastarel in mi nismo dolžni posodobiti tega materiala. Informacije in vsebino na spletnem mestu in v Razširitvi lahko posodobimo, spremenimo, spremenimo, naredimo vse spremembe in posodobitve po lastni odločitvi. </p>
<p> Za vse podatke, ki jih zbiramo na tej Storitev, velja naš Pravilnik o zasebnosti. Z uporabo Storitev se strinjate z vsemi dejanji, ki jih sprejmemo v zvezi z vašimi podatki v skladu s <a href="/privacy"> Pravilnikom o zasebnosti </a>. </p>
<p> Dodatni pogoji lahko veljajo tudi za določene dele, storitve ali funkcije Storitev. Vsi takšni dodatni pogoji in določila so s tem vključeni v referenco v te Pogoje uporabe.
Lahko se povežete z našim spletnim mestom ali razširitvijo, če to storite na pošten in zakonit način in ne škodujete našemu ugledu ali ga uporabljate, vendar povezave ne smete nastaviti na tak način, da bi ponudili kakršno koli obliko povezave, podpore ali potrditve z naše strani brez našega pisnega soglasja. </p>
<p> Storitev vsebuje povezave do drugih mest in virov, ki jih zagotavljajo tretje osebe, te povezave so na voljo samo za vaše udobje. To vključuje povezave v oglasih, vključno z oglasnimi pasicami in sponzoriranimi povezavami. Ne nadzorujemo vsebine teh spletnih strani ali virov in nismo odgovorni zanje ali za kakršno koli izgubo ali škodo, ki je lahko posledica njihove uporabe. Če se odločite za dostop do katerega koli spletnega mesta tretjih oseb, povezanega s to Storitev, to storite na lastno odgovornost in v skladu s pogoji uporabe takšnih spletnih strani. Pridržujemo si pravico, da prekličemo dovoljenje za povezavo brez predhodnega obvestila. </p>
<p> Razumete, da ne moremo in ne zagotavljamo ali jamčimo, da datoteke, ki so na voljo za prenos prek interneta ali na spletnih mestih, ne bodo vsebovale virusov ali druge zlonamerne kode. Odgovorni ste za izvajanje postopkov in kontrolnih točk, ki so zadostni za zadovoljitev vaših posebnih zahtev glede protivirusne zaščite in natančnosti vnosa in izhoda podatkov, kot tudi za vzdrževanje sredstev zunaj našega spletnega mesta za obnovo izgubljenih podatkov. NE ODGOVARJAMO ZA KAKRŠNO KOLI ŠKODO ALI POŠKODBO, KI JIH POVZROČI napad razdelitve STORITEV, VIRUSI ALI DRUGA TEHNOLOGIJA-MALWARE NAČRTOVANI PREK STORITEV ALI S PRENOSOM KAKRŠNEGA KOLI MATERIALA, POSLANEGA, ALI NA KATERIH KOLI SPLETNIH STRANEH, POVEZANIH, KI LAHKO OKUŽIJO ALI POŠKODUJEJO VAŠO RAČUNALNIŠKO OPREMO, RAČUNALNIŠKO PROGRAMSKO OPREMO, PODATKE. </p>
<p> STORITEV, NJENO VSEBINO IN STORITVE ALI PREDMETE, PRIDOBITVE PREK STORITEV, UPORABLJATE NA LASTNO ODGOVORNOST. STORITEV, NJENA VSEBINA IN STORITVE ALI PREDMETI, PRIDOBITVE PREK SPLETNE STRANI IN RAZŠIRITVE, SO POSREDOVANE NA PODLAGI "KAKRŠNA JE" IN "KOT JE NA VOLJO", BREZ KAKRŠNE KOLI GARANCIJE. KATERA KOLI OSEBA, POVEZANA S STORITVIJO, NE NUDI KAKRŠNE KOLI GARANCIJE ALI PREDSTAVITVE V ZVEZI S POPOLNOSTJO, VARNOSTJO, ZANESLJIVOSTJO, KAKOVO, NATNOSTJO ALI DOSTOPNOSTJO STORITVE. BREZ OMEJITVE ZGORAJ NAVEDENEGA, NE "CURSOR STYLE" NITI POVEZANA S PREDSTAVNIKI "CURSOR STYLE" NE ZAGOTAVLJA, DA SO STRAN, RAZŠIRITEV, NJENA VSEBINA ALI KAKRŠNA KOLI POPRAVILA, MORAJO BITI PREDHODNO NA VOLJO, POPRAVLJENO, DA NAŠA RAZŠIRITEV, STRAN ALI STREŽNIK, KI JO ZAGOTAVLJA, NE BO BREZ VIRUSOV ALI DRUGIH ŠKODLJIVIH KOMPONENT ALI TE SPLETNE STRANI ALI KAKRŠNIH STORITEV ALI PREDMETOV , IZVEDENIH, PREDLOŽENIH.
<p> V NOBENEM PRIMERU NE SMEJO ODGOVARJATI STORITEV, NJENI PODRUŽNICE ALI LICENCODAJALCI, STORITVE, ZAPOSLENI, ZASTOPNIKI, URADNIKI ali DIREKTORJI ZA KAKRŠNO KOLI ŠKODO, MI STORITEV KAKRŠNOKOLI ODGOVORNOST. ALI TAKŠNA DRUGA SPLETNA MESTA ALI KAKRŠNE STORITVE ALI PREDMETI, PRIDOBITE V STORITEVAH ALI NA DRUGE SPLETNE STRANI, VKLJUČNO Z VSE UNIČNI, POSEBNI ALI POSLEDIČNI ŠKODO, VKLJUČNO Z OSEBNO POŠKODBO, čustvenimi motnjami, POŠKODBAMI ALI PRIČAKOVANIMI HRANJENJI, IZGUBO UPORABE, PODATKOV ALI DRUGIH OKOLIŠČIN . OPREDELITEV NE VPLIVA NA KAKRŠNO KOLI ODGOVORNOST, KI JE NI MOGOČE IZKLJUČITI ALI OMEJITI V SKLADU Z VELJAVNIM ZAKONOM, KI LAHKO VKLJUČUJE ZLOČIN. </p>
<p> Strinjate se, da boste zaščitili, odškodnili in izpraznili “Cursor Style”, njegove podružnice, dajalce licence in ponudnike storitev, kot tudi njegove in njihove ustrezne uradnike, direktorje, zaposlene, izvajalce, zastopnike, dajalce licence, dobavitelje, dodelitve in iz kakršnih koli zahtevkov in obveznosti, izgube sodnih odločb, stroškov, stroškov ali provizij (vključno s stroški odvetnikov), ki izhajajo iz ali v povezavi z vašo kršitvijo teh Pogojev uporabe ali uporabo Storitev, vključno z, vendar ne omejeno na, obravnavo kakršne koli uporabe vsebine, storitev in izdelkov spletnega mesta ali razširitve, razen kot je izrecno določeno v teh Pogojih uporabe, ali vaše uporabe katere koli informacije, prejete od Storitev. </p>
<p> Če se ugotovi, da je katera koli določba teh Pogojev uporabe neveljavna, nezakonita ali neizvršljiva s strani sodišča ali drugega sodišča pristojne jurisdikcije iz kakršnega koli razloga, bi bilo treba to določbo razveljaviti ali omejiti na najmanjšo mero, tako da bo ostali določbe Pogojev uporabe bodo še naprej veljale v celoti. Pogoji uporabe, naš Pravilnik o zasebnosti in pogoji za registracijo dogodkov predstavljajo edini in popoln sporazum med vami in "Cursor Style" v zvezi s Storitev ter nadomestijo vse prejšnje in istočasne sporazume, dogovore, izjave in garancije, tako pisne kot ustne, v zvezi s Storitev . </p>
<p> Vse ocene, komentarje, zahteve za tehnično podporo in druga sporočila v zvezi s Storitvijo je treba nasloviti na stran za podporo "Cursor Style" v spletni trgovini Chrome. </p> ',
];
