<?php

return [
    'halo_descr' => 'Halo je borbena fantazijska medijska franšiza koju je kreirao Bungie. Zasnovana je na originalnoj trilogiji pucačina iz prvog lica. Radnja se vrti oko događaja koji se odvijaju u životu Master Chief-a, jednog od grupe super-vojnika kodnog imena Spartans, i njegove saputnice, veštačke inteligencije Cortane. Uspeh igara doveo je do širenja franšize u druge medije: Halo univerzum trenutno obuhvata mnoge knjige, grafičke romane, stripove, kratke filmove, animacije i igrane filmove.',
    'halo_short_descr' => 'Dodirnite kursor artefakta, možda ste vi izabrani.',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'LOL Surprise lutke su se zaljubile u decu i osvojile njihova srca od prvih minuta. I to ne iznenađuje, jer se takav uspeh zasniva na misteriji, očekivanju čuda, prijatnog iznenađenja, koje oduševljava ne samo decu, već i njihove roditelje. Tajna poklona se otkriva detetu tek nakon konačnog raspakivanja. U svakom slučaju, LOL lutke su atraktivan dizajn, intriga, veliki broj neverovatnih i realističnih dodataka i prijatnih sitnica, kao i najviši kvalitet izrade i detaljnosti igračke.',
    'lol_surprise_short_descr' => 'Kul slatkiši za poznavaoce prelepih iznenađenja',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Serija se vrti oko takmičenja gde 456 igrača, svi u dubokim finansijskim dugovima, rizikuju svoje živote da bi igrali niz smrtonosnih dečijih igara za šansu da osvoje nagradu od milijardu. Unutra, primamljiva nagrada čeka sa smrtonosno visokim ulozima. Naslov serije crpi inspiraciju iz istoimene korejske dečije igre. Hwang je osmislio ideju na osnovu sopstvenih ekonomskih borbi u ranom životu, kao i klasne razlike u Južnoj Koreji i kapitalizmu.',
    'squid_game_short_descr' => 'Izaberite pravo lice igrača kada igrate na sve ili ništa',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Hari Džejms Poter je glavni lik serije romana engleske književnice Dž. K. Rouling. Na svoj jedanaesti rođendan, Hari saznaje da je čarobnjak i da je predodređen za mesto u Hogvorts školi za veštičarenje, gde će vežbati magiju pod vođstvom direktora Albusa Dambldora i drugih profesora u školi. Hari takođe otkriva da je već poznat u čarobnjačkoj zajednici romana i da je njegova sudbina povezana sa sudbinom Voldemorta, opasnog mračnog maga.',
    'harry_potter_short_descr' => 'Šta ćeš uraditi sa čarobnim štapićem iz kolekcije kursora Harija Potera',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics je izdavačka kuća stripova poznata po stvaranju značajnih superheroja kao što su Spider-Man, Iron Man, Captain America, Hulk, Thor, Osvetnici, Čuvari galaksije, X-Men, Fantastična četvorka i Deadpool. Marvelovi najpoznatiji negativci uključuju Zelenog Goblina, Crvenu Lobanju, Lokija, Thanosa, Ultrona, Dr. Doom i Magneto. Marvel Comics i DC Comics su sarađivali na nekoliko crossover projekata zajedno, a takođe su suosnivači namerno kratkotrajnog Amalgam Comics otiska.',
    'marvel_comics_short_descr' => 'Superheroj živi u svakom od nas - izaberite svog',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Dobrodošli nazad u Kraljevstvo Kolačića u Cookie Run: Kingdom od strane Devsisters, šarmantnom strateškom RPG-u smeštenom u svetu Cookie Run. Sada kada je Đumbir Hrabri pobegao iz rerne zle veštice, vreme je da napravi tim Kolačića i krene u potragu da obnovi srušeno Kraljevstvo Kolačića. Otkrijte istinu o padu Kraljevstva i sastavite ekipu najmoćnijih Kolačića iz Kraljevstva da pobedite mračne sile koje žele da spreče Đumbira Hrabrog da ispuni svoju sudbinu.',
    'cookie_run_kingdom_short_descr' => 'Mali ratnici pravo iz rerne',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact je avanturistička igra otvorenog sveta. To znači da vas čeka novi, divan pejzaž na drugoj strani reke ili planine, samo treba pametno iskoristiti energiju. Ako naiđete na lutajuću vilu ili čudan mehanizam, usudite se i pokušajte da razotkrijete njihovu misteriju. Ali šta obećavaju - nevolje ili prijatno iznenađenje - samo vi možete saznati! Na ogromnom kontinentu Teyvat, posetićete sedam kraljevstava, pronaći saputnike sa raznim veštinama i boriti se protiv moćnih neprijatelja u potrazi za izgubljenom voljenom osobom.',
    'genshin_impact_short_descr' => 'Postanite Elementalni Majstor Sedam Kraljevstava',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'Kada se drevno proročanstvo ostvari i kraljevstvo zaroni u zagrljaj zime, troje neustrašivih heroja - princeza Ana, hrabri Kristof i njegov verni irvas Sven - odlaze u planine da pronađu Anuinu sestru, Elzu, koja može da ukloni zlokobnu čini sa zemlje. Na putu ih čeka mnogo teških iznenađenja i uzbudljivih avantura. Upoznavanje mističnih trolova, susret sa šarmantnim sneškom Olafom, planinski vrhovi strmiji od Everesta i mnogo magije. Heroji moraju da se odupru moćnim elementima kako bi spasili kraljevstvo i one koji su im dragi.',
    'frozen_short_descr' => 'Probijanje leda je lako uz kolekciju Frozen kursora',
    'frozen' => 'Frozen',
    'stranger_things_descr' => 'Prošlo je nešto više od šest meseci od finala treće sezone. Džojs, Vil, Eleven i Džonatan su se preselili u Kaliforniju gde je devojčica žrtva vršnjačkog nasilja u školi. Ostali počinju da se bore protiv novog čudovišta iz paralelnog sveta koje se pojavilo u Hokinsu. Dobio je ime Vekna po liku iz društvene igre Dungeons & Dragons. On psihološki utiče na tinejdžere, zatim mentalno ulazi u glavu i ubija. Uporedo, Džojs i Mari saznaju da je Džim Goper živ i kreću za njim u sovjetski zatvor u Kamčatki. A Eleven će morati da se vrati i poveća svoje moći, ali i da sazna svoju važnu ulogu u stvaranju istog čudovišta u Gokinsu.

Pisci nisu promenili taktiku zapleta koja im se dopala u poslednjih nekoliko sezona. U četvrtoj sezoni podelili su veliku grupu glavnih likova na grupe, smislili teške zadatke za njih, a na kraju su svoje priče izgradili zajedno u neverovatnom završetku. Nudimo vam da detaljno razumete sve ove avanture uz pomoć kolekcije kursora Stranger Things.',
    'stranger_things_short_descr' => 'Šta će se sledeće desiti? - Kursori Stranger Things 4',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars je originalni mod koji se prvi put pojavio u Minecraft-u. Zadatak igrača je bio da korisnici zaštite svoju bazu i krevet.

Roblox svakodnevno donosi uzbudljivije igre, a BedWars nije izuzetak. I stvar je u tome, ako volite Bed Wars i branite se u svojoj sobi, ovo je naslov za vas jer vas vraća u detinjstvo, doduše digitalno ovaj put.

Sve što treba da uradite je da branite svoj krevet od napadača sa svojim partnerom. Ulazite u lobi, birate sa kim ćete igrati i voila, samo je pitanje zaštite.

Naravno, kada je reč o odbrani, imaćete određenih problema i postoje određeni resursi, predmeti i stavke koje će vam pomoći da pobedite. Na primer, ekskluzivne skinove koje ćete pronaći u Bed Wars kolekciji kursora.',
    'roblox_bed_wars_short_descr' => 'Zaštitite svoj krevet pomoću Roblox Bed Wars kursora',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'Na rođendan Narutoa Uzumakija, legendarni demon, Lisica sa devet repova, napala je selo Konoha. Četvrti Hokage, po cenu svog života, spasao je selo zapečativši demona u novorođenog Narutoa, nesvesno ga osudivši na život mržnje od strane svojih sugrađana.
Uprkos nedostatku talenta u mnogim oblastima ninjutsua, nemiru i oholosti, Naruto sanja da postane Hokage, najjači nindža u selu. Želeći priznanje koje nije dobio, on vredno radi i trenira zajedno sa svojim saigračima Sasukeom Uchiha i Sakurom Haruno, kao i sa svojim mentorom Kakashijem Hatakeom. On i njegovi partneri će morati da prođu kroz mnogo toga na putu do svojih dragih snova: bitke, ljubav, prijateljstvo, izdaja, žeđ za moći. Kolekcija Naruto anime kursora će vam pomoći da se krećete sopstvenim putem!',
    'naruto_anime_short_descr' => 'Koračajte svojim nindža putem sa Naruto anime kursorima',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'Radnja se odvija u eri Taišo. Od davnina kruže glasine da u šumi žive humanoidni demoni, koji se hrane ljudima i hodaju noću, tražeći novu žrtvu. Ali... to je samo legenda, zar ne?..

Tanjiro Kamado je najstariji sin u porodici, koji je izgubio oca i brinuo se o svojoj porodici. Jednog dana ide u obližnji grad da proda ćumur. Vraćajući se ujutro, momak otkriva užasnu sliku ispred sebe: svi rođaci su brutalno ubijeni, a jedini preživeli je Nezuko, mlađa sestra pretvorena u demona, ali koja još nije izgubila svu svoju humanost.

Od ovog trenutka, Tanjiro i Nezuko započinju dugo i opasno putovanje, u kojem dečak namerava da pronađe ubicu i pronađe način da izleči svoju sestru. Ali da li deca mogu da prevaziđu sve poteškoće i vrate se kući? Već znate odgovor, a ako ne - radije postavite kursore Demon Slayer, sa likovima iz jedne od najpopularnijih manga.',
    'demon_slayer_anime_short_descr' => 'Kursori iz serijala *Demon Slayer* - za prave noćne lovce',
    'demon_slayer_anime' => 'Demon Slayer anime',
    'bts_descr' => 'BTS je sedmočlana muška grupa pod agencijom BigHit Music. Debitovali su 13. juna 2013. godine sa singlom "No More Dream". U Japanu su debitovali 24. decembra 2014. godine sa studijskim albumom Wake Up.

Ime grupe potiče od korejskog izraza Bangtan Sonyeondan, što znači "izviđači otporni na metke". Prema J Hopeu, ime označava želju benda da blokira stereotipe, kritike i očekivanja koja su usmerena na tinejdžere kao što su metki.

Kolekcija kursora posvećena grupi uključuje sve članove grupe, ovde je kursor Kim Nam Joon (poznat i kao RM), kursor Kim Seok Jin (Jin), kursor Min Yoongi (Suga), kursor Jung Ho Suk (J-Hope), kursor Park Ji Min (Jimin), kursor Kim Tae Hyun (V) i kursor Jeon Jungkook (Jungkook).',
    'bts_short_descr' => 'Upoznajte svoje idole sa BTS kursorima',
    'bts' => 'BTS',
    'miraculous_descr' => 'Mirakulos: Avanture Bubamare i Crnog Mačka, poznatiji kao Mirakulos Bubamara i Crni Mačak, su avanture superheroja iz crtanog filma o dva školska druga koji, ispod maski, igraju ulogu branilaca Pariza od zlikovca koji u svakoj epizodi smišlja novi način da naudi gradu. Mirakulos je napravljen u Francuskoj korišćenjem CGI i animacije. Mirakulos nije samo animirana serija, već i kolekcija stripova objavljenih širom sveta. Serija je veoma omiljena kod mlade publike.

Radnja se odvija u Parizu, gde su Marinete i Adrijan srednjoškolci u savremenoj školi. Dali su im ulogu da postanu izabrani u borbi protiv zla, spašavajući svoj rodni grad. Njihov cilj je da zaštite ljude od Akuma. Ova mala stvorenja u obliku leptira mogu da nasele osobu i pretvore je u zlikovca.

Marineta se može transformisati u bubamaru, a Adrijan - u Crnog Mačka, ali iznenađujuće, radeći u paru, ne prepoznaju jedno drugo ispod maski superheroja.

Pomozite Crnom Mačku i Bubamari da spasu Pariz sa našim kursorima sa vašim omiljenim likovima. Koji lik ćete odabrati za kursor? Da li će to biti kursor Mirakulos Bubamare, ili možda Tikkina preslatka mala Bubamara ili kursor Crnog Mačka? Ili možda Kraljica Pčela sa kursorima Rena Ruža? Izbor je vaš!',
    'miraculous_short_descr' => 'Pridružite se redovima superheroja uz kolekciju kursorа Bubamare i Crnog Mačka',
    'miraculous' => 'Čudesna: Avanture Bubamare i Crnog Mačka',
    'talking_tom_descr' => 'Serija prati svakodnevni život Talking Toma i njegovih prijatelja. Tom i njegov štreberski poslovni partner Ben neprestano razvijaju mobilne aplikacije i druge izume kako bi postigli slavu i bogatstvo i pokušavaju da se pokažu svetu, ali to uvek krene po zlu. Tomova devojka, Angela, pokušava da bude pevačica, bez obzira na to šta radi da bi to postigla. Tomov komšija, Ginger, vrlo često svraća ovde da bi pravio psine sa nestašlucima u rukavu. Glupi najbolji prijatelj i cimer Hank je domaćin, gleda VRLO TV. A bivša disidentska pop zvezda Becca Sparkles postala je Angelinina nova cimerka i čini se da se zaljubila u Hanka. Međutim, bez obzira na to koliko su stvari loše svih oblika i veličina, bilo da je to zli izvršni direktor, Tomov misteriozni novi komšija, ili samo nezgoda u Benovoj novoj kreaciji, ekipa će se zabavljati bez obzira na sve, i uvek će se sećati jedne stvari koja ih drži zajedno: prijateljstvo nikada ne prestaje, baš kao što naša ljubav prema likovima iz serije ne prestaje, pa sada možete da podesite kursor Talking Toma ili Benov kursor, ili možda Angelin kursor, Oliverov kursor!',
    'talking_tom_short_descr' => 'Hajde da pričamo o tvom omiljenom liku iz kolekcije kursora Talking Tom.',
    'talking_tom' => 'Talking Tom i prijatelji',
    'lego_descr' => 'Kompanija The LEGO Group osnovana je davne 1932. godine i tada je imala samo 7 ljudi. Cilj Lego tima bio je da stvori igračke koje razvijaju dečiju kreativnost, maštu i domišljatost. Neverovatna činjenica, od svog osnivanja 1949. godine, LEGO elementi u svim svojim varijantama ostali su kompatibilni jedni sa drugima. Svi predmeti kreirani kasnije i dalje su kompatibilni sa predmetima koji se objavljuju danas, uprkos promenama u dizajnu i obliku tokom godina.

LEGO kocka je osnova, koja je šuplji plastični blok koji se povezuje sa drugim sličnim kockama. Ali Lego setovi takođe sadrže i druge delove, točkove, figure, platforme, pa čak i elektronska kola sa senzorima i električnim motorima. Možete sakupljati modele automobila, aviona, vozova, brodova, zgrada, robota. LEGO se pridržava ideje modularnosti, što jasno demonstrira deci kako da rešavaju određene probleme, razvijaju maštu, finu motoriku ruku i veštine sklapanja. LEGO kocke su izrađene sa neverovatnom preciznošću i savršeno se uklapaju za zapanjujuću preciznost od 10 mikrona.

Nedavno je stvoreno mnogo popularnih 3D animiranih Lego priča, gde likovi iz setova oživljavaju i postaju učesnici neverovatnih avantura. Ako želite kul kursor, u našoj Lego Cursors kolekciji pronaći ćete mnogo likova iz Lego TV serija i animiranih filmova. Lego Ninjago Kursor, Lego Batman Kursor, Lego Ninjago Kursor, Lego Wyldstyle Kursor i mnogi drugi.',
    'lego_short_descr' => 'Izgradite svoj san o pregledaču sa kolekcijom Lego kursora.',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Nakon uspešnog finansiranja putem Kickstartera, 2017. godine, Team Cherry je izdao multiplatformsku PC igru Hollow Knight. Ovo je priča o bezimenom vitezu i njegovim otkrićima u kraljevstvu insekata Hallownest. Igra je s pravom prepoznata kao jedna od najboljih u metroidvania žanru.

Igranje Hollow Knighta zasniva se na istraživanju sveta igre. Savladavanje prepreka, rešavanje zagonetki i pronalaženje tajni, kao i borba sa neprijateljima. Igrač ima jedinstven set poboljšanja i trikova za istraživanje sveta i borbu u bitkama. Krećući se od zone do zone, igrač pobeđuje bosove i dobija potrebna poboljšanja za dalje napredovanje. Kao rezultat, igrači moraju da posete već pređene oblasti kako bi pronašli tajne i prošli kroz priču. I to je takođe uzbudljivo jer se zone menjaju svaki put, donoseći nova iznenađenja i iskustva. Igra se može igrati na različite načine, jer postoji nekoliko različitih puteva između zona. Prolazeći kroz priču, otvarate mapu zone, ali prvo morate dobiti mapu.

Glavno oružje heroja je ekser, koji je pomalo sličan maču, oružje se može poboljšati kod kovača, kao i naučiti različite veštine u korišćenju oružja, što proširuje raznolikost napada. Napadajući neprijatelje, akumulirate poseban resurs, koji se kasnije može koristiti za poboljšanja ili lečenje.
Zabavite se igrajući Hollow Knight i ne zaboravite da koristite naše Hollow Knight kursore sa vašim omiljenim likom. Naša kolekcija uključuje kursor Mister Mushroom, kursor Quirrel, kursor Igla Hornet, kursor Stari Ekser, kursor Myla, i još.',
    'hollow-knight_short_descr' => 'Pokušajte da se ne izgubite u kraljevstvu insekata koristeći kolekciju kursora Hollow Knight',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henri Stikmen je glavni lik u serijalu. Stikmin, ranije bez imena, započeo je kao sitni lopov, sa željom da brzo zaradi lak novac. Međutim, nakon bekstva iz zatvora Vest Mesa, mnoge promene se dešavaju u njegovom životu, i on postaje poznati kriminalac nakon što je ukrao tuniski dijamant. Henri ima izbor - da postane uspešan vladin agent, lovac na ucene, vođa kriminalne organizacije, kiborg, ili da sam nastavi kriminalni put. Igra oduševljava ljubitelje žanra mnogim avanturama i misterijama, a vi ćete pronaći našu novu kolekciju Henri Stikmen kursorima sa njegovim smešnim likovima, uključujući Henri Stikmin kursor, Čarls Kalvin kursor, Redžinald Koperbotom kursor, kursor Desna Ruka, Eli Rouz kursor i druge!',
    'henry-stickmin_short_descr' => 'Planirajte svoj beg od dosade sa kolekcijom kursora Henrija Stikmena',
    'henry-stickmin' => 'Henri Stikmen',
    'adopt-me_descr' => 'Veoma popularna onlajn igra Adopt Me je lansirana 2017. godine i postala je najpopularnija na Roblox gejming platformi. Suština igre je vrlo jednostavna - dobiti jaja sa ljubimcima i brinuti o njima.

Virtuelni ljubimci su podeljeni u 5 klasa, neki od njih su vrlo retki i skupi, dok se do drugih vrlo lako dođe. To su Neobične grupe, kao što je Plavi pas, Uobičajeni, Retki kursor, na primer, Adopt Me Majmun kursor miša, kao i ultra-retki, kao što je Koala kursor, i Legendarni, Zmaj kursor i Adopt me jednorog. Ako igrač ima četiri odrasla ljubimca iste vrste, može da ih kombinuje u neon ljubimca, kao što je Neon Konj kursor igre ili Adopt Me Neon Morske zvezde. Kombinovanjem četiri obična ljubimca, možete napraviti neon ljubimca koji zaista sija, a od neon ljubimaca možete kreirati mega-neon ljubimca.

Kupovina u igri Adopt Me! se obavlja sa virtuelnom valutom Roblox - takozvani Robux, a igra takođe ima svoju valutu - Bucks. Brinući o svom ljubimcu, pored zabave, možete zaraditi bucks, samo ga nahranite, stavite u krevet ili mu čitajte bajku, generalno, mnogo zanimljivih stvari.

Sada fanovi Roblox igre "Adopt Me!" mogu da ukrase svoj kursor igre omiljenim ljubimcem!',
    'adopt-me_short_descr' => 'Zabavite se sa slatkim ljubimcima u našoj Adopt Me! kolekciji kursora iz igara',
    'adopt-me' => 'Udomi me!',
    'among-us_descr' => 'Among Us je zasnovan na čuvenoj igri uloga "Mafija". Planirano je da igra bude ekskluzivna za mobilne uređaje, jer je imala samo jednu mapu. Igra je brzo postala popularna. Kasnije je razvojni tim dodao režim za više igrača, a dve dodatne mape su objavljene 2019. godine.
Among Us je igra iz trećeg lica, iz ptice perspektive, koja omogućava igraču da se kreće u svim smerovima. Od četiri do deset igrača može igrati u jednom krugu. Na početku igre, svakome se tajno dodeljuje uloga izdajnika ili člana posade. Impostor (u ruskom prevodu "Izdajnik") može se sakriti u ventilacionom otvoru, sabotirati i ubijati članove posade. Njegov cilj je da uništi sve članove posade ili da uništi svemirski brod sabotažom. Cilj posade broda je da reši razne zagonetke pripremljene za njih na početku igre. Ako svaki od članova posade završi sve zadatke, izdajnici će izgubiti. Takođe, posada broda može ostvariti pobedu eliminisanjem izdajnika tokom glasanja.
Izdajnici mogu s vremena na vreme da sabotiraju i ako se kvarovi ne poprave u roku od 30 sekundi, posada će izgubiti. Pre početka igre, možete izabrati boju lika za koga igrate, plavu, crvenu, žutu, sivu - šta god! I ne zaboravite da sebi postavite odgovarajući kursor iz nove Among Us kolekcije!',
    'among-us_short_descr' => 'Ne dajte se prevariti u ovoj komplikovanoj svemirskoj igri sa Among Us kursorima',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Kreator serije "Stiven Univerzum" je Rebeka Šugar. Ona je poznata po svom prethodnom radu pod nazivom Adventure Time. Prva epizoda Stiven Univerzum-a je objavljena na video platformi YouTube u proleće 2013. Ali u jesen, američki kanal Cartoon Network je počeo da je emituje svojim gledaocima. Od tada je objavljeno 6 sezona. Šesta obećava da će biti poslednja.
Što se tiče radnje animirane serije, ona se vrti oko tima Kristalni Dragulji. Sastoji se od vanzemaljskih stvorenja sa karakterističnim imenima: Biseri, Ametist i Granat. Ali postoji još jedan učesnik u njemu, u ulozi koga glumi običan dečak Stiven. Zajedno traže čudovišta i pokušavaju da ih neutrališu kako ne bi preuzeli Zemlju za ličnu korist. Suprotstavljaju im se Žaspar i Peridot - glasnici sa njihove matične planete koji žele da pobede Dragulje i uključe Klaster.
Ako ste ljubitelj Stiven Univerzum-a i želite da vidite likove iz animirane serije gde god možete, instalirajte ekstenziju Cursor Style! Zašto to uraditi? Možete dodati kolekciju posvećenu "Stiven Univerzumu" i pretvoriti standardni pokazivač miša u jedan od vaših omiljenih likova.',
    'steven_universe_short_descr' => 'Otkrijte tajnu dragulja sa kursorima iz Stivena Universea',
    'steven_universe' => 'Stiven Universe',
    'family_guy_descr' => 'Animirana serija pod nazivom "Family Guy" je u čitavoj istoriji svog postojanja 4 puta osvojila nagradu Emi i 3 puta "Annie". Animirana serija ismeva bolne teme američkog društva, kao što su: feminizam, ropstvo, gojaznost, politika, itd. Za razliku od drugih dela, ovde se koriste umeci sa šalama i sarkazmom. Štaviše, u mnogim slučajevima oni nisu integrisani u zaplet, već postoje sami za sebe.
Jedna epizoda animirane serije se kreira preko 10 meseci. Zašto toliko dugo? Zato što se čitava animacija crta ručno. Zbog toga, neki od događaja koje delo pokriva imaju vremena da izgube na relevantnosti. Ali čak i tako, sitkom ostaje veoma zanimljiv i dobija naklonost gledalaca širom sveta. Uostalom, ko ne voli da se dobro nasmeje političarima, poznatim ličnostima ili ljudima koji čine divlje ludosti i time iznenade ili čak šokiraju obične ljude.
Da li volite "Family Guy"? Imate jedinstvenu priliku da pretvorite normalni kursor miša u bilo koji od likova ove animirane serije! Šta treba da uradim? Samo instalirajte ekstenziju pretraživača “Cursor Style”, dodajte joj kolekciju posvećenu “Family Guy”, i uživajte u fantastičnoj reinkarnaciji!',
    'family_guy_short_descr' => 'Kolekcija kursorâ iz „Porodičnog čoveka“ za poznavaoce specifičnog humora',
    'family_guy' => 'Porodični čovek',
    'cute_cursors_descr' => 'Sigurno ste čuli izraz "Lepota će spasiti svet"? Dakle, mnogi ljudi, posebno devojke, slažu se sa ovom izjavom. Zbog toga se trude da se okruže svime što je najlepše i prijatno za oko. To mogu biti roze tapete u spavaćoj sobi, mekane igračke, jastuci izvezeni perlama, dragoceni nakit, itd. Spolja, sve to izgleda veoma slatko, pa čak i pomalo detinjasto. Ali svako od nas je malo dete u srcu, pa zašto mu ne bismo dozvolili da pokaže našu maštu?
Nežnost u nama može izazvati mnogo toga. Na primer, saosećajne oči mačeta koje želi da se pomazi ili nahrani. Šarena duga, koja viri nakon prolećne kiše i svetluca svim bojama na suncu. Dete kojem je data čokolada, i ono je odlučilo da je podeli sa svojom devojkom ili dečkom. Postoji dosta razloga za dirljivost, a mi smo odlučili da ih iskoristimo kao kursore.
Umorni ste od dosadne bele strelice u vašem pretraživaču? Zamenite je nečim slatkim iz naše kolekcije! Na primer, roze i belim jednorogom, tužnim paradajzom, namrgođenim oblakom, bodljikavim kaktusom u obliku mačke ili čime god želite. Sve što treba da uradite je da instalirate ekstenziju Cursor Style i dodate joj kolekciju slatkih kursora. I živela spasilac sveta - lepota!',
    'cute_cursors_short_descr' => 'Svet će biti ljubazniji sa kolekcijom slatkih pokazivača.',
    'cute_cursors' => 'Slatki pokazivači',
    'web_media_descr' => 'U modernim realnostima, skoro svi koriste internet. Počevši od dece pa do penzionera. Neko surfuje koristeći pretraživač, drugi gledaju video snimke na YouTube-u, a neko koristi mrežu da bi komunicirao sa voljenima. Bilo koji od ovih korisnika ne može da zamisli dan bez Svetske mreže.
Stariji ljudi često sede na društvenim mrežama kao što su Facebook ili VK. Oni takođe često komuniciraju sa svojom decom i unucima preko Skajpa. Ovo je posebno zgodno ako deca i roditelji žive u različitim gradovima ili čak državama.
Mladi ljudi više vole da komuniciraju preko Vajbera ili Telegrama, postavljaju fotografije na Instagram, smeju se FB mimovima. YouTube video snimci ljudskih reakcija dobijaju milione pregleda, kao i razne podvale ili socijalni eksperimenti. Na Tik-Toku stotine hiljada ljudi plešu, pokazuju magične trikove i izražavaju sebe.
Da li ste zainteresovani ili često koristite neku vrstu resursa iz oblasti veb medija? Želite da se otarasite dosadne strelice miša u vašem pretraživaču? Onda instalirajte ekstenziju i promenite podrazumevani kursor u naš kreativni! To može biti YouTube kursor, Vajber kursor, Google Chrome kursor ili drugi resursi.',
    'web_media_short_descr' => 'Živite u modernom ritmu sa kolekcijom kursora web medija',
    'web_media' => 'Web Mediji',
    'bobs_burgers_descr' => 'Animirana serija Bob\'s Burgers je zaplet animacije i harizma likova. I, sudeći po nominaciji za nagradu Emi i priznanju rada kao jednog od najboljih crtaća na svetu, Bob\'s Snack je zaista napravio bum.
Radnja animirane serije vrti se oko porodice Bob Belcher. Ova osoba je vlasnik restorana u prizemlju, a na spratu živi sa svojim najmilijima. Bob ima veselu ženu Lindu i 3 dece: Gene, Louise i Tina. Dečak sanja o muzičkoj karijeri, najstarija ćerka Tina je veoma ljubazna, ali nespretna, a najmlađa - Louise je još uvek nestaško i često svoju porodicu dovodi u neugodnu situaciju. Glavni konkurent Bob\'s Burgers je picerija Jimmy Pesto. Kao što možete pretpostaviti, vlasnik ove picerije se zove Jim i on i Bob se mrze. Sve ovo je urađeno tako da izgleda komično, ne ozbiljno. Stoga, mnoge njihove prepirke izazivaju samo osmeh.
Ako volite animiranu seriju „Bob\'s Burgers” i želite da vidite njegove likove ne samo na ekranu monitora ili TV-u, instalirajte ekstenziju, dodajte kolekciju i promenite kursor miša u pretraživaču u bilo koji od likova iz ovog crtanog filma!',
    'bobs_burgers_short_descr' => 'Bob kuva burgere, a mi pravimo kursore Bob\'s Burgers',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'Istorija video igre "Kirby" započela je još 90-ih godina prošlog veka. Sastoji se od mnogih serijala koje su razvili Nintendo i HAL Laboratory. Igra je namenjena deci od godinu i po do 8 godina. Njena popularnost može se oceniti brojem prodatih primeraka. Preko 34 miliona širom sveta.
Glavni lik Kirby je istoimeno roze stvorenje. Živi na planeti zvanoj Pop Zvezda, i periodično je štiti od raznih opasnosti. Kirby može da udahne neke objekte i svoje neprijatelje kako bi zatim naučio njihove sposobnosti: borbu prsa u prsa, posedovanje mača, disanje vatre, itd. Međutim, roze napuhač ne samo da se bori sa neprijateljima, već i rešava razne zagonetke, putuje u druge zemlje i čak može da leti u nivou.
Ovu video igru možete igrati na Nintendo ili Game Boy konzolama. U svim serijalima postoje slatki heroji, dobra grafika i smešni zvučni zapisi. Usput, za skoro 30 godina od izlaska prve verzije, svet je uspeo da vidi 20 Kirby serijala. Ovaj pokazatelj, zajedno sa višemilionskim obimom prodatih primeraka, pomogao je da igra bude u TOP 50 najuspešnijih i traženih video igara u industriji igara.
Volite Kirby toliko da biste želeli da vidite ovog lika gde god je to moguće? Onda koristite Kirby kolekciju i pretvorite uobičajeni pokazivač miša u glavnog lika vaše omiljene video igre! Sigurni smo da će vam se svideti novi izgled kursora.',
    'kirby_short_descr' => 'Pokušajte da udišete čitavu Kirby kolekciju kursora',
    'kirby' => 'Kirby',
    'undertale_descr' => 'U davna vremena, Zemlju nisu naseljavali samo ljudi, već i čudovišta. Zbog nesuglasica među njima, izbio je rat, koji se završio u korist ljudske rase. Sedam čarobnjaka je oteralo čudovišta pod zemlju i zauvek ih zatvorilo tamo čarolijom barijere. Međutim, postojao je samo jedan ulaz u planinu Ebott, koji je dete iskoristilo. Upravo za njega ćete igrati pokretanjem kompjuterske igre Undertale.
Ovu igru je razvio Toby Fox - poznati programer iz Sjedinjenih Američkih Država. U početku su vlasnici ličnih računara koji rade na operativnim sistemima Microsoft Windows i Linux mogli da uživaju u njoj, a zatim je došao red na korisnike gejming konzola.
Koja je poenta ove igre? Dečak putuje kroz podzemni svet naseljen čudovištima. Neka od njih su odmah neprijateljski raspoložena, dok druga vole da razgovaraju. Igrač može da izabere jedno od 2 ponašanja: izbegavanje nasilja ili borbu. U prvom slučaju, prelaženje igre će biti lakše, u drugom - naprotiv, teže je. Radnja i kraj, koji mogu da se granaju i menjaju, takođe zavise od ovog izbora.
Ako volite Underground Tale i želite da vidite njegove likove u svom pretraživaču, instalirajte ekstenziju i dodajte odgovarajuću kolekciju kursora! Pretvorite dosadni pokazivač miša u jedno od čudovišta ili glavnog lika Undertale!',
    'undertale_short_descr' => 'Vreme je da izađete iz rupe koristeći Undertale kursore',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune je igra igranja uloga objavljena za računare pre nekoliko godina. Kreirao ju je isti programer koji je razvio Undertale. Međutim, ove dve igre gotovo da nisu slične jedna drugoj, iako imaju nekoliko zajedničkih likova i lokacija.
U Delta Rune postoji nekoliko glavnih likova. Ovo je student Kris, koji se može kontrolisati, i šarmantno čudovište Sazi, nekontrolisano. Oba lika padaju u svet tame, gde sreću jednog od njegovih stanovnika - Ralsija. On im kaže da su oni zapravo stvorenja svetlosti koja imaju misiju - da zaustave protok tamne energije u mračnom svetu. Da bi to uradili, potrebno je da poštede lokalna čudovišta i da se trude da ne ulaze u bitku sa njima, iako je to ponekad prilično teško uraditi.
Igrač ima jednostavan izbor: ili poštedeti tamna stvorenja ili ih napasti. Pošto Sazi nije ljubitelj polovičnih mera, u mnogim slučajevima bira bitku. Stoga, Kris nema drugog izbora nego da podrži svoju devojku i da joj pomogne u bitkama.
Volite igru Deltarune? Onda stilizujte kursor miša u pretraživaču za jednog od njenih likova! To možete učiniti pomoću našeg ekstenzije. Instalirajte je, dodajte kolekciju “Rune Delta” i aktivirajte! Sada vaša strelica više nije ista kao svi ostali, već je postala Kris, Sazi ili jedno od stvorenja mračnog sveta.',
    'deltarune_short_descr' => 'Zaronite u mračni svet sa ovom kolekcijom kursora',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario je serija kompjuterskih igara koje je izdao Nintendo. Prva i najpopularnija igra zvala se Super Mario Bros. Ugledala je svetlost dana 1985. godine. Kasnije je upisana u Ginisovu knjigu rekorda. Od tada je objavljeno više od 20 igara, od kojih svaka ima svoju radnju. U 2019. godini pojavila se nova verzija pod nazivom Super Mario Maker 2. Uprkos poboljšanju grafike, stil i likovi su ostali isti, što izaziva nostalgiju za Super Mariom iz 80-ih.
Glavni junak je i dalje vodoinstalater Mario. U zapletu poslednje varijacije igre, princezin dvorac nije imao kamen na kamenu. Mario mora da ga obnovi, zaradivši pre toga novčiće koji mu se plaćaju za zadatke. Ukupno, ova igra ima više od 100 nivoa različite složenosti sa mogućnošću modifikacije. Takođe u Super Mario Maker 2 postoje novi režimi igre. Možete igrati četiri od njih odjednom i čim jedan završi, nivo se smatra završenim. Postoje i režimi kao što su: Mario Maraton, Duel i Ninjik trke.
Obožavate Super Mario i sve što je vezano za ovu divnu igru? Zatim podesite kursore napravljene u stilu ovog platformera! Sigurni smo da će vam se dopasti Mario kursor, Luigi kursor, Princess Peach kursor i drugi kursori koji su predstavljeni u našoj kolekciji!',
    'super_mario_short_descr' => 'Prođite kroz kraljevstvo pečuraka sa kolekcijom kursora Super Mario',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls su zajednički kreirali Disney Television Animation Corporation i Alex Hirsch. Premijera je objavljena 2012. godine i prikazana je na Disney Channel-u. Cela prva sezona animirane serije se tamo emitovala. Dve godine kasnije, objavljena je druga sezona, koju su gledaoci mogli da gledaju na prethodnom kanalu i na Disney XD. Nažalost, obožavaoci Gravity Falls-a nisu dočekali treću i naredne sezone. Kreatori su odlučili da se ograniče na dve sezone bez ikakvih nastavaka.
Što se tiče radnje ove animirane slike, sva akcija se odvija u izmišljenom gradu zvanom Gravity Falls. Dva blizanca dolaze tamo, čija su imena Mabel i Dipper. Oni borave kod svog rođaka Stana. On ima sopstvenu turističku suvenirnicu. Kada braća budu umorna od "nerada", oni kreću u potragu za avanturom. Jedan od njih pronalazi čudan dnevnik u šumi, koji govori o anomalijama ovog grada. Blizanci kreću u potragu za njegovim autorom i susreću se sa neobičnim stvorenjima i mestima. Ako ste zainteresovani za ovu animiranu seriju, i jednom ste bili obožavaoci njenih likova, preporučujemo vam našu kolekciju pokazivača miša u stilu Gravity Falls!',
    'gravity_falls_short_descr' => 'Krenite u avanturu sa kursorima iz serije Gravity Falls',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Apsolutno svi su čuli za tako čuvenu animiranu seriju kao što su Simpsonovi. Čak i oni ljudi koji nikada nisu gledali ovu seriju su svesni postojanja žutih likova. A obožavatelji su oduševljeni kada izađe sledeća sezona njihovog omiljenog crtaća. Usput, u jesen 2019. godine izašlo je 31 sezona. A prva se pojavila na televizijskim ekranima još 1989. godine. Fox je počeo da je prikazuje i još uvek to radi zbog visokih rejtinga i simpatija publike.
Simpsonovi su satirični žanr koji se dotiče relevantnih tema. To može biti način života prosečnog Amerikanca, politička i verska pitanja, "zvezdane" trikove poznatih ličnosti, feminizam, istopolne brakove. Generalno, sve što je povezano sa lokalnim i globalnim događajima u kojima učestvuju Sjedinjene Američke Države.
Radnja animirane serije se odvija u nepostojećem gradu Springfieldu. U stvari, postoji mnogo gradova sa tim imenom u Americi. Možda je zato izabran kako publika ne bi povezivala ono što se dešava na ekranima sa određenom lokacijom, već samo pogađala gde bi to moglo biti.
Vi ste najverovatnije obožavatelj Simpsonovih. U suprotnom, zašto biste čitali ovaj tekst do kraja? A ako jeste, onda imate priliku da promenite dosadni pokazivač miša u pokazivač koji je napravljen u stilu ove animirane serije.',
    'simpsons_short_descr' => 'Zabavna mala porodica u kojoj glume kursorima Simpsonovi',
    'simpsons' => 'Simpsonovi',
    'youtubers_descr' => 'YouTube platforma za video zapise pojavila se 2005. godine. U početku su se video zapisi objavljivali samo radi samoizražavanja ili informisanja o nečemu. Međutim, vremenom je sve to preraslo u profitabilan posao, koji uspešnim YouTube korisnicima donosi na hiljade, a ponekad i milione dolara mesečno. Što je popularniji vloger (osoba koja vodi video blog), to više može zaraditi preko svog kanala.
Koliko zarađuje petogodišnja devojčica vloger, čiji je zadatak da je roditelji vode u najzanimljivije atrakcije i snimaju šta se dešava na kameri? To je jednostavno način na koji se dete zabavlja u dečijim parkovima, koji izražava emocije, kako se glupira i sve te stvari. Iznos je zaista neverovatan - danas je dečiji kanal stekao skoro 47 miliona pretplatnika i počeo da generiše prihod u iznosu od 5 miliona rubalja mesečno.
Neko postavlja video zapise u kojima razgovara o kompjuterskim igrama, neko radi bitboks ili organizuje šale za prolaznike na ulici. Neki posvećuju svoje video zapise osetljivim temama, kao što su odnosi između muškaraca i žena. Što se više korisnika YouTube-a sviđaju ovi snimci, veća je popularnost vlogera.
Kolekcija je već dodala PewDiePie kursor, Shane Dawson kursor, Ray William Johnson kursor, Zoella kursor, MyLifeAsEva kursor i druge.',
    'youtubers_short_descr' => 'Nova generacija zvezda je uvek onlajn u našoj kolekciji Jutjubera.',
    'youtubers' => 'Jutjuberi',
    'pusheen_descr' => 'Skoro svi znaju Pušin mačku. Iako je samo lik iz dečijeg stripa izmišljenog pre 10 godina, ima milione obožavatelja danas. Pušin mačka se pojavila kao ilustracija koju je kreirala umetnica Klara Belton.
Godinu dana kasnije, mačka je dobila svoju stranicu na Tumblr.com i za par nedelja stekla čitavu armiju obožavatelja - oko 10.000 ljudi. U 2013. godini, Fejsbuk je bio željan da uključi slike iz Pušin-a u kolekcije sa drugim emotikonima. Nakon pregovora sa kreatorom, ova ideja je primenjena u praksi i „digla u vazduh“ Internet! Slike iz Pušin mačke se koriste u prepisci više od 10 miliona puta dnevno!
U 2014. godini, jedan od najvećih proizvođača igračaka u Sjedinjenim Američkim Državama obratio je pažnju na ovaj lik. GUND (ona je izmislila medvediće) lansirao je par Pušin modela. Pošto je uspeh bio ogroman, nakon nekoliko meseci, stvorena je kompletna kolekcija igračaka u obliku ove mačke.
Gde još možete sresti Pušin mačku? U poklon setovima od Isaac Morris Ltd, u slezu iz Boomf i, naravno, u našoj kolekciji Pušin kursora!',
    'pusheen_short_descr' => 'Dodajte malo udobnosti u svoj pregledač uz Pusheen kolekciju kursora',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'Prva serija animiranog dela „Rik i Morti” objavljena je 2013. Ovaj crtani se može direktno pripisati 2 žanra: naučnoj fantastici i komediji. Njegovi tvorci bili su Den Harmon i Džastin Rojland. U početku su sve serije prikazivane na kanalu Cartoon Network, a tek onda su duplirane u onlajn bioskopima i video hosting servisima. Na svakih nekoliko godina izlaze nove sezone Rika i Mortija, a u novembru 2019. izašla je četvrta sezona, koja se pokazala ništa manje zanimljivom od prethodnih. Radnja animirane serije vrti se oko genijalnog, a u isto vreme i ludog naučnika po imenu Rik, kao i njegovog neupadljivog unuka - Mortija. Ova dva lika povezuju zajedničke avanture na najneobičnijim mestima. I stižu tamo na letećem tanjiru, sposobnom da se kreće kroz među-prostorni tunel. Kao što ste možda pretpostavili, ova animirana serija pomalo liči na film Povratak u budućnost, ali ipak nije njena animirana verzija. Međutim, mnogi kritičari su ga pohvalili zbog duhovitih epizoda, kreativnosti i originalnosti. Želite da vidite Rika ili Mortija ne samo u serijama ovog dela, već i u pretraživaču? Ako je tako, instalirajte ekstenziju i dodajte našu kolekciju posvećenu vašem omiljenom crtanom filmu! Ovde je kursor Rika Sančeza, kursor Mortija Smita, kursor Portalskog pištolja i naravno kursor gospodina Misekasa.',
    'rick_and_morty_short_descr' => 'Prestani da gunđaš, samo koristi kursore iz Rick and Morty kolekcije',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Ljubitelji bejzbola se mogu naći bilo gde u svetu. Ovo posebno važi za stanovnike zemalja kao što su: SAD, Kina, Kuba, Južna Koreja, Japan i Venecuela. Suprotno popularnom verovanju, bejzbol nije nastao u Americi, već u Engleskoj. Prvo pominjanje i opis bejzbola pojavilo se daleke 1744. godine, u engleskom izdanju. Posle 145 godina, Amerikanci su prisvojili ovaj izum za sebe, uprkos činjenicama.
National League je formirana 1876. godine. Ona je deo Major League u Kanadi i Sjedinjenim Državama. Danas, postoji 15 timova u National Baseball League. U finalnom delu svake sezone dolazi vreme plej-ofa, u kojem učestvuju 4 najbolja tima. Tako se otkriva pobednik cele National League. Zatim pobednički tim dobija priliku da igra protiv pobednika iz American League u World Series.
Da li ste zainteresovani za bejzbol ili čak navijate za neki od timova? U tom slučaju, odajte počast svom omiljenom timu postavljanjem markera miša u obliku njegovih atributa! Promenite dosadan izgled pokazivača u pretraživaču u poznati korporativni identitet bejzbola! Pretvorite strelicu u palicu ili kacigu igrača u bilo kom od timova National League, koji već uključuju kursor New York Yankees, kursor Great Falls Dodgers, kursor Boston Red Sox, kursor Baltimore Orioles, kursor Oakland Athletics.',
    'mlb_teams_short_descr' => 'Kolekcija kursorâ bejzbol timova za sve naše fanove.',
    'mlb_teams' => 'MLB Timovi',
    'brawl_stars_descr' => 'Brawl Stars je mobilna igra u MOBA žanru od Supercell-a. Uprkos izlasku krajem 2018. godine, igra je stekla veliku popularnost, uglavnom zbog obilja borbenih modova i šarenih, fantastičnih heroja - svađača. Igrač ima mnogo izbora - 32 jedinstvena lika i svaki od njih ima svoj set sposobnosti i veština. Svaki heroj takođe ima svoju pasivnu veštinu, koja je dostupna kroz loot škrinje. Igrači se mogu boriti u nekoliko modova, na primer, "Nagrada za osvajanje" - jedna od dve ekipe pobeđuje, koja je prikupila više zvezda, ubijajući protivnike. U modu "pljačka", neophodno je razbiti sefove protivnika, dok se čuvaju sopstveni. Zanimljiv "Gem Grab" režim - tim postaje pobednik, tim koji sakupi najviše dragulja pobeđuje. Pa, u modu "Sudara", 10 igrača se međusobno bori na mapi, gde su granice smanjene usled toksičnog oblaka. Igra je prepuna šarenog dizajna koji se mnogima sviđa, uključujući i nas, što nas je inspirisalo da kreiramo zasebnu kolekciju Brawl Stars kursora. Postoje Brawl Stars Šeli kursor, Barlijev kursor, Peni kursor, Frenk kursor, Mortis kursor i drugi.',
    'brawl_stars_short_descr' => 'Izaberite pokazivače iz igre Brawl Stars i neka bitka počne',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Promenite pokazivač miša u dva klika! Besplatne kolekcije za svačiji ukus.',
    'all_descr' => 'Ako ste ikada razmišljali o tome kako da promenite dosadan kursor miša, onda su naše kolekcije kursora za vas! Ovde ćete pronaći sjajne heroje iz stripova, prelepe kursore za gejmere sa likovima iz popularnih igara, zabavne setove kursora za praktične šale, kursore u boji i mnoge druge zanimljive opcije.',
    'text_title' => 'Kul i najsmešniji zbirke kursora za svaki dan',
    'text_allcat_title' => 'Jedinstveni i kreativni pokazivači miša koji odgovaraju svakom vašem raspoloženju',
    'text_1' => 'Ne želite da budete kao svi ostali? Ili samo volite sve neobično? Želite da budete deo svog omiljenog heroja iz igre ili crtanog filma? Onda ste došli na pravo mesto. Ovde ćete pronaći svetle, neobične setove kursora koji mogu zameniti poznatu i već pomalo dosadnu belu strelicu. Kursor miša nas prati ceo dan na poslu i u učenju, pa bi trebalo da pruža sjajno raspoloženje i da nas pripremi za pozitivno.',
    'text_2' => 'Ovde ćete pronaći kursore za gejmere i ljubitelje filmova, prelepe kursore zasnovane na vašim omiljenim crtanim filmovima i sportskim motivima za najaktivnije ljude. Da li volite stripove ili ne možete da zamislite ni jedan dan bez smešnih mimova? Obožavate životinje ili sanjate da posetite sve zemlje sveta? Sve je jednostavno - imamo odgovarajuću sliku kursora i za vas. Takođe možete odabrati slike u zavisnosti od toga sa čime radite. Na primer, crni kursor će biti mnogo praktičniji od belog prilikom rada sa dokumentima ili crtežima, a kursor u obliku ruke će biti praktičniji ako morate da radite sa malim grafičkim elementima. Izaberite svoju omiljenu sliku, podesite njenu veličinu direktno u ekstenziji - i koristite je sa zadovoljstvom, svakog dana počevši sa pozitivnom notom!',
    'install_to_preview' => 'Instalirajte ekstenziju da biste videli pregled',
    'install' => 'Instaliraj',
    'add_button' => 'Dodaj',
    'preview_button' => 'Pregled',
    'added_button' => 'Dodato',
    'add_cursor' => 'Dodaj kursor',
    'to_your_collection' => 'u vašu kolekciju',
    'prev_text_1' => 'Pregled preko celog ekrana',
    'prev_text_2' => 'kursor',
    'cursor' => 'kursor',
    'pointer' => 'pokazivač',
    'a_title_1' => 'Cursor Style - Kul kursor za vaš pretraživač',
    'a_title_2' => 'Kul kolekcije tematskih kursora',
    'mouse_cursors' => 'kursori miša',
    'cursor_collection' => 'Kolekcija kursora',
    'sborka_cursorov' => 'kolekcija kursora',
    'collection_list_from_colllection' => 'Lista kursora - ',
    'christmas' => 'Božić',
    'nhl_teams' => 'Timovi Nacionalne Hokejaške Lige',
    'neon' => 'Neon',
    'adventure_time' => 'Vreme avanture',
    'nba_teams' => 'Timovi Nacionalne Košarkaške Asocijacije',
    'spongebob' => 'Sunđer Bob',
    'phineas_and_ferb' => 'Fineas i Ferb',
    'fortnite_chapter_2' => 'Fortnite Poglavlje 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Poznate ličnosti',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Stripovi',
    'igry' => 'Igre',
    'multfilmy' => 'Crtani filmovi',
    'kino_i_serialy' => 'Filmovi',
    'anime' => 'Anime',
    'futbol' => 'Fudbal',
    'avtomobili' => 'Automobili',
    'memy' => 'Meme',
    'emodji' => 'Emotikoni',
    'pitomcy' => 'Ljubimci',
    'stil_i_krasota' => 'Moda i stil',
    'prazdniki' => 'Praznici',
    'flagi' => 'Zastave',
    'vokrug_sveta' => 'Oko sveta',
    'eda_i_napitki' => 'Hrana i pića',
    'cvetnye' => 'U boji',
    'prank' => 'Šale',
    'startovyj_nabor' => 'Početni komplet',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Deda Mraz će voleti vaše božićne kursore',
    'nhl_teams_short_descr' => 'Kolekcija NHL kursora za prave obožavaoce',
    'neon_short_descr' => 'Dodajte svetlost sa neon kolekcijom',
    'adventure_time_short_descr' => 'Učenje matematike sa kolekcijom Adventure Time kursora',
    'nba_teams_short_descr' => 'NBA kursori kao simbol velikih košarkaških pobeda',
    'spongebob_short_descr' => 'Otkrijte ko živi na dnu okeana uz kolekciju Spongebob kursora',
    'phineas_and_ferb_short_descr' => 'Definitivno vam neće biti dosadno sa kolekcijom kursora Phineas and Ferb',
    'fortnite_chapter_2_short_descr' => 'Novo poglavlje kultne igre Fortnite',
    'pokemon_short_descr' => 'Uhvatite ih sve ako možete',
    'famous_people_short_descr' => 'Inspirisite se kursorom svog idola',
    'the_elder_scrools_short_descr' => 'Uronite u svet vitezova i zmajeva',
    'halloween_short_descr' => 'Bojte se da ne propustite novu Halloween kolekciju',
    'nfl_teams_short_descr' => 'Za prave ljubitelje fudbala',
    'five_nights_at_freddy_short_descr' => 'Pokušajte da se ne uplašite ovih animatronika',
    'komiksy_short_descr' => 'Kursori iz stripova: izaberite svoje raspoloženje danas.',
    'igry_short_descr' => 'Virtuelna realnost: koga igrate danas?',
    'multfilmy_short_descr' => 'Omiljeni crtani likovi u novom dizajnu',
    'kino_i_serialy_short_descr' => 'Gospodar kursora: Bratstvo desktopa',
    'anime_short_descr' => 'Svi vole anime: ko je tvoj omiljeni lik?',
    'futbol_short_descr' => 'Да ли сте прави љубитељ спорта? Онда треба да будете овде',
    'avtomobili_short_descr' => 'Ауто ваших снова: велика флота за професионалце',
    'memy_short_descr' => 'Омиљени мотиви: колекција курсора са мемовима',
    'emodji_short_descr' => 'Pokažite svoje pravo raspoloženje drugima - postavite Cursoji!',
    'pitomcy_short_descr' => 'Svetli kursor za sve ljubitelje naše manje braće',
    'stil_i_krasota_short_descr' => 'Originalni kursor za sve prilike',
    'prazdniki_short_descr' => 'Šta se nalazi u kalendaru? Nova kolekcija prazničnih kursora!',
    'flagi_short_descr' => 'U potrazi za avanturom: gde idemo danas?',
    'vokrug_sveta_short_descr' => 'Око света у трену: где идемо данас?',
    'eda_i_napitki_short_descr' => 'Укусни курсори за креативност',
    'cvetnye_short_descr' => 'Осликајте свој живот светлим бојама и смелим потезима',
    'prank_short_descr' => 'Set kursora za najsmešnije šale',
    'startovyj_nabor_short_descr' => 'Novi pogled na poznate stvari: ažurirana serija kursora',
    'fortnite_short_descr' => 'Pratite strimere!',
    'dota_2_short_descr' => 'Učinite vaš virtuelni svet stvarnim!',
    'minecraft_short_descr' => 'Likovi vaše omiljene igre uvek su u blizini',
    'christmas_descr' => 'Svako od nas nesumnjivo čeka na najpopularniji praznik - Božić. Svi hrišćani sveta tradicionalno ga slave svake godine, 25. decembra. Vreme kada se porodice okupljaju za jednim stolom, dele radost i ljubav i razmenjuju poklone. Dugo pre Božića ljudi ukrašavaju ulice svetlim girlandama, a svoje domove tradicionalnim atributima. Teško je naći osobu koja ne voli Božić - zabavan i tajanstven praznik, jer ga prate mnoge tradicije i rituali, oni nas vraćaju korenima cele naše porodice. Uoči Božića, bukvalno sve je zasićeno njegovim duhom, od obojenih medenjaka do dirljivih pesama. Elegantna božićna jelka i pokloni ispod nje, radost poznata svakom od nas iz detinjstva. Želimo da se pridružimo ovom čarobnom prazniku i, ko zna, možda će Deda Mraz pripremiti poseban poklon za vas ako ukrasite kursor našom božićnom kolekcijom. Ima svega što vam je potrebno za to, kursor Deda Mraza, kursor božićne jelke, kursor medenjaka, kursor Sneška Belića, pa čak i kursor torbe sa poklonima. Srećan Božić!',
    'nhl_teams_descr' => 'Nacionalna Hokejaška Liga je formirana 1917. godine - to je profesionalna sportska organizacija koja okuplja hokejaške klubove iz SAD-a i Kanade. I ovo je jedna od prvih profesionalnih hokejaških liga na svetu. NHL je jedna od vodećih sportskih liga Severne Amerike, zajedno sa NFL, NBA, Major League Baseball i MLS. Svake godine, 31 tim iz 30 gradova u SAD-u i Kanadi se bori za glavni trofej - Stenli kup, a tim koji je osvojio najviše poena u regularnoj sezoni dobija Predsednički kup. Vreme je da odamo počast ovoj sjajnoj igri stvaranjem kolekcije NHL kursora. Ako i vi volite hokej, navijajte za svoj omiljeni klub ili sami učestvujte u ovom sportu, samo promenite kursor i ne odvajajte se od svog omiljenog tima, uključujući kursor Boston Bruins, kursor St. Louis Blues, kursor Columbus Blue Jackets, kursor Tampa Bay Lightning, kursor Dallas Stars i druge klubove vredne iskrenog poštovanja.',
    'neon_descr' => 'Kreirali smo jedinstvenu kolekciju neonskih kursora kako bismo dodali raznolikost svakodnevnom surfovanju internetom i uneli malo svetlosti u očaravajuća neonska svetla. Neka njihove bogate boje stvore obuhvatajuću atmosferu grada noću, daju inspiraciju za stvaranje nečeg novog. U modernom svetu, svetla metropole uvek najavljuju početak noći, prate nas na svakoj ulici i ovaj sjaj je ispunjen energijom. Neka ga prate i svetleći kursor sladoleda, ukusan kursor hot doga, kursor sočnog burgera, kursor blistavog dijamanta i drugi kursori iz nove neonske kolekcije.',
    'adventure_time_descr' => '"Adventure Time" je crtani film fantastičnog žanra u kojem se radnja odvija u svetu koji je preživeo apokalipsu. Ova teritorija se zove Zemlja Ooo, koja je do nedavno bila nuklearni rat. Ali sve je to već prošlost, međutim, svi preživeli ljudi su bili predmet mutacija, a svet je bio ispunjen magijom. Glavni junaci animirane serije su Fin, dečak od 14 godina i njegov prijatelj pas po imenu Džejk. Dečak i pas jako vole avanture, stalno pomažu svima koji su u nevolji. Prijatelji žive na drvetu i provode svo vreme zajedno. Ako želite da se uronite u avanturistički svet sa drugim obožavaocima, onda uzviknite "Matematika". Ovde su i kursor dečaka Fina i kursor Džejka, kao i kursor Princeze Žvaka. Naravno, nismo zaboravili na Bimo kursor, kursor Kralja Leda i ostale.',
    'nba_teams_descr' => 'Ako je košarka vaša omiljena igra kao što je i naša, onda je kolekcija kursora posvećenih NBA timovima ono što vam treba. NBA je jedna od najboljih sportskih asocijacija na severnoameričkom kontinentu. Kada smo kreirali ovu kolekciju, mučila nas je dilema - koji tim izabrati, jer ih u NBA ima trideset. Ali postoje timovi koji su legende. To su Čikago Bulsi, koji su postavili rekord po broju pobeda sredinom 90-ih. Tu su i Golden Stejt Voriorsi, koji su pre nekoliko godina okupili najbolje igrače lige. Ili, na primer, Lejkersi, Seltiksi su takođe neverovatno sjajni timovi. Ako, kao i mi, jedva čekate utakmice svojih omiljenih košarkaških timova i želite da pokažete svoju podršku timu ili igračima, preuzmite našu kolekciju NBA kursora.',
    'spongebob_descr' => 'Animirana serija "Sunđer Bob Kockalone" je poznata tolikom broju ljudi. Bio je to ogroman uspeh nakon što je Nikelodeon 1999. godine odlučio da kreira animiranu seriju zasnovanu na edukativnom stripu Tide Zone, i pretvorio se u veoma unosnu franšizu. Tvorac serije je bivši zaposleni okeanološke laboratorije, zbog čega su gotovo svi likovi animirane serije smešni stanovnici morskog dna, sa svojim karakterističnim osobinama i harizmom. Radnja se vrti oko tajnog recepta za Krabsburger koji samo glavni lik može da kuva - Sunđer Bob. A ostali stanovnici mora danonoćno pokušavaju da ga dobiju, uključujući glavnog antijunaka Šeldona Planktona, koji to ne uspeva svaki put. U kolekciji kursora Sunđer Bob, sakupili smo kursore svih značajnih likova i događaja iz serije. Na primer, kursor gospodina Krabe sa dolarom, kursor Patrika Zvezde, Lignjoslava sa njegovim klarinetom, kursor meduze, kursor Sunđer Boba i mnogih drugih likova.',
    'phineas_and_ferb_descr' => 'У измишљеном америчком граду Денвилу из непостојеће Триштатје, живе два занимљива дечака. Сваки дан њиховог одмора претвара се у невероватне авантуре, јер могу да направе ролеркостер величине читавог града или прави портал на другу планету. Своју невероватну забаву деле са пријатељима. Истовремено, док се дечаци забављају, зли научник Хајнц Фуфелшмерц гради још једну злу машину која ствара хаос, са називом који се завршава на "-inator", уз помоћ које жели да освети своје детињске неправде или да преузме власт у Триштату, али га омета Пери - Утконос, тајни "Агент Пи", који ради под маском кућног љубимца дечака. Популарност ове анимиране серије, како међу децом тако и међу одраслима, инспирисала нас је да креирамо колекцију курсора из Финеаса и Ферба како бисте могли да промените свој курсор миша на ликове из серије. Међу њима су курсор Финеаса Флина, курсор др Хајнца Фуфелшмерца, курсор Ферба Флечера, курсор Кендис Гертруде Флин и курсор Перија кљунара.',
    'fortnite_chapter_2_descr' => 'Drugo poglavlje Fortnite-a došlo je nakon velikog događaja - The End, koji je sve što su igrači u igri voleli uvukao u crnu rupu. Fortnite Poglavlje 2 sada ima novu mapu, koja je na prvi pogled još divljija od originalne mape, kao i mnoge promene u mehanici igre i naravno puno novog sadržaja igre! Vozila, emocije, mehanika plivanja i mnogo više - sve ovo u svežim, zanimljivim slikama, sve onako kako volite i cenite u ovoj kultnoj igri. Uronite u novi svet - izaberite mesto sletanja i istražite potpuno novo ostrvo sa 13 lokacija. Plivanje, pecanje, motorne čamce - ovo je nova igra na vodi. Više zabave i manje napora - nadogradite potpuno novo poglavlje 2 i ne zaboravite da promenite kursor na nove skinove i oružje. Već vas čekaju ažurirani skinovi Turk kursor, Riptide kursor, Rippley kursor, Remedy kursor, Toxin kursor, 8-Ball kursor, Fusion kursor i drugi!',
    'pokemon_descr' => 'Reč "pokemon" znači stvorenje sa natprirodnim moćima. Oni imaju inteligenciju, a neki od njih su čak i sposobni da govore. Trenutno, već postoji 802 različite vrste Pokemona. U izmišljenom Pokémon univerzumu, ljudi se zovu Pokémon treneri, koje obučavaju za borbe sa Pokémonima drugih trenera. I što je trener iskusniji i jači, to više poštovanja uživa. Srećom, treba napomenuti da se Pokémon borbe nikada ne završavaju smrću ovih jedinstvenih stvorenja. Svi Pokémoni imaju različite sposobnosti i razlikuju se po vrsti elementa, a njegova otpornost na različite napade snažno zavisi od toga, a neka stvorenja imaju sposobnost dva elementa odjednom. Nakon pobede u borbi, Pokémon dobija dragoceno iskustvo koje je neophodno za povećanje nivoa i, shodno tome, njegovih karakteristika. Danas, Pokémon univerzum je ogromna medijska franšiza i odlučili smo da pripremimo za vas kolekciju kursora sa nekim popularnim Pokémonima. Među njima, najpoznatiji je Pikachu kursor, kao i Rattata kursor, Squirt kursor, Bulbasaur kursor i Charmander kursor. Ova lista će biti ažurirana, jer ih ima toliko mnogo i svaki od njih je jedinstven na svoj način.',
    'famous_people_descr' => 'Među mnogim poznatim ljudima, svako od nas pronađe uzor ili se jednostavno divi genijalnosti, talentu i upornosti ovih slavnih ličnosti. Pripremili smo kolekciju kursora slavnih ličnosti kako bismo vas inspirisali i podsetili na velika dostignuća koja svako od vas može da uveća. Ne, sve poznate ličnosti nisu imale srećnu sudbinu, ali nas uče glavnoj stvari da nikada ne treba odustati od svog dragog cilja, uprkos poteškoćama i problemima. Na kraju krajeva, ovo je glavni princip postizanja uspeha - ići ka svom snu svakog dana i, konačno, postati najbolji u svojoj oblasti. Možda danas samo želite da promenite kursor miša, a sutra će vam se ceo život promeniti na bolje! Kolekcija će se stalno obnavljati novim, vrednim predstavnicima čovečanstva. Među njima, naravno, naučnici, političari, sportisti, predstavnici umetnosti i mnogi drugi. Kursor Džordža Vašingtona, kursor Majkla Džordana, kursor Stivena Kinga, kursor Elvisa Prislija i kursor Merilin Monro su samo početak.',
    'the_elder_scrools_descr' => 'The Elder Scrolls je serija kompjuterskih igara uloga, ujedinjenih zajedničkim, pedantno dizajniranim univerzumom, koji igraču pružaju ogromnu slobodu izbora, omogućavajući im da posete različite oblasti i gradove fantastičnog sveta i sami istraže nova mesta i misije. Rad na serijalu je započeo davne 1992. godine i tokom godina je igra ujedinila ogromnu zajednicu igrača oko sebe. Stoga smo, na zahtev javnosti, objavili kolekciju kursora The Elder Scrolls, tako da možete da se uronite u jedinstvenu atmosferu igre. Večna bitka vitezova i zmajeva, na čijoj ste strani? Promenite kursor u zmaja i pridružite se vojsci vatrogasnih čudovišta ili se plemenito borite na strani ljudi birajući kursor mača i sliku svog omiljenog lika - odluka je vaša! Glavna stvar je da ste sa našom novom kolekcijom spremni za svaku bitku.',
    'halloween_descr' => 'Čekajući mističnu noć uoči Dana Svih Svetih. Istorija Noći veštica proteže se preko dve hiljade godina. Možda je ovo najčudniji praznik koji kombinuje zabavu i strah, domorodac keltske kulture. Tada su ljudi spaljivali vatre i oblačili strašne kostime kako bi otjerali duhove. Reč "Noć veštica" prvi put je pomenuta u 16. veku kao škotska skraćenica engleske fraze All-Hallows-Even. Papa Grgur III proglasio je 1. novembar Danom Svih Svetih, a veče pre toga nazvano je Eve of All Saints, a kasnije Noć veštica. Na ovaj dan ljudi nose kostime vukodlaka, duhova i drugih čudovišta i odlaze u susedne kuće, nudeći da kupe slatkiše. Tematske zabave, vatrometi, prelepe lampe, bundeve i vratolomije stvaraju jedinstvenu atmosferu. Takođe želimo da proslavimo ovaj strašni praznik sa dodacima kursorima i likovima Noći veštica. U našoj kolekciji možete pronaći: kursor zombija, kursor duha, kursor crne mačke, kursor bundeve i još mnogo toga. Promena raspoloženja je sada jednostavna kao i promena kursora sa našom novom kolekcijom za Noć veštica.',
    'nfl_teams_descr' => 'Šta bi moglo biti bolje za pravog obožavatelja američkog fudbala od kursora miša u vidu simbolike tima za koji navija? U modernoj Nacionalnoj fudbalskoj ligi (NFL), trideset i dva tima igraju, podeljena između Nacionalne i Američke fudbalske konferencije (Nacionalna fudbalska konferencija, NFC i Američka fudbalska konferencija, AFC). Zauzvrat, svaka od konferencija je podeljena na četiri divizije: Istok, Sever, Jug i Zapad. NFL sezona se sastoji od predsezonskih utakmica, regularne sezone i serije utakmica plej-ofa. Finalna utakmica NFL sezone se zove Super Bowl i u suštini je najpopularniji sportski događaj u Sjedinjenim Američkim Državama. Ovo je omiljena utakmica za milione navijača i zato smo kreirali kolekciju NFL kursora tako da se ne odvajate od simbola vašeg omiljenog tima. Bilo da su to Nju Ingland Patrioti, Njujork Džajantsi, Bafalo Bilsi ili neki drugi tim, uvek budite na istoj talasnoj dužini sa svojim idolima, koristeći naše kursore u vidu logotipa i kacige tima. Kolekcija će se stalno ažurirati kako bi svako mogao da promeni kursor u sliku svog omiljenog tima.',
    'five_nights_at_freddy_descr' => 'Zaista jedinstvena igra Five Nights at Freddy\'s brzo je stekla veliku popularnost i to ne iznenađuje, jer njena jednostavna, a istovremeno fascinantna radnja može držati igrače na ekranima satima. Dizajnirali smo kursorje Five Nights at Freddy\'s na zahtev obožavatelja igre i bili smo veoma zadovoljni što smo otelovili tako zanimljive i smešne likove. Ali za razliku od igre, ništa vam ne preti s našim kursorima, pa slobodno birajte svoje omiljene animatronike, bilo da je to Medved Freddy ili Zec Bonnie ili druge. Glavno je da sada igra oživljava u vašem pregledaču i daje sveže emocije. Garantujemo da u našim kursorima nema duhova, ali oni savršeno prenose duh igre koja izaziva strah zbog zamršenosti dizajna i elemenata radnje. Ali što ako napravite da je veličina kursora veoma velika? Možete li ostati mirni i ne uplašiti se?',
    'komiksy_descr' => 'Činilo bi se da je kursor miša sitnica, ali često su takvi detalji ti koji mogu poboljšati vaše raspoloženje, probuditi vas u sivo jutro ili jednostavno pružiti svetle emocije. Kolekcija kursora iz stripova dizajnirana je posebno za sve ljubitelje superheroja. Ovde možete pronaći apsolutno ceo Marvelov univerzum i DC Comics - od Ajronmena do Tanosa, Spajdermena i Halka. Stil kursora može biti u obliku superheroja ili u obliku njegovog karaktera. Kursor nije samo funkcionalni element; važan je u profesionalnom smislu. Na primer, ako snimate video sa ekrana, bolje će biti da vidite svetlu, originalnu sliku, i to izgleda mnogo zanimljivije. I naravno - ko ne bi želeo da koristi rukavicu besmrtnosti u stvarnom životu? Promena kursora miša je jednostavna - samo preuzmite ekstenziju na svoj pretraživač i dodajte kursor koji vam se sviđa u svoja podešavanja putem njega. Možete birati kursor prema svom raspoloženju barem svaki dan. Dosta sivih dana - postanite superheroj odmah!',
    'igry_descr' => 'Računarske igre su odavno postale sastavni dio naših života. Uz njihovu pomoć, možete se uroniti u novi svijet, učestvovati u avanturama i postati potpuno drugačija osoba. Svi imaju svoju omiljenu igračku, čiji su likovi već postali skoro porodica. Set kursora zasnovanih na dobro poznatim računarskim igrama je prilika da se razvodni dosadna svakodnevica i doda malo kreativnosti, sjaja i zabave u radni proces. Set sadrži i slike samih heroja igre, i pomoćne likove, oružje i ikone igre. Izaberite ono što odgovara vašem raspoloženju - kurori za igre će se svidjeti ne samo igračima, već i svima koji su jednostavno umorni od sive svakodnevice. Samo preuzmite set, promijenite kursor miša - i idite, da ispunjavate zadatke, uništavate neprijatelje i ostvarujete svoje ciljeve.',
    'multfilmy_descr' => 'Unutar svakog odraslog čovjeka još uvijek postoji dijete koje voli crtaće i još uvijek sanja da postane jedan od heroja. Mi ćemo pomoći da vam se snovi ostvare - koristite novu kolekciju kursora zasnovanih na najpoznatijim i omiljenim crtanim filmovima. Tom i Džeri, Buzz Lightyear i Šrek, Gravity Falls i čak Pokemon - možete postati ono što želite svakog dana. Odaberite kursor miša u skladu sa svojim raspoloženjem. Ko ste vi danas? Neoprezni i veseli minion koji lako rešava bilo koje probleme ili snažan i hrabar Rafael, čiji cilj nije samo da ostvari podvige, već i da jede picu? Možda ste svemogući džin koji drži čitavu kancelariju pod svojom komandom? U kolekciji postoje heroji za svakoga - od princeza do zmajeva - ostaje samo da odlučite ko odražava današnje raspoloženje. Cursor Style nije samo svetla slika. Ovo je odraz individualnosti, samoizražavanja i jednostavno - zabave, radosti i pozitivnosti za ceo dan. Da li je dosadno raditi ili previše lenj za učenje? Da li ste postali tužni i niste srećni? Promenite kursor i svet će zasijati novim bojama.',
    'kino_i_serialy_descr' => 'Filmovi - to je magija, misticizam i samo odličan način da se opustite, zabavite i dobijete živopisne emocije. U isto vreme, nakon gledanja, i dalje se sećamo omiljenih junaka koje zaista želimo da sretnemo u stvarnosti. Sada je to moguće - samo preuzmite novu kolekciju kursora zasnovanih na poznatim filmovima i TV emisijama. Svetli, kul kursori će biti odličan dodatak radnoj površini, pretvoriti dosadan sivi svakodnevni život u praznik, a banalne zadatke - u uzbudljivu avanturu. Menjajte kursor junaka svaki dan - za raspoloženje, zadatke ili nasumice. Ko ćete biti danas? Iskreni i pošteni Džon Snežni ili hrabri, neumoljivi Džon Vik? Možda imate tešku misiju ispred sebe i samo Frodo može da je ispuni? Možda ste danas samo vanzemaljac koji ne želi da stupi u kontakt sa drugima? Odaberite odgovarajući kursor - podignite raspoloženje i istovremeno pokažite drugima šta mislite i kako planirate da provedete dan. Probajte - nije samo zabavno, već i zarazno - definitivno nećete želeti da se vratite na uobičajenu strelicu.',
    'anime_descr' => 'Anime je jedinstveni stil animacije, koji, uprkos svojoj izraženoj etničkoj pripadnosti, uživa veliki broj ljudi širom sveta. Malo je verovatno da postoji bar jedna osoba koja nije gledala crtaće u ovom stilu. Mi smo kreirali najkul anime stil kursore koje će svi obožavatelji ovog stila voleti. Standardni kursori su dosadni i otrcana stvar. Pokažite svoju ličnost - koristite kolekciju Anime kursora sa svojim omiljenim likovima. Izaberite kursor tamnog mača ako sanjate o avanturama i hrabrim bitkama. Slatki debeli čovek Totoro će vas razveseliti čak i u najtužnijem danu, a Naruto će vas motivisati na avanture i pokazati svima oko vas da ste mega kul. Svetli kursori će ulepšati radni dan ili učiniti proces učenja zanimljivijim i prijatnijim. Ne ograničavajte se - koristite svoje omiljene motive čak i u tako malim elementima kao što je kursor miša. Menjajte kursore svakog dana, prilagodite ih svom raspoloženju i pokažite svoju ličnost - sa anime stil kursorima je to tako jednostavno.',
    'futbol_descr' => 'Fudbal je poseban sport koji uključuje elemente rvanja, atletike, preciznosti. Uopšte, on je spektakularan, nemilosrdan i okuplja milione navijača širom sveta. Da li volite fudbal ili samo volite sport? Zatim preuzmite skup kursorа u stilu svetski poznate igre i dokažite titulu lojalnog navijača. Kolekcija sadrži 24 opcije za dizajniranje kursorа - u obliku najpopularnijih timova koji zaslužuju svoje titule kao očajna i uporna igra. Kursorі su napravljeni u dve verzije - u obliku standardnog trougla, ukrašenog u bojama tima, ili u obliku odgovarajuće kacige za igru. Standardni kursor pretraživača je dosadan i ne dostojan pravog ljubitelja sporta. Postanite originalni i jedinstveni sa našom kolekcijom. Preuzmite slike i odaberite boje vašeg omiljenog tima ili prilagođenih kursorа, ako samo volite sport i navijate za sve. Praćenje vaših hobija je tako jednostavno - ne morate da dođete na posao u šalu ili kapu vašeg omiljenog tima, brzo je i lako promeniti kursor u svetlu, stilsku sliku.',
    'avtomobili_descr' => 'Da li volite automobile i uživate u gledanju modela različitih proizvođača? Ili sanjate o određenom brendu već dugo, ali još uvek nemate priliku da ga kupite? Posebno za vas, kreirali smo svetli set kursora "Superautomobili". Ovde ćete pronaći klasični Ford i stilski Bentley, svetli Lamborghini i jedinstveni Ferrari. Želite li da postanete vlasnik originalnog automobila? Jednostavno je - preuzmite našu kolekciju kursora na svoj uređaj i menjajte sliku automobila barem svaki dan. Kursori su dizajnirani u dve verzije - kao punopravni automobil ili kao njegov znak. Izaberite ono što vam se najviše sviđa ili kako preferirate da radite. Takve slike će izgledati sjajno kao kursor za igru ili jednostavno kao neobičan element radne površine. Biti svetao je jednostavno - za to nije nužno raditi nezamislive stvari ili menjati svoj izgled. Dovoljno je samo prestati koristiti uobičajene predmete i odabrati ono što vam se zaista sviđa. Kolekcija kursora "Automobili" je izbor za one koji se ne boje da se dokažu.',
    'memy_descr' => 'M ими су одавно познати део наших живота. И ко од нас не воли ове капацитивне, занимљиве и оригиналне слике упркос дану? Многи хероји мимова нису постали само популарни - стекли су статус популарних фаворита, а фразе и изрази су одавно укључени у колоквијални говор као добро успостављени обрти. Представљамо колекцију најбољих курсора заснованих на најпопуларнијим мимовима. Уз њихову помоћ, не само да можете показати своју личност, већ и изразити своје расположење. Да ли сте сви уморни и уморни од свега? Изаберите љуту мачку која својим изгледом изражава огорчење и непријатељство према свему око себе. Или данас сијате са сарказмом и не смета вам смех? Тада ће Дрејк Блинг бити одличан пратилац - развеселиће вас и учинити сваки задатак оригиналним и занимљивим. Инсталирајте екстензију, преузмите нашу колекцију - и изаберите стил курсора за сваки дан. Није тешко бити светао и оригиналан - промените стандардни дизајн иконе у једног од хероја мемова и добијте налет енергије за цео дан.',
    'emodji_descr' => 'Emotikoni - svetle, kul ikone, bez kojih više ne možemo uobičajeno da komuniciramo. Uz njihovu pomoć, ne morate da opisujete svoje raspoloženje rečima - samo izaberite željenu ikonu i sagovornik vas razume bez daljih reči. U našem novom setu kursora, mi smo otelotvorili ideju emotikona - tako su se pojavili smešni i neobični Kursorići koji će obojiti svet i učiniti život zanimljivijim. Uz pomoć kursora, ne samo da možete raditi i obavljati poznate zadatke, već i pokazati svojim kolegama, prijateljima i samo drugima svoje raspoloženje. Kursor koji spava je savršen za ponedeljak ujutro, a kursor koji plače će izraziti stav o dodatnim odgovornostima. Kul kursor sa naočarima je najbolji izbor pre praznika, a kursor sa dolarima u očima je dobar razlog da nagovestite šefu o povećanju plate. Korišćenje Kursorića je zabavno i zanimljivo - bilo da je u pitanju posao, studiranje ili prezentacija. U potonjem slučaju, čak se preporučuje da to uradite ukoliko kolege imaju smisao za humor ili samo treba da razvedrite situaciju. Generalno, za bilo koji zadatak - samo izaberite pravi kursor!',
    'pitomcy_descr' => 'Da li volite životinje? Sigurno - one su tako slatke, smešne i jako duhovite. Zašto ne biste proveli ceo dan u pratnji najboljih prijatelja čoveka? Preuzmite kolekciju kursorа Ljubimci za sebe i izaberite prijatelja za sebe svakog dana. Ikona kursora može da bude slatka, poput dobrodušne alpake, ili moderna, poput ružičastog flaminga. Ili možda ćete biti zauzeti ceo dan i izabrati jednoroga koji čita novine, ili jednostavno ne želite da komunicirate ni sa kim, kao zao crni mačak? Za svako raspoloženje imamo odgovarajuću životinju. Veseli mops će vas oraspoložiti čak i u najdosadnijem i najsivljem danu, a ružičasti kursor u obliku jednoroga će svima pokazati da niste lišeni osećaja za lepotu, čak i ako ste brutalni bradati čovek. Šta ako nema raspoloženja, i ne osećam se kao da radim rutinske zadatke? Recept je jednostavan - preuzmite kolekciju Ljubimci, promenite kursor miša - i voila, sunce ponovo sija, vreme je lepo, a raspoloženje je na najvišem nivou. Nije ni čudo što kažu da životinje pomažu u borbi protiv depresije i tuge!',
    'stil_i_krasota_descr' => 'U novoj kolekciji kursora prikupili smo širok spektar predmeta koji u nama izazivaju prijatne emocije i podižu raspoloženje. Ovaj set kursora nazvan je "Stil i Lepota", jer su to vaše omiljene stvari koje određuju naš svakodnevni život, pružaju radost i motivišu nas da radimo važne stvari, budeći želju za poboljšanjem. Da li ste zaljubljeni u svemir i sanjate da odete na druge planete? Izaberite NASA kursor ili tanjir vanzemaljaca - približite se svom snu. Ako ne možete da zamislite život bez muzike ili ste zakleti roker, onda je kursor u stilu električne gitare za vas. Kursor sa četkom, lenjirom i kompasom je specijalno razvijen za inženjere - takve slike će pomoći da se dosadne kalkulacije i crteži pretvore u originalna rešenja. Čarobni štapić i patike, skejtbord i ruž za usne, sunce i hemijske kupe - izaberite ono što odgovara vašem načinu života, vašim željama i težnjama - i obični zadaci će postati zanimljiviji, a radni dani će biti obojeni novim, svetlim bojama.',
    'prazdniki_descr' => 'Kao praznici? Ali ko ih ne voli - prijatelji, pokloni, opet isti vikend. Da bi čekanje na praznike bilo prijatnije, kraće i toplije, možete ne samo da brojite dane na kalendaru, već i da postavite odgovarajuću ikonu kao kursor miša. Počnimo sa Novom godinom - izabraćemo jelku, poklon ili Deda Mraza, tako da praznik bude svetao i veseo. Možda će medenjak biti bliži - smešan, sladak i uvek veseo? Sa njim sigurno neće biti vremena za tugu i dosadu. Nastavljamo da slavimo sa kupidima i veselim srcima, a nije daleko ni Uskršnji zeka. Negde među praznicima, biće rođendan, koji će biti još prijatnije čekati sa balonima umesto standardne strelice kursora. A na Noć veštica, možete iznenaditi kolege i one oko sebe neobičnim kursorom miša u obliku zloslutne bundeve ili duha. Set kursora za praznike je prilika da ulepšate iščekivanje, unapred se pripremite za predstojeću zabavu i održite odlično raspoloženje ne samo uoči proslave, već tokom cele godine.',
    'flagi_descr' => 'Zastava je jedinstveni simbol koji se široko koristi u svim društvenim mrežama. Mislili smo, zašto ne bismo napravili kursor u obliku zastave? Na kraju krajeva, zaista je svetao i neobičan. Sada možete provesti svaki dan u društvu nove zemlje, a posao neće biti tako monoton i dosadan. Kursovi miša sada se mogu napraviti u obliku nacionalne zastave Kine ili SAD-a, Japana ili Kanade i u još 38 opcija zastava, a možete odabrati ili standardni oblik strelice u neobičnoj boji ili kursor u obliku same zastave. Ovaj set će se dopasti svim ljubiteljima putovanja. Sa njim možete planirati nova putovanja i sanjati o dugim putovanjima. Da li ste isplanirali odmor? Pokažite svima u koju zemlju želite da idete. Možda ste odlučili da naučite novi strani jezik? Onda će vas ovaj kursor definitivno podržati i motivisati da pažljivo učite. Ili, kao Šeldon, jednostavno volite zastave? U svim slučajevima, kolekcija Zastava kursora će biti odličan dodatak vašoj radnoj površini i odvesti vas do novih otkrića.',
    'vokrug_sveta_descr' => 'Svi vole putovanja. Kako je divno posetiti nove zemlje i gradove, videti znamenitosti i provesti se u novoj kulturi. Šteta što ne možemo tako često da putujemo, ali pokušali smo to da popravimo. Set kursora „Oko sveta“ je kolekcija najupečatljivijih slika, simbola različitih zemalja, uz pomoć kojih se čak i sedeći kod kuće možete osećati kao pravi putnik. U našem kompletu možete pronaći Japan i Australiju, Italiju i Kanadu, SAD i Meksiko - najzanimljivije, originalne i živopisne zemlje na svetu. Slika kursora može postati standardna strelica, u bojama zastave zemlje, ili postati jedna od glavnih atrakcija države. Na primer, možete otvarati dokumente sa Krivim tornjem u Pizi i praviti prezentacije koristeći Statuu slobode. Garantujemo - uspeh će biti obezbeđen. Pa, ili ako ne uspeh, onda osmesi kolega i prepoznavanje originalnosti - sigurno. Da, i davanje nagoveštaja rukovodstvu da je vreme za odmor takođe će biti vredno - samo postavite kofer ili avion kao kursor - i najverovatnije ćete leteti veoma brzo.',
    'eda_i_napitki_descr' => 'Set kursora u obliku proizvoda je neverovatna kolekcija svetlih, ukusnih i sočnih slika koje će se svima sigurno dopasti i biće odličan dodatak pregledaču. Da li ste ikada kliknuli na brokoli ili pomfrit? Imate takvu priliku - samo preuzmite novi set kursora i postavite ih umesto dosadne bele strelice. Kursori "Hrana" su napravljeni i u obliku standardnog trouglastog pokazivača, i u obliku proizvoda. Ovde ćete pronaći povrće i voće, vaša omiljena jela, kao što su pica ili hot-dog, kafa, lizalice i još mnogo toga, što razveseljava bilo koji dan. Volite kafu, ali njeno celodnevno ispijanje nije baš dobro? Dopunite svoju ishranu virtuelnom kafom, koja će vas takođe osvežiti i probuditi, kao i dati živopisne emocije. Strm kursor u obliku virtuelnog krofna neće naškoditi figuri, dok će dati živopisne emocije i razveseliti. Možete koristiti svoje omiljene kursore ili menjati sliku svaki dan - veliki izbor kursora će pomoći da se oboji svakodnevni život i dodaju nove boje poznatim akcijama.',
    'cvetnye_descr' => 'Kursor je glavni element pretraživača, sa kojim provodimo ceo radni dan, učimo, komuniciramo i opuštamo se. Standardni prikaz kursora je dosadan i čak pomalo depresivan, ali ipak, za mnoge ljude, ovaj oblik je zgodan, a promena će biti neudobna. Ali za ovu situaciju, imamo rešenje - set kursora u svetlim, veselim bojama koje će uneti raznolikost u vašu svakodnevnicu i učiniti rešavanje bilo kakvih problema lakšim i bržim. Ako razmišljate o tome kako promeniti boju kursora, odgovaramo - preuzmite našu kolekciju i izaberite svetla rešenja za svaki dan! Možete izabrati monohromne tonove u različitim bojama kako bi odgovarali raspoloženju ili specifičnostima posla. Na primer, pri radu sa standardnim dokumentima, ljubičasti kursor će se isticati na pozadini, a na tamnoj pozadini, naprotiv, biće lakše raditi sa žutim kursorima. Ako želite eksploziju boja, svetlosti i maksimalne originalnosti - izaberite kursor u duginim bojama koji uključuje sve boje spektra - sa ovom ikonom, raspoloženje će definitivno biti dobro tokom celog dana.',
    'prank_descr' => 'Šale na poslu nisu uvek dobrodošle, jer često ometaju radni proces. Ali sa novim setom kursora „Pranks“, možete ljubazno da se našalite sa svojim kolegama ili prijateljima, a da ne ometate svoj rad ili studiranje. Razvili smo posebnu kolekciju koja će zabaviti svakoga i dati razlog da se malo opusti usred zauzetog procesa rada ili obavljanja drugog zadatka. Da biste promenili kursor miša, samo preuzmite komplet na uređaj i izaberite dizajn koji vam se sviđa u parametrima. Na primer, možete dobiti kursor standardnog oblika, ali u obrnutom stanju ili strelicu zakrivljenu talasom. Ovaj oblik uopšte neće ometati proces rada, ali će istovremeno predstaviti divno raspoloženje i postaviti vas u pozitivno raspoloženje. Promenite postavke prikaza kursora prema vašem raspoloženju ili svakog dana - i svaki zadatak će postati zanimljiviji i prijatniji, a svakodnevni život će prestati da izaziva negativne emocije. Štaviše, takvi kursori se mogu koristiti čak i za ozbiljne projekte - imaju neutralne boje i ne ističu se iz radne površine.',
    'startovyj_nabor_descr' => 'Kursori iz početne kolekcije su mešavina standardnih oblika i veličina sa svetlim, neobičnim izgledom. Ovo je odličan izbor za one koji preferiraju uobičajene oblike, ali želeli bi da unesu raznolikost, originalnost i svetlost u svakodnevni život. Kolekcija ima kursor ruke i poznatu strelicu u različitim varijacijama - od Google Chrome logotipa do emotikona, ovde možete sresti i davno zaboravljenog zmaja sa kaktusima i nostalgijom. Dokazujemo da standardni kursor takođe može biti zanimljiv i atraktivan. Različite boje, oblici, teksture i zanimljiv dizajn pomoći će vam da izaberete kursor po svom ukusu ili da ga menjate svakog dana u zavisnosti od raspoloženja ili zadataka. Promena kursora u pretraživaču je vrlo jednostavna - samo instalirajte ekstenziju i preuzmite kolekciju na svoj uređaj. Smešni, zanimljivi kursori ne samo da će obojiti radne dane, već će vam, na primer, pomoći da učinite svaku prezentaciju zanimljivijom, a uz pomoć posebno svetlih kursora, takođe skrenuti pažnju na pojedine elemente izveštaja.',
    'fortnite_descr' => 'Fortnite je osvojio milione ljudi širom sveta. Uzbudljive bitke, strategija i taktika, avanture - upio je apsolutno sve što igrači toliko vole. Nismo mogli da ostanemo po strani i razvili smo set kursora u stilu igre koji će se dopasti ne samo strastvenim igračima, već i onima koji su prvi put čuli za Fortnite. Ikona Fortnite kursora je slika heroja ili njegovog oružja, razrađena do najsitnijih detalja. Ovde možete pronaći slike lisica i riba, maske pakla i crnih vitezova, postaviti strelu ili kosu sa šiljcima kao strelicu. Uvereni smo da niko neće ostati ravnodušan! Biti strašan ili misteriozan, originalan ili humorističan - na vama je. Odaberite svoj stil i pratite ga ili postavite prilagođene kursore u podešavanjima i menjajte svoju ulogu svaki dan. Sada će postati znatno zanimljivije i prijatnije obavljati čak i dosadan i monoton posao - vreme će proleteti brzo u društvu živopisnih slika i omiljenih likova. Ili možda organizujete takmičenja sa kolegama, koji će heroj biti jači? Izbor je vaš!',
    'dota_2_descr' => 'DotA2 sada nije samo jednostavna igra, to je pravi paralelni svet. U virtuelnoj realnosti u DotA2, možete uraditi sve - živeti, boriti se, razvijati se, putovati, steći prijatelje. Generalno, sve je kao u životu, samo ponekad zanimljivije. Dota 2 pokazivači su nastavak strategije koja će vam omogućiti da dobijete živopisne emocije i izrazite sebe u stvarnom svetu. Novi set pokazivača uključuje najupečatljivije likove u igri, kao i originalne predmete koji se ne mogu pomešati ni sa čim drugim. Izaberite pokazivač koji će vam biti bliži - i krenite u avanturu bez napuštanja svog radnog mesta. Kako je ponekad dosadno biti na poslu ili obavljati obrazovne zadatke, ali sa pokazivačima iz igara ovaj problem vas više neće sresti. Malo mašte, svetao pokazivač - i voala, svaki posao će biti neobična avantura, sa kojom se neće biti teško i zanimljivo nositi. Nema potrebe da se suzdržavate. Da li volite Dota? Onda obavezno preuzmite našu kolekciju, izaberite jedan ili nekoliko nasumičnih pokazivača odjednom - i svaki novi dan će postati svetliji, zanimljiviji i zasićeniji.',
    'minecraft_descr' => 'Miševi kursori u obliku standardnih strelica i prstiju su odavno postali dosadni svima. Ako ste ljubitelj neobičnog i originalnog, onda je vreme da promenite kursor miša i date mu zanimljiviji dizajn. Razvili smo kolekciju kursora u stilu svetski poznate igre Minecraft, gde možete pronaći najupečatljivije likove. Vuk i lisica, Alex i Creeper, dijamantski mač i riba - možete izabrati onaj koji vam se najviše sviđa ili instalirati novog heroja svakog dana. Ovo su pravi kursori za igrače, i apsolutno će se svima svideti - na kraju krajeva, ko od nas nije igrao Minecraft? Uvereni smo da oni jednostavno ne postoje. Dosta sa dosadnom svakodnevnicom - vreme je da uronite u avanture, što se može učiniti čak i bez napuštanja vaše kuće ili kancelarijske stolice. Biće zanimljivije pripremiti izveštaj i smanjiti balans sa pištoljem - bilo koji zadatak će postati prijatniji i neće vam dozvoliti da vam bude dosadno na licu mesta. Preuzmite novu kolekciju Minecraft kursora - postavite ih i čak i u najsivljem i najdosadnijem danu vaše raspoloženje će uvek biti najbolje. A kolege će zavideti vašim rezultatima - jednostavno je nemoguće ne uraditi svoj posao uz pomoć hrabrih heroja Minecraft-a.',
    'astrology-signs-zodiac' => 'Znaci Zodijaka',
    'sports-cars_short_descr' => 'Snažni i stilski automobili napravljeni za brzinu i agilnost',
    'spider-man' => 'Spider-Man',
    'astrology-signs-zodiac_short_descr' => 'Set od 12 astroloških simbola koji predstavljaju osobine ličnosti, kosmičke energije i životne obrasce.',
    'sports-cars' => 'Sportski automobili',
    'sports-cars_descr' => 'Sportski automobili su vozila visokih performansi dizajnirana za brzo ubrzanje, oštro upravljanje i uzbudljivo iskustvo vožnje. Od elegantnih kupea do agilnih roadstera, ova kategorija sadrži neke od najikonastijih mašina napravljenih za uzbuđenje na putu ili stazi. Idealno za entuzijaste koji vole brzinu, dizajn i snagu. 🏎️🔥',
    'spider-man_short_descr' => 'Heroji iz univerzuma Spider-Man',
    'starwars' => 'Star Wars',
    'spider-man_descr' => 'Kolekcija likova i heroja iz Spider-Man univerzuma. Uključuje različite verzije Spider-Mana, saveznike i jedinstvene stilove iz stripova, igara i animiranih serija. Svaki dizajn odražava agilnost, hrabrost i vizuelni identitet koji definišu svet Spider-Mana.',
    'astrology-signs-zodiac_descr' => 'Znakovi Zodijaka ♈♉♊♋♌♍♎♏♐♑♒♓ su dvanaest simboličkih podela nebeskog pojasa koji se koriste u astrologiji. Svaki znak je povezan sa specifičnim datumima, elementima (🌍 Zemlja, 🔥 Vatra, 🌊 Voda, 💨 Vazduh), vladajućim planetama i jedinstvenim karakteristikama ličnosti. Astrolozi koriste znakove zodijaka da tumače ponašanje, predviđaju kompatibilnost i istražuju životne puteve. Bez obzira da li ste strastveni Lav 🔥 ili zamišljena Riba 🌊, vaš znak nudi uvid u vaš unutrašnji svet. Ova kategorija uključuje svih 12 znakova, njihova značenja i vizuelne prikaze.',
    'starwars_descr' => 'Uronite u galaksiju daleko, daleko sa ovom kolekcijom koja sadrži legendarne heroje, moćne Sith lordove, droide, pobunjenike i još mnogo toga. Od Jedi vitezova do stormtroopera, svaka ikona oživljava duh Ratova zvezda u obliku kursora. Savršeno za fanove svake trilogije. 🌌',
    'starwars_short_descr' => 'Likovi i simboli iz univerzuma Ratova zvezda',
    'glitter' => 'Šljokice',
    'glitter_short_descr' => 'Sjajni i svetlucavi kursori sa stilom šljokica ✨🌟',
    'glitter_descr' => 'Glamurozna kolekcija kursora inspirisanih šljokičastim teksturama i sjajnim vizualima. Savršeno za one koji vole blistavu estetiku na svom ekranu. Ovi kursoru donose sjaj, eleganciju i malo magije svakom kliku.',
    'roblox-2025' => 'Roblox 2025',
    'roblox-2025_short_descr' => 'Likovi iz najnovijeg Roblox talasa 🕹️🚀',
    'roblox-2025_descr' => 'Potpuno nova kolekcija za 2025. godinu koja sadrži legendarne i moderne Roblox likove. Uključuje klasične noobove, horor legende i omiljene avatare obožavalaca iz popularnih igara. Dizajnirana u zabavnom i šarenom stilu savršenom za decu i Roblox fanove svih uzrasta.',
];
