<?php
 return [
     	'halo_descr' => 'Halo es una franquicia de medios de fantasía de combate creada por Bungie. Basado en la trilogía original de videojuegos de disparos en primera persona. La trama gira en torno a los acontecimientos que tienen lugar en la vida de Master Chief, uno de un grupo de supersoldados cuyo nombre en código es \"Spartans\", y su compañera, la inteligencia artificial Cortana. El éxito de los juegos ha llevado a la expansión de la franquicia a otros medios: el universo de Halo actualmente abarca muchos libros, novelas gráficas, cómics, cortos, animaciones y largometrajes.',
	'halo_short_descr' => 'Toque el cursor del artefacto, tal vez usted sea el elegido',
	'halo' => 'HALO',
	'lol_surprise_descr' => 'Las muñecas LOL Surprise enamoraron a los niños y conquistaron su corazón desde los primeros minutos. Y esto no es de extrañar, porque tal éxito se basa en un misterio, la expectativa de un milagro, una sorpresa agradable, que hace las delicias no sólo de los niños, sino también de sus padres. El secreto del regalo se revela al niño solo después del desempaque final. En cualquier caso, las muñecas LOL tienen un diseño atractivo, intriga, una gran cantidad de accesorios asombrosos y realistas y pequeñas cosas agradables, así como la más alta calidad de producción y detalles del juguete.',
	'lol_surprise_short_descr' => 'Bellezas geniales para conocedores de hermosas sorpresas.',
	'lol_surprise' => 'L.O.L. Surprise',
	'squid_game_descr' => 'La serie gira en torno a un concurso en el que 456 jugadores, todos los cuales tienen una gran deuda financiera, arriesgan sus vidas para jugar una serie de juegos infantiles mortales por la oportunidad de ganar un premio de mil millones. En el interior, un premio tentador espera con altas apuestas mortales. El título de la serie se basa en un juego infantil coreano con un nombre similar. Hwang había concebido la idea sobre la base de sus propias luchas económicas a temprana edad, así como la disparidad de clases en Corea del Sur y el capitalismo.',
	'squid_game_short_descr' => 'Elige la cara de jugador correcta cuando vayas all-in',
	'squid_game' => 'Juego de calamar',
	'harry_potter_descr' => 'Harry James Potter es el protagonista de una serie de novelas de la escritora inglesa JK Rowling. En su undécimo cumpleaños, Harry se entera de que es un mago y está destinado a un lugar en la Escuela de Hechicería de Hogwarts, donde practicará magia bajo la guía del director Albus Dumbledore y otros profesores de la escuela. Harry también descubre que ya es conocido en toda la comunidad mágica de la novela y que su destino está relacionado con el destino de Voldemort, un peligroso mago oscuro.',
	'harry_potter_short_descr' => 'Qué harás con una varita mágica de la colección de cursores de Harry Potter',
	'harry_potter' => 'Harry Potter',
	'marvel_comics_descr' => 'Marvel Comics es una editorial de cómics conocida por crear superhéroes notables como Spider-Man, Iron Man, Capitán América, Hulk, Thor, los Vengadores, los Guardianes de la Galaxia, los X-Men, los Cuatro Fantásticos y Deadpool. . Los villanos más conocidos de Marvel incluyen Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom y Magneto. Marvel Comics y DC Comics han colaborado juntos en varios proyectos cruzados y también cofundaron el sello Amalgam Comics intencionalmente de corta duración.',
	'marvel_comics_short_descr' => 'El superhéroe vive en cada uno de nosotros - elige el tuyo',
	'marvel_comics' => 'Marvel Comics',
	'cookie_run_kingdom_descr' => 'Bienvenido de nuevo al Reino de las Galletas en Cookie Run: Kingdom de Devsisters, el adorable RPG de estrategia ambientado en el universo de Cookie Run. Ahora que GingerBrave ha escapado del horno de la bruja malvada, es hora de que construya un equipo de Cookies y se embarque en una búsqueda para reconstruir el caído Reino de las Galletas. Descubre la verdad detrás de la caída del Reino y reúne un escuadrón de las Cookies más poderosas del Reino para derrotar a las fuerzas oscuras que quieren evitar que GingerBrave cumpla su destino.',
	'cookie_run_kingdom_short_descr' => 'Pequeños guerreros recién salidos del horno',
	'cookie_run_kingdom' => 'Cookie Run Kingdom',
     	'genshin_impact_descr' => 'Genshin Impact es un juego de aventuras de mundo abierto. Esto significa que un nuevo y encantador paisaje te espera al otro lado del río o la montaña, solo necesitas usar tu energía sabiamente. Si te encuentras con un hada errante o un mecanismo extraño, atrévete e intenta desentrañar su misterio. Pero lo que prometen, problemas o una sorpresa agradable, ¡solo usted puede descubrirlo! En el vasto continente de Teyvat, visitará siete reinos, encontrará compañeros con diversas habilidades y luchará contra poderosos enemigos en busca de un ser querido desaparecido.',
	'genshin_impact_short_descr' => 'Conviértete en el Maestro Elemental de los Siete Reinos',
	'genshin_impact' => 'Genshin Impact',
	'frozen_descr' => 'Cuando una antigua profecía se hace realidad y el reino se sumerge en el abrazo del invierno, tres intrépidos héroes, la princesa Anna, el valiente Kristoff y su fiel reno Sven, van a las montañas para encontrar a la hermana de Anna, Elsa, que puede eliminar el hechizo escalofriante del país. En el camino, les esperan muchas sorpresas difíciles y aventuras emocionantes. Conocer trolls místicos, conocer a un encantador muñeco de nieve llamado Olaf, picos de montañas más empinados que el Everest y mucha magia. Los héroes tienen que resistir los poderosos elementos para salvar el reino y a sus seres queridos.',
	'frozen_short_descr' => 'Romper el hielo es fácil con la colección de cursores de Frozen',
	'frozen' => 'Frozen',

     
	'stranger_things_descr' => 'Han pasado poco más de seis meses desde el final de la tercera temporada. Joyce, Will, Eleven y Jonathan se han mudado a California, donde la niña está siendo acosada en la escuela. El resto comienza a luchar contra un nuevo monstruo de un mundo paralelo que ha aparecido en Hawkins. Fue nombrado Vecna ​​por el personaje del juego de mesa Dungeons & Dragons. Afecta psicológicamente a los adolescentes, luego sube mentalmente a la cabeza y mata. Paralelamente, Joyce y Murray se enteran de que Jim Gopper está vivo y van tras él a una prisión soviética en Kamchatka. Y Eleven tendrá que regresar y aumentar sus poderes, pero también aprenderá su importante papel en la creación del mismo monstruo en Gokins.

Los escritores no cambiaron las tácticas de la trama que les gustaron en las últimas temporadas. En la cuarta temporada, dividieron al gran grupo de personajes principales en grupos, se les ocurrieron tareas difíciles y, al final, construyeron sus historias juntos en un final sorprendente. Te ofrecemos comprender todas estas aventuras en detalle con la ayuda de la colección de cursores de Stranger Things.',
	'stranger_things_short_descr' => '¿Qué pasará después? - Cosas extrañas 4 cursores',
	'stranger_things' => 'Cosas más extrañas 4',
	'roblox_bed_wars_descr' => 'Bed Wars es un modo original que apareció por primera vez en Minecraft. La tarea de los jugadores era que el usuario protegiera su base y su cama.

Roblox trae juegos más emocionantes todos los días y BedWars no es una excepción. Y es que si te encantan las bed wars y te defiendes en tu habitación, este es tu título porque te traslada a la infancia, aunque esta vez de forma digital.

Todo lo que necesitas hacer es defender tu cama de los atacantes con tu pareja. Entras en un lobby, eliges con quién jugar y listo, es solo una cuestión de protección.

Por supuesto, cuando se trata de defensa, tendrás algunos problemas y hay ciertos recursos, elementos y elementos que te ayudarán a ganar. Por ejemplo, pieles exclusivas que encontrarás en la colección de cursores de Bed Wars.',
	'roblox_bed_wars_short_descr' => 'Protege tu cama con los cursores de Roblox Bed Wars',
	'roblox_bed_wars' => 'Roblox Bed Wars',
	'naruto_anime_descr' => 'En el cumpleaños de Naruto Uzumaki, un demonio legendario, el zorro de nueve colas, atacó un pueblo llamado Konoha. El Cuarto Hokage, a costa de su vida, salvó la aldea sellando al demonio en el recién nacido Naruto, sin saberlo, condenándolo a una vida de odio por parte de sus compañeros aldeanos.
A pesar de su falta de talento en muchas áreas del ninjutsu, inquietud y esnobismo, Naruto tiene el sueño de convertirse en Hokage, el ninja más fuerte del pueblo. Deseando el reconocimiento que no obtuvo, trabaja duro y entrena junto a sus compañeros de equipo Sasuke Uchiha y Sakura Haruno, así como a su mentor Kakashi Hatake. Él y sus socios tendrán que pasar por mucho en el camino hacia sus preciados sueños: batallas, amor, amistad, traición, sed de poder. ¡Una colección de cursores de anime de Naruto te ayudará a hacer tu propio camino!',
	'naruto_anime_short_descr' => 'Recorre tu camino ninja con los cursores de anime de Naruto',
	'naruto_anime' => 'Naruto animado',
	'demon_slayer_anime_descr' => 'La acción tiene lugar durante la era Taisho. Desde la antigüedad, ha habido rumores de que en el bosque viven demonios humanoides, que se alimentan de las personas y caminan de noche en busca de una nueva víctima. Pero... es solo una leyenda, ¿no?..

Tanjiro Kamado es el hijo mayor de la familia, quien perdió a su padre y se hizo cargo de su familia. Un día va a un pueblo cercano a vender carbón. Al regresar por la mañana, el chico descubre una imagen terrible frente a él: todos los familiares fueron brutalmente asesinados, y el único sobreviviente es Nezuko, una hermana menor convertida en demonio, pero que aún no ha perdido toda su humanidad.

A partir de este momento, Tanjiro y Nezuko emprenden un largo y peligroso viaje, en el que el chico pretende encontrar al asesino y encontrar la forma de curar a su hermana. Pero, ¿son capaces los niños de superar todas las dificultades y volver a casa? Ya sabes la respuesta, y si no, mejor configura los cursores Demon Slayer, con personajes de uno de los manga más populares.',
	'demon_slayer_anime_short_descr' => 'Cursores Demon Slayer - para verdaderos cazadores nocturnos',
	'demon_slayer_anime' => 'Asesino de demonios animado',
	'bts_descr' => 'BTS es un grupo de chicos de siete miembros bajo BigHit Music. Debutaron el 13 de junio de 2013 con el sencillo \"No More Dream\". En Japón, hicieron su debut el 24 de diciembre de 2014 con el álbum de estudio Wake Up.

El nombre del grupo proviene de la expresión coreana Bangtan Sonyeondan, que significa \"boy scouts a prueba de balas\". Según J Hope, el nombre significa el deseo de la banda de bloquear los estereotipos, las críticas y las expectativas que se dirigen a los adolescentes como balas.

La colección de cursores dedicada al grupo incluye a todos los miembros del grupo, aquí el cursor de Kim Nam Joon (también conocido como RM), el cursor de Kim Seok Jin (Jin), el cursor de Min Yoongi (Suga), el cursor de Jung Ho Suk (J-Hope), Cursor de Park Ji Min (Jimin), cursor de Kim Tae Hyun (V) y cursor de Jeon Jungkook (Jungkook).',
	'bts_short_descr' => 'Conoce a tus ídolos con los cursores BTS',
	'bts' => 'BTS',
	'miraculous_descr' => 'Miraculous: Tales of Ladybug y Cat Noir, más conocidos como Miraculous Ladybug y Cat Noir, son aventuras de superhéroes de la caricatura sobre dos compañeros de clase que, bajo máscaras, interpretan el papel de los defensores de París de un villano que en cada episodio se le ocurre. una nueva forma de dañar la ciudad. Miraculous está hecho en Francia usando CGI y animación. Miraculous no es solo una serie animada, sino también una colección de cómics lanzados en todo el mundo. La serie es muy querida por el público joven.

La acción tiene lugar en París, donde Marinette y Adrian son estudiantes de secundaria en una escuela moderna. Se les dio el papel de convertirse en los elegidos en la lucha contra el mal, salvando su ciudad natal. Su objetivo es proteger a la gente de Akumas. Estas pequeñas criaturas en forma de mariposas son capaces de habitar en una persona y convertirla en un villano.

Marinette puede transformarse en una mariquita, y Adrian, en un Cat Noir, pero sorprendentemente, trabajando en parejas, no se reconocen bajo las máscaras de superhéroes.

Ayuda a Cat Noir y Ladybug a salvar París con nuestros cursores con tus personajes favoritos. ¿Qué personaje elegirás para el cursor? ¿Será un cursor de Miraculous Ladybug, o tal vez el adorable cursor de Ladybug o Cat Noir de Tikki? ¿O tal vez una abeja reina con cursores Rena Rouge? ¡La decisión es tuya!',
	'miraculous_short_descr' => 'Únete a las filas de superhéroes con la colección de cursores Lady Bug y Cat Noir',
	'miraculous' => 'Miraculous: Tales of Ladybug & Cat Noir',
	'talking_tom_descr' => 'La serie cuenta la vida diaria de Talking Tom y sus amigos. Tom y su socio comercial nerd Ben desarrollan constantemente aplicaciones móviles y otros inventos para alcanzar la fama y la fortuna y tratar de mostrarse al mundo, pero esto siempre resulta contraproducente. La novia de Tom, Angela, intenta ser cantante, sin importar lo que haga para lograrlo. El vecino de Tom, Ginger, viene muy a menudo aquí para hacer bromas con travesuras bajo la manga. Estúpido mejor amigo y compañero de cuarto Hank se queda en casa, mira MUY TV. Y la ex estrella del pop disidente Becca Sparkles se ha convertido en la nueva compañera de cuarto de Angela y parece haberse enamorado de Hank. Dicho esto, sin importar los problemas de todas las formas y tamaños, ya sea el malvado CEO, el misterioso nuevo vecino de Tom o simplemente un accidente en la nueva creación de Ben, la pandilla se divertirá sin importar qué, y siempre recordará una cosa que los mantiene. juntos: la amistad nunca termina, al igual que nuestro amor por los personajes de la serie no termina, así que ahora puedes configurar el cursor de Talking Tom o el cursor de Ben, o tal vez el cursor de Angela, el cursor de Oliver.',
	'talking_tom_short_descr' => 'Hablemos de tu personaje favorito de Talking Tom Cursor Collection',
	'talking_tom' => 'Hablando de Tom y amigos',
	'lego_descr' => 'La empresa LEGO Group se fundó en 1932 y luego estaba formada por solo 7 personas. El objetivo del equipo de Lego era crear juguetes que desarrollaran la creatividad, la imaginación y el ingenio de un niño. Un hecho sorprendente, desde sus inicios en 1949, los elementos LEGO en todas sus variantes se han mantenido compatibles entre sí. Todos los artículos creados posteriormente siguen siendo compatibles con los artículos que se lanzan hoy, a pesar de los cambios en el diseño y la forma a lo largo de los años.

Un ladrillo LEGO es una base, que es un bloque de plástico hueco que se conecta a otros ladrillos similares. Pero los sets de Lego también contienen otras partes, ruedas, figuras, plataformas e incluso circuitos electrónicos con sensores y motores eléctricos. Puede recolectar modelos de automóviles, aviones, trenes, barcos, edificios, robots. LEGO se adhiere a la idea de modularidad, que demuestra claramente a los niños cómo resolver ciertos problemas, desarrollar la imaginación, la motricidad fina de las manos y las habilidades de montaje. Los ladrillos LEGO están fabricados con una precisión increíble y encajan perfectamente para lograr una precisión asombrosa de 10 micrones.

Recientemente, se han creado muchas historias populares de Lego animadas en 3D, donde los personajes de los sets cobran vida y se convierten en participantes de increíbles aventuras. Si quieres un cursor genial, encontrarás muchos personajes de la serie de televisión Lego y películas animadas en nuestra colección Lego Cursors. Lego Ninjago Cursor, Lego Batman Cursor, Lego Ninjago Cursor, Lego Wyldstyle Cursor y muchos más.',
	'lego_short_descr' => 'Construye el navegador de tus sueños con la colección de cursores Lego',
	'lego' => 'Lego',
	'hollow-knight_descr' => 'Después de una financiación exitosa de Kickstarter, en 2017, Team Cherry lanzó el juego de PC multiplataforma Hollow Knight. Esta es la historia de un caballero sin nombre y sus descubrimientos en el reino de insectos Hallownest. El juego fue reconocido legítimamente como uno de los mejores del género metroidvania.

La jugabilidad de Hollow Knight se basa en la exploración del mundo del juego. Superar obstáculos, resolver acertijos y encontrar secretos, así como luchar contra enemigos. El jugador tiene un conjunto único de mejoras y trucos para explorar el mundo y luchar en batallas. Moviéndose de una zona a otra, el jugador derrota a los jefes y obtiene las mejoras necesarias para avanzar más. Como resultado, los jugadores deben visitar las áreas ya pasadas para encontrar secretos y repasar la historia. Y también es emocionante porque las zonas cambian cada vez, trayendo nuevas sorpresas y experiencias. El juego se puede jugar de diferentes maneras, porque hay varios caminos diferentes entre las zonas. Al pasar por la historia, abre el mapa de la zona, pero primero necesita obtener el mapa.

El arma principal del héroe es un clavo, que es algo similar a una espada, las armas se pueden mejorar con un herrero, además de aprender diferentes habilidades en el uso de armas, lo que amplía la variedad de ataques. Al atacar a los enemigos, acumulas un recurso especial, que luego se puede usar para mejorar o curar.
Diviértete jugando Hollow Knight y no te olvides de nuestros cursores Hollow Knight con tu personaje favorito. Nuestra colección incluye el cursor Mister Mushroom, el cursor Quirrel, el cursor Hornet Needle, el cursor Old Nail, el cursor Myla y otros.',
	'hollow-knight_short_descr' => 'Intenta no perderte en el reino de los insectos con la colección de cursores Hollow Knight',
	'hollow-knight' => 'Hollow Knight',
	'henry-stickmin_descr' => 'Henry Stickman es el personaje principal de la serie de juegos. Stikmin, que anteriormente no tenía nombre, comenzó como un ladrón menor, con el deseo de ganar dinero fácil rápidamente. Sin embargo, después de escapar de la prisión de West Mesa, se producen muchos cambios en su vida, y se convierte en un famoso criminal después de robar el Diamante tunecino. Henry tiene una opción: convertirse en un exitoso agente del gobierno, cazarrecompensas, líder de una organización criminal, cyborg o continuar solo en el camino criminal. El juego deleita a los fanáticos del género con muchas aventuras y acertijos, y encontrarás nuestra nueva colección de cursores Henry Stickman con sus divertidos personajes, incluido el cursor Henry Stickmin, el cursor Charles Calvin, el cursor Reginald Copperbottom, el cursor de la mano derecha, el cursor Ellie Rose y ¡otros!',
	'henry-stickmin_short_descr' => 'Planifique su escape del aburrimiento con Henry Stickman Cursors Collection',
	'henry-stickmin' => 'Henry Stickmin',
	'adopt-me_descr' => 'El muy popular juego en línea Adopt Me se lanzó en 2017 y se convirtió en el más popular en la plataforma de juegos Roblox. La esencia del juego es muy simple: consigue huevos con las mascotas y cuídalos.

Las mascotas virtuales se dividen en 5 clases, algunas de ellas son muy raras y caras, mientras que otras son muy fáciles de conseguir. Estos son grupos poco comunes, como el cursor Blue Dog, Common, Rare, por ejemplo, el cursor del mouse Adopt Me Monkey, así como los ultrararos, como el cursor Koala, y Legendary, Dragon cursor y Accept me unicorn. Si el jugador tiene cuatro mascotas adultas del mismo tipo, pueden combinarse en una mascota de neón, como el cursor del juego Neon Horse o Adopt Me Neon Starfish. Combinando cuatro mascotas normales, puedes hacer una mascota de neón que realmente brille, y a partir de mascotas de neón puedes crear una mascota mega-neón.

Compras en el juego Adopt Me! se llevan a cabo con la moneda virtual Roblox, el llamado Robux, y el juego también tiene su propia moneda, Bucks. Cuidando a tu mascota, además del entretenimiento, puedes ganar dólares, solo alimentarlo, acostarlo o leer un cuento de hadas, en general, muchas cosas interesantes.

Ahora los fanáticos del juego de Roblox \"Adopt Me!\" ¡Puede decorar el cursor del juego con su mascota favorita!',
	'adopt-me_short_descr' => '¡Diviértete con lindas mascotas en nuestro Adopt Me! colección de cursores de juego',
	'adopt-me' => 'Adopt me!',
	'among-us_descr' => 'Among Us se basa en el famoso juego de rol \"Mafia\". Se planeó que el juego se convirtiera en exclusivo para dispositivos móviles, porque solo tenía un mapa. El juego se hizo popular rápidamente. Más tarde, el equipo de desarrollo agregó un modo multijugador y se lanzaron dos mapas adicionales en 2019.
Among Us es un juego en tercera persona de arriba hacia abajo que permite al jugador moverse en todas las direcciones. En una ronda pueden jugar de cuatro a diez jugadores. Al comienzo del juego, a todos se les asigna en secreto el papel de un traidor o miembro de la tripulación. Impostor (en la traducción rusa \"Traidor\") puede esconderse en una escotilla de ventilación, sabotear y matar a los miembros de la tripulación. Su objetivo es destruir a todos los miembros de la tripulación o destruir la nave espacial mediante sabotaje. El objetivo de la tripulación del barco es resolver varios acertijos preparados para ellos al comienzo del juego. Si cada uno de los miembros de la tripulación completa todas las tareas, los traidores perderán. Además, la tripulación del barco puede lograr la victoria eliminando a los traidores durante la votación.
Los traidores pueden sabotear de vez en cuando y si el daño no se repara en 30 segundos, la tripulación perderá. Antes de comenzar el juego, puedes elegir el color del personaje que estás jugando, azul, rojo, amarillo, gris, ¡lo que sea! ¡Y no olvide colocar el cursor apropiado de la nueva colección Among Us!',
	'among-us_short_descr' => 'No te dejes engañar en este complicado juego espacial con los cursores Among Us',
	'among-us' => 'Among Us',
	'steven_universe_descr' => 'El creador del \"Steven Universe\" fue Rebecca Sugar. Es conocida por su trabajo anterior llamado Adventure Time. El primer episodio de Steven Universe fue lanzado en la plataforma de videos de YouTube en la primavera de 2013. Pero en el otoño, el canal estadounidense Cartoon Network comenzó a transmitirlo para sus televidentes. Desde entonces, se han lanzado 6 temporadas. El sexto promete ser final.
En cuanto a la trama de la serie animada, gira en torno al equipo de Crystal Gems. Se compone de criaturas alienígenas con nombres característicos: perlas, amatista y granada. Pero hay otro participante en él, en el papel del cual actúa un chico normal, Stephen. Juntos buscan monstruos e intentan neutralizarlos para que no se apoderen de la Tierra en beneficio personal. Se les oponen Jasper y Peridot, mensajeros de su planeta de origen que quieren derrotar a las Gemas y activar el Clúster.
Si eres fanático de Steven Universe y quieres ver a los personajes de la serie animada donde sea que puedas, ¡instala la extensión Cursor Style! ¿Por qué hacer esto? Puede agregar una colección dedicada al \"Universo Steven\" y convertir el puntero del mouse estándar en uno de sus personajes favoritos.',
	'steven_universe_short_descr' => 'Descubre el secreto de las gemas con los cursores Steven Universe',
	'steven_universe' => 'Steven Universe',
	'family_guy_descr' => 'Una comedia animada llamada \"Family Guy\" en toda la historia de su existencia ganó 4 veces el Premio Emmy y 3 veces el \"Annie\". La serie animada ridiculiza los temas problemáticos de la sociedad estadounidense, tales como: feminismo, esclavitud, obesidad, política, etc. A diferencia de otras obras, aquí se usan inserciones con chistes y sarcasmo. Además, en muchos casos no están integrados en la trama, sino que existen por sí solos.
Un episodio de la serie animada se crea durante 10 meses. ¿Porque tan largo? Porque toda la animación está dibujada a mano. Debido a esto, algunos de los eventos cubiertos por el trabajo tienen tiempo para perder relevancia. Pero aun así, la comedia sigue siendo muy interesante y gana el favor de los espectadores de todo el mundo. Después de todo, a quién no le gusta reírse bien de políticos, celebridades o personas que cometen payasadas salvajes y, por lo tanto, sorprenden o incluso sorprenden a la gente común.
¿Te gusta \"Family Guy\"? ¡Tienes una oportunidad única de convertir un cursor de mouse normal en cualquiera de los personajes de esta serie animada! ¿Que necesito hacer? Simplemente instale la extensión del navegador \"Cursor Style\", agregue una colección dedicada a \"Family Guy\" y disfrute de una fabulosa reencarnación.',
	'family_guy_short_descr' => 'Colección de cursores de Family Guy para conocedores de humor especial',
	'family_guy' => 'Chico de familia',
	'cute_cursors_descr' => '¿Seguramente escuchaste la expresión \"La belleza salvará al mundo\"? Entonces, muchas personas, especialmente las niñas, están de acuerdo con esta declaración. Por lo tanto, se esfuerzan por rodearse de todo lo más bello y agradable a la vista. Puede ser papel tapiz rosado en el dormitorio, peluches, almohadas bordadas con cuentas, joyas preciosas, etc. Desde el exterior, todo se ve muy lindo e incluso un poco infantil. Pero cada uno de nosotros es un niño pequeño en nuestros corazones, entonces, ¿por qué no dejar que muestre nuestra imaginación?
La ternura en nosotros puede causar mucho. Por ejemplo, los ojos compasivos de un gatito que quiere ser acariciado o alimentado. Un arcoiris multicolor que se asoma después de una lluvia de primavera y brilla con todos los colores del sol. El niño que recibió el chocolate y decidió compartirlo con su novia o novio. Hay bastantes razones para tocar, y decidimos usarlas como cursores.
¿Cansado de la flecha blanca aburrida en su navegador? ¡Reemplácelo con algo lindo de nuestra colección! Por ejemplo, un unicornio rosa y blanco, un tomate triste, una nube melancólica, un cactus espinoso en forma de gato, o lo que quieras. Todo lo que necesita hacer es instalar la extensión Cursor Style y agregarle una colección de lindos cursores. Y viva el salvador del mundo: ¡belleza!',
	'cute_cursors_short_descr' => 'El mundo será más amable con la linda colección de cursores',
	'cute_cursors' => 'Cursores lindos',
	'web_media_descr' => 'En las realidades modernas, casi todos usan Internet. Comenzando desde niños pequeños y terminando con jubilados. Alguien navega usando un navegador, otro mira videos en YouTube y alguien necesita la Red para comunicarse con sus seres queridos. Ninguno de estos usuarios puede imaginarse un día sin la World Wide Web.
Las personas mayores a menudo se sientan en una red social como Facebook u Odnoklassniki. También a menudo se comunican con sus hijos y nietos por Skype. Esto es especialmente conveniente si los niños y los padres viven en diferentes ciudades o incluso países.
Los jóvenes prefieren comunicarse a través de Viber o Telegram, subir fotos en Instagram, reírse de los memes de VK. Los videos de YouTube de las reacciones de las personas están ganando millones de visitas, al igual que varias bromas o experimentos sociales. En Tik-Tok, cientos de miles de personas bailan, muestran trucos de magia y se expresan.
¿Está interesado o simplemente utiliza algún tipo de recurso del ámbito de los medios web? ¿Quiere deshacerse de la aburrida flecha del mouse en su navegador? ¡Luego instale la extensión y cambie el cursor predeterminado a nuestra creatividad! Puede ser un cursor de YouTube, un cursor de Viber, un cursor de Google Chrome u otros recursos.',
	'web_media_short_descr' => 'Vive en un ritmo moderno con una colección de cursores de medios web',
	'web_media' => 'Web Media',
	'bobs_burgers_descr' => 'La serie animada Bob’s Burgers es la trama del trabajo de animación y el carisma de los personajes. Y, a juzgar por la nominación al Premio Emmy y el reconocimiento del trabajo como una de las mejores caricaturas en todo el mundo, Bob\'s Snack realmente causó sensación.
La trama de la serie animada gira en torno a la familia Bob Belcher. Esta persona es el dueño del restaurante en el primer piso, y en el segundo vive con sus seres queridos. Bob tiene una esposa alegre, Linda, y 3 hijos: Gene, Louise y Tina. El niño sueña con una carrera musical, la hija mayor, Tina, es muy amable, pero incómoda, y la más joven: Louise sigue siendo una descarada y a menudo pone a su familia en una posición incómoda. El principal competidor de las hamburguesas de Bob es la pizzería de Jimmy Pesto. Como puede suponer, el dueño de esta pizzería se llama Jim, y él y Bob se odian. Todo esto fue golpeado para que pareciera cómico, no en serio. Por lo tanto, muchas de sus escaramuzas solo causan una sonrisa.
Si te encanta la serie animada \"Bob\'s Burgers\" y quieres ver a sus personajes no solo en la pantalla del monitor o en la TV, instala la extensión, agrega una colección dedicada a \"Bob\'s Burgers\" y cambia el cursor del mouse en el navegador a cualquiera de los personajes de esta caricatura!',
	'bobs_burgers_short_descr' => 'Bob hace hamburguesas y nosotros hacemos los cursores de Bob\'s Burgers',
	'bobs_burgers' => 'Hamburguesas de Bob',
	'kirby_descr' => 'La historia del videojuego \"Kirby\" comenzó ya en los años 90 del siglo pasado. Consiste en muchas series que fueron desarrolladas por Nintendo y HAL Laboratory. El juego está destinado a niños de un año y medio a 8 años. Su popularidad se puede juzgar por la cantidad de copias vendidas. Más de 34 millones en todo el mundo.
El personaje principal de Kirby es la criatura rosa del mismo nombre. Vive en un planeta llamado Pop Star, y periódicamente lo protege de varios peligros. Kerby puede respirar algunos objetos y sus enemigos para luego aprender sus habilidades: combate cuerpo a cuerpo, posesión de una espada, respiración de fuego, etc. Sin embargo, el globo rosa no solo lucha con los enemigos, sino que también resuelve varios rompecabezas, viaja a otros países e incluso puede volar a nivel.
Puedes jugar este videojuego en las consolas Nintendo o Game Boy. En todas las series hay héroes lindos, buenos gráficos y bandas sonoras divertidas. Por cierto, durante casi 30 años desde el lanzamiento de la primera versión, el mundo logró ver 20 series de Kirby. Este indicador, junto con el volumen multimillonario de copias vendidas, ayudó al juego a estar en el TOP 50 de los videojuegos más exitosos y buscados en la industria del juego.
¿Ama a Kirby para que le guste ver a este personaje siempre que sea posible? ¡Luego usa la colección Kirby y convierte el puntero del mouse en el personaje principal de tu videojuego favorito! Estamos seguros de que le gustará la nueva apariencia del cursor.',
	'kirby_short_descr' => 'Intenta inhalar toda la colección de cursores Kirby',
	'kirby' => 'Kirby',
	'undertale_descr' => 'En la antigüedad, la Tierra estaba habitada no solo por personas, sino también por monstruos. Debido a los desacuerdos entre ellos, estalló una guerra, que terminó a favor de la raza humana. Siete magos condujeron a los monstruos bajo tierra y los encerraron allí para siempre con un hechizo de barrera. Sin embargo, solo había una entrada al Monte Ebott, que el niño aprovechó. Es para él que jugarás ejecutando el juego de computadora Undertale.
Este juego fue desarrollado por Toby Fox, un conocido programador de los Estados Unidos. Al principio, los propietarios de computadoras personales con sistema operativo Microsoft Windows y Linux podían disfrutarlo, y luego llegó el turno de los usuarios de consolas de juegos.
¿Cuál es el punto de este juego? El niño viaja a través del inframundo habitado por monstruos. Algunos de ellos son inmediatamente hostiles, mientras que a otros les gusta hablar. El jugador puede elegir uno de 2 comportamientos: evitar la violencia o luchar. En el primer caso, pasar el juego será más fácil, en el segundo, por el contrario, es más difícil. La trama y el final, que pueden ramificarse y cambiar, también dependen de esta elección.
Si te gusta Underground Tale y te gustaría ver sus personajes en tu navegador, instala la extensión y agrega la colección de cursores adecuada. ¡Convierte un puntero de ratón aburrido en uno de los monstruos o en el personaje principal de Undertale!',
	'undertale_short_descr' => 'Es hora de salir del agujero usando los cursores Undertale',
	'undertale' => 'Undertale',
	'deltarune_descr' => 'Deltarune es un juego de rol lanzado para computadoras hace un par de años. Fue creado por el mismo programador que desarrolló Undertale. Sin embargo, estos dos juegos casi no son similares entre sí, aunque tienen un par de personajes y ubicaciones comunes.
Hay varios personajes principales en Delta Rune. Este es un estudiante Chris, que puede ser controlado, y un encantador monstruo Susie, incontrolable. Ambos personajes caen en el mundo de la oscuridad, donde se encuentran con uno de sus habitantes: Ralsay. Él les dice que, de hecho, son criaturas ligeras que tienen una misión: detener el flujo de energía oscura en un mundo sombrío. Para hacer esto, necesitan evitar a los monstruos locales e intentar no participar en una batalla con ellos, aunque esto a veces es bastante difícil de hacer.
El jugador tiene una opción simple: ahorrar a las criaturas oscuras o atacarlas. Como Susie no es fanática de las medias tintas, en muchos casos elige una batalla. Por lo tanto, Chris no tiene más remedio que apoyar a su novia y ayudarla en las batallas.
Me encanta el juego Deltarune? ¡Luego estiliza el cursor del mouse en el navegador para uno de sus personajes! Puedes hacer esto con nuestra extensión. ¡Instálalo, agrega la colección \"Rune Delta\" y actívalo! Ahora tu flecha ha dejado de ser la misma que todos los demás, y se ha convertido en Chris, Susie o en una de las criaturas del mundo oscuro.',
	'deltarune_short_descr' => 'Sumérgete en el mundo oscuro con esta colección de cursores',
	'deltarune' => 'Deltarune',
	'super_mario_descr' => 'Super Mario es una serie de juegos de computadora lanzados por Nintendo. El primer y más popular juego se llamaba Super Mario Bros. Ella vio la luz en 1985. Más tarde fue incluido en el Libro Guinness de los Récords. Desde entonces, se han lanzado más de 20 juegos, cada uno de los cuales tiene su propia trama. En 2019, apareció una nueva versión llamada Super Mario Maker 2. A pesar de la mejora en los gráficos, el estilo y los personajes permanecieron igual, y esto evoca nostalgia por el Super Mario de los años 80.
El protagonista sigue siendo el fontanero Mario. En la trama de la última variación del juego, el castillo de la princesa no tenía una piedra sin remover. Mario debe reconstruirlo, habiendo ganado antes las monedas que se le pagan por las tareas. En total, este juego tiene más de 100 niveles de diversa complejidad con la posibilidad de modificación. También en Super Mario Maker 2 hay nuevos modos de juego. Puedes jugar cuatro de ellos a la vez y tan pronto como uno termine, el nivel se considera completado. También hay modos tales como: Mario Marathon, Duel y Ninjik.
¿Adoras a Super Mario y todo lo relacionado con este maravilloso juego? ¡Luego coloca los cursores hechos al estilo de este juego de plataformas! ¡Estamos seguros de que le gustará el cursor Mario, el cursor Luigi, el cursor Princess Peach y otros cursores que se presentan en nuestra colección!',
	'super_mario_short_descr' => 'Recorre el reino de los hongos con la colección de cursores de Super Mario',
	'super_mario' => 'Super Mario',
	'gravity_falls_descr' => 'Gravity Falls fue creado conjuntamente por Disney Television Animation Corporation y Alex Hirsch. El estreno se lanzó en 2012 y se mostró en Disney Channel. Toda la primera temporada de la serie animada giraba allí. Dos años más tarde, se lanzó la segunda temporada, que los espectadores podían ver en el canal anterior y en Disney XD. Desafortunadamente, los fanáticos de Gravity Falls no esperaron la tercera temporada y las siguientes. Los creadores decidieron limitarse a dos temporadas sin secuelas.
En cuanto a la trama de esta imagen animada, toda la acción tiene lugar en una ciudad ficticia llamada Gravity Falls. Allí vienen dos gemelas, cuyos nombres son Mabel y Dipper. Se están quedando con su primo Stan. Él tiene su propia tienda de souvenirs turísticos. Cuando los hermanos se aburren de \"no hacer nada\", van en busca de aventuras. Uno de ellos encuentra un extraño diario en el bosque, que cuenta sobre las anomalías de esta ciudad. Los gemelos partieron en busca de su autor y se encontraron con criaturas y lugares inusuales. Si estás interesado en esta serie animada y alguna vez fuiste fanático de sus personajes, ¡te recomendamos nuestra colección de cursores de mouse al estilo de Gravity Falls!',
	'gravity_falls_short_descr' => 'Emprende una aventura con los cursores de Gravity Falls',
	'gravity_falls' => 'Gravity Falls',
	'simpsons_descr' => 'Absolutamente todos escucharon sobre una serie animada tan famosa como Los Simpson. Incluso aquellas personas que nunca se han visto así son conscientes de la existencia de caracteres amarillos. Y los fanáticos están encantados cuando sale la próxima temporada de sus dibujos animados favoritos. Por cierto, en el otoño de 2019, se lanzaron 31 cuentas de temporada. Y el primero apareció en las pantallas de televisión en 1989. Fox comenzó a mostrarlo y aún continúa haciéndolo debido a las altas calificaciones y la simpatía de la audiencia.
Los Simpson es un género satírico que toca temas relevantes. Este puede ser el estilo de vida de los problemas estadounidenses, políticos y religiosos promedio, trucos \"estrellados\" de celebridades, feminismo, matrimonio entre personas del mismo sexo. En general, todo lo relacionado con eventos locales y globales en los que Estados Unidos participa.
La acción de la serie animada tiene lugar en la ciudad inexistente de Springfield. De hecho, hay muchas ciudades con ese nombre en Estados Unidos. Quizás por eso se eligió para que el público no asociara lo que estaba sucediendo en las pantallas con una localidad específica, sino que solo adivinó dónde podría estar esto.
Es muy probable que seas fanático de los Simpson. De lo contrario, ¿por qué leerías este texto hasta el final? Y si es así, tiene la oportunidad de cambiar el cursor aburrido del mouse a un puntero que se haga al estilo de esta serie animada.',
	'simpsons_short_descr' => 'Una pequeña familia divertida protagonizada por los cursores de Los Simpson',
	'simpsons' => 'Simpsons',
	'youtubers_descr' => 'La plataforma de videos de YouTube apareció en 2005. Al principio, los videos se publicaron allí solo por autoexpresión o para informar sobre algo. Sin embargo, con el tiempo, todo esto se convirtió en un negocio rentable, que brinda miles y, a veces, millones de dólares al mes a usuarios exitosos de YouTube. Cuanto más popular sea vloger (la persona que dirige el video blog), más puede ganar a través de su canal.
¿Cuánto gana una niña vloger de cinco años, cuyos padres la llevan a las atracciones más interesantes y filman lo que está sucediendo en la cámara? Es solo cómo un niño se divierte en los parques infantiles, que expresa emociones, cómo perder el tiempo y todo ese tipo de cosas. La cantidad es realmente sorprendente: hoy el canal del niño ha ganado casi 47 millones de suscriptores y comenzó a generar ingresos por un monto de 5 millones de rublos por mes.
Alguien sube videos donde habla sobre juegos de computadora, alguien hace beatboxing u organiza bromas para los transeúntes en la calle. Algunos dedican sus videos a temas delicados, como la relación entre hombres y mujeres. Cuantos más usuarios de YouTube les gusten estas tomas, mayor será la popularidad del vlogger.
La colección ya ha agregado el cursor PewDiePie, el cursor Shane Dawson, el cursor Ray William Johnson, el cursor Zoella, el cursor MyLifeAsEva y otros.',
	'youtubers_short_descr' => 'Una nueva generación de estrellas está siempre en línea en nuestra colección de YouTubers.',
	'youtubers' => 'YouTubers',
	'pusheen_descr' => 'Casi todos conocen al gato Pushin. Aunque solo es un personaje de un cómic infantil inventado hace 10 años, hoy tiene millones de admiradores. El gato Pusheen apareció como una ilustración creada por la artista Claire Belton.
Un año después, el gato adquirió su propia página en Tumblr.com y en unas pocas semanas ganó todo un ejército de admiradores, unas 10.000 personas. En 2013, Facebook estaba ansioso por incluir imágenes de Pushin en colecciones con otros emoticones. Después de negociaciones con el creador, esta idea se puso en práctica y \"explotó\" Internet. ¡Las imágenes del gato Pusheen se usan en correspondencia más de 10 millones de veces al día!
En 2014, uno de los mayores fabricantes de juguetes en los Estados Unidos dirigió su atención a este personaje. GUND (fue ella quien inventó los ositos de peluche) lanzó un par de modelos Pushin. Como el éxito fue enorme, después de unos meses se creó una colección completa de juguetes en forma de este gato.
¿Dónde más puedes conocer al gato Pusheen? ¡En juegos de regalo de Isaac Morris Ltd, en malvaviscos de Boomf y, por supuesto, en nuestra colección de cursores para gatos Pusheen!',
	'pusheen_short_descr' => 'Agregue un poco de comodidad en su navegador con la colección de cursor Pushin',
	'pusheen' => 'Pusheen',
	'rick_and_morty_descr' => 'La primera serie de obra animada \"Rick and Morty\" se lanzó en 2013. Esta caricatura se puede atribuir directamente a 2 géneros: ciencia ficción y comedia. Sus creadores fueron Dan Harmon y Justin Royland. Inicialmente, todas las series se mostraron en el canal Cartoon Network, y solo entonces se duplicaron en cines en línea y alojamiento de videos. Cada pocos años, se lanzan nuevas temporadas de Rick y Morty, y en noviembre de 2019 salió la cuarta temporada, que resultó ser no menos interesante que las anteriores. La trama de la serie animada gira en torno a un genio y, al mismo tiempo, a un científico loco llamado Rick, así como a su nieto, Morty. Estos dos personajes están conectados por aventuras conjuntas en los lugares más inusuales. Y llegan allí en un platillo volador, capaz de moverse a través de un túnel inter-espacial. Como habrás adivinado, esta serie animada es un poco como la película Regreso al futuro, pero aún así no es su versión animada. Sin embargo, fue alabado por muchos críticos por episodios humorísticos, creatividad y originalidad. ¿Quieres ver a Rick o Morty no solo en la serie de este trabajo, sino también en el navegador? Si es así, ¡instala la extensión y agrega nuestra colección dedicada a tus dibujos animados favoritos! Aquí está el cursor de Rick Sánchez, el cursor de Morty Smith, el cursor de Portal Gun y, por supuesto, el cursor del Sr. Meeseeks.',
	'rick_and_morty_short_descr' => 'Deja de gruñir, solo usa los cursores de la colección Rick and Morty',
	'rick_and_morty' => 'Rick y Morty',
	'mlb_teams_descr' => 'Los fanáticos del béisbol se pueden encontrar en cualquier parte del mundo. Esto es especialmente cierto para los residentes de países como: Estados Unidos, China, Cuba, Corea del Sur, Japón y Venezuela. Contrariamente a la creencia popular, el béisbol no se originó en Estados Unidos, sino en Inglaterra. La primera mención y descripción del béisbol apareció en la lejana 1744, en la edición en inglés. Después de 145 años, los estadounidenses se apropiaron de esta invención para sí mismos, a pesar de los hechos.
La Liga Nacional se formó en 1876. Ella es parte de la Major League en Canadá y Estados Unidos. Hoy, hay 15 equipos en la Liga Nacional de Béisbol. En la parte final de cada temporada, llega el momento de los playoffs, en el que participan los 4 mejores equipos. Entonces se revela el ganador de toda la Liga Nacional. Luego, el equipo ganador tiene la oportunidad de jugar contra el ganador de la Liga Americana en la Serie Mundial.
¿Estás interesado en el béisbol o incluso en la raíz de uno de los equipos? ¡Luego rinde homenaje a tu equipo favorito configurando los cursores del mouse en la forma de sus atributos! ¡Cambie el aspecto aburrido del puntero en el navegador a la identidad corporativa familiar del béisbol! Convierta la flecha en el bate o casco de un jugador en cualquiera de los equipos de la Liga Nacional, que ya incluyen el cursor de los New York Yankees, el cursor de los Great Falls Dodgers, el cursor de los Boston Red Sox, el cursor de los Baltimore Orioles y el cursor de los Oakland Athletics.',
	'mlb_teams_short_descr' => 'Colección de cursores de MLB Teams para todos nuestros fanáticos.',
	'mlb_teams' => 'Equipos de MLB',
	'brawl_stars_descr' => 'Brawl Stars es un juego móvil en el género MOBA de Supercell. A pesar del lanzamiento a finales de 2018, el juego ganó gran popularidad, en gran parte debido a la abundancia de modos de batalla y héroes coloridos y fantásticos: peleas. El jugador tiene mucho para elegir: 32 personajes únicos y cada uno de ellos tiene su propio conjunto de habilidades y destrezas. Cada héroe también tiene su propia habilidad pasiva, que está disponible a través de cofres de botín. Los jugadores pueden luchar en varios modos, por ejemplo, \"Recompensa por la captura\": gana uno de los dos equipos, que ha reunido más estrellas, matando oponentes. En el modo de \"robo\", es necesario romper las cajas fuertes de los oponentes, manteniendo las suyas. Un interesante modo \"Gem Grab\": el equipo se convierte en el ganador, el equipo que recoge la mayor cantidad de gemas gana. Bueno, en el modo \"Colisión\", 10 jugadores luchan entre sí en el mapa, donde las fronteras se reducen debido a una nube tóxica. El juego está repleto de un diseño colorido que gusta a muchas personas, incluidos nosotros, que nos inspiró a crear una colección separada de cursores Brawl Stars. Hay cursor Brawl Stars Shelley, cursor Barley, cursor Penny, cursor Frank, cursor Mortis y otros.',
	'brawl_stars_short_descr' => 'Elige los cursores de Brawl Stars y deja que comience la batalla',
	'brawl_stars' => 'Brawl Stars',
	'all_title' => '¡Cambie el cursor del mouse con dos clics! Colecciones gratuitas para todos los gustos.',
	'all_descr' => 'Si alguna vez pensó en cómo cambiar un cursor de mouse aburrido, ¡nuestras colecciones de cursor son para usted! Aquí encontrarás héroes geniales de cómics, hermosos cursores para jugadores con personajes de juegos populares, divertidos juegos de cursores para bromas prácticas, cursores de colores y muchas otras opciones interesantes.',
	'text_title' => 'Colecciones de cursor geniales y divertidas para todos los días',
	'text_1' => '¿No quieres ser como todos los demás? O simplemente amar todo lo inusual? ¿Quieres ser parte de tu héroe de juego favorito o personaje de dibujos animados? Entonces has venido a la dirección correcta. Aquí encontrarás conjuntos de cursores brillantes e inusuales que pueden reemplazar la flecha blanca familiar y ya bastante aburrida. El cursor del mouse nos acompaña todo el día en el trabajo y el estudio, por lo que debería dar un gran estado de ánimo y prepararse para lo positivo.',
	'text_2' => 'Aquí encontrarás cursores para jugadores y amantes del cine, hermosos cursores basados en tus dibujos animados favoritos y motivos deportivos para las personas más activas. ¿Te gustan los cómics o no puedes imaginar un solo día sin memes divertidos? ¿Adora a los animales o sueña con visitar todos los países del mundo? Todo es simple: también tenemos una imagen de cursor adecuada para usted. También puede seleccionar imágenes dependiendo de con qué esté trabajando. Por ejemplo, un cursor negro será mucho más conveniente que el blanco cuando trabaje con documentos o dibujos, y un cursor de mano será más conveniente si tiene que trabajar con pequeños elementos gráficos. Elija su imagen favorita, ajuste su tamaño directamente en la extensión y úsela con placer, ¡todos los días comenzando con una nota positiva!',
	'test_zone' => 'ÁREA DE PRUEBA',
	'install_to_preview' => 'Instale la extensión para obtener una vista previa',
	'install' => 'Instalar',
	'add_button' => 'Añadir',
	'preview_button' => 'Avance',
	'added_button' => 'Adicional',
	'add_cursor' => 'Agregar cursor',
	'to_your_collection' => 'a la colección',
	'prev_text_1' => 'Vista previa de pantalla completa',
	'prev_text_2' => 'cursor',
	'cursor' => 'cursor',
	'pointer' => 'puntero',
	'a_title_1' => 'Cursor Style - Cursores geniales para tu navegador',
	'a_title_2' => 'Colecciones geniales de cursores temáticos',
	'mouse_cursors' => 'cursores del mouse',
	'cursor_collection' => 'Colección cursores',
	'sborka_cursorov' => 'colección de cursor',
	'collection_list_from_colllection' => 'Listado de cursores - ',
	'christmas' => 'Navidad',
	'nhl_teams' => 'National Hockey League',
	'neon' => 'Neon',
	'adventure_time' => 'Hora de aventura',
	'nba_teams' => 'National Basketball Association',
	'spongebob' => 'Bob Esponja',
	'phineas_and_ferb' => 'Phineas and Ferb',
	'fortnite_chapter_2' => 'Fortnite Chapter 2',
	'pokemon' => 'Pokemon',
	'famous_people' => 'Celebridades',
	'the_elder_scrools' => 'The Elder Scrolls',
	'halloween' => 'Halloween',
	'nfl_teams' => 'Liga Nacional de Fútbol',
	'five_nights_at_freddy' => 'Cinco Noches en Freddy\'s',
	'komiksy' => 'Historietas',
	'igry' => 'Juegos',
	'multfilmy' => 'Dibujos animados',
	'kino_i_serialy' => 'Películas',
	'anime' => 'Anime',
	'futbol' => 'Fútbol',
	'avtomobili' => 'Coches',
	'memy' => 'Memes',
	'emodji' => 'Emoji',
	'pitomcy' => 'Mascotas',
	'stil_i_krasota' => 'Moda y estilo',
	'prazdniki' => 'Días festivos',
	'flagi' => 'Banderas',
	'vokrug_sveta' => 'Alrededor del mundo',
	'eda_i_napitki' => 'Alimentos y bebidas',
	'cvetnye' => 'De colores',
	'prank' => 'Bromas',
	'startovyj_nabor' => 'Kit de inicio',
	'fortnite' => 'Fortnite',
	'dota_2' => 'DOTA 2',
	'minecraft' => 'Minecraft',
	'christmas_short_descr' => 'Santa amará tus cursores navideños',
	'nhl_teams_short_descr' => 'Una colección de cursores NHL para verdaderos fanáticos.',
	'neon_short_descr' => 'Agrega brillo con una colección de neón',
	'adventure_time_short_descr' => 'Aprendiendo Matemáticas con Hora de aventura colección cursores',
	'nba_teams_short_descr' => 'Cursores de la NBA como símbolo de grandes victorias de baloncesto',
	'spongebob_short_descr' => 'Descubre quién vive en el fondo del océano con la colección de cursores de Bob Esponja',
	'phineas_and_ferb_short_descr' => 'Definitivamente no te aburrirás con la colección de cursores de Phineas y Ferb',
	'fortnite_chapter_2_short_descr' => 'El nuevo capítulo del juego de culto Fortnite',
	'pokemon_short_descr' => 'Atrápalos a todos si puedes',
	'famous_people_short_descr' => 'Inspira tu cursor de ídolo',
	'the_elder_scrools_short_descr' => 'Sumérgete en el mundo de los caballeros y dragones',
	'halloween_short_descr' => 'Tenga miedo de perderse la nueva colección de Halloween',
	'nfl_teams_short_descr' => 'Para verdaderos fanáticos del fútbol',
	'five_nights_at_freddy_short_descr' => 'Intenta no asustarte de estos animatronics',
	'komiksy_short_descr' => 'Cursores de cómic: elige tu estado de ánimo hoy.',
	'igry_short_descr' => 'Realidad virtual: ¿a quién juegas hoy?',
	'multfilmy_short_descr' => 'Personajes de dibujos animados favoritos en un nuevo diseño',
	'kino_i_serialy_short_descr' => 'El señor del cursor: la hermandad del escritorio',
	'anime_short_descr' => 'Todo el mundo ama el anime: ¿quién es tu personaje favorito?',
	'futbol_short_descr' => '¿Eres un verdadero fanático de los deportes? Entonces necesitas estar aquí',
	'avtomobili_short_descr' => 'El auto de tus sueños: una gran flota para profesionales',
	'memy_short_descr' => 'Motivos favoritos: colección de cursores de Memes',
	'emodji_short_descr' => 'Muestre su estado de ánimo real a los demás: ¡configure Cursoji!',
	'pitomcy_short_descr' => 'Cursores brillantes para todos los amantes de nuestros hermanos menores.',
	'stil_i_krasota_short_descr' => 'Cursores originales para todas las ocasiones.',
	'prazdniki_short_descr' => '¿Qué hay en el calendario? ¡Nueva colección de cursores de vacaciones!',
	'flagi_short_descr' => 'Buscando aventura: ¿a dónde vamos hoy?',
	'vokrug_sveta_short_descr' => 'La vuelta al mundo en un instante: ¿a dónde vamos hoy?',
	'eda_i_napitki_short_descr' => 'Cursores deliciosos para la creatividad',
	'cvetnye_short_descr' => 'Pinta tu vida con colores brillantes y trazos atrevidos',
	'prank_short_descr' => 'Un conjunto de cursores para las bromas más divertidas.',
	'startovyj_nabor_short_descr' => 'Una nueva mirada a las cosas familiares: una serie actualizada de cursores',
	'fortnite_short_descr' => '¡Sigue a los streamers!',
	'dota_2_short_descr' => '¡Haz que tu mundo virtual sea real!',
	'minecraft_short_descr' => 'Los personajes de tu juego favorito siempre están cerca',
	'christmas_descr' => 'Sin duda, cada uno de nosotros está esperando las vacaciones más populares: la Navidad. Todos los cristianos del mundo tradicionalmente lo celebran cada año, el 25 de diciembre. Un momento en que las familias se reúnen en la misma mesa, comparten su alegría y amor e intercambian regalos. Mucho antes de Navidad, la gente decora las calles con guirnaldas brillantes y sus hogares con atributos tradicionales. Es difícil encontrar a una persona que no le guste la Navidad, unas vacaciones divertidas y misteriosas, porque está acompañado de muchas tradiciones y rituales, nos devuelven a las raíces de toda nuestra familia. En la víspera de Navidad, literalmente todo está saturado de espíritu, desde pan de jengibre pintado hasta cantos conmovedores. Un árbol elegante y regalos debajo de él, una alegría familiar para cada uno de nosotros desde la infancia. Queremos unirnos a estas vacaciones mágicas y, quién sabe, quizás Santa te prepare un regalo especial si decoras tu cursor con nuestra colección de Navidad. Hay todo lo que necesita para esto, el cursor de Santa Claus, el cursor del árbol de Navidad, el cursor de pan de jengibre, el cursor del muñeco de nieve e incluso el cursor de la bolsa de regalo. Feliz navidad',
	'nhl_teams_descr' => 'La Liga Nacional de Hockey se formó en 1917: es una organización deportiva profesional que reúne a clubes de hockey de EE. UU. Y Canadá. Y esta es una de las primeras ligas profesionales de hockey del mundo. La NHL es una de las principales ligas deportivas de América del Norte, junto con la NFL, la NBA, las Grandes Ligas y la MLS. Cada año, 31 equipos de 30 ciudades de EE. UU. Y Canadá luchan por el trofeo principal: la Copa Stanley, y el equipo que anotó la mayor cantidad de puntos en la temporada regular recibe la Copa Presidencial. Es hora de honrar este gran juego creando una colección de cursores NHL. Si también le gusta el hockey, anime a su club favorito o participe en este deporte usted mismo, simplemente cambie el cursor y no se separe de su equipo favorito, incluido el cursor Boston Bruins, el cursor St. Louis Blues, el cursor Columbus Blue Jackets, el cursor Tampa Bay Lightning, Dallas Stars cursor y otros clubes dignos de sincero respeto.',
	'neon_descr' => 'Hemos creado una colección única de cursores de neón para agregar variedad a la navegación diaria por Internet y agregar un poco de brillo a las fascinantes luces de neón. Deje que sus colores intensos creen la atmósfera envolvente de la ciudad por la noche, inspírese para crear algo nuevo. En el mundo moderno, las luces de una metrópoli siempre anuncian el inicio de la noche, nos siguen en cada calle y este resplandor está lleno de energía. Deje que también le siga un cursor brillante de helado, un delicioso cursor de hot dog, un jugoso cursor de hamburguesa, un brillante cursor de diamante y otros cursores de la nueva colección de neón.',
	'adventure_time_descr' => '\"Hora de aventura\" es una caricatura de un género fantástico en el que la acción tiene lugar en un mundo que ha sobrevivido al apocalipsis. Este territorio se llama Land Ooo, que hasta hace poco era una guerra nuclear. Pero todo esto ya está en el pasado, sin embargo, todas las personas sobrevivientes estaban sujetas a mutaciones, y el mundo estaba lleno de magia. Los personajes principales de la serie animada son Finn, un niño de 14 años y su amigo un perro llamado Jake. El niño y el perro son muy aficionados a la aventura, ayudan constantemente a todos los que están en problemas. Los amigos viven en un árbol y pasan todo el tiempo juntos. Si quieres sumergirte en un mundo de aventuras con otros admiradores, grita \"Matemáticas\". Aquí están tanto el cursor de Finn Boy como el cursor de Jake, así como el cursor de chicle Princess. Por supuesto, no nos olvidamos del cursor Bimo, el cursor del Rey Hielo y otros.',
	'nba_teams_descr' => 'Si el baloncesto es tu juego favorito para ti, como lo es para nosotros, entonces lo que necesitas es una colección de cursores dedicados a los equipos de la NBA. La NBA es una de las principales asociaciones deportivas del continente norteamericano. Cuando creamos esta colección, nos atormentó la elección, qué equipo elegir, porque hay treinta de ellos en la NBA. Pero hay equipos que son leyendas. Esto y los Chicago Bulls establecieron un récord de victorias a mediados de los 90. Estos son los Golden State Warriors, que reunieron a los mejores jugadores de la liga hace un par de años. O, por ejemplo, los Lakers, los Celtics también son equipos increíblemente geniales. Si usted, como nosotros, espera con ansias los partidos de sus equipos de baloncesto favoritos y desea mostrar su apoyo al equipo o los jugadores, descargue nuestra colección de cursores de la NBA.',
	'spongebob_descr' => 'La serie animada SpongeBob SquarePants es conocida por muchas personas. Fue un éxito abrumador después de que Nickelodeon en 1999 decidiera crear una serie animada basada en la tira cómica educativa Tide Zone, y se convirtió en una franquicia muy lucrativa. El creador de la serie es un ex empleado del laboratorio oceanológico, por lo que casi todos los personajes de la serie animada son habitantes divertidos del fondo marino, con sus propias características y carisma. La acción gira en torno a la receta secreta de Krabsburger que solo el personaje principal puede cocinar: Bob Esponja. Y los otros habitantes del día del mar están tratando de obtenerlo, incluido el principal antihéroe Sheldon Plankton, que no lo consigue todo el tiempo. En la colección de cursores de Bob Esponja, hemos reunido los cursores de todos los personajes y eventos notables de la serie. Por ejemplo, el cursor del Sr. Cangrejo con el dólar, el cursor de Patrick Star, Calamardo con su clarinete, el cursor de la medusa, el cursor de Bob Esponja y muchos otros personajes.',
	'phineas_and_ferb_descr' => 'En la ciudad estadounidense ficticia de Denville, de la inexistente Trishtatya, viven dos niños interesantes. Todos los días de sus vacaciones se convierten en aventuras increíbles, porque pueden hacer una montaña rusa del tamaño de una ciudad entera o un portal real a otro planeta. Comparten su increíble entretenimiento con amigos. Al mismo tiempo, mientras los niños se divierten, el científico malvado Heinz Fufelschmertz está construyendo otra máquina malvada que crea caos, con el nombre que termina en \"-inator\", con la ayuda de la cual quiere vengar sus quejas infantiles o apoderarse de ellos. poder en Trishtat, pero Perry lo está obstaculizando: Utkonos, el \"Agente Pi\" secreto, trabajando bajo la apariencia de una mascota de niños. La popularidad de esta serie animada, tanto entre niños como entre adultos, nos inspiró a crear una colección de cursores Phineas y Ferb para que pueda cambiar el cursor del mouse sobre los personajes de la serie. Entre ellos se encuentran el cursor Phineas Flynn, el cursor Dr. Heinz Fufelschmertz, el cursor Ferb Fletcher, el cursor Candace Gertrude Flynn y el cursor de pico de pato Perry.',
	'fortnite_chapter_2_descr' => 'El segundo capítulo de Fortnite llegó después de un gran evento: The End, que arrastró todo lo que los jugadores en el juego amaron a un agujero negro. Fortnite Capítulo 2 ahora tiene un nuevo mapa, que a primera vista es aún más salvaje que el mapa original, ¡así como muchos cambios en la mecánica del juego y, por supuesto, mucho contenido nuevo! Vehículos, emociones, mecánica de natación y mucho más: todo esto en imágenes frescas e interesantes, todo lo que amas y aprecias en este juego de culto. Sumérgete en un mundo nuevo: elige un lugar de aterrizaje y explora una isla completamente nueva con 13 ubicaciones. Natación, pesca, lanchas a motor: este es un nuevo juego de agua. Más diversión y menos esfuerzo: actualiza un capítulo 2 completamente nuevo y no olvides cambiar el cursor a nuevos diseños y armas. ¡Ya está esperando las máscaras actualizadas Cursor turco, Riptide cursor, Rippley cursor, Remedy cursor, Toxin cursor, 8-Ball cursor, Fusion cursor y otros!',
	'pokemon_descr' => 'La palabra \"pokemon\" significa una criatura con poderes sobrenaturales. Tienen inteligencia, y algunos incluso pueden hablar. Actualmente, ya hay 802 variedades de Pokémon. En el universo Pokémon inventado, las personas se llaman entrenadores Pokémon, a quienes entrenan para batallas con otros entrenadores Pokémon. Y cuanto más experimentado y fuerte es el entrenador, más respeto disfruta. Afortunadamente, debe tenerse en cuenta que las peleas de Pokémon nunca terminan en la muerte de estas criaturas únicas. Todos los Pokémon tienen diferentes habilidades y difieren en el tipo de elemento, y su resistencia a diferentes ataques depende en gran medida de esto, y algunas criaturas tienen la habilidad de dos elementos a la vez. Después de ganar la batalla, el Pokémon obtiene una valiosa experiencia, que es necesaria para aumentar el nivel y, en consecuencia, sus características. Hoy, el universo Pokémon es una gran franquicia de medios y decidiremos preparar una colección de cursores con algunos Pokémon populares. Entre ellos, el más famoso es el cursor Pikachu, así como el cursor Rattata, el cursor Squirt, el cursor Bulbasaur y el cursor Charmander. Esta lista se actualizará, porque hay muchos de ellos y cada uno de ellos es único a su manera.',
	'famous_people_descr' => 'Entre las muchas personas famosas, cada uno de nosotros encuentra un modelo a seguir o simplemente admira el genio, el talento y la perseverancia de estas celebridades. Hemos preparado una colección de cursores de celebridades para inspirarte y recordarte los grandes logros que cada uno de ustedes puede aumentar. No todas las personalidades famosas tuvieron un destino feliz, pero nos enseñan lo más importante que nunca debe retirarse de su objetivo preciado, a pesar de las dificultades y los problemas. Después de todo, este es el principio principal para lograr el éxito: ir a su sueño todos los días y, finalmente, convertirse en el mejor en su campo. ¡Quizás hoy solo quiera cambiar el cursor del mouse, y mañana toda su vida cambiará para mejor! La colección se actualizará constantemente con nuevos y dignos representantes de la humanidad. Entre ellos, por supuesto, científicos, políticos, atletas, representantes del arte y muchos otros. El cursor George Washington, el cursor, Michael Jordan, el cursor Stephen King, el cursor Elvis Presley y el cursor Marilyn Monroe son solo el comienzo',
	'the_elder_scrools_descr' => 'The Elder Scrolls es una serie de juegos de rol de computadora, unidos por un universo común y meticulosamente diseñado, que proporciona al jugador una enorme libertad de elección, lo que le permite visitar diferentes áreas y ciudades del mundo de fantasía y fantasía y explorar nuevos lugares y misiones por su cuenta. El trabajo en la serie comenzó en 1992 y, a lo largo de los años, el juego reunió a una gran comunidad de jugadores. Por lo tanto, por demanda popular, hemos lanzado una colección de cursores The Elder Scrolls, para que puedas sumergirte en la atmósfera única del juego. La eterna batalla de caballeros y dragones, ¿de qué lado estás? Cambia el cursor a un dragón y únete al ejército de monstruos que escupen fuego o lucha noblemente al lado de las personas eligiendo el cursor de espada y la imagen de tu personaje favorito: ¡la decisión es tuya! Lo principal es que con nuestra nueva colección, estás listo para cualquier batalla.',
	'halloween_descr' => 'Esperando una noche mística en la víspera del Día de Todos los Santos. La historia de Halloween se remonta a más de dos mil años. Quizás esta es la fiesta más extraña que combina diversión y miedo, nativa de la cultura celta. Luego la gente quemaba hogueras y se ponía disfraces de miedo para alejar a los fantasmas. La palabra \"Halloween\" se mencionó por primera vez en el siglo XVI como una abreviatura escocesa de la frase inglesa All-Hallows-Even. El Papa Gregorio III declaró el 1 de noviembre el Día de Todos los Santos, y la noche anterior se conoció como la Víspera de Todos los Santos, y más tarde Halloween. En este día, la gente usa disfraces de hombres lobo, fantasmas y otros monstruos y van a las casas vecinas, ofreciendo comprar dulces. Fiestas temáticas, fuegos artificiales, linternas lindas, calabazas y acrobacias crean una atmósfera única. También queremos celebrar esta terrible fiesta con accesorios, cursores y personajes de Halloween. En nuestra colección puedes encontrar: cursor zombie, cursor fantasma, cursor de gato negro, cursor de calabaza y mucho más. Cambiar tu estado de ánimo ahora es tan fácil como cambiar el cursor con nuestra nueva colección de Halloween.',
	'nfl_teams_descr' => '¿Qué podría ser mejor para un verdadero fanático del fútbol americano que un cursor del mouse en forma de simbolismo del equipo del que es fanático? En la moderna Liga Nacional de Fútbol, ​​treinta y dos equipos juegan, divididos entre las Conferencias de Fútbol Nacional y Americana (National Football Conference, NFC y American Football Conference, AFC). A su vez, cada una de las conferencias se divide en cuatro divisiones: Este, Norte, Sur y Oeste. La temporada de la NFL consiste en juegos de pretemporada, una temporada regular y una serie de playoffs. El partido final de la temporada de la NFL se llama Super Bowl y es esencialmente el evento deportivo más popular en los Estados Unidos. Este es un juego favorito para millones de fanáticos y, por lo tanto, hemos creado una colección de cursores de la NFL para que no se separe de los símbolos de su equipo favorito. Ya sean New England Patriots, New York Giants, Buffalo Bills u otro equipo, siempre estén en la misma onda que sus ídolos, utilizando nuestros cursores en forma de logotipo y casco del equipo. La colección se actualizará constantemente para que todos puedan cambiar el cursor a la imagen de su equipo favorito.',
	'five_nights_at_freddy_descr' => 'El juego verdaderamente único Cinco noches en Freddy\'s ganó rápidamente una gran popularidad y esto no es sorprendente, porque su trama simple y al mismo tiempo fascinante puede mantener a los jugadores en las pantallas durante horas. Diseñamos los cursores de Cinco noches en Freddy\'s a pedido de los fanáticos del juego y estuvimos muy contentos de encarnar personajes tan interesantes y divertidos. Pero a diferencia del juego, nada lo amenaza con nuestros cursores, así que siéntase libre de elegir sus animatronics favoritos, ya sea Bear Freddy o Rabbit Bonnie u otros. Lo principal es que ahora el juego cobra vida en tu navegador y da nuevas emociones. Garantizamos que no hay fantasmas en nuestros cursores, pero transmiten perfectamente el espíritu de un juego que inspira miedo debido a las complejidades del diseño y los elementos de la trama. Pero, ¿qué pasa si haces que el tamaño del cursor sea muy grande? ¿Puedes mantener la calma y no tener miedo?',
	'komiksy_descr' => 'Parece que el cursor del mouse es un poco, pero a menudo son esos detalles los que pueden mejorar su estado de ánimo, despertarse en la mañana gris o simplemente dar emociones brillantes. Una colección de cursores de cómics diseñados específicamente para todos los amantes de los superhéroes. Aquí puedes encontrar absolutamente todos los Marvel Universe y DC Comics, desde Iron Man hasta Thanos, Spider-Man y Hulk. El estilo del cursor puede ser en forma de superhéroe o en forma de su personaje. Un cursor no es solo un elemento funcional; Es importante en un sentido profesional. Por ejemplo, si graba un video desde la pantalla, será mejor ver una imagen brillante y original, y se verá mucho más interesante. Y, por supuesto, ¿quién no querría usar el guante del infinito en la vida real? Cambiar el cursor del mouse es simple: simplemente descargue la extensión a su navegador y agregue el cursor que desee a su configuración a través de él. Puede elegir un cursor según su estado de ánimo al menos todos los días. Basta de días grises: ¡conviértete en un superhéroe ahora mismo!',
	'igry_descr' => 'Los juegos de computadora se han convertido en una parte integral de nuestras vidas. Con su ayuda, puedes sumergirte en un mundo nuevo, participar en aventuras y convertirte en una persona completamente diferente. Todos tienen su propio juguete favorito, cuyos personajes ya se han convertido casi en familia. Un conjunto de cursores basados en juegos de computadora conocidos es una oportunidad para diluir la aburrida vida cotidiana y agregar un poco de creatividad, brillo y diversión al flujo de trabajo. El conjunto contiene imágenes de los héroes del juego y personajes auxiliares, armas e íconos del juego. Elija lo que se adapte a su estado de ánimo: los cursores del juego atraerán no solo a los jugadores, sino también a todos los que simplemente están cansados de la vida cotidiana gris. Simplemente descargue el conjunto, cambie el cursor del mouse y listo para completar tareas de búsqueda, destruir enemigos y alcanzar sus objetivos.',
	'multfilmy_descr' => 'Dentro de cada adulto todavía hay un niño que ama los dibujos animados y que todavía sueña con convertirse en uno de los héroes. Le ayudaremos a hacer realidad sus sueños: use la nueva colección de cursores basada en los dibujos animados más famosos y favoritos. Tom y Jerry, Buzz Lightyear y Shrek, Gravity Falls e incluso Pokémon: puedes convertirte en lo que quieres todos los días. Seleccione el cursor del mouse según su estado de ánimo. Quien eres hoy Minion imprudente y alegre que resuelve fácilmente cualquier problema o un Raphael fuerte y valiente, cuyo objetivo no es solo lograr hazañas, sino también comer pizza. ¿Quizás eres el genio todopoderoso que tiene una oficina entera bajo su mando? En la colección hay héroes para todos, desde princesas hasta dragones, solo queda decidir quién refleja el estado de ánimo de hoy. El estilo del cursor no es solo una imagen brillante. Esto es un reflejo de la individualidad, la autoexpresión y simplemente: diversión, alegría y positivo para todo el día. ¿Es aburrido trabajar o demasiado vago para estudiar? ¿Se ha vuelto triste y no es feliz? Cambia el cursor y el mundo brillará con nuevos colores.',
	'kino_i_serialy_descr' => 'Películas: son magia, misticismo y una excelente manera de relajarse, divertirse y experimentar emociones vívidas. Al mismo tiempo, después de mirar, aún recordamos a los héroes favoritos a quienes realmente quiero conocer en realidad. Ahora es posible: simplemente descargue la nueva colección de cursores basada en películas y programas de televisión famosos. Los cursores brillantes y geniales serán una gran adición al escritorio, convertirán la aburrida vida cotidiana gris en vacaciones y las tareas banales, en una aventura emocionante. Cambia el cursor del héroe todos los días, por estado de ánimo, tareas o al azar. ¿Quién serás hoy? ¿El honesto y justo John Snow o el audaz e implacable John Wick? ¿Quizás tienes una misión difícil por delante y solo Frodo puede completarla? ¿Quizás hoy eres solo un extraterrestre que no quiere hacer contacto con otros? Elija un cursor adecuado: levante el ánimo y, al mismo tiempo, muestre a los demás lo que piensa y cómo planea pasar el día. Pruébalo, no solo es divertido, sino también adictivo, definitivamente no querrás volver a la flecha habitual.',
	'anime_descr' => 'El anime es un estilo único de animación que, a pesar de su marcada etnia, ha sido disfrutado por millones de personas en todo el mundo. Es poco probable que haya al menos una persona que no haya visto dibujos animados en este estilo. Creamos los mejores cursores de estilo anime que todos los fanáticos de este estilo adorarán. Los cursores estándar son aburridos y cursis. Muestre su personalidad: use la colección de cursores de Anime con sus personajes favoritos. Elige el cursor de una espada oscura si sueñas con aventuras y batallas valientes. El lindo y gordo Totoro te animará incluso en los días más tristes, y Naruto te motivará en las aventuras y les mostrará a todos a tu alrededor que eres genial. Los cursores brillantes alegrarán la jornada laboral o harán que el proceso de aprendizaje sea más interesante y agradable. No se limite: use sus motivos favoritos incluso en elementos tan pequeños como el cursor del mouse. Cambie los cursores todos los días, ajústelos a su estado de ánimo y muestre su personalidad: con los cursores de estilo anime es así de simple.',
	'futbol_descr' => 'El fútbol es un deporte especial que incluye elementos de lucha, atletismo, precisión. En general, es espectacular, despiadado y reúne a millones de fanáticos en todo el mundo. ¿Te gusta el fútbol o simplemente te gustan los deportes? Luego descargue un juego de cursores al estilo del juego mundialmente famoso y demuestre el título de un fanático leal. La colección contiene 24 opciones para diseñar cursores, en la forma de los equipos más populares que merecen sus títulos como un juego desesperado y persistente. Los cursores se realizan en dos versiones: en forma de triángulo estándar, decorados con los colores del equipo o en forma de casco de juego correspondiente. El cursor estándar del navegador es aburrido y no merece un verdadero fanático de los deportes. Conviértete en original y único con nuestra colección. Descargue imágenes y elija los colores de su equipo favorito o cursores personalizados, si simplemente ama los deportes y anima a todos. Seguir tus pasatiempos es muy simple: no tienes que venir a trabajar con una bufanda o gorra de tu equipo favorito, es rápido y fácil cambiar el cursor a una imagen brillante y elegante.',
	'avtomobili_descr' => '¿Te gustan los coches y disfrutas mirando modelos de diferentes fabricantes? ¿O has estado soñando con una marca en particular durante mucho tiempo, pero aún no tienes la oportunidad de comprarla? Especialmente para usted, hemos creado un brillante conjunto de cursores \"Supercars\". Aquí encontrarás el clásico Ford y el elegante Bentley, el brillante Lamborghini y el exclusivo Ferrari. ¿Quieres ser el dueño del auto original? Es simple: descargue nuestra colección de cursores en su dispositivo y cambie la imagen del automóvil al menos todos los días. Los cursores están diseñados en dos versiones: como un automóvil completo o como su signo. Elija lo que más le guste o cómo prefiera trabajar. Dichas imágenes se verán geniales como cursores del juego o simplemente como un elemento inusual del escritorio. Ser brillante es simple: no es necesario hacer cosas inimaginables para esto o cambiar su apariencia. Es suficiente dejar de usar objetos comunes y elegir lo que realmente te gusta. La colección de cursores \"Cars\" es la elección para aquellos que no tienen miedo de demostrar su valía.',
	'memy_descr' => 'Los memes han sido una parte familiar de nuestras vidas. ¿Y a quién de nosotros no le gustan estas imágenes amplias, interesantes y originales para fastidiar el día? Muchos héroes de los memes se han vuelto no solo populares: han adquirido el estatus de favoritos populares, y las frases y expresiones se han incluido durante mucho tiempo en el discurso coloquial como turnos bien establecidos. Presentamos una colección de los mejores cursores basados ​​en los memes más populares. Con su ayuda, no solo puede mostrar su personalidad, sino también expresar su estado de ánimo. ¿Estás cansado y cansado de todo? Elija un gato enojado que, con toda su apariencia, expresa indignación y hostilidad hacia todo lo que lo rodea. ¿O brillas con sarcasmo hoy y no te importa reír? Entonces Drake Bling será un excelente acompañamiento: te animará y hará que cualquier tarea sea original e interesante. Instale la extensión, descargue nuestra colección y elija un estilo de cursor para cada día. No es difícil ser brillante y original: cambie el diseño estándar del icono a uno de los héroes de los memes y obtenga un impulso de energía para todo el día.',
	'emodji_descr' => 'Emoji: iconos brillantes y geniales, sin los cuales ya no podemos comunicarnos habitualmente. Con su ayuda, no es necesario que describa su estado de ánimo con palabras: simplemente seleccione el icono deseado y el interlocutor lo entenderá sin más preámbulos. En nuestro nuevo conjunto de cursores, encarnamos la idea de emoji, así es como apareció Cursoji divertido e inusual que coloreará el mundo y hará la vida más interesante. Con la ayuda de los cursos, no solo puede trabajar y realizar tareas familiares, sino también mostrarles a sus colegas, amigos y simplemente a otros su estado de ánimo. Un cursor adormecido es perfecto para el lunes por la mañana, y un cursor que llora expresará una actitud sobre responsabilidades adicionales. Un cursor fresco con gafas es la mejor opción antes de las vacaciones, y un cursor con dinero en los ojos es una buena razón para insinuar al jefe sobre el aumento de los salarios. Usar Cursoji es divertido e interesante, ya sea trabajo, estudio o presentación. En el último caso, incluso se recomienda hacer esto si los colegas tienen sentido del humor o simplemente necesitan calmar la situación. En general, para cualquier tarea, ¡simplemente elija el curso correcto!',
	'pitomcy_descr' => 'Te gustan los animales Seguramente, son tan lindos, divertidos y muy divertidos. ¿Por qué no pasar todo el día acompañado de los mejores amigos de una persona? Descarga la colección de cursores Pets para ti y elige un amigo para ti todos los días. El ícono del cursor puede ser lindo, como una alpaca de buen carácter, o elegante, como un flamenco rosado. ¿O tal vez estarás ocupado todo el día y elegirás un unicornio leyendo un periódico, o simplemente no quieres comunicarte con nadie, como un malvado gato negro? Para cualquier estado de ánimo, tenemos un animal correspondiente. Un pug alegre te animará incluso en el día más aburrido y gris, y el cursor rosa en forma de unicornio mostrará a todos que no estás desprovisto de un sentido de belleza, incluso si eres un hombre barbudo brutal. ¿Qué pasa si no hay ánimo y no tengo ganas de hacer tareas de rutina? La receta es simple: descargue la colección Mascotas, cambie el cursor del mouse, y listo, el sol vuelve a brillar, el clima está bien y el estado de ánimo está al más alto nivel. ¡No es de extrañar que digan que los animales ayudan a combatir la depresión y la tristeza!',
	'stil_i_krasota_descr' => 'En la nueva colección de cursores, hemos reunido una amplia variedad de temas que nos causan emociones agradables y elevadoras. Este conjunto de cursores se llama \"Estilo y belleza\", porque son sus cosas favoritas las que determinan nuestra vida cotidiana, nos dan alegría y nos motivan a hacer cosas importantes, despertar el deseo de mejorar. ¿Estás interesado en el espacio y sueñas con ir a otros planetas? Elija un cursor de la NASA o un plato de extraterrestres: acérquese a su sueño. Si no puedes imaginar la vida sin música o eres un rockero empedernido, entonces el cursor al estilo de una guitarra eléctrica es para ti. El cursor de pincel, regla y brújula ha sido especialmente desarrollado para ingenieros: estas imágenes ayudarán a convertir los aburridos cálculos y dibujos en soluciones originales. Una varita mágica y zapatillas de deporte, una patineta y lápiz labial, el sol y los conos químicos: elija lo que se adapte a su estilo de vida, sus deseos y aspiraciones, y las tareas ordinarias se volverán más interesantes y los días de trabajo se pintarán en colores nuevos y brillantes.',
	'prazdniki_descr' => '¿Te gustan las vacaciones? Pero a quién no le gustan: amigos, regalos, nuevamente el mismo fin de semana. Para que la espera de las vacaciones sea más agradable, más corta y más cálida, no solo puede contar los días en el calendario, sino también establecer el icono correspondiente como el cursor del mouse. Comencemos con el Año Nuevo: elegiremos un árbol de Navidad, un regalo o Santa Claus, para que las vacaciones sean brillantes y alegres. Tal vez el hombre de pan de jengibre esté más cerca: ¿divertido, lindo y siempre alegre? Con él ciertamente no habrá tiempo para estar triste y aburrido. Continuamos celebrando con cupidos y corazones alegres, y el conejo de Pascua no está lejos. En algún momento de las vacaciones, habrá un cumpleaños, que será aún más agradable esperar con globos en lugar de la flecha del cursor estándar. Y en Halloween, puede sorprender a sus colegas y a quienes lo rodean con un cursor de mouse inusual en forma de una calabaza ominosa o un fantasma. Un conjunto de cursores para las vacaciones es una oportunidad para alegrar las expectativas, sintonizar con anticipación la próxima diversión y mantener un excelente estado de ánimo no solo en la víspera de la celebración, sino durante todo el año.',
	'flagi_descr' => 'La bandera es un símbolo único que se usa ampliamente en todas las redes sociales. Pensamos, ¿por qué no hacer que el cursor sea una bandera? Después de todo, es realmente brillante e inusual. Ahora puede pasar todos los días en una empresa con un nuevo país, y el trabajo no será tan monótono y aburrido. Los cursores del mouse ahora se pueden convertir en la bandera nacional de China o los EE. UU., Japón o Canadá, y en otras 38 opciones de bandera, y puede elegir la forma de flecha estándar en un color inusual o el cursor en la forma de la bandera en sí . Este conjunto será de interés para todos los amantes de los viajes. Con él, puede planificar nuevos viajes y soñar con largos viajes. ¿Has planeado unas vacaciones? Muestra a todos a qué país quieres ir. ¿Quizás decidiste aprender un nuevo idioma extranjero? Entonces este cursor definitivamente lo apoyará y lo motivará a estudiar cuidadosamente. ¿O, como Sheldon, te encantan las banderas? En todos los casos, la colección de cursor Flags será una gran adición a su escritorio y lo llevará a nuevos descubrimientos.',
	'vokrug_sveta_descr' => 'A todos les gusta viajar. Qué maravilloso es visitar nuevos países y ciudades, ver los lugares de interés y pasar un buen rato en la nueva cultura. Es una pena que no podamos viajar con tanta frecuencia, pero tratamos de solucionarlo. El conjunto de cursores “Alrededor del mundo” es una colección de las imágenes más llamativas, símbolos de diferentes países, con la ayuda de las cuales incluso sentado en casa puede sentirse como un verdadero viajero. En nuestro kit puede encontrar Japón y Australia, Italia y Canadá, Estados Unidos y México, los países más interesantes, originales y pintorescos del mundo. La imagen del cursor puede convertirse en una flecha estándar, en los colores de la bandera del país, o convertirse en una de las principales atracciones del estado. Por ejemplo, puede abrir documentos con la Torre Inclinada de Pisa y hacer presentaciones con la Estatua de la Libertad. Garantizamos: el éxito estará asegurado. Bueno, o si no el éxito, entonces las sonrisas de los colegas y el reconocimiento de la originalidad, seguro. Sí, y dar a entender a la gerencia que es hora de irse de vacaciones también valdrá la pena, simplemente coloque la maleta o el avión como cursor, y lo más probable es que vuele muy pronto.',
	'eda_i_napitki_descr' => 'Un conjunto de cursores en forma de productos es una increíble colección de imágenes brillantes, sabrosas y deliciosas que definitivamente gustarán a todos y serán una gran adición al navegador. ¿Alguna vez has hecho clic en brócoli o papas fritas? Tiene esa oportunidad: simplemente descargue un nuevo conjunto de cursores y configúrelos en lugar de una flecha blanca aburrida. Los cursores \"Alimentos\" están hechos tanto en forma de puntero triangular estándar como en forma de productos. Aquí encontrarás verduras y frutas, tus platos favoritos, como pizzas o hot dogs, café, piruletas y mucho más, que te animan cualquier día. Me encanta el café, ¿pero beberlo todo el día no es tan bueno? Complemente su dieta con café virtual, que también lo vigorizará y lo despertará, además de darle emociones vívidas. Un cursor empinado en forma de rosquilla virtual no dañará la figura, al tiempo que dará vívidas emociones y vítores. Puede usar sus cursores favoritos o cambiar la imagen todos los días; una gran selección de cursores ayudará a colorear la vida cotidiana y agregará nuevos colores a las acciones familiares.',
	'cvetnye_descr' => 'El cursor es el elemento principal del navegador, con el que pasamos todo el día de trabajo, estudiamos, nos comunicamos y nos relajamos. La vista estándar del cursor es aburrida e incluso algo deprimente, pero aún así, para muchas personas, este formulario es conveniente, y cambiarlo será incómodo. Pero para esta situación, tenemos una solución: un conjunto de cursores en colores brillantes y alegres que agregarán variedad a su vida cotidiana y harán que resolver cualquier problema sea más fácil y rápido. Si está pensando en cómo cambiar el color del cursor, le respondemos: descargue nuestra colección y elija soluciones brillantes para cada día. Puede elegir tonos monocromáticos en diferentes colores para adaptarse al estado de ánimo o los detalles del trabajo. Por ejemplo, cuando se trabaja con documentos estándar, un cursor morado se destacará contra el fondo, y sobre un fondo oscuro, por el contrario, será más fácil trabajar con cursores amarillos. Si desea una explosión de color, brillo y máxima originalidad, elija un cursor de arco iris que incluya todos los colores del espectro, con este icono, el estado de ánimo definitivamente estará bien durante todo el día.',
	'prank_descr' => 'Las bromas en el trabajo no siempre son bienvenidas, ya que a menudo interfieren con el flujo de trabajo. Pero con el nuevo conjunto de cursores \"Pranks\", puede hacer un truco con sus colegas o amigos sin dañar su trabajo o estudio. Hemos desarrollado una colección especial que divertirá a cualquiera y dará una razón para relajarse un poco en medio del ajetreado proceso de trabajo o la realización de otra tarea. Para cambiar el cursor del mouse, simplemente descargue el kit en el dispositivo y seleccione el diseño que desee en los parámetros. Por ejemplo, puede obtener un cursor de forma estándar, pero en un estado invertido o una flecha curvada por una onda. Esta forma no impedirá en absoluto el proceso de trabajo, pero al mismo tiempo presentará un estado de ánimo maravilloso y lo pondrá en un estado de ánimo positivo. Cambie la configuración de visualización del cursor según su estado de ánimo o todos los días, y cualquier tarea será más interesante y agradable, y la vida cotidiana dejará de causar emociones negativas. Además, estos cursores se pueden usar incluso para proyectos serios: tienen colores neutros y no se destacan del escritorio.',
	'startovyj_nabor_descr' => 'Los cursores de la colección de inicio son una mezcla de formas y tamaños estándar con un aspecto brillante e inusual. Esta es una excelente opción para aquellos que prefieren las formas habituales, pero quieren aportar diversidad, originalidad y brillo a la vida cotidiana. La colección tiene un cursor de mano y una flecha familiar en una variedad de variaciones: desde el logotipo de Google Chrome hasta los emoticones, incluso puedes encontrar aquí un dragón olvidado hace mucho tiempo con cactus y nostalgia. Probamos que un cursor estándar también puede ser interesante y atractivo. Diferentes colores, formas, texturas y diseños interesantes lo ayudarán a elegir el cursor a su gusto o cambiarlo todos los días según el estado de ánimo o las tareas realizadas. Cambiar los cursores del navegador es muy simple: simplemente instale la extensión y descargue la colección en su dispositivo. Los cursores divertidos e interesantes no solo colorearán los días hábiles, sino que también, por ejemplo, ayudarán a hacer que cualquier presentación sea más interesante, y con la ayuda de cursores especialmente brillantes, también llamarán la atención sobre los elementos individuales del informe.',
	'fortnite_descr' => 'Fortnite ha conquistado a millones de personas en todo el mundo. Emocionantes batallas, estrategias y tácticas, aventuras, ha absorbido absolutamente todo lo que a los jugadores les gusta tanto. No pudimos mantenernos alejados y desarrollamos un conjunto de cursores en el estilo del juego que atraerá no solo a los ávidos jugadores, sino incluso a aquellos que escucharon por primera vez sobre Fortnite. El icono del cursor Fortnite es una imagen de un héroe o su arma, elaborada hasta el más mínimo detalle. Aquí puedes encontrar imágenes de zorros y peces, máscaras de infierno y caballeros negros, prepárate una flecha o una guadaña con puntas como flecha. ¡Estamos seguros de que nadie quedará indiferente! Ser aterrador o misterioso, original o humorístico, depende de usted. Elija su estilo y sígalo o establezca cursores personalizados en la configuración y cambie su rol todos los días. Ahora será mucho más interesante y agradable realizar incluso un trabajo tedioso y monótono: el tiempo pasará rápidamente en una compañía con imágenes vívidas y personajes favoritos. O tal vez organizarás competiciones con colegas, ¿qué héroe será más fuerte? ¡La elección es tuya!',
	'dota_2_descr' => 'DotA2 ahora no es solo un juego simple, es un mundo paralelo real. En la realidad virtual en DotA2, puedes hacer todo: vivir, luchar, desarrollarte, viajar, hacer amigos. En general, todo es como en la vida, solo que a veces es más interesante. Los cursores Dota 2 son una continuación de una estrategia que le permitirá obtener emociones vívidas y expresarse en el mundo real. Un nuevo conjunto de cursores incluye los personajes más llamativos del juego, así como elementos originales que no se pueden confundir con nada más. Elija un cursor que esté más cerca de usted y emprenda una aventura sin salir de su lugar de trabajo. Qué aburrido es a veces estar en el trabajo o realizar tareas educativas, pero con los cursores del juego este problema ya no te enfrentará. Un poco de imaginación, un cursor brillante, y listo, cualquier negocio será una aventura inusual, para hacer frente a lo que no será difícil e interesante. No hay necesidad de contenerse. ¿Te gusta Dota? Luego, asegúrese de descargar nuestra colección, seleccione uno o varios cursores aleatorios a la vez, y cada nuevo día será más brillante, más interesante y saturado.',
	'minecraft_descr' => 'Los cursores del mouse en forma de flechas y dedos estándar se han vuelto aburridos para todos. Si eres fanático de lo inusual y original, entonces es hora de cambiar el cursor del mouse y darle un diseño más interesante. Hemos desarrollado una colección de cursores al estilo del famoso juego de Minecraft, donde puedes encontrar los personajes más llamativos. Wolf and fox, Alex and Creeper, espada de diamantes y peces: puedes elegir el que más te guste o instalar un nuevo héroe todos los días. Estos son cursores reales para los jugadores, y absolutamente a todos les gustarán, después de todo, ¿quién de nosotros no ha jugado Minecraft? Estamos seguros de que estos simplemente no existen. Abajo la aburrida vida cotidiana: es hora de sumergirse en aventuras, lo que se puede hacer incluso sin abandonar la silla de su hogar u oficina. Será más interesante preparar un informe y reducir el equilibrio con una pistola: cualquier tarea será más agradable y no te aburrirás en el acto. Descargue la nueva colección de cursores de Minecraft: configúrelos e incluso en el día más gris y aburrido, su estado de ánimo siempre estará en su mejor momento. Y sus colegas envidiarán sus resultados: es simplemente imposible no hacer su trabajo con la ayuda de los valientes héroes de Minecraft.',
];