<?php

return [
    'title' => 'Cursor Style - Política de privacidad',
    'descr' => 'En "Cursor Style", disponible en cursor.style o mediante la extensión de Chrome, una de nuestras principales prioridades es la privacidad de nuestros visitantes. Es en esta sección que hablaremos sobre todos los aspectos del trabajo con la extensión.',
    'text' => '<h2> Política de privacidad </h2>
<p> En Cursor Style, disponible en <a href="https://cursor.style"> cursor.style </a> o mediante la extensión de Chrome, una de nuestras principales prioridades es la privacidad de nuestros visitantes. Este documento de Política de privacidad contiene los tipos de información que recopila y registra el sitio web cursor.style, y cómo la usamos. Si tiene preguntas adicionales o necesita más información sobre nuestra Política de privacidad, no dude en contactarnos. </p>
<p> La extensión "Cursor Style" y el sitio web siguen el procedimiento estándar para usar archivos de registro. Estos archivos registran a los visitantes cuando visitan sitios web o usan nuestra extensión. Todas las empresas de hosting hacen esto y son parte de la analítica del servicio de hosting. La información recopilada a través de los archivos de registro incluye direcciones de Protocolo de Internet (IP), tipo de navegador, Proveedor de servicios de Internet (ISP), marca de fecha y hora, páginas de transición / salida, y posiblemente la cantidad de clics. No están asociados con ninguna información de identificación personal. El propósito de esta información es analizar tendencias, administrar el sitio y expandir, rastrear el movimiento de los usuarios en el sitio y expandir, y recopilar información demográfica. </p>
<p> Como cualquier otro sitio, cursor.style utiliza cookies. Estas cookies se utilizan para almacenar información, incluidas las preferencias del visitante y las páginas del sitio web que el visitante visitó o visitó. Esta información se utiliza para optimizar la experiencia del usuario al personalizar el contenido de nuestra página web según el tipo de navegador del visitante y / u otra información. También utilizamos anuncios de terceros en cursor.style para apoyar el proyecto y nuestro sitio web. Algunos de estos anunciantes pueden usar tecnologías como cookies y balizas web cuando anuncian en nuestro sitio web, que también enviará a estos anunciantes (por ejemplo, Google a través del programa Google AdSense) información, incluida su dirección IP, su proveedor de Internet, el navegador que solía visitar nuestro sitio y, en algunos casos, si tiene instalado Flash. Esto se usa generalmente para fines de orientación geográfica (por ejemplo, mostrar anuncios para la venta de productos en su ciudad) o para mostrar ciertos anuncios basados ​​en ciertos sitios web visitados (por ejemplo, mostrar anuncios de compra a quienes visitan con frecuencia sitios de compras). </ P>
<p> Puede deshabilitar o deshabilitar selectivamente nuestras cookies o las de terceros en la configuración del navegador o administrando configuraciones en programas como Kaspersky, etc. Sin embargo, esto puede afectar la forma en que interactúa con nuestro sitio, así como con otros sitios. Esto puede incluir la imposibilidad de iniciar sesión en servicios o programas, como iniciar sesión en foros o cuentas. </p>
<p> Google es uno de los proveedores de terceros en nuestro sitio. También utiliza cookies, conocidas como cookies de DART, para ofrecer anuncios a los visitantes de nuestro sitio en función de sus visitas a cursor.style y otros sitios en Internet. Sin embargo, los visitantes pueden optar por no usar las cookies de DART visitando la política de privacidad de Google Advertising and Content Network en <a href="https://policies.google.com/technologies/ads"> la siguiente dirección </a> . Algunos de los anunciantes en nuestro sitio web pueden usar cookies y balizas web. Cada uno de nuestros socios publicitarios tiene su propia política de privacidad para sus políticas con respecto a los datos del usuario. Puede leer más sobre sus Políticas de privacidad <a href="https://policies.google.com/technologies/ads"> aquí </a>. </p>
<p> Nuestro sitio web utiliza Google Analytics, un servicio de análisis web de Google, Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043 EE. UU., www.google.com ("Google Analytics" o "Google"). Google Analytics utiliza cookies que se almacenan en su computadora para facilitar el análisis de su uso del sitio web. La información generada por estas cookies, como la hora, el lugar y la frecuencia de sus visitas a nuestro sitio web, incluida su dirección IP, se transfiere a una ubicación de Google en los EE. UU. Y se almacena allí. Google también puede transferir esta información a terceros si así lo exige la ley o si terceros procesan estos datos en nombre de Google. Google afirma que nunca asociará su dirección IP con otros datos de Google. Puede evitar la configuración de cookies cambiando la configuración del software de su navegador en consecuencia, como se especifica en esta Política de privacidad. Sin embargo, debe tener en cuenta que de esta manera no podrá utilizar todas las funciones de nuestro sitio web. </p>
<p> Google Analytics también usa imágenes electrónicas conocidas como balizas web (a veces llamadas GIF de un solo píxel) y se usan con cookies para compilar estadísticas agregadas para analizar el uso de nuestro sitio.
Puede encontrar más información sobre cómo instalar el complemento del navegador al que vincula el <a href="https://tools.google.com/dlpage/gaoptout?hl=es"> enlace </a>.
Este sitio utiliza Google Tag Manager. Este servicio le permite administrar etiquetas de sitio a través de la interfaz. Google Tag Manager implementa solo etiquetas. Esto significa que las cookies no están configuradas y no se registran datos personales. Google Tag Manager lanza otras etiquetas, que a su vez pueden registrar datos. Sin embargo, Google Tag Manager no tiene acceso a estos datos. Si las etiquetas se han deshabilitado a nivel de dominio o cookie, se guardan para todas las etiquetas de seguimiento, si se implementan mediante el Administrador de etiquetas de Google. Puede obtener más información sobre Google Tag Manager visitando <a href="http://www.google.com/tagmanager/use-policy.html"> enlace </a>. </p>
<p> Puede familiarizarse con esta lista para encontrar la Política de privacidad para cada uno de los socios publicitarios "Cursor Style". Los servidores de anuncios de terceros o las redes publicitarias utilizan tecnologías como cookies, JavaScript o balizas web, que se utilizan en sus respectivos anuncios y enlaces, que se muestran en "Cursor Style" y se envían directamente al navegador del usuario. Obtienen automáticamente su dirección IP cuando esto sucede. Estas tecnologías se utilizan para medir la efectividad de sus campañas publicitarias y / o para personalizar el contenido publicitario que ve en los sitios web que visita. Tenga en cuenta que "Cursor Style" no tiene acceso ni control sobre estas cookies que utilizan los anunciantes de terceros. La política de privacidad de Cursor Style no se aplica a otros anunciantes o sitios web. Por lo tanto, le recomendamos que revise las políticas de privacidad relevantes de estos servidores de anuncios de terceros para obtener más información. Puede incluir sus métodos e instrucciones sobre cómo darse de baja de ciertas opciones. Puede encontrar enlaces a estas Políticas de privacidad de terceros arriba o en los sitios web de estos servicios de terceros. </p>
<p> Puede deshabilitar las cookies en la configuración de su navegador. Para obtener más información sobre la administración de cookies en navegadores web específicos, puede encontrarla en sus respectivos sitios web de navegador. Otra parte de nuestra prioridad es agregar protección infantil al usar Internet. Alentamos a los padres y tutores a observar, participar y / o monitorear y dirigir sus actividades en Internet. "Cursor Style" no recopila deliberadamente información personal de niños menores de 13 años. Si cree que su hijo ha proporcionado dicha información en nuestro sitio web, le recomendamos encarecidamente que se comunique con nosotros de inmediato y haremos todo lo posible para eliminar rápidamente dicha información de nuestros registros. Esta Política de privacidad se aplica solo a nuestras actividades en línea y es válida para los visitantes de nuestro sitio web en relación con la información que compartieron y / o recopilaron en "Cursor Style". Esta política no se aplica a ninguna información recopilada fuera de línea o a través de canales distintos a este sitio web. </p>
<p> Puede leer más sobre el uso de cookies en nuestro Servicio en nuestra <a href="/cookie-policy"> Política de cookies </a>. </p> '
];
