<?php

return[
    'title' => 'Сursor Style - Términos de uso de nuestro producto',
    'descr' => 'Los términos de uso se ingresan entre usted y "Сursor Style" ("Servicio", "nosotros" o "Servicio"). Este servicio se ofrece y está disponible para usuarios mayores de 13 años solo para uso personal y no comercial.',
    'text' => '<h2> Términos de servicio </h2>
<h3> POR FAVOR LEA ESTOS TÉRMINOS Y CONDICIONES ANTES DE USAR EL SITIO WEB Y LA EXTENSIÓN. </h3>
<p> Estos términos de uso se ingresan entre usted y "Сursor Style" ("Servicio", "nosotros" o "Servicio"). Los siguientes términos y condiciones, junto con cualquier documento que incluyan expresamente como referencia (colectivamente, estos "Términos de uso") rigen su acceso y uso del sitio web cursor.style y sus extensiones de navegador, incluido cualquier contenido, funcionalidad y servicio. ofrecido en oa través de nuestro servicio (en conjunto, el "Servicio"). </p>
<p> Al usar el sitio web o la extensión, acepta y acepta cumplir con estos Términos de uso. Si no está de acuerdo con estos Términos de uso o nuestra <a href="/privacy"> Política de privacidad </a>, no debe acceder ni utilizar el Sitio web y la Extensión. </p>
<p> Este servicio se ofrece y está disponible para usuarios mayores de 13 años solo para uso personal y no comercial. Al usar este Servicio, usted declara y garantiza que tiene (I) 13 años o más, (II) no tiene prohibido usar los Sitios web de acuerdo con la ley aplicable y (III) usa el Servicio solo para sus necesidades personales . Si no cumple con estos requisitos, no debe acceder ni utilizar el Servicio. </p>
<p> Podemos revisar y actualizar estos Términos de uso de vez en cuando a nuestro criterio. Todos los cambios surten efecto inmediatamente después de su publicación. Su uso continuado del Servicio después de la publicación de los Términos de uso revisados ​​significa que acepta y acepta los cambios. Se espera que visite esta página con frecuencia para mantenerse al tanto de cualquier cambio, ya que son vinculantes para usted. </p>
<p> Nos reservamos el derecho de retirar o modificar este sitio web y la extensión, cualquier servicio o material que proporcionemos en el sitio web y la extensión, a nuestro exclusivo criterio, sin previo aviso. No garantizamos que nuestro sitio, extensión o cualquier contenido en él siempre estará disponible o será interrumpido. No seremos responsables si por alguna razón todo o parte del Servicio no está disponible en cualquier momento o durante cualquier período. De vez en cuando, podemos restringir el acceso a ciertas partes del sitio web o la extensión o el servicio completo para los usuarios. </p>
<p> Usted es responsable de tomar todas las medidas necesarias para asegurarse de tener acceso al Servicio. Asegurarse de que todas las personas que acceden al Servicio a través de su conexión a Internet conozcan estos Términos de uso y los cumplan. Para acceder al Servicio o algunos de los recursos que ofrece, es posible que se le solicite que brinde cierta información u otra información. Usted acepta que toda la información que nos proporciona utilizando este Servicio o de otro modo, incluido, entre otros, el uso de cualquier función interactiva en el Servicio, se rige por nuestra <a href="/privacy"> Política de privacidad </a> , y usted acepta todas las acciones que tomamos con respecto a su información. de acuerdo con nuestra <a href="/privacy"> Política de privacidad </a>. </p>
<p> Debe tener especial cuidado al ingresar información personal en el Servicio en una computadora pública o compartida para que otros no puedan ver o registrar su información personal. El sitio web, la extensión y todos sus contenidos, funciones y características (incluida, entre otras, toda la información, la extensión, el texto, las imágenes, las imágenes, las imágenes y los cursores, así como su diseño, selección y ubicación) pertenecen al "Сursor Style", sus licenciantes u otros proveedores de dichos materiales están protegidos por derechos de autor, marca registrada, patente, secreto comercial y otras leyes de propiedad intelectual o derechos de propiedad. </p>
<p> Estos Términos de uso le permiten usar los sitios web solo para su uso personal y no comercial. No debe reproducir, distribuir, modificar, crear trabajos derivados, volver a publicar, descargar, almacenar o transmitir ningún material en nuestro sitio web, excepto en los siguientes casos: puede usarlo para necesidades personales, puede imprimir o descargar una copia de un archivo razonable cantidad de páginas del sitio web y la extensión o sus contenidos para uso personal, no comercial, y no para su posterior reproducción, publicación o distribución. </p>
<p> No debe modificar copias de ningún material de este sitio o extensión y sus contenidos. Elimine o modifique cualquier derecho de autor, marca registrada u otros avisos de propiedad de las copias de este sitio y la extensión. No debe tener acceso ni utilizar para ningún fin comercial ninguna parte de los Sitios web o extensiones, así como tampoco los servicios o materiales disponibles a través del Sitio web o la Extensión. </p>
<p> Si desea utilizar cualquier material en sitios web o extensiones que no sean los enumerados en esta sección, envíe una solicitud en la página de soporte de Chrome Web Store. </p>
<p> Si imprime, copia, modifica, descarga o de otra manera usa o proporciona a cualquier otra persona acceso a cualquier parte del sitio web o la extensión en violación de los términos de uso, su derecho a usar el sitio web y la extensión termina inmediatamente , y debe, a nuestra discreción, devolver o destruir cualquier copia de los materiales que tenga. Cualquier uso del sitio web de la extensión que no esté expresamente permitido por estos Términos de uso viola estos Términos de uso y puede violar los derechos de autor, marcas registradas y otras leyes. </p>
<p> El nombre "Сursor Style", el logotipo "Сursor Style" y todos los nombres, logotipos, imágenes, cursores y nombres de servicio, diseños y lemas asociados son marcas comerciales de "Сursor Style" o sus filiales o licenciantes. No debe usar tales marcas sin el permiso previo por escrito del Servicio. Todos los demás nombres, logotipos, nombres de productos y servicios, diseños y lemas en este sitio web y en la extensión son marcas comerciales de sus respectivos propietarios. Puede usar el Servicio solo para fines legítimos y de acuerdo con estos Términos de uso. </p>
<h3> Usted acepta NO usar el Servicio: </h3>
<ul>
<li> De cualquier manera que viole las leyes o regulaciones federales, regionales, locales o internacionales aplicables (incluidas, entre otras, las leyes relativas a la exportación de datos o software a Rusia y otros países). </li>
<li> Con el propósito de explotación, daño o intentos de usar o dañar a menores, exponiéndolos a contenido inapropiado, solicitando información que los identifique, o de otra manera. </li>
<li> Para enviar, recibir, descargar, usar o reutilizar a sabiendas cualquier material que no cumpla con estos Términos de uso. </li>
<li> Transmita o compre el envío de cualquier publicidad o material promocional sin nuestro consentimiento previo por escrito, incluidas las "cartas no solicitadas", "cartas en cadena" o "spam" o cualquier otra oferta similar. </li>
<li> Para suplantar o intentar hacerse pasar por un "Сursor Style" un empleado, otro usuario o cualquier otra persona u organización (incluido, entre otros, el uso de direcciones de correo electrónico o alias asociados con cualquiera de los anteriores). </ li>
<li> Participación en cualquier otra acción que limite o impida el uso del Servicio o el uso de cualquier persona, o que, según determinemos, pueda dañar el Servicio o los usuarios del Servicio o hacerlos responsables. </li> </ul>
<h3> Además, usted acepta NO: </h3>
<ul>
<li> Usar el Servicio de cualquier manera que pueda deshabilitar, sobrecargar, dañar o degradar el funcionamiento del sitio, expandir o interferir con el uso del Servicio por parte de cualquier otra parte, incluida su capacidad de participar en acciones en tiempo real a través del Servicio. </li>
<li> Use cualquier herramienta, proceso o medio de automatización para acceder al Servicio para cualquier propósito, incluido el monitoreo o la copia de cualquier material en el Servicio. </li>
<li> Utilice cualquier proceso manual para rastrear o copiar cualquier material en el Servicio o para cualquier otro propósito no autorizado sin nuestro consentimiento previo por escrito. </li>
<li> Utilice cualquier dispositivo, software o procedimiento que interfiera con el funcionamiento normal del Servicio. </li>
<li> Introduzca virus, troyanos, gusanos, bombas lógicas u otros materiales que sean dañinos o tecnológicamente dañinos. </li>
<li> Intente obtener acceso no autorizado, interferir, dañar o interrumpir cualquier parte del Servicio, el servidor en el que se almacena el Servicio, o cualquier servidor, computadora o base de datos conectada al Servicio. </li>
<li> Ataque a un servicio utilizando un ataque de denegación de servicio o un ataque de denegación de servicio distribuido. </li> </ul>
<p> La información proporcionada en oa través del Servicio se proporciona únicamente con fines informativos generales. No garantizamos la exactitud, integridad o utilidad de esta información. Usted confía en dicha información bajo su propio riesgo. Renunciamos a toda responsabilidad que surja de cualquier dependencia de dichos materiales por parte de usted, cualquier otro visitante del Servicio o cualquier persona que pueda ser informada sobre cualquiera de sus contenidos. </p>
<p> Este Servicio incluye contenido proporcionado por terceros, incluidos materiales proporcionados por otros usuarios y terceros licenciantes, sindicadores, agregadores y / o servicios de informes. Todas las declaraciones y / u opiniones expresadas en estos materiales, así como todos los artículos y respuestas a preguntas y otro contenido, excepto el contenido proporcionado por el Servicio, son únicamente las opiniones y responsabilidades de la persona u organización que proporciona estos materiales. Estos materiales no reflejan necesariamente los puntos de vista del Servicio. No somos responsables ante usted ni ante ningún tercero por el contenido o la precisión de los materiales proporcionados por terceros. </p>
<p> Podemos actualizar el contenido del Servicio de vez en cuando, pero su contenido no es necesariamente completo o actual. Cualquier material en el Servicio puede estar desactualizado en cualquier momento, y no estamos obligados a actualizar dicho material. Podemos actualizar, modificar, modificar información y contenido en el sitio web y en la extensión, realizar cambios y actualizaciones de acuerdo con nuestra propia decisión. </p>
<p> Toda la información que recopilamos sobre este Servicio está sujeta a nuestra Política de privacidad. Al utilizar el Servicio, acepta todas las acciones que tomemos en relación con su información de acuerdo con la <a href="/privacy"> Política de privacidad </a>. </p>
<p> Términos adicionales también pueden aplicarse a ciertas partes, servicios o características del Servicio. Todos estos términos y condiciones adicionales se incorporan por referencia en estos Términos de uso.
Puede hacer un enlace a nuestro sitio web o extensión si lo hace de una manera honesta y legal y no daña nuestra reputación ni la utiliza, pero no debe establecer el enlace de manera que ofrezca ningún tipo de asociación, respaldo o respaldo. de nuestra parte sin nuestro consentimiento por escrito. </p>
<p> El servicio contiene enlaces a otros sitios y recursos proporcionados por terceros, estos enlaces se proporcionan solo para su conveniencia. Esto incluye enlaces contenidos en anuncios, incluidos anuncios de banner y enlaces patrocinados. No controlamos el contenido de estos sitios o recursos y no somos responsables de ellos ni de ninguna pérdida o daño que pueda resultar de su uso. Si decide acceder a sitios web de terceros asociados con este Servicio, lo hace bajo su propio riesgo y de acuerdo con los términos de uso de dichos sitios web. Nos reservamos el derecho de revocar el permiso para vincular sin previo aviso. </p>
<p> Usted comprende que no podemos garantizar ni garantizamos que los archivos disponibles para descargar a través de Internet o en sitios web no contengan virus u otro código malicioso. Usted es responsable de la implementación de procedimientos y puntos de control suficientes para satisfacer sus requisitos especiales de protección antivirus y la precisión de la entrada y salida de datos, así como de mantener medios externos a nuestro sitio para recuperar los datos perdidos. NO SEREMOS RESPONSABLES POR NINGÚN DAÑO O LESIÓN CAUSADA POR EL SERVICIO DE DEnegación distribuido, virus u otro tipo de tecnología maliciosa obtenida A TRAVÉS DEL SERVICIO, O AL DESCARGAR CUALQUIER MATERIAL PUBLICADO EN ESTE, O CUALQUIER SITIO WEB, RELACIONADO CON PUEDE INFECTAR O DAÑAR SU EQUIPO DE COMPUTADORA , SOFTWARE INFORMÁTICO, DATOS. </p>
<p> USTED UTILIZA EL SERVICIO, SU CONTENIDO Y CUALQUIER SERVICIO O ARTÍCULO OBTENIDO A TRAVÉS DE LOS SERVICIOS BAJO SU PROPIO RIESGO. EL SERVICIO, SU CONTENIDO Y CUALQUIER SERVICIO O ARTÍCULO OBTENIDO A TRAVÉS DEL SITIO WEB Y SU EXTENSIÓN, SE OFRECE TÉRMINOS Y CONDICIONES "TAL CUAL" Y "DISPONIBLES", SIN NINGUNA GARANTÍA. CUALQUIER PERSONA ASOCIADA CON EL SERVICIO NO PROPORCIONA NINGUNA GARANTÍA O REPRESENTACIÓN CON RESPECTO A LA COMPLETIDAD, SEGURIDAD, CONFIABILIDAD, CALIDAD, EXACTITUD O ACCESIBILIDAD DEL SERVICIO. SIN LIMITACIÓN ANTERIOR, NINGÚN "Сursor Style" NI RELACIONADO CON UN REPRESENTANTE "Сursor Style" NO GARANTIZA QUE EL SITIO, LA EXTENSIÓN, SU CONTENIDO O CUALQUIER REPARACIÓN DEBE ESTAR DISPONIBLE PREVIAMENTE FIJO QUE NUESTRA EXTENSIÓN, UN SITIO O UN SERVIDOR EN EL QUE SE ENCUENTRE , SERÁ SIN VIRUS U OTROS COMPONENTES DAÑINOS O ESTE SITIO WEB O CUALQUIER SERVICIO O ARTÍCULO REALIZADO, PREFERENCIADO.
<p> Bajo ninguna circunstancia el SERVICIO, SUS AFILIADOS O LICENCIANTES, SERVICIOS, EMPLEADOS, AGENTES, OFICIALES O DIRECTORES SERÁN RESPONSABLES POR DAÑOS DE NINGÚN TIPO, DAMOS SERVICIO A NINGUNA RESPONSABILIDAD. O TALES OTROS SITIOS WEB O CUALQUIER SERVICIO O ARTÍCULO OBTENIDO EN EL SERVICIO O EN OTROS SITIOS WEB, INCLUIDOS CUALQUIER DAÑO DIRECTO, ESPECIAL O CONSECUENTE, INCLUYENDO LESIONES PERSONALES, trastornos emocionales, DAÑOS O AHORRO ESPERADO, PÉRDIDA DE USO, DATOS U OTRAS CONDICIONES. LA DEFINICIÓN NO AFECTA NINGUNA RESPONSABILIDAD QUE NO PODRÍA SER EXCLUIDA O LIMITADA DE ACUERDO CON LA LEY APLICABLE QUE PUEDE INCLUIR FRAUDE. </p>
<p> Usted acepta proteger, indemnizar y desactivar el "Сursor Style", sus afiliados, licenciantes y proveedores de servicios, así como sus respectivos funcionarios, directores, empleados, contratistas, agentes, licenciantes, proveedores, cesionarios y de cualquier reclamo y responsabilidades, pérdida de decisiones judiciales, costos, gastos o comisiones (incluidos honorarios de abogados) que surjan de o en conexión con su violación de estos Términos de uso o uso del Servicio, incluido, entre otros, arrepentirse de cualquier uso del contenido, servicios y productos del sitio web o las extensiones, excepto según lo dispuesto expresamente en estos Términos de uso, o su uso de cualquier información recibida del Servicio. </p>
<p> Si cualquier disposición de estos Términos de uso es inválida, ilegal o inaplicable por un tribunal u otro tribunal de jurisdicción competente por cualquier motivo, dicha disposición debe derogarse o limitarse al mínimo, de modo que el resto de las disposiciones de los Términos de uso continuarán al máximo. Los Términos de uso, nuestra Política de privacidad y las condiciones para registrar eventos constituyen el acuerdo único y completo entre usted y el "Сursor Style" con respecto al Servicio y reemplazan todos los acuerdos, acuerdos, representaciones y garantías anteriores y simultáneos, tanto escritos como orales, con respecto a el servicio . </p>
<p> Todas las revisiones, comentarios, solicitudes de soporte técnico y otros mensajes relacionados con el Servicio deben dirigirse a la página de soporte "Сursor Style" en Chrome Web Store. </p> '
    ];
