<?php

return [
    'title' => 'Cursor Style - Patakaran sa Cookie',
    'descr' => 'Isang patakaran sa cookie kapag binisita mo ang aming website na cursor.style o ang extension na “Cursor Style”. Ilang patakaran na dapat mong isaalang-alang kapag ginagamit ang aming produkto.',
    'text' => '<h2> Patakaran sa Cookie </h2>
<p> Kapag binisita mo ang aming website na cursor.style o ang extension na "Cursor Style" sa panel ng iyong browser, o kapag nakipag-ugnayan ka sa aming mga kinatawan (ang "Serbisyo"), gagamitin namin (at papayagan ang mga third party na gamitin) ang mga web beacon, cookies, pixel tags, scripts, tag, API at iba pang teknolohiya ("Mga Tracking Technologies"). Ipinaliwanag ito sa patakarang ito ("Patakaran sa Cookie"), na bahagi ng aming <a href="/privacy"> Patakaran sa Privacy </a>. </p>
<p> Pinapayagan kami ng mga teknolohiya sa pagsubaybay na awtomatikong mangolekta ng impormasyon tungkol sa iyo at sa iyong pag-uugali sa Internet upang mapabuti ang iyong pag-navigate sa aming Serbisyo, mapabuti ang pagganap ng aming Serbisyo at mapabilis ang iyong karanasan sa aming Serbisyo. Ginagamit din namin ang impormasyong ito upang mangolekta ng mga istatistika sa paggamit ng aming Serbisyo, magsagawa ng analytics, maghatid ng nilalaman na nababagay sa iyong mga interes, at mamahala ng mga serbisyo para sa aming mga Gumagamit, customer at kasosyo. Pinapayagan din namin ang mga third party na mangolekta ng impormasyon tungkol sa iyo gamit ang mga teknolohiya sa pagsubaybay. </p>
<p> Ano ang mga cookies? Ang mga cookies ay maliliit na text file (na binubuo lamang ng mga letra at numero) na inilalagay ng web server sa iyong computer o mobile device kapag bumisita ka sa isang web page. Ang paggamit ng isang cookie ay makakatulong na gawing mas user-friendly ang aming Serbisyo, halimbawa, na tinatandaan ang iyong mga kagustuhan sa wika at mga setting. Makakahanap ka ng karagdagang impormasyon tungkol sa cookies sa <a href="http://www.allaboutcookies.org"> allaboutcookies.org </a>. </p>
<p> Ang mga cookies ay malawakang ginagamit para sa pagganap ng website. Ang paggamit ng mga cookies ay nagbibigay-daan sa iyo upang mahusay na mag-navigate sa pagitan ng mga pahina. Naaalala ng mga cookies ang iyong mga kagustuhan at ginagawang mas maayos at mas mahusay ang pakikipag-ugnayan sa pagitan mo at ng mga Serbisyo. </p>
<p> Gumagamit kami ng mga teknolohiya sa pagsubaybay kapag binisita o na-access mo ang aming mga Serbisyo (karaniwan kapag binisita mo ang aming mga website) - tinatawag silang “First-Party Tracking Technologies”. Bilang karagdagan, ang mga teknolohiya sa pagsubaybay ay nakaimbak ng iba pang mga third-party na organisasyon (halimbawa, ang aming mga service provider ng analytics, mga kasosyo sa negosyo at advertiser) na nagpo-post ng nilalaman sa aming mga Serbisyo - tinatawag silang “Third-party tracking technologies”. Ang parehong uri ng mga teknolohiya sa pagsubaybay ay maaaring maiimbak alinman para sa oras ng iyong pagbisita sa aming mga Serbisyo, o para sa paulit-ulit na pagbisita. </p>
<h3> Anong uri ng mga teknolohiya sa pagsubaybay ang ginagamit namin? Mayroong limang pangunahing uri ng mga teknolohiya sa pagsubaybay: </h3>
<ul>
<li> <b> Mahigpit na kinakailangang mga teknolohiya sa pagsubaybay </b> <br> <p> Ang mga teknolohiya sa pagsubaybay na ito ay kinakailangan upang makapag-log in ka, mag-navigate at gamitin ang mga function ng aming Serbisyo o magbigay ng serbisyo na iyong hinihiling (halimbawa, ang iyong pangalan ng gumagamit). Hindi namin kailangan ang iyong pahintulot na gamitin ang mga teknolohiya sa pagsubaybay na ito. Ang mga teknolohiyang ito sa pagsubaybay ay maaaring gamitin para sa mga layunin ng seguridad at integridad, halimbawa, upang matukoy ang mga paglabag sa aming mga patakaran, pati na rin para sa mga tampok sa suporta o seguridad. </p> </li>
<li> <b> Mga Teknolohiya sa Pagsubaybay sa Pag-andar </b> <br> <p>
Pinapayagan ng mga teknolohiya sa pagsubaybay na ito ang aming mga serbisyo na tandaan ang iyong mga pagpipilian (tulad ng wika) at magbigay ng mga advanced at isinapersonal na tampok. Halimbawa, ang mga teknolohiyang ito sa pagsubaybay ay ginagamit para sa pagpapatunay (upang matandaan kung kailan ka naka-log in) at suportahan ang iba pang mga function ng aming Serbisyo. </p> </li>
<li> <b> Mga Teknolohiya sa Pagsubaybay sa Pagganap </b> <br> <p>
Kinokolekta ng mga teknolohiyang ito sa pagsubaybay ang impormasyon tungkol sa iyong online na aktibidad (halimbawa, ang tagal ng iyong pagbisita sa aming mga Serbisyo), kabilang ang data ng pag-uugali at mga tagapagpahiwatig ng pakikipag-ugnayan sa nilalaman. Ang mga teknolohiyang ito sa pagsubaybay ay ginagamit para sa analytics, pananaliksik at istatistika (batay sa pinagsama-samang impormasyon). </p> </li>
<li> <b> Mga teknolohiya sa pagsubaybay sa marketing o advertising </b> <br> <p>
Ginamit ang mga teknolohiyang ito sa pagsubaybay upang mabigyan ka ng mga espesyal na alok at advertising batay sa iyong mga interes, pati na rin upang magsagawa ng mga kampanya sa marketing sa email. Maaari rin silang gamitin upang limitahan ang bilang ng mga beses na nakikita ang isang ad, pati na rin upang sukatin ang pagiging epektibo ng isang kampanya sa advertising. Karaniwan silang hino-host ng aming mga advertiser (halimbawa, mga ad network) at binibigyan sila ng ideya sa mga taong nakakakita at nakikipag-ugnayan sa kanilang mga ad, binibisita ang kanilang mga website o gumagamit ng kanilang app. </p> </li>
<li> <b> Mga Teknolohiya sa Pagsubaybay sa Social Media </b> <br> <p>
Kasama sa aming website ang mga function ng mga social network, tulad ng mga Like o Share button sa Facebook at Vkontakte, o mga serbisyo sa pag-login ng third-party. Ang mga function na ito ay na-post ng isang third party o direktang na-post sa aming Serbisyo. Ang iyong pakikipag-ugnayan sa mga tampok na ito ay pinamamahalaan ng pahayag sa privacy ng kumpanya na nagbibigay ng mga tampok na ito. </p> </li> </ul>
<h3> Ang mga sumusunod ay ang mga cookies na mahahanap mo sa aming mga Serbisyo: </h3>
<ul>
<li> <b> Mga Cookie Analytics </b> <br> <p> Ang mga teknolohiya sa pagsubaybay na ito ay ginagamit upang mangolekta ng impormasyon tungkol sa kung paano ka nakikipag-ugnayan sa nilalaman sa aming mga Serbisyo, mga layunin ng attribution (halimbawa, mga referral URL), atbp. Ginagamit namin ang impormasyong ito upang magtipon ng mga ulat, kalkulahin ang kita na dapat sa amin, at tulungan kaming pagbutihin ang mga Serbisyo at mag-alok ng mga isinapersonal na produkto at nilalaman. </p> </li>
<li> <b> Google Analytics </b> <br> <p> Ang cookie na ito ay ginagamit upang mangolekta ng impormasyon tungkol sa kung paano ginagamit ng mga bisita ang aming Platform. Ginagamit namin ang impormasyong ito upang magtipon ng mga ulat at upang mapabuti ang Platform. Kinokolekta ng mga cookies ang impormasyon sa hindi nagpapakilalang anyo, kasama ang bilang ng mga bisita sa Platform, kung saan nagmula ang mga bisita sa Platform, at ang mga pahinang kanilang binisita. <br> <a href = "https://policies.google.com/privacy?hl=en" > Patakaran sa Privacy </a> </p> </li>
<li> <b> Google Tag Manager </b> <br> <p> Ang cookie na ito ay nauugnay sa Google Tag Manager, na ginagamit namin upang i-load ang mga script sa mga pahina ng aming website. <br> <a href = "https: / /policies.google.com/privacy?hl=en">Patakaran sa Privacy </a> </p> </li>
</ul>
<p> Mangyaring tandaan na hindi namin kinikilala o tumutugon sa mga awtomatikong alerto ng browser tungkol sa mga teknolohiya sa pagsubaybay, kasama ang Kahilingan na Huwag Subaybayan. Gayunpaman, mayroong iba\'t ibang mga paraan upang pamahalaan at pamahalaan ang iyong mga setting ng cookie. Tandaan na kapag tinanggal o binublok ang mga cookies, maaaring hindi gumana nang tama o hindi gaanong mahusay ang ilang mga function ng Serbisyo. </p>
<p> Nagbibigay sa iyo ang karamihan sa mga web browser ng ilang pangkalahatang impormasyon tungkol sa mga cookies, pinapayagan kang makita kung anong mga cookies ang nakaimbak sa iyong aparato, pinapayagan kang tanggalin silang lahat o isa-isa, at pinapayagan ka ring i-block o payagan ang paggamit ng mga cookies para sa lahat ng mga website o isa-isang napiling mga site. Maaari mo ring i-disable ang mga third-party na cookies nang hiwalay. Mangyaring tandaan na ang mga setting na inaalok ng browser o aparato ay madalas na nalalapat lamang sa partikular na browser o aparato. </p>
<h3> Ang impormasyon sa cookie ay karaniwang matatagpuan sa seksyon ng Tulong ng isang web browser. </h3>
<p> Ang mga sumusunod ay mga link sa ilang karaniwang ginagamit na web browser: </p>
<p><a href="https://support.google.com/chrome/answer/95647?hl=en"> Chrome </a> <br>
<a href="https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies"> Internet Explorer at Microsoft Edge </a> <br>
<a href="https://support.mozilla.org/en/kb/kuki-informaciya-kotoruyu-veb-sajty-hranyat-na-vas"> Mozilla Firefox </a> <br>
<a href="https://support.apple.com/ru-ru/guide/safari/sfri11471/mac"> Safari </a> </p>
<p> Maaari mong i-off ang ilang mga third-party na cookies para sa pag-target / advertising sa pamamagitan ng pag-click sa sumusunod na link: <a href="http://optout.networkadvertising.org/?c=1"> Pag-opt out sa advertising na nakabatay sa interes </a>. </p>
				',
];
