<?php

return [
    'title' => 'Cursor Style - Patakaran sa Pagkapribado',
    'descr' => 'Sa “Cursor Style,” na makukuha sa cursor.style o sa pamamagitan ng Chrome extension, isa sa aming mga pangunahing priyoridad ay ang privacy ng aming mga bisita. Sa seksyong ito, ating tatalakayin ang lahat ng aspeto ng paggamit ng extension.',
    'text' => '<h2> Patakaran sa Pagkapribado </h2>
                <p> Sa "Cursor Style", na makukuha sa <a href="https://cursor.style"> cursor.style </a> o sa pamamagitan ng extension ng Chrome, isa sa aming mga pangunahing priyoridad ay ang privacy ng aming mga bisita. Naglalaman ang dokumentong Patakaran sa Pagkapribado na ito ng mga uri ng impormasyon na nakolekta at naitala ng website na cursor.style, at kung paano namin ito ginagamit. Kung mayroon kang karagdagang mga katanungan o kailangan mo ng karagdagang impormasyon tungkol sa aming Patakaran sa Pagkapribado, huwag mag-atubiling makipag-ugnay sa amin. </p>
                <p> Ang extension na "Cursor Style" at ang website ay sumusunod sa karaniwang pamamaraan para sa paggamit ng mga file ng log. Itinatala ng mga file na ito ang mga bisita kapag bumisita sila sa mga website o gumamit ng aming extension. Ginagawa ito ng lahat ng mga kumpanya ng hosting at bahagi ng analytics ng serbisyo sa hosting. Kasama sa impormasyong nakalap sa pamamagitan ng mga file ng log ang mga Internet Protocol (IP) address, uri ng browser, Internet Serbisyo Provider (ISP), petsa at oras ng selyo, mga pahina ng paglipat / paglabas, at posibleng bilang ng mga pag-click. Hindi sila nauugnay sa anumang personal na makikilalang impormasyon. Ang layunin ng impormasyong ito ay upang suriin ang mga uso, pamahalaan ang site at palawakin, subaybayan ang paggalaw ng mga gumagamit sa site at palawakin, at mangolekta ng impormasyon ng demograpiko. </p>
                <p> Tulad ng anumang iba pang site, gumagamit ang cursor.style ng mga cookies. Ang mga cookies na ito ay ginagamit upang mag-imbak ng impormasyon, kasama ang mga kagustuhan ng bisita at ang mga pahina sa website na binisita o binisita ng bisita. Ginagamit ang impormasyong ito upang i-optimize ang karanasan ng gumagamit sa pamamagitan ng pag-customize ng nilalaman ng aming web page batay sa uri ng browser ng bisita at / o iba pang impormasyon. Gumagamit din kami ng mga third-party na ad sa cursor.style upang suportahan ang proyekto at suportahan ang aming website. Ang ilan sa mga advertiser na ito ay maaaring gumamit ng mga teknolohiya tulad ng mga cookies at web beacon kapag nag-aanunsyo sila sa aming website, na magpapadala rin sa mga advertiser na ito (halimbawa, Google sa pamamagitan ng programang Google AdSense) ng impormasyon, kabilang ang iyong IP address, ang iyong Internet provider, ang browser na ginamit mo upang bisitahin ang aming site, at sa ilang mga kaso, kung mayroon kang naka-install na Flash. Karaniwang ginagamit ito para sa mga layunin ng geotargeting (halimbawa, pagpapakita ng mga ad para sa pagbebenta ng mga kalakal sa iyong lungsod) o para sa pagpapakita ng ilang mga ad batay sa ilang mga website na binisita (halimbawa, pagpapakita ng mga anunsyo sa pagbili sa mga madalas na bumibisita sa mga shopping site). </p >
                <p> Maaari mong huwag paganahin o piliing huwag paganahin ang aming o third-party na mga cookies sa mga setting ng browser o sa pamamagitan ng pamamahala ng mga setting sa mga programa tulad ng Kaspersky, atbp. Gayunpaman, maaaring makaapekto ito kung paano ka makipag-ugnay sa aming site, pati na rin sa iba pang mga site. Maaaring isama nito ang kawalan ng kakayahang mag-log in sa mga serbisyo o programa, tulad ng pag-log in sa mga forum o account. </p>
<p> Ang Google ay isa sa mga third-party na provider sa aming site. Gumagamit din ito ng mga cookies, na kilala bilang DART cookies, upang maghatid ng mga ad sa mga bisita sa aming site batay sa kanilang mga pagbisita sa cursor.style at iba pang mga site sa Internet. Gayunpaman, maaaring i-opt out ng mga bisita sa paggamit ng mga DART cookies sa pamamagitan ng pagbisita sa patakaran sa pagkapribado ng Google Advertising at Content Network sa <a href="https://policies.google.com/technologies/ads"> sumusunod na address </a>. Ang ilan sa mga advertiser sa aming website ay maaaring gumamit ng mga cookies at web beacon. Ang bawat isa sa aming mga kasosyo sa advertising ay may sariling patakaran sa pagkapribado para sa mga patakaran nito tungkol sa data ng gumagamit. Maaari kang magbasa nang higit pa tungkol sa kanilang Mga Patakaran sa Pagkapribado <a href="https://policies.google.com/technologies/ads"> dito </a>. </p>
                <p> Gumagamit ang aming website ng Google Analytics, isang serbisyo sa pagsusuri sa web ng Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com (“Google Analytics” o “Google”). Gumagamit ang Google Analytics ng mga cookies na nakaimbak sa iyong computer upang mapadali ang pag-aaral ng iyong paggamit sa website. Ang impormasyong nabuo ng mga cookies na ito, tulad ng oras, lugar at dalas ng iyong mga pagbisita sa aming website, kabilang ang iyong IP address, ay inililipat sa isang lokasyon ng Google sa USA at nakaimbak doon. Maaari ring ilipat ng Google ang impormasyong ito sa mga third party kung kinakailangan ng batas o kung pinoproseso ng mga third party ang data na ito sa ngalan ng Google. Sinasabi ng Google na hindi nito kailanman iugnay ang iyong IP address sa iba pang data ng Google. Maaari mong pigilan ang pagtatakda ng mga cookies sa pamamagitan ng pagbabago ng iyong mga setting ng software ng browser nang naaayon, tulad ng tinukoy sa Patakaran sa Pagkapribado na ito. Gayunpaman, dapat mong malaman na sa ganitong paraan hindi mo magagawang ganap na magamit ang lahat ng mga pag-andar ng aming website. </p>
                <p> Gumagamit din ang Google Analytics ng mga elektronikong imahe na kilala bilang web beacon (kung minsan ay tinatawag na single-pixel GIFs) at ginagamit sa mga cookies upang magtipon ng pinagsama-samang istatistika upang pag-aralan ang paggamit ng aming site.
Maaari kang makahanap ng karagdagang impormasyon sa kung paano i-install ang add-on ng browser na na-link mo sa itaas <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> link </a>.
Ang site na ito ay gumagamit ng Google Tag Manager. Pinapayagan ka ng serbisyong ito na pamahalaan ang mga tag ng site sa pamamagitan ng interface. Ang Google Tag Manager ay nagpapatupad lamang ng mga tag. Nangangahulugan ito na ang mga cookies ay hindi nakatakda at walang personal na data na naitala. Inilulunsad ng Google Tag Manager ang iba pang mga tag, na maaaring magrekord ng data. Gayunpaman, ang Google Tag Manager ay walang access sa data na ito. Kung ang mga tag ay hindi pinagana sa antas ng domain o cookie, nai-save ang mga ito para sa lahat ng mga tracking tag, kung ipinatupad gamit ang Google Tag Manager. Maaari mong malaman ang higit pa tungkol sa Google Tag Manager sa pamamagitan ng pagbisita sa <a href="http://www.google.com/tagmanager/use-policy.html"> link </a>. </p>
<p> Maaari mong pamilyar ang iyong sarili sa listahang ito upang mahanap ang Patakaran sa Pagkapribado para sa bawat isa sa mga kasosyo sa advertising na "Cursor Style". Ang mga third-party ad server o ad network ay gumagamit ng mga teknolohiya tulad ng mga cookies, JavaScript o web beacon, na ginagamit sa kani-kanilang mga advertisement at link, na ipinapakita sa "Cursor Style" at ipinadala nang direkta sa browser ng mga gumagamit. Awtomatiko nilang nakukuha ang iyong IP address kapag nangyari ito. Ang mga teknolohiyang ito ay ginagamit upang sukatin ang pagiging epektibo ng kanilang mga kampanya sa advertising at / o upang i-personalize ang nilalaman ng advertising na nakikita mo sa mga website na binibisita mo. Mangyaring tandaan na ang "Cursor Style" ay walang access o kontrol sa mga cookies na ito na ginagamit ng mga third-party na advertiser. Ang patakaran sa pagkapribado ng Cursor Style ay hindi nalalapat sa iba pang mga advertiser o website. Samakatuwid, inirerekumenda namin na suriin mo ang mga nauugnay na patakaran sa pagkapribado ng mga third-party ad server na ito para sa karagdagang impormasyon. Maaari nitong isama ang kanilang mga pamamaraan at tagubilin kung paano mag-opt out sa ilang mga pagpipilian. Maaari mong mahanap ang mga link sa mga Third Party na Patakaran sa Pagkapribado sa itaas o sa mga website ng mga serbisyong third-party na ito. </p>
                <p> Maaari mong huwag paganahin ang mga cookies sa iyong mga setting ng browser. Upang matuto nang higit pa tungkol sa pamamahala ng cookie sa mga tukoy na web browser, maaari mo itong mahanap sa kani-kanilang mga website ng browser. Ang isa pang bahagi ng aming prayoridad ay ang pagdaragdag ng proteksyon ng bata kapag gumagamit ng Internet. Hinihikayat namin ang mga magulang at tagapag-alaga na obserbahan, lumahok at / o subaybayan at direktang kanilang mga aktibidad sa Internet. Ang "Cursor Style" ay hindi malayong nangongolekta ng personal na impormasyon mula sa mga batang wala pang 13 taong gulang. Kung sa palagay mo ang iyong anak ay nagbigay ng naturang impormasyon sa aming website, lubos naming inirerekumenda na makipag-ugnay ka kaagad sa amin at gagawin namin ang aming makakaya upang mabilis na alisin ang naturang impormasyon mula sa aming mga talaan. Nalalapat ang Patakaran sa Pagkapribado na ito sa aming mga online na aktibidad lamang at may bisa para sa mga bisita sa aming website na may kaugnayan sa impormasyon na ibinahagi at / o nakolekta sa "Cursor Style". Ang patakarang ito ay hindi nalalapat sa anumang impormasyon na nakolekta offline o sa pamamagitan ng mga channel maliban sa website na ito. </p>
                <p> Maaari kang magbasa nang higit pa tungkol sa paggamit ng mga cookies sa aming Serbisyo sa aming <a href="/cookie-policy"> Patakaran sa Cookie </a>. </p> ',
];
