<?php

return [
    'title' => 'Cursor Style - Mga Tuntunin ng paggamit ng aming produkto',
    'descr' => 'Ang mga Tuntunin ng Paggamit ay ipinasok sa pagitan mo at ng “Cursor Style” (“Serbisyo”, “kami” o “Serbisyo”). Ang serbisyong ito ay inaalok at magagamit lamang sa mga user na may edad 13 taong gulang pataas para sa personal na paggamit at hindi para sa komersyal na paggamit.',
    'text' => '<h2> Mga Tuntunin ng Serbisyo </h2>
<h3> PAKIBASA ANG MGA TUNTUNIN AT KUNDISYON NA ITO BAGO GAMITIN ANG WEBSITE AT EXTENSION. </h3>
<p> Ang mga tuntunin ng paggamit na ito ay ipinasok sa pagitan mo at ng "Cursor Style" ("Serbisyo", "kami" o "Serbisyo"). Ang mga sumusunod na tuntunin at kundisyon, kasama ang anumang mga dokumento na malinaw na isinasama nila sa pamamagitan ng sanggunian (sama-sama, ang mga "Tuntunin ng Paggamit"), ang namamahala sa iyong pag-access at paggamit ng website ng cursor.style at mga extension ng browser nito, kasama ang anumang nilalaman, pag-andar at serbisyo na inaalok sa o sa pamamagitan ng aming serbisyo (sama-sama ang “Serbisyo”). </p>
<p> Sa pamamagitan ng paggamit ng website o extension, tinatanggap at sumasang-ayon kang sumunod sa mga Tuntunin ng Paggamit na ito. Kung hindi ka sumasang-ayon sa mga Tuntunin ng Paggamit na ito o sa aming <a href="/privacy"> Patakaran sa Privacy </a>, hindi mo dapat i-access o gamitin ang Website at ang Extension. </p>
<p> Ang serbisyong ito ay inaalok at available sa mga user na may edad na 13 taong gulang at mas matanda lamang para sa personal na paggamit at hindi para sa komersyal na paggamit. Sa paggamit ng Serbisyo na ito, kinatawan at ginagarantiyahan mo na ikaw ay (I) 13 taong gulang o mas matanda, (II) hindi ka pinagbawalan na gamitin ang mga Website alinsunod sa naaangkop na batas, at (III) ginagamit mo ang Serbisyo para lamang sa iyong mga personal na pangangailangan. Kung hindi mo natutugunan ang mga kinakailangang ito, hindi mo dapat i-access o gamitin ang Serbisyo. </p>
<p> Maaari naming baguhin at i-update ang mga Tuntunin ng Paggamit na ito paminsan-minsan sa aming pagpapasya. Ang lahat ng pagbabago ay magkakabisa kaagad pagkatapos ng kanilang publikasyon. Ang iyong patuloy na paggamit ng Serbisyo pagkatapos ng publikasyon ng binagong Mga Tuntunin ng Paggamit ay nangangahulugan na tinatanggap at sinasang-ayunan mo ang mga pagbabago. Inaasahan kang bisitahin ang pahinang ito nang madalas upang mapanatiling alam ang anumang mga pagbabago dahil sila ay nagbubuklod sa iyo. </p>
<p> Nakalaan sa amin ang karapatang bawiin o baguhin ang Website at ang Extension na ito, anumang serbisyo o materyales na ibinibigay namin sa Website at sa Extension, sa aming sariling pagpapasya, nang walang abiso. Hindi namin ginagarantiyahan na ang aming site, extension o anumang nilalaman dito ay palaging magiging available o maaantala. Hindi kami mananagot kung sa anumang kadahilanan ang lahat o anumang bahagi ng Serbisyo ay hindi available sa anumang oras o sa anumang panahon. Paminsan-minsan, maaari naming limitahan ang pag-access sa ilang bahagi ng Website o ng Extension o sa buong Serbisyo para sa mga user. </p>
<p> Ikaw ay responsable sa pagkuha ng lahat ng kinakailangang hakbang upang matiyak na mayroon kang access sa Serbisyo. Tinitiyak na ang lahat ng taong nag-access sa Serbisyo sa pamamagitan ng iyong koneksyon sa Internet ay may kamalayan sa mga Tuntunin ng Paggamit na ito at sumunod sa kanila. Upang ma-access ang Serbisyo o ang ilan sa mga mapagkukunan na inaalok nito, maaari kang hilingin na magbigay ng ilang impormasyon o iba pang impormasyon. Sumasang-ayon ka na ang lahat ng impormasyon na ibinibigay mo sa amin gamit ang Serbisyo na ito o kung hindi man, kasama ngunit hindi limitado sa paggamit ng anumang mga interactive na tampok sa Serbisyo, ay nasasakupan ng aming <a href="/privacy"> Patakaran sa Privacy </a>, at sumasang-ayon ka sa lahat ng aksyon na gagawin namin tungkol sa iyong impormasyon. alinsunod sa aming <a href="/privacy"> Patakaran sa Privacy </a>. </p>
<p> Dapat kang maging maingat lalo na kapag nagpasok ng personal na impormasyon sa Serbisyo sa isang pampubliko o nakabahaging computer upang ang iba ay hindi makita o maitala ang iyong personal na impormasyon. Ang website, ang extension at ang lahat ng nilalaman nito, mga function at tampok (kasama, ngunit hindi limitado sa, lahat ng impormasyon, ang extension, teksto, mga larawan, mga larawan, mga larawan at mga cursor, pati na rin ang kanilang disenyo, pagpili at paglalagay) ay kabilang sa "Cursor Style", ang mga lisensyado nito o iba pang mga supplier ng naturang mga materyales ay protektado ng copyright, trademark, patent, trade secret at iba pang mga batas sa intelektwal na ari-arian o mga karapatan sa ari-arian. </p>
<p> Ang Mga Tuntunin ng Paggamit na ito ay nagpapahintulot sa iyo na gamitin ang mga Website para lamang sa iyong personal, hindi pangkomersyal na paggamit. Hindi mo dapat i-reproduce, ipamahagi, baguhin, lumikha ng mga gawaing hango, i-republish, i-download, iimbak o i-transmit ang anumang mga materyales sa aming Website, maliban sa mga sumusunod na kaso: maaari mong gamitin ito para sa mga personal na pangangailangan, maaari mong i-print o i-download ang isang kopya ng isang makatuwirang dami ng mga pahina ng Website at ng Extension o ng kanilang mga nilalaman para sa personal, hindi pangkomersyal na paggamit, at hindi para sa karagdagang pag-reproduction, publikasyon o pamamahagi. </p>
<p> Hindi mo dapat baguhin ang mga kopya ng anumang mga materyal mula sa site o extension na ito at ang kanilang mga nilalaman. Tanggalin o baguhin ang anumang copyright, trademark, o iba pang mga paunawa ng pagmamay-ari mula sa mga kopya ng site na ito at ang extension. Hindi ka dapat magkaroon ng access sa o gumamit para sa anumang komersyal na layunin ang anumang bahagi ng mga Website o extension, pati na rin ang anumang mga serbisyo o materyales na available sa pamamagitan ng Website o ng Extension. </p>
<p> Kung nais mong gumamit ng anumang materyal sa Mga Website o Extension maliban sa mga nakalista sa seksyong ito, magpadala ng kahilingan sa pahina ng suporta ng Chrome Web Store. </p>
<p> Kung nag-print ka, kumopya, nagbabago, nag-download, o kung hindi man ay gumamit o nagbibigay ng anumang ibang tao ng access sa anumang bahagi ng Website o ng Extension na lumalabag sa Mga Tuntunin ng Paggamit, ang iyong karapatang gamitin ang Website at ang Extension ay agad na nagtatapos, at dapat mong, sa aming pagpapasya, ibalik o sirain ang anumang mga kopya ng mga materyales na mayroon ka. Ang anumang paggamit ng website ng extension na hindi tahasang pinahihintulutan ng Mga Tuntunin ng Paggamit na ito ay lumalabag sa Mga Tuntunin ng Paggamit na ito at maaaring lumabag sa mga copyright, trademark at iba pang mga batas. </p>
<p> Ang pangalan na “Cursor Style”, ang logo na “Cursor Style” at lahat ng nauugnay na pangalan, logo, larawan, cursor at pangalan ng serbisyo, disenyo at slogan ay mga trademark ng “Cursor Style” o mga kaakibat o lisensyado nito. Hindi mo dapat gamitin ang naturang mga marka nang walang paunang nakasulat na pahintulot ng Serbisyo. Ang lahat ng iba pang mga pangalan, logo, produkto at pangalan ng serbisyo, disenyo at slogan sa website na ito at sa extension ay mga trademark ng kani-kanilang mga may-ari. Maaari mo lamang gamitin ang Serbisyo para sa mga lehitimong layunin at alinsunod sa Mga Tuntunin ng Paggamit na ito. </p>
<h3> Sumasang-ayon ka na HUWAG gamitin ang Serbisyo: </h3>
<ul>
<li> Sa anumang paraan na lumalabag sa anumang naaangkop na pederal, panrehiyon, lokal o internasyonal na mga batas o regulasyon (kasama, ngunit hindi limitado sa, anumang mga batas tungkol sa pag-export ng data o software sa Russia at iba pang mga bansa). </li>
<li> Para sa layunin ng pagsasamantala, pinsala, o pagtatangkang gamitin o pinsalain ang mga menor de edad, na inilalantad sila sa hindi naaangkop na nilalaman, na humihiling ng impormasyon na nagpapakilala sa kanila, o kung hindi man. </li>
<li> Upang magpadala, sinasadyang tumanggap, mag-download, gumamit o muling gamitin ang anumang mga materyales na hindi sumusunod sa Mga Tuntunin ng Paggamit na ito. </li>
<li> Magpadala o bumili ng pagpapadala ng anumang mga advertisement o pang-promosyong materyales nang walang aming paunang nakasulat na pahintulot, kabilang ang anumang "hindi hinihiling na mga liham", "mga liham ng kadena" o "spam" o anumang iba pang katulad na mga alok. </li>
<li> Upang magpanggap o subukang magpanggap na isang empleyado ng “Cursor Style”, isa pang user, o anumang iba pang tao o organisasyon (kasama ngunit hindi limitado sa paggamit ng mga email address o alias na nauugnay sa anuman sa itaas). </ li >
<li> Pakikilahok sa anumang iba pang mga aksyon na naglilimita o humahadlang sa paggamit ng Serbisyo o ang paggamit ng sinuman, o na, tulad ng aming matukoy, ay maaaring makapinsala sa Serbisyo o sa mga user ng Serbisyo o gawing mananagot sila. </li> </ul>
<h3> Bilang karagdagan, sumasang-ayon ka na HUWAG: </h3>
<ul>
<li> Gamitin ang Serbisyo sa anumang paraan na maaaring mag-disable, mag-overload, makapinsala o makapagpababa sa pagpapatakbo ng site, palawakin o makagambala sa paggamit ng Serbisyo ng anumang iba pang partido, kabilang ang kanilang kakayahan na lumahok sa mga real-time na aksyon sa pamamagitan ng Serbisyo. </li>
<li> Gumamit ng anumang mga tool sa automation, proseso o paraan upang ma-access ang Serbisyo para sa anumang layunin, kabilang ang pagsubaybay o pagkopya ng anumang materyal sa Serbisyo. </li>
<li> Gumamit ng anumang manu-manong proseso upang subaybayan o kopyahin ang anumang materyal sa Serbisyo o para sa anumang iba pang hindi awtorisadong layunin nang walang aming paunang nakasulat na pahintulot. </li>
<li> Gumamit ng anumang device, software o pamamaraan na nakakasagabal sa normal na pagpapatakbo ng Serbisyo. </li>
<li> Magpakilala ng anumang mga virus, trojan horse, worm, logic bomb o iba pang mga materyales na nakakapinsala o nakakapinsala sa teknolohiya. </li>
<li> Subukang makakuha ng hindi awtorisadong pag-access, makagambala, makapinsala o makasira sa anumang bahagi ng Serbisyo, ang server kung saan nakaimbak ang Serbisyo, o anumang server, computer o database na konektado sa Serbisyo. </li>
<li> Atakehin ang isang Serbisyo gamit ang isang denial of service attack o isang distributed denial of service attack. </li> </ul>
<p> Ang impormasyon na ibinigay sa o sa pamamagitan ng Serbisyo ay ibinigay para lamang sa mga pangkalahatang layuning pang-impormasyon. Hindi namin ginagarantiyahan ang katumpakan, pagkakumpleto o kapaki-pakinabang ng impormasyong ito. Umuuasa ka sa naturang impormasyon sa iyong sariling peligro lamang. Itinanggi namin ang lahat ng responsibilidad at pananagutan na nagmumula sa anumang pag-asa sa naturang mga materyales ng iyo, anumang iba pang mga bisita sa Serbisyo o sinuman na maaaring ipaalam sa anumang nilalaman ng mga ito. </p>
<p> Kasama sa Serbisyo na ito ang nilalaman na ibinigay ng mga third party, kasama ang mga materyales na ibinigay ng iba pang mga user at third-party na mga lisensyado, syndicator, aggregator at / o mga serbisyo sa pag-uulat. Ang lahat ng mga pahayag at / o opinyon na ipinahayag sa mga materyales na ito, pati na rin ang lahat ng mga artikulo at sagot sa mga tanong at iba pang nilalaman, maliban sa nilalaman na ibinigay ng Serbisyo, ay tanging ang mga opinyon at responsibilidad ng tao o organisasyon na nagbibigay ng mga materyales na ito. Ang mga materyales na ito ay hindi kinakailangang sumasalamin sa mga pananaw ng Serbisyo. Hindi kami mananagot sa iyo o sa anumang ikatlong partido para sa nilalaman o katumpakan ng anumang mga materyales na ibinigay ng mga third party. </p>
<p> Maaari naming i-update ang nilalaman ng Serbisyo paminsan-minsan, ngunit ang nilalaman nito ay hindi kinakailangang kumpleto o kasalukuyang. Ang anumang materyal sa Serbisyo ay maaaring lipas na sa anumang oras, at hindi kami kinakailangang mag-update ng naturang materyal. Maaari kaming mag-update, magbago, magbago ng impormasyon at nilalaman sa Website at sa Extension, gumawa ng anumang mga pagbabago at update ayon sa aming sariling desisyon. </p>
<p> Ang lahat ng impormasyong kinokolekta namin sa Serbisyo na ito ay napapailalim sa aming Patakaran sa Privacy. Sa paggamit ng Serbisyo, sumasang-ayon ka sa lahat ng aksyon na ginawa namin na may kaugnayan sa iyong impormasyon alinsunod sa <a href="/privacy"> Patakaran sa Privacy </a>. </p>
<p> Maaaring maging naaangkop din ang mga karagdagang tuntunin sa ilang bahagi, serbisyo o tampok ng Serbisyo. Ang lahat ng naturang karagdagang tuntunin at kundisyon ay isinasama dito sa pamamagitan ng sanggunian sa Mga Tuntunin ng Paggamit na ito.
Maaari kang mag-link sa aming website o extension kung gagawin mo ito sa isang tapat at legal na paraan at hindi mo sinisira ang aming reputasyon o ginagamit ito, ngunit hindi mo dapat itakda ang link sa paraang mag-alok ng anumang anyo ng asosasyon, pag-endorso o pag-endorso sa aming bahagi nang walang aming nakasulat na pahintulot. </p>
<p> Ang serbisyo ay naglalaman ng mga link sa iba pang mga site at mapagkukunan na ibinigay ng mga third party, ang mga link na ito ay ibinigay lamang para sa iyong kaginhawahan. Kasama rito ang mga link na nakapaloob sa mga advertisement, kabilang ang mga banner ad at naka-sponsor na mga link. Hindi namin kinokontrol ang nilalaman ng mga site o mapagkukunang ito at hindi responsable para sa kanila o para sa anumang pagkawala o pinsala na maaaring magresulta mula sa kanilang paggamit. Kung magpasya kang i-access ang anumang mga website ng third-party na nauugnay sa Serbisyo na ito, ginagawa mo ito sa iyong sariling peligro at alinsunod sa mga tuntunin ng paggamit ng naturang mga website. Nakalaan sa amin ang karapatang bawiin ang pahintulot na mag-link nang walang paunang abiso. </p>
<p> Naiintindihan mo na hindi namin at hindi ginagarantiyahan o ginagarantiyahan na ang mga file na magagamit para sa pag-download sa pamamagitan ng Internet o sa mga Website ay hindi maglalaman ng mga virus o iba pang nakakahamak na code. Ikaw ang responsable sa pagpapatupad ng mga pamamaraan at pagkontrol ng mga punto na sapat upang matugunan ang iyong mga espesyal na kinakailangan para sa proteksyon laban sa virus at ang katumpakan ng pagpasok at paglabas ng data, pati na rin para sa pagpapanatili ng mga paraan sa labas ng aming site para sa pagbawi ng anumang nawalang data. HINDI KAMI MANANAGOT PARA SA ANUMANG PINSALA O PINSALA NA DULOT NA DISTRIBUTED NA PAGTANGGI SA SERBISYO, MGA VIRUS O IBA PANG TEKNOLOHIYA-MALWARE NA NAKUHA SA PAMAMAGITAN NG SERBISYO, O SA PAMAMAGITAN NG PAG-DOWNLOAD NG ANUMANG MATERIAL NA NA-POST SA ITO, O ANUMANG WEB SITES, NA MAY KINALAMAN NA MAARING MAHAWAAN O MAG-PINSALA SA IYONG KAGAMITAN SA COMPUTER, SOFTWARE SA COMPUTER, DATA. </p>
<p> GINAGAMIT MO ANG SERBISYO, ANG NILALAMAN NITO AT ANUMANG MGA SERBISYO O MGA ITEM NA NAKUHA SA PAMAMAGITAN NG MGA SERBISYO SA IYONG SARILING PANGANIB. ANG SERBISYO, ANG NILALAMAN NITO AT ANUMANG MGA SERBISYO O MGA ITEM NA NAKUHA SA PAMAMAGITAN NG WEBSITE AT EXTENSION, AY IBINIGAY SA ISANG “AS IS” AT “AS AVAILABLE” NA MGA TUNTUNIN AT KUNDISYON, NA WALANG ANUMANG WARRANTY. ANUMANG TAO NA KAUGNAY SA SERBISYO AY HINDI NAGBIBIGAY NG ANUMANG WARRANTY O REPRESENTATION NA MAY RESPETO SA PAGKAKUMPLETO, KALIGTASAN, KATIWALAAN, KALIDAD, KATUMPAKAN O ACCESSIBILITY NG SERBISYO. WALANG LIMITASYON SA ITAAS, WALANG "CURSOR STYLE" NI KAUGNAY SA ISANG "CURSOR STYLE" NA MGA KINATAWAN AY HINDI NAG-WA-WARRANT NA ANG SITE, ANG EXTENSION, ANG NILALAMAN NITO O ANUMANG PAG-AAYOS AY DAPAT NA HINDI ALAM NANG NAUNA NA NAKATAKDA NA ANG ATING EXTENSION, ISANG SITE O ISANG SERVER NA NAGLALAGAY NITO, AY HINDI MAGIGING WALANG MGA VIRUS O IBA PANG NAKAKAPINSALANG MGA SANGKAP O ANG WEB SITE NA ITO O ANUMANG MGA SERBISYO O MGA ITEM NA GUMAGANAP, NAIBA. </p>
<p> Sa ilalim ng walang mga pangyayari ay dapat managot ang SERBISYO, ANG KABIT NITO O O LISENSYADO, MGA SERBISYO, MGA EMPLEYADO, MGA AHEYENTE, MGA OPISYAL o MGA DIREKTOR PARA SA MGA PINSALA NG ANUMANG URI, NAG-AALOK KAMI SA ANUMANG PANANAGUTAN. O ANG IBA PANG MGA WEBSITE O ANUMANG MGA SERBISYO O MGA ITEM NA NAKUHA SA SERBISYO O SA IBA PANG MGA WEB SITES, KASAMA ANG ANUMANG DIREKTA, ESPESYAL O KONSEKENSYAL NA MGA PINSALA, KASAMA ANG PERSONAL NA PINSALA, EMOSYONAL NA MGA KARAMDAMAN, MGA PINSALA O INAASAHANG MATITIPID, PAGKAWAL SA PAG-GAMIT, DATA O IBA PANG MGA KONDISYON. ANG KAHULUGAN AY HINDI NAKAKAAPEKTO SA ANUMANG PANANAGUTAN NA HINDI MAAARING EXCLUDE O LIMITADO ALINSUNOD SA NAAANGKOP NA BATAS NA MAAARING MAGLAMAN NG PANLOLOKO. </p>
<p> Sumasang-ayon kang protektahan, bayaran at i-defuse ang “Cursor Style”, ang mga kaakibat nito, mga lisensyado at service provider, pati na rin ang mga opisyal, direktor, empleyado, kontraktor, ahente, lisensyado, supplier, itinalaga at mula sa anumang mga paghahabol at pananagutan, pagkawala ng mga desisyon ng korte, gastos, gastos o komisyon (kabilang ang mga bayad sa abogado) na nagmumula sa o may kaugnayan sa iyong paglabag sa mga Tuntunin ng paggamit na ito o ang paggamit ng Serbisyo, kasama ngunit hindi limitado sa pagbabayad sa anumang paggamit ng nilalaman, mga serbisyo at produkto ng Website o ng Mga Extension, maliban kung malinaw na ibinigay sa Mga Tuntunin ng Paggamit na ito, o ang iyong paggamit ng anumang impormasyong natanggap mula sa Serbisyo. </p>
<p> Kung ang anumang probisyon ng Mga Tuntunin ng Paggamit na ito ay natagpuang hindi wasto, ilegal o hindi maipapatupad ng isang korte o iba pang tribunal ng may kakayahang hurisdiksyon para sa anumang kadahilanan, ang naturang probisyon ay dapat na pawalang-bisa o limitado sa isang minimum, upang ang natitirang mga probisyon ng Mga Tuntunin ng Paggamit ay magpapatuloy sa pinakamalawak. Ang Mga Tuntunin ng Paggamit, ang aming Patakaran sa Privacy at ang mga kundisyon para sa pagrehistro ng mga kaganapan ay bumubuo ng nag-iisang at kumpletong kasunduan sa pagitan mo at ng "Cursor Style" tungkol sa Serbisyo at pinapalitan ang lahat ng nakaraang at magkakasabay na mga kasunduan, kasunduan, representasyon at warranty, parehong nakasulat at pasalita, tungkol sa Serbisyo . </p>
<p> Ang lahat ng mga pagsusuri, komento, kahilingan sa suporta sa teknikal, at iba pang mga mensahe tungkol sa Serbisyo ay dapat na idirekta sa pahina ng suporta ng "Cursor Style" sa Chrome Web Store. </p> ',
];
