<?php

return [
    'title' => 'Cursor Style - Privatumo politika',
    'descr' => 'Programoje „Cursor Style“, kurią galite rasti adresu cursor.style arba per „Chrome“ plėtinį, vienas iš pagrindinių mūsų prioritetų yra lankytojų privatumas. Būtent šiame skyriuje kalbėsime apie visus darbo su plėtiniu aspektus.',
    'text' => '<h2> Privatumo politika </h2>
                <p> „Cursor Style“, pasiekiama adresu <a href="https://cursor.style"> cursor.style </a> arba per „Chrome“ plėtinį, yra vienas iš pagrindinių mūsų prioritetų mūsų lankytojų privatumas. Šiame Privatumo politikos dokumente pateikiama informacija, kurią renka ir įrašo svetainė cursor.style, ir kaip mes ją naudojame. Jei turite papildomų klausimų ar jums reikia daugiau informacijos apie mūsų Privatumo politiką, nedvejodami susisiekite su mumis. </p>
                <p> „Cursor Style“ plėtinys ir svetainė laikosi standartinės procedūros naudodami žurnalo failus. Šie failai registruoja lankytojus apsilankius svetainėse ar naudojant mūsų plėtinį. Tai daro visos prieglobos įmonės ir yra prieglobos paslaugų analizės dalis. Informacija, surinkta per žurnalo failus, apima interneto protokolo (IP) adresus, naršyklės tipą, interneto paslaugų teikėją (ISP), datos ir laiko žymą, perėjimo / išėjimo puslapius ir galbūt paspaudimų skaičių. Jie nėra susiję su jokiais asmeniškai identifikuojamais duomenimis. Šios informacijos tikslas yra analizuoti tendencijas, administruoti svetainę ir plėsti, stebėti vartotojų judėjimą svetainėje ir plėsti bei rinkti demografinę informaciją. </p>
                <p> Kaip ir bet kuri kita svetainė, cursor.style naudoja slapukus. Šie slapukai naudojami informacijai saugoti, įskaitant lankytojo nuostatas ir svetainės puslapius, kuriuos lankytojas aplankė ar aplankė. Ši informacija naudojama optimizuoti vartotojo patirtį pritaikant mūsų tinklalapio turinį pagal lankytojo naršyklės tipą ir (arba) kitą informaciją. Taip pat naudojame trečiųjų šalių skelbimus svetainėje cursor.style, kad paremtume projektą ir palaikytume mūsų svetainę. Kai kurie iš šių reklamuotojų gali naudoti tokias technologijas kaip slapukai ir žiniatinklio švyturiai, kai jie reklamuoja mūsų svetainėje, o tai taip pat atsiųs šiems reklamuotojams (pavyzdžiui, „Google“ per „Google AdSense“ programą) informaciją, įskaitant jūsų IP adresą, jūsų interneto paslaugų teikėją, naršyklę, kurią naudojote norėdami apsilankyti mūsų svetainėje, ir kai kuriais atvejais, ar turite įdiegtą „Flash“. Tai paprastai naudojama geografinio taikymo tikslais (pavyzdžiui, rodyti skelbimus apie prekių pardavimą jūsų mieste) arba rodant tam tikrus skelbimus remiantis tam tikromis lankomomis svetainėmis (pavyzdžiui, rodant pirkimo pranešimus tiems, kurie dažnai lankosi apsipirkimo svetainėse). </ P >
                <p> Galite išjungti arba selektyviai išjungti mūsų ar trečiųjų šalių slapukus naršyklės nustatymuose arba tvarkydami nustatymus tokiose programose kaip „Kaspersky“ ir kt. Tačiau tai gali turėti įtakos jūsų sąveikai su mūsų svetaine, taip pat su kitomis svetainėmis. Tai gali apimti negalėjimą prisijungti prie paslaugų ar programų, pavyzdžiui, prisijungti prie forumų ar paskyrų. </p>
<p> „Google“ yra vienas iš trečiųjų šalių teikėjų mūsų svetainėje. Ji taip pat naudoja slapukus, vadinamus DART slapukais, kad galėtų rodyti skelbimus mūsų svetainės lankytojams pagal jų apsilankymus svetainėje cursor.style ir kitose interneto svetainėse. Tačiau lankytojai gali atsisakyti naudoti DART slapukus apsilankę „Google“ reklamos ir turinio tinklo privatumo politikoje <a href="https://policies.google.com/technologies/ads"> šiuo adresu </a>. Kai kurie iš reklamuotojų mūsų svetainėje gali naudoti slapukus ir žiniatinklio švyturius. Kiekvienas iš mūsų reklamos partnerių turi savo privatumo politiką dėl savo politikos, susijusios su vartotojo duomenimis. Daugiau apie jų privatumo politiką galite paskaityti <a href="https://policies.google.com/technologies/ads"> čia </a>. </p>
                <p> Mūsų svetainė naudoja „Google Analytics“, „Google, Inc.“ žiniatinklio analizės paslaugą, 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com („Google Analytics“ arba „Google“). „Google Analytics“ naudoja slapukus, kurie saugomi jūsų kompiuteryje, kad būtų lengviau analizuoti jūsų naudojimąsi svetaine. Informacija, kurią generuoja šie slapukai, pvz., Laikas, vieta ir jūsų apsilankymų mūsų svetainėje dažnumas, įskaitant jūsų IP adresą, perduodama į „Google“ vietą JAV ir ten saugoma. Taip pat „Google“ gali perduoti šią informaciją trečiosioms šalims, jei to reikalauja įstatymai arba jei trečiosios šalys apdoroja šiuos duomenis „Google“ vardu. „Google“ teigia, kad niekada nesusies jūsų IP adreso su kitais „Google“ duomenimis. Galite užkirsti kelią slapukų nustatymui atitinkamai pakeisdami savo naršyklės programinės įrangos nustatymus, kaip nurodyta šioje Privatumo politikoje. Tačiau turėtumėte žinoti, kad tokiu būdu negalėsite visiškai pasinaudoti visomis mūsų svetainės funkcijomis. </p>
                <p> „Google Analytics“ taip pat naudoja elektroninius vaizdus, ​​žinomus kaip žiniatinklio švyturiai (kartais vadinami vieno pikselio GIF) ir yra naudojami su slapukais, norint sudaryti apibendrintą statistiką, kad būtų galima analizuoti mūsų svetainės naudojimą.
Galite rasti daugiau informacijos apie tai, kaip įdiegti naršyklės papildinį, į kurį jungiatės aukščiau esančioje <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> nuorodoje </a>.
Ši svetainė naudoja „Google Tag Manager“. Ši paslauga leidžia valdyti svetainės žymes per sąsają. „Google Tag Manager“ įgyvendina tik žymes. Tai reiškia, kad slapukai nenustatomi ir jokie asmeniniai duomenys neįrašomi. „Google Tag Manager“ paleidžia kitas žymes, kurios savo ruožtu gali įrašyti duomenis. Tačiau „Google Tag Manager“ neturi prieigos prie šių duomenų. Jei žymos buvo išjungtos domeno ar slapuko lygmeniu, jos išsaugomos visoms stebėjimo žymoms, jei jos įgyvendinamos naudojant „Google Tag Manager“. Daugiau apie „Google Tag Manager“ galite sužinoti apsilankę <a href="http://www.google.com/tagmanager/use-policy.html"> nuorodoje </a>. </p>
<p> Galite susipažinti su šiuo sąrašu, kad rastumėte kiekvieno „Cursor Style“ reklamos partnerio Privatumo politiką. Trečiųjų šalių skelbimų serveriai ar skelbimų tinklai naudoja tokias technologijas kaip slapukai, „JavaScript“ ar žiniatinklio švyturiai, kurie naudojami jų atitinkamuose skelbimuose ir nuorodose, kurie rodomi „Cursor Style“ ir siunčiami tiesiai į vartotojų naršyklę. Jie automatiškai gauna jūsų IP adresą, kai tai įvyksta. Šios technologijos naudojamos matuojant jų reklamos kampanijų efektyvumą ir (arba) individualizuojant reklamos turinį, kurį matote apsilankytose svetainėse. Atkreipkite dėmesį, kad „Cursor Style“ neturi prieigos prie šių slapukų, kuriuos naudoja trečiųjų šalių reklamuotojai, ir jų nekontroliuoja. „Cursor Style“ privatumo politika netaikoma kitiems reklamuotojams ar svetainėms. Todėl rekomenduojame peržiūrėti atitinkamą šių trečiųjų šalių skelbimų serverių privatumo politiką, kad gautumėte daugiau informacijos. Tai gali apimti jų metodus ir instrukcijas, kaip atsisakyti tam tikrų parinkčių. Nuorodas į šias trečiųjų šalių privatumo politikas galite rasti aukščiau arba trečiųjų šalių paslaugų svetainėse. </p>
                <p> Galite išjungti slapukus savo naršyklės nustatymuose. Norėdami sužinoti daugiau apie slapukų valdymą konkrečiose žiniatinklio naršyklėse, galite rasti atitinkamose naršyklių svetainėse. Kita mūsų prioriteto dalis yra pridėti vaikų apsaugą naudojant internetą. Raginame tėvus ir globėjus stebėti, dalyvauti ir (arba) stebėti ir nukreipti savo veiklą internete. „Cursor Style“ sąmoningai nerenka asmeninės informacijos iš jaunesnių nei 13 metų vaikų. Jei manote, kad jūsų vaikas pateikė tokią informaciją mūsų svetainėje, primygtinai rekomenduojame nedelsdami susisiekti su mumis ir mes padarysime viską, kad kuo greičiau pašalintume tokią informaciją iš savo įrašų. Ši Privatumo politika taikoma tik mūsų veiklai internete ir galioja mūsų svetainės lankytojams, atsižvelgiant į bendrinamą ir (arba) surinktą informaciją „Cursor Style“. Ši politika netaikoma jokiai informacijai, surinktai neprisijungus ar per kitus kanalus, o ne per šią svetainę. </p>
                <p> Daugiau apie slapukų naudojimą mūsų Paslaugoje galite perskaityti mūsų <a href="/cookie-policy"> Slapukų politikoje </a>. </p> ',
];
