<?php

return [
    'title' => 'Cursor Style - Mūsų produkto naudojimo sąlygos',
    'descr' => 'Naudojimosi sąlygos susitartos tarp jūsų ir „Cursor Style“ („Paslauga“, „mes“ arba „Paslauga“). Ši paslauga siūloma ir prieinama tik 13 metų ir vyresniems vartotojams tik asmeniniam, o ne komerciniam naudojimui.',
    'text' => '<h2>Paslaugos sąlygos</h2>
<h3> PRAŠOME PERSKAITYTI ŠIAS SĄLYGAS PRIEŠ NAUDOJANT SVETAINĘ IR PLĖTINĮ.</h3>
<p> Šios naudojimo sąlygos sudaromos tarp jūsų ir „Cursor Style“ („Paslauga“, „mes“ arba „Paslauga“). Šios sąlygos bei bet kokie dokumentai, į kuriuos aiškiai nurodoma nuoroda (toliau kartu – „Naudojimo sąlygos“), reguliuoja jūsų prieigą ir naudojimąsi cursor.style svetaine ir jos naršyklės plėtiniais, įskaitant bet kokį turinį, funkcionalumą ir paslaugas, siūlomas per mūsų paslaugą ar joje (toliau – „Paslauga“). </p>
<p> Naudodamiesi svetaine ar plėtiniu, jūs sutinkate ir įsipareigojate laikytis šių Naudojimo sąlygų. Jei nesutinkate su šiomis Naudojimo sąlygomis ar mūsų <a href="/privacy">Privatumo politika</a>, neturėtumėte pasiekti ar naudotis Svetaine ir Plėtiniu.</p>
<p> Ši paslauga siūloma ir prieinama tik 13 metų ir vyresniems vartotojams tik asmeniniam naudojimui, o ne komerciniam naudojimui. Naudodamiesi šia Paslauga, jūs pareiškiate ir garantuojate, kad esate (I) 13 metų ar vyresnis, (II) jums nedraudžiama naudotis Svetainėmis pagal galiojančius įstatymus ir (III) naudojate Paslaugą tik savo asmeniniams poreikiams. Jei neatitinkate šių reikalavimų, neturėtumėte pasiekti ar naudotis Paslauga. </p>
<p> Mes galime peržiūrėti ir atnaujinti šias Naudojimo sąlygas savo nuožiūra. Visi pakeitimai įsigalioja iškart po jų paskelbimo. Tolesnis Paslaugos naudojimas po peržiūrėtų Naudojimo sąlygų paskelbimo reiškia, kad sutinkate su pakeitimais. Tikimasi, kad dažnai lankysitės šiame puslapyje, kad neatsiliktumėte nuo bet kokių pakeitimų, nes jie jums yra privalomi. </p>
<p> Mes pasiliekame teisę atsiimti ar pakeisti šią Svetainę ir Plėtinį, bet kokias paslaugas ar medžiagas, kurias teikiame Svetainėje ir Plėtinyje, savo nuožiūra, be įspėjimo. Mes negarantuojame, kad mūsų svetainė, plėtinys ar bet koks jo turinys visada bus prieinamas ar bus nenutrūkstamas. Mes nebūsime atsakingi, jei dėl bet kokios priežasties visa ar bet kuri Paslaugos dalis bus nepasiekiama bet kuriuo metu ar bet kuriuo laikotarpiu. Kartais galime apriboti prieigą prie tam tikrų Svetainės ar Plėtinio dalių arba visos Paslaugos visiems vartotojams.</p>
<p> Jūs esate atsakingi už visų būtinų priemonių ėmimąsi, kad turėtumėte prieigą prie Paslaugos. Užtikrinimas, kad visi asmenys, kurie pasiekia Paslaugą per jūsų interneto ryšį, žino apie šias Naudojimo sąlygas ir jų laikosi. Norint pasiekti Paslaugą ar kai kuriuos jos siūlomus išteklius, jūsų gali būti paprašyta pateikti tam tikrą informaciją ar kitą informaciją. Jūs sutinkate, kad visai informacijai, kurią mums pateikiate naudodamiesi šia Paslauga ar kitaip, įskaitant, bet neapsiribojant, bet kokių interaktyvių funkcijų naudojimą Paslaugoje, taikoma mūsų <a href="/privacy"> Privatumo politika </a> ir sutinkate su visais veiksmais, kuriuos mes atliekame dėl jūsų informacijos, laikydamiesi mūsų <a href="/privacy"> Privatumo politikos </a>. </p>
<p> Turite būti ypač atsargūs įvesdami asmeninę informaciją į Paslaugą viešame ar bendrame kompiuteryje, kad kiti negalėtų peržiūrėti ar įrašyti jūsų asmeninės informacijos. Svetainė, plėtinys ir visas jo turinys, funkcijos ir funkcijos (įskaitant, bet neapsiribojant, visą informaciją, plėtinį, tekstą, vaizdus, ​​vaizdus ir žymeklius, taip pat jų dizainą, pasirinkimą ir patalpinimą) priklauso „Cursor Style“, jos licencijų išdavėjams ar kitiems tokių medžiagų tiekėjams yra saugoma autorių teisių, prekės ženklo, patento, komercinės paslapties ir kitų intelektinės nuosavybės įstatymų ar nuosavybės teisių. </p>
<p> Šios Naudojimo sąlygos leidžia jums naudoti Svetaines tik asmeniniam, nekomerciniam naudojimui. Negalite atgaminti, platinti, modifikuoti, kurti išvestinių kūrinių, pakartotinai skelbti, atsisiųsti, saugoti ar perduoti jokių medžiagų mūsų Svetainėje, išskyrus šiuos atvejus: galite jas naudoti asmeniniams poreikiams, galite atspausdinti ar atsisiųsti vieną pagrįsto dydžio Svetainės ir Plėtinio ar jų turinio kopiją asmeniniam, nekomerciniam naudojimui, o ne tolesniam atgaminimui, publikavimui ar platinimui. </p>
<p> Negalite keisti jokių šios svetainės ar plėtinio ir jų turinio medžiagų kopijų. Ištrinti ar modifikuoti bet kuriuos autorių teisių, prekės ženklų ar kitus nuosavybės pranešimus iš šios svetainės ir plėtinio kopijų. Neturite turėti prieigos ar naudoti komerciniais tikslais jokios Svetainių ar plėtinių dalies, taip pat jokių paslaugų ar medžiagų, kurias galima rasti per Svetainę ar Plėtinį. </p>
<p> Jei norite naudoti bet kokią medžiagą svetainėse ar plėtiniuose, išskyrus nurodytą šioje skiltyje, išsiųskite užklausą „Chrome“ internetinės parduotuvės palaikymo puslapyje. </p>
<p> Jei spausdinate, kopijuojate, modifikuojate, atsisiunčiate ar kitaip naudojate ar suteikiate bet kuriam kitam asmeniui prieigą prie bet kurios Svetainės ar Plėtinio dalies pažeisdami Naudojimo sąlygas, jūsų teisė naudotis Svetaine ir Plėtiniu nedelsiant nutraukiama, ir turite , savo nuožiūra, grąžinti ar sunaikinti visas turimas medžiagų kopijas. Bet koks plėtinio svetainės naudojimas, kuris nėra aiškiai leidžiamas šiomis Naudojimo sąlygomis, pažeidžia šias Naudojimo sąlygas ir gali pažeisti autorių teises, prekės ženklus ir kitus įstatymus. </p>
<p> Pavadinimas „Cursor Style“, logotipas „Cursor Style“ ir visi susiję pavadinimai, logotipai, vaizdai, žymekliai ir paslaugų pavadinimai, dizainas ir šūkiai yra „Cursor Style“ prekės ženklai arba jo patronuojančių įmonių ar licencijų išdavėjų prekės ženklai. Negalite naudoti tokių ženklų be išankstinio rašytinio Paslaugos leidimo. Visi kiti pavadinimai, logotipai, produktų ir paslaugų pavadinimai, dizainas ir šūkiai šioje svetainėje ir plėtinyje yra atitinkamų savininkų prekės ženklai. Paslauga galite naudotis tik teisėtais tikslais ir laikydamiesi šių Naudojimo sąlygų. </p>
<h3> Jūs sutinkate nenaudoti Paslaugos: </h3>
<ul>
<li> Jokiu būdu, kuris pažeidžia bet kokius taikomus federalinius, regioninius, vietos ar tarptautinius įstatymus ar kitus teisės aktus (įskaitant, bet neapsiribojant, visus duomenų ar programinės įrangos eksporto į Rusiją ir kitas šalis įstatymus). </li>
<li> Siekiant išnaudoti, pakenkti ar bandyti naudoti ar pakenkti nepilnamečiams, juos paveikti netinkamu turiniu, prašyti informacijos, kuri juos identifikuoja, ar kitaip. </li>
<li> Siųsti, sąmoningai gauti, atsisiųsti, naudoti ar pakartotinai naudoti bet kokią medžiagą, kuri neatitinka šių Naudojimo sąlygų. </li>
<li> Perduoti ar pirkti bet kokių reklaminių ar reklamos medžiagų siuntimą be išankstinio rašytinio mūsų sutikimo, įskaitant bet kokius „neprašytus laiškus“, „grandininės grandinėlės“ ar „šlamšto“ ar bet kokius kitus panašius pasiūlymus. </li>
<li> Norint apsimesti ar bandyti apsimesti „Cursor Style“ darbuotoju, kitu vartotoju ar bet kuriuo kitu asmeniu ar organizacija (įskaitant, bet neapsiribojant, naudojant el. pašto adresus ar slapyvardžius, susijusius su bet kuriuo iš aukščiau minėtų). </ li >
<li> Dalyvavimas bet kokiuose kituose veiksmuose, kurie riboja ar trukdo Paslaugos naudojimui ar bet kurio naudojimui, arba kurie, kaip mes nustatome, gali pakenkti Paslaugai ar Paslaugos vartotojams arba juos įpareigoti. </li> </ul>
<h3> Be to, sutinkate NE: </h3>
<ul>
<li> Naudoti Paslaugą bet kokiu būdu, kuris gali išjungti, perkrauti, sugadinti ar pabloginti svetainės veikimą, išplėsti ar trukdyti bet kurios kitos šalies naudojimuisi Paslauga, įskaitant jos galimybę dalyvauti realaus laiko veiksmuose per Paslaugą. </li>
<li> Naudoti bet kokius automatizavimo įrankius, procesus ar priemones, norint patekti į Paslaugą jokiais tikslais, įskaitant bet kokios medžiagos stebėjimą ar kopijavimą Paslaugoje. </li>
<li> Naudoti jokį rankinį procesą, norint sekti ar kopijuoti bet kurią medžiagą Paslaugoje ar bet kokiais kitais neteisėtais tikslais be išankstinio rašytinio mūsų sutikimo. </li>
<li> Naudoti bet kokį įrenginį, programinę įrangą ar procedūras, kurios trukdo įprastam Paslaugos veikimui. </li>
<li> Įdiegti virusus, trojos arklius, kirminus, logines bombas ar kitas medžiagas, kurios yra kenksmingos ar technologiškai žalingos. </li>
<li> Bandyti gauti neteisėtą prieigą, trukdyti, sugadinti ar sutrikdyti bet kurią Paslaugos dalį, serverį, kuriame saugoma Paslauga, ar bet kurį serverį, kompiuterį ar duomenų bazę, prijungtą prie Paslaugos. </li>
<li> Užpulti Paslaugą naudojant atsisakymo paslaugos ataką arba paskirstytą atsisakymo paslaugos ataką. </li> </ul>
<p> Informacija, pateikta per Paslaugą ar per ją, pateikiama tik bendrais informaciniais tikslais. Mes negarantuojame šios informacijos tikslumo, išsamumo ar naudingumo. Jūs pasikliaujate tokia informacija tik savo rizika. Mes atsisakome visos atsakomybės, atsirandančios dėl to, kad jūs, kiti Paslaugos lankytojai ar kas nors, kas galėtų būti informuoti apie bet kokį jų turinį, priklauso nuo tokios medžiagos. </p>
<p> Ši Paslauga apima trečiųjų šalių pateiktą turinį, įskaitant medžiagas, kurias pateikė kiti vartotojai ir trečiųjų šalių licencijų išdavėjai, sindikatoriai, agregatoriai ir (arba) ataskaitų teikimo tarnybos. Visos deklaracijos ir (arba) nuomonės, išreikštos šiose medžiagose, taip pat visi straipsniai ir atsakymai į klausimus ir kitas turinys, išskyrus Paslaugos pateiktą turinį, yra tik asmens ar organizacijos, teikiančios šias medžiagas, nuomonės ir atsakomybė. Šios medžiagos nebūtinai atspindi Paslaugoje išreikštas nuomones. Mes nesame atsakingi jums ar jokiai trečiajai šaliai už bet kokio trečiųjų šalių pateikto turinio ar medžiagos tikslumą. </p>
<p> Mes galime retkarčiais atnaujinti Paslaugos turinį, tačiau jos turinys nebūtinai yra išsamus ar aktualus. Bet kuri medžiaga Paslaugoje bet kuriuo metu gali būti pasenusi, ir mes neprivalome atnaujinti tokios medžiagos. Mes galime atnaujinti, keisti, modifikuoti informaciją ir turinį Svetainėje ir Plėtinyje, atlikti bet kokius pakeitimus ir atnaujinimus pagal savo sprendimą. </p>
<p> Visa informacija, kurią renkame šioje Paslaugoje, priklauso mūsų Privatumo politikai. Naudodamiesi Paslauga, jūs sutinkate su visais mūsų veiksmais, susijusiais su jūsų informacija, remiantis <a href="/privacy"> Privatumo politika </a>. </p>
<p> Papildomos sąlygos taip pat gali būti taikomos tam tikroms Paslaugos dalims, paslaugoms ar funkcijoms. Visos tokios papildomos sąlygos ir nuostatos yra įtrauktos nuoroda į šias Naudojimo sąlygas.
Jūs galite susieti su mūsų svetaine ar plėtiniu, jei tai darote sąžiningu ir teisėtu būdu ir nekenkiate mūsų reputacijai ar ją naudojate, bet neturėtumėte nustatyti nuorodos taip, kad būtų siūloma kokia nors asociacijos, pritarimo ar patvirtinimo forma iš mūsų pusės be mūsų rašytinio sutikimo. </p>
<p> Paslaugoje yra nuorodų į kitas svetaines ir išteklius, kuriuos teikia trečiosios šalys, šios nuorodos pateikiamos tik jūsų patogumui. Tai apima nuorodas, esančias reklamose, įskaitant reklamos juostas internete ir remiamas nuorodas. Mes nekontroliuojame šių svetainių ar išteklių turinio ir nesame atsakingi už juos ar už bet kokius nuostolius ar žalą, kuri gali atsirasti dėl jų naudojimo. Jei nuspręsite pasiekti bet kurias trečiųjų šalių svetaines, susijusias su šia Paslauga, tai darote savo rizika ir vadovaudamiesi tokių svetainių naudojimo sąlygomis. Mes pasiliekame teisę atšaukti leidimą susieti be išankstinio įspėjimo. </p>
<p> Jūs suprantate, kad mes negalime ir negarantuojame, kad failai, kuriuos galima atsisiųsti per internetą ar svetainėse, neturės virusų ar kito kenksmingo kodo. Jūs esate atsakingi už procedūrų ir kontrolės taškų, kurie yra pakankami, įgyvendinimą, kad patenkintumėte savo specialius reikalavimus dėl antivirusinės apsaugos ir duomenų įvesties ir išvesties tikslumo, taip pat už išorinių priemonių išlaikymą, kad būtų galima atkurti visus prarastus duomenis. MES NEBŪSIME ATSAKINGI UŽ JOKIĄ ŽALĄ AR SUŽALOJIMĄ, ATSIRADUSIĄ ATSISAKYMO PASLAUGOS, VIRUSŲ AR KITOS TECHNOLOGIJOS ŽALOS, GAUTOS PER PASLAUGĄ AR ATSISIŲSDANT BET KOKIĄ MEDŽIAGĄ, PASKELBTĄ ŠIOJE AR BET KOKIOSE SVETAINĖSE, SUSIJUSIĄ SU GALIU UŽKRĖSTI AR PABLOGINTI JŪSŲ KOMPIUTERINĘ ĮRANGĄ, KOMPIUTERINĘ PROGRAMINĘ ĮRANGĄ, DUOMENIS. </p>
<p> JŪS NAUDOJATE PASLAUGĄ, JO TURINĮ IR BET KOKIAS PASLAUGAS AR PREKES, GAUTAS PER PASLAUGAS, TIK SAVO RIZIKA. PASLAUGA, JO TURINYS IR BET KOKIOS PASLAUGOS AR PREKĖS, GAUTOS PER SVETAINĘ IR PLĖTINĮ, YRA TEIKIAMOS „KAIP YRA“ IR „KAIP GALIMA“ SĄLYGOMIS BE JOKIOS GARANTIJOS. BET KOKS SU PASLAUGA SUSIJĘS ASMUO NESUTEIKIA JOKIOS GARANTIJOS AR ATSTOVAVIMO DĖL PASLAUGOS IŠSANOS, SAUGUMO, PATIKIMUMO, KOKYBĖS, TIKSLUMO AR PRIEINAMUMO. BE PIRMIAU PATEIKTŲ APRIBOJIMŲ, JOKS „CURSOR STYLE“ AR SU „CURSOR STYLE“ SUSIJĘ ATSTOVAUJA NESUTEIKIA GARANTIJOS, KAD SVETAINĖ, PLĖTINYS, JO TURINYS AR BET KOKS REMONTAS TURI BŪTI ANKSTESNIS PRIEINAMAS. PADARYTA, KAD MŪSŲ PLĖTINYS, SVETAINĖ AR SERVERIS, KURIS JĮ DĖSTO, BUS BE VIRUSŲ AR KITŲ KENKŠMINGŲ KOMPONENTŲ AR ŠI SVETAINĖ AR BET KOKIOS PASLAUGOS AR PREKĖS, ATLIEKTA, PREFERUOTA.
<p> JOKIU ATVEJU PASLAUGA, JO FILIALAI AR LICENCIJOS, PASLAUGOS DARBUOTOJAI, AGENTAI, PAREIGŪNAI AR DIREKTORIAI NEATSAKO UŽ JOKIĄ ŽALĄ, MES PASLAUGAJOKIAI ATSAKOMYBEI. AR KITOS TOKIOS SVETAINĖS AR BET KOKIOS PASLAUGOS AR PREKĖS, GAUTOS IŠ PASLAUGOS AR KITŲ SVETAINIŲ, ĮSKAITANT BET KOKIĄ TIESIOGINĘ, SPECIALIĄ AR PADARINIŲ ŽALĄ, ĮSKAITANT ASMENIS SUŽEIDIMUS, emocinius sutrikimus, ŽALĄ AR TIKIMĄ TAUPYMĄ, NAUDOJIMO, DUOMENŲ AR KITUS SĄLYGUS. APIBRĖŽIMAS NETURI ĮTAKOS JOKIAI ATSAKOMYBEI, KURI NEGALĖTŲ BŪTI PANAUDOTA AR APRIBOJAMA PAGAL TAIKOMUS ĮSTATYMUS, KURI GALI BŪTI SUKČIAU. </p>
<p> Jūs sutinkate apsaugoti, atlyginti ir nutildyti „Cursor Style“, jo filialus, licencijų išdavėjus ir paslaugų teikėjus, taip pat jo ir jų atitinkamus pareigūnus, direktorius, darbuotojus, rangovus, agentus, licencijų išdavėjus, tiekėjus, perėmėjus ir iš bet kokių pretenzijų ir atsakomybės, teismų sprendimų praradimo, išlaidų, išlaidų ar komisinių (įskaitant advokatų honorarus), atsirandančių dėl jūsų Naudojimo sąlygų pažeidimo ar naudojimosi Paslauga, įskaitant, bet neapsiribojant, bet kokio turinio, paslaugų ir produktų naudojimo Svetainėje ar Plėtiniuose, išskyrus tuos atvejus, kai tai yra aiškiai numatyta šiose Naudojimo sąlygose, ar jūsų naudojimo bet kurios iš Paslaugos gautos informacijos. </p>
<p> Jei bet kuri šių Naudojimo sąlygų nuostata yra negaliojanti, neteisėta ar neįgyvendinama teismo ar kito kompetentingos jurisdikcijos teismo dėl bet kokios priežasties, tokia nuostata turėtų būti panaikinta arba apribota iki minimumo, kad likusios Naudojimo sąlygų nuostatos išliktų visapusiškai. Naudojimo sąlygos, mūsų Privatumo politika ir įvykių registravimo sąlygos sudaro vienintelį ir visą susitarimą tarp jūsų ir „Cursor Style“ dėl Paslaugos ir pakeičia visus ankstesnius ir tuo pačiu metu sudarytus susitarimus, susitarimus, pareiškimus ir garantijas, tiek rašytinius, tiek žodinius, dėl Paslaugos. </p>
<p> Visos apžvalgos, komentarai, techninės pagalbos užklausos ir kiti pranešimai, susiję su Paslauga, turėtų būti nukreipti į „Cursor Style“ palaikymo puslapį „Chrome“ internetinėje parduotuvėje. </p> ',
];
