<?php

return [
    'halo_descr' => 'Halo är en stridsfantasi-mediafranchise skapad av Bungie. Baserat på den ursprungliga trilogin av förstapersonsskjutare-videospel. Handlingen kretsar kring händelserna i Master Chiefs liv, en av en grupp supersoldater med kodnamnet Spartans, och hans följeslagare, den artificiella intelligensen Cortana. Spelens framgång har lett till utvidgningen av franchisen till andra medier: Halo-universumet omfattar för närvarande många böcker, grafiska romaner, serier, kortfilmer, animationer och spelfilmer.',
    'halo_short_descr' => 'Tryck på artefaktpekaren, kanske är du den utvalde.',
    'halo' => 'HALO',
    'lol_surprise_descr' => 'LOL Surprise-dockor blev kära i barn och vann deras hjärtan från de första minuterna. Och detta är inte förvånande, eftersom en sådan framgång bygger på ett mysterium, förväntan om ett mirakel, en trevlig överraskning, som glädjer inte bara barn, utan också deras föräldrar. Hemligheten med gåvan avslöjas för barnet först efter den slutliga uppackningen. I vilket fall som helst är LOL-dockor en attraktiv design, intriger, ett stort antal fantastiska och realistiska tillbehör och trevliga småsaker, samt den högsta kvaliteten på produktionen och detaljerna i leksaken.',
    'lol_surprise_short_descr' => 'Häftiga små varelser för finsmakare av vackra överraskningar',
    'lol_surprise' => 'L.O.L. Surprise',
    'squid_game_descr' => 'Serien kretsar kring en tävling där 456 spelare, som alla befinner sig i djup ekonomisk skuld, riskerar sina liv för att spela en serie dödliga barnspel för chansen att vinna ett pris på en miljard. Inuti väntar ett lockande pris med dödligt höga insatser. Titeln på serien är hämtad från ett liknande koreanskt barnspel. Hwang hade fått idén baserat på sina egna ekonomiska svårigheter tidigt i livet, såväl som klasskillnaderna i Sydkorea och kapitalismen.',
    'squid_game_short_descr' => 'Välj rätt spelaransikte när du satsar allt',
    'squid_game' => 'Squid Game',
    'harry_potter_descr' => 'Harry James Potter är huvudpersonen i en serie romaner av den engelska författaren JK Rowling. På sin elvaårsdag får Harry veta att han är en trollkarl och är ämnad för en plats på Hogwarts skola för häxkonst och trolldom, där han kommer att utöva magi under ledning av rektor Albus Dumbledore och andra skolprofessorer. Harry upptäcker också att han redan är känd i hela romanens magiska samfund, och att hans öde är förbundet med Voldemorts öde, en farlig mörk magiker.',
    'harry_potter_short_descr' => 'Vad kommer du att göra med en trollstav från samlingen av Harry Potter-markörer',
    'harry_potter' => 'Harry Potter',
    'marvel_comics_descr' => 'Marvel Comics är ett serietidningsförlag känt för att skapa anmärkningsvärda superhjältar som Spider-Man, Iron Man, Captain America, Hulk, Thor, Avengers, Guardians of the Galaxy, X-Men, Fantastic Four och Deadpool. Marvels mest kända skurkar inkluderar Green Goblin, Red Skull, Loki, Thanos, Ultron, Doctor Doom och Magneto. Marvel Comics och DC Comics har samarbetat om flera crossover-projekt tillsammans och var också med och grundade det avsiktligt kortlivade Amalgam Comics-imprintern.',
    'marvel_comics_short_descr' => 'Superhjälten bor i oss alla - välj din egen',
    'marvel_comics' => 'Marvel Comics',
    'cookie_run_kingdom_descr' => 'Välkommen tillbaka till Kak-riket i Cookie Run: Kingdom av Devsisters, det bedårande strategiska RPG-spelet som utspelar sig i Cookie Run-universumet. Nu när GingerBrave har flytt den onda häxans ugn, är det dags för honom att bygga ett lag av Kakor och ge sig ut på en uppgift att återuppbygga det fallna Kak-riket. Upptäck sanningen bakom Rikets fall och sätt ihop en trupp av Rikets mäktigaste Kakor för att besegra de mörka krafterna som vill stoppa GingerBrave från att uppfylla sitt öde.',
    'cookie_run_kingdom_short_descr' => 'Små krigare direkt från ugnen',
    'cookie_run_kingdom' => 'Cookie Run Kingdom',
    'genshin_impact_descr' => 'Genshin Impact är ett äventyrsspel i en öppen värld. Det betyder att ett nytt, härligt landskap väntar dig på andra sidan floden eller berget, du behöver bara använda din energi klokt. Om du stöter på en vandrande älva eller en konstig mekanism, våga och försök att reda ut deras mystik. Men vad de lovar - problem eller en trevlig överraskning - bara du kan ta reda på! På den stora kontinenten Teyvat kommer du att besöka sju kungadömen, hitta följeslagare med olika färdigheter och kämpa mot mäktiga fiender i jakten på en saknad älskad.',
    'genshin_impact_short_descr' => 'Bli elementmästaren över de sju kungadömena',
    'genshin_impact' => 'Genshin Impact',
    'frozen_descr' => 'När en uråldrig profetia slår in och kungariket störtar in i vinterns famn, beger sig tre orädda hjältar - prinsessan Anna, modige Kristoffer och hans trogna ren Sven - till bergen för att hitta Annas syster, Elsa, som kan ta bort den kyliga förtrollningen från landet. Längs vägen väntar många svåra överraskningar och spännande äventyr på dem. Möte med mystiska troll, möte med en charmig snögubbe vid namn Olof, bergstoppar brantare än Everest och en massa magi. Hjältarna måste motstå de mäktiga elementen för att rädda kungariket och de som är kära för dem.',
    'frozen_short_descr' => 'Att bryta isen är enkelt med samlingen av Frozen-pekare',
    'frozen' => 'Frozen',
    'stranger_things_short_descr' => 'Vad händer härnäst? - Stranger Things 4-markörer',
    'stranger_things' => 'Stranger Things 4',
    'roblox_bed_wars_descr' => 'Bed Wars är ett originalläge som först dök upp i Minecraft. Uppgiften för spelarna var att användaren skulle skydda sin bas och säng.

Roblox ger mer spännande spel varje dag och BedWars är inget undantag. Och grejen är att om du älskar bed wars och försvarar dig i ditt rum, är detta titeln för dig eftersom den tar dig tillbaka till barndomen, om än digitalt den här gången.

Allt du behöver göra är att försvara din säng från angripare med din partner. Du går in i en lobby, väljer vem du ska spela med, och voila, det är bara en fråga om skydd.

Visst, när det gäller försvar kommer du att ha vissa problem och det finns vissa resurser, föremål och prylar som hjälper dig att vinna. Till exempel exklusiva skins som du hittar i Bed Wars-markörkollektionen.',
    'roblox_bed_wars_short_descr' => 'Skydda din säng med Roblox Bed Wars-markörer',
    'roblox_bed_wars' => 'Roblox Bed Wars',
    'naruto_anime_descr' => 'På Naruto Uzumakis födelsedag attackerade en legendarisk demon, Niosvansfoxen, en by som heter Konoha. Den fjärde Hokage räddade till priset av sitt liv byn genom att försegla demonen i den nyfödde Naruto, ovetande om att döma honom till ett liv av hat från sina bybor.
Trots sin brist på talang inom många områden av ninjutsu, rastlöshet och snobberi, drömmer Naruto om att bli Hokage, den starkaste ninjan i byn. I önskan om den uppskattning han inte fick, arbetar han hårt och tränar tillsammans med sina lagkamrater Sasuke Uchiha och Sakura Haruno, såväl som sin mentor Kakashi Hatake. Han och hans partners kommer att behöva gå igenom mycket på vägen till sina kära drömmar: strider, kärlek, vänskap, svek, törst efter makt. En samling Naruto anime-markörer hjälper dig att navigera på din egen väg!',
    'naruto_anime_short_descr' => 'Gå din ninja-väg med Naruto anime-markörer',
    'naruto_anime' => 'Naruto anime',
    'demon_slayer_anime_descr' => 'Handlingen utspelar sig under Taisho-eran. Ända sedan urminnes tider har det funnits rykten om att humanoidiska demoner lever i skogen, som livnär sig på människor och vandrar på natten och letar efter ett nytt offer. Men... det är bara en legend, eller hur?..

Tanjiro Kamado är den äldsta sonen i familjen, som förlorade sin far och tog hand om sin familj. En dag går han till en närliggande stad för att sälja kol. När han återvänder på morgonen upptäcker killen en hemsk bild framför sig: alla släktingar dödades brutalt, och den enda överlevande är Nezuko, en yngre syster som förvandlats till en demon, men som ännu inte har förlorat all sin mänsklighet.

Från och med detta ögonblick börjar Tanjiro och Nezuko en lång och farlig resa, där pojken tänker hitta mördaren och hitta ett sätt att bota sin syster. Men är barnen kapabla att övervinna alla svårigheter och återvända hem? Du vet redan svaret, och om inte - ställ hellre in markörerna Demon Slayer, med karaktärer från en av de mest populära mangan.',
    'demon_slayer_anime_short_descr' => 'Demon Slayer-markörer - för riktiga nattjägare',
    'demon_slayer_anime' => 'Demon Slayer anime',
    'bts_descr' => 'BTS är en sjumanna pojkband under BigHit Music. De debuterade den 13 juni 2013 med singeln "No More Dream". I Japan gjorde de sin debut den 24 december 2014 med studioalbumet Wake Up.

Gruppens namn kommer från det koreanska uttrycket Bangtan Sonyeondan, vilket betyder "skottsäkra pojkscouter". Enligt J Hope betyder namnet bandets önskan att blockera de stereotyper, kritiker och förväntningar som riktas mot tonåringar som kulor.

Samlingen av markörer tillägnad gruppen inkluderar alla medlemmar i gruppen, här Kim Nam Joon-markören (även känd som RM), Kim Seok Jin-markören (Jin), Min Yoongi-markören (Suga), Jung Ho Suk-markören (J-Hope), Park Ji Min-markören (Jimin), Kim Tae Hyun-markören (V) och Jeon Jungkook-markören (Jungkook).',
    'bts_short_descr' => 'Möt dina idoler med BTS-markörer',
    'bts' => 'BTS',
    'miraculous_short_descr' => 'Anslut dig till superhjältarnas led med samlingen av Ladybug och Cat Noir-markörer',
    'miraculous' => 'Miraculous: Berättelser om Ladybug & Cat Noir',
    'talking_tom_descr' => 'Serien följer det dagliga livet för Talking Tom och hans vänner. Tom och hans nördiga affärspartner Ben utvecklar ständigt mobilappar och andra uppfinningar för att uppnå berömmelse och förmögenhet och försöker visa sig för världen, men detta slår alltid tillbaka. Toms flickvän, Angela, försöker vara sångare, oavsett vad hon gör för att uppnå det. Toms granne, Ginger, kommer väldigt ofta in här för att spela spratt med bus i ärmen. Dumma bästa vännen och rumskamraten Hank är en hemmaboende som tittar VÄLDIGT på TV. Och den före detta dissidenten popstjärnan Becca Sparkles har blivit Angelas nya rumskamrat och verkar ha blivit kär i Hank. Oavsett hur dåliga saker är av alla former och storlekar, vare sig det är den onda VD:n, Toms mystiska nya granne eller bara en olycka i Bens nya skapelse, kommer gänget att ha kul oavsett vad, och alltid komma ihåg en sak som håller dem samman: vänskapen tar aldrig slut, precis som vår kärlek till karaktärerna i serien aldrig tar slut, så nu kan du ställa in dig själv Talking Tom-markören eller Ben-markören, eller kanske Angela-markören, Oliver-markören!',
    'talking_tom_short_descr' => 'Låt oss prata om din favoritkaraktär i Talking Tom Cursor Collection',
    'talking_tom' => 'Talking Tom and Friends',
    'lego_descr' => 'Företaget LEGO Group grundades 1932 och bestod då av endast 7 personer. LEGO-teamets mål var att skapa leksaker som utvecklar ett barns kreativitet, fantasi och uppfinningsrikedom. En fantastisk sak, sedan starten 1949, har LEGO-elementen i alla deras varianter förblivit kompatibla med varandra. Alla föremål som skapats senare är fortfarande kompatibla med föremål som släpps idag, trots förändringar i design och form genom åren.

En LEGO-kloss är en bas, som är ett ihåligt plastblock som ansluts till andra liknande klossar. Men LEGO-set innehåller också andra delar, hjul, figurer, plattformar och till och med elektroniska kretsar med sensorer och elmotorer. Du kan samla modeller av bilar, flygplan, tåg, fartyg, byggnader, robotar. LEGO håller sig till idén om modularitet, vilket tydligt visar barn hur man löser vissa problem, utvecklar fantasi, finmotorik i händer och monteringsfärdigheter. LEGO-klossar är tillverkade med otrolig precision och passar perfekt ihop för en fantastisk precision på 10 mikron.

Nyligen har många populära 3D-animerade LEGO-berättelser skapats, där karaktärerna från seten kommer till liv och blir deltagare i otroliga äventyr. Om du vill ha en cool markör hittar du många karaktärer från LEGO-TV-serien och animerade filmer i vår LEGO Cursors-kollektion. Lego Ninjago Cursor, Lego Batman Cursor, Lego Ninjago Cursor, Lego Wyldstyle Cursor och många fler.',
    'lego_short_descr' => 'Bygg din drömwebbläsare med Lego-markörsamlingen',
    'lego' => 'Lego',
    'hollow-knight_descr' => 'Efter framgångsrik Kickstarter-finansiering, år 2017, släppte Team Cherry multiplatform-PC-spelet Hollow Knight. Detta är berättelsen om en namnlös riddare och hans upptäckter i Hallownest-insektriket. Spelet erkändes med rätta som ett av de bästa i metroidvania-genren.

Spelupplägget i Hollow Knight är baserat på utforskning av spelvärlden. Övervinna hinder, lösa pussel och hitta hemligheter, samt slåss mot fiender. Spelaren har en unik uppsättning förbättringar och knep för att utforska världen och slåss i strider. Genom att röra sig från zon till zon besegrar spelaren bossar och får de nödvändiga förbättringarna för att avancera vidare. Som ett resultat måste spelare besöka de redan passerade områdena för att hitta hemligheter och gå igenom berättelsen. Och det är också spännande eftersom zonerna förändras varje gång och ger nya överraskningar och upplevelser. Spelet kan spelas på olika sätt, eftersom det finns flera olika vägar mellan zonerna. Genom att gå igenom berättelsen öppnar du zonkartan, men först måste du få kartan.

Hjältens huvudsakliga vapen är en spik, som påminner om ett svärd, vapen kan förbättras med en smed, samt lära sig olika färdigheter i att använda vapen, vilket utökar variationen av attacker. Genom att attackera fiender ackumulerar du en speciell resurs, som senare kan användas för förbättringar eller läkning.
Ha kul med att spela Hollow Knight och glöm inte våra Hollow Knight-markörer med din favoritkaraktär. Vår samling inkluderar Mister Mushroom Cursor, Quirrel Cursor, Hornet Needle Cursor, Old Nail Cursor, Myla Cursor och andra.',
    'hollow-knight_short_descr' => 'Försök att inte gå vilse i insekternas rike med hjälp av Hollow Knight-samlingen av markörer',
    'hollow-knight' => 'Hollow Knight',
    'henry-stickmin_descr' => 'Henry Stickman är huvudkaraktären i serien. Stikmin, tidigare namnlös, började som en mindre tjuv, med en önskan om att snabbt tjäna lätta pengar. Men efter att ha flytt från West Mesa-fängelset sker många förändringar i hans liv, och han blir en berömd brottsling efter att ha stulit Tunisian Diamond. Henry har ett val - att bli en framgångsrik statlig agent, prisjägare, ledare för en kriminell organisation, cyborg, eller fortsätta den kriminella vägen ensam. Spelet glädjer fans av genren med många äventyr och mysterier, och du hittar vår nya samling av Henry Stickman-pekare med dess roliga karaktärer, inklusive Henry Stickmin-pekare, Charles Calvin-pekare, Reginald Copperbottom-pekare, Höger Hand-pekare, Ellie Rose-pekare och andra!',
    'henry-stickmin_short_descr' => 'Planera din flykt från tristess med Henry Stickman Cursors Collection',
    'henry-stickmin' => 'Henry Stickmin',
    'adopt-me_descr' => 'Det mycket populära onlinespelet Adopt Me lanserades 2017 och blev det mest populära på Roblox-spelplattformen. Kärnan i spelet är mycket enkel - få ägg med husdjur och ta hand om dem.

Virtuella husdjur är indelade i 5 klasser, vissa av dem är mycket sällsynta och dyra, medan andra är mycket enkla att få. Detta är Unga grupper, såsom den blå hunden, vanliga, sällsynta markören, till exempel Adopt Me Monkey-musmarkören, samt ultra-sällsynta, såsom Koala-markören och Legendariska, Dragon-markören och Accept me unicorn. Om spelaren har fyra vuxna husdjur av samma typ kan de kombineras till ett neonhusdjur, till exempel Neon Horse-spelpekaren eller Adopt Me Neon Starfish. Genom att kombinera fyra vanliga husdjur kan du göra ett neonhusdjur som verkligen lyser, och från neonhusdjur kan du skapa ett mega-neonhusdjur.

Shopping i spelet Adopt Me! utförs med den virtuella valutan Roblox - den så kallade Robux, och spelet har också sin egen valuta - Bucks. Genom att ta hand om ditt husdjur kan du, förutom underhållning, tjäna bucks, bara mata honom, lägga honom i sängen eller läsa en saga, i allmänhet, en massa intressanta saker.

Nu kan fans av Roblox-spelet "Adopt Me!" dekorera sin spelmarkör med favorithusdjur!',
    'adopt-me_short_descr' => 'Ha kul med söta husdjur i vår Adopt Me!-samling av spelpekare',
    'adopt-me' => 'Adoptera mig!',
    'among-us_descr' => 'Among Us är baserat på det berömda rollspelet "Mafia". Det var planerat att spelet skulle vara exklusivt för mobila enheter, eftersom det bara hade en karta. Spelet blev snabbt populärt. Senare lade utvecklingsteamet till ett flerspelarläge, och två ytterligare kartor släpptes 2019.
Among Us är ett top-down tredjepersonspel som låter spelaren röra sig i alla riktningar. Från fyra till tio spelare kan spela i en runda. I början av spelet tilldelas alla i hemlighet rollen som en förrädare eller besättningsmedlem. Impostor (i rysk översättning "Förrädare") kan gömma sig i ventilationsluckan, sabotera och döda besättningsmedlemmar. Dess mål är att förstöra alla besättningsmedlemmar, eller förstöra rymdskeppet genom sabotage. Målet för skeppets besättning är att lösa olika pussel som förberetts för dem i början av spelet. Om var och en av besättningsmedlemmarna slutför alla uppgifter kommer förrädarna att förlora. Skeppets besättning kan också uppnå seger genom att eliminera förrädare under omröstningen.
Förrädare kan sabotera då och då och om felen inte åtgärdas inom 30 sekunder kommer besättningen att förlora. Innan du startar spelet kan du välja färgen på karaktären du spelar för, blå, röd, gul, grå - vad som helst! Och glöm inte att ställa in lämplig markör från den nya Among Us-kollektionen!',
    'among-us_short_descr' => 'Låt dig inte luras i detta invecklade rymdspel med Among Us-markörerna',
    'among-us' => 'Among Us',
    'steven_universe_descr' => 'Skaparen av "Steven Universe" var Rebecca Sugar. Hon är känd för sitt tidigare arbete kallat Adventure Time. Det första avsnittet av Steven Universe släpptes på YouTube-videoplattformen våren 2013. Men på hösten började den amerikanska kanalen Cartoon Network sända det för sina tittare. Sedan dess har 6 säsonger släppts. Den sjätte lovar att bli den sista.
När det gäller handlingen i den animerade serien kretsar den kring Crystal Gems-teamet. Det består av utomjordiska varelser med karakteristiska namn: Pearls, Amethyst och Pomegranate. Men det finns en annan deltagare i den, i rollen som en vanlig pojke Stephen agerar. Tillsammans letar de efter monster och försöker neutralisera dem så att de inte tar över jorden för personlig vinning. De motarbetas av Jasper och Peridot - budbärare från deras hemplanet som vill besegra Gems och slå på Cluster.
Om du är ett fan av Steven Universe och vill se karaktärerna från den animerade serien vart du än kan, installera Cursor Style-tillägget! Varför göra det? Du kan lägga till en samling dedikerad till "Steven Universe" och förvandla den vanliga muspekaren till en av dina favoritkaraktärer.',
    'steven_universe_short_descr' => 'Avslöja hemligheten med ädelstenar med Steven Universe-markörer',
    'steven_universe' => 'Steven Universe',
    'family_guy_descr' => 'En animerad sitcom som heter "Family Guy" har i hela sin historia vunnit Emmy-priset 4 gånger och "Annie" 3 gånger. Den animerade serien förlöjligar de ömma ämnena i det amerikanska samhället, såsom: feminism, slaveri, fetma, politik, etc. Till skillnad från andra verk används här inlägg med skämt och sarkasm. Dessutom är de i många fall inte integrerade i handlingen, utan existerar på egen hand.
Ett avsnitt av den animerade serien skapas under 10 månader. Varför så länge? Eftersom hela animationen ritas för hand. På grund av detta hinner vissa av de händelser som behandlas i verket tappa relevans. Men ändå förblir sitcomen mycket intressant och vinner favör hos tittare runt om i världen. För vem gillar trots allt inte att skratta gott åt politiker, kändisar eller människor som begår vilda upptåg och därigenom överraskar eller till och med chockerar vanliga människor.
Gillar du "Family Guy"? Du har en unik möjlighet att förvandla en vanlig muspekare till någon av karaktärerna i denna animerade serie! Vad behöver jag göra? Installera bara webbläsartillägget “Cursor Style”, lägg till en samling tillägnad “Family Guy” till det och njut av en fantastisk reinkarnation!',
    'family_guy_short_descr' => 'Family Guy-markörsamling för finsmakare av speciell humor',
    'family_guy' => 'Family Guy',
    'cute_cursors_descr' => 'Du har säkert hört uttrycket "Skönhet ska rädda världen"? Många människor, särskilt tjejer, håller med om detta uttalande. Därför strävar de efter att omge sig med allt det vackraste och mest tilltalande för ögat. Det kan vara rosa tapeter i sovrummet, mjuka leksaker, kuddar broderade med pärlor, dyrbara smycken etc. Utifrån ser det hela väldigt gulligt ut och till och med lite barnsligt. Men var och en av oss är ett litet barn i våra hjärtan, så varför inte låta det visa vår fantasi?
Ömhet kan väckas i oss av mycket. Till exempel de medkännande ögonen på en kattunge som vill bli klappad eller matad. En flerfärgad regnbåge som tittar fram efter ett vårregn och skimrar med alla färger i solen. Barnet som fick choklad och bestämde sig för att dela den med sin flickvän eller pojkvän. Det finns en hel del anledningar till att bli rörd, och vi bestämde oss för att använda dem som markörer.
Trött på den tråkiga vita pilen i din webbläsare? Byt ut den mot något gulligt från vår samling! Till exempel en rosa och vit enhörning, en ledsen tomat, ett buttert moln, en taggig kaktus i form av en katt, eller vad du nu vill. Allt du behöver göra är att installera tillägget Cursor Style och lägga till en samling söta markörer till det. Och länge leve världens frälsare - skönheten!',
    'cute_cursors_short_descr' => 'Världen kommer att bli snällare med en samling söta markörer',
    'cute_cursors' => 'Söta Markörer',
    'web_media_descr' => 'I moderna realiteter använder nästan alla internet. Från småbarn till pensionärer. Någon surfar med en webbläsare, en annan tittar på videor på YouTube, och någon behöver nätverket för att kommunicera med nära och kära. Någon av dessa användare kan inte föreställa sig en dag utan World Wide Web.
Äldre sitter ofta på ett socialt nätverk som Facebook eller VK. De kommunicerar också ofta med sina barn och barnbarn på Skype. Detta är särskilt bekvämt om barn och föräldrar bor i olika städer eller till och med länder.
Unga människor föredrar att kommunicera via Viber eller Telegram, ladda upp foton på Instagram, skratta åt FB-memes. YouTube-videor med folks reaktioner får miljontals visningar, precis som olika upptåg eller sociala experiment. I Tik-Tok dansar hundratusentals människor, visar trolleritrick och uttrycker sig.
Är du intresserad av eller använder du ofta någon typ av resurs från webbmediaområdet? Vill du bli av med den tråkiga muspilen i din webbläsare? Installera då tillägget och ändra standardpekaren till vår kreativa! Det kan vara en YouTube-pekare, Viber-pekare, Google Chrome-pekare eller andra resurser.',
    'web_media_short_descr' => 'Lev i en modern rytm med webbmediakursorsamlingen',
    'web_media' => 'Webbmedia',
    'bobs_burgers_descr' => 'Den animerade serien Bob\'s Burgers är handlingen i animationsarbetet och karaktärernas karisma. Och, att döma av nomineringen till Emmy Award och erkännandet av arbetet som en av de bästa tecknade serierna i hela världen, så gjorde Bob\'s Snack verkligen ett avtryck.
Handlingen i den animerade serien kretsar kring familjen Bob Belcher. Denna person är ägaren till matstället på första våningen, och på andra våningen bor han med sina nära och kära. Bob har en glad fru Linda och 3 barn: Gene, Louise och Tina. Pojken drömmer om en musikalisk karriär, den äldsta dottern Tina är väldigt snäll, men klumpig, och den yngsta - Louise är fortfarande en slyngel och försätter ofta sin familj i en obekväm situation. Huvudkonkurrenten till Bob\'s Burgers är Jimmy Pestos Pizzeria. Som du kanske gissar heter ägaren till denna pizzeria Jim, och han och Bob hatar varandra. Allt detta behandlades så att det såg komiskt ut, inte seriöst. Därför orsakar många av deras sammanstötningar bara ett leende.
Om du älskar den animerade serien “Bob\'s Burgers” och vill se hans karaktärer inte bara på skärmen eller TV:n, installera tillägget, lägg till en samling och ändra muspekaren i webbläsaren till någon av karaktärerna i denna tecknade serie!',
    'bobs_burgers_short_descr' => 'Bob lagar hamburgare, och vi gör Bob\'s Burgers-markörer',
    'bobs_burgers' => 'Bob\'s Burgers',
    'kirby_descr' => 'Spelet "Kirbys" historia började redan på 90-talet av förra århundradet. Det består av många serier som utvecklats av Nintendo och HAL Laboratory. Spelet är avsett för barn från ett och ett halvt till 8 år. Dess popularitet kan bedömas av antalet sålda exemplar. Över 34 miljoner världen över.
Huvudkaraktären i Kirby är den eponymiska rosa varelsen. Den lever på en planet som heter Pop Star och skyddar den periodvis från olika faror. Kerby kan andas in vissa föremål och sina fiender för att därefter lära sig deras förmågor: hand-till-hand-strid, innehav av ett svärd, eldandning, etc. Men den rosa puffern kämpar inte bara med fiender, utan löser också olika pussel, reser till andra länder och kan till och med flyga i level.
Du kan spela detta videospel på Nintendo- eller Game Boy-konsoler. I alla serier finns söta hjältar, bra grafik och roliga soundtracks. Förresten, under nästan 30 år sedan lanseringen av den första versionen lyckades världen se 20 Kirby-serier. Denna indikator, tillsammans med den mångmiljonbeloppiga volymen av sålda exemplar, hjälpte spelet att hamna i TOP 50 av de mest framgångsrika och eftertraktade videospelen i spelindustrin.
Älskar du Kirby så mycket att du skulle vilja se den här karaktären var som helst? Använd då Kirby-kollektionen och förvandla den vanliga muspekaren till huvudkaraktären i ditt favoritvideospel! Vi är säkra på att du kommer att gilla det nya utseendet på pekaren.',
    'kirby_short_descr' => 'Försök att andas in hela Kirby-markörkollektionen',
    'kirby' => 'Kirby',
    'undertale_descr' => 'I uråldriga tider beboddes jorden inte bara av människor, utan också av monster. På grund av oenigheter mellan dem utbröt ett krig, som slutade till förmån för den mänskliga rasen. Sju magiker drev monstren under jorden och fängslade dem där för alltid med en barriärformel. Men det fanns bara en ingång till Mount Ebott, som barnet utnyttjade. Det är för honom som du kommer att spela genom att köra datorspelet Undertale.
Detta spel utvecklades av Toby Fox - en välkänd programmerare från USA. Till en början kunde ägare av persondatorer som kör Microsoft Windows och Linux OS njuta av det, och sedan kom turen för användare av spelkonsoler.
Vad är poängen med det här spelet? Pojken reser genom underjorden bebodd av monster. Några av dem är omedelbart fientliga, medan andra gillar att prata. Spelaren kan välja ett av två beteenden: undvika våld eller slåss. I det första fallet blir det lättare att klara spelet, i det andra - tvärtom är det svårare. Handlingen och slutet, som kan förgrena sig och förändras, beror också på detta val.
Om du gillar Underground Tale och vill se dess karaktärer i din webbläsare, installera tillägget och lägg till lämplig samling av markörer! Förvandla en tråkig muspekare till ett av monstren eller huvudpersonen i Undertale!',
    'undertale_short_descr' => 'Det är dags att ta sig ur hålet med Undertale-pekarna',
    'undertale' => 'Undertale',
    'deltarune_descr' => 'Deltarune är ett rollspel som släpptes för datorer för ett par år sedan. Det skapades av samma programmerare som utvecklade Undertale. Dessa två spel liknar dock nästan inte varandra, även om de har ett par gemensamma karaktärer och platser.
Det finns flera huvudkaraktärer i Delta Rune. Det här är studenten Chris, som kan kontrolleras, och ett charmigt monster Susie, okontrollerbart. Båda karaktärerna faller in i mörkets värld, där de möter en av dess invånare - Ralsay. Han berättar för dem att de i själva verket är ljusvarelser som har ett uppdrag - att stoppa flödet av mörk energi i en dyster värld. För att göra detta måste de skona de lokala monstren och försöka att inte engagera sig i strid med dem, även om det ibland är ganska svårt att göra.
Spelaren har ett enkelt val: antingen skona de mörka varelserna, eller attackera dem. Eftersom Susie inte är ett fan av halva åtgärder, väljer hon i många fall en strid. Därför har Chris inget annat val än att stödja sin flickvän och hjälpa henne i striderna.
Älskar du Deltarune-spelet? Då kan du styla din muspekare i webbläsaren för en av dess karaktärer! Du kan göra detta med vår extension. Installera den, lägg till "Rune Delta"-samlingen och aktivera! Nu har din pil slutat vara likadan som alla andra, och har istället blivit Chris, Susie eller en av varelserna i den mörka världen.',
    'deltarune_short_descr' => 'Dyk ner i den mörka världen med den här markörsamlingen',
    'deltarune' => 'Deltarune',
    'super_mario_descr' => 'Super Mario är en serie datorspel utgivna av Nintendo. Det första och mest populära spelet kallades Super Mario Bros. Det såg dagens ljus 1985. Senare listades det i Guinness Rekordbok. Sedan dess har mer än 20 spel släppts, där var och en har sin egen handling. År 2019 dök en ny version upp kallad Super Mario Maker 2. Trots förbättringen av grafiken förblev stilen och karaktärerna desamma, och detta framkallar nostalgi för 80-talets Super Mario.
Huvudpersonen är fortfarande rörmokaren Mario. I handlingen i den sista varianten av spelet hade prinsessans slott ingen sten orörd. Mario måste bygga om det och ha tjänat in mynten som betalas till honom för uppgifter. Totalt har det här spelet mer än 100 nivåer av varierande komplexitet med möjlighet till modifiering. Även i Super Mario Maker 2 finns det nya spellägen. Du kan spela fyra av dem samtidigt och så fort en avslutas anses nivån vara klar. Det finns också sådana lägen som: Mario Marathon, Duel och Ninjik race.
Älskar du Super Mario och allt som hör till detta underbara spel? Ställ då in pekarna gjorda i stil med denna plattformsspelare! Vi är säkra på att du kommer att gilla Mario-pekaren, Luigi-pekaren, Princess Peach-pekaren och andra pekare som presenteras i vår samling!',
    'super_mario_short_descr' => 'Gå genom Svampriket med Super Mario-markörsamlingen',
    'super_mario' => 'Super Mario',
    'gravity_falls_descr' => 'Gravity Falls skapades gemensamt av Disney Television Animation Corporation och Alex Hirsch. Premiären släpptes 2012 och visades på Disney Channel. Hela den första säsongen av den animerade serien visades där. Två år senare släpptes den andra säsongen, som tittarna kunde se på den tidigare kanalen och på Disney XD. Tyvärr väntade inte Gravity Falls-fans på de tredje och efterföljande säsongerna. Skaparna beslutade att begränsa sig till två säsonger utan några uppföljare.
När det gäller handlingen i denna animerade bild, så utspelar sig all action i en fiktiv stad som heter Gravity Falls. Två tvillingar kommer dit, vars namn är Mabel och Dipper. De bor hos sin kusin Stan. Han har sin egen turist souvenirbutik. När bröderna tröttnar på "att inte göra något", ger de sig ut på jakt efter äventyr. En av dem hittar en konstig dagbok i skogen, som berättar om avvikelserna i den här staden. Tvillingarna ger sig iväg på jakt efter dess författare och stöter på ovanliga varelser och platser. Om du är intresserad av denna animerade serie, och du en gång var fans av dess karaktärer, rekommenderar vi dig vår samling av muspekare i stil med Gravity Falls!',
    'gravity_falls_short_descr' => 'Ge dig ut på ett äventyr med Gravity Falls-markörer',
    'gravity_falls' => 'Gravity Falls',
    'simpsons_descr' => 'Absolut alla har hört talas om en så berömd animerad serie som The Simpsons. Även de som aldrig har sett det är medvetna om existensen av gula karaktärer. Och fansen är glada när nästa säsong av deras favorittecknad serie kommer ut. Förresten, hösten 2019 släpptes 31 säsongkonton. Och den första dök upp på tv-skärmar redan 1989. Fox började visa den och fortsätter fortfarande att göra det på grund av höga betyg och publiksympati.
The Simpsons är en satirisk genre som berör relevanta ämnen. Detta kan vara livsstilen för den genomsnittliga amerikanen, politiska och religiösa frågor, "stjärniga" knep av kändisar, feminism, samkönade äktenskap. I allmänhet allt relaterat till lokala och globala händelser som USA deltar i.
Handlingen i den animerade serien utspelar sig i den icke-existerande staden Springfield. Faktum är att det finns många städer med det namnet i Amerika. Kanske är det därför det valdes så att publiken inte skulle associera det som hände på skärmarna med en specifik ort, utan bara gissade var detta kunde vara.
Du är troligen ett fan av The Simpsons. Annars, varför skulle du läsa den här texten till slutet? Och om så är fallet, då har du möjlighet att ändra den uttråkade muspekaren till en pekare som är gjord i stil med denna animerade serie.',
    'simpsons_short_descr' => 'En rolig liten familj med Simpsons-markörer',
    'simpsons' => 'The Simpsons',
    'youtubers_descr' => 'YouTube-videoplattformen dök upp 2005. Till en början publicerades videor där bara för självuttryckssyfte eller för att informera om något. Men med tiden växte allt detta till en lönsam affärsverksamhet, som genererar tusentals, och ibland miljontals dollar i månaden till framgångsrika YouTube-användare. Ju mer populär vloggaren (personen som genomför videobloggen), desto mer kan han eller hon tjäna genom sin kanal.
Hur mycket tjänar en femårig vloggarflicka, vars föräldrar tar med henne till de mest intressanta attraktionerna och filmar vad som händer på kameran? Det är bara hur ett barn har roligt i barnparker, som uttrycker känslor, hur man busar och allt sådant. Beloppet är verkligen fantastiskt - idag har barnets kanal fått nästan 47 miljoner prenumeranter och börjat generera intäkter på 5 miljoner rubel per månad.
Någon laddar upp videor där han diskuterar datorspel, någon gör beatbox eller ordnar upptåg för förbipasserande på gatan. Vissa ägnar sina videor åt känsliga ämnen, som förhållandet mellan män och kvinnor. Ju mer YouTube-användare gillar dessa tagningar, desto högre blir vloggerns popularitet.
Samlingen har redan lagt till PewDiePie-markören, Shane Dawson-markören, Ray William Johnson-markören, Zoella-markören, MyLifeAsEva-markören och andra.',
    'youtubers_short_descr' => 'En ny generation av stjärnor är alltid online i vår YouTubers-samling',
    'youtubers' => 'YouTubers',
    'pusheen_descr' => 'Nästan alla känner till katten Pusheen. Trots att det bara är en karaktär från en barnserietidning uppfunnen för 10 år sedan, har han miljontals fans idag. Katten Pusheen dök upp som en illustration skapad av konstnären Claire Belton.
Ett år senare skaffade katten en egen sida på Tumblr.com och på några veckor fick den en hel armé av fans - runt 10 000 personer. År 2013 var Facebook angelägna om att inkludera bilder från Pusheen i samlingar med andra uttryckssymboler. Efter förhandlingar med skaparen sattes denna idé i praktiken och "exploderade" på internet! Bilder från katten Pusheen används i korrespondens mer än 10 miljoner gånger om dagen!
År 2014 riktade en av de största leksakstillverkarna i USA sin uppmärksamhet mot denna karaktär. GUND (det var de som uppfann nallebjörnarna) lanserade ett par Pusheen-modeller. Eftersom succén var enorm skapades efter några månader en komplett samling leksaker i form av denna katt.
Var annars kan du träffa katten Pusheen? I presentförpackningar från Isaac Morris Ltd, i marshmallows från Boomf och, naturligtvis, i vår samling av Pusheen-markörer!',
    'pusheen_short_descr' => 'Lägg till lite komfort i din webbläsare med Pushin-markörsamlingen',
    'pusheen' => 'Pusheen',
    'rick_and_morty_descr' => 'Den första serien av animerade verk "Rick and Morty" släpptes 2013. Den här tecknade serien kan direkt hänföras till 2 genrer: science fiction och komedi. Dess skapare var Dan Harmon och Justin Royland. Ursprungligen visades alla serier på Cartoon Network-kanalen, och först därefter duplicerades de i onlinebiografer och videovärdar. Med några års mellanrum släpps nya Rick and Morty-säsonger, och i november 2019 kom den fjärde säsongen ut, som visade sig vara inte mindre intressant än de föregående. Handlingen i den animerade serien kretsar kring ett geni och samtidigt en galen vetenskapsman vid namn Rick, samt hans oansenliga sonson - Morty. Dessa två karaktärer är förbundna av gemensamma äventyr på de mest ovanliga platserna. Och de tar sig dit på en flygande tefat, kapabelt att röra sig genom en interspatial tunnel. Som du kanske har gissat är den här animerade serien lite som filmen Tillbaka till framtiden, men ändå är den inte dess animerade version. Emellertid berömdes han av många kritiker för humoristiska avsnitt, kreativitet och originalitet. Vill du se Rick eller Morty inte bara i serien av detta verk, utan också i webbläsaren? I så fall, installera tillägget och lägg till vår samling tillägnad din favorit tecknad serie! Här är Rick Sanchez markör, Morty Smith markör, Portal Gun markör och naturligtvis Mr. Meeseeks markör.',
    'rick_and_morty_short_descr' => 'Sluta gnälla, använd bara markörerna från Rick and Morty-kollektionen',
    'rick_and_morty' => 'Rick and Morty',
    'mlb_teams_descr' => 'Basebollfans kan hittas överallt i världen. Detta gäller särskilt invånare i länder som: USA, Kina, Kuba, Sydkorea, Japan och Venezuela. I motsats till vad många tror, ​​uppstod inte baseboll i Amerika, utan i England. Det första omnämnandet och beskrivningen av baseboll dök upp 1744, i den engelska upplagan. Efter 145 år tillägnade sig amerikanerna denna uppfinning, trots fakta.
National League bildades 1876. Den ingår i Major League i Kanada och USA. Idag finns det 15 lag i National Baseball League. I slutet av varje säsong kommer slutspelet, där de 4 bästa lagen deltar. Så vinnaren av hela National League avslöjas. Sedan får det vinnande laget chansen att spela mot vinnaren från American League i World Series.
Är du intresserad av baseboll eller till och med hejar på något av lagen? Hylla då ditt favoritlag genom att ställa in muspekarna i form av dess attribut! Ändra det tråkiga utseendet på pekaren i webbläsaren till den välbekanta basebollens företagsidentitet! Förvandla pilen till en spelarbatt eller hjälm i något av National League-lagen, som redan inkluderar New York Yankees-pekaren, Great Falls Dodgers-pekaren, Boston Red Sox-pekaren, Baltimore Orioles-pekaren, Oakland Athletics-pekaren.',
    'mlb_teams_short_descr' => 'MLB Teams markörsamling för alla våra fans där ute.',
    'mlb_teams' => 'MLB Teams',
    'brawl_stars_descr' => 'Brawl Stars är ett mobilspel i MOBA-genren från Supercell. Trots lanseringen i slutet av 2018 fick spelet stor popularitet, till stor del tack vare överflödet av stridslägen och färgglada, fantastiska hjältar - bråkstakar. Spelaren har gott om att välja mellan - 32 unika karaktärer och var och en av dem har sina egna uppsättningar av förmågor och färdigheter. Varje hjälte har också sin egen passiva färdighet, som är tillgänglig via bytekistor. Spelare kan slåss i flera lägen, till exempel, "Belöning för fångsten" - ett av de två lagen vinner, som har samlat fler stjärnor, och dödat motståndare. I "rånläget" är det nödvändigt att bryta motståndarnas kassaskåp, samtidigt som man behåller sina egna. Ett intressant "Gem Grab"-läge - laget blir vinnaren, laget som samlar de flesta ädelstenar vinner. Tja, i "Collision"-läget slåss 10 spelare mot varandra på kartan, där gränserna minskas på grund av ett giftigt moln. Spelet är fullt av en färgglad design som många gillar, inklusive oss, vilket inspirerade oss att skapa en separat samling av Brawl Stars-markörer. Det finns Brawl Stars Shelley-markör, Barley-markör, Penny-markör, Frank-markör, Mortis-markör och andra.',
    'brawl_stars_short_descr' => 'Välj Brawl Stars-markörer och låt striden börja',
    'brawl_stars' => 'Brawl Stars',
    'all_title' => 'Ändra din muspekare med två klick! Gratis samlingar för alla smaker.',
    'all_descr' => 'Om du någonsin funderat på hur du ändrar en tråkig muspekare, då är våra markörsamlingar något för dig! Här hittar du coola serietidningshjältar, vackra markörer för spelare med karaktärer från populära spel, roliga uppsättningar av markörer för praktiska skämt, färgmarkörer och många andra intressanta alternativ.',
    'text_title' => 'Coola och roligaste markörsamlingarna för varje dag',
    'text_allcat_title' => 'Unika och kreativa muspekare som matchar alla dina humör',
    'text_1' => 'Vill du inte vara som alla andra? Eller bara älskar allt ovanligt? Vill du vara en del av din favoritspelhjälte eller tecknad karaktär? Då har du kommit rätt. Här hittar du ljusa, ovanliga uppsättningar av markörer som kan ersätta den välbekanta och redan ganska tråkiga vita pilen. Muspekaren följer oss hela dagen i arbete och studier, så den borde ge ett fantastiskt humör och ställa in för positivitet.',
    'text_2' => 'Här hittar du markörer för spelare och filmälskare, vackra markörer baserade på dina favorit tecknade serier och sportmotiv för de mest aktiva människorna. Gillar du serietidningar eller kan du inte föreställa dig en enda dag utan roliga memes? Älskar du djur eller drömmer du om att besöka alla världens länder? Allt är enkelt - vi har en lämplig markörbild för dig också. Du kan också välja bilder beroende på vad du arbetar med. Till exempel kommer en svart markör att vara mycket bekvämare än vit när du arbetar med dokument eller ritningar, och en handmarkör kommer att vara bekvämare om du måste arbeta med små grafiska element. Välj din favoritbild, justera dess storlek direkt i tillägget - och använd den med glädje, varje dag med en positiv notering!',
    'install_to_preview' => 'Installera tillägget för att förhandsgranska',
    'install' => 'Installera',
    'add_button' => 'Lägg till',
    'preview_button' => 'Förhandsgranska',
    'added_button' => 'Tillagd',
    'add_cursor' => 'Lägg till markör',
    'to_your_collection' => 'till din samling',
    'prev_text_1' => 'Förhandsgranska i helskärm',
    'prev_text_2' => 'markör',
    'cursor' => 'markör',
    'pointer' => 'pekare',
    'a_title_1' => 'Cursor Style - Coola markörer för din webbläsare',
    'a_title_2' => 'Coola samlingar av tematiska markörer',
    'mouse_cursors' => 'Musmarkörer',
    'cursor_collection' => 'Markörsamling',
    'sborka_cursorov' => 'Markörsamling',
    'collection_list_from_colllection' => 'Lista över markörer - ',
    'nhl_teams' => 'National Hockey League',
    'neon' => 'Neon',
    'adventure_time' => 'Adventure Time',
    'nba_teams' => 'National Basketball Association',
    'spongebob' => 'SvampBob',
    'phineas_and_ferb' => 'Fineas och Ferb',
    'fortnite_chapter_2' => 'Fortnite Kapitel 2',
    'pokemon' => 'Pokemon',
    'famous_people' => 'Kändisar',
    'the_elder_scrools' => 'The Elder Scrolls',
    'halloween' => 'Halloween',
    'nfl_teams' => 'National Football League',
    'five_nights_at_freddy' => 'Five Nights at Freddy\'s',
    'komiksy' => 'Serietidningar',
    'igry' => 'Spel',
    'multfilmy' => 'Tecknat',
    'kino_i_serialy' => 'Filmer',
    'anime' => 'Anime',
    'futbol' => 'Fotboll',
    'avtomobili' => 'Bilar',
    'memy' => 'Meme',
    'emodji' => 'Emoji',
    'pitomcy' => 'Husdjur',
    'stil_i_krasota' => 'Mode och stil',
    'prazdniki' => 'Helgdagar',
    'flagi' => 'Flaggor',
    'vokrug_sveta' => 'Jorden runt',
    'eda_i_napitki' => 'Mat och dryck',
    'cvetnye' => 'Färgade',
    'prank' => 'Spratt',
    'startovyj_nabor' => 'Startpaket',
    'fortnite' => 'Fortnite',
    'dota_2' => 'DOTA 2',
    'minecraft' => 'Minecraft',
    'christmas_short_descr' => 'Tomten kommer att älska dina julmarkörer',
    'nhl_teams_short_descr' => 'En samling NHL-markörer för riktiga fans',
    'neon_short_descr' => 'Lägg till ljusstyrka med en neonkollektion',
    'adventure_time_short_descr' => 'Lär dig matte med Adventure Time markörsamling',
    'nba_teams_short_descr' => 'NBA-markörer som en symbol för fantastiska basketsegrar',
    'spongebob_short_descr' => 'Ta reda på vem som bor på havsbotten med SpongeBob-markörkollektionen',
    'phineas_and_ferb_short_descr' => 'Du kommer definitivt inte att bli uttråkad med Phineas och Ferb-markörkollektionen',
    'fortnite_chapter_2_short_descr' => 'Det nya kapitlet i det kultförklarade Fortnite-spelet',
    'pokemon_short_descr' => 'Fånga dem alla om du kan',
    'famous_people_short_descr' => 'Inspirera din idol markör',
    'the_elder_scrools_short_descr' => 'Fördjupa dig i en värld av riddare och drakar',
    'halloween_short_descr' => 'Var rädd för att missa den nya Halloween-kollektionen',
    'nfl_teams_short_descr' => 'För riktiga fotbollsfans',
    'five_nights_at_freddy_short_descr' => 'Försök att inte bli rädd för dessa animatronics',
    'komiksy_short_descr' => 'Markörer från serietidningar: välj ditt humör idag.',
    'igry_short_descr' => 'Virtuell verklighet: vem spelar du idag?',
    'multfilmy_short_descr' => 'Favorit tecknade seriefigurer i en ny design',
    'kino_i_serialy_short_descr' => 'Herren över Pekaren: Skrivbordets Brödraskap',
    'anime_short_descr' => 'Alla älskar anime: vem är din favoritkaraktär?',
    'futbol_short_descr' => 'Är du ett riktigt sportfan? Då måste du vara här.',
    'avtomobili_short_descr' => 'Bilen du drömmer om: en stor flotta för proffs.',
    'memy_short_descr' => 'Favoritmotiv: Memes cursors samling',
    'emodji_short_descr' => 'Visa ditt verkliga humör för andra - ställ in Cursoji!',
    'pitomcy_short_descr' => 'Ljusa markörer för alla älskare av våra mindre bröder',
    'stil_i_krasota_short_descr' => 'Ursprungliga markörer för alla tillfällen',
    'prazdniki_short_descr' => 'Vad står det på kalendern? Ny samling av Högtidscursors!',
    'flagi_short_descr' => 'Letar du efter äventyr: vart går vi idag?',
    'vokrug_sveta_short_descr' => 'Jorden runt på ett ögonblick: vart ska vi i dag?',
    'eda_i_napitki_short_descr' => 'Mumsiga markörer för kreativitet',
    'cvetnye_short_descr' => 'Måla ditt liv i ljusa färger och djärva penseldrag',
    'prank_short_descr' => 'En uppsättning markörer för de roligaste practical jokesen',
    'startovyj_nabor_short_descr' => 'Ett nytt utseende på bekanta saker: en uppdaterad serie av markörer',
    'fortnite_short_descr' => 'Följ streamarna!',
    'dota_2_short_descr' => 'Gör din virtuella värld till verklighet!',
    'minecraft_short_descr' => 'Karaktererna från ditt favoritspel är alltid nära',
    'christmas_descr' => 'Var och en av oss väntar utan tvekan på den mest populära högtiden - julen. Alla kristna i världen firar den traditionellt varje år, den 25 december. En tid då familjer samlas runt ett bord, delar sin glädje och kärlek och byter presenter. Långt före jul dekorerar människor gatorna med ljusstarka girlanger och sina hem med traditionella attribut. Det är svårt att hitta en person som inte gillar julen - en rolig och mystisk högtid, eftersom den åtföljs av många traditioner och ritualer, de återför oss till rötterna av hela vår familj. På julafton är bokstavligen allt mättat med dess anda, från målade pepparkakor till rörande sånger. En elegant julgran och presenter under den, en glädje som är bekant för var och en av oss från barndomen. Vi vill ansluta oss till denna magiska högtid och vem vet, kanske Tomten kommer att förbereda en speciell present till dig om du dekorerar din markör med vår julkollektion. Det finns allt du behöver för detta, Tomte-markören, julgransmarkören, pepparkaksmarkören, Snögubbe-markören och till och med presentpåse-markören. God jul!',
    'nhl_teams_descr' => 'National Hockey League grundades 1917 - det är en professionell idrottsorganisation som samlar hockeyklubbar från USA och Kanada. Och det här är en av de första professionella hockeyligorna i världen. NHL är en av Nordamerikas främsta sportligor, tillsammans med NFL, NBA, Major League Baseball och MLS. Varje år kämpar 31 lag från 30 städer i USA och Kanada om huvudtrofén - Stanley Cup, och laget som fick flest poäng under den ordinarie säsongen tilldelas President\'s Cup. Det är dags för oss att hedra det här fantastiska spelet genom att skapa en samling NHL-markörer. Om du också gillar hockey, heja på din favoritklubb eller delta i den här sporten själv, ändra bara markören och skiljs inte från ditt favoritlag, inklusive Boston Bruins-markören, St. Louis Blues-markören, Columbus Blue Jackets-markören, Tampa Bay Lightning-markören, Dallas Stars-markören och andra klubbar värda uppriktig respekt.',
    'neon_descr' => 'Vi har skapat en unik samling av neonpekare för att lägga till variation till den vardagliga internetanvändningen och lägga till lite ljusstyrka till de fascinerande neonljusen. Låt deras rika färger skapa den omslutande atmosfären i staden på natten, ge inspiration att skapa något nytt. I den moderna världen tillkännager ljusen från en metropol alltid nattens ankomst, de följer oss på varje gata och denna glöd är fylld med energi. Låt det också följas av en glödande glasspekare, en läcker korvpekare, en saftig burgarpekare, en glittrande diamantpekare och andra pekare från den nya neonkollektionen.',
    'adventure_time_descr' => '"Adventure Time" är en tecknad serie i en fantastisk genre där handlingen utspelar sig i en värld som överlevt apokalypsen. Detta territorium kallas Landet Ooo, som fram till nyligen var ett kärnvapenkrig. Men allt detta ligger redan i det förflutna, men alla överlevande människor utsattes för mutationer och världen fylldes med magi. Huvudpersonerna i den animerade serien är Finn, en 14-årig pojke och hans vän hunden Jake. Pojken och hunden älskar äventyr, de hjälper ständigt alla som är i trubbel. Vännerna bor i ett träd och tillbringar all sin tid tillsammans. Om du vill fördjupa dig i en äventyrsvärld med andra beundrare, skrik då "Matematik". Här finns både Finn Pojk-pekaren och Jake-pekaren, samt prinsessan Tuggummi-pekaren. Vi glömde naturligtvis inte Bimo-pekaren, Iskung-pekaren och andra.',
    'nba_teams_descr' => 'Om basket är ditt favoritspel för dig, som det är för oss, då är en samling av markörer dedikerade till NBA-lagen vad du behöver. NBA är en av de främsta idrottsföreningarna på den nordamerikanska kontinenten. När vi skapade denna samling plågades vi av valet - vilket lag ska man välja, eftersom det finns trettio av dem i NBA. Men det finns lag som är legender. Detta och Chicago Bulls, som satte rekord för segrar i mitten av 90-talet. Detta är Golden State Warriors, som samlade de bästa ligaspelarna för ett par år sedan. Eller till exempel Lakers, Celtics är också vansinnigt coola lag. Om du, som vi, ser fram emot matcherna för dina favoritbasketlag och vill visa ditt stöd till laget eller spelarna, ladda ner vår samling av NBA-markörer.',
    'spongebob_descr' => 'Den animerade serien "SvampBob Fyrkant" är känd av så många människor. Det blev en överväldigande framgång efter att Nickelodeon 1999 bestämde sig för att skapa en animerad serie baserad på den pedagogiska tecknade serien Tide Zone, och förvandlades till en mycket lukrativ franchise. Skaparen av serien är en före detta anställd vid det oceanologiska laboratoriet, vilket är anledningen till att nästan alla karaktärer i den animerade serien är roliga invånare i havsbotten, med sina egna egenskaper och karisma. Handlingen kretsar kring det hemliga Krabby Patty-receptet som bara huvudpersonen kan laga - SvampBob. Och de andra invånarna i havet försöker få tag på det, inklusive huvudanti-hjälten Sheldon Plankton, som misslyckas varje gång. I SvampBob-markörsamlingen har vi samlat markörerna för alla de anmärkningsvärda karaktärerna och händelserna i serien. Till exempel markören för Mr. Krabs med dollarn, markören för Patrick Star, Bläckvard med sin klarinett, markören för maneten, markören för SvampBob och många andra karaktärer.',
    'phineas_and_ferb_descr' => 'I den fiktiva amerikanska staden Denville i den icke-existerande Trishtatya bor två intressanta pojkar. Varje dag av deras semester förvandlas till otroliga äventyr, eftersom de kan bygga en berg- och dalbana stor som en hel stad eller en riktig portal till en annan planet. De delar sitt fantastiska nöje med vänner. Samtidigt, medan pojkarna har roligt, bygger den onda vetenskapsmannen Heinz Fufelschmertz en annan ond maskin som skapar kaos, vars namn slutar på "-inator", med vars hjälp han vill hämnas sina barndomsbesvikelser eller ta makten i Trishtat, men Perry hindrar honom - Utkonos, den hemliga "Agent Pi", som arbetar under täckmantel av en pojkars husdjur. Populariteten för denna animerade serie, både bland barn och vuxna, inspirerade oss att skapa en samling av Phineas och Ferb-pekare så att du kan ändra din muspekare på karaktärerna från serien. Bland dem finns Phineas Flynn-pekaren, Dr. Heinz Fufelschmertz-pekaren, Ferb Fletcher-pekaren, Candace Gertrude Flynn-pekaren och Perry näbb-pekaren.',
    'fortnite_chapter_2_descr' => 'Det andra kapitlet av Fortnite kom efter en storslagen händelse - The End, vilket drog allt som spelarna i spelet älskade in i ett svart hål. Fortnite Chapter 2 har nu en ny karta, som vid första anblicken är ännu vildare än den ursprungliga kartan, samt många förändringar i spelmekaniken och naturligtvis mycket nytt spelmaterial! Fordon, känslor, simmekanik och mycket mer - allt detta i fräscha, intressanta bilder, allt som du älskar och uppskattar i detta kultspel. Fördjupa dig i en ny värld - välj en landningsplats och utforska en helt ny ö med 13 platser. Simning, fiske, motorbåtar - detta är ett nytt vattenspel. Mer kul och mindre ansträngning - uppgradera ett helt nytt kapitel 2 och glöm inte att ändra markören till nya skal och vapen. Du väntar redan på de uppdaterade skinnen med Turk-markören, Riptide-markören, Rippley-markören, Remedy-markören, Toxin-markören, 8-Ball-markören, Fusion-markören och andra!',
    'pokemon_descr' => 'Ordet "pokemon" betyder en varelse med övernaturliga krafter. De har intelligens och en del av dem kan till och med prata. För närvarande finns det redan 802 sorters Pokemon. I det uppfunna Pokémon-universumet kallas människor Pokémon-tränare, som de tränar för strider med andra tränare Pokémon. Och ju mer erfaren och starkare tränaren är, desto mer respekt åtnjuter han. Lyckligtvis bör det noteras att Pokemon-strider aldrig slutar med dessa unika varelser död. Alla Pokémon har olika förmågor och skiljer sig åt i typ av element, och dess motståndskraft mot olika attacker beror starkt på detta, och vissa varelser har förmågan hos två element samtidigt. Efter att ha vunnit striden får Pokemonen den värdefulla erfarenhet som är nödvändig för att öka nivån och därmed dess egenskaper. Idag är Pokémon-universumet en enorm mediefranchise och vi bestämmer oss för att förbereda en samling markörer med några populära Pokémon. Bland dem är den mest kända Pikachu-markören, såväl som Rattata-markören, Squirt-markören, Bulbasaur-markören och Charmander-markören. Denna lista kommer att uppdateras, eftersom det finns så många av dem och var och en av dem är unik på sitt eget sätt.',
    'famous_people_descr' => 'Bland de många kända personerna finner var och en av oss en förebild eller beundrar helt enkelt dessa kändisars genialitet, talang och uthållighet. Vi har förberett en samling kändispekare för att inspirera dig och påminna dig om de stora prestationer som var och en av er kan öka. Inte alla kända personligheter hade ett lyckligt öde, men de lär oss det viktigaste att du aldrig behöver dra dig tillbaka från ditt kära mål, trots svårigheter och problem. När allt kommer omkring är detta huvudprincipen för att uppnå framgång - att gå till din dröm varje dag och slutligen bli bäst på ditt område. Kanske vill du bara byta muspekare idag, och i morgon kommer hela ditt liv att förändras till det bättre! Samlingen kommer ständigt att uppdateras med nya, värdiga representanter för mänskligheten. Bland dem, naturligtvis, forskare, politiker, idrottare, representanter för konst och många andra. George Washington-pekaren, Michael Jordan-pekaren, Stephen King-pekaren, Elvis Presley-pekaren och Marilyn Monroe-pekaren är bara början.',
    'the_elder_scrools_descr' => 'The Elder Scrolls är en serie datorspel, förenade av ett gemensamt, minutiöst utformat universum, som ger spelaren enorm valfrihet, vilket gör att de kan besöka olika områden och städer i fantasy-världen och utforska nya platser och uppdrag på egen hand. Arbetet med serien påbörjades redan 1992 och genom åren har spelet förenat en enorm gemenskap av spelare kring sig. Därför, på populär begäran, har vi släppt en samling markörer The Elder Scrolls, så att du kan fördjupa dig i spelets unika atmosfär. Den eviga kampen mellan riddare och drakar, vilken sida står du på? Byt markören till en drake och gå med i armén av eldsprutande monster eller kämpa ädelt på folkets sida genom att välja svärdmarkören och bilden av din favoritkaraktär - beslutet är ditt! Huvudsaken är att med vår nya kollektion är du redo för alla strider.',
    'halloween_descr' => 'Väntar på en mystisk natt på Allhelgonaafton. Halloweens historia går tillbaka över två tusen år. Kanske är detta den konstigaste helgdagen som kombinerar nöje och rädsla, en infödd i den keltiska kulturen. Då brände folk brasor och tog på sig läskiga kostymer för att hålla spöken borta. Ordet "Halloween" nämndes första gången på 1500-talet som en skotsk förkortning av den engelska frasen All-Hallows-Even. Påven Gregorius III förklarade den 1 november Allhelgonadagen, och kvällen innan kallades Eve of All Saints, och senare Halloween. Denna dag bär folk kostymer av varulvar, spöken och andra monster och går till grannhusen och erbjuder sig att köpa godis. Temafester, fyrverkerier, vackra lyktor, pumpor och stunt skapar en unik atmosfär. Vi vill också fira denna fruktansvärda helgdag med accessoarkursorer och Halloween-karaktärer. I vår samling kan du hitta: zombie-markör, spökmarkör, svart katt-markör, pumpa-markör och mycket mer. Att ändra ditt humör är nu lika enkelt som att ändra din markör med vår nya Halloween-kollektion.',
    'nfl_teams_descr' => 'Vad kan vara bättre för en sann amerikansk fotbollsfantast än en muspekare i form av symboliken för det lag som han är ett fan av? I den moderna National Football League spelar trettiotvå lag, uppdelade mellan National and American Football Conferences (National Football Conference, NFC och American Football Conference, AFC). I sin tur är var och en av konferenserna uppdelad i fyra divisioner: East, North, South och West. NFL-säsongen består av försäsongsmatcher, en grundserie och en serie slutspelsmatcher. Den sista matchen i NFL-säsongen kallas Super Bowl och är i grunden den mest populära sportevenemanget i USA. Detta är ett favoritspel för miljontals fans och därför har vi skapat en samling NFL-pekare så att du inte skiljs åt med symbolerna för ditt favoritlag. Oavsett om det är New England Patriots, New York Giants, Buffalo Bills eller ett annat lag, var alltid på samma våglängd som dina idoler, genom att använda våra pekare i form av en laglogotyp och hjälm. Samlingen kommer ständigt att uppdateras så att alla kan ändra pekaren till bilden av sitt favoritlag.',
    'five_nights_at_freddy_descr' => 'Det verkligt unika spelet Five Nights at Freddy\'s fick snabbt stor popularitet och detta är inte förvånande, eftersom dess enkla och samtidigt fascinerande handling kan hålla spelare framför skärmarna i timmar. Vi designade Five Nights at Freddy\'s-markörerna på begäran av spelets fans och var mycket glada över att förkroppsliga sådana intressanta och roliga karaktärer. Men till skillnad från spelet hotar ingenting dig med våra markörer, så välj gärna dina favoritanimatroniker, vare sig det är Björn Freddy eller Kanin Bonnie eller andra. Det viktigaste är att spelet nu väcks till liv i din webbläsare och ger nya känslor. Vi garanterar att det inte finns några spöken i våra markörer, men de förmedlar perfekt andan i ett spel som inspirerar till rädsla på grund av designens krångligheter och handlingselement. Men tänk om du gör markörstorleken väldigt stor? Kan du behålla lugnet och inte bli rädd?',
    'komiksy_descr' => 'Det kan tyckas att muspekaren är en bagatell, men ofta är det sådana detaljer som kan förbättra ditt humör, vakna upp en grå morgon eller bara ge ljusa känslor. En samling serietidningspekare designade speciellt för alla superhjälteälskare. Här kan du hitta absolut alla Marvel-universum och DC Comics - från Iron Man till Thanos, Spider-Man och Hulk. Pekarstilen kan vara antingen i form av en superhjälte eller i form av hans karaktär. En pekare är inte bara ett funktionellt element; det är viktigt i professionell mening. Till exempel, om du spelar in en video från skärmen, är det bättre att se en ljus, originell bild, och det ser mycket mer intressant ut. Och naturligtvis - vem skulle inte vilja använda oändlighetshandsken i verkliga livet? Att ändra muspekaren är enkelt - ladda bara ner tillägget till din webbläsare och lägg till den pekare du gillar i dina inställningar via den. Du kan välja en pekare efter ditt humör minst varje dag. Slut på de grå dagarna - bli en superhjälte just nu!',
    'igry_descr' => 'Datorspel har länge blivit en integrerad del av våra liv. Med deras hjälp kan du fördjupa dig i en ny värld, delta i äventyr och bli en helt annan person. Alla har sin egen favoritleksak, vars karaktärer redan har blivit nästan familjära. En uppsättning markörer baserade på välkända datorspel är en möjlighet att späda ut det tråkiga vardagslivet och lägga till lite kreativitet, ljusstyrka och roligt i arbetsflödet. Uppsättningen innehåller både bilder av själva spelhjältarna och hjälptecken, vapen och spelikoner. Välj vad som passar ditt humör - spelmarkörer kommer att tilltala inte bara spelare, utan också alla som helt enkelt är trötta på det grå vardagslivet. Bara ladda ner uppsättningen, ändra muspekaren - och gå, för att slutföra uppdragsuppgifter, förstöra fiender och uppnå dina mål.',
    'multfilmy_descr' => 'Inuti varje vuxen finns det fortfarande ett barn som älskar tecknat, och drömmer fortfarande om att bli en av hjältarna. Vi hjälper till att förverkliga dina drömmar - använd den nya samlingen av markörer baserade på de mest berömda och älskade tecknade serierna. Tom och Jerry, Buzz Lightyear och Shrek, Gravity Falls och till och med Pokemon - du kan bli vad du vill varje dag. Välj musmarkören efter ditt humör. Vem är du idag? En hänsynslös och glad minion som lätt löser alla problem eller en stark och modig Raphael, vars mål inte bara är att åstadkomma bedrifter utan också att äta pizza? Kanske är du den allsmäktige anden som har ett helt kontor under sin kommando? I samlingen finns det hjältar för alla - från prinsessor till drakar - det återstår bara att bestämma vem som återspeglar dagens humör. Cursor Style är inte bara en ljus bild. Detta är en återspegling av individualitet, självuttryck och helt enkelt - kul, glädje och positivt för hela dagen. Är det tråkigt att arbeta eller för lat för att studera? Har det blivit ledsamt och är inte glatt? Ändra markören så kommer världen att glittra med nya färger.',
    'kino_i_serialy_descr' => 'Filmer - är magi, mystik och bara ett bra sätt att slappna av, ha kul och få livfulla känslor. Samtidigt, efter att ha tittat, kommer vi fortfarande ihåg de favorithjältar som jag verkligen vill träffa i verkligheten. Nu är det möjligt - bara ladda ner den nya samlingen av markörer baserade på kända filmer och TV-program. Ljusa, coola markörer kommer att vara ett bra tillägg till skrivbordet, förvandla tråkig grå vardag till en semester, och banala uppgifter - till ett spännande äventyr. Byt markörhjälte varje dag - för humör, uppgifter eller slumpmässigt. Vem kommer du att vara idag? Ärliga och rättvisa John Snow eller den djärva, obevekliga John Wick? Kanske har du ett svårt uppdrag framför dig och bara Frodo kan slutföra det? Kanske är du bara en utomjording idag som inte vill ha kontakt med andra? Välj en lämplig markör - höj ditt humör och visa samtidigt andra vad du tänker och hur du planerar att spendera din dag. Prova det - det är inte bara roligt, utan också beroendeframkallande - du kommer definitivt inte att vilja återvända till den vanliga pilen.',
    'anime_descr' => 'Anime är en unik animationsstil, som trots sin uttalade etnicitet har uppskattats av miljontals människor runt om i världen. Det är osannolikt att det finns åtminstone en person som inte har tittat på tecknat i denna stil. Vi skapade de coolaste anime-stil-pekarna som alla fans av denna stil kommer att älska. Standardpekare är tråkiga och klyschiga. Visa din personlighet - använd samlingen av Anime-pekare med dina favoritkaraktärer. Välj pekaren av ett mörkt svärd om du drömmer om äventyr och modiga strider. Den söta feta mannen Totoro kommer att muntra upp dig även på den sorgligaste dagen, och Naruto kommer att motivera dig på äventyr och visa alla runt omkring dig att du är mega cool. Ljusa pekare kommer att lysa upp arbetsdagen eller göra inlärningsprocessen mer intressant och trevlig. Begränsa dig inte - använd dina favoritteman även i så små element som muspekaren. Byt pekare varje dag, anpassa dem efter ditt humör och visa din personlighet - med anime-stil-pekare är det så enkelt.',
    'futbol_descr' => 'Fotboll är en speciell sport som inkluderar element av brottning, friidrott, noggrannhet. Generellt sett är den spektakulär, skoningslös och samlar miljoner fans över hela världen. Gillar du fotboll eller älskar du bara sport? Ladda då ner en uppsättning markörer i stil med det världsberömda spelet och bevisa titeln som en lojal fan. Samlingen innehåller 24 alternativ för att designa markörer - i form av de mest populära lagen som förtjänar sina titlar som ett desperat och ihärdigt spel. Markörerna är gjorda i två versioner - i form av en standardtriangel, dekorerad i lagets färger, eller i form av en motsvarande spelhjälm. Standardmarkören i webbläsaren är tråkig och inte värdig en sann sportfantast. Bli originell och unik med vår samling. Ladda ner bilder och välj färgerna på ditt favoritlag eller anpassade markörer, om du bara älskar sport och hejar på alla. Att följa dina intressen är så enkelt - du behöver inte komma till jobbet i en halsduk eller mössa från ditt favoritlag, det är snabbt och enkelt att ändra markören till en ljus, snygg bild.',
    'avtomobili_descr' => 'Gillar du bilar och tycker om att titta på modeller från olika tillverkare? Eller har du länge drömt om ett visst märke, men ännu inte haft möjlighet att köpa det? Speciellt för dig har vi skapat en ljus uppsättning av markörer "Superbilar". Här hittar du klassiska Ford och stiliga Bentley, ljusa Lamborghini och unika Ferrari. Vill du bli ägare till originalbilen? Det är enkelt - ladda ner vår samling av markörer till din enhet och ändra bilden på bilen minst varje dag. Markörerna är designade i två versioner - som en fullfjädrad bil eller som dess logotyp. Välj vad du gillar bäst eller hur du föredrar att arbeta. Sådana bilder kommer att se bra ut som spelmarkörer eller helt enkelt som ett ovanligt element på skrivbordet. Att vara ljus är enkelt - det är inte nödvändigt att göra ofattbara saker för detta eller att ändra ditt utseende. Det räcker bara att sluta använda vanliga föremål och välja vad du verkligen gillar. Samlingen av markörer "Bilar" är valet för dem som inte är rädda för att bevisa sig själva.',
    'memy_descr' => 'Memes har länge varit en välbekant del av våra liv. Och vem av oss gillar inte dessa innehållsrika, intressanta och originella bilder för att trotsa dagen? Många hjältar från memes har inte bara blivit populära - de har fått status som populära favoriter, och fraser och uttryck har länge ingått i vardagligt tal som väletablerade vändningar. Vi presenterar en samling av de bästa pekarna baserade på de mest populära memes. Med deras hjälp kan du inte bara visa din personlighet, utan också uttrycka ditt humör. Är du helt trött och less på allt? Välj en arg katt som med sitt utseende uttrycker indignation och fientlighet mot allt runt omkring sig. Eller skiner du av sarkasm idag och har inget emot att skratta? Då kommer Drake Bling att vara ett utmärkt ackompanjemang - det kommer att pigga upp dig och göra varje uppgift originell och intressant. Installera tillägget, ladda ner vår samling - och välj en pekstil för varje dag. Det är inte svårt att vara ljus och originell - ändra ikonens standarddesign till en av hjältarna från memes och få en energikick för hela dagen.',
    'emodji_descr' => 'Emoji - ljusa, coola ikoner, utan vilka vi inte längre vanligen kan kommunicera. Med deras hjälp behöver du inte beskriva ditt humör med ord - välj bara önskad ikon så förstår din samtalspartner dig utan vidare åtgärder. I vårt nya set av cursors förkroppsligade vi idén om emoji - det är så roliga och ovanliga Cursoji dök upp som kommer att färga världen och göra livet mer intressant. Med hjälp av kursarbeten kan du inte bara arbeta och utföra välbekanta uppgifter, utan också visa dina kollegor, vänner och bara andra ditt humör. En sömnig cursor är perfekt för måndag morgon, och en gråtande cursor kommer att uttrycka en attitydinfo om ytterligare ansvar. En cool cursor med glasögon är det bästa valet inför helgerna, och en cursor med pengar i ögonen är en bra anledning att antyda för chefen om löneökningen. Att använda Cursoji är roligt och intressant - oavsett om det är arbete, studier eller presentation. I det senare fallet rekommenderas det till och med att göra detta om kollegor har sinne för humor eller bara behöver avdramatisera situationen. Generellt sett, för alla uppgifter - välj bara rätt kurs!',
    'pitomcy_descr' => 'Gillar du djur? Visst - de är så söta, roliga och väldigt roliga. Varför inte tillbringa hela dagen i sällskap av människans bästa vänner? Ladda ner samlingen Djur -pekare till dig själv och välj en vän åt dig varje dag. Markörikonen kan vara söt, som en godmodig alpacka, eller snygg, som en rosa flamingo. Eller så kanske du kommer att vara upptagen hela dagen och välja en enhörning som läser en tidning, eller helt enkelt inte vill kommunicera med någon, som en elak svart katt? För alla humör har vi ett motsvarande djur. En glad mops kommer att muntra upp dig även på den mest tråkiga och gråa dagen, och den rosa markören i form av en enhörning kommer att visa alla att du inte är utan en känsla för skönhet, även om du är en brutal skäggig man. Tänk om det inte är humör, och jag känner inte för att göra rutinuppgifter? Receptet är enkelt - ladda ner samlingen Djur, ändra muspekaren - och voila, solen skiner igen, vädret är fint och humöret är på högsta nivå. Inte konstigt att de säger att djur hjälper till att bekämpa depression och sorg!',
    'stil_i_krasota_descr' => 'I den nya samlingen av markörer har vi samlat ett brett utbud av ämnen som väcker behagliga känslor och lyfter oss. Denna uppsättning markörer kallas "Stil och skönhet", eftersom det är dina favoritsaker som bestämmer vårt vardagsliv, ger glädje och motiverar oss att göra viktiga saker, väcker lusten till förbättring. Är du intresserad av rymden och drömmer om att åka till andra planeter? Välj en NASA-markör eller en tallrik med utomjordingar - kom närmare din dröm. Om du inte kan föreställa dig livet utan musik eller är en inbiten rocker, så är markören i stil med en elgitarr för dig. Penseln, linjalen och kompassmarkören har utvecklats speciellt för ingenjörer - sådana bilder hjälper till att förvandla tråkiga beräkningar och ritningar till originella lösningar. En trollstav och sneakers, en skateboard och läppstift, solen och kemiska koner - välj vad som passar din livsstil, dina önskningar och ambitioner - och vanliga uppgifter kommer att bli mer intressanta, och vardagarna kommer att målas i nya, ljusa färger.',
    'prazdniki_descr' => 'Gillar du helgerna? Men vem gillar dem inte - vänner, presenter, återigen samma helg. För att göra väntan på helgerna trevligare, kortare och varmare kan du inte bara räkna dagarna på kalendern, utan också ställa in motsvarande ikon som muspekare. Låt oss börja med nyår - vi väljer en julgran, en present eller tomten, så att högtiden blir ljus och glad. Kanske pepparkaksgubben kommer närmare - rolig, söt och alltid glad? Med honom kommer det säkert inte att finnas tid att vara ledsen och uttråkad. Vi fortsätter att fira med amorer och glada hjärtan, och det är inte långt till påskharen. Någonstans bland helgerna kommer det att finnas en födelsedag, som kommer att vara ännu trevligare att vänta med ballonger istället för den vanliga pekaren. Och på Halloween kan du överraska kollegor och de runt omkring dig med en ovanlig muspekare i form av en olycksbådande pumpa eller ett spöke. En uppsättning pekare för helgerna är en möjlighet att lysa upp förväntan, ställa in dig i förväg för det kommande roliga och behålla ett utmärkt humör inte bara på själva högtidsdagen, utan under hela året.',
    'flagi_descr' => 'Flaggan är en unik symbol som används flitigt i alla sociala nätverk. Vi tänkte, varför inte göra markören till en flagga? Trots allt är den väldigt ljus och ovanlig. Nu kan du spendera varje dag i ett sällskap med ett nytt land, och arbetet kommer inte att bli så monotont och tråkigt. Muspekare kan nu göras till Kinas eller USA:s, Japans eller Kanadas nationsflagga, och i ytterligare 38 flaggalternativ, och du kan välja antingen den vanliga pilformen i en ovanlig färg eller markören i form av själva flaggan. Denna uppsättning kommer att tilltala alla reseälskare. Med den kan du planera nya resor och drömma om långa resor. Har du planerat en semester? Visa alla vilket land du vill åka till. Kanske bestämde du dig för att lära dig ett nytt främmande språk? Då kommer den här markören definitivt att stödja dig och motivera dig att studera noggrant. Eller älskar du bara flaggor som Sheldon? I alla fall kommer flaggmarkörkollektionen att vara ett bra tillägg till din skrivbord och kommer att flytta dig till nya upptäckter.',
    'vokrug_sveta_descr' => 'Alla gillar att resa. Hur underbart det är att besöka nya länder och städer, se sevärdheterna och ha en fantastisk tid i den nya kulturen. Det är synd att vi inte kan resa så ofta, men vi försökte fixa det. Uppsättningen av markörer "Runt om i världen" är en samling av de mest slående bilderna, symboler för olika länder, med hjälp av vilka du till och med kan känna dig som en riktig resenär när du sitter hemma. I vårt kit kan du hitta Japan och Australien, Italien och Kanada, USA och Mexiko - de mest intressanta, originella och pittoreska länderna i världen. Markörbilden kan bli en standardpil, i färgerna på landets flagga, eller bli en av statens huvudattraktioner. Du kan till exempel öppna dokument med lutande tornet i Pisa och göra presentationer med Frihetsgudinnan. Vi garanterar - framgång kommer att säkerställas. Tja, eller om inte framgång, så leenden från kollegor och erkännande av originalitet - säkert. Ja, och antyder till ledningen att det är dags att gå på semester kommer också att vara värt det - bara ställ in resväskan eller planet som markören - och mest troligt kommer du att flyga mycket snart.',
    'eda_i_napitki_descr' => 'En uppsättning markörer i form av produkter är en otrolig samling ljusa, läckra och aptitretande bilder som alla definitivt kommer att gilla och kommer att vara ett bra tillägg till webbläsaren. Har du någonsin klickat på broccoli eller pommes frites? Du har en sådan möjlighet - bara ladda ner en ny uppsättning markörer och ställ in dem istället för en tråkig vit pil. Markörer "Mat" är gjorda både i form av en standardtriangulär pekare och i form av produkter. Här hittar du grönsaker och frukter, dina favoriträtter, som pizza eller korv, kaffe, klubbor och mycket mer, vilket piggar upp varje dag. Älskar du kaffe, men är det inte så bra att dricka det hela dagen? Komplettera din kost med virtuellt kaffe, vilket också kommer att vitalisera och väcka dig, samt ge levande känslor. En brant markör i form av en virtuell munk kommer inte att skada figuren, samtidigt som den ger levande känslor och piggar upp. Du kan använda dina favoritmarkörer eller ändra bilden varje dag - ett stort urval av markörer hjälper till att färga vardagen och lägga till nya färger till välbekanta handlingar.',
    'cvetnye_descr' => 'Markören är huvudkomponenten i webbläsaren, med vilken vi tillbringar hela arbetsdagen, studerar, kommunicerar och slappnar av. Standardvyn för markören är tråkig och till och med lite deprimerande, men för många människor är den här formen fortfarande bekväm, och att ändra den kommer att vara obekvämt. Men för denna situation har vi en lösning - en uppsättning markörer i ljusa, glada färger som kommer att lägga till variation i din vardag och göra det lättare och snabbare att lösa eventuella problem. Om du funderar på hur du ändrar färgen på markören, svarar vi - ladda ner vår samling och välj ljusa lösningar för varje dag! Du kan välja monokroma toner i olika färger för att passa humöret eller arbetets specifika egenskaper. Till exempel, när du arbetar med standarddokument, kommer en lila markör att sticka ut mot bakgrunden, och på en mörk bakgrund kommer det tvärtom att vara lättare att arbeta med gula markörer. Om du vill ha en explosion av färg, ljusstyrka och maximal originalitet - välj en regnbågsmarkör som inkluderar alla spektrums färger - med denna ikon kommer humöret definitivt att vara bra under hela dagen.',
    'prank_descr' => 'Skämt på jobbet är inte alltid välkomna, eftersom de ofta stör arbetsflödet. Men med den nya uppsättningen "Pranks" markörer kan du vänligt spela ett spratt på dina kollegor eller vänner utan att skada ditt arbete eller studier. Vi har utvecklat en speciell samling som kommer att roa alla och ge en anledning att slappna av lite mitt i den hektiska processen med arbete eller utförande av en annan uppgift. För att ändra muspekaren, ladda bara ner paketet till enheten och välj den design du gillar i parametrarna. Till exempel kan du få en markör av en standardform, men i ett inverterat tillstånd eller en pil krökt av en våg. Denna form kommer inte alls att hindra arbetsprocessen, men samtidigt kommer den att presentera ett underbart humör och sätta dig på ett positivt humör. Ändra visningsinställningarna för markören efter ditt humör eller varje dag - och alla uppgifter kommer att bli mer intressanta och roliga, och vardagen kommer att sluta orsaka negativa känslor. Dessutom kan sådana markörer användas även för seriösa projekt - de har neutrala färger och sticker inte ut från skrivbordet.',
    'startovyj_nabor_descr' => 'Markörer från startkollektionen är en blandning av standardformer och storlekar med ett ljust, ovanligt utseende. Detta är ett utmärkt val för de som föredrar de vanliga formerna, men vill tillföra mångfald, originalitet och ljusstyrka till vardagen. Kollektionen har en handmarkör och en bekant pil i en mängd olika variationer - från Google Chromes logotyp till uttryckssymboler, du kan till och med möta en sedan länge glömd drake med kaktusar och nostalgi här. Vi bevisar att en standardmarkör också kan vara intressant och attraktiv. Olika färger, former, texturer och intressant design hjälper dig att välja markören efter din smak eller ändra den varje dag beroende på humör eller utförda uppgifter. Att ändra webbläsarmarkörer är väldigt enkelt - bara installera tillägget och ladda ner kollektionen till din enhet. Roliga, intressanta markörer kommer inte bara att färga arbetsdagarna utan också, till exempel, hjälpa till att göra alla presentationer mer intressanta, och med hjälp av särskilt ljusa markörer dra uppmärksamheten till enskilda delar av rapporten.',
    'fortnite_descr' => 'Fortnite har erövrat miljontals människor runt om i världen. Spännande strider, strategi och taktik, äventyr - det har absorberat absolut allt som spelare gillar så mycket. Vi kunde inte hålla oss borta och utvecklade en uppsättning markörer i spelets stil som kommer att tilltala inte bara ivriga spelare, utan även de som först hörde talas om Fortnite. Fortnite-markörikonen är en bild av en hjälte eller hans vapen, utarbetad in i minsta detalj. Här kan du hitta bilder av rävar och fiskar, masker av inferno och svarta riddare, ställa in dig själv en pil eller en lie med taggar som en pil. Vi är säkra på att ingen kommer att förbli oberörd! Att vara läskig eller mystisk, originell eller humoristisk - det är upp till dig. Välj din stil och följ den eller ställ in anpassade markörer i inställningarna och ändra din roll varje dag. Nu blir det mycket mer intressant och trevligt att utföra även tråkigt och monotont arbete - tiden kommer att flyga snabbt i sällskap med levande bilder och favoritkaraktärer. Eller kanske du kommer att ordna tävlingar med kollegor, vilken hjälte som kommer att vara starkare? Valet är ditt!',
    'dota_2_descr' => 'DotA2 är inte bara ett enkelt spel, det är en riktig parallell värld. I virtuell verklighet i DotA2 kan du göra allt - leva, slåss, utvecklas, resa, få vänner. I allmänhet, allt är som i livet, bara ibland mer intressant. Dota 2-markörer är en fortsättning på en strategi som gör att du kan få levande känslor och uttrycka dig i den verkliga världen. En ny uppsättning markörer inkluderar de mest slående karaktärerna i spelet, samt originalföremål som inte kan förväxlas med något annat. Välj en markör som kommer närmare dig - och ge dig ut på ett äventyr utan att lämna din arbetsplats. Hur tråkigt det är ibland att vara på jobbet eller att utföra pedagogiska uppgifter, men med spelmarkörer kommer detta problem inte längre att konfrontera dig. Lite fantasi, en ljus markör - och voila, alla affärer kommer att bli ett ovanligt äventyr, att klara av som inte kommer att vara svårt och intressant. Du behöver inte begränsa dig själv. Gillar du Dota? Var då noga med att ladda ner vår samling, välj en eller flera slumpmässiga markörer på en gång - och varje ny dag kommer att bli ljusare, mer intressant och mättad.',
    'minecraft_descr' => 'Muspekare i form av vanliga pilar och fingrar har länge blivit tråkiga för alla. Om du är ett fan av det ovanliga och originella, så är det dags att byta muspekaren och ge den en mer intressant design. Vi har utvecklat en samling pekare i stil med det världsberömda Minecraft-spelet, där du kan hitta de mest slående karaktärerna. Varg och räv, Alex och Creeper, diamantsvärd och fisk - du kan välja den du gillar mest eller installera en ny hjälte varje dag. Det här är riktiga pekare för spelare, och absolut alla kommer att gilla dem - trots allt, vem av oss har inte spelat Minecraft? Vi är säkra på att dessa helt enkelt inte finns. Ned med det tråkiga vardagslivet - det är dags att dyka in i äventyr, vilket kan göras även utan att lämna ditt hem eller din kontorsstol. Det kommer att bli mer intressant att förbereda en rapport och minska saldot med en pistol - vilken uppgift som helst kommer att bli trevligare och kommer inte att låta dig bli uttråkad på plats. Ladda ner den nya Minecraft-pekarsamlingen - ställ in dem och även den gråaste och mest tråkiga dagen kommer ditt humör alltid att vara som bäst. Och kollegor kommer att avundas dina resultat - det är helt enkelt omöjligt att inte göra ditt jobb med hjälp av de modiga hjältarna i Minecraft.',
    'christmas' => 'Jul',
    'stranger_things_descr' => 'Lite mer än sex månader har gått sedan finalen av den tredje säsongen. Joyce, Will, Eleven och Jonathan har flyttat till Kalifornien där tjejen blir mobbad i skolan. Resten börjar slåss mot ett nytt monster från en parallell värld som har dykt upp i Hawkins. Han fick namnet Vecna ​​efter karaktären från brädspelet Dungeons & Dragons. Det påverkar tonåringar psykologiskt, klättrar sedan mentalt in i huvudet och dödar. Parallellt lär sig Joyce och Murray att Jim Gopper lever och ger sig efter honom till ett sovjetiskt fängelse i Kamtjatka. Och Eleven måste återvända och öka sina krafter, men också lära sig sin viktiga roll i att skapa samma monster i Gokins.

Författarna ändrade inte den plot-taktik som de gillade de senaste säsongerna. I den fjärde säsongen delade de in den stora gruppen av huvudkaraktärer i grupper, kom på svåra uppgifter åt dem och byggde i slutändan ihop sina berättelser i ett fantastiskt slut. Vi erbjuder dig att i detalj förstå alla dessa äventyr med hjälp av Stranger Things-markörsamlingen.',
    'miraculous_descr' => 'Miraculous: Berättelser om Ladybug och Cat Noir, mer känd som Miraculous Ladybug och Cat Noir, är äventyr om superhjältar från tecknat om två klasskamrater som, under masker, spelar rollen som försvarare av Paris från en skurk som i varje avsnitt kommer på ett nytt sätt att skada staden. Miraculous är gjord i Frankrike med CGI och animation. Miraculous är inte bara en animerad serie, utan också en samling serietidningar som släppts runt om i världen. Serien är mycket älskad av den unga publiken.

Handlingen utspelar sig i Paris, där Marinette och Adrian är gymnasieelever i en modern skola. De fick rollen att bli den utvalda i kampen mot ondska och rädda sin hemstad. Deras mål är att skydda människor från Akumas. Dessa små varelser i form av fjärilar kan bebo en person och förvandla honom till en skurk.

Marinette kan förvandlas till en nyckelpiga, och Adrian - till en Cat Noir, men överraskande nog, arbetar de tillsammans, de känner inte igen varandra under superhjältarnas masker.

Hjälp Cat Noir och Ladybug att rädda Paris med våra markörer med dina favoritkaraktärer. Vilken karaktär ska du välja för markören? Kommer det att vara en Miraculous Ladybug-markör, eller kanske Tikki\'s bedårande lilla Ladybug eller Cat Noir-markör? Eller kanske Queen Bee med Rena Rouge-markörer? Valet är ditt!',
];
