<?php

return [
    'title' => 'Cursor Style - Integritetspolicy',
    'descr' => 'I "Cursor Style", tillgängligt på cursor.style eller genom Chrome-tillägget, är en av våra högsta prioriteringar integriteten för våra besökare. Det är i det här avsnittet som vi kommer att prata om alla aspekter av att arbeta med tillägget.',
    'text' => '<h2> Sekretesspolicy </h2>
                <p> I Cursor Style, tillgängligt på <a href="https://cursor.style"> cursor.style </a> eller via Chrome-tillägget, är en av våra högsta prioriteringar våra besökares integritet. Detta dokument om sekretesspolicy innehåller de typer av information som samlas in och registreras av webbplatsen cursor.style och hur vi använder den. Om du har ytterligare frågor eller behöver mer information om vår sekretesspolicy, tveka inte att kontakta oss. </p>
                <p> Tillägget "Cursor Style" och webbplatsen följer standardproceduren för användning av loggfiler. Dessa filer registrerar besökare när de besöker webbplatser eller använder vårt tillägg. Alla hostingföretag gör detta och är en del av hostingtjänstanalysen. Information som samlas in via loggfiler inkluderar Internet Protocol (IP)-adresser, webbläsartyp, Internetleverantör (ISP), datum- och tidsstämpel, övergångs-/utgångssidor och eventuellt antalet klick. De är inte associerade med någon personligt identifierbar information. Syftet med denna information är att analysera trender, administrera webbplatsen och utöka den, spåra användarnas rörelser på webbplatsen och utöka den samt samla in demografisk information. </p>
                <p> Som alla andra webbplatser använder cursor.style cookies. Dessa cookies används för att lagra information, inklusive besökarens preferenser och de sidor på webbplatsen som besökaren besökte eller besökte. Denna information används för att optimera användarupplevelsen genom att anpassa innehållet på vår webbsida baserat på typen av besökarens webbläsare och/eller annan information. Vi använder också tredjepartsannonser på cursor.style för att stödja projektet och stödja vår webbplats. Vissa av dessa annonsörer kan använda teknologier som cookies och webbfyrar när de annonserar på vår webbplats, vilket också kommer att skicka information till dessa annonsörer (till exempel Google via Google AdSense-programmet), inklusive din IP-adress, din Internetleverantör, den webbläsare som du använde för att besöka vår webbplats och i vissa fall, om du har Flash installerat. Detta används vanligtvis för geotargetingändamål (till exempel att visa annonser för försäljning av varor i din stad) eller för att visa vissa annonser baserat på vissa webbplatser som besöks (till exempel att visa köpmeddelanden till dem som ofta besöker köpwebbplatser). </p>
                <p> Du kan inaktivera eller selektivt inaktivera våra eller tredjeparts cookies i webbläsarinställningarna eller genom att hantera inställningar i program som Kaspersky etc. Detta kan dock påverka hur du interagerar med vår webbplats, såväl som med andra webbplatser. Detta kan inkludera oförmågan att logga in på tjänster eller program, till exempel att logga in på forum eller konton. </p>
<p> Google är en av tredjepartsleverantörerna på vår webbplats. Den använder också cookies, kända som DART-cookies, för att visa annonser för besökare på vår webbplats baserat på deras besök på cursor.style och andra webbplatser på Internet. Besökare kan dock välja bort användningen av DART-cookies genom att besöka Googles sekretesspolicy för annonsering och innehållsnätverk på <a href="https://policies.google.com/technologies/ads"> följande adress </a>. Vissa av annonsörerna på vår webbplats kan använda cookies och webbfyrar. Var och en av våra annonspartners har sin egen sekretesspolicy för sina policyer angående användardata. Du kan läsa mer om deras sekretesspolicyer <a href="https://policies.google.com/technologies/ads"> här </a>. </p>
                <p> Vår webbplats använder Google Analytics, en webbanalystjänst från Google, Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043 USA, www.google.com (”Google Analytics” eller ”Google”). Google Analytics använder cookies som lagras på din dator för att underlätta analysen av din användning av webbplatsen. Information som genereras av dessa cookies, såsom tid, plats och frekvens för dina besök på vår webbplats, inklusive din IP-adress, överförs till en Google-plats i USA och lagras där. Google kan också överföra denna information till tredje parter om det krävs enligt lag eller om tredje parter behandlar dessa data för Googles räkning. Google anger att de aldrig kommer att associera din IP-adress med andra Google-data. Du kan förhindra inställningen av cookies genom att ändra dina webbläsarprograminställningar i enlighet därmed, vilket anges i denna sekretesspolicy. Du bör dock vara medveten om att du på detta sätt inte kommer att kunna använda alla funktioner på vår webbplats fullt ut. </p>
                <p> Google Analytics använder också elektroniska bilder som kallas webbfyrar (ibland kallade GIF-filer med en pixel) och används med cookies för att sammanställa aggregerad statistik för att analysera användningen av vår webbplats.
Du kan hitta mer information om hur du installerar webbläsartillägget som du länkar till ovan <a href="https://tools.google.com/dlpage/gaoptout?hl=en"> länk </a>.
Denna webbplats använder Google Tag Manager. Denna tjänst låter dig hantera webbplatstaggar via gränssnittet. Google Tag Manager implementerar endast taggar. Detta innebär att cookies inte ställs in och inga personuppgifter registreras. Google Tag Manager lanserar andra taggar, som i sin tur kan registrera data. Google Tag Manager har dock inte tillgång till dessa data. Om taggar har inaktiverats på domän- eller cookienivå sparas de för alla spårningstaggar, om de implementeras med Google Tag Manager. Du kan lära dig mer om Google Tag Manager genom att besöka <a href="http://www.google.com/tagmanager/use-policy.html"> länk </a>. </p>
<p> Du kan bekanta dig med den här listan för att hitta sekretesspolicyn för var och en av "Cursor Style" annonspartners. Tredjepartsannonservers eller annonsnätverk använder teknologier som cookies, JavaScript eller webbfyrar, som används i deras respektive annonser och länkar, som visas i "Cursor Style" och skickas direkt till användarens webbläsare. De får automatiskt din IP-adress när detta händer. Dessa teknologier används för att mäta effektiviteten av deras annonskampanjer och/eller för att anpassa annonsinnehållet som du ser på de webbplatser du besöker. Observera att "Cursor Style" inte har tillgång till eller kontroll över dessa cookies som används av tredjepartsannonsörer. Cursor Styles sekretesspolicy gäller inte för andra annonsörer eller webbplatser. Därför rekommenderar vi att du granskar de relevanta sekretesspolicyerna för dessa tredjepartsannonservrar för mer information. Det kan inkludera deras metoder och instruktioner om hur du väljer bort vissa alternativ. Du kan hitta länkar till dessa tredjeparts sekretesspolicyer ovan eller på webbplatserna för dessa tredjepartstjänster. </p>
                <p> Du kan inaktivera cookies i dina webbläsarinställningar. För att lära dig mer om cookiehantering i specifika webbläsare kan du hitta det på deras respektive webbläsarwebbplatser. En annan del av vår prioritet är att lägga till barnskydd när du använder Internet. Vi uppmuntrar föräldrar och vårdnadshavare att observera, delta och/eller övervaka och styra sina aktiviteter på Internet. "Cursor Style" samlar inte medvetet in personlig information från barn under 13 år. Om du tror att ditt barn har tillhandahållit sådan information på vår webbplats, rekommenderar vi starkt att du kontaktar oss omedelbart så gör vi vårt bästa för att snabbt ta bort sådan information från våra register. Denna sekretesspolicy gäller endast för våra onlineaktiviteter och gäller för besökare på vår webbplats i förhållande till den information som de delade och/eller samlade in i "Cursor Style". Denna policy gäller inte för information som samlas in offline eller via andra kanaler än denna webbplats. </p>
                <p> Du kan läsa mer om användningen av cookies i vår tjänst i vår <a href="/cookie-policy"> Cookie Policy </a>. </p> ',
];
