on:
  push:
    branches:
      - main
  
jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.WONCHOE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.WONCHOE_HOSTNAME }} > ~/.ssh/known_hosts
    - name: connect and pull
      run: ssh ${{ secrets.WONCHOE_USERNAME }}@${{ secrets.WONCHOE_HOSTNAME }} "cd /var/www/cursor.style && git checkout main && git pull && exit"
    - name: cleanup
      run: rm -rf ~/.ssh
