on:
  push:
    branches:
      - main
  
jobs:
  run_pull:
    name: Run Pull Command
    runs-on: ubuntu-latest
    
    steps:
    - name: Install SSH Key
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.WONCHOE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.WONCHOE_HOSTNAME }} >> ~/.ssh/known_hosts

    - name: Connect and Pull
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.WONCHOE_USERNAME }}@${{ secrets.WONCHOE_HOSTNAME }} \
        "cd /var/www/cursor.style && git checkout main && git pull"

    - name: Cleanup
      run: rm -rf ~/.ssh
