name: CI Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: cursorstyle-runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a script
      run: |
        git config --global --add safe.directory /var/www/cursor.style
        cd /var/www/cursor.style
        git pull

    # Add more steps as needed
