name: 🔄 Synchronize with server
on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: cursorstyle-runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a script
      run: |
        cd /var/www/cursor.style
        git pull cursorstyle main
    - name: Clean up Docker
      run: docker system prune -af --volumes
