<?php

return [
    'title' => 'Cursor Style - Cookiebeleid',
    'descr' => 'Een cookiebeleid wanneer u onze website cursor.style of de "Cursor Style" extensie bezoekt. Enkele regels die u in overweging moet nemen bij het gebruik van ons product.',
    'text' => '<h2> Cookiebeleid </h2>
<p> Wanneer u onze website cursor.style of de "Cursor Style"-extensie in uw browserpaneel bezoekt, of wanneer u interactie heeft met onze vertegenwoordigers (de "Service"), gebruiken we (en staan we derden toe om te gebruiken) webbakens, cookies, pixeltags, scripts, tags, API\'s en andere technologieën ("Trackingtechnologieën"). Dit wordt uitgelegd in dit beleid ("Cookiebeleid"), dat deel uitmaakt van ons <a href="/privacy"> Privacybeleid </a>. </p>
<p> Trackingtechnologieën stellen ons in staat om automatisch informatie over u en uw gedrag op internet te verzamelen om uw navigatie op onze Service te verbeteren, de prestaties van onze Service te verbeteren en uw ervaring in onze Service te vergemakkelijken. We gebruiken deze informatie ook om statistieken te verzamelen over het gebruik van onze Service, analyses uit te voeren, inhoud te leveren die bij uw interesses past en diensten te beheren voor onze gebruikers, klanten en partners. We staan ​​derden ook toe om informatie over u te verzamelen met behulp van trackingtechnologieën. </p>
<p> Wat zijn cookies? Cookies zijn kleine tekstbestanden (bestaande uit alleen letters en cijfers) die de webserver op uw computer of mobiele apparaat plaatst wanneer u een webpagina bezoekt. Het gebruik van een cookie kan helpen om onze Services gebruiksvriendelijker te maken, bijvoorbeeld door uw taalvoorkeuren en instellingen te onthouden. U kunt meer informatie over cookies vinden op <a href="http://www.allaboutcookies.org"> allaboutcookies.org </a>. </p>
<p> Cookies worden veel gebruikt voor websiteprestaties. Door cookies te gebruiken, kunt u efficiënt tussen pagina\'s navigeren. Cookies onthouden uw voorkeuren en maken de interactie tussen u en de Services soepeler en efficiënter. </p>
<p> We gebruiken trackingtechnologieën wanneer u onze Services bezoekt of gebruikt (meestal wanneer u onze websites bezoekt) - ze worden “First-Party Trackingtechnologieën” genoemd. Daarnaast worden trackingtechnologieën opgeslagen door andere organisaties van derden (bijvoorbeeld onze leveranciers van analyseservices, zakenpartners en adverteerders) die inhoud op onze Services plaatsen - ze worden “Third-party trackingtechnologieën” genoemd. Beide soorten trackingtechnologieën kunnen worden opgeslagen voor de duur van uw bezoek aan onze Services of voor herhaalde bezoeken. </p>
<h3> Welke soorten trackingtechnologieën gebruiken we? Er zijn vijf hoofdtypen trackingtechnologieën: </h3>
<ul>
<li> <b> Strikt noodzakelijke trackingtechnologieën </b> <br> <p> Deze trackingtechnologieën zijn noodzakelijk zodat u kunt inloggen, navigeren en de functies van onze Services kunt gebruiken of de service kunt leveren die u aanvraagt ​​(bijvoorbeeld uw gebruikersnaam). We hebben uw toestemming niet nodig om deze trackingtechnologieën te gebruiken. Deze trackingtechnologieën kunnen worden gebruikt voor beveiligings- en integriteitsdoeleinden, bijvoorbeeld om schendingen van ons beleid te identificeren, evenals voor ondersteunings- of beveiligingsfuncties. </p> </li>
<li> <b> Functionaliteit Trackingtechnologieën </b> <br> <p>
Deze trackingtechnologieën stellen onze services in staat om uw keuzes (zoals taal) te onthouden en geavanceerde en gepersonaliseerde functies te bieden. Deze trackingtechnologieën worden bijvoorbeeld gebruikt voor authenticatie (om te onthouden wanneer u bent ingelogd) en ondersteunen andere functies van onze Services. </p> </li>
<li> <b> Prestatie Trackingtechnologieën </b> <br> <p>
Deze trackingtechnologieën verzamelen informatie over uw online activiteit (bijvoorbeeld de duur van uw bezoek aan onze Services), inclusief gedragsgegevens en indicatoren van contentbetrokkenheid. Deze trackingtechnologieën worden gebruikt voor analyses, onderzoek en statistieken (gebaseerd op geaggregeerde informatie). </p> </li>
<li> <b> Marketing- of advertentie-trackingtechnologieën </b> <br> <p>
Deze trackingtechnologieën worden gebruikt om u speciale aanbiedingen en advertenties aan te bieden op basis van uw interesses, evenals om e-mailmarketingcampagnes uit te voeren. Ze kunnen ook worden gebruikt om het aantal keren dat een advertentie wordt bekeken te beperken, evenals om de effectiviteit van een reclamecampagne te meten. Ze worden meestal gehost door onze adverteerders (bijvoorbeeld advertentienetwerken) en geven hen een idee van ​​de mensen die hun advertenties zien en ermee interageren, hun websites bezoeken of hun app gebruiken. </p> </li>
<li> <b> Social Media Trackingtechnologieën </b> <br> <p>
Onze website bevat functies van sociale netwerken, zoals de knoppen Leuk vinden of Delen op Facebook en Vkontakte, of inlogservices van derden. Deze functies worden ofwel geplaatst door een derde partij of rechtstreeks op onze Services. Uw interactie met deze functies wordt beheerst door de privacyverklaring van het bedrijf dat deze functies levert. </p> </li>
</ul>
<h3> Dit zijn de cookies die u in onze Services kunt vinden: </h3>
<ul>
<li> <b> Cookies Analytics </b> <br> <p> Deze trackingtechnologieën worden gebruikt om informatie te verzamelen over hoe u interactie hebt met inhoud in onze Services, toeschrijvingsdoeleinden (bijvoorbeeld verwijzings-URL\'s), enz. We gebruiken deze informatie om rapporten samen te stellen, de omzet te berekenen die ons verschuldigd is, en ons te helpen de Services te verbeteren en gepersonaliseerde producten en inhoud aan te bieden. </p> </li>
<li> <b> Google Analytics </b> <br> <p> Deze cookie wordt gebruikt om informatie te verzamelen over hoe bezoekers ons platform gebruiken. We gebruiken deze informatie om rapporten samen te stellen en het platform te verbeteren. Cookies verzamelen informatie in anonieme vorm, inclusief het aantal platformbezoekers, waar bezoekers naar het platform zijn gekomen en de pagina\'s die ze hebben bezocht. <br> <a href = "https://policies.google.com/privacy?hl=en" > Privacybeleid </a> </p> </li>
<li> <b> Google Tag Manager </b> <br> <p> Deze cookie wordt geassocieerd met de Google Tag Manager, die we gebruiken om scripts te laden op de pagina\'s van onze website. <br> <a href = "https: / /policies.google.com/privacy?hl=en">Privacybeleid </a> </p> </li>
</ul>
<p> Houd er rekening mee dat we geen automatische browserwaarschuwingen met betrekking tot trackingtechnologieën herkennen of beantwoorden, inclusief Do Not Track-verzoeken. Er zijn echter verschillende manieren om uw cookie-instellingen te beheren en te beheren. Onthoud dat bij het verwijderen of blokkeren van cookies, sommige functies van de Services mogelijk niet correct of niet zo efficiënt werken. </p>
<p> De meeste webbrowsers bieden u wat algemene informatie over cookies, stellen u in staat om te zien welke cookies op uw apparaat zijn opgeslagen, stellen u in staat om ze allemaal of individueel te verwijderen en stellen u ook in staat om het gebruik van cookies voor alle websites of individueel geselecteerde sites te blokkeren of toe te staan. U kunt cookies van derden ook afzonderlijk uitschakelen. Houd er rekening mee dat de instellingen die door de browser of het apparaat worden aangeboden, vaak alleen van toepassing zijn op die specifieke browser of dat specifieke apparaat. </p>
<h3> Cookie-informatie is meestal te vinden in de Help-sectie van een webbrowser. </h3>
<p> Dit zijn links naar enkele veelgebruikte webbrowsers: </p>
<p><a href="https://support.google.com/chrome/answer/95647?hl=en"> Chrome </a> <br>
<a href="https://support.microsoft.com/en-us/help/17442/windows-internet-explorer-delete-manage-cookies"> Internet Explorer en Microsoft Edge </a> <br>
<a href="https://support.mozilla.org/en/kb/kuki-informaciya-kotoruyu-veb-sajty-hranyat-na-vas"> Mozilla Firefox </a> <br>
<a href="https://support.apple.com/ru-ru/guide/safari/sfri11471/mac"> Safari </a> </p>
<p> U kunt bepaalde cookies van derden uitschakelen voor targeting / advertenties door op de volgende link te klikken: <a href="http://optout.networkadvertising.org/?c=1"> Afmelden voor op interesses gebaseerde advertenties </a>. </p>
				',
];
